### PR TITLE
Lock some unlocked project.lock.json files

### PR DESCRIPTION
**Pull request by ellismg**
Noticed this while playing around with some other stuff.  I just edited the files by hand, didn't actually do another restore pass.

### CODE REVIEW

**Comment by stephentoub** [comment]
LGTM

**Comment by stephentoub** [comment]
(Though it seems like these files are going away imminently with https://github.com/dotnet/corefx/pull/4894)

**Comment by ellismg** [comment]
Oh, great.  Didn't realize that was so close to landing.  I'll just wait.

**Comment by dagood** [comment]
I don't mind merging, especially small things like this. There might be more changes to buildtools before merging in #4894 (pending discussion) so going ahead with this is fine with me.

**Pull request merged**
