### PR TITLE
[2.0] Fix -Wzero-as-null-pointer-constant errors on macOS

### PR DESCRIPTION
**Pull request by qmfrederik**
`release/2.0.0` currently fails to build on macOS 10.13.4 because Apple LLVM version 9.1.0 (clang-902.0.39.1) added a  `-Wzero-as-null-pointer-constant` check.

Not sure what the policy is for this kind of fixes for release branches, so feel free to close if not appropriate.

### CODE REVIEW

**Comment by qmfrederik** [comment]
... or would a better option be to add -Wno-zero-as-null-pointer-constant, as done in #27178?

**Comment by stephentoub** [comment]
> Not sure what the policy is for this kind of fixes for release branches, so feel free to close if not appropriate.

cc: @karelz

**Comment by karelz** [comment]
@leecow what is our policy to get such changes into 2.0 servicing branch? Is it worth it?

**Comment by tarekgh** [comment]
just to mention the change is relatively safe. I would recommend taking this fix if it is possible. 

CC @Petermarcu @weshaggard

**Comment by Petermarcu** [comment]
Is this already fixed in 2.1?

**Comment by tarekgh** [comment]
@qmfrederik are you fixing this in the master branch too? I am seeing we have the issue there too, here is example 

https://github.com/dotnet/corefx/blob/master/src/Native/Unix/System.Native/pal_random.cpp#L84

**Comment by tarekgh** [comment]
@Petermarcu 

> Is this already fixed in 2.1?

I don't think it is fixed there, I am seeing some places have the same issue:

https://github.com/dotnet/corefx/blob/release/2.1/src/Native/Unix/System.Native/pal_random.cpp#L83

**Comment by Petermarcu** [comment]
In general, as an open source project we should aim to make sure our product can build on all the platforms it is supported on. I wouldn't do that at all cost but for low risk things, I think we should take them.

**Comment by leecow** [comment]
Agreed with Peter and the need to also look at this in master.

**Comment by tarekgh** [comment]
@leecow what is needed to be done if we agree we'll take this fix? I mean, is there any process to proceed? or we just merge it?

**Comment by tarekgh** [comment]
test OSX x64 Debug Build 
test Windows x64 Debug Build
test Windows x86 Release Build

**Comment by tarekgh** [comment]
System.Data.SqlClient.Tests failure is already tracked by the issue https://github.com/dotnet/corefx/issues/28950
System.Security.Cryptography failure is tracked with https://github.com/dotnet/corefx/issues/29637

**Comment by tarekgh** [comment]
I am just trying the same build environment and I am seeing the change here is fixing the native build but I am seeing some other build error which we may need to fix too.

```
/Users/tarek/oss/corefx/Tools/depProj.targets(83,5): error : Error no assets were resolved from NuGet packages. [/Users/tarek/oss/corefx/external/ilasm/ilasm.depproj]
```

**Comment by tarekgh** [comment]
some update: 

2.1 and master are building fine on Mac OS 10.13.4 with LLVM version 9.1.0 (clang-902.0.39.1). so, we don't have the same issue with these branches

**Comment by tarekgh** [comment]
@joperezr could you please push the package change fix to this PR?

**Comment by joperezr** [comment]
done

**Comment by weshaggard** [comment]
>@weshaggard could you please review the commit submitted by @joperezr? thanks

That looks good to me.

**Comment by bartonjs** [comment]
@dotnet-bot Test this please (branch was in a bad state when the PR was opened)

**Comment by tarekgh** [comment]
I am closing this PR as we decided not take the change in the current time and also we have the following commits which can be used as a workaround as needed. 

https://github.com/dotnet/corefx/pull/29576/commits/c711266a748b753201fd7feb1f878a930eb579f2
https://github.com/dotnet/corefx/pull/29576/commits/7243c5f17294f0ee8b118d0cbd338526f4ae9da9

Also, I have confirmed we don't have any problem building 2.1 and master too. 

@qmfrederik thanks for trying fixing this issue.

**Pull request closed without merging**
