### PR TITLE
Mention global.json in dogfooding instructions

### PR DESCRIPTION
**Pull request by svick**

### CODE REVIEW

**Comment by mellinoe** [comment]
@livarcocc Is this accurate? I'm not familiar with this part of the CLI.

**Comment by danmosemsft** [comment]
@livarcocc ?

**Comment by danmosemsft** [comment]
@livarcocc ?

**Comment by karelz** [comment]
@mellinoe can you please catch @livarcocc on IM / over email / in office? It doesn't seem like we are getting any traction just on GitHub :(

**Comment by mellinoe** [comment]
The global.json file mentioned here is no longer necessary. The CLI should automatically pick up the latest pre-release version. See discussion [here](https://github.com/dotnet/core-setup/issues/1664) and PR [here](https://github.com/dotnet/core-setup/pull/2055) for more information.

**Comment by mellinoe** [comment]
@svick Sorry about dropping the ball on this PR. This was correct when you submitted it 😞 .

**Pull request closed without merging**
