### PR TITLE
Update projects to netcoreapp2.0 and netstandard2.0

### LINKED ISSUE #14501: Update projects to netcoreapp2.0 / netstandard2.0 / net461
We need to update our projects to build against these new monikers and package as the same.  

Since netstandard2.0 is supported by net461 most desktop builds should be targeting this version rather than net463.

### PR DESCRIPTION
**Pull request by alexperovich**
Fixes #14501

### CODE REVIEW

**Comment by mellinoe** [comment]
Huh, none of your stuff is failing with the `-notrait` issue... That is bizarre to me, but perhaps that means that #14943 will fix the rest of this stuff.

**Comment by mellinoe** [comment]
@dotnet-bot Test Innerloop CentOS7.1 Release Build and Test
Test Innerloop Ubuntu14.04 Release Build and Test
Test Innerloop OSX Release Build and Test

The useServerGC problem should be fixed now. Restarting those legs.

**Comment by jkotas** [comment]
Number of the uses of netstandard1.7 should be renamed to netcodeapp2.0 instead. For example, the `ArrayTests.netstandard1.7.cs → ArrayTests.netstandard.cs` rename should be to `ArrayTest.netcoreapp2.0.cs` instead.

**Comment by weshaggard** [comment]
Please wait to merge this until @joperezr's merge from master goes in https://github.com/dotnet/corefx/pull/14949

**Comment by alexperovich** [comment]
@jkotas that rename was automated. If you know which ones need to be changed to netcoreapp I can manually change them.

**Comment by jkotas** [comment]
You should look for similar patterns as the example that I gave you. I can glance at the delta one more time once you fix those.

**Pull request merged**
