### PR TITLE
Add System.Xml.ReaderWriter tests

### PR DESCRIPTION
**Pull request by krwq**
Reviewing guidelines:
- .cs files in the initial commit are a simple port, please ignore them (please DO review .csproj files packages.config and other changes except .cs files)

### CODE REVIEW

**Comment by Maxwe11** [comment]
local build

	  Discovering: System.Xml.RW.XmlWriter.Tests
	  Discovered:  System.Xml.RW.XmlWriter.Tests
	  Starting:    System.Xml.RW.XmlWriter.Tests
		 XmlWriterTests.WriteWithEncoding [FAIL]
			Assert.Equal() Failure
									    (pos 17)
			Expected: <orderID>1-456-ab&#x661;</orderID><orderID>2-36-00a&#x1000תתת
			Actual:   <orderID>1-456-ab\n</orderID><orderID>2-36-00a&#x10000;&#x1תתת
									    (pos 17)
			Stack Trace:
			   d:\corefx-krwq\src\System.Xml.ReaderWriter\tests\XmlWriter\WriteWithEncoding.cs(36,0): at XmlWriterTests.WriteWithEncoding()
	  Finished:    System.Xml.RW.XmlWriter.Tests

**Comment by krwq** [comment]
Thanks @Maxwe11, I will disable the test. I saw this issue sometimes appearing before on remote machines but couldn't ever repro locally. Could you tell me what OS and locale are you using?
I have a feeling that it might be an encoding issue or a fallback encoder bug.
@tarekgh - did you see any similar issues before perhaps? What other information can be useful to repro it?

**Comment by Maxwe11** [comment]
OS: Win 8.1 64-bit
Culture: uk-UA

**Comment by krwq** [comment]
https://github.com/dotnet/corefx/issues/1263

**Comment by mellinoe** [comment]
LGTM

**Comment by krwq** [comment]
Thanks @Maxwe11 & @mellinoe

**Pull request merged**
