### PR TITLE
Fixing expression interpreter for Increment and Decrement nodes

### PR DESCRIPTION
**Pull request by bartdesmet**
This addresses issue #3758.

### CODE REVIEW

**Comment by bartdesmet** [comment]
cc @VSadov

**Comment by bartdesmet** [comment]
Rebased, should be good to go after review.

**Comment by VSadov** [comment]
Test this please

**Comment by VSadov** [comment]
Test this please

**Comment by jasonwilliams200OK** [comment]
Test this please ([linux build](http://dotnet-ci.cloudapp.net/job/dotnet_corefx_linux_debug_tst_prtest/3258/console) was failing with [this error](https://gist.github.com/jasonwilliams200OK/e3e3c920055db7df9b40))

**Comment by bartdesmet** [comment]
@dotnet-bot test this please

**Comment by VSadov** [comment]
it seems the linux CI is busted ATM.

**Comment by stephentoub** [comment]
> it seems the linux CI is busted ATM.

Yes, I think we picked up a recent change from coreclr that broke some of the corefx tests.

**Comment by stephentoub** [comment]
@dotnet-bot test this please (after Jenkins changes related to setting culture-related env vars)

**Pull request merged**
