### PR TITLE
Improve tracing in CurlHandler

### PR DESCRIPTION
**Pull request by stephentoub**
While debugging some HttpClient issues, I needed more tracing in CurlHandler.  It's useful to check this in to help with future investigations.

This is the same changes as from:
https://github.com/dotnet/corefx/pull/8894
https://github.com/dotnet/corefx/pull/8884
as I'd like to get these tracing changes merged without first resolving what to do with those changes.

cc: @bartonjs, @ericeil (you guys already reviewed these changes as part of that other commit)

### CODE REVIEW

**Comment by ericeil** [comment]
Agreed - these should go in regardless of what happens with the rest of the change.

**Comment by bartonjs** [comment]
LGTM, despite the not-exactly-for-logging changes :smirk:.

**Comment by stephentoub** [comment]
> despite the not-exactly-for-logging changes 

Which aren't for better tracing?

**Comment by bartonjs** [comment]
> Which aren't for better tracing?

I didn't see any real tracing effect from this aspect:

```diff
 -            /// <summary>The HttpContent to read from, potentially repeatedly until a response is received.</summary>
-            private readonly HttpContent _content;
+            /// <summary>The associated EasyRequest.</summary>
+            private readonly EasyRequest _easy;

              /// <summary>Initializes the stream.</summary>
-            /// <param name="content">The content the stream should read from.</param>
-            internal HttpContentAsyncStream(HttpContent content)
+            /// <param name="easy">The associated easy request containing the content to transfer to this stream.</param>
+            internal HttpContentAsyncStream(EasyRequest easy)
             {

                  // Start the copy and store the task to represent it.
-                _copyTask = _content.CopyToAsync(this, _transportContext);
+                _copyTask = _easy._requestMessage.Content.CopyToAsync(this, _transportContext);
```

or

```diff
-            internal ulong TransferDataToStream(IntPtr pointer, long length)
+            internal ulong TransferDataToResponseStream(IntPtr pointer, long length)
```

(Side note, this is the first time I've wanted to copy the +/- prefixes from the review pane... usually: annoyance, today: feature)

**Comment by stephentoub** [comment]
> I didn't see any real tracing effect from this aspect

Without the EasyRequest being available to the code in HttpContentAsyncStream, tracing done inside of the stream would not be correlated with that particular request, so if you look at the resulting trace (where each event includes the ID of the multi agent and the ID of the easy request), all of the IDs before this change would be 0, making it extremely difficult to understand flow if multiple requests were happening.

And the TransferDataToStream name change to TransferDataToResponseStream affects tracing because the tracing using [CallerNameAttribute] to pick up the calling method name and include it in the trace.  When it was TransferDataToStream, it wasn't clear which stream that was referring to.

**Comment by bartonjs** [comment]
Fair enough. I stand corrected, withdraw my smirk, and am seeking out humble pie.

LGTM :).

**Comment by stephentoub** [comment]
:)

**Pull request merged**
