### PR TITLE
Updating xunit.performance.* rev num

### PR DESCRIPTION
**Pull request by dsgouda**
Updating the xunit performance runner version so we pick up the changes that escape the strings during csv generation of results
@brianrob @davmason

### CODE REVIEW

**Comment by davmason** [comment]
LGTM

**Comment by dsgouda** [comment]
@dotnet-bot Test this please

**Comment by dsgouda** [comment]
@dotnet-bot Test this please

**Comment by weshaggard** [comment]
What is the "q" file in the root?

**Comment by dsgouda** [comment]
I mistakenly added that. Fixing it here https://github.com/dotnet/corefx/pull/6643

**Pull request merged**
