### PR TITLE
Remove non-functional win10 and win-nano functionality

### PR DESCRIPTION
**Pull request by mmitche**

### CODE REVIEW

**Comment by mmitche** [comment]
@dotnet-bot test ci please

**Comment by mmitche** [comment]
Am I good to merge this or is there another step since it's against 1.0.0?

**Comment by danmosemsft** [comment]
@weshaggard do you know if 1.0 is open for this?

**Comment by weshaggard** [comment]
We are good for taking 1.0 changes, so merging.

**Pull request merged**
