### PR TITLE
Fixed the System.ComponentModel.DataAnnotations.CustomValidationAttribute which does not correctly implement the RequiresValidationContext property.

### PR DESCRIPTION
**Pull request by DmitryGaravsky**
The *System.ComponentModel.DataAnnotations.CustomValidationAttribute* does not override the **RequiresValidationContext** property so this property **always returns false** due to base implementation despite of the fact that the *Method* parameter can actually point to the method that requires validation context as a second parameter. 

Related links: [issue description at MSConnect](https://connect.microsoft.com/VisualStudio/feedback/details/1820586/system-componentmodel-dataannotations-customvalidationattribute-does-not-correctly-implement-the-requiresvalidationcontext-property).

### CODE REVIEW

**Comment by stephentoub** [comment]
cc: krwq, ianhays

**Comment by stephentoub** [comment]
cc: @lajones

**Comment by lajones** [comment]
Should add tests that `RequiresValidationContext` throws if the attribute is not well-formed. Otherwise looks good.

**Comment by stephentoub** [comment]
Thanks, @lajones.  @DmitryGaravsky, can you add such a test and squash this?

**Comment by DmitryGaravsky** [comment]
@lajones Thanks.
@stephentoub, - Yes,I can. I'll add it a bit later.

**Comment by stephentoub** [comment]
@DmitryGaravsky, just checking in on this... no rush, but are you still planning to follow-up with the test and squashing?

**Comment by DmitryGaravsky** [comment]
Hi @stephentoub 
Sorry for the late reply(I fall into a troubles with my merges/branches ecause i' new in git). 
I have updated my pull request - please check it.

**Comment by stephentoub** [comment]
Thanks, @DmitryGaravsky.  The changes LGTM.

@lajones, could you review again?

And @DmitryGaravsky, could you squash this to a single commit to get rid of that merge commit?

**Comment by lajones** [comment]
Thanks @DmitryGaravsky. LGTM. :shipit:

**Comment by stephentoub** [comment]
Replaced by https://github.com/dotnet/corefx/pull/5203, which just squashes the commits.

**Pull request closed without merging**
