### PR TITLE
Remove packages from NETStandard.Library 1.6

### PR DESCRIPTION
**Pull request by ericstj**
With one exception: System.Runtime.InteropServices.RuntimeInformation.

For the rest we will no longer ship packages.

Instead the types will be supported as follows:
1. In a netstandard2.0+ project via NETStandard.Library package's
    netstandard.dll
2. In a netstandard1.x project via NETStandard.Library package and
    closure which ship from servicing branches.
3. In a framework specific project via the framework's targeting pack
    or framework package.

/cc @weshaggard @chcosta 

This does not yet include removal of packages that are being absorbed into netstandard2.0.

### CODE REVIEW

**Comment by ericstj** [comment]
@weshaggard do you think I should keep the System.IO.Compression and System.Net.Http packages since these include out-of-band implementations for desktop?  If we remove them then there is no way to get the new API/bugfixes on desktop.

**Comment by weshaggard** [comment]
Yes I think we should probably keep them. We should include placeholders for everything that isn't desktop though.

**Comment by weshaggard** [comment]
I will look more into this and your other PR tomorrow once I get my shims PR completed and compare our lists.

**Comment by ericstj** [comment]
> We should include placeholders for everything that isn't desktop though.

Either that or the actual implementations and let conflict resolution drop them like it does for Immutable, Roslyn, etc.

**Pull request merged**
