### PR TITLE
[release/2.1] Fix Sockets hang caused by concurrent Socket disposal (#29786)

### PR DESCRIPTION
**Pull request by stephentoub**
Port https://github.com/dotnet/corefx/pull/29786 to release/2.1
Fixes https://github.com/dotnet/corefx/issues/29785

### CODE REVIEW

**Comment by danmosemsft** [comment]
@davidsh the branch is open and this is approved, could you please do the honors of a CR of this port?

**Comment by danmosemsft** [comment]
@davidsh failures are known issues so if you sign off, you can merge this.

**Comment by davidsh** [comment]
>@davidsh failures are known issues so if you sign off, you can merge this.

I noticed that no Outerloop tests were run. I know that the newly added tests are Innerloop. But we usually run Outerloop tests especially when networking code is changed.  Since this is Windows-only, I'll run just the Windows Outerloop.

**Comment by davidsh** [comment]
@dotnet-bot test Outerloop Windows x64 Debug Build

**Comment by danmosemsft** [comment]
Outerloop failure is a hang in a System.Runtime test. Stack dumping failed. Unlikely to be related but let's rerun.

@dotnet-bot test Outerloop Windows x64 Debug Build please

**Comment by davidsh** [comment]
The only Sockets failures are in Nano which is expected (those multicast tests were recently disabled on Nano in master branch).

@danmosemsft Please confirm the other outerloop failures are expected (I don't think they are related to this PR).  If so, this is ok to merge.

**Comment by danmosemsft** [comment]
Windows issues are known/irrelevant.

**Comment by ahsonkhan** [comment]
FYI, we were able to get dumps for the System.Runtime test hang (it is this test: System.Runtime.ExceptionServices.Tests.HandleProcessCorruptedStateExceptionsTests.ProcessExit_Called).

https://dumpling-internal.int-dot.net/api/dumplings/archived/14a9341455838a53d7c662bef31bd4f991a03c0f

```text
 Child SP               IP Call Site
0000003cdbc7ca68 00007fffb9fb09d4 [HelperMethodFrame_1OBJ: 0000003cdbc7ca68] System.Threading.WaitHandle.WaitOneNative(System.Runtime.InteropServices.SafeHandle, UInt32, Boolean, Boolean)
0000003cdbc7cb80 00007fff8a6d6d7b System.Threading.WaitHandle.InternalWaitOne(System.Runtime.InteropServices.SafeHandle, Int64, Boolean, Boolean) [E:\A\_work\31\s\src\mscorlib\src\System\Threading\WaitHandle.cs @ 199]
0000003cdbc7cbb0 00007fff36b42197 System.Diagnostics.Process.WaitForExitCore(Int32)
0000003cdbc7cc50 00007fff36b41f91 System.Diagnostics.Process.WaitForExit(Int32)
0000003cdbc7ccb0 00007fff3702819b System.Diagnostics.Process.WaitForExit()
0000003cdbc7ccf0 00007fff37027f7d System.Runtime.ExceptionServices.Tests.HandleProcessCorruptedStateExceptionsTests.ProcessExit_Called()
0000003cdbc7cf88 00007fff9613f3b3 [DebuggerU2MCatchHandlerFrame: 0000003cdbc7cf88] 
0000003cdbc7d328 00007fff9613f3b3 [HelperMethodFrame_PROTECTOBJ: 0000003cdbc7d328] System.RuntimeMethodHandle.InvokeMethod(System.Object, System.Object[], System.Signature, Boolean, Boolean)
0000003cdbc7d470 00007fff8a64e3b1 System.Reflection.RuntimeMethodInfo.Invoke(System.Object, System.Reflection.BindingFlags, System.Reflection.Binder, System.Object[], System.Globalization.CultureInfo) [E:\A\_work\31\s\src\mscorlib\src\System\Reflection\RuntimeMethodInfo.cs @ 472]
0000003cdbc7d4e0 00007fff3699860b Xunit.Sdk.TestInvoker`1[[System.__Canon, System.Private.CoreLib]].CallTestMethod(System.Object) [C:\BuildAgent\work\cb37e9acf085d108\src\xunit.execution\Sdk\Frameworks\Runners\TestInvoker.cs @ 147]
0000003cdbc7d520 00007fff36998323 Xunit.Sdk.TestInvoker`1+c__DisplayClass46_1+<b__1>d[[System.__Canon, System.Private.CoreLib]].MoveNext() [C:\BuildAgent\work\cb37e9acf085d108\src\xunit.execution\Sdk\Frameworks\Runners\TestInvoker.cs @ 224]
0000003cdbc7d5b0 00007fff36997bdf System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[[Xunit.Sdk.TestInvoker`1+c__DisplayClass46_1+<b__1>d[[System.__Canon, System.Private.CoreLib]], xunit.execution.dotnet]](<b__1>d<System.__Canon> ByRef) [E:\A\_work\31\s\src\mscorlib\src\System\Runtime\CompilerServices\AsyncMethodBuilder.cs @ 958]
0000003cdbc7d630 00007fff36997ae7 Xunit.Sdk.TestInvoker`1+c__DisplayClass46_1[[System.__Canon, System.Private.CoreLib]].b__1()
...
```

**Pull request merged**
