### PR TITLE
Test ci

### PR DESCRIPTION
**Pull request by stephentoub**

### CODE REVIEW

**Comment by stephentoub** [comment]
@dotnet/dnceng, CI appears to be on the floor.
cc: @ViktorHofer

**Comment by davidsh** [comment]
>@dotnet/dnceng, CI appears to be on the floor.

Most of the test failures are Sockets:
image

@wfurt does this look familiar?

**Comment by stephentoub** [comment]
@davidsh, those were in one leg... several other legs failed for no apparent reason and a 503 error status code.

**Pull request closed without merging**
