### PR TITLE
Augment terminfo search with first-letter-as-hex

### LINKED ISSUE #723: System.ConsolePal.TermInfo.ReadDatabase() does not work on Mac OS X
In [line 448](https://github.com/dotnet/corefx/blob/5deb320669242090b28ed63d7faec4834b07201f/src/System.Console/src/System/ConsolePal.Unix.cs#L448) of ConsolePal.Unix.cs:
```csharp
string filePath = directoryPath + "/" + term[0] + "/" + term;
```
If run on Linux Ubuntu, the filePath is `/lib/terminfo/x/xterm-256color`.
If run on Mac OS X, the program will seach following paths:
```
~/.terminfo/x/xterm-256color
/etc/terminfo/x/xterm-256color
/lib/terminfo/x/xterm-256color
/usr/share/terminfo/x/xterm-256color
```
But on Mac OS X, the xterm-256color is in `/usr/share/terminfo/78/xterm-256color`. 78 is hex ascii of "x". 
When change 'x' to 78, there are following failures:
```
Assert failure (unable to format)
/git/dotnet/coreclr/src/vm/stackwalktypes.h
SPOffset >= pUnwindInfo->RSPOffsetFromUnwindInfo
**** MessageBox invoked, title 'Assert failure (unable to format)' ****
  SPOffset >= pUnwindInfo->RSPOffsetFromUnwindInfo
********

Assert failure (unable to format)
/git/dotnet/coreclr/src/vm/stackwalktypes.h
FitsIn<DWORD>(pUnwindInfo->RBPOffset + (SPOffset - pUnwindInfo->RSPOffsetFromUnwindInfo))
**** MessageBox invoked, title 'Assert failure (unable to format)' ****
  FitsIn<DWORD>(pUnwindInfo->RBPOffset + (SPOffset - pUnwindInfo->RSPOffsetFromUnwindInfo))
********
```

### PR DESCRIPTION
**Pull request by stephentoub**
terminfo files are organized into subdirectories based on the first letter of the terminal name.  On Linux, the letter itself is used as the directory name.  On OS X, the hex value for the letter is used as the directory name.  This commit updates the logic that searches for the terminfo database file to try both locations.

Fixes #723 (the search portion of it, not the runtime asserts once the correct search path is used)

### CODE REVIEW

**Comment by stephentoub** [comment]
cc: @ellismg, @cnblogs-dudu

**Comment by stephentoub** [comment]
@cnblogs-dudu, is the Debug.Assert condition and thus causing a failure, or is the condition passing but this is still resulting?  If you remove the Debug.Assert call, does it behave as you expect (until you hit the other issue you mentioned in your original issue)?

**Comment by cnblogs-dudu** [comment]
@stephentoub 
If building System.Console in release mode, this failure is gone.
In the whole System.Console.sln, Debug.Assert take place in two places. One is here. Another is in Win32Marshal.cs. But that is for Win32.

**Comment by stephentoub** [comment]
@cnblogs-dudu, thanks, but I think I didn't ask my question clearly. If you leave the debug assert but change the condition to just be hardcoded to true, what happens? If you Console.WriteLine the condition, do you see true or false? I'm trying to understand if the Assert call itself is erroneous because the condition is failing, or if this is a runtime issue with regards to the Assert method no matter what the condition.

Also, just to be clear, when you remove the assert or compile in release, the new functionality for finding the terminfo file behaves as you expect, right?

Thanks!

**Comment by cnblogs-dudu** [comment]
@stephentoub 
I try it step by step.
First of all, I change Interop.libc.lseek64 to Interop.libc.lseek in ConsolePal.Unix.cs. Details in #733 .
1) Keep Debug.Assert and build in debug mode [Fail]
```
Assert failure (unable to format)
/git/dotnet/coreclr/src/utilcode/ccomprc.cpp
false && "UNIXTODO: Implement string loading from resources"
```
2) Remove Debug.Assert and build in debug mode [Success]
```csharp
private static Database ReadDatabase(string term, string directoryPath)
{
    //Debug.Assert(term != null);
    //Debug.Assert(directoryPath != null);
```
Run command `runtime_mac/corerun app/HelloWorld.exe mac`
Output on mac:
```
Hello, Mac...
TryOpen Successfully:/usr/share/terminfo/78/xterm-256color
termInfoLength:3322
HeaderLength:12
[Apple Logo]
```
3) "leave the debug assert but change the condition to just be hardcoded to true" [Fail]
Same with case 1
```
Assert failure (unable to format)
/git/dotnet/coreclr/src/utilcode/ccomprc.cpp
false && "UNIXTODO: Implement string loading from resources"
```
4) Build in release mode [Fail]
Fail but it is a new issue. 
```
Hello, Mac...
TryOpen Successfully:/usr/share/terminfo/78/xterm-256color
termInfoLength:3322
HeaderLength:12
Assert failure(PID 57872 [0x0000e210], Thread: -580261696 [0xdd69e8c0]): Assertion failed 'emitCurIG != emitPrologIG' in

    File: /git/dotnet/coreclr/src/jit/emit.cpp, Line: 6392 Image:
/Git/dotnet/CoreClrHelloWorld/runtime_mac/corerun
**** MessageBox invoked, title 'corerun - Assert Failure (PID 57872, Thread -580261696/dd69e8c0)        ' ****
  Assertion failed 'emitCurIG != emitPrologIG' in 'ParameterizedStrings:EvaluateInternal(ref,byref,ref,ref,byref,byref):

/Users/dudu/git/dotnet/coreclr/src/jit/emit.cpp, Line: 6392
```

**Comment by stephentoub** [comment]
Great, thank you, @cnblogs-dudu.  I just wanted to confirm that the problem wasn't that the condition I was asserting was the problem, and you've done that.  I'll comment out the asserts for now, just to avoid triggering whatever underlying runtime issue this is hitting.  Thanks, also, for demonstrating that the new functionality is finding the terminfo file as desired.

**Comment by ellismg** [comment]
LGTM.

**Pull request merged**
