### PR TITLE
Build System.Threading.Overlapped on uapaot

### PR DESCRIPTION
**Pull request by alexperovich**

### CODE REVIEW

**Comment by danmosemsft** [comment]
@alexperovich why does it not work as-is? I know Createfile is not in the WACK, but that's not affecting hte tests.
Ideally they approve CreateFile at which point we would have to back out this stuff.

**Comment by alexperovich** [comment]
There is some special handling that causes CreateFile to not exist when the app tries to bind to it.

**Comment by danmosemsft** [comment]
That's unfortunate and hopefully will be fixed in future.

**Comment by danmosemsft** [comment]
Actually -- would it make sense to make this #if uap (thus uapaot also) ? That would help make sure that F5 behavior stays the same as Ctrl-F5.

**Comment by tijoytom** [comment]
@alexperovich @danmosemsft 
=> There is some special handling that causes CreateFile to not exist when the app tries to bind to it.
Take out -usedefaultPinvoke switch from UILC arguments , then test would fail with TypeLoad exception at runtime whne this API is used.

**Comment by alexperovich** [comment]
> Actually -- would it make sense to make this #if uap (thus uapaot also) ? That would help make sure that F5 behavior stays the same as Ctrl-F5.

These tests actually don't fail on UAP it would appear that ILC is doing something special.

**Comment by danmosemsft** [comment]
> These tests actually don't fail on UAP

Right but that way the tests would run the same on CoreCLR which makes it easier to make sure it doesn't diverge behavior from PN

**Pull request merged**
