### PR TITLE
Unique names for System.Native.* exports

### PR DESCRIPTION
**Pull request by eerhardt**
The methods exported from System.Native.* shims have short generic names, like Close or Stat. Making them more unique by adding "SystemNative_" prefix to each method name.

This is a partial fix for #4818.  I split just the System.Native exports out first.  Will do the rest in a forthcoming PR.

@stephentoub @sokket @jkotas @nguerrera @weshaggard @bartonjs

### CODE REVIEW

**Comment by sokket** [comment]
If it builds and passes, LGTM! So many renames...

**Comment by bartonjs** [comment]
Nice and mechanical; LGTM.  I'm confused why the number of pending checks is so small, though.

**Comment by jkotas** [comment]
:+1:

**Comment by mellinoe** [comment]
It looks like some of the tests are failing because they are still looking for an entrypoint named "Dup" rather than "SystemNative_Dup". It does look like you renamed that, though. Perhaps there are multiple declarations?

**Comment by stephentoub** [comment]
> It looks like some of the tests are failing because they are still looking for an entrypoint named "Dup" rather than "SystemNative_Dup". It does look like you renamed that, though. Perhaps there are multiple declarations?

My guess is that something is using the System.Console.dll from the NuGet package in conjunction with the System.Native.so built with this PR.

**Comment by stephentoub** [comment]
Once it passes CI, LGTM.

**Comment by eerhardt** [comment]
@dotnet-bot test this please

**Comment by eerhardt** [comment]
@dotnet-bot test this please

**Comment by eerhardt** [comment]
@dotnet-bot test this please

**Comment by eerhardt** [comment]
@dotnet-bot test this please

**Comment by eerhardt** [comment]
@dotnet-bot test this please

**Pull request merged**
