### PR TITLE
Make SqlDataRecord GetData implementation ref dll compatible

### PR DESCRIPTION
**Pull request by marek-safar**

### CODE REVIEW

**Comment by saurabh500** [comment]
@marek-safar how does this change help?

**Comment by marek-safar** [comment]
It helps not to break compatibility in Mono build

**Comment by saurabh500** [comment]
Can you elaborate what is the problem with mono that this PR solves?

**Comment by marek-safar** [comment]
This is public compatibility/API breakage for Mono build which is not using ref assemblies but directly src/ files.

**Comment by saurabh500** [comment]
@dotnet-bot Test Linux x64 Release Build please
@dotnet-bot Test Windows x64 Debug Build please

**Pull request merged**
