### PR TITLE
Remove redundant OpenSslX509StoreProvider

### PR DESCRIPTION
**Pull request by bartonjs**
OpenSslX509StoreProvider was the original stand-in for Windows Store equivalence, and it was mainly tape and bailing wire.

As the Unix X509Certificates implementation expanded eventually there was a CollectionBackedStoreProvider type, which had at least as much functionality.

Since OpenSslX509StoreProvider was one of the last sanctuaries of NotImplementedException in Unix X509Certificates, this type is being removed and the callers migrated over to CollectionBackedStoreProvider.

This is a partial fix for #1993.

### CODE REVIEW

**Comment by bartonjs** [comment]
Ah, I developed this after #5132, but submitted them as peer changes.  The method deleted in 5132 instantiated the type that I'm removing here.  I guess this one gets to sit as blocked.

**Comment by stephentoub** [comment]
LGTM

**Comment by stephentoub** [comment]
@dotnet-bot test this please

**Comment by stephentoub** [comment]
Test Innerloop CentOS7.1 Debug Build and Test please

**Pull request merged**
