### PR TITLE
release/2.0: Fix IPv6 address parsing when last number is too long

### PR DESCRIPTION
**Pull request by stephentoub**
Port https://github.com/dotnet/corefx/pull/23712 to release/2.0 (just the relevant commits).

### CODE REVIEW

**Comment by stephentoub** [comment]
@dotnet-bot test Innerloop CentOS7.1 Debug x64 Build and Test please (native build failed with "fatal error: 'limits' file not found")
@dotnet-bot test Innerloop CentOS7.1 Release x64 Build and Test please (native build failed with "fatal error: 'limits' file not found")

**Comment by stephentoub** [comment]
@dotnet/dnceng, do you what's up with CentOS?  The last four legs have failed with compilation errors, e.g.
https://ci.dot.net/job/dotnet_corefx/job/release_2.0.0/job/centos7.1_debug_prtest/569/
```
[ 10%] Building CXX object System.Net.Http.Native/CMakeFiles/System.Net.Http.Native.dir/pal_slist.cpp.o
/mnt/resource/j/workspace/dotnet_corefx/release_2.0.0/centos7.1_debug_prtest/src/Native/Unix/System.Net.Http.Native/pal_easy.cpp:9:10: fatal error: 'memory' file not found
#include <memory>
         ^
In file included from /mnt/resource/j/workspace/dotnet_corefx/release_2.0.0/centos7.1_debug_prtest/src/Native/Unix/System.Native/pal_errno.cpp:7:
/mnt/resource/j/workspace/dotnet_corefx/release_2.0.0/centos7.1_debug_prtest/src/Native/Unix/Common/pal_utilities.h:12:10: fatal error: 'limits' file not found
#include <limits>
         ^
1 error generated.
In file included from /mnt/resource/j/workspace/dotnet_corefx/release_2.0.0/centos7.1_debug_prtest/src/Native/Unix/System.Net.Http.Native/pal_multi.cpp:7:
/mnt/resource/j/workspace/dotnet_corefx/release_2.0.0/centos7.1_debug_prtest/src/Native/Unix/Common/pal_utilities.h:12:10: fatal error: 'limits' file not found
#include <limits>
         ^
```
@dotnet-bot test Innerloop CentOS7.1 Debug x64 Build and Test please
@dotnet-bot test Innerloop CentOS7.1 Release x64 Build and Test please

**Comment by mmitche** [comment]
@stephentoub These machines got patched, though only java and git (though git had to be recompiled from source).

I'll poke around on a machine.

**Comment by mmitche** [comment]
@stephentoub I'm rolling back temporarily to the previous image.  I took a quick look at the image and limits is in the same spot in both....

I'm suspicious that the cmake logic is incorrect.

**Comment by mmitche** [comment]
@dotnet-bot test Innerloop CentOS7.1 Release x64 Build and Test

**Comment by mmitche** [comment]
@dotnet-bot test Innerloop CentOS7.1 Release x64 Build and Test

**Comment by mmitche** [comment]
@stephentoub @danmosemsft @smile21prc Is going to take a look at figuring out why this update causes corefx to fail.

**Comment by smile21prc** [comment]
According to https://ci.dot.net/job/dotnet_corefx/job/release_2.0.0/job/centos7.1_debug_prtest/569/console, the build command below starts BEFORE "Scanning dependencies of target System.Native" step is executed:

09:58:35 [  2%] Building CXX object System.Net.Http.Native/CMakeFiles/System.Net.Http.Native.dir/pal_curlinit.cpp.o
09:58:35 Scanning dependencies of target System.Native
09:58:35 In file included from /mnt/resource/j/workspace/dotnet_corefx/release_2.0.0/centos7.1_debug_prtest/src/Native/Unix/System.IO.Compression.Native/pal_zlib.cpp:6:
09:58:35 /mnt/resource/j/workspace/dotnet_corefx/release_2.0.0/centos7.1_debug_prtest/src/Native/Unix/Common/pal_utilities.h:12:10: fatal error: 'limits' file not found
09:58:35 #include <limits>

I suspect that was why the build failed -- it didn't find where native headers live (through "Scanning dependencies of target System.Native") yet, when it attempted to use them to build.

The upgraded image is slower, which might have caused the "Scanning dependencies" steps to take longer. I suspect current "make" configuration does NOT force build starts AFTER all "Scanning dependencies" are complete. In this case, it started before it should.

If we can configure "make" to hold the build until all "Scanning dependencies" are complete, this failure might be gone.

**Comment by danmosemsft** [comment]
"limit" is not generated by our build. On machines that hit this, is it present under /usr/include ? I didn't check where we normally find it, but on my machine, it's in /usr/include/c++/5.4.0, at least.

**Comment by smile21prc** [comment]
Yep, the build sequences in make is not the root cause. The run below also had "Scanning dependencies" steps intervening with builds steps, but it passed
https://ci.dot.net/job/dotnet_corefx/job/release_2.0.0/job/centos7.1_debug_prtest/567/

@danmosemsft , I double checked both the good (pre-upgrade) and bad (post-upgrade) image:
1. <limits> as well as other C++ STL headers are pre-installed on both images at identical dir:
       /usr/include/c++/4.8.3
2. Their printenv results are identical. Both have env var correctly set to where <limits> sits:
       PWD=/usr/include/c++/4.8.3
3. Their make versions are identical (GNU Make 3.82)

Not obvious why it can find <limits> with before upgrade, but not after.


For your reference, the command to connect to both images are as below:

Bad image

ssh dotnet-bot@centos71-20170216-1f19d0.westus2.cloudapp.azure.com

Good Image

ssh dotnet-bot@centos71-20170216-3a19a0.westus2.cloudapp.azure.com

**Comment by smile21prc** [comment]
Figured out the root cause.

From the yum history log, one upgrade step was to update gcc ("Aug 31 21:10:46 Updated: gcc-4.8.5-11.el7.x86_64"), which upgraded it to 4.8.5 from the default version 4.8.3.

The problem was, it probably upgraded gcc with command:
    sudo yum install gcc

In that case, new headers were not installed, even though new libs were:
[dotnet-bot@centos71-20170216-1f19d0 ~]$ ls /usr/include/c++
4.8.2  4.8.3
[dotnet-bot@centos71-20170216-1f19d0 x86_64-redhat-linux]$ ls /lib/gcc/x86_64-redhat-linux
4.8.2  4.8.3  4.8.5

4.8.5 version gcc failed to load 4.8.3 headers during CI leg run.

The fix is to uninstall 4.8.5, then reinstall it with command below:
    sudo yum install gcc-c++

This does updates both headers and lib files:
[dotnet-bot@centos71-20170216-1f19d0 home]$ ls /usr/include/c++
4.8.2  4.8.5
[dotnet-bot@centos71-20170216-1f19d0 home]$ ls /lib/gcc/x86_64-redhat-linux
4.8.2  4.8.5

**Comment by stephentoub** [comment]
@dotnet-bot test Innerloop CentOS7.1 Release x64 Build and Test please

**Comment by weshaggard** [comment]
@smile21prc @stephentoub are we confident this is only a infa issue and is ready to be merged?

**Comment by danmosemsft** [comment]
It's clearly an infra issue, but it means the centos tests didn't run.

**Comment by mmitche** [comment]
@danmosemsft This has been fixed

**Comment by mmitche** [comment]
@dotnet-bot test Innerloop CentOS7.1 Release x64 Build and Test

**Pull request merged**
