### PR TITLE
Remove unused serialization members

### PR DESCRIPTION
**Pull request by ViktorHofer**
Fixes https://github.com/dotnet/corefx/issues/22780

Not sure what the intent of those types is. Their sole purpose is to serialize something. What should be do about them?

- https://github.com/dotnet/corefx/blob/master/src/System.Security.Claims/src/System/Security/Claims/ClaimsIdentity.cs
- https://github.com/dotnet/corefx/blob/master/src/System.Security.Claims/src/System/Security/Claims/GenericPrincipal.cs
- https://github.com/dotnet/corefx/blob/master/src/System.Security.Principal.Windows/src/System/Security/Principal/WindowsPrincipal.cs

### CODE REVIEW

**Comment by stephentoub** [comment]
> Not sure what the intent of those types is. Their sole purpose is to serialize something.

I'm not understanding the question... the sole purpose of which types is to serialize something?

**Comment by ViktorHofer** [comment]
Oh let me ask that again.

What are these types used for besides serialization? I see serialization attributes on the methods but not on the types (I guess they were removed by Morgan). Do we still need the serialization methods of the mentioned types?

**Comment by stephentoub** [comment]
> What are these types used for besides serialization?

WindowsPrincipal, GenericPrincipal, and ClaimsIdentity?
https://msdn.microsoft.com/en-us/library/system.security.principal.genericprincipal
https://msdn.microsoft.com/en-us/library/system.security.principal.windowsprincipal
https://msdn.microsoft.com/en-us/library/system.security.claims.claimsidentity

**Comment by ViktorHofer** [comment]
Sorry I thought at least one of the types isn't doing anything besides serialization but I was wrong. @stephentoub please review my latest commit. I'm now done.

**Pull request merged**
