### PR TITLE
Adding span tests to improve coverage

### LINKED ISSUE #17078: Add tests to increase code coverage for Span<T> APIs
Here is a snapshot of the coverage:
image

Currently, SpanHelpers, specifically SpanHelpers.Clear.cs needs tests.
https://ci.dot.net/job/dotnet_corefx/job/master/job/code_coverage_windows/Code_Coverage_Report/System.Memory_SpanHelpers.htm

### PR DESCRIPTION
**Pull request by ahsonkhan**
Fixes #17078 

Adding tests for:
- Implicit operators
- Obsolete methods
- Clear EnumType and Clear ValueType Without References Pointer Size
- Copy empty source
- Fill native memory
- Fill ValueType Without References for larger arrays
- Test IndexOf for larger arrays

Gets us much closer to 100% test coverage (for slow span at least), esp if you include outer-loop and 32-bit tests.

### CODE REVIEW

**Comment by ahsonkhan** [comment]
cc @shiftylogic, @KrzysztofCwalina, @jkotas

**Comment by ahsonkhan** [comment]
@dotnet-bot test code coverage please

**Comment by ahsonkhan** [comment]
**Questions:**
- How do we get branch coverage where`if (Vector.IsHardwareAccelerated)` is false? This is always true for our tests.

- @benaadams, when is this true (i.e. what test scenario would expose this branch?
https://github.com/dotnet/corefx/blob/master/src/System.Memory/src/System/SpanHelpers.byte.cs#L144

- Is there a way to prevent generation and compilation of System.SR (i.e. SR.cs) for fast span by excluding Strings.resx?

**Comment by ahsonkhan** [comment]
@dotnet-bot test Innerloop OSX10.12 Debug x64 Build and Test please

**Comment by benaadams** [comment]
> How do we get branch coverage whereif (Vector.IsHardwareAccelerated) is false? This is always true for our tests.

Use #if instead and use readonly static instead of `Vector.IsHardwareAccelerated`?
```csharp
#if DEBUG
    readonly static bool IsHardwareAccelerated = false;
#else
    readonly static bool IsHardwareAccelerated = Vector.IsHardwareAccelerated;
#end
```
> when is this true

Input is multiple of Vector length without match

**Comment by ahsonkhan** [comment]
> Use #if instead and use readonly static instead of Vector.IsHardwareAccelerated?

I do not want to change the source. I am wondering if there is a change on the test infra side that would test this branch. Do we run CI on machines where this is false?

**Comment by ahsonkhan** [comment]
> Input is multiple of Vector length without match

I tried that with the following test, but I don't hit that branch:
https://github.com/dotnet/corefx/blob/f77be4bad9367de7c900202edf1ae36e1860cf67/src/System.Memory/tests/Span/IndexOf.byte.cs#L58

**Comment by benaadams** [comment]
Might be alignment adjustment as the array is allocated each time and will move in memory.

Allocate an fixed array then for loop down it to move the alignment?

e.g. something like
```csharp
byte[] array = new byte[4 * Vector<byte>.Count];

for (var i = 0; i < array.Length - Vector<byte>.Count; i++)
{
    var span = new Span<byte>(array, i, Vector<byte>.Count);
    int idx = span.IndexOf((byte)'1');
    Assert.Equal(-1, idx);
}
```

**Comment by ahsonkhan** [comment]
> Might be alignment adjustment as the array is allocated each time and will move in memory.

This doesn't hit it either. Also, in your example code, the span length is always Vector<byte>.Count which means you always drop down to SequentialScan (i.e., this is false):
https://github.com/dotnet/corefx/blob/f77be4bad9367de7c900202edf1ae36e1860cf67/src/System.Memory/src/System/SpanHelpers.byte.cs#L59

I tried the following and still `((int)(byte*)index > length)` is always false.
```C#
            byte[] array = new byte[6 * Vector<byte>.Count];

            for (var i = 0; i < array.Length - 3* Vector<byte>.Count; i++)
            {
                var span = new Span<byte>(array, i, 3* Vector<byte>.Count);
                int idx = span.IndexOf((byte)'1');
                Assert.Equal(-1, idx);
            }
```

**Comment by ahsonkhan** [comment]
@dotnet-bot test code coverage please

**Comment by benaadams** [comment]
:(

**Comment by ahsonkhan** [comment]
@benaadams, is this unnecessary/dead code then?

@shiftylogic, does this PR look good?

**Comment by benaadams** [comment]
Would suggest an unnecessary jump back; might need to be `if (index == length)` instead

**Comment by AndyAyersMS** [comment]
You can disable vectorization by setting `COMPlus_FeatureSIMD=0` before you run tests. This should cause the `IsHarwareAccelerated` predicate to evaluate to false.

You can force a shorter vector lengths (assuming you normally run on AVX capable HW) via `COMPlus_EnableAVX=0`.

Both of these are available in release builds, I believe.

**Comment by ahsonkhan** [comment]
> You can disable vectorization by setting `COMPlus_FeatureSIMD=0` before you run tests. This should cause the `IsHardwareAccelerated` predicate to evaluate to false.

@AndyAyersMS, thanks :)
Is this a change in the environment variable or can you do this in C# code? If so, can you provide code samples where this is done?

**Comment by ahsonkhan** [comment]
@dotnet-bot test code coverage please

**Comment by ahsonkhan** [comment]
> Would suggest an unnecessary jump back; might need to be if (index == length) instead

@benaadams, I submit a PR with changes to the IndexOf worker method, please take a look: https://github.com/dotnet/corefx/pull/17500

**Comment by AndyAyersMS** [comment]
It's an environment setting. It needs to be determined when the CLR initializes, before any jitting happens, since it alters the way SIMD types are handled. You can't set this from C# code.

**Comment by ahsonkhan** [comment]
> It's an environment setting. It needs to be determined when the CLR initializes, before any jitting happens, since it alters the way SIMD types are handled. You can't set this from C# code.

So how can we add this to CI?

**Comment by ahsonkhan** [comment]
@dotnet-bot test Innerloop Windows_NT Debug x86 Build and Test please

**Comment by AndyAyersMS** [comment]
There might be some sort of customizable environment setup that you could leverage to get the right settings in place before running tests. CoreCLR's CI has this for things like jit stress and gc stress.

**Comment by ahsonkhan** [comment]
> There might be some sort of customizable environment setup that you could leverage to get the right settings in place before running tests.

Who would be the right person to talk to about making this change? @crummel

**Comment by ahsonkhan** [comment]
@shiftylogic, good to go?

image

**Comment by shiftylogic** [comment]
👍

**Comment by ahsonkhan** [comment]
Fixes part of https://github.com/dotnet/corefxlab/issues/1314

**Pull request merged**
