### PR TITLE
Vectors package

### PR DESCRIPTION
**Pull request by ericstj**
We need the package even though this library is currently part of
netstandard2.0 (at least for now https://github.com/dotnet/standard/issues/250)
because not all types are present in .NET 4.6.1 even though it supports
netstandard2.0.

/cc @weshaggard @mellinoe

### CODE REVIEW

**Comment by mellinoe** [comment]
I think this will need to be changed since we are removing S.N.V from netstandard.dll, right?

**Comment by weshaggard** [comment]
>I think this will need to be changed since we are removing S.N.V from netstandard.dll, right?

yes it will need an update once we ingest the netstandard changes.

**Comment by ericstj** [comment]
It'll conveniently break the build at that point 😄

**Comment by weshaggard** [comment]
You mean like https://github.com/dotnet/corefx/pull/17381 :)

**Comment by ericstj** [comment]
Indeed, thanks for fixing that.

**Pull request merged**
