### PR TITLE
[release/1.0.0] Update buildtools

### PR DESCRIPTION
**Pull request by ellismg**
This brings in updated-buildtools with some support for capturing core dumps on Linux and printing back traces.

### CODE REVIEW

**Comment by joshfree** [comment]
@ericstj

**Comment by ericstj** [comment]
LGTM.

**Comment by stephentoub** [comment]
LGTM2

**Comment by gkhanna79** [comment]
@eerhardt If this change is about getting backtraces of all the threads from CoreDump, can you please make the same change for CLI since it does not consume Buildtools?

CC @sergiy-k @adityamandaleeka

**Comment by eerhardt** [comment]
I made what I considered the same change in a CLI PR:  https://github.com/dotnet/cli/pull/3525.

We don't need to merge that CLI PR, we can just keep running it over and over until it fails.

**Pull request merged**
