### PR TITLE
Make optimization in GetHashCode function

### PR DESCRIPTION
**Pull request by ichensky**

### CODE REVIEW

**Comment by Wraith2** [comment]
Can you explain why you want to make this change? and how it optimizes the function? 
It looks like it does more work and deviates from the pattern where primitive numeric types use their own value as their hashcode.

**Comment by danmosemsft** [comment]
I am not sure why it is done the way it is today (as it seems it would not increase entropy). Unsigned Byte does not do it.

**Comment by Wraith2** [comment]
I've misread, I thought you were adding the second use and you're removing it, I apologise.
The change log shows it was that way from the initial commit.

**Comment by danmosemsft** [comment]
Opening up the 2.0 mscorlib in ILSPY, it seems it was the same then, so presumably since 1.0. Probably hard to know why, at this point.

Is there any particular reason to change it, other than it's odd?

**Comment by danmosemsft** [comment]
Maybe @jkotas knows why

**Comment by jkotas** [comment]
I do not know. It has been like that since ~2001 and there is no easy way to access older history.

**Comment by danmosemsft** [comment]
I think it is OK to change. We do not guarantee that hash codes are stable between versions. As for why it is needed, it is not clear, if there was an issue with collections that did not properly use the bottom 8 bits of the hashcode, then `Byte` and `Boolean` would already have a problem.

**Comment by danmosemsft** [comment]
@dotnet-bot test this please

**Comment by tannergooding** [comment]
Do we need the explicit cast to int, or can we remove it as part of this?

**Comment by jkotas** [comment]
This is CoreLib change. CoreLib changes shouldbe submitted via CoreCLR repo.

**Comment by jkotas** [comment]
Also, Int16 should get the same change: https://github.com/dotnet/corefx/blob/master/src/Common/src/CoreLib/System/Int16.cs#L66

**Comment by danmosemsft** [comment]
Note that some hash table implementations assume that the hashcode bits are uniformly distributed over the space.

For example Google's Abseil table described here https://blog.waffles.space/2018/12/07/deep-dive-into-hashbrown/ uses the full code to find a group, then the most significant 7 bits within the group
https://github.com/abseil/abseil-cpp/blob/master/absl/container/internal/raw_hash_set.h#L68

As mentioned bool and byte would already have problems with this scheme.

**Comment by danmosemsft** [comment]
@ichensky as noted above, this repo mirrors this code from CoreCLR repo. Can you please make the change there instead? Eg https://github.com/dotnet/coreclr/blob/master/src/System.Private.CoreLib/shared/System/SByte.cs#L69 and Int16 is in the same place.

The tests would be in this repo, there are probably not any that check the actual value of the hash code, but if there are any, we should either fix or remove them with a PR in this repo. Probably you just need the CoreCLR PR though.

**Comment by danmosemsft** [comment]
We do not need this now

**Pull request closed without merging**
