### PR TITLE
Improve coverage of the S.S.Cryptography.Csp package

### PR DESCRIPTION
**Pull request by bartonjs**
This was originally motivated by a report that said that our internal test suite had marginally better (30 blocks, 1.9% line coverage) coverage results.  But we only have 53.3% line coverage... so I went ahead and just did a full coverage-improvement pass.

* Added tests to validate the PublicOnly property
* Added tests to validate the CspKeyContainerInfo population
* Added tests for the RSACryptoServiceProvider-specific Sign and Verify methods
* Added tests which verify persistent key support

This additional coverage turned up a few bugs that happened while porting from the desktop code (largely errors that happened when porting the CSP support from within the VM to just using managed code)
* RSACryptoServiceProvider.PublicOnly was always false
* RSACryptoServiceProvider.CspKeyContainerInfo.UniqueKeyContainerName had trailing null characters
* RSACryptoServiceProvider.CspKeyContainerInfo.ProviderName didn't populate the value when only a ProviderType was set

I also got "lucky" and started hitting an assert in SafeKeyHandle.ReleaseHandle, it turned out to be that SafeKeyHandles need to be freed before their allocating SafeProvHandles, and the increased coverage showed that GetProviderParameter (in particular, reading the Exportable property) was causing SafeKeyHandles to be finalized, and there's a race condition against the SafeProvHandle.  This specific problem was fixed in this PR, but opened #6210 and #6211 to track the overall problems discovered with these handles.

cc: @AtsushiKan @morganbr @stephentoub

### CODE REVIEW

**Comment by bartonjs** [comment]
Test code coverage please

**Comment by stephentoub** [comment]
53.3% to 73.8% is a nice increase.

**Comment by bartonjs** [comment]
|Name|Covered|Uncovered|Coverable|Total|LinePct|BranchPct|
|---|---|---|---|---|---|---|
|System.Security.Cryptography.Csp (Rollup)|296|-313|-17|-93|20.50%|15.50%|
|Internal.Cryptography.CryptoThrowHelper|0|0|0|0|0.00%|0.00%|
|Internal.Cryptography.Helpers|0|0|0|0|0.00%|0.00%|
|Internal.NativeCrypto.CapiHelper|133|-130|3|12|17.30%|14.80%|
|Internal.NativeCrypto.CRYPT_OID_INFO|0|0|0|0|0.00%|0.00%|
|Internal.NativeCrypto.OidInfo|2|-2|0|0|4.00%|12.50%|
|Interop|0|0|0|0|0.00%|0.00%|
|Microsoft.Win32.SafeHandles.SafeHandleZeroOrMinusOneIsInvalid|0|0|0|0|0.00%|0.00%|
|System.Security.Cryptography.CspKeyContainerInfo|78|-78|0|0|67.20%|39.20%|
|System.Security.Cryptography.CspParameters|3|-3|0|0|6.30%|50.00%|
|System.Security.Cryptography.RSACryptoServiceProvider|63|-63|0|0|19.50%|12.50%|
|System.Security.Cryptography.SafeHashHandle|0|-4|-4|-35|28.60%|0.00%|
|System.Security.Cryptography.SafeKeyHandle|6|-12|-6|-35|37.50%|0.00%|
|System.Security.Cryptography.SafeProvHandle|7|-17|-10|-35|21.20%|50.00%|

**Comment by bartonjs** [comment]
Maybe soon I'll come up with a presentation form for delta-coverage comments that doesn't end up feeling confusing. :)

**Comment by bartonjs** [comment]
|Name|Covered|Uncovered|Coverable|Total|LinePct|BranchPct|
|---|---|---|---|---|---|---|
|System.Security.Cryptography.Csp (Rollup)|804 => 1100 (+296)|703 => 390 (-313)|1507 => 1490 (-17)|4097 => 4004 (-93)|53.30% => 73.80% (+20.50%)|46.00% => 61.50% (+15.50%)|
|Internal.NativeCrypto.CapiHelper|435 => 568 (+133)|320 => 190 (-130)|755 => 758 (+3)|1656 => 1668 (+12)|57.60% => 74.90% (+17.30%)|50.90% => 65.70% (+14.80%)|
|Internal.NativeCrypto.OidInfo|29 => 31 (+2)|21 => 19 (-2)|50 => 50 (+0)|134 => 134 (+0)|58.00% => 62.00% (+4.00%)|25.00% => 37.50% (+12.50%)|
|System.Security.Cryptography.CspKeyContainerInfo|0 => 78 (+78)|116 => 38 (-78)|116 => 116 (+0)|253 => 253 (+0)|0.00% => 67.20% (+67.20%)|0.00% => 39.20% (+39.20%)|
|System.Security.Cryptography.CspParameters|38 => 41 (+3)|10 => 7 (-3)|48 => 48 (+0)|92 => 92 (+0)|79.10% => 85.40% (+6.30%)|50.00% => 100.00% (+50.00%)|
|System.Security.Cryptography.RSACryptoServiceProvider|195 => 258 (+63)|128 => 65 (-63)|323 => 323 (+0)|629 => 629 (+0)|60.30% => 79.80% (+19.50%)|49.00% => 61.50% (+12.50%)|
|System.Security.Cryptography.SafeHashHandle|10 => 10 (+0)|4 => 0 (-4)|14 => 10 (-4)|258 => 223 (-35)|71.40% => 100.00% (+28.60%)|0.00% => 0.00% (+0.00%)|
|System.Security.Cryptography.SafeKeyHandle|15 => 21 (+6)|15 => 3 (-12)|30 => 24 (-6)|258 => 223 (-35)|50.00% => 87.50% (+37.50%)|0.00% => 0.00% (+0.00%)|
|System.Security.Cryptography.SafeProvHandle|36 => 43 (+7)|32 => 15 (-17)|68 => 58 (-10)|258 => 223 (-35)|52.90% => 74.10% (+21.20%)|50.00% => 100.00% (+50.00%)|


Maybe that's better?  If anyone likes it, I can share my crazy workbook of VLOOKUP and conditional formats (not conditional formatting, that's a different beast altogether :)).  (Sometimes I get fixated on the small things...)

**Comment by bartonjs** [comment]
```
13:42:19 
Build timed out (after 120 minutes). Marking the build as aborted.
13:42:19 
Build was aborted
13:42:19 [xUnit] [INFO] - Starting to record.
13:42:19 [xUnit] [INFO] - Processing xUnit.Net-v2 (default)
13:42:19 ./run-test.sh: line 131: 77961 Terminated: 15          ./corerun xunit.console.netcore.exe $testDllName -xml testResults.xml -notrait category=failing -notrait category=OuterLoop -notrait category=$xunitOSCategory -notrait Benchmark=true
13:42:19 error: One or more tests failed while running tests from 'System.Net.Sockets.AsyncServer.Tests'.  Exit code 143.
```

Do we have a known hang in the sockets tests?   I don't really want to ask for a rerun if we're in a known bad state right now.

**Comment by stephentoub** [comment]
> Do we have a known hang in the sockets tests?

https://github.com/dotnet/corefx/pull/6219

**Comment by stephentoub** [comment]
LGTM

**Comment by bartonjs** [comment]
@stephentoub Since these changes are only in Windows-specific code, I'm okay with merging if you are.

**Pull request merged**
