### PR TITLE
Add an AsSpan method to ImmutableArray

### PR DESCRIPTION
**Pull request by agocke**

### CODE REVIEW

**Comment by stephentoub** [comment]
Is there an API-approved issue for this?

**Comment by agocke** [comment]
@stephentoub this is a draft pr :)

**Comment by stephentoub** [comment]
I understand. Draft prevents it from being merged, but personally I'd still want to avoid such PRs adding new APIs that haven't been reviewed or even proposed. Otherwise we spend time reviewing the implementation of something for which the concept isn't agreed upon. And if we ignore the PR, then what's the point of the PR?

@jkotas, @danmosemsft, @terrajobst, opinions?

**Comment by danmosemsft** [comment]
I guess the purpose of a draft PR is to exercise CI (or possibly to get feedback on a general approach), without getting a code review?

Creating one for an API that isn't approved and may never be approved may cause more noise than its worth. I don't feel strongly though.

**Comment by agocke** [comment]
We're trying to get Github to remove draft PRs from the default view in the PR list. What other noise does it create? Notifications are already silenced.

**Comment by agocke** [comment]
@stephentoub Yeah, I wanted to explicitly point out -- the point of a draft PR is that it is *not* for review, it's for CI and looking at the diff.

How did you find the PR? By looking through the PRs list on CoreFX? You shouldn't have gotten notified about it.

**Comment by stephentoub** [comment]
> By looking through the PRs list on CoreFX?

Yes.  I do that *a lot*.

> We're trying to get Github to remove draft PRs from the default view in the PR list.

That would help in this particular way.  It has downsides as well, though.  Anyone can create a PR, and if draft PRs end up following a similar pattern to normal PRs, they frequently get created and go stale, so over time a drafts PR list is going to grow and grow, and will need to be culled.  There's also the side issue of paying attention to what's consuming CI resources.

**Comment by agocke** [comment]
Yup, so then the main problem is that draft PRs are showing up in the PR list. I agree and want to get this sorted with Github. I'll cite this example to them.

**Comment by stephentoub** [comment]
> the point of a draft PR is that it is not for review

That's not agreed upon.  You can look at diffs without PRs.  And it's an implementation detail that we don't have a good way to run CI without PRs.  The only thing a draft PR actually signals is ability to merge, unless the relevant repo has a convention that applies further meaning to it, which we don't yet.

**Comment by agocke** [comment]
By definition, a Github draft PR is "not ready for review", which is why it has a button to click saying it is "Ready for review", which turns the PR into a regular PR.

You may not have explicitly opted-in to this definition in CoreFX, but the truth of the matter is that as long as you host code on Github you will be defined by their conventions, regardless of whether you like them or not.

**Comment by stephentoub** [comment]
> you will be defined by their conventions, regardless of whether you like them or not.

How do you define review?  GitHub's description of the feature explicitly states that you use draft PRs to get feedback.

**Comment by jkotas** [comment]
Our contribution guidelines specifically say to not send PRs until the APIs have been approved: https://github.com/dotnet/corefx/blob/master/Documentation/project-docs/contributing.md#api-changes

I can see the point of draft PRs for not-yet-approved APIs for complex new features. Draft PR for APIs like this one, where the most work is in agreeing on the shape and writing the code is super trivial, do not have much point.

> By looking through the PRs list on CoreFX?

Yes, Stephen, me and several other folks are looking at all PRs to make sure that they are getting the right attention, etc. Getting github to hide draft PRs (and out-close them after some time of non-activity) would help.

**Comment by agocke** [comment]
@jkotas The code is not at all trivial! It took me two hours to figure out how to build CoreFX, required me to talk to a developer on the team to actually get it to work, and these tests passed locally!

I created this PR to see if I was running tests successfully on my machine and the answer was, I was not.

**Comment by jkotas** [comment]
> It took me two hours to figure out how to build CoreFX, required me to talk to a developer on the team to actually get it to work, and these tests passed locally!

This says that the contribution guidelines can be improved. The code to write is still trivial after you figure out the above.

**Comment by ahsonkhan** [comment]
> > By looking through the PRs list on CoreFX?

> Yes.  I do that *a lot*.

Same here, although the grey vs green icon helps me skip them.

image

> Yes, Stephen, me and several other folks are looking at all PRs to make sure that they are getting the right attention, etc. Getting github to hide draft PRs (and out-close them after some time of non-activity) would help.

+ 1

**Pull request closed without merging**
