### PR TITLE
Port to RC2: Make MoveFile on unix fall back to CopyFile in more cases

### PR DESCRIPTION
**Pull request by stephentoub**
#7094

### CODE REVIEW

**Comment by ellismg** [comment]
@dotnet-bot test Innerloop Windows_NT Release Build and Test please

**Comment by stephentoub** [comment]
FYI, the OSX release leg passed all tests, but then failed at the end due to https://github.com/dotnet/corefx/issues/7096.  @mmitche, any further ideas how to fix this issue?

**Comment by stephentoub** [comment]
Test Innerloop OSX Release Build and Test please

**Comment by stephentoub** [comment]
Test Innerloop OSX Debug Build and Test please

**Pull request merged**
