### PR TITLE
Add post-close delay  to async SerialPort tests

### PR DESCRIPTION
**Pull request by willdean**
Possible fix for #16055 - it's really a work around for long-established problems in SerialPort rather than a test fix, but it should do for now.

### CODE REVIEW

**Comment by danmosemsft** [comment]
@JeremyKuhne can review but my 2c, if we have to have sleeps to workaround bugs, they should be large enough that the test does not fail on a heavily loaded machine running other tests, etc. Otherwise sooner or later they fail and then we just have to make the sleeps longer. So you may want 1 sec, not 200ms, with a flag you can use to run them faster locally.

**Comment by willdean** [comment]
@danmosemsft You could well be right that 1000ms would be a better choice than 200ms here - I was just following what had gone before.   However, most of the test suite can be doomed if you postulate long enough pauses on the test machine (because ultimately it interacts with real hardware and has to test timeouts, transfer speeds, etc.)

Funny enough I do already have a flag (in another PR) to speed up slow tests, so we could certainly do that.

Again, I think we really just shouldn't test hardware-requiring stuff in the inner-loop.  We could do the most basic non-hardware dependent tests (about 120 out of 975)  in the inner loop and then leave the rest for some kind of dedicated machine with proper hardware support and some reasonable expectation of performance.    I think @JeremyKuhne feels more strongly that we should be trying to as much as possible in inner-loop, but  I fear we may never get an adequate intersection of robustness and speed, and it's going to be a tedious and goodwill-destroying process trying to get there.

**Comment by danmosemsft** [comment]
Whatever you guys think best. I assumed these were outer loop, we should certainly minimize or avoid sleeping in inner loop tests.

**Comment by JeremyKuhne** [comment]
> I think @JeremyKuhne feels more strongly that we should be trying to as much as possible in inner-loop, but I fear we may never get an adequate intersection of robustness and speed

To be clear, we should have as much coverage as possible _without_ sacrificing speed. Whatever is caught in CI is much cheaper to fix than the outer loop.

And for any test we should be robust- inner or outer loop. We should, however, also be mindful of writing ourselves a blank check with machine resources. If individual tests need minutes to run we should be extra aware of unnecessary duplication, looking for more efficient ways to get the coverage, etc.  Don't lose sleep over it, just be mindful. :)

**Comment by JeremyKuhne** [comment]
@dotnet-bot test Innerloop Windows_NT Debug Build and Test (retest for stability)

**Comment by JeremyKuhne** [comment]
@dotnet-bot test Innerloop Windows_NT Release Build and Test (retest for stability)

**Comment by JeremyKuhne** [comment]
@willdean Feel free to strip out the references to the internal issues and replace with detailed comments when they're provided. I'll continue to dig up what I can when you point them out. (As mentioned, there have been numerous databases over the past 15 years, and sometimes references are incorrect, so I can't guarantee I'll find everything)

**Comment by willdean** [comment]
@JeremyKuhne Thanks for the comments about mindfulness - very useful.  There is a terrible lot of duplication, partly in source code terms but also in coverage - this is partly because of the rather mechanistic way the test have been constructed.

So, for example, a test which tests write timeouts does it by blocking up the output (which needs hardware handshake to to work), writing data, checking it's been blocked up (which requires the buffer counters to work) and then check it times out.   Then later there's a totally different test for the buffer counters, which blocks up the output, writes data, checks it's buffered, and then lets it time out.

So we're using a double the time, with double the test writing/maintenance effort but getting exactly the same coverage from two tests which differ by little more than their name and motivation.  

I understand why it came to be like this - somebody was told to write a test for every method/property - but it's not really the most optimal use of engineering or CI time.

But I did feel (I think we all do) that it would be valuable to get to a point where, with minimal (FSVO, and it's getting bigger all the time) modification we could run the entire existing suite before we started hacking into it - I think, modulo the recent wobble on the CI - that we're actually very close to that, and I've made huge progress with the flexibility to support USB-Serial devices too, which will help those people who don't have piles of specialised kit around to test things on like I do.

**Comment by JeremyKuhne** [comment]
@dotnet-bot test Innerloop Windows_NT Debug Build and Test (retest for stability)

**Comment by JeremyKuhne** [comment]
@dotnet-bot test Innerloop Windows_NT Release Build and Test (retest for stability)

**Comment by JeremyKuhne** [comment]
> But I did feel (I think we all do) that it would be valuable to get to a point where, with minimal (FSVO, and it's getting bigger all the time) modification we could run the entire existing suite before we started hacking into it

I agree, my recommendations are more about long-term strategy as opposed to timing. I'll try to be specific on things being back vs. front burner.

**Pull request merged**
