### PR TITLE
Add platform selection to build.sh.

### PR DESCRIPTION
**Pull request by pgavlin**
Prior to recent changes, it was possible to use build.sh to cross-compile
CoreFX by passing "/p:OSGroup=<target OS>" at the command line. This
change restores the ability to cross-compile by allowing the specification
of the target OS as a command-line option to build.sh: any one of
"windows", "linux", "osx", or "freebsd" is accepted.

### CODE REVIEW

**Comment by pgavlin** [comment]
@stephentoub @nguerrera @ellismg PTAL

**Comment by nguerrera** [comment]
Someone else pinged about /t:rebuild being broken. Should we say that trailing args are forwarded to msbuild again? I think this was an oversight in the merger of build.sh with src/Native/build.sh.

Then again parsing /p:OSGroup= to skip native build is awkward.

Something to think about, but this LGTM either way.

**Comment by nguerrera** [comment]
Also, wondering if build_os != windows should be build_os != host os. Native build can't cross-compile as of now.

**Comment by pgavlin** [comment]
> Someone else pinged about /t:rebuild being broken. Should we say that trailing args are forwarded to msbuild again?

Maybe it's worth considering the syntax ` [managed managed-build-args] [native native-build-args]` or similar.

> Also, wondering if build_os != windows should be build_os != host os. Native build can't cross-compile as of now.

That's a fair point. Seems reasonable.

**Comment by nguerrera** [comment]
>Maybe it's worth considering the syntax  [managed managed-build-args] [native native-build-args]  or similar.

Works for me.

**Comment by pgavlin** [comment]
I'll leave the managed/native args for another PR as it's a more involved change.

**Comment by nguerrera** [comment]
> I'll leave the managed/native args for another PR as it's a more involved change.

Makes sense.

Also, cc @mmitche @chcosta for any implications of current change on CI or official builds (I don't think there are any.

LGTM

**Comment by mmitche** [comment]
Assuming that the defaults don't change then no.

**Pull request merged**
