### PR TITLE
Update System.Diagnostics.Tracing to 4.1.0.0

### PR DESCRIPTION
**Pull request by ericstj**
Fix assembly version for tracing and include previous version to support .NET 4.6.

Fixes https://github.com/dotnet/corefx/issues/5706

/cc @cshung @davmason

### CODE REVIEW

**Comment by ericstj** [comment]
Failure is the following:
```
23:17:05 d:\j\workspace\dotnet_corefx\windows_nt_debug_prtest\Tools\tests.targets(129,5): warning MSB3073: The command "d:\j\workspace\dotnet_corefx\windows_nt_debug_prtest\bin/tests/Windows_NT.AnyCPU.Debug\System.Composition.Tests\dnxcore50/CoreRun.exe xunit.console.netcore.exe System.Composition.Tests.dll  -xml testResults.xml -notrait category=nonwindowstests -notrait Benchmark=true  -notrait category=OuterLoop -notrait category=failing " exited with code -2146233082. [d:\j\workspace\dotnet_corefx\windows_nt_debug_prtest\src\System.Composition\tests\System.Composition.Tests.csproj]
23:17:05 
d:\j\workspace\dotnet_corefx\windows_nt_debug_prtest\Tools\tests.targets(136,5): error : One or more tests failed while running tests from 'System.Composition.Tests' please check log for details! 
```
Doesn't repro locally.  No error in the console spew.  That return code is COR_E_EXECUTIONENGINE.  Runtime bug?

**Comment by ericstj** [comment]
@dotnet-bot please test Innerloop Windows_NT Debug Build and Test

**Comment by ericstj** [comment]
Ping.  /cc @weshaggard

**Comment by weshaggard** [comment]
LGTM

**Pull request merged**
