### PR TITLE
Canonicalize MSBuild ToolsVersion to 12.0

### PR DESCRIPTION
**Pull request by akoeplinger**
Like 57cffc78, but for the recently added projects.

### CODE REVIEW

**Comment by mmitche** [comment]
Can one of the admins verify this patch?

**Comment by mmitche** [comment]
Can one of the admins verify this patch?

**Comment by ellismg** [comment]
add to whitelist

**Comment by ellismg** [comment]
LGTM.

@joshfree.  What do we need to do internally so this setting is the default for new projects we open source?

**Comment by weshaggard** [comment]
LGTM As for getting set internally we can probably just file a bug to do a pass over all the projects and fix them.

**Pull request merged**
