### PR TITLE
Remove unnecessary pinvoke

### PR DESCRIPTION
**Pull request by danmosemsft**
Lock/UnlockFile are not used. We requested them already but we can certainly remove the usage.

### CODE REVIEW

**Comment by danmosemsft** [comment]
@mmitche how is the repo not clean? 
```
15:29:24 ERROR: There are some uncommited changes. To avoid losing these changes commit them and try again.
15:29:24 
15:29:24 HEAD detached at a122769
15:29:24 Changes not staged for commit:
15:29:24   (use "git add <file>..." to update what will be committed)
15:29:24   (use "git checkout -- <file>..." to discard changes in working directory)
15:29:24 
15:29:24 	modified:   src/System.Diagnostics.FileVersionInfo/tests/NativeConsoleApp/Resource.rc
15:29:24 	modified:   src/System.Diagnostics.FileVersionInfo/tests/NativeLibrary/NativeLibrary.rc
15:29:24 	modified:   src/System.Diagnostics.FileVersionInfo/tests/SecondNativeLibrary/SecondNativeLibrary.rc
15:29:24 
```

https://ci.dot.net/job/dotnet_corefx/job/master/job/ubuntu16.04_arm_cross_debug_prtest/875/

same for @krwq 's

**Comment by jkotas** [comment]
It just moved to CoreLib...

**Comment by danmosemsft** [comment]
@jkotas yep, and there are others, I"ll push up more as I see them.

**Comment by danmosemsft** [comment]
@dotnet-bot test Innerloop Ubuntu16.04 arm Debug Cross Build (wierd issue with old clone)

**Pull request merged**
