### PR TITLE
Update branding to 3.1.23

### PR DESCRIPTION
**Pull request by vseanreesermsft**

### CODE REVIEW

**Review by safern — APPROVED** [review]

**Comment by safern** [comment]
@layomia could you please take a look at the JSON test failures?

@bartonjs could you please take a look at the crypto failures?

**Comment by danmoseley** [comment]
@bartonjs is out. maybe @GrabYourPitchforks

**Comment by danmoseley** [comment]
```

Error message
Assert.Equal() Failure\r\n                                 ↓ (pos 1601661)\r\n
Expected: ···qKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioqKioq···\r\n
Actual:     ···qKioqKioqKioqKioqKio\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0qKioqKioqKioqKio\0\0\0\0\0\0\0\0\0···\r\n                                 ↑ (pos 1601661)


Stack trace
   at System.Text.Json.JsonTestHelper.AssertContents(String expectedValue, ArrayBufferWriter`1 buffer) in /_/src/System.Text.Json/tests/JsonTestHelper.cs:line 718
   at System.Text.Json.Tests.Utf8JsonWriterTests.Writing3MBBase64Bytes(Boolean formatted, Boolean skipValidation) in /_/src/System.Text.Json/tests/Utf8JsonWriterTests.cs:line 2728
```
and 
```
  Starting:    System.Security.Cryptography.X509Certificates.Tests (parallel test collections = on, max threads = 12)
    System.Security.Cryptography.X509Certificates.Tests.ChainTests.VerifyExpiration_LocalTime(verificationTime: 2014-10-15T00:00:00.0000000Z, shouldBeValid: True, kind: Utc) [FAIL]
      Assert.Equal() Failure
      Expected: True
      Actual:   False
      Stack Trace:
        /_/src/System.Security.Cryptography.X509Certificates/tests/ChainTests.cs(310,0): at System.Security.Cryptography.X509Certificates.Tests.ChainTests.VerifyExpiration_LocalTime(DateTime verificationTime, Boolean shouldBeValid, DateTimeKind kind)
    System.Security.Cryptography.X509Certificates.Tests.ChainTests.VerifyExpiration_LocalTime(verificationTime: 2014-10-14T20:00:00.0000000-04:00, shouldBeValid: True, kind: Local) [FAIL]
      Assert.Equal() Failure
      Expected: True
      Actual:   False
      Stack Trace:
        /_/src/System.Security.Cryptography.X509Certificates/tests/ChainTests.cs(310,0): at System.Security.Cryptography.X509Certificates.Tests.ChainTests.VerifyExpiration_LocalTime(DateTime verificationTime, Boolean shouldBeValid, DateTimeKind kind)
    System.Security.Cryptography.X509Certificates.Tests.ChainTests.VerifyExpiration_LocalTime(verificationTime: 2014-10-14T20:00:00.0000000, shouldBeValid: True, kind: Unspecified) [FAIL]
      Assert.Equal() Failure
...
```

**Comment by danmoseley** [comment]
JSON looks like long standing issue https://github.com/dotnet/runtime/issues/59678

Crypto had similar failure in https://github.com/dotnet/runtime/issues/26576 that was fixed by adding GrayListedLeaf, but that change was in 3.1 5e46fe15925c29732f5fdbc333e44c49564e082e and 047eee076a1f90792f4f34360696d84b6b3ae717. Are we testing on the same macOS version as in main?

**Comment by safern** [comment]
Thanks, @danmoseley, it seems like  dotnet/runtime#26576 refers to a build issue, here is not a build issue but test failures, so perhaps those are new? We are building on the latest macOS but testing on: OSX10.13.

**Comment by danmoseley** [comment]
dotnet/runtime#26576 sort of covered several things.

**Comment by danmoseley** [comment]
I don't think either of these should block rebranding, of course.

**Comment by safern** [comment]
Thanks, @danmoseley. I'll merge this then.

**Pull request merged**
