### PR TITLE
Use new delimiter "+"

### PR DESCRIPTION
**Pull request by smile21prc**
Apply the new delimiter "+" added in
https://github.com/dotnet/core-eng/issues/596.

### CODE REVIEW

**Comment by smile21prc** [comment]
Apply the new delimiter "+" added in https://github.com/dotnet/buildtools/commit/8ad88be4ffc69590091c1c59b73f1115e52fd868, to address https://github.com/dotnet/core-eng/issues/596.
@mmitche @weshaggard , can you review this?

**Comment by weshaggard** [comment]
You also need to update the build tools version in corefx.

**Comment by smile21prc** [comment]
Thanks @weshaggard for the review. Updated the build tools version in corefx as suggested.

**Comment by smile21prc** [comment]
@dotnet-bot test this please

**Comment by weshaggard** [comment]
BuildToolsVersion.txt was updated to a higher version with https://github.com/dotnet/corefx/pull/17314 so just remove that commit from your PR and merge.

**Comment by smile21prc** [comment]
Thanks Wes for the review, just merged as you suggested.

**Comment by weshaggard** [comment]
@smile21prc for future reference I would squash these into one commit, either locally and force push to your branch or as part of the merging PR button use the squash on merge option.

**Comment by smile21prc** [comment]
Opps, thanks @weshaggard for the reminding. Will do that for future merges.

**Pull request merged**
