### PR TITLE
Fix arrow keys in Console.ReadKey() on Unix

### PR DESCRIPTION
**Pull request by stephentoub**
We interpret the escape strings sent to stdin in order to determine what keys were pressed, and we do so using the terminfo data for the current terminal.  However, the terminfo data is written to assume "application" mode, but apps are invoked by default in "normal" mode.  To enter "application" mode, we need to emit the keypad_xmit string.

The arrow keys in particular have terminfo strings affected by normal vs application mode.  Before this change, using the arrow keys with ReadKey() would result in the values being misterpreted.  Now they're correctly understood.

We were also missing handling for KeyUp.  I've fixed that, as well.

cc: @pallavit

### CODE REVIEW

**Comment by pallavit** [comment]
> The arrow keys in particular have terminfo strings affected by normal vs application mode. Before this change, using the arrow keys with ReadKey() would result in the values being misterpreted. Now they're correctly understood.

Is this true about different terminals as well. For example, in my testing I found that the db values also depended on the terminal used. Xterm and Eterm had different db values. And Eterm could intercept arrow keys. Was this difference also because of application vs normal mode?

**Comment by stephentoub** [comment]
> Was this difference also because of application vs normal mode?

Likely. Eterm doesn't have a keypad_xmit string, e.g.
```
~/netcore$ infocmp Eterm xterm
comparing Eterm to xterm.
...
	smkx: '', '\E[?1h\E='.
...
```

**Comment by pallavit** [comment]
> Likely. Eterm doesn't have a keypad_xmit string, e.g.

Thanks. I was a little surprised at the difference. Good to know. Thanks for doing this. LGTM

**Comment by stephentoub** [comment]
Thanks, Pallavi.

**Pull request merged**
