### PR TITLE
Port to 2.0: Test change - Increasing mutex time, ensuring the mutex is released. 

### LINKED ISSUE #19430: SslStream test failing to access Mutex
@cipop, this looks like fall out from your recent change:
https://ci.dot.net/job/dotnet_corefx/job/master/job/osx10.12_release_prtest/3093/consoleText
```
System.Net.Security.Tests.SslStreamStreamToStreamTest_Async.SslStream_StreamToStream_Successive_ClientWrite_Sync_Success [FAIL]
        Cannot acquire the global certificate mutex.
        Expected: True
        Actual:   False
        Stack Trace:
           /Users/dotnet-bot/j/workspace/dotnet_corefx/master/osx10.12_release_prtest/src/Common/tests/System/Net/Configuration.Certificates.cs(38,0): at System.Net.Test.Common.Configuration.Certificates.GetCertificateCollection(String certificateFileName)
           /Users/dotnet-bot/j/workspace/dotnet_corefx/master/osx10.12_release_prtest/src/System.Net.Security/tests/FunctionalTests/SslStreamStreamToStreamTest.cs(391,0): at System.Net.Security.Tests.SslStreamStreamToStreamTest_Async.DoHandshake(SslStream clientSslStream, SslStream serverSslStream)
           /Users/dotnet-bot/j/workspace/dotnet_corefx/master/osx10.12_release_prtest/src/System.Net.Security/tests/FunctionalTests/SslStreamStreamToStreamTest.cs(78,0): at System.Net.Security.Tests.SslStreamStreamToStreamTest.SslStream_StreamToStream_Successive_ClientWrite_Sync_Success()
     System.Net.Security.Tests.SslStreamStreamToStreamTest_BeginEnd.SslStream_StreamToStream_Authentication_Success [FAIL]
        Cannot acquire the global certificate mutex.
        Expected: True
        Actual:   False
        Stack Trace:
           /Users/dotnet-bot/j/workspace/dotnet_corefx/master/osx10.12_release_prtest/src/Common/tests/System/Net/Configuration.Certificates.cs(38,0): at System.Net.Test.Common.Configuration.Certificates.GetCertificateCollection(String certificateFileName)
           /Users/dotnet-bot/j/workspace/dotnet_corefx/master/osx10.12_release_prtest/src/System.Net.Security/tests/FunctionalTests/SslStreamStreamToStreamTest.cs(404,0): at System.Net.Security.Tests.SslStreamStreamToStreamTest_BeginEnd.DoHandshake(SslStream clientSslStream, SslStream serverSslStream)
           /Users/dotnet-bot/j/workspace/dotnet_corefx/master/osx10.12_release_prtest/src/System.Net.Security/tests/FunctionalTests/SslStreamStreamToStreamTest.cs(36,0): at System.Net.Security.Tests.SslStreamStreamToStreamTest.SslStream_StreamToStream_Authentication_Success()
```

### PR DESCRIPTION
**Pull request by CIPop**
Fixes #19430.
Port #20028

### CODE REVIEW

**Comment by karelz** [comment]
I compared the change to master PR, it is the same.
I noticed that @stephentoub's comment https://github.com/dotnet/corefx/pull/20028/files#r117607492 was not answered. Should it block the original PR/this one?

Otherwise LGTM (pending @stephentoub's judgment on answer for his question in master PR).

**Comment by CIPop** [comment]
> I noticed that @stephentoub's comment 

@karelz I've answered in the original thread.

**Comment by karelz** [comment]
OK, let's wait @stephentoub agrees. I also assume you started the shiproom approval process.

**Comment by CIPop** [comment]
> I also assume you started the shiproom approval process.

Yes, the bug was approved by Shiproom yesterday evening.

**Comment by stephentoub** [comment]
We can go ahead with this; it's better than what we already have.  I'm just wondering if there's something even better.

**Comment by CIPop** [comment]
> I'm just wondering if there's something even better.

@stephentoub This particular fix is just to make OSX work better (for some reason the mutex was held for more than 30 seconds, something that only happens on Windows if >50 test processes are running in parallel.)

I'm not sure anymore that the original bug: #16516 was actually fixed by this mutex (we have had a new crash but within the Release builds - no dump...). When we have some time, I'm actually thinking of removing the mutex completely to capture an instance of the original crash and get more understanding why it's happening.

**Pull request merged**
