### PR TITLE
Update job and badge links

### PR DESCRIPTION
**Pull request by ellismg**
The badge links and jobs were pointing at the handcrafted jobs in Jenkins not the new generated jobs.

This caused some badges to be red that should be green because the older jobs are stale and some of them are failing.

### CODE REVIEW

**Comment by ellismg** [comment]
As part of this I also added badges for release xplat tests, since we have the jobs running in CI.

**Comment by mmitche** [comment]
@ellismg yep doing that.

**Comment by stephentoub** [comment]
LGTM. Thanks, Matt.

**Pull request merged**
