### PR TITLE
Update buildtools to 1.0.25-prerelease-00148

### PR DESCRIPTION
**Pull request by ericstj**
This contains an update to the NuGet binaries that 
allow us to use the latest TFM:generation mappings.
Specifically dotnet5.6.

### CODE REVIEW

**Comment by AlexGhiondea** [comment]
LGTM :)

**Comment by stephentoub** [comment]
I already have a pending PR that updates to v147, but also bumps the version of some of our code coverage tools.  Can you incorporate the changes from my PR?  Then we can close mine.
https://github.com/dotnet/corefx/pull/5327

**Comment by ericstj** [comment]
@stephentoub done.

**Comment by stephentoub** [comment]
Thanks! LGTM

**Comment by ericstj** [comment]
@dotnet-bot please test Innerloop Windows_NT Release Build and Test

**Comment by ericstj** [comment]
@dotnet-bot please test  Innerloop Ubuntu Debug Build and Test

**Comment by ericstj** [comment]
@dotnet-bot please test Innerloop Ubuntu Release Build and Test

**Comment by stephentoub** [comment]
Test Innerloop Ubuntu Release Build and Test please
Test Innerloop Ubuntu Debug Build and Test please

**Pull request merged**
