### PR TITLE
Have Expression.TypeIs return true for void expressions and void

### LINKED ISSUE #5244: Should Expression.TypeIs allow void as a type argument?
Currently any expression will compare with `void` with `TypeIs` as `false`:

```C#
Expression.Lambda<Func<bool>>(
    Expression.TypeIs(Expression.Empty(), typeof(void))
).Compile()() // false
```

This is at odds with `TypeEqual`:

```C#
Expression.Lambda<Func<bool>>(
    Expression.TypeEqual(Expression.Empty(), typeof(void))
).Compile()() // true
```

The decision happens at `AnalyzeTypeIs()` which is commented as saying:

```C#
// Oddly, we allow void operands
// This is LinqV1 behavior of TypeIs
```

Arguably, its not that odd to allow void operands, considering that expressions of void type are allowed, or more reasonaly that dynamic use could mean passing something an expression of type `void` one time and a different type another.

This also makes it a logical exception to the comment saying the result should match the result of `isinst` since there's no way to pass a void expression's value to in CIL (obviously enough as it doesn't have one). The differences between expression trees and CIL (and C#, VB.NET, etc.) are such that what is meaningless in CIL is meaningful, though constant, in trees.

As such it seems to me that the value of `Expression.TypeIs(Expression.Empty(), typeof(void))` should be true, rather than false.

In the other direction, we allow `Expression.TypeIs(Expression.Constant("hello"), typeof(void))` but:

```C#
Expression.Lambda<Func<bool>>(Expression.TypeIs(Expression.Constant("hello"), typeof(void))).Compile()()
```
Throws `InvalidProgramException`. By the same reasoning as above it would make sense for this to return false. This would also make it match `IsInstanceOf()` (but not `isinst` but again that isn't as meaningful in CIL as it is in trees).

### PR DESCRIPTION
**Pull request by JonHanna**
Fixes #5244

### CODE REVIEW

**Comment by JonHanna** [comment]
Test Innerloop Windows_NT Release Build and Test

**Comment by JonHanna** [comment]
Test Innerloop Windows_NT Release Build and Test

**Comment by JonHanna** [comment]
#5279 has tests relevant to this. Currently avoiding the data which triggers it, commented so that they can be changed to hit the relevant cases.

**Comment by bartdesmet** [comment]
Good find and odd behavior indeed. While returning `true` in case of a `void` expression seems right, I'm wondering whether we have cases that rely on the odd behavior for `void`. I really doubt it given that `e is void` is not permitted in C# and the likes but one could always craft an expression by hand. It seems that comment in the code was added in the DLR days, possibly implying that the behavior of always returning `false` for type checks against `void` is kept for sake of compatibility.

@VSadov, what do you think? Maybe some digging in the source history in TFS may bring some clarity on the introduction / retention of this odd behavior.

**Comment by JonHanna** [comment]
I don't have great knowledge of the DLR, but from what I do know I would guess that it is only likely to make trees that are equivalent to the (invalid) C# `e is void` for some non-void `e` and as such the always-false behaviour would be correct for any case it could construct. Such a case would at least still behave as expected after this change.

**Comment by JonHanna** [comment]
The wording of the comment suggests that maybe when the author came across the case of the LHS being void, which they thought "strange", that viewing it as strange stopped them considering that the RHS could just as well be void too. From that viewpoint, the only thing the "strange" construct could result in is `false`, and so the simplest thing to do is to return exactly that.

And in fairness to them, it is a bit strange, and likely the best way to find it is to build some xUnit test that push through a bunch of different types :)

**Comment by JonHanna** [comment]
Test Innerloop CentOS7.1 Debug Build and Test
Test Innerloop CentOS7.1 Release Build and Test

**Comment by JonHanna** [comment]
Test Innerloop CentOS7.1 Debug Build and Test
Test Innerloop CentOS7.1 Release Build and Test

**Comment by JonHanna** [comment]
Tests added.

**Comment by VSadov** [comment]
LGTM

**Pull request merged**
