### PR TITLE
[WIP] [ARM/CI] Test

### PR DESCRIPTION
**Pull request by wateret**
This PR is only for ARM-CI test, I'll close this when the test is done.

### CODE REVIEW

**Comment by wateret** [comment]
@dotnet-bot help

**Comment by wateret** [comment]
@dotnet-bot Test Innerloop Linux ARM Emulator SoftFP Debug Cross Build

**Comment by wateret** [comment]
@dotnet-bot Test Innerloop Linux ARM Emulator HardFP Debug Cross Build

**Comment by wateret** [comment]
@dotnet-bot test outerloop Windows 7 Debug

**Comment by wateret** [comment]
@dotnet-bot test innerloop Fedora24 Debug

**Comment by wateret** [comment]
@dotnet-bot test innerloop Fedora24 Debug

**Comment by wateret** [comment]
@dotnet-bot help

**Comment by wateret** [comment]
@dotnet-bot test innerloop linuxarmemulator HardFP Debug

**Comment by wateret** [comment]
@dotnet-bot test innerloop linuxarmemulator HardFP Debug

**Comment by wateret** [comment]
@dotnet-bot test innerloop linuxarmemulator HardFP Debug

**Comment by stephentoub** [comment]
@wateret, what's the status of this PR? Thanks.

**Comment by wateret** [comment]
@stephentoub I'm done with this PR, closing. I'll keep tracking at #13749. Thanks.

**Pull request closed without merging**
