### PR TITLE
Move solution files to the appropriate projects folders

### LINKED ISSUE #746: The top-level src/ folder is cluttered with all of those .slns
IMHO, each library should have its sln file within its own folder. 

Instead of
```
src\
    System.Xyz\
    System.Xyz.sln
```

We should have

```
src\
    System.Xyz\
          System.Xyz.sln
```

I believe the reasons why we had the former originally are obsolete now.

1) We liked the idea of grouping related libraries together in a solution. Today, only System.Xml.* does this. However, it will not really work long-term because we shouldn't have library-to-library project-to-project references as it messes with our package versioning story post-V1.

2) We had problems with redundant packages/ folders. I believe this was solved by the NuGet.config change that moved packages to a folder at the root outside of src

### PR DESCRIPTION
**Pull request by Maxwe11**
fixes #746

### CODE REVIEW

**Comment by akoeplinger** [comment]
Hmm, what should we do about System.Xml.sln? Wouldn't it make sense to split it up into System.Xml.XDocument, System.Xml.XPath.XDocument, etc. like the rest of corefx?

**Comment by sharwell** [comment]
I would prefer this change not be made, but that's just my opinion of course. :smile:

**Comment by Maxwe11** [comment]
@akoeplinger I mostly think yes, but System.Xml depends on a lot of test projects, so it would be better to review it in another PR

**Comment by weshaggard** [comment]
After you move these solutions does VS correctly pick up the Nuget.config file still? I was under the impression that it needed to live next to the solution files.

**Comment by stephentoub** [comment]
@dotnet-bot test this please

**Comment by Maxwe11** [comment]
I think nuget should pick up config from parent (relatively to solution location) folder too
https://docs.nuget.org/consume/nuget-config-file#chaining-multiple-configuration-files

**Comment by weshaggard** [comment]
Thanks @Maxwe11. If you haven't already would you mind double checking that by loading this in VS to ensure the config is setup correctly still and that you can restore the packages from a clean enviroment (i.e. run git clean -xdf from root). 

Also did you just do a text find replace for location updates or did you open them each in VS? I ask because I'm pretty sure that some of them have some invalid guids and I would have expected to see other updates if you opened them in VS. Also I know a number of these solutions don't have the .nuget/packages.config solution item that seems to get added whenever you do a package restore in one of the solutions. Would you mind having a look into that? Also I do want to do the Xml solutions as well but, I don't want any .sln files in the root src dir. I'm fine if you want to do it in another PR but please do update them as well.

@sharwell what is your reasoning for not wanting to move the solution files? In general we want to eliminate clutter in the root src directory as well as make a given library self-contained inside its directory which is why I support moving the solution files similar to others in #746.

**Comment by sharwell** [comment]
@weshaggard I disagree with the premise of #746, and find it easier to just open the solution I want from the root folder.

**Comment by Maxwe11** [comment]
`> invalid guids

@weshaggard  my investigation shows that only one project has invalid GUID, take a look #819

>Also I know a number of these solutions don't have the .nuget/packages.config solution item that seems to get added whenever you do a package restore in one of the solutions

`.nuget/packages.config` doesn't added as a solution item on a package restore, I've checked each solution in VS. However packages listed in this config restored when solution loading in VS independently on that presented this config in solution or not

**Comment by Maxwe11** [comment]
>Also I do want to do the Xml solutions as well but, I don't want any .sln files in the root src dir. I'm fine if you want to do it in another PR but please do update them as well.
@weshaggard take a look #916 

Also what to do with FileSystem? Split up into FileSystem and into FileSystem.Primitives?

**Comment by weshaggard** [comment]
@Maxwe11 thanks for doing these solution updates. Lets finish the splitting of the Xml and FileSystem solution files and then update this again with all of them moved the appropriate library directory.

**Comment by Maxwe11** [comment]
rebased

**Comment by weshaggard** [comment]
Thanks @Maxwe11

**Pull request merged**
