### PR TITLE
Increase coverage of BinaryExpression (Equals and NotEquals)

### PR DESCRIPTION
**Pull request by hughbe**
Also cleans up Expression.Equal and Expression.NotEqual tests to make it
easier to add new tests

Contributes to #1198

/cc @stephentoub @VSadov

### CODE REVIEW

**Comment by stephentoub** [comment]
Test Innerloop Windows_NT Debug Build and Test please (networking failures)
Test loop CentOS7.1 Debug Build and Test please (networking failures)
Test loop CentOS7.1 Release Build and Test please (networking failures)

**Comment by stephentoub** [comment]
Test Innerloop Windows_NT Debug Build and Test please (networking failures)
Test loop CentOS7.1 Debug Build and Test please (networking failures)
Test loop CentOS7.1 Release Build and Test please (networking failures)

**Comment by hughbe** [comment]
Tests Innerloop CentOS7.1 Debug Build and Test
Tests Innerloop CentOS7.1 Release Build and Test

**Comment by stephentoub** [comment]
cc: @JonHanna

**Comment by hughbe** [comment]
I've rebased this PR to fix a merge conflcit.

**Comment by VSadov** [comment]
LGTM.

**Pull request merged**
