### PR TITLE
Fix two issues in System.Web.HttpUtility

### LINKED ISSUE #23574: HttpUtility.ParseQueryString incorrect if first item's name begins with a question mark
If a query-string's first name-value pair begins with a question mark then the initial question mark is stripped twice, so the name in the parsed collection is incorrect.

E.g. with `??name=value&x=y` the result is a collection where `["name"] == "value"` while if it isn't the first element, as in `?x=y&?name=value` then it has the correct result of `["?name"] == "value"`

### LINKED ISSUE #23582: HttpUtility.ParseQueryString does HTML decoding first on CoreFX, but not on NetFX
The version of `HttpUtility.ParseQueryString` in CoreFX does HTML decoding first, differing from desktop:

```C#
HttpUtility.ParseQueryString("name=value&amp;name2=value2").ToString()
// name=value&amp%3bname2=value2 on Desktop
// name=value&name2=value2 on CoreFX

HttpUtility.ParseQueryString("?name=valu&#xe9;")["name"]
// valu on Desktop
// valué on CoreFX
```

#23573 is a knock-on effect of this. (Closing as such).
#23574 is an indirect knock-on effect in that ? is stripped both before and after HTML decoding that shouldn't be done at all.

### PR DESCRIPTION
**Pull request by JonHanna**
* Don't HTML-decode in HttpUtility.ParseQueryString

Fixes #23582

* Only strip initial ? in HttpUtility.ParseQueryString once.

Fixes #23574

* Simplify ParseQueryString exit logic.

Checks for exit conditions two ways, when just one suffices.

* Inline private ParseQueryString into caller.

Allows for avoiding allocation for initial ?

* Add more HttpUtilityTests

### CODE REVIEW

**Comment by JonHanna** [comment]
Test Tizen armel Debug Build

"docker: failed to register layer: ApplyLayer exit status 1 stdout:  stderr: write /usr/lib/llvm-3.6/bin/clang-tidy: no space left on device." https://ci.dot.net/job/dotnet_corefx/job/master/job/tizen_armel_cross_debug_prtest/6817/console

**Comment by karelz** [comment]
I am hesitant to take the "don't HTML decode" without further compat discussion.
If we take it, we should IMO take it into 2.0.x.

@JonHanna can you please split that one off from your changes?

**Comment by JonHanna** [comment]
@karelz yeah, I called out the compat issue myself in the issue because it's definitely a break (but it also fixes a break with desktop, which argues for taking the change). Obviously I think it should be taken or I wouldn't have submitted the PR, but I agree the break needs to be thought about.

**Comment by JonHanna** [comment]
@karelz I've submitted #23640 that just tackles #23574

I'll leave this as-is until that's in, because it going in will cause conflicts here anyway, and as well as the change to decoding the other commits are either some optimising of the code subsequent to the change and tests of which several will fail without this change, so they're not sensible to split off further.

**Comment by davidsh** [comment]
>I am hesitant to take the "don't HTML decode" without further compat discussion.
If we take it, we should IMO take it into 2.0.x.

System.Web.HttpUtility was ported from .NET Framework into .NET Core but I don't think there were sufficient tests. I recommend this class get fixed asap to make it more compat with .NET Framework *and* backport all such changes to .NET Core 2.0.x.  Fixing is sooner rather than later will mitigate devs taking a dependency on an incorrect difference from NETFX.

**Comment by karelz** [comment]
@davidsh I agree. Can you please send email to AppCompat alias double checking both changes? (HTML decode and removal of extra '?' character)

**Comment by karelz** [comment]
@davidsh @stephentoub can you please review the code change ASAP?
We want a chance to get it into 2.0.2. I just started compat discussion with .NET Core shiproom.
Thanks!

**Comment by JonHanna** [comment]
@karelz are you planning on taking both changes here? Shall I close the split-off #23640?

**Comment by karelz** [comment]
@JonHanna yes, I plan to merge this PR later today. I closed the dupe per your comment.

If you can prepare same PR like this one against release/2.0.0 branch, that would be awesome. If not, I'll do it over the weekend to be ready to take it into servicing branch on Monday to catch the 2.0.2 servicing release train.

**Comment by stephentoub** [comment]
@karelz, please squash PRs like this when merging.

**Comment by stephentoub** [comment]
The implementation looks quite different from the one in reference source.  Do we understand how we ended up with these differences?  History just shows they came over in the initial port from @alexperovich:
https://github.com/dotnet/corefx/pull/11642
@alexperovich, any context?

**Comment by karelz** [comment]
Th source code came from Mono - see details: https://github.com/dotnet/corefx/pull/23918#issuecomment-329558714

**Pull request merged**
