### PR TITLE
Remove dead code from System.Security.Cryptography.Cng

### PR DESCRIPTION
**Pull request by satano**
PR addresses issue #17905, project **System.Security.Cryptography.Cng**.

### CODE REVIEW

**Comment by stephentoub** [comment]
cc: @bartonjs

**Comment by stephentoub** [comment]
@dotnet-bot test OSX x64 Debug Build please ("Failed to retrieve information about 'Microsoft.DotNet.Build.Tasks.Feed'"...)

**Comment by bartonjs** [comment]
@dotnet-bot Test Linux x64 Release Build please (DiagnosticSourceStartStop Assert.InRange() Failure Range:  (00:00:00.0000001 - 00:00:00.1413145) Actual: 00:00:03.2465433)

**Comment by danmosemsft** [comment]
Thanks @satano

**Pull request merged**
