### PR TITLE
allocation optimizations for immutable collections

### PR DESCRIPTION
**Pull request by mtrofin**
requesting the Keys or Values of an immutable (sorted) dictionary allocates every time. In scenarios where a dictionary is setup and then used repeatedly, this is inefficient.

### CODE REVIEW

**Comment by stephentoub** [comment]
@mtrofin, I'm curious, what's happening with this?

**Comment by mmitche** [comment]
Can one of the admins verify this patch?

**Comment by sharwell** [comment]
@stephentoub Here's the status from my perspective:

1. A workaround already exists where a user can enumerate the keys or values of a dictionary without unnecessary allocations (described in #249).
2. The ideal updated implementation for the `Keys` and `Values` properties is not possible due to the breaking changes policy for the library (described in #246).
3. This pull request increases the memory overhead for dictionary instances, and the result is still not as efficient as the original workaround.

Therefore, my recommendation is this pull request not be merged, but instead address the underlying concern as a documentation issue (#249 was created for this).

**Comment by ellismg** [comment]
@mtrofin and I discussed what to do here in person.  Some of his initial investigation showed an improvement in scenarios and it was not clear that the impact of the increased class size was problematic.

However, we have a desire to run more extensive End-To-End scenarios based on Roslyn.  At this point, it's not straight forward for us to do this ourselves, let alone in a way that the community could also participate in and so for now we're going to close this.

At some point, we may revisit it or we may just decide that #249 is sufficient.

**Pull request closed without merging**
