### PR TITLE
Update System.Xml.ReaderWriter to use System.Threading.Tasks.Extensions

### PR DESCRIPTION
**Pull request by stephentoub**
ReaderWriter had been using an internal version of ValueTask.  Now that we have it public and published in the System.Threading.Tasks.Extensions library, switch over to using it.

(I had to update the package validation to today's build, as it was the first build to contain the new assembly. @dagood, can you verify I did it correctly?)

### CODE REVIEW

**Comment by stephentoub** [comment]
@mmitche, FYI, on this and other PRs, Ubuntu Debug Build and Test seems to be having problems ("hung process")

**Comment by dagood** [comment]
@stephentoub That looks right to me, thanks for asking.

@weshaggard Currently `UpdatePrereleaseDependencies` is the only thing available to upgrade these until https://github.com/dotnet/corefx/pull/4926 is merged. (Pending review.) You're right that the new target shouldn't make that change.

**Comment by stephentoub** [comment]
@dotnet-bot Test Innerloop Ubuntu Debug Build and Test please (Jenkins failure)

**Comment by stephentoub** [comment]
@dotnet-bot Test Innerloop Ubuntu Debug Build and Test please (Jenkins failure)

**Comment by stephentoub** [comment]
@dotnet-bot Test Innerloop Ubuntu Debug Build and Test please (lots of disk-related failures)

**Pull request merged**
