### PR TITLE
Add a retry to an EventLog test on Win7

### PR DESCRIPTION
**Pull request by stephentoub**
Hopefully fixes https://github.com/dotnet/corefx/issues/39389

### CODE REVIEW

**Comment by danmosemsft** [comment]
You beat me to it 😃 What about in ClearLog_LogExists_Success()? Every other access to `Entries.Count` is already protected by the retry.

**Comment by stephentoub** [comment]
> What about in ClearLog_LogExists_Success()?

Don't know. If it warrants it, please submit a PR for it, too. :)

If every call to Count is broken without this, shouldn't we be fixing Count?

**Comment by danmosemsft** [comment]
> If every call to Count is broken without this, shouldn't we be fixing Count?

You're right that so far, we've worked around this flakiness with these test retries. In retrospect we could possibly have added retries in the EventLog code itself instead, but that could also potentially introduce other problems (?) and the issue seems to be with Windows 7, which will not be in support for much longer.

**Comment by stephentoub** [comment]
>  but that could also potentially introduce other problems (?) and the issue seems to be with Windows 7

Understood.  It's just that our adding retries to fix flakiness only helps our tests, not customer code hitting the same flakiness.  If it's a product bug, we should be fixing the product bug, not hacking around it in tests.  As you say, there may be reasons we're not doing that, but... it feels wrong.

**Comment by danmosemsft** [comment]
Agreed, and the way we got here is bit by bit, not a conscious decision. Plus, we have been making the assumption that the same problem exists in .NET Framework and has done for years, so perhaps our experience in the tests is not typical - or customers are used to retrying.

**Pull request merged**
