### PR TITLE
[WIP] Vector.SquareRoot Test Precision

### PR DESCRIPTION
**Pull request by mellinoe**
Don't merge or review yet -- just trying to see what happens in the ARM run for now.

### CODE REVIEW

**Comment by danmosemsft** [comment]
@joperezr is there a way to request ARM ILC in CI here? This reltaes to https://github.com/dotnet/corefx/issues/21261

**Comment by danmosemsft** [comment]
May have to check it in .

**Comment by joperezr** [comment]
> @joperezr is there a way to request ARM ILC in CI here? This reltaes to #21261

No, it's not possible but you could definitely can send a private run to Helix with these tests for ARM. @mellinoe  let me know if you need help doing that.

**Comment by danmosemsft** [comment]
@mellinoe this still needs resolving. Why not add logging and check it in?

**Pull request closed without merging**
