### PR TITLE
Add netcore50 configuration to System.Net.Http

### PR DESCRIPTION
**Pull request by mellinoe**
This includes a bit of new platform-specific code for System.Net.Http, as this library is built on top of WinRT for .NET Native / UWP.

I opened #5525 and #5523 as trackers for existing issues in the code/project files.

NOTE: We still need to do some major cleanup of the code to bring it in line with the style guidelines. I would like to leave that as a separate work item. I did some very minor cleanup before bringing the code out from our internal repository.

@davidsh , @CIPop , @weshaggard

### CODE REVIEW

**Comment by davidsh** [comment]
cc: @stephentoub

**Comment by stephentoub** [comment]
@dotnet-bot test this please

**Comment by davidsh** [comment]
>NOTE: We still need to do some major cleanup of the code to bring it in line with the style guidelines. I would like to leave that as a separate work item. I did some very minor cleanup before bringing the code out from our internal repository.

The current #5525 is really about a few files being moved to Common as well as reconciling duplicate cookie source code.

The other aspects of this PR such as style fixes (i.e. using underscores for private field name, etc.) could be done later.  But I would suggest #5525 get re-titled to be a little more generalized to include this work as well.

Otherwise, LGTM.

**Comment by weshaggard** [comment]
LGTM

**Comment by davidsh** [comment]
CI Failure: http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/centos7.1_debug_prtest/1137/

**Comment by davidsh** [comment]
Test  Innerloop CentOS7.1 Debug Build and Test

**Comment by mellinoe** [comment]
Thanks for the review. I've re-titled #5525 and added more description as you suggested, @davidsh . Going to merge this in now as the CentOS CI has cooperated :smile: .

**Pull request merged**
