### PR TITLE
Enable Pipes RunAsClient test dependent on package update

### PR DESCRIPTION
**Pull request by ianhays**

### CODE REVIEW

**Comment by stephentoub** [comment]
Looks like there's still an issue with the tests on macOS:
```
System.IO.Pipes.Tests.NamedPipeTest_RunAsClient.RunAsClient_Unix [FAIL]
        Assert.True() Failure
        Expected: True
        Actual:   False
        Stack Trace:
           /Users/dotnet-bot/j/workspace/dotnet_corefx/master/osx_debug_prtest/src/Common/tests/System/Diagnostics/RemoteExecutorTestBase.cs(170,0): at System.Diagnostics.RemoteExecutorTestBase.RemoteInvokeHandle.Dispose()
           /Users/dotnet-bot/j/workspace/dotnet_corefx/master/osx_debug_prtest/src/System.IO.Pipes/tests/NamedPipeTests/NamedPipeTest.RunAsClient.cs(52,0): at System.IO.Pipes.Tests.NamedPipeTest_RunAsClient.RunAsClient_Unix()
```
and
```
System.IO.Pipes.Tests.NamedPipeTest_RunAsClient.RunAsClient_Unix [FAIL]
        Assert.Equal() Failure
        Expected: 42
        Actual:   134
        Stack Trace:
  Discovering: System.Numerics.Vectors.Performance.Tests
           /Users/dotnet-bot/j/workspace/dotnet_corefx/master/osx_release_prtest/src/Common/tests/System/Diagnostics/RemoteExecutorTestBase.cs(164,0): at System.Diagnostics.RemoteExecutorTestBase.RemoteInvokeHandle.Dispose()
           /Users/dotnet-bot/j/workspace/dotnet_corefx/master/osx_release_prtest/src/System.IO.Pipes/tests/NamedPipeTests/NamedPipeTest.RunAsClient.cs(53,0): at System.IO.Pipes.Tests.NamedPipeTest_RunAsClient.RunAsClient_Unix()
```

**Comment by ianhays** [comment]
huh... that's odd. It looks like the actual RemoteInvoke call is timing out or returning the incorrect exit code.

I can't repro this on my OSX machine or Ubuntu machine. Any ideas on investigation/potential issues with the test that I missed?

**Comment by stephentoub** [comment]
> is timing out or returning the incorrect exit code

An exit code of 134 suggests that the process encountered a SIGABORT and was killed.

**Comment by karelz** [comment]
@ianhays any update here?

**Comment by karelz** [comment]
@ianhays ping again?

**Comment by ianhays** [comment]
@karelz no update. I'll just close this PR and re-open when I get the chance to investigate the failure.

**Pull request closed without merging**
