### PR TITLE
Tag ToTypeTest as a known issue on Windows

### PR DESCRIPTION
**Pull request by mmitche**
Issue #1303

### CODE REVIEW

**Comment by stephentoub** [comment]
Why is the file marked as binary file?

**Comment by mmitche** [comment]
Oh that's wacky, let me investigate.  It didn't do that when I did git diff locally.

**Comment by akoeplinger** [comment]
@stephentoub @mmitche that's because the file is in UTF16 like a lot of the other files in System.Xml. I'll raise an issue about making those consistent, as they caused issues with third-party tools as well (see gitter chat).

**Comment by mmitche** [comment]
@stephentoub @akoeplinger I can change the encoding in bulk right now unless there is another issue at hand.

**Comment by akoeplinger** [comment]
@mmitche raised https://github.com/dotnet/corefx/issues/1339 to discuss this further, I don't think we should do it as part of this PR.

**Comment by mmitche** [comment]
Okay sounds good.

**Comment by mmitche** [comment]
Anyways @stephentoub, this is the change:

 [Fact] 
54         [OuterLoop] 
55         [ActiveIssue(846, PlatformID.Linux | PlatformID.OSX)] 
56         +[ActiveIssue(1303, PlatformID.Windows)] 
57         public static void ToTypeTests() 
58         { 
59             RunTestCase(new ToTypeTests { Attribute = new TestCase { Name = "XmlConvert type conversion functions", Desc = "XmlConvert" } }); 
60         }

**Comment by stephentoub** [comment]
LGTM.  My only question is whether the previous ActiveIssue I added for Linux/OSX is actually the same problem; I hadn't realized this was failing on Windows as well.  But we can leave that for another day.

**Comment by mmitche** [comment]
Yeah I wasn’t sure and the issue doesn’t have any specificity, so I just added another tag.

**Pull request merged**
