### PR TITLE
SslStream override stream's async methods

### LINKED ISSUE #5488: SslStream ReadAsync/WriteAsync end up Sync
Symptom: https://github.com/aspnet/KestrelHttpServer/issues/569

`SslStream` doesn't override `Stream`'s `ReadAsync`/`WriteAsync` methods which means they call the default implementation which is a wrapper on `Stream`'s `BeginRead` and `EndRead` etc.

`BeginRead` eventually ends up calling the underlying stream's synchronous `Read` method.

If the stream it wraps is completely async; then its sync read may wait on a `.GetAwaiter().GetResult()` of its async read/write.

At which point you have Async->Sync->Async.Wait() and things go bad...

First guess would be `SslStream` should additionally override
```csharp
public override Task<int> ReadAsync(byte[] buffer, int offset, int count, CancellationToken cancellationToken)
{
    return _sslState.SecureStream.ReadAsync(buffer, offset, count, cancellationToken);
}

public override Task WriteAsync(byte[] buffer, int offset, int count, CancellationToken token)
{
    return _sslState.SecureStream.WriteAsync(buffer, offset, count, token);
}
```
but there may be more to it.

### PR DESCRIPTION
**Pull request by benaadams**
Rather than using Streams default implementation which end up calling the sync methods.

Resolves #5488

### CODE REVIEW

**Comment by stephentoub** [comment]
cc: @cipop, @davidsh

**Comment by stephentoub** [comment]
@benaadams, thanks, but does this even compile?  The type returned from _sslState.SecureStream doesn't appear to actually derive from Stream, nor does it expose ReadAsync/WriteAsync methods.

**Comment by benaadams** [comment]
O_o

**Comment by benaadams** [comment]
Obviously need some sleep

**Comment by stephentoub** [comment]
:smile: Thanks for trying, regardless.

**Pull request closed without merging**
