### PR TITLE
Clean up ValueTask code in preparation for copying it to coreclr

### PR DESCRIPTION
**Pull request by stephentoub**
Contributes to #21753 

@weshaggard, we should have deleted the temporary, hidden member previously, but neglected to do so.  No one should be using it.  Concerns about removing it?

### CODE REVIEW

**Comment by weshaggard** [comment]
>@weshaggard, we should have deleted the temporary, hidden member previously, but neglected to do so. No one should be using it. Concerns about removing it?

How do we know if there aren't any existing binaries that have references to this member? Especially if the compiler was generating calls to it for people?

**Comment by stephentoub** [comment]
> Especially if the compiler was generating calls to it for people?

No RTM compiler ever shipped targeting this.

> How do we know if there aren't any existing binaries that have references to this member?

We don't.

**Comment by weshaggard** [comment]
In general we don't ever remove public API's after they ship, even if they were hidden from intellisense. I would like more folks on @dotnet/fxdc to agree to removing this beyond just myself before moving forward with this.

**Comment by stephentoub** [comment]
> I would like more folks on @dotnet/fxdc to agree to removing this beyond just myself before moving forward with this.

Ok.  I'll remove that part of this PR and open an issue for it.

**Pull request merged**
