### PR TITLE
Revert "Merge pull request #18043 from safern/CopyConfigFile"

### PR DESCRIPTION
**Pull request by danmosemsft**
This reverts commit 8b3c00781a82d1239dc2e6da8d443d491add8a39, reversing
changes made to f9bca96f57feeb1092b2245377e8f66436c9ddfc.

See whether this fixes OSX or not.

@mmitche @safern

### CODE REVIEW

**Comment by danmosemsft** [comment]
relates to #18006

**Comment by danmosemsft** [comment]
Yes - init tools succeeded! Let's merge that when it finishes.

**Comment by danmosemsft** [comment]
Merging without CR as it's a build break fix

**Comment by safern** [comment]
Was this the build tools version update? Do we know why updating the build tools broke init-tools on OSX?

**Pull request merged**
