### PR TITLE
Fix NRE when context value is null in method Save from Principal class

### PR DESCRIPTION
**Pull request by Marusyk**
Related to #41655

Please review.
Thank you in advance

### CODE REVIEW

**Review by scalablecory — APPROVED** [review]

**Comment by danmosemsft** [comment]
Thank you @Marusyk !

**Comment by danmosemsft** [comment]
Would you consider adding a quick unit test?

**Comment by Marusyk** [comment]
Yes, I will try

**Comment by Marusyk** [comment]
I've added a simple test. It is cover only the changed logic.

**Review by safern — APPROVED** [review]

**Review by danmoseley — APPROVED** [review]

**Pull request merged**
