### PR TITLE
Fix NumberFormatInfoNumberGroupSizes failed test

### LINKED ISSUE #23628: Test failure: System.Globalization.Tests.NumberFormatInfoNumberGroupSizes/NumberGroupSizes_Get(format: NumberFormatInfo { CurrencyDecimalDigits = 2, CurrencyDecimalSeparator = \".\", CurrencyGroupSeparator ...
Opened on behalf of @Jiayili1

The test `System.Globalization.Tests.NumberFormatInfoNumberGroupSizes/NumberGroupSizes_Get(format: NumberFormatInfo { CurrencyDecimalDigits = 2, CurrencyDecimalSeparator = \".\", CurrencyGroupSeparator ...` has failed.

Assert.Equal() Failure
    Expected: Int32[] [3, 2]
    Actual:   Int32[] [3]

        Stack Trace:

        
Build : Master - 20170829.01 (Core Tests)
Failing configurations:
- RedHat.69.Amd64-x64
  - Release
  - Debug

Detail: https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Fcli~2F/build/20170829.01/workItem/System.Globalization.Tests/analysis/xunit/System.Globalization.Tests.NumberFormatInfoNumberGroupSizes~2FNumberGroupSizes_Get(format:%20NumberFormatInfo%20%7B%20CurrencyDecimalDigits%20=%202,%20CurrencyDecimalSeparator%20=%20%5C%22.%5C%22,%20CurrencyGroupSeparator%20...

### PR DESCRIPTION
**Pull request by tarekgh**
Fixes #23628

### CODE REVIEW

**Comment by tarekgh** [comment]
test OSX x64 Debug Build please

```
Error during cleanup: java.io.IOException: remote file operation failed: /Users/dotnet-bot/j/workspace/dotnet_corefx/master/osx-TGroup_netcoreapp+CGroup_Debug+AGroup_x64+TestOuter_false_prtest at hudson.remoting.Channel@54f2d0ef:JNLP4-connect connection from 131.107.19.215/131.107.19.215:57456: hudson.remoting.ChannelClosedException: channel is already closed
```

**Comment by tarekgh** [comment]
@dotnet/dnceng could you please check OSX build failures?

**Comment by mmitche** [comment]
@tarekgh Machine disconnected.  Rebooted it.  @dotnet-bot test OSX x64 Debug Build

**Comment by tarekgh** [comment]
Thank you @stephentoub and @mmitche

**Pull request merged**
