### PR TITLE
Find test builds files deeper in file structure.

### PR DESCRIPTION
**Pull request by StephenBonikowsky**
In WCF repo many of our test projects are more than one level below the 'tests' directory.
If this doesn't break anything in corefx could we take this change?

### CODE REVIEW

**Comment by StephenBonikowsky** [comment]
@sokket @weshaggard

**Comment by weshaggard** [comment]
LGTM if CI is green.

**Comment by StephenBonikowsky** [comment]
All the checks failed, having trouble getting Jenkins to load the logs for me but it looks like test projects were discovered and running but the common failure is...
error MSB4015: The build stopped unexpectedly because the "ReusableLogger" logger failed unexpectedly during shutdown.

Not sure if that has anything to do with this change?

**Comment by weshaggard** [comment]
It isn't clear to me if this is caused by your change either but it is possible that it pulled in more tests projects now that aren't working.

**Comment by weshaggard** [comment]
@dotent-bot test this please

**Comment by mellinoe** [comment]
I think this failure is due to a new .builds file being picked up. But it seems like this new builds file is 1) faulty and 2) unnecessary. The project it includes is already included by a builds file one directory up. It also doesn't specify a correct OSGroup for the project it includes, so it tries to compile a bad configuration. We should just delete that builds file.

corefx\src\System.Net.Sockets\tests\PerformanceTests\System.Net.Sockets.Async.Performance.Tests.builds

**Comment by StephenBonikowsky** [comment]
Updated and removed System.Net.Sockets.Async.Performance.Tests.builds

**Comment by mellinoe** [comment]
It seems like there are still some extra .builds files which are in some System.Net subdirectories. I think we should just delete those and leave a single .builds file directly under .../tests/.

**Comment by StephenBonikowsky** [comment]
Found some others as well, also, without this change I don't think `"corefx\src\System.ServiceProcess.ServiceController\tests\System.ServiceProcess.ServiceController.Tests\System.ServiceProcess.ServiceController.Tests.builds"` would have been found.

**Comment by StephenBonikowsky** [comment]
Something looks strange with System.Data.SqlClient and System.Net.Http.WinHttpHandler.
In my local file structure I have a builds file for each of those but after pushing it here I only see the one for System.Net.Http.WinHttpHandler and the one I added for System.Data.SqlClient isn't here.

**Comment by weshaggard** [comment]
Just so I understand where the builds files you deleted referencing projects that were already in higher level builds files? As I would expect nested builds files to work just fine assuming there weren't conflicts/duplication.

**Comment by StephenBonikowsky** [comment]
All of them except the two under System.Net.Http.WinHttpHandler
```
System.Net.Http.WinHttpHandler/tests/FunctionalTests/System.Net.Http.WinHttpHandler.Functional.Tests.builds 
System.Net.Http.WinHttpHandler/tests/UnitTests/System.Net.Http.WinHttpHandler.Unit.Tests.builds
```

These two were the only two that did not already have a .builds file one level higher that already included their respective .csproj files.
I deleted them and added the .builds file one level up to be consistent with all the other ones.
I'm happy to undo that if you wish.

**Comment by weshaggard** [comment]
Yes lets leave the nested builds as they were as long as they were functioning correctly.

**Comment by StephenBonikowsky** [comment]
ok

**Comment by StephenBonikowsky** [comment]
Reverted the previous change to the System.Net.Http.WinHttpHandler builds files.

**Comment by weshaggard** [comment]
Assuming all the tests projects in the builds files you are removing exist in another builds file LGTM. Although there does seem to be one more related failure on windows.

**Comment by StephenBonikowsky** [comment]
Looks to me like the following test projects have not been getting run since PR #6572 replaced `"*\test*\**\*.csproj"` with `"*\tests\*.builds"
`
- System.Net.Http.WinHttpHandler.Functional.Tests
- System.Net.Http.WinHttpHandler.Unit.Tests
- System.ServiceProcess.ServiceController.Tests

The current Windows failures look related to the System.Net.Http.WinHttpHandler.Functional.Tests and perhaps is showing a test related failure that is occurring since it last ran?

> Compile Error
> 
> error CS7036: There is no argument given that corresponds to the required formal parameter 'hops' of 'HttpTestServers.RedirectUriForDestinationUri(bool, int, Uri, int)' [D:\j\workspace\windows_nt_de---06b7984d\src\System.Net.Http.WinHttpHandler\tests\FunctionalTests\System.Net.Http.WinHttpHandler.Functional.Tests.csproj]

**Comment by weshaggard** [comment]
@davidsh @CIPop do those networking failures look familiar?

**Comment by davidsh** [comment]
If you're talking about this weird compiler error:

>error CS7036: There is no argument given that corresponds to the required formal parameter 'hops' of 'HttpTestServers.RedirectUriForDestinationUri(bool, int, Uri, int)' [D:\j\workspace\windows_nt_re---37265eab\src\System.Net.Http.WinHttpHandler\tests\FunctionalTests\System.Net.Http.WinHttpHandler.Functional.Tests.csproj]
Indication 1 

Then it looks like this PR needs to be rebased

**Comment by davidsh** [comment]
Looking at this again, there seems to be build problem with the CI system.  I checked in a PR yesterday that merged clean.

And yet, it appears like the CI system is not building src/System.Net.Http.WinHttpHandler/tests/FunctionalTests directory.  Because building that now shows the compiler error.

I will submit a PR to fix these tests. But I don't understand why they are not building from the root.  This would have been caught otherwise.

**Comment by davidsh** [comment]
cc: @stephentoub

**Comment by StephenBonikowsky** [comment]
@davidsh look at my earlier comment, without the change to src/tests.builds in this PR that test project has not been getting built the last few weeks.

**Comment by davidsh** [comment]
@dotnet-bot Test Innerloop Windows_NT Release Build and Test

**Comment by davidsh** [comment]
@dotnet-bot Test Innerloop Windows_NT Debug Build and Test

**Comment by StephenBonikowsky** [comment]
Looks like it is good to go now?

**Comment by davidsh** [comment]
LGTM

**Pull request merged**
