### PR TITLE
CI test PR

### PR DESCRIPTION
**Pull request by morganbr**
Change to test CI. No need to merge (unless you really want one more expression-bodied property)

### CODE REVIEW

**Comment by morganbr** [comment]
@dotnet-bot test Windows NetCoreAppAOT x64 Release Build

**Comment by morganbr** [comment]
@dotnet-bot test Windows NetCoreAppAOT x64 Release Build

**Comment by morganbr** [comment]
@dotnet-bot test Windows NetCoreAppAOT x64 Release Build

**Comment by stephentoub** [comment]
@morganbr, can this be closed?

**Comment by morganbr** [comment]
I'll reopen when I get back to this.

**Pull request closed without merging**
