### PR TITLE
Delete unnecessary ApiCompat baselines

### PR DESCRIPTION
**Pull request by MichalStrehovsky**
These should no longer be necessary.

### CODE REVIEW

**Comment by stephentoub** [comment]
https://ci3.dot.net/job/dotnet_corefx/job/master/job/windows-TGroup_all+CGroup_Debug+AGroup_x64+TestOuter_false_prtest/19075/
```
D:\j\workspace\windows-TGrou---0d2c9ac4\.packages\microsoft.dotnet.apicompat\1.0.0-beta.18578.2\build\Microsoft.DotNet.ApiCompat.targets(69,5): error : MembersMustExist : Member 'System.Math.ILogB(System.Double)' does not exist in the implementation but it does exist in the contract. [D:\j\workspace\windows-TGrou---0d2c9ac4\src\System.Runtime.Extensions\src\System.Runtime.Extensions.csproj]
D:\j\workspace\windows-TGrou---0d2c9ac4\.packages\microsoft.dotnet.apicompat\1.0.0-beta.18578.2\build\Microsoft.DotNet.ApiCompat.targets(69,5): error : MembersMustExist : Member 'System.MathF.ILogB(System.Single)' does not exist in the implementation but it does exist in the contract. [D:\j\workspace\windows-TGrou---0d2c9ac4\src\System.Runtime.Extensions\src\System.Runtime.Extensions.csproj]
D:\j\workspace\windows-TGrou---0d2c9ac4\.packages\microsoft.dotnet.apicompat\1.0.0-beta.18578.2\build\Microsoft.DotNet.ApiCompat.targets(83,5): error : ApiCompat failed for 'D:\j\workspace\windows-TGrou---0d2c9ac4\artifacts\bin\System.Runtime.Extensions\uapaot-Windows_NT-Debug\System.Runtime.Extensions.dll' [D:\j\workspace\windows-TGrou---0d2c9ac4\src\System.Runtime.Extensions\src\System.Runtime.Extensions.csproj]
```

**Comment by stephentoub** [comment]
Ah, I see you already submitted a fix :)

**Comment by stephentoub** [comment]
@dotnet-bot test UWP NETNative x86 Release Build please
@dotnet-bot test Packaging All Configurations x64 Debug Build please
@dotnet-bot test UWP NETNative x86 Release Build please

**Comment by MichalStrehovsky** [comment]
I pushed the change over to Project N today - (dotnet/corert#6674) - we should be able to merge this after the next ProjectNTfs update.

**Comment by MichalStrehovsky** [comment]
@dotnet-bot test this please

**Pull request merged**
