### PR TITLE
Merging branch dev/eng to master

### PR DESCRIPTION
**Pull request by joperezr**
related issue: https://github.com/dotnet/corefx/issues/15135

Merging branch dev/eng into master

cc: @weshaggard @chcosta @ericstj @mellinoe @karajas

### CODE REVIEW

**Comment by joperezr** [comment]
@dotnet-bot test Innerloop OSX Release Build and Test please
@dotnet-bot test Innerloop Ubuntu14.04 Release Build and Test please

**Comment by weshaggard** [comment]
Looks like we have some test hanging https://ci.dot.net/job/dotnet_corefx/job/master/job/ubuntu14.04_release_prtest/2134/consoleFull which is still running.

**Comment by joperezr** [comment]
yeah I saw that as well, I was about to requeue the build. I've seen that occasionally happen even in master, perhaps the build machine lost connection with Helix?

**Comment by joperezr** [comment]
@dotnet-bot test Innerloop Ubuntu14.04 Release Build and Test please

**Pull request merged**
