### PR TITLE
Add System.Resources.ResourceWriter sources and tests.

### PR DESCRIPTION
**Pull request by jhendrixMSFT**
Add System.Resources.ResourceWriter sources its tests.

### CODE REVIEW

**Comment by joshfree** [comment]
The tests are not running as part of the build.

At least one part of that problem is the assembly name isn't matching the wildcard search used to discover tests

System.Resources.ResourceWriterTests.dll should be renamed to System.Resources.ResourceWriter.Tests.dll

Can you please fix this and update the pull request?

**Comment by joshfree** [comment]
See here: http://corefx-ci.cloudapp.net/jenkins/job/dotnet_corefx_windows_prtest/166/console

**Comment by jhendrixMSFT** [comment]
Good catch, the assembly renaming was inadvertent.  I must have had a stale copy as the tests were running on my machine.  I've updated the test csproj file with the correct assembly name.

**Comment by joshfree** [comment]
Also can you squash your commit history please?  This should show up as 1 commit and not  4+

**Comment by jhendrixMSFT** [comment]
History has been cleaned up.

**Comment by joshfree** [comment]
10:16:04 Building remotely on Azure0120094403 (windows-azure)FATAL: java.io.IOException: Connection aborted: org.jenkinsci.remoting.nio.NioChannelHub$MonoNioTransport@141a5a3[name=Azure0120094403]
10:16:23 hudson.remoting.RequestAbortedException: java.io.IOException: Connection aborted: org.jenkinsci.remoting.nio.NioChannelHub$MonoNioTransport@141a5a3[name=Azure0120094403]
10:16:23 	at hudson.remoting.Request.abort(Request.java:295)
10:16:23 	at hudson.remoting.Channel.terminate(Channel.java:814)
10:16:23 	at hudson.remoting.Channel$2.terminate(Channel.java:491)
10:16:23 	at hudson.remoting.AbstractByteArrayCommandTransport$1.terminate(AbstractByteArrayCommandTransport.java:72)

....

**Comment by joshfree** [comment]
test this please

**Comment by joshfree** [comment]
as a side note, is there an easier way to re-run a failed Jenkins job than "test this please" which dirties the PR history on GitHub?

**Comment by joshfree** [comment]
:+1: now that Jenkins has passed.

**Pull request merged**
