### PR TITLE
Update buildtools.

### PR DESCRIPTION
**Pull request by Priya91**
Contains changes for native shim local copy.

cc @stephentoub @weshaggard 
#7081

### CODE REVIEW

**Comment by Priya91** [comment]
@dotnet-bot Test outerloop osx debug

**Comment by Priya91** [comment]
@dotnet-bot Test outerloop Ubuntu14.10 debug

**Comment by stephentoub** [comment]
Is that the new format for build tools numbering? If so, LGTM.

**Comment by Priya91** [comment]
@stephentoub Yeah..

**Comment by Priya91** [comment]
@dotnet-bot Test outerloop Ubuntu14.04 debug

**Comment by stephentoub** [comment]
Thanks, @Priya91.  Looks like this addressed the shims issue.  A few tests failed, but they're all known issues unrelated to your change.

**Comment by stephentoub** [comment]
Test outerloop osx debug please

**Comment by stephentoub** [comment]
test Outerloop OSX Debug please

**Comment by stephentoub** [comment]
The OSX tests appear to be hanging in the NetworkInformation tests.  Same thing happened the first time the outerloop OSX tests ran... hung in what appears to be the same place.

**Comment by Priya91** [comment]
> The OSX tests appear to be hanging in the NetworkInformation tests. Same thing happened the first time the outerloop OSX tests ran... hung in what appears to be the same place.

This does not repro locally on Mac OSX. Retriggering the run again.

**Comment by Priya91** [comment]
@dotnet-bot Test outerloop OSX debug

**Comment by Priya91** [comment]
Outerloop OSX passed. Merging.

**Pull request merged**
