### PR TITLE
Update UAP pinvoke baselines (#22516)

### PR DESCRIPTION
**Pull request by pjanotti**
* readding 1 API and updating buildtools

* removing more APIs that were added

### CODE REVIEW

**Comment by danmosemsft** [comment]
@dotnet-bot test this please (let's see if we get more legs?)

**Comment by danmosemsft** [comment]
Nope...

**Comment by danmosemsft** [comment]
We should wait on the UWP CI legs to come up before we merge this

**Comment by pjanotti** [comment]
I subscribed to https://github.com/dotnet/dotnet-ci/pull/733 and will request another test run here when there is an update on that one.

**Comment by joshfree** [comment]
@dotnet-bot test this please

**Comment by joshfree** [comment]
Nope...

**Comment by danmosemsft** [comment]
aha! new legs

**Comment by pjanotti** [comment]
All issues are not related to the changes in this PR. Tracking issues for the failures:
#21720 
#22492 
#22493

**Comment by pjanotti** [comment]
@dotnet-bot test this please (checking Linux x64 that did not complete)

**Pull request merged**
