### PR TITLE
Remove "UnsupportedPlatforms" metadata

### PR DESCRIPTION
**Pull request by ellismg**
Since #6572 was merged, we only build test projects for the platforms
they test.  This means the UnsupportedPlatforms metadata is no longer
needed (instead using the .builds file to control when the project is
built is the right thing to do).

Leverage this in run-test.sh, we now simply loop over all the tests in
the relevent folders under bin/tests, depending on the platform in
question.

### CODE REVIEW

**Comment by ellismg** [comment]
/cc @sokket @weshaggard 
FYI @Chrisboh

**Comment by weshaggard** [comment]
cc FYI @Priya91 @joperezr

**Comment by weshaggard** [comment]
LGTM

For the cases were you removed them from the csproj files could you please have a look at the associated builds file to make sure the filtering looks correct.

**Comment by ellismg** [comment]
I'm going to add some code to run-test.sh to handle the case where an path is passed to corefx-tests that is a platform specific test folder (like CI does) instead of the root of the test folder (which is what we want going forward).

After this lands, I'll update the build definitions.

**Comment by Priya91** [comment]
LGTM

**Comment by Priya91** [comment]
@ellismg Doesn't the netci.groovy have to be updated? It has this now,

```
--corefx-tests \${WORKSPACE}/bin/tests/${osGroup}.AnyCPU.${configurationGroup} \\
```

**Comment by Chrisboh** [comment]
LGTM

**Comment by ellismg** [comment]
> @ellismg Doesn't the netci.groovy have to be updated?

Yes.  I'm fixing the script locally to work with and without the changes to netci.groovy and I will update netci.groovy as well.

**Pull request closed without merging**
