### PR TITLE
Preserve more environment variables during tests remote execution

### PR DESCRIPTION
**Pull request by tarekgh**

### CODE REVIEW

**Comment by tarekgh** [comment]
https://github.com/dotnet/corefx/issues/38768

@BruceForstall @ericstj @ViktorHofer could you please have a quick look?

**Comment by tarekgh** [comment]
> As a nit: On non-Windows, the variables are case-sensitive (I believe in all cases), so comparing with "IgnoreCase" might keep more than strictly necessary, but that doesn't seem like a problem.

Yes I thought about it while coding it, and I preferred to make it case insensitive because it will not hurt to include any such variables anyway and maybe in the future, we may run into some variable with different casing. thanks for your review.

**Comment by tarekgh** [comment]
The failing CI looks already tracked with the issue https://github.com/dotnet/corefx/issues/38824

**Comment by ViktorHofer** [comment]
Thanks Tarek. Lgtm

**Pull request merged**
