### PR TITLE
Remove unused legacy data contract json serializer code

### PR DESCRIPTION
**Pull request by khdang**
We have switched to share data contract json serializer with NetNative instead of the implementation based on JavaScriptSerializer in https://github.com/dotnet/corefx/commit/06d51d6f49eb41a71810833c26c3eb4a89a73df7. This change is to remove the remaining unused code.

cc: @mellinoe @SGuyGe @shmao @zhenlan

### CODE REVIEW

**Comment by SGuyGe** [comment]
LTGM

**Comment by shmao** [comment]
LGTM. Can you please confirm if the NetNative csproj builds successfully with the changes?

**Comment by stephentoub** [comment]
@dotnet-bot test this please

**Comment by stephentoub** [comment]
LGTM

**Comment by khdang** [comment]
@shmao I've confirmed that the csproj for NetNative builds successfully. Thanks.

**Pull request merged**
