### PR TITLE
Fixed netfx System.Linq.Tests fails

### PR DESCRIPTION
**Pull request by AlexRadch**
See https://github.com/dotnet/corefx/issues/28136

### CODE REVIEW

**Comment by AlexRadch** [comment]
How to make next code correct on netfx?
```cs
// should be replaced on something like #if netfx
#if true
                     "Append",
                     "Prepend",
#endif
```
I did not find any documentation about conditional coding at https://github.com/dotnet/corefx/blob/master/Documentation/project-docs/developer-guide.md
Can be the documentation supplement with conditional coding?

**Comment by stephentoub** [comment]
What is the problem this is fixing?  How is this related to a non-English culture?

**Comment by AlexRadch** [comment]
> What is the problem this is fixing? How is this related to a non-English culture?

It is not related to non-English Windows. It is related to netfx.

**Comment by AlexRadch** [comment]
I wanted to use conditional compilation. Something like `#if netfx`. Advised to use `PlatformDetection.IsFullFramework`

**Comment by stephentoub** [comment]
> It is not related to non-English Windows. It is related to netfx.

The issue you linked to is about non-English.

And as far as I can tell, this test is passing in our CI system.

So I'm confused.  What is the problem with it that's being fixed?

**Comment by stephentoub** [comment]
Ah, I see, these methods were added to Enumerable in .NET 4.7.1.

**Comment by AlexRadch** [comment]
> The issue you linked to is about non-English.

When I created https://github.com/dotnet/corefx/issues/28136 issue I think that all fails are related to netfx on non-English Windows.
System.Linq.Tests fails is not related to non-English Windows but to netfx only.

**Pull request merged**
