### PR TITLE
Make DisableMediaInsertionPrompt to be private struct to match CoreLib

### PR DESCRIPTION
**Pull request by jkotas**

### CODE REVIEW

**Comment by danmosemsft** [comment]
@dotnet-bot test OSX x64 Debug Build please (`System.Private.Uri.Functional.Tests` segfault... need dumpling)

**Comment by jkotas** [comment]
@dotnet-bot test Windows x64 Debug Build please (timeout)

**Comment by jkotas** [comment]
@dotnet-bot test Linux x64 Release Build please

**Comment by danmosemsft** [comment]
@dotnet/dnceng what does this mean --
```
Setting status of 5d3ef873b41d807ca07c7851555a90aa5f044e0b to FAILURE with url https://ci3.dot.net/job/dotnet_corefx/job/master/job/linux-TGroup_netcoreapp+CGroup_Release+AGroup_x64+TestOuter_false_prtest/2636/ and message: 'Build finished. '
Using context: Linux x64 Release Build
Exception: null
org.jenkinsci.plugins.workflow.steps.FlowInterruptedException
	at org.jenkinsci.plugins.workflow.cps.CpsBodyExecution.cancel(CpsBodyExecution.java:242)
	at org.jenkinsci.plugins.workflow.steps.BodyExecution.cancel(BodyExecution.java:76)
	at org.jenkinsci.plugins.workflow.cps.steps.ParallelStepExecution.stop(ParallelStepExecution.java:66)
	at org.jenkinsci.plugins.workflow.cps.CpsThread.stop(CpsThread.java:296)
	at org.jenkinsci.plugins.workflow.cps.CpsBodyExecution$2.onSuccess(CpsBodyExecution.java:260)
	at org.jenkinsci.plugins.workflow.cps.CpsBodyExecution$2.onSuccess(CpsBodyExecution.java:247)
	at org.jenkinsci.plugins.workflow.cps.CpsFlowExecution$4$1.run(CpsFlowExecution.java:744)
	at org.jenkinsci.plugins.workflow.cps.CpsVmExecutorService$1.run(CpsVmExecutorService.java:35)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at hudson.remoting.SingleLaneExecutorService$1.run(SingleLaneExecutorService.java:112)
	at jenkins.util.ContextResettingExecutorService$1.run(ContextResettingExecutorService.java:28)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Finished: ABORTED
```
https://ci3.dot.net/job/dotnet_corefx/job/master/job/linux-TGroup_netcoreapp+CGroup_Release+AGroup_x64+TestOuter_false_prtest/2636/consoleText

**Comment by danmosemsft** [comment]
@dotnet-bot test Linux x64 Release Build please

**Comment by Chrisboh** [comment]
@mmitche have you seen this before?

**Comment by mmitche** [comment]
@Chrisboh @danmosemsft  I don't think that is the error.  A few lines prior:

[suse.422.amd64.Open] Will try again after 5 min 0 sec
**Cancelling nested steps due to timeout**
[Pipeline] [suse.422.amd64.Open] // waitUntil
[Pipeline] [Ubuntu.1604.Amd64.Open] // waitUntil
[Pipeline] [Ubuntu.1604.Amd64.Open] }
[Ubuntu.1604.Amd64.Open] Failed in branch Ubuntu.1604.Amd64.Open
[Pipeline] [suse.422.amd64.Open] }
[suse.422.amd64.Open] Failed in branch suse.422.amd64.Open

Helix never completed the test runs

**Comment by mmitche** [comment]
@Chrisboh Maybe this was related to Chad's db cleanup?

**Pull request merged**
