### PR TITLE
Stamp packagebaseline in release/1.1.0

### PR DESCRIPTION
**Pull request by ericstj**
This is a direct cherry-pick of the commits I made to master to enable WCF to pick up our package baseline.

/cc @StephenBonikowsky @weshaggard

### CODE REVIEW

**Comment by weshaggard** [comment]
LGTM

I assume you re-ran the packageindex update to ensure it matches what is in this branch.

**Comment by ericstj** [comment]
I've reviewed all the deletes to make sure we got all of them and reviewed the diff between the fork for 1.1.0 and this change: there were no other changes.

**Comment by ericstj** [comment]
@dotnet-bot test Innerloop CentOS7.1 Debug Build and Test

**Comment by ericstj** [comment]
@dotnet-bot test Innerloop CentOS7.1 Release Build and Test

**Pull request merged**
