### PR TITLE
Add support for IsDefaultAttribute on TypeDescriptor attributes

### PR DESCRIPTION
**Pull request by twsouthwick**
This adds a layer between `System.Attribute` and the TypeDescriptor attributes that expose `IsDefaultAttribute`, `Matches`, and `TypeId` as these are used extensively in the TypeDescriptor implementation.

@chlowell

### CODE REVIEW

**Comment by chlowell** [comment]
LGTM

**Comment by twsouthwick** [comment]
@dotnet-bot please test

**Comment by twsouthwick** [comment]
@weshaggard This is the PR I mentioned to you yesterday. You mentioned you'd rather not have another class in between the ComponentModel attributes and `System.Attribute` - would an interface be better? The only other option I can think of is using reflection, which is not very desirable

**Comment by weshaggard** [comment]
Can you point me at the code that calls tries to use these methods? 

While I think an internal interface would be better then a new public base type I have a feeling we are going to be causing some interesting compat issues with desktop. You guys should think through the scenarios a little here to make sure we aren't backing ourselves into a corner. The scenarios I"m thinking about is if someone compiles against the .NET Core contract and applies these attributes and tries running on desktop (which we would support via a facade) will the attributes be successfully interpreted? I think that is worth a test.

**Comment by twsouthwick** [comment]
Very good points @weshaggard. I wasn't thinking about exposing this stuff in the contracts due to possible compat issues, but we need a way to use them internally. Thus, no one would actually be able to override the methods if they're compiling against Core. There may be a compat issue I'm not seeing, but it seems like by keeping it an internal change (not in the contract), the facades will continue to work. We can definitely test that, though.

An example of the scenario this enables:

1. `AttributCollection[Type]` will return `null` if the attribute has not been added except under the following circumstances (in order) [source](https://github.com/twsouthwick/corefx/blob/is-default-attribute/src/System.ComponentModel.TypeConverter/src/System/ComponentModel/AttributeCollection.cs#L300-L324):
     1. There is a public static field with the name `Default`
     2. There is a public constructor with no args AND `IsDefaultAttribute()` returns true
2. There are members, such as `MemberDescriptor.DisplayName` that tries to call `AttributeCollection[Type]` and only uses the DisplayNameAttribute if it is not the default [source](https://github.com/twsouthwick/corefx/blob/is-default-attribute/src/System.ComponentModel.TypeConverter/src/System/ComponentModel/MemberDescriptor.cs#L261-L272)

I understand this is a weird design, but it's fairly pervasive so it would be easier, for now, to just mimic it to ensure the same behavior.

**Comment by twsouthwick** [comment]
@weshaggard I've switched it to use a private interface so there shouldn't be any compat concerns.

**Comment by weshaggard** [comment]
@twsouthwick yes that is more along the lines of what I was thinking.

**Pull request merged**
