### PR TITLE
Remove private reflection agaist RuntimeWrappedException constructor

### PR DESCRIPTION
**Pull request by jkotas**
RuntimeWrappedException constructor is public in CoreLib now. It can be called directly.

### CODE REVIEW

**Comment by stephentoub** [comment]
@dotnet/dnceng, Windows runs are again hanging, e.g. https://ci3.dot.net/job/dotnet_corefx/job/master/job/windows-TGroup_netcoreapp+CGroup_Debug+AGroup_x64+TestOuter_false_prtest/4772/ has been going for almost 10 hours.

**Comment by danmosemsft** [comment]
@dotnet-bot test Windows x64 Debug Build  (win7 timed out)
@dotnet-bot test Windows x64 release Build (win7 timed out)

**Comment by JonHanna** [comment]
Maybe I'm doing something silly, (and/or misidentifying the cause) but this seems to be causing unresolved project references when opening S.L.Expressions in Visual Studio.

**Comment by jkotas** [comment]
@JonHanna #25175 should fix it.

**Comment by JonHanna** [comment]
Ah good, I wasn't doing something silly. I like to keep that to the minimum amount required to remain modest 😄

**Pull request merged**
