### PR TITLE
Config ReaderQotas.MaxStringContentLength has no effect for some test…

### PR DESCRIPTION
**Pull request by imcarolwang**
… data on NetCore.

For wcf issue [#3408](https://github.com/dotnet/wcf/issues/3408)
@mconnew , @StephenBonikowsky .

### CODE REVIEW

**Comment by csturm83** [comment]
Would this be considered a breaking change, since it may now throw an exception where it previously didn't? If so, might be worth documenting/mentioning somewhere.

**Comment by csturm83** [comment]
Maybe falls in [Bucket 2](https://github.com/dotnet/corefx/blob/master/Documentation/coding-guidelines/breaking-changes.md#bucket-2-reasonable-grey-area)?

@buyaa-n @stephentoub

**Comment by mconnew** [comment]
If a customer explicitly specifies that the maximum string length is X, I can't imagine a scenario why they wish to depend on us allowing strings longer than X to be processed. The reader quotas are there to prevent a remote host from causing your process to allocate an excessive amount of memory and this capability not working is a problem as it removes a protection. The default value is int32.MaxValue so this code only has an effect if the customer has asked for it.

**Comment by csturm83** [comment]
I agree that it is probably worthwhile to bring back this code from .NET Framework. The protection it provides is a good thing. Also, MaxStringContentLength is not completely broken in Core, just for some specific types of inputs.  

I would also agree that customers wouldn't necessarily _wish_ to depend on allowing strings longer than X to be processed, quite the opposite. The scenario I had in mind was that a customer opts into what they think is a reasonable MaxStringContentLength (in a project created with a previous version of Core). They have the expectation that their setting is honored/has been honored, and that if the remote host goes outside of the limits, an exception will be/is thrown at runtime. Code is deployed to production, all is well, no limits _seem_ to be violated.

The customer then upgrades their project to the version of Core that contains these fixes, without making any changes to MaxStringContentLength. Suddenly their code is failing (at runtime) where it previously didn't because in reality the remote host had been violating the limit the whole time (maybe not egregiously). Ideally, a behavioral change like this would be caught in the customer's testing - but can we count on that?

That said, I was curious why the code was removed in the initial porting? Does this behavioral change have implications outside of WCF, since XmlDictionaryReader is a public API? Maybe the area owners have some insight? I didn't see an issue created for this PR in corefx, so I wasn't sure if the area owners had been notified. I realize that discussions might happen behind the scenes, so if things have already been discussed then I apologize for dragging this out.

Also, would it be useful to add a regression test that would fail before this change, but succeed with these changes?

**Comment by mconnew** [comment]
The only scenario this broke was leading whitespace was being ignored. As soon as you had a non-whitespace character, the length started to be counted. I would be very surprised if there's anyone using this feature in core who doesn’t also use it on .NET Framework against the same server. 
As to why it got removed, I don't know but I have two very good guesses. A lot of code related to serialization was actually ported into core from the Silverlight code base which was missing some features so it's possible this class came from there and when putting the feature back, this was missed. The other possibility is that in the early days of this project, before it was even open sourced, XmlReaderQuotas weren't going to be supported. The class had been made immutable and only MaxQuotas was supported. Somebody might have attempted a cleanup of code with that in mind. 
As for discussion, the totality of the discussion is in the issue in the WCF repo which is linked. The same people in the WCF team own serialization too so there was no need for a hand-off. This is a safety feature to prevent malicious payloads from causing harm so there was really no discussion other than this is incorrect behavior so needs to be fixed. This is not working alone as a protection as there's still another limit for the total maximum size of the entire document so it doesn't fall into the must service category. 
I agree about there should be a unit test added for this. I'll follow up on that next week to make sure we add one.

**Comment by buyaa-n** [comment]
I am not familiar with how this code ported and how these checks got missed, maybe @krwq knows. But agree that we need to add them back. Thank you @csturm83 good point to add more test and documenting the exception as needed

**Comment by mconnew** [comment]
Test now merged in PR #38805

**Pull request merged**
