### PR TITLE
Override ReadByte on DeflateStream and GZipStream

### PR DESCRIPTION
**Pull request by stephentoub**
Improves throughput of ReadByte by ~15-20% and mostly eliminates involved allocations.

cc: @ianhays

### CODE REVIEW

**Comment by stephentoub** [comment]
Test Innerloop Windows_NT Debug and Test please
Test Innerloop OSX Debug and Test please
Test Innerloop OSX Release and Test please

**Comment by stephentoub** [comment]
Test Innerloop Windows_NT Debug and Test please
Test Innerloop OSX Debug and Test please
Test Innerloop OSX Release and Test please

**Comment by stephentoub** [comment]
@dotnet-bot test this please

**Comment by jkotas** [comment]
> Unable to find an entry point named 'ToAscii' in DLL 'System.Globalization.Native'.

This failure is caused by me reverting the workaround in CoreCLR prematurely. I have put it back already.

**Comment by stephentoub** [comment]
@dotnet-bot test this please

**Comment by stephentoub** [comment]
Test Innerloop OSX Debug Build and Test please
Test Innerloop Ubuntu Debug Build and Test please

**Comment by ianhays** [comment]
LGTM.

**Comment by stephentoub** [comment]
Thanks, Ian.

**Pull request merged**
