### PR TITLE
Added System.Converter to System.Runtime

### PR DESCRIPTION
**Pull request by hann013**
Adding this in order to complete #9995

### CODE REVIEW

**Comment by hann013** [comment]
@danmosemsft

**Comment by stephentoub** [comment]
> Adding this in order to complete #9995 

This is just the first part of that, right?  Then we'll need to add the relevant members to the collections using this delegate?

Regardless, LGTM.

**Comment by hann013** [comment]
@stephentoub Correct, but I have to submit this first so the type is exposed to System.Collections contract.

**Comment by stephentoub** [comment]
> Correct, but I have to submit this first so the type is exposed to System.Collections contract

Yup, got it, makes sense, I was just slightly confused by the wording.

**Pull request merged**
