### PR TITLE
Add RID for Linux/ARM32 (ubuntu)

### PR DESCRIPTION
**Pull request by hseok-oh**
Add RID for Linux/ARM32 - ubuntu*-arm

related PR: https://github.com/dotnet/coreclr/pull/8421

### CODE REVIEW

**Comment by stephentoub** [comment]
cc: @ericstj, @mellinoe, @ellismg

**Comment by mellinoe** [comment]
Looks good to me. Could you also add extra entries for Linux Mint? We consider it binary-compatible with Ubuntu.

**Comment by hseok-oh** [comment]
@mellinoe I don't have environment that installed Linux Mint, so I don't know proper RID for Linux Mint.

**Comment by ellismg** [comment]
I don't believe there is actually an ARM version of Mint (even with it being downstream of Ubuntu).  There's now download link on linuxmint.com and the forums imply that there is no ARM version.

**Comment by mellinoe** [comment]
Good point, @ellismg . That was a bad assumption on my part. The rest of this looks good to me.

**Pull request merged**
