### PR TITLE
Randomize UapRunner GUID

### PR DESCRIPTION
**Pull request by ViktorHofer**
Fixes https://github.com/dotnet/corefx/issues/33550

### CODE REVIEW

**Comment by stephentoub** [comment]
Thank you for fixing this.

**Comment by ViktorHofer** [comment]
@MattGal just FYI, with this change the XUnitRunnerUap is now using randomized GUIDs.

**Comment by ViktorHofer** [comment]
You think that uninstalling the app is not sufficient?

**Comment by ViktorHofer** [comment]
@dotnet-bot test UWP CoreCLR x64 Debug Build

**Comment by ViktorHofer** [comment]
@MattGal as the whole thing could also be an issue with Windows itself installing UWP console applications on edge case let me ask what's the timeline for upgrading our RS4 machines to RS5?

**Comment by MattGal** [comment]
@ViktorHofer good point, I filed https://github.com/dotnet/core-eng/issues/4956 to track enabling this.  It would seem odd though that the same old appx we've been using since RS3 would actually require RS5 but it's something we need to test regardless.

**Comment by ViktorHofer** [comment]
No it doesn't require RS5 but I could think of bugs in the installation routine that lead to the error that we are currently hitting frequently: `FAILED 0x80080008 (Object server is stopping when OLE service contacts it` which could be fixed in RS5 (only an assumption).

Testing in CI shows that randomizing the appx GUID doesn't solve the issue :/

**Comment by ViktorHofer** [comment]
@dotnet-bot test UWP CoreCLR x64 Debug Build

**Pull request closed without merging**
