### PR TITLE
Backport to 1.0 of Unix file locking fix to FileStream

### PR DESCRIPTION
**Pull request by danmosemsft**
As proposed in https://github.com/dotnet/corefx/issues/16256

Not shiproom approved - putting up to run CI.

### CODE REVIEW

**Comment by danmosemsft** [comment]
@dotnet-bot test Innerloop OSX Debug Build and Test please

**Comment by danmosemsft** [comment]
@krwq do you have cycles to throw up a shiproom template email for this one? Jeremy is booked and Ian is out.

**Comment by danmosemsft** [comment]
@stephentoub could you please review / any concerns on backporting this?

**Comment by krwq** [comment]
template sent

**Comment by danmosemsft** [comment]
thanks!

**Comment by danmosemsft** [comment]
approve.d

**Comment by Priya91** [comment]
@danmosemsft @krwq  This requires package version bump if you intend to ship this, please put up PR for this change to update package version.

**Pull request merged**
