### PR TITLE
A few more ActiveIssues on tests for ILC.

### PR DESCRIPTION
**Pull request by AtsushiKan**

### CODE REVIEW

**Comment by tarekgh** [comment]
Should these tests be skipped on aot only? why we are skipping it for all UAP?

**Comment by tarekgh** [comment]
To let you know the globalization tests were passing on UAP but we had to revert the change in xunit runner temporary. please mark these tests against the issue https://github.com/dotnet/corefx/issues/20726 instead of skipping it. thanks.

**Comment by AtsushiKan** [comment]
Actually, the tests are failing on AoT because the ILC runs are not running inside an appcontainer at the present. So #20726 isn't the blocking issue here. 

I think the way to disable this is by skipping the tests if:

    PlatformDetection.IsNetNative && !PlatformDetection.IsWinRT

if it's never intended that Project N will have a Win32 (non-AppContainer) path for these apis, then this will disable the tests for now and light them up once that test is running inside an AppContainer.

**Comment by tarekgh** [comment]
@AtsushiKan if the concern here is aot only, then we should disable the test against active issue tracking fixing the tests there using whatever mechanism. but we shouldn't disable the tests for uap. you may log issue for these tests against aot and then disable the tests on aot using this issue.

**Comment by AtsushiKan** [comment]
Pushed new commit that disables for aot only (and should automatically light up the test once those tests are running inside an appcontainer.) That's better than opening an issue where someone has to manually go in and reenable those tests.

**Comment by tarekgh** [comment]
LGTM. thanks @AtsushiKan

**Pull request merged**
