### PR TITLE
Update buildtools to take fix for coverage issue.

### PR DESCRIPTION
**Pull request by crummel**

### CODE REVIEW

**Comment by crummel** [comment]
@stephentoub This should fix the coverage issue.

**Comment by stephentoub** [comment]
Thanks, @crummel!

**Comment by stephentoub** [comment]
@dotnet-bot test Innerloop Linux ARM Emulator SoftFP Debug Cross Build (#13394)
@dotnet-bot test Innerloop Linux ARM Emulator SoftFP Release Cross Build (#13394)
@dotnet-bot test Innerloop OSX Debug Build and Test please (failure to clone github) FYI @mmitche 
@dotnet-bot test Innerloop OSX Release Build and Test please (failure to clone github) FYI @mmitche

**Comment by stephentoub** [comment]
@dotnet-bot test Innerloop OSX Debug Build and Test please (failure to clone github)
@dotnet-bot test Innerloop OSX Release Build and Test please (failure to clone github)

**Pull request merged**
