### PR TITLE
Fix pal_networking.c compilation error on some platforms

### PR DESCRIPTION
**Pull request by stephentoub**
Fixes https://github.com/dotnet/corefx/issues/25682

### CODE REVIEW

**Comment by stephentoub** [comment]
@dotnet/dnceng, anything to be done about various PRs waiting on "All nodes of label ‘osx-10.12||OSX.1012.Amd64.Open’ are offline"?

**Comment by mmitche** [comment]
@dotnet/dnceng Did all the OSX dtap machines disappear?

**Comment by MattGal** [comment]
I'm looking currently.

**Comment by MattGal** [comment]
Notes in https://github.com/dotnet/core-eng/issues/2205, basically the GitHub auth token used got broken some time during the day due to a security audit.  Fixed now.

**Comment by ahsonkhan** [comment]
@dotnet-bot test Outerloop OSX x64 Debug Build

**Comment by ahsonkhan** [comment]
@dotnet-bot test OSX x64 Debug Build

https://mc.dot.net/#/user/stephentoub/pr~2Fjenkins~2Fdotnet~2Fcorefx~2Fmaster~2F/test~2Ffunctional~2Fcli~2F/21c04a391de9b21eae8c0465fba19da6843c9953/workItem/System.Net.Security.Tests/analysis/xunit/System.Net.Security.Tests.ServerAsyncAuthenticateTest~2FServerAsyncAuthenticate_MismatchProtocols_Fails(serverProtocol:%20Tls,%20clientProtocol:%20Tls12,%20expectedException:%20typeof(System.Security.Auth...
```text
Assert.Throws() Failure
Expected: typeof(System.Security.Authentication.AuthenticationException)
Actual:   typeof(System.TimeoutException): Task timed out after 240000
```

**Pull request merged**
