### PR TITLE
Remove duplcated test assemblies from System.Runtime

### PR DESCRIPTION
**Pull request by weshaggard**
As part of https://github.com/dotnet/corefx/pull/33101 these
assemblies were moved under System.Reflection but weren't
deleted from System.Runtime so this work finishes up the move.

fixes https://github.com/dotnet/corefx/issues/33219 

PTAL @stoub @MaximLipnin

### CODE REVIEW

**Comment by ViktorHofer** [comment]
I think you meant @stephentoub and not @Stoub :D

**Comment by weshaggard** [comment]
test Linux x64 Release Build

**Comment by danmosemsft** [comment]
Test failure
```
Assert.Throws() Failure
Expected: typeof(System.IO.FileNotFoundException)
Actual:   (No exception was thrown)
Stack Trace :
   at System.Reflection.Tests.AssemblyNameTests.Constructor_String_LoadVersionTest() in /mnt/j/workspace/dotnet_corefx/master/linux-TGroup_netcoreapp+CGroup_Release+AGroup_x64+TestOuter_false_prtest/src/System.Reflection/tests/AssemblyNameTests.cs:line 55
```

**Comment by weshaggard** [comment]
@dotnet-bot test this please

**Comment by weshaggard** [comment]
@stephentoub @danmosemsft it does look like AssemblyNameTests.Constructor_String_LoadVersionTest seems to failing from multiple PR's. Are you guys seeing the same things? If it fails again I'm going to disable it as part of this PR.

**Comment by stephentoub** [comment]
> Are you guys seeing the same things?

Yes, though I was hoping it would be resolved by yours :)

**Comment by weshaggard** [comment]
I'll resolve it by disabling the test and filing an issue.

**Comment by weshaggard** [comment]
@joperezr @ericstj we probably should have another look at our packaging CI leg as it seems to be the long pole during our CI legs and taking more then an hour. We should see if we can streamline or perhaps prune some of the matrix.

**Pull request merged**
