### PR TITLE
Shortcutting the code path of LongFileTime.ToDateTimeOffset()

### PR DESCRIPTION
**Pull request by alfredmyers**
Shortcutted `LongFileTime.ToDateTimeOffset()` avoiding conversions from UTC to Local back to UTC again.

Clearly, I have a lot to improve on my Git-Fu. Sorry for the extraneous commits.

### CODE REVIEW

**Comment by JeremyKuhne** [comment]
@tarekgh Should we consider adding FromFileTimeUtc() to DateTimeOffset?

**Comment by danmosemsft** [comment]
@alfredmeyers next time if you like you can do `git rebase -i` to squash unwanted commits in your PR. Personally I prefer to `git rebase master` to catch up to master rather than `git merge master ` as that avoids the merge commit noise.

**Comment by alfredmyers** [comment]
Thanks, @danmosemsft! I'll try that from now on.

**Comment by stephentoub** [comment]
If these are equivalent but the new one is significantly faster, wouldn't it be better to just change the implementation of `DateTimeOffset.FromFileTime`?  Or are they not equivalent / the new one's not always better?

**Comment by tarekgh** [comment]
> If these are equivalent but the new one is significantly faster, wouldn't it be better to just change the implementation of DateTimeOffset.FromFileTime? 

It is by design DateTimeOffset.FromFileTime returns the value relative to the local time. so it is not slow but it has to do an extra step to convert the value from Utc to local value.

> Should we consider adding FromFileTimeUtc() to DateTimeOffset?

This will make sense if we think there will be more places need it which I don't know. as you see the workaround looks very simple but I don't mind adding this API. Also, note that this will be used on Windows only.

**Comment by JeremyKuhne** [comment]
@dotnet-bot test Tizen armel Debug Build

Machine appears to have gone offline...

```
20:14:27   System.Web.HttpUtility -> /opt/corefx/bin/AnyOS.AnyCPU.Debug/System.Web.HttpUtility/netcoreapp/System.Web.HttpUtility.dll
21:58:24 
Build timed out (after 120 minutes). Marking the build as aborted.
21:58:24 
Build was aborted
21:58:24 [Current build status] check if current [ABORTED] is worse or equals then [SUCCESS] and better or equals then [SUCCESS]
21:58:24 Run condition [Current build status] preventing perform for step [[Archive the artifacts]]
21:58:24 ++ handle_exit
21:58:24 ++ set +x
21:58:24 The script is exited. Cleaning environment..
21:58:24 [BFA] Scanning build for known causes...
21:58:25 [BFA] Found failure cause(s):
21:58:25 [BFA] Build Timed Out or was Manually Aborted from category Aborted
21:58:25 [BFA] Done. 1s
21:58:25 Notifying endpoint with credentials id 'helix-int-notification-url'
21:58:25 Notifying endpoint with credentials id 'helix-prod-notification-url'
21:58:26 Setting status of e9680db0abeb9d132347bd761790056afa1497fb to FAILURE with url https://ci.dot.net/job/dotnet_corefx/job/master/job/tizen_armel_cross_debug_prtest/13625/ and message: 'Build finished. '
21:58:26 Using context: Tizen armel Debug Build
21:58:26 [WS-CLEANUP] Deleting project workspace...Cannot delete workspace :remote file operation failed: /mnt/j/workspace/dotnet_corefx/master/tizen_armel_cross_debug_prtest at hudson.remoting.Channel@351a468a:ubuntu1404-20170120-3b6cb19: java.io.IOException: Unable to delete '/mnt/j/workspace/dotnet_corefx/master/tizen_armel_cross_debug_prtest/Tools/15.0/Microsoft.Common.props'. Tried 3 times (of a maximum of 3) waiting 0.1 sec between attempts.
21:58:29 ERROR: Step ‘Delete workspace when build is done’ failed: Cannot delete workspace: remote file operation failed: /mnt/j/workspace/dotnet_corefx/master/tizen_armel_cross_debug_prtest at hudson.remoting.Channel@351a468a:ubuntu1404-20170120-3b6cb19: java.io.IOException: Unable to delete '/mnt/j/workspace/dotnet_corefx/master/tizen_armel_cross_debug_prtest/Tools/15.0/Microsoft.Common.props'. Tried 3 times (of a maximum of 3) waiting 0.1 sec between attempts.
21:58:29 Finished: ABORTED
```

**Comment by JeremyKuhne** [comment]
@dotnet-bot test Windows x64 Debug Build

Nano build appears to have timed out

```
07:14:02 [Windows.10.Nano.Amd64.Open] Will try again after 5 min 0 sec
Cancelling nested steps due to timeout
[Pipeline] [Windows.10.Nano.Amd64.Open] // waitUntil
[Pipeline] [Windows.10.Nano.Amd64.Open] }
[Pipeline] [Windows.10.Nano.Amd64.Open] // timestamps
[Pipeline] [Windows.10.Nano.Amd64.Open] }
[Windows.10.Nano.Amd64.Open] Failed in branch Windows.10.Nano.Amd64.Open
[Pipeline] // parallel
[Pipeline] }
[Pipeline] // timeout
[Pipeline] }
[Pipeline] // stage
[Pipeline] }
[Pipeline] // stage
[Pipeline] End of Pipeline
[BFA] Scanning build for known causes...
[BFA] No failure causes found
[BFA] Done. 0s
Notifying endpoint with credentials id 'helix-int-notification-url'
Notifying endpoint with credentials id 'helix-prod-notification-url'
Setting status of e9680db0abeb9d132347bd761790056afa1497fb to FAILURE with url https://ci3.dot.net/job/dotnet_corefx/job/master/job/windows-TGroup_netcoreapp+CGroup_Debug+AGroup_x64+TestOuter_false_prtest/10023/ and message: 'Build finished. '
Using context: Windows x64 Debug Build
Exception: null
Finished: ABORTED
```

**Comment by JeremyKuhne** [comment]
OSX failure is #21037:

```
Unhandled Exception of Type System.Net.Internals.SocketExceptionFactory+ExtendedSocketException
Message :
System.Net.Internals.SocketExceptionFactory+ExtendedSocketException : Connection refused 127.0.0.1:1538
Stack Trace :
   at System.Net.Sockets.Socket.DoConnect(EndPoint endPointSnapshot, SocketAddress socketAddress) in /Users/dotnet-bot/j/workspace/dotnet_corefx/master/osx-TGroup_netcoreapp+CGroup_Debug+AGroup_x64+TestOuter_false_prtest/src/System.Net.Sockets/src/System/Net/Sockets/Socket.cs:line 4418
   at System.Net.Sockets.Socket.Connect(EndPoint remoteEP) in /Users/dotnet-bot/j/workspace/dotnet_corefx/master/osx-TGroup_netcoreapp+CGroup_Debug+AGroup_x64+TestOuter_false_prtest/src/System.Net.Sockets/src/System/Net/Sockets/Socket.cs:line 829
   at System.Net.Sockets.Socket.Connect(IPAddress[] addresses, Int32 port) in /Users/dotnet-bot/j/workspace/dotnet_corefx/master/osx-TGroup_netcoreapp+CGroup_Debug+AGroup_x64+TestOuter_false_prtest/src/System.Net.Sockets/src/System/Net/Sockets/Socket.cs:line 944
--- End of stack trace from previous location where exception was thrown ---
   at System.Net.Sockets.Socket.Connect(IPAddress[] addresses, Int32 port) in /Users/dotnet-bot/j/workspace/dotnet_corefx/master/osx-TGroup_netcoreapp+CGroup_Debug+AGroup_x64+TestOuter_false_prtest/src/System.Net.Sockets/src/System/Net/Sockets/Socket.cs:line 955
   at System.Net.Sockets.Socket.Connect(String host, Int32 port) in /Users/dotnet-bot/j/workspace/dotnet_corefx/master/osx-TGroup_netcoreapp+CGroup_Debug+AGroup_x64+TestOuter_false_prtest/src/System.Net.Sockets/src/System/Net/Sockets/Socket.cs:line 899
   at System.Net.Tests.HttpListenerFactory.GetConnectedSocket() in /Users/dotnet-bot/j/workspace/dotnet_corefx/master/osx-TGroup_netcoreapp+CGroup_Debug+AGroup_x64+TestOuter_false_prtest/src/System.Net.HttpListener/tests/HttpListenerFactory.cs:line 155
   at System.Net.Tests.InvalidClientRequestTests.GetContext_InvalidRequest_DoesNotGetContext() in /Users/dotnet-bot/j/workspace/dotnet_corefx/master/osx-TGroup_netcoreapp+CGroup_Debug+AGroup_x64+TestOuter_false_prtest/src/System.Net.HttpListener/tests/InvalidClientRequestTests.cs:line 104
--- End of stack trace from previous location where exception was thrown ---
```

**Pull request merged**
