### PR TITLE
branding update for 3.1.3

### PR DESCRIPTION
**Pull request by Anipik**
@mmitche we don't need to turn off the stable package here as we didn't do it last time ?

### CODE REVIEW

**Review by mmitche — APPROVED** [review]
Nope, keep stable on.

**Comment by safern** [comment]
Do you need to update the packageIndex to contain the last stable packages that were shipped on previous release?

**Review by safern — APPROVED** [review]

**Comment by Anipik** [comment]
> Do you need to update the packageIndex to contain the last stable packages that were shipped on previous release?

not yet because we have not release them to nuget yet.

**Comment by Anipik** [comment]
The OSX errors are known so merging this one

**Pull request merged**
