### PR TITLE
Port Japanese Era Tests

### PR DESCRIPTION
**Pull request by tarekgh**

### CODE REVIEW

**Comment by tarekgh** [comment]
@danmosemsft  this PR pending on the new coreclr build to come to corefx. I got the news such build was disabled for awhile and they are going to resume it today.

**Comment by danmosemsft** [comment]
Oh OK I was too eager!

**Comment by danmosemsft** [comment]
Yes, it was a note to myself 😃

**Comment by danmosemsft** [comment]
cherry picked into https://github.com/dotnet/corefx/pull/33624

**Comment by tarekgh** [comment]
Closing this PR as we already got the changes with #33624

**Pull request closed without merging**
