### PR TITLE
Associate issues with more TODO comments in System.Net

### PR DESCRIPTION
**Pull request by ericeil**
This covers all TODO comments I found in the System.Net code.  We should now have an open issue for every TODO, and every TODO should reference each issue by ID. 

There were a couple of comments suggesting that we change some iterative `[Fact]` cases into `[Theory]` cases; rather than file issues on these, I just went ahead and did it.

@stephentoub, @CIPop, @davidsh

### CODE REVIEW

**Comment by stephentoub** [comment]
28 commits seems excessive ;)  but other than that, LGTM.

**Comment by ericeil** [comment]
> 28 commits seems excessive

I did this intentionally, to get GitHub to give me links from the issues to the source files relevant to those issues (via the commits that changed the comments).  If this turns out to be useless, I won't do it again. :)

(I went ahead and squashed a few of the commits that were related, so now it's "only" 23 commits...)

**Comment by CIPop** [comment]
Thanks @ericeil! Appreciate the help cleaning up the comments as well as reopening incorrectly closed issues.

LGTM

**Comment by ericeil** [comment]
The OSX tests failed due #7902.

**Pull request merged**
