### PR TITLE
Update Windows.Compatibility pkg with references to newer WCF versions.

### LINKED ISSUE #35961: Update Windows.Compatibility package with newer WCF Core packages.
WCF ran into dotnet/wcf#3437

Could we update the Microsoft.Windows.Compatibility 2.1.0 package to reference WCF Core 4.5.0 or above packages please?

@safern

### PR DESCRIPTION
**Pull request by StephenBonikowsky**
Fixes #35961 
@safern 
@Lxiamail 

If all is good with this then I will cherry-pick it to release2.2

### CODE REVIEW

**Comment by safern** [comment]
cc: @ericstj

**Comment by ericstj** [comment]
@StephenBonikowsky don't we have newer versions of WCF than this?  I thought there was a 4.5.3.

**Comment by StephenBonikowsky** [comment]
Yes, wasn't sure how far forward to bring it. If we bring it all the way forward to the latest should I still add versions 4.5.0, 4.5.2 to the json file?

**Comment by ericstj** [comment]
Technically you only need the one version you're referencing in that index file.

I believe @safern just added the JSON as an alternative to plumbing [WCF's index](https://github.com/dotnet/wcf/blob/master/pkg/baseline/packageIndex.json) info into corefx, which we can't do since WCF doesn't have a package for this.  For now I think it's fine to just manually update the index with the latest version

**Comment by StephenBonikowsky** [comment]
Ok, made the 4.5.3 update, once the checks complete could one of you merge for me?
Thanks.

**Pull request merged**
