### PR TITLE
Marking code as unchecked (pt 1)

### PR DESCRIPTION
**Pull request by dennisdietrich**
Marking code that may intentionally lead to over or underflows with
unchecked in preparation of turning on CheckForOverflowUnderflow for
all projects (issue #3140)

### CODE REVIEW

**Comment by danmosemsft** [comment]
How did you identify this code --test failures with the flag on?

@mellinoe @ianhays @safern for the collecitons and numerics stuff.

**Comment by danmosemsft** [comment]
Perhaps we should have a comment whereever we use unchecked explaining why overflow is okay?

**Comment by dennisdietrich** [comment]
@danmosemsft Yes. At the moment I'm simply running the inner loop tests with CheckForOverflowUnderflow set globally and fix exceptions as I find them. As for comments, I'm open to that, but I'm not sure how valuable that is. The exceptions so far were pretty much in places where I'd expect them and where the need is IMHO obvious (e.g. hash calculations, uint/int casting, truncations).

The next PR might be more interesting in that regard as I had to add unchecked to a few types in System.Drawing were I didn't really expect it. Point.Offset(int, int) for example does not care about overflows and that is consistent with the MSDN documentation (i.e. it doesn't list any exceptions being thrown by that method). Though, on the other hand, even in that case all I can add without additional input is "this is by design" which, again, isn't all that useful.

**Comment by tarekgh** [comment]
CC @stephentoub  @jkotas @weshaggard @nguerrera 

The changes LGTM.

**Comment by tarekgh** [comment]
merging this one. if anyone still have any comment can add it and we can address it in the future PR's

**Pull request merged**
