### PR TITLE
Fix code coverage build

### PR DESCRIPTION
**Pull request by stephentoub**
cc: @ericstj, @bartonjs
Fixes https://github.com/dotnet/corefx/issues/7380
Disables tests from https://github.com/dotnet/corefx/issues/7465

### CODE REVIEW

**Comment by stephentoub** [comment]
Test Innerloop Ubuntu Debug Build and Test please (known test bug in System.Net.Requests)

**Comment by stephentoub** [comment]
Test code coverage please

**Comment by stephentoub** [comment]
The build is now passing, with all tests completing successfully under OpenCover, but then ReportGenerator fails:
```
(GenerateFullCoverageReport target) -> 
         d:\j\workspace\code_coverage---a11efc90\Tools\CodeCoverage.targets(78,5): error MSB3073: The command "d:\j\workspace\code_coverage---a11efc90\packages/ReportGenerator\2.4.3\tools\ReportGenerator.exe -targetdir:d:\j\workspace\code_coverage---a11efc90\bin/tests/coverage\ -reporttypes:Html;Badges -reports:d:\j\workspace\code_coverage---a11efc90\bin/tests/coverage\\*.coverage.xml" exited with code 1. [d:\j\workspace\code_coverage---a11efc90\src\dirs.proj]
```

**Comment by stephentoub** [comment]
Actually, it looks like ReportGenerator fails because it's now running *before* any of the tests have run.  This is true prior to this PR (I can see in the logs of failing runs previously that it's being executed early on).

**Comment by ericstj** [comment]
LGTM

**Comment by stephentoub** [comment]
Thanks, @ericstj.

@weshaggard, @maririos, I added a commit to fix ReportGenerator.  Thanks for the help, Wes.

**Pull request merged**
