### PR TITLE
Add RebuildAndTest convenience target

### PR DESCRIPTION
**Pull request by nguerrera**
cc @weshaggard @stephentoub

### CODE REVIEW

**Comment by stephentoub** [comment]
Nice. So I no longer need to do /t:rebuild /t:BuildAndTest and can just do /t:RebuildAndTest? Should we instead make BuildAndTest do a rebuild?

**Comment by nguerrera** [comment]
I thought about that, but settled on this. I was a little frustrated by the incremental nature of BuildAndTest, but it makes sense when you incrementally build the world to incrementally test only what changed. I think also think there's good value in having XxxAndYyy just be Xxx then Yyy.

**Comment by davidsh** [comment]
FYI. When I need more precision with this, I simply do "msbuild /t:clean;build;test".

**Comment by stephentoub** [comment]
LGTM.

**Comment by nguerrera** [comment]
@davidsh I didn't know that worked. I'll still keep this for consistency with the BuildAndTest muscle memory.

**Pull request merged**
