### PR TITLE
Cleanup BinaryExpression comparison tests

### PR DESCRIPTION
**Pull request by hughbe**
/cc @VSadov @stephentoub @bartdesmet

### CODE REVIEW

**Comment by stephentoub** [comment]
@dotnet-bot test this please

**Comment by hughbe** [comment]
Test Innerloop CentOS7.1 Release Build and Test

**Comment by hughbe** [comment]
Test Innerloop Ubuntu14.04 Release Build and Test

**Comment by VSadov** [comment]
LGTM

**Pull request merged**
