### PR TITLE
Make DEBUG builds always print chain errors

### PR DESCRIPTION
**Pull request by bartonjs**
To help with https://github.com/dotnet/corefx/issues/35224, but we can leave it on.

cc @stephentoub @vcsjones

### CODE REVIEW

**Comment by vcsjones** [comment]
Oops, I did the same in #35242

**Comment by bartonjs** [comment]
@vcsjones No worries; I happened to glance over and notice that my mac was in an available state shortly after I had said it wasn't :smile:

**Comment by vcsjones** [comment]
@bartonjs uh, I guess trigger the macOS build again?

**Comment by stephentoub** [comment]
@dotnet-bot test OSX x64 Debug Build please

**Pull request merged**
