### PR TITLE
Import XML comments for System.Reflection

### PR DESCRIPTION
**Pull request by mairaw**
@cartermp @joshfree

### CODE REVIEW

**Comment by Priya91** [comment]
>         public virtual Type[] FindInterfaces(TypeFilter filter, object filterCriteria) { return default(Type[]); }

Some public types don't have documentation comments.. There are several below as well.

---
Refers to: src/System.Reflection/ref/System.Reflection.cs:3158 in 3d73e8d. [](commit_id = 3d73e8d64df64d75e20796baca771a133ec410d7, deletion_comment = False)

**Comment by Priya91** [comment]
:-1:

**Comment by Priya91** [comment]
:+1:

**Comment by mairaw** [comment]
yes @Priya91 but these APIs only exist in .NET Core and haven't been documented yet. We're only importing existing documentation at this point.

**Comment by mellinoe** [comment]
@Priya91 I think the main problem here is that for the .NET Framework, most of the documentation for `TypeInfo` is inherited from `Type`, because it is a subclass there. That's not the case in .NET Core, so the documentation doesn't follow accordingly. If you look at the documentation [here](https://msdn.microsoft.com/en-us/library/system.reflection.typeinfo_methods(v=vs.110).aspx), you'll see that `FindInterfaces(TypeFilter filter, object filterCriteria)` is listed, but it links to the `Type` class's documentation.

We'll probably have to fix this somehow, probably manually. Bringing over the existing documentation is a good start, but we'll have to go back and grab some of the additional docs and move them to different types as appropriate.

**Comment by mairaw** [comment]
I discussed this with @cartermp before submitting this PR and we thought for this first round, it'd be best to just only the exact matches (the whole approach is based on Comment ID of each API). So when this class was refactored in Core, the Comment ID changed and it's not a match anymore. I can "hack" our process to copy the missing content from Type to TypeInfo for example, but if this happens across several classes, this will slow down our import process significantly. However, there are types that are completely new in Core and will have to be documented later on such as System.Reflection.DispatchProxy. But let me know how you prefer to do this.

**Comment by mairaw** [comment]
Also, I'm not familiar with the checks here. Why would they fail if we didn't change code? Can someone explain? Thanks!

**Comment by mellinoe** [comment]
> we thought for this first round, it'd be best to just only the exact matches

That sounds fine to me.

As for the tests that failed: they are just flaky. I'll re-run the parts that failed, but we can just ignore them in the end.

@dotnet-bot Test Innerloop OSX Debug Build and Test
Test Innerloop Ubuntu14.04 Debug Build and Test
Test Innerloop Windows_NT Debug Build and Test

**Comment by cartermp** [comment]
Closing this out as we have a different plan for reference docs now.

**Pull request closed without merging**
