### PR TITLE
Update BuildToolsVersion to 01010-01

### PR DESCRIPTION
**Pull request by ericstj**
Needed to fix a race condition in package build when creating layouts

/cc @stephentoub

### CODE REVIEW

**Comment by ericstj** [comment]
@mellinoe looks like this might have been due to your buildtools change...

**Comment by ericstj** [comment]
Yeah, looks like it.  Previously this was relying on https://github.com/dotnet/buildtools/commit/dc96481c395342d274f7ad30686efd523ad6b5c1#diff-db41212f1f42312b1cb34de3960602dbL17.  If I pick up @mellinoe's latest fix it works.

**Comment by mellinoe** [comment]
I have a similar PR up here with a couple of extra things: https://github.com/dotnet/corefx/pull/13533.

**Comment by ericstj** [comment]
Closing in preference of  #13533.

**Pull request closed without merging**
