### PR TITLE
Improving ConstantCheck with support for Default

### PR DESCRIPTION
**Pull request by bartdesmet**
This addresses issue #11096 by adding a case for `ExpressionType.Default` to `ConstantCheck.IsNull`. Also adding some tests to cover these cases.

Note that this branch builds on top of the PR for #11097; if we decide to take these changes, we could do that one first.

### CODE REVIEW

**Comment by bartdesmet** [comment]
CC @VSadov

**Comment by VSadov** [comment]
LGTM

**Comment by VSadov** [comment]
@dotnet-bot test this please

**Comment by bartdesmet** [comment]
Test Innerloop CentOS7.1 Release Build and Test please

**Comment by bartdesmet** [comment]
Test Innerloop CentOS7.1 Release Build and Test please (seg fault; likely CoreCLR bug with `GCInfo`)

**Comment by bartdesmet** [comment]
@VSadov, @stephentoub - CI issues have been resolved; this can be merged now.

**Pull request merged**
