### PR TITLE
[release/2.1] Skip certificates we can't read when populating machine store. (#29973)

### PR DESCRIPTION
**Pull request by stephentoub**
Port https://github.com/dotnet/corefx/pull/29973 to release/2.1/
Fixes https://github.com/dotnet/corefx/issues/29942

### CODE REVIEW

**Comment by stephentoub** [comment]
@ericstj, do you know what's going on here?
https://ci3.dot.net/job/dotnet_corefx/job/release_2.1/job/windows-TGroup_all+CGroup_Debug+AGroup_x64+TestOuter_false_prtest/202/
```
D:\j\workspace\windows-TGrou---27e62afc\Tools\Packaging.targets(435,5): error : Cannot harvest package 'System.Net.WebSockets.WebSocketProtocol' version '4.5.0' because D:\j\workspace\windows-TGrou---27e62afc\packages/System.Net.WebSockets.WebSocketProtocol\4.5.0 does not exist.  Harvesting is needed to redistribute assets and ensure compatiblity with the previous release.  You can disable this by setting HarvestStablePackage=false. [D:\j\workspace\windows-TGrou---27e62afc\src\System.Net.WebSockets.WebSocketProtocol\pkg\System.Net.WebSockets.WebSocketProtocol.pkgproj]
```

**Comment by pjanotti** [comment]
@ericstj I guess that this is being held by the packaging issue mentioned above by @stephentoub, do you know what is going on with it? We are getting more reports of users hitting this on 2.1:

https://github.com/dotnet/corefx/issues/30641
https://github.com/dotnet/corefx/issues/30635

**Comment by ericstj** [comment]
/cc @weshaggard @wtgodbe 

This means that the PackageIndex knows that WebSocketProtocol has a stable version of 4.5.0 but that version isn't being downloaded by external\harvestPackages. 

The fix is to add it to https://github.com/dotnet/corefx/blob/release/2.1/external/harvestPackages/harvestPackages.props.

**Comment by stephentoub** [comment]
@dotnet-bot test Packaging All Configurations x64 Debug Build please

**Pull request merged**
