### PR TITLE
Enable analyzer for xUnit2000 (Constants and literals should be the expected argument)

### PR DESCRIPTION
**Pull request by Gnbrkm41**
Contributes toward #39697.

cc @stephentoub, @ViktorHofer

### CODE REVIEW

**Comment by Gnbrkm41** [comment]
Oh great, looks like I missed Unix ones since I'm running on Windows....

**Comment by Gnbrkm41** [comment]
Looks like linux machines don't treat warnings as error? just wondering why it isn't the case for only these.

**Comment by Gnbrkm41** [comment]
@danmosemsft, yes, that was a merge conflict & I apparently missed that bit :^(. it has been addressed in 1ef7cff.

**Comment by Gnbrkm41** [comment]
Wondering why the logs for macOS is [unavailable](https://helix.dot.net/api/2018-03-14/jobs/803c599a-ab44-4d30-9e53-f6da3009add3/workitems/System.Memory.Tests/console)? It was the same [the other attempt as well.](https://dev.azure.com/dnceng/public/_build/results?buildId=283320)

**Comment by Gnbrkm41** [comment]
>RedHat.7.Amd64.Open-x64-Debug
>System.Text.RegularExpressions.Tests.RegexCultureTests/TurkishI_Is_Differently_LowerUpperCased_In_Turkish_Culture
>Timed out after 60000ms waiting for remote process.

Odd. didn't fail the other time.

**Comment by danmosemsft** [comment]
TurkishI is tracked by https://github.com/dotnet/corefx/issues/38195 and can be ignored.

macOS is broken right now and @mattgal is already investigating...

**Comment by danmosemsft** [comment]
The mac test jobs are different libraries each time, which tells me it's hitting a bad machine in the cluster, not an issue with this change.

**Comment by stephentoub** [comment]
Thank you for fixing all of these!

**Comment by MattGal** [comment]
> The mac test jobs are different libraries each time, which tells me it's hitting a bad machine in the cluster, not an issue with this change.

I very much agree with this assessment but other than knowing some machines got reimaged it's been a tough time finding the offender.

**Pull request merged**
