### PR TITLE
Add System.Diagnostics.StackTrace to test runtime dependencies

### PR DESCRIPTION
**Pull request by tmat**
The library was missing from test output directory, which prevented xunit to display stack traces with source locations.

### CODE REVIEW

**Comment by tmat** [comment]
@MattGal

**Comment by stephentoub** [comment]
This fixes the lack-of-line-numbers-in-exception-stack-traces problem?  If so, excellent!

**Comment by MattGal** [comment]
LGTM.  I would only want to consult with @ericstj  and make sure that including this by default with all tests is not going to be an issue (i.e. it may need to be specificallly included only in certain groups)

**Comment by tmat** [comment]
@stephentoub Yes. Seems like it should.

**Comment by tmat** [comment]
test  Innerloop Ubuntu14.04 Debug Build and Test  please

**Comment by tmat** [comment]
test Innerloop Ubuntu14.04 Release Build and Test  please

**Comment by MattGal** [comment]
@dotnet-bot  test Innerloop Ubuntu14.04 Debug Build and Test please

**Comment by MattGal** [comment]
test Innerloop Ubuntu14.04 Release Build and Test please

**Comment by MattGal** [comment]
@tmat , with the dependency-versioning issue fixed, it's clear that there is a serious and detrimental effect of including this DLL on Ubuntu runs.  We'll need to figure that out (may be a product issue) before you can merge, as this will affect all tests running on Ubuntu all the time.

**Comment by ericstj** [comment]
It looks like the growth in log is only for Ubuntu debug.  I believe this was introduced with https://github.com/dotnet/corefx/pull/12287.  /cc @jamesqo 

LGTM.

**Comment by stephentoub** [comment]
> It looks like the growth in log is only for Ubuntu debug. I believe this was introduced with #12287. /cc @jamesqo

We need to either remove the assert that's getting triggered, or remove the tests that are hitting the assert.  I'd prefer the former: if it's possible to hit an assert from a test, assuming it's via publicly exposed surface area, then either there's a bug in the implementation or the assert is invalid.

**Comment by ericstj** [comment]
Agreed, I pinged @jamesqo in his PR that added these.

**Comment by jamesqo** [comment]
Sorry for this. Fixed the issue in #12599 by removing the relevant tests

**Comment by tmat** [comment]
OK, I'll wait for #12599 before merging this.

**Comment by stephentoub** [comment]
> OK, I'll wait for #12599 before merging this.

It's been merged.  Though due to other things having been merged you're unfortunately going to need to rebase to address a merge conflict.

**Pull request merged**
