### PR TITLE
Improved collection deserialization in System.Text.Json

### LINKED ISSUE #38435: JsonSerializer throwing "System.NotSupportedException : Collection was of a fixed size" for some array/collection parsing
~~Before adding ` SimpleTestClass MySampleTestClass { get; set; }` property to the SimpleTestStruct struct and json test was running successfully, after adding object type JsonSerializer cannot parse it anymore~~
`Update:` The original test failure is fixed with recent update, but the below case is still failing so updated the test case
Exception: `System.NotSupportedException : Collection was of a fixed size.`
```csharp
[Fact]
public void TestMethod1()
{
    var state = new AppState();
    string serialized = "{\"Values\":[1,2,3]}";
    object deserializedState = System.Text.Json.Serialization.JsonSerializer.Parse(serialized, typeof(AppState));
}

public class AppState
{
    public int[] Values { get; set; }
    public AppState()
    {
        Values = Array.Empty<int>();
    }
}

System.NotSupportedException : Collection was of a fixed size.
Stack Trace:
/_/src/System.Private.CoreLib/src/System/Array.CoreCLR.cs(482,0): at System.SZArrayHelper.Add[T](T value)
D:\dotnet\corefx\src\System.Text.Json\src\System\Text\Json\Serialization\JsonSerializer.Read.HandleArray.cs(264,0): 
at System.Text.Json.JsonSerializer.ApplyValueToEnumerable[TProperty](TProperty& value, ReadStack& state, Utf8JsonReader& reader)
D:\dotnet\corefx\src\System.Text.Json\src\System\Text\Json\Serialization\JsonPropertyInfoNotNullable.cs(67,0) : 
at System.Text.Json.JsonPropertyInfoNotNullable`3.ReadEnumerable(JsonTokenType tokenType, ReadStack& state, Utf8JsonReader& reader)
D:\dotnet\corefx\src\System.Text.Json\src\System\Text\Json\Serialization\JsonPropertyInfoNotNullable.cs(25,0)  : 
at System.Text.Json.JsonPropertyInfoNotNullable`3.Read(JsonTokenType tokenType, ReadStack& state, Utf8JsonReader& reader)
D:\dotnet\corefx\src\System.Text.Json\src\System\Text\Json\Serialization\JsonSerializer.Read.HandleValue.cs(28,0): 
at System.Text.Json.JsonSerializer.HandleValue(JsonTokenType tokenType, JsonSerializerOptions options, Utf8JsonReader& reader, ReadStack& state)
D:\dotnet\corefx\src\System.Text.Json\src\System\Text\Json\Serialization\JsonSerializer.Read.cs(48,0): 
at System.Text.Json.JsonSerializer.ReadCore(JsonSerializerOptions options, Utf8JsonReader& reader, ReadStack& readStack)
D:\dotnet\corefx\src\System.Text.Json\src\System\Text\Json\Serialization\JsonSerializer.Read.Helpers.cs(22,0) : 
at System.Text.Json.JsonSerializer.ReadCore(Type returnType, JsonSerializerOptions options, Utf8JsonReader& reader)
D:\dotnet\corefx\src\System.Text.Json\src\System\Text\Json\Serialization\JsonSerializer.Read.String.cs(74,0): 
at System.Text.Json.JsonSerializer.ParseCore(String json, Type returnType, JsonSerializerOptions options)
D:\dotnet\corefx\src\System.Text.Json\src\System\Text\Json\Serialization\JsonSerializer.Read.String.cs(31,0): 
at System.Text.Json.JsonSerializer.Parse[TValue](String json, JsonSerializerOptions options)
D:\dotnet\corefx\src\System.Text.Json\tests\Serialization\Object.ReadTests.cs(312,0): 
at System.Text.Json.Serialization.Tests.ObjectTests.ReadStructObjectValueTest()

```

### PR DESCRIPTION
**Pull request by YohDeadfall**
Fixes #38435. I will write some tests to cover the second commit (read only and fixed size collections), but otherwise it's ready to review.

/cc @ahsonkhan @steveharter @layomia @buyaa-n

### CODE REVIEW

**Comment by ahsonkhan** [comment]
cc @JeremyKuhne

**Comment by YohDeadfall** [comment]
I found what tends the test to fail:

https://github.com/dotnet/corefx/blob/219b67118e3a2d539afc1ff3bb2c10e1bc7b03d2/src/System.Text.Json/src/System/Text/Json/Serialization/JsonSerializer.Read.HandleArray.cs#L190-L198

The code should be changed to fall into the first block and not the second one, but I can't understand what it is for. In which case the `Add` method should be called on the `list`?

**Comment by steveharter** [comment]
> The code should be changed to fall into the first block and not the second one, but I can't understand what it is for. In which case the Add method should be called on the list?

IIRC, the first branch is when the property should be set explicitly and Add() not called. This is for arrays (the final set, not the temporary list to build up the values) and perhaps other collection types that aren't an IList.

**Comment by YohDeadfall** [comment]
I see. It's just strange how it's implemented and behaves now. The first solution is to set a null value, but I don't like it. So will research how to solve it another way. On the weekend I will have enouhg time to finish it.

**Comment by YohDeadfall** [comment]
@steveharter I haven't found a better way than this to fix the bug. Take a look, please.

**Comment by steveharter** [comment]
> @steveharter I haven't found a better way than this to fix the bug. Take a look, please.

@YohDeadfall this is more involved than I thought. I'll take over the issue and close the PR. Thanks for your research into this.

The best approach is to do this early during warm-up so we don't have to call the property getter in order to inspect every collection instance that doesn't have a setter.

**Comment by YohDeadfall** [comment]
@steveharter Did you mean that you want to store the current collection in `ReturnValue` and not to access the setter each time? I thought about it too, but haven't touched yet. This will improve performance and make the code more observable and clear.

**Pull request closed without merging**
