### PR TITLE
Disable failing NamedPipeTest test on Windows

### PR DESCRIPTION
**Pull request by stephentoub**
cc: @saurabh500 
#17373

### CODE REVIEW

**Comment by saurabh500** [comment]
@stephentoub Is there a link to the failed execution in the CI?

**Comment by saurabh500** [comment]
I am wondering if the failures pertain to the test execution against the Full Framework or is it for Core?

**Comment by stephentoub** [comment]
>Is there a link to the failed execution in the CI?

Yes, there are a bunch in that issue, e.g.
https://ci.dot.net/job/dotnet_corefx/job/master/job/outerloop_win10_debug_prtest/9/consoleText
```
     System.Data.SqlClient.Tests.ExceptionTest.NamedPipeTest(dataSource: \"np:\\\\\\\\localhost\\\\pipe\\\\sqlbad\\\\query\") [FAIL]
        Assert.Contains() Failure
        Not found: (provider: Named Pipes Provider, error: 11 - Timeout error)
        In value:  A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: Named Pipes Provider, error: 40 - Could not open a connection to SQL Server)
        Stack Trace:
           D:\j\workspace\outerloop_win---631b87b7\src\System.Data.SqlClient\tests\FunctionalTests\ExceptionTest.cs(116,0): at System.Data.SqlClient.Tests.ExceptionTest.VerifyConnectionFailure[TException](Action connectAction, String expectedExceptionMessage, Func`2 exVerifier)
           D:\j\workspace\outerloop_win---631b87b7\src\System.Data.SqlClient\tests\FunctionalTests\ExceptionTest.cs(124,0): at System.Data.SqlClient.Tests.ExceptionTest.VerifyConnectionFailure[TException](Action connectAction, String expectedExceptionMessage)
           D:\j\workspace\outerloop_win---631b87b7\src\System.Data.SqlClient\tests\FunctionalTests\ExceptionTest.cs(96,0): at System.Data.SqlClient.Tests.ExceptionTest.NamedPipeTest(String dataSource)
```

**Comment by saurabh500** [comment]
Thanks. I will try to debug this on Win 10

**Comment by stephentoub** [comment]
> Thanks. I will try to debug this on Win 10
Thanks

**Pull request merged**
