### PR TITLE
Update prerelease packages in release/1.0.0-rc2 to version 23722

### PR DESCRIPTION
**Pull request by weshaggard**

### CODE REVIEW

**Comment by weshaggard** [comment]
@ellismg @stephentoub 

Beyond the package version bump this also contains two other commits:
1) Switch to resolve packages from dotnet-core-rel
2) https://github.com/dotnet/corefx/pull/5624 which reverts the regression in the dynamic tests, because it blocks testing against the latest packages.

**Comment by stephentoub** [comment]
You're also going to need https://github.com/dotnet/corefx/pull/5640.

**Comment by weshaggard** [comment]
@stephentoub I've come to realize that I need to wait for both of those changes to be submitted and packages actually published with them. Are we waiting for approval for them or do we think we can get them merged and mirrored internally before the build kicks off tomorrow night?

**Comment by stephentoub** [comment]
Yes, you will need both https://github.com/dotnet/corefx/pull/5640 and https://github.com/dotnet/corefx/pull/5624, for product changes.  You'll also need the test changes in https://github.com/stephentoub/corefx/commit/9d7b531e52f28d518ff38f7e09e70651b85fb9f6 and https://github.com/stephentoub/corefx/commit/a7d743c973b2eea287c5c6dcde807fe640ed491a to get the tests to pass successfully.  And to workaround the lack of these fixes in packages, I had to use tricks like https://github.com/stephentoub/corefx/commit/5eb4a0405e16f1cc7d2488f9106f644141f62de5.

We really need a better solution. If we're set on not switching to using live versions, then we should at least enable packages to be built and published more frequently so that we don't have to wait 24 hours after a check-in to be able to use that fix.  Why not publish new packages on every check-in?  Or once an hour that has had changes made? Etc.  Also, even with the nightly builds, why don't we do them and publish packages on weekends?

**Comment by weshaggard** [comment]
@stephentoub I hear you, I'm thinking about ways to get some better coverage. As for publishing of packages more than once daily, we are getting close to being able to do that but not quite their yet. Once we finish the work to get all the packages built and shipped from git we will be able to consider doing this on a per-check-in basis. However even that isn't a slam dunk given all our troubles we currently have with retention of our packages and running out of storage space.

Right now I'm more thinking about adding more test legs that cover both the minimal dependencies and the live dependencies.

**Comment by ellismg** [comment]
BTW, @weshaggard.  I took a quick peak at buildtools and I think since the refactoring of where we drop outputs, TestWithLocalLibraries is not going to do the right thing for us since [the paths it grovels are out of date](https://github.com/dotnet/buildtools/blob/9d5782860fe092c7b3d035db57737b804a4bb6a2/src/Microsoft.DotNet.Build.Tasks/PackageFiles/publishtest.targets).

I would expect that `/p:TestWithLocalLibraries=true` is a no-op right now, but I haven't sat down with the build logs to confirm.

**Comment by weshaggard** [comment]
@ellismg thanks for calling that out, I will investigate it further.

**Comment by weshaggard** [comment]
Closing this and will submit another PR with the latest packages once I can get my windows build working with them.

**Pull request closed without merging**
