### PR TITLE
typo: src/System.ComponentModel.Composition/src/System/ComponentModel/Composition/Hosting/CatalogExportProvider.ScopeManager.cs

### PR DESCRIPTION
**Pull request by nschonni**
- rejetecion -> rejection
- satsify -> satisfy
- perspecitive -> perspective
- otehr -> other
- teh -> the

### CODE REVIEW

**Comment by stephentoub** [comment]
Thank you for fixing all these typos. But rather than submitting all of these separate PEs, can you please batch them up into a single PR with as many commits as you like?

**Comment by danmosemsft** [comment]
I suggest closing all these and creating one single one. It's filling up the list of PR'S.

**Comment by nschonni** [comment]
Thanks, I won't be resubmitting these though

**Comment by stephentoub** [comment]
> Thanks, I won't be resubmitting these though

Ok. If you'd like to submit a single PR for all such changes, we'd be happy to accept it.

**Comment by nschonni** [comment]
> Ok. If you'd like to submit a single PR for all such changes, we'd be happy to accept it.

That's fine wanting one PR, but i'm not going to redo the fixes as I mentioned.
If you want to see some of the issues that are in the repo, I'm just running https://github.com/Jason3S/cspell which is used on the MSDocs side.

**Comment by stephentoub** [comment]
> i'm not going to redo the fixes as I mentioned.

I understand. That's obviously your choice. I was saying we'd welcome a single PR if you change your mind. We just do not want a ton of PRs that are all one-line typo changes. It clutters up the PR list and the repo history, and consumes a lot of CI resources.

**Pull request closed without merging**
