### PR TITLE
Add checks for PlatformNotSupported exceptions in Named Pipe ManualTests when running on non-Windows platforms.

### PR DESCRIPTION
**Pull request by corivera**
Not sure why DataStreamTest.cs is showing as a binary here. The only changes I made were platform if/else checks in its *_NP tests. Just check the raw for that one.

Edit: Fixed an encoding issue with DataStreamTest.cs

### CODE REVIEW

**Comment by corivera** [comment]
CC @saurabh500 @kkurni @nadiatk

**Comment by akoeplinger** [comment]
> Not sure why DataStreamTest.cs is showing as a binary here

That usually happens when a file is in UTF-16 instead of UTF8

**Comment by saurabh500** [comment]
@corivera the encoding of your DataStreamTest.cs is UCS-2 LE BOM according to Notepad++

**Comment by corivera** [comment]
@dotnet-bot Test This please

**Comment by saurabh500** [comment]
LGTM

**Comment by kkurni** [comment]
LGTM

**Pull request merged**
