### PR TITLE
Test: Fixes for FreeBSD in run-test script

### PR DESCRIPTION
**Pull request by jasonwilliams200OK**
Although it is failing with:

```bash
Pulling down Microsoft.DotNet.CoreFx.FreeBSD.TemporaryTestHost.0.0.2-prerelease.nupkg
Unzipping to packages/Microsoft.DotNet.CoreFx.FreeBSD.TemporaryTestHost.0.0.2-prerelease
unzip: Unrecognized archive format
Package not laid out as expected
```

but this change was required to get to this point.

@VSadov, @mmitche. we made necessary changes in BuildTools https://github.com/dotnet/buildtools/pull/180. Is there anything else required to have FreeBSD test host published on myget?

/cc: @janhenke

### CODE REVIEW

**Comment by janhenke** [comment]
LGTM

**Comment by stephentoub** [comment]
LGTM

**Comment by mmitche** [comment]
The temporary test host was a manually created package with some bits that were required but not yet OSS.  I am not quite sure how much of the contents were still required.  Can you get the tests to run locally (if so then it's not necessary any longer)

**Comment by jasonwilliams200OK** [comment]
@mmitche,

>  I am not quite sure how much of the contents were still required

Do you mean this is not required -> [/run-test.sh#L86-L160](https://github.com/dotnet/corefx/blob/ed0bd8b06d60910157ade78294006592f2c71d49/run-test.sh#L86-L160)

> Can you get the tests to run locally

This is what I am doing, trying to execute `./run-test.sh` on FreeBSD locally? :)

**Comment by mmitche** [comment]
Some of the overlay will be required until we have test layout publishing all sorted out for all platforms.  However, it's possible that the TemporaryTestHost bit of that overlay is not required right now.

**Pull request merged**
