### PR TITLE
Retarget System.Data.SqlClient to be on top of netstandard2.0.

### PR DESCRIPTION
**Pull request by weshaggard**
Fixes https://github.com/dotnet/corefx/issues/16795

cc @saurabh500 @ericstj

### CODE REVIEW

**Comment by stephentoub** [comment]
I don't think this is a reason to stop this approach, but I want to re-highlight one thing.  SqlClient required access to some internals on types that are in System.Data.Common.  To address that, we created some workarounds:
https://github.com/dotnet/corefx/blob/master/src/System.Data.SqlClient/src/System/Data/SqlTypes/SqlTypeWorkarounds.cs
This was less scary when both System.Data.Common and System.Data.SqlClient were essentially always part of the same implementation and there just happened to be an assembly-barrier between them as an implementation detail.  With the former in .NET Core's implementation of netstandard and the latter now about to be separated out and sitting a top netstandard, these workarounds could potentially be problematic, e.g. if the implementations of these dependencies in other netstandard implementations were sufficiently different as to mess up these workarounds.  Just something to keep in mind.

**Comment by weshaggard** [comment]
@stephentoub thanks for calling that out I wasn't aware of that dependency. Looking at the code you pointed out I don't see where the internals are being accessed nor do I see any reflection usage. So it is just a copy of the code that needs to be updated or shared?

**Comment by weshaggard** [comment]
@dotnet-bot test Innerloop Ubuntu14.04 Release Build and Test please

**Comment by stephentoub** [comment]
> Looking at the code you pointed out I don't see where the internals are being accessed nor do I see any reflection usage

It's not that internals are being accessed: it's that a dependency is being taken on the exact layout of some internal types.

For example, SqlClient needs to be able to construct a SqlMoney using a ctor that's not public:
https://github.com/dotnet/corefx/blob/master/src/System.Data.Common/src/System/Data/SQLTypes/SQLMoney.cs#L50
but SqlMoney is a struct, so we hack it by creating an identically shaped struct:
https://github.com/dotnet/corefx/blob/master/src/System.Data.SqlClient/src/System/Data/SqlTypes/SqlTypeWorkarounds.cs#L100
and then using a wrapper struct with explicit layout to effectively reinterpret cast from one to the other:
https://github.com/dotnet/corefx/blob/master/src/System.Data.SqlClient/src/System/Data/SqlTypes/SqlTypeWorkarounds.cs#L107
https://github.com/dotnet/corefx/blob/master/src/System.Data.SqlClient/src/System/Data/SqlTypes/SqlTypeWorkarounds.cs#L75
If the layout of SqlMoney were to be different in a different netstandard implementation, this would break in bad ways.

**Comment by saurabh500** [comment]
@stephentoub Would SqlClient being a part of netstandard have solved this problem? It seems that before the PR also the SqlClient could have broken on different netstandard implementations based on the layout of the types.

**Comment by stephentoub** [comment]
If it was part of netstandard along with System.Data.Common, then an implementation of netstandard would be providing both implementations, together.

**Comment by weshaggard** [comment]
Thanks for the explanation @stephentoub. I agree it isn't ideal but I would guess a majority of these types are actually fixed as they are either directly used by interop or they are supposed to represent the exact structure of a Sql data type so changing that layout is most likely going to be a breaking change. So I think I can live with this dependency. It would be nice to be able to share some code so the logic stays in-sync but I couldn't really come up with any clever way to do that because of the struct types being different.

**Comment by weshaggard** [comment]
>It seems that before the PR also the SqlClient could have broken on different netstandard implementations based on the layout of the types.

As @stephentoub pointed out the new implementations were netcoreapp/uap specific so it wouldn't have been an issue for those configurations. We have a netstandard1.3 implementation (we don't build it live we harvest it from the last stable package) that is fixed and had the SqlTypes directly in the library so it isn't an issue for those ones.

**Comment by stephentoub** [comment]
Sounds good, Wes.

**Comment by saurabh500** [comment]
Had a conversation with @stephentoub offline. 

LGTM.

**Pull request merged**
