### PR TITLE
Add context to InternalExceptions

### PR DESCRIPTION
**Pull request by stephentoub**
To help with debugging if they ever occur (they're not supposed to).

Closes https://github.com/dotnet/corefx/issues/32825
cc: @davidsh, @Tratcher

### CODE REVIEW

**Comment by stephentoub** [comment]
@dotnet-bot test OSX x64 Debug Build please

**Comment by stephentoub** [comment]
@dotnet/dnceng, is there a problem with the CROSS Check leg?  It's failed a couple of times now:
```
D:\j\workspace\CROSS_check_p---251af28f>powershell -Command "wget '****' -OutFile cross-integration.zip" 
wget : The remote name could not be resolved: 'crossdist.blob.core.windows.net'
At line:1 char:1
+ wget 
'https://crossdist.blob.core.windows.net/debug/cross.zip?sv=2014-02-14&ss=2 ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:Htt 
   pWebRequest) [Invoke-WebRequest], WebException
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShe 
   ll.Commands.InvokeWebRequestCommand
```

**Comment by stephentoub** [comment]
@dotnet-bot test OSX x64 Debug Build please

**Comment by stephentoub** [comment]
@dotnet-bot test CROSS Check please

**Comment by MattGal** [comment]
@stephentoub we don't actually own CROSS, that's a separate team.  As I can't seem to find the Github @ tags for any of the guys I've talked to from CROSS, I've started an email thread with you and them.  I suspect you can ignore it for now, based off the content of your changes.

**Comment by stephentoub** [comment]
Thanks, @MattGal.  I'm just going to ignore the leg for now.

**Comment by stephentoub** [comment]
> Did you verify that all of these various objects have reasonable ToString behavior?

They're all ints or enums.

**Pull request merged**
