### PR TITLE
[WIP] Re-enable functional http2 tests timing out in CI

### PR DESCRIPTION
**Pull request by eiriktsarpalis**
Investigates #39545. Do not merge.

### CODE REVIEW

**Comment by maryamariyan** [comment]
@eiriktsarpalis just checking if this PR is still under your radar to get merged/updated.

**Comment by eiriktsarpalis** [comment]
@maryamariyan It's intended for merging, just being used to test CI builds. That being said, I'm not actively using this at the moment, so perhaps we can close it?

**Comment by maryamariyan** [comment]
Thanks

**Pull request closed without merging**
