### PR TITLE
More FileStream cleanup

### PR DESCRIPTION
**Pull request by jkotas**

### CODE REVIEW

**Comment by jkotas** [comment]
cc @JeremyKuhne

**Comment by stephentoub** [comment]
@mmitche, FYI, both of the macOS debug and release runs hit this:
https://ci.dot.net/job/dotnet_corefx/job/master/job/osx10.12_debug_prtest/212/consoleText
https://ci.dot.net/job/dotnet_corefx/job/master/job/osx10.12_release_prtest/211/consoleText
```
[WS-CLEANUP] Deleting project workspace...
ERROR: [WS-CLEANUP] Cannot delete workspace: remote file operation failed: /Users/dotnet-bot/j/workspace/dotnet_corefx/master/osx10.12_debug_prtest at hudson.remoting.Channel@381a9d0a:dci-mac-build-084: hudson.remoting.ChannelClosedException: channel is already closed
ERROR: Cannot delete workspace: remote file operation failed: /Users/dotnet-bot/j/workspace/dotnet_corefx/master/osx10.12_debug_prtest at hudson.remoting.Channel@381a9d0a:dci-mac-build-084: hudson.remoting.ChannelClosedException: channel is already closed
[xUnit] [INFO] - Starting to record.
[xUnit] [INFO] - Processing xUnit.Net-v2 (default)
ERROR: Step ‘Publish xUnit test result report’ aborted due to exception: 
java.io.IOException: remote file operation failed: /Users/dotnet-bot/j/workspace/dotnet_corefx/master/osx10.12_debug_prtest at hudson.remoting.Channel@381a9d0a:dci-mac-build-084: hudson.remoting.ChannelClosedException: channel is already closed
	at hudson.FilePath.act(FilePath.java:1014)
	at hudson.FilePath.act(FilePath.java:996)
	at org.jenkinsci.plugins.xunit.XUnitProcessor.performTests(XUnitProcessor.java:145)
	at org.jenkinsci.plugins.xunit.XUnitProcessor.performXUnit(XUnitProcessor.java:88)
	at org.jenkinsci.plugins.xunit.XUnitPublisher.perform(XUnitPublisher.java:142)
	at org.jenkinsci.plugins.xunit.XUnitPublisher.perform(XUnitPublisher.java:134)
	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:779)
	at hudson.model.AbstractBuild$AbstractBuildExecution.performAllBuildSteps(AbstractBuild.java:720)
	at hudson.model.Build$BuildExecution.post2(Build.java:185)
	at hudson.model.AbstractBuild$AbstractBuildExecution.post(AbstractBuild.java:665)
	at hudson.model.Run.execute(Run.java:1745)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:98)
	at hudson.model.Executor.run(Executor.java:404)
Caused by: hudson.remoting.ChannelClosedException: channel is already closed
	at hudson.remoting.Channel.send(Channel.java:578)
	at hudson.remoting.Request.call(Request.java:130)
	at hudson.remoting.Channel.call(Channel.java:796)
	at hudson.FilePath.act(FilePath.java:1007)
	... 14 more
Caused by: java.io.IOException
	at hudson.remoting.Channel.close(Channel.java:1180)
	at hudson.slaves.ChannelPinger$1.onDead(ChannelPinger.java:115)
	at hudson.remoting.PingThread.ping(PingThread.java:130)
	at hudson.remoting.PingThread.run(PingThread.java:86)
Caused by: java.util.concurrent.TimeoutException: Ping started at 1489775016397 hasn't completed by 1489775256398
	... 2 more
[Current build status] check if current [FAILURE] is worse or equals then [FAILURE] and better or equals then [SUCCESS]
Run condition [Current build status] enabling perform for step [[Archive the artifacts]]
Archiving artifacts
ERROR: Failed to archive artifacts: msbuild.log,bin/build.tar.gz
java.io.IOException: remote file operation failed: /Users/dotnet-bot/j/workspace/dotnet_corefx/master/osx10.12_debug_prtest at hudson.remoting.Channel@381a9d0a:dci-mac-build-084: hudson.remoting.ChannelClosedException: channel is already closed
	at hudson.FilePath.act(FilePath.java:1014)
	at hudson.FilePath.act(FilePath.java:996)
	at hudson.tasks.ArtifactArchiver.perform(ArtifactArchiver.java:237)
	at hudson.tasks.BuildStepCompatibilityLayer.perform(BuildStepCompatibilityLayer.java:78)
	at org.jenkins_ci.plugins.flexible_publish.builder.FailFastBuilder.perform(FailFastBuilder.java:102)
	at org.jenkins_ci.plugins.run_condition.BuildStepRunner$2.run(BuildStepRunner.java:110)
	at org.jenkins_ci.plugins.run_condition.BuildStepRunner$Fail.conditionalRun(BuildStepRunner.java:154)
	at org.jenkins_ci.plugins.run_condition.BuildStepRunner.perform(BuildStepRunner.java:105)
	at org.jenkins_ci.plugins.flexible_publish.strategy.FailFastExecutionStrategy.perform(FailFastExecutionStrategy.java:63)
	at org.jenkins_ci.plugins.flexible_publish.ConditionalPublisher.perform(ConditionalPublisher.java:206)
	at org.jenkins_ci.plugins.flexible_publish.FlexiblePublisher.perform(FlexiblePublisher.java:124)
	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:779)
	at hudson.model.AbstractBuild$AbstractBuildExecution.performAllBuildSteps(AbstractBuild.java:720)
	at hudson.model.Build$BuildExecution.post2(Build.java:185)
	at hudson.model.AbstractBuild$AbstractBuildExecution.post(AbstractBuild.java:665)
	at hudson.model.Run.execute(Run.java:1745)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:98)
	at hudson.model.Executor.run(Executor.java:404)
Caused by: hudson.remoting.ChannelClosedException: channel is already closed
	at hudson.remoting.Channel.send(Channel.java:578)
	at hudson.remoting.Request.call(Request.java:130)
	at hudson.remoting.Channel.call(Channel.java:796)
	at hudson.FilePath.act(FilePath.java:1007)
	... 19 more
Caused by: java.io.IOException
	at hudson.remoting.Channel.close(Channel.java:1180)
	at hudson.slaves.ChannelPinger$1.onDead(ChannelPinger.java:115)
	at hudson.remoting.PingThread.ping(PingThread.java:130)
	at hudson.remoting.PingThread.run(PingThread.java:86)
Caused by: java.util.concurrent.TimeoutException: Ping started at 1489775016397 hasn't completed by 1489775256398
	... 2 more
```

**Comment by jkotas** [comment]
@dotnet-bot test Innerloop OSX10.12 Debug x64 Build and Test please
@dotnet-bot test Innerloop OSX10.12 Release x64 Build and Test please

**Comment by jkotas** [comment]
@dotnet-bot test Innerloop OSX10.12 Release x64 Build and Test please

**Comment by stephentoub** [comment]
@mmitche, the macOS legs continue to have issues:
https://ci.dot.net/job/dotnet_corefx/job/master/job/osx10.12_release_prtest/225/consoleText

I'm going to merge this without that leg.

**Pull request merged**
