### PR TITLE
Fixing Native Non-Windows version info issues in Official builds

### PR DESCRIPTION
**Pull request by joperezr**
@ellismg @weshaggard 

Thanks for catching this issues @ellismg, this should fix them for corefx. I'll send out the coreclr changes soon.

### CODE REVIEW

**Comment by stephentoub** [comment]
Test Innerloop CentOS7.1 Release Build and Test please
Test Innerloop OSX Debug Build and Test please

**Comment by ellismg** [comment]
LGTM.  We will want to bring this into the release branch as well.

**Comment by joperezr** [comment]
@ellismg will do, I'll send out the Pr for that shortly

**Comment by joperezr** [comment]
@dotnet-bot test Innerloop OSX Debug Build and Test please

**Pull request merged**
