### PR TITLE
Update advanced-inner-loop-testing.md

### PR DESCRIPTION
**Pull request by danmosemsft**
(empty PR for discussion)

@ViktorHofer I have found it easier to

- Not bother copying files out of 9.9.9.9. Create program.cs in place.
- First time only:  `for /f %i in ('dir /s /b System*dll') do @echo /r:%i >> out.rsp`
- `corerun \git\corefx\Tools\csc.dll program.cs @out.rsp`
- `devenv /debugexe corerun.exe program.exe`
- First time only: manually set the debug engine to .NET Core (program, args, and working directory are set for you). VS will prompt you to save the .sln to persist these settings.
- set breakpoints, F5 etc. All .NET Core symbols are loaded, and sources are resolved, debug happily, edit sources, build whatever folder with `msbuild` as normal, this updates 9.9.9.9 folder, hit F5 again, .etc

It seems to me this is an improvement to the inner loop without a unit test. It's the quickest way I know to debug a .NET Core program with CoreFX sources/binaries.

Shall I update this document as above?

### CODE REVIEW

**Comment by danmosemsft** [comment]
I can extend this for Linux to use lldb.

**Comment by stephentoub** [comment]
> Not bother copying files out of 9.9.9.9. Create program.cs in place.

That doesn't work well in a variety of situations, such as wanting to maintain multiple different directories, e.g. one with a checked coreclr and one with a release coreclr, or one with "current" corefx bits and then one with an updated assembly to make it easier to do A/B perf comparisons.

> First time only

Isn't that referencing the implementation assemblies rather than the contract assemblies?  That's problematic for any full or partial facade.

> It seems to me this is an improvement to the inner loop without a unit test.

These updates are focused on using VS and seem to assume a desire to debug something, rather than, say, do perf experiments.

**Comment by danmosemsft** [comment]
Good points, I'll think about how to improve it. I do think we need to make it easier to debug test apps when working on corefx.

**Comment by ViktorHofer** [comment]
Dan I think your suggestions make sense for the scenario of debugging something with VS. As most of our existing customers use VS and like to debug into their code I think this is fine.

For benchmarking and testing on headless environments like Ubuntu Server I think the existing steps are the way to go.

I think extending the existing doc would be the best fit here.

> Isn't that referencing the implementation assemblies rather than the contract assemblies? If so, that's problematic for any full or partial facade.

If I understand it right, the existing steps also just make use of the implementation assemblies and ignore the reference assemblies: `bin\testhost\netcoreapp-Windows_NT-Release-x64\shared\Microsoft.NETCore.App\9.9.9`? Or does that folder consist of both impl and ref assemblies?

**Pull request closed without merging**
