### PR TITLE
Dispose of X509Certificate used in WinHttpHandler server callback

### PR DESCRIPTION
**Pull request by stephentoub**
cc: @davidsh, @bartonjs

### CODE REVIEW

**Comment by davidsh** [comment]
LGTM

**Comment by stephentoub** [comment]
Test Innerloop OSX Release Build and Test please (#7096)

**Comment by bartonjs** [comment]
LGTM2

**Comment by stephentoub** [comment]
Ubuntu debug failed in a Jenkins timeout copying bits to the machine.  As this change is Windows-only, I'm not going to re-run that leg.

Thanks for the review.

**Pull request merged**
