### PR TITLE
Change dependsOn Parameter when calling post-build tempalte to react …

### PR DESCRIPTION
**Pull request by ghost**
…to Arcade breaking change

Test build for this: https://dev.azure.com/dnceng/internal/_build/results?buildId=365845&view=results (canceled the builds, but the stage flow looks correct again)

### CODE REVIEW

**Review by ViktorHofer — APPROVED** [review]

**Comment by ViktorHofer** [comment]
Thanks. Can you please point me to the breaking change in arcade?

**Comment by ViktorHofer** [comment]
Ok you linked to in offline: https://github.com/dotnet/arcade/pull/3986

**Comment by riarenas** [comment]
Sure. It was https://github.com/dotnet/arcade/pull/3986/files#diff-853fb537e588caa8b548253bdcf21cd8R19

**Review by safern — APPROVED** [review]
Thanks!

**Pull request merged**
