### PR TITLE
Adding member/types added in the Core surface area for mscorlib classic assembly

### PR DESCRIPTION
**Pull request by joperezr**
Adding member/types added in the Core surface area for mscorlib classic assembly

cc: @weshaggard @danmosemsft

### CODE REVIEW

**Comment by mellinoe** [comment]
I see there's a couple things under FEATURE_COMINTEROP. Should we just go ahead and remove the #if's, since it seems to be defined in the project, and this is a reference assembly?

**Comment by joperezr** [comment]
@dotnet-bot test Innerloop Windows_NT Debug Build and Test please

**Comment by joperezr** [comment]
Sure that makes sense, I'll remove those.

---
In reply to: [231195645](https://github.com/dotnet/corefx/pull/9901#issuecomment-231195645) [](ancestors = 231195645)

**Comment by joperezr** [comment]
Actually, this ones I copy over from coreclr's mscorlib reference assembly, and they are all WinRT types. You can see how coreclr also adds this Ifdefs in its reference assembly [here](https://github.com/dotnet/coreclr/blob/master/src/mscorlib/ref/mscorlib.cs#L11160)

---
In reply to: [231197120](https://github.com/dotnet/corefx/pull/9901#issuecomment-231197120) [](ancestors = 231197120,231195645)

**Comment by danmosemsft** [comment]
:shipit:

**Comment by joperezr** [comment]
@dotnet-bot test Innerloop CentOS7.1 Release Build and Test please

**Pull request merged**
