### PR TITLE
200 to uwp6.1

### PR DESCRIPTION
**Pull request by wtgodbe**
@HollyAM @karelz @nattress @weshaggard PTAL

This ports servicing changes from release/2.0.0 to UWP 6.1. I made some judgement calls on what should and shouldn't be ported, so there may be some needed changes to this PR. PTAL if anything stands out.

### CODE REVIEW

**Comment by wtgodbe** [comment]
@dotnet-bot help

**Comment by karelz** [comment]
@wtgodbe how do I tell which commits were skipped?

**Comment by wtgodbe** [comment]
@karelz I did this by resolving merge conflicts manually, not by cherry-picking (that is, I went file-by-file, not commit by commit). So I'm not sure.

**Comment by karelz** [comment]
I was referring to your mention of "judgement calls". If it was basic merge conflicts resolutions, I am fine.
@weshaggard any suggestion for code review strategies beside making sure UWP tests pass?

**Comment by wtgodbe** [comment]
@mmitche do you know how to run inner/outerloop CI tests in UWP 6.1?

**Comment by wtgodbe** [comment]
@weshaggard no need to line-by-line review this, but do you know of any obvious places I should check (e.g. MSBuild files) for changes I should/shouldn't have ported?

**Comment by wtgodbe** [comment]
@dotnet-bot test Outerloop netcoreapp Windows_NT Release

**Comment by wtgodbe** [comment]
@dotnet-bot test outerloop netcoreapp Windows_NT Release

**Comment by mmitche** [comment]
hmm, those should work if there is a branch entry in the repo list, let me check.

**Comment by mmitche** [comment]
@wtgodbe There was no entry.  Adding, should generate soon.

**Comment by wtgodbe** [comment]
@dotnet-bot test outerloop netcoreapp Ubuntu16.04 Release

**Comment by wtgodbe** [comment]
@dotnet-bot test outerloop netcoreapp OSX10.12 Release

**Comment by wtgodbe** [comment]
@dotnet-bot test outerloop netcoreapp PortableLinux Release

**Comment by weshaggard** [comment]
>@weshaggard no need to line-by-line review this, but do you know of any obvious places I should check (e.g. MSBuild files) for changes I should/shouldn't have ported?

Look for anything that enables/disable package builds. We should only be building/shipping the UWP package so ensure packages.builds file only contains that.

Beyond that were there any merge issues in particular you want someone to help look at closer?

**Comment by wtgodbe** [comment]
Nothing specific, I just wanted to know if there was anything you knew I should pay close attention to. packages.builds should be correct.

**Comment by wtgodbe** [comment]
@dotnet-bot test outerloop netcoreapp Windows_NT Release

**Comment by wtgodbe** [comment]
> 15:24:41 D:\j\workspace\windows-TGrou---ee38dc2b>call "D:\j\workspace\windows-TGrou---ee38dc2b\Tools\dotnetcli\dotnet.exe" restore "D:\j\workspace\windows-TGrou---ee38dc2b\packages\microsoft.dotnet.buildtools\2.0.0-uwp61-02602-01\lib\\tool-runtime\project.csproj" --source https://dotnet.myget.org/F/dotnet-core/api/v3/index.json --source https://dotnet.myget.org/F/dotnet-buildtools/api/v3/index.json --source https://api.nuget.org/v3/index.json  
15:24:41 D:\j\workspace\windows-TGrou---ee38dc2b\packages\microsoft.dotnet.buildtools\2.0.0-uwp61-02602-01\lib\tool-runtime\project.csproj : error NU1003: PackageTargetFallback and AssetTargetFallback cannot be used together. Remove PackageTargetFallback(deprecated) references from the project environment.

@weshaggard do we need to update uwp6.1 buildtools as well?

**Pull request closed without merging**
