### PR TITLE
Refactor ManagedWebSocket out of ClientWebSocket on Unix

### PR DESCRIPTION
**Pull request by stephentoub**
On Unix we use a managed implementation of WebSocket as the backing for ClientWebSocket.  We'd like to be able to share this same implementation with ASP.NET so that we have a single implementation of the protocol across client and server.  This change refactors out that support to make it more shareable.

I made a few tweaks to the ClientWebSocket code shared across platforms.  While we typically like to have argument validation be in the shared code, I moved the (minimal) argument validation into each of the Windows and managed-specific implementations of the PAL, so that the ManagedWebSocket implementation would perform that validation.

I also added support for masking on the server (the current implementation assumed that all sent messages should be masked and all received messages should not be, but a server needs the opposite), though that isn't tested, so we may have some issues to fix there subsequently.

I believe ASP.NET should be able to share just the ManagedWebSocket.cs and WebSocketValidate.cs files, plus define a handful of members on an SR type.  If this is too complicated to manage well, I can try to simplify it further.

cc: @anurse, @Tratcher, @ericeil, @davidsh, @cipop, @davidfowl

### CODE REVIEW

**Comment by stephentoub** [comment]
Test Innerloop Windows_NT Debug Build and Test please (HTTP test)

**Comment by stephentoub** [comment]
> would it be feasible to extract those into either a separate type or a partial class or something? Ideally I'd like to pull over entire files

At some point we'd need to pull the strings from the SR files that get generated by the corefx infrastructure from Strings.resx.  I can certainly put some intermediary in the middle if that helps, but something somewhere would still be accessing SR.*.

**Comment by anurse** [comment]
Meh, sounds like it's not worth it right now :). We'll make this work.

**Comment by anurse** [comment]
LGTM, but I'm reviewing primarily from a code-sharing/API perspective. I'm sure we'll do some further iterating together on the implementation after this is done and we can start sharing :).

**Comment by stephentoub** [comment]
> I'm sure we'll do some further iterating together on the implementation after this is done and we can start sharing 

Yup, definitely.  FWIW, I did do a quick perf comparison between this and the one in the aspnet/websockets repo, and at least in my informal measurements there's a nice bump in throughput and decrease in memory utilization, so hopefully this is in fact heading in the right direction.

**Comment by anurse** [comment]
Awesome! Good to hear!

**Comment by stephentoub** [comment]
Anyone else want to review this before I merge?

**Comment by ericeil** [comment]
Thought I'd already said this, but I guess not:  LGTM. :)

**Comment by stephentoub** [comment]
Thanks, Andrew and Eric.

**Pull request merged**
