### PR TITLE
Clean up dead code in System.Diagnostics*

### PR DESCRIPTION
**Pull request by xhoogland**
Removed dead code in Common, S.D.FileVersionInfo and S.D.Process for
issue #17905 to clean up the source.

### CODE REVIEW

**Comment by xhoogland** [comment]
Mmhh, interesting...

Build says it fails at some tests, but meanwhile I get the following error:
`D:\j\workspace\windows-TGrou---2a8f9c29>taskkill /F /IM VBCSCompiler.exe 
ERROR: The process "VBCSCompiler.exe" not found.`

**Comment by danmosemsft** [comment]
The hash code test failure is unrelated to your changes...someone will fix it..

**Comment by Anipik** [comment]
@dotnet-bot test NETFX x86 Release Build

**Comment by ViktorHofer** [comment]
The VBSC error is just a cleanup error which doesn't kill the build. The netfx failure is unrelated and will be fixed with https://github.com/dotnet/corefx/pull/32405

**Pull request merged**
