### PR TITLE
System.Drawing: Consolidate the FontFamily class

### PR DESCRIPTION
**Pull request by qmfrederik**
Use the Windows implementation of the `FontFamily` class for both Windows and Unix.
Update the P/Invoke declarations accordingly.

### CODE REVIEW

**Comment by qmfrederik** [comment]
@dotnet-bot test UWP CoreCLR x64 Debug Build

**Comment by qmfrederik** [comment]
The Linux failures seems consistent but I'm not sure I fully understand them:

```
Assert.Equal() Failure
Expected: FontFamily[] [[FontFamily: Name=DejaVu Serif], [FontFamily: Name=DejaVu Sans Mono], [FontFamily: Name=DejaVu Sans]]
Actual:   FontFamily[] [[FontFamily: Name=DejaVu Serif], [FontFamily: Name=DejaVu Sans Mono], [FontFamily: Name=DejaVu Sans]]
```

Additionally, the OS X tests pass which is strange.

**Comment by mellinoe** [comment]
@qmfrederik That may mean that the native handle for the font doesn't match. That value isn't being printed out. We are expecting that the same font will be cached into the same native handle, but perhaps libgdiplus is not always doing that.

Just a guess, though; I could be wrong.

**Comment by qmfrederik** [comment]
@dotnet-bot test Windows x64 Debug Build
@dotnet-bot test UWP NETNative x86 Release Build

**Comment by mellinoe** [comment]
@qmfrederik We should confirm whether my assumption above was correct, e.g. whether the native handles are different despite the other properties being identical. If that's the case, we should change the assertions slightly and make a note about the behavior difference.

**Comment by qmfrederik** [comment]
@mellinoe What confuses me is that the tests previously passed. I had a cursory look at the differences in implementation between Windows & Unix and couldn't immediately find any difference that would explain the difference in behavior.

I'll have a second look at this.

**Comment by mellinoe** [comment]
@qmfrederik I think I've seen similar things. Whether a cached or new handle is returned seems to be non-deterministic for some operations. If that's the case, then we can't rely on it being cached, and should accept either behavior.

**Comment by qmfrederik** [comment]
@mellinoe Yup, I observed the same behavior when porting Mono's test over. GDI+ (and libgdiplus) both try to cache handles for some well-known font families, but don't manage to always return the same handle. Plus, some System.Drawing code clones font families, resulting in a new handle all together.

I'll update the tests accordingly.

**Comment by qmfrederik** [comment]
@dotnet-bot test Linux x64 Release Build

**Comment by qmfrederik** [comment]
@dotnet-bot test Linux x64 Release Build

(Unrelated failures in System.Net.NameResolution.Tests)

**Comment by qmfrederik** [comment]
@mellinoe I think this one is ready for another review round :)

**Comment by karelz** [comment]
@safern can you please review while @mellinoe is OOF?

**Comment by safern** [comment]
> @safern can you please review while @mellinoe is OOF?

Yes I will later today.

**Pull request merged**
