### PR TITLE
Avoid three expensive allocations in UriHelper

### PR DESCRIPTION
**Pull request by stephentoub**
In this repro:
```C#
using System;
using System.Diagnostics;
using System.Text;

class Program
{
    static void Main()
    {
        string input = $"param1={GenerateUrlEncoded(40)}&param2={GenerateUrlEncoded(220)}";
        Console.WriteLine("Input length: " + input.Length);
        var sw = Stopwatch.StartNew();
        string result = Uri.UnescapeDataString(input);
        Console.WriteLine("Result length: " + result.Length);
        Console.WriteLine(sw.Elapsed);
    }

    private  static string GenerateUrlEncoded(int rowsCount)
    {
        var sb = new StringBuilder();
        for (int i = 0x100; i < 0x999; i++)
        {
            sb.Append((char)i);
            if (i % 10 == 0) sb.Append('<');
            if (i % 20 == 0) sb.Append('>');
            if (i % 15 == 0) sb.Append('\"');
        }

        string escaped = Uri.EscapeDataString(sb.ToString());
        sb.Clear();
        for (int i = 0; i < rowsCount; i++)
        {
            sb.AppendLine(escaped);
        }

        return sb.ToString();
    }
}
```
on my machine it ends up allocating ~630GB of memory and takes ~14 seconds.

Almost all of that ~14 seconds is spent in gc_heap::allocate_large, and most of that inside memset_repmovs.  This ends up being due to some large allocations being done in a tight loop.

This PR contains three simple fixes that address the majority of the problem.  There's still more that can be done here, but this is the lowest of the low-hanging fruit and makes the biggest impact:
1. In UnescapeString, the previous code was allocating a new char[bytes.Length] for each iteration.  Stop doing that.  Instead, just reuse the same array over and over and only grow it if it's smaller than is needed.
2. In MatchUTF8Sequence, the previous code was allocating a byte[] for each character or surrogate pair.  Stop doing that.  Instead, just use a reusable four-byte segment of stack.
3. In UnescapeString, the previous code was allocating a new UTF8Encoding for each iteration of the loop.  Stop doing that.  The object is thread-safe and can be used for all requests, so we just make it a static.

These changes drop that ~630GB to ~22MB and that ~14s to ~0.05s.

Subsequently, there's more memory-related changes that could be done in this code, e.g. using pooling, addressing some of the other allocation, but I've left that for the future.

Fixes https://github.com/dotnet/corefx/issues/36050
cc: @rmkerr, @davidsh, @GrabYourPitchforks 

(@GrabYourPitchforks, might be something you want to improve further subsequently with Rune as a validation for the APIs :)

### CODE REVIEW

**Comment by GrabYourPitchforks** [comment]
@stephentoub This is the second time today I've seen somebody solve the problem "Given a `ROS<char>` input, strip the first sequence and put it directly into a UTF-8 `Span<byte>`, then report the number of chars read and bytes written."

This is possible through the pair `char.IsSurrogate` / `Encoding.UTF8.GetBytes` as you had done. It's also possible through the `Rune.DecodeUtf16` / `Rune.EncodeUtf8` pair. I wonder though if there's a need to wrap this up in a one-shot helper method to make the call sites simpler. Something like:

```cs
OperationStatus Whatever.Utf16ToUtf8(ROS<char> src, Span<byte> dst, out int charsRead, out int bytesWritten);
```

(Would having to deal with `OperationStatus` as a return value make your life harder?)

**Comment by stephentoub** [comment]
@GrabYourPitchforks, the first thing I went looking for was the equivalent of Rune.GetRuneAt that I could use here, but the only overload available was one that took a string.  Had there been one that took a span, then I would have done:
```C#
Rune.GetRuneAt(input.Slice(index)).EncodeUtf8(output);
```
or some such thing.

**Comment by yahorsi** [comment]
Offtopic question, how do you guys profile in such scenarios? We have solution where we'd like ro understand how much time is spent on boxing/unboxing and at least VS2017/VS2019/dotTrace does not show me boxing stats.

**Comment by stephentoub** [comment]
> how do you guys profile in such scenarios? We have solution where we'd like ro understand how much time is spent on boxing/unboxing and at least VS2017/VS2019/dotTrace does not show me boxing stats.

How much boxing and how much time is spent boxing are two different questions.  For the former, I use either the Performance Wizard .NET memory allocation profiler in Visual Studio:
image
or the .NET Object Allocation Tracking profiler in Visual Studio (which is relatively new and is working to subsume the functionality from the previous tool):
image
or dotMemory (rather than dotTrace) or some other allocation-profiling tool.

For the latter, any of the CPU profiling tools in Visual Studio or dotTrace or PerfView or such profilers can show you how much time is being spent in routines like JIT_Box and in garbage collection.

**Pull request merged**
