### PR TITLE
Set genericParameterCount in MethodSignature

### PR DESCRIPTION
**Pull request by twsouthwick**
This addresses issue #1463

### CODE REVIEW

**Comment by akoeplinger** [comment]
FYI if you include a [special keyword](https://help.github.com/articles/closing-issues-via-commit-messages/) in the commit message the issue will be automatically closed when the PR is merged.

**Comment by twsouthwick** [comment]
Awesome - I hadn't used that before. I've amended the commit and pushed it.

**Comment by akoeplinger** [comment]
@twsouthwick seems like you made a typo, the commit message mentions `#1464`, but it should be `#1463` :)

**Comment by twsouthwick** [comment]
Ok - it should be right now.  Thanks for catching that!

**Comment by stephentoub** [comment]
Thanks for the fix, @twsouthwick.  Should this be against the master branch rather than against dev/metadata?  Also, seems like we're missing some tests, if for nothing else than to verify the properties of this type return what they're supposed to; mind adding some?

**Comment by stephentoub** [comment]
> Should this be against the master branch rather than against dev/metadata?

Nevermind; I see now that this code only exists in that branch.  LGTM.

**Comment by mellinoe** [comment]
Yes, please add a test to catch this

**Comment by twsouthwick** [comment]
Ok - I've added tests for this change.

**Comment by stephentoub** [comment]
LGTM

**Comment by mellinoe** [comment]
Thanks, Taylor, looks good to me as well.

**Comment by akoeplinger** [comment]
@twsouthwick in case you wonder why the issue didn't get closed by the keyword, that only works when the PR is merged into the default branch (i.e. `master`) and I missed that this targets `dev/metadata`, so sorry for the confusion :)

**Comment by twsouthwick** [comment]
Good to know.  I'll manually close it.

**Comment by nguerrera** [comment]
@twsouthwick Thanks!

**Pull request merged**
