### PR TITLE
Fixes build for undefined SRM symbol, type spec decoding

### PR DESCRIPTION
**Pull request by tmat**

### CODE REVIEW

**Comment by tmat** [comment]
@nguerrera

**Comment by nguerrera** [comment]
:+1:

**Comment by nguerrera** [comment]
This job looks stuck. It's been running for quite a while. cc @weshaggard

**Comment by stephentoub** [comment]
@dotnet-bot test this please

**Comment by stephentoub** [comment]
@dotnet-bot test this please

**Comment by stephentoub** [comment]
@dotnet-bot test this please

**Comment by stephentoub** [comment]
LGTM

**Pull request merged**
