### PR TITLE
Update Newtonsoft.Json to 13.0.1

### PR DESCRIPTION
**Pull request by ericstj**

### CODE REVIEW

**Review by carlossanlop — APPROVED** [review]

**Comment by danmoseley** [comment]
I assume only used by tests ? (No package authoring, etc)

**Comment by ericstj** [comment]
> I assume only used by tests ? (No package authoring, etc)

Yes, none of our shipping packages have a dependency on Newtonsoft.Json - only tests.  

Looks like there was a breaking change to Newtonsoft that we might need to react to here.  Will update once I identify the fix.

**Comment by danmoseley** [comment]
OK. Of course, no permission needed to merge as a test only change.

**Comment by ViktorHofer** [comment]
I requeued just the failing legs.

**Comment by danmoseley** [comment]
I looked through the failures and they seem to be test rot and missing test fixes made since. Nothing related to newtonsoft.

Given 3.1 is out of support in December, I'm not sure it's worth chasing up the test failures unless possibly it's a well known fix that's trivial to port.

I think we can merge this @ericstj

**Review by ViktorHofer — APPROVED** [review]
LGTM, ready to be merged.

**Comment by danmoseley** [comment]
Looks like https://dnceng.visualstudio.com/internal/_componentGovernance/dotnet-corefx?_a=alerts&typeId=8301794&alerts-view-option=active isn't updated yet

**Comment by carlossanlop** [comment]
The default page for that link is the 2.1 branch. We will have to fix the issue there too: https://dev.azure.com/dnceng/internal/_componentGovernance/dotnet-corefx?_a=alerts&typeId=8301794&alerts-view-option=active

I don't see the Newtonsoft warning for 3.1: https://dev.azure.com/dnceng/internal/_componentGovernance/dotnet-corefx?_a=alerts&typeId=11624788&alerts-view-option=active

**Comment by danmoseley** [comment]
Ah, could you throw up a PR for 2.1? we should check with @ericstj before merging it though, maybe there was a reason.

**Comment by carlossanlop** [comment]
Sure, I can submit a PR. I think I should send it to the internal branch directly. The governance warning is happening there anyway.

**Comment by danmoseley** [comment]
sounds good. there are also some other things at the query above, I'll check with @ericstj when he's back.

**Pull request merged**
