### PR TITLE
Named Multiply and Divide methods on TimeSpan

### LINKED ISSUE #16476: API Proposal: Named Multiply and Divide on type TimeSpan
#7175 proposes, and dotnet/coreclr#9804 and #16475 provide `/` and `*` operators for `TimeSpan`.

For all previous operators on `TimeSpan` the policy of [CA2225](https://msdn.microsoft.com/en-us/library/ms182355.aspx) was followed by having named alternative methods for the operation, allowing languages which did not honour operator overloading to use the same functionality. This should be done for the new operators as well.

```C#
namespace System
{
    public struct TimeSpan
    {
        public TimeSpan Multiply(double factor);
        public TimeSpan Divide(double divisor);
        public double Divide(TimeSpan ts);
    }
}
```

Functionally these methods should behave identically to the operators dotnet/coreclr#9804 adds.

### PR DESCRIPTION
**Pull request by JonHanna**
Update refs and add tests.

Closes #16476

Won't pass CI until dotnet/coreclr#10366 and dotnet/corert#3052 are in.

### CODE REVIEW

**Comment by AlexGhiondea** [comment]
The change looks good -- we just need the updated CoreCLR.

Thanks for doing this @JonHanna !

**Comment by JonHanna** [comment]
Test this, please.

**Comment by JonHanna** [comment]
Test Vertical uapaot Build

**Comment by JonHanna** [comment]
Which update type is it that will make the corert changes available?

**Comment by joperezr** [comment]
@JonHanna did you make corert changes for this as well? if you don't add the Api in there, we have to either make this API netcoreapp-specific or we would have to baseline it for now while we make the changes in corert

**Comment by JonHanna** [comment]
@joperezr  dotnet/corert#3052

**Comment by joperezr** [comment]
Looks like the latest TargetingPack for NETNative doesn't have your change yet, since I downloaded it and the methods aren't there yet. I can't really check for sure since I cannot see the commit hash that was used to build System.Private.CoreLib but I will suggest to wait until our next package build and then re-run those two CI jobs.

**Comment by stephentoub** [comment]
@dotnet-bot test this please

**Comment by JonHanna** [comment]
Test Innerloop OSX10.12 Release x64 Build and Test please

(Build timed out).

**Comment by stephentoub** [comment]
Thanks, @JonHanna.

**Pull request merged**
