### PR TITLE
Remove DangerousTryGetArray and hide DangerousGetPinnableReference

### PR DESCRIPTION
**Pull request by ahsonkhan**
Fixes:
https://github.com/dotnet/corefx/issues/25412
https://github.com/dotnet/corefx/issues/25615

Also fixes https://github.com/dotnet/corefx/issues/23881

**Depends on the following PR (hence blocked):** https://github.com/dotnet/coreclr/pull/15557

Following the staging plan from here: https://github.com/dotnet/corefx/issues/23881#issuecomment-343767740

- [x] Add MemoryExtensions.GetReference/TryGetArray
- [x] Convert all uses of DangerousGetPinnableReference/DangerousTryGetArray in coreclr, corefx, corert, corefxlab, aspnet, ... to MemoryExtensions.GetReference
- [x] Change DangerousGetPinnableReference to whatever we like to make it fit the pinning pattern and remove DangerousTryGetArray.

Doing it this way will avoid the need for complex staging or things being on the floor for extensive periods of time.

cc @jkotas, @stephentoub, @KrzysztofCwalina, @davidfowl

### CODE REVIEW

**Comment by ahsonkhan** [comment]
@dotnet-bot test this please

**Comment by benaadams** [comment]
@dotnet-bot test this please

**Comment by ahsonkhan** [comment]
Cherry-picked into https://github.com/dotnet/corefx/pull/26041

**Comment by benaadams** [comment]
`ubuntu1404-20170120` gets some heavy queuing: `5 hr 53 min waiting in the queue`; not sure load is evenly distributed across build agents

**Pull request merged**
