### PR TITLE
Fix edge cases with Complex.Acos and Complex.Asin

### PR DESCRIPTION
**Pull request by leppie**
Acos where imaginary part is zero and real part is positive.
Acos where imaginary part is negative.

Asin where imaginary part is zero and real part is negative.
Asin where imaginary part is positive.

Previously reported @ https://connect.microsoft.com/VisualStudio/feedback/details/790328

### CODE REVIEW

**Comment by leppie** [comment]
Not sure what is going on here with the failure. Seems build 253 is making my build 255 break... Something is fishy.

**Comment by krwq** [comment]
@dotnet-bot test this please

**Comment by leppie** [comment]
@krwq thanks, but for some unknown daft reason the build server if failing... it seems to be trying older builds?

**Comment by stephentoub** [comment]
@dotnet-bot test this please

**Comment by leppie** [comment]
Verification:
http://www.wolframalpha.com/input/?i=acos%281234000000%29
http://www.wolframalpha.com/input/?i=acos%28-1234000000i%29
http://www.wolframalpha.com/input/?i=asin%28-1234000000%29
http://www.wolframalpha.com/input/?i=asin%281234000000i%29

**Comment by mellinoe** [comment]
This looks like a good fix, thanks for taking the time to add test cases and provide verification. Also, it looks like the merge build succeeded. Give me a bit to look this over (and brush up on my trigonometry) and I will get it merged in.

**Comment by leppie** [comment]
Thanks, but why I am not listed as the author for the commit?

**Comment by stephentoub** [comment]
You are the author of the commits, and you'll see them and the attribution if you look back in the commit history for the master branch. You're just not the author of the merge, since Eric was the one to commit the merge.

**Comment by leppie** [comment]
@stephentoub: Doh! I had to scroll down to when it was created (oops ;p) Thanks for making me look. All good :+1:

**Comment by stephentoub** [comment]
:smile:

**Pull request merged**
