### PR TITLE
Expose System.Reflection APIs in TypeInfo and MethodInfo

### PR DESCRIPTION
**Pull request by pallavit**
Expose TypeInfo and MethodInfo APIs tracked by the Issue #5381.

The PR - #6524 brought in the necessary runtime changes for the same.

### CODE REVIEW

**Comment by pallavit** [comment]
Looks like System.Net.Sockets.Tests failed with the following:

> Unhandled Exception: Xunit.Sdk.EqualException: Assert.Equal() Failure
Expected: Success
Actual:   OperationAborted
error: One or more tests failed while running tests from 'System.Net.Sockets.Tests'.  Exit code 134.
Finished:    System.Net.Requests.Tests

@dotnet-bot test Innerloop OSX Debug Build and Test please.

**Comment by pallavit** [comment]
/cc: @weshaggard , @AtsushiKan can you please take a look.

**Comment by AtsushiKan** [comment]
LGTM

**Comment by weshaggard** [comment]
I didn't verify all the APIs match what we reviewed (I assume you did that :)) otherwise LGTM

**Comment by pallavit** [comment]
Thanks for the review :)

**Comment by ericstj** [comment]
This added BindingFlags which conflicts with the BindingFlags defined in https://github.com/dotnet/corefx/blob/master/src/System.Reflection.TypeExtensions/ref/System.Reflection.TypeExtensions.cs.  Was it your intent to forward this down out of TypeExtensions?

**Comment by ericstj** [comment]
This is breaking the netcore50 build of System.Reflection.Extensions when updating packages.  S.R.E references S.R.TypeExtensions (project ref) on NetCore50 and the binding flags types collide.
This is also breaking tests that build against both S.R and S.R.TE.

**Comment by pallavit** [comment]
>  Was it your intent to forward this down out of TypeExtensions?

Yes. I will be doing that eventually. Since, I did not see any issues currently, I thought of doing it in phases. 

> This is breaking the netcore50 build of System.Reflection.Extensions when updating packages

I did not see any build issues in both open and TFS. Can you tell me how you are doing this? It will help me repro and fix the issue.

**Comment by weshaggard** [comment]
The issue comes when we try to update the corefx to use the new packages with this change. Now people see BindingFlags in both reference assemblies and build fails.

**Comment by pallavit** [comment]
Ahh i see. I will get a fix ready.

**Comment by ericstj** [comment]
Thanks Pallavi

**Comment by pallavit** [comment]
@ericstj Did you want to move to a particular build no or can I just move corefx to the latest 903?

**Comment by ericstj** [comment]
I was doing 903 + changes I made this morning using a private build (to test out my changes).  But getting it on 903 would be fine and should repro the issue.

**Pull request merged**
