### PR TITLE
Add a failing test for XObject.SkipNotify()

### PR DESCRIPTION
**Pull request by alexandrnikitin**
Added tests for #54 (Remove always true "if" and unreachable code in System.Xml.Linq.XObject.SkipNotify method.)
Tests fails because XObject.Annotations<T>() returns an enumerator object which is always not null.

### CODE REVIEW

**Comment by stephentoub** [comment]
@alexandrnikitin, thanks, now that you've incorporated this into #54, this PR can be closed, correct?

**Comment by alexandrnikitin** [comment]
@stephentoub if you are good with the fix #601 then yes. But I would prefer to merge tests first. BTW, how do you mark failing tests to not include in the main CI builds?

**Comment by stephentoub** [comment]
> how do you mark failing tests to not include in the main CI builds?

You should be able to mark it as an [ActiveIssue], e.g.
https://github.com/dotnet/corefx/blob/master/src/System.Reflection.Metadata/tests/Metadata/MetadataReaderTests.cs#L2443

> if you are good with the fix #601 

@krwq should probably be the one to review.

**Comment by krwq** [comment]
I have some more tests pending for XDocument and will take a look at the PRs once they are here.

**Comment by krwq** [comment]
@dotnet-bot test this please

**Comment by krwq** [comment]
We just merged v1.0 to master and looks like you got some conflic. Please update the PR. Since the XDoc tests are in I will take a look at this PR soon as you update it.

**Comment by alexandrnikitin** [comment]
@krwq I'm sorry but I can't figure out where to put my tests. Where are tests for `System.Xml.XDocument` project and its classes?

I write unit tests following the project structure, e.g. for the class in `System.Xml.XDocument\System\Xml\Linq\XObject.cs` I put unit tests in `System.Xml.XDocument.Tests\System\Xml\Linq\XObjectTests.cs`. Do you have convention how you write unit tests in your team?

**Comment by krwq** [comment]
@alexandrnikitin, Either add a new file into any of the existing projects (if category sounds correct) or create a new project System.Xml.XDocument.Tests and add it there. Please use the standard [Fact]. The way the existing tests are written is quite horrifying and please don't write them the same way - they were converted from one test harness to another (I guess few times) and now we have a huge mess :)

The only conventions I can think of is to name the test like:
ActionResult
i.e: LoadingXDocumentFromNullStreamThrows
You can skip XDocument part if the combination of class name and test name is descriptive. Following your intuition is usually ok.
long names of the tests are ok as long as they are not verbosely descriptive. Tests should cover whatever name says. As long as the test adds value it is fine to add a new one. Long tests are usually not ok unless you are writing stress tests.

**Comment by alexandrnikitin** [comment]
I couldn't add a new project for these tests. Feel powerless and miserable :tired_face:
Added tests to `TreeManipulation.Tests` projects that seems good for them.

**Comment by stephentoub** [comment]
@alexandrnikitin / @krwq, what's the status of this PR?  Should it be merged? Closed? etc. (Thanks.)

**Comment by alexandrnikitin** [comment]
@stephentoub I want it to be merged :smile:

**Comment by akoeplinger** [comment]
@alexandrnikitin can you rebase this on top of master and fix the merge conflicts?

**Comment by alexandrnikitin** [comment]
Created a new #1516 PR for that.

**Comment by stephentoub** [comment]
Replaced by #1516.

**Pull request closed without merging**
