### PR TITLE
Change System.IO.Compression Interop references

### LINKED ISSUE #33774: Properly factor DllImports into Common\src\Interop
We now have a bunch of libraries with their own DllImports, whereas the expected approach is that all DllImports in product src should be included from src\Common\src\Interop, appropriately factored by platform and library, and then those source files included into the relevant assemblies that need them.

- [ ] Microsoft.Diagnostics.Tracing.EventSource.Redist
- [ ] System.Data.SqlClient
- [ ] System.Diagnostics.EventLog
- [ ] System.DirectoryServices
- [ ] System.DirectoryServices.AccountManagement
- [ ] System.DirectoryServices.Protocols
- [ ] System.Drawing.Common
- [ ] System.IO.Compression
- [ ] System.IO.Compression.Brotli
- [ ] System.IO.Ports
- [ ] System.Management
- [ ] System.Reflection.Metadata
- [ ] System.Runtime.Caching
- [ ] System.Security.Cryptography.Csp
- [ ] System.Security.Cryptography.Pkcs
- [ ] System.Security.Cryptography.X509Certificates

This all needs to be refactored and dedup'd.

https://github.com/dotnet/corefx/blob/master/Documentation/coding-guidelines/interop-guidelines.md

### PR DESCRIPTION
**Pull request by eanova**
One effect of this change is to create a new directory Windows/ZLib.  I chose uppercase to match the rest of the Windows directory.

Fixes #33774

### CODE REVIEW

**Comment by stephentoub** [comment]
This is going to break Unix builds.  This interop file is used across all platforms, not just Windows.

**Comment by carlossanlop** [comment]
Hello Erhan, would you mind explaining the purpose of your change a bit more?

**Comment by eanova** [comment]
@carlossanlop I was trying to fix issue#33774. I guess I should see what I can do under linux to fix this?

**Comment by ViktorHofer** [comment]
@eanova I recommend to move that file directly into the Interop folder: `corefx/src/Common/src/Interop/Interop.ZLib.cs`.

**Comment by eanova** [comment]
Hey guys just wanted to touch base.  Super busy,  but I finally got all the target environments setup locally.

@ViktorHofer I'll check on that.

**Comment by ViktorHofer** [comment]
Maybe it helps, you don't need to setup "all" environments locally, you can use CI for testing (at least if you are confident that your changes make sense).

**Pull request closed without merging**
