### PR TITLE
Fix compile error on FreeBSD

### PR DESCRIPTION
**Pull request by sec**
This will allow native part to compile without errors on FreeBSD - related to https://github.com/dotnet/corefx/issues/1626
Command used to build:
`src/Native/build-native.sh freebsd x64 debug cmakeargs -DHAVE_IN_PKTINFO=0`

### CODE REVIEW

**Comment by stephentoub** [comment]
Thanks, @sec.  The change LGTM, but for the record, what compilation error were you getting that this fixed?

**Comment by stephentoub** [comment]
cc: @janvorli

**Comment by janvorli** [comment]
@sec, the cmakeargs -DHAVE_IN_PKTINFO=0 is not needed anymore, I have merged in a fix recently.

**Comment by janvorli** [comment]
@stephentoub the error reported was the warning that the `#pragma clang diagnostic ignored "-Wthread-safety-analysis"` disables. For some reason, clang on FreeBSD considers the last "if" in the function part of the lock releasing code and complains with the thread safety warning (as error). That's why the end of the pragma range needed to be moved to cover that.

**Comment by sec** [comment]
@stephentoub Hi. Yes it was the error @janvorli mentioned.

**Pull request merged**
