### PR TITLE
Fix Connection Resiliency in SqlClient

### PR DESCRIPTION
**Pull request by cheenamalhotra**
Backports PR https://github.com/dotnet/SqlClient/pull/310 to System.Data.SqlClient

### CODE REVIEW

**Review by David-Engel — APPROVED** [review]

**Comment by ericstj** [comment]
CoreFx is currently no longer the proper repository for library changes moving forward.  Please see https://github.com/dotnet/coreclr/issues/27549

**Comment by cheenamalhotra** [comment]
Ok I will re-create PR for 'master' branch in dotnet/runtime. 
How about servicing branches (release/3.1, 3.0, 2.1)? Can we continue to make PRs for them here?

**Comment by ericstj** [comment]
Yes, all servicing remains in corefx.

**Comment by cheenamalhotra** [comment]
Moved to https://github.com/dotnet/runtime/pull/62

**Pull request closed without merging**
