### PR TITLE
New incorrect test revealing a problem in `RSA.Dispose()` on OS X.

### PR DESCRIPTION
**Pull request by baulig**
In .NET 4.x, the `X509Certificate2.PublicKey.Key` property returned a reference instead
of a copy of the key, so disposing it would cause subsequent usages to throw:

    cert.PublicKey.Key.Dispose();
    using(var rsa = cert.PublicKey.Key as RSA)
        rsa.Encrypt(data, padding);

This behavior seems to have changed in corefx and you can now do

    using(var rsa = cert.PublicKey.Key as RSA)
        rsa.Encrypt(data, padding);
    using(var rsa = cert.PublicKey.Key as RSA)
        rsa.Encrypt(data, padding);

However, the `X509Certificate2.PrivateKey` property still returns a reference, so
this still fails:

    cert.PrivateKey.Dispose();
    using (var rsa = cert.PrivateKey as RSA)
        rsa.Decrypt(encrypted, padding);

We also do not throw `ObjectDisposedException`, but some internal exception type from
within the native PAL.

This PR simply documents the existing behavior by adding a new test for it.

### CODE REVIEW

**Comment by baulig** [comment]
Quite interesting looking at the build results and then comparing them with the source code.  My initial assumption was obviously wrong.

Looking at [`PublicKey.Key`](https://github.com/dotnet/corefx/blob/master/src/System.Security.Cryptography.X509Certificates/src/System/Security/Cryptography/X509Certificates/PublicKey.cs#L26) reveals that it actually caches the value, so calling `Dispose()` on it invalidates it.

However, considering that the `PublicKey` class is not platform-specific, this new test should consequently fail on all platforms - but it passes on OS X.  The only possible explanation that I have is that on OS X, calling `RSA.Dispose()` somehow does not invalidate the key.

Running this locally, I could actually confirm that you can do the following on OS X:

```
                using (var rsa = cert.PublicKey.Key as RSA)
                {
                    rsa.Dispose();
                    rsa.Dispose();
                    rsa.Dispose();
                    rsa.Dispose();
                    rsa.Dispose();
                    rsa.Dispose();
                    rsa.Dispose();
                    encrypted = rsa.Encrypt(src, padding);
                }
```

This broken test also reveals that we're throwing different exception types on different platforms - it even differs on different versions of Windows, it seems.

**Comment by bartonjs** [comment]
Presumably the problem is that it's not noticing the difference between "I haven't had to generate or import a key yet" and "I disposed my key", which is something that would be good to fix.

**Comment by karelz** [comment]
No activity for 3 weeks. What is the next step for this PR? @bartonjs do you expect changes before it can be merged?

**Comment by bartonjs** [comment]
Well, the test doesn't pass (which matches the title).

Since it was opened as a PR (instead of an issue) I guess I expected @baulig to follow up with a commit that made the test work as expected; but really I didn't look too deeply since the PR wasn't passing.

**Comment by baulig** [comment]
I'll file an issue for this.

**Pull request closed without merging**
