### PR TITLE
Fix a CompareAttribute.Validate problem

### LINKED ISSUE #11025: CompareAttribute throws TargetParameterCountException and ArgumentException
The following tests demonstrate the bugs, discovered in #10992 

```
[Fact]
public static void Property_HasIndexParameters_ThrowsParameterCountException()
{
    ValidationContext context = new ValidationContext(new CompareObject("a")) { DisplayName = "CurrentProperty" };
    CompareAttribute = new CompareAttribute("Item");
    Assert.Throws<TargetParameterCountException>(() => attribute.Validate("b", context));
}

[Fact]
public static void Property_SetOnly_ThrowsArgumentException()
{
    ValidationContext context = new ValidationContext(new CompareObject("a")) { DisplayName = "CurrentProperty" };
    CompareAttribute = new CompareAttribute("SetOnlyProperty");
    Assert.Throws<ArgumentException>(() => attribute.Validate("b", context));
}

private class CompareObject
{
    public string this[int index] { get { return "abc"; } set { } }
    public string SetOnlyProperty { set { } }
}
```

This is because the check [here](https://github.com/dotnet/corefx/blob/master/src/System.ComponentModel.Annotations/src/System/ComponentModel/DataAnnotations/CompareAttribute.cs#L70) for index parameters occurs **after** we call `PropertyInfo.GetValue` [here](https://github.com/dotnet/corefx/blob/master/src/System.ComponentModel.Annotations/src/System/ComponentModel/DataAnnotations/CompareAttribute.cs#L51)

We should also add a check to make sure we can read the property before calling `GetValue`.

In both these cases, we should instead return `false` for `IsValid`

/cc @stephentoub

### PR DESCRIPTION
**Pull request by hughbe**
Fixes #11025

### CODE REVIEW

**Comment by danmosemsft** [comment]
@divega @ajcvickers @lajones could you please review and merge if appropriate?

**Comment by karelz** [comment]
@divega @ajcvickers @lajones ping?

**Comment by danmosemsft** [comment]
@divega @ajcvickers @lajones

**Comment by hughbe** [comment]
I'm not sure if there is a point to fixing this one to be honest - it's an unnecessary divergence from netfx that doesn't really add much value in hindsight.
I only brought it up because there is a check for `!GetIndexParameters.Any()` so it's obvious the intention when writing this code was to throw an ArgumentException.
However, this intention was never tested so that check is never reached - it's dead code right now.

Maybe the best thing to do is to keep the current behaviour, and just remove the check for index parameters, as it's never reached anyway - a TargetParameterCount exception is thrown before this codepath is hit.

**Comment by danmosemsft** [comment]
merged as @ajcvickers signed off -- thanks @hughbe

**Pull request merged**
