### PR TITLE
Add back null checks to File.Encrypt/Decrypt

### PR DESCRIPTION
**Pull request by stephentoub**
Undoing a small part of https://github.com/dotnet/corefx/pull/31763, per https://github.com/dotnet/corefx/pull/31763#discussion_r219883563.

cc: @pjanotti

### CODE REVIEW

**Comment by jkotas** [comment]
Re-enable the tests that check this throws null reference exception on all platforms?

**Comment by jkotas** [comment]
https://github.com/dotnet/corefx/blob/master/src/System.IO.FileSystem/tests/File/EncryptDecrypt.cs#L14

**Comment by pjanotti** [comment]
> Re-enable the tests that check this throws ArgumentNullException on all platforms?

 I was assuming that if in the end there was a PNSE for a given platform it was better to throw it as soon as possible, on that platform, instead of after parameter validation.

**Comment by stephentoub** [comment]
> Re-enable the tests that check this throws ArgumentNullException on all platforms?

Yup, thanks.

**Pull request merged**
