### PR TITLE
StackTrace.GetFrames should return an array of non-nullable frames

### LINKED ISSUE #42422: Why does StackTrace.GetFrames() return `StackFrame?[]` instead of `StackFrame[]`?
Under what circumstances can the array returned by `StackTrace.GetFrames()` contain a null element? I couldn't figure out how to write any test that would trigger this behavior.

### PR DESCRIPTION
**Pull request by jnm2**
Fixes #42422

### CODE REVIEW

**Review by stephentoub — APPROVED** [review]
Thanks.

cc: @safern

**Review by safern — APPROVED** [review]
Thanks!

**Comment by stephentoub** [comment]
Actually, @jnm2, I just noticed this is a PR into corefx but it's changing source that's only compiled in corelib.  The ref change here is fine, but can you please revert the changes under src/Common and submit a PR to coreclr that makes those changes?  Thanks.

**Comment by jnm2** [comment]
Sure: https://github.com/dotnet/coreclr/pull/27787

**Review by stephentoub — APPROVED** [review]

**Review by safern — APPROVED** [review]

**Pull request merged**
