### PR TITLE
Temporarily disable CentOS PR legs

### PR DESCRIPTION
**Pull request by stephentoub**
#6240
cc: @mmitche

### CODE REVIEW

**Comment by stephentoub** [comment]
test ci please

**Comment by weshaggard** [comment]
@stephentoub would it make more sense to disable the failing test as opposed to the entire leg? Or is it set of/all tests failing?

**Comment by stephentoub** [comment]
@weshaggard, we could disable the TextWriterTraceListenerTests suite, which appears to be the one failing (basically all of its tests), but we don't currently have the ability to disable at a finer granularity than "Linux", so we'd be disabling for the other Linux runs as well.  Would you prefer that?

**Comment by stephentoub** [comment]
That said, doing it that way would likely help to "unblock" existing PRs which already have a CentOS leg.  Ok, I'll switch to that, and hopefully we can get whatever the issue is fixed in the interim.

**Comment by weshaggard** [comment]
I kind of would prefer that option more so that we can still get CentOS coverage which I think is more important than TraceSource coverage.

**Pull request closed without merging**
