### PR TITLE
Update to buildtools 2.0.0-prerelease-01928-01

### PR DESCRIPTION
**Pull request by ericstj**
This brings the latest compiler to our desktop-MSBuild builds as well.

I had to fix one instance of an unused field in the networking code.
I checked and that field was present in desktop to control logging all
consuming codepaths are missing from core.

/cc @weshaggard @joperezr @benaadams

### CODE REVIEW

**Comment by ericstj** [comment]
UAP builds are broken because compiler is requiring an mscorlib facade to map types from Windows.winmd > System.Runtime.  It looks like @weshaggard deleted the facade with this commit: db6e8c950c3c7c35034cf8fd6346cdf0c198f238.  We may need to bring that back...

/cc @jaredpar since this is another semi-breaking compiler change, though one our customers will never likely see.

**Comment by jaredpar** [comment]
At a glance that looks like expected behavior vs. a change. The facade was deleted, it contained types necessary for compilation and the compiler errors as a result.

**Comment by ericstj** [comment]
The breaking behavior seems to be that before the compiler didn't traverse the Windows.winmd types when compiling things like this https://github.com/dotnet/corefx/blob/02f9abf08f0d21d1ff928817db807e0eb6f6adea/src/System.Runtime.WindowsRuntime/ref/System.Runtime.WindowsRuntime.cs#L51.  It didn't need to know that the Windows type `Windows.Storage.CreationCollisionOption` that derived from `Enum` was the same `Enum` that lives in System.Runtime.  Though, IIRC we have seen various changes in the past where the compiler gets more or less aggressive in resolving types at compile time and the line we've always stuck to is that the only supported thing is to have a full compile closure.

**Comment by jaredpar** [comment]
> It didn't need to know that the Windows type Windows.Storage.CreationCollisionOption that derived from Enum was the same Enum that lives in System.Runtime.

Gotcha. I'm a bit surprised this worked before. Overall though this is a tricky area. Ensuring that overload resolution is "correct" while dealing with signatures that have missing types is ... fun. We try and hold the line on what assemblies we require between releases but occasionally or hand gets forced here in order to fix bugs in the compiler. 

> the line we've always stuck to is that the only supported thing is to have a full compile closure.

This makes the compiler happy 😄

**Pull request merged**
