### PR TITLE
Update packages to support UWP at NETStandard1.4

### LINKED ISSUE #5842: Consuming CoreFx packages on desktop
We currently run into a couple issues consuming CoreFx packages on desktop:
1. ResolveAssemblyReferences (RAR) doesn't unify facade revisions in the same way the desktop loader does.  This results in binding redirects incorrectly being emitted rather than ignoring the difference and unifying to the inbox version.  For example System.Runtime 4.0.21.0 will be unified to the 4.0.0.0 assembly by the desktop loader, but RAR will see multiple revisions (eg: 4.0.0.0 and 4.0.21.0) and emit a binding redirect.
2. ImplicitlyExpandDesigntimeFacades is adding facades when we want out-of-band facades from the packages to be preferred.  The result is that the compiler will see two copies of the same assembly.  This happens because it runs late, after RAR so there is no point to consider the different versions of inbox and out-of-band facades and choose the higher-versioned out of band facades.

To solve issue 1 we could try to change RAR to honor the desktop unification policy but that is a very risky change and could only be done in the latest version of VS.  Instead I'd like to change how we version assemblies which are inbox on desktop.

Today we apply uniform versioning policy to all assembly versions, that policy is tied to SemVer as well as the desktop unification rules.
1. Bug-fix changes that don't impact surface area are revision changes (3rd part)
2. API changes or moves from inbox to out of box are minor version changes (2nd part).
3. Major version is primarily for branding or breaking changes (though we currently never intend to have breaking changes for all stable assemblies).

I suggest we relax the first constraint for assemblies that also ship inbox in desktop.  In other words, if the assembly major.minor version is part of the desktop framework, never change revision.  One of the main reasons we change the revision is to guarantee uniqueness of the assembly should someone decide to put it in the GAC.  This isn't really an issue for the desktop assemblies since the OS places them in the GAC and they should be protected so that folks cannot overwrite them outside of an OS patch.  Also, we'll never ship a substantial revision to these that needs to be delivered to desktop without changing the minor version since we'd need to break out of unification.  This does complicate the package build a bit but its better to absorb that compexity in our own package build than push that complexity out to developers.

To solve issue 2 we need a fix for ImplicitlyExpandDesigntimeFacades.  At a minimum we can disable this to unblock folks.  A better fix is to update the inbox targets to only add facades that don't overlap with the output of RAR, similar to how the nuget targets only add framework references for those assemblies which don't overlap with the resolved dlls.  If folks need that fix without an update to VS we can share the updated targets.

### PR DESCRIPTION
**Pull request by ericstj**
Fixes #5842, #5843 

Update packages in shared-library to use the RTM binaries so as not to break shared library.  In cases where this resulted in less surface than is currently in the live build, move that surface area to netstandard1.5.

To do this I had to move reference assembly versions back to the version from RTM, incidentally fixing #5842.

/cc @weshaggard @pallavit

### CODE REVIEW

**Comment by ericstj** [comment]
@dotnet-bot please test Innerloop Ubuntu Debug Build and Test

**Comment by ericstj** [comment]
@dotnet-bot please test Innerloop Ubuntu Debug Build and Test

**Comment by ericstj** [comment]
@dotnet-bot please test  Innerloop Windows_NT Debug Build and Test

**Comment by stephentoub** [comment]
@ericstj, that sockets workaround is going to need to remain until changes that got checked in yesterday consumable in the packages.  I just merged that workaround yesterday.

**Comment by ericstj** [comment]
@stephentoub I see.  It was actually causing an issue in this PR.  See http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/ubuntu_release_tst_prtest/2873/consoleFull#-21371504001f1a4601-6aec-4fd5-b678-78d4389fd5e8.  Let me think about how I can avoid that.

**Comment by pallavit** [comment]
>  In cases where this resulted in less surface than is currently in the live build, move that surface area to netstandard1.5.

@ericstj I expected this change to also impact System.Reflection package, however I only see S.R.TE and S.R.E being updated. Should I update it separately?

**Comment by ericstj** [comment]
System.Reflection is not currently part of shared lib so I didn't update that one.  Let me pick that up as another commit.

**Comment by pallavit** [comment]
> System.Reflection is not currently part of shared lib so I didn't update that one. Let me pick that up as another commit.

That explains it. I was just curious why we included other Reflection packages. I can take a stab at it as well once this gets checked-in.

**Comment by ericstj** [comment]
@pallavit I added a commit that gave System.Reflection the same treatment.

**Comment by pallavit** [comment]
Thanks @ericstj

**Pull request merged**
