### PR TITLE
 Add support for trailing commas within Utf8JsonReader

### PR DESCRIPTION
**Pull request by ahsonkhan**
Fixes https://github.com/dotnet/corefx/issues/34794.

Note that: `"[,]"` is still considered **invalid** (just like `"{,}"`). Json.NET allows `"[,]"`, specifically, but that did not seem consistent to me.

Please review the test cases, specifically, for expected behavior: https://github.com/dotnet/corefx/blob/76a2a65d8ee9f98842973ed15b422338a05e506e/src/System.Text.Json/tests/Utf8JsonReaderTests.cs#L2576-L2684

Only trailing commas **within** an object/array are allowed.

cc @JamesNK, @bartonjs

### CODE REVIEW

**Comment by ahsonkhan** [comment]
cc @steveharter, if this option needs to be used/exposed by the deserializer.

**Comment by ahsonkhan** [comment]
The `System.Drawing.Common.Tests` crashes is a known issue: https://github.com/dotnet/corefx/issues/36683

**Comment by JamesNK** [comment]
`"[,]"` is valid in JavaScript. The end result is 1 length array containing an undefined. But I don't think you need to support that.

**Comment by ahsonkhan** [comment]
Since only the drawing tests are failing in CI (https://mc.dot.net/#/user/dotnet-bot/pr~2Fdotnet~2Fcorefx~2Frefs~2Fpull~2F36690~2Fmerge/test~2Ffunctional~2Fcli~2F/20190408.1/workItem/System.Drawing.Common.Tests), I am going to merge this in so up-stack consumers can leverage this option. Please still feel free to review and I will address the feedback separately, especially if it's critical.

**Pull request merged**
