### PR TITLE
Fixed Case Sensitive Issues in System.Data.OleDb

### PR DESCRIPTION
**Pull request by eanova**
CaseSenstive issues were preventing an -allConfigurations build on Ubuntu 18.04

### CODE REVIEW

**Comment by joperezr** [comment]
> this does make the casing consistent, but I am not clear why that broke allconfigurations builds. Usually it's an issue for Unix builds. @joperezr Jose Perez Rodriguez FTE?

I suppose the allconfigurations build was a one-off thing as I see that it is not happening anymore and wasn't able to get to the logs through AzDevOps. If you see that issue again please tag me so I can investigate.

**Comment by maryamariyan** [comment]
Failure is unrelated to this change, is test failure on `System.Net.Http.Functional.Tests`

**Comment by eanova** [comment]
Thanks to everyone for reviewing!

**Comment by eanova** [comment]
Hi @joeprezr,

Looks like this issue is back.  Currently the file has been renamed back to DBBindings.cs and won't allow a compile on Ubuntu 19.04.

Thanks!

**Comment by joperezr** [comment]
@eanova I see thanks for catching. Feel free to send a new PR with the fix. I see that latest PRs in corefx are passing, so I wonder if this is still a problem.

**Pull request merged**
