### PR TITLE
[release/2.0.0] Remove reference assemblies from NetFx netstandard support package

### PR DESCRIPTION
**Pull request by ericstj**
Multiple tools in .NETFramework projects are attempting to load references
for execution which fails for reference assemblies.

To work better with these tools, don't use reference assemblies in the support
package.

Note: this only fixes the problem in our support package, and this change will need to be ingested by SDK in order to work.  We should also consider making a change to our standalone packages.

/cc @weshaggard 

Related: https://github.com/dotnet/sdk/issues/1522

### CODE REVIEW

**Comment by weshaggard** [comment]
@ericstj given that we don't stablize this package did you want to bump the patch version of it or keep it the same?

**Comment by ericstj** [comment]
> @ericstj given that we don't stablize this package did you want to bump the patch version of it or keep it the same?

Good call, I'll bump it for clarity.

**Comment by weshaggard** [comment]
test Innerloop Windows_NT Debug x86 Build and Test

**Comment by weshaggard** [comment]
@dotnet/dnceng do we have a issue with getting windows machines in CI currently?

**Comment by mmitche** [comment]
@weshaggard Yes, please see the outage mail.

**Comment by weshaggard** [comment]
Merging without CI finishing because it was green before the last commit which was just a version bump.

**Pull request merged**
