### PR TITLE
Fix race in the StackTraceSymbols.CoreCLR.cs metadata provider cache.

### PR DESCRIPTION
**Pull request by mikem8361**

### CODE REVIEW

**Comment by karelz** [comment]
@danmosemsft was it approved for 2.2?

**Comment by mikem8361** [comment]
I assumed that for bug fixes like this, I didn't need approval at the time I merged the PR.

**Comment by danmosemsft** [comment]
Yeah, outside of ASP.NET work, we're holding the same bar and process as for 2.1.x, and in general fixes would go in both (if they apply). Could you please add a template like [this example](https://github.com/dotnet/corefx/pull/31768#issuecomment-413015349) and ping the alias? I"ll forward instructions also.

I assume this applies to 2.1 also?

**Comment by mikem8361** [comment]
### Shiproom template

#### Description

There is a race condition in the portable PDB metadata provider cache that leaked providers and caused crashes in the diagnostic StackTrace API.

To fix the race, detect the cause where the provider wasn't being disposed and dispose it.

#### Customer Impact
Without this fix, the StackTrace API can crash.

#### Regression?
No.

#### Risk
Low. 

#### Link to issue
https://github.com/dotnet/coreclr/issues/19698

**Comment by mikem8361** [comment]
@danmosemsft

**Comment by jamshedd** [comment]
Approved for 2.2

**Pull request merged**
