### PR TITLE
Make Socket.BeginConnect() checking for InvalidOperationException more robustly

### PR DESCRIPTION
**Pull request by caesar1995**
Socket.BeginConnect() was not properly throwing InvalidOperationException consistently when a previous async operation was in progress. This resulted in extra BeginConnect operations starting which then caused random Socket failures and exceptions. This was not a regression from previous releases but an old bug. Without fixing this, multiple BeginConnect's are started incorrectly and random network socket failures will occur.

This PR fixs race conditions in BeginConnect logic so that InvalidOperationException's are thrown consistently when multiple operations are detected. Use atomic Interlocked.Exchange operations to protect state fields.

BeginConnect will now consistently throw InvalidOperationException when attempting multiple operations. This method is already documented to throw this exception.

Also, split the test cases in `public void BeginConnect_EndPoint_ListeningSocket_Throws_InvalidOperation()` from `ArgumentValidationTests.cs` because the check for multiple BeginConnect operations on same endpoint should comes first. (We don't allow this situation).

This issue was reported in internal bug 188428.

### CODE REVIEW

**Comment by stephentoub** [comment]
So we're making Socket larger and adding expensive Interlocked operations in the success/common case to help throw a better exception in a misuse case?

**Comment by caesar1995** [comment]
@stephentoub 
This PR does a refactoring for the current BeginConnect/EndConnect methods in order to make the check for InvalidOperationException more robust.

It's not making socket larger, but we are using Interlocked.Exchange before BeginConnect, and after EndConnect to perform the check.

**Comment by DavidGoll** [comment]
Win32 Interlocked are not expensive, unless you consider having a memory barrier expensive. Do the .NET Interlocked have more overhead than that?

**Comment by caesar1995** [comment]
@dotnet-bot test Outerloop Windows x64 Debug Build
@dotnet-bot test Outerloop Windows x64 Release Build
@dotnet-bot test Outerloop Linux x64 Debug Build
@dotnet-bot test Outerloop OSX x64 Release Build

**Comment by stephentoub** [comment]
> Win32 Interlocked are not expensive

Sure they are, relatively. Last time I checked, for example, the interlockeds in SAEA used for detecting concurrent usage we're accounting for several percent of the overall time.

At a time when we're trying to remove unnecessary overheads from sockets, this goes in the other direction.

**Comment by stephentoub** [comment]
> It's not making socket larger

It looked like you were adding a field; is that not true? I only looked very quickly so maybe I read it wrong.

**Comment by caesar1995** [comment]
> It looked like you were adding a field; is that not true?

I did add a field `private int asyncConnectOperationLock = 0;` for the Interlocked.Exchange to perform the integrity check.

The majority changes in the PR are refactoring to reduce duplicate code, not adding new logic to complicate the socket code.

**Comment by caesar1995** [comment]
Close this PR based on feedback and offline discussion.

**Pull request closed without merging**
