### PR TITLE
Add Public API Marshal.GetEndComSlot and Marshal.IsTypeVisibleFromCom

### PR DESCRIPTION
**Pull request by luqunl**
Add API: Marshal.GetEndComSlot and Marshal.IsTypeVisibleFromCom

also testcase for Marshal.GetStartComSlot, Marshal.GetEndComSlot, Marshal.IsTypeVisibleFromCom

### CODE REVIEW

**Comment by hughbe** [comment]
I wrote some tests for GetStartComSlot here, maybe you could include those in this PR and also port them to GetEndComSlot? https://github.com/dotnet/corefx/pull/31057

**Comment by luqunl** [comment]
@dotnet-bot  test OSX x64 Debug Build please

**Comment by luqunl** [comment]
@hughbe, Thanks for your GetStartComSlot testcase. I will merge your GetStartComSlot scenarios into this PR.

**Comment by luqunl** [comment]
CC: @AaronRobinsonMSFT

**Comment by luqunl** [comment]
@dotnet-bot test Packaging All Configurations x64 Debug Build

**Comment by luqunl** [comment]
@dotnet-bot  test UWP CoreCLR x64 Debug Build

**Comment by luqunl** [comment]
@dotnet-bot test Linux x64 Release Build

**Comment by luqunl** [comment]
@dotnet-bot test UWP CoreCLR x64 Debug Build

**Pull request merged**
