### PR TITLE
Add restore packages target to allow grabbing packages without building....

### PR DESCRIPTION
**Pull request by JeremyKuhne**
... This will allow faster setup for offline work. Usage is "build.cmd /t:restorepackages"

@tarekgh @ericstj

### CODE REVIEW

**Comment by tarekgh** [comment]
I'll let @ericstj to comment on this PR but it looks good to me

**Comment by JeremyKuhne** [comment]
The test that failed is failing intermittently- how do we track these sorts of issues?

\src\System.IO.FileSystem\tests\FileInfo\get_LastWriteTime.cs:line 126

**Comment by tarekgh** [comment]
@JeremyKuhne you may create a new issue to track fixing this test. I think @ericstj would be the one to look at this issue. 
and you may ask @dotnet-bot to test this one too.

**Comment by stephentoub** [comment]
> src\System.IO.FileSystem\tests\FileInfo\get_LastWriteTime.cs:line 126

Feel free to assign it to me; I'm pretty sure I've already fixed that locally as part of fixing up FileSystem src and tests for Linux.

**Comment by ericstj** [comment]
I can look, or @FiveTimesTheFun who checked in the failing tests.

**Comment by JeremyKuhne** [comment]
@ericstj This is the change you wanted to see around NuGet.

**Pull request merged**
