### PR TITLE
Add System.ComponentModel.Annotations library and tests

### PR DESCRIPTION
**Pull request by YingP99**
Add System.ComponentModel.Annotations library and tests

### CODE REVIEW

**Comment by mellinoe** [comment]
Looks good to me

**Comment by akoeplinger** [comment]
I guess this needs to be committed under @dotnet-bot ?

**Comment by mellinoe** [comment]
> I guess this needs to be committed under @dotnet-bot ?

Oops, good point, thanks for catching.

**Comment by YingP99** [comment]
Thanks. Is there a easy way to make the changes?

**Comment by weshaggard** [comment]
@YingP99 See: http://stackoverflow.com/questions/750172/change-the-author-of-a-commit-in-git

>As some of the commenters have noted, if you just want to change the most recent commit, the rebase command is not necessary. Just do

>git commit --amend --author "New Author Name <email@address.com>"

After you do that locally in your branch you will need to do a force push to your fork.

**Comment by YingP99** [comment]
@weshaggard: thanks Wes, it works.
BTW, need to add <> around email address: git commit --amend --author "dotnet-bot <dotnet-bot@microsoft.com>"

**Comment by YingP99** [comment]
@weshaggard: I think your commend is correct but the <> have been eaten:(

**Comment by mellinoe** [comment]
Commit author looks correct to me now.

**Pull request merged**
