### PR TITLE
[release/uwp6.2] Remove ExactSpelling = true (#31035)

### PR DESCRIPTION
**Pull request by josalem**
(cherry picked from commit fabaf360d608614dc7274373e7369f7cd2d3c3f2)

Cherry-picking this change from master to remove this modifier unblocks building the CoreFX tests with TestILC in this branch.

CC - @sergiy-k @trylek @MichalStrehovsky

### CODE REVIEW

**Comment by sergiy-k** [comment]
cc @tommcdon

**Comment by sergiy-k** [comment]
@dotnet-bot test this please

**Comment by danmosemsft** [comment]
This s fine but looks like 88515750d2860e74b338360942ffdd6fe401995f had the fuller fix.

**Comment by josalem** [comment]
Just realized I didn't have this in a feature branch.  Let me do some bookkeeping and recreate this PR from a different branch.

**Pull request closed without merging**
