### PR TITLE
System collections specialized cleanup

### PR DESCRIPTION
**Pull request by Clockwork-Muse**
Companion to (and conflicts with) #5087

This PR represent existing, already completed work in an effort to clean up System.Collections.Specialized.  

@hughbe - we'll need to coordinate and figure out who's changing what.

@ianhays
@stephentoub

### CODE REVIEW

**Comment by Clockwork-Muse** [comment]
(le sigh.... I need to remember to break things up more for work PR/submit....)

**Comment by hughbe** [comment]
good work! Umm have you taken a look at my PR and seen the tests that I added - have you added any testing the same thing - I'll remove these

also, I'm not sure which should be merged first, mine or yours!

**Comment by Clockwork-Muse** [comment]
@hughbe - probably mine, and then add any tests I missed.  Mostly that's because I consolidated the individual files into one (given the original contents).  I think you had more work done in HybridDictionary (or at least different work), although that was one of the things I left out of this one.

**Comment by hughbe** [comment]
Brill.
Also can you shoot me a list of the stuff you haven't covered, and more importantly that you don't intend to cover?
This is so thqt I can do some work in redoing those tests

**Comment by stephentoub** [comment]
Test Innerloop Ubuntu Release Build and Test please
Test Innerloop CentOS7.1 Release Build and Test please

**Comment by Clockwork-Muse** [comment]
@hughbe - at the moment, I'm only going to cover what I'm submitting here.

I have work on HybridDictionary, but it needs to be gone over because I didn't account for other cultures properly (that is, I didn't properly check what the default comparer - and how it reacted to case insensitivity - was).  The base helper comparers I use in some of these tests only get a pass because none of the types really care about culture, so none of the tests do.  90% done or so otherwise, I think.  You could steal and submit, or  I'll maybe look after you've got your stuff in.  The most interesting thing thing I added was a test covering the transition point with regards to enumerators (because it doesn't invalidate the old one) - so not much, other than the reorg and combine.

There was some stuff in process for name-value collection, but nowhere near finished.

**Comment by stephentoub** [comment]
> I need to remember to break things up more for work PR/submit

Yes, please ;)

**Comment by Clockwork-Muse** [comment]
@stephentoub , @ianhays 

Comments addressed, rebased.

**Comment by stephentoub** [comment]
Thanks for cleaning up these tests, @Clockwork-Muse.  I left some feedback.  Please address in an additional commit rather than squashing just to make the large set of changes easier to re-review.

**Comment by Clockwork-Muse** [comment]
@stephentoub - I believe I've addressed everything.

**Comment by stephentoub** [comment]
Thanks for the additional test cleanup.  LGTM.  @ianhays?

**Comment by ianhays** [comment]
LGTM here.

**Pull request merged**
