### PR TITLE
Enable per-commit arm64 build and test runs

### PR DESCRIPTION
**Pull request by ianhays**
@gkhanna79 @Priya91

### CODE REVIEW

**Comment by ianhays** [comment]
@dotnet-bot test ci please

**Comment by ianhays** [comment]
@dotnet-bot test arm64 Windows_NT Release please

**Comment by ianhays** [comment]
@dotnet-bot test ARM64 Windows_NT Release please

**Comment by ianhays** [comment]
@dotnet-bot test ARM64 Windows_NT Release

**Comment by gkhanna79** [comment]
LGTM

**Pull request merged**
