### PR TITLE
Port a DataContractSerialization bug fix from netfx

### PR DESCRIPTION
**Pull request by yujayee**
This PR is to port a fix from .NET Framework (DTS bug 489771). 
Original issue: DataContractSerializer failed with IndexOutOfRange exception while serializing an huge object graph.
Fix: The size of isReferenceArray need be the same as the size of objectArray.  The fix is to keep the size of isReferenceArray and objectArray in sync and avoid the IndexOutOfRangeException.

### CODE REVIEW

**Comment by drieseng** [comment]
@yujayee  Do you also have a test for this?

**Comment by huanwu** [comment]
@yujayee Could you add more description for this issue?

**Comment by yujayee** [comment]
@huanwu I don't have much context on this one, it is from DTS bug 489771.

**Comment by karelz** [comment]
@yujayee what is the plan with this PR? There has not been progress in 2+ weeks.

**Comment by huanwu** [comment]
@yujayee Could you add a test?

**Comment by yujayee** [comment]
@dotnet-bot test OSX x64 Debug Build please

**Comment by yujayee** [comment]
@dotnet-bot test OSX x64 Debug Build please

**Comment by yujayee** [comment]
There are some build errors from System.Reflection.Tests, which seems not directly related to this code change. Comment out the code change to see if those errors still exist.

**Comment by yujayee** [comment]
I commentted out all the changes I made but the System.Reflection.Tests still failed, which proves the failure is not related to my change. 
Just added my changes back in the new commit.

**Comment by yujayee** [comment]
@dotnet-bot test Linux x64 Release Build 
@dotnet-bot test OSX x64 Debug Build

**Comment by yujayee** [comment]
Build fails on OSX ([link](https://mc.dot.net/#/user/yujayee/pr~2Fjenkins~2Fdotnet~2Fcorefx~2Fmaster~2F/test~2Ffunctional~2Fcli~2F/c030d5e713d04abb7d5dd97c52fadc66e3f1d263)), a stackoverflow exception was thrown for the new test. Investigating.

**Comment by yujayee** [comment]
@dotnet-bot test NETFX x86 Release Build

**Comment by yujayee** [comment]
@dotnet-bot test Packaging All Configurations x64 Debug Build

**Pull request merged**
