### PR TITLE
Disable System.Transactions.Local tests on .Net Framework

### PR DESCRIPTION
**Pull request by qizhanMS**

### CODE REVIEW

**Comment by danmosemsft** [comment]
@qizhanMS curious why they need to be disabled?

**Comment by stephentoub** [comment]
@qizhanMS, is this temporary?  Is there an issue tracking re-enabling them?

**Comment by qizhanMS** [comment]
The calculation for timeout is different for System.Transactions on .net core and full framework. Therefore some .net core tests randomly failed on full framework. We can either keep the test running and investigate when failure happens, or disable the test run on full framework. If we disable the test, we may miss the chance if there is other problem. If we keep the tests on full framework, we will get some noise and need to spend time on investigation. Because the number of failure is not high for now, I am ok with keeping the test run on full framework.

**Comment by stephentoub** [comment]
> The calculation for timeout is different for System.Transactions on .net core and full framework. 

Can we adapt the tests accordingly?  We already have helpers that tests can check to dynamically determine which platform/framework they're running on... could the tests be tweaked to use a different timeout value to accomodate the differences?

**Comment by karelz** [comment]
@qizhanMS any update on this PR?

**Comment by karelz** [comment]
@qizhanMS ping?

**Comment by stephentoub** [comment]
@qizhanMS, since it's been a month, I'm going to close this.  You can re-open when you're ready.

**Pull request closed without merging**
