### PR TITLE
Update CoreClr, CoreFx, ProjectNTfs to beta-24827-03, beta-24827-01, beta-24827-00, respectively (master)

### PR DESCRIPTION
**Pull request by jkotas**

### CODE REVIEW

**Comment by danmosemsft** [comment]
Why would this be...
```
MESSAGE:
System.BadImageFormatException : An attempt was made to load a program with an incorrect format. (Exception from HRESULT: 0x8007000B)
+++++++++++++++++++
STACK TRACE:
at System.IO.Pipes.Tests.Interop.GetNamedPipeHandleState
```

**Comment by karelz** [comment]
@dotnet-bot test Innerloop Windows_NT Debug

**Comment by karelz** [comment]
I think it was point in time failure ...
[2 failures](https://ci.dot.net/job/dotnet_corefx/job/master/job/windows_nt_debug_prtest/1688/):

**[System.IO.Pipes.Tests.NamedPipeTest_Specific.Windows_Get_NumberOfServerInstances_Succeed](https://ci.dot.net/job/dotnet_corefx/job/master/job/windows_nt_debug_prtest/1688/testReport/junit/System.IO.Pipes.Tests/NamedPipeTest_Specific/Windows_Get_NumberOfServerInstances_Succeed/):**

<details>
MESSAGE:
System.BadImageFormatException : An attempt was made to load a program with an incorrect format. (Exception from HRESULT: 0x8007000B)
+++++++++++++++++++
STACK TRACE:
at System.IO.Pipes.Tests.Interop.GetNamedPipeHandleState(SafePipeHandle hNamedPipe, IntPtr lpState, Int32& lpCurInstances, IntPtr lpMaxCollectionCount, IntPtr lpCollectDataTimeout, StringBuilder lpUserName, Int32 nMaxUserNameSize) at System.IO.Pipes.Tests.Interop.TryGetNumberOfServerInstances(SafePipeHandle handle, Int32& numberOfServerInstances) in D:\j\workspace\windows_nt_de---4526f5ff\src\System.IO.Pipes\tests\Interop.cs:line 58 at System.IO.Pipes.Tests.NamedPipeTest_Specific.<Windows_Get_NumberOfServerInstances_Succeed>d__5.MoveNext() in D:\j\workspace\windows_nt_de---4526f5ff\src\System.IO.Pipes\tests\NamedPipeTests\NamedPipeTest.Specific.cs:line 185 --- End of stack trace from previous location where exception was thrown --- at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) --- End of stack trace from previous location where exception was thrown --- at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) --- End of stack trace from previous location where exception was thrown --- at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
</details>

<br/>

**[System.IO.Pipes.Tests.NamedPipeTest_Specific.Windows_GetImpersonationUserName_Succeed](https://ci.dot.net/job/dotnet_corefx/job/master/job/windows_nt_debug_prtest/1688/testReport/junit/System.IO.Pipes.Tests/NamedPipeTest_Specific/Windows_GetImpersonationUserName_Succeed/):**

<details>
```
MESSAGE:
System.BadImageFormatException : An attempt was made to load a program with an incorrect format. (Exception from HRESULT: 0x8007000B)
+++++++++++++++++++
STACK TRACE:
at System.IO.Pipes.Tests.Interop.GetNamedPipeHandleState(SafePipeHandle hNamedPipe, IntPtr lpState, Int32& lpCurInstances, IntPtr lpMaxCollectionCount, IntPtr lpCollectDataTimeout, StringBuilder lpUserName, Int32 nMaxUserNameSize) at System.IO.Pipes.Tests.Interop.TryGetImpersonationUserName(SafePipeHandle handle, String& userName) in D:\j\workspace\windows_nt_de---4526f5ff\src\System.IO.Pipes\tests\Interop.cs:line 44 at System.IO.Pipes.Tests.NamedPipeTest_Specific.<Windows_GetImpersonationUserName_Succeed>d__6.MoveNext() in D:\j\workspace\windows_nt_de---4526f5ff\src\System.IO.Pipes\tests\NamedPipeTests\NamedPipeTest.Specific.cs:line 207 --- End of stack trace from previous location where exception was thrown --- at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) --- End of stack trace from previous location where exception was thrown --- at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) --- End of stack trace from previous location where exception was thrown --- at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
```
</details>

**Comment by jcouv** [comment]
@karelz It looks like those two tests are still failing.

**Comment by karelz** [comment]
It is still the same result. New test run wasn't kicked off :(
One more try:

@dotnet-bot test Innerloop Windows_NT Debug

**Comment by karelz** [comment]
@mmitche any idea why dotnet-bot is unresponsive?

**Comment by danmosemsft** [comment]
I meant to close and reopen. According to @mmitche this is how to shake lose the bot when it stops listening. Matt, a bug?

**Comment by mmitche** [comment]
Hmm, I'm wondering whether this crossed the Jenkins restart I did for upgrades.  But it should still have responded.

**Pull request merged**
