### PR TITLE
Prohibit LoopExpression with same label for break and continue.

### LINKED ISSUE #4298: Expression.Loop doesn't check against reference equal break and continue labels
Fails to compile with non-obvious error. Factory should likely check against this.

### PR DESCRIPTION
**Pull request by JonHanna**
Fixes #4298

### CODE REVIEW

**Comment by JonHanna** [comment]
Strictly speaking a breaking change, but it's hard to see what anyone could have usefully done with such an expression as any actual use would have thrown.

@bartdesmet I use the same error message (but a different type) as that in the exception you described as a "non-obvious error". I hope you find it obvious enough in this context, since it won't be buried as deep into a compilation. The message is still valid, and reusing it saves on localisation burden.

**Comment by stephentoub** [comment]
cc: @VSadov

**Comment by VSadov** [comment]
There are many cases where ET nodes with impossible/useless topology can be created. It tries to reject things early , but in some cases (like lambdas referencing variables from unreachable scopes) it is just hard to catch everything cheaply, so the error will happen when lambda is bound before execution. 
Generally, if a tree can be created, it does not guarantee that it will compile and run.

This particular check is not expensive, so it is likely an oversight. However, considering the node like that can be created right now, I think we should leave this for compat reasons.

We are not going to make it all that much better since there are many other possible continue/break targets that factory would not be able to validate.

**Comment by JonHanna** [comment]
If it's left, then it might be well to catch it upon compilation and give a different error message (but same message type).

Whether so or no, if it's being kept for compatibility, it may be well to add a test on it being accepted.

cc: @bartdesmet

**Comment by VSadov** [comment]
@JonHanna 
We need to move on on this. I think we should stay compatible here. It is not a big usability win to fix this behavior. 

Changing error message would be ok though. And adding a tests seems a good idea too.

**Comment by JonHanna** [comment]
I'll add a test, and see if a clearer message can be produced without requiring convoluted code.

**Pull request closed without merging**
