### PR TITLE
Fix for Mac Catalina failure on release/2.2 and 2.1 branches

### PR DESCRIPTION
**Pull request by buyaa-n**

### CODE REVIEW

**Comment by danmosemsft** [comment]
The title says 2.x but this is against master?

**Comment by buyaa-n** [comment]
From our yesterday's conversation i thought you meant raise it against master for now as for merging 2.x we need special approval

**Comment by buyaa-n** [comment]
> What is underlying type for SocketEvents? (e.g. did that changed?)

Underlying type is enum, seems it is changed from int to this enum: https://github.com/dotnet/corefx/commit/14569aeb72574b700093cc88b7c3af49cf1b4cdc#diff-eee4543f13c4d6b0c1bd8bdb53281f7a

**Comment by buyaa-n** [comment]
closing it as its need to be raised against 2.x branch

**Pull request closed without merging**
