### PR TITLE
Update CoreFx dependencies to build rc4-24203-07

### PR DESCRIPTION
**Pull request by weshaggard**
Remove System.IO.Compression and System.Data.SqlClient from the External dependencies

cc @stephentoub 

This PR should be preferred over the automatic one getting ready to be submitted for this build, as it fixes the external dependencies that should be corefx now instead of external. @jhendrix.

### CODE REVIEW

**Comment by stephentoub** [comment]
LGTM

**Comment by ianhays** [comment]
@jhendrixMSFT

**Comment by weshaggard** [comment]
Just rebased to deal with conflicts.

**Comment by ericstj** [comment]
I think this will need a fix from @jhendrixMSFT for SQLClient package.  I doctored up the RC3 package, could do the same here or just wait for a new build with that fix.

**Comment by weshaggard** [comment]
@jhendrixMSFT do you have your sql package fixes in master yet? 

We don't need to doctor up this PR I'm fine waiting for another build but we do need the other fixes I made in dir.props.

**Comment by jhendrixMSFT** [comment]
@weshaggard No I will get the posted shortly.

**Comment by ellismg** [comment]
We have newer versions of this and @weshaggard was going to port whatever he needed from here to them.

**Comment by weshaggard** [comment]
Yes I'm going to close this and wait for the latest packages to settle and I will then indpendently submit a PR with the other changes.

**Pull request closed without merging**
