### PR TITLE
Merge serialization changes to 2.0.0

### PR DESCRIPTION
**Pull request by krwq**
TODO:
- [ ] Merge CoreCLR's PR https://github.com/dotnet/coreclr/pull/12020
- [ ] Wait for bot to update CoreCLR dep and rebase
- [x] Merge and cherry-pick PR https://github.com/dotnet/corefx/pull/20247

### CODE REVIEW

**Comment by krwq** [comment]
@dotnet-bot test this please

**Comment by krwq** [comment]
@dotnet-bot test this please

**Comment by krwq** [comment]
@dotnet-bot test Portable Linux x64 Debug Build please

**Comment by krwq** [comment]
Per my offline conversation with @mmitche Portable runs can be ignored as they should've not run.

**Comment by krwq** [comment]
@stephentoub, could you please take another look? I've had some merge conflicts when cherry picking Viktor's PR.

Conflicting files:
- src/System.Net.Primitives/src/System/Net/Cookie.cs
- src/System.Runtime.Serialization.Json/tests/DataContractJsonSerializer.cs
- src/System.Runtime.Serialization.Xml/tests/DataContractSerializer.cs

I took master changes in all 3 cases since that looked correct. It seems they were all related to UAP (ifdefs, test disable etc.).
First file is a product change so here is example thing which got changed:
https://github.com/dotnet/corefx/blame/release/2.0.0/src/System.Net.Primitives/src/System/Net/Cookie.cs#L661

Is that ok or do we need to pick changes more granularily?

**Comment by ViktorHofer** [comment]
BinarySerializer change is in. Now we need an offline validation if tests are not working as expected in the release/2.0 branch.

**Comment by krwq** [comment]
@danmosemsft - local run with coreclr pending changes is passing all tests - once coreclr is merged and this PR can pick up the official coreclr bits this PR is expected to pass

**Comment by weshaggard** [comment]
>Per my offline conversation with @mmitche Portable runs can be ignored as they should've not run

Can you please clarify this? There shouldn't be any legs in the CI that should be ignored here. Those look like correct failures that need to be understood. Perhaps those failures are because they need the corresponding coreclr changes.

**Comment by krwq** [comment]
@weshaggard @mmitche said offline that those legs were not supposed to be run at all and that happened likely because I've opened this PR against master and closed it and then reopened another one against rel/2.0.0 with the same commit hash

**Comment by weshaggard** [comment]
Looking at the CI legs that kicked off they are the expected set for release/2.0.0 branch (at least for now until we move the CI changes to the release branch). Please don't ignore the results for these CI legs make sure they are understood.

**Comment by krwq** [comment]
@weshaggard I think current set looks good, previously it was trying to merge this PR with master branch causing merge conflicts

**Comment by mmitche** [comment]
@krwq I was looking for the ones that said "Portable Linux x64 Debug Build"/"Portable Windows x64 Debug Build" etc. that happened to run on that one PR. Beyond that, everything else here should pass

**Comment by danmosemsft** [comment]
Waiting on https://github.com/dotnet/corefx/pull/20595 to reset CI here.

**Pull request merged**
