### PR TITLE
Temporarily add OSX10.12 back into CI

### PR DESCRIPTION
**Pull request by mmitche**
Not available yet in pipeline, add triggers for traditional jobs back temporarily.

/cc @weshaggard @danmosemsft @stephentoub

### CODE REVIEW

**Comment by mmitche** [comment]
@dotnet-bot test ci please

**Comment by danmosemsft** [comment]
@mmitche seems jammed for 30 minutes on initializing build tools?
https://ci.dot.net/job/dotnet_corefx/job/master/job/AllConfigurations_debug_prtest/5215/console

**Comment by mmitche** [comment]
@danmosemsft I've actually seen this quite a bit in a the new pipeline builds.  The build tools restoration taking ~30 mins.  I think this is worth an investigation.

**Comment by danmosemsft** [comment]
@weshaggard thoughts about build tools restore? not sure who owns that...

**Comment by weshaggard** [comment]
I've seen that a few times as well only on some legs. We should definitely get to the bottom of that as it really hurts our CI perf. Last time I fixed a similar issue because of default wildcards with PR https://github.com/dotnet/corefx/pull/19109 perhaps something similar has crept in again. I will try and take a look.

**Pull request merged**
