### PR TITLE
System.Console: fix casing of file on disk

### PR DESCRIPTION
**Pull request by akoeplinger**
It had a different casing in the csproj than on disk which caused a build break on Linux.
The version in the csproj matches the naming convention so renaming the file.

/cc @sokket

### CODE REVIEW

**Comment by sokket** [comment]
Ah good catch...can you please rename the file to be Interop.SNPrintF.cs to fit with our naming conventions? Thanks again for catching this

**Comment by akoeplinger** [comment]
@sokket done :)

**Comment by akoeplinger** [comment]
@dotnet-bot test this please

**Comment by sokket** [comment]
LGTM, thanks!

**Comment by stephentoub** [comment]
LGTM. Thanks.

**Pull request merged**
