### PR TITLE
Re-enable Regex tests on UAP and speed them up (more than 40x times)

### PR DESCRIPTION
**Pull request by krwq**
Fixes https://github.com/dotnet/corefx/issues/21547
Fixes https://github.com/dotnet/corefx/issues/21835

I could not repro original issue (tests hanging) at all locally but seems to me like regular timeout.
**I'm leaving these tests running over the weekend in a loop to see if they will fail.**
Currently running for several minutes and haven't failed yet.

Timing change
```
System.Text.RegularExpressions.Tests.RegexGroupTests
Before => 128.812s
Now => 2.784
```

Most of the time difference is due to not calling RemoteInvoke so many times

### CODE REVIEW

**Comment by krwq** [comment]
Some unrelated to this PR Regex test has failed over the weekend:
```
System.Text.RegularExpressions.Tests.RegexMatchTests.Match_SpecialUnicodeCharacters
```

Fixing it now.

**Comment by krwq** [comment]
Failing test is using CurrentCulture twice but after splitting it is failing all the time on UAP only. Investigating

**Comment by krwq** [comment]
I'll shortly fix the test and disable the faulty path with an issue and work with @tarekgh on more details

**Comment by krwq** [comment]
@dotnet-bot test Linux x64 Release Build please

**Comment by krwq** [comment]
test Windows x64 Debug Build please

**Comment by safern** [comment]
Thanks @krwq for taking care of these issues!

**Pull request merged**
