### PR TITLE
Re-enable xunit 2013

### PR DESCRIPTION
**Pull request by adlich**
Contributes to #39697.
cc: @stephentoub, @ViktorHofer

### CODE REVIEW

**Comment by adlich** [comment]
I apologize I failed to notice that warning 2013 was removed from the list on Sunday. But since I haven't seen a PR yet, just sharing in case this is still helpful. Feel free to ignore (my main goal was to familiarize myself with the repo, build & test tooling, etc.)

**Comment by stephentoub** [comment]
> I apologize I did not notice warning 2013 was removed from the list last Sunday

No need to apologize; thank you for doing this!  I removed it from the list after examining the rule and being worried that it would actually be problematic due to the number of places in corefx where we actually implement Count methods and thus explicitly want to test Count; the rule would warn about using Empty/Single/etc., and we'd need to suppress it.  Now that you've implemented it, though, let's take a look and see whether my fears were warranted... it may just be that we want to suppress the rule via NoWarn in some projects.

**Comment by adlich** [comment]
Sounds good, thanks! Let me deal with the cross platform misses (only Mac is green) and the cases in which Count is the target of the test (good point!) I will ping you when this is updated (later in the week.)

**Comment by bartonjs** [comment]
Looking at the changes this introduces, I think the code that is correct per the rule is less clear as to what it's checking.

Perhaps `Assert.Empty(enumerable)` is better than `Assert.Equal(0, enumerable.Count())`; but for things with a Count property I think that `Assert.Equal(0, coll.Count)` and `Assert.Equal(1, coll.Count)` (and then any specific number for more complex states) is more legible than `Assert.Empty(coll)` and `Assert.Single(coll)`.  (It's also clearer that null isn't Empty, since it had a property dereference).

I'd advocate not enabling this rule globally; but certainly any area that wants to use it is welcome to.

**Comment by adlich** [comment]
I must say I agree -- bad choice when I picked this one warning #. It was worthwhile having a goal while setting up the workflow, and except for the small commit in the patchset, the large changes were easily automated. Closing it now. Thanks again!

**Pull request closed without merging**
