### PR TITLE
Improve performance of decoding only '+' in WebUtility

### PR DESCRIPTION
**Pull request by hughbe**
- x4-x5 performance increase (benchmark)
- 2x allocations decrease

- I think that this is quite a common use case, as a lot of the time our inputs are normal text/phrases/sentences which typically contain ASCII and spaces (e.g. in Google)
- Existing tests cover the new branches

## Benchmark
benchmark

## Benchmark Code
<details>
<summary>Click here</summary>
```c#
static unsafe void Main(string[] args)
{
    TimeAction("Old: ", () => Old.UrlDecode("abc+def"));
    TimeAction("New: ", () => New.UrlDecode("abc+def"));

    Console.ReadLine();
}

public static void TimeAction(string prefix, Action action)
{
    var sw = new Stopwatch();
    for (int iter = 0; iter < 5; iter++)
    {
        int gen0 = GC.CollectionCount(0);
        sw.Restart();
        for (int i = 0; i < 10000000; i++)
        {
            action();
        }
        sw.Stop();
        Console.WriteLine($"{prefix}Time: {sw.Elapsed.TotalSeconds}\tGC0: {GC.CollectionCount(0) - gen0}");
    }
}
```
</details>
/cc @davidsh @stephentoub @jamesqo

### CODE REVIEW

**Comment by stephentoub** [comment]
LGTM

**Comment by jamesqo** [comment]
LGTM, as well. 👍

**Comment by JonHanna** [comment]
LGTM, nice change. I think you are likely right in the judgement that this would be a common case in practice.

**Comment by hughbe** [comment]
Cheers, I'm making a similar change to UrlEncode once my other PR is merged for UrlEncode

**Comment by davidsh** [comment]
LGTM

**Pull request merged**
