### PR TITLE
Mark tests which require elevation

### PR DESCRIPTION
**Pull request by ellismg**
Previously we conflated "Outer Loop" with "Running as Administrator/root".  Helix does not follow this convention (so we got test failures there) and we are seeing other cases where outer loop runs may not be running elevated (e.g. OSX).

This augments the existing tests I found that require elevation to have a new trait that can be ignored with `/p:WithoutCategories=RequiresElevation`.

/cc @stephentoub @MattGal

### CODE REVIEW

**Comment by mellinoe** [comment]
LGTM, I'm surprised there's only three tests that require elevation.

**Comment by stephentoub** [comment]
> I'm surprised there's only three tests that require elevation.

I know a bunch of the ServiceController tests also require it, e.g.
https://github.com/dotnet/corefx/blob/master/src/System.ServiceProcess.ServiceController/tests/System.ServiceProcess.ServiceController.Tests/ServiceControllerTests.cs#L97

Looks like another process test does:
https://github.com/dotnet/corefx/blob/39c812e9c40218fadfa87e2dd0a1a4fb4fcaa8f0/src/System.Diagnostics.Process/tests/ProcessStartInfoTests.cs#L349

Not exactly the same thing, but some of the FileSystem tests are conditioned on whether they can create symlinks:
https://github.com/dotnet/corefx/blob/473f42d633a6172f2d21f0bf8f24d23c3a5bef49/src/System.IO.FileSystem.Watcher/tests/Utility/FileSystemWatcherTest.cs#L364
which requires elevated privileges on Windows.

There are probably some others lurking as well.

**Comment by ellismg** [comment]
@dotnet-bot test this please

**Comment by ianhays** [comment]
>Helix does not follow this convention

That explains https://github.com/dotnet/corefx/issues/9009.

**Comment by ellismg** [comment]
@dotnet-bot test this please.

**Comment by Priya91** [comment]
This is tracked in #9302

**Pull request closed without merging**
