### PR TITLE
Use correct charset when unpacking port names (#20668)

### PR DESCRIPTION
**Pull request by JeremyKuhne**
Port of #20668. Test only fix. None of the SerialPort tests work without this.

### CODE REVIEW

**Comment by danmosemsft** [comment]
@JeremyKuhne if you email shiproom and tell them it's a test only change, only affecting serial port tests, they'll probably take it now.

**Comment by JeremyKuhne** [comment]
> email shiproom 

Done.

@willdean I wonder if we could write some basic tests that ensure we don't fundamentally break like this again? Tests where we check that underlying support (like P/Invokes) aren't completely busted?

**Comment by willdean** [comment]
@JeremyKuhne To catch this particular bug at source it would be easy enough to write a test which said "if the test framework doesn't detect any COM ports, then that's a failure".  

We would then have to cross our fingers that all future CI systems did actually have serial ports (emulated or real) for us to detect.  I'm not sure that if that's a legitimate requirement or not.

The other way we could have caught this is to compare the test support's view of what ports we have (which comes from `QueryDosDevices`) with `SerialPorts`'s view of what ports we have - which comes from a registry query.  A mismatch there would be an error.   This isn't very portable even among flavors of Windows (there are a number of issues around the registry use already), but it should work in some places.

There is actually a test which almost does this already: `GetPortNames.OpenEveryPortName`.   I'm not sure why it didn't catch this specific problem so I will have a look at that.

**Comment by JeremyKuhne** [comment]
Shiproom approved

**Pull request merged**
