### PR TITLE
Fix ordering of test builds files

### PR DESCRIPTION
**Pull request by joperezr**
cc: @weshaggard 

This is addressing some post-merge feedback for #12241 . Wes, please let me know if this ordering makes sense and is what  you expected. Ordering algorithm I used was: `itemgroup.Items.OrderBy(i => i.ItemType).ThenByDescending(i => i.Include).ThenBy(i => i.Metadata.Count);`

### CODE REVIEW

**Comment by joperezr** [comment]
@dotnet-bot test Innerloop CentOS7.1 Release Build and Test please (infra error: failure to start run)

**Comment by bartonjs** [comment]
Seems reasonable, but you have merge conflicts now...

**Comment by weshaggard** [comment]
The project ordering looks good thanks. 

Can I add one more clean-up to your tool? In particular can we have a consistent order to the metadata items? I think TargetGroup, OSGroup, TestTFMs seems like the most consistent and reasonable order.

**Comment by joperezr** [comment]
> Can I add one more clean-up to your tool? In particular can we have a consistent order to the metadata items?

done in b565022

**Comment by weshaggard** [comment]
Thanks @joperezr

**Pull request merged**
