### PR TITLE
Merge master to dev/metadata

### PR DESCRIPTION
**Pull request by nguerrera**
No literal conflict, but had to add bf192c7 to make buildtools happy.

### CODE REVIEW

**Comment by stephentoub** [comment]
LGTM

**Comment by stephentoub** [comment]
@nguerrera, this failed due to a test I just disabled in https://github.com/dotnet/corefx/pull/3611... you might want to update the PR to include the more recent commits

**Comment by nguerrera** [comment]
@stephentoub Thanks. Trying that.

**Comment by nguerrera** [comment]
@dotnet-bot test this please (#3630)

**Pull request merged**
