### PR TITLE
Suppress tests in 'Close' module

### PR DESCRIPTION
**Pull request by willdean**
Possible suppression for recent test failures #16055, #16051

### CODE REVIEW

**Comment by willdean** [comment]
I don't currently know what this problem is, or even if these two sets of tests are really the cause, but it can't do any harm to merge this if the tests pass.   

If in my absence you need a very quick way to disable almost all the serial tests tests without adding a thousand `ActiveIssue` attributes, I'd suggest you just disable the serial port identification in 
`TCSupport.GenerateSerialInfo` (just force both port names to null before the `LocalMachineSerialInfo` ctor).

**Comment by JeremyKuhne** [comment]
@dotnet-bot test Innerloop Windows_NT Debug Build and Test (System.Net.Security.Tests.SslStreamNetworkStreamTest.SslStream_SendReceiveOverNetworkStream_Ok failed)

**Comment by JeremyKuhne** [comment]
@willdean Legacy.SerialStream.EndWrite.AsyncResult_MultipleInOrder failed in the release build

**Comment by willdean** [comment]
@JeremyKuhne Yes, I know what the problem is now - both EndRead and EndWrite have it, and I think I have an easy fix which has just run a 1000 cycles here (wouldn't run more than 2-3 before)  - I'm going to push another PR without the suppression but with the fixes and we'll see what the CI makes of that.

**Comment by JeremyKuhne** [comment]
@willdean Sounds good- I'll keep an eye out.

**Comment by willdean** [comment]
OK, I've just pushed the suppression for EndWrite - if this passes CI I think you should merge it so we don't end up with a flaky build over the weekend.  

I'll work up the proper fix in another PR.  Could you look at my comment about the Dev10 bug number in #16055 and see if there's any info you can find there?

**Pull request merged**
