### PR TITLE
Audit all corefx Streams with Read/WriteAsync overrides

### PR DESCRIPTION
**Pull request by stephentoub**
Any that have overrides of these that do something real (e.g. not just throw) also need overrides of Begin/EndRead/Write.

cc: @davidsh, @saurabh500, @ianhays

### CODE REVIEW

**Comment by karelz** [comment]
cc: @Priya91 @geoffkizer @CIPop

**Comment by ericstj** [comment]
@stephentoub Looks like you broke the new Windows_NT Debug AllConfigurations Build.  This build includes configurations that only ship in packages.  You can repro locally by doing the following:
`build.cmd | build.sh -allConfigurations`

After doing that once you can iterate on a project by running `msbuild /t:BuildAllConfigurations`

**Comment by ericstj** [comment]
@davidsh have a closer look at the System.Net.Http changes.  Looks like they broke the desktop build.

**Comment by davidsh** [comment]
>@davidsh have a closer look at the System.Net.Http changes. Looks like they broke the desktop build.

My approval was about the actual APM method overrides.

Clearly, this can't be merged until the all build configuration work including "Desktop" build works.

This PR needs some changes to add NET46 specific things to the project file and to exclude the inclusion of the added common TaskToAPM.cs file to the System.Net.Http build.

**Comment by stephentoub** [comment]
> What's the context behind these changes? Did the implementation change in the base class leading to this PR so that the derived classes can provide the implementation that existed earlier?

The Stream.Begin/End methods weren't exposed in .NET Standard prior to 2.0.  Now that they're exposed, they can be called.  The base implementation of these virtual methods queues a work item to the thread pool to call the synchronous counterpart, which is at best not as efficient as using the corresponding XxAsync method if such a method was overridden by the developer.  In many of the cases modified, the Begin/End methods exist in desktop but were removed when ported to core because the base methods weren't available to override, e.g. SqlSequentialStream: https://referencesource.microsoft.com/#System.Data/System/Data/SqlClient/SqlSequentialStream.cs,116

**Comment by stephentoub** [comment]
@dotnet-bot test Innerloop Ubuntu14.04 Release Build and Test please (build timed out before it even finished building the libs)

**Pull request merged**
