### PR TITLE
Portable PDB and PE/COFF specs

### PR DESCRIPTION
**Pull request by tmat**
System.Reflection.Metadata seems to be the best place for these documents. Portable PDB spec is currently in Roslyn, so the proposal is to move it here (and link it from Roslyn).

### CODE REVIEW

**Comment by tmat** [comment]
@nguerrera Please review.

**Comment by tmat** [comment]
@dotnet/dotnet-corefx

**Comment by tmat** [comment]
@gafter FYI

**Comment by weshaggard** [comment]
I'm fine with moving these docs here.

**Comment by nguerrera** [comment]
LGTM.

**Pull request merged**
