### PR TITLE
Remove TypeDoesNotHaveConstructorForTheSignature from S.L.Expressions

### PR DESCRIPTION
**Pull request by JonHanna**
Error is only thrown in an array of rank n does not have a constructor taking n integers, which it must. Replace throw site with assertion.

### CODE REVIEW

**Comment by stephentoub** [comment]
I'm not following: this method doesn't seem specific to arrays.  Is it?

**Comment by JonHanna** [comment]
That's the only place it's ever called though. The condition it's called on is impossible, so it's dead code.

**Comment by stephentoub** [comment]
Then it seems like it should be renamed, or its type argument should be renamed, or something that makes it less general.

**Comment by JonHanna** [comment]
Once I remove the `(ci == null)` branch it's down to having zero places where it's called anyway, so I'm removing it as dead code. It doesn't matter what it's called if its being deleted.

`ci == null` can only be true if e.g. `T[,,,]` didn't have a ctor for `new T[1,2,3,4]` which is only true once you get beyond 32 ranks but that couldn't get that far as trying to create `type` would have thrown a `TypeLoadException`.

**Comment by stephentoub** [comment]
I was talking about the EmitNew method.

**Comment by JonHanna** [comment]
Ahh, *that* method.

Yes, while it's a reasonable enough name when considered as a particular case of what `EmitNew` does, it isn't clear what that particular case is from the signature alone. I'll change that.

**Comment by JonHanna** [comment]
Sorry for the misunderstanding there. I've inlined the call to that overload of `EmitNew` as the relationship between the reason of the call and the `paramTypes` isn't very clear from examining just that method IMO, while its easier to see what's going on if it happens within `EmitArray`.

**Pull request merged**
