### PR TITLE
Use GetCurrentMethod in Queryable

### PR DESCRIPTION
**Pull request by bartdesmet**
Building on the move to `netstandard1.7` in https://github.com/dotnet/corefx/pull/13591, superseding the "infoof" approach in https://github.com/dotnet/corefx/pull/13561.

CC @stephentoub, @JonHanna

### CODE REVIEW

**Comment by bartdesmet** [comment]
After #13591 has been merged, I can rebase to retain the `GetCurrentMethod` changes for this PR.

**Comment by mmitche** [comment]
@dotnet-bot test this please

**Comment by mmitche** [comment]
@dotnet-bot test ci please

**Comment by JonHanna** [comment]
Shiny.
I've never looked at the cost of `GetCurrentMethod()`. Is it cheap enough to mitigate the benefits of caching, discussed earlier, entirely?

**Comment by jkotas** [comment]
In the current CoreCLR implementation, GetCurrentMethod() is not very cheap (it does stackwalk): https://github.com/dotnet/coreclr/blob/32f0f9721afb584b4a14d69135bea7ddc129f755/src/vm/reflectioninvocation.cpp#L1875

It can be made cheap if it is turned into JIT intrinsic. The JIT always knows what is the current method that it is JITing - it is trivial to expand it.

**Comment by bartdesmet** [comment]
Any plan for the JIT work?

**Comment by JonHanna** [comment]
Should we cache in the meantime? I'm inclined not to if this hasn't actually made things slower than before, if it's at all likely we'll see that JIT change any time soon.

**Comment by bartdesmet** [comment]
Yeah, it look like this gets it on par with the .NET Framework where we used `GetCurrentMethod` as well. The native code in the CLR looks the same at first sight too. An improvement to the JIT would just make it better; I don't think we need to cache if we can get that at some point. I'll run a quick test to see how much it'd get us.

**Comment by bartdesmet** [comment]
Micro-benchmark using the code below shows about a 2x:

| Raw | Cache |
|---|---|
| 2.873 | 1.449 |
| 3.177 | 1.510 |
| 2.804 | 1.453 |

```csharp
using System;
using System.Diagnostics;
using System.Reflection;

class GCM
{
  static void Main()
  {
    const int N = 1000000;

    var sw = new Stopwatch();

    sw.Restart();
    for (var i = 0; i < N; i++)
      Foo<int>();
    Console.WriteLine(sw.Elapsed);

    sw.Restart();
    for (var i = 0; i < N; i++)
      Bar<int>();
    Console.WriteLine(sw.Elapsed);
  }

  static MethodInfo Foo<T>()
  {
    return ((MethodInfo)MethodBase.GetCurrentMethod()).MakeGenericMethod(typeof(T));
  }

  private static MethodInfo s_bar;

  static MethodInfo Bar<T>()
  {
    return (s_bar ?? (s_bar = (MethodInfo)MethodBase.GetCurrentMethod())).MakeGenericMethod(typeof(T));
  }
}
```

**Comment by JonHanna** [comment]
Experimenting with 

```C#
static MethodInfo Baz<T>(T x)
{
    return GetMethodInfo(Baz, x);
}

static MethodInfo Qux<T>(T x)
{
    return GetMethodInfoX(Qux, x);
}

static MethodInfo Quxx<T>(T x)
{
    return GetMethodInfoOf(() => Quxx(default(T)));
}

private static MethodInfo GetMethodInfo<T1, T2>(Func<T1, T2> f, T1 _0)
{
    return f.Method;
}

private static MethodInfo GetMethodInfoX<T1, T2>(Func<T1, T2> f, T1 _0)
{
    return f.GetMethodInfo();
}

private static MethodInfo GetMethodInfoOf<T>(Expression<Func<T>> expression)
{
    var body = (MethodCallExpression)expression.Body;
    return body.Method;
}
```
Seems to show `Baz` and `Qux` about on par with each other and a bit ahead of your `Bar` presumably because they don't need `MakeGenericMethod()`. `Quxx` comes in between `Foo` and `Bar`. This was mostly done with desktop though because I'm not getting what I need to do to make `GetCurrentMethod()` available. The figures I get for core versions of what I could do with core (prefill the cache based on a call to `GetMethod()`) are about the same, though.

The `Func`-based approach seems to be the winner here.

**Comment by bartdesmet** [comment]
We've decided over at https://github.com/dotnet/corefx/pull/13561 to go with the delegate approach for the time being, so closing this PR.

**Pull request closed without merging**
