### PR TITLE
Mirror changes from dotnet/corert,coreclr

### PR DESCRIPTION
**Pull request by Anipik**
This PR contains mirrored changes from dotnet/corert,coreclr

**Please REBASE this PR when merging**

 cc @fiigii @fiigii @EgorBo

### CODE REVIEW

**Comment by danmosemsft** [comment]
```
MSBUILD : error MSB4166: Child node "3" exited prematurely. Shutting down. Diagnostic information may be found in files in "/tmp/" and will be named MSBuild_*.failure.txt. This location can be changed by setting the MSBUILDDEBUGPATH environment variable to a different directory.
```

**Comment by danmosemsft** [comment]
@dotnet-bot test Linux-musl x64 Debug Build  pelase

**Comment by danmosemsft** [comment]
@dotnet-bot test Linux-musl x64 Debug Build  pelase

**Comment by jkotas** [comment]
@dotnet-bot test Windows x64 Debug Build please

**Pull request merged**
