### PR TITLE
[release/3.1] Add cgroup2 support

### PR DESCRIPTION
**Pull request by omajid**
This is a cherry-pick of:

- #39633
- #39686

### CODE REVIEW

**Comment by danmoseley** [comment]
Hi @omajid . We have a process ([template](https://github.com/dotnet/corefx/pull/42810#issuecomment-573096370), and tactics meeting review) for backports into servicing releases. The changes have to have significant or widespread customer impact, that sort of thing. Was there someone in particular over here that has context on the motivation for this backport?

**Comment by omajid** [comment]
@danmosemsft Thanks for the pointers. I am going to fill out the template when I have this change passing all tests. The short version, though, is that various Linux distributions are starting to enable cgroupv2 ([more details in this blog post](https://medium.com/nttlabs/cgroup-v2-596d035be4d7)) and without support for cgroupv2, .NET Core wont work correctly in containerized environments when cgroupv2 is used on the host.

**Comment by omajid** [comment]
Test failures look unrelated:

```
    System.Drawing.Tests.BitmapTests.GetFrameCount_NewBitmap_ReturnsZero [FAIL]
      System.Runtime.InteropServices.ExternalException : A generic error occurred in GDI+.
      Stack Trace:
        /_/src/System.Drawing.Common/src/System/Drawing/Gdiplus.cs(175,0): at System.Drawing.SafeNativeMethods.Gdip.CheckStatus(Int32 status)
        /_/src/System.Drawing.Common/src/System/Drawing/Image.cs(271,0): at System.Drawing.Image.GetFrameCount(FrameDimension dimension)
        /_/src/System.Drawing.Common/tests/BitmapTests.cs(555,0): at System.Drawing.Tests.BitmapTests.GetFrameCount_NewBitmap_ReturnsZero()
    System.Drawing.Tests.IconTests.CorrectColorDepthExtracted [FAIL]
      Assert.Equal() Failure
      Expected: 2275337522
      Actual:   2275337265
      Stack Trace:
        /_/src/System.Drawing.Common/tests/IconTests.cs(864,0): at System.Drawing.Tests.IconTests.CorrectColorDepthExtracted()
```

**Comment by danmoseley** [comment]
@stephentoub looks like you have context on the original changes and can suggest whether this meets the servicing bar.

**Comment by omajid** [comment]
I am going to withdraw this servicing request, at least for now.

The coreclr-side changes haven't even been merged in master, and the corefx changes by themselves are not sufficient. Also, I just ran into some systems where it seems possible to have both cgroup1 and cgroup2 enabled. I think we need much more thorough testing and baking time and an LTS release might not be the best place for these changes right now.

**Pull request closed without merging**
