### PR TITLE
Revert "Enable api compat"

### PR DESCRIPTION
**Pull request by ellismg**
Reverts dotnet/corefx#8513

OSX CI has been hanging since this change, it seems.  Reverting to see if this fixes things (It looks like the PR job Wes did also hung) or if there is a deeper issue.

### CODE REVIEW

**Comment by ellismg** [comment]
@weshaggard It looks like with your changes the OSX builds are hanging or crashing.  There are a bunch of errors in the logs which look related to the API Compat infrastructure as well.

Should we just roll back the change?  In addition to blocking CI, when the jobs hang they eat machines for a long while.

/cc @stephentoub

**Comment by stephentoub** [comment]
Seems like this did address the problem. I'd like to see this merged until we can determine the cause. Thanks, Matt!

**Comment by ellismg** [comment]
Going to merge this.  Wes, if you want to add this back but disabled when build on OSX, so we still have coverage, that could be okay, I think.

**Comment by weshaggard** [comment]
Thanks for rolling back @ellismg. I will have a closer look, I orginially merged it because I was seeing OSX issues in other PR's so I didn't think is was related to this change.

**Pull request merged**
