### PR TITLE
Merging Changes from ReflectionBasedDCS to master

### PR DESCRIPTION
**Pull request by shmao**
The PR is to merge changes from ReflectionBasedDCS branch to master branch. The changes enable DCS/DCJS to do serialization without IL emit.

/cc: @mconnew @roncain @Zhenlan @huanwu

### CODE REVIEW

**Comment by shmao** [comment]
@dotnet-bot test Innerloop CentOS7.1 please
@dotnet-bot test Innerloop Ubuntu14.04 please
@dotnet-bot test Innerloop Windows_NT Debug Build and Test please

**Comment by shmao** [comment]
@dotnet-bot test Innerloop CentOS7.1 please

**Comment by shmao** [comment]
Each commit of the PR had already been reviewed. I'm going to merge the PR.

**Comment by stephentoub** [comment]
As @jasonwilliams200OK pointed out at https://github.com/dotnet/corefx/pull/10853#issuecomment-240078506, this was merged with failures in the Linux builds caused by this PR.  This should not have been merged.

**Comment by shmao** [comment]
Sorry, I shouldn't have merged the PR. I will fix the failed tests.

**Pull request merged**
