### PR TITLE
[release/3.1]  update Ubuntu and Alpine RID

### PR DESCRIPTION
**Pull request by wfurt**
This is port of https://github.com/dotnet/runtime/pull/37031 to add new RID for Ubuntu and Alpine releases.

fixes https://github.com/dotnet/runtime/issues/37000

I'm not sure what the approval process is for this @danmosemsft. 
Discussion in https://github.com/dotnet/corefx/pull/42871 sugests "tell-mode"  but I'm not sure if that is still correct.

### CODE REVIEW

**Review by ericstj — APPROVED** [review]

**Comment by danmoseley** [comment]
@wfurt my bad, missed your question. you do not need approval for RID changes and other changes just related to keeping up with distros. just set servicing-approved and @Anipik will merge it. (It's best for him to merge as sometimes branches are closed)

Should there be a change for 2.1 as well?

**Comment by wfurt** [comment]
I don't know @danmosemsft. I can look at 2.x history and craft PR as well if needed.

**Comment by danmoseley** [comment]
@wfurt I verified at tactics -- yes, please port to 2.1 and again consider approved, for anirudh to merge.

**Comment by danmoseley** [comment]
@Anipik is branch open? that's why i figured it's best that you do all the merges

**Comment by wfurt** [comment]
ops. sorry. I can roll it back.

**Comment by danmoseley** [comment]
I'll let @anipik say but almost surely it's fine. I just don't keep track of when branch is open or not.

**Comment by Anipik** [comment]
The branch is supposed to open next tuesday. I can help here and make sure we dont produce a new build.

**Comment by wfurt** [comment]
thanks.

**Pull request merged**
