### PR TITLE
Small change in MatchPattern()

### LINKED ISSUE #32979: Question about logic in MatchPattern()
Why `if (text.Length - index < Pattern.Length) { ...}` is not before line 210?
https://github.com/dotnet/corefx/blob/2f259de0bc566f4ef72e486133f71210416e440a/src/System.Text.RegularExpressions/src/System/Text/RegularExpressions/RegexBoyerMoore.cs#L208-L223

### PR DESCRIPTION
**Pull request by iSazonov**
Fix #32979

### CODE REVIEW

**Comment by stephentoub** [comment]
Doesn't string.Compare already do such a check implicitly? I'm wondering why the check is necessary for either branch, and whether it can just be deleted.

If it's functionally necessary, we should add a test as part of this that fails before and succeeds after.

If it's not functionally necessary, was the check there for perf for some reason? Probably not, but perf tests should be run.

**Comment by stephentoub** [comment]
cc: @viktorhofer

**Comment by ViktorHofer** [comment]
Same as Stephen I expect the check to be handled by string.Compare. Instead of changing the order of execution here I would just remove the check and run unit and performance tests (and make sure that our test covers that).

**Comment by iSazonov** [comment]
I don't see the check in string.CompareOrdinal.

**Comment by stephentoub** [comment]
I see.  Even though the code is doing an equality check, it's using Compare to do it.  Compare can't factor in length first (as you can in equality), because length only matters when comparing strings if all characters are equal up until the length of the shorter string.  So to short-circuit that in case they don't match, it's doing the length check as an optimization, because it does actually care about equality.  Ok.

**Comment by iSazonov** [comment]
I personally do not know what exactly it would be necessary to check because there are no functional changes.

**Comment by stephentoub** [comment]
> I personally do not know what exactly it would be necessary to check because there are no functional changes.

Whether it's intended to be a functional change or not, the issue is that it's changing code, and any time that happens, we want to make sure there's good test coverage.  In this case, there isn't: a code coverage report shows that the "return false;" branch is never taken by any of the tests.  Which means either we should be removing this check entirely because it's dead code (or it's an unnecessary optimization that's not actually an optimization), or we're missing important tests.

**Comment by iSazonov** [comment]
@stephentoub Thanks! I see your point. The code is too complicated for me to understand reading the source code how it works. I can guess that simple test is `Match("123", "1234")`. Perhaps optimization works well and the following also works `Match("123", "(1234|12345")`.
Please do not ask me to do this test. This is very interesting, but I'm still very busy. I started learning how Unicode simple case folding can help us speed up PowerShell. If our expectations are met, it will be a very useful extension of `System.Globalization` which could be used everywhere where there is a cae-insensitive string search.

**Comment by stephentoub** [comment]
> Please do not ask me to do this test. This is very interesting, but I'm still very busy.

That's fair.  In that case, we should revert the PR until it can be properly tested / proved that it's actually a meaningful change.

**Comment by iSazonov** [comment]
@ViktorHofer Thanks! So this omission is there anyway with and without the fix. And this is only one of the two - great code coverage.

**Comment by ViktorHofer** [comment]
> So this omission is there anyway with and without the fix

Correct. We need to determine if that code path is just dead code or just not covered yet. After that we can make adjustments to that code. path

**Comment by stephentoub** [comment]
> So this omission is there anyway with and without the fix.

Yes, that was my point. We don't like changing code that doesn't have test coverage. The change has no expected functional impact, but we can't rely on tests to catch bugs because we obviously are missing tests. And no perf testing was done to suggest the change has any perf benefit. So changing is more risky than not.

**Comment by iSazonov** [comment]
The test seems has pattern > text.
https://github.com/iSazonov/corefx/blob/d331f0ef8103cbfe1c547eb3e1ffd1f639a0a19a/src/System.Text.RegularExpressions/tests/Regex.Match.Tests.cs#L80

**Pull request merged**
