### PR TITLE
Publish corefx test assets

### PR DESCRIPTION
**Pull request by mikem8361**
So coreclr and other repos can run the corefx tests.

New step to publish the test zip files to dotnet-core blob storage.

Publishes the build manifest from above to blob storage path:

https://dotnetfeed.blob.core.windows.net/dotnet-core/corefx-tests/$(Version)/$(RuntimeOS).$(ArchGroup).$(ConfigurationGroup)/$(TargetGroup)/corefx-test-assets.xml

Uses the new Arcade ParseBuildManifest helper build task to read the above manifest and to create an ItemGroup of the test zips.

Uses the ItemGroup to send the tests to helix using the new PayloadUri metadata on the HelixWorkItem item.

### CODE REVIEW

**Comment by mikem8361** [comment]
This PR isn't ready for two reasons that I didn't see before:

1) The public CI obviously still needs to upload the test assets before it doesn't have access (and probably shouldn't) to the variable group containing the PAT for dotnet-core blob storage.
2) Test assets are redundantly being uploaded because the assets are being uploaded for each OS/Platform/TargetGroup which is part of the blob storage i.e. the test assets for all the Windows x64_Release, Windows x86_Release, Windows NEXTFX_x64_Release are all the same.  They really only differ between Windows, Linux and OSX. But I'm not sure how to do this yet because each job (OS/Platform/Config, etc) builds and zips the test assets and sends them to helix independently.

In the end there really only should be 3 sets of test assets uploaded: Windows, Linux and OSX. 

I'm going to close this PR until I figure this out.

**Comment by safern** [comment]
> 1. The public CI obviously still needs to upload the test assets before it doesn't have access (and probably shouldn't) to the variable group containing the PAT for dotnet-core blob storage.

Why? I thought we where only going to upload this manually during official builds?

**Comment by mikem8361** [comment]
I decided to do the same thing in corefx that will happen in coreclr to test and to save a little time. In the official build, uploading the test assets to dotnet-core and sending the URIs to helix isn’t any different than what the send to helix stuff was doing before except the helix SDK was implicitly doing the upload to a private blob storage.  I thought this would save a little time instead of uploading to dotnet-core and having helix upload again.  It would also test/verify the steps/build task/arcade changes that would be used on the coreclr side.

Both of the problems I outlined make me think I need to use helix SDK to do the upload like before and only in one job per platform (Windows, Linux, OSX) upload the test assets to dotnet-core. This is what you probably thought I was going do to begin with. This will solve both problems: not doing any uploads to dotnet-core in the public ci builds and only uploading the assets for the 3 platforms.

**Comment by safern** [comment]
> This is what you probably thought I was going do to begin with. This will solve both problems: not doing any uploads to dotnet-core in the public ci builds and only uploading the assets for the 3 platforms.

Yes, that is what I thought was the initial plan to begin with. Also, you might also want to consider uploading arm assets for those platforms, in case coreclr and mono want to use those to test in arm as well.

**Comment by mikem8361** [comment]
Are the arm assets different from the x64 ones?

For Windows arm/arm64 and Linux arm we don’t send any tests to helix and the test zips are not created.

**Comment by safern** [comment]
> Are the arm assets different from the x64 ones?

Yes they are. 

> For Windows arm/arm64 and Linux arm we don’t send any tests to helix and the test zips are not created.

Correct, we will eventually start testing on those archs though.

**Comment by ViktorHofer** [comment]
I think we should upload all the tests assets for all different targetgroups/osgroups/archgroups. Basically all variants of $(BuildConfiguration). I don't see any reason why we shouldn't upload all of them. Size shouldn't matter as there is a retention policy in place.

**Pull request closed without merging**
