### PR TITLE
Don't trample $(OS), use to determine current environment in $(OsEnviron...

### PR DESCRIPTION
**Pull request by JeremyKuhne**
...ment)

The only place we're consuming $(OS) is in the build tools, and fortunately that is currently looking for Windows_NT (which is what is set in a Windows environment).

@weshaggard, @stephentoub

### CODE REVIEW

**Comment by JeremyKuhne** [comment]
@dotnet-bot test this please

**Comment by ellismg** [comment]
BTW, CoreCLR uses the OS to mean the target, not the host, when building mscorlib, so I suspect you will want to make similar changes there.

**Comment by JeremyKuhne** [comment]
I updated the Wiki and all of the CoreFx build definitions. OS was ultimately setting OSGroup so the transition should just work (before/after this change). I'll be updating CoreCLR when I finish getting CoreFx building on MSBuild/Linux.

**Comment by ellismg** [comment]
@JeremyKuhne There are also comments in some of the docs in https://github.com/dotnet/coreclr/blob/master/Documentation/ (talking about how to build CoreFX for different platforms).  You'll want to do a PR for that as well.

**Comment by JeremyKuhne** [comment]
Updated the commit message. Fixed my box where the user info was different. I'll update the docs that you mention.

**Comment by ellismg** [comment]
Thanks.  LGTM.

**Comment by stephentoub** [comment]
For context, can you elaborate on why this needs to change?

Was the CI system updated to pass the right flags, too?

**Comment by JeremyKuhne** [comment]
@stephentoub Some of these details are inline. I updated all of the build definitions and docs to use OSGroup. We shouldn't be stomping on any normal environment variable. This particular one is understood to mean the current OS, not the target OS. The build needs a concept of current OS (which I already introduced), but I wasn't able to change initially as I had to validate OS hadn't leaked into the rest of the build (as opposed to OSGroup). Also note that the prior way I was getting the OS doesn't work on XBuild.

**Comment by weshaggard** [comment]
LGTM

**Pull request merged**
