### PR TITLE
I deleted the duplicate code in IList.Generic.Tests

### PR DESCRIPTION
**Pull request by AlexRadch**

### CODE REVIEW

**Comment by stephentoub** [comment]
I agree with @Wraith2, this doesn't look like duplication to me.

**Comment by AlexRadch** [comment]
@Wraith2, @stephentoub removed code is duplicate of code above it!

**Comment by stephentoub** [comment]
Thanks. You're right, it is... except for the `!AddRemoveClear_ThrowsNotSupported && ` check.  Why are things passing now without that check on this duplicated block, and if they're supposed to pass, then why is the check necessary on the above block?

**Comment by AlexRadch** [comment]
>  Why are things passing now without that check on this duplicated block, and if they're supposed to pass, then why is the check necessary on the above block?

I wrote `UnsafeSpan` struct in https://github.com/AlexRadch/DrNet to support collections interfaces above Span.
To test implementation of collections interfaces like IList, ICollection, IEnumerable and etc. I used test code from corefx.
The Span does not support insertion so 'duplicated code' that I removed does not passing on my structure.
`!AddRemoveClear_ThrowsNotSupported` checking is correct but 'duplicated code' is not.

**Comment by stephentoub** [comment]
@Wraith2, when you introduced this stuff recently, were you just being proactive with the AddRemoveClear_ThrowsNotSupported exception?  Since everything's passing, it would seem then we don't have any collections where Add/Remove/Clear throws NotSupportedException?  I'm not arguing with the property, but I want to make sure we're not missing something here.

**Comment by Wraith2** [comment]
I was being proactive. I wanted to make sure if anyone needed the capability in future they didn't have to do a big re-org of all the tests the way I was having to. 

It wasn't clear to me from the initial diff what the change was about but now I've reviewed the original file directly I see what this is about, good to go.

**Comment by AlexRadch** [comment]
@stephentoub There are `ModifyEnumeratorThrows` virtual property. So if set it to `ModifyOperation.None`  then all checks will be skipped also.

I think that current code should not skip some checks if `ModifyEnumeratorThrows` property is changed to `ModifyOperation.None`.

It should be corrected I think.

**Comment by Wraith2** [comment]
`ModifyEnumerableAllowed` and `ModifyEnumerableThrows` are allowed to be any combination that makes sense for the type being tested. Different types support different operations and behaviours. If a type never throws on alteration while being enumerated the `None` is a correct value. Any operation which is not supposed (for example `Insert` on queues) would not appear in either property value.

**Comment by stephentoub** [comment]
Thanks.

**Pull request merged**
