### PR TITLE
Disable large copy test causing hangs

### PR DESCRIPTION
**Pull request by stephentoub**

### CODE REVIEW

**Comment by stephentoub** [comment]
@dotnet-bot test Outerloop Windows x64 Debug Build please

**Comment by stephentoub** [comment]
@ahsonkhan, FYI.

**Comment by ahsonkhan** [comment]
Should we disable the other ones too (like ParserTests.2gbOverflow)?

**Comment by stephentoub** [comment]
> Should we disable the other ones too (like ParserTests.2gbOverflow)?

If they cause problems, yes.  The ones I disabled were the ones I saw causing problems.

**Comment by ahsonkhan** [comment]
> > If they cause problems, yes (and then figure out how to fix them or delete them). The ones I disabled were the ones I saw causing problems.

Can we merge this PR in and let it run for a bit to catch problematic tests?
https://github.com/dotnet/corefx/pull/25271

Or maybe, can we re-run the outerloop in the CI again (now that the CopyTo test has been disabled)?

**Comment by stephentoub** [comment]
> Or maybe, can we re-run the outerloop in the CI again (now that the CopyTo test has been disabled)?

I ran outerloop on this PR and it passed.  Is that what you mean?

> The active issue that you linked to already shows that other tests are causing problems.

It does?  Which?

**Comment by ahsonkhan** [comment]
> It does? Which?

ParserTests.2gbOverflow (given the snippet of the logs posted)

> I ran outerloop on this PR and it passed. Is that what you mean?

Yes, but don't these tests fail intermittently?

**Comment by stephentoub** [comment]
> ParserTests.2gbOverflow (given the snippet of the logs posted

I don't think those logs show that.  That's the same output as when this copy test hung.

> but don't these tests fail intermittently?

Not from what I saw.

> I don't see the CI showing green after you disabled the tests. 

Which run?  This whole PR, including the outerloop run, was green before I merged.  Where are you looking?

**Comment by ahsonkhan** [comment]
> Not from what I saw.

**Pull request merged**
