### PR TITLE
Update the framework from netstandard1.5 to netstandard1.6 for AppContext

### PR DESCRIPTION
**Pull request by AlexGhiondea**

### CODE REVIEW

**Comment by AlexGhiondea** [comment]
Addresses the build warnings from #8979

**Comment by stephentoub** [comment]
Thanks for fixing the warnings, Alex.

**Comment by stephentoub** [comment]
cc: @ericstj

**Comment by mellinoe** [comment]
LGTM

**Comment by weshaggard** [comment]
LGTM

**Pull request merged**
