### PR TITLE
Remove UAP console PAL

### PR DESCRIPTION
**Pull request by danmosemsft**
We expect to get Console API's approved so we shouldn't need the PAL (which only throws everywhere)

Also it was hiding these APIs we needed. I'll make sure they're all on our request list.

### CODE REVIEW

**Comment by stephentoub** [comment]
> We expect to get 

When will we know?  I'm just wondering if we should wait for changes like this until then.

**Comment by danmosemsft** [comment]
@stephentoub yes, it's a balance (you saw I already did something similar for IO paths). Where what we're deleting is stubs like this, it shouldn't be difficult to bring back if we have to. Meantime doing this enables us to get test coverage within appcontainer, and find bugs, while we wait.

Also in this case Peter T mentioned console support was coming.

**Comment by danmosemsft** [comment]
I am going through all other UAP specific code to make sure we didn't miss any pinvokes in the same way - that doesn't mean I need to swap it out llike this of course.

**Comment by danmosemsft** [comment]
@dotnet-bot test innerloop osx10.12 release x64 build and test (@mmitche, it was only getting 50.00 KiB/s  cloning and timed out)

**Comment by danmosemsft** [comment]
Still cloning super slow.

**Comment by danmosemsft** [comment]
@dotnet-bot test Innerloop OSX10.12 Debug x64 Build and Test please (network)
@dotnet-bot test Innerloop OSX10.12 Release x64 Build and Test please (network)

**Comment by danmosemsft** [comment]
@dotnet-bot test Innerloop OSX10.12 Release x64 Build and Test (network)

**Comment by danmosemsft** [comment]
@jkotas In general how do you feel about me deleting UAP only stub codepaths? I did this already for some IO ones as you saw.

This gives us valuable coverage now in appcontainer but if somehow allowlisting falls through, the stubs may have to come back. I think this is a reasonable risk.

Some of these stubs have caused me to overlook some necessar allowlist requests which is another reason to remove them.

**Comment by jkotas** [comment]
> how do you feel about me deleting UAP only stub codepaths?

I do not think there is much harm it in. It will very likely require some adjustments before we ship in any case.

**Pull request merged**
