### PR TITLE
Add '--testTFM' option and set default to netcoreapp1.1 in run-test.sh

### PR DESCRIPTION
**Pull request by hseok-oh**
By #12241, netcoreapp1.1 become new default TestTFM for all project. 
We need to change default netcoreapp1.0 to 1.1, and add new option to set TestTFM

### CODE REVIEW

**Comment by stephentoub** [comment]
cc: @weshaggard

**Comment by weshaggard** [comment]
I'm not sure what context this run-test.sh script is used in anymore. We have moved to using build.sh for all our builds. @hseok-oh what context are you using this script where the default build.sh scripts don't work? Is this for a platform that doesn't have a supported CLI yet? @ellismg are you aware of any contexts where we still use run-tests.sh?

**Comment by weshaggard** [comment]
(sorry accidentally hit the close button)

**Comment by hseok-oh** [comment]
@weshaggard It need for ARM 32 bit with linux, such as Raspberry Pi 2 or 3. We need to build CoreCLR and CoreFX using cross compilation in x64(or x86) linux, install to target machine, and test.

**Comment by ellismg** [comment]
As @hseok-oh this is used in cross build scinerios, for ARM.

**Comment by weshaggard** [comment]
I'm fine with this option being included but I do think we need to figure out how to improve this script and unify it with the way we do testing for our other platforms. Right now it is making some assumptions that are very fragile and will likely break often.

**Pull request merged**
