### PR TITLE
Port PR 8674  Added basic diagnostics to SqlConnection

### PR DESCRIPTION
**Pull request by saurabh500**
This pull request includes the basic logging for SqlConnection for the Open(), OpenAsync(), and Close() operations, logging Before, After, and Error events.

### CODE REVIEW

**Comment by saurabh500** [comment]
cc @tstringer @avanderhoorn

**Comment by stephentoub** [comment]
Test Innerloop Ubuntu14.04 Debug Build and Test please (out of disk space)

**Comment by saurabh500** [comment]
@stephentoub What do we do about the failing check because of disk space issue?

**Comment by stephentoub** [comment]
@mmitche is working on it...

**Comment by stephentoub** [comment]
Test Innerloop Ubuntu14.04 Debug Build and Test please (disk space)

**Pull request merged**
