### PR TITLE
Update buildtools version

### PR DESCRIPTION
**Pull request by MattGal**
Needed for missing AnyOS tests on full runs

### CODE REVIEW

**Comment by MattGal** [comment]
(Will try again when the package shows up on the feed)

**Comment by MattGal** [comment]
@dotnet-bot Test this please

**Comment by MattGal** [comment]
@dotnet-bot  Test this please

**Comment by MattGal** [comment]
@dotnet-bot  Test this please

**Comment by stephentoub** [comment]
@dotnet-bot test this please

**Comment by MattGal** [comment]
All builds passed, merging to fix tomorrow's master builds.

**Pull request merged**
