### PR TITLE
Update README.md with additional libraries

### PR DESCRIPTION
**Pull request by stephentoub**
Also fixed a link and the ordering of a few libraries.

### CODE REVIEW

**Comment by stephentoub** [comment]
cc: @richlander 

@terrajobst, the spreadsheet linked from the README.md that lists projects to be moved to GitHub appears to be out-of-date, not showing a bunch of projects that are now in fact on GitHub.  Can we get it updated?  Thanks.

**Comment by akoeplinger** [comment]
@stephentoub see https://github.com/dotnet/corefx-progress/issues/2#issuecomment-95965814

**Comment by stephentoub** [comment]
> sorry, just saw you were talking about the spreadsheet, I think we should replace that with a link to the corefx-progress repo anyway.

I'd be happy with that as the solution.

**Comment by richlander** [comment]
@stephentoub Do you want to just add that change to your PR (already updating the right file)?

**Comment by stephentoub** [comment]
Sure.

**Comment by stephentoub** [comment]
Updated the link.  Thanks for the suggestion, @akoeplinger.

**Pull request merged**
