### PR TITLE
Add WebAssembly build architecture

### LINKED ISSUE #26107: Add WebAssembly CoreFX build architecture
As the [CoreRT](https://github.com/dotnet/corert/issues/4659) and [Mono](http://www.mono-project.com/news/2017/08/09/hello-webassembly/) WebAssembly experiments progress, we'll want to start running CoreFX libraries (starting with System.Console). As a first step, we need to add a new build architecture in the CoreFX repo that can produce architecture-specific packages.

This should allow running ```build wasm``` similarly to ```build x86```. To match the CoreRT repo, the build flavor should set ```OSGroup``` to ```WebAssembly``` and ```Platform``` to ```wasm```. In general, settings should match Unix outputs as the WebAssembly platform is pretty similar (but it should be possible to run the build on Windows).

For examples, https://github.com/dotnet/corert/commit/da8c27da9644cd658b906cfbd0f6c9997d91c355 added the flavor in CoreRT, https://github.com/dotnet/corert/commit/15ce20d82918bb04009a30e3dbcebce85b1dd80e rounded out native compilation for it, and  https://github.com/dotnet/corert/commit/3d25db5b1c010346bbc480a20646c80ea413492f fixed issues in it.

### PR DESCRIPTION
**Pull request by morganbr**
Adds a WebAssembly build architecture (and matching OS) based on using the Emscripten SDK. For the most part, this flavor is similar to Unix (but can be built by any OS). While the current changes are focused on the CoreRT WebAssembly implementation, they will most likely be useful for Mono as well.

This change includes:
* Adding the ```wasm``` architecture and ```WebAssembly``` OS
* Changes to run emscripten for wasm on Windows (building on Mac/Linux can be done in a future change). This also includes compensating for emscripten's tendency to return true for check_function_exists for functions it doesn't actually have.
* Fixes for building System.Native (other native libraries are disabled for now as they have larger dependencies that may not map as well)

The managed build doesn't work yet as contracts need to target the .NET Native System.Private.Corelib, but breaking changes in the Memory class prevent them from compiling. 

Fixes #26107

### CODE REVIEW

**Comment by stephentoub** [comment]
Thanks, @morganbr. I'm going to add no-merge to this just for this week, to avoid churning these native files until master is targeting 2.2 instead of 2.1.

**Comment by morganbr** [comment]
@stephentoub, sounds reasonable. Hopefully we can work through feedback in that time and have it ready to go.

**Comment by morganbr** [comment]
@dotnet-bot build and test OSX x64 Debug Build please
@dotnet-bot build and test Linux x64 Release Build please

**Comment by morganbr** [comment]
@dotnet-bot build and test Linux x64 Release Build please

**Comment by morganbr** [comment]
@stephentoub, @ericstj, this is finally ready to review.

**Comment by karelz** [comment]
@morganbr @ericstj are there plans to review it? It is rather old PR ...

**Comment by morganbr** [comment]
@ericstj, I've undone runtimeGroups.props (and runtime.depproj) and we can worry about packaging and building managed code in a future change.

Building managed code will depend on #30980.

**Comment by ericstj** [comment]
I'm still seeing changes to the runtime graph: https://github.com/dotnet/corefx/pull/28936/files#diff-e3595732c7ee641a01385cfc918307baL3

I was ok with changes to runtime.depproj, but not the shipping runtime.json.  The concern is that we don't ship the `wasm` entries in the runtime.json in the next .NETCore release and then have to deal with a breaking change if you need to change them later on.  I went ahead and implemented what I was suggesting, it requires a [buildtools change](https://github.com/dotnet/buildtools/commit/82143335207864afd83f977476c61ca236d60ce9) in order to enable it: https://github.com/ericstj/corefx/commit/29bf851abdaa6fc1a0e636c1038c8cb26cb4c76c

**Comment by ericstj** [comment]
Test this please

**Comment by ericstj** [comment]
Test OSX x64 Debug Build

**Comment by morganbr** [comment]
@karelz, I've tested @ericstj's changes and it looks good, so I'll go ahead and merge. Thanks for the help, @ericstj!

**Pull request merged**
