### PR TITLE
Enable HttpStress to target http.sys in addition to Kestrel

### PR DESCRIPTION
**Pull request by stephentoub**
cc: @geoffkizer, @eiriktsarpalis, @Anipik

### CODE REVIEW

**Comment by karelz** [comment]
Just FYI: This PR was merged into master after the cut off and for of 3.0 out of master branch.

**Comment by davidsh** [comment]
>Just FYI: This PR was merged into master after the cut off and for of 3.0 out of master branch.

@karelz Actually, there was a side email on this and we got into the release/3.0 branch.

**Comment by stephentoub** [comment]
Yup, doesn't need to be in the 3.0 branch.

**Comment by davidsh** [comment]
>@karelz Actually, there was a side email on this and we got into the release/3.0 branch.

oops....wrong issue.  But actually, this stress test doesn't need to be in the release/3.0 branch.

**Pull request merged**
