### PR TITLE
Bug fix in tests

### PR DESCRIPTION
**Pull request by KrzysztofCwalina**

### CODE REVIEW

**Comment by sharwell** [comment]
Is there any reason why this is implemented manually, instead of just the following?

```csharp
public bool Equals(T[] x, T[] y)
{
    if (x.Length != y.Length)
    {
        return false;
    }
    for (int i = 0; i < x.Length; i++)
    {
        if (!EqualityComparer<T>.Default.Equals(x[i], y[i]))
            return false;
    }
    return true;
}
```

**Comment by KrzysztofCwalina** [comment]
Yeah, as I said in the other comment, the code got more general and complicated over several reviews and changes. I think you are right that now it crossed the boundary of being reasonable as an open coded block. I will fix that.

**Comment by mmitche** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://corefx-ci.cloudapp.net/jenkins/job/CoreFX_Linux_Build/86/
Test FAILed.

**Comment by mmitche** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://corefx-ci.cloudapp.net/jenkins/job/CoreFX_Windows_Build/88/
Test PASSed.

**Comment by mmitche** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://corefx-ci.cloudapp.net/jenkins/job/CoreFX_Linux_Build/87/
Test FAILed.

**Comment by mmitche** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://corefx-ci.cloudapp.net/jenkins/job/CoreFX_Windows_Build/89/
Test PASSed.

**Comment by mellinoe** [comment]
Latest version looks good to me.

**Pull request merged**
