### PR TITLE
Add back private ctors removed incorrectly in System.Drawing.Common

### LINKED ISSUE #21270: Add back some private constructors in System.Drawing.Common
https://github.com/dotnet/corefx/commit/f6bb2b5bb5f8841e839fb99eb60118b7b37c4901 removed a few private constructors, because they are not interesting for .NET Core. We should add them back behind a flag, because mono needs them to stick around when they compile this code.

@hughbe

### PR DESCRIPTION
**Pull request by hughbe**
Fixes #21270

### CODE REVIEW

**Comment by justinvp** [comment]
Actually, thinking about it more, these public sealed classes w/ private constructors are essentially static classes (same IL is emitted). Should we just make these static classes in the implementation and ref? We've done it before in .NET Core, e.g. https://github.com/dotnet/coreclr/pull/11439

Also, do we really need the tests for the private constructors?

**Comment by hughbe** [comment]
> Should we just make these static classes in the implementation and ref? 

I wasn't sure, because the mono folks said that they rely on the private constructor existing

> Also, do we really need the tests for the private constructors?

Regression tests, I guess. Again, apparently the Mono engineers need to use it so it's good to make sure

**Comment by justinvp** [comment]
I think @marek-safar was just [saying](https://github.com/dotnet/corefx/commit/f6bb2b5bb5f8841e839fb99eb60118b7b37c4901#commitcomment-22653593) that by removing the private constructor, a default public constructor will be emitted, when the intention for these classes is to be effectively static.

@marek-safar, any problem making these static classes (via `static class`)? They're essentially already static as they're sealed with private constructors.

Regarding the tests -- I don't think we typically test that static classes can be instantiated by calling the private constructor via reflection.

cc: @mellinoe

**Comment by hughbe** [comment]
If we change them to static, then I agree that we can delete the tests

**Comment by hughbe** [comment]
Test Windows x86 Release Build

**Comment by marek-safar** [comment]
I am ok with making the classes properly static

**Comment by hughbe** [comment]
Test Windows x86 Release Build

**Comment by mellinoe** [comment]
@hughbe Unfortunately, there's another merge conflict 😞 . Shouldn't be too hard to reconcile.

**Comment by hughbe** [comment]
Rebased to fix those pesky merge conflicts

**Comment by hughbe** [comment]
Test Windows x64 Debug Build
Test OSX x64 Debug Build

**Comment by hughbe** [comment]
Test Windows x64 Debug Build

**Pull request merged**
