### PR TITLE
Reenabled dns lookup tests

### PR DESCRIPTION
**Pull request by ViktorHofer**
Fixes https://github.com/dotnet/corefx/issues/4002

### CODE REVIEW

**Comment by stephentoub** [comment]
@ViktorHofer, did the tests pass for you locally?

**Comment by ViktorHofer** [comment]
@stephentoub I just noticed that I run the tests with the old source. Please wait for another commit!

**Comment by ViktorHofer** [comment]
The changes I made, don't make any sense as these tests should test DualMode. So establishing a connection to "www.microsoft.com" isn't helpful at all...

**Comment by davidsh** [comment]
>The changes I made, don't make any sense as these tests should test DualMode. So establishing a connection to "www.microsoft.com" isn't helpful at all...

I think there is confusion about what this test is. "DualMode" is a concept for listening sockets and not outbound sockets.  It allows a socket to listen on both an IPv4 and IPv6 address at the same time. This helps developers since they don't have to create 2 sockets on a server to listen for both IPv4 and IPv6.

I think this test was creating a listener and testing for receiving data on both IPv4 and IPv6. It thus required DNS resolution of the server endpoint to return both A and AAAA DNS records.  In addition, it probably required listening on that dual-mode socket.

Changing this test to 'www.microsoft.com' might be testing the DNS resolution part of the test but it isn't testing receiving data on a dual-mode socket.  We presumably used 'localhost' here because we were creating a loopback server to listen on.

**Comment by stephentoub** [comment]
@ViktorHofer, I'm going to close the PR for now.  Of course feel free to re-open or open a new PR when you figure out how you want to tackle these.

**Pull request closed without merging**
