### PR TITLE
Fix missing EnsureWriter()

### LINKED ISSUE #28747: DelimitedListTraceListener Constructor strange behavior
I tested this code :
```
var Listener = new DelimitedListTraceListener("test.txt");
Listener.Delimiter = ",";
Trace.Listeners.Add(Listener);
Trace.Write("x");
Trace.WriteLine("y");
Trace.TraceError("z");
Trace.TraceInformation("w");
Trace.Flush();
```
It workes in windows forms app, but in a .net Core console app, it didn't create the file, and after I manually created the file it didn't write any thing to it!
I had to modify the code to create the file myself and then close it:
```
var s = File.Open ("test.txt", FileMode.OpenOrCreate);
var Listener = new DelimitedListTraceListener(s);
Listener.Delimiter = ",";
Trace.Listeners.Add(Listener);
Trace.Write("x");
Trace.WriteLine("y");
Trace.TraceError("z");
Trace.TraceInformation("w");
Trace.Flush();
s.Close();
```
This worked but gave strange results regaring the delimiters as I showed here: https://github.com/dotnet/corefx/issues/28697
It seems that the constructor that accepts the file path doesn't work in .NET core, but works in .NET framework!

### PR DESCRIPTION
**Pull request by MarcoRossignoli**
fixes #28747 

I copied missing part from netfx source https://referencesource.microsoft.com/#System/compmod/system/diagnostics/TextWriterTraceListener.cs,157

cc: @brianrob @stephentoub

### CODE REVIEW

**Comment by wtgodbe** [comment]
@danmosemsft I don't own System.Diagnostics.Tracing, this area belongs to @brianrob, @vancem, @valenis

**Comment by danmosemsft** [comment]
@wtgodbe to my knowledge this does not relate to System.Diagnostics.Tracing: this is System.Diagnostics.TextWriterTraceListener. Think Trace.WriteLine and so forth.

**Comment by danmosemsft** [comment]
Thanks @MarcoRossignoli!

**Comment by MohammadHamdyGhanem** [comment]
@MarcoRossignoli 
Thanks a lot.
But, was there a reason to drop this missing part in first place? Does it affect other operating syatems other than windows? Do you tested this fix for linux and MacOS?

**Comment by MarcoRossignoli** [comment]
> But, was there a reason to drop this missing part in first place?

I don't know, maybe @danmosemsft or @wtgodbe know the reason.

>Do you tested this fix for linux and MacOS

Every change to code is compiled and tested cross plat.

**Pull request merged**
