### PR TITLE
Environment.ProcessorCount: use runtime implementation via EnvironmentAugments

### PR DESCRIPTION
**Pull request by tmds**
This doesn't build on my machine (yet):

> 'EnvironmentAugments' does not contain a definition for 'ProcessorCount'

EnvironmentAugments.ProcessorCount was added in https://github.com/dotnet/coreclr/pull/15297.

I've made the change for all platforms (i.e. also Windows) and removed the corefx implementation.

CC @stephentoub @jkotas

### CODE REVIEW

**Comment by jkotas** [comment]
You can also delete src\Common\src\Interop\Windows\kernel32\Interop.GetLogicalProcessorInformationEx.cs

**Comment by jkotas** [comment]
> 'EnvironmentAugments' does not contain a definition for 'ProcessorCount'

You will also need to add it to CoreRT first - UWP NETNative leg will have this build break without it.

**Comment by stephentoub** [comment]
@dotnet-bot test this please

**Comment by tmds** [comment]
@dotnet-bot test this please

**Pull request merged**
