### PR TITLE
Directory.Move behaves differently on Unix vs. Windows

### LINKED ISSUE #33486: Directory.Move behaves differently on Unix vs. Windows
The following program throws `System.IO.IOException: Cannot create a file when that file already exists` on Windows, but succeeds (and silently replaces the destination file) on i.e. macOS:

```c#
using System;
using System.IO;

namespace MoveFile_DestFile_Exists
{
    class Program
    {
        static void Main(string[] args)
        {
            string TempFolder = Path.GetTempPath ();
            string tempFile1 = Path.Combine (TempFolder, "temp1.txt");
            string tempFile2 = Path.Combine (TempFolder, "temp2.txt");

            using (StreamWriter sw = File.CreateText (tempFile1)) {
                sw.Write ("temp1");
            }
            using (StreamWriter sw = File.CreateText (tempFile2)) {
                sw.Write ("temp2");
            }

            Directory.Move (tempFile1, tempFile2);
        }
    }
}
```

For context, expecting this to fail is part of Mono's tests.

### PR DESCRIPTION
**Pull request by carlossanlop**
Fixes #33486

@stephentoub @JeremyKuhne @danmosemsft Do we want to take this breaking change for the sake of consistency across operating systems?

### CODE REVIEW

**Comment by carlossanlop** [comment]
> Can we add a test for this? Otherwise it looks good.

Gladly. I'll add a test and will include it in this PR.

**Comment by karelz** [comment]
@carlossanlop FYI: You created a new milestone by accident (GitHub makes it way too easy :)) ... fixing it now

**Comment by carlossanlop** [comment]
> @carlossanlop FYI: You created a new milestone by accident (GitHub makes it way too easy :)) ... fixing it now

Thanks for noticing. The value with the comma was among the options in the dropdown, not sure why.

**Comment by carlossanlop** [comment]
> Can we add a test for this? Otherwise it looks good.
> 
> Gladly. I'll add a test and will include it in this PR.

@JeremyKuhne the test we needed for this change already existed but it's exclusive for Windows. I'll rename it so it's platform independent, and will add a comment that will mention this issue.

**Comment by carlossanlop** [comment]
Thanks Stephen for the clarification, I'll keep that in mind in the future.

**Pull request merged**
