### PR TITLE
Update .NET SDK link 

### PR DESCRIPTION
**Pull request by MarcoRossignoli**
I'm working on benchmarking and reading this guide i think that the correct link is 
https://github.com/dotnet/core-sdk#installers-and-binaries 
and not 
https://github.com/dotnet/core-setup#daily-builds (only runtime)

/cc @ViktorHofer @adamsitnik

### CODE REVIEW

**Comment by adamsitnik** [comment]
Hi @MarcoRossignoli 

Thanks for the PR! You are right. As soon as https://github.com/dotnet/core-sdk/issues/16 gets fixed I am going to merge this PR.

**Comment by karelz** [comment]
@adamsitnik is it ready to be merged now? If not is there any ETA?

**Comment by MarcoRossignoli** [comment]
@adamsitnik @karelz i've updated link, seems docs changed since my PR

**Comment by adamsitnik** [comment]
@MarcoRossignoli thanks!

**Pull request merged**
