### PR TITLE
[WIP] [NO MERGE] Testing adding link to jenkins

### PR DESCRIPTION
**Pull request by karajas**

### CODE REVIEW

**Comment by karajas** [comment]
@dotnet-bot help please

**Comment by karajas** [comment]
@dotnet-bot test ci please

**Comment by karajas** [comment]
@dotnet-bot test ci please.

**Comment by karajas** [comment]
@dotnet-bot test Portable Linux x64 Release Build please

**Comment by karajas** [comment]
@dotnet-bot test Portable Linux x64 Release Build please

**Comment by karajas** [comment]
@dotnet-bot test Portable Linux x64 Release Build please

**Comment by karajas** [comment]
@dotnet-bot test Portable Linux x64 Release Build please

**Comment by karajas** [comment]
@dotnet-bot test Portable Linux x64 Release Build please

**Comment by karajas** [comment]
@dotnet-bot test Portable Linux x64 Release Build please

**Comment by karajas** [comment]
PTAL @mmitche @weshaggard https://ci3.dot.net/job/dotnet_corefx/job/master/job/portable-linux-Config_Release+OuterLoop_false_prtest/604/

**Comment by karajas** [comment]
Actually this looks wrong atm, it looks like the build is marked green but test runs haven't finished.

**Comment by karajas** [comment]
@dotnet-bot test Portable Linux x64 Release Build please

**Comment by karajas** [comment]
This now works, running tests still shows up as in progress.

**Comment by karajas** [comment]
@dotnet-bot test this please

**Comment by karajas** [comment]
@dotnet-bot help please.

**Comment by stephentoub** [comment]
@karajas, can this be closed now?

**Comment by karelz** [comment]
Closing, looks like it is not needed anymore. Feel free to reopen if I it is not true.

**Pull request closed without merging**
