### PR TITLE
Consistent exception on out-of-range IRunVariables access.

### LINKED ISSUE #4014: IRuntimeVariables implementations inconsistent on out-of-range access
Some of the implementations of `IRuntimeVariables` that can be produced from `RuntimeVariablesExpression` will, when indexed with an out-of-range index, throw `ArgumentOutOfRangeException` with a `ParamName` value of `"index"` as one would expect.

Some however will throw `IndexOutOfRangeException`.

### PR DESCRIPTION
**Pull request by JonHanna**
Fixes #4014 
Temporarily adding to branch for #4016

### CODE REVIEW

**Comment by JonHanna** [comment]
Now clean of that branch and ready to merge.

**Comment by VSadov** [comment]
It looks like the majority of implementations would throw IndexOutOfRangeException which is also faster since it simply a result of implementation using array. Performance could be more important for RuntimeVariables than whether IndexOutOfRangeException or ArgumentOutOfRangeException is more appropriate.

I think we should do the opposite - just unify everything on throwing IndexOutOfRangeException. 
It is informative enough and in most cases would not require any additional checks.

**Comment by JonHanna** [comment]
ArgumentOutOfRangeException would seem to be more in keeping with the rest of the foundational libraries, but I think the main thing is consistency. Have change this to turn the case that was originally an ArgumentOutOfRangeException to be IndexOutOfRangeException and altered the tests accordingly.

**Comment by JonHanna** [comment]
On the side of the previous approach, It's worth considering that even `((IList<int>)(new int[0]))[0]` throws ArgumentOOR rather than IndexOOR, though I'm still happy with the current approach.

**Comment by VSadov** [comment]
IMO - I can only guess why AOOR was created in a first place, perhaps to be used in cases like ```OpenDoor(degrees: 270)``` - i.e when argument is not within allowed range, but we are not accessing an element by its ordinal position, so it is not indexing. But that is just me...

In this case there are clear advantages of throwing IOOR (or letting it propagate) and it should not be any harder on the caller to figure what was the cause of an error.

**Comment by JonHanna** [comment]
I'd agree with that way of splitting the responsibility of AOOR and IOOR in principle, it seems unfortunate that AOOR would be the norm in cases like this, but generally I'd go with "yes I would jump of a bridge if they did, I'm trying to be compatible with them". If it was more likely to come up often I'd argue for AOOR for that reason. As it probably isn't, and probably isn't something one is often going to catch, I'll settle for the consistency.

**Pull request merged**
