### PR TITLE
Add TypeConverter library and tests

### PR DESCRIPTION
**Pull request by YingP99**
Add new library System.ComponentModel.TypeConverter and tests

### CODE REVIEW

**Comment by YingP99** [comment]
@Maxwe11 Fixed all formatting issues.

**Comment by YingP99** [comment]
@Maxwe11 Are you looking the new commit?

**Comment by Maxwe11** [comment]
New commit dies double type checking only in one place. You can find more e.g. through search with regexs

**Comment by YingP99** [comment]
test this please

**Comment by YingP99** [comment]
@Maxwe11 Updated again. Thx.

**Comment by mmitche** [comment]
@dotnet-bot test this please

**Comment by mellinoe** [comment]
Looks good to me. We can further clean up bad areas as separate work items, IMO.

**Pull request merged**
