### PR TITLE
Implements fast document name comparison, parsing, and general case-insensitive string comparison

### PR DESCRIPTION
**Pull request by tmat**

### CODE REVIEW

**Comment by tmat** [comment]
@nguerrera Please review.

**Comment by tmat** [comment]
@nguerrera I'm going to merge this to unblock myself and follow up on feedback once you have a chance to review.

**Comment by nguerrera** [comment]
OK. I've flagged this and will get to it as soon as I can pop some higher pri things off my stack.

**Comment by tmat** [comment]
No rush.

**Pull request merged**
