### PR TITLE
[Script] Add options for running selected tests

### PR DESCRIPTION
**Pull request by lemmaa**
* add `--test-dir <path>` : specify a test directory path
* add `--test-dir-file <path>` : specify a file that contains test directory list

### CODE REVIEW

**Comment by lemmaa** [comment]
@dotnet-bot test Innerloop OSX Debug Build and Test

**Comment by lemmaa** [comment]
@ellismg, @mmitche, Please take a look this one.

**Comment by mmitche** [comment]
LGTM

**Comment by lemmaa** [comment]
@ellismg  Would please review & merge this one?

**Comment by ellismg** [comment]
LGTM, sorry for the delay.

**Pull request merged**
