### PR TITLE
[release/3.1] Add RID for Alpine 3.16

### PR DESCRIPTION
**Pull request by carlossanlop**
@rbhanda @mmitche @ericstj @wfurt 

Please let me know if everything looks in order.

This was based on the 3.15 PR: https://github.com/dotnet/corefx/pull/43129/files

### CODE REVIEW

**Comment by carlossanlop** [comment]
I don't think we need a change in coreclr or core-setup, do we? I can't find merged PRs related to RIDs.

**Review by wfurt — APPROVED** [review]
LGTM

**Comment by rbhanda** [comment]
https://github.com/dotnet/core/issues/7401 - tracking issue

**Review by ericstj — APPROVED** [review]
LGTM, looks consistent with https://github.com/dotnet/corefx/commit/5c061759d8c3a379d20c4b1546eeb723d5e70609.

**Pull request merged**
