### PR TITLE
Modify OOM exeception check in 'System.System.Security.Cryptography.Encryption.Aes.Tests.AesContractTests'

### PR DESCRIPTION
**Pull request by hseok-oh**
Related issue: #12441
Additional out-of-memory exception in `System.Security.Cryptography.Encryption.Aes.Tests.AesContractTests.InvalidKeySizes`
and `System.Security.Cryptography.Encryption.Aes.Tests.AesContractTests.InvalidIVSizes`.

Because CreateEncryptor(key, iv) and CreateDecryptor(key, iv) uses Array.Clone() to array argument `iv`, we need to check OOM exception for cloned object.

### CODE REVIEW

**Comment by stephentoub** [comment]
I don't understand this. What is the improvement here?

**Comment by bartonjs** [comment]
I think the idea is that since the IV will be cloned before the sizes are validated that it wants to clone now to prove there's memory again for the 500MB bad input.  Then when it goes to clone again it'll just pressure the GC into realizing that the previous buffer is available.

But unless this is executing with no parallelization whatsoever, the precondition test isn't really valid.  Other memory could have been allocated between the precondition clone and the actual one, making the actual clone fail.

If we have a way of identifying that we're executing in a constrained memory environment I'd much rather block that test by that constraint than by fishy preallocation tests.

**Comment by stephentoub** [comment]
It seems like this is all a workaround for not being able to do the equivalent of:
```C#
Assert.ThrowsEither(typeof(ArgumentException), typeof(OutOfMemoryException), () => aes.CreateEncryptor(key, iv));
```
Am I understanding correctly?  If so, rather than this try/catch for an OOM and allocating unnecessary arrays that don't actually guarantee anything, it'd be better to do something like:
```C#
Exception e = Record.Exception(() => aes.CreateEncryptor(key, iv));
Assert.True(e is ArgumentException || e is OutOfMemoryException, $"Got {e}");

e = Record.Exception(() => aes.CreateDecryptor(key, iv));
Assert.True(e is ArgumentException || e is OutOfMemoryException, $"Got {e}");
```

**Comment by bartonjs** [comment]
I like Steve's suggestion.  @hseok-oh Can you change the test to that pattern instead? That way we're considering the OOM to not fail but also not depending on risky probing behavior.

**Comment by hseok-oh** [comment]
@bartonjs, @stephentoub I agree with you and change tests.

**Pull request merged**
