### PR TITLE
Delete deadcode identified by the ILLinker update

### PR DESCRIPTION
**Pull request by jkotas**

### CODE REVIEW

**Comment by jkotas** [comment]
cc @sbomer

**Comment by sbomer** [comment]
LGTM, thanks!

**Comment by stephentoub** [comment]
@dotnet/dncenghot, is there something wrong with the Windows.81.Amd64.Open-x64 and indows.81.Amd64.Open-x86 queues?  They're timing out on lots of corefx PRs.

**Comment by MattGal** [comment]
@stephentoub  everything was messed up when you posted that, but I did notice this plus Ubuntu 18.04 being weird (I suspect some azure thing; couldn't actually see useful data) yesterday and have https://github.com/dotnet/core-eng/issues/6923 to track investigating it. Seems OK for now.

**Pull request merged**
