### PR TITLE
Moving `Perf_Array` under `System.Tests` namespace

### PR DESCRIPTION
**Pull request by jorive**
This will group its results with the rest of the other benchmarks in the same project.

### CODE REVIEW

**Comment by jorive** [comment]
@dotnet/rap-team PTAL

**Comment by jorive** [comment]
@dotnet-bot  test Windows_NT perf

**Comment by DrewScoggins** [comment]
Sounds good. When you merge this I will move it over.

**Comment by danmosemsft** [comment]
Thanks..although really we should get rid of `System.Tests` namespace entirely so benchview makes sense

**Comment by stephentoub** [comment]
> although really we should get rid of System.Tests namespace entirely so benchview makes sense

@danmosemsft, can you clarify?  Are you suggesting that namespaces be removed from all perf tests?

**Comment by danmosemsft** [comment]
I can't access benchview right now but it categorizes by namespace. many tests are categorized well but a bunch are hidden under "tests"

**Pull request merged**
