### PR TITLE
Add ping path for ArchLinux

### PR DESCRIPTION
**Pull request by jasonwilliams200OK**
This fixes one of the test failure listed in #7270.

cc @vindicatorr, @mellinoe

### CODE REVIEW

**Comment by jasonwilliams200OK** [comment]
@mellinoe, if it is possible to pull S.D.P for `Process` in this contract, should we use `which ping` here instead? Or expose `which` from `System.Native` for Unix (maybe just for internal usage)?

**Comment by ellismg** [comment]
Why do we not just walk $PATH ourselves?

**Comment by stephentoub** [comment]
When this was initially done, I'd suggested just letting Process do its normal search, which includes PATH. The push back I got was around security and concerns that a malicious ping could be put on the path. cc: @bartonjs

**Comment by jasonwilliams200OK** [comment]
@ellismg, I added alternative impl: 7ae6f7a760628dce4acded62a0661c939b4c38a2. Based on @stephentoub's comment, probably the first approach (handpicking paths) is a safer option?

**Comment by jasonwilliams200OK** [comment]
Test Innerloop OSX Debug Build and Test

**Comment by mellinoe** [comment]
The current version LGTM. And yes, as @stephentoub mentioned, the current method is an attempt to mitigate potential security issues. We can always re-think that design if we think it isn't valuable, but as long as we have it that way the current branch in the PR looks correct.

**Comment by ellismg** [comment]
Could we add a comment to GetPingUtilityPath or the list of folders explaining that we don't want to pick up an arbitrary ping command and so that's why we do the path probing ourselves?

**Comment by ellismg** [comment]
LGTM otherwise.  Thanks for this.

**Comment by bartonjs** [comment]
From framework code we shouldn't ever create a process that uses $PATH; it's always considered a reliability risk which is a security risk (and possibly a big one).  The options would be

* It just works, got lucky.
* It hit some other program, but we didn't know how to read the output -- what behavior do we have now?
* It hit some other file, which wasn't a program, what happens now?
* It hit a malicious target in user-space (because, e.g. they prepended ~/bin to their path) which does whatever a malicious target wants to do.
    * e.g. an abusable arbitrary-file-download bug, combined with something like this, could cause a drive-by botnet-gathering, etc.
* It's definitely a bigger concern with arbitrary inputs, but, like using strnlen, it's just better to always do the more secure thing.

**Comment by bartonjs** [comment]
LGTM as the explicit path

**Comment by mellinoe** [comment]
I agree that adding an extra comment explaining the path probing would be good. Once that is added, we can merge this in. Thanks for the fix, @jasonwilliams200OK.

**Comment by jasonwilliams200OK** [comment]
Thanks for explaining guys. I have added the comment to `GetPingUtilityPath`.

**Comment by mellinoe** [comment]
LGTM, thanks again.

**Pull request merged**
