### PR TITLE
Update licensing headers

### PR DESCRIPTION
**Pull request by stephentoub**
cc: @richlander, @weshaggard, @joshfree, @ellismg

### CODE REVIEW

**Comment by ellismg** [comment]
I looked at your branch and did a git grep for `Copyright (c)`.  There's still some weirdness at the bottom of these two files:

```
src/System.Private.DataContractSerialization/src/System/Runtime/Serialization/Json/JavaScriptObjectDeserializer.cs
src/System.Private.DataContractSerialization/src/System/Runtime/Serialization/Json/JavaScriptString.cs
```

That we may want to follow up on.  Otherwise, LGTM.

**Comment by stephentoub** [comment]
Thanks, Matt.  I've removed those two footers.

**Comment by richlander** [comment]
LGTM

**Comment by stephentoub** [comment]
(OS X builds failing due to https://github.com/dotnet/corefx/issues/5732)

**Comment by stephentoub** [comment]
Test Innerloop OSX Debug Build and Test please
Test Innerloop OSX Release Build and Test please

**Pull request merged**
