### PR TITLE
Add a test for ConditionalWeakTable.Clear

### PR DESCRIPTION
**Pull request by stephentoub**
This function is internal and used by other parts of CoreLib, so the test uses reflection to access and invoke it.

cc: @jkotas

### CODE REVIEW

**Comment by jkotas** [comment]
LGTM

Do we want to make this public method? We are adding the Clear method to other collections that are missing it ... https://github.com/dotnet/corefx/issues/2338

**Comment by stephentoub** [comment]
> Do we want to make this public method?

Sounds reasonable.  There are a bunch of other collection-like methods missing as well, most notably support for enumeration.

**Comment by jkotas** [comment]
Yes, emumerator would be nice - it would get rid the other special internal method used by interop https://github.com/dotnet/corert/blob/a09de49cbf64f7c22d950a98678830bcf8d6ce82/src/System.Private.CoreLib/src/System/Runtime/CompilerServices/ConditionalWeakTable.cs#L559

**Comment by stephentoub** [comment]
Opened https://github.com/dotnet/corefx/issues/14387 for additional APIs.

**Pull request merged**
