### PR TITLE
[release/2.0.0] Update to buildtools 2.0.0-servicing-02201-03

### PR DESCRIPTION
**Pull request by dagood**
Port PRs https://github.com/dotnet/corefx/pull/23559, https://github.com/dotnet/corefx/pull/23610 to release/2.0.0 to allow updating to a new BuildTools containing an upgraded compiler. (See https://github.com/dotnet/corefx/issues/20942.)

Unblocks https://github.com/dotnet/source-build/pull/271: allows source-build to upgrade the provided BuildTools version.

### CODE REVIEW

**Comment by weshaggard** [comment]
> I assume Wes knows more about why do we need that new mscorlib.WinRT-Facade.csproj

Yes that is needed because of a compiler change, see details in https://github.com/dotnet/corefx/pull/23610

**Comment by joperezr** [comment]
Sorry I didn't realize that the uap tools package was still being restored using optional tooling on this branch. Can you try using the latest one we have instead of this one? We have added a bunch of improvements to the runners. Latest version is `1.0.17`

**Comment by dagood** [comment]
Sure, I'll bring it forward. Do you know if there are other non-upgrade changes around this area I should cherry-pick, too?

**Comment by dagood** [comment]
Ah, missing `ArchGroup` from https://github.com/dotnet/corefx/commit/97990bd934604a6ec7a9cd89b2c42cd11b17fb48. (1.0.17 Failed locally after I remembered to see if it works from an empty testhost dir.)

**Comment by dagood** [comment]
Gets this now: `FAILED 0x80073CF6 (Package could not be registered.)`

I saw [this post](https://social.msdn.microsoft.com/Forums/en-US/da89f2ee-03b6-43ed-aa21-97ef091798c9/deploy-error-package-could-not-be-registered?forum=WindowsPhonePreviewSDK) which mentions it might be because `SplashScreen.png` is missing. Manually copying `SplashScreen.scale-200.png` to `SplashScreen.png` locally does get past this error, but then I hit:

```
FAILED 0x800706BE (The remote procedure call failed.)
Removing the application...
FAILED 0x800706BE (The remote procedure call failed.)
```

I don't know how to coax any more useful data out of the runner. Any ideas, @joperezr?

**Comment by ViktorHofer** [comment]
Yes the EventLog shows this:

```
Faulting application name: XUnit.Runner.Uap.exe, version: 1.0.1429.0, time stamp: 0x56c69c5d
Faulting module name: Windows.UI.Xaml.dll, version: 10.0.17035.1000, time stamp: 0x12d7c414
Exception code: 0xc000027b
Fault offset: 0x00000000006f80b9
Faulting process id: 0x2f08
Faulting application start time: 0x01d35d67de34debc
Faulting application path: C:\git\corefx\bin\AnyOS.AnyCPU.Debug\System.Runtime.Serialization.Formatters.Tests\netstandard\XUnit.Runner.Uap.exe
Faulting module path: C:\Windows\System32\Windows.UI.Xaml.dll
Report Id: 0072e8bc-8788-44d8-ab1e-eec64c731c95
Faulting package full name: 5cd54353-3ed7-4a6e-a72f-db349f28867c_1.0.0.0_x64__v52bfwc2c21ha
Faulting package-relative application ID: App
```

**Comment by joperezr** [comment]
mm doesn't ring any bells, latest revisions of the runner were made by @safern so perhaps he knows about this? Latest changes have been more around the console output of the runner in order to make it easier to diagnose issues on a failed test run, but if that is not something we depend on, then perhaps we can try downgrading the version of the tool to one that doesn't throw any errors.

**Comment by ViktorHofer** [comment]
I'm wondering if the error "remote procedure call" means that something with the RemoteExecutor is wrong... I did a local build of the xunit.runner.uap on both master and release/2.0.0 and both are working fine for me with x86...

That said, we need to find a way fixing this asap as today is deadline for the servicing release (code wise).

**Comment by safern** [comment]
> mm doesn't ring any bells, latest revisions of the runner were made by @safern so perhaps he knows about this?

I'll take a look today.

**Comment by joperezr** [comment]
cc: @tarekgh since it might be that we need to cherry pick other changes regarding remote execution support in order to use the latest Runner and he did all that work.

**Comment by weshaggard** [comment]
Lets not worry about the UWP legs as we have never really run tests in the release/2.0.0 branch that was an issue with merging the CI changes into release/2.0.0

**Comment by safern** [comment]
I will submit a PR to disable running the tests.

**Comment by dagood** [comment]
Removed the UAP changes and brought in the commits from @weshaggard's BuildTools upgrade PR https://github.com/dotnet/corefx/pull/25315.

**Comment by dagood** [comment]
Merging: all legs green except UWP.

**Pull request merged**
