### PR TITLE
Fix more test visibility issues

### PR DESCRIPTION
**Pull request by stephentoub**

### CODE REVIEW

**Comment by stephentoub** [comment]
> I guess many of these were showing up when @safern switched on that Xunit analyzer recently?

Not that I know of. I'm hitting them with https://github.com/dotnet/corefx/pull/36434.

**Comment by safern** [comment]
> I guess many of these were showing up when @safern switched on that Xunit analyzer recently?

They where showing yes. So great that you fix them, thanks :smile:

**Comment by stephentoub** [comment]
> They where showing yes.

Where is that running / where are the results?

**Comment by safern** [comment]
> Where is that running / where are the results?

I was running it locally in my computer. I don't have the results, but I can get them of course. There are thousands and thousands of errors. I was in the process of using their analyzers and apply the code fixes automatically, but then started with nullable. 

I can disable all the warns and then community could help fix them, but really, they're a LOT.

**Comment by stephentoub** [comment]
> I was running it locally in my computer.

Ah, ok. Thanks.

**Pull request merged**
