### PR TITLE
[release/1.0.0] Disable package build for packages not shipping

### PR DESCRIPTION
**Pull request by ericstj**
We've shipped 1.0.3 change the build back to producing no packages.

/cc @weshaggard @chcosta @gkhanna79

### CODE REVIEW

**Comment by gkhanna79** [comment]
This has not yet shipped, so we cannot merge this in yet.

**Comment by ericstj** [comment]
I see.  Well, let's keep it ready for the time it ships.

**Comment by ericstj** [comment]
Looks like build doesn't like no packages.  I'll make sure we at least build the baseline package, that will workaround this.

**Comment by ericstj** [comment]
@chcosta do we need to update `LKG_Packages.txt`?

**Comment by ericstj** [comment]
Ping.  @chcosta please review.

**Comment by chcosta** [comment]
Yes, you'll need to update LKG_Packages.txt, there is no automation updating these files at the moment.  
I'd like to move to a place where we can remove this file from servicing branches and rely on the dotnet/versions repo, but we're not there at the moment.  I need to sync with Davis to determine if it's something we can tackle in the next sprint.

/cc @dagood

**Pull request merged**
