### PR TITLE
Marking code as unchecked (pt 8)

### PR DESCRIPTION
**Pull request by dennisdietrich**
Marking code that may intentionally lead to over or underflows with
unchecked in preparation of turning on CheckForOverflowUnderflow for
all projects (issue #3140)

### CODE REVIEW

**Comment by dennisdietrich** [comment]
Ubuntu 14.04 build seems to be hanging (it's been running for 75 minutes already).

**Comment by danmosemsft** [comment]
@VSadov @steveharter @sepidehMS @mellinoe for Linq, Crypto, Xml, Numerics.

**Comment by sepidehMS** [comment]
Xml changes LGTM.

@dotnet-bot test outerloop Windows_NT debug

**Comment by tarekgh** [comment]
@JeremyKuhne could you please look at  the failure https://ci.dot.net/job/dotnet_corefx/job/master/job/outerloop_windows_nt_debug_prtest/78/

thanks.

**Comment by tarekgh** [comment]
test Innerloop Ubuntu14.04 Debug Build and Test please

**Comment by tarekgh** [comment]
test OuterLoop Windows_NT Debug please

**Comment by JeremyKuhne** [comment]
> @JeremyKuhne could you please look at the failure https://ci.dot.net/job/dotnet_corefx/job/master/job/outerloop_windows_nt_debug_prtest/78/

@willdean

**Comment by tarekgh** [comment]
I looked at the whole change and LGTM. thanks @dennisdietrich for your awesome work.

**Comment by willdean** [comment]
The failure https://ci.dot.net/job/dotnet_corefx/job/master/job/outerloop_windows_nt_debug_prtest/78/ predates the merge of #16102 which now prevents that kind of problem

**Comment by VSadov** [comment]
LGTM

**Pull request merged**
