### PR TITLE
Add tests for binaryFormatted resources

### PR DESCRIPTION
**Pull request by ericstj**
Requires https://github.com/dotnet/coreclr/pull/20907, will fail until we pick it up.

This is just a couple basic tests.  I'll add some tests for the lightup scenarios in a bit.

### CODE REVIEW

**Comment by ericstj** [comment]
Test this please

**Comment by stephentoub** [comment]
@dotnet-bot test this please

**Comment by ericstj** [comment]
test UWP CoreCLR x64 Debug Build

**Comment by ericstj** [comment]
Looks like my check for UAP wasn't good enough...  Will try a local repro.

**Comment by ericstj** [comment]
test OSX x64 Debug Build

**Pull request merged**
