### PR TITLE
Expose String.GetHashCode(StringComparison) with tests

### PR DESCRIPTION
**Pull request by jnm2**
Closes https://github.com/dotnet/corefx/issues/13800

/cc @karelz @danmosemsft @stephentoub @hughbe @MikevanDongen

### CODE REVIEW

**Comment by danmosemsft** [comment]
```
Set baselineallapoicompaterror=true
Build -framework:uap
Build -framework:uapaot
```
At the root should give you updated folks to add to your commit to fix CI

**Comment by jnm2** [comment]
@dan Wondered about that, thanks. Would be great if you guys documented all in one place the steps to add APIs.

**Comment by jnm2** [comment]
@danmosemsft `Build -framework:uap` succeeded and changed `src\System.Runtime\src\ApiCompatBaseline.uap.txt` to say `Total Issues: 0`.

`Build -framework:uapaot` failed in 25 different projects, all errors of the type:

> referenceFromRuntime.targets(55,5): error : Could not resolve ReferenceFromRuntime item(s) 'System.Private.CoreLib' from 'C:\Users\Joseph\Source\Repos\corefx\\external\runtime\runtime.depproj'.

**Comment by danmosemsft** [comment]
Weird, but meantime you can just paste the api as a new line into the uapaot baseline file (look at other examples) if you want and see if CI accepts that

**Comment by karelz** [comment]
> Would be great if you guys documented all in one place the steps to add APIs.

We're already working on that - see [New contributor docs](https://github.com/dotnet/corefx/wiki/New-contributor-Docs#main-page-section-content). Adding APIs is still only in a form of hints/ideas [here](https://github.com/dotnet/corefx/wiki/Contributions#expose-api-in-corefx), so feel free to chip in (wiki is writeable by anyone - we are partying on it with @haralabidis for last week and it is slowly growing ;))

**Comment by jnm2** [comment]
@danmosemsft

> Weird, but meantime you can just paste the api as a new line into the uapaot baseline file (look at other examples) if you want and see if CI accepts that

Apparently it did.

**Comment by danmosemsft** [comment]
Thanks @jnm2!

**Comment by karelz** [comment]
Thank you for your help here @jnm2 !

**Pull request merged**
