### PR TITLE
Move new SignedCms/EnvelopedCms API to netcoreapp ref

### PR DESCRIPTION
**Pull request by bartonjs**
The new members on existing types got added to their type definition for netstandard.  This moves them to the netcoreapp-specific ref.cs.

This is the follow-on to  #30233 to clean up the rest of the members not present in netfx.

### CODE REVIEW

**Comment by bartonjs** [comment]
@stephentoub The UAP build is complaining about the implementation having more members than the ref (netstandard).  I assume I should just suppress those errors for UAP, vs define a new UAP ref or split the src build.  I further assume that you've seen more of this than I have, and can quickly validate or refute the first assumption :smile:.

**Comment by stephentoub** [comment]
> I assume I should just suppress those errors for UAP

I believe that's the right answer, but @weshaggard can confirm, too.

**Comment by weshaggard** [comment]
Unless there is a reason to not support these on UAP then I would add them to the UAP ref as well instead of suppressing.

**Comment by bartonjs** [comment]
@weshaggard So make a new UAP ref for the package?  It only builds { netcoreapp, netfx, netstandard } refs.

**Comment by bartonjs** [comment]
Rebased to solve the merge conflict (against myself).  Any feedback @weshaggard?

**Comment by weshaggard** [comment]
Looks reasonable to me. Although the name .netcoreapp.cs being included in both netcoreapp and uap is a little against convention but I don't have a clear better suggestion at this time.

**Pull request merged**
