### PR TITLE
Avoid specific contract versions in light-up code

### PR DESCRIPTION
**Pull request by tmat**

### CODE REVIEW

**Comment by tmat** [comment]
@ericstj @weshaggard @nguerrera

**Comment by tmat** [comment]
Merging to get a new build asap.

**Comment by ericstj** [comment]
Sorry for the delay. Lgtm!

**Comment by weshaggard** [comment]
@tmat did you dig in to understand why 0.0.0.0 work to resolve the 4.0.1.0 references but 4.0.0.0 didn't?

**Comment by tmat** [comment]
@weshaggard Nope. I'll leave that to you :)

**Comment by tmat** [comment]
Actually I haven't confirmed that it resolved to 4.0.1.0 yet. Just confirmed it resolved to 4.0.0.0.

**Comment by ericstj** [comment]
Come to think of it, I'd expect both to work (though we have always used 0.0.0.0 in lightup in the past) because the host for coreclr puts S.IO.FS in the TPA list which should behave like the unification table.  /cc @gkhanna79

**Comment by nguerrera** [comment]
I don't understand what was broken with this. Please clarify. We need at least version 4.0.0.0 and I thought CoreCLR policy would bind to later version without intervention. I don't understand how 0.0.0.0 changes anything with respect to binding to 4.0.0.0 or later on any platform. 

Have we really always used 0.0.0.0 in the past? Shouldn't we be indicating a minimum version known to have the functionality we need?

Do we also need to change https://github.com/dotnet/coreclr/blob/775003a4c72f0acc37eab84628fcef541533ba4e/src/mscorlib/src/System/Reflection/Emit/ILGenerator.cs#L1183

cc @stephentoub @weshaggard

**Comment by nguerrera** [comment]
Sorry, just saw offline thread on this (was OOF). Looks like it was just a first-chance exception and this doesn't actually change that. I am still not convinced that 0.0.0.0 is a better practice than 4.0.0.0 (actual minimum version needed).

**Comment by tmat** [comment]
@nguerrera I agree. I'll file a bug to revert this change and normalize light-up across CoreFX.

**Pull request merged**
