### PR TITLE
Updating CoreFx dependencies to beta-devapi-24416-01

### PR DESCRIPTION
**Pull request by joperezr**
FYI: @weshaggard @stephentoub 

Given the recent changes I did in S.R.Serialization packages, the automatic update of the versions failed. This is updating it again + the required changes to make it build.

### CODE REVIEW

**Comment by stephentoub** [comment]
@joperezr, thanks, though is it easy for you to split this into two commits, one with the automated changes and one with the manual?  It's a large set of changes and I'm not sure which were which.

**Comment by joperezr** [comment]
@stephentoub sure, 7141d98 contains the changes required for this to build now.

**Comment by stephentoub** [comment]
Thanks. LGTM.

**Comment by joperezr** [comment]
I'm working on a merge from master into dev/api, so I'll hold off this change for after that gets merged to avoid additional merge conflicts.

**Pull request merged**
