### PR TITLE
Move MethodSemanticsAttributes back to System.Reflection namespace

### PR DESCRIPTION
**Pull request by tmat**
S.R.M.dll already shipped with public enums in System.Reflection namespace:
```
MethodImportAttributes
ManifestResourceAttributes
AssemblyHashAlgorithm
DeclarativeSecurityAction
AssemblyFlags
```

So adding ```MethodSemanticsAttributes``` keeps it consistent.

### CODE REVIEW

**Comment by tmat** [comment]
@nguerrera

**Comment by nguerrera** [comment]
:+1:

**Comment by tmat** [comment]
@nguerrera: One more change to match PE/COFF spec, which uses IMAGE_DEBUG_TYPE_REPRO for debug directory entry type.

**Comment by nguerrera** [comment]
:+1:

**Pull request merged**
