### PR TITLE
Adapt updated AsnReader/AsnWriter from dotnet/corefxlab

### PR DESCRIPTION
**Pull request by filipnavara**
Contributes to https://github.com/dotnet/corefx/issues/21833. Removes the unused ASN serializer.

Differences from CoreFX Lab version:
- Classes are `internal`
- One comment markup is changed to avoid compiler error because of missing reference to `System.Security.Cryptography.X509Certificates`
- Couple of tests are renamed to match the new `AsnReader` API names

Updates carried from CoreFX Lab version:
* Apply first round API normalization
  * Asn1Tag
    * TryParse => TryDecode
    * TryWriter => TryEncode
  * AsnReader
    * TryGet* => TryRead*
    * Get* => Read*
  * AsnWriter
    * TryWrite => TryEncode
    * ArgumentException on unbalanced stack => InvalidOperationException
    * Add GetEncodedLength
    * Add Reset
    * Add ObjectDisposedExceptions
    * Harden PushSequence(Custom3),PopSetOf(Custom3)
    * Change WriteUtcTime(DTO, int) to be maxYear, not minYear
    * Add missing WriteUtcTime(Tag, DTO, int) overload
* Explode types to distinct files
* Add xmldoc to all public members
* Explode the AsnReader and AsnWriter to one partial file per data type
  * All restricted character strings are together under Text
* Tests
  * AssertExtensions.Throws => Assert.Throws
  * Rename private overloads of public methods to *Core to avoid xunit discovery bug
  * Add tests for WriteUtcTime(maxYear)
  * Add tests for the ObjectDisposedException priority

### CODE REVIEW

**Comment by bartonjs** [comment]
Why?  Until it actually goes through an API review this feels like it's just noise...

**Comment by bartonjs** [comment]
I'm just going to close this.

* The internal shared source in corefx is intentionally in fewer files to make including in projects easy.
* The public version in corefxlab is intentionally in more files because that's what it would be when it becomes public API in corefx
* The API changes were just me doing a scrub before letting other people use it
  * There has been literally 0 feedback on the corefxlab version
  * Nothing has gone through API review

I don't see any justification at this time for a 169 file edit.  If there is one, we can revisit this.

**Comment by filipnavara** [comment]
> Why? Until it actually goes through an API review this feels like it's just noise...

I can drop the PR if you think it's unnecessary.

I have two actual motivations:
- Running all the unit tests from the libraries against the updated copy to check whether something got broken or not. The AsnXml part and all its usages is not tested in CoreFX Lab.
- Shipping this code along our application on Mono/macOS where the current libraries are lacking proper X509Chain support. Obviously I can compile this with the internal classes, but we use the S.S.C.Asn1.Experimental package already and it would result in duplicated code.

**Comment by filipnavara** [comment]
> The internal shared source in corefx is intentionally in fewer files to make including in projects easy.

I actually added a shared project file to make it easier to include and less scattered than it currently is.

**Comment by bartonjs** [comment]
> [legitimate needs for synchronization exist]

> Actually the edits are [fairly trivial]

Okay, I'll look into doing this, perhaps tonight.  Given the nature of the scenarios where this component is used the hard-to-diff nature of the PR in this form means that 9000 lines of code have to be re-reviewed.  If I do the initial explosion into partial files for corefx then it saves several hours of code re-reviewing; and then later synchronization between corefxlab and corefx (if needed) should be easier.

**Comment by filipnavara** [comment]
> Given the nature of the scenarios where this component is used the hard-to-diff nature of the PR in this form means that 9000 lines of code have to be re-reviewed.

That's unfortunate. :-/

If there's something I can do to restructure it for easier review I will do my best to do that. I can split out the changes into different commits so the moved code, regenerated files and find-and-replace are in their own commits. I started with copying the files byte-for-byte and then updating everything to compile, so it's rather easy for me to go back and split it into individual commits.

**Comment by filipnavara** [comment]
The closed PR doesn't update with new commit, but I have restructured the [whole branch](https://github.com/filipnavara/corefx/tree/asnlab) into many little commits. The move between repositories is in one commit and each find-and-replace/regenerate commit is separate from any manual changes. The end result is exactly the same diff as in the original PR.

**Comment by bartonjs** [comment]
@filipnavara I pulled the files over in #35840.  If you want to do the changes on top of that now it'll be much easier to review.

**Pull request closed without merging**
