### PR TITLE
Rename System.Runtime.Intrinsics.X86 to System.Runtime.Intrinsics.

### LINKED ISSUE #26194: Proposal rename System.Runtime.Intrinsics.X86.dll to System.Runtime.Intrinsics.dll
For HW Intrinsics X86 has created `System.Runtime.Intrinsics.X86.dll`.  It currently contains Vector128, and Vector256 from `System.Runtime.Intrinsics` as well as the X86
HW intrinsics from `System.Runtime.Intrinsics.X86`

ARM64 intrinsics will use Vector128 from `System.Runtime.Intrinsics`
ARM64 intrinsics will add Vector64 to `System.Runtime.Intrinsics`

The question arises about where to put ARM64 intrinsic reference assemblies.

It seems any application which takes the time to optimize code using intrinsics may want to support multiple platforms.

My preference would be to add ARM64 intrinsics to the same reference assembly.  Therefore to rename the reference assembly to a more generic name `System.Runtime.Intrinsics.dll` rather than creating `System.Runtime.Intrinsics.ARM.ARM64.dll` and later `System.Runtime.Intrinsics.ARM.ARM32.dll`.

@eerhardt @CarolEidt @RussKeldorph Please advise

@tannergooding @fiigii FYI

### PR DESCRIPTION
**Pull request by eerhardt**
Since the ref assembly is so small, it doesn't pay to split each architecture into separate assemblies.  Also, there are common types shared between architectures - ex. Vector128.

Fix #26194 

/cc @sdmaclea @fiigii @CarolEidt @jkotas

### CODE REVIEW

**Comment by fiigii** [comment]
Thanks for the work. But you may want to wait for https://github.com/dotnet/corefx/pull/26230

**Comment by eerhardt** [comment]
> But you may want to wait for #26230

The changes should merge together fine.  But I'll wait until #26230 gets merged to merge mine, since that will make it easier to consume the new coreclr.

**Comment by weshaggard** [comment]
Looks like coreclr change https://github.com/dotnet/corefx/pull/26230 has merged.

**Comment by jkotas** [comment]
For the ARM build break, you either need to move https://github.com/dotnet/corefx/blob/master/src/System.Runtime.Intrinsics.X86/src/ApiCompatBaseline.txt too; or wait for the next CoreCLR update to be merged and delete this file.

**Pull request merged**
