### PR TITLE
 [ARM/CI] Set default CI job and change docker image

### PR DESCRIPTION
**Pull request by hseok-oh**
- Set default CI job: dotnet/core-setup#790
- Chnage docker image newer

### CODE REVIEW

**Comment by hseok-oh** [comment]
@dotnet-bot test ci please

**Comment by hseok-oh** [comment]
@dotnet-bot test innerloop Ubuntu14.04 arm Release Build
@dotnet-bot test innerloop Ubuntu14.04 arm Debug Build
@dotnet-bot test innerloop Ubuntu16.04 arm Release Build
@dotnet-bot test innerloop Ubuntu16.04 arm Debug Build
@dotnet-bot test innerloop Tizen armel Release Build
@dotnet-bot test innerloop Tizen armel Debug Build

**Comment by hseok-oh** [comment]
It needs to merge #17543 first to clear build error.

**Comment by mellinoe** [comment]
@dotnet-bot Test this please

**Comment by mellinoe** [comment]
@dotnet-bot test innerloop Ubuntu14.04 arm Release Build
@dotnet-bot test innerloop Ubuntu14.04 arm Debug Build
@dotnet-bot test innerloop Ubuntu16.04 arm Release Build
@dotnet-bot test innerloop Ubuntu16.04 arm Debug Build
@dotnet-bot test innerloop Tizen armel Release Build
@dotnet-bot test innerloop Tizen armel Debug Build

**Comment by hseok-oh** [comment]
@mellinoe PTAL and merge this if no problem and clear test

**Pull request merged**
