### PR TITLE
Fix typos in descriptions.json

### PR DESCRIPTION
**Pull request by hughbe**
Not a very big change, but I spotted several small typos and fixed 'em. 
Has NFC.

### CODE REVIEW

**Comment by mellinoe** [comment]
LGTM. I'm not really sure about the API's -> APIs change, but it looks like most people agree that the apostrophe should be omitted. I don't have a strong opinion on that one.

**Comment by hughbe** [comment]
I just Went for consistency with the rest of the document

**Comment by mellinoe** [comment]
Even better. GitHub had condensed down the diff so I didn't see how the others were written. "APIs" seems like the way to go regardless.

**Comment by stephentoub** [comment]
LGTM

**Pull request merged**
