### PR TITLE
Consolidate TypeBuilder.Define* tests

### PR DESCRIPTION
**Pull request by hughbe**
Makes it easier to add new tests without duplicating test data everywhere

/cc @AtsushiKan @stephentoub

### CODE REVIEW

**Comment by stephentoub** [comment]
@dotnet-bot test Innerloop CentOS7.1 Debug Build and Test please (https://github.com/dotnet/corefx/issues/12886)

**Comment by stephentoub** [comment]
@dotnet-bot test Innerloop CentOS7.1 Debug Build and Test please (#12886)

**Comment by AtsushiKan** [comment]
LGTM

**Comment by hughbe** [comment]
Is this OK to be merged? Cheers

**Pull request merged**
