### PR TITLE
Add RHEL 8 runtime ids

### PR DESCRIPTION
**Pull request by omajid**
This is a manual backport of b8d3d34151 (#33529) to release/2.1

Add RHEL 8 runtime ids - 8 and 8.0 - to the runtime id graph so RHEL 8
fallback is handled correctly.

### CODE REVIEW

**Comment by omajid** [comment]
Anyone willing to review this?

**Comment by stephentoub** [comment]
@danmosemsft, who should review this?

**Comment by danmosemsft** [comment]
@ericstj could you please take a look

**Comment by karelz** [comment]
@omajid can you check the test results please / rerun the tests?

**Comment by karelz** [comment]
Oh, this is servicing 2.1.x - @danmosemsft do you plan to bring it to shiproom first?

**Comment by vivmishra** [comment]
Approved for 2.1.10 and 2.2.4.
Wait for branch to open.

**Comment by wtgodbe** [comment]
@omajid we need to update packaging with this change - For an example of what needs to be done, see https://github.com/dotnet/corefx/commit/a13191ed3109371db7d40e809cda2aac4f41ac9f#diff-fe8c56d21de09c67fa6221510e07495f

**Comment by omajid** [comment]
@wtgodbe I tried to update the package, but I have no idea what I am doing... can you please review my last commit?

**Comment by wtgodbe** [comment]
LGTM, thanks @omajid!

**Pull request merged**
