### PR TITLE
Update PathInternal.Windows.cs

### PR DESCRIPTION
**Pull request by HugoRoss**
Moved the "if" from inside the loop to outside the loop for performance reasons.

### CODE REVIEW

**Comment by stephentoub** [comment]
Thanks, @HugoRoss.  Do you have any measurements to go along with this to show an improvement in the performance of the APIs that consume this?  It's great to avoid branches, especially in cases where there aren't any already; in this case, though, by the point we'd be checking checkAdditional we've already done a bunch of conditionals, so I'm curious if one more actually makes a difference.  I personally find the new code slightly less intuitive, and it increases the size of the generated IL (almost doubles it) so I'd only want to make the change if we could show that it actually helped performance.

**Comment by HugoRoss** [comment]
No, I haven't and I'm sure it's not a huge amount as an "if" is pretty fast. It's just something I noticed when I was browsing the reference source and thought could be optimized. Throw it away it you think the other reasons outweigh the benefit. (I never cared about the size of IL code yet, but of course, in the core libraries that matters).

**Comment by stephentoub** [comment]
Thanks, @HugoRoss.  I'm going to close this for now, but if you find some time to do some measurements and discover that it does make a measurably positive impact on performance, please do reopen it.

**Comment by HugoRoss** [comment]
OK.

**Pull request closed without merging**
