### PR TITLE
Add DllCharacteristics.HighEntropyVirtualAddressSpace

### PR DESCRIPTION
**Pull request by tmat**

### CODE REVIEW

**Comment by tmat** [comment]
@nguerrera

**Comment by nguerrera** [comment]
:+1:

**Comment by tmat** [comment]
```
error: Did not find corresponding test dll for ./src/System.Drawing.Primitives/tests/System.Drawing.Primitives.Tests.csproj at /mnt/resource/j/workspace/dotnet_corefx/centos7.1_debug_tst_prtest/bin/tests/Linux.AnyCPU.Debug/System.Drawing.Primitives.Tests/dnxcore50/System.Drawing.Primitives.Tests.dll
```

**Comment by ellismg** [comment]
@dotnet-bot test Innerloop CentOS7.1 Debug Build and Test

**Comment by ellismg** [comment]
@dotnet-bot Innerloop CentOS7.1 Release Build and Test (race in finding test dlls to run)

**Comment by ellismg** [comment]
@dotnet-bot test Innerloop CentOS7.1 Release Build and Test

**Pull request merged**
