### PR TITLE
Cleans up TupleElementNamesAttribute

### PR DESCRIPTION
**Pull request by agocke**
The TupleElementNamesAttribute had an unused and incorrect constructor which
has been removed and some incorrect comments which have been updated.

/cc @stephentoub @jcouv @VSadov @jaredpar @dotnet/roslyn-compiler

### CODE REVIEW

**Comment by stephentoub** [comment]
This doesn't compile:
```
System\Runtime\CompilerServices\TupleElementNamesAttribute.cs(13,25): error CS3015: 'TupleElementNamesAttribute' has no accessible constructors which use only CLS-compliant types [D:\j\workspace\windows_nt_de---4526f5ff\src\System.ValueTuple\src\System.ValueTuple.csproj]
```

**Comment by agocke** [comment]
@stephentoub Looks like CLS compliance is the problem. Is there a CoreFX policy on mandated CLS compliance? I'm going to discuss this with the team, but I'm inclined to turn off CLS compliance rather than introduce an unused and unrecognized constructor to the attribute.

**Comment by stephentoub** [comment]
> Is there a CoreFX policy on mandated CLS compliance?

We try to be whenever possible. Where not possible, we use a CLSCompliant attribute to supress it. But I'd think support for a key language feature is a case where we want to be compliant, no?

**Comment by jcouv** [comment]
@agocke I understand that the attribute won't be emitted at all if there are no names, so the default constructor shouldn't be used. Is it an option to keep that constructor but have it throw instead?

**Pull request merged**
