### PR TITLE
Add OSX 10.12 support to the RID graph.

### PR DESCRIPTION
**Pull request by gkhanna79**
Port https://github.com/dotnet/corefx/commit/c61127f8f23adc32271ccc572a0dd05856ca3a84 to 1.0.X so that RID fallback graph supports OSX 10.12.

@ericstj @mellinoe PTAL

CC @weshaggard @Petermarcu @leecow

### CODE REVIEW

**Comment by gkhanna79** [comment]
Fixes https://github.com/dotnet/corefx/issues/12224

**Comment by weshaggard** [comment]
What about https://github.com/dotnet/corefx/pull/10348/commits/cb217c066c93e331059f0273f816074faf3f456c do we not need those other linux RID's as well?

**Comment by gkhanna79** [comment]
@weshaggard I am not aware of any new RIDs aside of OSX 10.12. @Petermarcu are the additional Linux RIDs also required?

**Comment by mellinoe** [comment]
This is in release/1.0.0, so the new RIDs shouldn't be supported there. That's my understanding, at least.

**Pull request merged**
