### PR TITLE
Updating release/1.0.0 dependencies to rc3-24125-01

### PR DESCRIPTION
**Pull request by ericstj**
/cc @joshfree @ellismg @bartonjs

### CODE REVIEW

**Comment by bartonjs** [comment]
LGTM

**Comment by joshfree** [comment]
should we actually remove the pinvoke workaround so soon?  Otherwise LGTM

**Comment by ericstj** [comment]
> should we actually remove the pinvoke workaround so soon? Otherwise LGTM

Yes, the workaround was only needed to get things to build correctly.  We actually have to remove since the PInvoke package no longer exists.  Since it doesn't exist we don't need the project-ref hack to get the right ref, we're getting that from packages now.

**Comment by ericstj** [comment]
Windows failed with the StackTrace issue and CentOS failed with the char tests.  Tarek has ported the char test workaround.  I've added the StackTrace workaround to this commit.

**Comment by ericstj** [comment]
WOOT!  Just waiting for approval on this one.

**Comment by joshfree** [comment]
LGTM

**Pull request merged**
