### PR TITLE
Update ExceptionUtils.vb

### PR DESCRIPTION
**Pull request by markhurd**
I assume this was a copy'n'paste typo.

### CODE REVIEW

**Comment by stephentoub** [comment]
LGTM

cc: @VSadov, @AnthonyDGreen

**Comment by VSadov** [comment]
LGTM, clearly a typo

**Comment by VSadov** [comment]
@dotnet-bot test this please

**Comment by stephentoub** [comment]
@dotnet-bot test this please

**Comment by stephentoub** [comment]
Test Innerloop Ubuntu Release Build and Test please
Test Innerloop Windows_NT Release Build and Test please

**Pull request merged**
