### PR TITLE
[release/2.1] Add Fedora 35 RID

### PR DESCRIPTION
**Pull request by omajid**
$ podman run -it registry.fedoraproject.org/fedora:rawhide /bin/bash -c 'cat /etc/os-release'
    NAME=Fedora
    VERSION="35 (Container Image Prerelease)"
    ID=fedora
    VERSION_ID=35
    VERSION_CODENAME=""
    PLATFORM_ID="platform:f35"
    PRETTY_NAME="Fedora 35 (Container Image Prerelease)"
    ANSI_COLOR="0;38;2;60;110;180"
    LOGO=fedora-logo-icon
    CPE_NAME="cpe:/o:fedoraproject:fedora:35"
    HOME_URL="https://fedoraproject.org/"
    DOCUMENTATION_URL="https://docs.fedoraproject.org/en-US/fedora/rawhide/system-administrators-guide/"
    SUPPORT_URL="https://fedoraproject.org/wiki/Communicating_and_getting_help"
    BUG_REPORT_URL="https://bugzilla.redhat.com/"
    REDHAT_BUGZILLA_PRODUCT="Fedora"
    REDHAT_BUGZILLA_PRODUCT_VERSION=rawhide
    REDHAT_SUPPORT_PRODUCT="Fedora"
    REDHAT_SUPPORT_PRODUCT_VERSION=rawhide
    PRIVACY_POLICY_URL="https://fedoraproject.org/wiki/Legal:PrivacyPolicy"
    VARIANT="Container Image"
    VARIANT_ID=container

This is a backport of https://github.com/dotnet/runtime/pull/48200.

### CODE REVIEW

**Review by ViktorHofer — COMMENTED** [review]
@Anipik does the PackageVersion need to be incremented here as well and the package explicitly marked to be built?

**Comment by Anipik** [comment]
> @Anipik does the PackageVersion need to be incremented here as well and the package explicitly marked to be built?

yes we need to do the same things here as we did in 3.1 and 5.0

**Comment by omajid** [comment]
Wasn't that already done via https://github.com/dotnet/corefx/pull/43024 ?

**Comment by Anipik** [comment]
>Wasn't that already done via #43024 ?

its fedora35

**Comment by omajid** [comment]
I meant updating the package version :smile: 

Edit: To elaborate, #43024  updates PackageVersion. Is this anything additional that needs to be done in this PR here?

**Comment by Anipik** [comment]
> I meant updating the package version 😄

correct but it wont probably shipped in this release, it will be shipped in the next release

**Comment by Anipik** [comment]
The branches are already closed for march release.

**Comment by omajid** [comment]
Hey @Anipik! Can you help me understand what exact changes I need to make to this PR?

I updated `pkg/Microsoft.NETCore.Platforms/Microsoft.NETCore.Platforms.pkgproj`; do I need to somehow update `src/packages.builds` as well?

**Comment by Anipik** [comment]
here is an example 

https://github.com/dotnet/corefx/blob/release/2.1/src/packages.builds#L27

**Comment by omajid** [comment]
Thanks!

But since that line is already present in the 2.1 branch, I am not sure how to add it again.,,

**Comment by Anipik** [comment]
Yeah we need to wait for the release

**Comment by ViktorHofer** [comment]
@omajid the release/2.1 branch needs to be "reset" to accommodate for the next servicing release which involves updating the branding and resetting the list of packages that should be built. We plan to make this easier with 6.0 LTS (i.e. sourcebuild RID support, defining packages that should be built directly in their project file, getting rid of the package index, ...).

**Comment by omajid** [comment]
Is the repo open now?

**Comment by aik-jahoda** [comment]
@omajid, @Anipik, can you please confirm all requested changes are in place?

**Comment by Anipik** [comment]
Yes the repo is open, @omajid can you add the packaging changes(packages.builds file and packageindex changes.)

**Comment by omajid** [comment]
I updated the `packages.builds` file. The packgesIndex.json didn't get updated on build. I manually added the new version 2.1.14 to it.

**Comment by aik-jahoda** [comment]
@ViktorHofer can you please approve? Do wee need service approval?

**Comment by omajid** [comment]
AFAIK, RID updates are tell-mode.

**Review by ViktorHofer — APPROVED** [review]

**Comment by aik-jahoda** [comment]
Just for the clarification: Is for tell-mode review approve enough? Is there a group op people who should participate in the review?

**Comment by ViktorHofer** [comment]
Tell mode means letting your M2 and/or Tactics know but not seeking their approval. Usually the release managers and/or infra crew would review and approve such a change.

**Pull request merged**
