### PR TITLE
Fix EventSource test to be aware of ArrayPoolEventSource

### PR DESCRIPTION
**Pull request by stephentoub**
See https://github.com/dotnet/corefx/pull/14919#issuecomment-270832193
cc: @jkotas, @davmason

### CODE REVIEW

**Comment by jkotas** [comment]
@stephentoub Thanks for fixing it.

I am wondering whether we should fold ArrayPoolEventSource into FrameworkEventSource now that ArrayPool is in corelib.

**Comment by nerdcorerising** [comment]
LGTM. Thanks

**Comment by davmason** [comment]
LGTM. Thanks

**Comment by stephentoub** [comment]
> I am wondering whether we should fold ArrayPoolEventSource into FrameworkEventSource now that ArrayPool is in corelib.

On the one hand, it'd be nice to minimize the number of EventSources we have.  On the other, it'd be nice to have consistency across runtimes, and right now the ArrayPool available for .NET Framework comes from System.Buffers.dll, which needs to use its own EventSource. Do we know what the perf impact is to an extra EventSource?

**Pull request merged**
