### PR TITLE
[Arm64] Add Base HW Intrinsics

### PR DESCRIPTION
**Pull request by sdmaclea**
@CarolEidt @eerhardt @RussKeldorph PTAL

### CODE REVIEW

**Comment by sdmaclea** [comment]
Windows x64 Debug Build has been running for 10hrs.  Most jobs triggered around the same time failed.
Retriggering.

test Windows x64 Debug Build

**Comment by sdmaclea** [comment]
The most recently trigger CI run for Windows x64 Debug Build is here.  It passed after running a little over an hour.
https://ci3.dot.net/job/dotnet_corefx/job/master/job/windows-TGroup_netcoreapp+CGroup_Debug+AGroup_x64+TestOuter_false_prtest/10028/

The original run took 12 hours.  It looks like it was started when the tip was unstable as noted above.

https://ci3.dot.net/job/dotnet_corefx/job/master/job/windows-TGroup_netcoreapp+CGroup_Debug+AGroup_x64+TestOuter_false_prtest/9983/

Since it was the most recent to finish it was the last to update the check status above which therefore is showing failed.

I think it is safe to merge this.

**Comment by eerhardt** [comment]
test Windows x64 Debug Build

**Comment by sdmaclea** [comment]
Triggering again
test Windows x64 Debug Build

**Comment by CarolEidt** [comment]
@eerhardt - are you OK with merging this now?

**Pull request merged**
