### PR TITLE
Make arguments in crossbuild.json consistent with other Linux job

### PR DESCRIPTION
**Pull request by wtgodbe**

### CODE REVIEW

**Comment by wtgodbe** [comment]
CC @MattGal @gkhanna79 @chcosta

**Comment by MattGal** [comment]
LGTM.  The SourceVersion change I assume is just to get parity with the other Linux build, not sure if that should have PB.

**Comment by wtgodbe** [comment]
@MattGal yup, just for parity.

**Comment by wtgodbe** [comment]
@gkhanna79 @maddin2016 @chcosta Here's the queued build - https://devdiv.visualstudio.com/DevDiv/Net%20CoreFX/_build/explorer?_a=summary&buildId=552373

**Pull request merged**
