### PR TITLE
Fix System.Data.SqlClient package

### PR DESCRIPTION
**Pull request by ericstj**
A couple problems with this package that surfaced after the change to
the version.  The net45 facade had an incorrect version.  There was no
net46 facade.  I've fixed up both of these problems and moved the 4.0
reference assembly to a folder that matches our conventions for
semantic-versioned reference assemblies (3-part is only used for the
legacy versions that didn't follow semantic versioning).

### CODE REVIEW

**Comment by ericstj** [comment]
/cc @saurabh500 all of these surfaced as build errors after https://github.com/dotnet/corefx/pull/6739 (red text/failed build).  If I look at the Jenkins runs I see that this did indeed fail, but Jenkins didn't bubble up the msbuild errors as failure /cc @mmitche 
```
16:56:28 d:\j\workspace\windows_nt_de---06b7984d\Tools\Packaging.targets(842,5): error : System.Data.SqlClient should support API version 4.0.0.0 on .NETFramework,Version=v4.5/win-x86 but System.Data.SqlClient/ref/net45/System.Data.SqlClient.dll was found to support 4.1.0.0. [d:\j\workspace\windows_nt_de---06b7984d\src\System.Data.SqlClient\pkg\System.Data.SqlClient.pkgproj]
16:56:28 d:\j\workspace\windows_nt_de---06b7984d\Tools\Packaging.targets(842,5): error : System.Data.SqlClient should support API version 4.0.0.0 on .NETFramework,Version=v4.5/win-x86 but System.Data.SqlClient/lib/net45/System.Data.SqlClient.dll was found to support 4.1.0.0. [d:\j\workspace\windows_nt_de---06b7984d\src\System.Data.SqlClient\pkg\System.Data.SqlClient.pkgproj]
16:56:28 d:\j\workspace\windows_nt_de---06b7984d\Tools\Packaging.targets(842,5): error : System.Data.SqlClient should support API version 4.0.0.0 on .NETFramework,Version=v4.5/win-x64 but System.Data.SqlClient/ref/net45/System.Data.SqlClient.dll was found to support 4.1.0.0. [d:\j\workspace\windows_nt_de---06b7984d\src\System.Data.SqlClient\pkg\System.Data.SqlClient.pkgproj]
16:56:28 d:\j\workspace\windows_nt_de---06b7984d\Tools\Packaging.targets(842,5): error : System.Data.SqlClient should support API version 4.0.0.0 on .NETFramework,Version=v4.5/win-x64 but System.Data.SqlClient/lib/net45/System.Data.SqlClient.dll was found to support 4.1.0.0. [d:\j\workspace\windows_nt_de---06b7984d\src\System.Data.SqlClient\pkg\System.Data.SqlClient.pkgproj]
16:56:28 d:\j\workspace\windows_nt_de---06b7984d\Tools\Packaging.targets(842,5): error : System.Data.SqlClient should support API version 4.0.0.0 on .NETFramework,Version=v4.5.1/win-x86 but System.Data.SqlClient/ref/net45/System.Data.SqlClient.dll was found to support 4.1.0.0. [d:\j\workspace\windows_nt_de---06b7984d\src\System.Data.SqlClient\pkg\System.Data.SqlClient.pkgproj]
16:56:28 d:\j\workspace\windows_nt_de---06b7984d\Tools\Packaging.targets(842,5): error : System.Data.SqlClient should support API version 4.0.0.0 on .NETFramework,Version=v4.5.1/win-x86 but System.Data.SqlClient/lib/net45/System.Data.SqlClient.dll was found to support 4.1.0.0. [d:\j\workspace\windows_nt_de---06b7984d\src\System.Data.SqlClient\pkg\System.Data.SqlClient.pkgproj]
16:56:28 d:\j\workspace\windows_nt_de---06b7984d\Tools\Packaging.targets(842,5): error : System.Data.SqlClient should support API version 4.0.0.0 on .NETFramework,Version=v4.5.1/win-x64 but System.Data.SqlClient/ref/net45/System.Data.SqlClient.dll was found to support 4.1.0.0. [d:\j\workspace\windows_nt_de---06b7984d\src\System.Data.SqlClient\pkg\System.Data.SqlClient.pkgproj]
16:56:28 d:\j\workspace\windows_nt_de---06b7984d\Tools\Packaging.targets(842,5): error : System.Data.SqlClient should support API version 4.0.0.0 on .NETFramework,Version=v4.5.1/win-x64 but System.Data.SqlClient/lib/net45/System.Data.SqlClient.dll was found to support 4.1.0.0. [d:\j\workspace\windows_nt_de---06b7984d\src\System.Data.SqlClient\pkg\System.Data.SqlClient.pkgproj]
```

```
16:58:11     20 Warning(s)
16:58:11     8 Error(s)
16:58:11 Time Elapsed 00:11:37.44
16:58:11 [ 0:58:25.23] Build Exit Code = 0
```

**Comment by saurabh500** [comment]
Thanks @ericstj 
LGTM

**Comment by mmitche** [comment]
@ericstj What leg failed?

**Comment by ericstj** [comment]
@mmitche I looked at Windows Debug, but I'd expect all legs to have that error.  http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/windows_nt_debug_prtest/3219/

**Comment by mmitche** [comment]
@ericstj This is an issue with the tools.  The continue on error is causing msbuild to not report a non-zero exit code.

16:58:10 d:\j\workspace\windows_nt_de---06b7984d\Tools\Packaging.targets(842,5): error : System.Data.SqlClient should support API version 4.0.0.0 on .NETFramework,Version=v4.5.1/win-x86 but System.Data.SqlClient/lib/net45/System.Data.SqlClient.dll was found to support 4.1.0.0. [d:\j\workspace\windows_nt_de---06b7984d\src\System.Data.SqlClient\pkg\System.Data.SqlClient.pkgproj]

```<ValidatePackage ContractName="$(BaseId)"
                     PackageId="$(Id)"
                     Files="@(PackageFile);@(RuntimeFile)"
                     SupportedFrameworks="@(SupportedFramework)"
                     Frameworks="@(ValidateFramework)"
                     RuntimeFile="$(RuntimeIdGraphDefinitionFile)"
                     FrameworkListsPath="$(FrameworkListsPath)"
                     SkipGenerationCheck="$(SkipGenerationCheck)"
                     SkipSupportCheck="$(SkipSupportCheck)"
                     SuppressionFile="$(ValidationSuppressionFile)"
                     UseNetPlatform="$(UseNetPlatform)"
                     ContinueOnError="ErrorAndContinue"/>```

**Comment by mmitche** [comment]
@ericstj Or at least, I think that's what is going on.  the ErrorAndContinue bit is ringing some bells from a ways back.  Anyways, msbuild must return non-zero for the CI system to pick it up.

**Comment by ericstj** [comment]
So I just tested and MSBuild does return non-zero for ErrorAndContinue in a single project case.  Perhaps something about how we're wrapping that in multiple msbuild invocations loses that.  I will force the failure and investigate.

**Comment by mmitche** [comment]
@ericstj Here is what I remember:

When I was working on the coreclr testing build infra, some parallel invocations with ContinueOnError would indeed print the right error, but the return code would get swallowed.

https://github.com/dotnet/coreclr/blob/master/tests/dir.traversal.targets#L25

That looks like what you want.  Is that being used?

**Comment by ericstj** [comment]
Dir.traversal.targets does use that.  I wouldn't want to put this after my task that is ErrorAndContinue since the effect of this task is to halt the build (specifically what we don't want to do).  I think this does have something to do with it.  When I do an individual project build I see the error level is set to 1, so I'll just roll up the project stack until I find the place this is being swallowed.

**Comment by mmitche** [comment]
@ericstj I think in this case, it will do all the tasks, but error if any of the queued tasks fail. The alternative is not good (swallowing the exit code), especially since it leads to bogus downstream errors.

I think this may also be related to other errors we've seen lately, where a package restore fails, but compilation continues on for a project or set of projects.  This leads to every single project throwing errors where they can't find System.String, and the console output tops out at like 100MB per build.

**Pull request merged**
