### PR TITLE
Port XmlReader, XmlTextReader: ensure Readers created from a full path have an absolute BaseURI to 2.0

### PR DESCRIPTION
**Pull request by tmds**
Port 1db6c8a203ef8a752ffefd2a194fa7dd4bce59fb to 2.0.0

cc @danmosemsft @sepidehMS @stephentoub

### CODE REVIEW

**Comment by danmosemsft** [comment]
@sepidehMS can you please review and if you approve send the template to shiproom to propose porting it to 2.0. I'll send you the template offline.

**Comment by danmosemsft** [comment]
Scratch that, it looks like @Priya91 is driving this according to the email I saw to shiproom. Over to you Priya.

**Comment by danmosemsft** [comment]
fyi @karelz

**Comment by danmosemsft** [comment]
marking no merge until shiproom okay

**Comment by sepidehMS** [comment]
LGTM. Thank you @tmds and thanks @Priya91 for driving this.

FYI: @krwq

**Comment by tmds** [comment]
I'm curious why this hasn't been merged yet.

**Comment by krwq** [comment]
@sepidehMS has this been approved for 2.0?

**Comment by sepidehMS** [comment]
@krwq I believe @Priya91 is taking care of shiproom for this.

**Comment by Priya91** [comment]
> @krwq I believe @Priya91 is taking care of shiproom for this.

@sepidehMS I'm not tracking shiproom for this.. I'm only tracking #21290. I think @danmosemsft sent out shiproom email for this.

**Comment by karelz** [comment]
@Priya91 can you please catch @danmosemsft ASAP and prepare plan for next steps? Thanks!

**Comment by krwq** [comment]
Sorry @tmds for waiting... seems like overlook on our side... 😞

**Comment by danmosemsft** [comment]
@sepidehMS is going to own this.

**Comment by sepidehMS** [comment]
Shiproom approved. Merging.

**Pull request merged**
