### PR TITLE
Centralize calls to FormatMessage

### LINKED ISSUE #287: Centralize all calls to FormatMessage
Currently we have at least two places where we call FormatMessage; Win32Exception and Win32Marshal. The former was updated to handle messages that exceeded the buffer, but the later was not.

1. Move the FormatMessage code in Win32Exception -> Win32Marshal.GetMessage
1. Look for calls to FormatMessage and make sure they go through Win32Marshal.
1. Look at the buffer size that we're passing to FormatMessage in Win32Exception, it looks like we're trying to account for trailing null, but interop already does that for us. This is a bug waiting to happen if a message happens to fall on the buffer's boundary.
1. Figure out why we're attempting to remove extraneous trailing chars? If there's extra chars in the message - we should be filling bugs against Windows to fix them, not doing something special.

### PR DESCRIPTION
**Pull request by Maxwe11**
fixes items 1 and 2 from #287

TODO
--------

- [x] Move the FormatMessage code in Win32Exception -> Win32Marshal.GetMessage
- [ ] Look for calls to FormatMessage and make sure they go through Win32Marshal (**work in progress**)

### CODE REVIEW

**Comment by Maxwe11** [comment]
Second item almost done, but adding string resources to Microsoft.Win32.Primitives requires additional packages like:
System.Diagnostics.Debug
System.Diagnostics.Tools
System.Globalization
System.IO
System.Reflection
System.Reflection.Primitives
System.Threading.Tasks
System.Text.Encoding.
This looks like overkill for just library primitives.

**Comment by YingP99** [comment]
@Maxwe11 Thank you for your good work.
* Please create a separate PR to contain just FormatMessage Interop API, and corresponding GetMessage implementation. 
* Please put the GetMessage method into the same file as FormatMessage, not the Win32.Marshal (even though the issue#287 say so).
* Don't modify other files for now, you can do subsequent changes in other PRs after the first PR reviewed, and checked in.
* If you haven't, please take a look at our documentation on how to structure Interop code - https://github.com/dotnet/corefx/wiki/Structuring-Interop-Code.

**Comment by weshaggard** [comment]
@stephentoub @pallavit can you guys please have a look at this PR.

**Comment by Maxwe11** [comment]
@YingP99 done #681

**Comment by stephentoub** [comment]
@Maxwe11, should this PR be closed now that you've opened 681? Seems like that one covers half of this, and then one or more additional PRs would be opened to address the consolidation?

**Pull request closed without merging**
