### PR TITLE
Release/2.0.0 - Add tests for EventArgs serialization (#25940)

### PR DESCRIPTION
**Pull request by ViktorHofer**
Relates to https://github.com/dotnet/corefx/issues/25930

* Add tests for EventArgs serialization

* Add EventArgs equality check as the type doesn't provide its own check

### CODE REVIEW

**Comment by danmosemsft** [comment]
Tests pending on https://github.com/dotnet/coreclr/pull/15686

**Comment by ViktorHofer** [comment]
Triggered a coreclr 2.0 build. waiting for maestro PR...

**Comment by ViktorHofer** [comment]
@dotnet-bot test this please

**Comment by ViktorHofer** [comment]
@dotnet/dnceng some of these legs show that they succeeded but have failed tests. wrong status shown?

**Comment by danmosemsft** [comment]
@dotnet-bot test this please

**Comment by MattGal** [comment]
@ViktorHofer thanks for bringing this to @dnceng 's attention, I'll take a look and file an internal issue if needed if I find anything actionable and broken.

**Comment by MattGal** [comment]
@ViktorHofer I spent some time looking at this.  Unfortunately, as you've restarted the build I can't see what the results view (mc.dot.net) looked like when you first raised the issue, but in either case the windows tests are reliably failing in the binary serialization tests, i.e. 
 https://mc.dot.net/#/user/ViktorHofer/pr~2Fjenkins~2Fdotnet~2Fcorefx~2Frelease~2F2.0.0~2F/test~2Ffunctional~2Fcli~2F/5e42ac4b84d5061eba00ebd45ccc34338e713724/workItem/System.Runtime.Serialization.Formatters.Tests .  

The test fails on every platform actually.  If you can capture a screen shot of what you're seeing if this happens again that'd be awesome, as I'd expect to have seen this test fail uniformly (every run in your PR seems to have it failing)

**Comment by ViktorHofer** [comment]
Yes I expected nearly all legs to fail as there was a bug in the test code. Unfortunately Dan restarted the build today but I still have the link to the leg: https://ci3.dot.net/job/dotnet_corefx/job/release_2.0.0/job/windows-TGroup_netfx+CGroup_Release+AGroup_x86+TestOuter_false_prtest/66/

Is that enough?

**Comment by ViktorHofer** [comment]
@dotnet/dnceng  this time a failing OSX x64 Debug Build leg:

```
ERROR: Error cloning remote repo 'origin'
hudson.plugins.git.GitException: Could not init /Users/dotnet-bot/j/workspace/dotnet_corefx/release_2.0.0/osx-TGroup_netcoreapp+CGroup_Debug+AGroup_x64+TestOuter_false_prtest

https://ci3.dot.net/job/dotnet_corefx/job/release_2.0.0/job/osx-TGroup_netcoreapp+CGroup_Debug+AGroup_x64+TestOuter_false_prtest/73/consoleText
```

**Comment by ViktorHofer** [comment]
@dotnet-bot test OSX x64 Debug Build

**Pull request merged**
