### PR TITLE
Allow TupleElementNamesAttribute on events

### PR DESCRIPTION
**Pull request by jcouv**
We realized that one AttributeTarget was missing.

@stephentoub for review
FYI for @agocke

### CODE REVIEW

**Comment by agocke** [comment]
@jcouv Thanks!

**Comment by stephentoub** [comment]
LGTM

**Comment by jcouv** [comment]
@stephentoub for review. This one is easy ;-)

**Comment by jcouv** [comment]
Nevermind, you already merged. Thanks!

**Pull request merged**
