### PR TITLE
Fix proxy authentication handling during redirects

### PR DESCRIPTION
**Pull request by davidsh**
/cc @CIPop @pgavlin @SidharthNabar @ChengTian

Reference issue #2168

### CODE REVIEW

**Comment by davidsh** [comment]
I didn't submit any new tests into GitHub because an automated test would require 4 separate machines (client, proxy, server1, server2).  I did manually test this in our internal environment.

**Comment by CIPop** [comment]
@davidsh Maybe we can add a UnitTest to validate and pin the code behavior. Having a 4-box environment involving proxy is probably not going to be possible long term either.

**Comment by davidsh** [comment]
@CIPop I've added that as a TODO in my tracking issue #2165.  It is non-trivial to add this right now as a unit test because the source code is not factored in that fashion and adding it to the mock network currently implemented in the unit tests would require adding proxy support.

**Comment by CIPop** [comment]
LGTM

**Pull request merged**
