### PR TITLE
Move tests for queryable and enumerable out of expressions.

### LINKED ISSUE #7904: Some tests in Linq.Expressions should be in Linq or Linq.Queryable
In particular `MatchSequencePattern` tests for consistency between `Enumerable` and `Queryable` and so should be in the tests for each to catch any regressions in either. (Consider how #5947 changing the `Enumerable` API didn't trigger it in CI).

There are some further tests that are really testing `Enumerable` or `Queryable` and should be tested along with the relevant assembly, though most are already well covered by the existing tests. And exception is `QueryableOfQueryable` which hits features of both `Queryable` and of `Expressions` but those features of `Expressions` it touches on are already well covered in parameter an lambda tests.

### PR DESCRIPTION
**Pull request by JonHanna**
Fixes #7904

Refactor `MatchSequencePattern` test to not use `Console.WriteLine()` and remove it from Linq.Expressions.Tests putting a copy in the tests for Linq and Linq.Queryable to catch regressions in either.

Simplify `QueryableOfQueryable` and move it into queryable tests.

Remove tests from Expressions test testing features of `Enumerable` or `Queryable` and already covered by tests in the relevant project.

### CODE REVIEW

**Comment by JonHanna** [comment]
Test Innerloop CentOS7.1 Debug Build and Test 
(Permissions: http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/master/job/centos7.1_debug_tst_prtest/174/consoleFull#6262143651f1a4601-6aec-4fd5-b678-78d4389fd5e8)

**Comment by JonHanna** [comment]
Test Innerloop OSX Debug Build and Test
Test Innerloop OSX Release Build and Test
(Failed to launch)

**Comment by JonHanna** [comment]
Test Innerloop OSX Debug Build and Test
Test Innerloop OSX Release Build and Test

**Comment by JonHanna** [comment]
Test Innerloop CentOS7.1 Debug Build and Test
(Connection dropped during System.Net.WebHeaderCollection.Tests)
Test  Innerloop Windows_NT Release Build and Test 
(Unable to connect to the remote server during System.Net.WebSockets.Client.Tests.ClientWebSocketTest.CloseAsync_CloseDescriptionHasUnicode_Success)

**Comment by VSadov** [comment]
LGTM, thanks!

**Pull request merged**
