### PR TITLE
Port build reliability fixes from master.

### PR DESCRIPTION
**Pull request by jhendrixMSFT**
This is a port of the following commits.

329de5ea298885637d01ae85186a42436a375b8b
7307337eee2884a631d0c5495f360a0aa77b2d40
23850bd98a17495c24392a5b2d47a52fc7b46e18

### CODE REVIEW

**Comment by joshfree** [comment]
LGTM.  Please merge this once CI passes

**Comment by weshaggard** [comment]
@dagood had some changes to UpdateDependencies that we are going to need in the release branch to make it fully functional when we make the switch.

**Comment by weshaggard** [comment]
https://github.com/dotnet/corefx/pull/8886
https://github.com/dotnet/corefx/pull/8999
https://github.com/dotnet/corefx/pull/9042

Those are a few PR's that I remember we will need.

**Comment by jhendrixMSFT** [comment]
@weshaggard Thanks I will port those in a separate commit as this PR is about ready to be merged.

**Pull request merged**
