### PR TITLE
Re-enable EventSource tests on Unix

### LINKED ISSUE #4871: EventSource tests fail on non-windows platforms
The majority of the EventSource tests fail on non-windows platforms. Need to investigate further.

### PR DESCRIPTION
**Pull request by stephentoub**
cc: @davmason 
Hopefully fixed now that https://github.com/dotnet/coreclr/pull/3955 was merged.
Fixes #4871

### CODE REVIEW

**Comment by davmason** [comment]
The only other thing is the Test_EventSource_Lifetime test should have a [PlatformSpecific(PlatformID.Windows)], because non-windows eventsources don't have a liftetime, they don't keep any ETW state around so the test is meaningless.

**Comment by stephentoub** [comment]
Thanks, @davmason. I updated the test to be Windows-only.

**Comment by stephentoub** [comment]
@dotnet-bot test this please

**Comment by stephentoub** [comment]
@dotnet-bot test this please (hopefully picking up a new enough mscorlib this time)

**Pull request merged**
