### PR TITLE
Fix failing tests on Windows 7

### PR DESCRIPTION
**Pull request by tarekgh**

### CODE REVIEW

**Comment by tarekgh** [comment]
#12050
#12051

**Comment by tarekgh** [comment]
CC @stephentoub @danmosemsft

**Comment by stephentoub** [comment]
These are just expected differences at the OS level?

LGTM

**Comment by tarekgh** [comment]
@stephentoub 

> These are just expected differences at the OS level?

Yes. Windows 7 collations is very old and many things was not supported there like the surrogate casing for instance. 
Thanks for your review

**Pull request merged**
