### PR TITLE
Fix on EnvelopedCms.Decode for Unix

### PR DESCRIPTION
**Pull request by hoyosjs**
+Fixed bugs introduced by the refactoring of EnvelopedCms.Decode
refactoring.
+Added sanity check on encoded lengths for DerSequenceReader and added
corresponding test cases.

@bartonjs @weshaggard

### CODE REVIEW

**Comment by hoyosjs** [comment]
As of right now I'm having some build problems, unrelated to the files modified, on my local machine on Linux so please wait until I get to solve these before merging.

**Comment by bartonjs** [comment]
@dotnet-bot Test this please

(seeing if the CI job is working)

**Comment by stephentoub** [comment]
LGTM

**Comment by bartonjs** [comment]
LGTM2, once @hoyosjs retracts his declaration of "please wait"

**Comment by bartonjs** [comment]
@dotnet-bot Test this please (now with package prefetch issues resolved externally)

**Comment by bartonjs** [comment]
@hoyosjs We have CI now, and it says all of the enabled tests pass.  You can look at http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/dev_cms_unix/job/ubuntu14.04_debug_prtest/2/testReport/ to spot check that tests you think should be running actually are.

**Comment by hoyosjs** [comment]
Reviewed the output of the tests. It's fine to merge now.

**Pull request merged**
