### PR TITLE
Fix ProcessStart_TryOpenFolder_UseShellExecuteIsTrue_DoesNotThrow

### PR DESCRIPTION
**Pull request by maryamariyan**
Fix ProcessStart_TryOpenFolder_UseShellExecuteIsTrue_DoesNotThrow

### CODE REVIEW

**Comment by maryamariyan** [comment]
@dotnet-bot help please

**Comment by safern** [comment]
@dotnet/dnceng Linux build is marked as failed but I don't see any failed test, all of them are marked as passed.

**Comment by maryamariyan** [comment]
@dotnet-bot test outerloop netcoreapp Windows_NT Release

**Comment by mmitche** [comment]
@safern I don't see a failed link.  Where are you seeing this?

**Comment by maryamariyan** [comment]
@dotnet-bot test Outerloop UWP NETNative x64 Release Build

**Comment by maryamariyan** [comment]
@mmitche I think after I triggered the first outerloop build it refreshed and the failure disappeared.

**Comment by maryamariyan** [comment]
@dotnet-bot test Outerloop Windows x64 Release Build

**Comment by danmosemsft** [comment]
failure was unrelated https://github.com/dotnet/corefx/issues/20223

**Pull request merged**
