### PR TITLE
Removed dead code from Security.Cryptography.X509Certificates for issue #17905.

### PR DESCRIPTION
**Pull request by yaelkeemink**
Removed dead code from Security Cryptography X509Certificates for issue #17905.

### CODE REVIEW

**Comment by karelz** [comment]
@yaelkeemink thanks for your contribution!
Which CSVs did you cover in this PR? (I'd like to update the top post in #17905)

**Comment by yaelkeemink** [comment]
@karelz I coverd System.Security.Cryptography.X509Certificates in this PR

**Comment by karelz** [comment]
Ah, it is in the title even - I missed it as it is on 2nd line - sorry!

**Comment by karelz** [comment]
Top post of #17905 updated
cc @danmosemsft

**Pull request merged**
