### PR TITLE
Tests for not calling AssemblyResolve event for CoreLib resources

### PR DESCRIPTION
**Pull request by kouvel**
Port of https://github.com/dotnet/corefx/pull/22552 to release/2.0.0
Depends on https://github.com/dotnet/coreclr/pull/13003
Fixes dotnet/coreclr#12668

### CODE REVIEW

**Comment by karelz** [comment]
@kouvel any progress on this one?

**Comment by kouvel** [comment]
This is intended for servicing 2.0.0. Is this the right branch for that, and is it open for checkins? dotnet/coreclr#13003 would need to be merged first for tests in this PR to pass.

**Comment by kouvel** [comment]
@dotnet-bot test this please

**Comment by karelz** [comment]
release/2.0.0 is the right servicing branch.
Please send email to shiproom for approval.

**Comment by kouvel** [comment]
This one was already approved, just waiting for CoreCLR packages to be updated

**Comment by kouvel** [comment]
@dotnet-bot test this please

**Comment by danmosemsft** [comment]
Waiting on https://github.com/dotnet/coreclr/pull/13003 to reach here. I kicked off a coreclr pipe build for some reason it didn't do it automatically.

**Comment by kouvel** [comment]
@dotnet-bot test this please

**Comment by kouvel** [comment]
@dotnet-bot test this please

**Comment by danmosemsft** [comment]
Waiting on @weshaggard to do manual ingestion into corefx 2.0

**Comment by weshaggard** [comment]
The update was merged with https://github.com/dotnet/corefx/pull/23303.

**Comment by kouvel** [comment]
Thanks @weshaggard

**Comment by kouvel** [comment]
@dotnet-bot test this please

**Comment by danmosemsft** [comment]
ARMEL is known.

**Comment by danmosemsft** [comment]
Fix released https://github.com/dotnet/corefx/releases/tag/v2.0.3

**Pull request merged**
