### PR TITLE
[release/3.1] Fix build clang10

### PR DESCRIPTION
**Pull request by ayakael**
Fixes build with clang 10+. I'm not sure how this affects previous versions of clang, I havn't had the opportunity to test.

Made as part of Alpine Linux dotnet31 / dotnet5 packaging project, see dotnet/source-build#2695

### CODE REVIEW

**Comment by ayakael** [comment]
@omajid This bug is also in Fedora's 3.1 package. Is there a reason you did not upstream? I see if breaks checks in Windows / MacOS build, thus I want to see if its worth keeping open.

**Comment by omajid** [comment]
I think it's a good idea to keep corefx (and coreclr) building with newer clang versions. I have a PR in progress for clang 13 support as well. But we can't break Windows or macOS. Perhaps we can check that the compiler supports the flags before enabling them?

**Comment by ayakael** [comment]
Referencing your PR, I've introduced the checks. Thanks!

**Comment by carlossanlop** [comment]
@ayakael should this PR be closed, since we have this other one? https://github.com/dotnet/corefx/pull/43104

**Comment by carlossanlop** [comment]
@hoyosjs is this something you could help review?

**Comment by hoyosjs** [comment]
Don't see how, but there's a fair amount of failures here.

**Comment by carlossanlop** [comment]
Closing since 3.1 is going out of support.

**Pull request closed without merging**
