### PR TITLE
Misc. minor code improvements to System.Linq.Expressions

### PR DESCRIPTION
**Pull request by bartdesmet**
* Removing unwarranted uses of `var`
* Removing unnecessary namespace qualifications in type names
* Removing some more unused usings
* Fixing some comments

CC @stephentoub

### CODE REVIEW

**Comment by stephentoub** [comment]
@ericstj, the OSX leg failed with tons of errors like this:
```
Microsoft.Private.CoreFx.NETCoreApp.pkgproj(63,5): error : Assembly 'System.Console' is missing dependency 'System.Collections'
```
Any ideas what causes that / why it only affected macOS?

**Comment by stephentoub** [comment]
@dotnet-bot test Innerloop OSX Debug Build and Test please (errors about missing dependencies)

**Comment by ericstj** [comment]
Hmm, that's the closure task I added.  That would indicate that System.Collections was missing from the layout.  Let me have a look at the build.

**Comment by ericstj** [comment]
Here's the warning that seems to have caused it:
```
09:27:14 /Users/dotnet-bot/j/workspace/dotnet_corefx/master/osx_debug_prtest/Tools/Packaging.targets(1281,5): warning MSB3026: Could not copy "/Users/dotnet-bot/j/workspace/dotnet_corefx/master/osx_debug_prtest/bin/AnyOS.AnyCPU.Debug/System.Collections/System.Collections.dll" to "/Users/dotnet-bot/j/workspace/dotnet_corefx/master/osx_debug_prtest/bin/packages/Debug/layout/runtimes/osx.10.10-x64/lib/netcoreapp1.1/System.Collections.dll". Beginning retry 1 in 1000ms. The process cannot access the file '/Users/dotnet-bot/j/workspace/dotnet_corefx/master/osx_debug_prtest/bin/packages/Debug/layout/runtimes/osx.10.10-x64/lib/netcoreapp1.1/System.Collections.dll' because it is being used by another process. [/Users/dotnet-bot/j/workspace/dotnet_corefx/master/osx_debug_prtest/src/System.Collections/pkg/System.Collections.pkgproj]
```

**Comment by ericstj** [comment]
Looks like it might be a race, I am investigating...

**Comment by ericstj** [comment]
Yep, found the problem.  It is a race.  Needs a buildtools fix.  Retry until that fix goes in.  Sorry for the break :(.

**Comment by stephentoub** [comment]
Thanks, @ericstj.

**Comment by ericstj** [comment]
NP, FYI we now have closure and cycle detection at build time for netcoreapp.1.1

**Pull request merged**
