### PR TITLE
Add test verifying HttpClient negotiates Tls12 when None specified

### PR DESCRIPTION
**Pull request by stephentoub**
Fixes https://github.com/dotnet/corefx/issues/8523
cc: @davidsh, @cipop

### CODE REVIEW

**Comment by davidsh** [comment]
I'm not sure this test will work on Windows 7. So, if/when the CI machines run that, this test might fail. TLS 1.2 on Windows 7 needs to be enabled.

https://technet.microsoft.com/en-us/library/dn786418.aspx
(See the TLS 1.2 section).

**Comment by stephentoub** [comment]
Test Outerloop windows7 Debug please

**Comment by stephentoub** [comment]
Test Outerloop windows 7 Debug please

**Comment by stephentoub** [comment]
> I'm not sure this test will work on Windows 7

It passed on Win7 in CI. Maybe those machines are configured appropriately already?

Are you ok checking it in like that, or you want me to make some other change to it?

**Comment by davidsh** [comment]
>Maybe those machines are configured appropriately already?

I would at least add some comments to the test referencing that documentation link before checking it in. Then, we'll have a place to start if the test starts failing. 

This test uses the Loopback server, So, that means that a dev machine running Windows 7 has to be configured correctly.  Have you tried out a new Windows 7 VM to see if the test runs or not? Maybe the documentation is wrong but it implies that on a new Windows 7 box it Tls12 might not be enabled. It might be worth it to spend a little time testing it out to be sure.

**Comment by stephentoub** [comment]
> I would at least add some comments to the test referencing that documentation link before checking it in. Then, we'll have a place to start if the test starts failing.

Ok.

> Have you tried out a new Windows 7 VM to see if the test runs or not? Maybe the documentation is wrong but it implies that on a new Windows 7 box it Tls12 might not be enabled. It might be worth it to spend a little time testing it out to be sure.

The issue was marked as Future.  This was worth my time to fix (and  verify  we're doing   the right   thing on  current OSes) when it was taking 5 minutes. Not so much for doing much more than that :) I can leave the issue open if you'd like something to track verifying on win7.

**Comment by davidsh** [comment]
@stephentoub Thanks for fixing this issue that was originally assigned to me. Now I have more time to fix other bugs. ;)

I will set up a new Win7 VM and do some experiments. I'll open a new issue if I see problems.

**Comment by CIPop** [comment]
@davidsh 

> I'm not sure this test will work on Windows 7

Win7 supports TLS1.2 if specifically requested. The OS _Default_ will not include TLS1.2 without a registry change. Your code isn't using the system default (and I doubt that can be achieved with WinHttp).

**Pull request merged**
