### PR TITLE
Added test for Delegate.CreateDelegate method

### PR DESCRIPTION
**Pull request by zaytsev-victor**
Added test for dotnet/coreclr#15196

### CODE REVIEW

**Comment by joperezr** [comment]
Thanks for the contribution. I'll double check to see if this works in the core-rt scenario

**Comment by joperezr** [comment]
test runs fine in uapaot FWIW

**Comment by stephentoub** [comment]
@dotnet-bot test UWP CoreCLR x64 Debug Build please

**Comment by stephentoub** [comment]
Is this test expected to fail on netfx?  If yes, it needs to have an attribute like:
```C#
[SkipOnTargetFramework(TargetFrameworkMonikers.NetFramework, "dotnet/coreclr#15196")]
```
applied to it.

**Comment by zaytsev-victor** [comment]
@stephentoub yes, it is expected that this test is failed on netfx (since behavior updated only for CoreCLR). Thanks for the tip!

**Pull request merged**
