### PR TITLE
S.S.C.Pkcs: Move ASN.1 decoding/encoding from PkcsPal to PkcsHelpers

### PR DESCRIPTION
**Pull request by filipnavara**
...and always use the managed ASN.1 API.

Related to #39357.

I intentionally didn't clean-up the Interop.* files because they should be reused from S.S.C.X509Certificates later on.

### CODE REVIEW

**Comment by bartonjs** [comment]
This is potentially disruptive to 3.0, so marking as hold until master is vNext.

**Comment by filipnavara** [comment]
Totally understood. That's why I split it from the trivial and obvious fix. Let's wait for the merge window to open.

**Comment by bartonjs** [comment]
Looks like the only failures (and "not yet reported" results) are #39081 and #34361.

**Pull request merged**
