### PR TITLE
Add Exceptions and Tests to System.Runtime

### PR DESCRIPTION
**Pull request by Lixire**
Referring to #9854 

**Notes:** 
 - These tests target netstandard1.7 so they currently don't run (although they do build)
 - Merge only when coreclr version is updated to any version past 24408-03

@ellismg @weshaggard @ioanacrant

### CODE REVIEW

**Comment by Lixire** [comment]
@dotnet-bot test this please

**Comment by weshaggard** [comment]
Looks like you are testing a member that isn't in the reference assembly.

>error CS1061: 'NotFiniteNumberException' does not contain a definition for 'OffendingNumber' and no extension method 'OffendingNumber' accepting a first argument of type 'NotFiniteNumberException' could be found (are you missing a using directive or an assembly reference?) [D:\j\workspace\windows_nt_de---0cbbd14c\src\System.Runtime\tests\System.Runtime.Tests.csproj]

**Comment by Lixire** [comment]
I think it's probably because I didn't include the offendingNumber getter? It's strange that mine still built locally though.

**Comment by weshaggard** [comment]
>12:04:29 D:\j\workspace\windows_nt_de---0cbbd14c\Tools\ApiCompat.targets(55,5): error : MembersMustExist : Member 'System.ExecutionEngineException..ctor()' does not exist in the implementation but it does exist in the contract. [D:\j\workspace\windows_nt_de---0cbbd14c\src\System.Runtime\src\System.Runtime.csproj]
12:04:29 D:\j\workspace\windows_nt_de---0cbbd14c\Tools\ApiCompat.targets(55,5): error : MembersMustExist : Member 'System.ExecutionEngineException..ctor(System.String)' does not exist in the implementation but it does exist in the contract. [D:\j\workspace\windows_nt_de---0cbbd14c\src\System.Runtime\src\System.Runtime.csproj]
12:04:29 D:\j\workspace\windows_nt_de---0cbbd14c\Tools\ApiCompat.targets(55,5): error : MembersMustExist : Member 'System.ExecutionEngineException..ctor(System.String, System.Exception)' does not exist in the implementation but it does exist in the contract. [D:\j\workspace\windows_nt_de---0cbbd14c\src\System.Runtime\src\System.Runtime.csproj]
12:04:29 D:\j\workspace\windows_nt_de---0cbbd14c\Tools\ApiCompat.targets(55,5): error : MembersMustExist : Member 'System.NotFiniteNumberException..ctor(System.Double)' does not exist in the implementation but it does exist in the contract. [D:\j\workspace\windows_nt_de---0cbbd14c\src\System.Runtime\src\System.Runtime.csproj]
12:04:29 D:\j\workspace\windows_nt_de---0cbbd14c\Tools\ApiCompat.targets(55,5): error : MembersMustExist : Member 'System.NotFiniteNumberException..ctor(System.String, System.Double)' does not exist in the implementation but it does exist in the contract. [D:\j\workspace\windows_nt_de---0cbbd14c\src\System.Runtime\src\System.Runtime.csproj]
12:04:29   System.Diagnostics.Tools -> D:\j\workspace\windows_nt_de---0cbbd14c\bin\AnyOS.AnyCPU.Debug\System.Diagnostics.Tools\System.Diagnostics.Tools.dll
12:04:29 D:\j\workspace\windows_nt_de---0cbbd14c\Tools\ApiCompat.targets(55,5): error : MembersMustExist : Member 'System.NotFiniteNumberException..ctor(System.String, System.Double, System.Exception)' does not exist in the implementation but it does exist in the contract. [D:\j\workspace\windows_nt_de---0cbbd14c\src\System.Runtime\src\System.Runtime.csproj]
12:04:29 D:\j\workspace\windows_nt_de---0cbbd14c\Tools\ApiCompat.targets(55,5): error : MembersMustExist : Member 'System.NotFiniteNumberException.OffendingNumber.get()' does not exist in the implementation but it does exist in the contract. [D:\j\workspace\windows_nt_de---0cbbd14c\src\System.Runtime\src\System.Runtime.csproj]
12:04:29 D:\j\workspace\windows_nt_de---0cbbd14c\Tools\ApiCompat.targets(55,5): error : MembersMustExist : Member 'System.Runtime.InteropServices.ExternalException..ctor(System.String, System.Int32)' does not exist in the implementation but it does exist in the contract. [D:\j\workspace\windows_nt_de---0cbbd14c\src\System.Runtime\src\System.Runtime.csproj]
12:04:29 D:\j\workspace\windows_nt_de---0cbbd14c\Tools\ApiCompat.targets(69,5): error : ApiCompat failed for 'D:\j\workspace\windows_nt_de--

Looks like there are still some members missing in S.P.CoreLib/Mscorlib from coreclr. 

Having a closer look it appears as thoe they are there. https://github.com/dotnet/coreclr/blob/master/src/mscorlib/ref/mscorlib.cs#L1878. You likely need to rebase your commits on top of the latest dev/api commit to ensure you have picked up the latest CoreCLR package changes.

**Comment by Lixire** [comment]
@weshaggard I rebased the commits but Innerloop Windows_NT Debug Build and Test did not pass. This isn't an issue with my code though, right?

**Comment by joperezr** [comment]
@Lixire right, I doubt this has something to do with your change, I'll requeue your build.

**Comment by joperezr** [comment]
@dotnet-bot test Innerloop Windows_NT Debug Build and Test please

**Pull request merged**
