### PR TITLE
Add rel-notes and project URL to nupkgs

### LINKED ISSUE #1706: Release notes for packages
I just saw that [System.Collections.Immutable](https://github.com/dotnet/corefx/releases/tag/System.Collections.Immutable-1.1.36) and [System.Reflection.Metadata](https://github.com/dotnet/corefx/releases/tag/System.Reflection.Metadata-1.0.21) were tagged by @nguerrera.

The releases page on github has links to release notes on the msdn blog:

- http://blogs.msdn.com/b/bclteam/p/immutable.aspx
- http://blogs.msdn.com/b/bclteam/p/metadata.aspx

Is this how release notes are planned to be done in the future as well? Or can we put the release notes as Markdown on github?

### LINKED ISSUE #8758: link to the release notes github tag from the nuspec files
New bug copied from conversation @ https://github.com/dotnet/corefx/issues/1706

from @akoeplinger --

> The only other suggestion I'd have is adding the link to the releaseNotes tag into the nuspec for the packages as well, so they show up on nuget.org.

### PR DESCRIPTION
**Pull request by ericstj**
This is a 1.1.0-beta specific link for relnotes.

/cc @joshfree @leecow @weshaggard 

Fixes #8758

### CODE REVIEW

**Comment by weshaggard** [comment]
CC @StephenBonikowsky @zhenlan for WCF

LGTM

**Comment by zhenlan** [comment]
Thanks @weshaggard @ericstj for the heads up. I think we can use the same fwlink as corefx for now as long as WCF and corefx are in the same release. I will make sure the .Net Core release note has a link to WCF release note. In the future, if WCF has separate releases, we can consider to have our own fwlink.

**Comment by ericstj** [comment]
Merged since this passed before conflicting on BuildTools version.

**Pull request merged**
