### PR TITLE
Improve serial throughput of HttpClient on Unix

### PR DESCRIPTION
**Pull request by stephentoub**
HttpClient on Unix has a thread dedicated to multiplexing the processing of any number of concurrent requests on that client.  When a request comes in and that worker thread isn't running, a worker is spun up, and that worker will service any number of requests that come in while it's up.  Then, when requests quiesce and there's no more processing to be done, the worker goes away.  If more work later arrives, a new worker is spun up.

This is done to avoid burning a thread per HttpClient when there's no work to be done on that client.  It works well for bursts of activity as well as for sustained concurrent usage.  However, if the client is used for a sequence of requests, one after the other, there's a good chance that the worker will go away between requests, requiring a new worker to be spun up for each.  This has non-trivial costs, both in terms of CPU processing and in terms of managed and native resource allocation/deallocation.

This commit enables a worker to briefly pause before exiting, blocking for a short period of time for new work to arrive rather than simply exiting.

With a simple serial workload like:
```C#
using System;
using System.Diagnostics;
using System.Net.Http;
using System.Threading.Tasks;

public class Program
{
    public static void Main() { MainAsync().GetAwaiter().GetResult(); }
    private static async Task MainAsync()
    {
        var c = new HttpClient();
        var url = new Uri("http://httpbin.org/ip");
        while (true)
        {
            var sw = Stopwatch.StartNew();
            for (int i = 0; i < 100; i++)
            {
                await c.GetStringAsync(url);
            }
            Console.WriteLine(sw.Elapsed.TotalSeconds);
            Task.Delay(500).Wait();
        }
    }
}
```
Prior to this change, each run of 100 requests would end up spinning up anywhere between 20 and 40 workers, whereas after the change it typically only spins up 1.  This has a significant impact on throughput, typically doubling throughput of this test on my machine, e.g. before:
```
4.1502928
3.8951023
4.7506992
4.0254529
```
and after:
```
2.2819518
1.9307756
1.9129248
1.8165896
```

cc: @ericeil, @kapilash, @davidsh, @cipop

### CODE REVIEW

**Comment by ericeil** [comment]
This looks good to me, though we should probably consider consolidating this with the epoll support in Socket at some point.  It would be nice if we didn't have a separate background processing thread for every individual component. :)

**Comment by stephentoub** [comment]
Thanks, Eric.

> though we should probably consider consolidating this with the epoll support in Socket at some point

Yeah, if we were to implement a shared mechanism in its own library that would allow for reuse and which System.Net.Http.dll and System.Net.Sockets.dll could sit on top of, we could switch to using the socket-based APIs in libcurl, which would let us use epoll, and then use that shared mechanism.

**Comment by stephentoub** [comment]
@dotnet-bot test this please

**Comment by stephentoub** [comment]
Test Innerloop OSX Debug Build and Test please
Test Innerloop Ubuntu Release Build and Test please

**Comment by stephentoub** [comment]
Test Innerloop OSX Debug Build and Test please
Test Innerloop Ubuntu Release Build and Test please

**Comment by stephentoub** [comment]
Test Innerloop OSX Debug Build and Test please

**Pull request merged**
