### PR TITLE
Fix typo 'segement' to 'segment'

### PR DESCRIPTION
**Pull request by jo-ninja**

### CODE REVIEW

**Comment by davidfowl** [comment]
We all approved it, who is merging it 🤣

**Comment by ahsonkhan** [comment]
> We all approved it, who is merging it

Waiting for CI to go green :)

**Comment by ahsonkhan** [comment]
@dotnet-bot Linux x64 Release Build
@dotnet-bot test NETFX x86 Release Build
@dotnet-bot test OSX x64 Debug Build
@dotnet-bot test Windows x64 Debug Build 
@dotnet-bot test Windows x86 Release Build

@dotnet/dnceng

**Comment by ahsonkhan** [comment]
@dotnet-bot test Linux x64 Release Build

**Comment by ahsonkhan** [comment]
@dotnet-bot test Linux x64 Release Build
@dotnet-bot test NETFX x86 Release Build
@dotnet-bot test OSX x64 Debug Build
@dotnet-bot test Windows x64 Debug Build 
@dotnet-bot test Windows x86 Release Build

**Pull request merged**
