### PR TITLE
Add osx.10.9 to runtimes.json

### PR DESCRIPTION
**Pull request by natemcmaster**
Resolves package restore issues on OSX 10.9

### CODE REVIEW

**Comment by natemcmaster** [comment]
cc @ericstj 
This will unblock [Entity Framework's Travis CI](https://travis-ci.org/aspnet/EntityFramework/jobs/93278505#L2811) (the CI agents run on OSX Mavericks).

**Comment by ellismg** [comment]
In the past we have said we only supported 10.10+.  Are we changing that promise?  If so, at some point we should get coverage on 10.9.

**Comment by natemcmaster** [comment]
@ellismg I wasn't aware that we only support 10.10+. I couldn't find this anywhere in documentation or README's. We definitely have customers on Mavericks. If we don't plan to add support for 10.9, can we at least message more clearly the 10.10+ requirement?

FWIW [a few ASP.NET projects](https://github.com/search?utf8=%E2%9C%93&q=user%3Aaspnet+extension%3Ayml+osx) build and run on Travis CI (osx 10.9) without problems (but of course this is nowhere near full 10.9 testing).

**Comment by stephentoub** [comment]
cc: @joshfree

**Comment by moozzyk** [comment]
@natemcmaster have you tried overriding the runtime id on Travis using the  `DNX_RUNTIME_ID`?

**Comment by natemcmaster** [comment]
@moozzyk no, didn't know this existed. IMO I'd rather build true 10.9 support than start requiring all 10.9 to have a magic env variable.

**Comment by moozzyk** [comment]
`DNX_RUNTIME_ID` allows overwriting the runtime id for cases like this - i.e. you know that your OS is officially not supported but on the other hand you know/expect things will/should work. I think "true 10.9" is not about adding a runtime id to a json file - you also need to verify it really works (I would say you would have to ensure the same level of verification as for the other supported versions (e.g. 10.10 in this case))

**Comment by joshfree** [comment]
@natemcmaster 10.10 is the current minimum required version for .NET Core and for VS Code.  We're currently looking at moving the minimum up to El Capitan 10.11

**Comment by natemcmaster** [comment]
@joshfree I don't have any usage stats about versions of OSX, so I can't defend an opinion on whether 10.10 is the right cutoff or not. But if 10.9 support is definitely out, then we can close this PR. 

Still would be nice to make it clearer to users what versions of OSX are required.

**Comment by joshfree** [comment]
@blackdwarf can you make the minimum OS versions clearer on http://dotnet.github.io/getting-started/?

**Comment by blackdwarf** [comment]
@joshfree I didn't want to put the version # in the buttons themselves, since we will be changing those (the supported versions) in the future as we progress. First step for Ubuntu has the note. I can either place it more prominently or place it in the button. What would help the most?

**Comment by joshfree** [comment]
@blackdwarf I didn't see any note for Mac; the Ubuntu note could be more prominent also (perhaps the first line).

**Pull request closed without merging**
