### PR TITLE
Update split CoreFX dependencies to rc4-24201-04

### PR DESCRIPTION
**Pull request by dagood**
The same update as https://github.com/dotnet/corefx/pull/9026, but after splitting the CoreFX from the TFS-built dependencies.

/cc @dotnet/corefx-contrib

### CODE REVIEW

**Comment by stephentoub** [comment]
LGTM.

**Comment by weshaggard** [comment]
LGTM - It does appear as though it conflicted with https://github.com/dotnet/corefx/pull/9029 after I merged we will need to figure out how we prevent these PR's from overlapping conflicting.

**Comment by dagood** [comment]
Hmm, kdiff3 can resolve these without any input. They're like:

```diff
[C:\git\corefx\dir.props]
<<<<<<< HEAD
    <CoreFxExpectedPrerelease>rc4-24201-04</CoreFxExpectedPrerelease>
    <CoreClrExpectedPrerelease>rc4-24131-00</CoreClrExpectedPrerelease>
    <ExternalExpectedPrerelease>rc4-24131-00</ExternalExpectedPrerelease>
=======
    <CoreFxExpectedPrerelease>rc4-24131-00</CoreFxExpectedPrerelease>
    <CoreClrExpectedPrerelease>rc4-24201-00</CoreClrExpectedPrerelease>
    <ExternalExpectedPrerelease>rc4-24201-00</ExternalExpectedPrerelease>
>>>>>>> upstream/master
```

```diff
[C:\git\corefx\src\System.Data.SqlClient\tests\FunctionalTests\project.json]
{
  "dependencies": {
    "Microsoft.CSharp": "4.0.1-rc4-24201-04",
    "Microsoft.NETCore.Platforms": "1.0.1-rc4-24201-04",
    "runtime.native.System.Data.SqlClient.sni": "4.0.0-rc3-24131-00",
<<<<<<< HEAD
    "System.Data.Common": "4.1.0-rc4-24201-04",
    "System.Data.SqlClient": "4.1.0-rc4-24131-00",
    "System.Text.Encoding.CodePages": "4.0.1-rc4-24201-04",
    "System.Text.RegularExpressions": "4.1.0-rc4-24201-04",
    "System.Collections": "4.0.11-rc4-24201-04",
    "System.Collections.Concurrent": "4.0.12-rc4-24201-04",
    "System.Diagnostics.DiagnosticSource": "4.0.0-rc4-24201-04",
    "System.Xml.ReaderWriter": "4.0.11-rc4-24201-04",
=======
    "System.Data.Common": "4.1.0-rc4-24131-00",
    "System.Data.SqlClient": "4.1.0-rc4-24201-00",
    "System.Text.Encoding.CodePages": "4.0.1-rc4-24131-00",
    "System.Text.RegularExpressions": "4.1.0-rc4-24131-00",
    "System.Collections": "4.0.11-rc4-24131-00",
    "System.Collections.Concurrent": "4.0.12-rc4-24131-00",
    "System.Diagnostics.DiagnosticSource": "4.0.0-rc4-24131-00",
    "System.Xml.ReaderWriter": "4.0.11-rc4-24131-00",
>>>>>>> upstream/master
    "xunit": "2.1.0",
    "xunit.netcore.extensions": "1.0.0-prerelease-00312-04",
    "test-runtime": {
      "target": "project",
      "exclude": "compile"
    }
  },
```

I'll resolve these and keep the old commit on a new branch to check it out more later.

**Comment by dagood** [comment]
I see, when adjacent lines change, there's a conflict. (http://programmers.stackexchange.com/q/194788)

For a real, nice solution, I think we need some sort of central version thing (global.json?) that project.jsons can draw from.

In the short term, addressing the merge conflicts directly, I can think of a hacky workaround: we could segment the dependencies into groups in the project.jsons instead of sorting them alphabetically, or add extra newlines between each dependency. Putting this into dependency auto-fix would keep it from being cumbersome, but I think I'd view this as a last resort.

Anyone have other ideas? Maybe we could do infrastructure work to combine or stage the PR's, or some other approach I'm not even considering.

**Comment by weshaggard** [comment]
Lets see how these start to progress and see if we can find a nice pattern and fix it when it becomes a problem.

**Comment by dagood** [comment]
I'm fairly certain the issue is the adjacent-line changes. I made a test repo to try it out, and without a newline there was a conflict and with one there wasn't. That said, it doesn't hurt (beyond some manual conflict resolution) to let it happen a few more times in case there really is something weirder going on.

**Pull request merged**
