### PR TITLE
Revert "Revert "System.Globalization.Extensions cleanup""

### PR DESCRIPTION
**Pull request by tarekgh**
Reverts dotnet/corefx#12865

### CODE REVIEW

**Comment by tarekgh** [comment]
@dotnet-bot test innerloop OpenSUSE13.2 Debug
@dotnet-bot test innerloop OpenSUSE13.2 Release
@dotnet-bot test innerloop Ubuntu16.04 Debug
@dotnet-bot test innerloop Ubuntu16.04 Release

**Comment by tarekgh** [comment]
CC @Clockwork-Muse

**Comment by Clockwork-Muse** [comment]
@tarekgh - okay, clearly, I have no idea what those strings are supposed to be.   Do you know?

**Comment by tarekgh** [comment]
@Clockwork-Muse I'll try to take a look tomorrow on that. thanks.

**Comment by Clockwork-Muse** [comment]
@tarekgh - tracked down why OSPlatform.Create doesn't work; neither Ubuntu nor OpenSUSE are listed in [this file](https://github.com/dotnet/corefx/blob/bffef76f6af208e2042a2f27bc081ee908bb390b/src/Native/Unix/configure.cmake), which is how the system decides what the current platform is.
So, what's the plan here?  Go back to how tests were?  (problematic, because it means we essentially have no test on Linux).  Add entries to that file (and build scripts)?  Or  add something to RuntimeInformation to get/compare distro name?

**Comment by tarekgh** [comment]
@Clockwork-Muse I don't think we need to change anything in the file configure.cmake. PAL_UNIX_NAME for Ubuntu (and I think for OpenSUSE) will be defined as Linux. what we need to so is to create a version of the method similar to IsDistroAndVersion something like:

```
        private static bool IsDistro(string distroId)
        {
            if (RuntimeInformation.IsOSPlatform(OSPlatform.Linux))
            {
                IdVersionPair v = ParseOsReleaseFile();
                if (v.Id == distroId)
                {
                    return true;
                }
            }
            return false;
        }
```

and then define 

```
 public static bool IsUbuntu { get; } = IsDistro("ubuntu");
```

**Comment by stephentoub** [comment]
I'm going to close this PR, since we're obviously not going to merge the revert of the revert that's broken.  @Clockwork-Muse, please feel free to open one with your fixed changes.

**Pull request closed without merging**
