### PR TITLE
Unify the two definitions of WinHttpException.

### LINKED ISSUE #2542: Unify System.Net.WebSockets.Client's WinHttpException with System.Net.Http's WinHttpException.

### PR DESCRIPTION
**Pull request by pgavlin**
Fixes #2542.

### CODE REVIEW

**Comment by pgavlin** [comment]
@davidsh PTAL

**Comment by davidsh** [comment]
LGTM

But this will break the TFS build in ProjectK. So, as soon as this is merged and it mirrors in, the TFS changes need to be done asap.

**Comment by stephentoub** [comment]
Compilation error:
```
d:\j\workspace\dotnet_corefx_windows_debug_prtest\src\Common\src\System\Net\Http\WinHttpException.cs(33,44): error CS0117: 'Interop.mincore' does not contain a definition for 'HRESULT_FROM_WIN32' [d:\j\workspace\dotnet_corefx_windows_debug_prtest\src\System.Net.Http.WinHttpHandler\src\System.Net.Http.WinHttpHandler.csproj]
```

**Comment by pgavlin** [comment]
@dotnet-bot test this please

**Comment by stephentoub** [comment]
LGTM

**Pull request merged**
