### PR TITLE
Overhaul TPL Dataflow tests

### PR DESCRIPTION
**Pull request by stephentoub**
This overhauls the System.Threading.Tasks.Dataflow test suite, rewriting most of the tests while retaining pieces here and there that made sense.  

A large portion of the tests were marked as OuterLoop because they involved long and flaky timeouts, were unreliable, etc.  After the rewrite, the vast majority of tests are inner loop, ~250 [Fact]s instead of ~40 (the suite previously rolled a bunch of tests into a single [Fact], tracking their success in a local Boolean), with only a handful remaining as [OuterLoop].  I've not scrubbed through the ConcurrentTests.cs and HardeningTests.cs files, which are still all outer loop and should be reviewed and updated in the future.

With this change, product source code coverage via inner inner loop tests jumps from ~60% to ~90%, while also reducing LOC by ~2000 lines in the tests.  Further, on my machine the inner loop tests now currently run in ~3 seconds, and with https://github.com/FiveTimesTheFun/xunit/pull/1 applied in the build tools, they run in < 1 second.

I also made two very minor tweaks to the product source, deleting a type and a member that were dead code.

### CODE REVIEW

**Comment by mmitche** [comment]
@dotnet-bot test this please

**Comment by stephentoub** [comment]
(As I haven't seen any feedback on the PR yet, I took some more time to boost the block code coverage a bit further, now at ~92%,  Most of what remains are more difficult to reach error paths or paths that are only reachable due to contention.)

**Comment by stephentoub** [comment]
@AlfredoMS, @nguerrera, @Priya91, or someone else... could you review this? Thanks!

**Comment by nguerrera** [comment]
Looks good to me, but can you send this through v1.0 so that we have better coverage there too?

**Comment by stephentoub** [comment]
Thanks, Nick.  Will close and reopen to merge into v1 instead.

**Pull request closed without merging**
