### PR TITLE
Add four new Linux RIDs & OSX 10.12

### PR DESCRIPTION
**Pull request by mellinoe**
* Linux Mint 18: Binary compatible with Ubuntu 16.04

The following RIDs will need additional work to enable platform-specific
packages to be produced for them:

* Ubuntu 16.10
* Fedora 24
* openSUSE 42.1

@livarcocc , @ericstj , @ellismg

### CODE REVIEW

**Comment by mellinoe** [comment]
In addition to the Linux distros, I also added osx.10.12 ("macOS Sierra") to the graph.

**Comment by ericstj** [comment]
LGTM.  /cc @gkhanna79 @schellap

**Comment by ellismg** [comment]
LGTM as well.

**Comment by gkhanna79** [comment]
@ericstj To confirm, we need to generate nuget packages for these RIDs across CoreCLR/CoreFX/Core-setup repos, correct?

**Comment by ericstj** [comment]
I think @mellinoe's intent is that they are treated as binary-compatible with existing RIDs so we don't need to cross compile.  For standalone apps folks can simply publish with these RIDs and it will work.  We did have some concern over whether or not the host would honor these RIDs in portable apps.  I'll open an issue in the core-setup repo with that question.  https://github.com/dotnet/core-setup/issues/229

**Comment by ericstj** [comment]
@mellinoe was it intentional that you didn't import the previous version of these when adding the RIDs?

**Comment by mellinoe** [comment]
@ericstj Do you mean, for example, importing openSUSE 13.2 from openSUSE 42.1? We don't do those imports across major versions for Linux distros.

**Comment by ericstj** [comment]
That's one example, also Ubuntu16.10 was added and didn't import from Ubuntu16.04 which isn't across a major version.

I'm trying to codify the versioning policy for these, which is why I'm looking at cases that have discrepancies.

**Comment by mellinoe** [comment]
To me, it still counts as a major version change -- Ubuntu version numbers are dates, and I don't think there's any guarantee that binaries will be portable across the versions. All these Linux distros have their own semantics for versioning, though, so it is tricky...

**Comment by ericstj** [comment]
We don't need to represent 100% binary compatibility in the RID graph we just need to represent the potential of reuse.  Even if we treat them as compatible folks can still cross-compile by version if they are not (in their case).  I think its better to have simpler rules that people can understand rather than making ad-hoc associations (as is permitted by the current runtime.json format).  See https://github.com/ericstj/corefx/commit/eeccb107b01f332448fc7bb6b6493e771173ab52#commitcomment-24438653

That said I think I'm identifying the expected policy for these is no-version importing, I'll model that for now but also model version importing (since that's required for Windows, OSX, and other linux distros like RHEL).

**Pull request merged**
