### PR TITLE
Change non-existent package dependencies to actual versions

### PR DESCRIPTION
**Pull request by dagood**
Fixes https://github.com/dotnet/corefx/issues/7902: a dependency version that doesn't exist makes NuGet search for a best match, so it tries to examine corrupted cache entries and fail restore. This change makes them exact matches which results in no searching, so the invalid cache entries aren't accessed.

/cc @ericstj @mellinoe @Priya91

### CODE REVIEW

**Comment by ericstj** [comment]
LGTM, we'll need to do the same for the next package upgrade since ComponentModel.Primitives and TypeConverter just went to 4.1.

**Comment by ericstj** [comment]
Will conflict with https://github.com/dotnet/corefx/pull/7919

**Comment by mellinoe** [comment]
LGTM

**Comment by mellinoe** [comment]
> Will conflict with #7919

We should probably just get this one in first. That one needs to be rebased and can be auto-generated again anyways.

**Comment by ericstj** [comment]
> That one needs to be rebased and can be auto-generated again anyways.

And the autogenerated change will reintroduce this same bug due to the change in package versions that happened yesterday. https://github.com/dotnet/corefx/commit/2c770515f041be7d23382a10778ef6f3a7b875d7

**Comment by Priya91** [comment]
LGTM!

**Comment by dagood** [comment]
Thanks, merging when CI goes through. @ericstj Yeah, I think that's the best way to handle it.

**Comment by dagood** [comment]
Error on the [OSX Release build](http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/master/job/osx_release_prtest/28/):

```
Tools are already initialized
  [14:24:51.24] Restoring all packages...
  /tmp/tmp62f36ecd1afa49f8a8396d696921c22e.exec.cmd: line 3:  4667 Segmentation fault: 11  "/Users/dotnet-bot/j/workspace/dotnet_corefx/master/osx_release_prtest/Tools/dotnetcli/dotnet" restore --packages "/Users/dotnet-bot/j/workspace/dotnet_corefx/master/osx_release_prtest/packages" --source https://dotnet.myget.org/F/dotnet-core/api/v3/index.json --source https://www.nuget.org/api/v2/ --infer-runtimes "/Users/dotnet-bot/j/workspace/dotnet_corefx/master/osx_release_prtest/src" "/Users/dotnet-bot/j/workspace/dotnet_corefx/master/osx_release_prtest/pkg"
  [14:28:23.61] Restoring all packages...Done.
```
And then a ton of `The type or namespace name 'System' could not be found` errors. It seems odd for this change to be able to cause something like that... any idea what this is or how to debug it?

**Comment by mellinoe** [comment]
> And then a ton of The type or namespace name 'System' could not be found errors.

I'm sure this is just because restore crashed, so there's no lockfiles.

> It seems odd for this change to be able to cause something like that... any idea what this is or how to debug it?

We haven't actually gotten a clean OSX run using `build.sh` since at least this Saturday (I'm not sure I can see the history past that for the outer-loop runs), so there may be other issues lurking around in the build. Since the debug build passed, this might be a one-off error, but it might warrant investigation regardless.

**Comment by ericstj** [comment]
@dotnet-bot test  Innerloop OSX Release Build and Test 

The failure being hit now could just be another symptom of what's causing failures on Mac.  If we were occasionally hitting seg fault, that would leave behind the corrupt cache files.  There could be some root issue that's causing the seg fault.  One thing to try might be to update CLI version.  We're quite a ways behind and I know fixes have been taken to the runtime.

The corrupt cache files is a problem here that needs to be tracked as well.  Davis, can you file a bug on that?  I suppose it could happen if a previous restore halts and leaves those behind.  NuGet should be resilient to the corrupt files.

**Comment by dagood** [comment]
Hmm. I think I'll merge this and make a new issue for the restore segfault. (I'm not able to repro on my mac with `./build.sh managed release`.) Thanks!

**Comment by ericstj** [comment]
Thanks for fixing this Davis!

**Comment by dagood** [comment]
Sure thing! I'm filing the segfault issue now.

**Comment by dagood** [comment]
Created https://github.com/dotnet/corefx/issues/7952

**Pull request merged**
