### PR TITLE
Update buildtools version to 00307.07

### PR DESCRIPTION
**Pull request by AlexGhiondea**
This enables a few more analyzers to run and also creates a way to
optimize code based on training scenarios.

### CODE REVIEW

**Comment by pallavit** [comment]
Interesting. These were exactly the errors I was seeing on my machine earlier when I had pinged. Looking at the log it looks like the pinvoke analyzer is not getting disabled for Linux builds. However the targets file seem to be adding the config file.

**Comment by AlexGhiondea** [comment]
This might be a race condition of some sort. I am not able to get this to repro locally.

**Comment by pallavit** [comment]
I can repro it on my machine. One interesting thing is that in case of failure, it does not disable the analyzer for any of the conditions, which makes sense since s_disabledAnalyzer is static and protected by lock. Could this be a race between when the GenerateAnalyzerConfigFile target has written to the file and when the analyzer reads it?

**Comment by stephentoub** [comment]
https://github.com/dotnet/corefx/pull/7588 appears to be upgrading to a newer buildtools
cc: @joperezr

**Comment by AlexGhiondea** [comment]
@stephentoub this is the latest version. I believe there is some state being cached by the analyzers leading to this break. I am getting ready an updated buildtools package that should solve this.

**Comment by AlexGhiondea** [comment]
The next package for buildtools should have this fix https://github.com/dotnet/buildtools/pull/623

**Comment by AlexGhiondea** [comment]
@dotnet-bot please test Innerloop OSX Debug Build and Test

**Pull request merged**
