### PR TITLE
Adding tests for the last 2 issues noted in coreclr#2185

### PR DESCRIPTION
**Pull request by eerhardt**
New tests for the last 2 issues logged in https://github.com/dotnet/coreclr/issues/2185.

@tarekgh @jskeet

Note: This can't be merged until a CoreCLR with the fix in https://github.com/dotnet/coreclr/pull/2685 is merged into CoreFX.

### CODE REVIEW

**Comment by stephentoub** [comment]
LGTM

**Comment by tarekgh** [comment]
LGTM. Thanks :-) I assume you'll merge this after merging the coreclr change.

**Comment by stephentoub** [comment]
@dotnet-bot test this please

**Comment by stephentoub** [comment]
Test Windows_NT Release Build and Test please

**Comment by stephentoub** [comment]
Test Innerloop Windows_NT Release Build and Test please

**Pull request merged**
