### PR TITLE
Remove the stubs for ResourceManager from TypeConverter.

### PR DESCRIPTION
**Pull request by AlexGhiondea**
Introduced MainAssembly on ResourceManager and implemented GetNeutralResourcesLanguage on ResourceManager.

### CODE REVIEW

**Comment by stephentoub** [comment]
@dotnet-bot Test Innerloop Ubuntu14.04 Debug Build and Test please (build timeout). FYI @adityamandaleeka and @mmitche

**Comment by tarekgh** [comment]
LGTM

**Comment by tarekgh** [comment]
CC @ramarag

**Comment by AlexGhiondea** [comment]
@dotnet-bot please test Innerloop CentOS7.1 Debug Build and Test  (machine issue)

**Comment by weshaggard** [comment]
@stephentoub @AlexGhiondea I think this PR conflicted with @stephentoub clean-up PR https://github.com/dotnet/corefx/pull/12621. As this relied on the ProjectReferences from TypeConverter to ResourceManager but it was removed with the clean-up PR. So master is broken right now.

**Comment by weshaggard** [comment]
I've submitted PR https://github.com/dotnet/corefx/pull/12651 to add the P2P back for now.

**Comment by stephentoub** [comment]
Thanks, Wes.

**Comment by AlexGhiondea** [comment]
Thanks @weshaggard

**Pull request merged**
