### PR TITLE
Remove  Assert.True(weakSwitch.IsAlive); from PruneTest() in SwitchClassTests.cs under System.Diagnostics.TraceSourceTests

### PR DESCRIPTION
**Pull request by Jiayili1**
Remove  Assert.True(weakSwitch.IsAlive); from PruneTest() in SwitchClassTests.cs under System.Diagnostics.TraceSourceTests

File: src\System.Diagnostics.TraceSource\tests\SwitchClassTests.cs
Method: PruneTest()

### CODE REVIEW

**Comment by Jiayili1** [comment]
@Priya91

**Comment by Jiayili1** [comment]
https://github.com/dotnet/corefx/issues/17300

**Comment by danmosemsft** [comment]
@Jiayili1 please have another go at rebasing. When you are done the only diff that should show up here in the PR when you look at it in github is the one line you are changing.

**Comment by Jiayili1** [comment]
@danmosemsft I met some problem when merging confilts, I will close this PR and create a new one.

**Pull request closed without merging**
