### PR TITLE
Add msbuild.log to archived outerloop jobs.

### LINKED ISSUE #9278: We should archive msbuild.* even on failed CI jobs
Today we only archive msbuild log files if the job completes successfully, but the logs have value in cases where the job fails as well.

### PR DESCRIPTION
**Pull request by Priya91**
Add msbuild.log archival even if build has failed.

cc @mmitche 

fixes #9278

### CODE REVIEW

**Comment by Priya91** [comment]
@dotnet-bot test ci please

**Comment by mmitche** [comment]
I think in this case the subsquent calls to archival will overwrite the previous settings (which is why we built up a list before).  As far as I know, today there isn't a way to archive X and Y only if passed, and Z unconditionally.

**Comment by Priya91** [comment]
@mmitche Set the donotfailifnothingarchived flag to true, and try to archive even if build is unsuccessful is enabled..

**Comment by Priya91** [comment]
@dotnet-bot test ci please

**Comment by mmitche** [comment]
I think that looks right now.

**Pull request merged**
