### PR TITLE
Fix writer depth issue on large stream async (#39417)

### PR DESCRIPTION
**Pull request by wtgodbe**
Fixes https://github.com/dotnet/corefx/issues/39413 for preview7. 

Port of https://github.com/dotnet/corefx/pull/39417

CC @steveharter @pranavkm @ericstj @mmitche

### CODE REVIEW

**Comment by wtgodbe** [comment]
> ##[error].packages\microsoft.net.compilers.toolset\3.3.0-beta1-19327-03\tasks\netcoreapp2.1\Microsoft.CSharp.Core.targets(59,5): error : Internal CLR error. (0x80131506)
D:\a\1\s\.packages\microsoft.net.compilers.toolset\3.3.0-beta1-19327-03\tasks\netcoreapp2.1\Microsoft.CSharp.Core.targets(59,5): error :    at Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.LanguageParser.ParseAttributes(Microsoft.CodeAnalysis.Syntax.InternalSyntax.SeparatedSyntaxListBuilder`1<Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.AttributeSyntax>) [D:\a\1\s\src\System.Globalization.Calendars\src\System.Globalization.Calendars.csproj]
##[error].packages\microsoft.net.compilers.toolset\3.3.0-beta1-19327-03\tasks\netcoreapp2.1\Microsoft.CSharp.Core.targets(59,5): error :    at Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.LanguageParser.ParseAttributes(Microsoft.CodeAnalysis.Syntax.InternalSyntax.SeparatedSyntaxListBuilder`1<Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.AttributeSyntax>)
D:\a\1\s\.packages\microsoft.net.compilers.toolset\3.3.0-beta1-19327-03\tasks\netcoreapp2.1\Microsoft.CSharp.Core.targets(59,5): error :    at Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.LanguageParser.ParseAttributeDeclaration() [D:\a\1\s\src\System.Globalization.Calendars\src\System.Globalization.Calendars.csproj]
##[error].packages\microsoft.net.compilers.toolset\3.3.0-beta1-19327-03\tasks\netcoreapp2.1\Microsoft.CSharp.Core.targets(59,5): error :    at Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.LanguageParser.ParseAttributeDeclaration()
D:\a\1\s\.packages\microsoft.net.compilers.toolset\3.3.0-beta1-19327-03\tasks\netcoreapp2.1\Microsoft.CSharp.Core.targets(59,5): error :    at Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.LanguageParser.ParseNamespaceBody(Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.SyntaxToken ByRef, NamespaceBodyBuilder ByRef, Microsoft.CodeAnalysis.Syntax.InternalSyntax.SyntaxListBuilder ByRef, Microsoft.CodeAnalysis.CSharp.SyntaxKind) [D:\a\1\s\src\System.Globalization.Calendars\src\System.Globalization.Calendars.csproj]
##[error].packages\microsoft.net.compilers.toolset\3.3.0-beta1-19327-03\tasks\netcoreapp2.1\Microsoft.CSharp.Core.targets(59,5): error :    at Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.LanguageParser.ParseNamespaceBody(Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.SyntaxToken ByRef, NamespaceBodyBuilder ByRef, Microsoft.CodeAnalysis.Syntax.InternalSyntax.SyntaxListBuilder ByRef, Microsoft.CodeAnalysis.CSharp.SyntaxKind)
D:\a\1\s\.packages\microsoft.net.compilers.toolset\3.3.0-beta1-19327-03\tasks\netcoreapp2.1\Microsoft.CSharp.Core.targets(59,5): error :    at Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.LanguageParser.ParseCompilationUnitCore() [D:\a\1\s\src\System.Globalization.Calendars\src\System.Globalization.Calendars.csproj]
##[error].packages\microsoft.net.compilers.toolset\3.3.0-beta1-19327-03\tasks\netcoreapp2.1\Microsoft.CSharp.Core.targets(59,5): error :    at Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.LanguageParser.ParseCompilationUnitCore()
D:\a\1\s\.packages\microsoft.net.compilers.toolset\3.3.0-beta1-19327-03\tasks\netcoreapp2.1\Microsoft.CSharp.Core.targets(59,5): error :    at Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.LanguageParser.ParseWithStackGuard[[System.__Canon, System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]](System.Func`1<System.__Canon>, System.Func`1<System.__Canon>) [D:\a\1\s\src\System.Globalization.Calendars\src\System.Globalization.Calendars.csproj]
##[error].packages\microsoft.net.compilers.toolset\3.3.0-beta1-19327-03\tasks\netcoreapp2.1\Microsoft.CSharp.Core.targets(59,5): error :    at Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.LanguageParser.ParseWithStackGuard[[System.__Canon, System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]](System.Func`1<System.__Canon>, System.Func`1<System.__Canon>)
D:\a\1\s\.packages\microsoft.net.compilers.toolset\3.3.0-beta1-19327-03\tasks\netcoreapp2.1\Microsoft.CSharp.Core.targets(59,5): error :    at Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.LanguageParser.ParseCompilationUnit() [D:\a\1\s\src\System.Globalization.Calendars\src\System.Globalization.Calendars.csproj]
##[error].packages\microsoft.net.compilers.toolset\3.3.0-beta1-19327-03\tasks\netcoreapp2.1\Microsoft.CSharp.Core.targets(59,5): error :    at Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.LanguageParser.ParseCompilationUnit()
D:\a\1\s\.packages\microsoft.net.compilers.toolset\3.3.0-beta1-19327-03\tasks\netcoreapp2.1\Microsoft.CSharp.Core.targets(59,5): error :    at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxTree.ParseText(Microsoft.CodeAnalysis.Text.SourceText, Microsoft.CodeAnalysis.CSharp.CSharpParseOptions, System.String, System.Collections.Immutable.ImmutableDictionary`2<System.String,Microsoft.CodeAnalysis.ReportDiagnostic>, System.Threading.CancellationToken) [D:\a\1\s\src\System.Globalization.Calendars\src\System.Globalization.Calendars.csproj]
##[error].packages\microsoft.net.compilers.toolset\3.3.0-beta1-19327-03\tasks\netcoreapp2.1\Microsoft.CSharp.Core.targets(59,5): error :    at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxTree.ParseText(Microsoft.CodeAnalysis.Text.SourceText, Microsoft.CodeAnalysis.CSharp.CSharpParseOptions, System.String, System.Collections.Immutable.ImmutableDictionary`2<System.String,Microsoft.CodeAnalysis.ReportDiagnostic>, System.Threading.CancellationToken)
D:\a\1\s\.packages\microsoft.net.compilers.toolset\3.3.0-beta1-19327-03\tasks\netcoreapp2.1\Microsoft.CSharp.Core.targets(59,5): error :    at Microsoft.CodeAnalysis.CSharp.SyntaxFactory.ParseSyntaxTree(Microsoft.CodeAnalysis.Text.SourceText, Microsoft.CodeAnalysis.ParseOptions, System.String, System.Collections.Immutable.ImmutableDictionary`2<System.String,Microsoft.CodeAnalysis.ReportDiagnostic>, System.Threading.CancellationToken) [D:\a\1\s\src\System.Globalization.Calendars\src\System.Globalization.Calendars.csproj]
##[error].packages\microsoft.net.compilers.toolset\3.3.0-beta1-19327-03\tasks\netcoreapp2.1\Microsoft.CSharp.Core.targets(59,5): error :    at Microsoft.CodeAnalysis.CSharp.SyntaxFactory.ParseSyntaxTree(Microsoft.CodeAnalysis.Text.SourceText, Microsoft.CodeAnalysis.ParseOptions, System.String, System.Collections.Immutable.ImmutableDictionary`2<System.String,Microsoft.CodeAnalysis.ReportDiagnostic>, System.Threading.CancellationToken)
D:\a\1\s\.packages\microsoft.net.compilers.toolset\3.3.0-beta1-19327-03\tasks\netcoreapp2.1\Microsoft.CSharp.Core.targets(59,5): error :    at Microsoft.CodeAnalysis.CSharp.CSharpCompiler.ParseFile(Microsoft.CodeAnalysis.CSharp.CSharpParseOptions, Microsoft.CodeAnalysis.CSharp.CSharpParseOptions, Microsoft.CodeAnalysis.Text.SourceText, Microsoft.CodeAnalysis.CommandLineSourceFile, System.Collections.Immutable.ImmutableDictionary`2<System.String,Microsoft.CodeAnalysis.ReportDiagnostic>) [D:\a\1\s\src\System.Globalization.Calendars\src\System.Globalization.Calendars.csproj]
##[error].packages\microsoft.net.compilers.toolset\3.3.0-beta1-19327-03\tasks\netcoreapp2.1\Microsoft.CSharp.Core.targets(59,5): error :    at Microsoft.CodeAnalysis.CSharp.CSharpCompiler.ParseFile(Microsoft.CodeAnalysis.CSharp.CSharpParseOptions, Microsoft.CodeAnalysis.CSharp.CSharpParseOptions, Microsoft.CodeAnalysis.Text.SourceText, Microsoft.CodeAnalysis.CommandLineSourceFile, System.Collections.Immutable.ImmutableDictionary`2<System.String,Microsoft.CodeAnalysis.ReportDiagnostic>)
D:\a\1\s\.packages\microsoft.net.compilers.toolset\3.3.0-beta1-19327-03\tasks\netcoreapp2.1\Microsoft.CSharp.Core.targets(59,5): error :    at Microsoft.CodeAnalysis.CSharp.CSharpCompiler.ParseFile(Microsoft.CodeAnalysis.CSharp.CSharpParseOptions, Microsoft.CodeAnalysis.CSharp.CSharpParseOptions, System.Collections.Immutable.ImmutableDictionary`2<System.String,Microsoft.CodeAnalysis.ReportDiagnostic>, Boolean ByRef, Microsoft.CodeAnalysis.CommandLineSourceFile, Microsoft.CodeAnalysis.DiagnosticBag, System.String ByRef) [D:\a\1\s\src\System.Globalization.Calendars\src\System.Globalization.Calendars.csproj]
##[error].packages\microsoft.net.compilers.toolset\3.3.0-beta1-19327-03\tasks\netcoreapp2.1\Microsoft.CSharp.Core.targets(59,5): error :    at Microsoft.CodeAnalysis.CSharp.CSharpCompiler.ParseFile(Microsoft.CodeAnalysis.CSharp.CSharpParseOptions, Microsoft.CodeAnalysis.CSharp.CSharpParseOptions, System.Collections.Immutable.ImmutableDictionary`2<System.String,Microsoft.CodeAnalysis.ReportDiagnostic>, Boolean ByRef, Microsoft.CodeAnalysis.CommandLineSourceFile, Microsoft.CodeAnalysis.DiagnosticBag, System.String ByRef)
D:\a\1\s\.packages\microsoft.net.compilers.toolset\3.3.0-beta1-19327-03\tasks\netcoreapp2.1\Microsoft.CSharp.Core.targets(59,5): error :    at Microsoft.CodeAnalysis.CSharp.CSharpCompiler+<>c__DisplayClass8_0.<CreateCompilation>b__0(Int32) [D:\a\1\s\src\System.Globalization.Calendars\src\System.Globalization.Calendars.csproj]
##[error].packages\microsoft.net.compilers.toolset\3.3.0-beta1-19327-03\tasks\netcoreapp2.1\Microsoft.CSharp.Core.targets(59,5): error :    at Microsoft.CodeAnalysis.CSharp.CSharpCompiler+<>c__DisplayClass8_0.<CreateCompilation>b__0(Int32)
D:\a\1\s\.packages\microsoft.net.compilers.toolset\3.3.0-beta1-19327-03\tasks\netcoreapp2.1\Microsoft.CSharp.Core.targets(59,5): error :    at Roslyn.Utilities.UICultureUtilities+<>c__DisplayClass6_0`1[[System.Int32, System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].<WithCurrentUICulture>b__0(Int32) [D:\a\1\s\src\System.Globalization.Calendars\src\System.Globalization.Calendars.csproj]
##[error].packages\microsoft.net.compilers.toolset\3.3.0-beta1-19327-03\tasks\netcoreapp2.1\Microsoft.CSharp.Core.targets(59,5): error :    at Roslyn.Utilities.UICultureUtilities+<>c__DisplayClass6_0`1[[System.Int32, System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].<WithCurrentUICulture>b__0(Int32)
D:\a\1\s\.packages\microsoft.net.compilers.toolset\3.3.0-beta1-19327-03\tasks\netcoreapp2.1\Microsoft.CSharp.Core.targets(59,5): error :    at System.Threading.Tasks.Parallel+<>c__DisplayClass19_0`1[[System.__Canon, System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].<ForWorker>b__1(System.Threading.Tasks.RangeWorker ByRef, Int32, Boolean ByRef) [D:\a\1\s\src\System.Globalization.Calendars\src\System.Globalization.Calendars.csproj]
##[error].packages\microsoft.net.compilers.toolset\3.3.0-beta1-19327-03\tasks\netcoreapp2.1\Microsoft.CSharp.Core.targets(59,5): error :    at System.Threading.Tasks.Parallel+<>c__DisplayClass19_0`1[[System.__Canon, System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].<ForWorker>b__1(System.Threading.Tasks.RangeWorker ByRef, Int32, Boolean ByRef)
D:\a\1\s\.packages\microsoft.net.compilers.toolset\3.3.0-beta1-19327-03\tasks\netcoreapp2.1\Microsoft.CSharp.Core.targets(59,5): error :    at System.Threading.Tasks.TaskReplicator+Replica`1[[System.Threading.Tasks.RangeWorker, System.Threading.Tasks.Parallel, Version=4.0.3.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a]].ExecuteAction(Boolean ByRef) [D:\a\1\s\src\System.Globalization.Calendars\src\System.Globalization.Calendars.csproj]
##[error].packages\microsoft.net.compilers.toolset\3.3.0-beta1-19327-03\tasks\netcoreapp2.1\Microsoft.CSharp.Core.targets(59,5): error :    at System.Threading.Tasks.TaskReplicator+Replica`1[[System.Threading.Tasks.RangeWorker, System.Threading.Tasks.Parallel, Version=4.0.3.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a]].ExecuteAction(Boolean ByRef)
D:\a\1\s\.packages\microsoft.net.compilers.toolset\3.3.0-beta1-19327-03\tasks\netcoreapp2.1\Microsoft.CSharp.Core.targets(59,5): error :    at System.Threading.Tasks.TaskReplicator+Replica.Execute() [D:\a\1\s\src\System.Globalization.Calendars\src\System.Globalization.Calendars.csproj]
##[error].packages\microsoft.net.compilers.toolset\3.3.0-beta1-19327-03\tasks\netcoreapp2.1\Microsoft.CSharp.Core.targets(59,5): error :    at System.Threading.Tasks.TaskReplicator+Replica.Execute()
D:\a\1\s\.packages\microsoft.net.compilers.toolset\3.3.0-beta1-19327-03\tasks\netcoreapp2.1\Microsoft.CSharp.Core.targets(59,5): error :    at System.Threading.Tasks.TaskReplicator+Replica+<>c.<.ctor>b__4_0(System.Object) [D:\a\1\s\src\System.Globalization.Calendars\src\System.Globalization.Calendars.csproj]
##[error].packages\microsoft.net.compilers.toolset\3.3.0-beta1-19327-03\tasks\netcoreapp2.1\Microsoft.CSharp.Core.targets(59,5): error :    at System.Threading.Tasks.TaskReplicator+Replica+<>c.<.ctor>b__4_0(System.Object)
D:\a\1\s\.packages\microsoft.net.compilers.toolset\3.3.0-beta1-19327-03\tasks\netcoreapp2.1\Microsoft.CSharp.Core.targets(59,5): error :    at System.Threading.Tasks.Task.InnerInvoke() [D:\a\1\s\src\System.Globalization.Calendars\src\System.Globalization.Calendars.csproj]
##[error].packages\microsoft.net.compilers.toolset\3.3.0-beta1-19327-03\tasks\netcoreapp2.1\Microsoft.CSharp.Core.targets(59,5): error :    at System.Threading.Tasks.Task.InnerInvoke()
D:\a\1\s\.packages\microsoft.net.compilers.toolset\3.3.0-beta1-19327-03\tasks\netcoreapp2.1\Microsoft.CSharp.Core.targets(59,5): error :    at System.Threading.Tasks.Task+<>c.<.cctor>b__274_0(System.Object) [D:\a\1\s\src\System.Globalization.Calendars\src\System.Globalization.Calendars.csproj]
##[error].packages\microsoft.net.compilers.toolset\3.3.0-beta1-19327-03\tasks\netcoreapp2.1\Microsoft.CSharp.Core.targets(59,5): error :    at System.Threading.Tasks.Task+<>c.<.cctor>b__274_0(System.Object)
D:\a\1\s\.packages\microsoft.net.compilers.toolset\3.3.0-beta1-19327-03\tasks\netcoreapp2.1\Microsoft.CSharp.Core.targets(59,5): error :    at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(System.Threading.Thread, System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object) [D:\a\1\s\src\System.Globalization.Calendars\src\System.Globalization.Calendars.csproj]
##[error].packages\microsoft.net.compilers.toolset\3.3.0-beta1-19327-03\tasks\netcoreapp2.1\Microsoft.CSharp.Core.targets(59,5): error :    at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(System.Threading.Thread, System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
D:\a\1\s\.packages\microsoft.net.compilers.toolset\3.3.0-beta1-19327-03\tasks\netcoreapp2.1\Microsoft.CSharp.Core.targets(59,5): error :    at System.Threading.Tasks.Task.ExecuteWithThreadLocal(System.Threading.Tasks.Task ByRef, System.Threading.Thread) [D:\a\1\s\src\System.Globalization.Calendars\src\System.Globalization.Calendars.csproj]
##[error].packages\microsoft.net.compilers.toolset\3.3.0-beta1-19327-03\tasks\netcoreapp2.1\Microsoft.CSharp.Core.targets(59,5): error :    at System.Threading.Tasks.Task.ExecuteWithThreadLocal(System.Threading.Tasks.Task ByRef, System.Threading.Thread)
D:\a\1\s\.packages\microsoft.net.compilers.toolset\3.3.0-beta1-19327-03\tasks\netcoreapp2.1\Microsoft.CSharp.Core.targets(59,5): error :    at System.Threading.Tasks.Task.ExecuteEntryUnsafe(System.Threading.Thread) [D:\a\1\s\src\System.Globalization.Calendars\src\System.Globalization.Calendars.csproj]
##[error].packages\microsoft.net.compilers.toolset\3.3.0-beta1-19327-03\tasks\netcoreapp2.1\Microsoft.CSharp.Core.targets(59,5): error :    at System.Threading.Tasks.Task.ExecuteEntryUnsafe(System.Threading.Thread)
D:\a\1\s\.packages\microsoft.net.compilers.toolset\3.3.0-beta1-19327-03\tasks\netcoreapp2.1\Microsoft.CSharp.Core.targets(59,5): error :    at System.Threading.Tasks.Task.ExecuteFromThreadPool(System.Threading.Thread) [D:\a\1\s\src\System.Globalization.Calendars\src\System.Globalization.Calendars.csproj]
##[error].packages\microsoft.net.compilers.toolset\3.3.0-beta1-19327-03\tasks\netcoreapp2.1\Microsoft.CSharp.Core.targets(59,5): error :    at System.Threading.Tasks.Task.ExecuteFromThreadPool(System.Threading.Thread)
D:\a\1\s\.packages\microsoft.net.compilers.toolset\3.3.0-beta1-19327-03\tasks\netcoreapp2.1\Microsoft.CSharp.Core.targets(59,5): error :    at System.Threading.ThreadPoolWorkQueue.Dispatch() [D:\a\1\s\src\System.Globalization.Calendars\src\System.Globalization.Calendars.csproj]
##[error].packages\microsoft.net.compilers.toolset\3.3.0-beta1-19327-03\tasks\netcoreapp2.1\Microsoft.CSharp.Core.targets(59,5): error :    at System.Threading.ThreadPoolWorkQueue.Dispatch()
D:\a\1\s\.packages\microsoft.net.compilers.toolset\3.3.0-beta1-19327-03\tasks\netcoreapp2.1\Microsoft.CSharp.Core.targets(59,5): error :    at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback() [D:\a\1\s\src\System.Globalization.Calendars\src\System.Globalization.Calendars.csproj]
##[error].packages\microsoft.net.compilers.toolset\3.3.0-beta1-19327-03\tasks\netcoreapp2.1\Microsoft.

**Comment by wtgodbe** [comment]
@ericstj looks like the compiler error you were concerned about a few weeks ago. Will retry when possible

**Comment by wtgodbe** [comment]
Mac failure is a flaky Sockets test

**Comment by wtgodbe** [comment]
CC @ViktorHofer @safern in case you guys were interested in this instance of the compiler error

**Comment by ViktorHofer** [comment]
@wtgodbe to fix that issue you want to update the dotnet version in global.json to the one that we use in master...

**Pull request merged**
