### PR TITLE
Add test project for common shared code.

### PR DESCRIPTION
**Pull request by JeremyKuhne**
Includes the shared code in the test assembly allowing writing of
unit tests against internals in shared code.

@weshaggard, @stephentoub 
This is a rough prototype of what I proposed in a comment thread with Stephen. It makes more sense to have tests living with the shared code I think. Including the sources also allows unit testing the internals.

### CODE REVIEW

**Comment by stephentoub** [comment]
@dotnet-bot test this please

**Comment by weshaggard** [comment]
Unless I'm missing something I don't actually see any tests in this project only the common source code itself. Is that part to come?

As for the general approach it is somewhat interesting if we feel we gain enough value from testing this in isolation. I always fear that we end up testing the wrong things while doing it this way because you aren't testing what the public APIs that use these is actually doing. What do you feel the value of this will be?

**Comment by JeremyKuhne** [comment]
It is there (https://github.com/dotnet/corefx/pull/2472/files#diff-a31c16d8200fd8634c6e257cfc7ead15).

I'm not suggesting that we don't test higher up the stack. Testing the blocks *first* at this level is easy to do thoroughly and accurately and quickly. (They're true Unit tests) They are also often separated from OS calls and other methods that make it difficult to get at the underlying complexity.

In the shared code case it is extra important as these can be thought of as another virtual assembly of sorts. It is much easier to miss impacts of changes to the shared code when the consumption isn't as front and center.

You can do orders of magnitude more unit tests that don't touch IO / external components (which many would argue is the definition of a unit test). The more we get at internals to do tests at a core logic level the better that we'll be covered with less time consumed. It also gives us the ability to find breaks quicker if we start doing tests in stages.

**Comment by davidsh** [comment]
cc: @CIPop @SidharthNabar 

+1 on this UnitTest approach.  We do this as well for System.Net networking components.

**Pull request merged**
