### PR TITLE
PropertyDescriptor - MemberDescriptor.Attributes (iteration 2) 

### LINKED ISSUE #26600: PropertyDescriptor - MemberDescriptor.Attributes returns base attribute instead of ancestor's attribute
"prop.Description" returns "A" instead of "B"
```c#
static void Main(string[] args) {
    var prop = (DescriptionAttribute)TypeDescriptor.GetProperties(typeof(B))["Value"].Attributes[typeof(DescriptionAttribute)];
    Assert.Equal("B", prop.Description);
}
class A {
    [Description("A")]
    public virtual int Value { get; set; }
}
class B : A {
    [Description("B")]
    public override int Value { get; set; }
}
```

[EDIT] Add C# syntax highlighing & change code formatting by @karelz

### PR DESCRIPTION
**Pull request by k0st1x**
Fixes #26600
PropertyDescriptor - MemberDescriptor.Attributes returns base attribute instead of ancestor's attribute

### CODE REVIEW

**Comment by safern** [comment]
Cc: @stephentoub

**Comment by karelz** [comment]
BTW: You can add "Fixes #<number>" into top post to trigger GitHub auto-closing feature upon merge - see [details](https://help.github.com/articles/closing-issues-using-keywords/).

**Comment by k0st1x** [comment]
@karelz thank you for guiding me.
This PR was reviewed, it passed the auto tests.
Is this enough to accept the changes?

**Comment by karelz** [comment]
Area owners/experts (@safern @maryamariyan) will decide when to merge. Looks like @safern wanted another code review from @stephentoub

**Comment by k0st1x** [comment]
i very much count on that issue will be closed in 2.1 release.
@stephentoub what can I do to facilitate issue closing as soon as possible?

**Comment by karelz** [comment]
@k0st1x 2.1 has still some time to bake - few days is not going to make a difference. We do not need to rush it "ASAP".

**Pull request merged**
