### PR TITLE
Fix restore compatability errors on Ubuntu/OSX

### PR DESCRIPTION
**Pull request by dagood**
The combination of upgrading CLI and the .NETStandard rename caused compatibility errors on non-windows restore. To fix it I added a `netcore50` project.json fork and lifted System.Runtime 4.0.0 with the prerelease `Microsoft.NETCore.Platforms` package. (4.0.0 doesn't have Ubuntu compat.)

I haven't been able to validate this locally since package restore has been very slow. Adding the PR here for visibility and in case CI can get it done more quickly.

/cc @ericstj @joperezr @stephentoub

### CODE REVIEW

**Comment by ericstj** [comment]
LGTM

**Comment by stephentoub** [comment]
Lots of errors in System.Xml.XmlSerializer:
```
System.Xml.XmlSerializer.Forwards.cs(8,60): error CS0234: The type or namespace name 'IXmlSerializable' does not exist in the namespace 'System.Xml.Serialization' (are you missing an assembly reference?) [d:\j\workspace\windows_nt_de---06b7984d\src\System.Xml.XmlSerializer\src\System.Xml.XmlSerializer.csproj]
System.Xml.XmlSerializer.Forwards.cs(9,60): error CS0234: The type or namespace name 'XmlSchemaProviderAttribute' does not exist in the namespace 'System.Xml.Serialization' (are you missing an assembly reference?) [d:\j\workspace\windows_nt_de---06b7984d\src\System.Xml.XmlSerializer\src\System.Xml.XmlSerializer.csproj]
System\Xml\schema\XmlSchemaType.cs(6,14): error CS0234: The type or namespace name 'ComponentModel' does not exist in the namespace 'System' (are you missing an assembly reference?) [d:\j\workspace\windows_nt_de---06b7984d\src\System.Xml.XmlSerializer\src\System.Xml.XmlSerializer.csproj]
System\Xml\Extensions\ExtensionMethods.cs(10,14): error CS0234: The type or namespace name 'Linq' does not exist in the namespace 'System' (are you missing an assembly reference?) [d:\j\workspace\windows_nt_de---06b7984d\src\System.Xml.XmlSerializer\src\System.Xml.XmlSerializer.csproj]
System\Xml\Serialization\XmlAnyElementAttributes.cs(8,14): error CS0234: The type or namespace name 'ComponentModel' does not exist in the namespace 'System' (are you missing an assembly reference?) [d:\j\workspace\windows_nt_de---06b7984d\src\System.Xml.XmlSerializer\src\System.Xml.XmlSerializer.csproj]
System\Xml\Serialization\XmlArrayItemAttributes.cs(8,14): error CS0234: The type or namespace name 'ComponentModel' does not exist in the namespace 'System' (are you missing an assembly reference?) [d:\j\workspace\windows_nt_de---06b7984d\src\System.Xml.XmlSerializer\src\System.Xml.XmlSerializer.csproj]
System\Xml\Serialization\XmlAttributes.cs(8,14): error CS0234: The type or namespace name 'ComponentModel' does not exist in the namespace 'System' (are you missing an assembly reference?) [d:\j\workspace\windows_nt_de---06b7984d\src\System.Xml.XmlSerializer\src\System.Xml.XmlSerializer.csproj]
System\Xml\Serialization\XmlAttributes.cs(9,14): error CS0234: The type or namespace name 'Linq' does not exist in the namespace 'System' (are you missing an assembly reference?) [d:\j\workspace\windows_nt_de---06b7984d\src\System.Xml.XmlSerializer\src\System.Xml.XmlSerializer.csproj]
System\Xml\Serialization\XmlCustomFormatter.cs(10,14): error CS0234: The type or namespace name 'ComponentModel' does not exist in the namespace 'System' (are you missing an assembly reference?) [d:\j\workspace\windows_nt_de---06b7984d\src\System.Xml.XmlSerializer\src\System.Xml.XmlSerializer.csproj]
...
```

**Comment by dagood** [comment]
Thanks @stephentoub, I was just missing a redirect from the `netcore50aot` `TargetGroup` to use the `netcore50

**Comment by dagood** [comment]
The Ubuntu failure looks like a transient Jenkins error, failed to clone repo: http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/ubuntu_debug_tst_prtest/2322/console.

@dotnet-bot test Innerloop Ubuntu Debug Build and Test please

**Comment by joperezr** [comment]
@dotnet-bot test Innerloop Ubuntu Debug Build and Test

**Comment by stephentoub** [comment]
Test Innerloop Ubuntu Debug Build and Test please

**Pull request merged**
