### PR TITLE
Consolidate Interop calls for System.ServiceProcess.ServiceController

### PR DESCRIPTION
**Pull request by pallavit**

### CODE REVIEW

**Comment by pallavit** [comment]
@Maxwe11 Thanks for the feedback, I have incorporated the comments.

**Comment by pallavit** [comment]
@stephentoub Could you please take a look at this.

**Comment by stephentoub** [comment]
LGTM

**Comment by pallavit** [comment]
Thank you for the review. Squashing the commits before merging.

**Pull request merged**
