### PR TITLE
Sync Interop.GetCwd with coreclr

### PR DESCRIPTION
**Pull request by tmds**
Sync changes made in https://github.com/dotnet/coreclr/pull/15229

### CODE REVIEW

**Comment by eerhardt** [comment]
test Alpine.3.6 x64 Debug Build
test Packaging All Configurations x64 Debug Build

**Comment by janvorli** [comment]
@eerhardt it seems that with my latest fix, the build passes, but the CI fails aftger that with java.lang.NullPointerException: Cannot invoke method size() on null object. My guess is that it could be due to the fact that the tests are not being built.

**Comment by tmds** [comment]
@eerhardt can you please merge this?

**Comment by eerhardt** [comment]
test Alpine.3.6 x64 Debug Build

**Comment by eerhardt** [comment]
Sorry for the delay @tmds.  This had slipped off my radar.

Thanks for the contribution.

**Comment by tmds** [comment]
Thanks @eerhardt !

**Pull request merged**
