### PR TITLE
Add tests for ResourceManager on custom Assembly type.

### PR DESCRIPTION
**Pull request by filipnavara**
Unit tests for https://github.com/dotnet/coreclr/pull/21979. /cc @jkotas

### CODE REVIEW

**Comment by filipnavara** [comment]
Following discussion in dotnet/coreclr#21979 I started over. Now it's a unit test that ensures that custom assemblies cannot be passed to the `ResourceManager` constructor.

**Comment by filipnavara** [comment]
@dotnet-bot test Packaging All Configurations x64 Debug Build

**Comment by MarcoRossignoli** [comment]
AzurePipelines commands seems broken https://github.com/dotnet/corefx/pull/34747#issuecomment-458765351

**Comment by filipnavara** [comment]
@MarcoRossignoli Thanks, I am aware of the issue, but I kinda hoped it was fixed meanwhile :)

**Comment by filipnavara** [comment]
@safern Is there any (public) issue that tracks the state of Azure Pipelines triggers on GitHub?

**Comment by safern** [comment]
> @safern Is there any (public) issue that tracks the state of Azure Pipelines triggers on GitHub?

No, there was not one. I just opened: https://github.com/dotnet/corefx/issues/35121 -- we're supposed to get the fix by Friday or Monday according to their team.

**Comment by safern** [comment]
I just retried your build manually :smile:

**Pull request merged**
