### PR TITLE
Fix warnings causing FreeBSD build failure

### LINKED ISSUE #3289: FreeBSD shim build broken due to sign-conversion warning
While building the native shims on FreeBSD, I see the following warnings. These warnings do not appear on Linux.

```
/usr/home/jan/corefx/src/Native/System.Native/pal_mount.cpp:84:49: error: implicit conversion changes signedness: 'int64_t' (aka 'long') to 'unsigned long' [-Werror,-Wsign-conversion]
        mpi->AvailableFreeSpace = bsize * stats.f_bavail;
                                        ~ ~~~~~~^~~~~~~~
1 error generated.
--- System.Native/CMakeFiles/System.Native.dir/pal_mount.cpp.o ---
*** [System.Native/CMakeFiles/System.Native.dir/pal_mount.cpp.o] Error code 1

make[2]: stopped in /usr/home/jan/corefx/bin/obj/FreeBSD.x64.Debug/Native
/usr/home/jan/corefx/src/Native/System.Native/pal_process.cpp:246:23: error: implicit conversion changes signedness: 'uint64_t' (aka 'unsigned long') to 'rlim_t' (aka 'long') [-Werror,-Wsign-conversion]
    native.rlim_cur = ConvertFromManagedRLimitInfinityToPalIfNecessary(pal.CurrentLimit);
                    ~ ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/home/jan/corefx/src/Native/System.Native/pal_process.cpp:247:23: error: implicit conversion changes signedness: 'uint64_t' (aka 'unsigned long') to 'rlim_t' (aka 'long') [-Werror,-Wsign-conversion]
    native.rlim_max = ConvertFromManagedRLimitInfinityToPalIfNecessary(pal.MaximumLimit);
                    ~ ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/home/jan/corefx/src/Native/System.Native/pal_process.cpp:253:83: error: implicit conversion changes signedness: 'const rlim_t' (aka 'const long') to 'uint64_t' (aka 'unsigned long') [-Werror,-Wsign-conversion]
    pal.CurrentLimit = ConvertFromNativeRLimitInfinityToManagedIfNecessary(native.rlim_cur);
                       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ ~~~~~~~^~~~~~~~
/usr/home/jan/corefx/src/Native/System.Native/pal_process.cpp:254:83: error: implicit conversion changes signedness: 'const rlim_t' (aka 'const long') to 'uint64_t' (aka 'unsigned long') [-Werror,-Wsign-conversion]
    pal.MaximumLimit = ConvertFromNativeRLimitInfinityToManagedIfNecessary(native.rlim_max);
                       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ ~~~~~~~^~~~~~~~
4 errors generated.
```

### PR DESCRIPTION
**Pull request by nguerrera**
Fix #3289.

cc @janhenke Would you mind trying this patch on FreeBSD?

cc @sokket

### CODE REVIEW

**Comment by janhenke** [comment]
That fixes the warnings & the build for me on FreeBSD, thanks for the quick fix! LGTM

**Comment by stephentoub** [comment]
LGTM

**Comment by nguerrera** [comment]
Note minor changes since LGTMs

Since @stephentoub's: Fix typo s/a signed types/signed types/

Since @janhenke's:  Fixed boundary case where value == RLIM_T_MAX as platform could have e.g. RLIM_INFINITY = -1 and RLIM_T_MAX == INT64_MAX, in which case we should let INT64_MAX through.

**Comment by stephentoub** [comment]
> Note minor changes since LGTMs

WHAT?!  You dared fix a typo?!

Just kidding of course. :smile: Still LGTM.

**Comment by janhenke** [comment]
LGTM as well for me.

**Comment by nguerrera** [comment]
:)

**Comment by jasonwilliams200OK** [comment]
Thanks @nguerrera ! :+1: :tada:

**Pull request merged**
