### PR TITLE
Fix duplicated XDocumentExtensions

### PR DESCRIPTION
**Pull request by sepidehMS**
Fixes https://github.com/dotnet/corefx/issues/19552

cc: @krwq @ericstj @danmosemsft

### CODE REVIEW

**Comment by safern** [comment]
@dotnet-bot test Innerloop netfx Windows_NT Release x64 Build and Test (#19580)

**Comment by safern** [comment]
@dotnet-bot test Innerloop netfx Windows_NT Debug x64 Build and Test (#19580)

**Comment by safern** [comment]
@dotnet-bot test Innerloop netfx Windows_NT Debug x86 Build and Test (#19580)

**Comment by danmosemsft** [comment]
@dotnet-bot test Innerloop netfx Windows_NT Release x86 Build and Test (#19580)

**Comment by danmosemsft** [comment]
@dotnet-bot test Innerloop netfx Windows_NT Release x64 Build and Test (#19580)

**Comment by krwq** [comment]
@danmosemsft @ericstj @weshaggard do we still push to master or do we have some release branch yet?

**Comment by weshaggard** [comment]
>@danmosemsft @ericstj @weshaggard do we still push to master or do we have some release branch yet?

Still keep changes in master.

**Pull request merged**
