### PR TITLE
Numerics.Vectors tests improvents

### PR DESCRIPTION
**Pull request by Maxwe11**

### CODE REVIEW

**Comment by akoeplinger** [comment]
> Make all System.Numerics.Vectors test methods static 

Why? What problem does this solve?

**Comment by Maxwe11** [comment]
@akoeplinger without static xunit runner create object for each test

**Comment by akoeplinger** [comment]
@Maxwe11 yes, this is actually a good thing as it helps test isolation and was an explicit design goal of xunit: https://xunit.codeplex.com/wikipage?title=WhyDidWeBuildXunit

**Comment by Maxwe11** [comment]
@akoeplinger it's reasonable if tests use shared data or accessing resources but here isn't that case

**Comment by akoeplinger** [comment]
@Maxwe11 I think it's a general anti-pattern to use static unit test methods, so does this give any performance/etc. benefits that would make this worthwhile?

**Comment by stephentoub** [comment]
I agree with @akoeplinger on this; I don't see the value here in making these tests static.

**Comment by Maxwe11** [comment]
rebased

**Comment by stephentoub** [comment]
Thanks, @Maxwe11.  The test additions LGTM.

**Pull request merged**
