### PR TITLE
Add back Socket.Handle

### PR DESCRIPTION
**Pull request by ericeil**
Part of #11788.

@stephentoub @CIPop @davidsh

### CODE REVIEW

**Comment by ericeil** [comment]
@dotnet-bot Test Outerloop Windows_NT Debug please
@dotnet-bot Test Outerloop Ubuntu14.04 Debug please
@dotnet-bot Test Outerloop OSX Debug please

**Comment by stephentoub** [comment]
LGTM. Thanks.

Note that https://github.com/dotnet/corefx/issues/6807 is also about exposing Handle, so we can probably close that as well when this goes in.  However, we currently have one place in the code where we'd like to use Handle and are getting it via reflection:
https://github.com/dotnet/corefx/blob/d0dc5fc099946adc1035b34a8b1f6042eddb0c75/src/System.IO.Pipes/src/Microsoft/Win32/SafeHandles/SafePipeHandle.Unix.cs#L34
Before we close all issues related to this, we should fix that as well.

**Comment by ericeil** [comment]
Test failures are due to https://github.com/dotnet/corefx/issues/11803.  Not related to this change.

**Comment by ericeil** [comment]
> we currently have one place in the code where we'd like to use Handle and are getting it via reflection:

I filed #11807 to get that fixed.

**Pull request merged**
