### PR TITLE
[release/3.0] Re-add removed Packaging.props lines related to IntelliSense packages

### PR DESCRIPTION
**Pull request by wtgodbe**
cherry-picks https://github.com/dotnet/corefx/pull/39017 into release/3.0 for preview7.

CC @ericstj @ViktorHofer @carlossanlop

### CODE REVIEW

**Comment by wtgodbe** [comment]
Unrelated infra failure on Windows in `System.Security.Cryptography.X509Certificates.Tests`

**Comment by wtgodbe** [comment]
Tests have finished, reporting is being weird.

**Comment by ericstj** [comment]
Agreed that this failure is unrelated to your change, however it looks like that crytpo test crashed.  That might be a product bug to follow up on:
```
2019-06-28 17:35:59,685: INFO: executor(554): _execute_command: running %HELIX_CORRELATION_PAYLOAD%\scripts\6d93d14473a64406b7c128911d5b6191\execute.cmd in C:\dotnetbuild\work\a2ab7774-09ed-4b17-ac29-b2f4bac91690\Work\4f558c7a-8aca-47da-b53d-b245611659c7\Exec max 900 seconds
2019-06-28 17:36:18,094: INFO: executor(581): _execute_command: Dump file are created and ready to be uploaded
2019-06-28 17:36:18,094: INFO: azure_storage(192): _upload: Uploading single blob: 'console.a1b7c881.log'
```
https://mc.dot.net/#/user/dotnet-bot/pr~2Fdotnet~2Fcorefx~2Frefs~2Fpull~2F39034~2Fmerge/test~2Ffunctional~2Fcli~2Finnerloop~2F/20190628.33/workItem/System.Security.Cryptography.X509Certificates.Tests/wilogs

Where can we get this dump @MattGal @alexperovich?

**Comment by MattGal** [comment]
@ericstj alas you cannot get those dumps as they were not actually created, I fixed that issue on non-english OSes but it can't roll out until we're able to do Helix machine rollouts again (after the current release lockdown).

The issue is tracked by https://github.com/dotnet/core-eng/issues/6811.  I can help get you a machine with the image we use for our Spanish RS4 execution to experiment with but based on a cursory previous investigation this likely is a timing-dependent bug that may be hard to directly repro.

**Comment by ericstj** [comment]
Yep, not easily repro-able.  Once that dump support comes online can you share a pointer to the team with how to use it?

**Pull request merged**
