### PR TITLE
[NO MERGE] This is a test of the emergency broad cast system (eg. CI)

### PR DESCRIPTION
**Pull request by weshaggard**
cc @stephentoub 

test for https://github.com/dotnet/corefx/issues/18580.

### CODE REVIEW

**Comment by weshaggard** [comment]
@dotnet-bot help

**Comment by weshaggard** [comment]
@dotnet-bot test innerloop Ubuntu16.04 Debug

**Comment by weshaggard** [comment]
@stephentoub @ericstj it looks like all but the cross builds successfully failed when we caused a failure. 

@gkhanna79 who owns the cross builds? They should probably have a look to make sure the errors are correctly propagating.

**Comment by gkhanna79** [comment]
Can you share more details about what is being tried?

**Comment by weshaggard** [comment]
@gkhanna79 I was just verifying that CI correctly fails when there is a build failure and all the builds failed for my first test except for the cross build which had the failure when looking at the logs (ex: https://ci.dot.net/job/dotnet_corefx/job/master/job/ubuntu14.04_arm_cross_release_prtest/1865/consoleFull) but the CI leg said it passed. This means that the error isn't correctly propagating and the success for that build leg cannot be trusted.

**Comment by weshaggard** [comment]
@stephentoub I think I figured out why my local repo was working before, I was polluting the exit code by calling echo, so I cannot repro locally any more. However you can see from https://ci.dot.net/job/dotnet_corefx/job/master/job/ubuntu14.04_release_prtest/7105/consoleFull 

```
15:26:13     0 Warning(s)
15:26:13     8 Error(s)
15:26:13 
15:26:13 Time Elapsed 00:07:47.82
15:26:13 Command execution succeeded.
```

There is still something getting messed up on some legs for this failure case at least. I will keep investigating to see if I can figure out the gap, likely will pick this up again on Monday.

**Comment by stephentoub** [comment]
Ok, thanks.

**Comment by weshaggard** [comment]
@dotnet-bot test innerloop Ubuntu16.04 Debug
@dotnet-bot test innerloop Ubuntu16.10 Debug

**Comment by weshaggard** [comment]
Test results for commit https://github.com/dotnet/corefx/pull/19122/commits/1506d6026d1a38c981a9cdfe392bacced3a91f23. 

Correctly Failed:
Innerloop OSX10.12 Debug x64 Build and Test — Build finished.
Innerloop Ubuntu16.04 Debug x64 Build and Test — Build finished.
Innerloop Windows_NT Debug x86 Build and Test — Build finished.
Innerloop Windows_NT Release x64 Build and Test — Build finished.
Windows_NT Debug AllConfigurations Build — Build finished.


Incorrectly Succeeded:
CROSS Check — Build finished.
Innerloop CentOS7.1 Debug x64 Build and Test — Build finished.
Innerloop CentOS7.1 Release x64 Build and Test — Build finished.
Innerloop OSX10.12 Release x64 Build and Test — Build finished.
Innerloop PortableLinux Debug x64 Build and Test — Build finished.
Innerloop PortableLinux Release x64 Build and Test — Build finished.
Innerloop Tizen armel Debug Cross Build — Build finished.
Innerloop Tizen armel Release Cross Build — Build finished.
Innerloop Ubuntu14.04 Debug x64 Build and Test — Build finished.
Innerloop Ubuntu14.04 Release x64 Build and Test — Build finished.
Innerloop Ubuntu14.04 arm Release Cross Build — Build finished.
Innerloop Ubuntu16.04 arm Debug Cross Build — Build finished.
Innerloop Ubuntu16.10 Debug x64 Build and Test — Build finished.

Correctly Succeeded:
Vertical netfx Build — Build finished.
Vertical uap Build — Build finished.
Vertical uapaot Build — Build finished.

**Comment by weshaggard** [comment]
@ericstj commit https://github.com/dotnet/corefx/pull/19122/commits/2662923fe283b191f199688dcbddca2da80469e6 seems to have fixed the inconsistent failure modes for these Verify targets. The CrossBuild's still aren't correctly failing but that is because of other issues. @ericstj are you good with that commit, if so I will merge that independent of my testing.

**Comment by ericstj** [comment]
Yeah I'm ok with that.  If its a generic problem with AfterTargets though I'm sure we have other instances of AfterTargets that can fail.

**Comment by karelz** [comment]
@weshaggard do we still need this PR or can it be closed?

**Comment by weshaggard** [comment]
This is on the back burner, so I will close it to keep the stale PR's off the radar.

**Pull request closed without merging**
