### PR TITLE
Bring release/3.0 up to date

### PR DESCRIPTION
**Pull request by mmitche**

### CODE REVIEW

**Comment by wtgodbe** [comment]
LGTM, thanks Matt!

**Comment by wtgodbe** [comment]
Looks like we're hitting a lot of APICompat errors - are these expected (e.g. should we update the baselines), or is there something else going on here? CC @terrajobst 

https://dev.azure.com/dnceng/public/_build/results?buildId=96186

> __w/1/s/.packages/microsoft.dotnet.apicompat/1.0.0-beta.19112.3/build/Microsoft.DotNet.ApiCompat.targets(72,5): error : MembersMustExist : Member 'System.MidpointRounding System.MidpointRounding.ToNegativeInfinity' does not exist in the implementation but it does exist in the contract. [/__w/1/s/src/System.Runtime/src/System.Runtime.csproj]
/__w/1/s/.packages/microsoft.dotnet.apicompat/1.0.0-beta.19112.3/build/Microsoft.DotNet.ApiCompat.targets(72,5): error : MembersMustExist : Member 'System.MidpointRounding System.MidpointRounding.ToPositiveInfinity' does not exist in the implementation but it does exist in the contract. [/__w/1/s/src/System.Runtime/src/System.Runtime.csproj]
/__w/1/s/.packages/microsoft.dotnet.apicompat/1.0.0-beta.19112.3/build/Microsoft.DotNet.ApiCompat.targets(72,5): error : MembersMustExist : Member 'System.MidpointRounding System.MidpointRounding.ToZero' does not exist in the implementation but it does exist in the contract. [/__w/1/s/src/System.Runtime/src/System.Runtime.csproj]
/__w/1/s/.packages/microsoft.dotnet.apicompat/1.0.0-beta.19112.3/build/Microsoft.DotNet.ApiCompat.targets(85,5): error : ApiCompat failed for '/__w/1/s/artifacts/bin/System.Runtime/netcoreapp-Unix-Release/System.Runtime.dll' [/__w/1/s/src/System.Runtime/src/System.Runtime.csproj]
/__w/1/s/.packages/microsoft.dotnet.apicompat/1.0.0-beta.19112.3/build/Microsoft.DotNet.ApiCompat.targets(72,5): error : MembersMustExist : Member 'System.MidpointRounding System.MidpointRounding.ToNegativeInfinity' does not exist in the implementation but it does exist in the contract. [/__w/1/s/src/System.Runtime.Intrinsics/src/System.Runtime.Intrinsics.csproj]
/__w/1/s/.packages/microsoft.dotnet.apicompat/1.0.0-beta.19112.3/build/Microsoft.DotNet.ApiCompat.targets(72,5): error : MembersMustExist : Member 'System.MidpointRounding System.MidpointRounding.ToPositiveInfinity' does not exist in the implementation but it does exist in the contract. [/__w/1/s/src/System.Runtime.Intrinsics/src/System.Runtime.Intrinsics.csproj]
/__w/1/s/.packages/microsoft.dotnet.apicompat/1.0.0-beta.19112.3/build/Microsoft.DotNet.ApiCompat.targets(72,5): error : MembersMustExist : Member 'System.MidpointRounding System.MidpointRounding.ToZero' does not exist in the implementation but it does exist in the contract. [/__w/1/s/src/System.Runtime.Intrinsics/src/System.Runtime.Intrinsics.csproj]
/__w/1/s/.packages/microsoft.dotnet.apicompat/1.0.0-beta.19112.3/build/Microsoft.DotNet.ApiCompat.targets(72,5): error : MembersMustExist : Member 'System.Runtime.Intrinsics.Vector128.As<T, U>(System.Runtime.Intrinsics.Vector128<T>)' does not exist in the implementation but it does exist in the contract. [/__w/1/s/src/System.Runtime.Intrinsics/src/System.Runtime.Intrinsics.csproj]
/__w/1/s/.packages/microsoft.dotnet.apicompat/1.0.0-beta.19112.3/build/Microsoft.DotNet.ApiCompat.targets(72,5): error : MembersMustExist : Member 'System.Runtime.Intrinsics.Vector128.AsByte<T>(System.Runtime.Intrinsics.Vector128<T>)' does not exist in the implementation but it does exist in the contract. [/__w/1/s/src/System.Runtime.Intrinsics/src/System.Runtime.Intrinsics.csproj]

**Comment by wtgodbe** [comment]
Seems maybe related to this PR - https://github.com/dotnet/corefx/pull/35291/files ?

CC @stephentoub

**Comment by stephentoub** [comment]
> Looks like we're hitting a lot of APICompat errors - are these expected (e.g. should we update the baselines), or is there something else going on here?

What build flavor is hitting these?  The APIs were recently added and should be there in coreclr's CoreLib; if they're not, that suggests the branch is pulling in too old a CoreLib… it may be that you need to allow for the Preview3 coreclr changes to build and propagate before completing the corefx merge.

**Comment by wtgodbe** [comment]
Just updated this PR with the latest CoreClr preview3 changes

**Comment by wtgodbe** [comment]
Actually, looks like that commit didn't include the CoreClr update, as the CoreClr 3.0 builds have also been failing with a signing issue. @sbomer is there any update on when that will be fixed?

**Comment by wtgodbe** [comment]
Now this should have the latest CoreClr from 3.0, let's see how the CI goes

**Pull request merged**
