### PR TITLE
Remove the temporary references to pkgproj files for System.ComponentMode.TypeConverter

### LINKED ISSUE #11762: Change S.ComponentModel.TypeConverter projects to use project.json references rather than ProjectReferences
The System.ComponentModel.TypeConverter src and test projects have ProjectReferences to System.Drawing.Primitives.
Change these to project.json references once the new System.Drawing.Primitives surface area is exposed in published packages.

### PR DESCRIPTION
**Pull request by AlexGhiondea**
Fixes #11762

/cc @alexperovich

### CODE REVIEW

**Comment by AlexGhiondea** [comment]
@dotnet-bot please test Innerloop CentOS7.1 Release Build and Test  (machine setup issue)

**Comment by AlexGhiondea** [comment]
@dotnet-bot please test Innerloop CentOS7.1 Release Build and Test (machine setup issue)

**Comment by AlexGhiondea** [comment]
@dotnet-bot please test  Innerloop CentOS7.1 Debug Build and Test (machine setup issue)

**Comment by stephentoub** [comment]
LGTM

**Pull request merged**
