### PR TITLE
no merge: add output tests to check Kusto records

### PR DESCRIPTION
**Pull request by wfurt**

### CODE REVIEW

**Comment by wfurt** [comment]
It looks like Output is written out to Console log on test failure:

https://mc.dot.net/#/user/dotnet-bot/pr~2Fdotnet~2Fcorefx~2Frefs~2Fpull~2F35496~2Fmerge/test~2Ffunctional~2Fcli~2F/20190221.20/workItem/System.Net.Http.Functional.Tests/wilogs

```
[m[33;1m    System.Net.Http.Functional.Tests.SocketsHttpHandler_Output_Test.OutputTest_Skip [SKIP]
[m[37m      CurlHandler (libCurl) doesn't not work
[m[31;1m    System.Net.Http.Functional.Tests.SocketsHttpHandler_Output_Test.OutputTest_Fail [FAIL]
[m[37m      Assert.True() Failure
[m[37m      Expected: True
[m[37m      Actual:   False
[m[30;1m      Stack Trace:
[m[37m        /Users/vsts/agent/2.147.1/work/1/s/src/System.Net.Http/tests/FunctionalTests/SocketsHttpHandlerTest.cs(1663,0): at System.Net.Http.Functional.Tests.SocketsHttpHandler_Output_Test.OutputTest_Fail()
[m[30;1m      Output:
[m[37m        Going to fail 02/21/2019 10:13:54
[m[33;1m    System.Net.Http.Functional.Tests.SocketsHttpHandler_HttpClientHandler_Authentication_Test.Credentials_ServerUsesWindowsAuthentication_Success [SKIP]
```

I also searched Kusto database it seems like the Output is not stored. However, with following query, the Uri filed allows to download raw testResult.xml and ConsoleUri plain text output. 

```
Jobs | project JobId, Name, Source, Type, Build, Started , Finished , QueueName , PullRequestId |where  Started >= ago(1d) | join kind=inner (TestResults | project Method, Result, JobId, WorkItemFriendlyName , EventId , Arguments, Type , Exception , StackTrace , Message , Duration, Reason, Attempt , Traits, WorkItemId   | where Method contains "OutputTest" ) on JobId | order by Finished asc nulls last | join  kind=inner (WorkItems | project WorkItemId , Uri , ConsoleUri)  on WorkItemId 
```

example from test run and Kusto query:
https://helixexecution.blob.core.windows.net/helix-job-0c7fda81-dd8d-454b-c0baea83ef1940be835177f914bdb606/net_4_x_System.Xml_test.dll/testResults.xml?sv=2017-07-29&sr=c&sig=%2FlrEXa5zVNNBzKlwOEK791m%2FGxKbr%2FrT37f4shVC%2FC4%3D&se=2019-03-22T20%3A33%3A01Z&sp=rl
 
cc: @danmosemsft @karelz @rmkerr @davidsh

**Comment by danmosemsft** [comment]
@wfurt did you find out how to download testresult.xml from the MC page? If it's vanished - we should ask for it back - since you have discovered they do retain it...

**Comment by wfurt** [comment]
I did not find the link and it would be useful to add IMHO. There is cheat to get it:

Got test run page where there is the "Console".
Next to it the download icon. Right-click and do "Copy link". Replace console.*.log with testResults.xml and fetch. If passed to curl, it must be quoted (at least on Unix)

**Comment by danmosemsft** [comment]
@alexperovich @ChadNedzlek do you know where the link went to download testresults.xml? I know we used to have it.

**Comment by ChadNedzlek** [comment]
This job doesn't appear to be reporting to either Azure DevOps or Mission Control, so there aren't any xunits anywhere, which explains why things aren't working well...

**Comment by wfurt** [comment]
This was PR run but it did make it to Kusto database. 

How about this one: https://mc.dot.net/#/product/netcore/30/source/official~2Fdotnet~2Fcorefx~2Frefs~2Fheads~2Fmaster/type/test~2Ffunctional~2Fcli~2F/build/20190221.5/workItem/System.Security.Cryptography.X509Certificates.Tests/wilogs

That seems to be latest corefx "official" build.

**Comment by danmosemsft** [comment]
+ @safern @ViktorHofer in case they have context on @ChadNedzlek comment above.

**Comment by safern** [comment]
> This job doesn't appear to be reporting to either Azure DevOps or Mission Control, so there aren't any xunits anywhere, which explains why things aren't working well... One of `<EnableAzurePipelinesReporter>` or `<EnableXUnitReporter>` needs to be set during the build to cause it to upload to one of the two (or I guess both) places. I'm not sure what in the build system would need to change to make this be set.

We're actually using XunitReporter -- that is how all of our PRs work...

https://github.com/dotnet/corefx/blob/bfb495d39e2d7b5d7cc0b571ed504670b2faa68c/eng/sendtohelix.proj#L18

**Comment by ChadNedzlek** [comment]
@safern Hrm... the logs do seem to say it uploaded them... but for some reason the Helix processor didn't see them.  This is very strange. I'm going to poke around the database and figure out what's going on here. @alexperovich might be able to help too.

**Comment by safern** [comment]
Btw, to get test results xml file we will be adding this to the helix SDK: https://github.com/dotnet/arcade/issues/2076

**Comment by ChadNedzlek** [comment]
Hrm. Some of them sent it... and some of them didn't... I wonder what's going on here...

**Comment by ChadNedzlek** [comment]
I found where the UI tries to get this value... but I can't see any reason it would be where it's looking... or when it would have changed. Presumably it's been missing for a long time.  I wonder if we can expose this somewhere in a reasonable place. Or if Alex and include the output in the Azure DevOps attachments...

**Pull request closed without merging**
