### PR TITLE
Update buildtools to 2.0.0-prerelease-01708-01

### PR DESCRIPTION
**Pull request by mellinoe**
Includes a small fix in DumplingHelper.py.

### CODE REVIEW

**Comment by danmosemsft** [comment]
@mmitche is looking at OSX box

**Comment by mellinoe** [comment]
@dotnet-bot Test Innerloop Tizen armel Release Cross Build

It seems to have hung during the build.

**Comment by danmosemsft** [comment]
That is https://github.com/dotnet/corefx/issues/20458. I am going to merge this to fix the Helix breaks given OSX and Tizen passed in the other flavor.

**Comment by mellinoe** [comment]
Thanks @danmosemsft

**Pull request merged**
