### PR TITLE
Fix RegexCultureTests by moving it out-of-proc

### PR DESCRIPTION
**Pull request by stephentoub**
All of our tests that manipulate current culture currently need to be run out-of-proc.

Fixes https://github.com/dotnet/corefx/issues/38165
cc: @ViktorHofer

### CODE REVIEW

**Comment by ViktorHofer** [comment]
Thanks! Have you also thought about using the Culture test helper?

**Comment by stephentoub** [comment]
> Have you also thought about using the Culture test helper in addition to the RemoteExecutor.

I didn't think about it.  I simply wrapped the existing code in a `RemoteExecutor.Invoke(() => ...).Dispose();`, and didn't invest in changing the test / cleaning it up further.

**Comment by ViktorHofer** [comment]
Fair enough. Thanks!

**Comment by danmosemsft** [comment]
> All of our tests that manipulate current culture currently need to be run out-of-proc.

I thought this was only necessary when running in UAP, because otherwise culture is per-thread and flows to worker threads. What am I missing?

**Comment by stephentoub** [comment]
> I thought this was only necessary when running in UAP, because otherwise culture is per-thread and flows to worker threads. What am I missing?

You're not missing anything, other than we still do that.

**Comment by danmosemsft** [comment]
@stephentoub do you know why culture is not per-thread? Is it an OS artefact (eg you set for one thread it applies to all, or only the first set is respected). I mean, they ought to fix it ideally.

**Comment by stephentoub** [comment]
@tarekgh can probably best answer that.  Tarek?

**Comment by tarekgh** [comment]
CultureInfo.CurrentCulture sets the culture to the current thread (if you are not running in UAP app). The thing you need to be aware of is the current culture travel through the async calls (as AsyncLocal object).

**Comment by stephentoub** [comment]
> CultureInfo.CurrentCulture sets the culture to the current thread (if you are not running in UAP app)

Right, the question was about if you are running in UAP :)

**Comment by tarekgh** [comment]
For UAP, current culture is global to the whole app as WinRT doesn't have the concepts of thread cultures.

**Pull request merged**
