### PR TITLE
Make System.Threading.ThreadPool compile for AOT

### PR DESCRIPTION
**Pull request by jkoritzinsky**
This is needed to test the new thread pool on CoreRT.

### CODE REVIEW

**Comment by jkoritzinsky** [comment]
@kouvel @joperezr

**Comment by joperezr** [comment]
This is not required, by having a uap configuration, then uapaot is on by default. This change should be reverted as it only causes us to recompile an assembly one more time that produces the exact same output.

**Comment by joperezr** [comment]
Oh I see nevermind, I just saw that this is basically a facade that types forward to corelib, in which case the build configuration will be required since CoreRT's corelib and CoreCLR's one have different surface area and different public key.

**Comment by jkoritzinsky** [comment]
Any chance we can get an updated System.Threading.ThreadPool package pushed to MyGet?

**Comment by joperezr** [comment]
System.Threading.ThreadPool doesn't have it's own package, it instead ships as part of the UWP metapackage (Microsoft.Private.CoreFx.UAP) which gets consumed by core-setup which in turn will produce Microsoft.Net.UniversalWindowsPlatform package which will be consumed by customers.

**Pull request merged**
