### PR TITLE
Fixing a comment to check if CI fails

### PR DESCRIPTION
**Pull request by ahsonkhan**
Comments were added here: https://github.com/dotnet/corefx/pull/33415

### CODE REVIEW

**Comment by mmitche** [comment]
@dotnet-bot test this please

**Comment by stephentoub** [comment]
@ahsonkhan, any reason not to merge this?

**Comment by ahsonkhan** [comment]
> any reason not to merge this?

Nope. I realized that CI was failing in my other PR due to the original post of the PR being too long.

**Comment by stephentoub** [comment]
Thanks.

**Pull request merged**
