### PR TITLE
Remove InternalsVisibleTo from S.C.C.Registration

### PR DESCRIPTION
**Pull request by ViktorHofer**
Allow the linker and ILC to do its work and change internal refs in tests to reflection based calls.

### CODE REVIEW

**Comment by ViktorHofer** [comment]
@MichalStrehovsky can you help diagnose this remaining error on uapaot?

```
System.ComponentModel.Composition.Registration.Tests.RegistrationBuilderTests.GenericInterfaceExportInRegistrationBuilder [FAIL]
        System.PlatformNotSupportedException : PlatformNotSupported_MakeGenericType", @"MakeGenericType can only accept Type objects created by the runtime.
        Stack Trace:
             at xunit.console!<BaseAddress>+0x15f9554
             at System.ComponentModel.Composition.Hosting.CompositionServices.AdjustSpecifiedTypeIdentityType(Type, Type) + 0x146
             at System.ComponentModel.Composition.Hosting.CompositionServices.GetTypeIdentityTypeFromExport(MemberInfo, ExportAttribute) + 0x3b
             at System.ComponentModel.Composition.AttributedModel.AttributedPartCreationInfo.CreateExportDefinition(MemberInfo, ExportAttribute) + 0x21
             at System.ComponentModel.Composition.AttributedModel.AttributedPartCreationInfo.GetExportDefinitions() + 0x19b
             at System.ComponentModel.Composition.AttributedModel.AttributedPartCreationInfo.GetExports() + 0x1c
             at System.ComponentModel.Composition.ReflectionModel.ReflectionComposablePartDefinition.get_ExportDefinitionsInternal() + 0x31
             at System.ComponentModel.Composition.ReflectionModel.ReflectionComposablePartDefinition.get_ExportDefinitions() + 0x9
             at System.ComponentModel.Composition.Hosting.TypeCatalog.CreateIndex() + 0xad
             at System.Lazy`1.ViaFactory(LazyThreadSafetyMode) + 0xd6
             at System.Lazy`1.ExecutionAndPublication(LazyHelper, Boolean) + 0x51
             at System.Lazy`1.CreateValue() + 0xb0
             at System.ComponentModel.Composition.Hosting.TypeCatalog.GetCandidateParts(String) + 0x26
             at System.ComponentModel.Composition.Hosting.TypeCatalog.GetCandidateParts(ImportDefinition) + 0x58
             at System.ComponentModel.Composition.Primitives.ComposablePartCatalog.GetExports(ImportDefinition) + 0x65
             at System.ComponentModel.Composition.Hosting.CatalogExportProvider.InternalGetExportsCore(ImportDefinition, AtomicComposition) + 0x10d
             at System.ComponentModel.Composition.Hosting.CatalogExportProvider.InnerCatalogExportProvider.GetExportsCore(ImportDefinition, AtomicComposition) + 0x10
             at System.ComponentModel.Composition.Hosting.ExportProvider.TryGetExportsCore(ImportDefinition, AtomicComposition, IEnumerable`1&) + 0x19
             at System.ComponentModel.Composition.Hosting.CatalogExportProvider.GetExportsCore(ImportDefinition, AtomicComposition) + 0x4d
             at System.ComponentModel.Composition.Hosting.ExportProvider.TryGetExportsCore(ImportDefinition, AtomicComposition, IEnumerable`1&) + 0x19
             at System.ComponentModel.Composition.Hosting.ExportProvider.TryGetExports(ImportDefinition, AtomicComposition, IEnumerable`1&) + 0x16
             at System.ComponentModel.Composition.Hosting.AggregateExportProvider.GetExportsCore(ImportDefinition, AtomicComposition) + 0x1e2
             at System.ComponentModel.Composition.Hosting.ExportProvider.TryGetExportsCore(ImportDefinition, AtomicComposition, IEnumerable`1&) + 0x19
             at System.ComponentModel.Composition.Hosting.CompositionContainer.GetExportsCore(ImportDefinition, AtomicComposition) + 0x10e
             at System.ComponentModel.Composition.Hosting.ExportProvider.TryGetExportsCore(ImportDefinition, AtomicComposition, IEnumerable`1&) + 0x19
             at System.ComponentModel.Composition.Hosting.ExportProvider.GetExports(ImportDefinition, AtomicComposition) + 0x24
             at System.ComponentModel.Composition.Hosting.ExportProvider.GetExportsCore(Type, Type, String, ImportCardinality) + 0x82
             at System.ComponentModel.Composition.Hosting.ExportProvider.GetExportedValueCore[T](String, ImportCardinality) + 0x47
             at System.ComponentModel.Composition.Registration.Tests.RegistrationBuilderTests.GenericInterfaceExportInRegistrationBuilder() + 0x6d
             at _$ILCT$.$ILT$ReflectionDynamicInvoke$.InvokeRetV(Object, IntPtr, InvokeUtils.ArgSetupState&, Boolean) + 0x38
             at System.InvokeUtils.CalliIntrinsics.Call(IntPtr, Object, IntPtr, InvokeUtils.ArgSetupState&, Boolean) + 0x44
             at System.InvokeUtils.CallDynamicInvokeMethod(Object, IntPtr, Object, IntPtr, IntPtr, Object, Object[], BinderBundle, Boolean, Boolean, Boolean) + 0x190
```

**Comment by MichalStrehovsky** [comment]
> @MichalStrehovsky can you help diagnose this remaining error on uapaot?

Can you send me the .NET Native compiled binary for the test? The stack trace doesn't tell me much because S.C.C.Registration is a special kind of reflection hell.

**Comment by stephentoub** [comment]
> is a special kind of reflection hell

This literally made me laugh out loud :)

**Comment by MichalStrehovsky** [comment]
Okay, so the tests that are failing with this are failing because ComponentModel is trying to MakeGenericType things with a `System::Reflection::Context::Custom::CustomType` in it. The exception is correct in the sense that it's not a runtime provided type. CLR would get Reflection.Emit involved at that point and .NET Native has no Reflection.Emit.

Can you disable the test on platforms that don't have Reflection.Emit?

The other tests that are failing because `get_MetadataToken` is throwing can be disabled too. Those are failing because when we native-compile the assembly, we forget the metadata tokens that things in the original IL module had. This would be fixable, but it's a size bloat that I'm unwilling to pay at this point.

**Comment by ViktorHofer** [comment]
Thanks a lot Michal!

> This would be fixable, but it's a size bloat that I'm unwilling to pay at this point.

Does that mean S.ComponentModel.Composition.Registration won't be usable on UWP with ILC? Sounds like this is a product issue, not a test related one.

**Comment by MichalStrehovsky** [comment]
> Does that mean S.ComponentModel.Composition.Registration won't be usable on UWP with ILC? Sounds like this is a product issue, not a test related one.

Yes. Based on the comment I've seen around the `PlatformNotSupportedException` it seems like S.CM.C.R indirectly relies on pieces of System.Reflection.Emit and that's a deal breaker for platforms that don't have it. We can track it behind a P3 issue.

**Comment by ViktorHofer** [comment]
I see. I hit similar errors in System.ComponentModel.Composition. That probably means it isn't usable on UWP either...

**Pull request merged**
