### PR TITLE
Add jit stress modes for linux testing

### PR DESCRIPTION
**Pull request by sejongoh**
First cut of adding Jit stress mode testings

### CODE REVIEW

**Comment by sejongoh** [comment]
@dotnet-bot test Ubuntu jitstress1

**Comment by sejongoh** [comment]
@dotnet-bot test Ubuntu jitstress1

**Comment by sejongoh** [comment]
@dotnet-bot test Ubuntu jitstress1

**Comment by sejongoh** [comment]
@mmitche Could you please review the changes? 

The changes add new triggers, "(?i).*test\\W+${os}\\W+${scenario}.*, to run JIT stress testing on Linux. If I want to test this, should the changes be checked in first?

**Comment by sejongoh** [comment]
@dotnet-bot test Innerloop OSX Release Build and Test

**Comment by sejongoh** [comment]
@dotnet-bot test ci please.

**Comment by mmitche** [comment]
@sejongoh I just heard from some of the CoreFx guys that they are going to switch over the builds to use a full build/test of CoreFx on Linux rather than the hacked up workflow today.  I would hold off on this change since most of the code you changed will be eliminated

/cc @joperezr

**Comment by sejongoh** [comment]
@mmitche  I see. Thank you for update. 

@joperezr When does the CoreFx team plan to switch over?

**Comment by joperezr** [comment]
@sejongoh There was actually a slight change of plans. The idea now is to leave the innerloop as it is today because switching would mean that non-Windows CI builds would take ~2 hours to complete. For this reason, we decided to keep innerloops as they are for now, and only add Ubuntu and OSX to the outerloop jobs which will do the whole workflow by calling build.sh. I'm about to merge that change which is here #5883

**Comment by sejongoh** [comment]
@joperezr Thank you for update. Since I am focusing on testing on Ubuntu, The new workflow with build.sh looks helpful to me. 
Just to confirm, does run-test.sh currently run the outerloop? It looks like run-test.sh runs corerun with category=OuterLoop.

**Comment by joperezr** [comment]
The outerloop is not running run-test.sh, since the test run is triggered when you call build.sh, so even though the outerloop is not calling run-test.sh directly, it is running the tests.

**Comment by stephentoub** [comment]
@sejongoh, @joperezr, what's the status of this PR?  Is it going to move forward or should it be closed?  I can't tell from the discussion comments.

**Comment by joperezr** [comment]
The innerloop Unix jobs won't change yet, since we don't plan on changing the workflow for this until .Net Core MSBuild is faster (supports /m). I believe that @sejongoh should go ahead and merge his changes if he wants, since there is no clear ETA of when are we moving the innerloop jobs to call build.sh

**Comment by sejongoh** [comment]
I am testing the new workflow for JIT stress testing. If it works well with JIT stress testing, we probably don't need this PR. Can I hold this PR for a while until we can fully enable and test it?

Although the outerloop testing takes long time with checked build coreclr, we are mostly interested in daily testing and long testing time would be acceptable.. Also, innerloop testing with some failures are okay now.

**Comment by stephentoub** [comment]
> Can I hold this PR for a while until we can fully enable and test it?

What's the value in keeping it open?  You have your branch with the changes in it, and you can always submit a PR in the future if/when it's relevant.

**Comment by stephentoub** [comment]
I'm going to close this for now.  Please feel free to re-open of course if/when you're ready to move ahead with it.

**Pull request closed without merging**
