### PR TITLE
pul in updated Alpine39 image

### PR DESCRIPTION
**Pull request by wfurt**
pulls in sudo change to stabilize test runs.

### CODE REVIEW

**Comment by MattGal** [comment]
This is why doing this via direct Docker images is great, makes it easy for you to fix your own issues :)

**Comment by wfurt** [comment]
should the exact version be in separate file like rest of the images?  Also if the queue name keeps changing it will be harder IMHO to track results over time

**Comment by wfurt** [comment]
and yes, docker images are great.

**Comment by MattGal** [comment]
@wfurt once https://github.com/dotnet/core-eng/issues/5335 is done, you can put something like (Alpine.39.Amd64) before your existing queue id and have this show up in Mission Control and elsewhere like that.

**Comment by safern** [comment]
> should the exact version be in separate file like rest of the images? Also if the queue name keeps changing it will be harder IMHO to track results over time

No, those defined containers under the resources section in .azure-pipelines.yml file can only be used within a Job definition under the `container` metadata. This is for the azure's builtin support for docker containers for build to run within them. 

What we could potentially do, is define variables that define this containers and then append the variable after the @, which might avoid duplication whenever we use a container for Open and Non-Open jobs.

**Comment by wfurt** [comment]
would that impact how things are stored in kusto? 
I guess it could as we could use the friendly name.

**Comment by MattGal** [comment]
The idea would be that Kusto would only ever see the fake name, since it exists to report for your consumption.

**Pull request merged**
