### PR TITLE
[release/2.2] Add CentOS 8 Runtime ID to the graph

### PR DESCRIPTION
**Pull request by omajid**
CentOS 8 has been released:
https://wiki.centos.org/Manuals/ReleaseNotes/CentOSLinux8

    $ cat /etc/os-release
    NAME="CentOS Linux"
    VERSION="8 (Core)"
    ID="centos"
    ID_LIKE="rhel fedora"
    VERSION_ID="8"
    PLATFORM_ID="platform:el8"
    PRETTY_NAME="CentOS Linux 8 (Core)"
    ANSI_COLOR="0;31"
    CPE_NAME="cpe:/o:centos:centos:8"
    HOME_URL="https://www.centos.org/"
    BUG_REPORT_URL="https://bugs.centos.org/"
    CENTOS_MANTISBT_PROJECT="CentOS-8"
    CENTOS_MANTISBT_PROJECT_VERSION="8"
    REDHAT_SUPPORT_PRODUCT="centos"
    REDHAT_SUPPORT_PRODUCT_VERSION="8"

This is a backport of https://github.com/dotnet/corefx/pull/41397 and
commit c939f5d441979a45aeac84e5f2e16e62748f607b.

### CODE REVIEW

**Review by safern — APPROVED** [review]
/cc: @bartonjs

**Comment by danmosemsft** [comment]
If this is identical to https://github.com/dotnet/corefx/pull/41791 then you can just rely on that to flow to 2.2.

**Comment by omajid** [comment]
@danmosemsft Yes, it should be identical unless I screwed up. Should I just close this PR, then?

**Comment by safern** [comment]
> Edit: actually, #41791 is a superset. I didn't want to bother adding Fedora 32 (comes out around mid-2020) to 2.2 which will go EOL at the end of this year.

It will anyway flow and will contain both changes, the Fedora32 and the Centos8, so I think this PR can be closed.

**Comment by omajid** [comment]
Thanks, @safern! I am closing this PR in favour of #41791, then.

**Comment by bartonjs** [comment]
I feel like historically we've needed a different one in 2.2... and that this was missing the package authoring change to bump the package version and include it back in the build.

**Pull request closed without merging**
