### PR TITLE
System.ComponentModel - Replace Assert.True(false, with ShouldNotBeInvokedException

### PR DESCRIPTION
**Pull request by Clockwork-Muse**

### CODE REVIEW

**Comment by stephentoub** [comment]
Thanks, @Clockwork-Muse, but what's the value of this change?  I can understand replacing assert usage in helpers that aren't necessarily themselves tests, but these are tests.  I would prefer we just continue to use Assert here.

**Comment by Clockwork-Muse** [comment]
Hmm, I guess I see the general philosophy as only testing for desired behavior/values - only using `Assert...` when you expect a call to _succeed_.  That when you're asserting failure (`Assert.true(false, ...)`, `fail()`, etc), often tests should be rephrased somehow, or use an exception.
So when people are scanning through code, they don't have to flip logic trees or whatever.

**Comment by Clockwork-Muse** [comment]
Note that this sort of philosophy means that, if it's important to assert that the lambda doesn't run, it should be rephrased something like:
```
bool ran = false;
Action a = () => { ran = true; };
Assert.False(ran);
```
... whereas if the lambda isn't expected to run (and shouldn't), but you aren't positively asserting it, you'd use an exception.

I dunno, am I just overthinking things?

**Comment by stephentoub** [comment]
In the examples you've changed, nothing is ever really invoking the delegates; if something did, they'd assert and fail.  That's not the purpose of the test, though.  These tests are really just using dummy delegates, adding and removing them from a collection, and verifying that they were added/removed as expected.  If they get invoked, the asserts will throw and things will fail.

**Comment by Clockwork-Muse** [comment]
Right, that's what I'm getting at; the tests aren't dealing with whether or not the delegate gets called or not, it just needs a dummy delegate (and wants a SAN check in the case they somehow do get called).

It's like implementing a mock object, when you're expecting to only end up calling half the methods for a test: I'd probably have the leftover methods throw `NotImplementedException` (or maybe a couple of other things depending on the exact test).

Anyways, that's where I'm coming from.  :shrug: I can yank this, though.

**Comment by stephentoub** [comment]
An Assert.True/False is really no different than throwing an exception; that's all it does.  I don't see why for something like this it needs to be of a specific exception type; all other issues in the test are going to manifest as assertion failures, these can, too.  If it were helper code elsewhere that may or may not have a dependency on xunit, I understand throwing an explicit exception. Here, though, I see little value in making such a change, and I see decreased value that some failures are written as asserts, others as exceptions, and the difference seems relatively arbitrary.

**Pull request closed without merging**
