### PR TITLE
Fix the Build of Syndication and the Test.

### PR DESCRIPTION
**Pull request by shmao**
Make the builds for S.SM.Syndication and its test project work on corefx's build infrastructure. All the tests passed with the fixed.

I haven't fixed the namespace yet. I will address that later in a separate PR.

### CODE REVIEW

**Comment by shmao** [comment]
> UWP CoreCLR x64 Debug Build
Timeout has been exceeded

@dotnet-bot  test UWP CoreCLR x64 Debug Build

**Comment by shmao** [comment]
All active PRs are failing on UWP CoreCLR x64 Debug Build. This seems not related to this PR.

/cc: @mmitche

**Comment by mmitche** [comment]
@dotnet/dnceng Can you take a look?

**Comment by ChadNedzlek** [comment]
@mmitche this is already being investigated, the RS2.Open queue is currently broken

**Comment by shmao** [comment]
I'm merging the PR as the failure on UWP CoreCLR x64 Debug Build is not related.

**Comment by MattGal** [comment]
FYI Windows.10.Amd64.ClientRS2.Open should be good again (for UWP builds)

**Pull request merged**
