### PR TITLE
[release/2.1] Fix build errors in some build configurations

### PR DESCRIPTION
**Pull request by omajid**
There's two issues that cause different build warnings, breaking the build under certain conditions:

## Issue 1
This was a mistake in e4bcbd5885 (#34443) made when backporting it to the release branches. All other uses of NEED_OPENSSL_1_0 are guarded by an `#ifdef`, not an `#if`. This one should be too.

The warning is seen when building corefx using source-build. I couldn't observe it directly:

    source-build/src/corefx/src/Native/Unix/System.Security.Cryptography.Native/pal_asn1_print.cpp:34:5:
    error: 'NEED_OPENSSL_1_0' is not defined, evaluates to 0 [-Werror,-Wundef]
      #if NEED_OPENSSL_1_0
      ^

## Issue 2

When building in non-portable mode, some OpenSSL 1.1 function definitions that are marked as unused can be picked up by our build. When those functions are called, clang reports a warning and fails the build:

    src/Native/Unix/System.Security.Cryptography.Native/openssl.cpp:432:12:
    error: 'sk_ASN1_OBJECT_num' was marked unused but was used [-Werror,-Wused-but-marked-unused]
          return sk_ASN1_OBJECT_num(eku);
                 ^

This 'unused' attribute was recently added to `sk_*` methods in OpenSSL 1.1: https://github.com/openssl/openssl/pull/8246

cc @bartonjs

### CODE REVIEW

**Comment by bartonjs** [comment]
Do both `./build-native.sh` and `./build-native.sh -portable` from `src/Native/Unix/` work now?

**Comment by omajid** [comment]
No, `./build-native.sh` doesn't work. Looking into fixing other warnings now.

**Comment by omajid** [comment]
When OpenSSL **1.0** development headers and libraries are installed: both `./build-native.sh` and `./build-native.sh -portable` work.

When OpenSSL **1.1** development headers and libraries installed: `./build-native.sh` fails, but that error exists in master too: https://github.com/dotnet/corefx/issues/35807

**Comment by bartonjs** [comment]
Annoying re-verifying: Do both the portable and non-portable `build-native.sh`s work on your machine now? :)

**Comment by omajid** [comment]
Yes, both `./build-native.sh` and `./build-native.sh -portable` work with OpenSSL 1.1 headers installed. I didn't check OpenSSL 1.0 again.

**Comment by omajid** [comment]
Tested with OpenSSL 1.0 installed: both `./build-native.sh` and `./build-native.sh -portable` work too.

**Comment by vivmishra** [comment]
Approved for 2.1.10 and 2.2.4.

**Pull request merged**
