### PR TITLE
Exclude XML test assemblies from code coverage

### LINKED ISSUE #1582: XML test libs included in coverage report
I looked at the coverage report and noticed that a bunch of XML test libs are included:

image

Those are dragging the overall coverage down and should be excluded from coverage.

/cc @krwq

### PR DESCRIPTION
**Pull request by stephentoub**
A bunch of XML helper assemblies used by tests are showing up in our code coverage reports, and due to the amount of code in these helper libraries, significantly skewing the results.

OpenCover was very recently updated to support excluding assemblies via an attribute.  This commit simply adds an ExcludeFromCodeCoverage attribute to these assemblies; our use of OpenCover is already excluding things marked with this attribute, as we were previously using it on some members in System.Collections.Immutable.

This will take effect on code coverage once our buildtools are updated to the latest release of OpenCover.

Fixes #1582

### CODE REVIEW

**Comment by Maxwe11** [comment]
:+1: 
Just to clarify: How OpenCover pick up this attribute name (`System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage`) ?

**Comment by stephentoub** [comment]
It's passed to the command-line arguments: https://github.com/dotnet/buildtools/blob/7e6ddcd74b1e7ffea8f66e385d717d5b31069cab/src/Microsoft.DotNet.Build.Tasks/Targets/CodeCoverage.targets#L39

**Comment by KrzysztofCwalina** [comment]
looks good.

**Comment by stephentoub** [comment]
Thanks, Krzysztof.

**Comment by stephentoub** [comment]
@dotnet-bot test this please

**Pull request merged**
