### PR TITLE
Add Socket.Send/Receive concurrency test

### PR DESCRIPTION
**Pull request by stephentoub**
Help validate that on Unix we're able to invoke Send/Receive multiple times to run concurrently on the same socket instance.  We already have similar tests for Send/ReceiveAsync, so this just adds one for the synchronous Send/Receive.

cc: @geoffkizer, @wfurt

### CODE REVIEW

**Comment by stephentoub** [comment]
@dotnet-bot help

**Comment by stephentoub** [comment]
@dotnet-bot test outerloop netcoreapp OSX10.12 Debug
@dotnet-bot test outerloop netcoreapp Ubuntu16.10 Debug

**Comment by stephentoub** [comment]
@dotnet-bot test outerloop netcoreapp OSX10.12 Debug
@dotnet-bot test outerloop netcoreapp Ubuntu16.10 Debug

**Comment by stephentoub** [comment]
@dotnet-bot test outerloop netcoreapp OSX10.12 Debug
@dotnet-bot test outerloop netcoreapp Ubuntu16.10 Debug

**Comment by geoffkizer** [comment]
The test LGTM.

**Comment by geoffkizer** [comment]
@dotnet-bot test outerloop netcoreapp OSX10.12 Debug
@dotnet-bot test outerloop netcoreapp Ubuntu16.10 Debug

**Comment by geoffkizer** [comment]
The failures look unrelated, but running again just to be sure.

**Pull request merged**
