### PR TITLE
Move InvalidEnumArgumentException to System.ComponentModel.Primitives

### PR DESCRIPTION
**Pull request by hughbe**
Lays the groundwork for #20897

Note: is System.ComponentModel.Primitives the right place to put this? I thought about System.ComponentModel, but that library looks like its for interfaces only.

The reason why this is necessary is because we need use InvalidEnumArgumentException in System.Drawing.Common. This exception resides in System.ComponentModel.TypeConverter right now, but we want System.ComponentModel.TypeConverter to depend on System.Drawing.Common in the future.

### CODE REVIEW

**Comment by mellinoe** [comment]
@weshaggard Does this look reasonable? I brought this issue up with you a couple weeks back but had punted on it for now.

**Comment by mellinoe** [comment]
I believe we need to replace the old type (in System.ComponentModel.TypeConverter) with a type forwarder to its new location. This will allow code compiled against the old version to continue to work. For example: https://github.com/dotnet/corefx/blob/master/src/System.Reflection/ref/System.Reflection.cs#L8-L9

**Comment by weshaggard** [comment]
When did InvalidEnumArgumentException get added? If we shipped it in a stable version of TypeConverter then we should leave behind a type-forward there.

**Comment by hughbe** [comment]
I've updated the ref to type forward this class

**Comment by hughbe** [comment]
Windows nano failure looks unrelated

**Comment by mellinoe** [comment]
Thanks, @hughbe

**Pull request merged**
