### PR TITLE
Re-enable unicode zip tests for Unix

### LINKED ISSUE #5096: System.IO.Compression: Tests for creating ZipArchive with unicode filename failing on Unix
When trying to create a ZipArchive from a directory that contains a filename containing unicode characters a FileNotFoundException is thrown.

CI failure from #5085:
12:22:45       System.IO.FileNotFoundException : Could not find file '/mnt/j/workspace/dotnet_corefx/ubuntu_debug_tst_prtest/bin/tests/Linux.AnyCPU.Debug/System.IO.Compression.Tests/dnxcore50/ZipTestData/refzipfolders/unicode/������.txt'.

Unable to repro on my Ubuntu VM but is failing CI for CentOS and Ubuntu Debug&Release.

### PR DESCRIPTION
**Pull request by ianhays**
Consumes the new xunit Trait "IgnoreForCI" for the System.IO.Compression unicode tests that are failing on Jenkins.

We'll need to pass ```-notrait Category=IgnoreForCI``` to build.cmd in Jenkins, though I do not know the process for that.

resolves #5096, #5459

@stephentoub @ellismg

### CODE REVIEW

**Comment by ianhays** [comment]
@Priya91 @mmitche where do we store the args that are passed to the xunit test runner on Jenkins?

**Comment by Priya91** [comment]
@ianhays ```build.cmd /p:WithoutCategories="IgnoreForCI"``` should work..

**Comment by Priya91** [comment]
To update the command that goes to jenkins, you should edit the ```netci.groovy``` Innerloop job steps. Is that what you were looking for?

**Comment by ianhays** [comment]
>Is that what you were looking for?

Yes, thank you :)

**Comment by mmitche** [comment]
@Priya91 Thanks for letting @ianhays know how to do this!  It's always great to get help and shared ownership.

**Comment by Priya91** [comment]
@mmitche Anytime :)

**Comment by ianhays** [comment]
@Priya91 you mentioned on call issues with updating netci.groovy from another branch. Wouldn't that also affect PR's to master since they're technically on a different branch?

I ask because my changes aren't working :) Though it could certainly be an issue with my changes.

**Comment by Priya91** [comment]
@ianhays Yes, the PR's don't test the netci.groovy changes.. should be using test ci please.

cc @mmitche

**Comment by Priya91** [comment]
@dotnet-bot test ci please

**Comment by Priya91** [comment]
The jobs generated have the withoutcategories setup in the execute command setup in the genprtest result. LGTM!

**Comment by ianhays** [comment]
Thanks Priya! I had to do some manual rebasing and add the WithoutCategories a few more places after other changes to netci.groovy, so I'll retest.

@dotnet-bot test ci please

**Comment by ianhays** [comment]
To be safe, I'm going to split this into two PRs: one that updates the xunit.netcore.extensions and netci.groovy, and one that re-enables the compression tests. That way we're not merging a bunch of red tests.

Because of the title of this PR, I'm going to move the netci change to a new PR: #6522

**Comment by stephentoub** [comment]
@ianhays, as this is now pretty stale, I'm going to close it, and you can open a new one with just the needed test attributions once CI respects it appropriately. Thanks.

**Pull request closed without merging**
