### PR TITLE
Add/Cleanup GetDecoder negative tests

### PR DESCRIPTION
**Pull request by hughbe**
- Move to new more modern file

/cc @tarekgh

### CODE REVIEW

**Comment by tarekgh** [comment]
LGTM. Thanks!

**Comment by hughbe** [comment]
Test Innerloop OSX Release Build and Test
Test  Innerloop Windows_NT Release Build and Test

**Comment by tarekgh** [comment]
test Innerloop OSX Debug Build and Test please

**Comment by tarekgh** [comment]
test nerloop OSX Release Build and Test please

**Comment by tarekgh** [comment]
test Innerloop OSX Release Build and Test please

**Pull request merged**
