### PR TITLE
Obsolete Microsoft.VisualBasic.Constants.vbNewLine

### LINKED ISSUE #1817: Microsoft.VisualBasic.ControlChars.NewLine defined to be "\r\n"
This is correct on Windows but not on Unix.  We should consider making it a property or static readonly field that either delegates to or gets its value from Environment.NewLine.

### PR DESCRIPTION
**Pull request by stephentoub**
cc: @VSadov, @ljw1004, @AnthonyDGreen, @weshaggard, @terrajobst 
Fixes #1817

### CODE REVIEW

**Comment by VSadov** [comment]
Implementation LGTM
@AnthonyDGreen @ljw1004  -  are we ok with this? 
It seems leaving the constant (that should not have been a constant) as it was, but making it obsolete is the most explicit way to handle the problem.

**Comment by stephentoub** [comment]
@dotnet-bot test this please (https://github.com/dotnet/corefx/issues/4423 and https://github.com/dotnet/corefx/issues/3504)

**Comment by ljw1004** [comment]
I am *delighted* to have this marked Obsolete.

**Comment by weshaggard** [comment]
I'm OK with marking it as obsolete however it does require a version bump of the contract. //cc @ericstj

**Comment by stephentoub** [comment]
>  does require a version bump of the contract

The ref .vbproj contains <AssemblyVersion>10.0.1.0</AssemblyVersion>... I change that to 10.0.2.0?

**Comment by ericstj** [comment]
Not entirely sure about this one @weshaggard.  Since it isn't a surface area change it may be fine to do so in a bug fix release.  In that case you don't change anything (we've already changed version to 10.0.1.0 at the start of this release).

Wes is saying that officially the process for updating surface area requires a bump to the minor revision of the reference assembly, eg: 10.1.0.0.  I think that this is a special case since there is not change to surface area.  Wes, what do you think?

**Comment by AnthonyDGreen** [comment]
LGTM,

@weshaggard when you say a version bump do you mean major, minor, or what? Given that it isn't a surface area change and the obsolescence is only a warning I wouldn't expect either.

**Comment by weshaggard** [comment]
I was referring to the minor version as @ericstj called out. However I had similar thoughts as @ericstj on this one as it doesn't actually change any public API surface. For now lets stick with 10.0.1.0 which means no change necessary to the version right now.

**Comment by stephentoub** [comment]
Great.  Thanks, all.

**Pull request merged**
