### PR TITLE
Remove empty .resx files

### PR DESCRIPTION
**Pull request by stephentoub**
These were causing the build system to generate SR gook even though the assembly never uses it.  I searched and these appear to be the only such empty .resx files currently in the corefx repo.

### CODE REVIEW

**Comment by stephentoub** [comment]
cc: @tarekgh, @bartonjs

**Comment by bartonjs** [comment]
LGTM

**Comment by tarekgh** [comment]
LGTM too.

**Comment by stephentoub** [comment]
Thanks, guys.

**Pull request merged**
