### PR TITLE
Eliminate extra time zone conversions in DateTimeOffset

### PR DESCRIPTION
**Pull request by ts2do**
Revised members dealing specifically with local time by removing delegation to `DateTime` methods to avoid an extra call to `TimeZoneInfo` to determine offset:
> Now
> FromFileTime(long)
> ToLocalTime()

### CODE REVIEW

**Comment by stephentoub** [comment]
Can you please share performance tests and results demonstrating that this is an improvement? Thanks.

**Comment by ts2do** [comment]
I'm not exactly sure the best way of going about this. Can you point me to a good example?
Until then, here are some preliminary results:
`Now`: 485 ns/op >> 315 ns/op
`FromFileTime(long)`: 515 ns/op >> 300 ns/op
`ToLocalTime()`: 470 ns >> 250 ns/op

**Comment by ts2do** [comment]
I figured out what to do from your recent PR.

Here are the results:
**Before**

|        Method |      Mean |     Error |    StdDev |  Gen 0 |  Gen 1 |  Gen 2 |  Allocated |
| ------------- | --------- | --------- | --------- | ------ | ------ | ------ | ---------- |
|           Now |  474.7 ns |  1.913 ns |  1.790 ns |      - |      - |      - |          - |
|  FromFileTime |  498.1 ns |  1.685 ns |  1.494 ns |      - |      - |      - |          - |
|  ToLocalTime  |  459.5 ns |  1.732 ns |  1.620 ns |      - |      - |      - |          - |

**After**

|        Method |      Mean |     Error |    StdDev |  Gen 0 |  Gen 1 |  Gen 2 |  Allocated |
| ------------- | --------- | --------- | --------- | ------ | ------ | ------ | ---------- |
|           Now |  303.8 ns |  1.438 ns |  1.269 ns |      - |      - |      - |          - |
|  FromFileTime |  290.1 ns |  1.611 ns |  1.507 ns |      - |      - |      - |          - |
|   ToLocalTime |  236.7 ns |  0.881 ns |  0.824 ns |      - |      - |      - |          - |

And here is the benchmark:
```csharp
using BenchmarkDotNet.Attributes;
using BenchmarkDotNet.Running;
using System;

[MemoryDiagnoser]
public class Program
{
    static void Main(string[] args) => BenchmarkSwitcher.FromTypes(new[] { typeof(Program) }).Run(args);

    private long _fileTime;
    private DateTimeOffset _utc;

    [GlobalSetup]
    public void GlobalSetup()
    {
        _utc = DateTimeOffset.UtcNow;
        _fileTime = _utc.ToFileTime();
    }

    [Benchmark] public DateTimeOffset Now() => DateTimeOffset.Now;
    [Benchmark] public DateTimeOffset FromFileTime() => DateTimeOffset.FromFileTime(_fileTime);
    [Benchmark] public DateTimeOffset ToLocalTime() => _utc.ToLocalTime();
}
```

**Comment by stephentoub** [comment]
@ts2do, can you please submit this as a PR in coreclr instead?  The code you're modifying here isn't actually compiled in corefx.  I assume you got the benchmark numbers then by actually making these changes in coreclr instead?

**Comment by stephentoub** [comment]
Per my previous comment, I'm going to close this.  A PR in coreclr would be welcome.

**Pull request closed without merging**
