### PR TITLE
Merge v1 to master

### PR DESCRIPTION
**Pull request by stephentoub**

### CODE REVIEW

**Comment by weshaggard** [comment]
This is hard to review on the web but I looked for the only interesting merge I could remember (System.IO.FileSystem.DriveInfo.csproj) and it looks good. The changes LGTM.

I know @nguerrera had some suggestions on how he wanted these merges to happen so I will let him have a look as well.

**Comment by stephentoub** [comment]
Thanks, Wes. Nick, this look ok to you? I mainly just wanted the DriveInfo test changes, to hopefully get master's CI build back to green. (I think we should be a bit more aggressive on pushing such commits from v1 to master.)

**Comment by nguerrera** [comment]
LGTM. I'm not 100% sure about how best to review merges either. 

I tried to pull down your branch and review using @haacked's suggested approach around reviewing merges: http://haacked.com/archive/2014/02/21/reviewing-merge-commits/

The output was empty, which from my reading of the article suggests there are no interesting diffs to review. However, when I applied the same approach to my own merge commits where there were definitely conflicts to resolve, I didn't see any output either. I don't know if this means that the conflicts were resolved in a way that is deemed "uninteresting" or if I'm not following the instructions correctly..

I am curious why other folks' merge commits never seem to have the conflicting files listed in the commit message as in 8018d0685e1cc40fdb2df3c8577ceb95503a8ff9. 

Are you using tools other than git merge on the command line that don't add that or are you deleting them. I think it is good to persist the list of conflicts in case it ever helps someone diagnose a merge gone bad. I did try to merge this myself on Friday and there were definitely conflicts reported. Not critical, but if it's not too much trouble next time, I'd leave the list in the commit message.

**Comment by stephentoub** [comment]
> Are you using tools other than git merge on the command line that don't add that or are you deleting them

I just used the support in VS for resolving merge conflicts and committing the results. I didn't muck with commit messages at all, other then adding "Merge v1 to master" when I committed.

**Comment by nguerrera** [comment]
@stephentoub Ah. I see. If VS doesn't do this for you, I won't bother asking for it in the future. I am curious to see if anyone knows the best way to reverse engineer the list without having to persist it in the commit message.

**Comment by Haacked** [comment]
>  I am curious to see if anyone knows the best way to reverse engineer the list without having to persist it in the commit message.

Well the obvious way I can think of is to redo the merge and see what conflicts there are.

```
git checkout -b throwaway-branch
git reset MERGE-SHA^1
git merge MERGE-SHA^2
```

Where MERGE-SHA is the SHA of the merge commit. What this does is create a branch for experimental purposes. Resets it to the first parent of the merge commit. Then merges it with the second parent.

The resulting merge will either complete successfully, or will show you the list of conflicts.

Is there a better way to do this? Probably. With git, there's always another way. :smirk: If anyone would know, it's probably @mhagger. He works on Git and seems to specialize in merge and merge conflicts. :smile:

**Comment by mhagger** [comment]
@Haacked: That's about what I would do. One small simplification: you can avoid the creation of the throwaway branch by using a "detached head":

    git checkout MERGE-SHA^1
    git merge MERGE-SHA^2

To go back to normal work, run

    git checkout --hard master

or whatever, which will leave behind the detached merge commit without having pointed a reference at it.

Regarding the "Conflicts:" file list in the commit message of merge commits: as of Git 2.3.0, this list is slated to be changed into a commented-out hint when the commit message is generated, so by default it won't appear in the permanent record anymore.

**Comment by Haacked** [comment]
Thanks @mhagger. Any recommendations for how best to review a merge commit? I wrote [this post a while back](http://haacked.com/archive/2014/02/21/reviewing-merge-commits/), but they said it wasn't showing them what they needed to see. I'm concerned I may have made an error in it.

**Comment by mhagger** [comment]
> The output was empty, which from my reading of the article suggests there are no interesting diffs to review. However, when I applied the same approach to my own merge commits where there were definitely conflicts to resolve, I didn't see any output either. I don't know if this means that the conflicts were resolved in a way that is deemed "uninteresting" or if I'm not following the instructions correctly.

If each conflict hunk was resolved in such a way that the result looked like one of the branch tips, then those hunks would be considered "uninteresting", even if the conflicts were resolved manually. If all hunks were uninteresting, then nothing would be shown. My guess is that this explains what you saw.

**Comment by Haacked** [comment]
Interesting. It seems to me, if you really want to review how a merge conflict was resolved, you'd want to do something like:

1. Commit the merge complete with conflicts.
2. Resolve the commits in a separate commit.
3. Review that last commit.

Probably not worth the trouble. :smile:

**Comment by nguerrera** [comment]
@mhagger @Haacked 

>If each conflict hunk was resolved in such a way that the result looked like one of the branch tips, then those hunks would be considered "uninteresting", even if the conflicts were resolved manually.

Makes sense. That's good enough for me. I was trying the approach for the first time and couldn't even find a commit with an "interesting" merge so I wasn't sure if I was even doing it right. :)

Any chance you could integrate these "interesting hunks" only merge diffs in to the GitHub UI?

**Comment by Haacked** [comment]
> Any chance you could integrate these "interesting hunks" only merge diffs in to the GitHub UI?

Maybe if enough people email support@github.com and point out how this would really make their lives easier and better, we might prioritize it more highly than we do today *hint* *hint*. No promises though. :smile:

**Pull request merged**
