### PR TITLE
Fixing expression interpreter for NegateChecked overflow behavior

### PR DESCRIPTION
**Pull request by bartdesmet**
This fixes issue #3750.

cc @VSadov

### CODE REVIEW

**Comment by bartdesmet** [comment]
Note this also removes a few Negate instructions for arithmetic types that are not supported through the factory methods anyway.

**Comment by VSadov** [comment]
LGTM.

**Comment by VSadov** [comment]
looks like this needs rebasing

**Comment by bartdesmet** [comment]
Should be good to go now.

**Pull request merged**
