### PR TITLE
Add code of conduct information to README.md

### PR DESCRIPTION
**Pull request by stephentoub**
cc: @joshfree, @richlander, @martinwoodward

### CODE REVIEW

**Comment by joshfree** [comment]
LGTM

**Comment by martinwoodward** [comment]
Sorry - can we use the .NET Foundation Code of Conduct instead? https://github.com/dotnet/home/blob/master/guidance/readme-guide.md#code-of-conduct

**Comment by stephentoub** [comment]
> can we use the .NET Foundation Code of Conduct instead? 

Updated

**Comment by martinwoodward** [comment]
Thanks LGTM

**Pull request merged**
