### PR TITLE
[RC2] Add support for PCL profiles

### PR DESCRIPTION
**Pull request by ericstj**
Adds support for profile-based PCL using placeholders.

Port of commit: https://github.com/dotnet/corefx/commit/80c6626eab4c4974a4fa4bc9fa31125884f207ab

### CODE REVIEW

**Comment by ellismg** [comment]
The X-Plat runs are failing due to infrastructure issues.  There are two problems:

1) We don't have separate PR jobs for `rc2` vs `master` so we use the new `master` rules for invoke `run-test.sh`.  The way you invoke it differs between `rc2` and `master` and so that leads to some issues.
2) A similar issues exists for the per merge jobs.  While we have separate runs there, the rules for invoking `run-test.sh` are not factored out in `netci.groovy` to be per branch, so we always use the `master` version of the command, which doesn't work as expected.

Both of these errors were a result of 001983b9c3da7479ef8fe8c46a7dc6dd73054731.  Sorry about that.

The tactical fix is to move netci.groovy back to the old invocation of `run-test.sh` in all cases and update the version of `run-test.sh` in `master` to convert the invocation into something that is compatible with the test layout there.

I can try to make these changes.

At a minimum, we need to come up with a long term fix for a way to have an `rc2` version of the PR job.  @mmitche, do you know if it's possible to do something like that (trigger a different job if the pull is against `rc2` branch)?

**Comment by mmitche** [comment]
@ellismg Yes, CoreCLR is on a model where the CI definitions are branch specific already.  CoreFx has a PR ready for this but it has not been merged (it's a bit of a disruptive change)

**Comment by ericstj** [comment]
@weshaggard, @chcosta, & @davidfowl can you please review this change?

**Comment by weshaggard** [comment]
:+1:

**Comment by ellismg** [comment]
@dotnet-bot test this please (I believe I have fixed the RC2 PR infrastructure issues)

**Comment by ericstj** [comment]
Per @Petermarcu approved for RC2

**Pull request merged**
