### PR TITLE
Drop windows netstandard1.1 implementation to lib/netstandard1.1

### PR DESCRIPTION
**Pull request by Priya91**
In reference to issue #10445 

cc @ericstj @weshaggard @karelz

### CODE REVIEW

**Comment by ericstj** [comment]
We need to make that implementation work x-plat on mono as well.

I was discussing this with @mhutch and she recommended that we check
```c#
If (Type.GetType (“System.MonoType”) != null)
{
    // set RuntimeInformation.FrameworkDescription as mono
    // use reflection to read Environment.OSVersion and Environment.Is64OperatingSystem to 
    // determine values for RuntimeInformation.OSArchitecture and OSDescription

}
else
{
    // use windows pinvokes
}
```

**Comment by Priya91** [comment]
@ericstj has alternate idea to drop a dummy stub assembly to lib/netstandard1.1 instead of windows .netcore implementation. 

cc @weshaggard

**Comment by ericstj** [comment]
I was conflating a couple issues before.  The mono problem is a separate issue #9012.

For this issue we don't have any platforms that need a lib/netstandard1.1: all platforms that support netstandard1.1 have explicit implementations.  Placing the Windows implementation there would actually cause it to be used in some future platform that is not necessarily Windows.  As such I think its more appropriate to either have a dummy implementation that throws, or a default implementation that doesn't pinvoke.

@Priya91 and I put together a change that uses a dummy implementation: https://github.com/ericstj/corefx/commit/565eb78807579fbddb741bb59631fd68f18eb9ca

**Comment by weshaggard** [comment]
I'm fine with that approach for now.

**Comment by mhutch** [comment]
@ericstj in this case you can check for the OS rather than the runtime - you can use Windows P/Invokes on Mono/Windows :)

So `Environment.OSVersion.Platform != PlatformID.Win32NT`.

**Comment by Priya91** [comment]
Updated PR with @ericstj commit.

**Comment by ericstj** [comment]
@mhutch good point.  That's actually what we'd want to do in the desktop (eg: net45) implementation since mono pretends to be desktop.  Issue #9012.   How interesting do you think making that fix is, now that mono has it's own implementation for these types?

**Comment by ericstj** [comment]
I did a quick scan of other contracts to see if anything else fell into this bucket and didn't find anything else.

**Comment by mhutch** [comment]
As long as it behaves the same way, I don't think it really matters TBH. Just pointing out that Mono isn't equivalent to !Windows :)

**Comment by Priya91** [comment]
Windows build failed with test failures #13025

**Pull request merged**
