### PR TITLE
Try/Catch added to stopping service controller

### LINKED ISSUE #23388: System.ServiceProcess.Tests.ServiceBaseTests.TestOnStartThenStop failed in CI
Failed test: System.ServiceProcess.Tests.ServiceBaseTests.TestOnStartThenStop 

Detail: https://ci.dot.net/job/dotnet_corefx/job/master/job/outerloop_netcoreapp_win7_release/lastCompletedBuild/testReport/System.ServiceProcess.Tests/ServiceBaseTests/TestOnStartThenStop/

Configuration: OuterLoop_netcoreapp_win7_release

MESSAGE:
~~~
System.InvalidOperationException : Cannot open 40da180b-bbda-4b43-a0dc-256ebc6130e6 service on computer '.'.
    ---- System.ComponentModel.Win32Exception : The specified service does not exist as an installed service
~~~
STACK TRACE:
~~~
at System.ServiceProcess.ServiceController.GetServiceHandle(Int32 desiredAccess) in D:\j\workspace\outerloop_net---15cfbbd5\src\System.ServiceProcess.ServiceController\src\System\ServiceProcess\ServiceController.cs:line 638 
at System.ServiceProcess.ServiceController.GenerateStatus() in D:\j\workspace\outerloop_net---15cfbbd5\src\System.ServiceProcess.ServiceController\src\System\ServiceProcess\ServiceController.cs:line 473 
at System.ServiceProcess.ServiceController.Stop() in D:\j\workspace\outerloop_net---15cfbbd5\src\System.ServiceProcess.ServiceController\src\System\ServiceProcess\ServiceController.cs:line 882 
at System.ServiceProcess.Tests.TestServiceInstaller.RemoveService() in D:\j\workspace\outerloop_net---15cfbbd5\src\System.ServiceProcess.ServiceController\tests\System.ServiceProcess.ServiceController.TestService\TestServiceInstaller.cs:line 136 
at System.ServiceProcess.Tests.TestServiceProvider.DeleteTestServices() in D:\j\workspace\outerloop_net---15cfbbd5\src\System.ServiceProcess.ServiceController\tests\TestServiceProvider.cs:line 95 
at System.ServiceProcess.Tests.TestServiceProvider.DeleteTestServices() in D:\j\workspace\outerloop_net---15cfbbd5\src\System.ServiceProcess.ServiceController\tests\TestServiceProvider.cs:line 111 
at ReflectionAbstractionExtensions.DisposeTestClass(ITest test, Object testClass, IMessageBus messageBus, ExecutionTimer timer, CancellationTokenSource cancellationTokenSource) in C:\BuildAgent\work\cb37e9acf085d108\src\xunit.execution\Extensions\ReflectionAbstractionExtensions.cs:line 76 
----- Inner Stack Trace -----
~~~

### PR DESCRIPTION
**Pull request by Anipik**
Fixes #23388

### CODE REVIEW

**Comment by danmosemsft** [comment]
I don't believe this is related to #24933 ?

It is to "fix" https://github.com/dotnet/corefx/issues/23388 right?

**Comment by danmosemsft** [comment]
I updated comment

**Comment by danmosemsft** [comment]
@dotnet/dnceng OSX build is failing to git clone
```
Caused by: hudson.plugins.git.GitException: Command "git init /Users/dotnet-bot/j/workspace/dotnet_corefx/master/osx-TGroup_netcoreapp+CGroup_Debug+AGroup_x64+TestOuter_false_prtest" returned status code 1:
stdout: 
stderr: xcrun: error: unable to exec Xcode native xcrun (Permission denied).
```

**Comment by markwilkie** [comment]
@danmosemsft - is this still happening?

cc/ @mmitche

**Comment by mmitche** [comment]
@danmosemsft Last time we saw this, it was an OSX machine with a bad xcode installation.
@MattGal Looks like there might be another bad xcode installation on auth.prep.xbox.com.  @jpratherMS Can you map this back to a machine in DDCCS and check the xcode installation there?

**Comment by MattGal** [comment]
@mmitche I'll spend a few minutes seeing if I can track it down on the KVMs as well. Certainly nothing named like that in the 2 KVMs I have access to.

**Comment by MattGal** [comment]
I discovered dci-macpro-13 is ppt.prep.xbox.com but was unable to find the specific machine.  Hopefully @JPratherMs can!

**Comment by MattGal** [comment]
Quick update for historical reasons, I did use some trickery to get that machine offline.  We still don't know where it actually is though.

**Pull request merged**
