### PR TITLE
Add issue / pull request template explaining repo consolidation

### PR DESCRIPTION
**Pull request by Gnbrkm41**
Related: https://github.com/dotnet/corefx/issues/42733

I left the PR template commented out, since I heard the repo will still be used for servicing fixes (so PRs would be opened here for legitimate reasons in future)

Nits welcome, I'm terrible when it comes to my English skills 😄. Also wanted to give a go at modifying README.md but I guess someone else could do it better, and repo descriptions... well, I don't have the perms!

cc @danmosemsft

### CODE REVIEW

**Comment by maryamariyan** [comment]
Thank you for your contribution. As announced in #27549 the dotnet/runtime repository will be used going forward for changes to this code base. Closing this PR as no more changes will be accepted into master for this repository. If you’d like to continue working on this change please move it to dotnet/runtime.

**Comment by Gnbrkm41** [comment]
@maryamariyan, this PR is intended to add issue templates on this repo (to tell people exactly that).

**Comment by gfoidl** [comment]
The same should be done in coreclr-repo. Right now the templates are empty.

**Comment by vcsjones** [comment]
This PR should be re-opened and re-targeted against the `archive` branch.

**Comment by danmoseley** [comment]
Despite my earlier comment I just realized these may not be useful for very long

1. for issues, it seems not mentioned in https://github.com/dotnet/coreclr/issues/27549, but immediately after the bulk migration of all issues open and closed to dotnet/runtime, we will disable issues in the old repos. It will not be possible to open them. Until that point, I guess we could have a template (in the default branch whatever it is), but it does not matter too much whether an issue is opened here or not. 
1. for PR's any new PR against master presumably will fail because there will be no code in it. It will hopefully be easy to see you are in the wrong place.

**Comment by Gnbrkm41** [comment]
Ah, that's good to hear 😃

**Comment by vcsjones** [comment]
@danmosemsft given what appears to be a delay in the issue migration, perhaps this is worth re-considering?

**Comment by danmoseley** [comment]
Yeah, probably. I can't seem to reopen this. I'll throw something simple up.

**Comment by danmoseley** [comment]
@vcsjones  done.

**Pull request closed without merging**
