### PR TITLE
Fixing the official build

### PR DESCRIPTION
**Pull request by Anipik**

### CODE REVIEW

**Review by ericstj — APPROVED** [review]

**Comment by Anipik** [comment]
Tested with official builds and the fix works

**Review by safern — APPROVED** [review]

**Comment by safern** [comment]
Hmm now the PR build is not working, it is not generating the runtime package. @ericstj it is weird that in the removal of the Platforms package it did build the runtime package but in this one it is not building it, something seems off there.

**Comment by Anipik** [comment]
it is generating the nuspec
```
  Verifying closure of runtime.win-x64.Microsoft.Private.CoreFx.NETCoreApp runtime assemblies
  Verifying no duplicate types in runtime.win-x64.Microsoft.Private.CoreFx.NETCoreApp runtime assemblies
  Microsoft.Private.CoreFx.NETCoreApp -> D:\a\1\s\artifacts\packages\Debug\specs\runtime.win-x64.Microsoft.Private.CoreFx.NETCoreApp.nuspec

```

**Comment by safern** [comment]
Oh I see that  the runtime package is actually generated. I looked at the .binlog and the `GenerateProjects` is not being executed at all because the `SupportedPackage` is empty since it is populated in a target which is chained in, by the `ArchiveHelixItems` dependson so it is causing that the targets that fill in `SupportedPackage` to not run... I think the condition should be when we call the `ZipDirectory` or we should do the target chaining different. Something like

```
T: Build
 DependsOn:
   T: BuildProjects
   T: HarvestVersionValidation
   T: BuildHelixItems (Empty target)
      Condition: '$(ArchiveTests.ToLower())' == 'packages' or '$(ArchiveTests.ToLower())' == 'all'
      DependsOn:
        T: GenerateProjects
        T: CopyProducedPackages
        T: ArchiveHelixItems (Do the zipping)
            Condition: '@(SupportedPackage)' != ''
```

Try that locally and see if it works.

**Comment by Anipik** [comment]
okay i will try that loally

**Comment by safern** [comment]
Oh I see it is actually generating, is it maybe that the item is empty when the evaluation of the condition is evaluated?

**Comment by Anipik** [comment]
we need the second zip to execute. Output after the change locally
```
  Microsoft.Private.CoreFx.NETCoreApp -> C:\git\corefx\artifacts\packages\Debug\specs\runtime.win-x64.Microsoft.Private.CoreFx.NETCoreApp.nuspec
  Zipping directory "C:\git\corefx\artifacts\bin\testPkg\projects\runtime.win-x64.Microsoft.Private.CoreFx.NETCoreApp" to "C:\git\corefx\artifacts\helix\tests\runtime.win-x64.Microsoft.Private.CoreFx.NETCoreApp.zip".
  Zipping directory "C:\git\corefx\artifacts\bin\testPkg\support\" to "C:\git\corefx\artifacts\helix\runtime\packages-testPayload-Debug.zip".
```
This should fix the problem.

**Pull request merged**
