### PR TITLE
Delete erroneous file in Microsoft.CSharp

### PR DESCRIPTION
**Pull request by stephentoub**
Introduced I assume accidentally in https://github.com/dotnet/corefx/pull/23278.
cc: @JonHanna

### CODE REVIEW

**Comment by mmitche** [comment]
@dotnet-bot test this please (restarted for plugin update)

**Comment by JonHanna** [comment]
I'm rather at a loss as to how this happened (and am keen to learn how), given I'm working on Windows so it can't have both a `src/Microsoft.CSharp/src/Microsoft/CSharp/RuntimeBinder/Semantics/Types/TypeParameterType.cs` and a ` src/microsoft.csharp/src/microsoft/csharp/runtimebinder/semantics/types/typeparametertype.cs`. It explains the confusion I was having with #25075, so thanks for sorting it.

**Comment by stephentoub** [comment]
@mmitche, what's up with the failed legs? ("java.lang.NullPointerException")

**Comment by mmitche** [comment]
@stephentoub Ahh,. that's because of the restart.  Some jobs resumed after the restart, but I guess that's unsupported.  I think only one leg has that error.  The others are real failures. 

@dotnet-bot test UWP NETNative x86 Release Build

**Comment by mmitche** [comment]
When I did test th*s please.  It did restart the legs, but the ones that got resumed finished before those and updated status.

**Comment by stephentoub** [comment]
Thanks, Matt.

**Pull request merged**
