### PR TITLE
Add uap10.1 target to System.Runtime.WindowsRuntime 

### PR DESCRIPTION
**Pull request by luqunl**
Update code according to code review feedback for the original PR: https://github.com/dotnet/corefx/pull/12339

1. Remove netcore50aot
2. Unify code path for uap101aot and coreclr: both are using wrapper
3. Remove some #if netstandard which is only used in netcore50aot

### CODE REVIEW

**Comment by luqunl** [comment]
CC: @jkotas, @weshaggard , @yizhang82 , @tarekgh , @SedarG

**Comment by jkotas** [comment]
@luqunl Could you please resolve the conflicts against the reverts?

**Comment by luqunl** [comment]
Close this PR due to the conflicts against server

**Comment by jkotas** [comment]
@luqunl You do not need to close PR to resolve merge conflict. The common practice is to push the commit with resolved merge conflicts into *same* PR.

**Pull request closed without merging**
