### PR TITLE
Fix a bunch of Xml OuterLoop test failures on Unix

### PR DESCRIPTION
**Pull request by stephentoub**
- Lots of tests were depending on '\' being the path separator
- Lots of tests were depending on Environment.NewLine being "\r\n"

I'm trying to get our outer loop tests passing on Unix, and these are standing in the way.

cc: @ellismg, @krwq

### CODE REVIEW

**Comment by stephentoub** [comment]
Test OuterLoop Ubuntu Debug please

**Comment by stephentoub** [comment]
test outerloop Ubuntu Debug

**Comment by stephentoub** [comment]
Test Outerloop Ubuntu Debug Build and Test please

**Comment by stephentoub** [comment]
test outerloop Ubuntu14.04 debug please

**Comment by stephentoub** [comment]
test outerloop Ubuntu14.04 Debug

**Comment by stephentoub** [comment]
test outerloop Win8 Debug

**Comment by stephentoub** [comment]
test outerloop Windows_NT Debug

**Comment by stephentoub** [comment]
@mmitche, here's another of those mkdir failures:
http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/nativecomp_centos7.1_debug_prtest/2666/console

**Comment by mmitche** [comment]
This seems to be happening when the VM spins up and the init script doesn't complete properly (maybe the resource disk isn't mounted properly?)  I'm thinking that the cloud provisioner should probably just avoid using the VM if that happens.

**Comment by stephentoub** [comment]
@ellismg, FYI, this fixes all of the failures in the Ubuntu OuterLoop job:
```
10:18:08     12 Warning(s)
10:18:08     0 Error(s)
```
For some reason after running all of the tests, the job then gets aborted:
```
10:14:41 ERROR: Step ‘Publish xUnit test result report’ aborted due to exception: 
10:14:41 
java.io.IOException: remote file operation failed: /mnt/j/workspace/dotnet_corefx/outerloop_ubuntu14.04_release_prtest at hudson.remoting.Channel@73060d42:Azure0223084819: hudson.util.IOException2: There are some problems during the conversion into JUnit reports: 
```

**Comment by ellismg** [comment]
LGTM

**Comment by stephentoub** [comment]
Thanks.

**Pull request merged**
