### PR TITLE
Add remaining missing members of System.Security namespace (not child namespaces)

### PR DESCRIPTION
**Pull request by danmosemsft**
Tests are not passing at all on my box yet due to unrelated errors which I will follow up with offline if they don't occur on CI.

Also updated the baselines with /p:baselineallapicompaterror=true, which shows up as a large diff.

Issues: #11122 and #11115 

@weshaggard

### CODE REVIEW

**Comment by danmosemsft** [comment]
Next problem, running the System.Collections tests for netcoreapp1.1 is failing because it cannot load System.Diagnostics.Debug 4.1.0.0 -- which System.Collections itself references -- the tests reference 4.0.10, and the copy in the test folder is 4.0.12.0

@weshaggard @ericstj @stephentoub any pointers ?

**Comment by danmosemsft** [comment]
Hmm, let's go back to my original System.Runtime changes and rethink...

**Comment by danmosemsft** [comment]
Back to `CS1685: The predefined type 'UnverifiableCodeAttribute' is defined in multiple assemblies in the global alias; using definition from 'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e' `

This is because my new implementation in System.Runtime conflicts with the existing one in mscorlib. (I'm preferring System.Runtime so it accrues to CoreRT)

@stephentoub Should I disable CS1685 globally, update model.xml to remove the replaced types, then re-enable the warning when we get the updated mscorlib? This must not be an uncommon problem.

**Comment by danmosemsft** [comment]
@jkotas agreed with that strategy, but suggested I not bother moving some of these attributes. I'll revise.

**Comment by danmosemsft** [comment]
CLR side in https://github.com/dotnet/coreclr/pull/7352

**Comment by karelz** [comment]
@danmosemsft are you still working on it?

**Comment by danmosemsft** [comment]
Closing this. If I continue I'll start a fresh PR>

**Pull request closed without merging**
