### PR TITLE
Update BuildToolsVersion to 00212 and test changes to support this

### PR DESCRIPTION
**Pull request by MattGal**
- Remove addition of NETFrameworkAssembly metadata, which now resides in build tools.
- Update public key used for InternalsVisibleTo in tests
- Fix test that was signing test assembly w/ product key

### CODE REVIEW

**Comment by eerhardt** [comment]
:shipit:

**Comment by stephentoub** [comment]
Will this fix #7125, #7126, and #7061?

**Comment by stephentoub** [comment]
cc: @ericstj, @weshaggard

**Comment by stephentoub** [comment]
Test Innerloop OSX Debug Build and Test please (https://github.com/dotnet/corefx/issues/4829)

**Comment by MattGal** [comment]
@stephentoub I did fix #7061  because I thought I caused it, but I didn't intend to and expect that the change wouldn't fix the other ones.  I mostly made this change to get the test assemblies to not look like framework assemblies so I could try putting them through the native compilation toolchain, and this is the fallout from doing that.

**Comment by gkhanna79** [comment]
I took Matt's change, to skip signing for System.Runtime.Loader.Noop.Assembly.csproj, and confirmed that it fixes #7061.   Does this mean that Outerloop test build actually signs the tests while Innerloop test build does not?

CC @joshfree @Priya91 @stephentoub

**Comment by gkhanna79** [comment]
@MattGal I will assign #7061 to you since you have a fix for it in this PR.

**Comment by weshaggard** [comment]
@MattGal your change LGTM.

Orthogonal to this change InternalVisibleToAttributes are going to need to be removed as we start to enable these tests to run on other platforms where the implementations are different and we enable scenarios like @chcosta is doing about running the test against a specific set of packages.

**Comment by stephentoub** [comment]
Test Innerloop OSX Debug Build and Test please

**Comment by nguerrera** [comment]
@weshaggard

> Orthogonal to this change InternalVisibleToAttributes are going to need to be removed as we start to enable these tests to run on other platforms where the implementations are different and we enable scenarios like @chcosta is doing about running the test against a specific set of packages. 

Will this apply to System.Reflection.Metadata and System.Collections.Immtuable which are entirely portable and only have 1 build? InternalsVisibleTo(test) can be very practical and there are a number of places where I don't think we can get the same coverage or at least the same dev workflow expedience without it.

**Comment by weshaggard** [comment]
@nguerrera I suspect it will not apply to those. Currently what I'm thinking is we will have two different classes of test projects. One that is implementation specific test library and one portable/conformance based test library. The implementation specific test library could continue to use IVT and project references all the time as it is binding itself to a specific implementation. The portable/conformance base tests will only be able to build against the contracts and so will not be able to use IVT at all.

**Pull request merged**
