### PR TITLE
Update BuildTools to 1.0.27-prerelease-01219-01, add EnableDumpling to pipeline

### PR DESCRIPTION
**Pull request by sepidehMS**
Updates BuildTools from `1.0.27-prerelease-01211-03` to `1.0.27-prerelease-01219-01` (To get https://github.com/dotnet/buildtools/pull/1306)

Also, adding `/p:EnableDumpling=true` to pipeline.json for all Linux runs, as I need Dumpling.Targets to be imported in tests.targets and add commands to `RunTests.sh` on Helix tests.

cc: @chcosta @danmosemsft @karajas

### CODE REVIEW

**Comment by sepidehMS** [comment]
PTAL. Thanks.

**Comment by chcosta** [comment]
I'm not familiar with Dumpling, but the changes to pipeline.json LGTM

**Comment by sepidehMS** [comment]
Thanks @chcosta.
@danmosemsft @karajas Any comments?

**Comment by karajas** [comment]
LGTM.

**Pull request merged**
