### PR TITLE
Move System.Drawing.Common files to the correct folder

### PR DESCRIPTION
**Pull request by qmfrederik**
Move System.Drawing.Common files to the correct folder based on the namespace of the type they contain.

### CODE REVIEW

**Comment by mellinoe** [comment]
@qmfrederik Looks good to me. Unfortunately, there are a ton of PR's out right now that are touching this project file, so it has merge conflicts currently.

**Comment by qmfrederik** [comment]
@dotnet-bot help

**Comment by qmfrederik** [comment]
@dotnet test Portable Linux x64 Debug Build  please

**Comment by qmfrederik** [comment]
@dotnet-bot test Innerloop OSX10.12 Release x64 Build and Test  please

**Comment by qmfrederik** [comment]
@mellinoe Rebased and all tests pass now.

**Comment by mellinoe** [comment]
@qmfrederik Thanks for the cleanup.

**Comment by qmfrederik** [comment]
@marek-safar @akoeplinger With this PR the file names in CoreFX System.Drawing are more or less stable.

If you update the corefx dependency of Mono, I can create another PR in mono which replaces parts of Mono's System.Drawing with the one from CoreFX.

**Comment by akoeplinger** [comment]
@qmfrederik https://github.com/mono/mono/pull/5031, will merge once tests come back green :)

**Pull request merged**
