### PR TITLE
Manual darc update from build '20190418.2'

### PR DESCRIPTION
**Pull request by ViktorHofer**
Consume changes from CoreFxTesting to allow the new rsp option: `/p:TestRspFile=...`.

### CODE REVIEW

**Comment by safern** [comment]
It seems like this is hitting: https://github.com/dotnet/arcade/issues/2556

cc: @tannergooding correct me if wrong.

**Comment by tannergooding** [comment]
Yes, looks the same. The fix has been merged, so we just need to wait for a new build to flow

**Comment by tannergooding** [comment]
Looks like it might already exist...

**Comment by tannergooding** [comment]
I think https://github.com/dotnet/corefx/pull/37020 contains everything from here, plus the new GenAPI fix.

**Comment by safern** [comment]
Yeah, we can close this PR.

**Pull request closed without merging**
