### PR TITLE
Fix race condition on Unix pooling canceled Socket operations

### PR DESCRIPTION
**Pull request by stephentoub**
Fixes https://github.com/dotnet/corefx/issues/26452 (or it at least fixes one cause of the symptom; hopefully that's it)

cc: @geoffkizer, @wfurt

### CODE REVIEW

**Comment by stephentoub** [comment]
@dotnet-bot test Outerloop Linux x64 Debug Build please

**Comment by geoffkizer** [comment]
This seems like it will fix the issue, but I wonder if it would be better to avoid this earlier in the logic.

The only place we actually remove the operation from the queue is in ProcessQueue.  Instead of calling ReturnOperation from InvokeCallback, we could call it from ProcessQueue.  That way we avoid ReturnOperation being called when InvokeCallback is called for cancellation.  ProcessQueue could then also call ReturnOperation in the cancelled case, since that's when the cancelled operation will actually be removed from the queue.

**Comment by geoffkizer** [comment]
Also, since we had a simple repro here, can we add that as a test?

**Comment by stephentoub** [comment]
Yeah, that's better, I'll do that.

**Comment by stephentoub** [comment]
Actually, that gets complicated, as we really want the object pooled before the callback is Invoked, so the next operation can use it.

**Comment by geoffkizer** [comment]
Hmmmm, you're right.

That said, we can still change the code to avoid calling ReturnOperation in the cancelled case, right?

**Comment by wfurt** [comment]
I can test the change. I was also thinking about not returning operation to the pool before we are done with it but I don't know if that is right choice.

**Comment by stephentoub** [comment]
> That said, we can still change the code to avoid calling ReturnOperation in the cancelled case, right?

How? Pass a bool into InvokeCallback and conditionally invoke ReturnOperation based on that? Then it's just a question of whether the check is at each of N call sites or N callees. I don't have a strong preference, but it doesn't seem any cleaner.

**Comment by geoffkizer** [comment]
> How? Pass a bool into InvokeCallback and conditionally invoke ReturnOperation based on that?

Sure, or have two different versions of InvokeCallback, one for success and one for cancellation.

This seems slightly better to me in that the caller is being intentional about what should happen, instead of relying on _state.

**Comment by stephentoub** [comment]
Feedback addressed.

**Comment by stephentoub** [comment]
> I can test the change.

Thanks.

>  I was also thinking about not returning operation to the pool before we are done with it but I don't know if that is right choice.

Yes, we definitely don't want to return it before we are done with it.  The issue here is we thought we were done with it but we weren't actually, because of how the locking is done in ProcessQueue.

**Pull request merged**
