### PR TITLE
Add additional runtimes

### PR DESCRIPTION
**Pull request by ellismg**
- Add "debian.8-x64". This is the correct rid for Debian, after this
  lands, I will need to update CI before we can remove "debian.8.2-x64"

- Add a generic "linux-x64" rid which we can use in cases where we want
  to build for a distro where we don't yet have a set of runtime
  packages.  This will let us restore the managed assets (since they are
  specific to "unix" or "linux" and then folks can do a native build to
  get the shims and runtime and copy them over (this is a more
  reasonable approach than our current strategy of just using
  ubuntu.14.04-x64)

- Sort runtime sections

### CODE REVIEW

**Comment by ellismg** [comment]
@dagood do you mind taking a look?  I generated this via a tool that walked all the project.json's and for any runtime section that had "ubuntu.14.04-x64" in it, rewrote the runtime sections.

**Comment by ellismg** [comment]
I plan to make similar changes in coreclr and wcf and then try to remove `debian.8.2-x64` from our runtimes section.  It would be a shame to ship 1.0 with it.

**Comment by dagood** [comment]
Did spot checks on the changes, LGTM. Plan sounds good too. :+1:

**Comment by ellismg** [comment]
The Windows_NT failure is the SSL issue we've been having problems with (and will be fixed when we can update packages).  Going to merge this.

**Pull request merged**
