### PR TITLE
Fix WebHeaderCollection.GetEnumerator().

### PR DESCRIPTION
**Pull request by pgavlin**
Change WebHeaderCollection.GetEnumerator() from an explicit implementation
to a public override to avoid delegating to the base collection. This change
also adds a test for this behavior.

### CODE REVIEW

**Comment by pgavlin** [comment]
@davidsh PTAL

**Comment by davidsh** [comment]
/cc @ericstj 
Looks ok but we need toverify that it doesn't impact anything regarding the public contract as defined by:

`
namespace System.Net {
  partial class WebHeaderCollection : System.Collections.IEnumerable {
    public string this[string name] { get { return default(string); } set { } }
    System.Collections.IEnumerator System.Collections.IEnumerable.GetEnumerator() { return default(System.Collections.IEnumerator); }
    public void Remove(string name) { }
  }
}
`

**Comment by pgavlin** [comment]
The latest commit should fix the surface area. Thanks for catching that.

**Comment by davidsh** [comment]
@pgavlin Don't understand your comment.  The contract source code I pasted in the official public definition listed in the closed TFS sources for Contracts\4.0.0.0\System.Net.WebHeaderCollection.

So, are you saying that this PR makes everything good now?  Or are you saying that we need to adjust the public TFS Contracts file?  The latter is something we can't do.

**Comment by pgavlin** [comment]
My original change broke the surface area by removing the explicit implementation of IEnumerable.GetEnumerator(), but my latest commit added that explicit implementation back. The latest commit both fixes the bug and avoids breaking the implementation's surface area vs. the contract.

**Comment by davidsh** [comment]
OK.  I understand now. LGTM as long as build/test is GREEN.

**Comment by stephentoub** [comment]
LGTM

**Pull request merged**
