### PR TITLE
SslStream IDN mapping host name on Windows

### PR DESCRIPTION
**Pull request by krwq**
Fixes https://github.com/dotnet/corefx/issues/28585

Adding IDN mapping as we do on OpenSsl implementation: https://github.com/dotnet/corefx/blob/c533892f2e57940ec9e66616288bf340b75a9217/src/Common/src/Interop/Unix/System.Security.Cryptography.Native/Interop.OpenSsl.cs#L129

First run (commit) was testing if SNI tests will work correctly with the fallback in SniHelper.DecodeString removed (fallback to utf-8 string in case idn unmapping failed)

### CODE REVIEW

**Comment by krwq** [comment]
test OSX x64 Debug Build

**Comment by davidsh** [comment]
Based on this comment from #28585:  

>@karelz I've tested multiple scenarios and HttpClient seems to work correctly (does IDN mapping higher up the stack). I've tested behaviors on .NET Core, full .NET and also compared data send by the browser.
Only people using SslStream directly are affected by this issue. Moving to future.

Doesn't this mean we should remove the, now redundant, IDN mapping in the SocketsHttpHandler stack? Otherwise, we're doing it twice might might have some performance impact?

cc: @geoffkizer

**Comment by stephentoub** [comment]
Yes, if SslStream is getting a fix that makes the code in SocketsHttpHandler duplicative, we should remove it from SocketsHttpHandler as part of this change.

**Comment by krwq** [comment]
@davidsh @stephentoub do we not need to do IDN mapping in order to translate host name (in order to obtain IP address)? If no then we could probably remove it. I do not know much about higher level stack - I can take a look tomorrow

**Comment by davidsh** [comment]
>@davidsh @stephentoub do we not need to do IDN mapping in order to translate host name (in order to obtain IP address)? 

On Windows, you do not want to do IDN mapping (Punnycode) automatically on DNS names before calling the OS-level name resolver APIs.  Windows has different settings based on group policy and registry that allow enterprises to decide when/how DNS mapping uses either IDN (Punnycode) or UTF-8 encoding on the wire.  If our HTTP stack (SocketsHttpHandler for example) is always doing IDN mapping at that layer it would break this ability of the OS stack to make the best decision.

**Comment by krwq** [comment]
@davidsh, I was going to investigate it but got distracted by higher priority issues but it makes sense to move that investigation to later since redundant call for max 64 character string is likely not a problem.

**Comment by krwq** [comment]
test OSX x64 Debug Build

**Pull request merged**
