### PR TITLE
Delete remaining uses of RuntimeThread

### PR DESCRIPTION
**Pull request by jkotas**

### CODE REVIEW

**Comment by stephentoub** [comment]
Another one here?
https://github.com/dotnet/corefx/blob/a10890f4ffe0fadf090c922578ba0e606ebdd16c/src/System.Runtime.InteropServices/src/System/Runtime/InteropServices/HandleCollector.cs#L83

And then presumably System.Threading.Thread also needs to be changed:
https://github.com/dotnet/corefx/blob/facf731986511cb0cc0ceb181b6c7d846afa0743/src/System.Threading.Thread/src/System.Threading.Thread.csproj
since Thread.cs still refers to RuntimeThread?

**Comment by filipnavara** [comment]
Thanks. I actually wanted to do this myself, but I was waiting for Maestro update of `ProjectNTfs` reference in `eng/dependencies.props`. That didn't happen for more than a month though. I already raised the question about how it gets updated on one of the Maestro PRs updating it for `release/3.0` branch. Unfortunately it got unnoticed.

**Comment by stephentoub** [comment]
The UWP_NETNative leg is failing with:
```
D:\a\1\s\src\shims\ApiCompat.proj(67,5): error : MembersMustExist : Member 'System.Runtime.CompilerServices.RuntimeHelpers.PrepareMethod(System.RuntimeMethodHandle)' does not exist in the implementation but it does exist in the contract.
D:\a\1\s\src\shims\ApiCompat.proj(67,5): error : MembersMustExist : Member 'System.Runtime.CompilerServices.RuntimeHelpers.PrepareMethod(System.RuntimeMethodHandle, System.RuntimeTypeHandle[])' does not exist in the implementation but it does exist in the contract.
D:\a\1\s\src\shims\ApiCompat.proj(75,5): error : ApiCompat failed comparing netstandard.dll to uapaot
```

**Comment by jkotas** [comment]
> Maestro update of ProjectNTfs reference in eng/dependencies.props

Filled https://github.com/dotnet/corefx/issues/36186

**Pull request merged**
