### PR TITLE
Update outdated project.lock.json file

### LINKED ISSUE #3691: project.lock.json files are all out of date as of yesterday afternoon.
- git checkout master (no local changes)
- build.cmd
- git status
- Ponder the sea of red as the build process made local changes to every project.lock.json file in the project.

I assume fixing this is just a matter of checking in those changes, but since I don't know what caused it, I'm not blindly sticking my head out either.

### PR DESCRIPTION
**Pull request by weshaggard**
Fixes #3691

### CODE REVIEW

**Comment by weshaggard** [comment]
@dotnet-bot test this please

**Comment by stephentoub** [comment]
@weshaggard, what was the failure?  Can you make sure an issue is opened for it if there isn't one already?

**Comment by weshaggard** [comment]
@stephentoub The error was: http://dotnet-ci.cloudapp.net/job/dotnet_corefx_linux_debug_tst_prtest/3119/console
```
Starting:    System.Collections.Immutable.Tests
System.Collections.Immutable.Tests.ImmutableSortedDictionaryTest.EqualsTest [FAIL]
       Assert.True() Failure
       Expected: True
       Actual:   False
       Stack Trace:
```
I did a rerun of just that leg of the run and it passed but I wanted to see a full green before merging. Yes we should probably file an issue for this but there was really nothing to go on in the logs that I could see that would help diagnose this issue.

**Comment by stephentoub** [comment]
@weshaggard, it's probably https://github.com/dotnet/corefx/issues/780.  We should probably just disable the test.

**Pull request merged**
