### PR TITLE
Don't ignore AsyncMethodBuilderAttribute for GenAPI/APICompat

### LINKED ISSUE #35602: Should GenAPI be removing the AsyncMethodBuilderAttribute attributes?
See https://github.com/dotnet/corefx/pull/35557#discussion_r259772806

This attribute is required to avoid compiler errors (for verifying that async methods return a task-like type), but it is being excluded here:
https://github.com/dotnet/corefx/blob/26b932e3c56702382d13ece010b300d3181d2891/eng/DefaultGenApiDocIds.txt#L53

```text
error CS1983: The return type of an async method must be void, Task, Task<T>, a task-like type, IAsyncEnumerable<T>, or IAsyncEnumerator<T>
```

**Given that behaviour, we should consider removing the exclusion from the list.**

cc @jaredpar, @ericstj, @stephentoub

### PR DESCRIPTION
**Pull request by ericstj**
Fixes #35602

### CODE REVIEW

**Comment by ericstj** [comment]
Hmm, missed a place that needs the attribute, looking.

**Comment by ericstj** [comment]
Now I may have rediscovered why this is suppressed.  APICompat isn't resolving this attribute correctly:

  | Name | Value | Type
-- | -- | -- | --
◢ | impl | {System.Threading.Tasks.ValueTask} | Microsoft.Cci.ITypeDefinition {Microsoft.Cci.MetadataReader.ObjectModelImplementation.NonGenericNamespaceTypeWithoutPrimitiveType}
  | ▶ AliasForType | {Microsoft.Cci.DummyNamespaceAliasForType} | Microsoft.Cci.IAliasForType {Microsoft.Cci.DummyNamespaceAliasForType}
  | Alignment | 0 | ushort
  | ◢ Attributes | {Microsoft.Cci.ICustomAttribute[2]} | System.Collections.Generic.IEnumerable<Microsoft.Cci.ICustomAttribute> {Microsoft.Cci.ICustomAttribute[]}
  | ▶ [0] | {Microsoft.Cci.MetadataReader.ObjectModelImplementation.CustomAttribute} | Microsoft.Cci.ICustomAttribute {Microsoft.Cci.MetadataReader.ObjectModelImplementation.CustomAttribute}
  | ▶ [1] | {Microsoft.Cci.DummyCustomAttribute} | Microsoft.Cci.ICustomAttribute {Microsoft.Cci.DummyCustomAttribute}

Debugged a bit of CCI and found we never hit this line `WinGuessingGame()`:
https://github.com/microsoft/cci/blob/659f31f9736a1e8ded870ee2132d91f87505148e/PEReaderAndWriter/PEReader/PEFileToObjectModel.cs#L3469-L3476

Not surprised that results in this failure...  Something busted in how CCI is decoding the attribute.

**Comment by stephentoub** [comment]
If/when it builds successfully, LGTM :)

**Comment by ericstj** [comment]
At the moment it looks like this is a CCI bug, I could fix it by leveraging SRM similar to what @safern did for the nullable feature, will follow up once I can say for sure.

**Comment by ericstj** [comment]
Closing for now until I can get a workaround into CCI.Extensions

**Pull request closed without merging**
