### PR TITLE
Delete bad crypto directories

### PR DESCRIPTION
**Pull request by bartonjs**
System.Security.Cryptography.Encryption.ECDsa and System.Security.Cryptography.Encryption.ECDiffieHellman were prototype contracts before the crypto contract consolidation.  The directories got populated here during a bulk move of the contract generation from TFS to git.

ECDsa is already part of the S.S.C.Algorithms 4.1.0 package, and ECDH will come
at a later date (it required net462 changes to be API-suitable for x-plat).

Deleting these directories since they don't do anything except cause bad search results.

### CODE REVIEW

**Comment by bartonjs** [comment]
Test Innerloop OSX Debug Build and Test please

(Collection modification exception during package restore? http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/master/job/osx_debug_prtest/72/consoleFull#205152537279494335-f7bd-47d0-8771-8661e00c2db2)

**Comment by stephentoub** [comment]
LGTM

(As for the collection modification during package restore, if you haven't opened an issue for it, sounds like a good thing to do.)

**Comment by bartonjs** [comment]
Thanks, Steve.  Opened #7959 for the weird restore error.  Probably belongs in cli or buildtools, but since I'm not sure which, it stayed local.

**Comment by bartonjs** [comment]
Test Innerloop OSX Debug Build and Test please

**Comment by bartonjs** [comment]
Test Innerloop OSX Debug Build and Test please

(#7961, different file, but same error)

**Pull request merged**
