### PR TITLE
Allow other file handle types

### PR DESCRIPTION
**Pull request by JeremyKuhne**
If using `\\?\` allow handle types via the path constructor that we allow
in handle constructors.

#187 
@zippy1981, @davkean, @ericstj, @ianhays

### CODE REVIEW

**Comment by ericstj** [comment]
Are you sure FileStream will treat those handles correctly?   Also if you make this change you'll need to get the same into desktop for compat.

**Comment by JeremyKuhne** [comment]
@ericstj We allow them already via the handle constructor. I do want to make the same change on desktop as well for > 4.6.2. It fits with the basic paradigm I introduced with 4.6.2 (and here)- you assert know what you're doing if you use `\\?\`. :)

**Comment by ericstj** [comment]
So you'll handle the bugs that come in when folks try to use FileStream for raw disk/volume/device access?  I imagine you could easily brick your system disk if running as admin.  FileStream has so much code that is specific to dealing with files that I don't trust it will do the right thing with other handle types.  At least with handle constructor you realize you are playing with a loaded gun.  What's the motivation for opening this up?

Would like to get some other opinions, /cc @weshaggard @stephentoub

**Comment by JeremyKuhne** [comment]
> So you'll handle the bugs that come in when folks try to use FileStream for raw disk/volume/device access? 

No more than what I would do if they manually opened the handle as told to and passed it in.

> What's the motivation for opening this up?

See the original issue for some cases: #187 

As far as I can tell we're not doing anything that we aren't allowing on Unix, but I'm not quite as familiar with access to devices.

Additionally I don't believe you can access the raw partitions if you aren't running elevated. WinObj seems to suggest that, but I'll experiment nonetheless for completeness.

**Comment by ericstj** [comment]
> I don't believe you can access the raw partitions if you aren't running elevated. 

Correct.  That's why I said running as admin.  I'm not suggesting we're opening up an EOP or anything.  Just that we're making something dangerous very easy to use.

> No more than what I would do if they manually opened the handle as told to and passed it in.

I don't think that is how it will play out.  Folks accept paths as user input.  Suppose someone passes in a device path to an app that never expected to deal with such a path?  Who is now responsible for whatever that app does accidentally by using FileStream on that path?  We are, since we enabled it.  With the handle constructor you don't have this.  I'd feel less nervous about this functionality if it was only permitted if someone explicitly opt-ed into that mode.  EG: explicitly disables the safety on the gun, using the analogy from before.

**Comment by JeremyKuhne** [comment]
> I don't think that is how it will play out. Folks accept paths as user input.
Couldn't the same thing be said for Unix? If you're running as sudo I'm sure all sorts of potential bad can happen with paths, right?

**Comment by JeremyKuhne** [comment]
@ericstj I would also expect this sort of vulnerability to be rampant in the native world if it were so simple, but I haven't heard of it. I assume the OS is more resilient than we might think?

**Comment by ericstj** [comment]
@JeremyKuhne again, I'm not talking about a vulnerability.  I'm talking about wrong, unexpected, and buggy behavior.  With the native APIs they don't pretend to be a high-level abstraction.  They are primitives: open/read/write/seek/close.

Our Unix filesystem implementation doesn't have millions of existing applications, it hasn't even shipped.  You can't use it as precedent.  It may even be the thing that is wrong.

Have you looked at the stream abstraction and FileStream behavior to see if that maps correctly to all handles you can open with paths?  It's possible that it works in most cases, but how do you know?  What tests did you write to validate all those types?  What documentation did we add around the places it doesn't work?  I don't object to exposing primitives, which is actually what #187 is about.  I don't think trying to expose those through existing File API is the right way to do it.

**Comment by JeremyKuhne** [comment]
> I imagine you could easily brick your system disk if running as admin.

To me that looks like you're talking about a vulnerability. Incidentally, from what I understand you can't party on raw disk info this way. I'm investigating further.

> Our Unix filesystem implementation doesn't have millions of existing applications, it hasn't even shipped. You can't use it as precedent. It may even be the thing that is wrong.

It may very well be wrong. I'm concerned that we make people jump through more hoops on Windows than Unix to get things accomplished- I'm not trying to say that Unix is the precedent.

If we create some other indirection by saying "use this and you'll be able to do everything" doesn't it risk eventually become the status quo and mooting the whole thing?

I'm generally concerned about trying too hard to sandbox apps- we never get it right and end up blocking valid scenarios, particularly with paths. We presume too much, imho.

**Comment by ericstj** [comment]
Not trying to sandbox.  Just trying to avoid a bad solution.  FileStream is not a generic IO port.  It is a higher level type.  It's meant to handle a specific type of handle.  Just like PipeStream is made for a specific type of handle.  Just like Socket is made for a specific type of handle.  You wouldn't want either of the others to handle files would you?

Creating something else wouldn't be status quo because it wouldn't work as well with files.  We have specific types that work well with specific handle types.  We could have a generic type that just exposes primitives.

**Comment by JeremyKuhne** [comment]
Some more data:

The physical drive handles report themselves as a file type, so they're _already_ allowed. They are, however, impossible to open if you aren't running elevated (validated). Even if you are elevated, the rules for writing have been restricted since Vista days: https://support.microsoft.com/en-us/kb/942448

**Comment by briangru** [comment]
I think the code changes are correct, but I haven't checked whether they are complete.  There are three things I recommend thinking about:

1) The async code in FileStream may be written to assume it can seek.  Look at code in (at least what used to be) BeginReadCore and BeginWriteCore.  They take a lock and adjust the position pointer by calling SeekCore before starting the async IO operation.  This code may not work if the stream isn't seekable - make sure that doesn't cause an exception.

2) There's a very weak but potential security angle here.  We should require that paths starting with \\\\?\ require unmanaged code permission, or whatever today's security model version of close to full trust is.  The hypothetical risk is someone using these paths to try getting a server to open your COM port or run your printer out of paper.  Now servers shouldn't be dumb enough to take a truly arbitrary file name over the internet and open it.  But that's a mitigation, not a certainty, and prior to this change, servers could assume you won't write to someone's local printer port using FileStream.  It's weak, but it's a remote possibility.  A security check may help partially mitigate this potential risk, assuming that CLR hosts still use a security policy for partial sandboxing of applications.  (Is ASP.NET still using v1 of the CLR hosting interfaces?)
2a)  The surprising thing about device names like this is you can open them in ANY directory, like c:\tmp\lpt1 or c:\program files\Foo\COM2.  Make sure you don't allow this accidentally.  I think you won't, but ensure a test case exists for now and the future.  (Look for BigIOTest in the BCL dev unit tests.)

3) I never tested FileStream with mailslots.  What is a mailslot, you might ask?  A one-directional pipe-like local or cross-computer communication mechanism in Windows.  Looks like they're sort of for the reverse of what you'd use the Reactive Extensions' IObservable for (ie, instead of publish/subscribe, they support multiple writers w/ one reader), with unreliable cross-machine capabilities and a crazy cross-machine limit of 424 bytes.  Your guess is as good as mine as to why they came up with that.  As far as I know, mailslots haven't been used since this article in 2004: [Using Mailslots for IPC](http://www.codeproject.com/Articles/8527/Using-Mailslots-for-Interprocess-Communication).  However, I don't have expert knowledge of every Win32 app ever written, and the MSDN pages on mailslots were rated by people, so presumably some people care.  But, guess what uses \\\\.\ syntax?  
[MSDN Mailslot example](https://msdn.microsoft.com/en-us/library/windows/desktop/aa365160(v=vs.85).aspx)
[Mailslot conceptual docs](https://msdn.microsoft.com/en-us/library/windows/desktop/aa365576(v=vs.85).aspx)
I would consider not supporting mail slots at all.  Check with win32prg to verify their obscurity - maybe there's even SQM data on that.  In my 14 years on the BCL team, no one asked me for them.  If you decide to support them, make FileStream treat them as one-directional pipes (ie, presumably they are non-seekable).  Your decision should be shaped in part by whether you view .NET as a friendly wrapper around Windows, or a platform that will be ported to other OS's.

**Comment by JeremyKuhne** [comment]
@briangru 

Thanks for the feedback!

> We should require that paths starting with \\?\ require unmanaged code permission, or whatever today's security model version of close to full trust is. 

This is the route I took for 4.6.2- \\?\ is allowed for full trust, and \\.\ isn't checked for file stream (again, in full trust)

> The surprising thing about device names like this is you can open them in ANY directory

They always get turned into the \\.\ version of the device syntax when normalized, we'll punt them as a result (as we don't allow the handle unless \\?\, thus avoiding accidental use of a legacy device name). I'll make sure to add tests.

> I never tested FileStream with mailslots.

I did. And it ends up our check for async/sync is busted in this case with reading. :) I've added a second change to call the API that will tell us the state of the file handle (NtQueryInformationFile). I'm following up to see about getting the API allowed for Store apps. In the meantime I've forked for WinRT.

Someone has gone through and done a fair amount of work with enabling pipes. My hope is not necessarily to support pipes, mailslots, etc.- it's more to not be to agressive in blocking non-core usage in order to (1) possibly unblock customers and (2) potentially get feedback that will make the core usage more robust (e.g. the sync/async check).

Fyi: I did a pretty thorough deep dive on paths this past year and put some blog posts detailing how they work- I'd encourage you to take a look and drop me feedback if you see that I'm missing anything. I found out a few of our prior assumptions were incorrect in the process.

https://blogs.msdn.microsoft.com/jeremykuhne/2016/04/21/path-format-overview/
https://blogs.msdn.microsoft.com/jeremykuhne/2016/04/21/path-normalization/
https://blogs.msdn.microsoft.com/jeremykuhne/2016/05/02/dos-to-nt-a-paths-journey/

**Comment by JeremyKuhne** [comment]
Test this please

**Comment by Petermarcu** [comment]
@JeremyKuhne , next steps on this PR?

**Comment by stephentoub** [comment]
@JeremyKuhne, what's the status of this PR?

**Comment by stephentoub** [comment]
Due to inactivity since May, I'm closing this PR.  It can be re-opened if/when appropriate.

**Comment by JeremyKuhne** [comment]
This isn't adding API, it's changing existing API behavior in two ways:

1. We're allowing all file handle types when using `\\?\`
2. We're programmatically checking for overlapped (async) status when constructed with handles

There are 3 types of file handles in Windows: Pipes, Mailslots, and "Normal Files". We allow you to create a FileStream with your own handle, but the checks aren't accurate (blocking Mailslots as a result). The idea here is:

- Fix the broken handle async check
- Not force users to P/Invoke if they want one of the other `CreateFile` types

We're not saying we explicitly supporting mailslots and pipes, we're saying we won't explicitly block them _if_ you are using the `\\?\` syntax. This will allow some currently blocked user scenarios and allow us to move forward if needed.

**Comment by karelz** [comment]
@JeremyKuhne what is status of the PR? Do you have ETA?

**Comment by JeremyKuhne** [comment]
@karelz The associated feature request is under review. No ETA yet.

**Comment by stephentoub** [comment]
Can we please close the PR until we're ready to do something with it?

**Comment by karelz** [comment]
Closing. @JeremyKuhne please reopen when you are ready to move forward on it.

**Pull request closed without merging**
