### PR TITLE
Pass CancellationToken from Http2Connection.SendHeadersAsync to StartWriteAsync

### PR DESCRIPTION
**Pull request by stephentoub**
Fixes https://github.com/dotnet/corefx/issues/39634
cc: @marklio, @geoffkizer 

@danmosemsft, this should be ported to release/3.0 for reliability reasons.

### CODE REVIEW

**Comment by danmosemsft** [comment]
Stress failures meet the bar.

Is there any simple grep feasible for other cases the cancelation token is not passed in thia library?

**Comment by marklio** [comment]
@danmosemsft yes. We are actively working on it. Eta early next week.

**Comment by danmosemsft** [comment]
@marklio thanks for helping with stress!

**Comment by karelz** [comment]
This PR went into master - fixing milestone to 5.0.
It was later ported into release/3.0 branch in PR #39646.

**Pull request merged**
