### PR TITLE
V1.0 catchup and test logging cleanup

### PR DESCRIPTION
**Pull request by nguerrera**
There are effectively two distinct parts to this PR. See individual commits for more context.

1. Cherry pick commits from master to v1.0 that should have gone in to v1.0 in the first place.
 * Addition of System.IO.MemoryMappedFiles
 * Fix for registry tests requiring elevation

2. Remove logging of things that are completely expected and occur on every test run.  This was very badly cluttering the output of build.cmd.

### CODE REVIEW

**Comment by mellinoe** [comment]
Thanks for getting MemoryMapped Files over. I originally created that PR before the 1.0 branch was created and it didn't occur to me to delete it and make a new one once the new branch was up. My mistake.

**Comment by weshaggard** [comment]
@nguerrera Should we find another way to capture the Console output for these tests? Or perhaps switch them to Debug.Output instead? I suspect this maybe useful for someone actually working on these tests and it would be nice to have something people can use and commit for debugging tests.

**Comment by nguerrera** [comment]
@weshaggard I'm not convinced they're all that useful. A lot of them were just sloppy IMHO. I think tests should be silent by design when they pass. If they detect a failure case, they should feel free to log as much info as possible and to wherever is most likely to be seen.

**Comment by weshaggard** [comment]
@nguerrera That's fair. I can live with a principle of only output more diagnostics if the test actually failed. 

Another question how did you pick these changes to cherry-pick? I think there were some others that were on that boundary of having a PR before the v1.0 fork and merged after the fork (commit https://github.com/dotnet/corefx/commit/546ed6b5ce426ef9bd610b6fe397aff153af450b#diff-02389dfac0a172ab80211625efc34318 as an example).

**Comment by nguerrera** [comment]
@weshaggard I picked these two because they needed to precede my work. There was some cleanup needed in MMF tests as well and I hate having to build as admin. ;)

We should look for other changes that need to be cherry-picked, but I think the others aren't urgent from a quick scan. Maybe we can sit down together next week and triage what else might have been missed?

Was there anything else on this PR? Good to merge?

**Comment by weshaggard** [comment]
The changes in the PR look good to me, feel free to merge. I agree we can look at the other changes independently.

**Pull request merged**
