### PR TITLE
[release/3.0] Make WebRequest.GetSystemWebProxy() return a working proxy (#41692)

### PR DESCRIPTION
**Pull request by stephentoub**
Port #41692 to release/3.0

## Description

Libraries like the Azure AMQP lib are using WebRequest.DefaultWebProxy with ClientWebSocket as a way to set the default web proxy.  This works with .NET Framework because ClientWebSocket under the covers on netfx establishes its connection with WebRequest, but on .NET Core it uses different mechanisms.  In fact, with netstandard2.0 APIs, there is no way to specify that ClientWebSocket should use the default proxy.  This breaks such libraries in environments such as those in enterprises where proxies are common and configured implicitly for everyone on the network.

In .NET Core 3.0 we added HttpClient.DefaultProxy, which implements IWebProxy and serves as a full cross-platform implementation for the default proxy.  The change is to make WebRequest.DefaultWebProxy return it, rather than just returning a dummy singleton used only for its reference identity.

## Customer Impact

Libraries like the Azure AMQP library don't work in enterprise environments, or any environments where default proxies are needed.

## Regression?

Yes, from .NET Framework.

## Testing

All existing tests, plus a new test.

## Risk

Our automated testing around proxies isn't great; this change, however, isn't changing any logic to do with actual proxy resolution or discovery, just using the same class in more places.  This change also stops throwing a NotSupportedException on some platforms that was previously thrown, though it's unlikely someone took a real dependency on that.

cc: @Petermarcu

### CODE REVIEW

**Comment by danmosemsft** [comment]
Requested by Azure SDK it looks like.

**Review by davidsh — APPROVED** [review]

**Comment by davidsh** [comment]
>Requested by Azure SDK it looks like.

https://github.com/Azure/azure-sdk-for-net/issues/7899

**Comment by danmosemsft** [comment]
Branch not open for 3.0.2 yet. Please hold. @wtgodbe is handling this for us while @Anipik is out.

**Review by davidsh — APPROVED** [review]

**Comment by maryamariyan** [comment]
Thank you for your contribution. As announced in dotnet/coreclr#27549 this repository will be moving to dotnet/runtime on November 13. If you would like to continue working on this PR after this date, the easiest way to move the change to dotnet/runtime is:
1.	In your corefx repository clone, create patch by running `git format-patch origin`
2.	In your runtime repository clone, apply the patch by running `git apply --directory src/corefx <path to the patch created in step 1>`

**Comment by maryamariyan** [comment]
Please ignore my previous comment. Since this PR is not targeting master branch, no action would be needed here. Thanks.

**Pull request merged**
