### PR TITLE
Clean style in Graphics/GraphicsPath

### PR DESCRIPTION
**Pull request by JeremyKuhne**
Make a consistency pass through Graphics & GraphicsPath.

Plan is to follow up with a change that removes the rest of the unnecessary allocations.

This change focuses on the Windows specific code. Some Unix code will be able to be unified with the Windows code once further changes happen. Rather than reformat the Unix code preemptively, leaving for final follow-up.

### CODE REVIEW

**Comment by stephentoub** [comment]
Probably good to hold off on this until @hughbe's https://github.com/dotnet/corefx/pull/29713 is merged; looks like there could be a fair number of conflicts.

**Comment by JeremyKuhne** [comment]
> Probably good to hold off on this until @hughbe's #29713 is merged; looks like there could be a fair number of conflicts.

Bummer, didn't know @hughbe had a pending PR. @hughbe, do you want to take a look at what I did here and over in #30244? Are you planning to finish your change soon?

**Comment by JeremyKuhne** [comment]
Note that the Linux-musl x64 Debug Build doesn't have any results- didn't think it was worth re-kicking that leg, particularly as #30244 passed (which includes this).

**Comment by JeremyKuhne** [comment]
Merged into #30244

**Pull request closed without merging**
