### PR TITLE
remove preauth handling for digest

### PR DESCRIPTION
**Pull request by geoffkizer**
We're not handling this correctly today.  

Ideally we should have an auth token cache here, and use this to pre-generate the auth request headers for Uris in a protection domain that we've already authenticated to -- whether basic or digest.  I will file a separate issue on this.

For now, just remove the current logic so that our behavior is at least correct, if not ideal.

### CODE REVIEW

**Comment by geoffkizer** [comment]
@dotnet-bot test Outerloop Windows x64 Debug Build please
@dotnet-bot test Outerloop Linux x64 Debug Build please
@dotnet-bot test Outerloop OSX x64 Debug Build please

**Comment by geoffkizer** [comment]
@stephentoub @Priya91

**Comment by stephentoub** [comment]
@Priya91, are there digest tests somewhere?

LGTM, but it'd be good to verify.

**Comment by Priya91** [comment]
> @Priya91, are there digest tests somewhere?

We don't have functional tests, and when I submitted the PR, I did one-time verification of my change using httpbin as the digest server. I'm currently working on converting the fixed statements to use span, and will be adding some unit tests for some of the logic in AuthenticationHelper.Digest.cs.. 

Currently, as far as i know, we do not have actual auth tests in our networking stack, other than basic.

**Comment by stephentoub** [comment]
> I did one-time verification of my change using httpbin as the digest server

Can we add tests that do the same?  If we don't want them to run as part of CI for reliability reasons, they could at least be manual tests.  At present, it seems like you're the only one who knows how to test this class.

**Comment by Priya91** [comment]
> Can we add tests that do the same?

Ok will explore options and include it in the digest PR. Maybe I can copy some digest server code logic from httpbin and have our localhost version.

**Comment by geoffkizer** [comment]
Yeah, it would be great to add some digest logic to our test LoopbackServer and use this to validate our digest handling.

**Comment by Priya91** [comment]
I added a new issue #26375 for tracking, since I may not get to it today.

**Pull request merged**
