### PR TITLE
[release/3.0] HTTP2: fix header corruption issue (#40487)

### PR DESCRIPTION
**Pull request by eiriktsarpalis**
Porting the HPACK bugfix from #40487 to the 3.0 branch.

### CODE REVIEW

**Comment by eiriktsarpalis** [comment]
## Description

Fixes a data corruption bug in the SocketsHttpHandler http/2 HPACK encoder implementation. See #40459 for more details.

## Customer Impact

Occasional data corruption in request headers specifying more than one values.

## Regression?

No.

## Risk

Low.

**Comment by scalablecory** [comment]
@ericstj will you be bringing this to shiproom? do you need @dotnet/ncl presence?

**Comment by ericstj** [comment]
I'll be in Tactics on Tuesday to represent it, but it may be reviewed earlier over email.

**Comment by eiriktsarpalis** [comment]
It's ready, yes.

**Comment by eiriktsarpalis** [comment]
@ericstj Looking at the test history for 
[System.Data.Tests.DataSetReadXmlSchemaTest.LocaleOnRootWithoutIsDataSet](https://dev.azure.com/dnceng/public/_build/results?buildId=321069&view=ms.vss-test-web.build-test-results-tab&runId=9299382&resultId=101628&paneView=history) it would seem like it's a one-off failure, only impacting PR builds of the time. The failures are timeouts. Perhaps an infrastructure hiccup? 

I'm not sure what the [System.Data.Common.Tests Work Item](https://dev.azure.com/dnceng/public/_build/results?buildId=321069&view=ms.vss-test-web.build-test-results-tab&runId=9299382&resultId=102666&paneView=history) test is. It's always failing and doesn't seem to correspond to a test in the codebase.

**Pull request merged**
