### PR TITLE
Add a lock-free fast path to HttpConnectionPool for getting an available connection

### PR DESCRIPTION
**Pull request by stephentoub**
Avoid taking a lock to get an available connection when there is a valid connection to be had in the connection pool. On my machine on a microbenchmark that uses HttpClient.GetAsync to make lots of small, concurrent requests to a localhost server, this appears to provide around a 10% throughput win.

@geoffkizer, could you try it out and let me know what you see with your test?

@aviviadi, @ayende, can you please also try it and confirm that it addresses your contention concerns from #31799?

@mikeharder, I believe you had a benchmark where you thought contention was showing up as an issue.  Could you try this with your benchmark as well?

Fixes https://github.com/dotnet/corefx/issues/31799

### CODE REVIEW

**Comment by geoffkizer** [comment]
It seems to me there's a race with this approach, when MaxConnectionsPerServer is set.

Assume MCPS=1.
(1) Thread A issues a request. A new connection is created. Connection count = 1.
(2) Thread B issues a request. It looks for idle connections but doesn't find any.
(3) Thread A completes its request and returns the connection to the idle connection queue. Connection count is still 1.
(4) Thread B now takes the lock. Since we are at the connection limit, it's going to enqueue a ConnectionWaiter. However, there's no in-use connection currently, so the waiter won't be completed, even though there's an idle connection.

**Comment by geoffkizer** [comment]
Also, we've changed from LIFO to FIFO for idle connections, right? This seems bad. I think we want LIFO semantics here so that the "'freshest" connections are reused first.

**Comment by stephentoub** [comment]
> It seems to me there's a race with this approach

Yes, though it's not fundamental to the approach: I'm just missing another check of the queue once the lock has been taken.  I'll add that.

**Comment by stephentoub** [comment]
> Also, we've changed from LIFO to FIFO for idle connections, right? This seems bad. I think we want LIFO semantics here so that the "'freshest" connections are reused first.

Your concern is that we may keep more connections alive than needed, by touching ones that would otherwise get collected?  Or that we'd get some kind of cache benefit from the memory associated with a connection being reused more often?

**Comment by geoffkizer** [comment]
> Your concern is that we may keep more connections alive than needed, by touching ones that would otherwise get collected? Or that we'd get some kind of cache benefit from the memory associated with a connection being reused more often?

Both, but mainly the former. Also, recently used connections are less likely to have been closed by the server due to server idle timeout.

**Comment by stephentoub** [comment]
> Also, recently used connections are less likely to have been closed by the server due to server idle timeout.

That's true, although there's a flip side to it as well: LIFO will cause us to touch more connections, thereby keeping more connections open, thereby reducing subsequent chances we'll need to pay the costs of creating a new connection because it was torn down by the server.

Regardless, I understand the concern.  I'll need to think about it.  LIFO lock-freedom is hard.

**Comment by geoffkizer** [comment]
I'm not convinced we really need to be lock-free here. The main problem is the expensive kernel calls under the lock -- EnsureReadAheadAndPollRead in particular, possibly the connection creation as well (though this is much less common). Simply moving this outside the lock should be a significant win.

Having a lock-free data structure for idle connections could be an additional win as well -- or not; I don't know.

**Comment by stephentoub** [comment]
> Simply moving this outside the lock should be a significant win.

Maybe.  We can try.  There are downsides, too, though, namely that if it fails, we then need to rinse and repeat, re-entering the lock, which could put even more contention pressure on the lock.

**Comment by geoffkizer** [comment]
Also, we call EnsureReadAheadAndPollRead under the lock in ReturnConnection as well. We only call this when there's a waiter, so it's less common; but we should still avoid this if possible.

**Comment by geoffkizer** [comment]
> Maybe. We can try. There are downsides, too, though, namely that if it fails, we then need to rinse and repeat, re-entering the lock, which could put even more contention pressure on the lock.

Yes, that's certainly possible, and if we see this then pursuing a lock-free approach seems worthwhile.

I guess my main point here is that we should first ensure we are not doing expensive operations under the lock. This may be enough to address the issue completely. If not, we can additionally pursue a lock-free structure for idle connections. Thoughts?

**Comment by stephentoub** [comment]
Closing in favor of #32495

**Pull request closed without merging**
