### PR TITLE
Implement GetECDsaPrivateKey() on Unix.

### PR DESCRIPTION
**Pull request by AtsushiKan**
cc @bartonjs

### CODE REVIEW

**Comment by bartonjs** [comment]
The ECDsa certificate tests can probably have their PlatformSpecific attribute removed now, no?

https://github.com/dotnet/corefx/blob/master/src/System.Security.Cryptography.X509Certificates/tests/PublicKeyTests.cs#L145 (and others)

**Comment by AtsushiKan** [comment]
The PublicKey extension method is still RSA-only on Linux. Given that we punted on Import/Export for ECDsa, I’m not sure there is a feasible way to get that implemented now.

**Comment by bartonjs** [comment]
Oh, hm. those tests actually use CNG knowledge.

What about something like

```C#
byte[] expectedSignature = "steal this from the implementation";
byte[] data = ByteUtils.RepeatByte(0x37, 161);
byte[] signature;

using (X509Certificate2 cert = new X509Certificate2(TestData.ECDsa384Certificate))
using (ECDsa ecdsa = cert.GetECDsaPrivateKey())
{
    signature = ecdsa.SignData(words, go here);
}

Assert.Equal(expectedSignature, signature);
```

**Comment by AtsushiKan** [comment]
We’d have to build a PFX or store a private key on the disk (not nice behavior for a unit test) to do private key testing (which is why the state of private key testing in X509.Tests is pretty sad right now in general.)

What’s our current state regarding PFX support in Unix?

**Comment by AtsushiKan** [comment]
Also, we couldn’t compare the sigs byte for byte anyway. Intentional non-determinism and all…

**Comment by bartonjs** [comment]
If the PFX contains exactly one cert and it has a private key, things are great.  The PFX bytes could be stored in TestData.

Except, now that I've said PFX, the test would likely want to be disabled on Windows, because we run into key concurrency problems there frequently (tests which use PFX-private keys need to all be put in one class to prevent concurrent execution).

So, sigh; I guess there's not really a good way to test this right now.

**Comment by bartonjs** [comment]
Oh yeah, silly non-deterministic signatures :)

**Comment by bartonjs** [comment]
As for GetECDsaPublicKey, I think that you can get there with `EVP_PKEY* X509_PUBKEY_get(X509_PUBKEY*)`.  Probably want to just add it to the native interop library as `EVP_PKEY* GetX509EvpPublicKey(X509* x509)`.  Then you can just unpack the EC_KEY the same way you did for the private key here.

If we don't have an open issue to remind us that we don't have GetECDsaPublicKey on Unix, please open one.

**Comment by bartonjs** [comment]
Code LGTM.  Oh, please also open an issue saying we have no GetECDsaPrivateKey tests on Linux.

**Pull request merged**
