### PR TITLE
Refactor and tests for MS.CSharp's GetBestAccessibleType()

### PR DESCRIPTION
**Pull request by JonHanna**
* Rearrange `GetBestAccessibleType` to avoid repeated tests & recursion.

Keep all code for `AggregateType` in the first branch for `AggregateType`, etc.

* Use `ContextForMemberLookup` instead of `BindingContext` for best accessible

The `BindingContext` is only used for this property, which it hits repeatedly, so just pass it in instead.

* Don't use intermediate variables for `out` parameters.

If just going to assign it to something anyway.

* Return type directly from `GetBestAccessibleType()`

The type passed in can never be `ParameterModifierType` or `PointerType` so the case where false is returned can never be hit. Change to returning the accessible type directly, and remove branches for false returns.

* Add tests for getting best accessible type.

### CODE REVIEW

**Comment by JonHanna** [comment]
Test UWP CoreCLR x64 Debug Build
Test Windows x64 Debug Build
Test Windows x86 Release Build
(CI issue, now resolved)

**Comment by JonHanna** [comment]
Test this please.

**Comment by JonHanna** [comment]
Test NETFX x86 Release Build

**Comment by JonHanna** [comment]
Test NETFX x86 Release Build (CI Issue fixed).

**Comment by JonHanna** [comment]
CC @VSadov @OmarTawfik

**Comment by OmarTawfik** [comment]
@JonHanna can you please post the links to the failed CI runs when it fails for non-PR-related reasons in the future? it is sometimes useful when the infra team hunts intermittent failures like this,

**Comment by VSadov** [comment]
Thanks!!

**Comment by JonHanna** [comment]
@OmarTawfik sorry, I should have been clearer in the comments there. I'd opened issues with links to the runs as they were persistent problems, by "CI Issue fixed" I meant they were issues that had been reported, dealt with, and for which fixes had been merged into master, so the benefit of the links had passed.

**Pull request merged**
