### PR TITLE
Prohibit pointer types from variable and parameter expressions.

### LINKED ISSUE #8074: Lamda expressions can have pointer types with high arity but not with low.
The following works:

```C#
Expression.Lambda(
    Expression.Constant(3L),
    Enumerable.Range(0, 20).Select(_ => Expression.Variable(typeof(int).MakePointerType()))
);
```

However, the following does not:

```C#
Expression.Lambda(
    Expression.Constant(3L),
    Enumerable.Range(0, 2).Select(_ => Expression.Variable(typeof(int).MakePointerType()))
);
```

The difference being whether the arity is higher than the highest-arity `Func<>` delegate or not.

Neither are likely to be useful, as pointer types hit snags elsewhere, but if the former is allowed, then so should be the latter.

### PR DESCRIPTION
**Pull request by JonHanna**
Fixes #8074.

Possibility of backward-compatibility issue discussed at that issue.

### CODE REVIEW

**Comment by JonHanna** [comment]
Test Innerloop OSX Release Build and Test
Test  Innerloop Windows_NT Release Build and Test

**Comment by VSadov** [comment]
It feels it is probably better to just disallow the pointer variables.
They are rather useless since you cannot dereference them.

note that as intermediate values, pointers seems to be ok.
The following compiles and runs on desktop:
```C#
            Expression<Func<string>> e = () => new IntPtr(new IntPtr().ToPointer()).ToString();
            System.Console.WriteLine(e.ToString());
```
I wonder if that works in interpreter or whether that could result in us needing a variable of a pointer type.

**Comment by JonHanna** [comment]
My impression at the time of looking at this was that intermediate pointers didn't work in interpreter, which was one of the reasons for taking this approach rather than fixing the support for defining pointer-taking lambdas (though #8122 probably does that anyway).
For one thing, the interpreter boxes all intermediate values, which won't work with pointers.

**Comment by VSadov** [comment]
Yes, considering that pointers cannot be boxed, very few scenarios would be possible in compiled case and none in interpreted case.

It seems better to just disallow pointer variables.

**Comment by VSadov** [comment]
LGTM

**Comment by JonHanna** [comment]
It's interesting to consider how to design for full support for pointers, but there's probably few merits beyond it being interesting to doing so.

**Pull request merged**
