### PR TITLE
Reenable String.Concat empty array test assert

### PR DESCRIPTION
**Pull request by stephentoub**

### CODE REVIEW

**Comment by stephentoub** [comment]
Test Innerloop OSX Debug Build and Test please
Test Innerloop OSX Release Build and Test please
(build machines went offline)

**Comment by ianhays** [comment]
LGTM.

**Comment by stephentoub** [comment]
Test Innerloop OSX Debug Build and Test please
Test Innerloop OSX Release Build and Test please

**Comment by stephentoub** [comment]
Test Innerloop OSX Debug Build and Test please
Test Innerloop OSX Release Build and Test please

**Comment by stephentoub** [comment]
Thanks, Ian.

**Pull request merged**
