### PR TITLE
ProtectedData: add DataProtectionScope parameter check

### PR DESCRIPTION
**Pull request by MaximLipnin**
Adds DataProtectionScope parameter value check to Protect and Unprotect methods.

### CODE REVIEW

**Comment by stephentoub** [comment]
Thanks, but why?  This check doesn't exist on the .NET Framework as far as I can tell, so this is introducing an exception that wasn't there before.

**Comment by stephentoub** [comment]
cc: @bartonjs

**Comment by MaximLipnin** [comment]
During the import ProtectedData type from CoreFX to Mono I faced a couple of failing unit test which check this parameter and expect ArgumentException on wrong value. There is no exactly the same check in .Net Framework but there are similar ones in other places (like [here](https://referencesource.microsoft.com/#mscorlib/microsoft/win32/registrykey.cs,1164)). CoreFX also has similar validations. So I thought it'd be acceptable for you.

**Comment by bartonjs** [comment]
> It sounds like the bug is actually in Mono

It's definitely in a grey area.

If someone wrote `ProtectedData.Protect(data, entropy, (DataProtectionScope)3)` then NetFX would have done a thing.

If we added more enum values in the future then their code would eventually encounter a behavioral difference.

---

If I had expectation of this API changing within the next 5-10 years then I'd say that adding the "don't give me unmapped states" check was reasonable future-proofing.   Since it seems pretty well done and set, I think that adding an exception in CoreFX that isn't present in NetFX is just a source of aggravation during porting.

So I don't know if I'd say that the "bug" is in Mono over NetFX, but I think that in this specific case the better answer is that Mono relax their tests instead of us constrain CoreFX.

**Comment by stephentoub** [comment]
@MaximLipnin, thanks for the interest in changing this.  Given the feedback, I'm going to close this.

**Comment by MaximLipnin** [comment]
@stephentoub @bartonjs Thank you for the clarification! I will resolve it on Mono side.

**Pull request closed without merging**
