### PR TITLE
Update UnsupportedOperatingSystems property on csproj to UnsupportedPlatforms based on the run-test.sh change.

### PR DESCRIPTION
**Pull request by Priya91**

### CODE REVIEW

**Comment by stephentoub** [comment]
Some of these were already addressed by https://github.com/dotnet/corefx/commit/2a6dee04a74f270619ca14accdea653200e9a48d, right?

**Comment by Priya91** [comment]
@stephentoub These test projects are not skipped on linux. Is that the expected change?

**Comment by stephentoub** [comment]
For the projects where @Maxwe11's change removed the unsupported attribute, that was by design: those projects are now fine to run their tests on Linux.  I think the only libraries that should still be marked as UnsupportedPlatform on Linux are Microsoft.Win32.Registry and System.Dynamic.Runtime, the latter of which is just a moment-in-time issue until a runtime assert is addressed.

**Comment by Priya91** [comment]
@stephentoub : sounds good. I'll close this PR :)

**Pull request closed without merging**
