### PR TITLE
Add Documentation/README link to auto-update documentation

### PR DESCRIPTION
**Pull request by dagood**
Adds a link in the readme to https://github.com/dotnet/buildtools/blob/master/Documentation/dependency-auto-update.md. For any comments on the auto-update doc itself, use https://github.com/dotnet/buildtools/pull/1088.

@weshaggard @markwilkie

### CODE REVIEW

**Comment by weshaggard** [comment]
What about https://github.com/dotnet/corefx/blob/master/Documentation/project-docs/project-nuget-dependencies.md? Do you want to remove that now or at least update it to point to the buildtools doc?

**Comment by dagood** [comment]
Hmm, that actually covers a bit of area not covered by the auto-PR docs (verification errors and how to resolve them) so I want to keep the info. Thinking about it, the auto-PR docs are actually a subsection of "Project NuGet Dependencies", so I'll move this whole chunk to buildtools, update the corefx link, and remove the doc from corefx.

**Comment by stephentoub** [comment]
@mmitche, another "error processing the xunit test results" failure:
https://ci.dot.net/job/dotnet_corefx/job/master/job/centos7.1_debug_prtest/1463/

**Comment by dagood** [comment]
Now that buildtools/1120 is merged, the links here are ok.

**Pull request merged**
