### PR TITLE
Remove problematic ArrayPool usage

### PR DESCRIPTION
**Pull request by stephentoub**
We decided in the design meeting today that we should only be using ArrayPool in corefx itself in places where we can guarantee the types/methods won't cause corruption, even if due to misuse. Some of the usage we've already put in place doesn't meet this bar and needs to be removed.   For example, we use ```ArrayPool<byte>.Shared``` in a special CopyToAsync implementation, but in doing so we hand a buffer from the pool out to the constiuent streams, and a poorly behaving stream could end up holding on to the buffer even after CopyToAsync has returned to the pool, such as if a Stream.WriteAsync implementation had a bug and completed the returned task before it was actually done with the buffer.

This commit removes all such usage (which we only very recently added).  There is one usage of ```ArrayPool<char>.Shared``` left in corefx, in ZipFile, which meets the bar, as the buffer is never handed out to code outside of the class, is used in a scoped manner on the stack, etc.

cc: @sokket, @KrzysztofCwalina, @jkotas 
Fies #6472

### CODE REVIEW

**Comment by sokket** [comment]
It makes me sad that these perf gains have to go away, but LGTM

**Comment by KrzysztofCwalina** [comment]
We should consider adding similar APIs that just take an array parameter to be used as the intermediate buffer.

**Comment by jkotas** [comment]
LGTM

**Comment by stephentoub** [comment]
> We should consider adding similar APIs that just take an array parameter to be used as the intermediate buffer.

Yes, or the pool to use.  Can you open an issue, @KrzysztofCwalina?

> LGTM

Thanks for the reviews.

**Pull request merged**
