### PR TITLE
[release/2.1] Fix Timer rooting issue with SocketsHttpHandler

### PR DESCRIPTION
**Pull request by stephentoub**
Port https://github.com/dotnet/corefx/pull/32793 to release/2.1.

Fixes https://github.com/dotnet/corefx/issues/31262

### CODE REVIEW

**Comment by stephentoub** [comment]
**Description**
We have an unexpected rooted cycle that's keeping an HttpConnectionPoolManager and all of its state alive indefinitely if the HttpClient/SocketsHttpHandler isn't Disposed. HttpConnectionPoolManager creates a "cleaning timer" that runs every now and then in order to remove stale connection pools that are no longer needed. In order to do that, the Timer is passed the HttpConnectionManagerPool as state. That normally wouldn't be a problem, except that the HttpConnectionManagerPool then stores a strong reference to the Timer, creating a cycle: Timer -> TimerHolder -> TimerQueueTimer -> HttpConnectionPoolManager -> Timer. The TimerQueueTimer is rooted by the underlying timer implementation, with it stored in a static array. And TimerHolder has a finalizer that disposes of the Timer, but it's being kept alive as part of the cycle. To break the cycle, we give the Timer a weak reference (rather than strong reference) to the HttpConnectionPoolManager.

**Customer Impact**
If a developer writes code like:
```C#
string result = await new HttpClient().GetStringAsync(url);
```
creating an HttpClient with the default options and not disposing of the HttpClient, it'll end up leaking some resources indefinitely.  Over time this can grow into a significant memory leak.  It also ends up keeping a connection open until the server decides to close it.

**Regression?**
Yes, from .NET Core 2.0.

**Risk**
Minimal.  The fix is very localized, and just passes a weak rather than strong reference to the Timer that was involved in the cycle.

**Comment by stephentoub** [comment]
@dotnet-bot test OSX x64 Debug Build please

**Comment by vivmishra** [comment]
Need more info for 2.1 but approved for 2.2.

**Comment by stephentoub** [comment]
> Need more info for 2.1

What info is needed?

**Comment by stephentoub** [comment]
> approved for 2.2

I opened https://github.com/dotnet/corefx/pull/32845 for release/2.2.

**Comment by karelz** [comment]
The additional info was meant "more customer reports".

As high memory usage, it is something we would take (also taking into account SocketsHttpHandler is brand new in 2.1).
But given it is not-recommended scenario for HttpClient (not disposing it + creating HttpClient per request/often), shiproom didn't think it will impact too many customers in a meaningful way to justify the risk in 2.1 LTS servicing without further evidence.

Closing the PR until we have more reports/upvotes on the problem in 2.1.

**Comment by stephentoub** [comment]
Thanks, @karelz.

**Comment by jarlehal** [comment]
I think this issue apply to the scenario when sharing HttpClient (not disposing) also. We have a service that uses 7 HttpClients but handles alot of requests. Over time the service consumes more and more memory. A heap snapshot shows a constantly growing number of HttpConnectionPoolManager objects. Any change of getting this PR merged? We tried 2.2, but since we run on k8s/linux we ran into "System.Net.Http.HttpRequestException: Address already in use" issues of #37044

**Comment by karelz** [comment]
@jarlehal you are first additional customer to ask for this in 8 months. That is not high-enough demand.

#37044 is unfortunate, but it should in general not be a reason to not upgrade to 2.2 -- we need to address that problem (i.e. somehow reproduce and root cause), not use it as an argument to port more changes to 2.1. That will not fly.
If you can, please work with us on the k8s/linux item primarily.

**Comment by karelz** [comment]
3.0 is option, or 3.1 which should be released in November.
Let's move porting discussion into the issue - PR is not the right place.

**Pull request closed without merging**
