### PR TITLE
Add perf test to measure Memory.Span.Slice vs. Memory.Slice.Span

### PR DESCRIPTION
**Pull request by ahsonkhan**
cc @stephentoub, @KrzysztofCwalina, @jkotas 

image

### CODE REVIEW

**Comment by ahsonkhan** [comment]
@dotnet-bot test Linux x64 Release Build

**Comment by ahsonkhan** [comment]
@dotnet-bot test Linux x64 Release Build

**Comment by KrzysztofCwalina** [comment]
Good information to have!

**Comment by AndyAyersMS** [comment]
You might want to accumulate results in a local and store back to the volatile static outside the timing loop.

Also would be good to take a look at why the perf is so different.

**Comment by ahsonkhan** [comment]
Any ideas what is causing this intermittent failure in System.Net.Security.Tests for Linux?

@davidsh, @Priya91, @wfurt

https://mc.dot.net/#/user/ahsonkhan/pr~2Fjenkins~2Fdotnet~2Fcorefx~2Fmaster~2F/test~2Ffunctional~2Fcli~2F/979fc46e68545bece6c940e1e9b9d657e908d323/workItem/System.Net.Security.Tests/wilogs
2017-10-21 00:52:43,216: INFO: proc(54): run_and_log_output: Output:    System.Net.Security.Tests.SslStreamEKUTest.SslStream_ClientEKUServerAuth_Fails [SKIP]
2017-10-21 00:52:43,216: INFO: proc(54): run_and_log_output: Output:       Condition(s) not met: \"IsRootCertificateInstalled\"
2017-10-21 00:52:45,556: INFO: proc(54): run_and_log_output: Output: 
2017-10-21 00:52:45,556: INFO: proc(54): run_and_log_output: Output: Unhandled Exception: 
2017-10-21 00:52:45,556: INFO: proc(54): run_and_log_output: Output:    Cannot print exception string because Exception.ToString() failed.
2017-10-21 00:52:47,262: INFO: proc(54): run_and_log_output: Output: /home/helixbot/dotnetbuild/work/252b9a6b-9b22-45d6-ba16-5e153ded98a2/Work/b38a49b6-de7e-49c0-b222-58737e380e48/Unzip/RunTests.sh: line 87:  1866 Aborted                 (core dumped) $RUNTIME_PATH/dotnet xunit.console.netcore.exe System.Net.Security.Tests.dll -xml testResults.xml -notrait Benchmark=true -notrait category=nonnetcoreapptests -notrait category=nonlinuxtests -notrait category=OuterLoop -notrait category=failing

**Comment by davidsh** [comment]
Might be related to #24775.

There have been a lot of code changes in System.Net.Security with @Priya91 changes for ALPN and other SslStream changes. So, I think people are aware that the code needs more stabilization.

cc: @karelz @stephentoub

**Comment by ahsonkhan** [comment]
> You might want to accumulate results in a local and store back to the volatile static outside the timing loop.

@AndyAyersMS, can you please explain what the benefit of doing that would be? How costly is writing to a volatile static? It looked like a couple of extra xors in the disassembly.

**Comment by AndyAyersMS** [comment]
The benchmark execution order in xunit-perf is not fixed (Microsoft/xunit-performance#238). I have seen cases where over time the burden for class init checks shifts from one benchmark to another somewhat unpredictably and this leads to what looks like odd shifts in perf with no obvious cause.

So, best to avoid any such static accesses unless they are intentionally part of your benchmark.

**Comment by ahsonkhan** [comment]
> Also would be good to take a look at why the perf is so different.

For one thing, Memory is a larger struct than Span and so the constructor does some more work (and Slice will create a new struct, either Memory or Span). Memory.Slice also has an extra if check for index < 0.

https://github.com/dotnet/coreclr/blob/master/src/mscorlib/shared/System/Span.cs#L371
```C#
return new Span<T>(ref Unsafe.Add(ref _pointer.Value, start), _length - start);
```
https://github.com/dotnet/coreclr/blob/master/src/mscorlib/shared/System/Memory.cs#L140-L142
```C#
            if (_index < 0)
                return new Memory<T>((OwnedMemory<T>)_arrayOrOwnedMemory, (_index & RemoveOwnedFlagBitMask) + start, _length - start);
            return new Memory<T>((T[])_arrayOrOwnedMemory, _index + start, _length - start);
```

**Pull request merged**
