### PR TITLE
Fixing test CurrencyNegativePattern_Get() on distro Ubuntu18.04

### LINKED ISSUE #27022: [Ubuntu 18.04] Test failed: System.Globalization.Tests.NumberFormatInfoCurrencyNegativePattern / CurrencyNegativePattern_Get
Fails on newly added distro: Ubuntu 18.04

Failure:
```
Assert.Contains() Failure
Not found: 1
In value:  Int32[] [8]
```

## History of failures

Day | Build | Details
-- | -- | --
2/10 | 20180210.01 | [link](https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Fcli~2F/build/20180210.01/workItem/System.Globalization.Tests/analysis/xunit/System.Globalization.Tests.NumberFormatInfoCurrencyNegativePattern~2FCurrencyNegativePattern_Get(locale:%20%5C%22fa-IR%5C%22))
2/10 | 20180210.03 | [link](https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Fcli~2F/build/20180210.03/workItem/System.Globalization.Tests/analysis/xunit/System.Globalization.Tests.NumberFormatInfoCurrencyNegativePattern~2FCurrencyNegativePattern_Get(locale:%20%5C%22fa-IR%5C%22))

### PR DESCRIPTION
**Pull request by maryamariyan**
From class/project System.Globalization.Tests.NumberFormatInfoCurrencyNegativePattern

Fixes #27022

CC: @danmosemsft @krwq

### CODE REVIEW

**Comment by maryamariyan** [comment]
FYI, this is a cherry-pick of https://github.com/dotnet/corefx/pull/27035

**Comment by tarekgh** [comment]
@danmosemsft does @maryamariyan need ship room approval for porting test fixes?

**Comment by tarekgh** [comment]
#21425

**Comment by krwq** [comment]
Thanks @maryamariyan!

**Pull request merged**
