### PR TITLE
Key item added to KeyNotFoundException

### LINKED ISSUE #5188: Add key value to KeyNotFoundException
It would be great if, for example, when dictionary throws KeyNotFoundException, we can have the searched key in the exception for some traces

### PR DESCRIPTION
**Pull request by Anipik**
Fix #5188
coreclr pr - https://github.com/dotnet/coreclr/pull/15201

### CODE REVIEW

**Comment by danmosemsft** [comment]
You have a test failure. @brianrob should review event source.
LGTM otherwise

**Comment by Anipik** [comment]
@dotnet-bot help

**Comment by Anipik** [comment]
@dotnet-bot test NETFX x86 Release Build

**Comment by Anipik** [comment]
@dotnet-bot test Packaging All Configurations x64 Debug Build

**Comment by danmosemsft** [comment]
@Anipik the test failure is real
```
D:\j\workspace\windows-TGrou---2a8f9c29\src\Microsoft.Diagnostics.Tracing.EventSource.Redist\shared\TraceLogging\EventPayload.cs(56,75): error CS0103: The name 'SR' does not exist in the current context [D:\j\workspace\windows-TGrou---2a8f9c29\src\Microsoft.Diagnostics.Tracing.EventSource.Redist\src\Microsoft.Diagnostics.Tracing.EventSource.Redist.csproj]
```
When you see a build failure you can't figure out immediately, reproduce it locally. For example, this is for NETFX, so from the root you would do `build -framework:netfx` or from src\Microsoft.Diagnostics.Tracing.EventSource.Redist you could do `msbuild /p:targetgroup=netfx` if you're built netfx before.

You should quickly be able to see what the error is and fix it. Hint: look at the compilation command line to find where SR.cs is coming from, and look at it.

**Comment by danmosemsft** [comment]
Wait for https://github.com/dotnet/corefx/pull/25490 to go in then rerun tests.

**Pull request merged**
