### PR TITLE
Add archiving all files in corefx for coreclr JIT stress testing

### PR DESCRIPTION
**Pull request by sejongoh**
Archive all files in corefx directory, so that coreclr JIT stress tests can use them.

### CODE REVIEW

**Comment by sejongoh** [comment]
@dotnet-bot test ci please.

**Comment by sejongoh** [comment]
@mmitche Could you please review the changes? The changes archive .\corefx directory to corefx.pack. I am planning to update coreclr/netci.groovy to enable corefx testing with JitStress modes on Windows which runs corefx/build.cmd with the runtime override option.

**Comment by sejongoh** [comment]
@dotnet-bot test Innerloop OpenSUSE13.2 Release Build and Test

**Comment by sejongoh** [comment]
@dotnet-bot test Innerloop OSX Debug Build and Test

**Comment by sejongoh** [comment]
@dotnet-bot test Innerloop OpenSUSE13.2 Release Build and Test

**Comment by mmitche** [comment]
@sejongoh How big is the pack file?  I would rather just sync multiple repos in coreclr if it's large.  The bin.pack will be contained within the corex.pack.

**Comment by sejongoh** [comment]
The pack file is large. As mmitche recommended offline, I will work on a way that coreclr testing gets corefx from git and build/test it.

**Comment by stephentoub** [comment]
@dotnet-bot test this please

**Pull request closed without merging**
