### PR TITLE
Add SignatureDecoder to System.Reflection.Metadata

### PR DESCRIPTION
**Pull request by nguerrera**
See #262 for API review and design information.

For those who followed the evolution in the dev branch, #4769 shows just the last round of design changes.

cc @tmat

### CODE REVIEW

**Comment by nguerrera** [comment]
Tagging @davkean

**Comment by nguerrera** [comment]
@dotnet-bot test this please (was green, not sure why it re-ran, OS X debug run got aborted)

**Comment by nguerrera** [comment]
@terrajobst Can I merge this pre-API review and fix things up with a follow-up?

**Comment by nguerrera** [comment]
I'll rebase away that merge before pushing, but wanted to keep @tmat's commit-specific comments visible and also needed the fix from master to unbreak initellisense.

**Comment by nguerrera** [comment]
Rebased away merge. Make note of @tmat's review on the original commit: 7d176ebcffbd39edee5668044f9424b98f856c27

**Comment by nguerrera** [comment]
@dotnet-bot Test Innerloop CentOS7.1 Debug Build and Test please (#4628)

**Comment by nguerrera** [comment]
@dotnet-bot Test Innerloop Windows_NT Release Build and Test please (#5234)

**Comment by nguerrera** [comment]
@dotnet-bot Test Innerloop Windows_NT Debug Build and Test (#5236)

**Comment by nguerrera** [comment]
@dotnet-bot Test Innerloop Windows_NT Release Build and Test please (#5234)

**Comment by nguerrera** [comment]
@CIPop I'm hitting #5234 over and over again and yet there's nothing sockets-related in this PR. Ideas?

**Comment by nguerrera** [comment]
@dotnet-bot Test Innerloop Windows_NT Release Build and Test please (#5234)

**Comment by nguerrera** [comment]
@dotnet-bot Test Innerloop Windows_NT Debug Build and Test please (#5234)

**Comment by CIPop** [comment]
> @CIPop I'm hitting #5234 over and over again and yet there's nothing sockets-related in this PR. Ideas?

The test is failing to validate a checksum although this is an UDP socket. I'm not sure if this points out some issue within the implementation or if the tcp driver just dropped a few of the packets because we're running too many tests on the CI machines.

Analysis of such issues based on CI system failures is blocked by #4152.

/cc: @pgavlin 

To unblock, please feel free to disable the tests.

**Comment by nguerrera** [comment]
Merging to unblock upstream work. #262 tracks tomorrow's API review and follow-up.

**Pull request merged**
