### PR TITLE
remove references to System.Reflection.Emit.Xxx for UAP builds of System.Linq.Expressions

### PR DESCRIPTION
**Pull request by VSadov**
remove references to System.Reflection.Emit.Xxx for UAP builds of System.Linq.Expressions

### CODE REVIEW

**Comment by joperezr** [comment]
This broke the uapaot vertical build. We can't remove those references yet or else we will be missing a bunch of in System.Reflection.Emit. First thing we have to do is to have System.Reflection.Emit actually fulfilling the contract, and then only reference that from Expressions.

**Comment by joperezr** [comment]
I'll revert this now to fix uapaot build

**Comment by danmosemsft** [comment]
Sorry. Did I somehow hit merge without a fully green CI?

**Comment by danmosemsft** [comment]
Oh - my guess is CI was down, and if that's the case, it just looks like a green badge even though it didn't do anything. My bad, and I'll look more carefully in future.

**Comment by VSadov** [comment]
Sorry. It was building on my machine, so I've submitted a PR, but CI was down, so I could not know if it breaks anything. I guess it does ...

**Comment by VSadov** [comment]
It is a bit annoying that it defaults to "ALL GREEN" when CI is down.

**Comment by danmosemsft** [comment]
@mmitche is there any way to make the PR not have a green merge button by default just because CI is down?

**Pull request merged**
