### PR TITLE
Remove MonoTODO and MonoLimitation from System.Drawing.Common

### PR DESCRIPTION
**Pull request by stephentoub**
cc: @marek-safar, @safern, @hughbe

### CODE REVIEW

**Comment by safern** [comment]
Is this enabling this features? Or was this Attribute only important to Mono?

**Comment by stephentoub** [comment]
It was only relevant for Mono. My understanding is it was used for documentation purposes only.

**Comment by safern** [comment]
Ok, thanks.

**Comment by stephentoub** [comment]
https://github.com/dotnet/corefx/pull/29424#discussion_r188613633

**Pull request merged**
