### PR TITLE
Make XElement.ctor() internal

### PR DESCRIPTION
**Pull request by krwq**
Fixes https://github.com/dotnet/corefx/issues/19204

### CODE REVIEW

**Comment by krwq** [comment]
@huanwu - got some more context on the failures perhaps?

**Comment by huanwu** [comment]
@krwq I will look at the test failures.

**Comment by huanwu** [comment]
@krwq, the reason why our tests fail because this internal constructor was optimized out by the compiler so our code cannot find the default constructor with the following code. 
`ConstructorInfo ctor = typeof(XElement).GetConstructor(BindingFlags.Instance | BindingFlags.NonPublic | BindingFlags.Public, Array.Empty<Type>());`

**Comment by zhenlan** [comment]
@krwq maybe we can try to add `[MethodImpl(MethodImplOptions.NoOptimization)]` to this constructor?

**Comment by krwq** [comment]
Thank you! I'll try that and see how it goes!

**Comment by stephentoub** [comment]
> the reason why our tests fail because this internal constructor was optimized out by the compiler 

The compiler shouldn't be removing the ctor.  Is it being removed by ILLINK? cc: @ericstj

**Comment by ericstj** [comment]
Yeah, ILLink would remove it /cc @erozenfeld 
You can manually root it like [this](https://github.com/dotnet/corefx/blob/master/src/System.Private.DataContractSerialization/src/ILLinkTrim.xml).  I believe the syntax would be as follows:
```xml
<linker>
  <assembly fullname="System.Private.Xml.Linq">
    <type fullname="System.Xml.Linq.XElement">
      <!-- called through reflection by tests -->
      <method name=".ctor" />
    </type>
  </assembly>
</linker>
```

**Comment by krwq** [comment]
Thanks everyone for help! PTAS(econd)L

**Comment by erozenfeld** [comment]
LGTM

**Pull request merged**
