### PR TITLE
Don't dispose StreamPipeWriter CancellationToken until after Flush 

### PR DESCRIPTION
**Pull request by jkotalik**
Same as https://github.com/dotnet/corefx/pull/39610 except on master.

### CODE REVIEW

**Comment by davidfowl** [comment]
Isn’t there a bit for that?

**Comment by jkotalik** [comment]
> Isn’t there a bit for that?

Clarify?

**Comment by davidfowl** [comment]
Bot

**Comment by stephentoub** [comment]
> Isn’t there a bot for that?

There is no automated porting of commits between master and release branches.  Our desired process is for changes to be merged into master, and then approved commits manually ported to the relevant release branch.  There's no bot for the other direction because we don't want thing to go in that direction in general :)

**Comment by jkotalik** [comment]
Thanks @stephentoub

**Comment by davidfowl** [comment]
Yea but that’s the wrong direction. Better to do it in the release branch then merge. The you can actually track what changes are in what branches. The issue with the other direction is missing things without the ability to track other than eye balling the changes or code

**Comment by stephentoub** [comment]
> Yea but that’s the wrong direction

There are arguments for both directions.  For example, it's often the case that we don't know until later that we're going to take something in a release branch.  We can always go from master to release branch, we can't always go the other way around.

If you want to change it, take it up with shiproom and @danmosemsft.

**Comment by danmosemsft** [comment]
One could also argue it's easier to miss things from master (where there's noise) rather than release (where there's attention). But, this isn't the place to discuss it. And aspnet can certainly choose its own approach. 😀

**Comment by davidfowl** [comment]
Yea I’m not pushing back, just explaining why the current process is sub-optimal 😬.

> And aspnet can certainly choose its own approach. 😀
 
I work in both repos 😉.

**Pull request merged**
