### PR TITLE
Update packages to rc3-23907

### PR DESCRIPTION
**Pull request by stephentoub**
cc: @weshaggard, @dagood, @pallavit

### CODE REVIEW

**Comment by stephentoub** [comment]
@ericstj, @weshaggard, trying to move the repo to the latest packages, all legs failed:
```
07:15:20   [15:15:33.08] Restoring all packages...
07:18:14 EXEC : error : System.Security.Cryptography.X509Certificates 4.1.0-rc3-23907 is not compatible with .NETStandard,Version=v1.3. [d:\j\workspace\windows_nt_de---06b7984d\build.proj]
07:18:14 EXEC : error : Some packages are not compatible with .NETStandard,Version=v1.3. [d:\j\workspace\windows_nt_de---06b7984d\build.proj]
07:18:21 EXEC : error : System.Security.Cryptography.X509Certificates 4.1.0-rc3-23907 is not compatible with .NETStandard,Version=v1.3. [d:\j\workspace\windows_nt_de---06b7984d\build.proj]
07:18:21 EXEC : error : Some packages are not compatible with .NETStandard,Version=v1.3. [d:\j\workspace\windows_nt_de---06b7984d\build.proj]
07:18:28 EXEC : error : System.Security.Cryptography.X509Certificates 4.1.0-rc3-23907 is not compatible with .NETStandard,Version=v1.3. [d:\j\workspace\windows_nt_de---06b7984d\build.proj]
07:18:28 EXEC : error : Some packages are not compatible with .NETStandard,Version=v1.3. [d:\j\workspace\windows_nt_de---06b7984d\build.proj]
07:19:27 
d:\j\workspace\windows_nt_de---06b7984d\build.proj(54,5): error MSB3073: The command ""d:\j\workspace\windows_nt_de---06b7984d\Tools/dotnetcli/bin/dotnet.exe" restore --packages "d:\j\workspace\windows_nt_de---06b7984d\packages" --source https://dotnet.myget.org/F/dotnet-core/api/v3/index.json --source https://www.nuget.org/api/v2/ "d:\j\workspace\windows_nt_de---06b7984d\/src" "d:\j\workspace\windows_nt_de---06b7984d\/pkg"" exited with code 1.
```
Is this expected?

**Comment by dagood** [comment]
From 23816 to 23907, `System.Security.Cryptography.X509Certificates` "lost" its `runtime.json` like I saw with `System.Runtime.InteropServices.RuntimeInformation` in https://github.com/dotnet/buildtools/pull/515. So there's a pattern here, but I don't know if it's intentional and I just don't understand why, or a mistake.

**Comment by ericstj** [comment]
This is expected.  We are doing away with runtime.json in the reference packages.  Those packages will require that a lineup be included.  Shortly (next week or so) many of these packages will merge from split (ref + impl) to fat (ref & impl in single package).  Regardless all of our projects should be pulling in the lineup.

Any projects that are hitting this now should add a reference to Microsoft.NETCore.Platforms.

**Comment by stephentoub** [comment]
> This is expected. We are doing away with runtime.json in the reference packages. Those packages will require that a lineup be included.

So this is a bug in the packages that someone is fixing?

**Comment by ericstj** [comment]
> So this is a bug in the packages that someone is fixing?

No, it's a bug in the corefx projects that aren't including a lineup (potentially).  Someone needs to take a look at the failing project.  I can do this.

**Comment by stephentoub** [comment]
Thanks, Eric.

**Comment by ericstj** [comment]
Actually the change here is that the reference assembly for X509Certitificates changed from NETStandard1.3 to NETStandard1.4.  Guardrails isn't even in play here since this is a library project targeting a portable TFM.  @bartonjs it looks like you missed adding a project reference the from the pkgproj to the downlevel reference assemblies (and I missed catching it in the review).

For now we can add a project reference to these projects and that can be cleaned up once we have a new build of packages.

**Comment by ericstj** [comment]
@stephentoub can you give me collaborator perms on your fork and I can just fix this up?

**Comment by ericstj** [comment]
Here's the fix: https://github.com/ericstj/corefx/commit/46dc6a8e50731a13488f33f5291ae23c4221ab2f
I have it made to a clone of your branch and can push directly if you give me [write permissions](https://help.github.com/articles/adding-collaborators-to-a-personal-repository/).

**Comment by stephentoub** [comment]
Thanks, @ericstj.  I cherry-picked your change.

**Comment by stephentoub** [comment]
@ericstj, a new failure now:
```
System\PinnableBufferCache.cs(465,17): error CS0433: The type 'GCHandle' exists in both 'System.Runtime.InteropServices, Version=4.0.20.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' and 'System.Runtime, Version=4.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' [d:\j\workspace\ubuntu_releas---9ea5f9c8\src\System.Net.Security\src\System.Net.Security.csproj]
```
I'm assuming this has something to do with https://github.com/dotnet/corefx/pull/6648?

(I see that System.Runtime.InteropServices.csproj contains an AssemblyVersion specifying 4.010, even though it looks like there's a contract for 4.0.20... is that correct?
```
https://github.com/dotnet/corefx/blob/master/src/System.Runtime.InteropServices/src/System.Runtime.InteropServices.csproj#L7
https://github.com/dotnet/corefx/tree/master/src/System.Runtime.InteropServices/ref/4.0.20
```)

**Comment by ericstj** [comment]
> I see that System.Runtime.InteropServices.csproj contains an AssemblyVersion specifying 4.010

https://github.com/dotnet/corefx/blob/master/src/System.Runtime.InteropServices/src/System.Runtime.InteropServices.csproj#L7 specifies 4.1.0.0, not 4.0.10.

So https://github.com/dotnet/corefx/pull/6648 was actually fixing the issue that Pallavi initially had to workaround with https://github.com/dotnet/corefx/commit/9b8403541bfbd4b1956944723b68167ad12fbf29.  So now we just need to undo that workaround.

I've done that here: https://github.com/ericstj/corefx/commit/cb0424296cff3563db64fb675aa9f4cdd1af68bb

I'm now doing a full stack build locally to see if any other problems exist.

**Comment by stephentoub** [comment]
> specifies 4.1.0.0, not 4.0.10.

Yes, I edited my comment after I realized I read it wrong.

> I've done that here: ericstj@cb04242

Cherry-picked as well.

**Comment by ericstj** [comment]
I'm also seeing a couple other errors related to reference refactoring:

```
       "E:\corefx\src\System.Data.SqlClient\src\System.Data.SqlClient.csproj" (default target) (81) ->
       (ValidatePackageTargetFramework target) -> 
         E:\corefx\Tools\PackageLibs.targets(155,5): error : Expected version 4.0.0.0 for referenced assembly E:\corefx\packages\System.Security.Cryptography.X509Certificates\4.1.0-rc3-23907\ref\netstandard1.4\System.Security.Cryptography.X509Certificates.dll but found 4.1.0.0 [E:\corefx\src\System.Data.SqlClient\src\System.Data.SqlClient.csproj]
         E:\corefx\Tools\PackageLibs.targets(155,5): error : Expected version 4.0.0.0 for referenced assembly E:\corefx\packages\System.Security.Cryptography.Algorithms\4.1.0-rc3-23907\ref\netstandard1.4\System.Security.Cryptography.Algorithms.dll but found 4.1.0.0 [E:\corefx\src\System.Data.SqlClient\src\System.Data.SqlClient.csproj]
```

```
       "E:\corefx\src\System.Security.Cryptography.OpenSsl\ref\System.Security.Cryptography.OpenSsl.csproj" (BuildAndTest target) (663) ->
       (CoreCompile target) -> 
         System.Security.Cryptography.OpenSsl.cs(10,77): error CS0234: The type or namespace name 'ECDsa' does not exist in the namespace 'System.Security.Cryptography' (are you missing an assembly reference?) 
```

I'm looking into them.

**Comment by stephentoub** [comment]
> I'm looking into them.

Shall I just close this PR and you can submit one with all of the changes when you have it working?

Thanks for investigating.

**Comment by ericstj** [comment]
might be easier rather than having you cherry-picking my changes

**Pull request closed without merging**
