### PR TITLE
Add SocketAsyncEventArgs test for 0-byte receive

### PR DESCRIPTION
**Pull request by stephentoub**
I got a report that 0-byte receives weren't working correctly, which led me to find that we don't have any tests for it.  Adding one (though it appears they're working ok, at least on the platforms on which I've tried it).

cc: @cipop, @davidsh

### CODE REVIEW

**Comment by davidfowl** [comment]
Glad this works, when we (@mgravell) ran this on travis. Hopefully it's not OS version sensitive...

**Comment by stephentoub** [comment]
> we could do a zero-length receive, but this is not supported equally on all platforms (fine on Windows, but, linux hates it)

@davidsh, can you elaborate on what the problem was?  Was there an exception, and if so, do you have the stack / error / etc.?

**Comment by stephentoub** [comment]
@dotnet-bot test Innerloop OSX Debug Build and Test please

**Comment by stephentoub** [comment]
@dotnet-bot test Innerloop OSX Debug Build and Test please
@dotnet-bot test Innerloop OSX Release Build and Test please

**Comment by stephentoub** [comment]
The tests all passed, but I'd seen a failure previously in an OSX run, so I want to run them again.  I'm a little concerned there may be a race condition somewhere (maybe in our implementation, maybe in OS) such that the async receive completes but Available (ioctl with FIONREAD) still ends up returning 0.
@dotnet-bot test Innerloop OSX Debug Build and Test please
@dotnet-bot test Innerloop OSX Release Build and Test please

**Comment by stephentoub** [comment]
@dotnet-bot test this please (trying all legs again to try to see if the raciness is only on OSX)

**Comment by stephentoub** [comment]
@dotnet-bot test this please (trying all legs again to try to see if the raciness is only on OSX)

**Comment by stephentoub** [comment]
@davidfowl, @mgravell, you mentioned you'd seen problems on Linux.  Can you elaborate on what they were?  I've not seen any problems on any flavor of Linux.  What I am seeing, though, is a race condition where sometimes Available (ioctl with FIONREAD on the socket) returns 0 immediately after the kevent call wakes up saying data is available on the socket.  Could that have been what you were seeing as well?  I'm not sure yet whether that's due to something in our implementation or something in the OS.

**Comment by mgravell** [comment]
I'd have to check, but IIRC the problem was that it would return without
data being available, meaning it wasn't useful as a tactic to do a
buffer-free wait for available data.

**Comment by stephentoub** [comment]
> I'd have to check, but IIRC the problem was that it would return without being available

Right, that's what I'm seeing on macOS.  You're seeing that on Linux, too?

**Comment by mgravell** [comment]
Yes. I don't know the state of the code, but you should be able to repro
using the "channels" (now "pipelines") test suite and changing the "OSes we
recognise" code to use zero-length reads on Linux. I'm on a mobile device
right now, but I can dig it out later.

**Comment by mgravell** [comment]
Here:
https://github.com/dotnet/corefxlab/blob/master/src/System.IO.Pipelines.Networking.Sockets/SocketConnection.cs

**Comment by stephentoub** [comment]
@dotnet-bot test this please

**Comment by stephentoub** [comment]
@dotnet-bot test this please

**Pull request merged**
