### PR TITLE
Improve performance of encoding only safe chars and spaces in WebUtility

### PR DESCRIPTION
**Pull request by hughbe**
- x4 performance boost
- halved number of allocations

This is quite common, so worth the extra code
Existing tests cover these branches
I didn't try to remove all allocations as this would negatively affect performance of encoding other strings

## Benchmark
benchmark encoding

## Benchmark Code
<details>
<summary> Click here </summary>
```
public static void PerformanceTests()
{
    TimeAction("Old: ", () => Old.UrlEncode("abc def"));
    TimeAction("New: ", () => New.UrlEncode("abc def"));
}

public static void TimeAction(string prefix, Action action)
{
    var sw = new Stopwatch();
    for (int iter = 0; iter < 5; iter++)
    {
        int gen0 = GC.CollectionCount(0);
        sw.Restart();
        for (int i = 0; i < 10000000; i++)
        {
            action();
        }
        sw.Stop();
        Console.WriteLine($"{prefix}Time: {sw.Elapsed.TotalSeconds}\tGC0: {GC.CollectionCount(0) - gen0}");
    }
}
```

</details>

/cc @davidsh @jamesqo @stephentoub

### CODE REVIEW

**Comment by stephentoub** [comment]
> This is quite common, so worth the extra code

Really? I wouldn't have expected that. What scenarios are you thinking of here?

**Comment by hughbe** [comment]
Example: type the word "hello world" into Google and its url encoded at the top in the url bar to "hello+world"

**Comment by stephentoub** [comment]
> Example: type the word "hello world" into Google and its url encoded at the top in the url bar to "hello+world"

Oh, that's not "only spaces". But yes, that's common.

**Comment by hughbe** [comment]
Sorry by "only spaces" I mean only spaces need encoding!

**Comment by stephentoub** [comment]
Makes sense.  Thanks, @hughbe.  LGTM.

**Pull request merged**
