### PR TITLE
Port #21273: read-only file system delete fix

### PR DESCRIPTION
**Pull request by niustephanie**
Ports changes from #21588, tests from #21684 for issue #21273.

### CODE REVIEW

**Comment by niustephanie** [comment]
@dotnet-bot test Innerloop CentOS7.1 Debug x64 Build and Test 
System.Runtime.Serialization.Formatters.Tests.BinaryFormatterTests.ValidateAgainstBlobs failed

**Comment by niustephanie** [comment]
@dotnet-bot  test Innerloop PortableLinux Debug x64 Build and Test
System.Runtime.Serialization.Formatters.Tests.BinaryFormatterTests.ValidateAgainstBlobs failed

**Comment by niustephanie** [comment]
@dotnet-bot test Innerloop PortableLinux Release x64 Build and Test
System.Runtime.Serialization.Formatters.Tests.BinaryFormatterTests.ValidateAgainstBlobs failed

**Comment by niustephanie** [comment]
@dotnet-bot test Innerloop PortableLinux Release x64 Build and Test
System.Runtime.Serialization.Formatters.Tests.BinaryFormatterTests.ValidateAgainstBlobs failed

**Comment by JeremyKuhne** [comment]
Merging to get this in tonight's build. @ViktorHofer, @krwq - any idea on what is going on with BinaryFormatterTests.ValidateAgainstBlobs? Are there changes we should consider making to get this stable in the release branch?

**Comment by ViktorHofer** [comment]
Any logs?

**Comment by JeremyKuhne** [comment]
@ViktorHofer https://ci.dot.net/job/dotnet_corefx/job/release_2.0.0/job/portablelinux_release_prtest/387/

**Pull request merged**
