### PR TITLE
[WIP] Enable deps.json generation

### PR DESCRIPTION
**Pull request by ViktorHofer**
Fixes https://github.com/dotnet/corefx/issues/38508

This will cause tests to fail.

### CODE REVIEW

**Comment by ericstj** [comment]
What's the purpose of the PR?  Is there a call to action here?  I believe the reasons for failure are things being absent from the deps file that are in the test output directory.

**Comment by ViktorHofer** [comment]
This is to see which tests are failing when enabling deps.json generation for test projects.

**Comment by ViktorHofer** [comment]
So we have 135 failing tests, which means 9 individually failing tests when enabling deps.json files. @ericstj this is a precursor for making VS Test Explorer and dotnet test work. What is your recommendation here? Should we change the behavior of those 9 tests?

**Comment by ViktorHofer** [comment]
also cc @sdmaclea for the failing load context tests

**Comment by sdmaclea** [comment]
/cc @vitek-karas 

The tests are covering various runtime required behavior of the loader.  If we add a deps.json and it breaks the tests, we will need to revise the tests to exercise the same behaviors in a different way.

I'm not sure why you are removing the `AddConflictResolutionAssetsForTests` `RemoveConflictResolutionAssetsForTests` targets.  It is possible the tests which use these targets will not work with a deps.json. The hostpolicy will prevent the tests from running with a missing asset.

deps,json is an optional feature.  We will need coverage without it.

**Comment by ViktorHofer** [comment]
> I'm not sure why you are removing the AddConflictResolutionAssetsForTests RemoveConflictResolutionAssetsForTests targets. It is possible the tests which use these targets will not work with a deps.json. The hostpolicy will prevent the tests from running with a missing asset.

That's an infra cleanup change that @ericstj suggested: https://github.com/dotnet/corefx/pull/38792/files#r299165719. Please ignore it for the discussion here.

> deps,json is an optional feature. We will need coverage without it.

Right. What I'm proposing here is to have it enabled by default but also include tests without it probably by adding an additional test assembly where we disable the deps generation.

**Comment by ViktorHofer** [comment]
> deps,json is an optional feature

Its initial idea was probably to be optional but since xunit turned it on by default and made it required, this isn't true anymore for test projects.

**Comment by ViktorHofer** [comment]
Closing this one in favor of https://github.com/dotnet/corefx/pull/39279/commits/be9479e9b8c0a2ba03f804425e9f93b01b59b3d6. Keeping the original issue open as a tracking issue to enable the deps.json generation on the three disabled projects.

**Pull request closed without merging**
