### PR TITLE
Check for RunTest.cmd before running test on Nano.

### PR DESCRIPTION
**Pull request by Priya91**
Will fix the failing Windows Nano runs.
cc @MattGal

### CODE REVIEW

**Comment by Priya91** [comment]
@dotnet-bot Test windows nano 2016 debug

**Comment by Priya91** [comment]
@dotnet-bot Test outerloop windows nano 2016 debug

**Comment by Priya91** [comment]
Filed issue #9975 to fix the buildtools.

**Comment by Priya91** [comment]
Filed issue #9979 for the CentOS failure.

**Comment by Priya91** [comment]
@dotnet-bot Test  Innerloop CentOS7.1 Release Build and Test

**Comment by MattGal** [comment]
Does this fix or hide the problem? If the file isn't present and we don't run it, shouldn't there be an error?  (i.e. if the file doesn't exist in either place, wouldn't this still "pass"?)

**Comment by Priya91** [comment]
@MattGal This doesn't fix the problem, filed issue #9979 to fix this in the buildtools, this only unblocks the Windows Nano Server script, which just runs tests under Windows and AnyOS dirs. The run-tests.cmd doesn't do any sku based validation, it is expected for the build to do all that, and drop the right bits in the tests folder.

**Pull request merged**
