### PR TITLE
Port System.Threading perf tests to release/2.0.0

### PR DESCRIPTION
**Pull request by kouvel**
So that we can get a baseline for comparison against 2.0.

https://github.com/dotnet/corefx/pull/28712

### CODE REVIEW

**Comment by kouvel** [comment]
```
   Test Name                                                    | Metric   | Iterations | AVERAGE | STDEV.S |     MIN |     MAX
  :------------------------------------------------------------ |:-------- |:----------:| -------:| -------:| -------:| -------:
   System.Threading.Tests.Perf_EventWaitHandle.Set_Reset        | Duration |    100     |  60.696 |   1.003 |  59.900 |  68.073
   System.Threading.Tests.Perf_Interlocked.Add_int              | Duration |    100     |  48.708 |   2.516 |  45.527 |  55.739
   System.Threading.Tests.Perf_Interlocked.Add_long             | Duration |    100     |  45.840 |   0.648 |  45.387 |  50.345
   System.Threading.Tests.Perf_Interlocked.CompareExchange_int  | Duration |    100     |  64.455 |   1.810 |  63.199 |  70.356
   System.Threading.Tests.Perf_Interlocked.CompareExchange_long | Duration |    100     |  63.875 |   1.249 |  63.066 |  70.525
   System.Threading.Tests.Perf_Interlocked.Decrement_int        | Duration |    100     |  48.314 |   3.223 |  45.508 |  58.344
   System.Threading.Tests.Perf_Interlocked.Decrement_long       | Duration |    100     |  51.727 |   3.842 |  45.550 |  59.111
   System.Threading.Tests.Perf_Interlocked.Exchange_int         | Duration |    100     |  66.760 |   2.501 |  63.084 |  78.572
   System.Threading.Tests.Perf_Interlocked.Exchange_long        | Duration |    100     |  48.108 |   2.538 |  45.412 |  55.321
   System.Threading.Tests.Perf_Interlocked.Increment_int        | Duration |    100     |  47.781 |   2.701 |  45.452 |  55.678
   System.Threading.Tests.Perf_Interlocked.Increment_long       | Duration |    100     |  48.333 |   3.901 |  45.403 |  67.759
   System.Threading.Tests.Perf_Lock.ReaderWriterLockSlimPerf    | Duration |    100     |  63.399 |   4.552 |  60.457 |  77.819
   System.Threading.Tests.Perf_Monitor.EnterExit                | Duration |    100     |  65.323 |   8.354 |   0.000 |  69.147
   System.Threading.Tests.Perf_Monitor.TryEnterExit             | Duration |    100     |  67.352 |   1.512 |  66.697 |  79.532
   System.Threading.Tests.Perf_SpinLock.EnterExit               | Duration |     54     | 185.400 |   4.757 | 183.446 | 215.245
   System.Threading.Tests.Perf_SpinLock.TryEnterExit            | Duration |     55     | 184.885 |   1.092 | 183.749 | 190.069
   System.Threading.Tests.Perf_Volatile.Read_double             | Duration |    100     |  51.310 |   1.619 |  50.533 |  63.469
   System.Threading.Tests.Perf_Volatile.Write_double            | Duration |    100     |  50.942 |   0.521 |  50.479 |  53.526
```

It looks like there is no regression in SpinLock tests from 2.0.

**Comment by stephentoub** [comment]
Just curious, why are we porting these to the 2.0 branch?

**Comment by kouvel** [comment]
Apparently, that is the only way to get a baseline from 2.0 for comparison (I guess in benchview). @danmosemsft, is there any additional process necessary before merging test changes to release/2.0.0?

**Comment by danmosemsft** [comment]
You can commit test only changes to release/2.0 without ceremony as long as @wtgodbe confirms it's not "paused" for servicing.

**Comment by wtgodbe** [comment]
Feel free to merge, we haven't sent out servicing builds yet.

**Comment by kouvel** [comment]
@dotnet-bot test Windows x86 Release Build

```
Unhandled Exception of Type Xunit.Sdk.TrueException
Message :
Assert.True() Failure
Expected: True
Actual:   False
Stack Trace :
   at System.Data.SqlClient.Tests.SqlConnectionBasicTests.ConnectionTimeoutTestWithThread()
```

**Comment by kouvel** [comment]
@dotnet-bot test Windows x64 Debug Build
test Windows x86 Release Build

**Comment by kouvel** [comment]
Above failure appears to be consistent and is not related to my change

**Pull request merged**
