### PR TITLE
ArrayMemoryPoolBuffer should only implement IMemoryOwner<T>

### LINKED ISSUE #28689: ArrayMemoryPool shouldn't dispose block on Unpin
https://github.com/dotnet/corefx/blob/master/src/System.Memory/src/System/Buffers/ArrayMemoryPool.ArrayMemoryPoolBuffer.cs#L110

/cc @ahsonkhan @GrabYourPitchforks

### PR DESCRIPTION
**Pull request by benaadams**
Resolves #28689

/cc @pakrym @GrabYourPitchforks @ahsonkhan

### CODE REVIEW

**Comment by pakrym** [comment]
Test?

**Comment by benaadams** [comment]
> Test?

Having trouble getting it to fail :-/ 

It `TryGetArray` currently should fail after a Dispose of a MemoryHandle?

**Comment by benaadams** [comment]
@pakrym I think its current behaviour is correct; its just written a bit strange.

**Comment by benaadams** [comment]
> The fix is to remove all reference counting from the array pool. 

Removed

**Comment by davidfowl** [comment]
@benaadams going further it should just implement IMemoryOwner not MemoryManager

**Comment by davidfowl** [comment]
Maybe that's a step to far?

**Comment by benaadams** [comment]
>  going further it should just implement IMemoryOwner not MemoryManager

Done

**Comment by benaadams** [comment]
Perhaps should make it less allocatey by actually pooling the `ArrayMemoryPoolBuffer`?

**Comment by benaadams** [comment]
```
    System.IO.Pipelines.Tests.PipelineReaderWriterFacts.AdvanceToInvalidCursorThrows [FAIL]
       System.InvalidCastException : Unable to cast object of type 'ArrayMemoryPoolBuffer[System.Byte]' to type 'System.Buffers.MemoryManager`1[System.Byte]'.

```

**Comment by benaadams** [comment]
The only major change is getting a `Span` from a stored `Memory` won't fail post block Dispose anymore as its directly on array (getting the `Memory` from the `ArrayMemoryPoolBuffer` will fail post `Dispose` though)

So its if that is acceptable? (e.g. if you follow the rules in [Memory<T> usage guidelines](https://gist.github.com/GrabYourPitchforks/4c3e1935fd4d9fa2831dbfcab35dffc6) its fine); or if it needs extra guard rails for getting the Span?

**Comment by davidfowl** [comment]
@GrabYourPitchforks are you working on other swap in diagnostic pool implementations right?

**Comment by GrabYourPitchforks** [comment]
We don't require extra guard rails against fetching the `Span` property after the backing array has been reassigned. I am working on a swap-in diagnostic implementation, but it wouldn't ship as part of corefx, and we wouldn't promote its use outside of test environments.

**Pull request merged**
