### PR TITLE
Add test for dotnet/coreclr#18521 fix

### PR DESCRIPTION
**Pull request by jkoritzinsky**
Adds a unit test for the fix in dotnet/coreclr#20194 based on the original repro.

Adds a unit test for dotnet/coreclr#20263

### CODE REVIEW

**Comment by stephentoub** [comment]
This is passing ci even though that coreclr PR isn't merged. Is that expected?

**Comment by jkoritzinsky** [comment]
That is not expected. I must have messed up porting over the test from CoreCLR. I'll figure it out on Monday.

**Comment by jkoritzinsky** [comment]
As soon as CoreCLR commit 737d0ea7c3e8a8ab42344f14b8338a0f7ffaf60d is propagated to CoreFX this will be ready for review.

**Comment by jkotas** [comment]
Note that this is a breaking change: It is changing non-throwing behavior into a throwing one. I do not think we should be making breaking changes like this.

**Comment by karelz** [comment]
@jkotas @luqunl @AaronRobinsonMSFT do you plan to revert the change in CoreCLR in that case?
Should these tests be just adjusted or do we need to discard them entirely?

**Comment by jkoritzinsky** [comment]
We have another change in flight that modifies where the exception is thrown. I'll update the tests in this PR once we decide whether or not to merge that PR. (Some of the tests in this PR should be merged anyway since they weren't breaking changes)

**Comment by karelz** [comment]
Can you link the CoreCLR change in flight please?

**Comment by jkoritzinsky** [comment]
https://github.com/dotnet/coreclr/pull/20375

**Pull request merged**
