### PR TITLE
Fix serialization roundtrip line number test on desktop

### PR DESCRIPTION
**Pull request by stephentoub**
Fixes https://github.com/dotnet/corefx/issues/19467
cc: @danmosemsft

### CODE REVIEW

**Comment by stephentoub** [comment]
@dotnet-bot test Innerloop Windows_NT Release Build and Test please (https://github.com/dotnet/corefx/issues/19474)

**Comment by stephentoub** [comment]
@dotnet-bot help

**Comment by stephentoub** [comment]
@dotnet-bot test Innerloop Windows_NT Release x64 Build and Test

**Comment by stephentoub** [comment]
@dotnet-bot test Innerloop Windows_NT Release x64 Build and Test please (#19474)

**Comment by danmosemsft** [comment]
LGTM

**Comment by safern** [comment]
Thanks for taking over this @stephentoub

**Pull request merged**
