### PR TITLE
PR and issue stats

### PR DESCRIPTION
**Pull request by khellang**
Would you be interested in showing the PR and issue stats in the README.md? :sparkles:

### CODE REVIEW

**Comment by stephentoub** [comment]
@richlander?  @terrajobst?

**Comment by mmitche** [comment]
@dotnet-bot test this please

**Comment by jasonwilliams200OK** [comment]
:+1:
Regarding another meta feature, on PRs would be really useful to make the coverage service like https://codecov.io/ submit a commit. It can probably hook with Jenkins and show pretty stats in the PR, with change in coverage. @stevepeak created an example here: https://github.com/codecov/example-csharp for C# project. 

Pros: it prevents people from digging into jenkins site for coverage info.

Cons: It produces extra noise in PR thread (for each commit, rebase etc.).

**Comment by stevepeak** [comment]
Hey! Just to mention, Codecov only posts one comment and updates it. So you'll get only one notification per PR and not on every commit. Thanks!

**Comment by akoeplinger** [comment]
@khellang we had those badges in the beginning, they were removed: https://github.com/dotnet/corefx/pull/583

Regarding code coverage: I'd love having that on PRs (afaik it's only done on master builds), but I don't like bots posting comments. The GitHub Status API was made for this.

**Comment by jasonwilliams200OK** [comment]
@akoeplinger, OMO according to the principle of separation of concerns, codecov can do this job without us fiddling with the raw API. It will also comply with the principle of least surprise. :smile: 

Thanks @stevepeak for the info, I have made the correction above! :)

**Comment by richlander** [comment]
Providing more context beyond @akoeplinger ... From a MSFT standpoint, these stats are not particularly important to us. That's probably because they are well within in an acceptable range and that's not likely to change. Also (and most importantly), many of the PRs are developed on a dev box within Microsoft, show up on the repo as a PR and then get quickly merged. That's because folks at Microsoft talk to each other, so the mergers know the change is coming and what it is. As a result, they feel like vanity metrics and not super accurate. They are overly good in our favor. If a significant number of people really want them, having them isn't /bad/, but I also don't think that they are a huge benefit for the reasons given.

Having more visible and upstream code coverage info would definitely be interesting. Probably missing the obvious on their site. Can someone share a PR example of this to look at.

**Comment by jasonwilliams200OK** [comment]
Thank you @richardlford! 
I think opencover is already incorporated in the Jenkins CI and generating the coverage for this repo: http://dotnet-ci.cloudapp.net/job/dotnet_corefx_coverage_windows/lastStableBuild/Code_Coverage_Report/.

Going by @stevepeak's example https://github.com/codecov/example-csharp, I think following actions are required:

* LogOn to https://codecov.io/ using CoreFX's admin GitHub credentials and click on dotnet/corefx in the project list. It will generate the upload token
* Add the following PowerShell command in CI's post-test / post-coverage generation `<command>`:

  ```powershell
  (New-Object System.Net.WebClient).DownloadFile("https://codecov.io/bash",".\CodecovUploader.sh")
  .\CodecovUploader.sh -t <your upload token> -X gcov
  ```

And that is all.
@stevepeak, please CMIIW.
@mmitche, would you please give it a try? :)

**Comment by weshaggard** [comment]
I agree with @richlander and as @akoeplinger pointed out I removed these with #583 and I still believe that the reasoning stands for not having these. So thanks for the PR @khellang but I'm going to close it.

As for the code coverage badge that should be opened as a separate issue but my initial thoughts are  we shouldn't do it because currently our CI system for PR's does not enable code coverage and I'm not sure I want to add the extra time to our CI system to do those runs. I want to keep the times for validating a PR down, even today I think they are taking too long, but it is always a balance of maintaining quality vs efficiency, but I don't think code coverage adds enough value to be run on every PR.

**Comment by stephentoub** [comment]
> I don't think code coverage adds enough value to be run on every PR

I agree with that, in large part because many PRs won't affect code coverage in any significant way.

However, I do think it'd be really useful if on any given PR there was a way to initiate such a comparative code coverage run.  I'm often pulling down PRs locally to do a code coverage run and then manually comparing it against the latest baseline for a given project... it'd be awesome if that could be automated on-demand.

**Comment by mmitche** [comment]
@stephentoub We figured out we can set up specific triggers for CI.  For instance, right now there is a "test ci please" for certain repos which tests some job generation.  We could add a "test codecoverage please". Which would queue a new job.

**Comment by mmitche** [comment]
@jasonwilliams200OK I'll try to do this soon, though I'm pretty busy at the moment.

**Comment by weshaggard** [comment]
@Stephentoub @mmitche I agree it would be nice to have a way to trigger a code coverage run on a given PR.

**Comment by stephentoub** [comment]
>  We could add a "test codecoverage please"

Sounds great!

**Comment by jasonwilliams200OK** [comment]
@cortana, test codecoverage please. :smile:

**Pull request closed without merging**
