### PR TITLE
Remove 500K random tests from System.Globalization.Tests

### PR DESCRIPTION
**Pull request by stephentoub**
cc: @weshaggard, @hughbe, @tarekgh

### CODE REVIEW

**Comment by weshaggard** [comment]
LGTM Thanks for tracking this down @stephentoub. What is the total test count now after you remove this?

**Comment by stephentoub** [comment]
> What is the totla test count now after you remove this?

```
=== TEST EXECUTION SUMMARY ===
     System.Globalization.Tests  Total: 5247, Errors: 0, Failed: 0, Skipped: 0, Time: 0.984s
```

**Comment by hughbe** [comment]
Oh this is perfect! Good catch. 

Just a quick note/excuse: these tests already existed before my addition, but we're not included in [MemberData] so I added them when o noticed it. 

Seems like this was the reason why they weren't included

**Comment by tarekgh** [comment]
LGTM too.

**Pull request merged**
