### PR TITLE
SslStream Correct current size calculations

### PR DESCRIPTION
**Pull request by Drawaes**
/cc @geoffkizer 

When attempting to remove the "ref" for the encrypt function I placed some Debug.Asserts and ran a lot fo testing. What I found is there was a lot of allocations on windows and a few on Linux.

The windows ones I tracked down to the fact that even though the header/trailer could not be any bigger than 32 bytes SChannel claimed it needed more space. So I have changed the calculation instead to use the StreamSizes that we have (from Linux/OSX they are fixed from SChannel it is retrieved from the API for that connection based on it's requirements/session ciphers etc).

This means we always now have the correct size on windows. So I could remove the allocations and the refs. I put in some Debug.Asserts to replace the code that checked the size and allocated.

Onto Linux. Currently we had zero for Headers + Trailers and just a fixed MaxMessageSize. The message size is currently set to 32k. Which the description even says is arbitrary.

As the max framesize for TLS is 16k if we set this to 32k we could need to output 16k * 2 + Overhead * 2. This means we can allocate in Linux/OSX whenever we go over the 16k boundary. As the frames are independent and it's not a Kernel call just native interop I have changed the this to 16k (reduces the buffer sizes in OpenSSL as well because it has to buffer the first completed frame).

Next I added the 32byte overhead to the header to work with the new flow of sizes above.

Last thing I fixed is the calculation of the "max data" we can send. Currently we are taking the max message size and subtracting the Head and Trailer. This is not what the API says for SChannel from my understanding and certainly isn't the logic from OpenSsl.

> The length of the SecBuffer structure that contains the message must be no greater than cbMaximumMessage, which is obtained from the QueryContextAttributes (Schannel) (SECPKG_ATTR_STREAM_SIZES) function.

However our data is the only thing that goes into that buffer there are separate buffers for the header and trailer so the max is the max.

Once this has been done I did some testing with your tool @geoffkizer and there was pretty much no difference (it's only allocations) but I could see a drop in allocations on large scale stress tests :)

### CODE REVIEW

**Comment by davidsh** [comment]
@dotnet-bot test Outerloop Linux x64 Debug Build
@dotnet-bot test Outerloop NETFX x86 Debug Build
@dotnet-bot test Outerloop UWP CoreCLR x64 Debug Build
@dotnet-bot test Outerloop Windows x64 Debug Build

**Comment by Drawaes** [comment]
Please wait for review, there is an issue with tests on unix/OSX on System.Net.Http that I am debugging

**Comment by Drawaes** [comment]
There are issues with this PR around openssl sending extra data that can't be solved easily if the ref is removed. I will re-evaluate at a later date

**Pull request closed without merging**
