### PR TITLE
Apply tfm versions to PackageConfigurations

### PR DESCRIPTION
**Pull request by ViktorHofer**
Relates to https://github.com/dotnet/corefx/issues/36577

### CODE REVIEW

**Comment by ViktorHofer** [comment]
@ericstj seems like currently there is uap vnext version tfm. I wanted to use uap10.0.16300. Do you know why we don't have one?

**Comment by ericstj** [comment]
It's still a hypothetical release, we shouldn't be including in any packages yet.   In fact I believe we strip all the assets that appear in the package with this TFM via a target, maybe we should just remove them completely from Configuration.props (packaging conifgurations that is, we still want to build for it).

**Comment by safern** [comment]
Make sure to also scan for if-defed code using the `netcoreapp` constant, so that we don't miss that code on projects that are being retargetted to `netcoreapp3.0`

**Comment by ViktorHofer** [comment]
Good catch, thanks! I think to make this whole approach work some infra changes are necessary as I assumed that different aliases map to the same TargetGroup and same literal paths for refs/src.

**Comment by ViktorHofer** [comment]
This never really worked. Closing for now

**Pull request closed without merging**
