### PR TITLE
Fixing NameResolution initialization

### LINKED ISSUE #10024: Dns.GetHostEntryAsync() throws SocketException if called before any other Socket APIs
# Repro Steps
* dotnet new
* Replace the contents of `Main()` with the following:
```csharp
Console.WriteLine(System.Net.Dns.GetHostEntryAsync("127.0.0.1").Result.AddressList.Length);
```
* dotnet run
* App throws following exception:
```
Unhandled Exception: System.AggregateException: One or more errors occurred. (Either the application has not called WSAStartup,
or WSAStartup failed) ---> System.Net.Sockets.SocketException: Either the application has not called WSAStartup,
 or WSAStartup failed
   at System.Net.Dns.HostResolutionEndHelper(IAsyncResult asyncResult)
   at System.Net.Dns.EndGetHostEntry(IAsyncResult asyncResult)
   at System.Net.Dns.<>c.<GetHostEntryAsync>b__16_1(IAsyncResult asyncResult)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction,
Task`1 promise, Boolean requiresSynchronization)
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at ConsoleApplication.Program.Main(String[] args)
```
* Add the following before the call to `Dns.GetHostEntryAsync()`:
```csharp
new System.Net.Sockets.Socket(System.Net.Sockets.SocketType.Stream, System.Net.Sockets.ProtocolType.Tcp);
```
* App works correctly.

CC: @stephentoub

### PR DESCRIPTION
**Pull request by CIPop**
Fixing NameResolution initialization for Windows, adding more FunctionalTest coverage, adding a new UnitTest project. (Ran out of time but I plan to add more Unit Tests to validate complicated scenarios such as no IPv6 available.)

Fixing the ParallelTestExecution script.

Fixes #10024 

@davidsh @stephentoub @ericeil @himadrisarkar PTAL

### CODE REVIEW

**Comment by stephentoub** [comment]
LGTM

**Comment by stephentoub** [comment]
@CIPop, can this be merged (once it's rebased)?

**Comment by davidsh** [comment]
LGTM

**Comment by stephentoub** [comment]
Replaced by https://github.com/dotnet/corefx/pull/10341, just to fix the merge/CI issues.

**Comment by CIPop** [comment]
Thanks @stephentoub for merging while I was on vacation!

**Pull request closed without merging**
