### PR TITLE
Include fragment and query in Uri.LocalPath on Unix

### PR DESCRIPTION
**Pull request by rmkerr**
While testing XmlUriResolver, @pjanotti discovered that any segments of a file path following a '#' symbol will be cut out of Uri.LocalPath on Unix. Based on additional tests, this also occurs for the '?' symbol. This is happening because the Unix specific case for local path only uses the path component of the URI:
https://github.com/dotnet/corefx/blob/9e8d443ff78c4f0a9a6bedf7f95961cf96ceff0a/src/System.Private.Uri/src/System/Uri.cs#L1032-L1037

The fix here is to include the fragment and query in LocalPath in the Unix path specific case. This PR enables the test case in XmlUriResolver that uncovered this issues, and adds some additional cases to our URI tests.

Fixes: #28486

### CODE REVIEW

**Comment by stephentoub** [comment]
cc: @tmds

**Comment by tmds** [comment]
@rmkerr The Uri class will strip off those fragments for Dos paths, so why should it not do this for Unix paths?
`new Uri("file://c:\\foo#bar").LocalPath` is `c:\foo`

**Comment by tmds** [comment]
> @rmkerr The Uri class will strip off those fragments for Dos paths, so why should it not do this for Unix paths?

So, the Uri class supports Query and Fragment for file:// scheme, and this PR is removing that support specifically for Unix paths.
If the filesystem path contains a '#' or a '?' you should escape it when passing it in as a file://xxx string (e.g. `file://c:\\foo%23bar`) . Or more convenient is to let the Uri class do that for you by passing in the path without the file:// scheme (e.g. `c:\\foo#bar`).

**Comment by rmkerr** [comment]
@tmds Thanks for pointing that out. After a bit more investigation, it looks like on Windows we expect '#' and '?' to be URL encoded for explicit file paths (starting with file://), but not for implicit file paths (starting with c://). I think that behavior makes sense, and for consistency I think we should make sure Unix behaves the same way. I can add `&& IsImplicitFile` to the check there, and that enforce the same behavior. 

Does that sound reasonable to you?

**Comment by rmkerr** [comment]
I've improved the fix to only apply to implicit files. I've also added test cases for both Unix and Windows that should demonstrate that the improved fix is consistent cross platform.

**Comment by rmkerr** [comment]
@tmds You're right about that. When parsing an implicit path it looks like we already encode '#', causing it not to be treated as a fragment. The real issue here is that the XML resolver test is using an explicit file scheme without encoding '#', not the encoding behavior of Uri. I'll close this PR, thanks for helping me work through this.

**Comment by tmds** [comment]
@rmkerr no problem!

**Pull request closed without merging**
