### PR TITLE
Remove ActiveIssue for #8356

### PR DESCRIPTION
**Pull request by ericeil**
Removes the ActiveIssue tag for #8356, and reorganizes the tests into [Theory]- based cases.

Won't pass CI until #8530 is merged.

@stephentoub @CIPop

### CODE REVIEW

**Comment by stephentoub** [comment]
> Won't pass CI until #8530 is merged.

You have the first commit in here as well, FYI, but GitHub will do the right thing if the other one is merged first; it'll then see that the first commit is a dup and essentially discard at when merging.

**Comment by stephentoub** [comment]
LGTM

**Comment by stephentoub** [comment]
@dotnet-bot test this please

**Comment by ericeil** [comment]
@dotnet-bot test Innerloop CentOS7.1 Debug Build and Test please
test Innerloop CentOS7.1 Release Build and Test please

**Comment by ericeil** [comment]
@dotnet-bot test this please.

**Comment by ericeil** [comment]
@dotnet-bot test Innerloop CentOS7.1 Debug Build and Test please
test Innerloop CentOS7.1 Release Build and Test please

**Pull request merged**
