### PR TITLE
Updating the Windows build instructions to clarify the requirements for VS2017.

### PR DESCRIPTION
**Pull request by tannergooding**
Resolves https://github.com/dotnet/corefx/issues/16860

### CODE REVIEW

**Comment by tannergooding** [comment]
FYI. @tinchou, @weshaggard, @karelz

**Comment by tinchou** [comment]
It did work with the minimal setup, thanks!

**Comment by karelz** [comment]
Thanks @tannergooding for quick fix here!

**Comment by weshaggard** [comment]
LGTM Thanks @tannergooding

**Comment by berdon** [comment]
I had VS2017 installed and went through and modified my installation to include the listed individual components; however, I still get the following error when attempting to build. I am using the VS 2017 developer command prompt.

> Commencing build of native components
> 
> -- The C compiler identification is unknown
> -- The CXX compiler identification is unknown
> CMake Error at CMakeLists.txt:28 (project):
>   No CMAKE_C_COMPILER could be found.
> 
> 
> 
> CMake Error at CMakeLists.txt:28 (project):
>   No CMAKE_CXX_COMPILER could be found.

**Comment by tannergooding** [comment]
@berdon, what version of CMake do you have installed?

**Comment by berdon** [comment]
cmake version 3.8.0-rc2

CMake suite maintained and supported by Kitware (kitware.com/cmake).

**Comment by berdon** [comment]
image

**Comment by tannergooding** [comment]
That all looks correct. Only thing that doesn't show is `Visual Studio C++ Core Features`, which (as far as I am aware) is the only remaining thing that could block CMake from locating the compiler.

**Comment by berdon** [comment]
image

Yeah :/

**Comment by tannergooding** [comment]
What does the output look like if you run:
```
set _echo=1
run.cmd build-native
```

**Comment by berdon** [comment]
> C:\Users\AustinH\workspace\microsoft\dotnet\corefx>setlocal
> 
> C:\Users\AustinH\workspace\microsoft\dotnet\corefx>if not defined VisualStudioVersion (
> if defined VS150COMNTOOLS (
> call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\Common7\Tools\\VsDevCmd.bat"
>  goto :Run
> )  else if defined VS140COMNTOOLS (
> call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\Tools\\VsDevCmd.bat"
>  goto :Run
> )
>  echo Error: Visual Studio 2015 or 2017 required.
>  echo        Please see https://github.com/dotnet/corefx/blob/master/Documentation/project-docs/developer-guide.md for build instructions.
>  exit /b 1
> )
> 
> C:\Users\AustinH\workspace\microsoft\dotnet\corefx>set Platform=
> 
> C:\Users\AustinH\workspace\microsoft\dotnet\corefx>call C:\Users\AustinH\workspace\microsoft\dotnet\corefx\init-tools.cmd
> 
> C:\Users\AustinH\workspace\microsoft\dotnet\corefx>setlocal
> 
> C:\Users\AustinH\workspace\microsoft\dotnet\corefx>set INIT_TOOLS_LOG=C:\Users\AustinH\workspace\microsoft\dotnet\corefx\init-tools.log
> 
> C:\Users\AustinH\workspace\microsoft\dotnet\corefx>if [] == [] set PACKAGES_DIR=C:\Users\AustinH\workspace\microsoft\dotnet\corefx\packages\
> 
> C:\Users\AustinH\workspace\microsoft\dotnet\corefx>if [] == [] set TOOLRUNTIME_DIR=C:\Users\AustinH\workspace\microsoft\dotnet\corefx\Tools
> 
> C:\Users\AustinH\workspace\microsoft\dotnet\corefx>set DOTNET_PATH=C:\Users\AustinH\workspace\microsoft\dotnet\corefx\Tools\dotnetcli\
> 
> C:\Users\AustinH\workspace\microsoft\dotnet\corefx>if [] == [] set DOTNET_CMD=C:\Users\AustinH\workspace\microsoft\dotnet\corefx\Tools\dotnetcli\dotnet.exe
> 
> C:\Users\AustinH\workspace\microsoft\dotnet\corefx>if [] == [] set BUILDTOOLS_SOURCE=https://dotnet.myget.org/F/dotnet-buildtools/api/v3/index.json
> 
> C:\Users\AustinH\workspace\microsoft\dotnet\corefx>set /P BUILDTOOLS_VERSION= 0<"C:\Users\AustinH\workspace\microsoft\dotnet\corefx\BuildToolsVersion.txt"
> 
> C:\Users\AustinH\workspace\microsoft\dotnet\corefx>set BUILD_TOOLS_PATH=C:\Users\AustinH\workspace\microsoft\dotnet\corefx\packages\Microsoft.DotNet.BuildTools\1.0.27-prerelease-01413-01\lib\
> 
> C:\Users\AustinH\workspace\microsoft\dotnet\corefx>set PROJECT_JSON_PATH=C:\Users\AustinH\workspace\microsoft\dotnet\corefx\Tools\1.0.27-prerelease-01413-01
> 
> C:\Users\AustinH\workspace\microsoft\dotnet\corefx>set PROJECT_JSON_FILE=C:\Users\AustinH\workspace\microsoft\dotnet\corefx\Tools\1.0.27-prerelease-01413-01\project.json
> 
> C:\Users\AustinH\workspace\microsoft\dotnet\corefx>set PROJECT_JSON_CONTENTS={ "dependencies": { "Microsoft.DotNet.BuildTools": "1.0.27-prerelease-01413-01" }, "frameworks": { "netcoreapp1.0": { } } }
> 
> C:\Users\AustinH\workspace\microsoft\dotnet\corefx>set BUILD_TOOLS_SEMAPHORE=C:\Users\AustinH\workspace\microsoft\dotnet\corefx\Tools\1.0.27-prerelease-01413-01\init-tools.completed
> 
> C:\Users\AustinH\workspace\microsoft\dotnet\corefx>if [] == [force] (
> if exist "C:\Users\AustinH\workspace\microsoft\dotnet\corefx\Tools" rmdir /S /Q "C:\Users\AustinH\workspace\microsoft\dotnet\corefx\Tools"
>  if exist "C:\Users\AustinH\workspace\microsoft\dotnet\corefx\packages\Microsoft.DotNet.BuildTools" rmdir /S /Q "C:\Users\AustinH\workspace\microsoft\dotnet\corefx\packages\Microsoft.DotNet.BuildTools"
> )
> 
> C:\Users\AustinH\workspace\microsoft\dotnet\corefx>if exist "C:\Users\AustinH\workspace\microsoft\dotnet\corefx\Tools\1.0.27-prerelease-01413-01\init-tools.completed" (
> echo Tools are already initialized.
>  goto :EOF
> )
> Tools are already initialized.
> 
> C:\Users\AustinH\workspace\microsoft\dotnet\corefx>if NOT [0] == [0] exit /b 1
> 
> C:\Users\AustinH\workspace\microsoft\dotnet\corefx>xcopy C:\Users\AustinH\workspace\microsoft\dotnet\corefx\Tools-Override\* C:\Users\AustinH\workspace\microsoft\dotnet\corefx\Tools /y  1>nul
> 
> C:\Users\AustinH\workspace\microsoft\dotnet\corefx>set _toolRuntime=C:\Users\AustinH\workspace\microsoft\dotnet\corefx\Tools
> 
> C:\Users\AustinH\workspace\microsoft\dotnet\corefx>set _dotnet=C:\Users\AustinH\workspace\microsoft\dotnet\corefx\Tools\dotnetcli\dotnet.exe
> 
> C:\Users\AustinH\workspace\microsoft\dotnet\corefx>call C:\Users\AustinH\workspace\microsoft\dotnet\corefx\Tools\dotnetcli\dotnet.exe C:\Users\AustinH\workspace\microsoft\dotnet\corefx\Tools\run.exe build-native
> Running: C:\Users\AustinH\workspace\microsoft\dotnet\corefx\src\Native\build-native.cmd   x64  Debug  Windows_NT  --numproc 8    toolSetDir=c:\tools\clr
> 
> C:\Users\AustinH\workspace\microsoft\dotnet\corefx>setlocal
> 
> C:\Users\AustinH\workspace\microsoft\dotnet\corefx>set __nativeWindowsDir=C:\Users\AustinH\workspace\microsoft\dotnet\corefx\src\Native\\Windows
> 
> C:\Users\AustinH\workspace\microsoft\dotnet\corefx>set __binDir=C:\Users\AustinH\workspace\microsoft\dotnet\corefx\src\Native\..\..\bin
> 
> C:\Users\AustinH\workspace\microsoft\dotnet\corefx>set __rootDir=C:\Users\AustinH\workspace\microsoft\dotnet\corefx\src\Native\..\..
> 
> C:\Users\AustinH\workspace\microsoft\dotnet\corefx>set __CMakeBinDir=""
> 
> C:\Users\AustinH\workspace\microsoft\dotnet\corefx>set __IntermediatesDir=""
> 
> C:\Users\AustinH\workspace\microsoft\dotnet\corefx>set __BuildArch=x64
> 
> C:\Users\AustinH\workspace\microsoft\dotnet\corefx>set __TargetGroup=netcoreapp
> 
> C:\Users\AustinH\workspace\microsoft\dotnet\corefx>set __appContainer=""
> 
> C:\Users\AustinH\workspace\microsoft\dotnet\corefx>set __VCBuildArch=x86_amd64
> 
> C:\Users\AustinH\workspace\microsoft\dotnet\corefx>set CMAKE_BUILD_TYPE=Debug
> 
> C:\Users\AustinH\workspace\microsoft\dotnet\corefx>set "__LinkArgs= "
> 
> C:\Users\AustinH\workspace\microsoft\dotnet\corefx>set "__LinkLibraries= "
> 
> C:\Users\AustinH\workspace\microsoft\dotnet\corefx>call C:\Users\AustinH\workspace\microsoft\dotnet\corefx\src\Native\..\../run.cmd build-managed -GenerateVersion -project=C:\Users\AustinH\workspace\microsoft\dotnet\corefx\src\Native\..\../build.proj
> 
> C:\Users\AustinH\workspace\microsoft\dotnet\corefx>setlocal
> 
> C:\Users\AustinH\workspace\microsoft\dotnet\corefx>if not defined VisualStudioVersion (
> if defined VS150COMNTOOLS (
> call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\Common7\Tools\\VsDevCmd.bat"
>  goto :Run
> )  else if defined VS140COMNTOOLS (
> call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\Tools\\VsDevCmd.bat"
>  goto :Run
> )
>  echo Error: Visual Studio 2015 or 2017 required.
>  echo        Please see https://github.com/dotnet/corefx/blob/master/Documentation/project-docs/developer-guide.md for build instructions.
>  exit /b 1
> )
> 
> C:\Users\AustinH\workspace\microsoft\dotnet\corefx>set Platform=
> 
> C:\Users\AustinH\workspace\microsoft\dotnet\corefx>call C:\Users\AustinH\workspace\microsoft\dotnet\corefx\init-tools.cmd
> 
> C:\Users\AustinH\workspace\microsoft\dotnet\corefx>setlocal
> 
> C:\Users\AustinH\workspace\microsoft\dotnet\corefx>set INIT_TOOLS_LOG=C:\Users\AustinH\workspace\microsoft\dotnet\corefx\init-tools.log
> 
> C:\Users\AustinH\workspace\microsoft\dotnet\corefx>if [] == [] set PACKAGES_DIR=C:\Users\AustinH\workspace\microsoft\dotnet\corefx\packages\
> 
> C:\Users\AustinH\workspace\microsoft\dotnet\corefx>if [] == [] set TOOLRUNTIME_DIR=C:\Users\AustinH\workspace\microsoft\dotnet\corefx\Tools
> 
> C:\Users\AustinH\workspace\microsoft\dotnet\corefx>set DOTNET_PATH=C:\Users\AustinH\workspace\microsoft\dotnet\corefx\Tools\dotnetcli\
> 
> C:\Users\AustinH\workspace\microsoft\dotnet\corefx>if [] == [] set DOTNET_CMD=C:\Users\AustinH\workspace\microsoft\dotnet\corefx\Tools\dotnetcli\dotnet.exe
> 
> C:\Users\AustinH\workspace\microsoft\dotnet\corefx>if [] == [] set BUILDTOOLS_SOURCE=https://dotnet.myget.org/F/dotnet-buildtools/api/v3/index.json
> 
> C:\Users\AustinH\workspace\microsoft\dotnet\corefx>set /P BUILDTOOLS_VERSION= 0<"C:\Users\AustinH\workspace\microsoft\dotnet\corefx\BuildToolsVersion.txt"
> 
> C:\Users\AustinH\workspace\microsoft\dotnet\corefx>set BUILD_TOOLS_PATH=C:\Users\AustinH\workspace\microsoft\dotnet\corefx\packages\Microsoft.DotNet.BuildTools\1.0.27-prerelease-01413-01\lib\
> 
> C:\Users\AustinH\workspace\microsoft\dotnet\corefx>set PROJECT_JSON_PATH=C:\Users\AustinH\workspace\microsoft\dotnet\corefx\Tools\1.0.27-prerelease-01413-01
> 
> C:\Users\AustinH\workspace\microsoft\dotnet\corefx>set PROJECT_JSON_FILE=C:\Users\AustinH\workspace\microsoft\dotnet\corefx\Tools\1.0.27-prerelease-01413-01\project.json
> 
> C:\Users\AustinH\workspace\microsoft\dotnet\corefx>set PROJECT_JSON_CONTENTS={ "dependencies": { "Microsoft.DotNet.BuildTools": "1.0.27-prerelease-01413-01" }, "frameworks": { "netcoreapp1.0": { } } }
> 
> C:\Users\AustinH\workspace\microsoft\dotnet\corefx>set BUILD_TOOLS_SEMAPHORE=C:\Users\AustinH\workspace\microsoft\dotnet\corefx\Tools\1.0.27-prerelease-01413-01\init-tools.completed
> 
> C:\Users\AustinH\workspace\microsoft\dotnet\corefx>if [] == [force] (
> if exist "C:\Users\AustinH\workspace\microsoft\dotnet\corefx\Tools" rmdir /S /Q "C:\Users\AustinH\workspace\microsoft\dotnet\corefx\Tools"
>  if exist "C:\Users\AustinH\workspace\microsoft\dotnet\corefx\packages\Microsoft.DotNet.BuildTools" rmdir /S /Q "C:\Users\AustinH\workspace\microsoft\dotnet\corefx\packages\Microsoft.DotNet.BuildTools"
> )
> 
> C:\Users\AustinH\workspace\microsoft\dotnet\corefx>if exist "C:\Users\AustinH\workspace\microsoft\dotnet\corefx\Tools\1.0.27-prerelease-01413-01\init-tools.completed" (
> echo Tools are already initialized.
>  goto :EOF
> )
> Tools are already initialized.
> 
> C:\Users\AustinH\workspace\microsoft\dotnet\corefx>if NOT [0] == [0] exit /b 1
> 
> C:\Users\AustinH\workspace\microsoft\dotnet\corefx>xcopy C:\Users\AustinH\workspace\microsoft\dotnet\corefx\Tools-Override\* C:\Users\AustinH\workspace\microsoft\dotnet\corefx\Tools /y  1>nul
> 
> C:\Users\AustinH\workspace\microsoft\dotnet\corefx>set _toolRuntime=C:\Users\AustinH\workspace\microsoft\dotnet\corefx\Tools
> 
> C:\Users\AustinH\workspace\microsoft\dotnet\corefx>set _dotnet=C:\Users\AustinH\workspace\microsoft\dotnet\corefx\Tools\dotnetcli\dotnet.exe
> 
> C:\Users\AustinH\workspace\microsoft\dotnet\corefx>call C:\Users\AustinH\workspace\microsoft\dotnet\corefx\Tools\dotnetcli\dotnet.exe C:\Users\AustinH\workspace\microsoft\dotnet\corefx\Tools\run.exe build-managed -GenerateVersion -project=C:\Users\AustinH\workspace\microsoft\dotnet\corefx\src\Native\..\../build.proj
> Running: C:\Users\AustinH\workspace\microsoft\dotnet\corefx\Tools\msbuild.cmd /nologo /verbosity:minimal /clp:Summary /maxcpucount /nodeReuse:false /l:BinClashLogger,Tools\net46\Microsoft.DotNet.Build.Tasks.dll;LogFile=binclash.log /p:ConfigurationGroup=Debug /p:BuildPackages=false /p:GenerateNativeVersionInfo=true  /flp:v=normal  /flp2:warningsonly;logfile=msbuild.wrn  /flp3:errorsonly;logfile=msbuild.err  C:\Users\AustinH\workspace\microsoft\dotnet\corefx\src\Native\..\../build.proj /t:GenerateVersionHeader
> 
> Build succeeded.
>     0 Warning(s)
>     0 Error(s)
> 
> Time Elapsed 00:00:00.06
> Command execution succeeded.
> 
> C:\Users\AustinH\workspace\microsoft\dotnet\corefx>exit /b 0
> 
> C:\Users\AustinH\workspace\microsoft\dotnet\corefx>if [x64] == [] goto :ToolsVersion
> 
> C:\Users\AustinH\workspace\microsoft\dotnet\corefx>if /I [x64] == [Release] (set CMAKE_BUILD_TYPE=Release  && shift & goto Arg_Loop )
> 
> C:\Users\AustinH\workspace\microsoft\dotnet\corefx>if /I [x64] == [Debug] (set CMAKE_BUILD_TYPE=Debug  && shift & goto Arg_Loop )
> 
> C:\Users\AustinH\workspace\microsoft\dotnet\corefx>if /I [x64] == [AnyCPU] (set __BuildArch=x64  && set __VCBuildArch=x86_amd64  && shift & goto Arg_Loop )
> 
> C:\Users\AustinH\workspace\microsoft\dotnet\corefx>if /I [x64] == [x86] (set __BuildArch=x86  && set __VCBuildArch=x86  && shift & goto Arg_Loop )
> 
> C:\Users\AustinH\workspace\microsoft\dotnet\corefx>if /I [x64] == [arm] (set __BuildArch=arm  && set __VCBuildArch=x86_arm  && set __SDKVersion="-DCMAKE_SYSTEM_VERSION=10.0"  && shift & goto Arg_Loop )
> 
> C:\Users\AustinH\workspace\microsoft\dotnet\corefx>if /I [x64] == [x64] (set __BuildArch=x64  && set __VCBuildArch=x86_amd64  && shift & goto Arg_Loop )
> 
> C:\Users\AustinH\workspace\microsoft\dotnet\corefx>if [Debug] == [] goto :ToolsVersion
> 
> C:\Users\AustinH\workspace\microsoft\dotnet\corefx>if /I [Debug] == [Release] (set CMAKE_BUILD_TYPE=Release  && shift & goto Arg_Loop )
> 
> C:\Users\AustinH\workspace\microsoft\dotnet\corefx>if /I [Debug] == [Debug] (set CMAKE_BUILD_TYPE=Debug  && shift & goto Arg_Loop )
> 
> C:\Users\AustinH\workspace\microsoft\dotnet\corefx>if [Windows_NT] == [] goto :ToolsVersion
> 
> C:\Users\AustinH\workspace\microsoft\dotnet\corefx>if /I [Windows_NT] == [Release] (set CMAKE_BUILD_TYPE=Release  && shift & goto Arg_Loop )
> 
> C:\Users\AustinH\workspace\microsoft\dotnet\corefx>if /I [Windows_NT] == [Debug] (set CMAKE_BUILD_TYPE=Debug  && shift & goto Arg_Loop )
> 
> C:\Users\AustinH\workspace\microsoft\dotnet\corefx>if /I [Windows_NT] == [AnyCPU] (set __BuildArch=x64  && set __VCBuildArch=x86_amd64  && shift & goto Arg_Loop )
> 
> C:\Users\AustinH\workspace\microsoft\dotnet\corefx>if /I [Windows_NT] == [x86] (set __BuildArch=x86  && set __VCBuildArch=x86  && shift & goto Arg_Loop )
> 
> C:\Users\AustinH\workspace\microsoft\dotnet\corefx>if /I [Windows_NT] == [arm] (set __BuildArch=arm  && set __VCBuildArch=x86_arm  && set __SDKVersion="-DCMAKE_SYSTEM_VERSION=10.0"  && shift & goto Arg_Loop )
> 
> C:\Users\AustinH\workspace\microsoft\dotnet\corefx>if /I [Windows_NT] == [x64] (set __BuildArch=x64  && set __VCBuildArch=x86_amd64  && shift & goto Arg_Loop )
> 
> C:\Users\AustinH\workspace\microsoft\dotnet\corefx>if /I [Windows_NT] == [amd64] (set __BuildArch=x64  && set __VCBuildArch=x86_amd64  && shift & goto Arg_Loop )
> 
> C:\Users\AustinH\workspace\microsoft\dotnet\corefx>if /I [Windows_NT] == [arm64] (set __BuildArch=arm64  && set __VCBuildArch=arm64  && shift & goto Arg_Loop )
> 
> C:\Users\AustinH\workspace\microsoft\dotnet\corefx>if /I [Windows_NT] == [toolsetDir] (set "__ToolsetDir=--numproc"  && shift && shift & goto Arg_Loop )
> 
> C:\Users\AustinH\workspace\microsoft\dotnet\corefx>if /I [Windows_NT] == [--TargetGroup] (set "__TargetGroup=--numproc"  && shift && shift & goto Arg_Loop )
> 
> C:\Users\AustinH\workspace\microsoft\dotnet\corefx>shift
> 
> C:\Users\AustinH\workspace\microsoft\dotnet\corefx>goto :Arg_Loop
> 
> C:\Users\AustinH\workspace\microsoft\dotnet\corefx>if [--numproc] == [] goto :ToolsVersion
> 
> C:\Users\AustinH\workspace\microsoft\dotnet\corefx>if /I [--numproc] == [Release] (set CMAKE_BUILD_TYPE=Release  && shift & goto Arg_Loop )
> 
> C:\Users\AustinH\workspace\microsoft\dotnet\corefx>if /I [--numproc] == [Debug] (set CMAKE_BUILD_TYPE=Debug  && shift & goto Arg_Loop )
> 
> C:\Users\AustinH\workspace\microsoft\dotnet\corefx>if /I [--numproc] == [AnyCPU] (set __BuildArch=x64  && set __VCBuildArch=x86_amd64  && shift & goto Arg_Loop )
> 
> C:\Users\AustinH\workspace\microsoft\dotnet\corefx>if /I [--numproc] == [x86] (set __BuildArch=x86  && set __VCBuildArch=x86  && shift & goto Arg_Loop )
> 
> C:\Users\AustinH\workspace\microsoft\dotnet\corefx>if /I [--numproc] == [arm] (set __BuildArch=arm  && set __VCBuildArch=x86_arm  && set __SDKVersion="-DCMAKE_SYSTEM_VERSION=10.0"  && shift & goto Arg_Loop )
> 
> C:\Users\AustinH\workspace\microsoft\dotnet\corefx>if /I [--numproc] == [x64] (set __BuildArch=x64  && set __VCBuildArch=x86_amd64  && shift & goto Arg_Loop )
> 
> C:\Users\AustinH\workspace\microsoft\dotnet\corefx>if /I [--numproc] == [amd64] (set __BuildArch=x64  && set __VCBuildArch=x86_amd64  && shift & goto Arg_Loop )
> 
> C:\Users\AustinH\workspace\microsoft\dotnet\corefx>if /I [--numproc] == [arm64] (set __BuildArch=arm64  && set __VCBuildArch=arm64  && shift & goto Arg_Loop )
> 
> C:\Users\AustinH\workspace\microsoft\dotnet\corefx>if /I [--numproc] == [toolsetDir] (set "__ToolsetDir=8"  && shift && shift & goto Arg_Loop )
> 
> C:\Users\AustinH\workspace\microsoft\dotnet\corefx>if /I [--numproc] == [--TargetGroup] (set "__TargetGroup=8"  && shift && shift & goto Arg_Loop )
> 
> C:\Users\AustinH\workspace\microsoft\dotnet\corefx>shift
> 
> C:\Users\AustinH\workspace\microsoft\dotnet\corefx>goto :Arg_Loop
> 
> C:\Users\AustinH\workspace\microsoft\dotnet\corefx>if [8] == [] goto :ToolsVersion
> 
> C:\Users\AustinH\workspace\microsoft\dotnet\corefx>if /I [8] == [Release] (set CMAKE_BUILD_TYPE=Release  && shift & goto Arg_Loop )
> 
> C:\Users\AustinH\workspace\microsoft\dotnet\corefx>if /I [8] == [Debug] (set CMAKE_BUILD_TYPE=Debug  && shift & goto Arg_Loop )
> 
> C:\Users\AustinH\workspace\microsoft\dotnet\corefx>if /I [8] == [AnyCPU] (set __BuildArch=x64  && set __VCBuildArch=x86_amd64  && shift & goto Arg_Loop )
> 
> C:\Users\AustinH\workspace\microsoft\dotnet\corefx>if /I [8] == [x86] (set __BuildArch=x86  && set __VCBuildArch=x86  && shift & goto Arg_Loop )
> 
> C:\Users\AustinH\workspace\microsoft\dotnet\corefx>if /I [8] == [arm] (set __BuildArch=arm  && set __VCBuildArch=x86_arm  && set __SDKVersion="-DCMAKE_SYSTEM_VERSION=10.0"  && shift & goto Arg_Loop )
> 
> C:\Users\AustinH\workspace\microsoft\dotnet\corefx>if /I [8] == [x64] (set __BuildArch=x64  && set __VCBuildArch=x86_amd64  && shift & goto Arg_Loop )
> 
> C:\Users\AustinH\workspace\microsoft\dotnet\corefx>if /I [8] == [amd64] (set __BuildArch=x64  && set __VCBuildArch=x86_amd64  && shift & goto Arg_Loop )
> 
> C:\Users\AustinH\workspace\microsoft\dotnet\corefx>if /I [8] == [arm64] (set __BuildArch=arm64  && set __VCBuildArch=arm64  && shift & goto Arg_Loop )
> 
> C:\Users\AustinH\workspace\microsoft\dotnet\corefx>if /I [8] == [toolsetDir] (set "__ToolsetDir=toolSetDir"  && shift && shift & goto Arg_Loop )
> 
> C:\Users\AustinH\workspace\microsoft\dotnet\corefx>if /I [8] == [--TargetGroup] (set "__TargetGroup=toolSetDir"  && shift && shift & goto Arg_Loop )
> 
> C:\Users\AustinH\workspace\microsoft\dotnet\corefx>shift
> 
> C:\Users\AustinH\workspace\microsoft\dotnet\corefx>goto :Arg_Loop
> 
> C:\Users\AustinH\workspace\microsoft\dotnet\corefx>if [toolSetDir] == [] goto :ToolsVersion
> 
> C:\Users\AustinH\workspace\microsoft\dotnet\corefx>if /I [toolSetDir] == [Release] (set CMAKE_BUILD_TYPE=Release  && shift & goto Arg_Loop )
> 
> C:\Users\AustinH\workspace\microsoft\dotnet\corefx>if /I [toolSetDir] == [Debug] (set CMAKE_BUILD_TYPE=Debug  && shift & goto Arg_Loop )
> 
> C:\Users\AustinH\workspace\microsoft\dotnet\corefx>if /I [toolSetDir] == [AnyCPU] (set __BuildArch=x64  && set __VCBuildArch=x86_amd64  && shift & goto Arg_Loop )
> 
> C:\Users\AustinH\workspace\microsoft\dotnet\corefx>if /I [toolSetDir] == [x86] (set __BuildArch=x86  && set __VCBuildArch=x86  && shift & goto Arg_Loop )
> 
> C:\Users\AustinH\workspace\microsoft\dotnet\corefx>if /I [toolSetDir] == [arm] (set __BuildArch=arm  && set __VCBuildArch=x86_arm  && set __SDKVersion="-DCMAKE_SYSTEM_VERSION=10.0"  && shift & goto Arg_Loop )
> 
> C:\Users\AustinH\workspace\microsoft\dotnet\corefx>if /I [toolSetDir] == [x64] (set __BuildArch=x64  && set __VCBuildArch=x86_amd64  && shift & goto Arg_Loop )
> 
> C:\Users\AustinH\workspace\microsoft\dotnet\corefx>if /I [toolSetDir] == [amd64] (set __BuildArch=x64  && set __VCBuildArch=x86_amd64  && shift & goto Arg_Loop )
> 
> C:\Users\AustinH\workspace\microsoft\dotnet\corefx>if /I [toolSetDir] == [arm64] (set __BuildArch=arm64  && set __VCBuildArch=arm64  && shift & goto Arg_Loop )
> 
> C:\Users\AustinH\workspace\microsoft\dotnet\corefx>if /I [toolSetDir] == [toolsetDir] (set "__ToolsetDir=c:\tools\clr"  && shift && shift & goto Arg_Loop )
> 
> C:\Users\AustinH\workspace\microsoft\dotnet\corefx>if [] == [] goto :ToolsVersion
> 
> C:\Users\AustinH\workspace\microsoft\dotnet\corefx>if not defined VisualStudioVersion (
> if defined VS150COMNTOOLS (
> call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\Common7\Tools\\VsDevCmd.bat"
>  goto :VS2017
> )  else if defined VS140COMNTOOLS (
> call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\Tools\\VsDevCmd.bat"
>  goto :VS2015
> )
>  goto :MissingVersion
> )
> 
> C:\Users\AustinH\workspace\microsoft\dotnet\corefx>if "15.0" == "15.0" (goto :VS2017 )  else if "15.0" == "14.0" (goto :VS2015 )
> 
> C:\Users\AustinH\workspace\microsoft\dotnet\corefx>set __VSVersion=vs2017
> 
> C:\Users\AustinH\workspace\microsoft\dotnet\corefx>set __PlatformToolset=v141
> 
> C:\Users\AustinH\workspace\microsoft\dotnet\corefx>if NOT "x64" == "arm64" (call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\Common7\Tools\\..\..\VC\Auxiliary\Build\vcvarsall.bat" x86_amd64 )
> **********************************************************************
> ** Visual Studio 2017 Developer Command Prompt v15.0.26228.9
> ** Copyright (c) 2017 Microsoft Corporation
> **********************************************************************
> [vcvarsall.bat] Environment initialized for: 'x86_x64'
> Commencing build of native components
> 
> -- The C compiler identification is unknown
> -- The CXX compiler identification is unknown
> CMake Error at CMakeLists.txt:28 (project):
>   No CMAKE_C_COMPILER could be found.
> 
> 
> 
> CMake Error at CMakeLists.txt:28 (project):
>   No CMAKE_CXX_COMPILER could be found.
> 
> 
> 
> -- Configuring incomplete, errors occurred!
> See also "C:/Users/AustinH/workspace/microsoft/dotnet/corefx/bin/obj/Windows_NT.x64.Debug/native/CMakeFiles/CMakeOutput.log".
> See also "C:/Users/AustinH/workspace/microsoft/dotnet/corefx/bin/obj/Windows_NT.x64.Debug/native/CMakeFiles/CMakeError.log".
> Failed to generate native component build project!
> Command execution failed with exit code 1.
> 
> C:\Users\AustinH\workspace\microsoft\dotnet\corefx>exit /b 1

**Comment by tannergooding** [comment]
After stripping out all the path information, the only delta's between my output and yours is:
* I have enterprise edition, while you have professional edition
* You appear to have VS2015 installed SxS (I did validate this, going to bring up another SxS machien to revalidate)
  * You're VS140COMNTOOLS path is set to `C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\Tools\\VsDevCmd.bat`, while mine is set to `C:\Program Files (x86)\Microsoft Visual Studio\Shared\14.0\Common7\Tools\\VsDevCmd.bat`. So maybe something weird about specific SxS installs...

Neither of these should matter though.

**Comment by berdon** [comment]
Could it be because I had a RC version of VS2017 before the recent release and updated post? What process makes cmake aware of VS2017?

Thanks for your time btw.

**Comment by tinchou** [comment]
Do you have Windows 8.1 SDK?

**Comment by berdon** [comment]
Yes

**Comment by Vertygo** [comment]
I have bumped into same issue as @berdon.  What version of CMake are you using @tannergooding?
My CMake version is 3.7.2.

**Comment by Vertygo** [comment]
It seems like https://github.com/dotnet/corefx/pull/12790 broke it. I have made some small changes and made PR. It is tested against with VS 2017 but also needs to be checked with VS 2015.

**Pull request merged**
