### PR TITLE
Update to latest compiler version with new nullable metadata

### PR DESCRIPTION
**Pull request by agocke**

### CODE REVIEW

**Comment by agocke** [comment]
FYI @safern I'm trying out the change here before we have to do the whole arcade loop

**Comment by safern** [comment]
I would suspect we need to add NullableContextAttribute doc id to DefaultGenApiDocId.txt.

**Comment by agocke** [comment]
Sounds good, I'll wait for the failure then we can add it to the branch and make sure that fixes it

**Comment by safern** [comment]
That was easier than expected. Might be worth checking the bin logs to make sure it is using the expected version. 

I’m on my phone but I can check that when I get home if you haven’t had a chance.

**Comment by agocke** [comment]
Yup, I'm looking into it

**Comment by agocke** [comment]
@safern You were correct -- I got confused by time zones :)

This should be the right build. I got it to fail locally and succeed after adding the change to the DefaultGenApiDocids

**Comment by safern** [comment]
Thanks, @agocke -- It looks like some tests are failing. It looks like they're missing a parenthesis:

```cs
input = input[..idx] + (char)ushort.Parse(input.Substring(idx + 1, 4), NumberStyles.AllowHexSpecifier, CultureInfo.InvariantCulture) + input[idx + 6..];
```

Should be
```cs
input = input[..idx] + (char)ushort.Parse(input.Substring(idx + 1, 4), NumberStyles.AllowHexSpecifier, CultureInfo.InvariantCulture) + input[(idx + 6)..];
```

Right?

**Comment by agocke** [comment]
Yup, exactly. This was a breaking change to the precedence of the Range operator that now places it above the precedence of the binary operators (like +)

**Comment by safern** [comment]
Great. Thanks for confirming. Hopefully that is the last issue we hit 😄 

I guess the plan is, one this is green, to do a manual arcade update with darc directly into the PR rather than leaving the overridden version?

**Comment by agocke** [comment]
Yup, that's my plan. I don't know how to do the manual update though :)

**Comment by safern** [comment]
I know how to, it is fairly simple, however I think you need to be part of the arcade contributors working group in github (which I would guess you already are). Ping me offline if you're curious how to, if not I can do it and push to your branch, whichever works for me.

**Comment by safern** [comment]
Ok, so just a flaky test failed. Everything else seems good. I merged the PR in arcade. Then we can get an update once it's produced and release by arcade-validation.

I'd suggest, that we probably do this in master first, then cherry-pick to 3.0, because we also need this in master for metadata coherency.

**Comment by agocke** [comment]
@safern do you want to take over this PR? I can publish it and leave it to you

**Comment by safern** [comment]
> @safern do you want to take over this PR? I can publish it and leave it to you

Sounds good. I'll take care of the following steps. Thanks for pushing towards getting it green, @agocke :)

**Comment by agocke** [comment]
@safern The System.Memory test failures seem new and probably unrelated to the compiler change?

**Comment by agocke** [comment]
Actually i don't even see test failures, just 503s in the tests when hitting a service

**Comment by wtgodbe** [comment]
> error : Request to https://dev.azure.com/dnceng/public/_apis/test/runs?api-version=5.0-preview.2 returned failed status 503 Service Unavailable [D:\a\1\s\eng\sendtohelix.proj]

**Comment by wtgodbe** [comment]
There are also some test infra failures in https://mc.dot.net/#/user/dotnet-bot/pr~2Fdotnet~2Fcorefx~2Frefs~2Fpull~2F38973~2Fmerge/test~2Ffunctional~2Fcli~2Finnerloop~2F/20190627.22, but they all appear to be https://github.com/dotnet/core-eng/issues/6824

**Comment by safern** [comment]
Everything looks like infrastructure issues caused by the azure test explorer API being down.

**Pull request merged**
