### PR TITLE
Enabling tests that were disabled for issue #2821.

### PR DESCRIPTION
**Pull request by eerhardt**

### CODE REVIEW

**Comment by eerhardt** [comment]
@tarekgh

**Comment by stephentoub** [comment]
Assuming it passes, LGTM.

**Comment by eerhardt** [comment]
@dotnet-bot test this please

**Comment by tarekgh** [comment]
LGTM too.

**Comment by stephentoub** [comment]
Hmm.  This failed with a bunch of errors like:
```
terminate called after throwing an instance of 'PAL_SEHException'
09:22:31 ./run-test.sh: line 156:  4854 Aborted                 (core dumped) ./corerun xunit.console.netcore.exe $testDllName -xml testResults.xml -notrait category=failing -notrait category=OuterLoop -notrait category=$xunitOSCategory
```
Let's see if it happens again and/or with other PRs.

**Comment by stephentoub** [comment]
@dotnet-bot test this please

**Comment by stephentoub** [comment]
@mmitche, can we get access to such core dumps somehow?

**Comment by stephentoub** [comment]
This looks like it's due to a recent coreclr change.  I'm working with @janvorli on it.

**Comment by janvorli** [comment]
I have a fix and will create a PR in coreclr for it soon.

**Comment by janvorli** [comment]
@stephentoub I have checked in a fix to coreclr

**Comment by ellismg** [comment]
@dotnet-bot test this please

**Comment by stephentoub** [comment]
Thanks for fixing, Jan.

**Comment by mmitche** [comment]
@stephentoub I think we might be able to on the machine.  Btw, I'm seeing these failures consistently since this morning.  The change that showed the failure is uninteresting, but we did of course take in new changes for coreclr for this.

**Pull request merged**
