### PR TITLE
Enable more ManagedHandler tests

### PR DESCRIPTION
**Pull request by stephentoub**
Required a few small src fixes:
- Special-case handling of count==0 reads
- Wrap IOExceptions and InvalidOperationExceptions from SendAsync in HttpRequestException
- Add a ToString override to SafeFreeContextBufferChannelBinding to output the value of the binding rather than the type name in order to match WinHttpHandler's binding's behavior (@davidsh, is this the right thing to do?)

cc: @geoffkizer, @davidsh

### CODE REVIEW

**Comment by davidsh** [comment]
>Add a ToString override to SafeFreeContextBufferChannelBinding to output the value of the binding rather than the type name in order to match WinHttpHandler's binding's behavior (@davidsh, is this the right thing to do?)

Yes, it is good to match the ToString() behavior to show the bytes.  But the reality is that consumers of this (such as WCF) will fetch real bytes via marshaling the unmanaged memory from the Intptr.  But it helps debugging this (especially in Visual Studio) if the ToString() has the override the show the byte array.

**Comment by stephentoub** [comment]
> Yes, it is good to match the ToString() behavior to show the bytes

Ok, thanks for confirming.

**Comment by stephentoub** [comment]
@dotnet-bot test NETFX x86 Release Build please

**Comment by stephentoub** [comment]
@dotnet-bot test outerloop netcoreapp Ubuntu14.04 Debug
@dotnet-bot test outerloop netcoreapp Windows_NT Debug

**Comment by stephentoub** [comment]
@dotnet-bot test OuterLoop netcoreapp Ubuntu16.10 Debug x64 please

**Comment by stephentoub** [comment]
@dotnet-bot test OuterLoop netcoreapp Ubuntu14.04 Debug x64 please

**Comment by geoffkizer** [comment]
Minor question: When would we see InvalidOperationException?

**Comment by stephentoub** [comment]
> When would we see InvalidOperationException?

I'm not sure.  It's just the set that the previous handlers were wrapping.

**Comment by geoffkizer** [comment]
OK, thanks.  LGTM.

**Comment by davidsh** [comment]
>When would we see InvalidOperationException?

We use that exception and sometimes wrap it in HttpRequestException when we have invalid combinations of settings but only can valid that during the SendAsync() call.

**Comment by davidsh** [comment]
We can't validate combinations of property settings in the property setters because we can't have a required ordering of what to set first, set next, etc.  So, we validate the whole set at SendAsync time

**Comment by stephentoub** [comment]
@dotnet-bot test OuterLoop netcoreapp Ubuntu14.04 Debug x64 please

**Pull request merged**
