### PR TITLE
Expose GC.GetAllocatedBytesForCurrentThread in netcoreapp1.1

### PR DESCRIPTION
**Pull request by jkotas**

### CODE REVIEW

**Comment by jkotas** [comment]
Fix #10157

cc @Maoni0

**Comment by stephentoub** [comment]
@dotnet-bot Test Innerloop Ubuntu14.04 Debug Build and Test  please (build timeout) FYI, @mmitche and @adityamandaleeka

**Comment by stephentoub** [comment]
LGTM

**Comment by mmitche** [comment]
@stephentoub Are you sure we should be merging these?  They're timeouts while running tests.

/mnt/j/workspace/dotnet_corefx/master/ubuntu14.04_debug_prtest/Tools/tests.targets(271,5): error : One or more tests failed while running tests from 'System.Reflection.Emit.Tests' please check log for details! [/mnt/j/workspace/dotnet_corefx/master/ubuntu14.04_debug_prtest/src/System.Reflection.Emit/tests/System.Reflection.Emit.Tests.csproj]

**Comment by stephentoub** [comment]
@mmitche, that's how the issue I've been mentioning on Ubuntu manifests, and why I've started to cc you and Aditya. It's not specific to any particular test suite; it just ends up spinning page failing at seemingly random places. This PR didn't change and doesn't impact that test suite.

**Comment by Maoni0** [comment]
cool :) thanks Jan. @swgillespie, @KrzysztofCwalina,  - you don't need to use reflection on this anymore.

**Pull request merged**
