### PR TITLE
[release/2.1] Add Fedora 33 runtime ids

### PR DESCRIPTION
**Pull request by omajid**
Fedora 32 is gearing up for release[1], and in-development version of Fedora has been offiically labelled as being Fedora 33:

    $ podman run -it fedora:33 cat /etc/os-release
    NAME=Fedora
    VERSION="33 (Container Image)"
    ID=fedora
    VERSION_ID=33
    VERSION_CODENAME=""
    PLATFORM_ID="platform:f33"
    PRETTY_NAME="Fedora 33 (Container Image)"
    ANSI_COLOR="0;34"
    LOGO=fedora-logo-icon
    CPE_NAME="cpe:/o:fedoraproject:fedora:33"
    HOME_URL="https://fedoraproject.org/"
    DOCUMENTATION_URL="https://docs.fedoraproject.org/en-US/fedora/rawhide/system-administrators-guide/"
    SUPPORT_URL="https://fedoraproject.org/wiki/Communicating_and_getting_help"
    BUG_REPORT_URL="https://bugzilla.redhat.com/"
    REDHAT_BUGZILLA_PRODUCT="Fedora"
    REDHAT_BUGZILLA_PRODUCT_VERSION=rawhide
    REDHAT_SUPPORT_PRODUCT="Fedora"
    REDHAT_SUPPORT_PRODUCT_VERSION=rawhide
    PRIVACY_POLICY_URL="https://fedoraproject.org/wiki/Legal:PrivacyPolicy"
    VARIANT="Container Image"
    VARIANT_ID=container

[1] https://fedorapeople.org/groups/schedule/f-32/f-32-key-tasks.html

This is a backport of https://github.com/dotnet/runtime/pull/32752

### CODE REVIEW

**Comment by omajid** [comment]
cc @bartonjs

**Review by bartonjs — APPROVED** [review]

**Comment by omajid** [comment]
Does this need a `servicing-consider` tag?

**Comment by bartonjs** [comment]
@leecow The 2.1 version of the RID update wasn't marked as consider when you marked the 3.1 version as approved.  Rather than being assertive and setting approved myself I'm poking you to do it instead :smile:.

**Comment by ericstj** [comment]
discussed in Tactics as tell-mode, marking approved.

**Comment by omajid** [comment]
Can someone please merge this?

**Review by Anipik — APPROVED** [review]

**Pull request merged**
