### PR TITLE
Remove hardcoded Windows_NT from System.Runtime.Tests

### PR DESCRIPTION
**Pull request by stephentoub**
cc: @ericstj, @sokket, @hughbe

### CODE REVIEW

**Comment by stephentoub** [comment]
bin clash failiure:
```
10:07:38 D:\j\workspace\centos7.1_rel---afe88ac5\build.proj -->
10:07:38   Global Properties:
10:07:38     ConfigurationGroup = Release
10:07:38     OSGroup = Linux
10:07:38     SkipTests = true
10:07:38     TestNugetRuntimeId = centos.7-x64
10:07:38 D:\j\workspace\centos7.1_rel---afe88ac5\src\tests.builds -->
10:07:38   Global Properties:
10:07:38     ConfigurationGroup = Release
10:07:38     SkipTests = true
10:07:38     TestNugetRuntimeId = centos.7-x64
10:07:38     DefaultBuildAllTarget = BuildAndTest
10:07:38     BuildAllProjects = true
10:07:38     InputOSGroup = Linux
10:07:38     FilterToOSGroup = Linux
10:07:38 D:\j\workspace\centos7.1_rel---afe88ac5\src\System.Runtime\tests\System.Runtime.Tests.builds -->
10:07:38   Global Properties:
10:07:38     ConfigurationGroup = Release
10:07:38     SkipTests = true
10:07:38     TestNugetRuntimeId = centos.7-x64
10:07:38     DefaultBuildAllTarget = BuildAndTest
10:07:38     BuildAllProjects = true
10:07:38     InputOSGroup = Linux
10:07:38     FilterToOSGroup = Linux
10:07:38     BuildAllOSGroups = false
10:07:38 D:\j\workspace\centos7.1_rel---afe88ac5\src\System.Runtime\tests\System.Runtime.Tests.csproj -->
10:07:38   Global Properties:
10:07:38     ConfigurationGroup = Release
10:07:38     SkipTests = true
10:07:38     TestNugetRuntimeId = centos.7-x64
10:07:38     BuildAllProjects = true
10:07:38     InputOSGroup = Linux
10:07:38 D:\j\workspace\centos7.1_rel---afe88ac5\src\System.Private.Uri\src\System.Private.Uri.csproj
10:07:38   Global Properties:
10:07:38     ConfigurationGroup = Release
10:07:38     SkipTests = true
10:07:38     TestNugetRuntimeId = centos.7-x64
10:07:38     BuildAllProjects = true
10:07:38     InputOSGroup = Linux
10:07:38 
10:07:38 D:\j\workspace\centos7.1_rel---afe88ac5\build.proj -->
10:07:38   Global Properties:
10:07:38     ConfigurationGroup = Release
10:07:38     OSGroup = Linux
10:07:38     SkipTests = true
10:07:38     TestNugetRuntimeId = centos.7-x64
10:07:38 D:\j\workspace\centos7.1_rel---afe88ac5\src\dirs.proj -->
10:07:38   Global Properties:
10:07:38     ConfigurationGroup = Release
10:07:38     SkipTests = true
10:07:38     TestNugetRuntimeId = centos.7-x64
10:07:38     DefaultBuildAllTarget = BuildAndTest
10:07:38     BuildAllProjects = true
10:07:38     InputOSGroup = Linux
10:07:38     FilterToOSGroup = Linux
10:07:38 D:\j\workspace\centos7.1_rel---afe88ac5\src\src.builds -->
10:07:38   Global Properties:
10:07:38     ConfigurationGroup = Release
10:07:38     SkipTests = true
10:07:38     TestNugetRuntimeId = centos.7-x64
10:07:38     DefaultBuildAllTarget = BuildAndTest
10:07:38     BuildAllProjects = true
10:07:38     InputOSGroup = Linux
10:07:38     FilterToOSGroup = Linux
10:07:38 D:\j\workspace\centos7.1_rel---afe88ac5\src\System.Collections\src\System.Collections.builds -->
10:07:38   Global Properties:
10:07:38     ConfigurationGroup = Release
10:07:38     SkipTests = true
10:07:38     TestNugetRuntimeId = centos.7-x64
10:07:38     DefaultBuildAllTarget = BuildAndTest
10:07:38     BuildAllProjects = true
10:07:38     InputOSGroup = Linux
10:07:38     FilterToOSGroup = Linux
10:07:38 D:\j\workspace\centos7.1_rel---afe88ac5\src\System.Collections\src\System.Collections.csproj -->
10:07:38   Global Properties:
10:07:38     ConfigurationGroup = Release
10:07:38     SkipTests = true
10:07:38     TestNugetRuntimeId = centos.7-x64
10:07:38     BuildAllProjects = true
10:07:38     InputOSGroup = Linux
10:07:38 D:\j\workspace\centos7.1_rel---afe88ac5\src\System.Runtime\src\System.Runtime.csproj -->
10:07:38   Global Properties:
10:07:38     ConfigurationGroup = Release
10:07:38     SkipTests = true
10:07:38     TestNugetRuntimeId = centos.7-x64
10:07:38     BuildAllProjects = true
10:07:38     InputOSGroup = Linux
10:07:38 D:\j\workspace\centos7.1_rel---afe88ac5\src\System.Private.Uri\src\System.Private.Uri.csproj
10:07:38   Global Properties:
10:07:38     ConfigurationGroup = Release
10:07:38     SkipTests = true
10:07:38     TestNugetRuntimeId = centos.7-x64
10:07:38     BuildAllProjects = true
10:07:38     InputOSGroup = Linux
10:07:38     OSGroup = Windows_NT
10:07:38 
10:07:38 
10:07:38 
MSBUILD : error MSB4015: The build stopped unexpectedly because the "ReusableLogger" logger failed unexpectedly during shutdown.
10:07:38 System.Exception: 1 bin clashes were detected during the build.
10:07:38    at Microsoft.DotNet.Build.Tasks.BinClashLogger.Shutdown()
10:07:38    at Microsoft.Build.Evaluation.ProjectCollection.ReusableLogger.Shutdown()
10:07:38    at Microsoft.Build.BackEnd.Logging.LoggingService.ShutdownLogger(ILogger logger)
```

**Comment by ericstj** [comment]
You need to pass in the OSGroup you are building with.  There should be some other tests that do this.

**Comment by ericstj** [comment]
Here's a place where @sokket did this in another project: https://github.com/dotnet/corefx/commit/752599494fce80b5d0059a9090fdc010d8c7f45b#diff-78b2ecfef898c6a676cf76e776acbc18R24

I'm guessing the System.Runtime test was just missed.

**Comment by stephentoub** [comment]
Thanks, Eric.

**Comment by ericstj** [comment]
NP, thanks for making the fix.

**Pull request merged**
