### PR TITLE
Disable parts of MemoryMappedFile tests for desktop

### PR DESCRIPTION
**Pull request by danmosemsft**
Fix https://github.com/dotnet/corefx/issues/17725 by disabling for desktop.

This was an intentional improvement made in https://github.com/dotnet/corefx/commit/e3e764f22db3e2f6f1fb9f0b78d291caea52d3d9 by @stephentoub .

### CODE REVIEW

**Comment by danmosemsft** [comment]
Also 
Fix https://github.com/dotnet/corefx/issues/17724
Fix https://github.com/dotnet/corefx/issues/17726

This is not related to the change in MMF from FileShare.None to FileShare.Read.

Both caused by using `MemoryMappedFile.CreateFromFile` passing FileMode.Truncate. Due to a bug in .NET Framework, this would always produce `ArgumentException : Combining FileMode: Truncate with FileSystemRights: ReadData, CreateFiles is invalid. FileMode.Truncate is valid only when used with FileSystemRights.Write.`

This exception is because `FileMode.Truncate` is only legal when the file is opened for `FileAccess.Write`. 

In .NET Framework,  `MemoryMappedFile.CreateFromFile` uses `MemoryMappedFileAccess.ReadWrite` which is passed to FileStream as `FileSystemRights.ReadData | FileSystemRights.WriteData`. 
https://referencesource.microsoft.com/#System.Core/System/IO/MemoryMappedFiles/MemoryMappedFile.cs,105

In FileStream that is checked at 
https://referencesource.microsoft.com/#mscorlib/system/io/filestream.cs,688
```c#
                if (fileSystemRights == FileSystemRights.Write) {
```
Which fails, therefore it acts as if there is no write access, and fails because `FileMode.Truncate` was passed.

It should have done
```c#
               if (fileSystemRights & FileSystemRights.Write) == 0)) {
```
as it is further up. 

This bug is now fixed in Core, where it just checks
``` c#
if ((access & FileAccess.Write) == 0)
```

Therefore I disabled tests that pass `FileMode.Truncate` when running on .NET Framework.

**Comment by danmosemsft** [comment]
@safern @stephentoub

**Comment by stephentoub** [comment]
Looks like you and @ianhays are working on the same issues:
https://github.com/dotnet/corefx/pull/17655
https://github.com/dotnet/corefx/pull/17622

**Comment by danmosemsft** [comment]
Ah - OK, @ianhays is out until 4/17. I'll try to get the discsusions resolved one way or another to figure which approach to merge.

**Comment by ianhays** [comment]
>Turns out this is not related to the change in MMF from FileShare.None to FileShare.Read in e3e764f.

>Looks like you and @ianhays are working on the same issues:

Ouch, looks like from your comment we ended up going through the same investigation process. I'm glad at least we came to the same conclusion :)

>I'll try to get the discsusions resolved one way or another to figure which approach to merge.

I think it would be wise to disable FileMode.Truncate to match netfx. Unintentional changes like allowing FileMode.Truncate where we previously always threw make me nervous. If we want to stay with the netcoreapp behavior then we should audit our tests and really make sure there aren't any unintentional breaks that we missed.

**Comment by stephentoub** [comment]
@danmosemsft, should this be closed, or updated?

**Comment by danmosemsft** [comment]
Since the change necessary is completely different to this PR I'm going to close it. @ianhays would you mind making the necessary change(s)?

**Pull request closed without merging**
