### PR TITLE
Correctly cleaning up the ToolRuntime folder once a new version is required.

### PR DESCRIPTION
**Pull request by joperezr**
Corefx has the same issue than buildtools: dotnet/buildtools#474
This line fixes that here as well.

CC: @weshaggard

### CODE REVIEW

**Comment by mellinoe** [comment]
lgtm

**Comment by weshaggard** [comment]
LGTM

**Comment by stephentoub** [comment]
@dotnet-bot test this please

**Comment by joperezr** [comment]
@dotnet-bot test this please

**Comment by joperezr** [comment]
@dotnet-bot test this please

**Pull request merged**
