### PR TITLE
Expose/Test span-based CopyTo/Async methods

### PR DESCRIPTION
**Pull request by manandre**
Depends on https://github.com/dotnet/coreclr/pull/27639
Contributes to #21472

### CODE REVIEW

**Review by GrabYourPitchforks — APPROVED** [review]
Aside from public API fixups resulting from swapping parameters in the coreclr issue, unit tests LGTM. Thanks! :)

**Comment by GrabYourPitchforks** [comment]
On further reflection, would it be possible to add tests that check both the span-based and the array-based code paths that were added? The private `Stream` implementation overrides both methods, so we should test both. This might involve writing a test `Stream` that can be configured to dispatch to either overload.

**Comment by maryamariyan** [comment]
Thank you for your contribution. As announced in dotnet/coreclr#27549 this repository will be moving to dotnet/runtime on November 13. If you would like to continue working on this PR after this date, the easiest way to move the change to dotnet/runtime is:
1.	In your corefx repository clone, create patch by running `git format-patch origin`
2.	In your runtime repository clone, apply the patch by running `git apply --directory src/corefx <path to the patch created in step 1>`

**Comment by maryamariyan** [comment]
Thank you for your contribution. As announced in #27549 the dotnet/runtime repository will be used going forward for changes to this code base. Closing this PR as no more changes will be accepted into master for this repository. If you’d like to continue working on this change please move it to dotnet/runtime.

**Pull request closed without merging**
