### PR TITLE
Several metadata reader bug fixes

### PR DESCRIPTION
**Pull request by nguerrera**
I've batched several metadata reader fixes together: #26, #260, #264, #816, #950 

The commits are well separated, so please see them for individual descriptions.

cc @tmat @ellismg @stephentoub

### CODE REVIEW

**Comment by mmitche** [comment]
This looks good (failed with the error mentioned in #988)

**Comment by nguerrera** [comment]
@dotnet-bot test this please

**Comment by nguerrera** [comment]
@ellismg @stephentoub Made the adjustments requested. Anything else?

**Comment by stephentoub** [comment]
LGTM.

**Comment by tmat** [comment]
:+1

**Pull request merged**
