### PR TITLE
Cleanup resources across all projects

### PR DESCRIPTION
**Pull request by tarekgh**
After this change we are going to have unified model for handling resources which is we always use resx files placed under Resources folder and the code will be automatically generated in SR.cs file.
We’ll access ant string resource using the SR class (e.g. SR.ArgumentException).

### CODE REVIEW

**Comment by tarekgh** [comment]
@weshaggard please have a look

**Comment by weshaggard** [comment]
The change looks correct to me.

**Comment by stephentoub** [comment]
@dotnet-bot test this please

**Comment by Maxwe11** [comment]
(consider add build-timeout)

**Comment by tarekgh** [comment]
Rebased to address merge conflict.

**Pull request merged**
