### PR TITLE
Remove LegacyNetCF serializer from XmlSerializer

### PR DESCRIPTION
**Pull request by khdang**

### CODE REVIEW

**Comment by stephentoub** [comment]
I don't have context on why this is being removed, but assuming that's the right thing to do, the mechanics of the change LGTM.

**Comment by khdang** [comment]
My understanding from previous reviews is that LegacyNetCf should be removed from CoreClr. @jkotas please let us know if that is not correct.

**Comment by jkotas** [comment]
Correct. LegacyNetCF serializer is unnecessary in the .NET Core implementation. It is only needed for Windows Phone Silverlight version that is built from different source.

**Comment by khdang** [comment]
Thanks!

**Pull request merged**
