### PR TITLE
Add documentation for building a single configuration of a csproj

### PR DESCRIPTION
**Pull request by mellinoe**
@maririos, @mattgal Is this what you had in mind for https://github.com/dotnet/corefx/issues/10439?

### CODE REVIEW

**Comment by mellinoe** [comment]
@weshaggard

**Comment by MattGal** [comment]
Change looks good to me and is easy to understand.  However, I think #10439 may have been with respect to enabling Run.exe to build a single project (I have tasks on me for next sprint that cover implementing this).  @maririos ?

**Comment by mellinoe** [comment]
I think @weshaggard was asking for something like this based on the comment [here](https://github.com/dotnet/corefx/pull/10359#r72675919). I'll let @maririos clarify, though.

**Comment by MattGal** [comment]
Sure, I definitely want your change just not sure (I got a bunch of @maririos' items assigned to me and sometimes lack context) what

**Comment by maririos** [comment]
> I think @weshaggard was asking for something like this based on the comment here. I'll let @maririos clarify, though.

Yes :) This PR addresses that issue

**Comment by mellinoe** [comment]
Thanks, I'll merge this in then.

**Comment by weshaggard** [comment]
Yes this documentation is what I was looking for. I of course would also like to make it easier to use your build scripts for individual projects as well which don't require people to go digging into the Tools directory directly.

**Pull request merged**
