### PR TITLE
Make IOrderedEnumerable covariant.

### LINKED ISSUE #2317: Make IOrderedEnumerable<T> covariant
Today, I was trying to convert an `IOrderedEnumerable<string>` to an `IOrderedEnumerable<object>`, but the compiler responded with an error. Looking into the interface, there doesn't seem to be any reason why it can't be [covariant](https://msdn.microsoft.com/en-us/library/dd799517%28v=vs.110%29.aspx), and in fact when I copied and pasted the interface and changed the class signature to `IOrderedEnumerable<out T>` everything compiled fine.

Can we change this in the BCL, as well? There doesn't seem to be a reason not to.

Sidenote: This **may** cause some [breaking changes](http://stackoverflow.com/a/2843563/4077294), but as the post points out this has already been done with `IEnumerable<T>` on a greater scale.

### Proposed API

```C#
 // Updates existing interface in being covariant.
public interface IOrderedEnumerable<out TElement> : IEnumerable<TElement>
{
    // Existing member
    IOrderedEnumerable<TElement> CreateOrderedEnumerable<TKey>(Func<TElement, TKey> keySelector, IComparer<TKey> comparer, bool descending);
}
```

*(edited by @terrajobst to include the API write-up from @JonHanna)*

### PR DESCRIPTION
**Pull request by JonHanna**
Fixes #2317

### CODE REVIEW

**Comment by stephentoub** [comment]
Thanks, but this needs to go through API review before it can come through as a PR.

**Comment by JonHanna** [comment]
Ah, I just misunderstood a label there.

**Comment by stephentoub** [comment]
> Ah, I just misunderstood a label there.

Yeah, they're confusing, and I think we're changing them to try to make them clearer.  @terrajobst?

**Comment by JonHanna** [comment]
Is there a list of them somewhere?

**Pull request closed without merging**
