### PR TITLE
Update Corefx Repo to depend on newer package versions

### PR DESCRIPTION
**Pull request by pallavit**
Update the NetCore packages across the corefx repo

### CODE REVIEW

**Comment by davidsh** [comment]
LGTM for System.Net.* libraries

**Comment by davidsh** [comment]
Test Innerloop Windows_NT Release Build and Test

**Comment by weshaggard** [comment]
@pallavit as you suspect these are only failing for release and likely a JIT bug. Can you please disable those tests and open a bug on this.

**Comment by ericstj** [comment]
These look like they might be real failures.  Repro'ing locally for me when applying your change.  Release only.

**Comment by pallavit** [comment]
Yes, these are real issues, I wanted to get a PR with only the package update and decouple my changes from it. I looked at the issue and all the changes that went in the 3 day time frame, since they repro only in release and not on debug (and fail at random points, while getting 2's complement of an index, at least that was the only relation I could find between the tests) and all the packages are release, this is most likely a codegen bug which was a major change that went in the time frame :). I will disable the bugs with an active issue and ask the JIT team to take a look :)

**Comment by pallavit** [comment]
OpenSUSE failed in earlier jobs's well. So, triggering the run again. 
@dotnet-bot test this please.

**Comment by weshaggard** [comment]
@dotnet-bot test  Innerloop OpenSUSE13.2 Debug Build and Tes

**Comment by weshaggard** [comment]
@dotnet-bot test Innerloop OpenSUSE13.2 Debug Build and Test

**Comment by pallavit** [comment]
@dotnet-bot test Innerloop OpenSUSE13.2 Debug Build and Test

**Comment by weshaggard** [comment]
@pallavit don't worry about the OpenSUSE failures we think that is like a JIT issue as well. Can you update your PR to fix the merge issues and also add a note in the issue for the JIT team on the  OpenSUSE failures.

**Comment by pallavit** [comment]
> Can you update your PR to fix the merge issues and also add a note in the issue for the JIT team on the OpenSUSE failures.

Sure, will do. Also, will resolve the conflicts and merge the change. Thanks!

**Pull request merged**
