### PR TITLE
deal with dualmode sockets

### PR DESCRIPTION
**Pull request by wfurt**
This got broken by #30036.
We now use DualMode sockets and we can do IPv4 over IPv6 socket.  That confuses logic to construct data connection. 

With this change I tested both passive and active mode and I can get listing.

### CODE REVIEW

**Comment by wfurt** [comment]
fixes #37175

**Comment by stephentoub** [comment]
> This got broken by #30036.

This is just one piece of code that was apparently dependent on the behavior in 30036.  Is it not likely that 30036 may have broken other things as well, including in code we don't control?

**Comment by davidsh** [comment]
>Is it not likely that 30036 may have broken other things as well, including in code we don't control?

It is possible. It can be considered a breaking change. I think it's "ok" for things like this to change in a major release of .NET Core, i.e. 3.0.  But we should definitely document it in release notes and perhaps add more test coverage to other areas we suspect would be impacted.

@karelz

**Comment by wfurt** [comment]
I don't know how to assess the risk but it is certainly possible. FTP was particularly vulnerable as it deeply cares about address and manipulates two sockets in coordinated way. 
The exposure is only when no AddressFamily is specified. When AddressFamily is used we use one or other socket as specified.

**Comment by wfurt** [comment]
note that original #29414 request seems reasonable. Better support for IPv6 and/or dual stack seems like a good thing.

**Pull request merged**
