### PR TITLE
Add Stream and {Unmanaged}MemoryStream Span-based APIs

### PR DESCRIPTION
**Pull request by stephentoub**
- Add the new Span-based Read/Write overloads to the refs
- Add tests for the new methods

Depends on https://github.com/dotnet/coreclr/pull/13058 and https://github.com/dotnet/corert/pull/4231; will fail CI until those are merged and consumed into corefx.

(The test changes for UnmanagedMemoryStream look more extensive than they actually are, as I moved some tests between files to enable more easily reusing them for both the span-based and array-based read/write overloads.)

Contributes to dotnet/corefx#22381, dotnet/corefx#22388, and dotnet/corefx#22389.

cc: @jkotas, @JeremyKuhne, @KrzysztofCwalina

### CODE REVIEW

**Comment by stephentoub** [comment]
@dotnet-bot test this please

**Comment by stephentoub** [comment]
@dotnet-bot test this please

**Comment by stephentoub** [comment]
@dotnet-bot test this please

**Comment by jkotas** [comment]
@dotnet-bot test this please

**Pull request merged**
