### PR TITLE
[release/2.1] add new Ubuntu & Alpine versions to RID graph

### PR DESCRIPTION
**Pull request by wfurt**
This is port of #42928 for https://github.com/dotnet/runtime/issues/37000
Adds new RID for Ubuntu & Alpine. 
Marking as servicing-approved per discussion in https://github.com/dotnet/corefx/pull/42928

fixes  https://github.com/dotnet/runtime/issues/37000

### CODE REVIEW

**Comment by Anipik** [comment]
cc @danmosemsft @ericstj is this change for july or august release ?

**Comment by ericstj** [comment]
@Anipik soonest that fits schedule.  @wfurt any reason why it must be in one vs other?

**Review by Anipik — COMMENTED** [review]
can you add this package to packages.builds https://github.com/dotnet/corefx/blob/release/2.1/src/packages.builds#L26 file ?

**Comment by wfurt** [comment]
I was expecting this would get on next servicing train @ericstj

**Comment by wfurt** [comment]
> can you add this package to packages.builds https://github.com/dotnet/corefx/blob/release/2.1/src/packages.builds#L26 file ?

I can look into it. But it seems like we did not do it for the previous RID update @anipik.

**Comment by ericstj** [comment]
My question was if there was any specific need to get this earlier than later.  For instance is a partner blocked on this?  Do we need to sync with a particular date?   We'll of course get it on the "next" servicing train, but trying to gauge how important it would be to reset it for this if builds are already done.

**Comment by Anipik** [comment]
> I can look into it. But it seems like we did not do it for the previous RID update @Anipik.

It should be similar to https://github.com/dotnet/corefx/pull/42940

**Comment by wfurt** [comment]
no, Im not aware of anything like that.

**Comment by danmoseley** [comment]
@wfurt @ericstj Tactics indicate this would put RedHat handoff at risk if we take it for next month's release. They are asking whether we have evidence of customer impact here.  Do we ? Or is this general goodness.

I assume it's general goodness and we can wait a month, correct? Same applies to the 3.1 change.

**Comment by ericstj** [comment]
@danmosemsft that's the question I asked @wfurt and response was

> no, Im not aware of anything like that.

**Comment by danmoseley** [comment]
Oops, I thought that was answering a question about packaging. thanks

**Comment by leecow** [comment]
Thanks all, we'll get this into the August release.

**Review by Anipik — APPROVED** [review]

**Pull request merged**
