### PR TITLE
Disable some thread test since the required methods are not implemented in uwp yet.

### PR DESCRIPTION
**Pull request by tijoytom**
See #20766

### CODE REVIEW

**Comment by tijoytom** [comment]
@AntonLapounov FYI

**Comment by tijoytom** [comment]
retest Win x64 tests - Debug - Windows.10.Amd64.Open

**Comment by tijoytom** [comment]
retest Innerloop OSX10.12 Release x64 Build and Test

**Comment by tijoytom** [comment]
Not sure if the failures have anything to do with this change , but nevertheless  it's hard to see what failed with the new helix UI. It says 37 tests failed , and it shows me 39 pages to browse through . Most of them are skipped tests  ( Yellow colored) and i randomly select a page .

Here is the failure 
ERROR!!!: The write method timedout in 0 expected 1054 percentage difference: 1\r\nExpected: True\r\nActual:   False

**Comment by tijoytom** [comment]
retest Win x64 tests - Debug - Windows.10.Amd64.Open

**Comment by kouvel** [comment]
@dotnet-bot test Win x64 tests - Debug - Windows.10.Amd64.Open

**Comment by kouvel** [comment]
@dotnet-bot help

**Comment by kouvel** [comment]
@dotnet-bot test this please

**Comment by tijoytom** [comment]
Unrelated System.Data.SqlClient.Tests.DiagnosticTest/ExecuteReaderAsyncTest
Assert.Equal() Failure\nExpected: 42\nActual:   134

**Pull request merged**
