### PR TITLE
Make Unix root certs be findable again when validOnly: true is specified

### LINKED ISSUE #10801: Root certificate cannot be found using X509Store.Certificates.Find where validOnly=true in Linux
Repro: https://gist.github.com/iamjasonp/db0a20a6c4cae5d55b383608941742bb

In Ubuntu14.04, when using the API X509Store.Certificates.Find(X509FindType, string, **bool validOnly**), if _validOnly_ is set to true, no certificate in the root certificate store is deemed valid and no certificates are returned in the X509CertificateCollection

This happens for both the CurrentUser and the LocalMachine _Root_ store, but not the _My_ store

Attached repro does the following: 

* Downloads certificates from WCF test services - a client cert and a root cert
* Writes both certificates to the CurrentUser:My and CurrentUser:Root store 
* Attempts to use X509Store.Certificates.Find to find the certs, _validOnly=true_
  * Expected result: certificates can be found
  * Actual result (Windows): certificates are found
  * Actual result (Ubuntu14.04): cert installed to user store can be found, cert installed to root store cannot be found

* Opens the LocalMachine:Root store (readOnly) 
* Attempts to find a well-known root cert,  _validOnly=true_
  * Expected result: certificates can be found 
  * Actual result (Windows): certificates are found
  * Actual result (Ubuntu14.04): certificate is not found 

Note that if validOnly is set to _false_ when looking in the root certificates stores, the certificates are found

### PR DESCRIPTION
**Pull request by bartonjs**
The X509 finalization cleanup (#9510) went a little further than required.
For non-root certificates the cleanup logic was fine, but for a root certificate
the following erroneous logic happened:

* Build trusted certs list
* FindIssuer(cert)
  * This cert is self-signed, it has no candidate parents
  * (candidates.Count == 0)
* For every trusted cert which wasn't already known to be a candidate, Dispose it.
  * This disposed all of the trusted certs.
* Now ask "is the root cert of the chain in the trusted certs set?".
  * The answer is no, since everything was disposed.

The caller, which received the candidates list and the trusted certs list, was
already disposing the trusted certs, so there's no reason to do that in the
inner method.  That realization then lets the cleanup logic be simplified to no
longer have an indexing dependency.

The new test which has the same root cert in both the user and machine root
store showed that there was a "didn't get added to the HashSet"-induced
finalization, and that has been cleaned up (and guarded against). The new
Dispose logic has been proven resilient to the system trust list being populated
in a different order than the FindIssuer presentation list.

Fixes #10801.
cc: @stephentoub @iamjasonp

### CODE REVIEW

**Comment by stephentoub** [comment]
LGTM

**Comment by stephentoub** [comment]
Looks like the new test is failing on OSX:
```
System.Security.Cryptography.X509Certificates.Tests.FindTests.FindByValidThumbprint_RootCert [FAIL]
        Assert.Equal() Failure
        Expected: 1
        Actual:   0
        Stack Trace:
              at System.Security.Cryptography.X509Certificates.Tests.FindTests.FindByValidThumbprint_RootCert()
```

**Comment by bartonjs** [comment]
Weird.  It looks like it's passing on my Mac... I'm strongly wondering if Macs are having an off-by-one problem with the product assembly; the bad assert being my prime evidence.

**Comment by iamjasonp** [comment]
Code LGTM. FYI, I ran this code against what I was testing against and things are passing where they were failing before

**Comment by bartonjs** [comment]
@iamjasonp Cool.  Did it also fix your HttpClient problem? :smile:

**Comment by bartonjs** [comment]
Test Innerloop OSX Debug Build and Test please ("Works on my box")

**Comment by bartonjs** [comment]
I'm going to run a test with a bad commit that completely destroys certs on OSX; and I'll force rewind my branch before clearing "NO MERGE".  I'm really baffled here.

**Comment by iamjasonp** [comment]
> @iamjasonp Cool. Did it also fix your HttpClient problem? :smile:

For context - this is an issue I observed where: 

* On *nix boxes
* A custom root cert was installed into only the CurrentUser certificate store
* HttpClient was used to hit a https endpoint where the server cert is signed by the custom root cert 

The server certificate was rejected with a message stating that the server certificate was not valid and the connection would be closed 

@bartonjs - something funny is happening on my box after applying this change, so I haven't been able to verify it yet... perhaps we should make it into a test too? :smile: We don't test explicitly for this scenario in the WCF testbed (we directly install into the machine root store), but it happened to be found while tangentially looking at other scenarios

**Comment by bartonjs** [comment]
Okay, the new debuggability commit has been pretty illuminating.  There's an automatic certificate on mac machines (com.apple.systemdefault) which is in the root store on the CI Macs, but not on mine.  OpenSSL doesn't like this cert, it thinks it's not its own issuer, so it flags it as an incomplete chain.  I'm still looking into why (for my edification) and to think on how I want to react (ignore any cert whose name starts with "com.apple"?)

**Comment by jasonwilliams200OK** [comment]
@bartonjs, some people are suggesting a solution (among other) here: https://github.com/rust-lang/cargo/issues/1420 about removing `/etc/openssl/cert.pem`.

**Comment by bartonjs** [comment]
@jasonwilliams200OK Well, that file is the entirely of the LocalMachine\Root store on OSX, so just removing it is a bad idea :smile:.  Removing the bad entry is reasonable, but some tool put that there, and I want the tests to work for all users; not just users who didn't run whatever tool that was.

**Comment by bartonjs** [comment]
Aha.  Tools are better at seeing missing data than humans are.  Apple's certs have a Key Usage extension which specifies { Digital Signature, Key Encipherment, Data Encipherment } but NOT Certificate Signing; therefore OpenSSL rejects it as a CA.  So I can probably filter on having a valid root KU and not need to single out Apple.

**Comment by bartonjs** [comment]
Test Innerloop CentOS7.1 Release Build and Test please
Test Innerloop OSX Debug Build and Test please

**Comment by bartonjs** [comment]
@iamjasonp Yeah, it'd be good to have an OuterLoop test for the custom CA case (outerloop since it has to modify system state).  It's hard to do "right" due to lack of ability to create certs on the fly; but we can always start with "very long expiration" and do it right later.

Of course, it's a (potentially) different problem than this, so I don't want to add the test at the same time.

**Comment by iamjasonp** [comment]
Makes sense to deal with this later. 

FWIW, WCF does do a lot of cert gen sort-of-kind-of on the fly during testing, so we can definitely see if there's a way for us to leverage the expertise gained there to help test here

**Pull request merged**
