### PR TITLE
[release/3.1] Add directory creation method that takes an ACL

### PR DESCRIPTION
**Pull request by carlossanlop**
Ported change: https://github.com/dotnet/corefx/pull/41834
Approved API Proposal: https://github.com/dotnet/corefx/issues/41614

### Description

We have extension methods in `System.IO.FileSystem.AclExtensions` that let the user get and set ACLs for _existing_ directories, but we do not have methods that _create_ directories with predefined ACLs.
.NET ACL (Access Control List) support is Windows specific. This change will reside inside the `System.IO.FileSystem.AccessControl` assembly.

### Customer impact

Before this change, customers had to create a directory, then set the ACLs. This presents a few problems:

- Potential security hole as directories can be accessed between creation and modification.
- Porting difficulties as there isn't a 1-1 API replacement
- Stability issues with background processes (file filters) can prevent modifying ACLs right after creation (typically surfaces as a security exception).

This change addresses those problems by adding a new extension method that allows creating a directory and ensuring the provided ACLs are set during creation.

### Regression

This change will not cause a regression.

### Risk

Medium:

- Customers will only be able to test this change in 3.1 Preview 2, before it goes into GA.
- ACL changes are risky because if they are set incorrectly by our APIs, we cannot fix them via servicing, since the ACLs will already have been written to filesystems everywhere.

### Testing

Added unit tests that verify the ACLs were correctly set and the expected exceptions are thrown.

----

#### Notes

_Some merge conflicts in csproj files had to be addressed during the cherry-pick due to elements that do not exist in the 5.0 versions, specifically related to UWP._

### CODE REVIEW

**Comment by danmosemsft** [comment]
Approved to merge for 3.1 by 4pm today (after signoff and CI). thanks!

**Comment by carlossanlop** [comment]
@JeremyKuhne @danmosemsft the test failures seem to be happening because these tests are running on UWP and the platform is not supported. I'll update the test code to skip that platform.

**Comment by danmosemsft** [comment]
Hold on merging pending discussion with  Joc.

**Comment by carlossanlop** [comment]
> _Hold on merging pending discussion with Joc._

Yes, no problem, @danmosemsft . I'll wait for your approval. FYI, all checks passed.

**Pull request merged**
