### PR TITLE
Fix outerloop JsonWriter test by creating new instance of the writer when writing invalid JSON

### PR DESCRIPTION
**Pull request by ahsonkhan**
Fixes https://github.com/dotnet/corefx/issues/34616

### CODE REVIEW

**Comment by ahsonkhan** [comment]
@dotnet-bot test outerloop Linux x64 debug build
@dotnet-bot test outerloop OSX x64 debug build
@dotnet-bot test outerloop Windows x64 debug build

**Comment by ahsonkhan** [comment]
@dotnet-bot test outerloop Linux x64 debug build
@dotnet-bot test outerloop Windows x64 debug build

**Comment by ahsonkhan** [comment]
The following outerloop tests failures are unrelated.

OpenSuse.42.Amd64.Open-x64-Debug
https://mc.dot.net/#/user/ahsonkhan/pr~2Fjenkins~2Fdotnet~2Fcorefx~2Fmaster~2F/test~2Ffunctional~2Fcli~2F/bb8aca689a2895f2ec07f6418420ef8a4c4ff3f4/workItem/System.Runtime.Serialization.Formatters.Tests/analysis/xunit/System.Runtime.Serialization.Formatters.Tests.BinaryFormatterTests~2FValidateAgainstBlobs(obj:%20Bitmap%20%7B%20Flags%20=%2077840,%20FrameDimensionsList%20=%20%5B7462dc86-6180-4c7e-8e3f-ee7333a7a483%5D,%20Height%20=%20)

`System.Runtime.Serialization.Formatters.Tests.BinaryFormatterTests/ValidateAgainstBlobs(obj: Bitmap { Flags = 77840, FrameDimensionsList = [7462dc86-6180-4c7e-8e3f-ee7333a7a483], Height = )`

```text
Message :
Assert.Equal() Failure
Expected: 77840
Actual:   73744
Stack Trace :
   at System.Runtime.Serialization.Formatters.Tests.EqualityExtensions.IsEqual(Bitmap this, Bitmap other, Boolean isSamePlatform) in /mnt/j/workspace/dotnet_corefx/master/linux-TGroup_netcoreapp+CGroup_Debug+AGroup_x64+TestOuter_true_prtest/src/System.Runtime.Serialization.Formatters/tests/EqualityExtensions.cs:line 1233
```

cc @ViktorHofer 

Windows.10.Nano.Amd64.Open-x64-Debug
https://mc.dot.net/#/user/ahsonkhan/pr~2Fjenkins~2Fdotnet~2Fcorefx~2Fmaster~2F/test~2Ffunctional~2Fcli~2F/bb8aca689a2895f2ec07f6418420ef8a4c4ff3f4/workItem/System.Net.Http.Functional.Tests/analysis/xunit/System.Net.Http.Functional.Tests.SocketsHttpHandler_HttpClientHandler_Proxy_Test~2FAuthProxy__ValidCreds_ProxySendsRequestToServer(proxyAuthScheme:%20Digest,%20secureServer:%20False,%20proxyClosesConnectionAfterFirst407Response:%20True)

`System.Net.Http.Functional.Tests.SocketsHttpHandler_HttpClientHandler_Proxy_Test/AuthProxy__ValidCreds_ProxySendsRequestToServer(proxyAuthScheme: Digest, secureServer: False, proxyClosesConnectionAfterFirst407Response: True)`

```text
Message :
System.Net.Http.HttpRequestException : An error occurred while sending the request.
---- System.IO.IOException : Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host..
-------- System.Net.Sockets.SocketException : An existing connection was forcibly closed by the remote host.
Stack Trace :
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken) in D:\j\workspace\windows-TGrou---db113413\src\System.Net.Http\src\System\Net\Http\SocketsHttpHandler\HttpConnection.cs:line 707
   at System.Net.Http.AuthenticationHelper.SendWithNtAuthAsync(HttpRequestMessage request, Uri authUri, ICredentials credentials, Boolean isProxyAuth, HttpConnection connection, HttpConnectionPool connectionPool, CancellationToken cancellationToken) in D:\j\workspace\windows-TGrou---db113413\src\System.Net.Http\src\System\Net\Http\SocketsHttpHandler\AuthenticationHelper.NtAuth.cs:line 44
   at System.Net.Http.HttpConnectionPool.SendWithNtConnectionAuthAsync(HttpConnection connection, HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken) in D:\j\workspace\windows-TGrou---db113413\src\System.Net.Http\src\System\Net\Http\SocketsHttpHandler\HttpConnectionPool.cs:line 512
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken) in D:\j\workspace\windows-TGrou---db113413\src\System.Net.Http\src\System\Net\Http\SocketsHttpHandler\HttpConnectionPool.cs:line 483
   at System.Net.Http.AuthenticationHelper.SendWithAuthAsync(HttpRequestMessage request, Uri authUri, ICredentials credentials, Boolean preAuthenticate, Boolean isProxyAuth, Boolean doRequestAuth, HttpConnectionPool pool, CancellationToken cancellationToken) in D:\j\workspace\windows-TGrou---db113413\src\System.Net.Http\src\System\Net\Http\SocketsHttpHandler\AuthenticationHelper.cs:line 220
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken) in D:\j\workspace\windows-TGrou---db113413\src\System.Net.Http\src\System\Net\Http\SocketsHttpHandler\RedirectHandler.cs:line 33
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts) in D:\j\workspace\windows-TGrou---db113413\src\System.Net.Http\src\System\Net\Http\HttpClient.cs:line 475
   at System.Net.Http.Functional.Tests.HttpClientHandler_Proxy_Test.AuthProxy__ValidCreds_ProxySendsRequestToServer(AuthenticationSchemes proxyAuthScheme, Boolean secureServer, Boolean proxyClosesConnectionAfterFirst407Response) in D:\j\workspace\windows-TGrou---db113413\src\System.Net.Http\tests\FunctionalTests\HttpClientHandlerTest.Proxy.cs:line 95
--- End of stack trace from previous location where exception was thrown ---
----- Inner Stack Trace -----
   at System.Net.Http.HttpConnection.FillAsync() in D:\j\workspace\windows-TGrou---db113413\src\System.Net.Http\src\System\Net\Http\SocketsHttpHandler\HttpConnection.cs:line 1317
   at System.Net.Http.HttpConnection.ReadNextResponseHeaderLineAsync(Boolean foldedHeadersAllowed) in D:\j\workspace\windows-TGrou---db113413\src\System.Net.Http\src\System\Net\Http\SocketsHttpHandler\HttpConnection.cs:line 1269
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken) in D:\j\workspace\windows-TGrou---db113413\src\System.Net.Http\src\System\Net\Http\SocketsHttpHandler\HttpConnection.cs:line 513
----- Inner Stack Trace -----
```

Similar to https://github.com/dotnet/corefx/issues/32809

cc @wfurt, @geoffkizer

**Comment by ViktorHofer** [comment]
cc @safern for the Bitmap outerloop test failure.

**Comment by ahsonkhan** [comment]
The above two tests are failing consistently. Since they are unrelated to this PR, merging.

**Pull request merged**
