### PR TITLE
Use HTTPS for fetching NuGet.exe

### PR DESCRIPTION
**Pull request by ellismg**

### CODE REVIEW

**Comment by ellismg** [comment]
@mmitche Can you look into why the windows release build is failing?  It seems to be hitting some access denied error, and I've seen this across a few PRs now, so I don't think it's somethings specific to these changes.

**Comment by stephentoub** [comment]
LGTM.

**Comment by mmitche** [comment]
@ellismg Got it

**Comment by weshaggard** [comment]
@dotnet-bot test this please

**Comment by weshaggard** [comment]
LGTM

**Comment by weshaggard** [comment]
@ellismg can you fix this in our other repos CoreCLR/BuildTools/Roslyn.

**Comment by ellismg** [comment]
Will do.

**Pull request merged**
