### PR TITLE
Remove special EOF handling in SocketAsyncContext event loop

### LINKED ISSUE #5750: SendRecvAsync_Stream_TCP test failed on OS X
http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/osx_debug_tst/306/console
```
09:48:08 Unhandled Exception: Xunit.Sdk.EqualException: Assert.Equal() Failure
09:48:08 Expected: Success
09:48:08 Actual:   OperationAborted
09:48:08    at Xunit.Assert.Equal[T](T expected, T actual, IEqualityComparer`1 comparer)
09:48:08    at System.Net.Sockets.Tests.SocketAsyncExtensions.<>c__DisplayClass3_0.<ReceiveAsync>b__0(Object _, SocketAsyncEventArgs args)
09:48:08    at System.Net.Sockets.Tests.SocketAsyncExtensions.ReceiveAsync(Socket socket, SocketAsyncEventArgs eventArgs, IList`1 buffers, SocketFlags flags, Action`1 handler)
09:48:08    at System.Net.Sockets.Tests.SendReceive.<>c__DisplayClass4_3.<SendRecvAsync_Stream_TCP>b__2(Int32 received)
09:48:08    at System.Net.Sockets.Tests.SocketAsyncExtensions.<>c__DisplayClass3_0.<ReceiveAsync>b__0(Object _, SocketAsyncEventArgs args)
09:48:08    at System.Net.Sockets.SocketAsyncEventArgs.OnCompleted(SocketAsyncEventArgs e)
09:48:08    at System.Net.Sockets.SocketAsyncEventArgs.ExecutionCallback(Object state)
09:48:08    at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
09:48:08    at System.Net.Sockets.SocketAsyncEventArgs.FinishOperationSuccess(SocketError socketError, Int32 bytesTransferred, SocketFlags flags)
09:48:08    at System.Net.Sockets.SocketAsyncEventArgs.CompletionCallback(Int32 bytesTransferred, SocketError socketError)
09:48:08    at System.Net.Sockets.SocketAsyncEventArgs.TransferCompletionCallback(Int32 bytesTransferred, Byte[] socketAddress, Int32 socketAddressSize, SocketFlags receivedFlags, SocketError socketError)
09:48:08    at System.Net.Sockets.SocketAsyncContext.<>c.<ReceiveFromAsync>b__42_0(Object args)
09:48:08    at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
09:48:08    at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
09:48:08    at System.Threading.ThreadPoolWorkQueue.Dispatch()
```

### LINKED ISSUE #6506: SocketAsyncEngine event loop FailFast on OSX
http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/osx_debug_tst_prtest/1447/console
```
16:35:47 CLR: Managed code called FailFast, saying "Exception thrown from SocketAsyncEngine event loop: System.Diagnostics.Debug+DebugAssertException: 
16:35:47 
16:35:47    at System.Environment.GetStackTrace(Exception e, Boolean needFileInfo)
16:35:47    at System.Environment.get_StackTrace()
16:35:47    at System.Diagnostics.Debug.Assert(Boolean condition, String message, String detailMessage)
16:35:47    at System.Net.Sockets.SocketAsyncContext.UnregisterRead()
16:35:47    at System.Net.Sockets.SocketAsyncContext.HandleEvents(SocketEvents events)
16:35:47    at System.Net.Sockets.SocketAsyncEngine.EventLoop()
16:35:47    at System.Threading.Tasks.Task.Execute()
16:35:47    at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
16:35:47    at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
16:35:47    at System.Threading.Tasks.Task.ExecuteEntry(Boolean bPreventDoubleExecution)
16:35:47    at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
16:35:47    at System.Diagnostics.Debug.UnixDebugLogger.ShowAssertDialog(String stackTrace, String message, String detailMessage)
16:35:47    at System.Net.Sockets.SocketAsyncContext.UnregisterRead()
16:35:47    at System.Net.Sockets.SocketAsyncContext.HandleEvents(SocketEvents events)
16:35:47    at System.Net.Sockets.SocketAsyncEngine.EventLoop()"
16:35:47 ./run-test.sh: line 135: 55204 Abort trap: 6           ./corerun xunit.console.netcore.exe $testDllName -xml testResults.xml -notrait category=failing -notrait category=OuterLoop -notrait category=$xunitOSCategory -notrait Benchmark=true
16:35:47 error: One or more tests failed while running tests from 'System.Net.Sockets.Tests'.  Exit code 134.
```
cc: @ericeil, @pgavlin

### PR DESCRIPTION
**Pull request by ericeil**
This code makes the assumption that if the other end of a socket is closed, all reads that will ever be issued on this end are already pending, so it's ok to shut down the read queue.  This is not necessarily true; we need to allow other threads to continue to issue reads until they've actually read all data.

This is resulting in assert failures (#6506) and is a likely cause of erroneous OperationAborted failures (#5750).

It's not clear to me what value the EOF handling is providing currently; currently, aside from erroneously shutting down the queue, the only difference from the normal read event logic is that we also unregister from read events.  Since we no longer are able to free handles, etc., on unregistration, it's not clear that we get any benefit from unregistering an event we'll probably never receive again.

This change therefore simply removes this logic.  

Fixes #6506.
Fixes #5750.

@stephentoub @pgavlin

### CODE REVIEW

**Comment by ericeil** [comment]
@dotnet-bot test Innerloop OSX Debug Build and Test please
test Innerloop OSX Release Build and Test please
test Innerloop Ubuntu Debug Build and Test please
test Innerloop Ubuntu Release Build and Test please

**Comment by stephentoub** [comment]
> test 

@ericeil, what were the failures?  Most of the failures I've seen of late in such legs are the exact two issues this PR is supposed to fix :)

**Comment by ericeil** [comment]
@stephentoub the build machines went offline during the build, apparently.

**Comment by stephentoub** [comment]
> the build machines went offline during the build, apparently.

Excellent.  I mean, not excellent... but excellent. :)

**Comment by stephentoub** [comment]
If we don't unregister here, are we leaking anything?

**Comment by ericeil** [comment]
> If we don't unregister here, are we leaking anything?

No, the socket will be fully unregistered from the event port when the file descriptor is closed.  All this "unregister" does is switch a bit in the native registration to indicate that we're no longer interested in "read" events.

**Comment by stephentoub** [comment]
Ok.  LGTM, then.  And I'll close my other PR to disable the tests that this is hopefully fixing.

**Comment by ericeil** [comment]
> And I'll close my other PR to disable the tests that this is hopefully fixing.

Thanks!  I didn't see that PR for some reason...

**Pull request merged**
