### PR TITLE
Fixing perf linux tests and revving xunit perf versions

### PR DESCRIPTION
**Pull request by dsgouda**
Enabling local perf test runs on linux
Revving xunit performance packages to 0035
Fixing linux perf test runs

@MattGal @lt72

### CODE REVIEW

**Comment by dsgouda** [comment]
@dotnet-bot Test this please

**Comment by dsgouda** [comment]
@dotnet-bot Test Innerloop Ubuntu14.04 Debug Build and Test please

**Comment by dsgouda** [comment]
@dotnet-bot Test Ubuntu14.04 Release Build and Test please

**Comment by dsgouda** [comment]
@dotnet-bot Test Innerloop Windows_NT Debug Build and Test please

**Comment by dsgouda** [comment]
@dotnet-bot Test  Innerloop Ubuntu14.04 Debug Build and Test please

**Comment by MattGal** [comment]
LGTM

**Pull request merged**
