### PR TITLE
Resolve build folder of managed corefx on Ubuntu 14.04 in  release mode.

### PR DESCRIPTION
**Pull request by leemgs**
This patch resolves the build folder of managed corefx for release mode 
on Ubuntu 14.04 64bit pc and Windows 7 pc

### CODE REVIEW

**Comment by stephentoub** [comment]
Thanks, @leemgs.  Did you mean to include c201972?  Looks like that's the same commit from PR #6585, so I assume the only commit meant for this PR is df390b1.

**Comment by stephentoub** [comment]
Commit df390b1 LGTM.

cc: @ellismg, @mellinoe, @joperezr

**Comment by leemgs** [comment]
> so I assume the only commit meant for this PR is df390b1.
Right.

**Comment by mellinoe** [comment]
> Commit df390b1 LGTM.

Yes, this looks good to me as well.

**Pull request merged**
