### PR TITLE
Script to retry a given command

### PR DESCRIPTION
**Pull request by ravimeda**
Introducing a script that will retry a given command. Script will retry the command until the command runs successfully or the specified number of retries are exhausted.

This script will be useful in a build step that involves network operations such as `git clone`, which might run into intermittent issues. Refer https://github.com/dotnet/core-eng/issues/1438

Plan is to commit directly to servicing branches. Same script will also be made available in newer versions of BuildTools (tracked through https://github.com/dotnet/buildtools/issues/1640) so that all `master` or any future branches can upgrade to.

### CODE REVIEW

**Comment by ravimeda** [comment]
Cc @weshaggard @dagood 

As you may have noticed these scripts are inspired from https://github.com/dotnet/buildtools/blob/master/src/Microsoft.DotNet.Build.Tasks/PackageFiles/scripts/docker/init-docker.sh

A limitation is if the command is a file and has spaces, for example, "_/User/ravi/scripts/**my test folder**/tests.sh_", then the script thinks "_/User/ravi/scripts/my_" is the command to run. So, spaces cannot be handled.

**Comment by dagood** [comment]
> This script will be useful in a build step that involves network operations such as `git clone`

With this script in CoreFX, wouldn't you need to clone first to get access to it? Or are we assuming that the "outer" git clone will be successful, and we're only using this for the "inner" clone? Even then, we could restore BuildTools for the "outer" clone and get this script from there. I'm not sure this belongs in CoreFX.

**Comment by ravimeda** [comment]
Yes, the first attempt to get the sources should succeed. Subsequent commands can benefit from the this retry command. For example, in (https://devdiv.visualstudio.com/DefaultCollection/DevDiv/_apps/hub/ms.vss-ciworkflow.build-ci-hub?_a=edit-build-definition&id=4323), `Run Git` steps will bring the latest CoreFx 1.0.0 sources. Subsequent step such as `Clone repository` can use the retry script.

If I understand correctly, you are suggesting, the first task will be to clone BuildTools, which will bring the retry script, and then get CoreFx sources with the retry. I think that sounds fine.

**Comment by dagood** [comment]
I suppose switching to cloning BuildTools or actually running init-tools in the outer repo to get the package is fairly disruptive.

From that link, though, I see that the definition is already set to clone DotNet-BuildPipeline master as the outer repo. These scripts can go there, instead, and there are actually already some other scripts in there as precedent.

**Comment by ravimeda** [comment]
Yes, putting this script in BuildPipeline is acceptable to me.

**Comment by weshaggard** [comment]
I agree with @dagood that these should go into some outer repo and not in all the inner repo's. Going into the BuildPipeline repo is good for now but we may need to move them when we start doing orchestration differently.

**Pull request closed without merging**
