### PR TITLE
Add debian.8-armel and tizen.4.0.0-armel into nupkg

### PR DESCRIPTION
**Pull request by chunseoklee**
Signed-off-by: chunseoklee <chunseok.lee@samsung.com>

### CODE REVIEW

**Comment by chunseoklee** [comment]
should be merged after armel naming issue is resolved( https://github.com/dotnet/coreclr/issues/8770
)

**Comment by hseok-oh** [comment]
@mellinoe `armel` naming issue is resolved. PTAL

**Comment by chunseoklee** [comment]
tizen.4.0.0-armel nupkg added

**Comment by mellinoe** [comment]
@dotnet-bot Test Innerloop Windows_NT Debug Build and Test

**Comment by mellinoe** [comment]
The changes look good to me now. Just to make sure, this is the finalized naming we've decided on @chunseoklee ?

**Comment by chunseoklee** [comment]
Yes. This PR seems OK to be merged.

**Comment by mellinoe** [comment]
@chunseoklee Thanks!

**Pull request merged**
