### PR TITLE
Fixing the logic in SystemNative_GetTimestampResolution to return the correct "ticks per second"

### PR DESCRIPTION
**Pull request by tannergooding**
This should resolve https://github.com/dotnet/corefx/issues/37231. CC. @MichalStrehovsky, @jkotas

### CODE REVIEW

**Comment by stephentoub** [comment]
Can we add a corefx test that validates within some window?

**Comment by tannergooding** [comment]
> Can we add a test that validates within some window?

What kind of window are you imagining? I think this will be very hard to test overall since it can be machine/OS/Architecture dependent. The only consistent thing is it shouldn't be zero or negative.

**Comment by stephentoub** [comment]
> What kind of window are you imagining?

Time sleeping for a second, and if it's more than two seconds, repeat again, up to, say, twenty times. If all twentyone-second sleeps took more than two seconds, fail the test. The most common error here will result in being off by a factor of 10 or more.

**Comment by danmosemsft** [comment]
Do we have an independent source of time ie the system clock? You could do two attempts, to be proof against leap seconds and DST.

**Comment by tannergooding** [comment]
I don't doubt we could get something working. My concern is that we would be adding yet another source of flakiness to the CI jobs.

**Comment by stephentoub** [comment]
> My concern is that we would be adding yet another source of flakiness to the CI jobs.

I'm suggesting you could choose the number of retries to be large enough such that it would effectively never fail due to flakiness.

**Comment by tannergooding** [comment]
> I'm suggesting you could choose the number of retries to be large enough

Then you have another problem, which is adding a test which takes a significant portion of time to run and which could be broken by debugging, system pauses, the GC, or any other number of scenarios.

**Comment by stephentoub** [comment]
> Then you have another problem, which is adding a test which takes a significant portion of time to run

Only if it's failing, which should be exceedingly rare.  It can also be outerloop if there's a strong concern about the time it takes.

**Comment by stephentoub** [comment]
> which could be broken by debugging, system pauses, the GC, or any other number of scenarios

On every of X retries where X is sufficiently large?

**Comment by tannergooding** [comment]
> On every of X retries where X is sufficiently large?

What are we going to define as sufficiently large and will it continue to work for things like IOT, x86 on ARM, or Mobile (including laptop) scenarios (all of which are things that people may be building and testing CoreFX against)?

Most of the other timing functionality (such as `Thread.Sleep`), which we would need to depend on in the test is dependent on the resolution of the system timer. On Windows 7 and above, this defaults to ~16ms but is configurable by both the application and end user. Linux and MacOS have similar functionality, to my knowledge.

So, we need to ultimately detect the system timer resolution (which is different from the hardware timer resolution), and then sleep for some multiple of that (and also use it for part of the tolerance level). Then we need to validate that the time we tracked is within some tolerance of the time we expected and repeat for 'x' times to try and weed out flaky results.

I'm not saying it's impossible nor that it isn't worthwhile. But I really wouldn't be in favor of adding a test that may cause CI or local build failures. Perhaps doing some explicit manual validation would be a better option?

**Comment by stephentoub** [comment]
I think you're making it more complicated than it needs to be.

**Pull request merged**
