### PR TITLE
Porting OleDb transaction API failure fix

### PR DESCRIPTION
**Pull request by saurabh500**
#### Description

Port the changes from PR https://github.com/dotnet/runtime/pull/32573
The changes address https://github.com/dotnet/runtime/issues/31177 and https://github.com/dotnet/runtime/issues/32405

The problem manifests in the usage of OleDbTransaction throwing exceptions in System.Data.OleDb. This is caused because a duplicate interface but with incorrect Guid for ITransaction.
The fix removes the duplicate interface and also releases the COM objects once they have been used.

#### Customer Impact

The customers will be able to use OleDbTransaction.Commit() and OleDbTransaction.RollBack(), successfully. These APIs are important to perform actions on OleDb providers with transaction support.
Also OleDbConnection.Dispose() would call OleDbTransaction.Rollback(), which used to fail silently underneath. These above issues would be addressed for customer.

#### Regression?

This is not a regression, and the bug had existed since the beginning. 

#### Risk

No risks identified.

#### Packaging changes reviewed? (if a libraries change) 

Package changes added after getting guidance from @anipik

### CODE REVIEW

**Review by Anipik — APPROVED** [review]
Packaging changes looks good. Still needs an approval from tactics and area owner

**Review by jkotas — APPROVED** [review]

**Comment by jamshedd** [comment]
Approved for 3.1.4.

**Comment by saurabh500** [comment]
@jamshedd @danmosemsft @Anipik 
From what I understood from the one note, I don't have to merge the PR, but I am not sure if that applies to non repo members or to members as well? If the CI is green, should I squash and merge this or wait for the next train and the DRI to merge this ?

**Comment by danmoseley** [comment]
@Anipik will merge. your work here is done hopefully 😄

**Pull request merged**
