### PR TITLE
Solve the question of whether ToString should return string or string?.

### PR DESCRIPTION
**Pull request by isaacabraham**
I've given this a great deal of thought and after painstaking analysis have come up with this solution to whether ToString should return a string or a nullable string.

I've done the main grunt work here and leave the rest of the implementation as an exercise to the reader.

Good luck and have fun.

### CODE REVIEW

**Comment by terrajobst** [comment]
I see what you did there 😄

In all seriousness, we’re interested in customer feedback after we shipped the first version of annotations. Right now, we’re all arguing in abstract.

Needless to say I’ve closed this because it’s an API breaking change, but you knew that 😇

**Comment by terrajobst** [comment]
Looks like @stephentoub raced me for the close. 😊

**Comment by isaacabraham** [comment]
Oh well. I tried.

**Comment by terrajobst** [comment]
The real reason I rejected was because you already your famous two-line PR ;-)

**Comment by isaacabraham** [comment]
Yeah. This was three lines!

**Pull request closed without merging**
