### PR TITLE
Merge of bigendian branch

### PR DESCRIPTION
**Pull request by marek-safar**
Don't review/merge I am using this for testing only but have no rights to set labels

### CODE REVIEW

**Comment by jkotas** [comment]
@marek-safar I have fixed the test failures ... sorry for the hassle.

**Comment by jkotas** [comment]
GetAllocatedBytesForCurrentThread test failure - https://github.com/dotnet/corefx/issues/16606

**Comment by jkotas** [comment]
@dotnet-bot test Innerloop Windows_NT Debug Build and Test  please

**Comment by stephentoub** [comment]
@marek-safar, what's the status of this PR? Thanks.

**Comment by marek-safar** [comment]
@stephentoub I'd like to see these changes to be merged at some point

**Comment by jkotas** [comment]
@tmat What kind of performance testing you would like to do on this before it can be merged?

**Comment by tmat** [comment]
/cc @TyOverby @VSadov @jaredpar 

I think it would be easiest to optimistically merge the SRM change and then create a PR in Roslyn repo that picks up a new SRM build. Then we can run Roslyn perf tests and measure PDB conversion time as well, which is metadata reading intensive.

**Comment by jkotas** [comment]
@dotnet-bot test this please

**Comment by nealef** [comment]
Has this made it into the binaries yet?

**Pull request merged**
