### PR TITLE
Add Xamarin platform placeholder in S.T.Tasks.Extensions package

### LINKED ISSUE #29585: System.Threading.Tasks.Extensions package needs _._ placeholders for Xamarin platforms
We're adding a facade for System.Threading.Tasks.Extensions.dll inbox so we'd like to add the placeholders for the usual Xamarin platforms to the package.

/cc @weshaggard

### PR DESCRIPTION
**Pull request by tarekgh**
Fixes #29585

### CODE REVIEW

**Comment by tarekgh** [comment]
CC @akoeplinger

**Comment by tarekgh** [comment]
The failure in Windows x64 Debug Build is unrelated and tracked by the issue https://github.com/dotnet/corefx/issues/29757

**Comment by joperezr** [comment]
This seems like a low-impact change, should we consider servicing it on 2.1.1? @danmosemsft

**Comment by danmosemsft** [comment]
Is this issue unique to this package? Sure feel free to leave issue ooen put in 2.1.x and mark with consider label

**Comment by tarekgh** [comment]
#29828 is regarding System.Buffer. So, I think we need to get the list of all packages need to have the placeholder and fix all of them for 2.1. 

I'll add the information to #29828 to include System.Threading.Tasks.Extensions and will mark that issue as 2.1. so if there is more packages need to be fixed same way can included in this issue.

**Comment by marek-safar** [comment]
This one is hitting customers already so you could get it out as soon as you can. The other issues are different because we need to coordinate on releasing not to break customers with previous Xamarin versions.

**Comment by joperezr** [comment]
@marek-safar this one I believe is going to be addressed on 2.1 servicing, so that means that 2.1 would be released with a package without the place holders. If you think that we should definitely address this on 2.1, please chime in on the issue #29585

**Pull request merged**
