### PR TITLE
[dev/eng] Merge branch master to dev/eng

### PR DESCRIPTION
**Pull request by joperezr**
One more round of this in order to pave the road for tomorrow's RI.

cc: @weshaggard @ericstj @chcosta @mellinoe @karajas

### CODE REVIEW

**Comment by joperezr** [comment]
Changes worth taking a look at: a9dd06b and d5ca751

**Comment by mellinoe** [comment]
I think we are pulling in a change to use a newer version of the CLI. It now has a 1.1.0 shared framework in it, so we need to update that version in @karajas 's new test targets for constructing the "test shared framework" we are using.

**Comment by joperezr** [comment]
>I think we are pulling in a change to use a newer version of the CLI.


@mellinoe yeah, on the dev/eng I grabbed as base we didn't have the dotnet host change yet, I've rebased and added cd09ed3 that should address this.

> Just noting that we still need to fix the auto-update thing for the project.json.template file

Yup, that is one of the things we will have to fix on the weekend.

**Comment by mellinoe** [comment]
> cd09ed3 that should address this.

👍

**Comment by weshaggard** [comment]
>Just noting that we still need to fix the auto-update thing for the project.json.template file. It might already be out of sync with tis value.

I filed https://github.com/dotnet/corefx/issues/15140

**Comment by weshaggard** [comment]
The changes I scanned through look reasonable. Looks like we still have some issues in CI to work through though.

**Comment by joperezr** [comment]
> The changes I scanned through look reasonable. Looks like we still have some issues in CI to work through though.

I spent some time with @ericstj trying to figure out the non-Windows CI issue, and the problem seems to be something with assembly loading in the new cli. The host can't seem to load CoreFx.Tools.dll that just got produced because it thinks it's not there, even though we have made sure to check if the file is present. Looks like @chcosta had faced this in the past already on official builds.

As a workaround, I was planning to temporarily modify build.sh script to call `msbuild.sh CoreFx.Tools.csproj` before running `build-managed.sh`. I've verified that these approach works, but it is a hack, so I wanted to know if that is ok with you.

**Comment by weshaggard** [comment]
>As a workaround, I was planning to temporarily modify build.sh script to call msbuild.sh CoreFx.Tools.csproj before running build-managed.sh. I've verified that these approach works, but it is a hack, so I wanted to know if that is ok with you.

I'm OK with it. Just be sure we file an issue to clean it up when we move the corefx tools to build tools.

**Comment by joperezr** [comment]
>Just be sure we file an issue to clean it up when we move the corefx tools to build tools

will do.

**Pull request merged**
