### PR TITLE
Display the contents of init-tools.log 

### PR DESCRIPTION
**Pull request by karajas**
Port of https://github.com/dotnet/corefx/pull/21894 to release/1.0.0

/cc @ravimeda

### CODE REVIEW

**Comment by ravimeda** [comment]
Thanks Karthik.

**Comment by karajas** [comment]
@dotnet-bot test Innerloop Windows_NT Debug Build and Test please

**Comment by karelz** [comment]
@karajas can you please change title to describe the change? Current text is not very useful and won't be as title in git history. Thanks!

**Comment by karajas** [comment]
Updated the name of the PR.

**Pull request merged**
