### PR TITLE
Update to latest preview6 SDK

### LINKED ISSUE #37907: Unable to build on Ubuntu 18.04
I'm struggling to build on Ubuntu 18.04 recently. Things get going for a few minutes and then:

<details>
<summary>MSBUILD : error MSB1025: An internal failure occurred while running MSBuild.</summary>
<pre>
System.ArgumentNullException: Value cannot be null.
Parameter name: array
   at Microsoft.Build.Execution.BuildManager.EndBuild()
   at Microsoft.Build.CommandLine.MSBuildApp.BuildProject(String projectFile, String[] targets, String toolsVersion, Dictionary`2 globalProperties, Dictionary`2 restoreProperties, ILogger[] loggers, LoggerVerbosity verbosity, DistributedLoggerRecord[] distributedLoggerRecords, Int32 cpuCount, Boolean enableNodeReuse, TextWriter preprocessWriter, Boolean detailedSummary, ISet`1 warningsAsErrors, ISet`1 warningsAsMessages, Boolean enableRestore, ProfilerLogger profilerLogger, Boolean enableProfiler, Boolean interactive, Boolean isolateProjects, Boolean graphBuild, String[] inputResultsCaches, String outputResultsCache)
</pre>
</details>

I'm not sure if this is related to #37868 or not, but on the surface it seems like two different issues.

This error always occurs after this in the build log:

```
Verifying closure of runtime.linux-x64.Microsoft.Private.CoreFx.NETCoreApp runtime assemblies
Verifying no duplicate types in runtime.linux-x64.Microsoft.Private.CoreFx.NETCoreApp runtime assemblies
Microsoft.Private.CoreFx.NETCoreApp -> /code/personal/corefx/artifacts/packages/Debug/specs/runtime.linux-x64.Microsoft.Private.CoreFx.NETCoreApp.nuspec
runtime.native.System.IO.Ports -> /code/personal/corefx/artifacts/packages/Debug/specs/runtime.native.System.IO.Ports.nuspec
runtime.native.System.IO.Ports -> /code/personal/corefx/artifacts/packages/Debug/specs/runtime.linux-x64.runtime.native.System.IO.Ports.nuspec
💥
```

### PR DESCRIPTION
**Pull request by ericstj**
Fixes #37907

Trying out the latest SDK.  I don't have a full read on this version yet.  We'll probably want to update again when we get a coherent SDK build.

### CODE REVIEW

**Comment by ViktorHofer** [comment]
@ericstj generally lgtm but there are some failures. Not sure if something changed in the SDK again.

**Comment by ericstj** [comment]
So I saw an Internal CLR Error 0x80131506 (ExecutionEngineException, I believe) on first run and it went away on rerun.  This could mean GC heap corruption.  Given we would want to fix that and would need repro I’m inclined to merge this anyway.  Anyone tracking a recent fix for something that would cause this? @tommcdon?

**Comment by ViktorHofer** [comment]
I would like to do validate with another CI run, just to make sure.

**Comment by tommcdon** [comment]
> So I saw an Internal CLR Error 0x80131506 (ExecutionEngineException, I believe) on first run...Anyone tracking a recent fix for something that would cause this? @tommcdon?

We recently fixed a race condition in release/3.0 with event pipe, but to reproduce the issue you need to have event pipe enabled.

**Comment by ericstj** [comment]
Ok, taking this for now.  We'll dig in if we start seeing more build failures after picking this up.

**Pull request merged**
