### PR TITLE
Fix ConnectionTimeoutTestWithThread test

### PR DESCRIPTION
**Pull request by geleems**
This fix is for https://github.com/dotnet/corefx/issues/26382
The test failed on Win10 and Win8.1 in CI jobs due to improper threshold value.
This change fixes the issue.

### CODE REVIEW

**Comment by geleems** [comment]
@dotnet-bot test OSX x64 Debug Build please
@dotnet-bot  test Windows x64 Debug Build please
@dotnet-bot  test Windows x86 Release Build please

**Comment by saurabh500** [comment]
How does the change fix the issue? How did you decide that this is the right threshold?

**Comment by geleems** [comment]
@saurabh500 
I changed the threshold set to 2 times bigger than proposed timeout value.
threshold = timeout * numOfTry * 2 * 1000
In the test code, 5 threads try open connection 2 times serially with timeout 5 sec option.
In this case, threshold is 5 * 2 * 2 * 1000 = 20000

**Comment by geleems** [comment]
@dotnet-bot  test Linux x64 Release Build please
@dotnet-bot  test Windows x64 Debug Build please
@dotnet-bot  test Windows x86 Release Build please
@dotnet-bot  test OSX x64 Debug Build please

**Pull request merged**
