### PR TITLE
Disable span test failing due to OOM Exception

### PR DESCRIPTION
**Pull request by ahsonkhan**
Related to issue #16593

### CODE REVIEW

**Comment by ahsonkhan** [comment]
Why do these tests start as failing?
Innerloop OSX Debug x64 Build and Test
Innerloop OSX Release x64 Build and Test

I can't even get them to run.

**Comment by bartonjs** [comment]
@dotnet-bot Test Innerloop OSX10.12 Debug x64 Build and Test please
@dotnet-bot Test Innerloop OSX10.12 Release x64 Build and Test please

**Comment by bartonjs** [comment]
@mmitche OSX10.11 tests still triggered.  Is there a delay before it switches master to 10.12 only?

**Comment by mmitche** [comment]
@bartonjs It's just going to launch both right now, since the checked in definitions are the old ones.  Just ignore them until the merge.

**Comment by mmitche** [comment]
@bartonjs Sorry didn't realize the main PR got merged.  Yes there is a 15 min delay.

**Comment by stephentoub** [comment]
@dotnet-bot Test Innerloop OSX10.12 Debug x64 Build and Test please
@dotnet-bot Test Innerloop OSX10.12 Release x64 Build and Test please

**Pull request merged**
