### PR TITLE
Update testdata versions

### PR DESCRIPTION
**Pull request by ViktorHofer**
We uploaded new versions of all the test data packages to reset the versioning schema. The new package versions don't contain any changes except System.Drawing.Common.TestData (cc @Anipik)

### CODE REVIEW

**Comment by ViktorHofer** [comment]
Yes I requested a review too early. Still working on the remaining places to change.

**Comment by safern** [comment]
The Crypto tests are failing, maybe related to the line endings?

**Comment by ViktorHofer** [comment]
No, the packages are fine - I validated them when I uploaded them earlier today. I had a typo in one of the SupplementalTestData items.

**Comment by safern** [comment]
LOL, that was definitely hard to spot :smile:

**Pull request merged**
