### PR TITLE
Increase Enum Test Coverage

### PR DESCRIPTION
**Pull request by benaadams**
Covers negative enums for various sizes

/cc @jkotas

### CODE REVIEW

**Comment by benaadams** [comment]
Needs some more cases

**Comment by jasonwilliams200OK** [comment]
@benaadams, I can't see the negative number case, is it still missing from the PR? :smile:

**Comment by benaadams** [comment]
@jasonwilliams200OK `Int32Enum.Min` though there are two other code paths that need adding

**Comment by jkotas** [comment]
👍

**Comment by benaadams** [comment]
@jkotas think I've covered the scenarios, I haven't done anything for double, float or char as VS doesn't like them.

**Comment by jkotas** [comment]
Thanks!

**Pull request merged**
