### PR TITLE
Notify GC of allocated native memory

### PR DESCRIPTION
**Pull request by tmat**

### CODE REVIEW

**Comment by tmat** [comment]
@nguerrera @stephentoub @Maoni0 Is it desirable to call GC.AddMemoryPressure when using Marshal.AllocHGlobal?

**Comment by stephentoub** [comment]
@Maoni0, do you have an opinion on this?

**Comment by stephentoub** [comment]
@dotnet-bot test this please

**Comment by Maoni0** [comment]
oops, sorry I totally missed this. 

@tmat have you tested this with the VS scenario? if so what was the result?

**Comment by tmat** [comment]
It hasn't been tested with the scenario yet afaik. This is a general purpose library though, so the question is whether or not the calls should be in such a library or whether we should rather move it to the specific host.

**Comment by Maoni0** [comment]
I am leery of adding this in library. It might cause problems as it might be triggering too many GCs. the implementation of A/RMP is fairly simplistic and I tend to tell people to use it on a higher level (more end user code than library code). I've seen it causing problems in library code before where particular usages can trigger too many GCs.

**Comment by tmat** [comment]
OK. Sounds like this is not the right fix then. Let's see if we can address the issue higher in the stack.

**Pull request closed without merging**
