### PR TITLE
Assume that NetBSD ships with case-sensitive filesystem

### PR DESCRIPTION
**Pull request by krytarowski**

### CODE REVIEW

**Comment by krytarowski** [comment]
@stephentoub PTAL

**Comment by stephentoub** [comment]
It looks fine, but should these just be part of your commit in the other PR?

**Comment by krytarowski** [comment]
Yes, these PR are similar. Thanks for reviewing.

My PRs reflect my current understanding of the project, at that time I wasn't aware of this code in this PR.

**Comment by krytarowski** [comment]
(note that this there is no FreeBSD support)

**Comment by stephentoub** [comment]
> My PRs reflect my current understanding of the project, at that time I wasn't aware of this code in this PR.

Ok, going forward, please try to avoid submitting PRs like this.  It gets confusing.  For a change like this, I'd prefer it if you'd just bunch all of them up into a single commit that gets submitted when you've gone through all of the relevant tests fixing the same problem.

**Comment by stephentoub** [comment]
> (note that this there is no FreeBSD support)

If you expect such a change to be needed for FreeBSD, why not add it now as well as long as you're added these values for NetBSD?

**Comment by krytarowski** [comment]
> If you expect such a change to be needed for FreeBSD, why not add it now as well as long as you're added these values for NetBSD?

I can do it on demand but I won't test FreeBSD.

**Comment by krytarowski** [comment]
> Ok, going forward, please try to avoid submitting PRs like this.

I will try my best. Thanks!

**Comment by stephentoub** [comment]
> I can do it on demand but I won't test FreeBSD.

Rather than have to update a bunch of tests like this each time someone wants to bring up a new platform, I'm centralizing these checks into one place:
https://github.com/dotnet/corefx/pull/6660

**Pull request closed without merging**
