### PR TITLE
Add nuget/myget version badges to library components

### PR DESCRIPTION
**Pull request by stephentoub**
Experimenting with including badges for each library, highlighting the latest published dev version of the component and providing a link to where it can be downloaded.

"View" the README.md as rendered markdown to see all of the badges, courtesy of shields.io.  The majority of these are from the dotnet-core myget gallery; when components weren't available there, they were usually on NuGet.  The remaining few that show up as "invalid" don't yet have a published package, but as soon as they're published to myget, these badges will be updated automatically.

### CODE REVIEW

**Comment by stephentoub** [comment]
@richlander, @jhendrixMSFT, @ericstj, thoughts?

**Comment by mellinoe** [comment]
I like it. I think it reads better/easier than our current mass of bullet points, and the package badge things are pretty nifty as well.

**Comment by Petermarcu** [comment]
I like it. Not sure why the build failed with this.

**Comment by stephentoub** [comment]
Thanks, guys.

> Not sure why the build failed with this.

All Windows builds in CI appear to be failing due to #1685.

**Comment by weshaggard** [comment]
I like the badges as well bug I'm curious about the links. Perhaps an orthogonal question but when are our builds going to point to the dotnet-core myget feed like you are linking from the badges. This is likely a question for @jhendrixMSFT.

**Comment by stephentoub** [comment]
> but I'm curious about the links

I couldn't find any way to get a link to the latest version without hardcoding it into the link. If there is a way, we should change the links to use it.

**Comment by jhendrixMSFT** [comment]
CoreFx builds are now pulling from the dotnet-core repro, see https://github.com/dotnet/corefx/commit/08c0d8628ef621fbd44d7aaa85b3239616a6b108.

**Pull request merged**
