### PR TITLE
Fixing NegotiateStream Windows Interop. Adding NTLM and Kerberos remote tests.

### LINKED ISSUE #9160: NegotiateStream AuthenticateAsClientAsync does not work for non default credential
NegotiateStream AuthenticateAsClientAsync works for default credential, but not non default credential.

I have a repro app similar to the sample in https://msdn.microsoft.com/en-us/library/system.net.security.negotiatestream(v=vs.110).aspx

The repro app is passing in desktop, but failing in .net core. I have observed that the client has got a NTLM credential instead of kerberos and failed to log on to the server.

[Repro.zip](https://github.com/dotnet/corefx/files/299179/Repro.zip)

with below exception from client.
>	System.Net.Security.dll!System.Net.Security.NegoState.ThrowCredentialException(long error) Line 842	C#
 	System.Net.Security.dll!System.Net.Security.NegoState.ProcessReceivedBlob(byte[] message, System.Net.LazyAsyncResult lazyResult) Line 608	C#
 	System.Net.Security.dll!System.Net.Security.NegoState.ReadCallback(System.IAsyncResult transportResult) Line 758	C#
 	System.Net.Security.dll!System.Net.LazyAsyncResult.Complete(System.IntPtr userToken) Line 481	C#
 	System.Net.Security.dll!System.Net.LazyAsyncResult.ProtectedInvokeCallback(object result, System.IntPtr userToken) Line 431	C#
 	System.Net.Security.dll!System.Net.StreamFramer.ReadFrameComplete(System.IAsyncResult transportResult) Line 292	C#
 	System.Net.Security.dll!System.Net.StreamFramer.ReadFrameCallback(System.IAsyncResult transportResult) Line 171	C#
 	System.Net.Security.dll!System.Threading.Tasks.TaskToApm.InvokeCallbackWhenTaskCompletes.AnonymousMethod__0() Line 137	C#
 	System.Private.CoreLib.ni.dll!System.Runtime.CompilerServices.TaskAwaiter.OutputWaitEtwEvents.AnonymousMethod__0()	Unknown
 	System.Private.CoreLib.ni.dll!System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, object state)	Unknown
 	System.Private.CoreLib.ni.dll!System.Threading.Tasks.AwaitTaskContinuation.RunCallback(System.Threading.ContextCallback callback, object state, ref System.Threading.Tasks.Task currentTask)	Unknown
 	System.Private.CoreLib.ni.dll!System.Threading.Tasks.Task.FinishContinuations()	Unknown
 	System.Private.CoreLib.ni.dll!System.Threading.Tasks.Task<int>.TrySetResult(int result)	Unknown
 	System.Private.CoreLib.ni.dll!System.Threading.Tasks.TaskFactory<int>.FromAsyncCoreLogic(System.IAsyncResult iar, System.Func<System.IAsyncResult, int> endFunction, System.Action<System.IAsyncResult> endAction, System.Threading.Tasks.Task<int> promise, bool requiresSynchronization)	Unknown
 	System.Private.CoreLib.ni.dll!System.Threading.Tasks.TaskFactory<int>.FromAsyncImpl.AnonymousMethod__1(System.IAsyncResult iar)	Unknown
 	System.Net.Sockets.dll!System.Net.LazyAsyncResult.Complete(System.IntPtr userToken) Line 481	C#
 	System.Net.Sockets.dll!System.Net.ContextAwareResult.CompleteCallback() Line 461	C#
 	System.Net.Sockets.dll!System.Net.ContextAwareResult.Complete.AnonymousMethod__15_0(object s) Line 450	C#
 	System.Private.CoreLib.ni.dll!System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, object state)	Unknown
 	System.Net.Sockets.dll!System.Net.ContextAwareResult.Complete(System.IntPtr userToken) Line 451	C#
 	System.Net.Sockets.dll!System.Net.LazyAsyncResult.ProtectedInvokeCallback(object result, System.IntPtr userToken) Line 431	C#
 	System.Net.Sockets.dll!System.Net.Sockets.BaseOverlappedAsyncResult.CompletionPortCallback(uint errorCode, uint numBytes, System.Threading.NativeOverlapped* nativeOverlapped) Line 181	C#
 	System.Threading.Overlapped.dll!System.Threading.ThreadPoolBoundHandleOverlapped.CompletionCallback(uint errorCode, uint numBytes, System.Threading.NativeOverlapped* nativeOverlapped) Line 48	C#

### PR DESCRIPTION
**Pull request by CIPop**
Fixing Windows SSPI Interop.
Adding a common Configuration and Capabilities infrastructure for System.Net in preparation for multi-machine testing.

Fixes #9160.

@davidsh @stephentoub PTAL

### CODE REVIEW

**Comment by CIPop** [comment]
project.json merge failure: will fix with the next commit.

```
19:39:38 D:\j\workspace\windows_nt_re---37265eab\build.proj(108,5): error : Dependency validation error: for System.Net.NameResolution 4.0.0-rc4-24214-03 in D:\j\workspace\windows_nt_re---37265eab\src\System.Net.Security\tests\FunctionalTests\unix\project.json package prerelease is 'rc4-24214-03', but expected 'rc4-24214-04' for packages matching '^(?i)((System\..*)|(NETStandard\.Library)|(Microsoft\.CSharp)|(Microsoft\.NETCore\.Targets)|(Microsoft\.NETCore\.Platforms)|(Microsoft\.Win32\..*)|(Microsoft\.VisualBasic))(?<!TestData)$'
19:39:38 D:\j\workspace\windows_nt_re---37265eab\build.proj(108,5): error : Dependency validation error: for System.Net.NameResolution 4.0.0-rc4-24207-03 in D:\j\workspace\windows_nt_re---37265eab\src\System.Net.Security\tests\FunctionalTests\win\project.json package prerelease is 'rc4-24207-03', but expected 'rc4-24214-04' for packages matching '^(?i)((System\..*)|(NETStandard\.Library)|(Microsoft\.CSharp)|(Microsoft\.NETCore\.Targets)|(Microsoft\.NETCore\.Platforms)|(Microsoft\.Win32\..*)|(Microsoft\.VisualBasic))(?<!TestData)$'
```

**Comment by CIPop** [comment]
Centos failed with #9444.

**Comment by davidsh** [comment]
Overall I'm ok with this approach to using partial classes for Capabilities and Configuration.

We should do a follow-up PR that modifies the existing tests here:
https://github.com/dotnet/corefx/blob/master/src/System.Net.Http/tests/FunctionalTests/DefaultCredentialsTest.cs

to see how those will fit into this revised model for capabilities/configuraiton. The System.Net.Http\tests\FunctionalTests\DefaultCredentialsTest is currently using the TestSettings class to do capabilities/configuration detection. It also uses environment variables similar to this PR.
https://github.com/dotnet/corefx/blob/master/src/Common/tests/System/Net/TestSettings.cs

LGTM.

**Comment by CIPop** [comment]
Test Innerloop CentOS7.1 Release Build and Test

**Comment by CIPop** [comment]
Test Innerloop CentOS7.1 Release Build and Test

**Comment by CIPop** [comment]
CentOS failed with #9449.

**Comment by CIPop** [comment]
Test Innerloop CentOS7.1 Release Build and Test

**Comment by CIPop** [comment]
Thanks @davidsh!

I'm working on scripts to deploy the multi-machine environment and, part of that work, I will make the changes to unify test configuration and capability discovery.

**Pull request merged**
