### PR TITLE
Enhance SqlClientDiagnosticListener to support SqlTransaction - Write…

### PR DESCRIPTION
**Pull request by fitzchak**
… tests

Writing tests for https://github.com/dotnet/corefx/pull/13212#issuecomment-259215456

cc @saurabh500

### CODE REVIEW

**Comment by stephentoub** [comment]
@dotnet-bot test this please

**Comment by saurabh500** [comment]
The changes add the diagnostics collectors. However there are no new tests added which exercise the Code path where the changes were made in `SqlTransaction`

To test this particular test you need to use 
msbuild /p:OSGroup=Windows_NT /t:ReBuildAndTest   /p:XunitOptions="-class  System.Data.SqlClient.Tests.DiagnosticTest" /p:EnableManualTests=true

You will need a valid connection string pointing to a Sql Server 
This is configured  at 
https://github.com/dotnet/corefx/blob/master/src/System.Data.SqlClient/tests/FunctionalTests/DiagnosticTest.cs#L17

**Comment by fitzchak** [comment]
@saurabh500 I tried to run using the `tools\msbuild.exe` but I'm getting the following error:

.\Tools\msbuild.exe /p:OSGroup=Windows_NT /t:ReBuildAndTest /p:XunitOptions="-cla
ss System.Data.SqlClient.Tests.DiagnosticTest" /p:EnableManualTests=true

Unhandled Exception: System.IO.FileLoadException: Could not load file or assembly 'MSBuild, Version=14.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. Strong name validation failed. (Exception from HRESULT: 0x8013141A) ---> System.Security.SecurityException: Strong name validation failed. (Exception from HRESULT: 0x8013141A)
   --- End of inner exception stack trace ---

It is simple test to write but I don't have how to debug it using the studio due to errors, it is hard for me to write this test.

**Comment by saurabh500** [comment]
@fitzchak  I think you need to clean the clone using clean.cmd from the root folder. 
I am not sure what is going on. But if I face such issues, I end up cleaning the clone and rebuilding it.

**Comment by fitzchak** [comment]
@saurabh500 Can you go on Skype with me? (fitzchak)

I done than but I have the same issue:

C:\work\corefx [13212-tests +0 ~1 -0]> .\Tools\msbuild.exe /p:OSGroup=Windows_NT /t:ReBuildAndTest /p:XunitOptions="-cla
>> ss System.Data.SqlClient.Tests.DiagnosticTest" /p:EnableManualTests=true


Unhandled Exception: System.IO.FileLoadException: Could not load file or assembly 'MSBuild, Version=14.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. Strong name validation failed. (Exception from HRESULT: 0x8013141A) ---> System.Security.SecurityException: Strong name validation failed. (Exception from HRESULT: 0x8013141A)
   --- End of inner exception stack trace ---

I addition, is there a way to debug the test from visual studio?
The issue there that the version of xunit that in use isn't supported by the visual studio tooling.

**Comment by saurabh500** [comment]
@fitzchak 
Try these steps. 
1. Open a command prompt 
2. Execute `call "%VS140COMNTOOLS%\VsDevCmd.bat" `
   This will add the VS tools on your path and this command prompt will be as good as using a Developer Command prompt from Visual Studio. I am assuming you have Visual Studio 2015 installed. 

3. Don't reference the `msbuild.exe` from the Tools folder. After execution of command at step 2, you should have msbuild on your path. 

4. Navigate to the FunctionalTests folder in SqlClient and run the test from the folder. 
`msbuild.exe /p:OSGroup=Windows_NT /t:ReBuildAndTest /p:XunitOptions="-class System.Data.SqlClient.Tests.DiagnosticTest" /p:EnableManualTests=true`

**Debugging the tests:**
The tests are executed from the folder they are built into, using the command like 
CoreRun.exe xunit.console.netcore.exe System.Data.SqlClient.Tests.dll -class System.Data.SqlClient.Tests.DiagnosticTest  -notrait category=OuterLoop -notrait category=failing -notrait category=nonwindowstests
The working directory for the tests is `corefx\bin\tests\Windows_NT.AnyCPU.Debug\System.Data.SqlClient.Tests\default.netcoreapp1.1`

After building the tests I execute the tests with `/d /v` parameters to the CoreRun.exe process. This waits for the debugger to attach.

Then in Visual studio. Debug > Attach To Process 
In Attach To: Select Managed (CoreCLR) Code
image


In the list of processes locate the corerun.exe process and attach the debugger.

**Comment by saurabh500** [comment]
If you have executed the build.cmd in a command prompt from the root of .Net core clone the "%VS140COMNTOOLS%\VsDevCmd.bat" is executed as a part of the build process and then you should be able to access msbuild from any folder.

**Comment by danmosemsft** [comment]
@fitzchak have you had a chance to take a look at this PR?

**Comment by fitzchak** [comment]
@saurabh500 @danmosemsft I'm looking into this now. 

@saurabh500 What is `CoreRun.exe`? Is it `dotnet`?

**Comment by fitzchak** [comment]
@saurabh500 FYI - I did executed the build.cmd but the was still needed for the msbuild to be recognized.

In addition, I wonder how important is it that I'll write the tests for the tracing, since this change is really minor. Please let me know.

This is what I'm getting: 

c:\work\corefx\bin\tests\Windows_NT.AnyCPU.Debug\System.Data.SqlClient.Tests\default.netcoreapp1.1>C:\work\coreclr\bin\Product\Windows_NT.x64.Debug\CoreRun.exe xunit.console.netcore.exe System.Data.SqlClient.Tests.dll -class System.Data.SqlClient.Tests.DiagnosticTest -notrait category=OuterLoop -notrait category=failing -notrait category=nonwindowstests /d /v

Unhandled Exception: System.MissingMethodException: Method not found: 'Void System.IO.FileStream..ctor(System.String, System.IO.FileMode)'.
   at Xunit.ConsoleClient.Program.Main(String[] args)

**Comment by danmosemsft** [comment]
@saurabh500 for question above.

**Comment by karelz** [comment]
@saurabh500 ping?

**Comment by danmosemsft** [comment]
@saurabh500?

**Comment by saurabh500** [comment]
@danmosemsft Ack. I will complete this.

**Comment by karelz** [comment]
@saurabh500 is the work now unblocked by your change #14960?

**Comment by karelz** [comment]
@saurabh500 ping?

**Comment by saurabh500** [comment]
The PR #14960 allows the execution of the Diagnostics tests without a Sql server dependency. So no additional installation is needed. 
What needs to be done here is add a few more test cases to Diagnostics test which invoke the diagnostics for Transactions and run them against the Test server. This is already mentioned in the comment https://github.com/dotnet/corefx/pull/13511#pullrequestreview-8308930

**Comment by karelz** [comment]
Thanks @saurabh500!

**Comment by danmosemsft** [comment]
@fitzchak do you expect to be able to finish this one off so we can merge it?

**Comment by karelz** [comment]
@fitzchak ping?

**Comment by fitzchak** [comment]
@saurabh500 @danmosemsft @karelz Yes I'll try to this again.

**Comment by fitzchak** [comment]
I am sorry but without been able to compile the test and run it in the visual studio it will be very hard to create a good test. 

See attached image:
image

The build of the tests is failing due to the following error:

{code}
1>------ Rebuild All started: Project: TDS, Configuration: Windows_Debug Any CPU ------
1>  TDS -> C:\work\corefx\bin\AnyOS.AnyCPU.Debug\TDS\netcoreapp\Microsoft.SqlServer.TDS.dll
2>------ Rebuild All started: Project: TDS.EndPoint, Configuration: Windows_Debug Any CPU ------
2>C:\work\corefx\buildvertical.targets(88,5): error MSB4018: The "FindBestConfiguration" task failed unexpectedly.
2>C:\work\corefx\buildvertical.targets(88,5): error MSB4018: System.ArgumentException: Unknown value 'Windows_Debug' found in configuration 'Windows_Debug'.  Expected property 'TargetGroup' with one of values netcore50, netcore50aot, uap101aot, uap101, uap, uapaot, netstandard1.0, netstandard1.1, netstandard1.2, netstandard1.3, netstandard1.4, netstandard1.5, netstandard1.6, netstandard2.0, netstandard, netcoreapp1.0, netcoreapp2.0, netcoreapp, netcoreapp1.2, netcoreapp1.2corert, net45, net451, net46, net461, net462, net463, netfx, win8, wpa81, portable_net45+win8+sl5, portable_net40+sl4+win8+wp8.
2>C:\work\corefx\buildvertical.targets(88,5): error MSB4018:    at Microsoft.DotNet.Build.Tasks.ConfigurationFactory.ParseConfiguration(String configurationString, Boolean permitUnknownValues) in C:\work\corefx\src\Tools\CoreFx.Tools\Configuration\ConfigurationFactory.cs:line 206
2>C:\work\corefx\buildvertical.targets(88,5): error MSB4018:    at Microsoft.DotNet.Build.Tasks.FindBestConfiguration.Execute() in C:\work\corefx\src\Tools\CoreFx.Tools\FindBestConfiguration.cs:line 34
2>C:\work\corefx\buildvertical.targets(88,5): error MSB4018:    at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
2>C:\work\corefx\buildvertical.targets(88,5): error MSB4018:    at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()
========== Rebuild All: 1 succeeded, 1 failed, 0 skipped ==========
{code}

**Comment by karelz** [comment]
@weshaggard @mellinoe can you please help here?

**Comment by weshaggard** [comment]
The solution file needs updated, as it doesn't have the correct configurations. See https://github.com/dotnet/corefx/pull/15505/files which has an updated version of that sln file, try and pull that version down and try again.

**Comment by danmosemsft** [comment]
@fitzchak any luck?

**Comment by karelz** [comment]
The PR drags for 3 months now :( ... @fitzchak do you have timeline you want to finish it on? Do you need any help/assistance?

**Comment by fitzchak** [comment]
I fetched the latest code, but still get error when compiling in VS the test project.
I cleaned the folder using `git clean -f -x -d` and run the `build` script successfully.

`1>------ Rebuild All started: Project: System.Data.SqlClient (ref\System.Data.SqlClient), Configuration: netcoreapp-Debug Any CPU ------
1>  System.Data.SqlClient -> C:\work\corefx\bin\ref\System.Data.SqlClient\4.1.2.0\netcoreapp\System.Data.SqlClient.dll
2>------ Rebuild All started: Project: System.Data.SqlClient (src\System.Data.SqlClient), Configuration: netcoreapp-Windows_NT-Debug Any CPU ------
2>  System.Data.SqlClient -> C:\work\corefx\bin\Windows_NT.AnyCPU.Debug\System.Data.SqlClient\netcoreapp\System.Data.SqlClient.dll
3>------ Rebuild All started: Project: IMonitorLoader, Configuration: Debug Any CPU ------
4>------ Rebuild All started: Project: TDS, Configuration: Debug Any CPU ------
5>------ Rebuild All started: Project: System.Data.SqlClient.ManualTesting.Tests, Configuration: netcoreapp-Debug Any CPU ------
3>  IMonitorLoader -> C:\work\corefx\bin\AnyOS.AnyCPU.Debug\IMonitorLoader\netcoreapp\Monitoring.dll
6>------ Rebuild All started: Project: System.Data.StressRunner, Configuration: Debug Any CPU ------
4>  TDS -> C:\work\corefx\bin\AnyOS.AnyCPU.Debug\TDS\netcoreapp\Microsoft.SqlServer.TDS.dll
7>------ Rebuild All started: Project: TDS.EndPoint, Configuration: Debug Any CPU ------
5>  System.Data.SqlClient.ManualTesting.Tests -> C:\work\corefx\bin\AnyOS.AnyCPU.Debug\System.Data.SqlClient.ManualTesting.Tests\netcoreapp\System.Data.SqlClient.ManualTesting.Tests.dll
6>CSC : error CS0006: Metadata file 'C:\work\corefx\bin\Windows_NT.AnyCPU.Debug\IMonitorLoader\netcoreapp\Monitoring.dll' could not be found
8>------ Rebuild All started: Project: System.Data.StressFramework, Configuration: Debug Any CPU ------
7>CSC : error CS0006: Metadata file 'C:\work\corefx\bin\Windows_NT.AnyCPU.Debug\TDS\netcoreapp\Microsoft.SqlServer.TDS.dll' could not be found
9>------ Rebuild All started: Project: TDS.Servers, Configuration: Debug Any CPU ------
8>CSC : error CS0006: Metadata file 'C:\work\corefx\bin\Windows_NT.AnyCPU.Debug\System.Data.StressRunner\netcoreapp\System.Data.StressRunner.exe' could not be found
10>------ Rebuild All started: Project: System.Data.SqlClient.Stress.Tests, Configuration: Debug Any CPU ------
9>CSC : error CS0006: Metadata file 'C:\work\corefx\bin\Windows_NT.AnyCPU.Debug\TDS\netcoreapp\Microsoft.SqlServer.TDS.dll' could not be found
9>CSC : error CS0006: Metadata file 'C:\work\corefx\bin\Windows_NT.AnyCPU.Debug\TDS.EndPoint\netcoreapp\Microsoft.SqlServer.TDS.EndPoint.dll' could not be found
11>------ Rebuild All started: Project: System.Data.SqlClient.Tests, Configuration: Debug Any CPU ------
10>CSC : error CS0006: Metadata file 'C:\work\corefx\bin\Windows_NT.AnyCPU.Debug\System.Data.StressFramework\netcoreapp\System.Data.StressFramework.dll' could not be found
10>CSC : error CS0006: Metadata file 'C:\work\corefx\bin\Windows_NT.AnyCPU.Debug\System.Data.StressRunner\netcoreapp\System.Data.StressRunner.exe' could not be found
11>CSC : error CS0006: Metadata file 'C:\work\corefx\bin\Windows_NT.AnyCPU.Debug\TDS\netcoreapp\Microsoft.SqlServer.TDS.dll' could not be found
11>CSC : error CS0006: Metadata file 'C:\work\corefx\bin\Windows_NT.AnyCPU.Debug\TDS.EndPoint\netcoreapp\Microsoft.SqlServer.TDS.EndPoint.dll' could not be found
11>CSC : error CS0006: Metadata file 'C:\work\corefx\bin\Windows_NT.AnyCPU.Debug\TDS.Servers\netcoreapp\Microsoft.SqlServer.TDS.Servers.dll' could not be found
========== Rebuild All: 5 succeeded, 6 failed, 0 skipped ==========`

**Comment by danmosemsft** [comment]
@joperezr

**Comment by karelz** [comment]
@fitzchak did you try build outside of VS?

**Comment by joperezr** [comment]
Hey @fitzchak, do you mind trying the following from a developer command prompt at the root of corefx and see if that works for you:
```cmd
<Close VS>
git clean -xfd
build.cmd
build-tests.cmd
<Reopen VS>
```
If you did a full clean, we now require you to run build.cmd at least once before you can open projects in VS since we need to build the right targeting packs in order for tests to work.
Let me know if that works for you.

**Comment by fitzchak** [comment]
@joperezr Thanks. That worked. I'm able to run the tests :)

@saurabh500 I amended the last commit and added a test to transactions, but the issue that it made other tests fail and I don't have any idea why. Can you take a look?

**Comment by stephentoub** [comment]
@dotnet-bot test this please (Jenkins was down)

**Comment by danmosemsft** [comment]
@fitzchak how are things going? Do you expect o have time to kick this along? Just chasing up the old PR's.

**Comment by fitzchak** [comment]
Unfortunately no, see my latest comment.

**Comment by danmosemsft** [comment]
@fitzchak did you mean to close?
@saurabh500 for q above.

**Comment by fitzchak** [comment]
@danmosemsft Yes. Because that all this PR is about testing a tracing statement that exists. This is a minor test really.
But you can open it after commenting on the above issue and I'll take a look again.

**Pull request closed without merging**
