### PR TITLE
[release/2.1] Add Fedora 32 and CentOS 8 runtime ids

### PR DESCRIPTION
**Pull request by omajid**
This is a combined backport of:

- PR #41397: commit 6f82bd59a05ea9556397596ae9e59f39b904b222
- PR #40786: commit 86fc9e751c424278a9c4e163e0a71a9d7e30c8e7

Do I need to bump the version in `pkg/Microsoft.NETCore.Platforms/Microsoft.NETCore.Platforms.pkgproj`?

### CODE REVIEW

**Comment by danmosemsft** [comment]
> pkg/Microsoft.NETCore.Platforms/Microsoft.NETCore.Platforms.pkgproj?

@ericstj  ?

**Comment by danmosemsft** [comment]
RID updates to preserve our supported OS matrix are "tell mode".

**Comment by omajid** [comment]
> RID updates to preserve our supported OS matrix are "tell mode".

Thanks. Is "tell mode" defined somewhere publicly? I think I have a rough idea of what this means ("inform release management team about this change, but doesn't need explicit permission from them for this change to be included in release") but it would be good to know if I am off.

**Comment by ericstj** [comment]
https://github.com/dotnet/corefx/commit/e990dfb99c3f10dd747dba8ae74533f11348f22b already bumped the platforms version to newer than what was previously shipped, however https://github.com/dotnet/corefx/commit/e07654a425a745f70766c08d452b51b97e68a41b stopped building the package.  You need to undo the latter: include the package in packages.builds to ensure we build & ship it in servicing.

**Comment by omajid** [comment]
> You need to undo the latter: include the package in packages.builds to ensure we build & ship it in servicing.

Thanks for pointing that out. Done.

**Comment by maryamariyan** [comment]
Thank you for your contribution. As announced in dotnet/coreclr#27549 this repository will be moving to dotnet/runtime on November 13. If you would like to continue working on this PR after this date, the easiest way to move the change to dotnet/runtime is:
1.	In your corefx repository clone, create patch by running `git format-patch origin`
2.	In your runtime repository clone, apply the patch by running `git apply --directory src/corefx <path to the patch created in step 1>`

**Comment by maryamariyan** [comment]
Please ignore my previous comment. Since this PR is not targeting master branch, no action would be needed here. Thanks.

**Review by ericstj — APPROVED** [review]
This looks good.  Confirmed the package version is already bumped.

**Review by safern — APPROVED** [review]

**Pull request merged**
