### PR TITLE
Add missing token property to System.Security.Principal.WindowsIdentity

### LINKED ISSUE #11297: S.S.P missing Token property
As per http://referencesource.microsoft.com/#mscorlib/system/security/principal/windowsidentity.cs,ec5619fe4ea57a04, `WindowsIdentity.Token` can be defined in CoreFX as:

```c#
public virtual IntPtr Token => m_safeTokenHandle.DangerousGetHandle();
```

The current workaround for consumers is: `AccessToken.DangerousGetHandle()`.

### PR DESCRIPTION
**Pull request by maddin2016**
fixes #11297
Add missing property `Token`.

### CODE REVIEW

**Comment by maddin2016** [comment]
Hi @stephentoub, i see that the CI test are failing. This is because they point to an older version of `System.Security.Principal.Windows.dll` which doesn't include the newly created property. Why it doesn't show to the latest build. Should i harcode?

**Comment by stephentoub** [comment]
> Why it doesn't show to the latest build

Because the reference assembly hasn't been updated (the ref folder), and the tests are targetting an older version of netstandard.

@weshaggard, do we have the directions written down anywhere for how someone can update a project that hasn't yet been updated for netstandard1.7, etc.?  If not, we've made it difficult for folks to contribute to the API effort in projects we haven't yet updated, e.g. this one (System.Security.Principal.Windows)

cc: @bartonjs

**Comment by bartonjs** [comment]
The implementation LGTM; but it'll need the contract change to be meaningful (and testable).

**Comment by weshaggard** [comment]
>@weshaggard, do we have the directions written down anywhere for how someone can update a project that hasn't yet been updated for netstandard1.7, etc.? If not, we've made it difficult for folks to contribute to the API effort in projects we haven't yet updated, e.g. this one (System.Security.Principal.Windows)

Not that I'm aware of. I'm not even sure it is worth documenting the netstandard1.7 stuff because that is just temporary work that will need to get changed at some point but the general process for adding new APIs to .NET Core, @ericstj is working on an example which I expect we will want to document.

**Comment by maddin2016** [comment]
Hey at all, because i'm realtively new to .net core, is there some docu about all this .net core, netstandard 1.0 1.2 1.3 ,,,, contracts, ... stuff. And how all this works together, especially from a technical standpoint. So what is this about when you say `hasn't yet been updated for netstandard1.7` or `contract change`. So in theory this all clear to me, but what i not found is how all this works together in a real example. Thanks in advance!!!!

**Comment by stephentoub** [comment]
@joperez, when you have a minute, could you help @maddin2016 with the changes that need to be made to System.Security.Principal.Windows (pkg, src, ref, tests, etc.) to enable adding back an API?  As a standalone commit, for at least the foreseeable future we can then use that as a reference / the documentation for how these projects need to be updated before post-1.0 APIs can be added.

**Comment by Petermarcu** [comment]
@ericstj

**Comment by joperezr** [comment]
> @joperezr, when you have a minute, could you help @maddin2016 with the changes that need to be made to System.Security.Principal.Windows (pkg, src, ref, tests, etc.) to enable adding back an API

@maddin2016 sorry, for some reason I didn't see this notification, I'll take a look at this PR later today and add some feedback

**Comment by ericstj** [comment]
Since this isn't part of NETStandard.Library it's a bit different than all the other stuff you guys have been doing in dev/API.  For this one I'd just update the assembly without changing TFM or anything since the new member can be supported on all frameworks the package currently targets and the package is fat so it can carry that new implementation to all frameworks.  In which case you can simply just update the assembly version in dir.props to 4.1.0.0 (as is done with any API change) and leave everything else alone.

@weshaggard does that sound correct?

**Comment by weshaggard** [comment]
@ericstj I think in this case where it isn't currently part of netstandard itself and the API already exists on all platforms I believe you are correct that we can just get away with versioning the assembly. 

We still really need to spend some time working through all the cases and documenting hat we cannot and cannot do as well as how people go about doing the different update cases.

**Comment by stephentoub** [comment]
@maddin2016, I've cherry-picked your commit and made the additional necessary changes in https://github.com/dotnet/corefx/pull/11700. Thanks.

**Pull request closed without merging**
