### PR TITLE
Expose and test APIs for some threading metrics (CoreFX)

### PR DESCRIPTION
**Pull request by kouvel**
- API review: https://github.com/dotnet/corefx/issues/35500
- Depends on https://github.com/dotnet/coreclr/pull/22754, https://github.com/dotnet/corert/pull/7066

### CODE REVIEW

**Comment by karelz** [comment]
@kouvel do you plan to update the change and push the PR forward now that we have API review?

**Comment by kouvel** [comment]
I have updated to remove local/global versions of PendingWorkItemCount. They can be added in the future if they would be useful. I think all three PRs (CoreCLR, CoreRT, and CoreFX) are now ready for review. @stephentoub, would you be able to take a look?

**Comment by kouvel** [comment]
The test in the latest commit is not exactly testing for the ordering issue that I mentioned in https://github.com/dotnet/corert/pull/7066, that would be more difficult to repro without adding a similar race between the `Values` getter and `Dispose`, and adding any synchronization to ensure that ordering would not repro the issue. So it would not be an issue when the caller is expected to ensure that `Dispose` does not race with the `Values` getter. The test seemed like a somewhat reasonable expectation though.

**Comment by karelz** [comment]
@kouvel still working on it?

**Comment by kouvel** [comment]
Yea still working on it, currently blocked on CI failures in https://github.com/dotnet/coreclr/pull/22754, doesn't look like my change but trying to get a clean run

**Comment by kouvel** [comment]
Continued in https://github.com/dotnet/corefx/pull/37401

**Pull request closed without merging**
