### PR TITLE
Further cleanup to GregorianCalendar tests

### PR DESCRIPTION
**Pull request by hughbe**
- Should make it considerably easier to add new tests

/cc @tarekgh @stephentoub

### CODE REVIEW

**Comment by tarekgh** [comment]
LGTM

**Comment by tarekgh** [comment]
test Innerloop OSX Debug Build and Test  please

**Comment by tarekgh** [comment]
test Innerloop OSX Debug Build and Test please

**Comment by stephentoub** [comment]
Test Innerloop OSX Debug Build and Test please (Jenkins failure)

**Pull request merged**
