### PR TITLE
Remove a test line that got left in

### PR DESCRIPTION
**Pull request by JeremyKuhne**
Was experimenting with different root paths on Unix and inadvertently left
in a line of code.

#13474

@danmosemsft, @ianhays

### CODE REVIEW

**Comment by danmosemsft** [comment]
Odd the test passed in CI

**Comment by danmosemsft** [comment]
@dotnet-bot test  Innerloop Windows_NT Release Build and Test  (https://github.com/dotnet/corefx/issues/14135)

**Comment by stephentoub** [comment]
> Odd the test passed in CI

Probably one of many test holes 😦

**Comment by danmosemsft** [comment]
Ah the test that failed probably wrapped the UnauthorizedAccessException it causes.

**Comment by JeremyKuhne** [comment]
>> Odd the test passed in CI

>Probably one of many test holes 😦

Are you inferring with this specific assembly or in general?

It was a matter of rights and where the enlistment is. I could put tests in that check that they start with whatever Environment gives back I suppose- but it would be an internals test- the path isn't exposed.

I wonder if it is plausible or valuable to have some sort of validation that we don't write outside of "approved" areas during tests.

**Comment by stephentoub** [comment]
> Are you inferring with this specific assembly or in general?

Nope, I meant across the whole repo, with overall 50% line coverage from our tests.

**Comment by danmosemsft** [comment]
@davidsh we hit the safe handles failure twice in a row. Retry?

**Comment by davidsh** [comment]
>@davidsh we hit the safe handles failure twice in a row. Retry?

Something seems to have changed in CoreCLR with SafeHandle and the dispose'ing logic.  Otherwise that test would never fail.

Probably needs to be disabled at this point so that it doesn't block CI.

**Comment by danmosemsft** [comment]
Jeremy since all the other tests pass I think you can ignore that failure while David disables it.

**Comment by stephentoub** [comment]
> Something seems to have changed in CoreCLR with SafeHandle and the dispose'ing logic. Otherwise that test would never fail.

@jkotas, are you aware of any changes related here?

**Comment by jkotas** [comment]
The test fails with: `Assert.Equal() Failure\r\nExpected: 1\r\nActual: 3` at `Assert.Equal(1, FakeSafeWinHttpHandle.HandlesOpen);`

HandlesOpen keeps track of active `FakeSafeWinHttpHandle` instances in a global static variable. FakeSafeWinHttpHandle are created by number of different tests. I do not see anything that guarantees that none of these tests are running in parallel. It looks like a classic global state race to me.

**Comment by davidsh** [comment]
@jkotas 
>HandlesOpen keeps track of active FakeSafeWinHttpHandle instances in a global static variable. FakeSafeWinHttpHandle are created by number of different tests. I do not see anything that guarantees that none of these tests are running in parallel. It looks like a classic global state race to me.

We do not run the tests in parallel. We explicitly tell Xunit to run these unit tests serially.  

See:
https://github.com/dotnet/corefx/blob/master/src/System.Net.Http.WinHttpHandler/tests/UnitTests/XunitTestAssemblyAtrributes.cs

```c#
// The WinHttpHandler unit tests need to have parallelism turned off between test classes since they rely on
// a mock network with simulated failures controlled by singleton static classes (TestControl, TestServer).
// This attribute will put all test classes into a single collection. Default Xunit behavior is to run tests
// within a single collection in series and not in parallel.
[assembly: CollectionBehavior(CollectionBehavior.CollectionPerAssembly)]
```

**Comment by jkotas** [comment]
This not sufficient to prevent the tests from stomping on the `FakeSafeWinHttpHandle.HandlesOpen` global state. Number of these tests do not cleanup after itself. They depend on the GC and finalizers to cleanup that happens later, in parallel with other tests running.

E.g. add `Assert.Equal(0, FakeSafeWinHttpHandle.HandlesOpen);` at the end of tests in https://github.com/dotnet/corefx/blob/master/src/System.Net.Http.WinHttpHandler/tests/UnitTests/WinHttpResponseStreamTest.cs to see the problem.

**Comment by jkotas** [comment]
@dotnet-bot test this please

**Comment by davidsh** [comment]
>This not sufficient to prevent the tests from stomping on the FakeSafeWinHttpHandle.HandlesOpen global state. Number of these tests do not cleanup after itself. They depend on the GC and finalizers to cleanup that happens later, in parallel with other tests running.

These unit tests used to work fine for many months until recently.  Perhaps there was a recent timing change to how GC/finalizers work?

What do you recommend to fix these tests?  How can we deterministicly have the GC/finalization work in order for these tests to pass consistently?

**Comment by jkotas** [comment]
Well, that's the usual pattern with races. They are hiding in the code for months or years, and suddenly start showing up for no apparent reason. I am not aware of any CoreCLR change that can be directly attributed to this.

The exact timing of the GC depends on *many* factors:

- Somebody might shave an allocation in completely unrelated place that makes the GC to kick in slightly different spot for these tests now
- The tests might have moved to slightly different block of machines in Azure that affected the exact GC timing
- ...

> What do you recommend to fix these tests?

I do not see a good reason for the safe handle tests to depend on GC/finalization, or global state:

- To test the unique added logic in SafeWinHttpHandle, you can just maintain an instance field on FakeSafeWinHttpHandle to detect whether the Release method was called. 

```
            Assert.False(safeHandle.IsClosed, "closed");
            Assert.Equal(1, FakeSafeWinHttpHandle.HandlesOpen);
```

would become:

```
            Assert.False(safeHandle.IsClosed, "closed");
            Assert.False(safeHandle.IsReallyClosed, "really closed");
```

Or you can just trust the SafeHandle.IsClosed property to validate that handle was closed. Most of the SafeWinHttpHandleTest tests are actually just testing general SafeHandle behavior. It does not hurt, but it is pretty low value. We should consider moving them under System.Runtime and turning them into regular SafeHandle tests.

- Change all tests that call `MakeRequestStream` to dispose the stream. This is a good general hygiene. For example, wrap the tests in `using`:
```
using (Stream stream = MakeRequestStream())
{
    ... the existing code of the test ...
}
```

**Pull request merged**
