### PR TITLE
Fix ParallelStateTests failing in outerloop

### PR DESCRIPTION
**Pull request by stephentoub**
These were broken by https://github.com/dotnet/corefx/pull/7796.
cc: @hughbe 
Fixes https://github.com/dotnet/corefx/issues/7807

### CODE REVIEW

**Comment by stephentoub** [comment]
test outerloop windows debug please

**Comment by stephentoub** [comment]
Test outerloop Windows_NT debug please

**Comment by hughbe** [comment]
Oh shucks, sorry - I wonder why the CI/local tests didn't catch this

**Comment by hughbe** [comment]
Oh I see - outer loop tests

**Pull request merged**
