### PR TITLE
[Arm/CI] Add hardfp build to arm32_ci_script.sh

### PR DESCRIPTION
**Pull request by wateret**
Now hardfp is default. For softfp, `--softfp` must be given as an argument.

Related Issue : #12545

### CODE REVIEW

**Comment by wateret** [comment]
Changes in `arm32_ci_script.sh` only. There is no effect to CI's behavior. Will keep working on it after adding rootfs image for arm-hardfp to CI.

**Comment by wateret** [comment]
It is natural that `Innerloop Linux ARM Emulator` checks fail because there is a little change on usage of `arm32_ci_script.sh`

**Comment by stephentoub** [comment]
> It is natural that Innerloop Linux ARM Emulator checks fail because there is a little change on usage of arm32_ci_script.sh

How will that be fixed?  We don't want to merge this if it's going to cause all PRs to start failing.

**Comment by wateret** [comment]
@stephentoub I changed the usage of `arm32_ci_script.sh` and there was changes in `netci.groovy` accordingly. AFAIK I can't test changes for `netci.groovy` before it is merged and that's why the CI complains. I think there would be no problem once it is merged.

**Comment by stephentoub** [comment]
@dotnet-bot test ci please

**Comment by stephentoub** [comment]
>  I changed the usage of arm32_ci_script.sh and there was changes in netci.groovy accordingly. AFAIK I can't test changes for netci.groovy before it is merged and that's why the CI complains. I think there would be no problem once it is merged.

Ok, thanks.  We can go ahead with it, and then we'll need to disable the emulator legs if that turns out not to be the case.

**Comment by wateret** [comment]
@dotnet-bot test ci please

**Pull request merged**
