### PR TITLE
WIP: StrongNameKeyPair experiments

### PR DESCRIPTION
**Pull request by SimonCropp**

### CODE REVIEW

**Comment by stephentoub** [comment]
@simoncropp, what is this?

**Comment by SimonCropp** [comment]
@stephentoub i need StrongNameKeyPair working with Fody, and hence cecil. Since StrongNameKeyPair  throws notImpls on net core, it doesnt work when i try to re-sn when using `dotnet build`. I have a partially working variant here https://github.com/Fody/cecil/blob/fody2/Mono.Cecil/StrongNameKeyPair.cs based on the good work from @atykhyy. it is not fully working yet, eg doesnt support delay signing. and it is not fully tested, i have only smoke tested it on a few projects.

so i was going to experiment with how difficult it would be to get proper support for it into netcore

cc @jbevain

**Comment by stephentoub** [comment]
Thanks for letting me know.  Sounds like an interesting project.

The actual implementation of StrongNameKeyPair is in System.Private.Corelib in the coreclr repo, and a PR here in corefx to tweak these tests would only run against changes there if those coreclr changes were merged and then that updated build consumed into corefx.

As such, I'm not clear on what this PR is actually going to achieve.

**Comment by SimonCropp** [comment]
ok. sorry for the confusion. i will look at the other repo

**Comment by stephentoub** [comment]
Not a problem.  Thanks!

**Comment by danmosemsft** [comment]
It's easy to be confused, maybe it would help if we rename `corefx\src\Common\src\CoreLib` to `corefx\src\Common\src\CoreLibReadOnlyMirror` ?

**Pull request closed without merging**
