### PR TITLE
Improve UnloadingAndProcessExitTests.netcoreapp.cs to help narrow down repro for recurring bug

### PR DESCRIPTION
**Pull request by nchikanov**
Based off of issue #23307 
Changes will make it slightly easier to track down the source of error for this test

### CODE REVIEW

**Comment by JeremyKuhne** [comment]
Interestingly it hit your change on the PR:

```
Assert.Equal() Failure
            ? (pos 2)
Expected: shu0u1e0e1
Actual:   sh
            ? (pos 2)
```

So clearly it's getting hooked, but maybe the callbacks aren't being called? It is possible that the file write is failing, but I'm struggling to think of how that might happen without surfacing an error. Perhaps a weakness in the remoting wrappers?

**Comment by stephentoub** [comment]
> Interestingly it hit your change on the CI

I think it's failed in most (all?) CI runs today.  Maybe something actually broke in the runtime?

Can we disable the test for now while it's investigated, in order to unblock other PRs (though there are other blocking issues, still, like the macOS networking infrastructure)?

**Comment by danmosemsft** [comment]
If the runtime broke I wonder why it doesn't repro for Nina locally

**Comment by nchikanov** [comment]
> If the runtime broke I wonder why it doesn't repro for Nina locally

@danmosemsft Sorry, I didn't run with TargetGroup set to UAP. I do see the error reproduced locally now.

`ERROR:    System.Tests.UnloadingAndProcessExitTests.UnloadingEventMustHappenBeforeProcessExitEvent [FAIL]
        Assert.Equal() Failure
                    Γåô (pos 2)
        Expected: shu0u1e0e1
        Actual:   sh
                    Γåæ (pos 2)
        Stack Trace:
          C:\repos\corefx\src\System.Runtime.Extensions\tests\System\UnloadingAndProcessExitTests.netcoreapp.cs(36,0): at System.Tests.UnloadingAndProcessExitTests.Unloadi
  ngEventMustHappenBeforeProcessExitEvent()`

**Comment by danmosemsft** [comment]
OK then yeah I suggest you add to this PR
`[ActiveIssue("https://github.com/dotnet/corefx/issues/23307", TargetFrameworkMonikers.Uap)]`

**Comment by danmosemsft** [comment]
LGTM

**Pull request merged**
