### PR TITLE
Fix helper thread stack size for Alpine

### PR DESCRIPTION
**Pull request by janvorli**
CoreFX creates a helper thread for handling some signals. This thread is
created using pthread API without explicit setting of stack size. That
means that on Alpine, it gets only 85kB of stack. We have hit stack
overflow in one of our coreclr tests in checked build due to that.

This change sets the default stack size of that thread to 512kB,
which should be sufficient.

### CODE REVIEW

**Comment by janvorli** [comment]
cc: @sandreenko

**Comment by janvorli** [comment]
Fixes https://github.com/dotnet/coreclr/issues/25067

**Comment by sandreenko** [comment]
Thanks, @janvorli, for the fix/help with that issue.

**Comment by danmosemsft** [comment]
You mention checked builds, should we use less in release?

**Comment by janvorli** [comment]
> You mention checked builds, should we use less in release?

We could even keep the default stack size for release. We were getting out of stack in debug / checked builds because the clang compiler generates very large frame (~5kB) due to some helper locals for one of the JIT methods that is called recursively when the failure happens. In release build, the same frame size is under 500 bytes.
@stephentoub what do you think, would you prefer to make the change for debug / checked builds only?

**Comment by stephentoub** [comment]
In the name of working better in more constrained environments, if we've never had an issue in release and don't anticipate one, let's leave it debug/checked only; if we think there's any chance we could hit it in release, let's keep it always. For post-3.0 I agree with Jan's initial question to me that we should look into whether we can just utilize the existing coreclr logic, centralizing this, e.g. by making this a managed thread that then calls into native for the handling loop.

**Comment by janvorli** [comment]
I've chatted with @sandreenko about the stack size. We believe that in release build, the default stack size is sufficient, so I have made it debug only.

**Pull request merged**
