### PR TITLE
Add nuget.org feed to NuGet.config

### PR DESCRIPTION
**Pull request by riarenas**
We need all restore sources to be located in NuGet.config since internal feeds can only be restored from there. More details including next steps [here](https://github.com/dotnet/arcade/blob/master/Documentation/RestoreSourcesUpdateStatus.md)

Please let me know if there are any other feeds that I missed.

### CODE REVIEW

**Comment by ViktorHofer** [comment]
Hey Ricardo, unfortunately I missed your PR and opened myself one to tackle this: https://github.com/dotnet/corefx/pull/39399. Are you sure that we need nuget.org in the NuGet.config? Ie I don't see it in Standard (https://github.com/dotnet/standard/blob/master/NuGet.config) but it's marked as no changes needed in the list.

**Comment by riarenas** [comment]
Standard didn't have nuget.org in its versions.props file, and they removed the only restoreSources they had, so moving the feeds ended up being a no-op. 
Corefx has nuget.org in its Directory.Build.Props. 
Since we're trying for this first step to be as harmless to the repo as possible, I added it just to be safe. If you think it's not necessary, then even better!

**Comment by ViktorHofer** [comment]
The RestoreSources in Directory.Build.props aren't used during Arcade restore. I think this isn't necessary.

**Comment by ViktorHofer** [comment]
OK, spoke to soon, we need nuget.org in the NuGet.config for the repo/global tools. Reopening.

**Pull request merged**
