### PR TITLE
Removing incorrect error numbers

### PR DESCRIPTION
**Pull request by michaelaird**
Error codes 40020, 40143, 40166, and 40540 are embedded within the message of 40197 and not SQL error numbers to retry on.

### CODE REVIEW

**Comment by weshaggard** [comment]
@saurabh500 PTAL

**Comment by stephentoub** [comment]
@saurabh500, should this be merged?

**Comment by saurabh500** [comment]
@michaelaird Thanks for the cleanup.

**Comment by michaelaird** [comment]
No problem. It came up as part of this discussion https://github.com/aspnet/EntityFramework/issues/237

**Pull request merged**
