### PR TITLE
Allow AdditionalCodeCoverageAssemblies to be specified in project files

### LINKED ISSUE #15429: CodeCoverage target clean-up
See https://github.com/dotnet/corefx/pull/15397#discussion_r97456921.

We should not have people referencing properties/items that begin with an underscore in projects those are intended to be private properties in targets. https://github.com/dotnet/corefx/blob/7642f1f980fb0e8fa45f67769e0755a97df7b4d5/Tools-Override/CodeCoverage.targets#L44

We should provide a non-private property or item group that folks can use to configure their project.

### PR DESCRIPTION
**Pull request by mellinoe**
Fixes #15429 

@weshaggard @JonHanna

### CODE REVIEW

**Comment by JonHanna** [comment]
So from now on one uses `<CodeCoverageAssemblies …` in the project csproj files rather than `<_CodeCoverageAssemblies …`? (Not that there should be that many cases where it's useful to consider tests as testing two things, I imagine the case of testing base classes in one project by testing derived classes in another isn't that common)

**Comment by mellinoe** [comment]
> So from now on one uses <CodeCoverageAssemblies … in the project csproj files rather than <_CodeCoverageAssemblies …?

After this, you would specify this in a project file:

```XML
<ItemGroup>
    <AdditionalCodeCoverageAssemblies Include="System.Assembly" />
    <AdditionalCodeCoverageAssemblies Include="System.Other" />
</ItemGroup>
```

**Comment by mellinoe** [comment]
There shouldn't be any existing usages that need modified yet.

**Comment by JonHanna** [comment]
I'm not sure this works.

I pulled down master after this went in, rebased my branch for #15397 on top of it and changed from `<_CodeCoverageAssemblies Include="Microsoft.CSharp" />` to `<AdditionalCodeCoverageAssemblies Include="Microsoft.CSharp" />`, built `Microsoft.CSharp` and then copied the DLL and PBD from D:\dotnet\corefx\bin\AnyOS.AnyCPU.Debug\Microsoft.CSharp\netstandard to D:\dotnet\corefx\bin\AnyOS.AnyCPU.Debug\System.Linq.Expressions.Tests\netstandard before running the expressions tests. The coverage report I got only covered expressions.

Changing back to `<_CodeCoverageAssemblies Include="Microsoft.CSharp" />` and running the tests again gave me a report with coverage of both assemblies, so it would seem that it wasn't that I'd made a mistake somewhere there.

**Comment by mellinoe** [comment]
@JonHanna Did you make sure to re-initialize tools (or run `cp Tools-Override/* Tools`, more importantly) ? You might still be using the old CodeCoverage.targets unless you did.

**Comment by JonHanna** [comment]
Ah. It seems that was all it was.
Since that PR is still open, I'm going to re-push the branch so it can serve as a full test with the CI.

**Pull request merged**
