### PR TITLE
Add project.lock.json files

### PR DESCRIPTION
**Pull request by krwq**
Those files are spamming all over the repo after each build. I think it is easiest to just add it.

+ @ericstj

### CODE REVIEW

**Comment by ericstj** [comment]
What's the problem?  They are part of gitignore, same as obj folder.

Please hold off on checking these in.

**Comment by krwq** [comment]
But they spam whole repo, The point of bin and packages folders is to reduce spam to those places. We don't want binaries next to projects for the same reason.

I often use "git clean -fdx --dry-run" to verify if I don't remove anything by accident. Right now I have list of around 150 items and it is impossible to find anything in there.

**Comment by sharwell** [comment]
:-1: This commit adds a bunch of intermediate files that are part of .gitignore **by design**.

**Comment by krwq** [comment]
We should change the design then.

**Comment by krwq** [comment]
I see that in theory lock.json should be created in $(IntermediateOutputPath). The path of that seems to be in the bin folder. I don't fully understand why is it created next to the project file.

**Comment by ericstj** [comment]
As I mentioned before, we'll add them at a later time once they actually contain the correct information.  Right now we're waiting on changes to DNX.  Checking them in is going to just cause unnecessary noise right now and could actually cause problems.  Suck it up and 'del /s *lock.json' or 'attrib +H *lock.json /S' if seeing them bothers you.

**Pull request closed without merging**
