### PR TITLE
Update CoreClr to preview2-26204-01 (master)

### PR DESCRIPTION
**Pull request by jkotas**

### CODE REVIEW

**Comment by jkotas** [comment]
cc @eerhardt @nattress @joshfree

**Comment by ericstj** [comment]
@jkotas when is UAP going to be turned back on?  We cannot ship 2.1 this way.  /cc @joperezr

**Comment by eerhardt** [comment]
@ericstj - See https://github.com/dotnet/corefx/issues/26802.

@nattress - any progress?

**Comment by jkotas** [comment]
@ericstj Which part of UAP is required to ship 2.1? I think we may want to look into re-enabling the specific part so that this does not block .NET Core 2.1.

**Comment by nattress** [comment]
ProjectN branch has been fixed such that Nutc should find the `Vector` and `Vector<T>` intrinsics in either CoreLib or S.N.Vectors. This Maestro PR contains the updated ProjectN tools: https://github.com/dotnet/corefx/pull/27443

Once that merges, we can re-enable UAP. There has been some rot in the last couple weeks with UAP incompatible commits that will require fixes. I have a few already available and will send out a PR for them once the new ILC is available.

**Comment by ericstj** [comment]
> Which part of UAP is required to ship 2.1? 

Any package we ship that carries a UAP specific implementation.  Specifically https://github.com/dotnet/corefx/pull/26825/commits/2202b4fd49ace58876763903f43cf27b2275c10a needs to be undone.  See @joperezr's changes in release/2.1: https://github.com/dotnet/corefx/pull/27385.

**Pull request merged**
