### PR TITLE
Make System.Net.Sockets.Tests run in build

### PR DESCRIPTION
**Pull request by stephentoub**
Fixes https://github.com/dotnet/corefx/issues/12994

@weshaggard, is this the right fix?

### CODE REVIEW

**Comment by stephentoub** [comment]
@dotnet-bot Test Outerloop Windows_NT Debug please
@dotnet-bot Test Outerloop Ubuntu14.04 Debug please
@dotnet-bot Test Outerloop OSX Debug please

**Comment by stephentoub** [comment]
@dotnet-bot Test Outerloop Windows_NT Debug please
@dotnet-bot Test Outerloop Ubuntu14.04 Debug please
@dotnet-bot Test Outerloop OSX Debug please

**Comment by stephentoub** [comment]
@dotnet-bot Test Outerloop OSX Debug please (restore failures)

**Comment by weshaggard** [comment]
Yes this should enable the default configuration of running them for netcoreapp1.1.

**Pull request merged**
