### PR TITLE
Remove SystemDrawingSection typeforward from our System.Drawing.dll shim

### PR DESCRIPTION
**Pull request by joperezr**
cc: @joshfree @Petermarcu @weshaggard 

Removing SystemDrawingSection from ConfigurationManager's ref so that System.Drawing shim won't type forward to it.

### CODE REVIEW

**Comment by joperezr** [comment]
Adding no merge label for now because I want to locally make sure that the build of the ConfigurationManager package is not  broken by this. Once I confirm I will remove the label.

**Comment by danmosemsft** [comment]
Can we have an issue for this so we don't lose it.

**Comment by joperezr** [comment]
We are not sure yet if we want to check this in yet which is why I haven't removed the label for no merge. The Xaml Compiler team has a fix that will fix this issue properly but we wanted to keep this open just in case we wanted to merge it in eventually.

**Comment by karelz** [comment]
@joperezr what is the status of this PR? Do we have ETA / plan?
Maybe we should close it until we have more info?

**Comment by danmosemsft** [comment]
@joperezr if this is actually required for UWP6.0 it needs to happen today/tomorrow --- if not, please remove that tag...

**Comment by joperezr** [comment]
Sorry no, this was fixed on the Xaml compiler side so it's now ok to close this.

**Pull request closed without merging**
