### PR TITLE
Revert "Build Linq.Expression tests against live Regex"

### PR DESCRIPTION
**Pull request by ericstj**
This reverts commit 4f192affbc07a77e6660e75caeae5fba07a9cddf.

### CODE REVIEW

**Comment by ericstj** [comment]
Fixes #11916

**Comment by stephentoub** [comment]
@dotnet-bot Test Innerloop CentOS7.1 Release Build and Test please (seg fault)
@adityamandaleeka, FYI, another CentOS seg fault

**Comment by stephentoub** [comment]
@dotnet-bot Test Innerloop CentOS7.1 Release Build and Test please ("failed to mkdirs")
@mmitche, FYI.

**Comment by ericstj** [comment]
@dotnet-bot test Innerloop Ubuntu14.04 Release Build and Test

**Pull request merged**
