### PR TITLE
Remove finalizer race in a testcase.

### LINKED ISSUE #4688: regclass029.regclass029.Test.DynamicCSharpRunTest failed in CI
http://dotnet-ci.cloudapp.net/job/dotnet_corefx_windows_release_prtest/6449/console
```
Failed: the finalizer hasn't executed!
     ManagedTests.DynamicCSharp.Conformance.dynamic.context.indexer.regclass.regclass029.regclass029.Test.DynamicCSharpRunTest [FAIL]
        Assert.Equal() Failure
        Expected: 0
        Actual:   2
        Stack Trace:
           d:\j\workspace\dotnet_corefx_windows_release_prtest\src\System.Dynamic.Runtime\tests\Dynamic.Context\Conformance.dynamic.context.indexer.regclass.cs(2355,0): at ManagedTests.DynamicCSharp.Conformance.dynamic.context.indexer.regclass.regclass029.regclass029.Test.DynamicCSharpRunTest()
```

### PR DESCRIPTION
**Pull request by VSadov**
Fixes #4688

### CODE REVIEW

**Comment by stephentoub** [comment]
What is this test actually testing now?

**Comment by VSadov** [comment]
The test tests that dynamic works in a finalizer. 
If dynamic relies on something that is weak-referenced, I can see how it might break. In theory... 

It does look a bit odd.

**Comment by VSadov** [comment]
Actually, I am not sure how running in finalizer would be all that different even in the presence of weak references. Everything reachable should still be alive. The only subtlety is that any finalizable dependency could be found already finalized  (since order is not guaranteed) and it is unusual to have dependency on that.

I guess the test team just wanted to have one test - just in case.

**Comment by stephentoub** [comment]
Ok. :wink:

**Pull request merged**
