### PR TITLE
Do not use *.ni.dll on test.

### PR DESCRIPTION
**Pull request by lemmaa**
Add option `--ignore-native-dlls` to ignore `*.ni.dll`s when running tests.
(mscorlib.ni.dll, System.Private.CoreLib.ni.dll)

* Workaround for running CoreFX unit-test on Linux/ARM32 device.

### CODE REVIEW

**Comment by jkotas** [comment]
Would it work for you to set `export COMPlus_ZapDisable=1` and `export COMPlus_ReadyToRun=0` before running the tests on ARM instead? You can also use COMPlus_ReadyToRunExcludeList for more finer grained control as things become to work.

**Comment by lemmaa** [comment]
@jkotas, it looks not work for me.

This is my env setting.
```
sjlee@pi2:~/git/corefx$ env
TERM=xterm-256color
SHELL=/bin/bash
OLDPWD=/home/sjlee/git
PAL_DBG_CHANNELS=+all.all
                    .
                    .
                    .
SSH_TTY=/dev/pts/0
LC_ALL=en_US.UTF-8
USER=sjlee
MAIL=/var/mail/sjlee
PATH=/home/sjlee/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games
PWD=/home/sjlee/git/corefx
LANG=en_US.UTF-8
SHLVL=1
HOME=/home/sjlee
LANGUAGE=en_US.UTF=8
LOGNAME=sjlee
LC_CTYPE=en_US.UTF-8
LESSOPEN=| /usr/bin/lesspipe %s
COMPlus_ZapDisable=1
COMPlus_ReadyToRun=0
sjlee@pi2:~/git/corefx$ 
```
and this is execution log with `export PAL_DBG_CHANNELS=+all.all`
```
sjlee@pi2:~/git/corefx$ ./run-test.sh \
> --sequential \
> --coreclr-bins /home/sjlee/git/coreclr/bin/Product/Linux.arm.Debug \
> --mscorlib-bins /home/sjlee/git/coreclr/bin/Product/Linux.arm.Debug \
> --corefx-tests /home/sjlee/git/corefx/bin/tests \
> --corefx-native-bins /home/sjlee/git/corefx/bin/Linux.arm.Debug/Native \
> --corefx-packages /home/sjlee/git/corefx/packages

Running tests in /home/sjlee/git/corefx/bin/tests/AnyOS.AnyCPU.Debug/Microsoft.CSharp.Tests/netcoreapp1.0
./RunTests.sh /home/sjlee/git/corefx/packages

Using /home/sjlee/git/corefx/packages as folder for resolving package dependencies.
Executing in .
Executing in unpack directory, do not have to copy files
Hard linking dependent files...
./xunit.abstractions.dll already exists, not copying.
./xunit.assert.dll already exists, not copying.
                              .
                              .
                              .
./mscorlib.ni.dll already exists, not copying.
./sosdocsunix.txt already exists, not copying.
./System.Private.CoreLib.dll already exists, not copying.
./mscorlib.dll already exists, not copying.
./corerun already exists, not copying.
                              .
                              .
                              .
./System.Xml.ReaderWriter.dll already exists, not copying.
./System.Xml.XDocument.dll already exists, not copying.
./xunit.console.netcore.exe already exists, not copying.
Finished linking needed files, moving to running tests.
Running tests... Start time: 17:40:40
Commands:
./corerun xunit.console.netcore.exe Microsoft.CSharp.Tests.dll -xml testResults.xml -notrait Benchmark=true -notrait category=OuterLoop -notrait category=failing -notrait category=nonlinuxtests
{0x4581-0x76a8e5fd} ENTRY [CRITSEC] at /home/sjlee/git3/coreclr/src/pal/src/sync/cs.cpp.207: InitializeCriticalSection(lpCriticalSection=76CD2804)
{0x4581-0x76a8e5fd} EXIT  [CRITSEC] at /home/sjlee/git3/coreclr/src/pal/src/sync/cs.cpp.212: InitializeCriticalSection returns void
{0x4581-0x76a8e5fd} TRACE [SHMEM  ] at SHMInitialize.405: Now initializing global shared memory system
{0x4581-0x76a8e5fd} TRACE [SHMEM  ] at SHMInitialize.415: Mapped first SHM segment at 762B6000
{0x4581-0x76a8e5fd} TRACE [SHMEM  ] at SHMInitPool.1218: Initializing SHM pool for 16-byte blocks
{0x4581-0x76a8e5fd} TRACE [SHMEM  ] at SHMLinkPool.1268: Linking 4094 blocks of 16 bytes, starting at 
                              .
                              .
                              .
{0x4581-0x76a8e5fd} ENTRY [UNICODE] at /home/sjlee/git3/coreclr/src/pal/src/locale/unicode.cpp.686: MultiByteToWideChar(CodePage=65001, dwFlags=0, lpMultiByteStr=01ED0C6C (/home/sjlee/git3.js1/corefx/bin/tests/AnyOS.AnyCPU.Debug/Microsoft.CSharp.Tests/netcoreapp1.0/mscorlib.ni.dll:/home/sjlee/git3.js1/corefx/bin/tests/AnyOS.AnyCPU.Debug/Microsoft.CSharp.Tests/netcoreapp1.0/System.Private.CoreLib.ni.dll:/home/sjlee/git3.js1/corefx/bin/tests/AnyOS.AnyCPU.Debug/Microsoft), cbMultiByte=-1, lpWideCharStr=00000000, cchWideChar=0)
{0x4581-0x76a8e5fd} EXIT  [UNICODE] at /home/sjlee/git3/coreclr/src/pal/src/locale/unicode.cpp.779: MultiByteToWideChar returns 10294.
{0x4581-0x76a8e5fd} ENTRY [MEM    ] at /home/sjlee/git3/coreclr/src/pal/src/memory/heap.cpp.186: HeapAlloc (hHeap=01020304, dwFlags=0, numberOfBytes=20604)
{0x4581-0x76a8e5fd} EXIT  [MEM    ] at /home/sjlee/git3/coreclr/src/pal/src/memory/heap.cpp.234: HeapAlloc returning LPVOID 01ED4C58
{0x4581-0x76a8e5fd} ENTRY [UNICODE] at /home/sjlee/git3/coreclr/src/pal/src/locale/unicode.cpp.686: MultiByteToWideChar(CodePage=65001, dwFlags=0, lpMultiByteStr=01ED0C6C (/home/sjlee/git3.js1/corefx/bin/tests/AnyOS.AnyCPU.Debug/Microsoft.CSharp.Tests/netcoreapp1.0/mscorlib.ni.dll:/home/sjlee/git3.js1/corefx/bin/tests/AnyOS.AnyCPU.Debug/Microsoft.CSharp.Tests/netcoreapp1.0/System.Private.CoreLib.ni.dll:/home/sjlee/git3.js1/corefx/bin/tests/AnyOS.AnyCPU.Debug/Microsoft), cbMultiByte=-1, lpWideCharStr=01ED4C68, cchWideChar=10294)
                              .
                              .
                              .
{0x4581-0x76a8e5fd} ENTRY [MEM    ] at /home/sjlee/git3/coreclr/src/pal/src/memory/heap.cpp.260: HeapFree (hHeap=01020304, dwFlags = 0, lpMem=01EC9608)
{0x4581-0x76a8e5fd} EXIT  [MEM    ] at /home/sjlee/git3/coreclr/src/pal/src/memory/heap.cpp.297: HeapFree returning BOOL 1
coreclr_initialize failed - status: 0x80004005
{0x4581-0x76a8e5fd} ENTRY [MEM    ] at /home/sjlee/git3/coreclr/src/pal/src/memory/heap.cpp.260: HeapFree (hHeap=01020304, dwFlags = 0, lpMem=01EDD4F0)
{0x4581-0x76a8e5fd} EXIT  [MEM    ] at /home/sjlee/git3/coreclr/src/pal/src/memory/heap.cpp.297: HeapFree returning BOOL 1
Finished running tests. End time=17:40:42. Return value was 255
error: One or more tests failed while running tests from ''.  Exit code 255.

Running tests in /home/sjlee/git/corefx/bin/tests/AnyOS.AnyCPU.Debug/System.AppContext.Tests/netcoreapp1.0
./RunTests.sh /home/sjlee/git/corefx/packages
```
I can find several trace of `mscorlib.ni.dll` and `System.Private.CoreLib.ni.dll` in here.

**Comment by jkotas** [comment]
Where is the `System.Private.CoreLib.ni.dll` coming from - was it generated by ARM crossgen? I wound not expect it to be so badly broken that it does not work at all even with these env settings.

**Comment by lemmaa** [comment]
@jkotas, in my understanding, it comes from downloaded NuGet packages extracted in `corefx/packages` by RunTests.sh during preparing test. So, it depends on host architecture and may not compatible with target architecture when cross build. So I'm willing to exclude if from test environment. In contrast, `mscorlib.dll` and `System.Private.CoreLib.dll` coming from `corefx/bin/Products/Linux.arm.Debug` by https://github.com/dotnet/corefx/blob/master/run-test.sh#L128 before copying from packages.

As we can see in https://github.com/dotnet/coreclr/blob/master/build.sh#L302 , we cannot generate `*.ni.dll` under cross compilation, as of now.

**Comment by jkotas** [comment]
Would it make sense to fix the `copy_test_overlay` method to delete .ni.dll in testdir, if it was properly overwritten? Something like:

```
if [ -f $MscorlibBins/mscorlib.ni.dll ] 
then 
    ln -f $MscorlibBins/mscorlib.ni.dll $testDir/mscorlib.ni.dll
else
    rm -f $testDir/mscorlib.ni.dll
fi 
```

and same for System.Private.CoreLib.dll. It would make your current config just work, without any special command line switches.

**Comment by lemmaa** [comment]
@jkotas, you mean that we don't need to use `*.ni.dll` completely? Why we have to give up the chance of better performance for test running, if we can get it? Isn't it better to just workaround in cross compiling situation, with command line switch?

Anyway, we need to keep the following code also, to prevent `RunTests.sh` is copying `*.ni.dll`s again.
```
if [ ! -f RunTests.sh.save ]; then
    mv -f RunTests.sh RunTests.sh.save
fi
cp RunTests.sh.save RunTests.sh

for file in ${ignore_dlls[@]}; do
    sed "/$file/d" RunTests.sh > RunTests.out
    mv -f RunTests.out RunTests.sh
done
```
or modifying the where generating `RunTests.sh`.

**Comment by jkotas** [comment]
`System.Private.CoreLib.ni.dll` has to match coreclr.dll. If there is no `System.Private.CoreLib.ni.dll` available in the overlay coreclr build, `System.Private.CoreLib.ni.dll` restored from the nuget package should be always deleted - regardless of cross-compilation. Mixing and matching builds of coreclr.dll and `System.Private.CoreLib.ni.dll` tends to result into very hard to diagnose crashes.

**Comment by lemmaa** [comment]
I see, I misunderstood your comment before. I updated the PR, Please take a look! :)

**Comment by stephentoub** [comment]
@jkotas, should this be merged?

**Comment by jkotas** [comment]
The discussion was going in parallel in both the issue and the PR. My last comment was: https://github.com/dotnet/corefx/issues/9865#issuecomment-231278558

- The modification of the auto-generated script on the fly is not pretty. It would be better to generate the script in the right form in the first place.
- There is existing `/p:TestWithoutNativeImages=true` switch that does exactly that.

@lemmaa Did you have a chance to look into whether the existing TestWithoutNativeImages switch addresses the problem that you are trying to solve?

**Comment by lemmaa** [comment]
@jkotas Yes, it works well. I can get what I want just passing `/p:TestWithoutNativeImages=true` on the `./build.sh` command line as following. 

```
sjlee@js1-desktop:~/git/corefx$ ./build.sh clean verbose /p:TestWithoutNativeImages=true
```

With this option, the `RunTests.sh` script doesn't include any commend for copying `*.ni.dll`s from `--corefx-packages` to test directories.

We'd better to close this PR. Thank you! :)

**Comment by lemmaa** [comment]
@jkotas I figured out a problem. When I use `/p:TestWithoutNativeImages=true` option, it not only suppress using `mscorlib.ni.dll` and `System.Private.CoreLib.ni.dll` on test but also suppress building native dlls. Following list is part of diff before using `/p:TestWithoutNativeImages=true` and after. So, we need to apply this patch.
If you mind unconditional modify of `RunTest.sh`, I can update the patch with command line option.
````
sjlee@js1-desktop:~/git.release.pi2$ diff -r corefx-Linux.arm.Release-test{,-with-option}
Only in corefx-Linux.arm.Release-test/coreclr/bin/Product/Linux.arm.Release: hfa_nested_f32_native_cpp.so
Only in corefx-Linux.arm.Release-test/coreclr/bin/Product/Linux.arm.Release: hfa_nested_f64_native_cpp.so
Only in corefx-Linux.arm.Release-test/coreclr/bin/Product/Linux.arm.Release: hfa_simple_f32_native_cpp.so
Only in corefx-Linux.arm.Release-test/coreclr/bin/Product/Linux.arm.Release: hfa_simple_f64_native_cpp.so
Only in corefx-Linux.arm.Release-test/coreclr/bin/Product/Linux.arm.Release: jitstructtests_lib.so
Only in corefx-Linux.arm.Release-test/coreclr/bin/Product/Linux.arm.Release: libBestFitMappingNative.so
Only in corefx-Linux.arm.Release-test/coreclr/bin/Product/Linux.arm.Release: libBoolNative.so
Only in corefx-Linux.arm.Release-test/coreclr/bin/Product/Linux.arm.Release: libForeignThreadExceptionsNative.so
Only in corefx-Linux.arm.Release-test/coreclr/bin/Product/Linux.arm.Release: libFuncPtrAsDelegateParamNative.so
Only in corefx-Linux.arm.Release-test/coreclr/bin/Product/Linux.arm.Release: libFunctionPointerNative.so
Only in corefx-Linux.arm.Release-test/coreclr/bin/Product/Linux.arm.Release: libIUnknownNative.so
Only in corefx-Linux.arm.Release-test/coreclr/bin/Product/Linux.arm.Release: libLPSTRTestNative.so
Only in corefx-Linux.arm.Release-test/coreclr/bin/Product/Linux.arm.Release: libLPTSTRTestNative.so
Only in corefx-Linux.arm.Release-test/coreclr/bin/Product/Linux.arm.Release: libMarshalArrayByValNative.so
Only in corefx-Linux.arm.Release-test/coreclr/bin/Product/Linux.arm.Release: libMarshalBoolArrayNative.so
Only in corefx-Linux.arm.Release-test/coreclr/bin/Product/Linux.arm.Release: libMarshalEnumNative.so
Only in corefx-Linux.arm.Release-test/coreclr/bin/Product/Linux.arm.Release: libMarshalStructAsParam.so
Only in corefx-Linux.arm.Release-test/coreclr/bin/Product/Linux.arm.Release: libNativeCallableDll.so
Only in corefx-Linux.arm.Release-test/coreclr/bin/Product/Linux.arm.Release: libRefCharArrayNative.so
Only in corefx-Linux.arm.Release-test/coreclr/bin/Product/Linux.arm.Release: libRefIntNative.so
Only in corefx-Linux.arm.Release-test/coreclr/bin/Product/Linux.arm.Release: libSimpleStructNative.so
Only in corefx-Linux.arm.Release-test/coreclr/bin/Product/Linux.arm.Release: libSizeConstNative.so
Only in corefx-Linux.arm.Release-test/coreclr/bin/Product/Linux.arm.Release: libStructABILib.so
Only in corefx-Linux.arm.Release-test/coreclr/bin/Product/Linux.arm.Release: libUIntPtrNative.so
Only in corefx-Linux.arm.Release-test/coreclr/bin/Product/Linux.arm.Release: libUTF8TestNative.so
Only in corefx-Linux.arm.Release-test/coreclr/bin/Product/Linux.arm.Release: libVector3TestNative.so
Only in corefx-Linux.arm.Release-test/coreclr/bin/Product/Linux.arm.Release: mirror.so
Only in corefx-Linux.arm.Release-test/coreclr/bin/Product/Linux.arm.Release: native_i0c.so
Only in corefx-Linux.arm.Release-test/coreclr/bin/Product/Linux.arm.Release: native_i0s.so
Only in corefx-Linux.arm.Release-test/coreclr/bin/Product/Linux.arm.Release: native_i1c.so
Only in corefx-Linux.arm.Release-test/coreclr/bin/Product/Linux.arm.Release: native_i1s.so
Only in corefx-Linux.arm.Release-test/coreclr/bin/Product/Linux.arm.Release: native_i3c.so
Only in corefx-Linux.arm.Release-test/coreclr/bin/Product/Linux.arm.Release: native_i3s.so
Only in corefx-Linux.arm.Release-test/coreclr/bin/Product/Linux.arm.Release: native_i5c.so
Only in corefx-Linux.arm.Release-test/coreclr/bin/Product/Linux.arm.Release: native_i5s.so
Only in corefx-Linux.arm.Release-test/coreclr/bin/Product/Linux.arm.Release: native_i6c.so
Only in corefx-Linux.arm.Release-test/coreclr/bin/Product/Linux.arm.Release: native_i6s.so
Only in corefx-Linux.arm.Release-test/coreclr/bin/Product/Linux.arm.Release: native_i7c.so
Only in corefx-Linux.arm.Release-test/coreclr/bin/Product/Linux.arm.Release: native_i7s.so
Only in corefx-Linux.arm.Release-test/coreclr/bin/Product/Linux.arm.Release: native_i8c.so
Only in corefx-Linux.arm.Release-test/coreclr/bin/Product/Linux.arm.Release: native_i8s.so
Only in corefx-Linux.arm.Release-test/coreclr/bin/Product/Linux.arm.Release: test2.so
...
````

**Comment by jkotas** [comment]
Why does it suppress building native dlls? The only place where TestWithoutNativeImages kicks in is here: https://github.com/dotnet/buildtools/blob/a38bf8b5653b1d912224402561f2704dfcdd2768/src/Microsoft.DotNet.Build.Tasks/PackageFiles/tests.targets#L200 It has nothing to do with building native dlls.

**Comment by lemmaa** [comment]
It was my mistake which came from an error in my private test script. The command line option worked well. Thank you again @jkotas :)

**Pull request closed without merging**
