### PR TITLE
Specify corefx packages to convert when generating a project.json for test

### PR DESCRIPTION
**Pull request by chcosta**
Pass the Identity RegEx to "AddDependenciesToProjectJson" so that we are only affecting the versions of the corefx repo libraries when generating a new project.json.

Corresponds with this update to buildtools - https://github.com/dotnet/buildtools/commit/3021a305338633901c84ccc6a2e1709c217ef9db

/cc @jhendrixMSFT , @weshaggard

### CODE REVIEW

**Comment by jhendrixMSFT** [comment]
LGTM

**Comment by chcosta** [comment]
Thanks.  I'll squash and merge this as soon as it passes the CI.  @weshaggard , if you have additional feedback, I'll provide an additional update, but I need to merge this ASAP to unblock our build pipeline.

**Comment by chcosta** [comment]
Looks like CI failed due to https://github.com/dotnet/corefx/issues/7812

@dotnet-bot test Innerloop Windows_NT Debug Build and Test

**Comment by chcosta** [comment]
@dotnet-bot test Innerloop Windows_NT Debug Build and Test

**Comment by weshaggard** [comment]
LGTM

**Pull request merged**
