### PR TITLE
Run code coverage runs in release mode.

### LINKED ISSUE #7514: Consider running code coverage builds in Release mode
Currently code coverage runs (in the CI) run in debug mode by default. I propose considering changing the build to be a release build for the following reasons:
1. Some debug code will always be uncovered (e.g. numerous `internal void Dump()` methods in System.Net or System.Text.RegularExpressions)
2. Release mode tends to run quicker than debug (I don't have empirical evidence to prove this, and this is definitely a smaller reason than 1.)
3. Tests (typically) test code that the API consumer calls publically to a .dll file built in release mode. If any behaviour is considerably different in release mode then it may not be covered in debug CC runs. This could cause problems.
4. A more accurate coverage report

I'd be interested in hearing the arguments for keeping the CC runs in debug mode.

### PR DESCRIPTION
**Pull request by Priya91**
fixes #7514

cc @maririos @stephentoub

### CODE REVIEW

**Comment by Priya91** [comment]
@dotnet-bot test ci please

**Comment by maririos** [comment]
LGTM

**Comment by stephentoub** [comment]
Why do we believe Release is better for code coverage than Debug?

**Comment by Priya91** [comment]
@stephentoub #7514 issue description has the details..

**Comment by stephentoub** [comment]
@Priya91, I've read the issue and @hughbe's comments on why he things we should use Release.  Why do you think we should use Release?  There are counter-arguments to many of those points.  For example, if there's debug-only code that's never being hit, isn't that something interesting to understand?

**Comment by Priya91** [comment]
@stephentoub I concur with the reasons in the issue, based on the reasoning that we want to measure code coverage to put a numerical statistic on how much code is covered in testing, and the code paths that matter are the ones that get hit in release mode. Since we want to test the scenarios a client will use, and the code that is shipped is release, measuring release code coverage sounds sufficient to me.

**Comment by Priya91** [comment]
For ex, in ```System.Text.RegularExpressions``` there's a RegexOptions.Debug which is not exposed in public surface area. But it is there to help during debugging, it prints some diagnostics messages. Including this code path in code coverage is unnecessary, since this is not a test scenario.

**Comment by stephentoub** [comment]
> For ex

Counter example.  Throughout the dataflow library, there is debug-only code that verifies the correct locks are held or not held at various points in the code (these checks are too expensive to perform in release).  It's valuable to see these code paths being hit in testing... if they're not hit, that means we're missing out on critically important coverage.

**Comment by stephentoub** [comment]
@ellismg, @weshaggard, @mmitche, any opinions here?

**Comment by weshaggard** [comment]
On the one hand I agree that coverage is more interesting for release builds because that is what is actually shipping, but on the other hand I would imagine the code coverage reports would be less accurate in release due to optimizations that might fold code and so it looks like we have less coverage then we actually do. 

In the end code coverage itself is only one quality metric which doesn't really take all the inputs into consideration, only that some inputs cause some code blocks to execute. With that in mind I think I would lean towards having it cover all the source code we have and have the reports more closely match what we see in the source code and not having to worry about optimizations and reports potentially giving inaccurate results.

That is a long-winded vote for sticking with debug builds for coverage.

**Comment by mmitche** [comment]
What about looking at a combined report?  Debug + Release

**Comment by weshaggard** [comment]
How would you combine the reports? In either case combining reports means that we would need to do a debug and release coverage run which I'm not sure is worth the machine cost.

**Comment by stephentoub** [comment]
@Priya91, are you ok if we close this?  Or do you feel strongly about switching to release?

**Comment by Priya91** [comment]
> @Priya91, are you ok if we close this? Or do you feel strongly about switching to release?

I do think that getting release code coverage numbers will be more accurate to the final product than debug, but given the fact that the release codepaths do get covered in debug, we are not losing on essential coverage information with respect to the product that the customer's use. So debug is fine.

**Pull request closed without merging**
