### PR TITLE
Increase the System.ServiceProcess.ServiceController tests timeout

### PR DESCRIPTION
**Pull request by pallavit**
System.ServiceProcess.ServiceController tests currently waits for 3 seconds for the service to transition from one state to the other, which might not always be sufficient. Increasing the time a little to make it more resilient to a machine that is slow or working on other things in parallel.

Fixes Issue #6029

### CODE REVIEW

**Comment by pallavit** [comment]
cc /@bartonjs

**Comment by stephentoub** [comment]
LGTM.  Should we make it even longer?  In general if we expect it to succeed, then we can afford a long timeout.

**Comment by pallavit** [comment]
>  Should we make it even longer? In general if we expect it to succeed, then we can afford a long timeout.

We can. I just thought 5 seconds seems plenty, the service is really doing no-work per se and we are just trying to wait until it transitions. Umm.. I will make it 10 secs, I don't think we need to go beyond it :).

**Comment by bartonjs** [comment]
The particular test that I reported as timing out refused to do so when I was trying to collect timing data on it; but the passes all happened at around 1.5 seconds.  7 times the average seems like a pretty reasonable amount of flexibility to me :)  (10 second timeout)

LGTM, and proposed 10-second adjustment LGTM2.

**Comment by pallavit** [comment]
Thanks :)

**Pull request merged**
