### PR TITLE
[3.1] Test-only followup for "Fix Unix named mutex crash during some race conditions"

### PR DESCRIPTION
**Pull request by kouvel**
Test-only port of https://github.com/dotnet/runtime/pull/36268 to 3.1
Test-only followup for and depends on https://github.com/dotnet/coreclr/pull/28039

Closes https://github.com/dotnet/runtime/issues/34271

### CODE REVIEW

**Comment by kouvel** [comment]
Tests will likely fail until the dependency change flows into corefx, flagging as no-merge for now

**Comment by danmoseley** [comment]
Restarted CI

**Comment by danmoseley** [comment]
@kouvel Windows all passes, but there is a segfault in Linux and Mac on x64 only.

**Comment by kouvel** [comment]
https://github.com/dotnet/coreclr/pull/28039 would have to be merged and flow into the corefx repo before the tests would pass, seg fault is expected until then, but not guaranteed (so keeping it flagged so no-merge for now).

**Comment by danmoseley** [comment]
@kouvel - oh, my bad. I just assumed that was merged. Does it make sense to close both PR's, until and unless you plan to move them forward?

**Comment by kouvel** [comment]
The plan was to take it for 3.1, I don't think that has changed, but it's just waiting for an appropriate time, as it's not a critical one. I prefer to keep them open just so as not to lose track of the changes until it's decided that we don't want to take them for 3.1, though I don't feel strongly about issue closing / keeping-open either way.

**Comment by kouvel** [comment]
CC @jeffschwMSFT

**Comment by danmoseley** [comment]
Whatever works for you guys.

**Comment by kouvel** [comment]
Dependency PR has been closed for now

**Pull request closed without merging**
