### PR TITLE
*NOT TO MERGE* Just to force all tests w/ SocketsHttpHandler

### PR DESCRIPTION
**Pull request by pjanotti**
Just in case something else depends on Http handler, provides a baseline that @caesar1995 can use for #27821

### CODE REVIEW

**Comment by pjanotti** [comment]
Just in the unlikely case that it matters:
@dotnet-bot Test Outerloop Windows x64 Debug Build
@dotnet-bot test Outerloop macOS x64 Debug Build
@dotnet-bot Test Outerloop Linux x64 Release Build

**Comment by caesar1995** [comment]
@dotnet-bot Test Linux x64 Release Build

**Comment by caesar1995** [comment]
@dotnet-bot test Outerloop NETFX x64 Debug Build

**Comment by caesar1995** [comment]
@dotnet-bot test Linux x64 Release Build
@dotnet-bot test OSX x64 Debug Build
@dotnet-bot test Outerloop Linux x64 Release Build
@dotnet-bot test Outerloop Windows x64 Debug Build

**Comment by pjanotti** [comment]
Not needed anymore.

**Pull request closed without merging**
