### PR TITLE
Remove netstandard configs from more unit test projects

### PR DESCRIPTION
**Pull request by stephentoub**
These "UnitTests" test product internals by building in the product src, which means there's no benefit in running them on configurations other than netcoreapp, and because they build in product src, having a netstandard configuration limits the ability to use netcoreapp-only features in those source files.

### CODE REVIEW

**Comment by safern** [comment]
I know that @joperezr did an effort to have a Netstandard Test Suite being built, which means, those are the tests that a runtime claiming to support netstandard should pass: https://github.com/dotnet/corefx/pull/31850

I don't know if these tests should be part of it.

**Comment by stephentoub** [comment]
> I don't know if these tests should be part of it.

They should not.  These tests are not about public surface area; they're testing internals by including the actual product source files and calling into internal methods.

**Comment by safern** [comment]
> They should not. These tests are not about public surface area; they're testing internals by including the actual product source files and calling into internal methods.

Sounds good. Just making sure, thanks for clarifying 😄

**Comment by danmosemsft** [comment]
Which reminds me @joperezr we should start the conversation again with @mareksafar about using your netstandard test bed now we have it.

**Pull request merged**
