### PR TITLE
Fix Linux / Mac build

### LINKED ISSUE #6760: Fork project.jsons for windows-only dependencies
@Priya91 pointed out some restore errors to me on Ubuntu that seem to be because of auto-RID:

http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/outerloop_ubuntu14.04_debug/23/consoleText

	EXEC : error : Microsoft.Win32.Registry 4.0.0-rc3-23908 provides a compile-time reference assembly for Microsoft.Win32.Registry on DNXCore,Version=v5.0, but there is no run-time assembly compatible with ubuntu.14.04-x64. [/mnt/j/workspace/dotnet_corefx/outerloop_ubuntu14.04_debug/build.proj]
	EXEC : error : Some packages are not compatible with DNXCore,Version=v5.0 (ubuntu.14.04-x64). [/mnt/j/workspace/dotnet_corefx/outerloop_ubuntu14.04_debug/build.proj]
	EXEC : error : System.Security.AccessControl 4.0.0-rc3-23908 provides a compile-time reference assembly for System.Security.AccessControl on DNXCore,Version=v5.0, but there is no run-time assembly compatible with ubuntu.14.04-x64. [/mnt/j/workspace/dotnet_corefx/outerloop_ubuntu14.04_debug/build.proj]
	EXEC : error : Some packages are not compatible with DNXCore,Version=v5.0 (ubuntu.14.04-x64). [/mnt/j/workspace/dotnet_corefx/outerloop_ubuntu14.04_debug/build.proj]
	EXEC : error : System.Threading.Overlapped 4.0.1-rc3-23908 provides a compile-time reference assembly for System.Threading.Overlapped on DNXCore,Version=v5.0, but there is no run-time assembly compatible with ubuntu.14.04-x64. [/mnt/j/workspace/dotnet_corefx/outerloop_ubuntu14.04_debug/build.proj]
	EXEC : error : Some packages are not compatible with DNXCore,Version=v5.0 (ubuntu.14.04-x64). [/mnt/j/workspace/dotnet_corefx/outerloop_ubuntu14.04_debug/build.proj]
	...

It looks like these stopped working after upgrading from `23829` because no `dnxcore50` implementation is provided anymore.

It seems to me that the right temporary fix is to fork any `project.json` using these dependencies. I can do this if it sounds right. I'm not sure how to see which configurations a project uses a dependency in except by compiling it.

The long-term fix is to take up a version of CLI/nuget that got rid of auto-RID. (We can get rid of our RID-specific forks then too.)

@ericstj Thoughts? Should this be happening?

/cc @weshaggard

### PR DESCRIPTION
**Pull request by ericstj**
Recent changes broke the build for max/linux.

Packages were made windows specific and some windows projects which happen to build on mac/linux were failing restore.

Once past that we found a recent build tools update regressed the compiler and caused it to fail silently.

Fixes #6760

### CODE REVIEW

**Comment by ericstj** [comment]
Feel free to merge this if it completes validation.  I know folks are blocked on this and I will be away from my PC for the next couple hours.

**Comment by dagood** [comment]
Errors look like they're from https://github.com/ericstj/corefx/blob/windowsSpecificProjects/src/System.IO.FileSystem/src/System.IO.FileSystem.csproj not having the `win\project.json` fork redirect. (Like https://github.com/dotnet/corefx/pull/6784/files#diff-21bfe1d5b2665a042fe4703783fb4850R18)

**Comment by dagood** [comment]
I'll base a new PR off this one with that fix.

**Comment by ericstj** [comment]
Your update missed the netcore50 project.json.  I fixed up my original change.

**Comment by dagood** [comment]
Awesome, thanks for getting to the bottom of this.

**Pull request merged**
