### PR TITLE
Avoid a closure/delegate allocation in WinHttpHandler

### PR DESCRIPTION
**Pull request by stephentoub**
One-line change to avoid a closure and delegate allocation on each call.

### CODE REVIEW

**Comment by stephentoub** [comment]
cc: @davidsh, @CIPop, @SidharthNabar

**Comment by davidsh** [comment]
LGTM

**Comment by davidsh** [comment]
@dotnet-bot test this please

**Comment by stephentoub** [comment]
Thanks, David.

**Pull request merged**
