### PR TITLE
Consume MSBuild Mono package

### PR DESCRIPTION
**Pull request by JeremyKuhne**
Add the Mono MSBuild package and update the build script to consume it and restore tools via xbuild.

@weshaggard, @akoeplinger, @valmenn, @ellismg, @joshfree

### CODE REVIEW

**Comment by weshaggard** [comment]
LGTM

**Comment by ellismg** [comment]
Is there a way we could not have the xbuild dependency?

**Comment by ellismg** [comment]
(e.g, why can we not just download the .nupkg ourselves with curl and unzip it?  That seems like less work than requiring all of xbuild?)

**Comment by JeremyKuhne** [comment]
@ellismg We could, but we already require mono/xbuild and that isn't likely to go away any time soon (MSBuild requires it). I considered scripting out the tool restore here, but went with expedient for right now.

**Comment by ellismg** [comment]
Okay.  Can you help me understand why we require xbuild now aside from this (I understand if you want to build msbuild from scratch you need it, but with this change you shouldn't have to build it from scratch anymore, right?)

**Comment by akoeplinger** [comment]
@ellismg I had the same thoughts. Instead of unzipping we should rather just fetch nuget.exe and use it to install msbuild via `nuget install`. We could do it on Windows as well and get rid of the DownloadFile inline task.

@JeremyKuhne I don't see why we would need xbuild with this change, the pcl reference assemblies can be installed without pulling in xbuild afaik.

**Comment by JeremyKuhne** [comment]
@akoeplinger @ellismg I would rather just use the script to pull, this was a fast first step. I have about 10 minutes worth of experience in writing bash scripts. :) If we didn't already have xbuild in place from our existing dependencies I wouldn't have used it.

**Comment by akoeplinger** [comment]
Yeah, makes sense. LGTM.

**Comment by ellismg** [comment]
LGTM.  Thanks!

**Comment by JeremyKuhne** [comment]
@dotnet-bot test this please

**Pull request merged**
