### PR TITLE
Update test namespaces in System.Net.Requests

### PR DESCRIPTION
**Pull request by Clockwork-Muse**
Update test namespaces in System.Net.Requests per #2898. 
Clean up `using`s.

### CODE REVIEW

**Comment by davidsh** [comment]
cc: @CIPop @stephentoub 

@Clockwork-Muse 

The previous namespace as listed in the files as `System.Net.Requests.Test'.  The new one you are proposing is `System.Net.Tests`.  That is not the correct one to use.

The namespaces used for the Tests in System.Net.* libraries follow the same guidline. It should be suffixed with ".Tests" or ".Unit.Tests" or ".Functional.Tests" if there are are multiple test projects.

So, this particular change should be to name the test namespaces are "System.Net.Requests.Tests".

**Comment by davidsh** [comment]
Now, I realize that the actual classes in this library are NOT under the System.Net.Requests namespace.  That namespace doesn't really exist in terms of class objects such the classes are from the System.Net namespace.

But in terms of how we group the tests and source code by "library package", we prefer to keep the namespaces of these things aligning with the library name (i.e. System.Net.Requests).  It will also keep things organized in terms of how they show up the TestResults.xml output from Jenkins, etc.

**Comment by akoeplinger** [comment]
@davidsh 
> But in terms of how we group the tests and source code by "library package", we prefer to keep the namespaces of these things aligning with the library name (i.e. System.Net.Requests).

That's contrary to what was decided in https://github.com/dotnet/corefx/issues/2898 though.

**Comment by davidsh** [comment]
I might have missed that nuance when #2898 was being discussed.

Because now that means that the test assembly binary would be named something like System.Net.Requests.Tests.dll and yet the namespaces used in the test methods would be System.Net.Tests according to what you propose.

We definitely want to keep the test assembly binary with the same common prefix name as the package itself.  So, the package binary is System.Net.Requests.dll and the test binaries would be System.Net.Requests.Tests.dll or possibly System.Net.Requests.Unit.Tests.dll or System.Net.Requests.Functional.Tests.dll.

So, am I correct in assuming that the only discussion point in the namespaces used for the test classes and methods in the test sources?

**Comment by akoeplinger** [comment]
> Because now that means that the test assembly binary would be named something like System.Net.Requests.Tests.dll and yet the namespaces used in the test methods would be System.Net.Tests according to what you propose.

Yes, same as for the actual types which often don't reside in a namespace that matches the binary  name, so no difference there :smile: 

/cc @nguerrera @weshaggard @mellinoe who were in favor of `$(Namespace of Type under Test).Tests` in #2898

**Comment by davidsh** [comment]
@akoeplinger Ok.  I understand now what was actually agreed to before in #2898.  

So, I'm ok with your change. Don't worry about updating other libraries such as System.Net.Http or System.Net.Http.WinHttpHandler because I am in the process of making changes there.  So, I'll make sure to re-align with this #2898 guidance.

**Comment by davidsh** [comment]
LGTM once the build goes GREEN.

**Comment by stephentoub** [comment]
@dotnet-bot test this please

**Comment by stephentoub** [comment]
@dotnet-bot test this please (BeginReceiveFromV4BoundToAnyV6_Success failed due to operation timeout)

**Pull request merged**
