### PR TITLE
System.Data.Common.Tests down to 1 failure on ILC

### PR DESCRIPTION
**Pull request by AtsushiKan**
Divering more BinaryFormatter tests to our Aot-trapped
helper.

More rd.xml magic.

### CODE REVIEW

**Comment by AtsushiKan** [comment]
@dotnet-bot Innerloop netfx Windows_NT Debug x86 Build and Test

Err.. why are there "Known Races" in InnerLoop?

**Comment by AtsushiKan** [comment]
@dotnet-bot test Innerloop netfx Windows_NT Debug x86 Build and Test

**Comment by AtsushiKan** [comment]
@dotnet-bot test Innerloop Tizen armel Debug Cross Build

**Comment by stephentoub** [comment]
> Err.. why are there "Known Races" in InnerLoop?

When you hit an issue, please note it so we can try to fix it.

**Pull request merged**
