### PR TITLE
Unix: Remove MaxPath, MaxName

### PR DESCRIPTION
**Pull request by tmds**
PATH_MAX is not an upper bound on path lengths on Unix. system function return
values should be used to determine behavior, instead of limiting the path length.

MaxName is not used. When used, it should take into account the file system at
that path.

### CODE REVIEW

**Comment by tmds** [comment]
This has a corresponding coreclr PR: https://github.com/dotnet/coreclr/pull/15229

CC @stephentoub

**Comment by tmds** [comment]
In this PR some functions are removed that are used by coreclr.
https://github.com/dotnet/coreclr/pull/15229 updates coreclr for this.

Since coreclr doesn't contain those changes yet, the CI builds are failing.
```
2017-11-27 10:21:25,441: INFO: proc(54): run_and_log_output: Output: Unhandled Exception: System.EntryPointNotFoundException: Unable to find an entry point named 'SystemNative_GetMaximumPath' in DLL 'System.Native'.
2017-11-27 10:21:25,442: INFO: proc(54): run_and_log_output: Output:    at Interop.Sys.GetMaximumPath()
2017-11-27 10:21:25,442: INFO: proc(54): run_and_log_output: Output:    at Interop.Sys.get_MaxPath() in /Users/buildagent/agent/_work/147/s/src/mscorlib/shared/Interop/Unix/System.Native/Interop.PathConf.cs:line 42
2017-11-27 10:21:25,442: INFO: proc(54): run_and_log_output: Output:    at System.TimeZoneInfo.FindTimeZoneIdUsingReadLink(String tzFilePath) in /Users/buildagent/agent/_work/147/s/src/mscorlib/src/System/TimeZoneInfo.Unix.cs:line 384
2017-11-27 10:21:25,442: INFO: proc(54): run_and_log_output: Output:    at System.TimeZoneInfo.TryLoadTzFile(String tzFilePath, Byte[]& rawData, String& id) in /Users/buildagent/agent/_work/147/s/src/mscorlib/src/System/TimeZoneInfo.Unix.cs:line 355
2017-11-27 10:21:25,442: INFO: proc(54): run_and_log_output: Output:    at System.TimeZoneInfo.TryGetLocalTzFile(Byte[]& rawData, String& id) in /Users/buildagent/agent/_work/147/s/src/mscorlib/src/System/TimeZoneInfo.Unix.cs:line 312
2017-11-27 10:21:25,443: INFO: proc(54): run_and_log_output: Output:    at System.TimeZoneInfo.GetLocalTimeZoneFromTzFile() in /Users/buildagent/agent/_work/147/s/src/mscorlib/src/System/TimeZoneInfo.Unix.cs:line 499
2017-11-27 10:21:25,443: INFO: proc(54): run_and_log_output: Output:    at System.TimeZoneInfo.CachedData.CreateLocal() in /Users/buildagent/agent/_work/147/s/src/mscorlib/src/System/TimeZoneInfo.cs:line 74
2017-11-27 10:21:25,443: INFO: proc(54): run_and_log_output: Output:    at System.DateTime.get_Now() in /Users/buildagent/agent/_work/147/s/src/mscorlib/shared/System/DateTime.cs:line 1005
```

**Comment by joperezr** [comment]
I think @JeremyKuhne is probably the right person to take a look at this.

**Comment by JeremyKuhne** [comment]
I've commented on the CoreCLR matching change dotnet/coreclr#15229. Once we resolve the discussion there I'll follow up here.

**Comment by stephentoub** [comment]
@dotnet-bot test this please

**Comment by tmds** [comment]
@dotnet-bot test Linux x64 Release Build please
@dotnet-bot test OSX x64 Debug Build please

**Comment by stephentoub** [comment]
@tmds, can you fix up the conflicts here?

**Pull request merged**
