### PR TITLE
Fix native-build command parsing and push it to log file in build.cmd

### PR DESCRIPTION
**Pull request by weshaggard**
@stephentoub @ianhays 

This should fix the outerloop build errors see:
http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/outerloop_win10_debug/52/console

### CODE REVIEW

**Comment by weshaggard** [comment]
@dotnet-bot test outerloop

**Comment by stephentoub** [comment]
Thanks for the fix, Wes. If it all builds successfully, LGTM.

**Comment by weshaggard** [comment]
PR https://github.com/dotnet/corefx/pull/5278 should fix these failures. Once that gets verified and merged I will re-test this.

**Comment by weshaggard** [comment]
@dotnet-bot test this please

**Comment by weshaggard** [comment]
@dotnet-bot test outerloop

**Comment by weshaggard** [comment]
@dotnet-bot test this please

**Comment by weshaggard** [comment]
@dotnet-bot test outerloop

**Comment by stephentoub** [comment]
@dotnet-bot test outerloop

**Comment by weshaggard** [comment]
The last two failures aren't related to this change so I'm going to merge this. 

Restore failure http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/outerloop_windows_nt_release_prtest/9/
Race condition https://github.com/dotnet/corefx/issues/5236 http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/outerloop_win10_release_prtest/7/

**Pull request merged**
