### PR TITLE
Fix MemberData in System.Collections.

### PR DESCRIPTION
**Pull request by ianhays**
Some of the files in System.Collections don't use nameof for their memberdata declaration.

@stephentoub

### CODE REVIEW

**Comment by stephentoub** [comment]
LGTM.  Thanks for cleaning these up.

**Comment by JonHanna** [comment]
:ship:

**Comment by JonHanna** [comment]
Test this please.

**Comment by JonHanna** [comment]
@dotnet-bot test this, please.

**Comment by stephentoub** [comment]
@dotnet-bot test this please

**Comment by stephentoub** [comment]
@dotnet-bot test this please

**Pull request merged**
