### PR TITLE
Fix run-test.sh

### PR DESCRIPTION
**Pull request by hseok-oh**
This makes run-test.sh work in x64/linux.
Remove useless argument and add --runtime argument to pass runtime directory

Not works for cross compile yet (ex. build in x64 & run in arm)

### CODE REVIEW

**Comment by hseok-oh** [comment]
The best solution is to use build-test.sh, but we need run-test.sh for arm build yet.
To use in arm build, we need to modify RunTests.sh in each test directory to use corerun instead of dotnet manually.

**Comment by stephentoub** [comment]
@dotnet-bot test this please (Jenkins was down)

**Comment by weshaggard** [comment]
@hseok-oh we have issue https://github.com/dotnet/corefx/issues/15814 tracking to fix run-tests scripts to try and add a "run" mode to build-tests to help eliminate this duplication of work.

cc @danmosemsft

**Comment by danmosemsft** [comment]
Looks good, thanks.

**Pull request merged**
