### PR TITLE
Make ordering of modifiers more consistent across corefx

### PR DESCRIPTION
**Pull request by stephentoub**
"public static" instead of "static public", "static readonly" instead of "readonly static", etc. Just search and replaces.

cc: @danmosemsft, @justinvp

### CODE REVIEW

**Comment by danmosemsft** [comment]
Would it make sense to improve the code fornatter?

**Comment by stephentoub** [comment]
> Would it make sense to improve the code fornatter?

Yes

**Comment by stephentoub** [comment]
@mmitche, @bartonjs, @adityamandaleeka, the Ubuntu leg failed for reasons unrelated to this PR, a seg fault in the X509Certificates tests: https://ci.dot.net/job/dotnet_corefx/job/master/job/ubuntu14.04_release_prtest/1251/consoleText
I've seen a few more such seg faults in the X509Certificates tests recently.  Is this a known issue?

**Comment by bartonjs** [comment]
` GDB was not found. Unable to print core file.` It's hard to say if this is the same intermittent segfault that I was unable to track down for 1.0 or a new one.

If the frequency has changed that sort of suggests that there's a new one.

But (again) it would be good if the coredump capture/processing was reliable.

**Comment by danmosemsft** [comment]
@schaabs @sepidehms to comment on dump capture

**Pull request merged**
