### PR TITLE
Fix regression in TCPClient behavior when Disposed/Client set to null

### PR DESCRIPTION
**Pull request by tmds**
Regressed by #37462
Fixes https://github.com/dotnet/corefx/issues/40765

CC @stephentoub

### CODE REVIEW

**Comment by tmds** [comment]
@stephentoub can you trigger an outerloop CI run?

**Comment by ViktorHofer** [comment]
We want to port this into the release/3.0 branch as well, assuming the fix is ready. This needs to happen today to meet the deadline.

**Comment by stephentoub** [comment]
> We want to port this into the release/3.0 branch as well, assuming the fix is ready

@ViktorHofer, I don't understand.  The thing this is fixing isn't in release/3.0.

**Comment by ViktorHofer** [comment]
Sorry ignore my comment. I only looked at the date of the PR but not when it was merged.

**Comment by ViktorHofer** [comment]
I'm surprised that the outerloop legs are now all green besides one mysterious crash (looking at the dump right now): https://helix.dot.net/api/2019-06-17/jobs/651df83f-3a34-48d7-9c0d-f5b66ed72d5e/workitems/System.Net.Http.Functional.Tests/files/console.9517de06.log

**Comment by stephentoub** [comment]
Thanks.

**Pull request merged**
