### PR TITLE
release/2.0: Fix lifetime handling of ReceiveMessageFromAsync buffer on Windows

### PR DESCRIPTION
**Pull request by stephentoub**
Port #22012 to release/2.0 branch
Fixes https://github.com/dotnet/corefx/issues/21995

### CODE REVIEW

**Comment by stephentoub** [comment]
@dotnet-bot test OuterLoop netcoreapp PortableLinux Debug x64 please
@dotnet-bot test OuterLoop OSX10.12 Debug x64 Build and Test please
@dotnet-bot test OuterLoop Windows_NT Debug x86 Build and Test please

**Comment by stephentoub** [comment]
@dotnet-bot help

**Comment by stephentoub** [comment]
@dotnet-bot test outerloop netcoreapp OSX10.12 Debug
@dotnet-bot test outerloop netcoreapp Windows_NT Debug

**Comment by geoffkizer** [comment]
LGTM

**Comment by stephentoub** [comment]
@dotnet-bot test outerloop netcoreapp OSX10.12 Debug
@dotnet-bot test outerloop netcoreapp Windows_NT Debug
@dotnet-bot test OuterLoop netcoreapp PortableLinux Debug x64 please

**Pull request merged**
