### PR TITLE
release/2.0: Fix handling of empty inputs to TakeLast (#24328)

### LINKED ISSUE #24327: TakeLast on empty list throws InvalidOperationException (Empty Queue)
**Repro steps**

```csharp
var x = new List<string>();
var y = x.TakeLast(100);
Console.WriteLine("Any()=" + y.Any());
````
**Expected Result**
The same as the `Take()`, i.e, the Any() returns false

**Actual Result**
An exception is thrown

```
Unhandled Exception: System.InvalidOperationException: Queue empty.
   at System.Collections.Generic.Queue`1.ThrowForEmptyQueue()
   at System.Collections.Generic.Queue`1.Dequeue()
   at System.Linq.Enumerable.<TakeLastIterator>d__208`1.MoveNext()
   at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source)
```

### PR DESCRIPTION
**Pull request by stephentoub**
Fixes #24327
Port https://github.com/dotnet/corefx/pull/24328 to release/2.0.0 branch.

### CODE REVIEW

**Comment by stephentoub** [comment]
There are a bunch of unrelated build errors with the Tizen build:
```
mscorlib.forwards.cs(9,73): error CS0122: 'CultureAwareComparer' is inaccessible due to its protection level [/opt/corefx/src/shims/manual/mscorlib.csproj]
mscorlib.forwards.cs(10,73): error CS0122: 'OrdinalComparer' is inaccessible due to its protection level [/opt/corefx/src/shims/manual/mscorlib.csproj]
mscorlib.forwards.cs(11,73): error CS0122: 'OrdinalIgnoreCaseComparer' is inaccessible due to its protection level [/opt/corefx/src/shims/manual/mscorlib.csproj]
mscorlib.forwards.cs(12,93): error CS0122: 'GenericComparer<T>' is inaccessible due to its protection level [/opt/corefx/src/shims/manual/mscorlib.csproj]
mscorlib.forwards.cs(13,93): error CS0122: 'NullableComparer<T>' is inaccessible due to its protection level [/opt/corefx/src/shims/manual/mscorlib.csproj]
mscorlib.forwards.cs(14,93): error CS0122: 'ObjectComparer<T>' is inaccessible due to its protection level [/opt/corefx/src/shims/manual/mscorlib.csproj]
mscorlib.forwards.cs(15,93): error CS0122: 'Int32EnumComparer<T>' is inaccessible due to its protection level [/opt/corefx/src/shims/manual/mscorlib.csproj]
mscorlib.forwards.cs(16,93): error CS0122: 'UInt32EnumComparer<T>' is inaccessible due to its protection level [/opt/corefx/src/shims/manual/mscorlib.csproj]
mscorlib.forwards.cs(17,93): error CS0122: 'Int64EnumComparer<T>' is inaccessible due to its protection level [/opt/corefx/src/shims/manual/mscorlib.csproj]
mscorlib.forwards.cs(18,93): error CS0122: 'UInt64EnumComparer<T>' is inaccessible due to its protection level [/opt/corefx/src/shims/manual/mscorlib.csproj]
mscorlib.forwards.cs(19,93): error CS0122: 'GenericEqualityComparer<T>' is inaccessible due to its protection level [/opt/corefx/src/shims/manual/mscorlib.csproj]
mscorlib.forwards.cs(20,93): error CS0122: 'NullableEqualityComparer<T>' is inaccessible due to its protection level [/opt/corefx/src/shims/manual/mscorlib.csproj]
mscorlib.forwards.cs(21,93): error CS0122: 'ObjectEqualityComparer<T>' is inaccessible due to its protection level [/opt/corefx/src/shims/manual/mscorlib.csproj]
mscorlib.forwards.cs(22,93): error CS0122: 'NonRandomizedStringEqualityComparer' is inaccessible due to its protection level [/opt/corefx/src/shims/manual/mscorlib.csproj]
mscorlib.forwards.cs(23,93): error CS0122: 'ByteEqualityComparer' is inaccessible due to its protection level [/opt/corefx/src/shims/manual/mscorlib.csproj]
mscorlib.forwards.cs(24,93): error CS0122: 'EnumEqualityComparer<T>' is inaccessible due to its protection level [/opt/corefx/src/shims/manual/mscorlib.csproj]
mscorlib.forwards.cs(25,93): error CS0122: 'SByteEnumEqualityComparer<T>' is inaccessible due to its protection level [/opt/corefx/src/shims/manual/mscorlib.csproj]
mscorlib.forwards.cs(26,93): error CS0122: 'ShortEnumEqualityComparer<T>' is inaccessible due to its protection level [/opt/corefx/src/shims/manual/mscorlib.csproj]
mscorlib.forwards.cs(27,93): error CS0122: 'LongEnumEqualityComparer<T>' is inaccessible due to its protection level [/opt/corefx/src/shims/manual/mscorlib.csproj]
mscorlib.forwards.cs(28,85): error CS0122: 'ListDictionaryInternal' is inaccessible due to its protection level [/opt/corefx/src/shims/manual/mscorlib.csproj]
mscorlib.forwards.cs(30,73): error CS0234: The type or namespace name 'UnitySerializationHolder' does not exist in the namespace 'System' (are you missing an assembly reference?) [/opt/corefx/src/shims/manual/mscorlib.csproj]
```
@dotnet-bot test Innerloop Tizen armel Debug Cross Build please
@dotnet-bot test Innerloop Tizen armel Release Cross Build please

**Comment by stephentoub** [comment]
@hseok-oh, @parjong, @hqueue , any idea what's going wrong with the Tizen builds here in the release/2.0 branch as well?

**Comment by danmosemsft** [comment]
From the log it is getting coreclr 2.0.2-servicing-25712-01 from 9/12 whereas it should be 2.0.2-servicing-25730-01 or nearly? Not sure how that corresponds to the errors though.

**Comment by hqueue** [comment]
It's interesting that Ubuntu 14.04 arm is also restoring `2.0.2-servicing-25712-01` now but no error observed.
https://ci.dot.net/job/dotnet_corefx/job/release_2.0.0/job/ubuntu14.04_arm_cross_release_prtest/619/console

```
00:03:49.687   /opt/corefx/packages/runtime.linux-x64.microsoft.netcore.runtime.coreclr/2.0.2-servicing-25712-01/runtimes/linux-x64/native/System.Globalization.Native.so (runtime.linux-x64.Microsoft.NETCore.Runtime.CoreCLR.2.0.2-servicing-25712-01) -> /opt/corefx/Tools/ilasm/System.Globalization.Native.so
```

I have no idea by now.

**Comment by stephentoub** [comment]
PR https://github.com/dotnet/corefx/pull/24270 from @MattGal was merged with the same Tizen failures.

**Comment by stephentoub** [comment]
Since it's an issue with the branch rather than with this specific PR, I'm going to merge it.

**Pull request merged**
