### PR TITLE
System.ComponentModel: Cache TypeConverter results

### LINKED ISSUE #5337: TypeConverter lookup does uncached reflection on CoreCLR
We're making fairly frequent use of `TypeConverter` in ASP.NET MVC. Traditionally, it's been a point of extensibility in our system for enabling serialization of your types to and from strings in query string and form data. We also rely on the built in converters for commonly used built-in types like `DateTime`.

On CoreCLR the lookup of a `TypeConverter` is doing a bunch of attribute work up and down the inheritance hierarchy before falling back to a lookup table. On Desktop CLR this is cached in the common case. 

The performance effect on MVC of all of this attribute lookup is quite large. This is sampling data from an app doing model binding on 3 fields and then displaying them in an HTML form. Two of these fields use `TypeConverter` as shown here in the profile. Percentages here reflect % of CPU time inside of routing/MVC:
image

**Is this something we could work to address inside CoreFx?**

**Or should we implement our own cache?**

This is caching we've never had a need to do on Desktop.

### PR DESCRIPTION
**Pull request by ianhays**
Uses the IntrinsicTypes table and performs a check for existing entries in that table before doing anything else. Also adds performance tests for GetConverter.

Works for types that declare a Converter through an attribute as well as built-in types.

resolves #5337

@Tanya-Solyanik

### CODE REVIEW

**Comment by ianhays** [comment]
Perf results for these changes (cached) vs. master (no caching):

|                                    TypeToConvert | Expected Converter Type                           | No Caching | cached   | cached / nocache |
|-------------------------------------------------:|---------------------------------------------------|------------|----------|------------------|
| bool                                             | System.ComponentModel.BooleanConverter            | 1.192578   | 0.028501 | 2.39%            |
| System.ComponentModel.Tests.IDerived             | System.ComponentModel.Tests.IBaseConverter        | 1.246748   | 0.027931 | 2.24%            |
| System.ComponentModel.Tests.IBase                | System.ComponentModel.Tests.IBaseConverter        | 1.106477   | 0.027931 | 2.52%            |
| System.ComponentModel.Tests.DerivedClass         | System.ComponentModel.Tests.DerivedClassConverter | 0.845892   | 0.027931 | 3.30%            |
| System.ComponentModel.Tests.BaseClass            | System.ComponentModel.Tests.BaseClassConverter    | 1.030354   | 0.029642 | 2.88%            |
| System.ComponentModel.Tests.ClassWithNoConverter | System.ComponentModel.TypeConverter               | 0.133419   | 0.027931 | 20.93%           |
| int?                                             | System.ComponentModel.NullableConverter           | 2.073832   | 0.750383 | 36.18%           |
| System.ComponentModel.Tests.SomeValueType?       | System.ComponentModel.NullableConverter           | 1.015814   | 0.747817 | 73.62%           |
| System.ComponentModel.Tests.SomeEnum             | System.ComponentModel.EnumConverter               | 1.256726   | 1.302343 | 103.63%          |
| System.Enum                                      | System.ComponentModel.EnumConverter               | 1.137838   | 0.112037 | 9.85%            |
| System.Collections.ICollection                   | System.ComponentModel.CollectionConverter         | 0.457582   | 0.027931 | 6.10%            |
| System.Array                                     | System.ComponentModel.ArrayConverter              | 1.149242   | 0.028216 | 2.46%            |
| System.Guid                                      | System.ComponentModel.GuidConverter               | 1.158366   | 0.028786 | 2.49%            |
| System.TimeSpan                                  | System.ComponentModel.TimeSpanConverter           | 1.142115   | 0.027646 | 2.42%            |
| decimal                                          | System.ComponentModel.DecimalConverter            | 1.408116   | 0.027646 | 1.96%            |
| System.ComponentModel.Tests.ClassIBase           | System.ComponentModel.Tests.IBaseConverter        | 1.237909   | 0.027931 | 2.26%            |
| System.DateTimeOffset                            | System.ComponentModel.DateTimeOffsetConverter     | 1.107332   | 0.028216 | 2.55%            |
| System.Void                                      | System.ComponentModel.TypeConverter               | 0.428786   | 0.027931 | 6.51%            |
| object                                           | System.ComponentModel.TypeConverter               | 0.327004   | 0.030212 | 9.24%            |
| ulong                                            | System.ComponentModel.UInt64Converter             | 1.388729   | 0.028216 | 2.03%            |
| uint                                             | System.ComponentModel.UInt32Converter             | 1.39101    | 0.029071 | 2.09%            |
| ushort                                           | System.ComponentModel.UInt16Converter             | 1.426933   | 0.027361 | 1.92%            |
| float                                            | System.ComponentModel.SingleConverter             | 1.418665   | 0.027931 | 1.97%            |
| long                                             | System.ComponentModel.Int64Converter              | 1.354517   | 0.027076 | 2.00%            |
| int                                              | System.ComponentModel.Int32Converter              | 1.340547   | 0.027931 | 2.08%            |
| short                                            | System.ComponentModel.Int16Converter              | 1.357083   | 0.028501 | 2.10%            |
| string                                           | System.ComponentModel.StringConverter             | 1.430069   | 0.029071 | 2.03%            |
| double                                           | System.ComponentModel.DoubleConverter             | 1.358508   | 0.027646 | 2.04%            |
| char                                             | System.ComponentModel.CharConverter               | 1.163212   | 0.027931 | 2.40%            |
| sbyte                                            | System.ComponentModel.SByteConverter              | 1.400418   | 0.027931 | 1.99%            |
| byte                                             | System.ComponentModel.ByteConverter               | 1.346819   | 0.027931 | 2.07%            |
| System.DateTime                                  | System.ComponentModel.DateTimeConverter           | 1.328572   | 0.027931 | 2.10%            |
| System.ComponentModel.Tests.ClassIDerived        | System.ComponentModel.Tests.IBaseConverter        | 1.343683   | 0.028501 | 2.12%            |

**Comment by ianhays** [comment]
@stephentoub Tanya mentioned that this could be troublesome if there were a method of adding attributes to types during runtime. I'm not aware of there being anything like that in CoreFX, though I'm not sure. If there was, then there could be a situation where we cache the TypeConverter and then it is changed through a modification of the attribute on the type.

**Comment by stephentoub** [comment]
> this could be troublesome if there were a method of adding attributes to types during runtime

@jkotas, does ref emit provide such facilities?

**Comment by jkotas** [comment]
I am not aware of any.

**Comment by Tanya-Solyanik** [comment]
LGTM

**Pull request merged**
