### PR TITLE
[release/2.2] Pass CancellationToken to Stream in ManagedWebSocket

### PR DESCRIPTION
**Pull request by stephentoub**
Port https://github.com/dotnet/corefx/pull/33196 to release/2.2.

### CODE REVIEW

**Comment by stephentoub** [comment]
@dotnet-bot test Linux x64 Release Build please
@dotnet-bot test Tizen armel Debug Build please
@dotnet-bot test Windows x64 Debug Build please

**Comment by stephentoub** [comment]
@dotnet-bot test Tizen armel Debug Build please
@dotnet-bot test Windows x64 Debug Build please

**Comment by danmosemsft** [comment]
Tizen is known broken.
Windows 7 seems to be broken. Since this is OK in master I think it's OK to merge.

**Comment by danmosemsft** [comment]
Merged by conversation with @Eilon

**Comment by danmosemsft** [comment]
@dotnet/dnceng do you know why Windows 7 isn't working here? There is no log at all. Did the queue change?

**Comment by MattGal** [comment]
@danmosemsft this was me doing that intentionally.  Last week the Windows 7 machines died horrifically and I fixed this up on monday.  Since work items were ~37K behind I deadlettered some to catch up quickly.

https://github.com/dotnet/core-eng/issues/4551

I will make a note to give a static log for dead-lettered work items, it should be a cheap fix.

**Pull request merged**
