### PR TITLE
Optimize string-like portable Span APIs for Ordinal and OrdinalIgnoreCase

### PR DESCRIPTION
**Pull request by AlexRadch**
See https://github.com/dotnet/corefx/issues/27379

### CODE REVIEW

**Comment by AlexRadch** [comment]
1. Should I add optimizations for OrdinalIgnoreCase? I think it require to write many code.
2. Should I add optimizations for ToUpper and ToLower? I think it require to write many code too.

**Comment by ahsonkhan** [comment]
> 1. Should I add optimizations for OrdinalIgnoreCase? I think it require to write many code.

The intent of the issue was to include optimizations for OrdinalIgnoreCase for all the string-like methods. If you would like to take that on, that would be awesome, but you don't have to do it in this PR. Otherwise, let me know and I will mark it back as up-for-grabs for now. Thanks for the contribution.

> 2. Should I add optimizations for ToUpper and ToLower? I think it require to write many code too.

No, you don't need to do anything for ToUpper/ToLower since it only takes in a culture (and not stringcomparison). Things like OrdinalIgnoreCase do not make sense here.

**Comment by ahsonkhan** [comment]
cc @tarekgh, @stephentoub

**Comment by stephentoub** [comment]
Thanks.

**Comment by ahsonkhan** [comment]
Regarding switching over to SequenceCompareTo (for T = char), we do not have an optimized version of that method (that is vectorized) similar to the version for T = byte.

We would need to make a change similar to the one here - https://github.com/dotnet/corefx/pull/27859/ first before we switch to use that method.

cc @AtsushiKan, @jkotas

See SequenceCompareTo (for byte): https://github.com/dotnet/corefx/blob/992a9607ad6d942e34d34d060c01073002f547ed/src/Common/src/CoreLib/System/SpanHelpers.Byte.cs#L970

Versus, the one for T:
https://github.com/dotnet/corefx/blob/992a9607ad6d942e34d34d060c01073002f547ed/src/Common/src/CoreLib/System/SpanHelpers.T.cs#L667

I think there might be perf regression if we do this before changing the implementation of the helper.

**Comment by stephentoub** [comment]
I spoke with Ahson offline.  We're going to revert this for now, as it does demonstrate a perf regression at larger string lengths.

**Comment by AlexRadch** [comment]
@ahsonkhan
> No, you don't need to do anything for ToUpper/ToLower since it only takes in a culture (and not string comparison). Things like OrdinalIgnoreCase do not make sense here.

I think that OrdinalIgnoreCase comparison and equality are depends on culture also? I think it is like makes ToLower and then make Ordinal comparison or equality.

**Comment by tarekgh** [comment]
> I think that OrdinalIgnoreCase comparison and equality are depends on culture also?

No. ordinal operations, in general, don't depend on the cultures.

**Pull request merged**
