### PR TITLE
Fix visibility of several test methods

### PR DESCRIPTION
**Pull request by stephentoub**

### CODE REVIEW

**Comment by stephentoub** [comment]
@dotnet/dnceng, it appears there's a problem again with the Ubuntu.1604.Arm64.Open-arm64:Release queue?
e.g. https://mc.dot.net/#/user/dotnet-bot/pr~2Fdotnet~2Fcorefx~2Frefs~2Fpull~2F36380~2Fmerge/test~2Ffunctional~2Fcli~2F/20190326.35/workItem/Common.Tests/wilogs
```
If you’re reading this, that means the Helix work item you’re trying to find the logs for has dead-lettered.  

What this means: 

- All possible attempts to retry execution of this work item were unable to complete.  This can be both for infrastructure reasons (problems within Azure) or issues with the work item (for instance, causing a machine to reboot unexpectedly will force a retry).
- No further work will be done for this specific work item, and its exit code is set to an artificial -1 (since it did not complete, there is no real exit code).

Common causes:

- Disabled queue (end-of-life Helix queues are automatically forwarded to deadletter and will fail instantly)
- Unhealthy Helix Client machine(s)
- Azure issues (e.g. Service Bus is overloaded)

For follow up:

- Check if your Helix Queue is still enabled, either via the metadata you see by browsing to https://helix.dot.net/api/2018-03-14/info/queues or recent emails from the .NET Engineering Infrastructure team.
- Check that all work item payloads are accessible using a browser.
- If you are sending to a non-disabled queue and find this error repeatedly occurring, please contact the dnceng team.
- If a single, specific work item dead letters and others do not, consider local debugging; it may be causing spontaneous reboot (or trigging one intentionally.
```

**Comment by MattGal** [comment]
Hi @stephentoub .  I've tried very hard to make the deadletter message useful, but since there can be more than one explanation I get it can be vague.  In this case, it's the first issue in the list, specifically `Disabled queue (end-of-life Helix queues are automatically forwarded to deadletter and will fail instantly)`.  The impending end of the queue `Ubuntu.1604.Arm64.Open` was communicated to the .NET Partners alias at Wednesday, March 13, 2019 5:32 PM.

All you need to do in this case is to merge master into your branch, as I believe @wfurt has already taken care of this for you via https://github.com/dotnet/corefx/blob/d44c43b64de0f942c81fea7a535bf8bade508db0/eng/pipelines/linux.yml#L96 .

I'd also recommend removing Fedora.27.Amd64.* while you're at it, as that is the next up for EOL'ing (and has been EOL for some time)

**Comment by wfurt** [comment]
yes, fixes are in master: 
https://mc.dot.net/#/product/netcore/30/source/official~2Fdotnet~2Fcorefx~2Frefs~2Fheads~2Fmaster/type/test~2Ffunctional~2Fcli~2F/build/20190326.9

Either ignore the failure @stephentoub or pull from master.

**Comment by stephentoub** [comment]
Thanks, @MattGal  and @wfurt.

**Pull request merged**
