### PR TITLE
Expose Resolving event off AssemblyLoadContext

### PR DESCRIPTION
**Pull request by gkhanna79**
Fixes https://github.com/dotnet/coreclr/issues/2095

@weshaggard @terrajobst @jkotas PTAL

CC @davidfowl

### CODE REVIEW

**Comment by gkhanna79** [comment]
@terrajobst @weshaggard I would like to get this resolved this week. What should be the next steps?

**Comment by weshaggard** [comment]
I share @jkotas feedback from the PR review in the implementation, which is we shouldn't use the same type names as desktop here unless they exactly match.

**Comment by mikedn** [comment]
Since the signature of the new delegate type doesn't follow the event handler conventions is there even a need for a new delegate type? `Func<AssemblyName, Assembly>` anyone?

**Comment by gkhanna79** [comment]
> Since the signature of the new delegate type doesn't follow the event handler conventions is there even a need for a new delegate type?

@mike Events can be declared in different ways - this is one of them and also used in other places (see AppDomain.cs for examples).

**Comment by KrzysztofCwalina** [comment]
For context, these are the event design guidelines, and they do allow not using EventArgs: https://msdn.microsoft.com/en-us/library/ms229011(v=vs.110).aspx

**Comment by mikedn** [comment]
It was never clear to me if those guidelines prevent using a delegate type such `Func`.

**Comment by KrzysztofCwalina** [comment]
Well, now that I reread the guidelines, I would say this API does not follow them strictly speaking. There is a section about custom event handlers and it requires two parameters one sender and the other subclass of EventArgs.

Having said that, I think this is a bug in the guidelines. At one point we added the "consider deriving from EventArgs" rule to the non-custom handler section, but I think the intention was to allow it in all handler cases. 

But, I don't think we ever intentionally allowed not having the sender, and/or naming the delegate with other suffix then "Handler".

But the guidelines are so old and optimized for drag-drop GUI designers that I would be totally open to discuss how we modernize them. Though I am not sure if it's even worth spending time on it.

**Comment by mikedn** [comment]
> But the guidelines are so old and optimized for drag-drop GUI designers that I would be totally open to discussing how we modernize them. Though I am not sure if it's even worth spending time on it.

My main concern is delegate type proliferation. This happened in .NET 1.0 due to lack of generics. When we got generics in 2.0 it happened again (`Comparison<T>`, `Predicate<T>` etc.). Now we have general purpose delegate types such as Func but somehow new delegate types are still being introduced. If this is done to follow existing rules then let's say ok, the rules are there for a reason. But this event breaks the rules in every possible way (the main issue is not the missing `EventArgs` param but the non void return type) and yet still introduces a new delegate type.

**Comment by terrajobst** [comment]
@mikedn 

> My main concern is delegate type proliferation. This happened in .NET 1.0 due to lack of generics. 

For obvious signatures I think we should prefer `Func` and `Action`. However, keep in mind that using those means that you can't name parameters or document them. Also, depending on how many generics are involved, they can get quickly quite unwieldy. For instance, Roslyn has an API that takes `Func<SyntaxNode, SyntaxNode, bool, SyntaxNode>`. Unless you invented the API there is very limited chance you understand what the parameters mean. So I'd say it's a case by case thing.

In this instance, I believe a `Func<AssemblyName, Assembly> ` is quite intuitive and I'm fine with not declaring a specific delegate type.

@KrzysztofCwalina, thoughts?

**Comment by KrzysztofCwalina** [comment]
I would prefer that we write up what we imagine the new guidance would be and run it through the regular guidelines update process. 
While we are waiting for the guidelines update, I am ok with Func, but we should finish the guidance deliberations soon.

**Comment by terrajobst** [comment]
So it seems we'd prefer this API shape:

```C#
namespace System.Runtime.Loader
{
    public abstract class AssemblyLoadContext
    {
        public event Func<AssemblyLoadContext, AssemblyName, Assembly> Resolving;
    }
}
```

**Comment by gkhanna79** [comment]
@terrajobst @KrzysztofCwalina PTAL  at the update post the suggested change.

**Comment by KrzysztofCwalina** [comment]
looks good to me.

**Comment by terrajobst** [comment]
Same here.

**Comment by weshaggard** [comment]
LGTM

**Comment by weshaggard** [comment]
@dotnet-bot test this please

**Comment by gkhanna79** [comment]
@weshaggard These will fail since I have not yet merged CoreCLR side of changes as they were pending validation post API review change.

**Comment by gkhanna79** [comment]
@dotnet-bot test this please

**Pull request merged**
