### PR TITLE
Set S.R.Metadata RTM to 1.2.1 for RTM and internalize v1.3 surface

### LINKED ISSUE #8771: Downgrade S.R.Metadata to v1.2.1 and internalize public surface for NET Core 1.0.0 RTM
The changes under development for S.R.Metadata 1.3 are aligned to the VS "15" schedule and there are insufficient resources to lock them down now. We should set the .NET Core 1.0.0 RTM version of System.Reflection.Metadata to 1.2.1 and internalize the features under development for 1.3. We still need a new 1.2.1 package to support the new netstandard scheme for packages.

cc @ericstj @tmat I have the change ready. Creating a tracking issue to follow the v1.0.0 change process.

### PR DESCRIPTION
**Pull request by nguerrera**
Fix #8771

### CODE REVIEW

**Comment by nguerrera** [comment]
@tmat @ericstj

**Comment by tmat** [comment]
:+1:

**Comment by ericstj** [comment]
LGTM.

**Comment by weshaggard** [comment]
LGTM

I assume you diffed the new library against the old one to make sure the public surface area aligns correct.

**Comment by nguerrera** [comment]
@weshaggard 
> I assume you diffed the new library against the old one to make sure the public surface area aligns correct

Yes.

**Pull request merged**
