### PR TITLE
Enabling Diagnostic performance runs.

### PR DESCRIPTION
**Pull request by jorive**
Now, there are two types of runs:
- Profile: Standard run running under Etw collection of Clr events, timing, and 'allocated bytes in the current thread'
- Diagnostic: Everything collected in the Profile runs plus Pmc events {branch mispredictions, cache misses, instructions retired} and process call.

### CODE REVIEW

**Comment by jorive** [comment]
@dotnet/rap-team PTAL

**Comment by jorive** [comment]
@brianrob @danmosemsft @DrewScoggins Should we run: {Profile + Diagnostic} types of runs on merge commits, and {Diagnostic} on PR?

**Comment by jorive** [comment]
@dotnet-bot test ci please

**Comment by danmosemsft** [comment]
Is this unrelated to the regular perf runs that occur on official builds and get logged onto benchview? This relates to CI?

**Comment by danmosemsft** [comment]
As discussed offline, it seems to make sense to only have diagnostic runs for private requests (on PR's) and both for official runs (so we can still compare old data). 

Signing off, but I'm guessing that means changing what you have here.

**Comment by jorive** [comment]
@dotnet-bot test ci please

**Comment by jorive** [comment]
@DrewScoggins I just realized this changes will build the tests twice when ideally we would only like to re-render the `RunTest.[cmd|sh]` scripts and execute them, which would keep perf run TP smaller than rebuilding all over again.

**Pull request merged**
