### PR TITLE
[release/2.1] Fix Expect: 100-continue handling when no request content (#30102)

### LINKED ISSUE #30038: ExpectContinue causes breaking behaviour in responseStream.Read
Since 2.1.300, setting `ExpectContinue` to `true` will cause `Read` operations on the response stream to block for a long period rather than immediately returning 0 at the end of stream content.

Reproduction:

```csharp
using System;
using System.IO;
using System.Net;
using System.Net.Http;

namespace http_response_read_test
{
    class Program
    {
        private const int buffer_size = 2048;

        static void Main(string[] args)
        {
            var client = new HttpClient();

            client.DefaultRequestHeaders.ExpectContinue = true;

            var response = client.SendAsync(new HttpRequestMessage(HttpMethod.Get, "https://httpbin.org/get")).Result;
            var buffer = new byte[buffer_size];

            using (var responseStream = response.Content.ReadAsStreamAsync().Result)
            {
                int read;
                while ((read = responseStream.Read(buffer, 0, buffer_size)) > 0)
                {
                    // consume buffer
                }
            }
            
            System.Console.WriteLine("finished");
        }
    }
}
```

Running this code under `netcoreapp2.0` and `net471` will exit immediately after the response is read, while running under `netcoreapp2.1` will block for a very long time before eventually exiting (takes around a minute).

Commenting out the `ExpectContinue` line will cause all three runtimes to match in behaviour.

### PR DESCRIPTION
**Pull request by stephentoub**
Port #30102 to release/2.1
Fixes #30038

### CODE REVIEW

**Comment by stephentoub** [comment]
cc: @jeffschwMSFT, FYI an exception from the linker:
https://ci3.dot.net/job/dotnet_corefx/job/release_2.1/job/linux-musl-TGroup_netcoreapp+CGroup_Debug+AGroup_x64+TestOuter_false_prtest/81/
```
Fatal error in IL Linker
System.InvalidOperationException: Operation is not valid due to the current state of the object.
   at Mono.Collections.Generic.Collection`1.Enumerator.CheckState()
   at Mono.Collections.Generic.Collection`1.Enumerator.MoveNext()
   at Mono.Linker.TypeReferenceExtensions.GetMethods(TypeReference type)+MoveNext()
   at Mono.Linker.Steps.TypeMapStep.TryMatchMethod(TypeReference type, MethodDefinition method)
   at Mono.Linker.Steps.TypeMapStep.MapInterfaceMethodsInTypeHierarchy(TypeDefinition type)
   at Mono.Linker.Steps.TypeMapStep.MapType(TypeDefinition type)
   at Mono.Linker.Steps.TypeMapStep.ProcessAssembly(AssemblyDefinition assembly)
   at Mono.Linker.Steps.BaseStep.Process(LinkContext context)
   at Mono.Linker.Pipeline.Process(LinkContext context)
   at Mono.Linker.Driver.Run(ILogger customLogger)
   at Mono.Linker.Driver.Execute(String[] args, ILogger customLogger)
```

@dotnet-bot test Linux-musl x64 Debug Build please

**Comment by stephentoub** [comment]
@dotnet/dnceng, can you help me understand why the Linux leg is shown as failing?  MC shows that Ubuntu failed:
https://mc.dot.net/#/user/stephentoub/pr~2Fjenkins~2Fdotnet~2Fcorefx~2Frelease~2F2.1~2F/test~2Ffunctional~2Fcli~2F/d0f90a3acdb7bbb92995e3bf79ac4c82311cdd1b/workItem/System.IO.FileSystem.Tests/wilogs
but then looking at the log included, it looks successful:
```
2018-06-03 13:50:32,725: INFO: proc(54): run_and_log_output: Output: === TEST EXECUTION SUMMARY ===
2018-06-03 13:50:32,737: INFO: proc(54): run_and_log_output: Output:    System.IO.FileSystem.Tests  Total: 4006, Errors: 0, Failed: 0, Skipped: 0, Time: 53.549s
2018-06-03 13:50:32,820: INFO: proc(54): run_and_log_output: Output: ~/dotnetbuild/work/c98a1ea2-2806-45f7-929f-d99c167df47d/Work/ab987b77-87ab-4b0f-be48-59a4a113142c/Unzip
2018-06-03 13:50:32,821: INFO: proc(54): run_and_log_output: Output: ----- end 13:50:32 ----- exit code 0 ----------------------------------------------------------
2018-06-03 13:50:32,821: INFO: proc(54): run_and_log_output: Output: exit code 0 means Exited Successfully
2018-06-03 13:50:32,823: INFO: proc(58): run_and_log_output: Exit Code: 0
2018-06-03 13:50:32,823: INFO: scriptrunner(60): _main: Uploading results from /home/helixbot/dotnetbuild/work/c98a1ea2-2806-45f7-929f-d99c167df47d/Work/ab987b77-87ab-4b0f-be48-59a4a113142c/Unzip/testResults.xml
2018-06-03 13:50:32,824: INFO: azure_storage(205): _upload: Uploading single blob: 'testResults.xml'
```
What happened here?

**Comment by jeffschwMSFT** [comment]
@sbomer

**Comment by Chrisboh** [comment]
It appears that the TestResult.xml didn't complete uploading before hitting the work item timeout. You can see what the status of Helix was in the run_client.py log.

` 2018-06-03 14:09:09,734: INFO: servicebusrepository(99): renew_workitem_lock: renew_workitem_lock Status Code: 200
2018-06-03 14:09:36,512: ERROR: job(44): kill: Job running for too long. Killing...
2018-06-03 14:09:36,519: ERROR: executor(403): _execute_command: Executor timed out after 1200 seconds and was killed.
2018-06-03 14:09:36,520: INFO: event(43): send: Sending event type WorkItemTimeout
2018-06-03 14:09:36,776: INFO: saferequests(90): request_with_retry: Response complete with status code '201'
2018-06-03 14:09:36,777: INFO: executor(422): _execute_command: Finished _execute_command, exit code: -3`

I filed https://github.com/dotnet/core-eng/issues/3605 to see if there was anything else going on besides network.

**Comment by stephentoub** [comment]
Thanks, @MattGal and @Chrisboh.

@dotnet-bot test Linux x64 Release Build please

**Comment by MattGal** [comment]
@stephentoub it's clear from the outer log:

```
2018-06-03 14:09:09,734: INFO: servicebusrepository(99): renew_workitem_lock: renew_workitem_lock Status Code: 200
2018-06-03 14:09:36,512: ERROR: job(44): kill: Job running for too long. Killing...
2018-06-03 14:09:36,519: ERROR: executor(403): _execute_command: Executor timed out after 1200 seconds and was killed.
2018-06-03 14:09:36,520: INFO: event(43): send: Sending event type WorkItemTimeout
2018-06-03 14:09:36,776: INFO: saferequests(90): request_with_retry: Response complete with status code '201'
2018-06-03 14:09:36,777: INFO: executor(422): _execute_command: Finished _execute_command, exit code: -3
``` 
... it would appear that a request made when writing to the storage account never got a server response and waited forever until it was killed.

I recently learned that we were using the python "Requests" library wrong; it should only take a few minutes to fix this up, I filed https://github.com/dotnet/core-eng/issues/3606 to track it and may just do it later in the day if someone else doesn't.

**Comment by sbomer** [comment]
@dotnet-bot test Linux-musl x64 Debug Build please

**Comment by stephentoub** [comment]
@dotnet-bot test Linux x64 Release Build please
@dotnet-bot test OSX x64 Debug Build please

@dotnet/dnceng FYI:
https://ci3.dot.net/job/dotnet_corefx/job/release_2.1/job/osx-TGroup_netcoreapp+CGroup_Debug+AGroup_x64+TestOuter_false_prtest/260/consoleText
https://ci3.dot.net/job/dotnet_corefx/job/release_2.1/job/linux-TGroup_netcoreapp+CGroup_Release+AGroup_x64+TestOuter_false_prtest/249/consoleText
```
Failed obtain Helix work item information:
[Pipeline] echo
java.lang.NullPointerException
```

**Pull request merged**
