### PR TITLE
Update Host to 2.0.0-preview2-002093-00

### PR DESCRIPTION
**Pull request by ramarag**
Lighting up the changes from https://github.com/dotnet/core-setup/issues/2176

### CODE REVIEW

**Comment by danmosemsft** [comment]
@gkhanna79 why doesnt this happen automatically? Does this mean that unless we manually update, corefx is not consuming the version that will ship?

**Comment by gkhanna79** [comment]
@weshaggard should chime in on the process of updating this as this is a dependency that CoreFX test infrastructure.

**Comment by weshaggard** [comment]
We don't currently have auto-PRs setup for changes coming from core-setup. This is the only dependency which doesn't change much. We could add it but I'm not sure it is worth it and I don't really like a continuous update cycle between corefx and core-setup (although we already do that between corefx and coreclr :().

**Comment by danmosemsft** [comment]
cc@ViktorHofer 

This test is breaking as expected and now needs updating...

```
     System.ConfigurationTests.UrlPathTests.GetDirectoryOrRootName_GettingDirectoryFromAFilePath [FAIL]
12:01:04         Assert.Equal() Failure
12:01:04                                          ↓ (pos 143)
12:01:04         Expected: ···urationManager.Tests/netstandar
12:01:04         Actual:   ···urationManager.Tests
12:01:04                                          ↑ (pos 143)**
```

We ought to add a test specifically checking AppDomain.CurrentDomain.BaseDirectory, it's just good luck that @dhoehna added a test for configuration manager that discovered this.

**Comment by danmosemsft** [comment]
cc @ViktorHofer

**Comment by dhoehna** [comment]
@danmosemsft But is the unit test correct?  I'm guessing it is since the PR was accepted.

**Comment by danmosemsft** [comment]
@dhoehna you validated the product behaved reasonably, however it wasn't the same when we ran against desktop product, demonstrating that we had broken compatibility. We fixed that so now we will chase your test expectations. Glad you had added it!

**Comment by ViktorHofer** [comment]
I think the new behavior still isn't the desired one: https://github.com/dotnet/core-setup/issues/2176#issuecomment-298925771

**Comment by ramarag** [comment]
closing this as the previous behavior was the desired one

**Pull request closed without merging**
