### PR TITLE
Handle `UnparseableExtension` status code when building X509Chain on OSX

### PR DESCRIPTION
**Pull request by buyaa-n**
Fixes: https://github.com/dotnet/corefx/issues/39988

### CODE REVIEW

**Comment by danmosemsft** [comment]
@buyaa-n if @krwq indicates this is not the corerct long term fix then we need an issue opened to track that.

**Comment by krwq** [comment]
I've talked with @buyaa-n offline and we will do correct fix here. She will update her PR shortly

**Comment by krwq** [comment]
@buyaa-n is there an issue for the remaining 5.0 work?

**Comment by buyaa-n** [comment]
https://github.com/dotnet/corefx/issues/40116

**Pull request merged**
