### PR TITLE
Reverts Cancellation on SslStream

### PR DESCRIPTION
**Pull request by Drawaes**
Checking that this now passes the outerloop

### CODE REVIEW

**Comment by Drawaes** [comment]
@dotnet-bot test Outerloop Linux x64 Debug Build please
@dotnet-bot test Outerloop Linux x64 Release Build please

**Comment by Drawaes** [comment]
ref #25199

**Comment by Drawaes** [comment]
@dotnet-bot test Linux arm Release Build please

**Comment by Drawaes** [comment]
/cc @stephentoub 

Okay so this has 1 socket failure on Suse for 
Socket_StaticConnectAsync_HostNotFound

Which is unrelated, but it confirms that reverting the cancellation puts SslStream back into a functioning state. I would say it should be put back to here and cancellation can be looked at again.

#25198 Shows a no-op PR that has the failures


Ubuntu 14.04 seems to be non responsive for whatever reason, maybe they are all in use?

**Comment by Drawaes** [comment]
Outerloop Linux x64 Release Build — Build finished. 

That outerloop finished fine, with 100% pass rate.

**Comment by Drawaes** [comment]
@dotnet-bot test Outerloop Linux x64 Debug Build please

**Comment by benaadams** [comment]
Failure is `SendAsync_ExpectedDiagnosticCancelledActivityLogging`
```
at System.Diagnostics.RemoteExecutorTestBase.RemoteInvokeHandle.Dispose() in /mnt/j/workspace/dotnet_corefx/master/linux-TGroup_netcoreapp+CGroup_Debug+AGroup_x64+TestOuter_true_prtest/src/CoreFx.Private.TestUtilities/src/System/Diagnostics/RemoteExecutorTestBase.cs:line 205
at System.Net.Http.Functional.Tests.DiagnosticsTest.SendAsync_ExpectedDiagnosticCancelledActivityLogging() in /mnt/j/workspace/dotnet_corefx/master/linux-TGroup_netcoreapp+CGroup_Debug+AGroup_x64+TestOuter_true_prtest/src/System.Net.Http/tests/FunctionalTests/DiagnosticsTests.cs:line 589
```
Assume unrelated..?

/cc @stephentoub

**Comment by stephentoub** [comment]
Thanks for investigating.  Reverting in https://github.com/dotnet/corefx/pull/25203.

**Pull request closed without merging**
