### PR TITLE
Make well-known IPv4 addresses readonly

### LINKED ISSUE #33373: IPAddress static fields are readonly, but their values aren't
`IPAddress` static fields for `Any`, `Broadcast`, `Local` and `None` are marked `readonly`

https://github.com/dotnet/corefx/blob/b0b1452eaaa120dc8267ebbe5a93798f77ec5ed1/src/System.Net.Primitives/src/System/Net/IPAddress.cs#L20-L23

Because of that, one could take for granted that they would **always** correspond to respectively `0.0.0.0`, `255.255.255.255`, `127.0.0.1` and `255.255.255.255`.

The thing is, it is possible to change their values through the obsoleted `IPAddress.Address` property such as in

```csharp
using System;
using System.Net;

class Program
{
    static void Main()
    {
        Console.WriteLine("Well known IP addresses");

        Write("Any", IPAddress.Any);
        Write("Broadcast", IPAddress.Broadcast);
        Write("Loopback", IPAddress.Loopback);
        Write("None", IPAddress.None);

        Console.WriteLine();

        IPAddress.Any.Address = uint.MaxValue;
        IPAddress.Broadcast.Address = 0;
        IPAddress.Loopback.Address = IPAddress.Any.Address;


        Console.WriteLine("Well known IP addresses. Or are they?");

        Write("Any", IPAddress.Any);
        Write("Broadcast", IPAddress.Broadcast);
        Write("Loopback", IPAddress.Loopback);
        Write("None", IPAddress.None);

        Console.ReadKey();

        void Write(string name, IPAddress address)
        {
            Console.WriteLine($"{name}\t{address}");
        }
    }
}
```

Output:
```
Well known IP addresses
Any     0.0.0.0
Broadcast       255.255.255.255
Loopback        127.0.0.1
None    255.255.255.255

Well known IP addresses. Or are they?
Any     255.255.255.255
Broadcast       0.0.0.0
Loopback        255.255.255.255
None    0.0.0.0
```

Although unexpected, it's quite easy to spot what is being done in the sample code above. But given the scope of static members, a troubleshooter may spend a couple of hours before realizing that any piece of code running in the process (or the AppDomain in case of the .NET Framework), including external dependencies (which would have generated warnings during compilation for members or types marked with `[ObsoleteAttribute]`) could have changed the values of those fields.

The property has been obsoleted since .NET Framework 1.1 but is still lingering around and has been brought into .NET Core in 2.0 and into the .NET Standard 2.0 as well.

Given the pervasive use of these fields inside the .NET Core, it would be prudent to put safeguards in place to minimize the chance that their values are changed.

### PR DESCRIPTION
**Pull request by alfredmyers**
@karelz : Proposal to fix #33373 

Pending:
- When set on a read-only IPAddress, should Address throw InvalidOperationException or another exception (perhaps ArgumentException or derived)
- Exception message

### CODE REVIEW

**Review by karelz — COMMENTED** [review]
I don't think adding the field to each instance is worth the value (preventing bad code in rare cases). The cost/benefit is not there IMO.

**Comment by stephentoub** [comment]
Thanks for the PR.

But I agree with @karelz.  This increases the size of IPAddress by 8 bytes (on 64-bit).  It's not the right trade-off to increase every instance just to prevent the long-standing ability to use an obsolete setter to mutate some shared singletons.

**Comment by nil4** [comment]
@stephentoub the IPAddress class does not appear sealed. Would it be an option to: 
1. define a nested, private `ReadonlyIPAddress` class
2. change the shared singletons *values* to instances of this class, leaving their *declared* type as IPAddress 
3. in the `IPAddress.Address` setter, throw when `this` is an `ReadonlyIPAddress` instance?

**Comment by alfredmyers** [comment]
@nil4 That's an approach I was considering as well, but, as I understand, IPAddress.Address would have to be marked as virtual and that is now considered a [breaking change](https://github.com/dotnet/corefx/blob/master/Documentation/coding-guidelines/breaking-change-rules.md#members).

> * Adding `virtual` to a member
>
>    While this change would often work without breaking too many scenarios because C# compiler tends to emit `callvirt` IL instructions to call non-virtual methods (`callvirt` performs a null check, while a normal `call` won't), we can't rely on it. C# is not the only language we target and the C# compiler increasingly tries to optimize `callvirt` to a normal `call` whenever the target method is non-virtual and the `this` is provably not null (such as a method accessed through the `?.` null propagation operator). Making a method virtual would mean that consumer code would often end up calling it non-virtually.

**Comment by alfredmyers** [comment]
@stephentoub, @nil4

Oh, I see. Somehow I missed the `this is ReadOnlyIPAddress` part.
I'm Ok with it as well.

**Pull request closed without merging**
