### PR TITLE
Remove/fix/mark as bug tests which are skipped or printing failures

### PR DESCRIPTION
**Pull request by krwq**
This should remove all non-essential messages printed on the console (only number of tests passed and the test group name is displayed now)

### CODE REVIEW

**Comment by weshaggard** [comment]
@krwq as we chatted the other day please move any tests that are xunit based (i.e. don't report properly with xunit) into OuterLoop. I see from http://dotnet-ci.cloudapp.net/job/dotnet_corefx_windows_debug_prtest/59/console that there is still a number of Xml tests that are dumping out their information in to log. See:

>TestCase:Constructors with params - XDocument - 
  Pass:23, Fail:0, Skip:0
  TestCase:XContainer.ReplaceNodesOnXDocument() - 
  Pass:7, Fail:0, Skip:0
  TestCase:XContainer.ReplaceNodesOnXDocument() with Events - 
  Pass:7, Fail:0, Skip:0
...

**Comment by krwq** [comment]
The only reason I didn't do it is marking them as OuterLoop causes console runner to fail because "no test were found". On the other hand disabling test project will make them not run at all.

**Comment by weshaggard** [comment]
@krwq can you work with @bartonjs to enable an msbuild property in the project file to filed the test project to be only OuterLoop?

**Comment by krwq** [comment]
This feature is not gonna be working soon. We need to get xunit updated as we are trying to kill our fork. I will send PR to xunit soon to not fail when there are facts but no tests - hopefully they will merge it or promise to merge it soon (within few months is acceptable). If they make a promise to merge it then we can update our fork of xunit and start using it soon.

As a temporary workaround we have two options:
- we can create a .cs file with 2 fake [Fact]s (outer and inner loop) in a common/tests directory and include it in each project which has only tests of one category (either outerloop or innerloop) - this will be fairly easy to do/understand/remove in the future and doesn't require changing buildtools
- build property for a project, something like: "HasInnerLoopTests", "HasOuterLoopTests" - easy to implement/fairly easy to understand/remove. Requires changing build tools.

I think I will go with option 1 - adding .cs file in the common folder.

Can we split this change as separate PR? This one is only cleaning up.

**Comment by weshaggard** [comment]
I actually prefer option 2 because that is a direction that I know we are going to need to move towards the more we start to support OuterLoop tests which is what @bartonjs is looking into. It could be as simple as a property like <TestProperties>OuterLoop</TestProperties> that we can detect and only run if we are running OuterLoop.

**Comment by krwq** [comment]
Can we merge this PR with having https://github.com/dotnet/corefx/pull/961 pending?

**Comment by weshaggard** [comment]
Yes I'm fine merging this change given that #961 will correctly mark the projects as OuterLoop. Thanks @krwq.

**Pull request merged**
