### PR TITLE
[release/3.1]Add RID for Alpine 3.15

### PR DESCRIPTION
**Pull request by ayakael**
Contributes to dotnet/core#6985
I havn't seen this popup yet, so here is a merge request to add RID for Alpine 3.15. Tell me if I'm stepping on your toes @wfurt, I'll close it if so :).

Made as part of Alpine Linux dotnet31 / dotnet5 packaging project, see dotnet/source-build#2695

### CODE REVIEW

**Comment by wfurt** [comment]
This is not sufficient for servicing. We also need to make the packaging changes. Look at #43099 @ayakael 
cc: @Anipik @safern

**Comment by ayakael** [comment]
Many thanks, will do!

**Comment by ayakael** [comment]
Made the changes, pushing to 3.1.10, and rebased.

**Review by wfurt — APPROVED** [review]
LGTM.
Do we need anything else @safern?

**Comment by carlossanlop** [comment]
Branch is now open for merging servicing-approved changes.

@wfurt thank you for reminding to make the OOB packaging changes as well.

@wfurt @ayakael are we confident the CI failures are unrelated to this change? I see they only happened in Windows legs, so I assume we're ok, but wanted to double check with you.

**Comment by wfurt** [comment]
Test failures seems unrelate XML, IO.Ports and Memory. The links are expired, so I started another test round to be sure.

**Pull request merged**
