### PR TITLE
Port Tests for #30263 fix (#30374)

### PR DESCRIPTION
**Pull request by JeremyKuhne**
Ports #30374, which goes with port: https://github.com/dotnet/coreclr/pull/18572

* Tests for #30263 fix

Goes with https://github.com/dotnet/coreclr/pull/18460

* Add case for `C:\` to `D:\`

### CODE REVIEW

**Comment by JeremyKuhne** [comment]
@dotnet-bot test Windows x64 Debug Build
@dotnet-bot test Windows x64 Release Build

**Comment by danmosemsft** [comment]
@dotnet-bot test Windows x64 Debug Build
@dotnet-bot test Windows x64 Release Build
@dotnet-bot test Windows x86 Release Build

**Comment by danmosemsft** [comment]
@Anipik can you please keep an eye on this and merge as soon as it's green.

**Comment by Anipik** [comment]
@dotnet-bot test Windows x64 Debug Build
@dotnet-bot test Windows x64 Release Build
@dotnet-bot test Windows x86 Release Build

**Comment by Anipik** [comment]
@danmosemsft I think coreclr has not been updated from this branch yet

**Comment by Anipik** [comment]
@dotnet-bot test Windows x64 Debug Build
@dotnet-bot test Windows x64 Release Build
@dotnet-bot test Windows x86 Release Build

**Comment by danmosemsft** [comment]
You are right. It wasn't updated for 4 weeks:
https://github.com/dotnet/corefx/pulls?q=is%3Apr+coreclr+release%2F2.1+update+respectively+is%3Aclosed

There is an open PR for the update right now

@weshaggard do you know why Maestro did not put up an update PR for a month? There were many changes in CoreCLR release/2.1, and the Maestro builds seem to have succeeded: https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=1846638&view=results

**Comment by Anipik** [comment]
@dotnet-bot test Windows x64 Debug Build
@dotnet-bot test Windows x64 Release Build
@dotnet-bot test Windows x86 Release Build

**Comment by Anipik** [comment]
@dotnet-bot test  Windows x64 Release Build

**Pull request merged**
