### PR TITLE
Cache HttpClient in CertificateAssetDownloader

### PR DESCRIPTION
**Pull request by stephentoub**
Today every time we download a certificate we spin up a new connection for it which is then torn down immediately after.  In constrained environments where this is done frequently, that has overhead but more impactfully can lead to port exhaustion.  This change modifies the downloader to cache the HttpClient instance so that connections can be pooled, but restricts the connections to only be idle for at most 15 seconds, as a compromise between consuming lots of resources with pooled connections hanging around for minutes and being able to reuse connections when bursts of downloads are required.

Fixes https://github.com/dotnet/corefx/issues/30693
cc: @bartonjs, @ayende 

@bartonjs, we have tests that already exercise this code, right?

### CODE REVIEW

**Comment by GrabYourPitchforks** [comment]
Seems fairly straightforward, but why the `Lazy<Func<...>>` static field instead of having a `Func<...>` static field and creating the delegate during static initialization? Is there a timing issue, memory issue, or some other issue it's trying to work around?

**Comment by bartonjs** [comment]
> @bartonjs, we have tests that already exercise this code, right?

Sorta/kinda/mostly.

`ChainTests.VerifyWithRevocation` (OuterLoop) will try.  But CI will still pass if it fails, because Internet.

If the test runs on a machine that has already run the test, then the CRL might be cached, and the code would be unreachable.

Making a test-self-hosted endpoint to serve out stuff that the downloader would ask for is on my in-head TODO list, which I'll go ahead and write down an issue now for in case I never did.

**Comment by bartonjs** [comment]
@dotnet-bot test Outerloop Linux x64 Debug Build please

**Comment by bartonjs** [comment]
> Making a test-self-hosted endpoint to serve out stuff that the downloader would ask for is on my in-head TODO list, which I'll go ahead and write down an issue now for in case I never did.

https://github.com/dotnet/corefx/issues/33511

**Comment by stephentoub** [comment]
> Seems fairly straightforward, but why the Lazy<Func<...>> static field instead of having a Func<...> static field and creating the delegate during static initialization? Is there a timing issue, memory issue, or some other issue it's trying to work around?

@GrabYourPitchforks, I think you're right, I'll simplify it.  I was originally concerned about exceptions, but that shouldn't be an issue, and I can just eat any that do occur.

**Comment by stephentoub** [comment]
Thanks, @bartonjs.

**Comment by stephentoub** [comment]
@dotnet-bot test Linux arm64 Release Build please

**Comment by bartonjs** [comment]
* Pulled down new corefx
* Wiped out my CRL cache
* Ran (inner+)outerloop X509 tests (with the "fail even if Internet" environment variable set)
* All tests passed
* CRL cache had entries in it.

So, everything looks happy.

**Comment by stephentoub** [comment]
Yay :)  Thanks for confirming.

**Comment by ayende** [comment]
👍

**Pull request merged**
