### PR TITLE
Delete unnecessary ComVisible attributes

### PR DESCRIPTION
**Pull request by jkotas**

### CODE REVIEW

**Comment by jkotas** [comment]
@danmosemsft PTLA

**Comment by danmosemsft** [comment]
>     ComVisible(false),

this?

---
Refers to: src/System.DirectoryServices/src/Interop/SafeNativeMethods.cs:14 in f4944cf. [](commit_id = f4944cfae33d0f3f190fd7dfe7ee94d2879ae519, deletion_comment = False)

**Comment by danmosemsft** [comment]
>         ComVisible(false),

this?

---
Refers to: src/System.DirectoryServices/src/System/DirectoryServices/ActiveDirectory/NativeMethods.cs:595 in f4944cf. [](commit_id = f4944cfae33d0f3f190fd7dfe7ee94d2879ae519, deletion_comment = False)

**Comment by danmosemsft** [comment]
>     // The ComVisible attributes are here to ensure there is no delta when rebuilding

remove comment

---
Refers to: src/System.Threading.Timer/ref/System.Threading.Timer.Manual.cs:13 in f4944cf. [](commit_id = f4944cfae33d0f3f190fd7dfe7ee94d2879ae519, deletion_comment = False)

**Comment by danmosemsft** [comment]
> [assembly: ComVisible(true)] // not embed

I assume this is used by reflection tests

---
Refers to: src/System.Reflection.Metadata/tests/Resources/Interop/Interop.Mock01.cs:18 in f4944cf. [](commit_id = f4944cfae33d0f3f190fd7dfe7ee94d2879ae519, deletion_comment = False)

**Comment by danmosemsft** [comment]
>             ComVisible(false)

this?

---
Refers to: src/System.DirectoryServices/src/System/DirectoryServices/DirectoryEntry.cs:635 in f4944cf. [](commit_id = f4944cfae33d0f3f190fd7dfe7ee94d2879ae519, deletion_comment = False)

**Pull request merged**
