### PR TITLE
Port clean-up of CreateFileW

### PR DESCRIPTION
**Pull request by pjanotti**
* Removing CreateFileW from UWP

* CR: move conditional to its own ItemGroup

* removed pinvoke exceptions for Runtime.Extensions

* Fixed condition for CreateFile ItemGroup

* exception still needed for netstandard

### CODE REVIEW

**Comment by pjanotti** [comment]
I am still running local tests for this change

**Comment by pjanotti** [comment]
@dotnet-bot test NETFX OSX

**Comment by pjanotti** [comment]
@dotnet-bot test NETFX x86 Release Build

**Comment by pjanotti** [comment]
@dotnet-bot test OSX x64 Debug Build

**Comment by danmosemsft** [comment]
NETFX is fixed by https://github.com/dotnet/corefx/pull/24325
Tizen armel also reproes on https://github.com/dotnet/corefx/pull/24325 so it's unrelated.

Approved by @russellhadley offline.

**Pull request merged**
