### PR TITLE
Fixed some issues based on a Code Analysis run

### PR DESCRIPTION
**Pull request by KrzysztofCwalina**

### CODE REVIEW

**Comment by JeremyKuhne** [comment]
LGTM

**Comment by bpschoch** [comment]
var ex = Assert.Throws<ArgumentOutOfRangeException>(() => new UnicodeRange(firstCodePoint, rangeSize));
+            Assert.Equal("length", ex.ParamName);

These kind of asserts can be simplified as:

Assert.Throws<ArgumentOutOfRangeException>("length", () => new UnicodeRange(firstCodePoint, rangeSize));

**Comment by KrzysztofCwalina** [comment]
@bpschoch, it's cute, but is it more readable?

**Comment by bpschoch** [comment]
I started to use this notation in tests I've written after I saw it used in other parts of the library.  It keeps the tests terse especially if you have a sequence of asserts.

**Comment by stephentoub** [comment]
And in such cases it avoids the introduction of unnecessary locals, which I personally find keeps things more readable.

**Comment by stephentoub** [comment]
LGTM

**Comment by KrzysztofCwalina** [comment]
When I work on tests with multiple lines like that, I will consider this overload. Thanks for the tip.

**Pull request merged**
