### PR TITLE
Removing files since MemoryExtensions is in CoreLib now.

### PR DESCRIPTION
**Pull request by ahsonkhan**
Part of https://github.com/dotnet/corefx/issues/25182

Depends on https://github.com/dotnet/coreclr/pull/16521 (and the subsequent mirror PR).

- Removed duplicated files
- Moved the internal Clear helper methods from SpanHelpers.Clear.cs to SpanHelpers.cs since it is a small enough file

cc @jkotas, @KrzysztofCwalina, @stephentoub

### CODE REVIEW

**Comment by joshfree** [comment]
@dotnet-bot test this please

**Comment by ahsonkhan** [comment]
We have to wait for https://github.com/dotnet/corefx/pull/27515

**Comment by ahsonkhan** [comment]
@dotnet-bot test this please

**Comment by joshfree** [comment]
```
14:29:16 Build FAILED.
14:29:16 
14:29:16 System\Buffers\StandardFormat.cs(106,95): error CS0103: The name 'MemoryExtensions' does not exist in the current context [D:\j\workspace\windows-TGrou---f8ac6754\src\System.Memory\src\System.Memory.csproj]
14:29:16 System\Number\Number.NumberBuffer.cs(43,40): error CS1061: 'Span<byte>' does not contain a definition for 'IndexOf' and no extension method 'IndexOf' accepting a first argument of type 'Span<byte>' could be found (are you missing a using directive or an assembly reference?) [D:\j\workspace\windows-TGrou---f8ac6754\src\System.Memory\src\System.Memory.csproj]
14:29:16 System\Buffers\BuffersExtensions.cs(21,41): error CS7036: There is no argument given that corresponds to the required formal parameter 'comparisonType' of 'Span.IndexOf(ReadOnlySpan<char>, ReadOnlySpan<char>, StringComparison)' [D:\j\workspace\windows-TGrou---f8ac6754\src\System.Memory\src\System.Memory.csproj]
14:29:16     0 Warning(s)
14:29:16     3 Error(s)

```

**Comment by ahsonkhan** [comment]
The current coreclr version that corefx points to doesn't have MemoryExtensions.

We needed a newer one: https://github.com/dotnet/corefx/pull/27530

**Comment by ahsonkhan** [comment]
Cherry-picked the changes into https://github.com/dotnet/corefx/pull/27530

Closing the PR.

**Pull request closed without merging**
