### PR TITLE
add FreeBSD among platforms.

### PR DESCRIPTION
**Pull request by wfurt**
This is small part so other repos can be fixed. They use this often as 

if (System.Runtime.InteropServices.RuntimeInformation.IsOSPlatform(System.Runtime.InteropServices.OSPlatform.OSX)) 
{
....
}

This allows to follow same pattern for FreeBSD

### CODE REVIEW

**Comment by danmosemsft** [comment]
@wfurt unfortunately this is a public API so it needs to go through the API review process. Shouldn't be difficult, but needs an issue opened and marked api-ready-for-review, etc.

**Comment by wfurt** [comment]
ok. thanks @danmosemsft

**Comment by karelz** [comment]
Blocked on API review in #23989

**Comment by karelz** [comment]
Closing the PR, until we have green light on the new API (after the OS port mostly works) - see https://github.com/dotnet/corefx/issues/23989#issuecomment-329523856 for details.

**Comment by wfurt** [comment]
fixes #23989 
It is API approved now.

**Pull request closed without merging**
