### PR TITLE
Disable GetNativeVariantForObject() API tests when targeting UAP

### PR DESCRIPTION
**Pull request by AaronRobinsonMSFT**
@stephentoub or @luqunl is this the apporpriate way to disable these test for UWP?

See #30936

### CODE REVIEW

**Comment by stephentoub** [comment]
@dotnet-bot test this please

**Comment by stephentoub** [comment]
@dotnet-bot test this please

**Comment by AaronRobinsonMSFT** [comment]
@stephentoub Am I okay to merge this in?

**Comment by stephentoub** [comment]
Yes

**Pull request merged**
