### PR TITLE
Port 39745 to release/3.0

### PR DESCRIPTION
**Pull request by geoffkizer**
Original PR: #39745 

@danmosemsft Can you approve? Note this is the fix I mentioned in #39775; I ended up porting it separately.

cc @stephentoub

### CODE REVIEW

**Comment by danmosemsft** [comment]
OK - stress fix. thanks

**Comment by geoffkizer** [comment]
@dotnet/dnceng UWP is failing with the below error. Is this a known issue? I tried to hit "re-run" but it doesn't seem to actually re-run the build.

```
D:\a\1\s\src\System.Runtime\tests\TestStructs\System.TestStructs.ilproj : error : Failed to resolve SDK 'Microsoft.NET.Sdk.IL'. Package restore was successful but a package with the ID of "Microsoft.NET.Sdk.IL" was not installed.
```

**Comment by danmosemsft** [comment]
@geoffkizer to rerun, you have to click the "view more in Azure Pipelines" link then (assuming you are logged into Azure Pipelines if necessary) you will be at https://dev.azure.com/dnceng/public/_build/results?buildId=279497 and there's a button in the top right with three dots on it. Click that and choose Retry. It will retry only the failing legs, which is nice.

I clicked it..

**Comment by karelz** [comment]
@geoffkizer please link the fixed issues even in 3.0 port PRs (that way it is easier to find and validate from the issue that it was truly fixed in 3.0) - see my edits to the top post. Thanks!

**Pull request merged**
