### PR TITLE
Support musl-libc based linux RIDs

### PR DESCRIPTION
**Pull request by eerhardt**
- Add `linux-musl` RID
- Set `alpine`'s parent to `linux-musl`
- Add `alpine.3.7` to the graph
- Fix up `android` to inherit from `unix` while we are here

Fixes https://github.com/dotnet/core-setup/issues/3817

QUESTION: Is `linux-musl` the correct name for this RID?  Do we like the order of the two words?  Is using a hyphen to separate them acceptable?

/cc @Petermarcu

### CODE REVIEW

**Comment by Petermarcu** [comment]
lgtm

**Comment by janvorli** [comment]
> Is musl-linux the correct name for this RID?  Do we like the order of the two words?  Is using a hyphen to separate them acceptable?

This name format makes sense, I only wonder if parsing of RID that we may have at various places would work correctly without changes.

**Comment by danmosemsft** [comment]
@weshaggard for question about RID parsing.

**Comment by eerhardt** [comment]
test Linux x64 Release Build
test OSX x64 Debug Build

Both System.Net.HttpListener test failures

**Comment by weshaggard** [comment]
>This name format makes sense, I only wonder if parsing of RID that we may have at various places would work correctly without changes.

It should work as far as I'm aware. @steveharter are you aware of anything in the host parsing code that wouldn't handle this naming convention?

**Comment by 4creators** [comment]
IMO as linux is more general term and musl is just a C runtime using linux-musl could be better.

**Comment by steveharter** [comment]
>> @steveharter are you aware of anything in the host parsing code that wouldn't handle this naming convention?

I am not aware of any parsing code like that. The host really depends on the "fallback graph" in NETCoreApp's runtimeconfig.json to define the list of RIDs and their fallback RIDs.

**Comment by eerhardt** [comment]
@4creators - we had the opposite opinion from @kasper3 on https://github.com/dotnet/core-setup/issues/3817#issuecomment-376773300.

**Comment by eerhardt** [comment]
I've renamed the RID to `linux-musl`.  I agree it makes sense to have the more general term first.

**Comment by eerhardt** [comment]
Can someone review this?  I'd like to get it in for ZBB tomorrow.

**Pull request merged**
