### PR TITLE
Update ILLink version.

### PR DESCRIPTION
**Pull request by erozenfeld**
This change updates ILLink version and the flags required by that version.

### CODE REVIEW

**Comment by erozenfeld** [comment]
@ericstj PTAL

**Comment by erozenfeld** [comment]
@dotnet-bot test outerloop netcoreapp CentOS7.1 Debug
@dotnet-bot test outerloop netcoreapp CentOS7.1 Release
@dotnet-bot test outerloop netcoreapp Debian8.4 Debug
@dotnet-bot test outerloop netcoreapp Debian8.4 Release
@dotnet-bot test outerloop netcoreapp Fedora24 Debug
@dotnet-bot test outerloop netcoreapp Fedora24 Release
@dotnet-bot test outerloop netcoreapp OpenSUSE13.2 Debug
@dotnet-bot test outerloop netcoreapp OpenSUSE13.2 Release
@dotnet-bot test outerloop netcoreapp OpenSUSE42.1 Debug
@dotnet-bot test outerloop netcoreapp OpenSUSE42.1 Release
@dotnet-bot test outerloop netcoreapp OSX10.12 Debug
@dotnet-bot test outerloop netcoreapp OSX10.12 Release
@dotnet-bot test outerloop netcoreapp PortableLinux Debug
@dotnet-bot test outerloop netcoreapp PortableLinux Release
@dotnet-bot test outerloop netcoreapp RHEL7.2 Debug
@dotnet-bot test outerloop netcoreapp RHEL7.2 Release
@dotnet-bot test outerloop netcoreapp Ubuntu14.04 Debug
@dotnet-bot test outerloop netcoreapp Ubuntu14.04 Release
@dotnet-bot test outerloop netcoreapp Ubuntu16.04 Debug
@dotnet-bot test outerloop netcoreapp Ubuntu16.04 Release
@dotnet-bot test outerloop netcoreapp Ubuntu16.10 Debug
@dotnet-bot test outerloop netcoreapp Ubuntu16.10 Release
@dotnet-bot test outerloop netcoreapp Windows 10 Debug
@dotnet-bot test outerloop netcoreapp Windows 10 Release

**Comment by danmosemsft** [comment]
Some of these may be flaky network tests. You'd have to have a quick look though.

@dotnet-bot test outerloop netcoreapp OSX10.12 Debug (network improved?)
@dotnet-bot test outerloop netcoreapp OSX10.12 Release ("")

**Comment by erozenfeld** [comment]
@dotnet-bot Innerloop OSX10.12 Debug x64 Build and Test
@dotnet-bot Innerloop OSX10.12 Release x64 Build and Test
@dotnet-bot OuterLoop netcoreapp CentOS7.1 Debug x64 
@dotnet-bot OuterLoop netcoreapp Fedora24 Debug x64
@dotnet-bot OuterLoop netcoreapp OSX10.12 Debug x64 
@dotnet-bot OuterLoop netcoreapp OSX10.12 Release x64
@dotnet-bot OuterLoop netcoreapp OpenSUSE13.2 Release x64
@dotnet-bot OuterLoop netcoreapp PortableLinux Debug x64

**Comment by erozenfeld** [comment]
@dotnet-bot test Innerloop OSX10.12 Debug x64 Build and Test
@dotnet-bot test Innerloop OSX10.12 Release x64 Build and Test
@dotnet-bot test OuterLoop netcoreapp CentOS7.1 Debug x64
@dotnet-bot test OuterLoop netcoreapp Fedora24 Debug x64
@dotnet-bot test OuterLoop netcoreapp OSX10.12 Debug x64
@dotnet-bot test OuterLoop netcoreapp OSX10.12 Release x64
@dotnet-bot test OuterLoop netcoreapp OpenSUSE13.2 Release x64
@dotnet-bot test OuterLoop netcoreapp PortableLinux Debug x64

**Comment by ericstj** [comment]
Looks like @mellinoe updated us to the 2.0-msbuild based tooling so you'll need to rebase this on his changes and update the depproj instead.

**Comment by mellinoe** [comment]
You should be able to edit [this line](https://github.com/dotnet/corefx/blob/master/external/ILLink/ILLink.depproj#L13) instead.

**Comment by erozenfeld** [comment]
@dotnet-bot test outerloop netcoreapp CentOS7.1 Debug
@dotnet-bot test outerloop netcoreapp CentOS7.1 Release
@dotnet-bot test outerloop netcoreapp Debian8.4 Debug
@dotnet-bot test outerloop netcoreapp Debian8.4 Release
@dotnet-bot test outerloop netcoreapp Fedora24 Debug
@dotnet-bot test outerloop netcoreapp Fedora24 Release
@dotnet-bot test outerloop netcoreapp OpenSUSE13.2 Debug
@dotnet-bot test outerloop netcoreapp OpenSUSE13.2 Release
@dotnet-bot test outerloop netcoreapp OpenSUSE42.1 Debug
@dotnet-bot test outerloop netcoreapp OpenSUSE42.1 Release
@dotnet-bot test outerloop netcoreapp OSX10.12 Debug
@dotnet-bot test outerloop netcoreapp OSX10.12 Release
@dotnet-bot test outerloop netcoreapp PortableLinux Debug
@dotnet-bot test outerloop netcoreapp PortableLinux Release
@dotnet-bot test outerloop netcoreapp RHEL7.2 Debug
@dotnet-bot test outerloop netcoreapp RHEL7.2 Release
@dotnet-bot test outerloop netcoreapp Ubuntu14.04 Debug
@dotnet-bot test outerloop netcoreapp Ubuntu14.04 Release
@dotnet-bot test outerloop netcoreapp Ubuntu16.04 Debug
@dotnet-bot test outerloop netcoreapp Ubuntu16.04 Release
@dotnet-bot test outerloop netcoreapp Ubuntu16.10 Debug
@dotnet-bot test outerloop netcoreapp Ubuntu16.10 Release
@dotnet-bot test outerloop netcoreapp Windows 10 Debug
@dotnet-bot test outerloop netcoreapp Windows 10 Release

**Comment by erozenfeld** [comment]
@ericstj @mellinoe Rebased and updated ILLink.depproj

**Comment by erozenfeld** [comment]
@dotnet-bot test OuterLoop netcoreapp OpenSUSE13.2 Debug x64
@dotnet-bot test OuterLoop netcoreapp OpenSUSE13.2 Release x64

**Comment by erozenfeld** [comment]
@dotnet-bot test Innerloop Windows_NT Debug x86 Build and Test 
@dotnet-bot test OuterLoop netcoreapp OpenSUSE13.2 Debug x64
@dotnet-bot test OuterLoop netcoreapp OpenSUSE13.2 Release x64

**Comment by erozenfeld** [comment]
@dotnet-bot test OuterLoop netcoreapp CentOS7.1 Release x64
@dotnet-bot test OuterLoop netcoreapp Fedora24 Debug x64
@dotnet-bot test OuterLoop netcoreapp OpenSUSE13.2 Debug x64
@dotnet-bot test OuterLoop netcoreapp OpenSUSE13.2 Release x64
@dotnet-bot test OuterLoop netcoreapp PortableLinux Debug x64
@dotnet-bot test OuterLoop netcoreapp Windows 10 Debug x64
@dotnet-bot  test OuterLoop netcoreapp Windows 10 Release x64

**Comment by ericstj** [comment]
Fedora24 is failing due to issue #17749, unrelated.
```
23:25:46   /mnt/resource/j/workspace/dotnet_corefx/master/outerloop_netcoreapp_fedora24_debug_prtest/src/Native/Unix/System.Native/pal_networking.cpp (414): error 22: Unknown gethostbyname/gethostbyaddr error code. Invalid argument (false failed)
23:25:46   dotnet: /mnt/resource/j/workspace/dotnet_corefx/master/outerloop_netcoreapp_fedora24_debug_prtest/src/Native/Unix/System.Native/pal_networking.cpp:414: int ConvertGetHostErrorPlatformToPal(int): Assertion `false && "assert_err failed"' failed.
```
OpenSUSE appears to be failing when restoring buildtools /cc @mellinoe 
```
22:50:05 Installing dotnet cli...
22:50:05 tar: This does not look like a tar archive
22:50:05 tar: Exiting with failure status due to previous errors
22:50:05 Restoring BuildTools version 1.0.27-prerelease-01510-01...
22:50:05 
```

Change LGTM.

**Comment by mellinoe** [comment]
AFAIK, we don't support or build for openSUSE 13.2 any longer. We should probably remove those jobs from netci.groovy.

**Pull request merged**
