### PR TITLE
Adding some System.Math tests to cover areas where other platforms may differ from windows.

### PR DESCRIPTION
**Pull request by tannergooding**
These are all scenarios which have custom handling in PAL but did not have explicit coverage here to validate the behavior is consistent across all platforms (including Windows).

### CODE REVIEW

**Comment by tannergooding** [comment]
I expect `Assert.Equal(double.NaN, Math.Pow(double.NaN, 0.0));` may fail. The result returned in Windows has changed from `double.NaN` to `1.0` (the latter is what is returned by other platforms and is the return value specified by POSIX).

**Comment by stephentoub** [comment]
Thanks, @tannergooding. LGTM once CI is green.

**Comment by stephentoub** [comment]
Test Innerloop Windows_NT Release Build and Test please (an AV in the XML tests)

**Comment by tannergooding** [comment]
Looks like all tests are passing.

**Comment by stephentoub** [comment]
> Looks like all tests are passing.

Do you expect some to break when we pick up a new coreclr with your changes?  Currently the CI run is using the latest successful build from coreclr on CentOS, but a build from a NuGet package from yesterday morning for the rest of the legs.

**Comment by tannergooding** [comment]
I don't expect any breaks in the new tests. However, I also don't see any reason this can't wait until the fix for #9053 (https://github.com/dotnet/coreclr/pull/5399) goes in.

If this does wait for the fix, then there are 12 other tests which should probably be added which cover scenarios where both `x` and `y` are +/-INFINITY and some scenarios where `x` is -0.0. There is a specific scenario, `pow(-0, -1)`, that is currently returning the wrong value for non-Windows platforms (both before and after my CoreCLR changes).

If this doesn't wait for the fix, I'll submit a separate PR that adds the 12 other tests.

**Comment by stephentoub** [comment]
Thanks, @tannergooding.  Let's go ahead then and merge this now, and you can submit a separate PR with the additional tests once we've upgraded to packages that include your changes.

**Pull request merged**
