### PR TITLE
Branchify RC2

### PR DESCRIPTION
**Pull request by mmitche**

### CODE REVIEW

**Comment by ellismg** [comment]
@dotnet-bot test ci please

**Comment by mmitche** [comment]
@ellismg Not going to do anything until I merge the main dotnet-ci change, which I won't do until this is in and I am ready to hit the button on the master branch one.

**Comment by mmitche** [comment]
It's a bit of a dance.  I have to go in a half hour.  Is it critical to get thje workflow changed tonight?

**Comment by ellismg** [comment]
Okay.  I'll merge this.  If we need to make any more changes in the RC2 branch, please coordinate with me.

**Pull request merged**
