### PR TITLE
Port release/2.0.0 fixes to Uwp6.1

### PR DESCRIPTION
**Pull request by wtgodbe**
CC @HollyAM @krwq @bartonjs @nattress @weshaggard

### CODE REVIEW

**Comment by wtgodbe** [comment]
Build Failures:

- Linux: Lots of failures in System.Net.Security tests - all I've checked have been `System.Net.Sockets.SocketException : Cannot assign requested address`
-NetFx x86: Three test failures in System.Diagnostics.StackTrace. All look like the following: 

> 12:57:06         Assert.Null() Failure
12:57:06         Expected: (null)
12:57:06         Actual:   StackFrame[] [InvokeException at offset 19 in file:line:column <filename unknown>:0:0
- OSX: Build failure with a double-import: 

> 12:56:06 /Users/dotnet-bot/j/workspace/dotnet_corefx/release_uwp6.1/osx-TGroup_netcoreapp+CGroup_Debug+AGroup_x64+TestOuter_false_prtest/dir.traversal.targets(81,3): warning MSB4011: "/Users/dotnet-bot/j/workspace/dotnet_corefx/release_uwp6.1/osx-TGroup_netcoreapp+CGroup_Debug+AGroup_x64+TestOuter_false_prtest/Tools/Dumpling.targets" cannot be imported again. It was already imported at "/Users/dotnet-bot/j/workspace/dotnet_corefx/release_uwp6.1/osx-TGroup_netcoreapp+CGroup_Debug+AGroup_x64+TestOuter_false_prtest/Tools/tests.targets (511,3)". This is most likely a build authoring error. This subsequent import will be ignored.
Tizen: Build failure with 

> System/SpanExtensions.cs(21,43): error CS0619: 'Span<T>' is obsolete: 'Types with embedded references are not supported in this version of your compiler.' [/opt/corefx/src/System.Memory/src/System.Memory.csproj]

None look related to me, but I can't be sure. @weshaggard @bartonjs @krwq thoughts?

**Comment by wtgodbe** [comment]
https://github.com/dotnet/corefx/pull/28736 is up to get a baseline on CI failures

**Comment by wtgodbe** [comment]
The NetFx, OSX, and Tizen failures are all present in the baseline PR. As for the Linux failures, there are several Ubuntu test failures in `System.Net.Security` in this PR - https://mc.dot.net/#/user/wtgodbe/pr~2Fjenkins~2Fdotnet~2Fcorefx~2Frelease~2Fuwp6.1~2F/test~2Ffunctional~2Fcli~2F/1f890add2719c4cf237b57a302dda9b6866a0897/workItem/System.Net.Security.Tests. However, in the baseline PR, it appears those tests didn't run - https://mc.dot.net/#/user/wtgodbe/pr~2Fjenkins~2Fdotnet~2Fcorefx~2Frelease~2Fuwp6.1~2F/test~2Ffunctional~2Fcli~2F/3e590a11fcf4106fb6fbbcdc50ade5bcac902c35/workItem/System.Net.Security.Tests (Make sure to uncheck the "Show failing results only" box). I'm not sure what's going on there - maybe they haven't run yet?

**Comment by wtgodbe** [comment]
For the Linux build:
- Logs from this PR: `System.Net.Security.Tests  Total: 167, Errors: 0, Failed: 53, Skipped: 5, Time: 5.926s`
- Logs from the baseline PR: `System.Net.Security.Tests  Total: 167, Errors: 0, Failed: 0, Skipped: 5, Time: 5.408s`

So we are getting failures in this PR that don't exist in the baseline. @krwq @bartonjs any idea what might be causing the test failures there? They are (at least for the most part) `System.Net.Sockets.SocketException : Cannot assign requested address`

**Comment by bartonjs** [comment]
@wtgodbe Nope.  I don't see how any of the changes could really affect this.  Did you try re-running? It could be that the host just got in a weird state, since it seems like the system sockets library reported that it couldn't open the server socket.  If it's persisting across runs then it probably is going to require someone from networking to look and see what's going on.

**Comment by wtgodbe** [comment]
@dotnet-bot test Linux x64 Release Build

**Comment by wtgodbe** [comment]
The ubuntu failures didn't repro in the most recent Linux test run, so all of the failures in this PR are also present in the baseline PR, meaning CI shouldn't be blocking this from going in @HollyAM

**Pull request merged**
