### PR TITLE
Change Build to BuildMoniker to get correct build id

### PR DESCRIPTION
**Pull request by mmitche**

### CODE REVIEW

**Comment by mmitche** [comment]
@dotnet-bot test portable linux debug pipeline
@dotnet-bot test portable linux release pipeline
@dotnet-bot test portable windows debug pipeline
@dotnet-bot test portable windows release pipeline

**Comment by mmitche** [comment]
@dotnet-bot test portable windows release pipeline

**Comment by mmitche** [comment]
@dotnet-bot test portable linux debug pipeline

**Comment by mmitche** [comment]
@MattGal PTAL

**Comment by mmitche** [comment]
@MattGal It's the hash, which means that a multiple submissions could have the same build.  That is the intention though, since we want to group results from the same hash together in reporting.

**Comment by MattGal** [comment]
@mmitche Ah then sounds good to me.  Perhaps your variable (helixBuild) could be renamed in a future change, say to "commitHash" or something, to make this more obvious.

**Comment by mmitche** [comment]
@MattGal Will do.

**Pull request merged**
