### PR TITLE
Add PortableLinux build to CI

### PR DESCRIPTION
**Pull request by gkhanna79**
@weshaggard @ellismg @mmitche PTAL

This adds the PortableLinux build support to CoreFX CI.

FYI @janvorli

### CODE REVIEW

**Comment by gkhanna79** [comment]
@dotnet-bot test ci please

**Comment by gkhanna79** [comment]
@dotnet-bot test Innerloop PortableLinux Debug Build and Test please

**Comment by mellinoe** [comment]
https://ci.dot.net/job/dotnet_corefx/job/master/job/GenPRTest/job/portablelinux_debug_prtest/

**Comment by gkhanna79** [comment]
Jenkins appears to be failing:

```
13:45:21 java.net.MalformedURLException
13:45:21 	at java.net.URL.<init>(URL.java:627)
13:45:21 	at java.net.URL.<init>(URL.java:490)
13:45:21 	at java.net.URL.<init>(URL.java:439)
13:45:21 	at com.tikal.hudson.plugins.notification.Protocol$3.send(Protocol.java:61)
13:45:21 	at com.tikal.hudson.plugins.notification.Phase.handle(Phase.java:47)
13:45:21 	at com.tikal.hudson.plugins.notification.JobListener.onStarted(JobListener.java:31)
13:45:21 	at hudson.model.listeners.RunListener.fireStarted(RunListener.java:240)
13:45:21 	at hudson.model.Run.execute(Run.java:1716)
13:45:21 	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
13:45:21 	at hudson.model.ResourceController.execute(ResourceController.java:98)
13:45:21 	at hudson.model.Executor.run(Executor.java:404)

```
@mmitche Do you know why is that?

**Comment by gkhanna79** [comment]
Here is another build that I queued that seems to be progressing: https://ci.dot.net/job/dotnet_corefx/job/master/job/GenPRTest/job/portablelinux_debug_prtest/2/console

**Comment by gkhanna79** [comment]
@dotnet-bot test ci please

**Comment by gkhanna79** [comment]
https://ci.dot.net/job/dotnet_corefx/job/master/job/GenPRTest/job/portablelinux_debug_prtest/3/console is the PR to test this change that passes the "-portableLinux" argument to the build.

**Comment by mmitche** [comment]
@gkhanna79 It's a bug in a change I made to a plugin which doesn't affect the status of the job.  it will happen if you manually save changes made to an automatic job.  It's interpreting the name of the URL to send telemtry as the URL itself.

**Comment by weshaggard** [comment]
@gkhanna79 do we know if this leg is more reliable now? Part of the reason it was removed before was because of the reliability issues.

**Comment by weshaggard** [comment]
Sorry ignore my earlier comment I mixed that up with the Linux ARM emulator legs.

**Comment by gkhanna79** [comment]
PortableLinux was never part of the CI @weshaggard and has been building/publishing from CoreFX pipeline for quite sometime (even before dev/eng RI).

I am not aware of any reliability issues.

**Comment by weshaggard** [comment]
cc @danmosemsft @karelz @stephentoub to get there opinions about what we should have as part of every PR.  I don't have any particular issue I only worry about finding the right balance of number of CI legs vs the value they provide. I kind of think we should start mixing and matching Debug/Release/Arch/OS to get a more sparse matrix as part of ever PR run, instead of testing every combination.

**Comment by stephentoub** [comment]
Adding it to CI seems like a good idea, but I agree that we don't need debug + release for all of the different OSes.

**Comment by gkhanna79** [comment]
To be clear, this change will only run the PortableLinux CI on RHEL7.2 and not all OS configurations (unless there is something wrong in my change - in which case, please point it out :)).

With the above said, is the inclination to enable it only for Release or Debug? If so, is there a preference?

**Comment by karelz** [comment]
I wonder if we should revisit the whole matrix now and rather cut some Debug/Release for existing distros and keep Debug & Release for PortableLinux. Bad idea?

**Comment by weshaggard** [comment]
@gkhanna79 is working on one portion of the corefx CI so I wouldn't suggest he mix-up the matrix as part of this PR as that isn't @gkhanna79's responsibility. I would suggest he continue with what he has which is to add both the Debug and Release for this leg which is following the pattern of the others. However I would suggest he adds to the matrix for the master merge and update the badges as @stephentoub suggests.

For mixing up the matrix I've filed issue https://github.com/dotnet/corefx/issues/15635 to discuss and address.

**Comment by gkhanna79** [comment]
Post discussing with @weshaggard, I have also added support for Outerloop testing. @weshaggard PTAL.

Once this is merged and correct label links are available, I will submit a second PR to update the status table.

**Comment by gkhanna79** [comment]
@dotnet-bot test ci please

**Pull request merged**
