### PR TITLE
Run OSX outerloop runs elevated.

### PR DESCRIPTION
**Pull request by Priya91**
depends on dotnet/dotnet-ci#308

cc @mmitche

### CODE REVIEW

**Comment by stephentoub** [comment]
LGTM

**Comment by stephentoub** [comment]
test ci please

**Comment by stephentoub** [comment]
test ci please

**Comment by stephentoub** [comment]
@mmitche, is the generator_prtest leg supposed to work still?  It's hitting this error:
```
06:57:46 ERROR: Error fetching remote repo 'origin'
06:57:46 hudson.plugins.git.GitException: Failed to fetch from https://github.com/dotnet/dotnet-ci
06:57:46 	at hudson.plugins.git.GitSCM.fetchFrom(GitSCM.java:766)
06:57:46 	at hudson.plugins.git.GitSCM.retrieveChanges(GitSCM.java:1022)
06:57:46 	at hudson.plugins.git.GitSCM.checkout(GitSCM.java:1053)
06:57:46 	at org.jenkinsci.plugins.multiplescms.MultiSCM.checkout(MultiSCM.java:129)
06:57:46 	at hudson.scm.SCM.checkout(SCM.java:485)
06:57:46 	at hudson.model.AbstractProject.checkout(AbstractProject.java:1276)
06:57:46 	at hudson.model.AbstractBuild$AbstractBuildExecution.defaultCheckout(AbstractBuild.java:607)
06:57:46 	at jenkins.scm.SCMCheckoutStrategy.checkout(SCMCheckoutStrategy.java:86)
06:57:46 	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:529)
06:57:46 	at hudson.model.Run.execute(Run.java:1738)
06:57:46 	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
06:57:46 	at hudson.model.ResourceController.execute(ResourceController.java:98)
06:57:46 	at hudson.model.Executor.run(Executor.java:410)
06:57:46 Caused by: hudson.plugins.git.GitException: Command "git config remote.origin.url https://github.com/dotnet/dotnet-ci" returned status code 4:
06:57:46 stdout: 
06:57:46 stderr: error: could not write config file .git/config: Permission denied
```

**Comment by mmitche** [comment]
@stephentoub It should.  I wonder if something is wrong with that machine.

**Comment by mmitche** [comment]
test ci please

**Comment by mmitche** [comment]
@dotnet-bot test ci please

**Comment by mmitche** [comment]
It looks like the git config on that machine was written by an admin account.

**Comment by stephentoub** [comment]
Thanks, @mmitche.

**Pull request merged**
