### PR TITLE
Consolidate more code in the "System.Drawing" namespace.

### PR DESCRIPTION
**Pull request by mellinoe**
* Remove all remaining Win32 codepaths from the mono codebase. All of this code now implicitly assumes that it will be run on a Unix platform.
* Consolidate the rest of the gdipFunctions.cs file into Gdip.cs and GdipNative.Unix.cs
* Consolidate the GraphicsUnit and ImageType enumerations -- they were duplicated.
* Remove the mono Status enum and use the Windows constants instead in all Unix code.
* Move all files into the regular directory structure. Suffix them with ".Unix" and ".Windows" when there are collisions.

@qmfrederik @akoeplinger  This is a fairly large change to some of the mono code files. All win32-specific codepaths have been ripped out, with the assumption that the Windows build configuration covers everything that we need there. I'd like to hear some feedback on that general approach, because to me it doesn't make sense to keep the Win32 codepaths around.

### CODE REVIEW

**Comment by qmfrederik** [comment]
@mellinoe

* Overall, makes sense to me. I would run the Mono unit test suite (WIP, I know) though to make sure this didn't break anything by accident.

* I think there's some similar work left to do, for example a lot of code in `Graphics` can still be shared between the `.Unix.cs` and  `.Windows.cs` variants, right?

* As for this one:
 > Remove the mono Status enum and use the Windows constants instead in all Unix code.

 I always found the status enum to be a bit more elegant (for example, you get IntelliSense support for free); may be a matter of preference, though.

* I can't really comment from a Mono-specific point of view (e.g. whether the Mono packaging process supports having two different assemblies for Windows & Unix).

**Comment by mellinoe** [comment]
> I can't really comment from a Mono-specific point of view (e.g. whether the Mono packaging process supports having two different assemblies for Windows & Unix).

I guess that is a good question that I took for granted. I assumed it was okay given how the rest of our code in corefx is structured. @akoeplinger @marek-safar Could one of you clarify whether the approach is okay?

**Comment by mellinoe** [comment]
> I always found the status enum to be a bit more elegant (for example, you get IntelliSense support for free); may be a matter of preference, though.

Yeah, I agree to an extent. It's a bit of a wash for me because I would also like to keep the code as close to the .NET Framework as possible, so I'd like to avoid making large changes like that to the Windows code.

**Comment by akoeplinger** [comment]
Discussed with @mellinoe on Skype, we can build OS-specific assemblies in Mono now so this should be fine from our side.

**Comment by mellinoe** [comment]
@akoeplinger Thanks, was just about to type that 😄 

@qmfrederik I agree that running the tests from your PR is a good idea before merging this. I will look at that today.

**Comment by mellinoe** [comment]
@qmfrederik I rebased this and ran it against the tests in your drawing/mono-tests branch and verified everything was still passing. I'll merge when CI goes green.

**Comment by qmfrederik** [comment]
Thanks!

**Comment by mellinoe** [comment]
Test Linux x64 Release Build
UWP CoreCLR x64 Debug Build
Windows x86 Release Build

(These all seem to have timed out).

**Comment by mellinoe** [comment]
Test UWP CoreCLR x64 Debug Build
Test Windows x86 Release Build

**Comment by mellinoe** [comment]
Something seems to be up with CI -- I'll wait to re-trigger those runs. They timed out again.

**Comment by mellinoe** [comment]
Test Windows x86 Release Build
Test Linux x64 Release Build

**Pull request merged**
