### PR TITLE
Added System.Version constructor

### PR DESCRIPTION
**Pull request by hann013**
Added constructor to System.Version, as per #10998

### CODE REVIEW

**Comment by hann013** [comment]
cc @danmosemsft

**Comment by danmosemsft** [comment]
:shipit:

**Comment by hann013** [comment]
@dotnet-bot test  Innerloop Windows_NT Release Build and Test please

**Comment by hann013** [comment]
@dotnet-bot test Innerloop CentOS7.1 Release Build and Test please

**Pull request merged**
