### PR TITLE
Change the ValueTuple hashing algorithm again

### PR DESCRIPTION
**Pull request by jamesqo**
## Background

I submitted a PR a couple of months ago at #8964 that changed the `GetHashCode` algorithm for ValueTuple. While the new algorithm was better than the old one since it took all bits of `h1` into account equally, I eventually came to realize there was a major flaw with it and its predecessor: if `h1` is zero (which will happen all the time if it is null), then the result will just be `h2`. This means that *all* of these will create collisions:

```cs
(null, null).GetHashCode() == (null, null, null).GetHashCode() // both 0
(0, 0).GetHashCode() == (0, 0, 0, 0).GetHashCode() // both 0

int age = 10;
age.GetHashCode() == (0, age).GetHashCode() == (0, 0, age).GetHashCode() // all 10

// Linked list where equality is determined based on the contents
public class ListNode<T> : IEquatable<ListNode<T>>
{
    public readonly T Item;
    public readonly ListNode<T> Next;

    public override int GetHashCode() => (_item, _next).GetHashCode();
}

var next = GetListNode();
var prev = new ListNode<T> { Next = next };
prev.GetHashCode() == next.GetHashCode() // Item is initialized to null,
                                         // and doesn't get represented in the final hash
```

Obviously this is unacceptable, since presumably when C# 7 comes out, there will be lazy/smart people who just use `return (_field1, _field2, ...).GetHashCode()` for their hashing, so the algorithm needs to be as robust as possible.

## Changes

I've changed `HashHelpers`, which does the actual combining work for `ValueTuple`, to use the same formula as [Boost's `hash_combine`](https://github.com/boostorg/functional/blob/develop/include/boost/functional/hash/hash.hpp#L212). There was even an [official proposal](http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2014/n3876.pdf) some time ago to make this formula part of the C++ standard library, although it was not accepted.

Benefits:

- Now the arity of the tuple affects the hash when the items are all zeroes; `(0, 0)` will have a very different hash code compared to `(0, 0, 0)`.

- The upper bits of the hash are not wasted when dealing with small numbers. Previously `(1, 2)` would only utilize about 6 bits of the hash code, `(1, 2, 3)` would generate an 11-bit hash code, `(1, 2, 3, 4)` a 16-bit one, etc. Now they all generate very large hashes.

Cons:

- The new hash is slightly more expensive than the old one, since we're no longer making use of the `rol` optimization. There are a couple more instructions now (`mov`, `shl`, `add`, `mov`, `shr`, `lea`, `xor`), when before there was only `mov`, `rol`, `add`, `mov`, `xor`. I also had to add `AggressiveInlining` to get the JIT to inline the method. However, the virtual method calls to EqualityComparer should far outstrip any perf regression from 2 extra 1-cycle instructions.

## Collision testing

I used [this code](https://gist.github.com/jamesqo/eac5350b25f59dc4bb90b53ed1e77a02#file-collisiontesting-cs) to test collisions with the new vs. the old algorithm; you can see the results in the same file. For randomly generated numbers (not the very specific case of some elements being 0, where the new one wins), the new/old algorithms seem to be about neck-and-neck in terms of hash collisions.

## Licensing

I updated THIRD-PARTY-NOTICES since I stole the algorithm from Boost. The library in question, Boost.Functional, is licensed under the Boost Software License which is similar to MIT [but with a few differences](http://law.stackexchange.com/questions/91/is-there-any-difference-in-meaning-between-the-boost-and-mit-software-licenses). I don't know much about licensing, so cc @richlander for this.

/cc @jcouv @VSadov @stephentoub, @DenisIstomin for #10668

### CODE REVIEW

**Comment by jcouv** [comment]
@jamesqo I should let you know that the ValueTuple code is going into mscorlib/desktop shortly (hopefully in days) and it will be painful to update ValueTuple afterwards, so we need to lock it down asap.
I'll look at the change on Monday.

**Comment by VSadov** [comment]
The boost hash is possibly a better hash, but i am not convinced it is worth the extra expense. The problems listed do not seem to be big problems.
- tuples of different cardinality are not comparable (Equals is not defined) so their hashes do not need to be compared either
- for variable lengh structures like list, the length is typically the first piece added to the hash. 
We could add cardinality in tuples too, but that is unnecessary since they are distinct incomparable types.
- slight bias towards lower bits vs. full spread is not necessarily a bad thing. It is a fairly common pattern to mask N lower bits to limit the range of a hash.

Also, testing the combining function on completely random input could be misleading.  X[i] ^ X[i+1] ... would be the best choice for that.
Curiois, if input is something like random 1k pairs from a set of numbers 0-1000 and if combined hash is masked to 10 bits - is the boost hash any better in terms of collisions?

**Comment by DenisIstomin** [comment]
@jamesqo, I think that [this code](https://github.com/dotnet/corefx/blob/d0dc5fc099946adc1035b34a8b1f6042eddb0c75/src/System.Runtime.Numerics/src/System/Numerics/NumericsHelpers.cs#L144) should also use `HashHelpers` described above.

**Comment by VSadov** [comment]
What i am saying is that current hash seems good enough for its purpose, while being simpler.

**Comment by jamesqo** [comment]
@VSadov

> i am not convinced it is worth the extra expense.

This "extra expense" will be immeasurable compared to the hashtable/hashset lookup, plus all of the virtual EqualityComparer calls.

> tuples of different cardinality are not comparable

> We could add cardinality in tuples too, but that is unnecessary since they are distinct incomparable types.

What if someone had a `Dictionary<object, T>` and used tuples as the key?

> It is a fairly common pattern to mask N lower bits to limit the range of a hash.

The current implementations of [`Dictionary`](https://github.com/dotnet/corefx/blob/master/src/System.Collections/src/System/Collections/Generic/Dictionary.cs#L286) and [`HashSet`](https://github.com/dotnet/corefx/blob/master/src/System.Collections/src/System/Collections/Generic/HashSet.cs#L225) use `% buckets` to constrain the hash, and since the number of buckets is always prime this will take all bits of the hash into account.

> The problems listed do not seem to be big problems.

There are also other problems in addition to the ones I mentioned earlier:

```cs
var set = new HashSet<Tuple<int, int>>();
set.Add(null);
set.Add(Tuple.Create(0, 0)); // collision
// luckily Dictionary doesn't allow null keys
// but...

public class Rating
{
    public int ThumbsUp { get; }
    public int ThumbsDown { get; }

    public override int GetHashCode() => (ThumbsUp, ThumbsDown).GetHashCode();
}

public class Feedback
{
    public Rating Rating { get; }

    public override int GetHashCode() => Rating?.GetHashCode() ?? 0;
}

// it can still bite in this circumstance
var dict = new Dictionary<Feedback, T>();
var feedbackNoRating = new Feedback();
var feedbackWithRating = new Feedback(new Rating(0, 0));

dict[feedbackNoRating] = ...
dict[feedbackWithRating] = ... // collision: both 0
```

**Comment by tannergooding** [comment]
This new implementation is definitely better than the old one.

However, the boost library itself (http://www.boost.org/doc/libs/1_55_0/doc/html/hash/rationale.html#ftn.hash.rationale.f0) states this should not be used as a 'general-purpose hash function'. That is, for small structures we will achieve results that work and collisions probably won't matter due to the speed of computation/lookup. However, as the size of the tuple grows, the poor distribution/collision properties will likely begin to show.

Since `ValueTuple` can be of arbitrary size/length and (given the built in support for tuples in C#) will likely be used quite frequently for all kinds of things (including being used as the key to a `Dictionary`). I think we should keep the 'naive' implementation for small ValueTuples (where the poor distribution/collision properties won't matter) and look into using one of the more robust 

The `SMHasher` test suite has some really good numbers on the speed/robustness of the various (non-cryptographic) general-purpose, hash functions. I believe that MurmurHash3 and CityHash (Google) are currently the fastest implementations (and both have extremely good distribution/collision properties).

**Comment by jamesqo** [comment]
> That is, for small structures we will achieve results that work and collisions probably won't matter due to the speed of computation/lookup. However, as the size of the tuple grows, the poor distribution/collision properties will likely begin to show.

@tannergooding ValueTuple stops hashing at 8 elements- see [here](https://github.com/dotnet/corefx/blob/master/src/System.ValueTuple/src/System/ValueTuple/ValueTuple.cs#L1915).

**Comment by tannergooding** [comment]
Ah, I was not aware of that implementation detail 😄

**Comment by VSadov** [comment]
@tannergooding - we are not defining a new hash function here. The hash function for a tuple is a combination of hashes of all its elements. We are defining the way to combine those.
We could just xor them, but that gives bad results if elements have the same values or if tuples tend to differ symmetrically (1,2) vs (2,1)
We could put all source hashes in a blob and SHA1 them - that would be expensive.
The assertion here is that the current algo may have a degenerate behavior, detrimental in common enough scenarios to require a more complex Combine function.
I am not sure that is the case though.

**Comment by jamesqo** [comment]
@VSadov I responded to your comment above. This will cause a collision:

```cs
var set = new HashSet<Tuple<int, int>>();
set.Add(null);
set.Add(Tuple.Create(0, 0));
```

as well as the other scenario I mentioned in the comment.

**Comment by jcouv** [comment]
@jamesqo Sorry for the delay getting back to you. Like Vlad, I have mixed feeling on this PR. 

On one hand the new hash function does seem a bit safer (collision-wise). On the other hand the collision scenarios with the existing hash function aren't that compelling in my opinion, the new hash function is a bit more expensive to evaluate, and there are various hurdles (sort out license questions with legal folks, pushing change to mscorlib).

I think I would rather stay with your previous implementation (which is currently committed). Thanks again!

**Comment by jamesqo** [comment]
@jcouv OK, then. Thank you for getting back to me on this.

**Pull request closed without merging**
