### PR TITLE
System.Diagnotics.Activity comments and documentation fixes

### PR DESCRIPTION
**Pull request by lmolkova**
This change improves comments and documentation, as described in PR #16920.

/cc @vancem

### CODE REVIEW

**Comment by vancem** [comment]
LGTM Thanks

**Comment by lmolkova** [comment]
Build failed because of "System.Net.Security.Tests.ClientAsyncAuthenticateTest.ClientAsyncAuthenticate_MismatchProtocols_Fails" test, not related to this change and tracked in #16968

**Comment by stephentoub** [comment]
@dotnet-bot test Innerloop Windows_NT Release x64 Build and Test please (#16968)

**Comment by karolz-ms** [comment]
@lmolkova FWIIW LGTM too

**Pull request merged**
