### PR TITLE
Removed DumpHeaders dependency & coded to avoid unnecessary splitting

### PR DESCRIPTION
**Pull request by rajansingh10**
modified:   System/Net/Http/Unix/CurlHandler.cs
I messed up while updating the changes in remote branch. Tried to fix that but could not. Will figure out what caused the issue. Sending new PR with updated changes. Copying the comments here.
Sorry for any inconvenience.

### CODE REVIEW

**Comment by rajansingh10** [comment]
Stephen:-

Does curl require that each header be added individually? If not, from looking at WinHttpHandler code it seems like this method could just be:

rawHandle = Interop.libcurl.curl_slist_append(rawHandle, headers.ToString());
handle.SetHandle(rawHandle);
?

Also, I just looked at the docs for curl_slist_append, which state:
"A null pointer is returned if anything went wrong, otherwise the new list pointer is returned."
So here and anywhere else we're using it we should be validating the result.

Rajan:-

I have added a null check wherever, curl_slist_append is being used. 
Regarding each header being added individually, all the blogs & helper doc points to adding individually. But I have validated a simple get by passing all headers at once. It was working.
But since this require a more elaborate testing with other options, I am not putting that as a part of this PR. I will test & fix that as part of different PR.

**Comment by rajansingh10** [comment]
cc: @stephentoub

**Comment by stephentoub** [comment]
LGTM

**Comment by davidsh** [comment]
cc: @CIPop @SidharthNabar

**Pull request merged**
