### PR TITLE
Renaming ZeroFreeMemoryUTF8 to ZeroFreeCoTaskMemUTF8

### PR DESCRIPTION
**Pull request by tijoytom**

### CODE REVIEW

**Comment by tijoytom** [comment]
@yizhang82 FYI

**Comment by weshaggard** [comment]
> error : MembersMustExist : Member 'System.Runtime.InteropServices.Marshal.ZeroFreeCoTaskMemUTF8(System.IntPtr)' does not exist in the implementation but it does exist in the contract. 

You need to fix the mscorlib.cs file in coreclr first, that is why the APICompat is failing.

**Comment by tijoytom** [comment]
@weshaggard @yizhang82 
The mscorlib in coreclr is merged , how do i propagate the change to corefx?
https://github.com/dotnet/coreclr/pull/6561

**Comment by weshaggard** [comment]
Looks like your coreclr change is what is blocking the PR to update CoreCLR version. See https://github.com/dotnet/corefx/pull/10552. Can you please do the update of CoreCLR version as part of this change? Just update the version in dir.props and run `build.cmd /p:UpdateInvalidPackageVersions` and it will fix all the project.json files.

**Comment by gkhanna79** [comment]
@tijoytom Can you please look into getting this resolved asap as it is blocking CoreCLR adoption in CoreFX?

**Comment by tijoytom** [comment]
@weshaggard @gkhanna79  To make sure i am doing the right thing ..

<CoreClrExpectedPrerelease>beta-24403-05</CoreClrExpectedPrerelease>
then  build.cmd /p:UpdateInvalidPackageVersions

but msbuild says 
MSBUILD : error MSB1006: Property is not valid.
Switch: UpdateInvalidPackageVersions

**Comment by tijoytom** [comment]
@weshaggard @gkhanna79 
PTAL

**Comment by tijoytom** [comment]
@dotnet-bot retest Innerloop Windows_NT Release Build and Test

**Comment by weshaggard** [comment]
LGTM 

Please fix the conflict and lets get this merged.

**Pull request merged**
