### PR TITLE
Filter out missing RIDs from official test builds.

### PR DESCRIPTION
**Pull request by jhendrixMSFT**
We don't yet have packages for Fedora 23, OpenSuse 13.2 andUbuntu 16.04,
as a result our official test builds fail.  To unblock the test build I
have added a mechanism to filter out RIDs during test project.json
generation.  Once the packages are available the change in dir.props
should be removed.

### CODE REVIEW

**Comment by ellismg** [comment]
Can you please add "opensuse.13.2-x64" to the mix?  The fact that you aren't hitting the problem right now is because I have a bad entry in our runtimes section (it's just "opensuse.13.2") so I think you are going to have problems once I fix that.

**Comment by jhendrixMSFT** [comment]
@ellismg Thanks Matt I've added opensuse.13.2-x64 to the list.

**Comment by jhendrixMSFT** [comment]
We no longer need to filter out the RIDs now that we have https://github.com/dotnet/corefx/commit/6d6f5bf35a567dfb0cb5c0554b608693a9f76a54 however we still need the build tools update to fix a bug that's blocking the official build.

**Pull request closed without merging**
