### PR TITLE
 Mark applicable structs as readonly

### LINKED ISSUE #24900: Nullable<T> must be a readonly struct
`Nullable<T>` is known to be an immutable struct with sideeffect-free methods.
C# compiler certainly relies on the implied purity for the soundness of null-propagating math as well as in various optimizations.

Basically - while for other structs `readonly` is a good thing to have, if possible. I think the spec for `Nullable<T>` should _demand_  that `Nullable<T>` is formally `readonly`.

In particular we consider methods like `HasValue` not mutating and therefore callable directly on references to readonly fields (which is currently unverifiable). When verification rules are updated to understand readonly references, we would need to special case `Nullable<T>` methods. - Unless the type is `readonly` by the spec, then the behavior would be subsumed by the general treatment or `readonly` structs.

### PR DESCRIPTION
**Pull request by stephentoub**
Fixes #24900
Related to https://github.com/dotnet/coreclr/pull/14789
Related to https://github.com/dotnet/corert/pull/4855

cc: @jkotas, @jaredpar, @VSadov, @tmat for System.Reflection.Metadata (which has the bulk of the changes)

### CODE REVIEW

**Comment by marek-safar** [comment]
I am wondering if this is potentially a breaking change. The runtimes don't ensure that the struct is read-only but C# compiler assumes that. Therefore in a scenario where read-only struct is used in pinvoke and actually modified are we sure the side effects are always visible?

**Comment by stephentoub** [comment]
> I am wondering if this is potentially a breaking change. The runtimes don't ensure that the struct is read-only but C# compiler assumes that. Therefore in a scenario where read-only struct is used in pinvoke and actually modified are we sure the side effects are always visible?

Can you provide an example?
cc: @jaredpar, @VSadov

**Comment by marek-safar** [comment]
I don't right now but possibly something like this where you pass in readonly version instead of non-readonly version and runtime decides to optimize/flow it differently.

```
readonly struct Foo
{
	public readonly int foo;
}

class X
{
	[DllImport ("foo.dll")]
	static extern void Foo (ref Foo foo);
}
```

**Comment by stephentoub** [comment]
> possibly something like this

@jaredpar or @VSadov could likely answer better, but from my perspective, in your example you can already do that with readonly fields (just remove the 'readonly' from the struct itself), and it's not really any different from that.  Interop is inherently unsafe and allows you to break out of whatever language/runtime enforcement exists.

**Comment by stephentoub** [comment]
@dotnet-bot test Linux x64 Release Build please (https://github.com/dotnet/corefx/pull/25004)

**Comment by jkotas** [comment]
Also, you can change readonly fields via reflection today. Runtime is not enforcing readonliness for reflection access either.

C# readonly is pretty similar to C++ const in this sense. There are number of ways how one can step around it.

**Comment by VladimirReshetnikov** [comment]
Making `System.Nullable<T>` a readonly struct would be a breaking change. Consider the following program:

```
using System;

struct S
{
    int x;

    public override string ToString()
    {
        x = 5;
        return "";
    }

    static void Main()
    {
        S? s = new S();
        Console.WriteLine(s.Value.x); // 0
        s.ToString();
        Console.WriteLine(s.Value.x); // 5
    }
}
```

If `System.Nullable<T>` were a readonly struct, both lines would print `0`.

**Comment by stephentoub** [comment]
Thanks for calling this out, @VladimirReshetnikov.  It's not so much making `Nullable<T>` readonly that's the problem, but rather changing its value field to be readonly (and then the type can't be readonly).  I've put up a PR to revert it.

**Comment by jkotas** [comment]
This change is just one of the hundreds of performance improvements in .NET Core 2.1. The "what's new" blogs mention the most signficant improvements only. It is not practical for them to mention every single performance improvement. This change is certainly nice, but pales in comparison with many other more significant ones.

.NET Framework updates receive targeted improvements only. Marking types readonly can introduce unexpected behavior changes as we have learned hard way when we marked `Nullable<T>` as readonly and then undone it. I do not expect that this change will be ever coming to .NET Framework 4.x because of the compat risk.

**Pull request merged**
