### PR TITLE
Reenabling some expression tests

### PR DESCRIPTION
**Pull request by bartdesmet**
This reenables tests for issues #4021, #4018, #4020, and #3164. Also see #3995 for the master issue on adding more tests for the expression interpreter.

### CODE REVIEW

**Comment by bartdesmet** [comment]
Also addressing some whitespace issues with generated test code.

**Comment by bartdesmet** [comment]
Hitting a seemingly unrelated error:

```
Regression

RenamedTests.FileSystemWatcher_Moved_NestedDirectoryRoot (from (empty)) 

Failing for the past 1 build (Since Failed#5551 ) 

Took 40 ms.



Stacktrace
MESSAGE:
System.UnauthorizedAccessException : Access to the path '\\?\d:\j\workspace\dotnet_corefx_windows_release_prtest\bin\tests\Windows_NT.AnyCPU.Release\System.IO.FileSystem.Watcher.Tests\dnxcore50\FileSystemWatcher_Moved_NestedDirectoryRoot\test_root' is denied.
+++++++++++++++++++
STACK TRACE:
at System.IO.Win32FileSystem.RemoveDirectoryHelper(String fullPath, Boolean recursive, Boolean throwOnTopLevelDirectoryNotFound) at System.IO.Win32FileSystem.RemoveDirectory(String fullPath, Boolean recursive) at TemporaryTestDirectory.Dispose() in d:\j\workspace\dotnet_corefx_windows_release_prtest\src\System.IO.FileSystem.Watcher\tests\Utility\TemporaryTestDirectory.cs:line 32 at RenamedTests.FileSystemWatcher_Moved_NestedDirectoryRoot() in d:\j\workspace\dotnet_corefx_windows_release_prtest\src\System.IO.FileSystem.Watcher\tests\FileSystemWatcher.Renamed.cs:line 122
```

**Comment by bartdesmet** [comment]
@dotnet-bot test this please

**Comment by stephentoub** [comment]
LGTM

**Pull request merged**
