### PR TITLE
Throw correct exception when Enumerable.Cast null to non-nullable

### LINKED ISSUE #2947: Enumerable.Cast() throws wrong exception in casting null to non-nullable value-type.
Enumerable.Cast() is documented as throwing:

`ArgumentNullException`: source enumerable is null.
`InvalidCastException`: (upon enumerating) an element in the sequence cannot be cast to the requested type.

If however a null element is in a sequence being cast to a non-nullable value-type, the exception thrown is `NullReferenceException`, which is both not documented, and an inappropriate exception in any case as the calling code has not directly used a null reference.

Example:

    new int?[]{1, null}.Cast<int>().ToList()

### PR DESCRIPTION
**Pull request by JonHanna**
Fixes #2947

### CODE REVIEW

**Comment by akoeplinger** [comment]
I'd separate out the migration of the legacy tests to xunit in another PR, so it doesn't get mixed up with your exception fix (which I guess needs to be discussed whether it's appropriate to change behavior).

**Comment by akoeplinger** [comment]
Ah sorry, you already did that, I'm dumb :sob:

**Comment by stephentoub** [comment]
cc: @VSadov

**Comment by stephentoub** [comment]
If the decision is this is the behavioral change make, the change LGTM.  @VSadov?

**Comment by stephentoub** [comment]
Closing per discussion on the associated issue.  Thanks.

**Pull request closed without merging**
