### PR TITLE
Fix LinuxCross Portable Build

### PR DESCRIPTION
**Pull request by gkhanna79**
Fixes https://devdiv.visualstudio.com/DefaultCollection/DevDiv/_build?_a=summary&buildId=649339

@weshaggard PTAL. Can you also help me understand why this is unique to Portable CrossBuild I introduced and not Linux-x64 Portable build though the definition structure is the same?

### CODE REVIEW

**Comment by Petermarcu** [comment]
I noticed in the error that there are actually two things duplicated. Are we sure fixing one won't just expose the other? 

`-buildArch=arm -Release -buildArch=arm -Release -portable`

**Comment by gkhanna79** [comment]
@Petermarcu Your question is the reason why I have asked @weshaggard my question. I would like to understand how this configuration system works.

I do suspect that the duplicate `-Release` maybe because of https://github.com/dotnet/corefx/pull/17742/files#diff-c9539d529b27144215b930ab94c59342L141. 

However, I do not follow why `-buildArch` was specified twice.

**Comment by gkhanna79** [comment]
Looking at the generated build defintion, it seems that PB_Arguments only needs to be additional arguments.

**Comment by gkhanna79** [comment]
Also, @weshaggard, while we set PB_SyncArguments, I do not see them getting used in the generated build definition's sync step  (see https://devdiv.visualstudio.com/DefaultCollection/DevDiv/_build/definitionEditor?definitionId=5244&_a=simple-process). 

How would sync do a portable sync in such a case?

**Comment by gkhanna79** [comment]
I have pushed another update that sets PB_Architecture (like other cross build definitions) to avoid passing a second -buildArch. 

@weshaggard What do you think? also, is there documentation around how this checked-in build definition is supposed to work?

**Comment by gkhanna79** [comment]
I am merging this to see if it helps.

**Comment by weshaggard** [comment]
cc @chcosta who knows most about the checked in build definitions. I think there are still lots of inconsistencies and duplications which is why I filed https://github.com/dotnet/corefx/issues/16161. 

As for your first question see the differences between the actual build definitions:
https://github.com/dotnet/corefx/blob/master/buildpipeline/DotNet-CoreFx-Trusted-Linux-Crossbuild.json#L194
https://github.com/dotnet/corefx/blob/master/buildpipeline/DotNet-CoreFx-Trusted-Linux.json#L194

Similar for the sync question the linux-cross build doesn't seem to use the SyncArguments. https://github.com/dotnet/corefx/blob/master/buildpipeline/DotNet-CoreFx-Trusted-Linux-Crossbuild.json#L176.

**Pull request merged**
