### PR TITLE
[x86/Linux] Change processor name from x86 to i686 in cmake

### PR DESCRIPTION
**Pull request by seanshpark**
As CMAKE_SYSTEM_PROCESSOR is eq to "uname -p" need to change to i686
To match with CoreCLR which uses i686

### CODE REVIEW

**Comment by seanshpark** [comment]
cc @lucenticus , @parjong

**Comment by seanshpark** [comment]
Need to clean project before building.
```
./build.sh -CleanAllProjects
```

**Comment by seanshpark** [comment]
@dotnet-bot test Innerloop Windows_NT Debug Build and Test please

**Comment by seanshpark** [comment]
@mellinoe, @janvorli , PTAL

**Comment by mellinoe** [comment]
LGTM, thanks for the fix / consistency.

**Comment by seanshpark** [comment]
Thank you.

**Pull request merged**
