### PR TITLE
Enable dotnet test by routing to /t:BuildAndTest

### PR DESCRIPTION
**Pull request by ViktorHofer**
Fixes https://github.com/dotnet/corefx/issues/35011

cc @hughbe

### CODE REVIEW

**Comment by ericstj** [comment]
Did you consider putting this in the CoreFx testing package?  I'd expect to live here: https://github.com/dotnet/arcade/blob/d37430d5f902154260b1d924d385b16c0929c290/src/Microsoft.DotNet.CoreFxTesting/build/core/test/Test.targets#L168

**Comment by ViktorHofer** [comment]
As I need to overwrite the target I'm not sure if that works.

**Comment by ericstj** [comment]
I see, yeah if the order of evaluation doesn't work I can see that being a problem.  I don't suppose you can make it work without overriding?

**Comment by ViktorHofer** [comment]
No currently not. For that to work we would need to switch away from xunit.console to vstest. There's an issue tracking that but currently not on my radar. Enabling project restore in test project could also be necessary, not sure. I think the current approach is ok.

**Comment by ericstj** [comment]
Ok.

**Pull request merged**
