### PR TITLE
[no merge] [WIP] Add perf testing

### PR DESCRIPTION
**Pull request by adiaaida**

### CODE REVIEW

**Comment by stephentoub** [comment]
@adiaaida, can you provide more details about what this is?  Thanks.

**Comment by adiaaida** [comment]
I guess I forgot to mark this as a draft PR, which is what this is. I am testing a template that I am working to add to arcade that will control much of performance testing to make sure it works with corefx's builds in the lab.

**Comment by ViktorHofer** [comment]
@adiaaida what's the status on this?

**Comment by adiaaida** [comment]
I am going to close this one and opening a new PR where the perf runs are in their own pipeline. We are still waiting for all of the new perf machines to be added to the appropriate queues, so that this the delay. When the new queues are ready, I will put out a new PR.

**Pull request closed without merging**
