### PR TITLE
Remove lockfiles, update dependency versions, and add dependency upgrade/validation tooling

### PR DESCRIPTION
**Pull request by dagood**
This removes `project.lock.json` files and makes it reasonable to have repeatable builds without them. Makes tooling described in https://github.com/dotnet/buildtools/pull/345 available in corefx: this tooling makes it easy to upgrade packages (alternative to `dnu restore --lock`) and validates that the set of dependencies in corefx stays up to date by checking some rules during builds.

There are a few small fixes I made to things that came up because I had to upgrade a bunch of packages.

I'd suggest looking at the individual commits, since I touched a bunch of files. I did some rebasing to try to make this easier to review.

/cc @ericstj @weshaggard

### CODE REVIEW

**Comment by dagood** [comment]
Hmm, I just noticed that this package doesn't exist: https://github.com/dagood/corefx/commit/df98b756c6134d3ac60a555c42a9873bc6baa0bc#diff-6f96638be0e7a224da3e5a163abbaa64R5 (The lockfile resolves to `4.0.0`)

I'm going to try to find more of these to fix by scripting something quick that goes through the dependencies and looks for any that don't exist.

**Comment by mellinoe** [comment]
Could you give a summary of what the new workflow for updating things will be? One thing I'm curious about is whether we need to manually update the values in dir.props, or does the tooling take care of that too? I assume not since it would be a bit silly / complicated to edit the xml file in place.

So is the workflow basically:

1. Update the dir.props file with whatever new value you want
2. Run a command like this (taken from the buildtools PR): `msbuild /t:UpdatePrereleaseDependencies /p:OldPrerelease=beta-45678;NewPrerelease=beta-45679`
3. Build the repo

Or is there some command like `msbuild /t:UpdateDependencies` which just reads the values out of dir.props for you?

**Comment by stephentoub** [comment]
@dotnet-bot test this please

**Comment by dagood** [comment]
@mellinoe Those steps are correct, and currently upgrading would require editing dir.props and running the upgrade target separately. Flowing from the validation rules to dependency update makes a lot of sense though, and could actually be a fairly small change to the buildtools task. (Earlier I thought about this but I only thought about writing the XML, which I agree isn't a great way to go.)

The only difference in behavior I see with that suggestion is that an "upgrading validate" is a bit less explicit, since it would change all versions to the valid version rather than just doing a specified version->version upgrade. That seems fine to me, though, since those extra packages wouldn't have been valid and would need to be changed anyway. @ericstj Is there more to consider here, or should I go ahead with this?

Back to the workflows, another one is upgrading a prerelease dependency when the package has also had its version bumped. Let's say the packages available are System.Foo `4.0.0-beta100` and `4.0.1-beta101`. After a prerelease update, when all beta100 -> beta101, System.Foo is left at `4.0.0-beta101`, which doesn't exist. To fix this:

    msbuild /t:UpdatePackageDependencyVersion /p:PackageId=System.Foo;OldVersion=4.0.0-beta101;NewVersion=4.0.1-beta101

This is a little rough because whoever's upgrading the prereleases needs to know if any major/minor/patch versions have changed. (If I'm not mistaken this isn't any better with * dependencies.) I'm planning on adding a validation check in future buildtools/corefx changes to make sure all dependencies actually exist, and it might be reasonable to make this a self-correcting validation step like the earlier stuff. This isn't as simple, though.

Does that help clarify things?

**Comment by mellinoe** [comment]
That sounds fine to me, certainly not worse than the current situation. Could we add a description of what the steps are in one of the Documentation files? I will definitely forget the exact syntax by the time I need to use it. Maybe you already added one, I can't see the whole diff on GitHub :smile: .

@weshaggard We should probably try to push these changes through as merge conflicts will probably pile up if we leave it. Also, my changes will conflict with this, but I can just re-run my generation tool on top of these changes so it probably makes sense to put this one through first.

**Comment by dagood** [comment]
I have changes here that will enable the simplified flow: https://github.com/dotnet/buildtools/pull/361

@mellinoe I haven't added that yet, definitely should and will, thanks.

**Comment by dagood** [comment]
@dotnet-bot test this please

**Comment by weshaggard** [comment]
LGTM - please squash and get this in as soon as possible to avoid the conflicts. We can do the UpdateDependencies build tools update as a separate change.

**Comment by dagood** [comment]
@dotnet-bot test this, please

**Comment by dagood** [comment]
Merged. The error for OpenSUSE didn't look like it could be caused by this (couldn't actually tell what it was, but it did seem to compile everything before it happened) and other platforms built successfully but Jenkins didn't seem to be running the tests on them.

**Comment by nguerrera** [comment]
:clap: Thanks!

**Pull request merged**
