### PR TITLE
Add more Complex::Cos test data

### PR DESCRIPTION
**Pull request by marek-safar**

### CODE REVIEW

**Comment by stephentoub** [comment]
@dotnet-bot test Innerloop Windows_NT Debug x86 Build and Test please (https://github.com/dotnet/corefx/issues/17104)

**Comment by stephentoub** [comment]
```
     System.Numerics.Tests.ComplexTests.Cos_Advanced(real: 1.79769313486232E+308, imaginary: -1.79769313486232E+308, expectedReal: Infinity, expectedImaginary: Infinity) [FAIL]
        Failure at line 534. Expected real: Infinity. Actual real: -Infinity
        Expected: True
        Actual:   False
        Stack Trace:
           D:\j\workspace\windows_nt_re---37265eab\src\System.Runtime.Numerics\tests\ComplexTests.cs(1721,0): at System.Numerics.Tests.ComplexTests.VerifyRealImaginaryProperties(Complex complex, Double real, Double imaginary, Int32 lineNumber)
           D:\j\workspace\windows_nt_re---37265eab\src\System.Runtime.Numerics\tests\ComplexTests.cs(535,0): at System.Numerics.Tests.ComplexTests.Cos_Advanced(Double real, Double imaginary, Double expectedReal, Double expectedImaginary)
```
cc: @mellinoe

**Comment by marek-safar** [comment]
This appears to be a regression in https://github.com/dotnet/corefx/commit/3d5508c7ac94d6b143791c8096e90505ee87fac5 compare to .NET Framework

**Comment by danmosemsft** [comment]
@dcwuser

**Comment by dcwuser** [comment]
The last new test assertion is incorrect. The behavior of Cos(x+iy) for large x and y is governed the the behavior of sinh and cosh, which blow up according to cosh(y) -> +inf and sinh(y) -> sgn(y) * inf, and the behavior of sin and cos, which continue to oscillate. The upshot is that Cos(x + i y) -> cos(x) * inf - sin(x) * sgn(y) * inf. It turns out -- I just checked in Mathematica -- that cos(max) is negative and sin(max) is positive, so
  Cos(+max, +max) -> cos(max) * inf - sin(max) * +inf = (-inf,-inf)
  Cos(-max, -max) -> cos(max) * inf + sin(max) * -inf = (-inf,-inf)
  Cos(-max,+max) -> cos(max) * inf + sin(max) * +inf = (-inf,+inf)
  Cos(+max,-max) -> cos(max) * inf - sin(max) * -inf = (-inf, +inf)
The second new test assertion is Cos(+max,-max) = (+inf, +inf), which is at odds with this analysis.

I am not a fan of these tests, because they depend on the behavior of Sin and Cos for large arguments, which has not been consistent across versions of the framework, and may not even be consistent across hardware. The documentation for Sin and Cos even says not to trust the output for arguments larger than ~1.0E20, because it used to be that the functions did not even attempt to compute the trig functions, but instead simply return the argument unchanged. It could well be that @tannergooding's check-in fixing this bad behavior is actually the cause of this "regression", since under the old bad behavior cos(+max) was +max, a positive number, which would have made Cos(+max,-max) return (+inf, +inf).

At very least these tests should be modified to use Sin(x), Cos(x), and Sign(y), and it's probably better to drop them all-together.

**Comment by mellinoe** [comment]
@tannergooding You've had good thoughts about boundary behaviors, any opinion here?

**Comment by tannergooding** [comment]
The tests should likely match the current CoreCLR behavior and we should have them. We can always update the boundary tests when/if the functions are updated to be IEEE compatible for the inputs/outputs.

Realistically, for any math function that uses floating-point values, there should be tests that cover the following areas:
* Positive and Negative Infinity
* Quiet and Signaling NaNs
* Positive and Negative Zero
* Subnormal Values
* Normal Values

For tests which have a known domain, we should also test:
* The minimum and maximum inputs
* Values where the bit representation is one lower/higher than the min/max inputs
* A selection of values over the domain, ensuring the results are within the precision requirements we have for the function

**Comment by tannergooding** [comment]
The last requirement (testing a selection of values) is really just important to validate the cross-platform implementations are relatively inline with each-other.

**Comment by dcwuser** [comment]
You can re-write these tests in a way that both the old .NET Framework and the new correct behavior will satisfy, even though they are returning different results. For example, the final new test assertion should be:
`yield return new object[] { double.MaxValue, double.MinValue, Math.Cos(double.MaxValue) * double.PositiveInfinity, -Math.Sin(double.MinValue) * Math.Sign(double.MinValue) * double.PositiveInfinity }`
(That's not compile-tested so beware typos.) Of course, a test that passes even tough the result changes is less stringent and therefore arguably less valuable, but it does still test for consistency between complex and real trig functions.

**Comment by mellinoe** [comment]
@marek-safar Could you please fill out some information about what you're hoping to accomplish with this? Please take into account the context from the commit / PR you have linked.

**Comment by marek-safar** [comment]
@mellinoe I am trying to understand how to fix some of existing tests to work on multiple platforms and be accepted. For example, is this test "wrong" based on discussion above https://github.com/dotnet/corefx/blob/94884ac7bb7a35b240c6064cf50c3bd52cbd7e47/src/System.Runtime.Numerics/tests/ComplexTests.cs#L557 ?

**Comment by dcwuser** [comment]
It's certainly "wrong" if you want your test to be robust to the outputs of Math.Sin and Math.Cos.

Whether it's wrong mathematically depends on analyzing what those values should be. Since cosh(z) = cos(iz), the previous result cos(x + i y) -> cos(x) * inf - i sin(x) * sgn(y) * inf implies that cosh(x + i y) = cos(-y) * inf - i sin(-y) * sgn(x) * inf = cos(y) * inf + i sin(y) * sgn(x) * inf. Since, again as noted above, cos(m) is negative and sin(m) is positive, and cos is an even function and sin is an odd function, Cos(-m, -m) should equal (-inf,+inf). So the line, as written, is mathematically correct.

If you want the test to be robust to changed outputs of Math.Sin and Math.Cos, you would write the line as
`{ double.MinValue, double.MinValue, Math.Cos(double.MinValue) * double.PositiveInfinity, Math.Sin(double.MinValue) * Math.Sign(double.MinValue) * double.PositiveInfinity }`
which is the same as the above, if the signs of Math.Sin and Math.Cos are what they should be.

You can derive expressions like this for all the complex trig functions, and similar ones for other complex functions such as the arc-trig functions and square root, but you will have to dust off a textbook with the definitions of the complex functions and your high-school math skills. What is definitely the wrong way to write these tests is to look at what's coming out of NETFX now, and write a test asserting that it should stay that way. Almost all the complex functions in NETFX currently have problems with their large-argument behaviors.

**Comment by dcwuser** [comment]
Oh, and one minor style ask: if you are messing with these functions, it would be easier to read "-double.MaxValue" than "double.MinValue". They are bit-equivalent, but the former makes it obvious that the value is negative, and every time you read the latter, your brain has to think "now does that mean the largest negative value (-10^-308) or the smallest positive values (10^-324)?"

**Comment by mellinoe** [comment]
> @mellinoe I am trying to understand how to fix some of existing tests to work on multiple platforms and be accepted.

Different platforms have different behavior, so this proposed change isn't going to work everywhere, unfortunately.

> For example, is this test "wrong" based on discussion above https://github.com/dotnet/corefx/blob/94884ac7bb7a35b240c6064cf50c3bd52cbd7e47/src/System.Runtime.Numerics/tests/ComplexTests.cs#L557 ?

Yes, the discussion above covers it. We could see whether expressing the expected results in terms of other transcendental functions works, but that might be straying a bit too close to "reimplementing the algorithm in the test" to be useful.

For this particular case, I think I would prefer that we just encode different expected values for different platforms. We already have test cases with "Legacy" in the name which are intended to validate the legacy behavior of .NET Framework. You could add to that test case (or create a new one if there isn't a "Legacy" one for `Cos`) to ensure that .NET Framework behavior stays the same.

**Comment by mellinoe** [comment]
@marek-safar While extra test coverage is always good, in this case I think we need to change where it is added a little bit in order to make sure we're only running these test cases where they make sense. Were you planning on updating this PR?

**Comment by marek-safar** [comment]
@mellinoe I'd like to get this one and more of existing tests fixed to work cross platform

**Comment by tannergooding** [comment]
@marek-safar, you essentially need to create legacy and new versions of the tests. For example, in the `System.Math` tests, we have: https://github.com/dotnet/corefx/pull/17217/files#diff-19973eb77d5f57cf6c8661e7fe588dc9R898 and https://github.com/dotnet/corefx/pull/17217/files#diff-19973eb77d5f57cf6c8661e7fe588dc9R948.

That is, we have the shared tests which should pass on either, and then we have a set of scenarios which are only expected to pass on .NET Core and a set of scenarios which are only expected to pass on .NET Framework.

If/when we ever merge the fixes back into .NET Framework, we can then remove the legacy tests entirely.

**Comment by mellinoe** [comment]
What @tannergooding said is correct. I also envision that we may keep around the "legacy" tests indefinitely in order to validate quirked behavior on the .NET Framework,and use the "regular" .NET Core tests when un-quirked.

**Comment by mellinoe** [comment]
As discussed above, I think this needs some further thinking and a bit of a rework. But I do support the addition of extra test coverage where it makes sense. Feel free to re-open if you address the stuff above.

**Pull request closed without merging**
