### PR TITLE
Cleanup AssociationAttributeTests

### PR DESCRIPTION
**Pull request by hughbe**
This is Obsolete, but worth cleaning up as part of a series of cleanups.

There are a whole bunch of bugs that I've found, but they are not worth fixing for compat reasons

### CODE REVIEW

**Comment by hughbe** [comment]
Test Windows_NT Debug Build and Test

**Comment by hughbe** [comment]
Test Innerloop Windows_NT Debug Build and Test

**Comment by jasonwilliams200OK** [comment]
The CI failure in http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/master/job/windows_nt_debug_prtest/3635/consoleFull reports:

> ---- System.ComponentModel.Win32Exception : The credentials supplied to the package were not recognized

**Comment by stephentoub** [comment]
Test Innerloop Windows_NT Debug Build and Test  please

**Comment by stephentoub** [comment]
LGTM

**Comment by stephentoub** [comment]
Test Innerloop Windows_NT Debug Build and Test please

**Comment by hughbe** [comment]
Test Innerloop Windows_NT Debug Build and Test

**Pull request merged**
