### PR TITLE
Improve code coverage for System.Globalization.Extensions

### LINKED ISSUE #926: Improve code coverage for System.Globalization.Extensions
According to the current code coverage report, this library is only at 51%.  Our general goal is closer to 90%, though this will depend on the library.  We should investigate to see whether the current coverage level is appropriate, and if not, improve our test suites to provide better coverage.

### PR DESCRIPTION
**Pull request by bpschoch**
Fix #926

### CODE REVIEW

**Comment by ellismg** [comment]
Thanks for doing this! I made a few small comments.

**Comment by bpschoch** [comment]
"NIT: You might just us a NoCase suffix here on the variable names, to align with the others"

Please expand on this,  Not sure exactly you were pointing to.
...
Will move the embedded nulls to the Embeddednulls test.

Will convert to using U+xxxx escape for unicode literal

**Comment by stephentoub** [comment]
LGTM

**Comment by stephentoub** [comment]
@dotnet-bot test this please

**Pull request merged**
