### PR TITLE
Update projectn-tfs* package dependencies

### PR DESCRIPTION
**Pull request by zamont**
Update dependencies.props to point projectn-tfs* packages to the release/uwp6.0 branch in dotnet/versions

### CODE REVIEW

**Comment by dagood** [comment]
I suppose it's not strictly necessary, but I always recommend running `/t:UpdateDependencies` on PRs like these to make sure the dependencies are in a coherent state in the repo. (To get that to work, you'll need to change `ProjectNTfsCurrentRef` and `ProjectNTfsTestILCCurrentRef` to commit hashes that have the dotnet/versions files.) The `BuildInfoPath` changes look good, though.

You'll also need to add triggers to https://github.com/dotnet/versions/blob/640876b7b36/Maestro/subscriptions.json#L329-L334 so that new uwp builds generate PRs, rather than only doing upgrades when corefx or coreclr build.

**Comment by dagood** [comment]
I missed that in https://github.com/dotnet/corefx/pull/21785, so `CoreFxCurrentRef`, `CoreClrCurrentRef`, and `CoreSetupCurrentRef` need to be updated for a clean `UpdateDependencies` too. (Same hash works.)

**Comment by zamont** [comment]
@dagood Does this look good to you now?

**Comment by dagood** [comment]
Looks good, thanks!

**Pull request merged**
