### PR TITLE
Add more Type tests and make it easier to add new types

### PR DESCRIPTION
**Pull request by hughbe**

### CODE REVIEW

**Comment by danmosemsft** [comment]
This needs more than a cursory review by me. Looks like @pjanotti owns System.Runtime.

**Comment by pjanotti** [comment]
Sorry @hughbe, this fell off my radar. I'll take a look at it today.

**Comment by pjanotti** [comment]
I confirmed that the coverage numbers improve for `System.Type`:

| Type | Line % | Branch % |
| ----- | -------:| -----------:|
| Baseline | 33.7 | 22.7 |
| This PR | 37.6 | 24.7 |

I will merge and will take care of my own nits in a separate PR.

Thanks @hughbe!

**Comment by hughbe** [comment]
Hey sorry for the lack of answering I’ve been  without a computer only with a phone so can’t verify the results thanks!

**Comment by pjanotti** [comment]
No worries, PR was good. I merged it so when you get access to a computer again you can start with something new :smile:

**Pull request merged**
