### PR TITLE
ProcessNameMatchesScriptName: add some asserts for debugging

### PR DESCRIPTION
**Pull request by tmds**
For debugging https://github.com/dotnet/corefx/issues/37739

### CODE REVIEW

**Comment by stephentoub** [comment]
> can you trigger CI to run on Debian 8 and RHEL6?

I believe that's happening.  RHEL6 should be the `corefx-ci (RedHat6 x64_Release)` leg, and I believe Debian should be part of the `corefx-ci (Linux x64_Release)` leg.

**Comment by tmds** [comment]
ok, if it doesn't reproduce in CI here, maybe we can merge it to get some runs.

**Comment by stephentoub** [comment]
Ok, but not while it's a draft ;)

**Pull request merged**
