### PR TITLE
Restored fixes in tests of DateTime serialization

### PR DESCRIPTION
**Pull request by speshuric**
Restore fixes made in #2496 and #2541 in tests of DateTime with UTC offset serialization.
That fixes was overwritten by commit 3f91ae109263904564edaceab039ab55ef2c0518

See #5127 for discussion

### CODE REVIEW

**Comment by stephentoub** [comment]
Test Innerloop Windows_NT Debug Build and Test please

**Comment by stephentoub** [comment]
cc: @khdang, @SGuyGe

**Comment by khdang** [comment]
LGTM

**Comment by SGuyGe** [comment]
LGTM. Thanks Alex!

**Pull request merged**
