### PR TITLE
ConcurrentDictionary: Faster check if lock array should be grown once it shouldn't be grown anymore

### PR DESCRIPTION
**Pull request by dnickless**
If there was such a thing as a nano optimization this would be it. ;)

In `Grow()` I'm setting the - previously readonly - _growLockArray flag to false if the lock array is about to grow to its full allowed size. From that point onwards the check if it should be grown even further during a `Grow()` operation comes down to just checking this one boolean variable as opposed to comparing the `tables._locks.Length < MaxLockNumber` on top of the boolean.

Small change, small effect...

### CODE REVIEW

**Comment by stephentoub** [comment]
> Small change, small effect

Is there any measurable beneficial effect?  It adds code, so I could even see it hurting.

**Comment by dnickless** [comment]
The whole thing is probably not worth the effort really. Oh well, I'm sorry for wasting your time. Let's see what's next. ;)

**Comment by danmosemsft** [comment]
@dnickless don't be discouraged, thanks for the attempt! It may be better to look at profiles of a test scenario, rather than starting from code inspection. Are you interested in perf work in general? I can maybe find some other places that need attention (profiling and improving) based on real data.

**Comment by dnickless** [comment]
@danmosemsft Never mind! It's about night-time here, wife's asleep, kids, too. And I just love that performance stuff. Plus, I work in an industry where performance of (y)our amazing framework matters... But the party's gotta stop when I start wasting other people's time. ;) Anyhoo, bring it on. I'm ready to take some more challenges.

**Pull request closed without merging**
