### PR TITLE
Porting the "RealParser" tests to the also test Utf8Parser

### PR DESCRIPTION
**Pull request by tannergooding**
This is a port of the tests we added to the Utf16Parser in https://github.com/dotnet/corefx/pull/33355

### CODE REVIEW

**Comment by tannergooding** [comment]
CC. @stephentoub, @gafter

**Comment by tannergooding** [comment]
CC. @KrzysztofCwalina, do you know why we throw an exception when specifying a precision with `G`? @GrabYourPitchforks suggested you might remember why...

**Comment by tannergooding** [comment]
@KrzysztofCwalina: https://github.com/dotnet/corefx/blob/master/src/Common/src/CoreLib/System/Buffers/Text/Utf8Formatter/Utf8Formatter.Float.cs#L80

**Comment by tannergooding** [comment]
I have worked around the issue by using `E17` and `E9` for the time being (which are not equivalent, but do allow the tests to work).

I have also logged https://github.com/dotnet/corefx/issues/33501, to track the Utf8Parser not correctly handling large exponents when parsing Double/Single

**Comment by stephentoub** [comment]
Rather than duplicating all of these, could we centralize it?  e.g. have a base test class with all of the theories and that then just calls into abstract methods for the actual work?  Then we'd have a few derived test types, one overriding the abstract method to use Utf8Parser and one overriding to use double.TryParse, etc.

**Comment by tannergooding** [comment]
> Rather than duplicating all of these, could we centralize it

Yes, I'll do that for the "RealParser" tests and log a bug suggesting something similar be done for the rest of the formatting/parsing tests...

**Comment by stephentoub** [comment]
Thanks.

**Comment by tannergooding** [comment]
Made the following changes:
* Moved the tests out of `DoubleTests.netcoreapp.cs` and `SingleTests.netcoreapp.cs` (`System.Runtime.Tests`) and into `RealParserTestsBase.netcoreapp.cs` (shared\Tests)
* Updated `System.Memory.Tests` and `System.Runtime.Tests` to each have a `RealParserTests.netcoreapp.cs` file which inherits from `RealParserTestsBase.netcoreapp.cs` and implements to `InvariantToString` and `InvariantTryParse` methods for `Single` and `Double`
* Logged https://github.com/dotnet/corefx/issues/33507

**Comment by tannergooding** [comment]
@stephentoub, any other feedback?

**Comment by KrzysztofCwalina** [comment]
> @KrzysztofCwalina, do you know why we throw an exception when specifying a precision with G?

Implementing float formatter is tricky, and so I think Ati might have skipped implementing G format precision.

**Comment by tannergooding** [comment]
> Implementing float formatter is tricky, and so I think Ati might have skipped implementing G format precision.

It seems to be skipped even for Integer types, with a note that 'G' with precision can product exponential format:
* https://github.com/dotnet/corefx/blob/master/src/Common/src/CoreLib/System/Buffers/Text/Utf8Formatter/Utf8Formatter.Integer.Signed.cs#L30
* https://github.com/dotnet/corefx/blob/master/src/Common/src/CoreLib/System/Buffers/Text/Utf8Formatter/Utf8Formatter.Integer.Unsigned.cs#L30

**Comment by ahsonkhan** [comment]
> Rather than duplicating all of these, could we centralize it? e.g. have a base test class with all of the theories and that then just calls into abstract methods for the actual work? Then we'd have a few derived test types, one overriding the abstract method to use Utf8Parser and one overriding to use double.TryParse, etc.

I was just recently reading this https://mtlynch.io/good-developers-bad-tests/#dare-to-violate-dry and its relevant here. In practice, I have found tests with abstractions harder to debug and diagnose the root cause of a failure, even when I am familiar with the code. Maybe duplication isn't too bad here. I know @JeremyKuhne had similar concerns when it came to the BufferReader tests in corefxlab. For example, imagine the following test is failing. Try to figure out what it is doing: https://github.com/dotnet/corefxlab/blob/9fc2ddf554009849d41db83315237e714f7695bc/tests/System.Buffers.ReaderWriter.Tests/ReaderBasicTests.cs#L47

It is probably not too bad in this case, but still something to consider when introducing abstractions in tests.

**Comment by stephentoub** [comment]
> Maybe duplication isn't too bad here.

I think it is, actually.  In particular, a) it's way too easy to add test data in one place and forget/neglect/not be aware it's necessary to add it in another, b) it's very difficult to determine whether we're testing all of the cases we want to across all of the things we're testing, and c) it leads to a lot more to maintain.

**Comment by tannergooding** [comment]
I completely agree with Stephen. I just spent a good bit of time ensuring that we could share the parsing/formatting production code, where possible and I feel like getting the tests to do the same has all the same benefits.

**Comment by stephentoub** [comment]
> It can be argued that, for tests specifically, debugging a failure easily might be more important.

I don't believe debugging is at all harmed in this case.  Can you please show me how it is?  What is the debuggability issue this introduces?  The test fails, and from the failure you know what the input data was.  You can run just this test by using the name of the test that fails, which includes the class name and the method name for the failure.  When you step into the virtual method, you step into the derived class' implementation that calls the thing being tested.  I don't see how it's any more complicated.

> How would the abstraction help while duplication hurt measuring code coverage?

Code coverage is insufficient.  All it tells you is that you've executed a given line or a given branch.  It doesn't tell you that you've properly covered all important data inputs that would cause a particular sequence of lines/branches/etc. to fail to produce the right result.  You could remove a bunch of the inputs in this case, and code coverage numbers would not be reduced.

Further, it's not just about avoiding duplication: it's about validating that the same inputs to two different APIs produces the same expected results.

**Comment by ahsonkhan** [comment]
> Can you please show me how it is? What is the debuggability issue this introduces?

It would depend on how the tests are laid out. I agree with you that if we have something like the following, diagnosing the issue is still easy. We know exactly what the input was and what API on which type failed (before even having to run the tests locally under a debugger).

```C#
[Input Data]
void TestingParsing(expected, ...)
{
    Assert.Equal(expected, Utf16.Parse(...));
    Assert.Equal(expected, Utf8.Parse(...));
}
```

But, if the type was hidden behind an abstraction, I would have to run the test myself to know which API is failing. The test failure output wouldn't provide that info.

```C#
[Input Data]
void TestingParsing(expected, ...)
{
    Assert.Equal(expected, ParserDelegate(...));
}
```

I misspoke when I said _debugging_ a failure becomes difficult. I meant finding the general vicinity of the cause of a test failure as a starting point (down to type name/method name) requires running the test locally. But I am realizing now that isn't really an issue, _since we still have a stack trace_ which can provide that info. **So, I retract my previous concern.**

> Further, it's not just about avoiding duplication: it's about validating that the same inputs to two different APIs produces the same expected results.

Good point.

**Pull request merged**
