### PR TITLE
Grab exit codes from bash-subprocesses

### PR DESCRIPTION
**Pull request by mmitche**

### CODE REVIEW

**Comment by mmitche** [comment]
@dotnet-bot test this please

**Comment by mmitche** [comment]
@dotnet-bot test this please

**Comment by mmitche** [comment]
reTEst this please

**Comment by mmitche** [comment]
Test this please

**Comment by mmitche** [comment]
test this please

**Comment by mmitche** [comment]
retest this please

**Comment by mmitche** [comment]
test this please

**Comment by mmitche** [comment]
test this please

**Comment by mmitche** [comment]
restest this please

**Comment by mmitche** [comment]
TEST This PLEASE

**Comment by mmitche** [comment]
test this please

**Comment by stephentoub** [comment]
LGTM

**Pull request merged**
