### PR TITLE
Add ubuntu.XX-arm to runtime.native.XX.pkgproj

### PR DESCRIPTION
**Pull request by jyoungyun**
This patch adds ubuntu.14.04-arm and ubuntu.16.04-arm into
runtime.native.XX.pkgproj

Signed-off-by: chunseoklee chunseok.lee@samsung.com

Related PR : #14655 
(@chunseoklee is on vacation, so I revised it and made another PR.)

### CODE REVIEW

**Comment by jyoungyun** [comment]
subtask for dotnet/core-setup#725

**Comment by jyoungyun** [comment]
@dotnet-bot help

**Comment by jyoungyun** [comment]
@dotnet-bot test Innerloop Ubuntu14.04 Release Build and Test

**Comment by jyoungyun** [comment]
cc/ @gkhanna79 @schellap @ramarag @janvorli

**Comment by gkhanna79** [comment]
LGTM.

@ericstj PTAL as well.

**Comment by mellinoe** [comment]
LGTM. Thanks for continuing the ARM work, @jyoungyun !

**Pull request merged**
