### PR TITLE
No local repro for #23768, re-enabling test

### PR DESCRIPTION
**Pull request by pjanotti**
~~Not to be committed as it is, just to check CI run.~~

Initial tests passed, now trying test in Outerloop.

### CODE REVIEW

**Comment by pjanotti** [comment]
After test CI passed, moving test back to OuterLoop.

@dotnet-bot test Outerloop Linux x64 Debug Build
@dotnet-bot test Outerloop Windows x64 Debug Build
@dotnet-bot test Outerloop OSX x64 Debug Build

**Comment by pjanotti** [comment]
@dotnet-bot test Windows x64 Debug Build

**Comment by davidsh** [comment]
@dotnet-bot Test Outerloop UWP CoreCLR x64 Debug Build

**Comment by pjanotti** [comment]
Failures on Outerloop UWP are unrelated and are happening also on [regular passes](https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Fdesktop~2Fcli~2F/build/20180119.06/workItem/System.Net.WebSockets.WebSocketProtocol.Tests)

**Pull request merged**
