### PR TITLE
[release/1.1.0] Inbox value tuple

### PR DESCRIPTION
**Pull request by ericstj**
Require buildtools update to build w/o validation errors.
https://github.com/dotnet/buildtools/pull/1348

Fixes: #14235 
/cc @jcouv @marek-safar @weshaggard

### CODE REVIEW

**Comment by jcouv** [comment]
ValueTuple is only inbox after a certain version on mono. Should the change be conditional on the version of mono?

**Comment by ericstj** [comment]
This doesn't apply for Mono, that behaves as desktop so its stuck getting the desktop binary.

Xamarin doesn't version their TFMs in a way that lets you target the framework API so those frameworks are stuck getting the behavior of the latest SDKs.

**Comment by ericstj** [comment]
Marking this as NO-MERGE since we need to wait for 1.1.0 to exit lock down and need to add the build-tools update.  This is somewhat dependent on https://github.com/dotnet/corefx/pull/16119 which does the boiler-plate work to version the ValueTuple package for servicing.

**Comment by ericstj** [comment]
Now that https://github.com/dotnet/corefx/pull/16119 is not going in we need to bring over the versioning changes to this PR.

**Comment by ericstj** [comment]
Brought those commits over.  I expect this to fail during package validation until we can get https://github.com/dotnet/buildtools/pull/1348

**Comment by ericstj** [comment]
This is ready to go, @jcouv and @marek-safar can you guys please try `"System.ValueTuple": "4.3.1-servicing-25101-0"` from feed `https://www.myget.org/F/ericstj-staging/api/v3/index.json`?

**Comment by jcouv** [comment]
I've run the tests from `ValueTupleTests.cs` against the package in a .Net Framework 2.0 project (with XUnit 1.9). I think that covers the PCL portion of the package.

I'm now trying to do the same with the .Net Standard portion of the package. But I'm having trouble getting XUnit to work on .Net Standard 1.0 or 1.1. I'll keep you posted.

**Comment by ericstj** [comment]
@marek-safar / @mhutch / @akoeplinger can one of you ack this and do whatever testing you need to make sure it satisfies your ask?  Given this fix is specifically for Xamarin TFMs I want to make sure it gets tested there.

**Comment by jcouv** [comment]
@marek-safar / @mhutch / @akoeplinger Can you validate the change with mono? Thanks in advance.

**Comment by marek-safar** [comment]
@ericstj @jcouv I can confirm that this package works as expected (no compiler errors when System.ValueTuple is used) on Xamarin dev15-2

**Comment by stephentoub** [comment]
@ericstj, can this be merged now?

**Comment by ericstj** [comment]
We have the green light.  Merging

**Pull request merged**
