### PR TITLE
Ignore standard error when querying openssl

### LINKED ISSUE #9272: [Release/1.0.0]System.Net.Security.Tests failing on Opensuse
```
15:50:21   Copyright (C) 2014 Outercurve Foundation.
15:50:21   
15:50:21   Discovering: System.Net.Security.Unit.Tests
15:50:21   Discovered:  System.Net.Security.Unit.Tests
15:50:21   Starting:    System.Net.Security.Unit.Tests
15:50:22   Finished:    System.Net.Security.Tests
15:50:22   
15:50:22   === TEST EXECUTION SUMMARY ===
15:50:22      System.Net.Security.Tests  Total: 97, Errors: 0, Failed: 0, Skipped: 3, Time: 3.204s
15:50:22   Finished running tests. End time=22:51:38. Return value was 0
15:50:22 /mnt/resource/j/workspace/dotnet_corefx/release_1.0.0/opensuse13.2_debug/Tools/tests.targets(202,5): warning MSB3073: The command "/mnt/resource/j/workspace/dotnet_corefx/release_1.0.0/opensuse13.2_debug/bin/tests/Linux.AnyCPU.Debug/System.Net.Security.Tests/netcoreapp1.0/RunTests.sh /mnt/resource/j/workspace/dotnet_corefx/release_1.0.0/opensuse13.2_debug/packages/" exited with code -1. [/mnt/resource/j/workspace/dotnet_corefx/release_1.0.0/opensuse13.2_debug/src/System.Net.Security/tests/FunctionalTests/System.Net.Security.Tests.csproj]
15:50:22 /mnt/resource/j/workspace/dotnet_corefx/release_1.0.0/opensuse13.2_debug/Tools/tests.targets(211,5): error : One or more tests failed while running tests from 'System.Net.Security.Tests' please check log for details! 
```

### PR DESCRIPTION
**Pull request by ellismg**
On some platforms, we get error text from openssl when we query for null
ciphers. The error message is written to standard error and printed in a
way such that MSBuild thinks xUnit has encounted an error and fails the
entire test suite.

To work around this issue, we'll just ignore standard error when we do
this query.

Fixes #9272

### CODE REVIEW

**Comment by ellismg** [comment]
test OpenSuse13.2 Debug Build and Test please
test OpenSuse13.2 Release Build and Test please

**Comment by ellismg** [comment]
test Innerloop OpenSuse13.2 Debug Build and Test please
test Innerloop OpenSuse13.2 Release Build and Test please

**Comment by joshfree** [comment]
Thank you for making this test-only fix to help get to green badges in /release/1.0.0

**Comment by joshfree** [comment]
http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/release_1.0.0/job/centos7.1_release_prtest/14/consoleFull#-1500052166ee26338-6221-4f7c-8c8f-1d1d5cb4704a
```
10:51:14 java.io.IOException: Failed to mkdirs: /mnt/resource/j/workspace/dotnet_corefx/release_1.0.0/centos7.1_release_prtest
10:51:14 	at hudson.FilePath.mkdirs(FilePath.java:1163)
10:51:14 	at hudson.model.AbstractProject.checkout(AbstractProject.java:1269)
10:51:14 	at hudson.model.AbstractBuild$AbstractBuildExecution.defaultCheckout(AbstractBuild.java:607)
10:51:14 	at jenkins.scm.SCMCheckoutStrategy.checkout(SCMCheckoutStrategy.java:86)
10:51:14 	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:529)
10:51:14 	at hudson.model.Run.execute(Run.java:1738)
10:51:14 	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
10:51:14 	at hudson.model.ResourceController.execute(ResourceController.java:98)
10:51:14 	at hudson.model.Executor.run(Executor.java:410)
10:51:14 [xUnit] [INFO] - Starting to record.
10:51:14 [xUnit] [INFO] - Processing xUnit.Net-v2 (default)
10:51:14 [xUnit] [WARNING] - Can't create the path /mnt/resource/j/workspace/dotnet_corefx/release_1.0.0/centos7.1_release_prtest/generatedJUnitFiles. Maybe the directory already exists.
10:51:14 [xUnit] [ERROR] - /mnt/resource/j/workspace/dotnet_corefx/release_1.0.0/centos7.1_release_prtest does not exist.
10:51:14 ERROR: Step ‘Publish xUnit test result report’ aborted due to exception: 
10:51:14 
java.io.IOException: remote file operation failed: /mnt/resource/j/workspace/dotnet_corefx/release_1.0.0/centos7.1_release_prtest at hudson.remoting.Channel@a569db3:Azure0609095326: hudson.util.IOException2: There are some problems during the conversion into JUnit reports: 
```

@mmitche as FYI

**Comment by joshfree** [comment]
@dotnet-bot test Innerloop CentOS7.1 Release Build and Test please

**Comment by mmitche** [comment]
@joshfree On CentOS only, occasionally (haven't seen this in a few months) the resource disk where the builds are done does not get chmodded.  My guess is that it gets attached just slightly too late so the startup script doesn't work.  In these cases,. you can simply delete the VM from Jenkins.

**Comment by mmitche** [comment]
https://github.com/dotnet/dotnet-ci/issues/307

**Pull request merged**
