### PR TITLE
Don't restore packages during the test build

### PR DESCRIPTION
**Pull request by chcosta**
CoreFx companion change for https://github.com/dotnet/buildtools/pull/1071

/cc @weshaggard

### CODE REVIEW

**Comment by chcosta** [comment]
@dotnet-bot test Innerloop Ubuntu14.04 Debug Build and Test

**Comment by weshaggard** [comment]
I'm fine setting this but I wasn't actually seeing restore happening just that the project.json files were getting regenerated.

**Comment by chcosta** [comment]
Corret, the restore wasn't happening during test builds.  I opted to go this way because I wanted to be explicit that a restore wasn't happening during test builds (and isn't expected to happen), and at the same time, if a restore doesn't happen, then we shouldn't be generating a new project.json.

**Comment by weshaggard** [comment]
did you also want this PR to include the buildtools update?

**Comment by chcosta** [comment]
It's not critical to me to update buildtools at the same time.  I'm not opposed to it though.  I'll include that with this as well.

**Comment by weshaggard** [comment]
Yeah I would do them both at the same time.

**Comment by chcosta** [comment]
@dotnet-bot test Innerloop CentOS7.1 Release Build and Test

**Comment by chcosta** [comment]
@dotnet-bot test Innerloop Ubuntu14.04 Release Build and Test

**Pull request merged**
