### PR TITLE
Performance improvement: Make ConcurrentDictionary with Enum values also profit from atomic writes.

### PR DESCRIPTION
**Pull request by dnickless**
Small change to extend the recently introduced performance improvements to the generic ConcurrentDictionary to Enum-value dictionaries, too.

### CODE REVIEW

**Comment by stephentoub** [comment]
@dnickless, can you add tests to go along with this that use an enum as a key (unless we already have some)?

**Comment by danmosemsft** [comment]
The Ubuntu failure is https://github.com/dotnet/corefx/issues/14775 which can be ignored. Not sure how it got thru CI.

**Comment by karelz** [comment]
Blocked on tests

**Comment by dnickless** [comment]
@stephentoub, I'm on the case - just having trouble with your funky build scripts. I have been unable so far to run a full build and unit test session on my machine... I'll get there eventually so bear with me.

**Comment by stephentoub** [comment]
Thanks, @dnickless. Sorry to hear you're having troubles with it.  What errors are you getting?

**Comment by dnickless** [comment]
@stephentoub:

Update: It seems like I have finally reached a stage where I can actually run some tests! Good stuff...

Before I got there, I came across a number of rather obscure error messages trying to run the various commands (build-tests, build, "msbuild System.Collections.Concurrent.Tests.builds", etc.):

- "Error reading JObject from JsonReader" somehow related to project.lock.json files. I think a "clean" helped if I remember correctly.
- then that ugly long list of errors mentioned here: http://stackoverflow.com/questions/27594393/compiled-mono-missing-default-net-libraries-system-object-is-not-defined-or-i

...plus warnings like that:
- "packageDrop does not exist - 'C:\projects\corefx\bin/packages/Debug/"

...and several crashing processes and more (see attached screenshots)

...and finally
- the "build" command doesn't seem to come to an end (perhaps related to all the failing processes?). The last output I can see is "System.Xml.Xsl.XslCompiledTransformApi.Tests  Total: 1627, Errors: 0, Failed: 0, Skipped: 0, Time: 23.945s
Finished running tests.  End time= 1:21:39.48, Exit code = 0"
- during the build/test run, my entire Windows occasionally grinds to a halt for several seconds with a frozen UI, an unresponsive greyed out Start menu with a spinning wait cursor, and no more apps starting up (which simply seems a bit odd looking at the fact that I'm running a 24 core/24GB system).

coreclr exe launcher has stopped working
error msb3021 unable to copy file
vbcscompiler exe has stopped working
your project is not referencing xyz
the type or namespace xyz is not defined

**Comment by stephentoub** [comment]
@dnickless, I'm glad you were able to get the tests running, but I'm sorry to hear you had so many issues along the way; that shouldn't be the case.  @weshaggard, are these known issues?  Someone who could help to investigate why @dnickless was hitting all of these issue?

**Comment by danmosemsft** [comment]
The CI failure is not yours, tracked elsewhere

**Comment by weshaggard** [comment]
@dnickless it sounds like there were some stale files in your local working directory. Can you try running `clean.cmd --all` followed by `build.cmd` and see if that completes successfully?

**Comment by dnickless** [comment]
@weshaggard: I did. And I had done that before, too. Same story, coreclr.exe crashing multiple times, Some other errors did disappear, though, so, yes, my workspace must have been messed up before for some reason.

Oddly enough, while the cmd box with the build was still open (and hanging as described earlier), another unrelated app (a .NET application, mind you, called MultiCharts.NET which I use for algo trading) crashed on me, too. Damn it, I missed a trading day because of that... ;) Oh well. I personally suggest you guys don't bother for now if nobody else observes anything similar. It might as well be that my machine is set up in a particularly unusual way or that some hardware is about to signal its end of life... On the other hand, I had never had those crashes before I attempted to run your build tools. ;)

In the Windows event log, I found 12 occurrences of the following message:
image

Here's the .wer file for one of them:
[Report.zip](https://github.com/dotnet/corefx/files/688471/Report.zip)

Plus another 12 errors:
image

Then, there's also:
image

And last but probably not least (certainly not in size), here's something for people who like reading log files - all log files from my corefx project folder.
[logs.zip](https://github.com/dotnet/corefx/files/688434/logs.zip)

**Comment by weshaggard** [comment]
I took a quick look at your logs and you are correct corerun which is our test runner did crash which happens in some test failure cases. I also noticed you are running these with Performance enabled as they are using our performance test runner. I know there are definitely a number of issues with our current performance runs which explains why you are hitting some failures. Pinging @DrewScoggins @brianrob who are our performance contacts.

**Comment by stephentoub** [comment]
@dnickless, thanks for adding tests.  All of the CI legs failed because the new tests get stuck in an infinite loop, in https://github.com/dotnet/corefx/blob/master/src/Common/tests/System/Collections/IDictionary.Generic.Tests.cs#L139-L140.  Some of the tests try to create collections with 75 unique keys, but your new enum tests are using % 10 to limit the values returned, which in turn causes that AddToCollection method to loop forever trying to get unique keys it'll never get.  Probably easiest to just remove the % 10 restriction; it doesn't really matter whether the enum contains named values for the key values returned, only that the type used is an enum, which the rest of your test satisifies.

**Comment by dnickless** [comment]
@stephentoub: Pah, infinite loop... You've never heard of *continuous* ingegration, have you? ;) No, seriously, that's embarrassing, a real ego-killer. And the worst thing is: I experienced the same locally but couldn't be bothered and wanted to get this out of the way so I blamed it on the CoreRun issues I had before and thought everything would be fine somehow. Ouch! Oh well... If my wife doesn't scream for me any louder than she just did you shall have the fix in a few minutes.

**Comment by dnickless** [comment]
@stephentoub: I am not sure I fully understand your suggestion. In order to add 75 items with an enum key into a dictionary, I need an enum type with 75 distinct members. Or am I missing something here? It's been a long day... What I had before was a test enum with only 10 distinct members which is why I had the % 10 in there - I wanted to map any seed value onto a valid member of the enum in order to generate a key based on a seed in a reproducible manner.

To make things worse, there is another test, IDictionary_Generic_Values_IncludeDuplicatesMultipleTimes, which effectively inserts duplicate values for all 75 contained elements under different keys again. So we really need a enum with 150 members, don't we? I tried using System.ConsoleKey as a test enum, which unfortunately only has 144 members. Are you aware of a bigger one or should I simply create a 150 member test enum?

**Comment by dnickless** [comment]
@stephentoub: OMG, I think I just woke up. I should be generating enum values and not enum keys... Stupid me, I'm sorry for wasting your time.

**Comment by stephentoub** [comment]
> In order to add 75 items with an enum key into a dictionary, I need an enum type with 75 distinct members

If I have an enum like:
```C#
enum MyColors
{
    Red = 1,
    White = 2,
    Blue = 3, 
}
```
it's perfectly valid to write code like:
```C#
MyColors c = (MyColors)1776;
```
even though there's no name for the value 1776.

**Comment by dnickless** [comment]
I think, we're getting closer. However, I had to flag the enum test as "SupportsSerialization = false" because of the following exception:

image

I am guessing that this could be due to the protected modifier on the EnumEqualityComparer constructor for the deserialization?

https://github.com/dotnet/coreclr/blob/master/src/mscorlib/src/System/Collections/Generic/EqualityComparer.cs#L388

**Comment by stephentoub** [comment]
> I am guessing that this could be due to the protected modifier on the EnumEqualityComparer constructor for the deserialization?

Related, but not exactly that.  The protected is fine, and that's how it is in the .NET Framework.  The problem appears to be that the member is getting stripped out by the rewriter / tree shaker that runs over System.Private.CoreLib.dll to remove unused members.  I'll submit a PR to fix it.

**Comment by dnickless** [comment]
OIC. That's starting to make sense now. I seemed to remember that the Serialization bits didn't need things to be public but I couldn't find anything else that would have been obviously wrong and hadn't come across that rewriter thing. Anyway, if you're short on time, I shall happily attempt to change that bit, too, if you tell me roughly where to look for it...

**Comment by stephentoub** [comment]
Thanks, @dnickless.  A fix for the deserialization issue is here: https://github.com/dotnet/coreclr/pull/8892

**Comment by dnickless** [comment]
Hmm, builds broken again, for this exact same ol' deserialization reason... What shall I say? "It worked on my machine" as far as I can tell...

**Comment by stephentoub** [comment]
@dotnet-bot test this please (now that #15219 has been fixed)

**Comment by dnickless** [comment]
You are very welcome, @stephentoub - it was a slightly difficult birth but we eventually got there. Good stuff, there shall be more!

**Comment by stephentoub** [comment]
> it was a slightly difficult birth but we eventually got there

Yeah, a series of unfortunate events: first some difficulties with the engineering system, then hitting a bug elsewhere in the stack (but yay for new tests highlighting bugs), and then working through some fallout from the changes to the engineering system. Thanks for sticking with it.

**Comment by dnickless** [comment]
@stephentoub, I was thinking the other day that the IsValueWriteAtomic() method should actually be reseated to the "Type" class because it might be meaningful in other contexts, too. Plus, it is not directly coupled to anything that the ConcurrentDictionary represents. What's your take on that?

**Comment by stephentoub** [comment]
> What's your take on that?

If/when there's a demand for it, it could be proposed as an API addition to Type.  Until such time, though, I'd leave it on ConcurrentDictionary as an implementation detail there.

**Pull request merged**
