### PR TITLE
Validate that the results of a restore are exactly what was requested

### PR DESCRIPTION
**Pull request by dagood**
Adds a post-restore validation step making sure that each dependency has an exact match (and fails the build if not). Detects errors like these that were currently in the build:
```
C:\git\corefx\build.proj(125,5): error : Exact package 'System.ComponentModel.Primitives 4.0.1-rc3-24022-00' was not restored: found '4.1.0-rc3-24020-00'
C:\git\corefx\build.proj(125,5): error : Exact package 'System.ComponentModel.TypeConverter 4.0.1-rc3-24022-00' was not restored: found '4.1.0-rc3-24020-00'
```

If you use detailed verbosity you can see which lockfiles have these errors. (Although you probably don't need to know.)

To fix the ones mentioned above, I did:
```
msbuild /t:UpdatePackageDependencyVersion /p:PackageId=System.ComponentModel.Primitives;OldVersion=4.0.1-rc3-24022-00;NewVersion=4.1.0-rc3-24022-00
msbuild /t:UpdatePackageDependencyVersion /p:PackageId=System.ComponentModel.TypeConverter;OldVersion=4.0.1-rc3-24022-00;NewVersion=4.1.0-rc3-24022-00
```

More info on this validation and why it's useful: https://github.com/dotnet/buildtools/pull/652

(Right now `UpdatePackageDependencyVersion` is broken, but I'll be including the fix https://github.com/dotnet/buildtools/pull/656 in this PR once it goes through.)

/cc @ericstj @weshaggard

### CODE REVIEW

**Comment by weshaggard** [comment]
LGTM but you might want to go ahead and pull in your other BuildTools fix along with this.

cc @StephenBonikowsky 
@dagood could you also apply the same change in WCF repo?

**Comment by StephenBonikowsky** [comment]
I'm working on a PR in WCF right now that is updating build.proj among other things, I can pull this change into it if you wish and add @dagood for review.

**Comment by ericstj** [comment]
LGTM

**Comment by dagood** [comment]
@StephenBonikowsky That would be great, thanks!

@weshaggard Yep, bringing that fix in this PR is the plan.

**Comment by dagood** [comment]
@dotnet-bot test Innerloop Ubuntu14.04 Release Build and Test

**Comment by dagood** [comment]
@dotnet-bot test Innerloop CentOS7.1 Debug Build and Test
@dotnet-bot test Innerloop CentOS7.1 Release Build and Test

**Pull request merged**
