### PR TITLE
System.Net.Http Removing unneeded blocking from tests

### PR DESCRIPTION
**Pull request by Drawaes**
Removed anywhere that had an WaitAll

ref #25346

### CODE REVIEW

**Comment by Drawaes** [comment]
@dotnet-bot Test outerloop Linux x64 Release Build please
@dotnet-bot Test outerloop Windows x64 Release Build please

**Comment by davidsh** [comment]
Please run outerloop tests since the majority of Http tests are outerloop and the tests you're changing are outerloop.

**Comment by Drawaes** [comment]
@dotnet-bot Test outerloop OSX x64 Release Build please

I already am (except I forgot the OSX tests 😄  )

**Comment by Drawaes** [comment]
@dotnet-bot Test Windows x86 Release Build please

**Comment by Drawaes** [comment]
@dotnet-bot Linux x64 Release Build please

**Comment by Drawaes** [comment]
@dotnet-bot Test Linux x64 Release Build please

**Pull request merged**
