### PR TITLE
Convert UTF-16 encoded files into UTF8

### PR DESCRIPTION
**Pull request by ellismg**
UTF16 encoded files trip up both Git and GitHub since the huristic they
use to determine if a file is binary or not depends on the existence of
null bytes in a file, which is common in UTF-16 encoded source.

This converts all the UTF-16 encoded files into UTF-8 with an explicit
byte order marker.

### CODE REVIEW

**Comment by ellismg** [comment]
The GitHub provided diff here is pretty terrible, since it believes the source files are binary.  I had success locally using kdiff3 + git difftool -d.  It shows the files and for each one tells me they are text equal but not binary equal.

**Comment by stephentoub** [comment]
Thanks. The only other differences I saw were adding some newlines at the end of files. LGTM.

**Comment by akoeplinger** [comment]
I assume this supersedes https://github.com/dotnet/corefx/pull/1470?

**Comment by ellismg** [comment]
Maybe?  It was unclear if we landed on a BOM vs no BOM call, but this certainly gets us closer.

**Comment by akoeplinger** [comment]
Yep, thanks, I actually didn't care about BOM vs no BOM when I opened https://github.com/dotnet/corefx/issues/1339, so this is fine by me :+1:

**Pull request merged**
