### PR TITLE
Ignore CTRequired when building an X509 chain

### LINKED ISSUE #35224: "X509ChainGetStatusAtIndex returned unexpected error 2" assert in macOS ChainPal.BuildChain
```
2019-02-10 17:13:57,029: INFO: proc(55): run_and_log_output: Output: X509ChainGetStatusAtIndex returned unexpected error 2
2019-02-10 17:13:57,029: INFO: proc(55): run_and_log_output: Output: 
2019-02-10 17:13:57,030: INFO: proc(55): run_and_log_output: Output:    at Internal.Cryptography.Pal.SecTrustChainPal.ParseResults(SafeX509ChainHandle chainHandle, X509RevocationMode revocationMode) in /Users/dotnet-bot/j/workspace/dotnet_corefx/master/osx-TGroup_netcoreapp+CGroup_Debug+AGroup_x64+TestOuter_false_prtest/src/System.Security.Cryptography.X509Certificates/src/Internal/Cryptography/Pal.OSX/ChainPal.cs:line 247
2019-02-10 17:13:57,030: INFO: proc(55): run_and_log_output: Output:    at Internal.Cryptography.Pal.SecTrustChainPal.Execute(DateTime verificationTime, Boolean allowNetwork, OidCollection applicationPolicy, OidCollection certificatePolicy, X509RevocationFlag revocationFlag) in /Users/dotnet-bot/j/workspace/dotnet_corefx/master/osx-TGroup_netcoreapp+CGroup_Debug+AGroup_x64+TestOuter_false_prtest/src/System.Security.Cryptography.X509Certificates/src/Internal/Cryptography/Pal.OSX/ChainPal.cs:line 210
2019-02-10 17:13:57,031: INFO: proc(55): run_and_log_output: Output:    at Internal.Cryptography.Pal.ChainPal.BuildChain(Boolean useMachineContext, ICertificatePal cert, X509Certificate2Collection extraStore, OidCollection applicationPolicy, OidCollection certificatePolicy, X509RevocationMode revocationMode, X509RevocationFlag revocationFlag, DateTime verificationTime, TimeSpan timeout) in /Users/dotnet-bot/j/workspace/dotnet_corefx/master/osx-TGroup_netcoreapp+CGroup_Debug+AGroup_x64+TestOuter_false_prtest/src/System.Security.Cryptography.X509Certificates/src/Internal/Cryptography/Pal.OSX/ChainPal.cs:line 571
2019-02-10 17:13:57,031: INFO: proc(55): run_and_log_output: Output:    at System.Security.Cryptography.X509Certificates.X509Chain.Build(X509Certificate2 certificate, Boolean throwOnException) in /Users/dotnet-bot/j/workspace/dotnet_corefx/master/osx-TGroup_netcoreapp+CGroup_Debug+AGroup_x64+TestOuter_false_prtest/src/System.Security.Cryptography.X509Certificates/src/System/Security/Cryptography/X509Certificates/X509Chain.cs:line 118
2019-02-10 17:13:57,032: INFO: proc(55): run_and_log_output: Output:    at System.Security.Cryptography.X509Certificates.X509Chain.Build(X509Certificate2 certificate) in /Users/dotnet-bot/j/workspace/dotnet_corefx/master/osx-TGroup_netcoreapp+CGroup_Debug+AGroup_x64+TestOuter_false_prtest/src/System.Security.Cryptography.X509Certificates/src/System/Security/Cryptography/X509Certificates/X509Chain.cs:line 105
2019-02-10 17:13:57,032: INFO: proc(55): run_and_log_output: Output:    at System.Security.Cryptography.X509Certificates.Tests.ChainTests.get_TrustsMicrosoftDotComRoot() in /Users/dotnet-bot/j/workspace/dotnet_corefx/master/osx-TGroup_netcoreapp+CGroup_Debug+AGroup_x64+TestOuter_false_prtest/src/System.Security.Cryptography.X509Certificates/tests/ChainTests.cs:line 33
2019-02-10 17:13:57,032: INFO: proc(55): run_and_log_output: Output:    at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
2019-02-10 17:13:57,033: INFO: proc(55): run_and_log_output: Output:    at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture) in /Users/vsts/agent/2.144.2/work/1/s/src/System.Private.CoreLib/src/System/Reflection/RuntimeMethodInfo.cs:line 472
2019-02-10 17:13:57,033: INFO: proc(55): run_and_log_output: Output:    at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters) in /Users/vsts/agent/2.144.2/work/1/s/src/System.Private.CoreLib/shared/System/Reflection/MethodBase.cs:line 54
2019-02-10 17:13:57,033: INFO: proc(55): run_and_log_output: Output:    at Microsoft.DotNet.XUnitExtensions.ConditionalTestDiscoverer.Discover(ITestFrameworkDiscoveryOptions discoveryOptions, IMessageSink diagnosticMessageSink, ITestMethod testMethod, IEnumerable`1 testCases, Object[] conditionArguments) in /_/src/Microsoft.DotNet.XUnitExtensions/src/Discoverers/ConditionalTestDiscoverer.cs:line 89
2019-02-10 17:13:57,034: INFO: proc(55): run_and_log_output: Output:    at Microsoft.DotNet.XUnitExtensions.ConditionalFactDiscoverer.Discover(ITestFrameworkDiscoveryOptions discoveryOptions, ITestMethod testMethod, IAttributeInfo factAttribute) in /_/src/Microsoft.DotNet.XUnitExtensions/src/Discoverers/ConditionalFactDiscoverer.cs:line 27
2019-02-10 17:13:57,034: INFO: proc(55): run_and_log_output: Output:    at Xunit.Sdk.XunitTestFrameworkDiscoverer.FindTestsForMethod(ITestMethod testMethod, Boolean includeSourceInformation, IMessageBus messageBus, ITestFrameworkDiscoveryOptions discoveryOptions) in C:\projects\xunit\src\xunit.execution\Sdk\Frameworks\XunitTestFrameworkDiscoverer.cs:line 119
2019-02-10 17:13:57,034: INFO: proc(55): run_and_log_output: Output:    at Xunit.Sdk.XunitTestFrameworkDiscoverer.FindTestsForType(ITestClass testClass, Boolean includeSourceInformation, IMessageBus messageBus, ITestFrameworkDiscoveryOptions discoveryOptions) in C:\projects\xunit\src\xunit.execution\Sdk\Frameworks\XunitTestFrameworkDiscoverer.cs:line 132
2019-02-10 17:13:57,035: INFO: proc(55): run_and_log_output: Output:    at Xunit.Sdk.TestFrameworkDiscoverer.FindTestsForTypeAndWrapExceptions(ITestClass testClass, Boolean includeSourceInformation, IMessageBus messageBus, ITestFrameworkDiscoveryOptions discoveryOptions) in C:\projects\xunit\src\xunit.execution\Sdk\Frameworks\TestFrameworkDiscoverer.cs:line 156
2019-02-10 17:13:57,035: INFO: proc(55): run_and_log_output: Output:    at Xunit.Sdk.TestFrameworkDiscoverer.<>c__DisplayClass26_0.<Find>b__0() in C:\projects\xunit\src\xunit.execution\Sdk\Frameworks\TestFrameworkDiscoverer.cs:line 101
2019-02-10 17:13:57,035: INFO: proc(55): run_and_log_output: Output:    at Xunit.Sdk.XunitWorkerThread.<>c.<QueueUserWorkItem>b__4_0(Object _) in C:\projects\xunit\src\common\XunitWorkerThread.cs:line 92
2019-02-10 17:13:57,035: INFO: proc(55): run_and_log_output: Output:    at System.Threading.QueueUserWorkItemCallbackDefaultContext.Execute() in /Users/vsts/agent/2.144.2/work/1/s/src/System.Private.CoreLib/shared/System/Threading/ThreadPool.cs:line 854
2019-02-10 17:13:57,036: INFO: proc(55): run_and_log_output: Output:    at System.Threading.ThreadPoolWorkQueue.Dispatch() in /Users/vsts/agent/2.144.2/work/1/s/src/System.Private.CoreLib/shared/System/Threading/ThreadPool.cs:line 645
2019-02-10 17:13:57,036: INFO: proc(55): run_and_log_output: Output:    at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback() in /Users/vsts/agent/2.144.2/work/1/s/src/System.Private.CoreLib/src/System/Threading/ThreadPool.CoreCLR.cs:line 29
```

@bartonjs, is it possible/likely I somehow caused this with my recent changes?

### PR DESCRIPTION
**Pull request by vcsjones**
Fixes #35224 

/cc @bartonjs @stephentoub

### CODE REVIEW

**Comment by safern** [comment]
Merged since we were hitting failures in other PRs and these PR was green on both, Jenkins and Azure legs.

**Comment by danmosemsft** [comment]
Thanks @vcsjones what do yo uthink about also changing to `#if DEBUGGING_UNKNOWN_VALUE || DEBUG` as @bartonjs suggested, so we can resolve this quicker next time?

**Comment by stephentoub** [comment]
@danmosemsft, that change was already merged ;-)

**Comment by danmosemsft** [comment]
Yeah, I know, sometimes it's just a convenient place to ask questions..

**Comment by stephentoub** [comment]
> Yeah, I know, sometimes it's just a convenient place to ask questions..

No, I mean the `#if DEBUGGING_UNKNOWN_VALUE || DEBUG` change was already merged.  It's already done.

**Comment by danmosemsft** [comment]
Ah - I see, in another PR. cool. thanks.

**Pull request merged**
