### PR TITLE
Make Stacktrace Symbols Cache Aware of Unloadability (phase 1)

### PR DESCRIPTION
**Pull request by josalem**
Adds an overload of the `GetSourceLineInfo` method with its original parameters list, and adds `System.Reflection.Assembly` as a paramter to the actual implementation.  This is to accomodate a cross corefx, coreclr change to use `System.Reflection.Assembly` as the cache key in a `ConditionalWeakTable<Assembly, MetadataReaderProvider>`.  To see what the end result will look like on the corefx side, please look [here](https://github.com/josalem/corefx/blob/stacktrace-cache-unloading-coreclr20179/src/System.Diagnostics.StackTrace/src/System/Diagnostics/StackTraceSymbols.CoreCLR.cs).

dotnet/coreclr#20179

CC - @janvorli

### CODE REVIEW

**Comment by danmosemsft** [comment]
I realize this is small, but does this have API approval

**Comment by janvorli** [comment]
> I realize this is small, but does this have API approval

This is not a public API, it is just a an internal interface between the parts of the stack trace creating that are split between coreclr and corefx repos.

**Comment by josalem** [comment]
Revising the order of PRs into CoreFX and CoreCLR.  This PR should not be merged in until *after* dotnet/coreclr#22841 in in CoreCLR, which will get rid of the AmbiguousMatch exception that is making CI fail.

**Comment by josalem** [comment]
Will rebase on master once dotnet/coreclr#22841 is picked up by corefx master.  This should fix the CI failures.

**Pull request merged**
