### PR TITLE
Add System.Text.Encoding.CodePages library to the shared framework

### LINKED ISSUE #38279: Consider putting System.Text.Encoding.CodePages in the shared framework
There are currently 6 copies in SDK. See below.

It seems to be used quite a lot, and it seems to be purpose defeating that every app/component is carrying it. I think we're making apps significantly bigger more than we're benefiting from shared framework being approximately 1% smaller.

Also, it seems when you deploy as portable (no RID), you get 3 copies so 2.4 MB instead if 800 KB. 

(Now there's an architectural issue in the SDK where we're publishing portable components into the toolset, then crossgening everything. This is causing excess copies of dlls like this in the SDK, which is actually tied to a single TFM and RID when all is said and done. This is hard to fix though we could hack it by deleting some files.)

```
C:\Program Files\dotnet\sdk\3.0.100-preview7-012271>dir /s System.Text.Encoding.CodePages.dll
 Volume in drive C is C
 Volume Serial Number is F0AA-6065

 Directory of C:\Program Files\dotnet\sdk\3.0.100-preview7-012271

06/05/2019  08:52 PM           876,624 System.Text.Encoding.CodePages.dll
               1 File(s)        876,624 bytes

 Directory of C:\Program Files\dotnet\sdk\3.0.100-preview7-012271\Roslyn\bincore

06/05/2019  08:52 PM           877,160 System.Text.Encoding.CodePages.dll
               1 File(s)        877,160 bytes

 Directory of C:\Program Files\dotnet\sdk\3.0.100-preview7-012271\Roslyn\bincore\runtimes\win\lib\netcoreapp2.0

06/05/2019  08:52 PM           880,720 System.Text.Encoding.CodePages.dll
               1 File(s)        880,720 bytes

 Directory of C:\Program Files\dotnet\sdk\3.0.100-preview7-012271\runtimes\win\lib\netcoreapp2.0

06/05/2019  08:52 PM           882,248 System.Text.Encoding.CodePages.dll
               1 File(s)        882,248 bytes

 Directory of C:\Program Files\dotnet\sdk\3.0.100-preview7-012271\Sdks\Microsoft.NET.Sdk.Razor\tools\netcoreapp3.0

05/15/2018  01:29 PM           758,928 System.Text.Encoding.CodePages.dll
               1 File(s)        758,928 bytes

 Directory of C:\Program Files\dotnet\sdk\3.0.100-preview7-012271\Sdks\Microsoft.NET.Sdk.Razor\tools\netcoreapp3.0\runtimes\win\lib\netcoreapp2.0

05/15/2018  01:29 PM           761,488 System.Text.Encoding.CodePages.dll
               1 File(s)        761,488 bytes

     Total Files Listed:
               6 File(s)      5,037,168 bytes
```

### PR DESCRIPTION
**Pull request by tarekgh**
Fixes #38279

### CODE REVIEW

**Comment by tarekgh** [comment]
CC @ericstj @joperezr @nguerrera @jkotas @stephentoub @marek-safar

**Comment by stephentoub** [comment]
Do we need or want to add something like https://github.com/dotnet/corefx/pull/38207/files#diff-26c8452e830a7d9ebcc180e57ac46c5dR13 , too?

**Comment by tarekgh** [comment]
> Do we need or want to add something like https://github.com/dotnet/corefx/pull/38207/files#diff-26c8452e830a7d9ebcc180e57ac46c5dR13 , too?

It is already there. https://github.com/dotnet/corefx/blob/46d9f33d96a1db41a9634b84dd68256db2eeed4f/src/System.Text.Encoding.CodePages/pkg/System.Text.Encoding.CodePages.pkgproj#L25

**Comment by ericstj** [comment]
```
C:\dotnetbuild\work\62c47906-8496-4962-ac42-1ff0cd8a2834\Payload\packageTest.targets(74,5): error : Assembly 'System.Data.SqlClient' is missing dependency 'System.Text.Encoding.CodePages' [C:\dotnetbuild\work\62c47906-8496-4962-ac42-1ff0cd8a2834\Work\4c28fd73-17b2-47ce-a6e0-cac8ffe28a67\Unzip\netcoreapp3.0\project.csproj]
C:\dotnetbuild\work\62c47906-8496-4962-ac42-1ff0cd8a2834\Payload\packageTest.targets(74,5): error : Assembly 'System.Data.SqlClient' is missing dependency 'System.Text.Encoding.CodePages' [C:\dotnetbuild\work\62c47906-8496-4962-ac42-1ff0cd8a2834\Work\4c28fd73-17b2-47ce-a6e0-cac8ffe28a67\Unzip\netcoreapp3.0\project.csproj]
```

SQLClient is failing package testing because it is missing the dependency on CodePages.  This happens because we test with an *LKG* shared framework that doesn't yet include CodePages inbox.  To workaround this you'll need a temporary suppression.  I can add it to this branch.

**Comment by tarekgh** [comment]
@ericstj it looks there still some failure in SqlClient packaging tests:

```
##[command]"C:\windows\system32\cmd.exe" /D /E:ON /V:OFF /S /C "CALL "D:\a\_temp\b6d4df59-48cb-45d0-a56d-0551da70e3c8.cmd""
D:\a\1\s\.dotnet\sdk\3.0.100-preview6-012234\MSBuild.dll /nologo -maxcpucount /m -verbosity:m /v:minimal /bl:D:\a\1\s/artifacts/log/Debug/SendToHelix.binlog /clp:Summary /logger:D:\a\1\s\.packages\microsoft.dotnet.arcade.sdk\1.0.0-beta.19309.1\tools\netcoreapp2.1\Microsoft.DotNet.Arcade.Sdk.dll /nr:False /p:ContinuousIntegrationBuild=True /p:ArchGroup=x64 /p:ConfigurationGroup=Debug /p:OSGroup=Windows_NT /p:testScope= /p:TargetGroup=allConfigurations /p:HelixTargetQueues=Windows.10.Amd64.ClientRS5.Open /p:HelixBuild=20190610.42 /p:HelixAccessToken= /p:Creator=dotnet-bot /p:OfficialBuildId= /t:test eng/sendtohelix.proj
  Starting Azure Pipelines Test Run allConfigurations-Windows_NT-Debug-x64-Windows.10.Amd64.ClientRS5.Open
  Results will be available from https://mc.dot.net/#/user/dotnet-bot/pr~2Fdotnet~2Fcorefx~2Frefs~2Fpull~2F38357~2Fmerge/test~2Ffunctional~2Fpackaging~2F/20190610.42
  Sent Helix Job d32fbaf6-6bf4-442e-beb2-f0cb1f6cabb4
  Waiting for completion of job d32fbaf6-6bf4-442e-beb2-f0cb1f6cabb4
  Job d32fbaf6-6bf4-442e-beb2-f0cb1f6cabb4 is completed with 76 finished work items.
  Stopping Azure Pipelines Test Run allConfigurations-Windows_NT-Debug-x64-Windows.10.Amd64.ClientRS5.Open
D:\a\1\s\.packages\microsoft.dotnet.helix.sdk\2.0.0-beta.19309.1\tools\Microsoft.DotNet.Helix.Sdk.MultiQueue.targets(67,5): error : Work item System.Data.SqlClient in job d32fbaf6-6bf4-442e-beb2-f0cb1f6cabb4 has failed. [D:\a\1\s\eng\sendtohelix.proj]
##[error].packages\microsoft.dotnet.helix.sdk\2.0.0-beta.19309.1\tools\Microsoft.DotNet.Helix.Sdk.MultiQueue.targets(67,5): error : Work item System.Data.SqlClient in job d32fbaf6-6bf4-442e-beb2-f0cb1f6cabb4 has failed.
```

looking at the logs https://mc.dot.net/#/user/dotnet-bot/pr~2Fdotnet~2Fcorefx~2Frefs~2Fpull~2F38357~2Fmerge/test~2Ffunctional~2Fpackaging~2F/20190610.42/workItem/System.Data.SqlClient/wilogs I am not seeing netcore3.0 is tested and there is no explicit errors there

**Comment by ericstj** [comment]
It looks like a timeout / hang.  Something that stands out is `Restore completed in 2.07 min for C:\dotnetbuild\work\d32fbaf6-6bf4-442e-beb2-f0cb1f6cabb4\Work\827377e2-43ec-44ca-a6df-f6bb75232ab0\Unzip\netcoreapp3.0\project.csproj.`

2 minutes for restoring a single project is a too high.  Let me see if I can repo this.

**Comment by ericstj** [comment]
Update: looked closer at the logs:
```
  Restore completed in 1.06 sec for C:\dotnetbuild\work\d32fbaf6-6bf4-442e-beb2-f0cb1f6cabb4\Work\827377e2-43ec-44ca-a6df-f6bb75232ab0\Unzip\monoandroid10\project.csproj.
  Restore completed in 1.06 sec for C:\dotnetbuild\work\d32fbaf6-6bf4-442e-beb2-f0cb1f6cabb4\Work\827377e2-43ec-44ca-a6df-f6bb75232ab0\Unzip\monotouch10\project.csproj.
  Restore completed in 40.94 sec for C:\dotnetbuild\work\d32fbaf6-6bf4-442e-beb2-f0cb1f6cabb4\Work\827377e2-43ec-44ca-a6df-f6bb75232ab0\Unzip\net451\project.csproj.
  Restore completed in 50.13 sec for C:\dotnetbuild\work\d32fbaf6-6bf4-442e-beb2-f0cb1f6cabb4\Work\827377e2-43ec-44ca-a6df-f6bb75232ab0\Unzip\net461\project.csproj.
  Restore completed in 13.86 sec for C:\dotnetbuild\work\d32fbaf6-6bf4-442e-beb2-f0cb1f6cabb4\Work\827377e2-43ec-44ca-a6df-f6bb75232ab0\Unzip\net462\project.csproj.
  Restore completed in 10.17 sec for C:\dotnetbuild\work\d32fbaf6-6bf4-442e-beb2-f0cb1f6cabb4\Work\827377e2-43ec-44ca-a6df-f6bb75232ab0\Unzip\net46\project.csproj.
  Restore completed in 47.83 ms for C:\dotnetbuild\work\d32fbaf6-6bf4-442e-beb2-f0cb1f6cabb4\Work\827377e2-43ec-44ca-a6df-f6bb75232ab0\Unzip\netcore451\project.csproj.
  Restore completed in 37.99 ms for C:\dotnetbuild\work\d32fbaf6-6bf4-442e-beb2-f0cb1f6cabb4\Work\827377e2-43ec-44ca-a6df-f6bb75232ab0\Unzip\netcore50\project.csproj.
  Restore completed in 1.8 min for C:\dotnetbuild\work\d32fbaf6-6bf4-442e-beb2-f0cb1f6cabb4\Work\827377e2-43ec-44ca-a6df-f6bb75232ab0\Unzip\net471\project.csproj.
  Restore completed in 6.53 min for C:\dotnetbuild\work\d32fbaf6-6bf4-442e-beb2-f0cb1f6cabb4\Work\827377e2-43ec-44ca-a6df-f6bb75232ab0\Unzip\netcoreapp1.0\project.csproj.
  Restore completed in 5.12 min for C:\dotnetbuild\work\d32fbaf6-6bf4-442e-beb2-f0cb1f6cabb4\Work\827377e2-43ec-44ca-a6df-f6bb75232ab0\Unzip\netcoreapp1.1\project.csproj.
  Restore completed in 3.73 min for C:\dotnetbuild\work\d32fbaf6-6bf4-442e-beb2-f0cb1f6cabb4\Work\827377e2-43ec-44ca-a6df-f6bb75232ab0\Unzip\netcoreapp2.1\project.csproj.
  Restore completed in 4.09 min for C:\dotnetbuild\work\d32fbaf6-6bf4-442e-beb2-f0cb1f6cabb4\Work\827377e2-43ec-44ca-a6df-f6bb75232ab0\Unzip\netcoreapp2.0\project.csproj.
  Restore completed in 168.98 ms for C:\dotnetbuild\work\d32fbaf6-6bf4-442e-beb2-f0cb1f6cabb4\Work\827377e2-43ec-44ca-a6df-f6bb75232ab0\Unzip\netstandard1.2\project.csproj.
  Restore completed in 20.77 sec for C:\dotnetbuild\work\d32fbaf6-6bf4-442e-beb2-f0cb1f6cabb4\Work\827377e2-43ec-44ca-a6df-f6bb75232ab0\Unzip\netstandard1.3\project.csproj.
  Restore completed in 563.54 ms for C:\dotnetbuild\work\d32fbaf6-6bf4-442e-beb2-f0cb1f6cabb4\Work\827377e2-43ec-44ca-a6df-f6bb75232ab0\Unzip\netstandard1.4\project.csproj.
  Restore completed in 668.67 ms for C:\dotnetbuild\work\d32fbaf6-6bf4-442e-beb2-f0cb1f6cabb4\Work\827377e2-43ec-44ca-a6df-f6bb75232ab0\Unzip\netstandard1.6\project.csproj.
  Restore completed in 382.9 ms for C:\dotnetbuild\work\d32fbaf6-6bf4-442e-beb2-f0cb1f6cabb4\Work\827377e2-43ec-44ca-a6df-f6bb75232ab0\Unzip\netstandard1.7\project.csproj.
  Restore completed in 2.5 sec for C:\dotnetbuild\work\d32fbaf6-6bf4-442e-beb2-f0cb1f6cabb4\Work\827377e2-43ec-44ca-a6df-f6bb75232ab0\Unzip\netstandard2.0\project.csproj.
  Restore completed in 43.16 ms for C:\dotnetbuild\work\d32fbaf6-6bf4-442e-beb2-f0cb1f6cabb4\Work\827377e2-43ec-44ca-a6df-f6bb75232ab0\Unzip\netstandard2.1\project.csproj.
  Restore completed in 57.1 ms for C:\dotnetbuild\work\d32fbaf6-6bf4-442e-beb2-f0cb1f6cabb4\Work\827377e2-43ec-44ca-a6df-f6bb75232ab0\Unzip\uap10.0.16299\project.csproj.
  Restore completed in 59.86 ms for C:\dotnetbuild\work\d32fbaf6-6bf4-442e-beb2-f0cb1f6cabb4\Work\827377e2-43ec-44ca-a6df-f6bb75232ab0\Unzip\uap10.0.16300\project.csproj.
  Restore completed in 43.38 ms for C:\dotnetbuild\work\d32fbaf6-6bf4-442e-beb2-f0cb1f6cabb4\Work\827377e2-43ec-44ca-a6df-f6bb75232ab0\Unzip\uap10.0\project.csproj.
  Restore completed in 18.87 ms for C:\dotnetbuild\work\d32fbaf6-6bf4-442e-beb2-f0cb1f6cabb4\Work\827377e2-43ec-44ca-a6df-f6bb75232ab0\Unzip\wpa81\project.csproj.
  Restore completed in 19.62 ms for C:\dotnetbuild\work\d32fbaf6-6bf4-442e-beb2-f0cb1f6cabb4\Work\827377e2-43ec-44ca-a6df-f6bb75232ab0\Unzip\xamarinios10\project.csproj.
  Restore completed in 14.07 ms for C:\dotnetbuild\work\d32fbaf6-6bf4-442e-beb2-f0cb1f6cabb4\Work\827377e2-43ec-44ca-a6df-f6bb75232ab0\Unzip\xamarinmac20\project.csproj.
  Restore completed in 15.93 ms for C:\dotnetbuild\work\d32fbaf6-6bf4-442e-beb2-f0cb1f6cabb4\Work\827377e2-43ec-44ca-a6df-f6bb75232ab0\Unzip\xamarintvos10\project.csproj.
  Restore completed in 18.45 sec for C:\dotnetbuild\work\d32fbaf6-6bf4-442e-beb2-f0cb1f6cabb4\Work\827377e2-43ec-44ca-a6df-f6bb75232ab0\Unzip\xamarinwatchos10\project.csproj.
  Restore completed in 2.07 min for C:\dotnetbuild\work\d32fbaf6-6bf4-442e-beb2-f0cb1f6cabb4\Work\827377e2-43ec-44ca-a6df-f6bb75232ab0\Unzip\netcoreapp3.0\project.csproj.
```

Multiple minute-plus restore operations is the cause of this failure.

**Comment by tarekgh** [comment]
Thanks @ericstj I'll rerun the failed tests then.

**Comment by ericstj** [comment]
I'll also take a look at a local repro to see if there is any followup here.

**Comment by ericstj** [comment]
Took a look at another successful build and found similar numbers, so I think we're just running close to the limit:
```
  Restore completed in 2.93 min for C:\dotnetbuild\work\27eea9da-62f0-4da4-9f52-93d36e675414\Work\e7b5088c-f5dc-44c7-bc13-611ccd4ebdaf\Unzip\netcoreapp1.0\project.csproj.
  Restore completed in 3.21 min for C:\dotnetbuild\work\27eea9da-62f0-4da4-9f52-93d36e675414\Work\e7b5088c-f5dc-44c7-bc13-611ccd4ebdaf\Unzip\netcoreapp1.1\project.csproj.
  Restore completed in 59.78 sec for C:\dotnetbuild\work\27eea9da-62f0-4da4-9f52-93d36e675414\Work\e7b5088c-f5dc-44c7-bc13-611ccd4ebdaf\Unzip\netcoreapp2.0\project.csproj.
  Restore completed in 37.12 sec for C:\dotnetbuild\work\27eea9da-62f0-4da4-9f52-93d36e675414\Work\e7b5088c-f5dc-44c7-bc13-611ccd4ebdaf\Unzip\netcoreapp3.0\project.csproj.
...
  Restore completed in 1.5 min for C:\dotnetbuild\work\27eea9da-62f0-4da4-9f52-93d36e675414\Work\e7b5088c-f5dc-44c7-bc13-611ccd4ebdaf\Unzip\netcoreapp2.1\project.csproj.
...
```

This is just a lot of downloading and restoring.  We're doing self-contained app restores for a large number of RIDs.  I bet that's what's causing this.  That's a lot of downloading + restoring.  Perhaps we should reduce the RID set for package testing or prime the package cache for the helix-shared-payload @safern.

**Pull request merged**
