### PR TITLE
Remove all Visual Studio configuration blocks from project files

### PR DESCRIPTION
**Pull request by mellinoe**
This is another cleanup change. I wrote a tool to strip all of these blocks out and write them into a central location in dir.props. Visual Studio still behaves correctly, and we don't need to duplicate this into every project file any longer.

@weshaggard @karajas

### CODE REVIEW

**Comment by weshaggard** [comment]
Are you sure VS behaves correctly? Even if it does behave correctly I would assume that means we end up with a huge set of configurations in configuration manager and so you have no idea which configurations are valid or not. I'm not sure if I like that approach or not.

**Comment by mellinoe** [comment]
@weshaggard This doesn't have any effect on what shows up in the Configuration Manager; it still just shows Debug and Release as the two valid configurations.

**Comment by weshaggard** [comment]
Yes I expect it will only show Debug/Release on the toolbar but if you go into configuration manager and try to change the configuration for an individual project I expect it will now show all configurations.

**Comment by mellinoe** [comment]
I see what you're saying. Yes, it does, but I don't see it as a big problem. Having these blocks in the project files is a much bigger problem in my eyes.

**Comment by weshaggard** [comment]
It will make it nearly impossible to know which configurations are valid to build in VS. What happens if we completely remove these property groups? Does VS try to add them back?

**Comment by mellinoe** [comment]
If they are removed, VS starts using "Debug" and "Release" as the full configuration string, which obviously doesn't work for us. We immediately get errors from the `FindBestConfiguration` task.

> It will make it nearly impossible to know which configurations are valid to build in VS

The way to determine valid configurations is to look at the configurations.props file, not the configuration manager in VS. The configuration manager in VS is already wrong today anyways, because these dummy blocks (which VS apparently uses to seed the Configuration Manager) never stay in sync with the configurations.props file (previously, the builds file).

**Comment by mellinoe** [comment]
Chatted with @weshaggard and a piece of information I was missing was that the auto-updater task for the solution files also updates these dummy blocks in the project files. It's still not ideal, but at least we have a way to keep everything in sync.

**Pull request closed without merging**
