### PR TITLE
Missing this in RegistryAclExtensions extension methods & argument check

### PR DESCRIPTION
**Pull request by ViktorHofer**
fixes https://github.com/dotnet/corefx/issues/15242

### CODE REVIEW

**Comment by jkotas** [comment]
cc @sepidehMS

**Comment by danmosemsft** [comment]
Don't know why builds are failing. They dno't locally, for me.

**Comment by ViktorHofer** [comment]
Forgot something, 1sec.

**Comment by ViktorHofer** [comment]
@dotnet-bot test Windows_NT Debug AllConfigurations Build please

**Comment by ViktorHofer** [comment]
@jkotas @karelz @danmosemsft Should this fix also go into the service releases 1.0.5 and 1.1.2?..

**Comment by ViktorHofer** [comment]
@safern: This test is also failing

**Comment by safern** [comment]
Yes it is a BaselineIssue, I will go ahead and submit a PR to fix it so that we can unblock CI.

**Comment by safern** [comment]
It is not a baseline issue. This PR: https://github.com/dotnet/corefx/pull/17880 removed an using statement which broke that build.

We are reverting changes in this PR: https://github.com/dotnet/corefx/pull/17889

Once that goes in this build should be unblocked.

**Comment by stephentoub** [comment]
@dotnet-bot test Windows_NT Debug AllConfigurations Build please (fixed build break)

**Pull request merged**
