### PR TITLE
Changing System.Net.Primitives AOT related conditions from uap to uapaot

### PR DESCRIPTION
**Pull request by ViktorHofer**
Discovered while working on uapaot stuff: https://github.com/dotnet/corefx/pull/22706#issuecomment-319158261

cc @morganbr @davidsh

### CODE REVIEW

**Comment by davidsh** [comment]
cc: @weshaggard @ericstj @CIPop

**Comment by CIPop** [comment]
@ViktorHofer I agree with @davidsh - since we don't have better understanding of the problem and we're using the same pattern as other contracts, why would we need to change?

/cc @AtsushiKan @morganbr

**Comment by CIPop** [comment]
@ViktorHofer since this is a System.Net change, please run the Outerloop tests as well.

**Comment by ViktorHofer** [comment]
We don't need to change anything :) I thought it was a mistake. Davids explanation sounds legit, I didn't know that we are not including uapaot binaries in the nuget packages. Thinking about it, it makes total sense as the optimization paths are dependent on the consuming application.

I'm closing the PR now. At least I got a better understanding of how uapaot works.

**Pull request closed without merging**
