### PR TITLE
Fix Macedonian display name in ComponentModel CultureInfo converter

### PR DESCRIPTION
**Pull request by tarekgh**

### CODE REVIEW

**Comment by tarekgh** [comment]
test Packaging All Configurations x64 Debug Build 
test Linux x64 Release Build

**Comment by tarekgh** [comment]
test Linux x64 Release Build
test OSX x64 Debug Build

**Comment by tarekgh** [comment]
https://github.com/dotnet/corefx/pull/37393

**Comment by tarekgh** [comment]
https://github.com/dotnet/corefx/pull/37390

**Comment by vivmishra** [comment]
Approved for 2.1.12 and 2.2.6.

**Pull request merged**
