### PR TITLE
Update the ReadOnlySequence Slice performance tests to only measure the Slice method

### PR DESCRIPTION
**Pull request by ahsonkhan**
cc @pakrym, @AlexRadch

### CODE REVIEW

**Comment by AlexRadch** [comment]
I thank such changing have one issue, it tests static slicing. So we can create slicing methods witch will be fast only for test.

**Comment by AlexRadch** [comment]
Now I fixed my dynamic slicing test for all except multi segment sequence. I can submit my fix to show how I changed slice performance testing.

**Comment by ahsonkhan** [comment]
> I think such changing have one issue, it tests static slicing. So we can create slicing methods which will be fast only for test.

I am not too concerned about this because we are not actively trying to optimize just for the performance test alone. I think more targeted tests are actually useful in this case since we are trying to optimize at such a low level.

> Now I fixed my dynamic slicing test for all except multi segment sequence. I can submit my fix to show how I changed slice performance testing.

Feel free to add them **in addition** to the tests in this PR.

**Comment by ahsonkhan** [comment]
@dotnet-bot test OSX x64 Debug Build

https://github.com/dotnet/corefx/issues/21037

**Comment by AlexRadch** [comment]
@ahsonkhan I updated performance tests for Slicing. Here https://github.com/dotnet/corefx/pull/29142. Can you review them and merge.

**Pull request merged**
