### PR TITLE
Make tools packages.config host platform specific.

### PR DESCRIPTION
**Pull request by JeremyKuhne**
Avoids downloading packages that don't apply to the current build environment.

@weshaggard, @ericstj, @chcosta

### CODE REVIEW

**Comment by weshaggard** [comment]
Given the rename in all the solution files I assume this still works in VS? If so the change looks reasonable to me.

**Comment by JeremyKuhne** [comment]
@weshaggard I don't see any problems- and was able to build cleanly on Windows and Ubuntu.

**Comment by JeremyKuhne** [comment]
@chcosta It will come from $(OS) which is always defined in a Windows environment.

**Comment by chcosta** [comment]
Yes, we're still importing dir.props, so that should work.

**Comment by chcosta** [comment]
LGTM

**Comment by JeremyKuhne** [comment]
@dotnet-bot test this please

**Comment by JeremyKuhne** [comment]
@dotnet-bot test this please

**Pull request merged**
