### PR TITLE
Cleanup netstandard ifdefs and conditions

### PR DESCRIPTION
**Pull request by jkotas**
Fixes https://github.com/dotnet/corefx/issues/15849

There is still quite a bit of cruft left - e.g. the `*.netstandard.cs` files should be folded into the main test .cs files as appropriate. They do not need separate files and the .netstandard suffix on them is just confusing.

### CODE REVIEW

**Comment by jkotas** [comment]
Disabled failing tests: https://github.com/dotnet/corefx/issues/16074

**Comment by jkotas** [comment]
@danmosemsft PTLA

Note that this is re-enabling a ton of tests that were disabled for last several weeks. Fortunately, they have not regressed much.

**Comment by jkotas** [comment]
System.Runtime tests run:

Before this change: 8624
After this change: 12073

**Comment by jkotas** [comment]
The "netstandard" ifdefs that I am deleting would be useless for segregating NS tests. There were used for APIs added on top of netstandard1.6 in the early days of netstandard2.0 project.

The "netcoreapp" ifdefs is what we is actually being used to segregate the netstandard tests in the current tree: The netstandard tests are included unconditionally, the netcoreapp-specific tests are included under the "netcoreapp" ifdef. It should be good enough if we wanted to add netstandard test vertical that can be consumed by other platforms like Mono.

**Comment by danmosemsft** [comment]
That makes sense.

**Comment by weshaggard** [comment]
>The "netcoreapp" ifdefs is what we is actually being used to segregate the netstandard tests in the current tree: The netstandard tests are included unconditionally, the netcoreapp-specific tests are included under the "netcoreapp" ifdef. It should be good enough if we wanted to add netstandard test vertical that can be consumed by other platforms like Mono.

Agreed that we should use netcoreapp defines for the majority of these things now. We do need to keep a netstandard build configuration however so that we can run the same set of tests on multiple platforms, which is what https://github.com/dotnet/corefx/issues/15667 is about. So after your change we are running more tests which is great but we are still not running the netstandard build of those tests.

**Comment by jkotas** [comment]
> We do need to keep a netstandard build configuration 

I agree that netstandard build configuration for the tests is useful. I would expect it to be in addition to netcoreapp vertical. netcoreapp test build would include all netstandard tests as well. Is it the plan?

**Comment by jkotas** [comment]
The netstandard build of the tests would presumably just run against netcoreapp as outer loop because of it would be just checking that nothing fell through the cracks.

**Comment by danmosemsft** [comment]
I agree that IMO running netcoreapp tests should include netstandard tests. That's because it's the default configuration, and we want essentially all tests to run by default.

**Pull request merged**
