### PR TITLE
Change Configuration to ConfigurationGroup in our build and test scripts

### PR DESCRIPTION
**Pull request by weshaggard**
Switch build and test scripts to pass ConfigurationGroup instead of Configuration for Debug/Release. This is necessary to avoid msbuild from force setting Configuration when passed at the command line, see https://github.com/weshaggard/corefx/commit/d41b1bf66901e8fd21d21ec7ea485a959e9182aa for how I've currently hacked around it. 

@mmitche PTAL. Can you tell me how I can test these groovy scripts updates before merging?

### CODE REVIEW

**Comment by mmitche** [comment]
@dotnet-bot test ci please

**Comment by mmitche** [comment]
@weshaggard This doesn't change any of the names of the output directories right?

**Comment by weshaggard** [comment]
@mmitche correct this shouldn't change the name of the output directories. My other change https://github.com/dotnet/corefx/pull/5125 will actually move a number of things under "AnyOS" instead "Windows_NT", "Linux", etc, so that may require some additional script changes I will look into that.

**Comment by mmitche** [comment]
LGTM for CI changes.

**Comment by weshaggard** [comment]
The other failures are because of my changes to run-test.sh that are needed in conjunction with netci.groovy changes. I'm going to go ahead and merge this and once the definitions update this should work itself out. I will monitor it closely.

**Pull request merged**
