### PR TITLE
Update buildtools to 00419-01

### LINKED ISSUE #8239: Reduce number of package references for runtime specific packages
Today when you reference a fat package that uses RIDs you also have to reference Microsoft.NETCore.Platforms to bring in the RID graph.

When you reference a split package you need both Microsoft.NETCore.Platforms for the RID graph and Microsoft.NETCore.Targets for the lineup.

When referencing NETStandard.Library we include both of these, but not when referencing individual packages.

Adding these references to the packages themselves is a simpler story and makes it so folks don't need to understand the RID-graph/lineup concepts (or think that it is somehow magic).

### PR DESCRIPTION
**Pull request by ericstj**
This adds references to MS.NETCore.Platforms and MS.NETCore.Targets
automatically.  As such, we are breaking the dependency between the two
as they need to be referenced independently.

In making this fix I noticed bad configuration in the SNI package
project and have fixed that.

fixes #8239 
/cc @weshaggard @chcosta @mellinoe

### CODE REVIEW

**Comment by ericstj** [comment]
@dotnet-bot test this please

**Comment by ericstj** [comment]
Now these are failing due to a regression from https://github.com/dotnet/corefx/pull/8600.  This buildtools update is specifically done to catch this type of regression since we aren't continuing on packaging failures.

**Comment by ericstj** [comment]
@dotnet-bot test this please

**Comment by bartonjs** [comment]
Test Innerloop OSX Debug Build and Test please (build machine went offline)

**Comment by stephentoub** [comment]
LGTM

**Comment by ericstj** [comment]
Thanks for the review!  Hopefully this will prevent future packaging regressions.  I'll keep an eye out to see if any have been introduced between this CI starting and the merge.

**Pull request merged**
