### PR TITLE
Implement CurlHandler.SupportsRedirectConfiguration

### LINKED ISSUE #3320: CurlHandler throwing "HTTP stack not implemented" exception from SupportsRedirectConfiguration
https://github.com/dotnet/corefx/blob/master/src/System.Net.Http/src/System/Net/Http/HttpClientHandler.Unix.cs#L25

### PR DESCRIPTION
**Pull request by stephentoub**
It does. Return true.

Fixes #3320 

cc: @kapilash

### CODE REVIEW

**Comment by stephentoub** [comment]
@dotnet-bot test this please

**Comment by stephentoub** [comment]
@kapilash or @vijaykota, can you review?

**Comment by kapilash** [comment]
LGTM please. Thank you.

**Comment by kapilash** [comment]
Merged. Thanks @stephentoub

**Comment by vijaykota** [comment]
LGTM

**Pull request merged**
