### PR TITLE
Support Proxy servers for our nuget download task

### LINKED ISSUE #963: Support Proxy servers for our nuget download task
See PR #788 where we reverted the fix for #38 because there were some unhanded cases which caused a null reference if the DefaultWebProxy is null. We should add support again with proper checks in place.

### PR DESCRIPTION
**Pull request by PatrickMcDonald**
Reapply #38, but handle the case when DefaultWebProxy is null.

Fix #963

### CODE REVIEW

**Comment by JeremyKuhne** [comment]
LGTM. @weshaggard / @chcosta

**Comment by weshaggard** [comment]
@dotnet-bot please test this

**Comment by weshaggard** [comment]
LGTM thanks for fixing it @PatrickMcDonald. I wanted add this but I didn't have a any way to verify test it at the time which is why I opened the issue.

**Comment by chcosta** [comment]
LGTM

**Comment by JeremyKuhne** [comment]
@dotnet-bot test this please

**Comment by JeremyKuhne** [comment]
@bpschoch, @stephentoub, @weshaggard Intermittent problem in the IO.Pipes.Tests? I assume this change isn't impacting this...

```
java.io.IOException: remote file operation failed: d:\j\workspace\dotnet_corefx_windows_release_prtest at hudson.remoting.Channel@571fc13e:dci-win-fbld-12: java.nio.file.AccessDeniedException: d:\j\workspace\dotnet_corefx_windows_release_prtest\bin\tests\Windows_NT.AnyCPU.Release\System.IO.Pipes.Tests\dnxcore50\api-ms-win-core-namedpipe-l1-2-1.dll
```
http://dotnet-ci.cloudapp.net/job/dotnet_corefx_prtest/1406/console

**Comment by JeremyKuhne** [comment]
@dotnet-bot test this please

**Comment by JeremyKuhne** [comment]
@dotnet-bot test this please

**Comment by JeremyKuhne** [comment]
@dotnet-bot test this please

**Comment by ellismg** [comment]
@JeremyKuhne The CI failure is something that @mmitche is tracking.  It seems like Jenkins can get into a state where it can't clean things up correctly after the test run completes.

**Comment by mmitche** [comment]
@JeremyKuhne Yeah I fixed this.

**Comment by PatrickMcDonald** [comment]
@weshaggard I'm only sorry it took me 3 months to notice that my pull request had been reverted!

**Pull request merged**
