### PR TITLE
Add System.Collections.Concurrent source and tests

### PR DESCRIPTION
**Pull request by YingP99**
This adds the System.Collections.Concurrent library and test code.

### CODE REVIEW

**Comment by mmitche** [comment]
Can one of the admins verify this patch?

**Comment by mmitche** [comment]
Can one of the admins verify this patch?

**Comment by joshfree** [comment]
add to whitelist

**Comment by joshfree** [comment]
I'm new to Jenkins, but hopefully that triggers testing of the PR (and all future PRs from you)

**Comment by mellinoe** [comment]
Not sure, but looks like something went wrong with the Jenkins build:

    Caused by: java.io.IOException: An existing connection was forcibly closed by the remote host

**Comment by YingP99** [comment]
Look like timeout. It might be the same threading issues as others have encountered. I'm creating a VM to with one core to test.

**Comment by ellismg** [comment]
test this please

**Comment by ellismg** [comment]
I hope the above kicked off another Jenkins job.  It will be interesting to see if it failed in the same way (from the log it does look like it was running the new tests and things might have gotten hung).

**Comment by YingP99** [comment]
Test this please

**Comment by mmitche** [comment]
It doesn't look like that kicked it off again.  dotnet and microsoft are whitelisted organizations, but I'm not sure why it's not treating them as such.

**Comment by mmitche** [comment]
@ellismg, it looks like it was a hiccup in the Jenkins transport layer.  Can you respond test this please again?

**Comment by ellismg** [comment]
test this please

**Comment by YingP99** [comment]
The multithreading tests are failing on build machines (timeout/hang). So I'll close the PR and resubmit another one with less inner tests.

**Comment by mmitche** [comment]
I think this is a Jenkins bug, investigating

**Pull request closed without merging**
