### PR TITLE
Moving shared default between winHttp & Unix Handler to a seperate common file

### PR DESCRIPTION
**Pull request by rajansingh10**
new file:   ../../Common/src/System/Net/Http/HttpHandlerDefaults.cs
	modified:   ../../System.Net.Http.WinHttpHandler/src/System/Net/Http/WinHttpHandler.cs
	modified:   System.Net.Http.csproj
	modified:   System/Net/Http/Unix/CurlHandler.cs

Moved shared default to common file. Addressing issue #2787 .

### CODE REVIEW

**Comment by rajansingh10** [comment]
cc: @stephentoub, @davidsh, @CIPop, @SidharthNabar, @pgavlin

**Comment by stephentoub** [comment]
LGTM.  Presumably this is a starting point, and we'll move other defaults to the common file over time.

**Comment by rajansingh10** [comment]
@stephentoub yes, going ahead any common defaults will goto this file & related handlers will be modified.

**Comment by stephentoub** [comment]
The build failed because src\System.Net.Http.WinHttpHandler\src\System.Net.Http.WinHttpHandler.csproj wasn't updated to include the file.

**Comment by rajansingh10** [comment]
@stephentoub Fixed the issue.

**Comment by rajansingh10** [comment]
There was some issue during rebasing, So PR got closed. Corrected it now.

**Comment by rajansingh10** [comment]
@dotnet-bot test this please

**Comment by stephentoub** [comment]
There's a build failure:

C:\Program Files (x86)\MSBuild\12.0\bin\Microsoft.CSharp.CurrentVersion.targets(448,9): error MSB3105: The item "d:\j\workspace\dotnet_corefx_windows_debug_prtest\src/Common\src\System\Net\Http\HttpHandlerDefaults.cs" was specified more than once in the "Sources" parameter.  Duplicate items are not supported by the "Sources" parameter. [d:\j\workspace\dotnet_corefx_windows_debug_prtest\src\System.Net.Http\src\System.Net.Http.csproj]

**Comment by rajansingh10** [comment]
@stephentoub  Fixed, build passed.

**Comment by stephentoub** [comment]
Thanks. LGTM.

**Pull request merged**
