### PR TITLE
Remove redundant check.

### PR DESCRIPTION
**Pull request by hackcraft**
Simple removal of a check-and-branch that has the same nett result in either
case.

Also added a comment to warn off anyone tempted to do the same dangerous
optimisation I attempted in #2809

### CODE REVIEW

**Comment by stephentoub** [comment]
@dotnet-bot test this please

**Comment by stephentoub** [comment]
LGTM

cc: @VSadov

**Comment by hackcraft** [comment]
BTW, does that comment to the bot work for anyone? There's been a couple of times there's been a failure that seemed to be unrelated to the actual commit, and I've wondered if there was a way to trigger another test.

**Comment by stephentoub** [comment]
> does that comment to the bot work for anyone? 

It does. We had a bunch of issues since yesterday that caused lots of PR failures, where the change to a new tool set, updating dependencies, and running tests as 64-bit exposed some latent issues, but I believe I've now fixed them all (or at least the most common problems) and things should be running smoothly again.

**Comment by VSadov** [comment]
LGRM

**Pull request merged**
