### PR TITLE
Inter-process communication tests

### PR DESCRIPTION
**Pull request by stephentoub**
Adds a project focused on inter-process communication testing, including an initial set of tests for a variety of IPC mechanisms (e.g. pipes, memory-mapped files, semaphores, etc.)

### CODE REVIEW

**Comment by stephentoub** [comment]
cc: @weshaggard, @Priya91, @pallavit, @mellinoe, @FiveTimesTheFun 

@weshaggard, I wasn't sure where this project should go.  If there's a better place for it, please let me know where to put it.

@Priya91, one or more of these tests may fail in CI until https://github.com/dotnet/corefx/pull/2418 is merged (the MMF test is particularly susceptible to it due to starting and then immediately waiting on the spawned process).

**Comment by stephentoub** [comment]
(Updated with feedback from Wes on where these tests should live.)

**Comment by stephentoub** [comment]
@dotnet-bot test this please

**Comment by stephentoub** [comment]
@Priya91, could you help review? Thanks.

**Comment by Priya91** [comment]
:+1: LGTM

**Comment by stephentoub** [comment]
Thanks, Priya.

**Pull request merged**
