### PR TITLE
Add test for AppDomain.SetData with the same key multiple times

### PR DESCRIPTION
**Pull request by stephentoub**
Closes https://github.com/dotnet/coreclr/issues/11453
cc: @sepidehMS, @AlexGhiondea

### CODE REVIEW

**Comment by stephentoub** [comment]
Blocked on new coreclr coming in

**Comment by stephentoub** [comment]
@dotnet-bot test this please

**Comment by ViktorHofer** [comment]
@stephentoub This should be fixed, right? I'm still hitting the issue locally. I cleaned and built everything again today.

```
System.Tests.AppDomainTests.SetData_SameKeyMultipleTimes_ReplacesOldValue [FAIL]
        System.InvalidOperationException : SetData can only be used to set the value of a given name once.
        Stack Trace:
              at System.AppDomain.SetData(String name, Object data)
           C:\Users\vikto\Documents\src\corefx\src\System.Runtime.Extensions\src\System\AppDomain.cs(150,0): at System.
  AppDomain.SetData(String name, Object data)
           C:\Users\vikto\Documents\src\corefx\src\System.Runtime.Extensions\tests\System\AppDomainTests.cs(271,0): at
  System.Tests.AppDomainTests.SetData_SameKeyMultipleTimes_ReplacesOldValue()
```

**Comment by stephentoub** [comment]
Yes, it's fixed.

> I cleaned and built everything again today

After pulling down the latest in master?  This is a deterministic failure, so if it weren't fixed, we would be seeing all legs in master fail as a result of this.

**Comment by ViktorHofer** [comment]
Yeah it was with the lastest master bit. Okay, hopefully it won't pop up again for me.

**Comment by ViktorHofer** [comment]
I just rebuilt everything, it is working now. Thanks!

**Pull request merged**
