### PR TITLE
Remove StreamToStreamCopy in HttpClient

### PR DESCRIPTION
**Pull request by justinvp**
This change removes the internal `StreamToStreamCopy` class, which is only used by `StreamContent.SerializeToStreamAsync`, thus avoiding the instance allocation of the class. `Stream` already has a built-in `CopyToAsync` helper that can be used, that `MemoryStream` [overrides](https://github.com/dotnet/coreclr/blob/ef1e2ab328087c61a6878c1e84f4fc5d710aebce/src/mscorlib/src/System/IO/MemoryStream.cs#L455-L457) to provide a more efficient implementation when the destination is another MemoryStream.

Also some minor cleanup: I made some fields `readonly` that could be, and removed an unused using.

Question about the existing behavior: If an exception is thrown during the copy operation, the source stream won't be disposed (if it can be disposed). Is this is by design? I was going to wrap the `await _content.CopyToAsync(...)` in a try/finally with the dispose in the finally, but I didn't want to change the existing behavior if it is by design.

### CODE REVIEW

**Comment by davidsh** [comment]
cc: @CIPop @SidharthNabar

**Comment by davidsh** [comment]
I'm concerned about this change.  SerializeToStreamAsync is a protected and thus a PUBLIC API surface.  There are many derived subclasses of the HttpContent base class. We're currently working a modification to this class to improve scenarios with .NETNative builds of this library which share this code.  And I would not want to do anything which would change the behavior of this class such as the questions you raised about the `dispose` issues.

**Comment by justinvp** [comment]
The dispose behavior hasn't changed, I was just asking the question about the existing behavior. If it needs to remain the way it is, for compat, it can.

Switching to using `Stream.CopyToAsync` should be a compatible change, unless `_content` is a `Stream` subclass that has overridden `CopyToAsync` with an incorrect implementation.

If `Stream.CopyToAsync` cannot be used here due to compat concerns, can we at least make the `StreamToStreamCopy` class static, so we don't have to allocate an instance of it? (In which case, what object should be passed to `Logging.Exception`, as `this` isn't available in a static class? null?)

**Comment by justinvp** [comment]
David, given the concern you raised, I'm going to close this and open a new PR that just makes `StreamToStreamCopy` static, to avoid the instance allocation, keeping its existing implementation as-is.

**Comment by davidsh** [comment]
ok.  Thx.

**Pull request closed without merging**
