### PR TITLE
Add SetCurrentDirectory test for a symlink path

### LINKED ISSUE #7358: System.IO.FileSystem: Unix SetCurrentDirectory follows symlinks
Using ```Directory.SetCurrentDirectory``` on a symlink in Unix follows the symlink and sets the directory to what the symlink links to. This differs from the Windows behavior as well as the behavior one would see on the command line using similar utilities.

Unit test:
```
[ConditionalFact(nameof(CanCreateSymbolicLinks))]
public void SetToPathContainingSymLink()
{
    var path = GetTestFilePath();
    var linkPath = GetTestFilePath();

    Directory.CreateDirectory(path);
    Assert.True(MountHelper.CreateSymbolicLink(linkPath, path, isDirectory: true));

    // Both the symlink and the target exist
    Assert.True(Directory.Exists(path), "path should exist");
    Assert.True(Directory.Exists(linkPath), "linkPath should exist");

    // Set Current Directory to symlink
    string currentDir = Directory.GetCurrentDirectory();
    try
    {
        Console.WriteLine("LINKPATH : " + linkPath);
        Console.WriteLine("PATH : " + path);

        Directory.SetCurrentDirectory(linkPath);
        Assert.Equal(path, Directory.GetCurrentDirectory());
    }
    finally
    {
        Directory.SetCurrentDirectory(currentDir);
    }
    Assert.Equal(currentDir, Directory.GetCurrentDirectory());
}
```

On Windows the current directory is set to LinkPath; on Unix it is path.

Ubuntu command line behavior using ```cd``` and ```pwd```:
```
mkdir cat
touch cat/fluffy
sudo ln -s cat fat
cd fat
pwd
```
prints ```/home/ianha/test/fat```. 

Ubuntu c program behavior using ```getcwd``` and ```chdir``` (what we interop to in System.IO.FileSystem) follows the link as expected:
```
#include <unistd.h>
#include <stdio.h>
#include <stdlib.h>

int main(char args[])
{
        char* currentPath = malloc(300);
        char linkPath[] = "fat";
        chdir(linkPath);
        getcwd(currentPath, 299);
        printf("%s\n", currentPath);
        free(currentPath);
}

```

Though the current behavior aligns with the c behavior on Unix, it is different from Windows so I decided to open this issue for Future visibility.

@stephentoub

### PR DESCRIPTION
**Pull request by ianhays**
resolves #7358

@stephentoub

### CODE REVIEW

**Comment by stephentoub** [comment]
Failure on OSX:
```
19:12:22    System.IO.Tests.Directory_SetCurrentDirectory+Directory_SetCurrentDirectory_SymLink.SetToPathContainingSymLink [FAIL]
19:12:22       Assert.Equal() Failure
19:12:22                  ↓ (pos 1)
19:12:22       Expected: /tmp/Directory_SetCurrentDirectory_SymLink···
19:12:22       Actual:   /private/tmp/Directory_SetCurrentDirectory···
19:12:22                  ↑ (pos 1)
19:12:22       Stack Trace:
19:12:23             at System.IO.Tests.Directory_SetCurrentDirectory.Directory_SetCurrentDirectory_SymLink.SetToPathContainingSymLink()
```

**Comment by ianhays** [comment]
Thanks Steve. This test is no good. I somehow forgot that ```path``` pointed to by ```linkPath``` is itself a symlink on OSX since I used GetTestFilePath() for it.

I'm going to hardcode OSX to expect "/private/" before the path I suppose. I don't recall a good (i.e. easy) way to get the path pointed to by a symlink.

**Comment by stephentoub** [comment]
> I don't recall a good (i.e. easy) way to get the path pointed to by a symlink.

readlink?

**Comment by ianhays** [comment]
>readlink?

That would work. I prefer pre-pending "private" to the expected path on OSX to adding an interop call, but I'm probably just being lazy :)

**Pull request merged**
