### PR TITLE
Implement VBMath module

### PR DESCRIPTION
**Pull request by iainnicol**
This module implements a VB6 compatible random number generator.

This code is a verbatim port of the Reference Source, with a couple
comments fixed.  The tests are new.

Relates to issue #31181.

### CODE REVIEW

**Comment by iainnicol** [comment]
Great.

**Comment by danmosemsft** [comment]
@iainnicol perhaps you'd like to take on more?

**Comment by iainnicol** [comment]
Yeah, now that I've got the hang of it, I'd like to try some more. Especially if there is no huge rush.

**Comment by danmosemsft** [comment]
No huge rush, but it needs to all get done in the next few months! Fortunately most of the work is easy.

I think only File* already has an active developer.

**Pull request merged**
