### PR TITLE
Fixing perf test runs for release branch

### PR DESCRIPTION
**Pull request by dsgouda**
- Revving xunit performance package references to 0035 (commit)
- Classifying NETCore JIT package as corerun dependency to fix perf helix test runs
@jhendrixMSFT @lt72 @MattGal

### CODE REVIEW

**Comment by lt72** [comment]
LGTM but please sync with Joel

**Comment by jhendrixMSFT** [comment]
@dsgouda this is a port of a change in master correct?  If so it would be good to provide the commit info in this PR.

**Comment by dsgouda** [comment]
@jhendrixMSFT 
I am a little confused here, the two commits I'm trying to reference here are 0d35a7fdc378de6df5058086bd1edddefcd2ed95 and ec9c0f28d2b76bf5bdf42cf3c57544d8ea970114
When I cherry-pick these commits, I see that some non-xunit-perf dependencies are also revved to rc4-* versions, xunit-performance does not need these dependencies and I'm not sure if these changes are going to be a part of RTM. Should I still reference the commits instead?
Currently, I have manually updated the xunit package references without cherry-picking any commits

**Comment by jhendrixMSFT** [comment]
@dsgouda The important part here is to show that the fix is in master and hasn't introduced any regressions.  It's ok (and expected in some cases) that the port to the release branch isn't an exact match (difference in package versions is a common example).

**Comment by MattGal** [comment]
LGTM

**Comment by joshfree** [comment]
Approved

**Pull request merged**
