### PR TITLE
[release/2.1] Fix ReadOnlySequence created out of sliced Memory owned by MemoryManager

### PR DESCRIPTION
**Pull request by teo-tsirpanis**
Fixes issue dotnet/runtime#57472

Main pr dotnet/runtime#57479

Also backported to 5.0 in dotnet/runtime#57562 and 3.1 in #43102. This PR will pave the way for backporting it to the `System.Memory` OOB package for .NET Framework.

# Customer Impact

A customer has encountered dotnet/runtime#57472 while on .NET Framework and reported it in dotnet/runtime#67295, necessiating backporting it once again. As an example provided in that issue, this memory manager:

``` csharp
private sealed class BasicMemoryManager : MemoryManager<byte>
{
    private readonly byte[] _buffer;
    public BasicMemoryManager(int size = 1024) => _buffer = new byte[size];

    protected override bool TryGetArray(out ArraySegment<byte> segment)
    {
        segment = new ArraySegment<byte>(_buffer);
        return true;
    }
    public override Span<byte> GetSpan() => _buffer;

    public override MemoryHandle Pin(int elementIndex = 0) => throw new NotSupportedException();
    public override void Unpin() => throw new NotSupportedException();
    protected override void Dispose(bool disposing) { }
}
```

will fail two of the following tests:

``` csharp
[Theory]
[InlineData(0, 32)]
[InlineData(0, 29)]
[InlineData(32, 32)] // fail: length 0
[InlineData(32, 29)] // fail: length -3
public void OffsetTest(int offset, int length)
{
    var mgr = new BasicMemoryManager(1024);
    var slice = mgr.Memory.Slice(offset, length);
    Assert.Equal(length, slice.Length);

    var ros = new ReadOnlySequence<byte>(slice);
    Assert.True(ros.IsSingleSegment);
    Assert.Equal(length, ros.Length);
}
```

# Testing

Failing test has been added in this PR.

# Risk

Low, as the change is very simple and obvious when you look at `ReadOnlySequence<T>` ctor that accepts `ReadOnlyMemory<T>` (notice line 133 versus lines 140 and 148):

https://github.com/dotnet/corefx/blob/0d40b482e6b6c232131dc808182d6b32d9d37394/src/System.Memory/src/System/Buffers/ReadOnlySequence.cs#L130-L149

Moreover, the changed code gets triggered only when creating a `ReadOnlySequence` from a `ReadOnlyMemory` backed by a `MemoryManager`. All other use cases (including creating from an array or from a `ReadOnlyMemory` backed by an array or a string) are unaffected. And the changes are identical to those in the other backports.

# Regression

This is not a regression.

### CODE REVIEW

**Comment by ericstj** [comment]
@dotnet/area-system-memory can someone please review this and be assigned as owner to take to tactics?

**Review by jozkee — APPROVED** [review]
No backporting conflicts and test classes in 2.1 seem similar as the ones in 3.1, which already contains the fix.

**Comment by danmoseley** [comment]
cc @Pilchie - for ASP.NET..

**Comment by jozkee** [comment]
@dotnet/area-infrastructure-libraries all Linux legs are being cancelled with this message:
```
##[warning]An image label with the label ubuntu-16.04 does not exist.
,##[error]The remote provider was unable to process the request.
Started: Just now
Duration: 44s
```
Is that concerning?

**Comment by ViktorHofer** [comment]
@danmoseley @ericstj looks like the release/2.1 branch isn't buildable and testable anymore based on Helix and docker EOL changes. Personally I didn't know that we still do servicing updates for 2.1 in the open.

**Comment by jozkee** [comment]
Ping @ericstj @danmoseley

**Comment by ericstj** [comment]
Chatted offline -- we believe we can merge this once it's ready.  I think this still needs package authoring.   Here's a recent example of a 2.1 fix that shipped a package: https://github.com/dotnet/corefx/commit/24e09fead0a4726566a0e4b8bc31656b2b9c2b77

**Comment by teo-tsirpanis** [comment]
Done @ericstj.

**Comment by jozkee** [comment]
@teo-tsirpanis @dotnet/area-infrastructure-libraries don't we need to include System.Memory in src/packages.builds?
https://github.com/dotnet/corefx/pull/43017/files#diff-43676c2abb12b62b72c9d923c709c340a45fafccf2a7b7daf84549b0ee2b0f54R26-R29

@ericstj does this still require local validation i.e: building 2.1 locally on Linux?

**Comment by teo-tsirpanis** [comment]
Oops I forgot it, will fix it soon.

**Comment by teo-tsirpanis** [comment]
Done @Jozkee.

**Comment by carlossanlop** [comment]
@Jozkee @ericstj If we are taking this, it needs to be merged directly into the 2.1 internal branch, not here. @Jozkee I'll give you instructions offline.

**Comment by carlossanlop** [comment]
Talked to @mmitche about this. We can take the change in the public repo, we will manually take care of any internal flows.

**Review by ViktorHofer — APPROVED** [review]
Infra changes LGTM

**Pull request merged**
