### PR TITLE
Port HttpListener fix for disconnect while reading request body

### PR DESCRIPTION
**Pull request by geoffkizer**
Merge fix #20428 

@stephentoub

### CODE REVIEW

**Comment by stephentoub** [comment]
@geoffkizer, FYI, one HttpListener test failed, though I don't know if it's related to your change:
```
System.Net.Tests.HttpListenerResponseHeadersTests.StatusCode_SetAndSend_Success(statusCode: 999, startLine: \"HTTP/1.1 999 \", expectedNumberOfBytes: 118) [FAIL]
        System.Net.Internals.SocketExceptionFactory+ExtendedSocketException : Connection refused 127.0.0.1:1168
        Stack Trace:
           /Users/dotnet-bot/j/workspace/dotnet_corefx/release_2.0.0/osx10.12_release_prtest/src/System.Net.Sockets/src/System/Net/Sockets/Socket.cs(4529,0): at System.Net.Sockets.Socket.DoConnect(EndPoint endPointSnapshot, SocketAddress socketAddress)
           /Users/dotnet-bot/j/workspace/dotnet_corefx/release_2.0.0/osx10.12_release_prtest/src/System.Net.Sockets/src/System/Net/Sockets/Socket.cs(825,0): at System.Net.Sockets.Socket.Connect(EndPoint remoteEP)
           /Users/dotnet-bot/j/workspace/dotnet_corefx/release_2.0.0/osx10.12_release_prtest/src/System.Net.Sockets/src/System/Net/Sockets/Socket.cs(930,0): at System.Net.Sockets.Socket.Connect(IPAddress[] addresses, Int32 port)
           --- End of stack trace from previous location where exception was thrown ---
              at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
           /Users/dotnet-bot/j/workspace/dotnet_corefx/release_2.0.0/osx10.12_release_prtest/src/System.Net.Sockets/src/System/Net/Sockets/Socket.cs(940,0): at System.Net.Sockets.Socket.Connect(IPAddress[] addresses, Int32 port)
           /Users/dotnet-bot/j/workspace/dotnet_corefx/release_2.0.0/osx10.12_release_prtest/src/System.Net.Sockets/src/System/Net/Sockets/Socket.cs(889,0): at System.Net.Sockets.Socket.Connect(String host, Int32 port)
           /Users/dotnet-bot/j/workspace/dotnet_corefx/release_2.0.0/osx10.12_release_prtest/src/System.Net.HttpListener/tests/HttpListenerFactory.cs(150,0): at System.Net.Tests.HttpListenerFactory.GetConnectedSocket()
           /Users/dotnet-bot/j/workspace/dotnet_corefx/release_2.0.0/osx10.12_release_prtest/src/System.Net.HttpListener/tests/HttpListenerResponseTests.cs(21,0): at System.Net.Tests.HttpListenerResponseTestBase..ctor()
              at System.RuntimeType.CreateInstanceDefaultCtor(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)
```
The tizen leg failure is entirely unrelated, just infrastructure.

**Comment by geoffkizer** [comment]
The OSX failure looks strangely similar to the connection pooling issue we're talking about.  I doubt it's related to my change.  Will rerun.

**Comment by geoffkizer** [comment]
@dotnet-bot test Innerloop OSX10.12 Release x64

**Comment by geoffkizer** [comment]
@dotnet-bot help

**Comment by geoffkizer** [comment]
@dotnet-bot test Innerloop OSX10.12 Release x64 Build and Test

**Pull request merged**
