### PR TITLE
Adjusted test for Dynamic method with ByRef return

### PR DESCRIPTION
**Pull request by cod7alex**
This PR changes test to reflect change to Dynamic method in coreclr: https://github.com/dotnet/coreclr/pull/15106.
I decided to use repro code as test here.

Related issue: https://github.com/dotnet/roslyn/issues/17993

@jkotas 

**Can be merged only after coreclr change**

### CODE REVIEW

**Comment by cod7alex** [comment]
@dotnet-bot test this please

**Comment by cod7alex** [comment]
This PR can be merged now.

**Comment by jkotas** [comment]
We need to wait for the next automatically generated PR that updates CoreCLR build used in CoreFX, like this one: https://github.com/dotnet/corefx/pull/25348. It will happen sometime today.

Your change will need to be cherry pick into that PR to make it green. One of the CoreFX maintainers will take care of it - you do not need to worry about it. Thanks!

**Comment by cod7alex** [comment]
Cool, thank you.

**Comment by jkotas** [comment]
Cherry picked into https://github.com/dotnet/corefx/pull/25368

**Pull request closed without merging**
