### PR TITLE
Enabling cross building of native corefx for Ubuntu 14.04 ARM target

### PR DESCRIPTION
**Pull request by leemgs**
ARM: Using the cross build process of coreclr, enable cross building
of native corefx components for Ubuntu 14.04 ARM target.
(e.g. u14.04$> ROOTFS_DIR=/work/dotnet/rootfs-corefx/arm \
		./build.sh native arm clean cross )

Signed-off-by: MyungJoo Ham <myungjoo.ham@samsung.com>
Signed-off-by: Geunsik Lim <geunsik.lim@samsung.com>
Signed-off-by: Prajwal A N <an.prajwal@samsung.com>

### CODE REVIEW

**Comment by leemgs** [comment]
This patch is based on the e19bb5b457a631a8f953d626757bd444db9c6a52 
(Mar 1 19:14:18 2016 -0800). 
We have tested on Ubuntu 14.04 X86 64bit PC and have executed 
"hello linux-arm 32bit.!!" on Raspberry Pi2 board.

**Comment by stephentoub** [comment]
Thanks, @leemgs.

> This patch is based on the e19bb5b 

That doesn't look like the right commit.  I'm assuming this is a replacement for https://github.com/dotnet/corefx/pull/6194?

cc: @jkotas 

> We have tested on Ubuntu 14.04 X86 64bit PC and have executed "hello linux-arm 32bit.!!" on Raspberry Pi2 board.

Very cool! :smile:

**Comment by stephentoub** [comment]
LGTM (as in that other PR, it'd be nice to factor out the cross-repo pieces, but that can be done separately)

**Comment by jkotas** [comment]
LGTM

**Pull request merged**
