### PR TITLE
Update dependencies: CoreCLR to rc3-24208-04, External to rc3-24208-00

### PR DESCRIPTION
**Pull request by dagood**
Making a manual PR because the CoreCLR auto-PR failed when it failed to do the native build. I'll be looking into why it tried to do a native build in the first place.

~~Added External upgrade because https://github.com/dotnet/corefx/pull/9243 didn't seem to go through CI right and this way we avoid merge conflicts.~~

/cc @dotnet/corefx-contrib

### CODE REVIEW

**Comment by joshfree** [comment]
Thanks @dagood.
/cc @eerhardt @mmitche re: github API limits being hit again

**Comment by dagood** [comment]
I mixed up PRs, this combines https://github.com/dotnet/corefx/pull/9254.

**Comment by dagood** [comment]
I mixed up some other PRs when I made this one, but looking more carefully, there is no other PR this is replacing.

**Comment by joshfree** [comment]
LGTM; feel free to merge once this passes CI

**Comment by mmitche** [comment]
@joshfree Please see my mail about the updates being rolled out tonight

**Comment by joshfree** [comment]
@mmitche just read it now; thanks for making the improvements! :)

**Pull request merged**
