### PR TITLE
Add tests for HtmlDecode and HtmlEncode to WebUtility

### PR DESCRIPTION
**Pull request by hughbe**
- Valid encoding
- Invalid encoding
- Unecessary encoding
- No encoding needed
- High BMP chars
- Surrogate pairs
- Chars in range 160-255

/cc @davidsh @stephentoub @jamesqo

### CODE REVIEW

**Comment by hughbe** [comment]
Test Innerloop CentOS7.1 Release Build and Test 
Test Innerloop OSX Release Build and Test
Tnnerloop Windows_NT Release Build and Test

**Comment by hughbe** [comment]
Test Innerloop Windows_NT Release Build and Test

**Comment by stephentoub** [comment]
LGTM. Thanks.

cc: @davidsh

**Comment by davidsh** [comment]
LGTM

**Comment by smith288** [comment]
I for some reason mistook LGMT as "Lets get this merged" lol

**Pull request merged**
