### PR TITLE
Update xml comment for {ReadOnly}Memory.Pin method

### PR DESCRIPTION
**Pull request by ahsonkhan**
See https://github.com/dotnet/coreclr/pull/17269#discussion_r177602812 for context.

This will need to get mirrored to coreclr (cc @Anipik)

### CODE REVIEW

**Comment by ahsonkhan** [comment]
@dotnet-bot test NETFX x86 Release Build
@dotnet-bot test Windows x64 Debug Build 
@dotnet-bot test Windows x86 Release Build

**Comment by ahsonkhan** [comment]
@dotnet-bot test Linux x64 Release Build
@dotnet-bot test NETFX x86 Release Build
@dotnet-bot test Windows x64 Debug Build 
@dotnet-bot test Windows x86 Release Build

**Comment by ahsonkhan** [comment]
@Anipik, @safern - it looks like mirroring isn't working as expected (waiting on a mirror PR to coreclr).

**Comment by safern** [comment]
It was stuck on a merge conflict -- just fixed it and it mirrored: https://github.com/dotnet/coreclr/pull/17556 opening https://github.com/dotnet/corefx/pull/29146

**Pull request merged**
