### PR TITLE
Port fix for 39638 to release/3.0

### PR DESCRIPTION
**Pull request by geoffkizer**
@danmosemsft 

Note: #39745 will need to go into release/3.0 too. It's currently blocked on eng system issues. If these get resolved, I will add to this PR. Can you approve that fix too?

### CODE REVIEW

**Comment by danmosemsft** [comment]
Approved - stress. Have we hammered enough on this using the stress app in master? @eiriktsarpalis any concerns about putting this into 3.0 today?

**Comment by geoffkizer** [comment]
I ran stress on this for about an hour locally, against http.sys. Zero failures, which is much better than previous results.

**Comment by danmosemsft** [comment]
Sounds good to me. Please go ahead.

**Comment by ahsonkhan** [comment]
Friendly reminder: please remember to squash commits when merging in the future (using the "Squash and merge" button on GitHub). Thanks.

**Pull request merged**
