### PR TITLE
Add reference assembly projects for significant past contract versions

### PR DESCRIPTION
**Pull request by ericstj**
This change adds projects to pull the reference assemblies from past packages for any significant contract revision.  Significant here means a version with different surface area that is supported on a different set of platforms.  EG.  System.Runtime 4.0.0 supported desktop 4.5, System.Runtime 4.0.10 supported desktop 4.5.1, etc.

These are needed for generations support in our nuget packages.

### CODE REVIEW

**Comment by ericstj** [comment]
@dotnet-bot test this please

**Comment by stephentoub** [comment]
@dotnet-bot test this please

**Comment by stephentoub** [comment]
@dotnet-bot test this please

**Comment by weshaggard** [comment]
I didn't review all the changes but the general approach looks good to me. Just make sure the CI is green.

**Comment by ericstj** [comment]
@dotnet-bot test this please

**Comment by ericstj** [comment]
Here's the error I am [seeing from CI](http://dotnet-ci.cloudapp.net/job/dotnet_corefx_windows_release_prtest/4656/consoleFull#1001945115a82fefab-f698-416f-8fca-58544c94cd4e).
> System.Diagnostics.DiagnosticSource.cs(6,66): error CS0840: 'System.Diagnostics.DiagnosticListener.AllListeners.get' must declare a body because it is not marked abstract or extern. Automatically implemented properties must define both get and set accessors. [d:\j\workspace\dotnet_corefx_windows_release_prtest\src\System.Diagnostics.DiagnosticSource\ref\System.Diagnostics.DiagnosticSource.csproj]

This looks like a valid error if the using the old CSC compiler.  Oddly enough it won't repro if I am using a Dev14 environment, so /langversion:5 doesn't seem to be working for this particular error (@pilchie).

This just started showing up because changes enabled build of the reference assembly projects during the open build.  The fix here is to update the syntax of this source file to not require c# 6.semantics.  I'll make that change.  /cc @vancem

**Comment by Pilchie** [comment]
Tagging @jaredpar for the `/langversion' discrepancy.

**Comment by ericstj** [comment]
@weshaggard if you are fine with the changes I'll go ahead and merge.

**Comment by weshaggard** [comment]
LGTM

**Pull request merged**
