### PR TITLE
Marking code as unchecked (pt 2)

### PR DESCRIPTION
**Pull request by dennisdietrich**
Marking code that may intentionally lead to over or underflows with
unchecked in preparation of turning on CheckForOverflowUnderflow for
all projects (issue #3140)

### CODE REVIEW

**Comment by tarekgh** [comment]
@karelz can we get the area owners of the touched files to code review the changes?

**Comment by karelz** [comment]
Sure if you think it is appropriate. Can you please arrange it? Here's the [list](https://github.com/dotnet/corefx/blob/master/Documentation/project-docs/issue-guide.md#areas). Thanks!

**Comment by tarekgh** [comment]
@mellinoe @VSadov @ianhays @saurabh500, @Priya91 @alexperovich @davidsh @AlexGhiondea @sepidehMS could you please help code reviewing the changes in your area?

**Comment by AlexGhiondea** [comment]
@dennisdietrich how did you identify the places where you need to put an `unchecked` block/expression?

**Comment by dennisdietrich** [comment]
@AlexGhiondea Same strategy as before: Turn on overflow checks globally and fix the resulting exceptions.

**Comment by tarekgh** [comment]
Went through the changes and LGTM. 

I merging it. if anyone got any comment we can try to fix it in other PR.

**Comment by davidsh** [comment]
System.Private.Uri changes LGTM.

**Comment by sepidehMS** [comment]
System.Private.Xml changes LGTM as.

**Pull request merged**
