### PR TITLE
Update OptimizationDataVersion

### PR DESCRIPTION
**Pull request by tmat**

### CODE REVIEW

**Comment by tmat** [comment]
@weshaggard

**Comment by weshaggard** [comment]
FYI - @AlexGhiondea

**Comment by weshaggard** [comment]
@tmat did you confirm that this works locally? I don't want to make assumptions that it is going to work as I've not looked at the workflow in a while.

**Comment by tmat** [comment]
@weshaggard Built `-release` locally but don't see IBC resource in `bin\AnyOS.AnyCPU.Release\System.Reflection.Metadata\netcoreapp\System.Reflection.Metadata.dll` :(

**Comment by tmat** [comment]
Is IBCMerge called locally or only on CI?

**Comment by weshaggard** [comment]
I think it is only happening in official builds. You need to pass EnableProfileGuidedOptimization=true to get it to run. https://github.com/dotnet/corefx/blob/2169709020cb51c95aedf66f3db7c41d7d54a725/buildpipeline/pipeline.json#L126

However I've not tested this locally myself @AlexGhiondea set this up so he would know for sure.

**Pull request merged**
