### PR TITLE
Forward porting AsyncRequestContext PR feedback.

### PR DESCRIPTION
**Pull request by CIPop**
Forward-porting changes made to #21100 after @DavidGoll 's PR feedback to 2.1.

Contributes to #20400.

### CODE REVIEW

**Comment by CIPop** [comment]
@dotnet-bot help

**Comment by CIPop** [comment]
@mmitche all "Portable" builds failed with
`Using context: Portable Linux x64 Debug Build
ERROR: /jenkins/workspace/dotnet_corefx/master/portable-linux-Config_Debug+OuterLoop_false_prtest@script/buildpipeline/portable-linux.groovy not found
`

**Comment by CIPop** [comment]
@dotnet-bot test outerloop netcoreapp Windows_NT Debug
@dotnet-bot test outerloop netcoreapp Windows_NT Release

**Comment by mmitche** [comment]
@dotnet/dnceng For visibility.  This is because of Wes's PR merge

**Comment by mmitche** [comment]
@dotnet-bot test this please

**Comment by CIPop** [comment]
> @dotnet/dnceng For visibility. This is because of Wes's PR merge

@mmitche @weshaggard OK to merge w/o the Portable tests passing or should I wait for a fix?

**Comment by weshaggard** [comment]
>OK to merge w/o the Portable tests passing or should I wait for a fix?

You can safely ignore the legs that start with "Portable". If you push another change to the your branch it should actually clear out all the old legs and only have the new legs.

**Comment by CIPop** [comment]
@mmitche The Linux error is:

```
16:19:05 + tar -czf bin/build.tar.gz --directory=bin/runtime/netcoreapp-null-Release-arm .
16:19:05 tar: bin/runtime/netcoreapp-null-Release-arm: Cannot open: No such file or directory
16:19:05 tar: Error is not recoverable: exiting now
16:19:06 Build step 'Execute shell' marked build as failure
16:19:06 [Current build status] check if current [FAILURE] is worse or equals then [SUCCESS] and better or equals then [SUCCESS]
16:19:06 Run condition [Current build status] preventing perform for step [[Archive the artifacts]]
```

Windows Outerloop failed with #21274.

**Comment by CIPop** [comment]
@mmitche the following runs were triggered but didn't run yet for the last day:


Innerloop Tizen armel Debug Cross Build — Triggered. (1/9 on auto-ubuntu1404-20170120)

Innerloop Tizen armel Release Cross Build — Triggered. (8/14 on auto-ubuntu1404-20170120)

Innerloop Ubuntu14.04 arm Release Cross Build — Triggered. (2/9 on auto-ubuntu1404-20170120)

Innerloop Ubuntu16.04 arm Debug Cross Build — Triggered. (7/14 on auto-ubuntu1404-20170120)

**Comment by weshaggard** [comment]
>@mmitche The Linux error is:

That was a known issue that fixed yesterday.

>@mmitche the following runs were triggered but didn't run yet for the last day:
Innerloop Tizen armel Debug Cross Build — Triggered. (1/9 on auto-ubuntu1404-20170120)
Innerloop Tizen armel Release Cross Build — Triggered. (8/14 on auto-ubuntu1404-20170120)
Innerloop Ubuntu14.04 arm Release Cross Build — Triggered. (2/9 on auto-ubuntu1404-20170120)
Innerloop Ubuntu16.04 arm Debug Cross Build — Triggered. (7/14 on auto-ubuntu1404-20170120)

All those runs were the old names so it is safe to ignore.

**Pull request merged**
