### PR TITLE
Remove dead code from System.Data.SqlClient

### PR DESCRIPTION
**Pull request by alexanderkozlenko**
Remove unused private fields, properties, constructors, methods, and nested types.

### CODE REVIEW

**Comment by alexanderkozlenko** [comment]
@dotnet-bot test  Innerloop Ubuntu Debug Build and Test

**Comment by alexanderkozlenko** [comment]
@dotnet-bot test Innerloop OpenSUSE13.2 Debug Build and Test

**Comment by mellinoe** [comment]
@saurabh500 

I recall you guys mentioning you had a special process for mirroring changes in the source code for this between the Desktop version and this version. Do you still have things like that in place, and would removing the dead code here cause any issues?

**Comment by saurabh500** [comment]
@mellinoe 
We had a system which would remove the #if #endif from the code for some directives.
We were using the DeadRegions.exe from the Microsoft Code Formatter project. 
Let me look at this PR.

**Comment by saurabh500** [comment]
cc @kkurni

**Comment by kkurni** [comment]
LGTM

**Comment by saurabh500** [comment]
@alexanderkozlenko Thanks for the clean up.

**Pull request merged**
