### PR TITLE
[rel/2.1] Add tests for TimeZoneInfo to ensure offset is not outside of range

### PR DESCRIPTION
**Pull request by krwq**
Tests for https://github.com/dotnet/coreclr/pull/18874

cc: @danmosemsft I presume this doesn't require additional shiproom?

tests should fail (linux) as long as coreclr PR is not merged

### CODE REVIEW

**Comment by tarekgh** [comment]
@krwq I assume this is a straight port from master. right?

**Comment by krwq** [comment]
yes

**Comment by danmosemsft** [comment]
Ok to merge yes

**Comment by krwq** [comment]
test this please

**Comment by danmosemsft** [comment]
waiting on https://github.com/dotnet/corefx/pull/31192

**Comment by krwq** [comment]
test Windows x64 Debug Build - failure seem to be unrelated but let's try again

**Pull request merged**
