### PR TITLE
Avoid disk fragmentation when unziping files

### PR DESCRIPTION
**Pull request by brunom**

### CODE REVIEW

**Comment by stephentoub** [comment]
Can you please share more details about what problem this is fixing?

Also, is this always going to work?  From a quick look at the implementation it seems like ZipArchiveEntry.Open works in more situations than ZipArchiveEntry.Length does, which would suggest this could actually be breaking some cases, unless I'm misunderstanding.

**Comment by brunom** [comment]
The idea is to tell Windows/ntfs the size of the file beforehand so it can reserve enough space. Otherwise Windows starts writing to short empty spans of disk and has to jump spans as the file grows.

**Comment by ericstj** [comment]
Correct, the Length getter can throw in the case you open a zip, modify an entry, then try to write it out.  You might be safer to access Length after you've already opened the entry.  Open will have similar constraints as checking the length and you'll want the exception to be thrown from Open rather than the Length getter.

It'd be good to increase the test coverage here: https://github.com/dotnet/corefx/blob/18d2d60caa5ddfc89f9a8bce6568cf207b4d1c24/src/System.IO.Compression.ZipFile/tests/ZipFileExtensions.ZipArchiveEntry.Extract.cs#L12 to add another case when the archive is opened in update mode, update after modifying the entry, and write mode to cover both success and failure cases and make sure this doesn't change any of the exceptions in those cases.

**Comment by scalablecory** [comment]
Are there any filesystems where `SetLength` can result in an I/O of the specified length?

**Comment by ericstj** [comment]
@carlossanlop @JeremyKuhne can you weigh in?  Also, @brunom do you have anything to back-up your claim about performance here: like a best practice document, white paper, or measurements?  @scalablecory makes a good point that this could have the opposite effect as well, and its hard to know unless you've tested all cases or have some documentation specifically perscribing this technique.

**Comment by lpereira** [comment]
FWIW, I checked the source for Info-Zip's unzip tool, and while it does have a function to set the file size to avoid fragmentation, it seems to be only called by their OS/2 port, even though it's defined for Win32 too (where it runs only on NT-based Windows).

**Comment by brunom** [comment]
Here's a discussion of when FileZilla started calling https://trac.filezilla-project.org/ticket/8094 SetEndOfFile. You can also use ProcMon to verify that when copying Windows sets file size before writing to created files.

**Comment by maryamariyan** [comment]
Thank you for your contribution. As announced in dotnet/coreclr#27549 this repository will be moving to dotnet/runtime on November 13. If you would like to continue working on this PR after this date, the easiest way to move the change to dotnet/runtime is:
1.	In your corefx repository clone, create patch by running `git format-patch origin`
2.	In your runtime repository clone, apply the patch by running `git apply --directory src/corefx <path to the patch created in step 1>`

**Comment by deinok** [comment]
What if the destination of the file is a stream like in linux?
Shouldn't the `SetLength` be guarded by `CanSeek`and `CanWrite`?

ref: https://docs.microsoft.com/en-us/dotnet/api/system.io.filestream.setlength?view=netcore-3.0

**Comment by maryamariyan** [comment]
Thank you for your contribution. As announced in #27549 the dotnet/runtime repository will be used going forward for changes to this code base. Closing this PR as no more changes will be accepted into master for this repository. If you’d like to continue working on this change please move it to dotnet/runtime.

**Pull request closed without merging**
