### PR TITLE
Use netcoreapp1.0 TFM for .NETCore validation

### PR DESCRIPTION
**Pull request by ericstj**
This change updates buildtools with the latest NuGet (3.5.0-rc) which has support for NETStandard1.6.  It also switches our validation moniker to netcoreapp1.0 instead of netstandardapp1.5, to match what is actually used by dotnet CLI.

/cc @weshaggard @chcosta @steveharter @bartonjs

### CODE REVIEW

**Comment by ericstj** [comment]
Note: we should be careful about using NETStandard1.6.  This enables us to use it in packaging folks won't be able to consume the netstandard1.6 assets out of the package until they have an updated NuGet client / DotNET CLI.  They won't fail, they'll just get the lower version.

**Comment by ericstj** [comment]
@dotnet-bot test Innerloop Windows_NT Release Build and Test

**Comment by ericstj** [comment]
Many legs hit this:
```
error MSB1021: Cannot create an instance of the logger. The given assembly name or codebase was invalid. (Exception from HRESULT: 0x80131047)
```
I often see this when updating buildtools.  I think it's due to a file-in-use issue.  We should probably have the CI kill running instances of MSBuild.exe and VBCSCompiler.exe that are left over from previous runs.

**Comment by ericstj** [comment]
@dotnet-bot please test Innerloop Windows_NT Debug Build and Test

**Comment by ericstj** [comment]
@dotnet-bot please test Innerloop Windows_NT Release Build and Test

**Comment by ericstj** [comment]
Actually, here's the root cause:
```
07:04:47 Errors in D:\j\workspace\windows_nt_de---4526f5ff\Tools\1.0.25-prerelease-00329-01\project.json
07:04:47     Unable to resolve 'Microsoft.DotNet.BuildTools (>= 1.0.25-prerelease-00329-01)' for 'DNXCore,Version=v5.0'.
07:04:47 ERROR: Could not restore build tools correctly. See 'D:\j\workspace\windows_nt_de---4526f5ff\init-tools.log' for more details.
```
Myget latency?

**Comment by ericstj** [comment]
@dotnet-bot test Innerloop Windows_NT Release Build and Test 
@dotnet-bot test Innerloop Windows_NT Debug Build and Test
@dotnet-bot test Innerloop CentOS7.1 Debug Build and Test
@dotnet-bot test Innerloop CentOS7.1 Release Build and Test

**Comment by ericstj** [comment]
Both OSX legs completed build/test successfully, but failed due to https://github.com/dotnet/corefx/issues/8166
```
07:22:17 tar: --exclude: Cannot stat: No such file or directory
07:22:17 tar: *.Tests: Cannot stat: No such file or directory
07:22:17 tar: Error exit delayed from previous errors.
07:22:17 Build step 'Execute shell' marked build as failure
```

**Comment by ericstj** [comment]
@dotnet-bot test Innerloop CentOS7.1 Debug Build and Test
@dotnet-bot test Innerloop CentOS7.1 Release Build and Test

**Comment by bartonjs** [comment]
> Note: we should be careful about using NETStandard1.6. This enables us to use it in packaging folks won't be able to consume the netstandard1.6 assets out of the package until they have an updated NuGet client / DotNET CLI. They won't fail, they'll just get the lower version.

They won't understand the new ref, and will be on an older contract version?  Or they won't understand the impl package and will fall back to the last impl before the runtime version was bumped?

**Comment by bartonjs** [comment]
Different error on OSX this time.  I wonder if we put a bad change in buildtools:

> 07:16:24   /Users/dotnet-bot/j/workspace/dotnet_corefx/master/osx_debug_prtest@2/bin/tests/AnyOS.AnyCPU.Debug/System.AppContext.Tests/dnxcore50/RunTests.sh: line 27: ${EXECUTION_DIR,,}: bad substitution
07:16:24   Hard linking dependent files...
07:16:24   cp: illegal option -- l
07:16:24   usage: cp [-R [-H | -L | -P]] [-fi | -n] [-apvX] source_file target_file
07:16:24          cp [-R [-H | -L | -P]] [-fi | -n] [-apvX] source_file ... target_directory
07:16:24   Using /Users/dotnet-bot/j/workspace/dotnet_corefx/master/osx_debug_prtest@2/packages/ as folder for resolving package dependencies.
07:16:24   Executing in /Users/dotnet-bot/j/workspace/dotnet_corefx/master/osx_debug_prtest@2/bin/tests/Unix.AnyCPU.Debug/Common.Tests/dnxcore50

**Comment by ericstj** [comment]
> They won't understand the new ref, and will be on an older contract version

Yes.

@MattGal I believe you're change https://github.com/dotnet/buildtools/pull/649 is causing trouble here that @bartonjs pointed out.

**Comment by bartonjs** [comment]
The TFM changes LGTM.  Thanks, Eric.

**Comment by weshaggard** [comment]
LGTM

**Comment by ericstj** [comment]
I'm going to revert @MattGal's buildtools change to unblock this change.

**Comment by ericstj** [comment]
Test Innerloop Windows_NT Debug Build and Test
Test Innerloop Windows_NT Release Build and Test
Test Innerloop CentOS7.1 Debug Build and Test
Test Innerloop CentOS7.1 Release Build and Test

**Comment by ericstj** [comment]
Test Innerloop Windows_NT Debug Build and Test
Test Innerloop Windows_NT Release Build and Test
Test Innerloop CentOS7.1 Debug Build and Test
Test Innerloop CentOS7.1 Release Build and Test

**Comment by ericstj** [comment]
Test Innerloop Windows_NT Debug Build and Test
Test Innerloop Windows_NT Release Build and Test
Test Innerloop CentOS7.1 Release Build and Test

**Pull request merged**
