### PR TITLE
Add tests for Semaphore

### PR DESCRIPTION
**Pull request by stephentoub**
We have some platform-specific code in Semaphore, but no tests for it.  This adds a bunch of Semaphore tests (plus a few additional ones for Barrier and SpinLock).

### CODE REVIEW

**Comment by stephentoub** [comment]
@dotnet-bot test this please

**Comment by stephentoub** [comment]
@dotnet-bot test this please

**Comment by stephentoub** [comment]
@dotnet-bot test this please

**Comment by stephentoub** [comment]
(The OpenExisting tests were initially failing due to OpenSemaphoreW not being exported from the PAL.  This was fixed in https://github.com/dotnet/coreclr/pull/979, and the tests now pass.)

**Comment by ellismg** [comment]
LGTM

**Comment by stephentoub** [comment]
Thanks, Matt.

**Pull request merged**
