### PR TITLE
Revert "Make debug the default native build configuration."

### PR DESCRIPTION
**Pull request by stephentoub**
Reverts dotnet/corefx#7005
https://github.com/dotnet/corefx/issues/7197

cc: @Priya91, @ianhays, @bjjones, @mellinoe

### CODE REVIEW

**Comment by Priya91** [comment]
This will cause build break on outerloop osx and ubuntu14.10. as we are copying the native libs built locally based on 
```
<ItemGroup Condition="'$(TestWithLocalLibraries)'=='true'">
      <TestCopyLocal Include="$(BaseOutputPath)$(OSGroup).$(Platform).$(ConfigurationGroup)/Native/*.*" />
    </ItemGroup>
```

So when building in Debug as default for managed, the script will look for debug native libs, which will not be built.

**Comment by stephentoub** [comment]
This zlib is only used on Windows.  Why will it cause a problem for OSX and Ubuntu?  Are you saying we're compiling and using this zlib on OSX and Ubuntu?  If so, that's the bug: we shouldn't be doing that.

**Comment by Priya91** [comment]
> This zlib is only used on Windows. Why will it cause a problem for OSX and Ubuntu? Are you saying we're compiling and using this zlib on OSX and Ubuntu? If so, that's the bug: we shouldn't be doing that.

I misunderstood the change, that it was for whole of native. But still regardless, when using TestWithLocalLibraries on Windows (as is the case with outerloop windows runs), we will not be copying over the locally built one, unless the ConfigurationGroup is explicitly specified. Should we make managed build also Release by default.

**Comment by stephentoub** [comment]
> Should we make managed build also Release by default.

No.  

> when using TestWithLocalLibraries on Windows (as is the case with outerloop windows runs), we will not be copying over the locally built one, unless the ConfigurationGroup is explicitly specified

Where will it get the zlib from in that case?  This should be a short-term workaround until we understand the root cause of the asserts.  If not copying over the local means we just end up running with one from a package, I'm fine with that.  We're not actively developing this component.

**Comment by Priya91** [comment]
> Where will it get the zlib from in that case? This should be a short-term workaround until we understand the root cause of the asserts. If not copying over the local means we just end up running with one from a package, I'm fine with that. We're not actively developing this component.

Yeah, it gets that version from package restore.

**Comment by Priya91** [comment]
@dotnet-bot Test outerloop Windows_nt debug

**Comment by Priya91** [comment]
LGTM

**Comment by stephentoub** [comment]
> Yeah, it gets that version from package restore.

Ok, good, that's fine.  Thanks, Priya.

We can re-revert this once we understand what's going on with #7197.

**Comment by mellinoe** [comment]
Thanks Stephen, LGTM.

**Comment by mellinoe** [comment]
It looks like it still hit the "no future" assertion.

````
11:33:48   Discovering: System.IO.Compression.ZipFile.Tests
11:33:48   Discovered:  System.IO.Compression.ZipFile.Tests
11:33:48   Starting:    System.IO.Compression.ZipFile.Tests
11:33:49   no future
11:33:49 D:\j\workspace\outerloop_win---c2e2123a\Tools\tests.targets(134,5): warning MSB3073: The command "D:\j\workspace\outerloop_win---c2e2123a\bin/tests/Windows_NT.AnyCPU.Debug/System.IO.Compression.ZipFile.Tests/dnxcore50/CoreRun.exe xunit.console.netcore.exe System.IO.Compression.ZipFile.Tests.dll  -xml testResults.xml -notrait Benchmark=true  -notrait category=failing -notrait category=nonwindowstests " exited with code 1. [D:\j\workspace\outerloop_win---c2e2123a\src\System.IO.Compression.ZipFile\tests\System.IO.Compression.ZipFile.Tests.csproj]
11:33:49 D:\j\workspace\outerloop_win---c2e2123a\Tools\tests.targets(141,5): error : One or more tests failed while running tests from 'System.IO.Compression.ZipFile.Tests' please check log for details! [D:\j\workspace\outerloop_win---c2e2123a\src\System.IO.Compression.ZipFile\tests\System.IO.Compression.ZipFile.Tests.csproj]
````

Does this mean we are still copying the local-built Debug binary?

**Comment by stephentoub** [comment]
> Does this mean we are still copying the local-built Debug binary?

My guess is that we're explicitly specifying Debug rather than relying on this default.  @mellinoe, do you want to track it down?  I can close this, assuming it's not having the desired effect.

**Comment by mellinoe** [comment]
Yeah, I can track this down, now that I have the context from #7197 .

**Comment by mellinoe** [comment]
I was able to repro this initially, but after deleting my package cache, it no longer reproduces. The bizarre part that I can't understand yet is that, when it did repro, the DLL in the native nuget package for clcompression was the debug version somehow, even though the version on myget is definitely not a debug version...

I've walked through the build steps and followed which DLLs are being copied around, and everything looks correct from what we initially thought, i.e. the DLL from the nuget package is being used. Like I said, the bizarre part is that there was a debug version in the nuget package folder, and I can't figure out why... Anyways like I said, when I deleted my package cache it stopped happening. I'm going to try to re-run this CI and see what happens.

@dotnet-bot Test OuterLoop Windows_NT Debug

**Comment by mellinoe** [comment]
I think I was over-complicating things above, and my repo was just in a bad state.

I think the problem is simply that even though we are setting the "default" value of CMAKE_BUILD_TYPE to "Debug", we are just overriding it a few lines later based on the value of /p:ConfigurationGroup passed in to build-native.cmd. So we end up building the native version anyways. I think in all of our CI builds, we are passing this parameter, so the default value at the top of the script probably has no effect in those cases.

Since CLRCompression.dll is the only native lib built for Windows, I guess we should just remove that part of Arg_Loop and therefore ALWAYS set CMAKE_BUILD_TYPE to "Release"?

**Comment by stephentoub** [comment]
> I think the problem is simply that even though we are setting the "default" value of CMAKE_BUILD_TYPE to "Debug", we are just overriding it a few lines later based on the value of /p:ConfigurationGroup passed in to build-native.cmd

Yeah, that's what I meant by "Or maybe we're explicitly specifying Debug rather than relying on this default" :)

**Comment by mellinoe** [comment]
I put a commit up here that comments out the configuration-parsing in build-native.cmd:

https://github.com/mellinoe/corefx/commit/3738fbe8dbb3519ee99cc1ea93b016cca9d1e646

You can add that commit to the PR or I could put up a separate PR for it.

**Comment by stephentoub** [comment]
Closing in favor of #7243.

**Pull request closed without merging**
