### PR TITLE
[WIP] Refactoring CoreFx build structure

### PR DESCRIPTION
**Pull request by chcosta**
https://github.com/dotnet/corefx/pull/11019

This change moves most of our build plumbing targets / properties into a separate build folder to ease with discoverability / reasoning about our build.

There are certainly some changes which may be overkill because they change the way we're used to interacting with our build.  init-tools.cmd, for example, is now in [repo root]/build/wrappers, so it's not as readily available.  I'm open to feedback on these types of changes, but I'd like to enable devs while at the same time making our repo a bit cleaner.

Unfortunately, this is also difficult to look at in a diff because there are so many moves, but you can feel free to look at my fork GitHub.com/chcosta/corefx:refactorbuild, to get an idea for what the repo will look like.

/cc @weshaggard @ericstj @dagood @jhendrixMSFT

### CODE REVIEW

**Comment by dagood** [comment]
I'll have to get back to this to take a closer look, but quickly checking https://github.com/chcosta/corefx/tree/refactorbuild, this looks a lot cleaner.

Will there be TFS-side changes needed?

**Comment by chcosta** [comment]
That's a good question.  I'll follow up on that.  I wouldn't expect there to be too much that would need to change for our TFS side, but I haven't looked around there recently.

I also expect, I'll need to update Jenkins since this is moving so much.  /cc @mmitche 

I'll take a look at our other internal builds but I don't think much will need to change for those.

**Comment by weshaggard** [comment]
I like a lot of what you have done here but I would like to hold off on this for now. I would actually like for us first to get into a room and walk through the changes together so we can better understand some of the intent. Can you schedule a time sometime next week (as I'm not in the office this week) to go through this?

**Comment by stephentoub** [comment]
> I like a lot of what you have done here but I would like to hold off on this for now. I would actually like for us first to get into a room and walk through the changes together so we can better understand some of the intent

Should this be closed in the meantime?

**Pull request closed without merging**
