### PR TITLE
Update buildtools to 119

### PR DESCRIPTION
**Pull request by ianhays**
@stephentoub @ellismg 

This is to consume https://github.com/dotnet/buildtools/pull/332

### CODE REVIEW

**Comment by stephentoub** [comment]
LGTM

**Comment by ianhays** [comment]
@dotnet-bot test this please

**Comment by ianhays** [comment]
"Timeout cloning repo" error

**Comment by ellismg** [comment]
@dotnet-bot test this please (marked one of the mac workers offline)

**Comment by stephentoub** [comment]
@dotnet-bot test this please (build timed out)

**Pull request merged**
