### PR TITLE
Store Activity wrapped into ObjectHandle in Logical CallContext

### PR DESCRIPTION
**Pull request by lmolkova**
Request to merge https://github.com/dotnet/corefx/pull/20963 into releae/2.0.0
Addresses #21027

**Is not approved by shiproom so far**

### CODE REVIEW

**Comment by stephentoub** [comment]
Should this be closed?

**Comment by karelz** [comment]
@lmolkova @vancem what is the status of this 2.0 PR?

**Comment by vancem** [comment]
We have fixed this bug (in the master branch, which corresponds to 2.1), and @lmolkova  opened this to port it to 2.0, but in E-mail I believe we decided that it was OK to just live with it. 

I think this can be closed.

@lmolkova ?

**Comment by karelz** [comment]
@lmolkova is OOF this week (maybe also on Mon), can you please ping the email thread with managers @vancem?

**Comment by vancem** [comment]
I have sent the e-mail to possibly interested parties.   The bottom line however, is that this fix is important enough for heroic measures.  It will already naturally get fixed in the next release.

**Pull request closed without merging**
