### PR TITLE
Enable DTFI & NFI netstandard 1.7 tests

### PR DESCRIPTION
**Pull request by tarekgh**
This change also include adding the missing APIs in the System.Text.Encoding.Extensions contract

### CODE REVIEW

**Comment by tarekgh** [comment]
cc @danmosemsft @AlexGhiondea @weshaggard @stephentoub

**Comment by tarekgh** [comment]
https://github.com/dotnet/coreclr/pull/7659
https://github.com/dotnet/coreclr/pull/7713
https://github.com/dotnet/corefx/issues/12816
https://github.com/dotnet/corefx/issues/11612
https://github.com/dotnet/corefx/issues/11611

**Comment by danmosemsft** [comment]
LGTM!

**Comment by tarekgh** [comment]
@stephentoub 

there is some failure 

```
14:56:49      System.Runtime.InteropServices.Tests.SafeArrayTypeMismatchExceptionTests.SerializationRoundTrip [FAIL]
14:56:49         Assert.Equal() Failure
14:56:49                                          ↓ (pos 289)
14:56:49         Expected: ···tterHelpers.cs:line 31
14:56:49         Actual:   ···tterHelpers.cs:line 26
14:56:49                                          ↑ (pos 289)
14:56:49         Stack Trace:
14:56:49   Discovering: System.Threading.Performance.Tests
14:56:49   Discovered:  System.Threading.Performance.Tests
```
https://ci.dot.net/job/dotnet_corefx/job/master/job/osx_release_prtest/2097/

do you think this can be related to your serialization change?

**Comment by danmosemsft** [comment]
@alexperovich added that, in 19f526

**Comment by tarekgh** [comment]
test Innerloop Windows_NT Release Build and Test please
test Innerloop Ubuntu14.04 Debug Build and Test please
test Innerloop OSX Release Build and Test please

**Comment by danmosemsft** [comment]
The issue above is tracked by https://github.com/dotnet/corefx/issues/12467

**Comment by tarekgh** [comment]
Thanks @danmosemsft for pointing to the issue. I'll merge my changes then.

**Pull request merged**
