### PR TITLE
Update branding for 3.1.22

### PR DESCRIPTION
**Pull request by vseanreesermsft**

### CODE REVIEW

**Review by Anipik — APPROVED** [review]

**Comment by wtgodbe** [comment]
What's up with the Linux jobs not being able to connect? Do we need to switch provider pools @Anipik? CC @MattGal

**Comment by Anipik** [comment]
It seems like ubuntu16 image no longer exists.

**Comment by wtgodbe** [comment]
Think we need to switch to the 1ES pool like this: https://github.com/dotnet/toolset/pull/5147/commits/9e91d4c3ea54f4ec60cbee09b4bbb24b426ea2b7

**Comment by Anipik** [comment]
@bartonjs can you take a look at the failure here. 

```
  In file included from /Users/runner/work/1/s/src/Native/Unix/System.Security.Cryptography.Native/apibridge.c:5:
/Users/runner/work/1/s/src/Native/Unix/System.Security.Cryptography.Native/opensslshim.h(99,22): error GA832097E: too many arguments provided to function-like macro invocation [/Users/runner/work/1/s/src/Native/build-native.proj]
##[error]src/Native/Unix/System.Security.Cryptography.Native/opensslshim.h(99,22): error GA832097E: (NETCORE_ENGINEERING_TELEMETRY=Build) too many arguments provided to function-like macro invocation
  int CRYPTO_num_locks(void);
                       ^
  /usr/local/Cellar/openssl@3/3.0.0_1/include/openssl/crypto.h:287:11: note: macro 'CRYPTO_num_locks' defined here
  #  define CRYPTO_num_locks()            (1)
            ^

```

cc @ericstj

**Comment by bartonjs** [comment]
The build machine has OpenSSL 3's headers installed (/usr/local/Cellar/openssl@3/3.0.0_1/...).  .NET Core 3.1 doesn't support OpenSSL 3 or build against it's headers.

I'm not sure how those machines get populated or selected, but what we want is OpenSSL 1.1.1 (the homebrew `openssl@1.1` formula)

**Comment by MattGal** [comment]
> The build machine has OpenSSL 3's headers installed (/usr/local/Cellar/openssl@3/3.0.0_1/...). .NET Core 3.1 doesn't support OpenSSL 3 or build against it's headers.
> 
> I'm not sure how those machines get populated or selected, but what we want is OpenSSL 1.1.1 (the homebrew `openssl@1.1` formula)

All the different hosted macos machines get imaged according to the docs here: https://github.com/actions/virtual-environments/tree/main/images/macos.  You're free to do whatever to the machine in your scripts (they're VMs, reset every build) but these images change whenever they want and our outside DncEng's control.

**Comment by Anipik** [comment]
the crypto certificate failure is known

**Pull request merged**
