### PR TITLE
Fixing issue #4355: Remove project reference to System.Runtime.Serial…

### PR DESCRIPTION
**Pull request by SGuyGe**
…ization.Primitives from System.Private.DataContractSerialization

@shmao @khdang @zhenlan

### CODE REVIEW

**Comment by shmao** [comment]
Nit: fix the title of the commit info.

LGTM.

**Comment by zhenlan** [comment]
LGTM

Since you are touching this, can you please double check system.private.DCS package indeed has a dependency on system.xml.xmlserializer?

**Comment by stephentoub** [comment]
@dotnet-bot test this please (timeout and #4396)

**Comment by stephentoub** [comment]
LGTM

**Comment by SGuyGe** [comment]
Yes System..Private.DataContractSerializer does have a dependency on System.Xml.XmlSerializer.

**Pull request merged**
