### PR TITLE
Port 2.0: Prep tests for CoreCLR/CoreRT [Serializable] cleanup (#20035)

### PR DESCRIPTION
**Pull request by morganbr**
2.0 port of #20035 Fixes tests that depend on types in System.Private.CoreLib being serializable that won't be serializable soon.

Fixes https://github.com/dotnet/corefx/issues/20041.

### CODE REVIEW

**Comment by morganbr** [comment]
CC @danmosemsft @tarekgh @dotnet/corert-contrib

**Comment by tarekgh** [comment]
LGTM. Thanks @morganbr

**Comment by danmosemsft** [comment]
Let's gather all changes and talk to shiproom before merging.

**Comment by tarekgh** [comment]
> Let's gather all changes and talk to shiproom before merging.

Is this will be done through the email or there is scheduled meeting for it?

**Comment by danmosemsft** [comment]
> Is this will be done through the email or there is scheduled meeting for it?

We are doing shiproom by email this week. We may end up going to shiproom physically on Thursday given the size of the change. We will have to explain that we will need to synchronize changes back and forth between coreclr and corefx which may take a couple days.

**Comment by tarekgh** [comment]
@danmosemsft any update regarding the shiproom?

**Comment by danmosemsft** [comment]
@tarekgh I have a conflict, but I'll send an update mail beforehand. Clearly we can't take it today.

**Comment by danmosemsft** [comment]
@morganbr I guess this is defunct?

**Comment by morganbr** [comment]
@danmosemsft yep. I'll close it out.

**Pull request closed without merging**
