### PR TITLE
Short-circuit in UrlEncode/Decode for WebUtility

### LINKED ISSUE #6542: WebUtility.UrlEncode/Decode methods allocate even when unneeded
As it stands, the [current implementation](https://github.com/dotnet/corefx/blob/master/src/System.Runtime.Extensions/src/System/Net/WebUtility.cs#L360-L362) of `WebUtility`'s `UrlEncode`/`Decode` methods allocate even when there is nothing to change in the original string, e.g. `UrlDecode("Foo")`. We should probably change this (I may submit a PR) so that it just returns the original string if no changes are needed.

### PR DESCRIPTION
**Pull request by jamesqo**
Partially fixes #6542 by short-circuiting in `UrlEncode` if no encoding is required. It uses the already-existing `IsUrlSafeChar` helper method to do this.

I think this may break in the case where a UTF-8 encoded string doesn't pass as 'safe' (and needs to be encoded), but its UTF-16 counterpart does. I'm not sure such a case could exist though, since all of the chars validated by `IsUrlSafeChar` should have the same representation when converted to UTF-8 and cast back to `char`.

cc @stephentoub @davidsh 

**edit:** Added commits to deal with this for `UrlDecode` as well.

### CODE REVIEW

**Comment by stephentoub** [comment]
@dotnet-bot test this please

**Comment by stephentoub** [comment]
Test Innerloop OSX Debug Build and Test please

**Comment by stephentoub** [comment]
This "short-circuiting" involves making another pass over the strings, which will add cost in the case where encoding is necessary.  How do we know that's a net-win based on cases where these functions are used?  Without perf data to show that it's truly beneficial, my inclination is to not do this.

**Comment by jamesqo** [comment]
@stephentoub Good point. I'm betting this could be rewritten with separate methods for the passes over the strings/byte arrays to do this without the extra pass. I'll be a bit busy for the next few days, though, so I'll close this for now.

**Pull request closed without merging**
