### PR TITLE
Revert Linq Version change 4.1.2.0 → 4.2.0.0 *no merge*

### PR DESCRIPTION
**Pull request by JonHanna**
This is failing for me locally, but a comment by @ericstj leads me to suspect maybe that is to be expected. It certainly shouldn't be merged until CI is definitely cleared though.

### CODE REVIEW

**Comment by justinvp** [comment]
I'm guessing `pkg/Microsoft.Private.PackageBaseline/packageIndex.json` needs to be changed back too.

**Comment by JonHanna** [comment]
It did.

I can build locally if I change the reference in System.Linq.Tets.csproj from referencing ..\pkg\System.Linq.pkgproj to referencing ..\src\System.Linq.csproj.

What further implications there?

**Comment by justinvp** [comment]
Have you tried reverting the change to packageIndex.json? I didn't see it in the diff here.

https://github.com/dotnet/corefx/blob/master/pkg/Microsoft.Private.PackageBaseline/packageIndex.json#L1607

**Comment by JonHanna** [comment]
Oh for goodness sake. I did, but then committed from too deep a directory and it didn't get included  :blush:

**Comment by JonHanna** [comment]
It would seem some change to layout/Microsoft.Private.CoreFx.NETCoreApp/Microsoft.Private.CoreFx.NETCoreApp.pkgproj or rather something(s) it pulls in needs to be changed.

@ericstj ?

**Comment by ericstj** [comment]
None of these are related to the index.

```
D:\j\workspace\windows_nt_de---4526f5ff\layout\Microsoft.Private.CoreFx.NETCoreApp\Microsoft.Private.CoreFx.NETCoreApp.pkgproj(63,5): error : Assembly 'System.Linq.Expressions' has insufficient version for dependency 'System.Linq' : 4.1.2.0 < 4.2.0.0.
D:\j\workspace\windows_nt_de---4526f5ff\layout\Microsoft.Private.CoreFx.NETCoreApp\Microsoft.Private.CoreFx.NETCoreApp.pkgproj(63,5): error : Assembly 'Microsoft.CSharp' has insufficient version for dependency 'System.Linq' : 4.1.2.0 < 4.2.0.0.
D:\j\workspace\windows_nt_de---4526f5ff\layout\Microsoft.Private.CoreFx.NETCoreApp\Microsoft.Private.CoreFx.NETCoreApp.pkgproj(63,5): error : Assembly 'System.Security.Cryptography.Encoding' has insufficient version for dependency 'System.Linq' : 4.1.2.0 < 4.2.0.0.
D:\j\workspace\windows_nt_de---4526f5ff\layout\Microsoft.Private.CoreFx.NETCoreApp\Microsoft.Private.CoreFx.NETCoreApp.pkgproj(63,5): error : Assembly 'System.ComponentModel.TypeConverter' has insufficient version for dependency 'System.Linq' : 4.1.2.0 < 4.2.0.0.
```
These are all problematic.  Those errors are occurring when I do a closure walk of the final output.

These are ref-def mismatches in the final package set that will cause runtime issues.  They're happening because each of these libraries is building against the old packages.

We could fix them all by adding p2p references but that is going to be painful.

I'm tempted to leave this as it is.  If we want to make this change that will be much easier once dev/eng work is done.

**Pull request closed without merging**
