### PR TITLE
Replace .NET Platform Standard with .NET Standard

### PR DESCRIPTION
**Pull request by terrajobst**
@weshaggard @ericstj @richlander

### CODE REVIEW

**Comment by richlander** [comment]
LGTM

**Comment by Petermarcu** [comment]
@terrajobst , we should avoid running CI on these changes. Looks good to me though. We need more of this kind of cleanup in the repo! Lots of stale docs.

**Comment by terrajobst** [comment]
@Petermarcu 

> we should avoid running CI on these change

Agree. Is there anything I need to do? Do I need to add a comment like "@dotnet no CI please"?

**Comment by davidfowl** [comment]
👏

**Comment by Petermarcu** [comment]
@terrajobst, in the PR comment write "skip ci please" with no quotes and it will skip. I want to add it to the PR template but didn't see where to edit that. In core-setup, its in the template but not as clear as I want it so wanted to update that one too :)

**Comment by weshaggard** [comment]
Ideally we should have some smarts in our CI that would automatically detect it. Seems like we could at least have some filters based on directories like documentation.

**Comment by Petermarcu** [comment]
Yes, @mmitche may have ideas on how we could exclude PR's with only certain files or file types from CI.

**Comment by mmitche** [comment]
@Petermarcu I am implementing that very feature at this second.

**Comment by mmitche** [comment]
According to the current plugin, skip ci must go in the initial comment (which kinda stinks).  I'll look at fixing this too.

**Pull request merged**
