### PR TITLE
Port test fixes from master into release/3.x

### PR DESCRIPTION
**Pull request by ViktorHofer**
cc @wfurt @stephentoub @davidsh @eiriktsarpalis

### CODE REVIEW

**Comment by ViktorHofer** [comment]
cc @Anipik

**Comment by danmosemsft** [comment]
@ViktorHofer this is large enough you should send a email with template to tactics for 'tell mode'.

**Comment by ViktorHofer** [comment]
Done

**Comment by ViktorHofer** [comment]
Can can someone pls approve the PR 🙏

**Comment by ViktorHofer** [comment]
I'm stuttering...

**Review by stephentoub — APPROVED** [review]

**Pull request merged**
