### PR TITLE
Port to 1.0.0: Move System.Linq.Expressions and System.Linq contracts to be supported from net463 

### PR DESCRIPTION
**Pull request by VSadov**
Porting change from https://github.com/dotnet/corefx/pull/9079 to the release branch.

Move System.Linq.Expressions and System.Linq contracts to be supported from net463

Fixes: #6017
Fixes: #9074

### CODE REVIEW

**Comment by VSadov** [comment]
@dotnet-bot test Innerloop Ubuntu14.04 Release Build and Test please

disk space issue

**Comment by VSadov** [comment]
@dotnet-bot test Innerloop OSX Debug Build and Test please
@dotnet-bot test Innerloop OSX Release Build and Test please

test machine went offline

**Comment by joshfree** [comment]
@mmitche

**Comment by mmitche** [comment]
@VSadov @joshfree Remember which machine it was?  I wonder whether it was one that got rebooted.  I would be surprised to see more disconnects.

**Pull request merged**
