### PR TITLE
Updating to RTM CLI

### PR DESCRIPTION
**Pull request by joperezr**
cc: @weshaggard @eerhardt 

Updating release/2.0 branch to the RTM CLI.

### CODE REVIEW

**Comment by eerhardt** [comment]
Do we need shiproom approval for this?  or at least a "tell" email?

**Comment by joperezr** [comment]
Good question, I'm not sure. @weshaggard ?

**Comment by weshaggard** [comment]
>Good question, I'm not sure. @weshaggard ?

@joperezr can you please make this PR against the dev/release/2.0.0 branch and we will get approval for all of it together.

**Comment by joperezr** [comment]
Will do, closing this one then.

**Pull request closed without merging**
