### PR TITLE
Check for IReadOnlyCollection

### PR DESCRIPTION
**Pull request by danielearwicker**
... as well as ICollection, to avoid IEnumerator loop.

### CODE REVIEW

**Comment by karelz** [comment]
Sounds reasonable, thanks for the fix!
@VSadov @OmarTawfik any concerns?

**Comment by VSadov** [comment]
Typecheck for a covariant generic interface is known to be very expensive. IReadOnlyCollection is one of those.
We need to know for sure that this leads to an improvement. Were there any measurements?
How does this affect common cases - when applying to lists, arrays, linq queries etc ?

**Comment by danielearwicker** [comment]
Have moved the new check to right before the enumerator allocation, so all collection types already supported will exit early and see no perf hit. So then the only impact would be the typecheck right before the full enumeration. I can run some tests to get a feel for how expensive the typecheck is in comparison to typical full iterations of various lengths.

**Comment by VSadov** [comment]
For reference - Here is a CoreClr bug about slowness of these casts: https://github.com/dotnet/coreclr/issues/603

The bug has some measurements. 
Since the bug is still open, I assume they are still relevant.

**Comment by VSadov** [comment]
One of the linked blog posts compares these casts with various tings and, for example, with exception of warm-up case, even `dynamic` casts could be 3x faster. - Just for the overall perspective on how slow these casts could be, unfortunately.

**Comment by danielearwicker** [comment]
Very interesting background, thanks. Wonder if anything can be done in the runtime about this.

**Comment by VSadov** [comment]
I think we should hold off fixes like this until  dotnet/coreclr#603 is fixed.

**Comment by stephentoub** [comment]
> I think we should hold off fixes like this until dotnet/coreclr#603 is fixed.

I agree.

FYI, there have been a few issues where this was discussed, e.g. https://github.com/dotnet/corefx/issues/24773, https://github.com/dotnet/corefx/issues/26579, etc.

Thanks for suggesting the change, but for now I'm going to close this.

**Comment by ViIvanov** [comment]
I think, the real collections, that implements IReadOnlyCollection<> also implements ICollection<> with IsReadOnly = true, so optimizations like this not needed.

**Pull request closed without merging**
