### PR TITLE
Update package index

### PR DESCRIPTION
**Pull request by weshaggard**
This should fix https://github.com/dotnet/corefx/issues/24606. 

This is a follow-up of https://github.com/dotnet/corefx/pull/23168 which fixes the inbox assembly versions. 

cc @ericstj

### CODE REVIEW

**Comment by ericstj** [comment]
SWAG: I believe the errors in the packaging build are caused because we're using live assembly version in the SupportedFrameworks clause.  We should update that clause to only list the TFMs that support that live version : for past frameworks that included a version inbox we should just harvest the SupportedFramework.

**Comment by weshaggard** [comment]
@ericstj https://github.com/dotnet/corefx/pull/24645/commits/a4364b283016758aff4d8ea162e6e8c550e2da6f is that what you had in mind? That seems to silence the validation errors.

**Comment by weshaggard** [comment]
Note I included https://github.com/dotnet/corefx/pull/24645/commits/d0e3851776a64cea638ae2c53f67a3b25def5756 to workaround an issue in the latest msbuild with path exclusions.

**Comment by ericstj** [comment]
> @ericstj a4364b2 is that what you had in mind? That seems to silence the validation errors.

Yep.

**Comment by ericstj** [comment]
UWP run appears to be infrastructure issue, in both cases tests are failing with `RemoteInvoke cannot open the remote service. Open Service Status: AppUnavailable`.
Test UWP CoreCLR x64 Debug Build

**Pull request merged**
