### PR TITLE
Removing warning for double importing versioning.targets

### PR DESCRIPTION
**Pull request by joperezr**
fixes: #8638 

Fixing the warning that was introduced by #8587 

cc: @stephentoub @weshaggard

### CODE REVIEW

**Comment by joperezr** [comment]
cc: @chcosta

**Comment by chcosta** [comment]
LGTM

**Comment by mellinoe** [comment]
LGTM

**Comment by stephentoub** [comment]
Test Innerloop OSX Debug Build and Test please

**Comment by joperezr** [comment]
@dotnet-bot test Innerloop OSX Debug Build and Test please

**Comment by weshaggard** [comment]
I made a comment on https://github.com/dotnet/corefx/pull/8587 but I will make it here as well. Why does the test.builds file need to versioning.targets?

**Pull request merged**
