### PR TITLE
Enable Tizen CI

### PR DESCRIPTION
**Pull request by gbalykov**
cc @alpencolt

### CODE REVIEW

**Comment by wtgodbe** [comment]
@dotnet-bot test CI please

**Comment by karelz** [comment]
@gbalykov is it still WIP on purpose? What is left? What is your timeline?

**Comment by gbalykov** [comment]
@karelz 

this PR should start to work after #32579 is merged

**Comment by gbalykov** [comment]
@dotnet-bot test this please

**Comment by gbalykov** [comment]
@dotnet-bot test ci please

**Comment by gbalykov** [comment]
@karelz Tizen tests have successfully passed

**Pull request merged**
