### PR TITLE
remove Linux SSL assert that's no longer true

### PR DESCRIPTION
**Pull request by geoffkizer**
My previous change made this assert no longer valid.  Remove it.

@stephentoub

### CODE REVIEW

**Comment by geoffkizer** [comment]
@dotnet-bot help

**Comment by geoffkizer** [comment]
@dotnet-bot test Linux x64 Debug Build

**Comment by karelz** [comment]
cc @Drawaes

**Comment by stephentoub** [comment]
@dotnet/dnceng, NullPointerException from Jenkins
https://ci3.dot.net/job/dotnet_corefx/job/master/job/linux-TGroup_netcoreapp+CGroup_Release+AGroup_x64+TestOuter_false_prtest/758/

**Pull request merged**
