### PR TITLE
Update Tizen CI docker image (tizen-rootfs-5.0m1)

### PR DESCRIPTION
**Pull request by JongHeonChoi**

### CODE REVIEW

**Comment by JongHeonChoi** [comment]
cc : @gbalykov

**Comment by JongHeonChoi** [comment]
@dotnet-bot test ci please

**Comment by stephentoub** [comment]
@dotnet-bot test this please

**Comment by gbalykov** [comment]
@JongHeonChoi same as for dotnet/core-setup#4246

**Comment by wtgodbe** [comment]
Ubuntu 16.04 is definitely preferable to 14.04

**Pull request merged**
