### PR TITLE
Add Usable HttpStatusCodes

### PR DESCRIPTION
**Pull request by RValore0323**
Including a handful of HttpStatusCodes that could be used

### CODE REVIEW

**Comment by axdiamond** [comment]
I need locked as well.

Currently, I can't use the .net status code enum because locked is missing.

**Comment by ViktorHofer** [comment]
@RValore0323 thanks for your first time contribution! Regarding the PR: Usually we first create an issue to discuss the desired change. Especially in this case I see a lot of potential discussion around the community (e.g. unofficial status codes).

This change is an API change as you are adding additional values to a public type. For such cases we definitely need a dedicated issue first as it must go trough the formal API review.

cc @karelz

**Comment by ViktorHofer** [comment]
See here: https://github.com/dotnet/corefx/blob/master/Documentation/coding-guidelines/adding-api-guidelines.md

**Comment by karelz** [comment]
Thanks @RValore0323 for your contribution!
@ViktorHofer is correct, we need to do API review first -- it is tracked in #4382 and waiting for formal API proposal (see link to example in [API process doc](https://github.com/dotnet/corefx/blob/master/Documentation/coding-guidelines/adding-api-guidelines.md)).

@RValore0323 if you are interested, please ping the API issue #4382. Until we have API review (which will take couple of weeks - just to set expectations), I would recommend to close this PR. We can reopen & update it when we have final API approved. Is that ok?

**Pull request closed without merging**
