### PR TITLE
Enabling perf tests' execution using universal runner

### PR DESCRIPTION
**Pull request by dsgouda**
@MattGal

### CODE REVIEW

**Comment by dsgouda** [comment]
@dotnet-bot Test  Innerloop Linux ARM Emulator Debug Cross Build

**Comment by MattGal** [comment]
LGTM except what are those failing ARM builds?

**Comment by dsgouda** [comment]
@dotnet-bot Test  Innerloop Linux ARM Emulator Debug Cross Build

**Comment by dsgouda** [comment]
@dotnet-bot Test  Innerloop Linux ARM Emulator Release Cross Build

**Comment by dsgouda** [comment]
@dotnet-bot Test Innerloop Linux ARM Emulator Debug Cross Build

**Comment by dsgouda** [comment]
@dotnet-bot Test Innerloop Linux ARM Emulator Release Cross Build

**Comment by dsgouda** [comment]
@stephentoub I believe we are still working on the ARM build failures, would it be safe to merge these changes in the meantime?

**Comment by stephentoub** [comment]
> would it be safe to merge these changes in the meantime?

Yes, you can ignore those Linux ARM CI failures.  Thanks.

**Pull request merged**
