### PR TITLE
branding for 2.1.17

### PR DESCRIPTION
**Pull request by Anipik**

### CODE REVIEW

**Comment by ViktorHofer** [comment]
Branding for 2.1.19 not 2.1.17 I guess, right?

**Comment by Anipik** [comment]
No it`s 2.1.17 and Microsoft.NETCore.Platforms version is 2.1.9

**Comment by ViktorHofer** [comment]
Ok, I love these versions :D

**Review by ViktorHofer — APPROVED** [review]

**Comment by joperezr** [comment]
Seems like we also forgot here to add the new entry for SqlClient on the package index right?

**Comment by Anipik** [comment]
> Seems like we also forgot here to add the new entry for SqlClient on the package index right?

we haven't yet released the package to nuget yet.

**Pull request merged**
