### PR TITLE
Add multiple test files for same class to System.Runtime.Extensions

### PR DESCRIPTION
**Pull request by hughbe**
- Follows the typical observation for tests across corefx.
- Removes clutter from the project

### CODE REVIEW

**Comment by stephentoub** [comment]
> Follows the typical guidelines for tests across corefx

Where is that stated?  I don't have a problem with it if that's a guideline we want to use, but in general we've used folders to map to namespaces, even if a few projects do otherwise.

**Comment by hughbe** [comment]
Oh right. Check out System.Globalization or System.Reflection or System.IO tests for examples of this

**Comment by stephentoub** [comment]
> Check out System.Globalization or System.Reflection or System.IO tests for examples of this

I understand there are other cases where this has been done, but are we explicitly trying to roll this out everywhere?  The PR message said "Follows the typical guidelines for tests across corefx"... where is this stated?

**Comment by hughbe** [comment]
Maybe the work observation was better than guideline ;)

**Comment by stephentoub** [comment]
> Maybe the word observation was better than guideline

Personally, I would prefer we not go through make changes like this... I find it harder to navigate a test folder if a folder might represent either a class or a namespace.  If such cases already exist, we can of course leave them, but I'm not seeing a need to go through an explicitly make this change everywhere the tests for a class are split across multiple files.  Others may of course disagree with me, and that's fine, but until we explicitly decide on this and update our test guidelines accordingly, I'd prefer to minimize such changes.

**Comment by hughbe** [comment]
Understood. Shall I close this PR then?

**Comment by stephentoub** [comment]
> Shall I close this PR then?

Yes, let's close it.  We can always reopen it later if we decide to follow this approach.  Regardless, thanks for your continued efforts to clean up the tests!

**Comment by hughbe** [comment]
No problemo

**Comment by hughbe** [comment]
And of course thanks for your continued effort reviewing! ;)

**Pull request closed without merging**
