### PR TITLE
Remove the friendly name attribute from PFX private keys.

### LINKED ISSUE #2583: PfxTests.TestPrivateKey intermittent failure
I can't repro it, but I got the following once:

```
 System.Security.Cryptography.X509Certificates.Tests.PfxTests.TestPrivateKey [FAIL]
               System.Security.Cryptography.CryptographicException : OpenCSP failed with error code 2148073494.
               Stack Trace:                  D:\Src\corefx\src\System.Security.Cryptography.Csp\src\System\Security\Cryptography\CapiHelper.cs(306,0): at Internal.NativeCrypto.CapiHelper.CreateProvHandle(CspParameters parameters, Boolean randomKeyContainer)
                  D:\Src\corefx\src\System.Security.Cryptography.Csp\src\System\Security\Cryptography\CapiHelper.cs(698,0): at Internal.NativeCrypto.CapiHelper.GetKeyPairHelper(CspAlgorithmType keyType, CspParameters parameters, Boolean randomKeyContainer, Int32 keySize, SafeProvHandle& safeProvHandle, SafeKeyHandle& safeKeyHandle)
                  D:\Src\corefx\src\System.Security.Cryptography.Csp\src\System\Security\Cryptography\RSACryptoServiceProvider.cs(89,0): at System.Security.Cryptography.RSACryptoServiceProvider.GetKeyPair()
                  D:\Src\corefx\src\System.Security.Cryptography.Csp\src\System\Security\Cryptography\RSACryptoServiceProvider.cs(69,0): at System.Security.Cryptography.RSACryptoServiceProvider..ctor(Int32 keySize, CspParameters parameters, Boolean useDefaultKeySize)
                  D:\Src\corefx\src\System.Security.Cryptography.Csp\src\System\Security\Cryptography\RSACryptoServiceProvider.cs(50,0): at System.Security.Cryptography.RSACryptoServiceProvider..ctor(CspParameters parameters)
                  D:\Src\corefx\src\System.Security.Cryptography.X509Certificates\src\Internal\Cryptography\Pal.Windows\CertificatePal.PrivateKey.cs(49,0): at Internal.Cryptography.Pal.CertificatePal.get_PrivateKey()
                  D:\Src\corefx\src\System.Security.Cryptography.X509Certificates\src\System\Security\Cryptography\X509Certificates\RSACertificateExtensions.cs(55,0): at System.Security.Cryptography.X509Certificates.RSACertificateExtensions.GetRSAPrivateKey(X509Certificate2 certificate)
                  D:\Src\corefx\src\System.Security.Cryptography.X509Certificates\tests\PfxTests.cs(70,0): at System.Security.Cryptography.X509Certificates.Tests.PfxTests.TestPrivateKey()
         Finished:    System.Security.Cryptography.X509Certificates.Tests
         
         === TEST EXECUTION SUMMARY ===
            System.Security.Cryptography.X509Certificates.Tests  Total: 157, Errors: 0, Failed: 1, Skipped: 0, Time: 0.854s
```

### LINKED ISSUE #2885: X509 ExportMultiplePrivateKeys test failed in CI
http://dotnet-ci.cloudapp.net/job/dotnet_corefx_windows_debug_prtest/3248/console
```
Discovering: System.Security.Cryptography.X509Certificates.Tests
  Discovered:  System.Security.Cryptography.X509Certificates.Tests
  Starting:    System.Security.Cryptography.X509Certificates.Tests
     System.Security.Cryptography.X509Certificates.Tests.CollectionTests.ExportMultiplePrivateKeys [FAIL]
        System.Security.Cryptography.CryptographicException : Error occurred during a cryptographic operation.
        Stack Trace:
           d:\j\workspace\dotnet_corefx_windows_debug_prtest\src\System.Security.Cryptography.X509Certificates\src\Internal\Cryptography\Pal.Windows\StorePal.Export.cs(82,0): at Internal.Cryptography.Pal.StorePal.Export(X509ContentType contentType, String password)
           d:\j\workspace\dotnet_corefx_windows_debug_prtest\src\System.Security.Cryptography.X509Certificates\src\System\Security\Cryptography\X509Certificates\X509Certificate2Collection.cs(123,0): at System.Security.Cryptography.X509Certificates.X509Certificate2Collection.Export(X509ContentType contentType, String password)
           d:\j\workspace\dotnet_corefx_windows_debug_prtest\src\System.Security.Cryptography.X509Certificates\src\System\Security\Cryptography\X509Certificates\X509Certificate2Collection.cs(116,0): at System.Security.Cryptography.X509Certificates.X509Certificate2Collection.Export(X509ContentType contentType)
           d:\j\workspace\dotnet_corefx_windows_debug_prtest\src\System.Security.Cryptography.X509Certificates\tests\CollectionTests.cs(482,0): at System.Security.Cryptography.X509Certificates.Tests.CollectionTests.ExportMultiplePrivateKeys()
  Finished:    System.Security.Cryptography.X509Certificates.Tests
```

### LINKED ISSUE #8393: Several EnvelopedCms test failures on Windows 7 and Windows 8.1
**Windows 7**

http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/master/job/outerloop_win7_release/lastCompletedBuild/testReport/System.Security.Cryptography.Pkcs.EnvelopedCmsTests.Tests/StateTests/PostDecrypt_Encode/

Stacktrace
MESSAGE:
Internal.Cryptography.CryptoThrowHelper+WindowsCryptographicException : Cannot find the certificate and private key for decryption
+++++++++++++++++++
STACK TRACE:
at System.Security.Cryptography.Pkcs.EnvelopedCms.DecryptContent(RecipientInfoCollection recipientInfos, X509Certificate2Collection extraStore) at System.Security.Cryptography.Pkcs.EnvelopedCmsTests.Tests.StateTests.PostDecrypt_Encode()

http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/master/job/outerloop_win7_release/lastCompletedBuild/testReport/System.Security.Cryptography.Pkcs.EnvelopedCmsTests.Tests/EdgeCasesTests/ImportEdgeCaseSki/

Stacktrace
MESSAGE:
Internal.Cryptography.CryptoThrowHelper+WindowsCryptographicException : Cannot find the certificate and private key for decryption
+++++++++++++++++++
STACK TRACE:
at System.Security.Cryptography.Pkcs.EnvelopedCms.DecryptContent(RecipientInfoCollection recipientInfos, X509Certificate2Collection extraStore) at System.Security.Cryptography.Pkcs.EnvelopedCmsTests.Tests.EdgeCasesTests.ImportEdgeCaseSki()

http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/master/job/outerloop_win7_debug/lastCompletedBuild/testReport/System.Net.Security.Tests/CertificateValidationClientServer/CertificateValidationClientServer_EndToEnd_Ok_useClientSelectionCallback__False_/

System.Net.Security.Tests.CertificateValidationClientServer.CertificateValidationClientServer_EndToEnd_Ok(useClientSelectionCallback: False) (from (empty))

MESSAGE:
System.AggregateException : One or more errors occurred. (Assert.Equal() Failure\r\nExpected: RemoteCertificateChainErrors\r\nActual: RemoteCertificateNotAvailable)\r\n---- Assert.Equal() Failure\r\nExpected: RemoteCertificateChainErrors\r\nActual: RemoteCertificateNotAvailable
+++++++++++++++++++
STACK TRACE:
at System.Threading.Tasks.Task.WaitAll(Task[] tasks, Int32 millisecondsTimeout, CancellationToken cancellationToken) at System.Threading.Tasks.Task.WaitAll(Task[] tasks, Int32 millisecondsTimeout) at System.Net.Security.Tests.CertificateValidationClientServer.<CertificateValidationClientServer_EndToEnd_Ok>d__5.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) --- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) --- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) ----- Inner Stack Trace ----- at System.Net.Security.Tests.CertificateValidationClientServer.ServerSideRemoteClientCertificateValidation(Object sender, X509Certificate certificate, X509Chain chain, SslPolicyErrors sslPolicyErrors) at System.Net.Security.SslStream.UserCertValidationCallbackWrapper(String hostName, X509Certificate2 certificate, X509Chain chain, SslPolicyErrors sslPolicyErrors) at System.Net.Security.SecureChannel.VerifyRemoteCertificate(RemoteCertValidationCallback remoteCertValidationCallback) at System.Net.Security.SslState.CompleteHandshake() at System.Net.Security.SslState.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest) at System.Net.Security.SslState.WriteCallback(IAsyncResult transportResult) --- End of stack trace from previous location where exception was thrown --- at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() at System.Net.Security.SslState.InternalEndProcessAuthentication(LazyAsyncResult lazyResult) at System.Net.Security.SslState.EndProcessAuthentication(IAsyncResult result) at System.Net.Security.SslStream.EndAuthenticateAsServer(IAsyncResult asyncResult) at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)

**Windows 8.1**

http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/master/job/outerloop_windows_nt_debug/lastCompletedBuild/testReport/System.Security.Cryptography.Pkcs.EnvelopedCmsTests.Tests/DecryptTests/Decrypt_IssuerAndSerial/

Stacktrace
MESSAGE:
Internal.Cryptography.CryptoThrowHelper+WindowsCryptographicException : Keyset does not exist
+++++++++++++++++++
STACK TRACE:
at System.Security.Cryptography.Pkcs.EnvelopedCms.DecryptContent(RecipientInfoCollection recipientInfos, X509Certificate2Collection extraStore) in D:\j\workspace\outerloop_win---bf7c4efa\src\System.Security.Cryptography.Pkcs\src\System\Security\Cryptography\Pkcs\EnvelopedCms.cs:line 240 at System.Security.Cryptography.Pkcs.EnvelopedCms.Decrypt(X509Certificate2Collection extraStore) in D:\j\workspace\outerloop_win---bf7c4efa\src\System.Security.Cryptography.Pkcs\src\System\Security\Cryptography\Pkcs\EnvelopedCms.cs:line 188 at System.Security.Cryptography.Pkcs.EnvelopedCmsTests.Tests.DecryptTests.VerifySimpleDecrypt(Byte[] encodedMessage, CertLoader certLoader, ContentInfo expectedContent) in D:\j\workspace\outerloop_win---bf7c4efa\src\System.Security.Cryptography.Pkcs\tests\EnvelopedCms\DecryptTests.cs:line 210 at System.Security.Cryptography.Pkcs.EnvelopedCmsTests.Tests.DecryptTests.TestSimpleDecrypt_RoundTrip(CertLoader certLoader, ContentInfo contentInfo, String algorithmOidValue, SubjectIdentifierType type) in D:\j\workspace\outerloop_win---bf7c4efa\src\System.Security.Cryptography.Pkcs\tests\EnvelopedCms\DecryptTests.cs:line 196 at System.Security.Cryptography.Pkcs.EnvelopedCmsTests.Tests.DecryptTests.Decrypt_IssuerAndSerial() in D:\j\workspace\outerloop_win---bf7c4efa\src\System.Security.Cryptography.Pkcs\tests\EnvelopedCms\DecryptTests.cs:line 30

### PR DESCRIPTION
**Pull request by bartonjs**
Windows, when creating a PFX, uses the friendly name attribute on a private key to record
    the key name at the time of export. On import this same name is used, if available.
    However, during a parallel load of the PFX there's a race condition where it has been determined
    that the key name is not in use but the key file has not yet been written. This allows parallel
    readers (same process or different) to collide on the key container name, and later cleanup can
    cause unpredictable results.

    The friendly name stripping was done with OpenSSL, using the following algorithm:
    * Validate MAC (check existing password)
    * Unpack the PKCS#7 authsafes from the PKCS#12 structure
    * Foreach authsafe
        * If the authtype is other than data, copy it as-is to the new authsafes list.
        * Otherwise (aka if pkcs7-data)
            * Unpack the PKCS#12 safebag from the PKCS#7 data blob
            * If the safebag's attribute collection contains 1.2.840.113549.1.9.20 then remove it.
            * Pack the safebag (modified or no) into a PKCS#7 data blob, append it to the new authsafes list.
    * Regenerate the MAC using the same password (since the encrypted materials are still using the same key)

    This approach was chosen over doing an ephemeral import followed by an export in Windows because OpenSSL
    exposes enough primitives to do the surgery without re-interpretation of the metadata, so it's a more
    minimal change to the datafiles than using Windows would be. The before and after can be diffed under ASN.1
    rules to determine that only two changes happened: 1) removal of any friendly name attributes,
    2) MAC regeneration.

Fixes #2583
Fixes #2885
Fixes #8393

cc: @AtsushiKan

### CODE REVIEW

**Comment by AtsushiKan** [comment]
LGTM

**Comment by bartonjs** [comment]
Ugh, I forgot to bump the SupplementalTestData version in the csproj.

**Comment by bartonjs** [comment]
Test Innerloop Windows_NT Debug Build and Test please (#3793)

**Comment by stephentoub** [comment]
LGTM

**Pull request merged**
