### PR TITLE
Do not pass ReadOnlySequence by "in" to the Utf8JsonReader.

### PR DESCRIPTION
**Pull request by ahsonkhan**
cc @stephentoub

### CODE REVIEW

**Comment by benaadams** [comment]
Its a 4 field struct (2x ptrs, 2x ints) so unlikely to get any benefit from SysV decomposition call passing; unless it was passed using vector calling at some point in the future; however it also isn't a vector size (24 bytes) so not sure that would work.

Also its only read from in a single pass for the .ctor so wouldn't get any advantages if it could be enregistered once loaded off the stack?

**Comment by stephentoub** [comment]
@benaadams, are you advocating for `in` or not `in`?  My preference is always simpler (aka not `in`) unless there's a demonstrated benefit to do otherwise.

**Comment by benaadams** [comment]
>  are you advocating for `in` or not `in`?

advocating for `in` 

However, both Utf8JsonReader's .ctor and its size are ferociously large; so an additional 28 byte stack copy will likely be lost in the noise...

**Comment by tannergooding** [comment]
> advocating for in

I said basically the same thing in the e-mail thread 😄

**Comment by ahsonkhan** [comment]
cc @BrennanConroy, @wli3, @billwert as an FYI

**Pull request merged**
