### PR TITLE
Collapse AsSpan().Slice(...) into .AsSpan(...)

### LINKED ISSUE #27330: Look for places to collapse AsSpan().Slice(start, length) into .AsSpan(start,length)

### PR DESCRIPTION
**Pull request by tarekgh**
Fixes #27330

### CODE REVIEW

**Comment by tarekgh** [comment]
CC @stephentoub @KrzysztofCwalina @AtsushiKan

**Comment by tarekgh** [comment]
> There's a lot of unrelated whitespace changes in the PR

Yes, I prefer setting my editor to remove the white spaces at the end of the lines. by the way, if you use code flow would be easier to see the actual changes and ignoring the space differences. 

thanks for your review.

**Comment by stephentoub** [comment]
? by the way, if you use code flow would be easier to see the actual changes and ignoring the space differences.

Or just adding `?w=1` to the url in the browser.

**Comment by stephentoub** [comment]
> Yes, I prefer setting my editor to remove the white spaces at the end of the lines.

Ok.  It'd be nice in the future if such widespread changes were isolated to their own commit or PR.

**Pull request merged**
