### PR TITLE
Fix for Base64 EncodeToUtf8 / DecodeFromUtf8 with empty input and isFinalBlock: false

### PR DESCRIPTION
**Pull request by gfoidl**
Fixes https://github.com/dotnet/corefx/issues/42236

Added test for this case, as there wasn't one + fixed it.

### CODE REVIEW

**Review by GrabYourPitchforks — CHANGES_REQUESTED** [review]
Per my comments at https://github.com/dotnet/corefx/issues/42236, I believe the 3.0 behavior to be correct. `OperationStatus.Done` means "all input has been consumed, and there was enough destination space in the output to hold the transformed data." For base64, this is trivially true for empty source buffers.

**Comment by gfoidl** [comment]
Let's conclude the correct behavior in the issue...I was to eager in fixing a "bug" I introduced :wink:

**Comment by gfoidl** [comment]
https://github.com/dotnet/corefx/issues/42236#issuecomment-548150697 -> close this PR and create a new one with the fix, or just update this one?

**Comment by GrabYourPitchforks** [comment]
If you already took the time to open this PR may as well keep using it. :)

**Comment by maryamariyan** [comment]
Thank you for your contribution. As announced in dotnet/coreclr#27549 this repository will be moving to dotnet/runtime on November 13. If you would like to continue working on this PR after this date, the easiest way to move the change to dotnet/runtime is:
1.	In your corefx repository clone, create patch by running `git format-patch origin`
2.	In your runtime repository clone, apply the patch by running `git apply --directory src/corefx <path to the patch created in step 1>`

**Comment by gfoidl** [comment]
I'm closing this one in favor of https://github.com/dotnet/corefx/pull/42395

**Pull request closed without merging**
