### PR TITLE
Ignore standard error when querying openssl

### LINKED ISSUE #9272: [Release/1.0.0]System.Net.Security.Tests failing on Opensuse
```
15:50:21   Copyright (C) 2014 Outercurve Foundation.
15:50:21   
15:50:21   Discovering: System.Net.Security.Unit.Tests
15:50:21   Discovered:  System.Net.Security.Unit.Tests
15:50:21   Starting:    System.Net.Security.Unit.Tests
15:50:22   Finished:    System.Net.Security.Tests
15:50:22   
15:50:22   === TEST EXECUTION SUMMARY ===
15:50:22      System.Net.Security.Tests  Total: 97, Errors: 0, Failed: 0, Skipped: 3, Time: 3.204s
15:50:22   Finished running tests. End time=22:51:38. Return value was 0
15:50:22 /mnt/resource/j/workspace/dotnet_corefx/release_1.0.0/opensuse13.2_debug/Tools/tests.targets(202,5): warning MSB3073: The command "/mnt/resource/j/workspace/dotnet_corefx/release_1.0.0/opensuse13.2_debug/bin/tests/Linux.AnyCPU.Debug/System.Net.Security.Tests/netcoreapp1.0/RunTests.sh /mnt/resource/j/workspace/dotnet_corefx/release_1.0.0/opensuse13.2_debug/packages/" exited with code -1. [/mnt/resource/j/workspace/dotnet_corefx/release_1.0.0/opensuse13.2_debug/src/System.Net.Security/tests/FunctionalTests/System.Net.Security.Tests.csproj]
15:50:22 /mnt/resource/j/workspace/dotnet_corefx/release_1.0.0/opensuse13.2_debug/Tools/tests.targets(211,5): error : One or more tests failed while running tests from 'System.Net.Security.Tests' please check log for details! 
```

### PR DESCRIPTION
**Pull request by ellismg**
On some platforms, we get error text from openssl when we query for null
ciphers. The error message is written to standard error and printed in a
way such that MSBuild thinks xUnit has encounted an error and fails the
entire test suite.

To work around this issue, we'll just ignore standard error when we do
this query.

Fixes #9272

### CODE REVIEW

**Comment by ellismg** [comment]
@dotnet-bot test Innerloop openSUSE13.2 Debug Build and Test please

**Comment by ellismg** [comment]
@dotnet-bot test Innerloop openSUSE13.2 Release Build and Test please

**Comment by ellismg** [comment]
test Innerloop openSUSE13.2 Debug Build and Test please
test Innerloop openSUSE13.2 Release Build and Test please

**Comment by ellismg** [comment]
Not my night for submitting PRs that don't need rebasing and don't have spelling errors.

test Innerloop openSUSE13.2 Debug Build and Test please
test Innerloop openSUSE13.2 Release Build and Test please

**Comment by stephentoub** [comment]
LGTM. Thanks, Matt.

**Pull request merged**
