### PR TITLE
Fixed typo

### PR DESCRIPTION
**Pull request by GerjanOnline**
Exising => Existing

### CODE REVIEW

**Comment by JonHanna** [comment]
LGTM

**Comment by GerjanOnline** [comment]
Not sure what's going wrong, does Github still have issues?

It can not find the commit if you click the commit of this PR:
https://github.com/dotnet/corefx/pull/7529/commits/ae23733307e7b3a0d4ef22c8930965bdd7ddee32

Original commit in my own fork:
https://github.com/GerjanOnline/corefx/commit/ae23733307e7b3a0d4ef22c8930965bdd7ddee32

**Comment by ericstj** [comment]
@dotnet-bot test this please.

**Comment by stephentoub** [comment]
> never mind, it does work now (after 15min), probably some delay somewhere in the Github servers ;)

It appears the issues were at least in part due to too many requests being made to GitHub:
```
14:57:03 Unable to query GitHub for status of PullRequestjava.io.IOException: {
14:57:03   "documentation_url": "https://developer.github.com/v3/#abuse-rate-limits",
14:57:03   "message": "You have triggered an abuse detection mechanism. Please wait a few minutes before you try again."
14:57:03 }
```

**Comment by stephentoub** [comment]
LGTM

**Pull request merged**
