### PR TITLE
[release/2.1] Add more Span-based parsing tests for Int32 and friends (#29363)

### PR DESCRIPTION
**Pull request by stephentoub**
Test only port of https://github.com/dotnet/corefx/pull/29363 to release/2.1

Closes https://github.com/dotnet/corefx/issues/29343

### CODE REVIEW

**Comment by stephentoub** [comment]
@dotnet-bot test Linux-musl x64 Debug Build please
```
/mnt/j/workspace/dotnet_corefx/release_2.1/linux-musl-TGroup_netcoreapp+CGroup_Debug+AGroup_x64+TestOuter_false_prtest/Tools/Symbols.targets(515,7): warning : Downloading https://dotnetfeed.blob.core.windows.net/dotnet-core/assets/symbols/runtime.linux-x64.Microsoft.NETCore.Runtime.CoreCLR.2.1.0-rc1-26419-03.symbols.nupkg failed with exception:  [/mnt/j/workspace/dotnet_corefx/release_2.1/linux-musl-TGroup_netcoreapp+CGroup_Debug+AGroup_x64+TestOuter_false_prtest/external/runtime/runtime.depproj]
/mnt/j/workspace/dotnet_corefx/release_2.1/linux-musl-TGroup_netcoreapp+CGroup_Debug+AGroup_x64+TestOuter_false_prtest/Tools/Symbols.targets(515,7): warning : Response status code does not indicate success: 404 (The specified blob does not exist.)
```

**Comment by stephentoub** [comment]
release/2.1 corefx needs to pull in a release/2.1 coreclr that contains https://github.com/dotnet/coreclr/pull/17820

**Comment by stephentoub** [comment]
@dotnet-bot test this please

**Comment by stephentoub** [comment]
@dotnet-bot test Linux x64 Release Build please
@dotnet-bot test OSX x64 Debug Build please
@dotnet-bot test Windows x64 Debug Build please
@dotnet-bot test Windows x86 Release Build please

**Comment by stephentoub** [comment]
> Assuming this was a clean cherry pick

Yup

**Comment by joperezr** [comment]
hey @stephentoub I was just wondering, why are we only porting the tests to release branch? Don't we want to fix bug #29343 for this release?

**Comment by stephentoub** [comment]
@joperezr, the fix is in coreclr and is already in the release/2.1 branch.

**Comment by stephentoub** [comment]
@dotnet-bot test Linux x64 Release Build please
@dotnet-bot test OSX x64 Debug Build please
@dotnet-bot test Windows x64 Debug Build please
@dotnet-bot test Windows x86 Release Build please

**Pull request merged**
