### PR TITLE
Remove the _customValues Dictionary.

### PR DESCRIPTION
**Pull request by saurabh500**
The change is meant for the issue #5611 

1. Remove the setter from the indexer.
2. Remove the dictionary from DbColumn
3. Allow the attributes being expsoed by the DbColumn to be retrieved using the names of the attributes as the default implementation.

The indexer in the DbColumn is supposed to allow access to the properties
being exposed by the DbColumn and its subclasses. The setter and the
storage is being removed from the DbColumn. The DbColumn will expose its
default properties using the indexer. However if a subclass of the
DbColumn needs to expose its properties via the indexer, then need to
implement their own mechanisms

### CODE REVIEW

**Comment by saurabh500** [comment]
@corivera @kkurni PTAL

**Comment by kkurni** [comment]
in my opinion, the switch case can be easily cause a human error (typo/ miss config) or more effort to do unit tests for each cases.

how about using reflector to get this automated ?

(I am not sure whether we have discussion about using reflector)

e.g 
```
public virtual object this[string propertyName]
        {
            get
            {
                var property = this.GetType().GetProperty(propertyName);
                if (property != null)
                    return null;
                else
                    return property.GetValue(this);
            }
        }
```

This will added a bit more performance but it is more convenient to write.
And each provider implementer doesn't need to override this method whenever they add new property.
Each provider can decide to optimized it if it needs too as well.

**Comment by corivera** [comment]
I like KK's idea, since it does the same thing but in an easily extensible way. You don't have to keep modifying the switch cases whenever you add a new field. We should do some perf testing on the switch vs reflection ideas, and if reflection doesn't add any severe penalty we should go with that.

**Comment by kkurni** [comment]
On second thought, why don't we enforce them to use property in getter as well ?
Since we already enforce setter to use property.

Except if we need to support DbColumn to be able to access any property without knowing specific implementer.

**Comment by NickCraver** [comment]
@kkurni A few points:

> This will added a bit more performance but it is more convenient to write.

With `nameof()` I don't agree this is true on the convenience side. It also eliminates the typos. The reflection route *is* a performance hit though. We're talking about saving providers the cost of implementation once vs. billions of runtime cost hits. It also prevents lining up several properties and heavily restricts what you can use. For example you may have a few switch labels for the same thing to support intuitive use on some database platforms.

> Except if we need to support DbColumn to be able to access any property without knowing specific implementer.

This is a key use case, libraries do not know the specific type - that's the exact reason for this design. To allow strongly or weakly typed access, without requiring libraries to reference every possible provider.

**Comment by NickCraver** [comment]
To give an idea of performance impact here (e.g. order of magnitude), a quick test of 10,000,000 iterations on this laptop:
 - Reflection: 2,495 ms
 - Switch: 131ms

Granted things like branch prediction are in play, but they're not making a huge impact - reflection is simply orders of magnitude slower than the dictionary which is pretty expected. Here's a simple gist to replicate: https://gist.github.com/NickCraver/92b8822b7f9cdc0be617

**Comment by saurabh500** [comment]
@NickCraver 
 >I would use a lot of nameof() in the switch here :) 

I would too and it would take care of a lot of problems wrt maintenance, convenience and readability. 
However there is no nameof() operator in C# 5.0.  CoreFX uses C# 5.0.

@kkurni  The performance numbers of switch vs Reflection favor switch by a far greater number.

**Comment by NickCraver** [comment]
> CoreFX uses C# 5.0.

Ah, fair enough. It's a non-breaking change to improve later when it's on the C#6 compilers, so not a blocker to continue with this, and doesn't prevent providers from using it. 

Tangential to this issue then: why isn't CoreFX on C# 6 yet? It's been out quite a while and this is yet another example of the benefits...

**Comment by saurabh500** [comment]
> Tangential to this issue then: why isn't CoreFX on C# 6 yet? It's been out quite a while and this is yet another example of the benefits.

https://github.com/dotnet/corefx/issues/1316 has discussions about this topic.
There are efforts underway to migrate our CI to support C# 6.0 and the related build tools.
Once the CoreFX repository is ready for migration, we will be able to use C# 6.0

There have been changes to test System.Reflection.Metadata to compile with 6.0, to test the upgrade to C# 6.0  https://github.com/dotnet/corefx/pull/5224

**Comment by saurabh500** [comment]
I have opened #5976 to make the change to C# 6.0 when its available.

**Comment by corivera** [comment]
LGTM

**Comment by kkurni** [comment]
LGTM

**Comment by kkurni** [comment]
@NickCraver, @saurabh500 I just quick prototype, it seems dynamic accessor give me faster results than switch.

https://gist.github.com/kkurni/eda73290642d56417e75

In my machine 
Switch : 720ms
Dynamic accessor : 523ms

image

**Comment by NickCraver** [comment]
@kkurni Running your test locally:
- Binder: 524ms
- Switch: 109ms

I have no idea how you'd get results for the binder to be faster (even excluding the spinup cost)...it's simply doing far more work than the `switch` which is already a dictionary lookup without the extra method calls tacked on. To be specific: any `switch` with 7 or more cases is converted to a dictionary in Roslyn; it's `if`/`else` logic with a lower case count.

Are you using an older compiler perhaps?

**Comment by kkurni** [comment]
@NickCraver 

Yes, I run it .net framework 4.6 and 4.5
Binder : 523
Switch : 745

But I also did quickly check using corefx, and it still give me slightly faster result.
image

Binder : 1015
Switch : 1030

This callsite binder essentially similar how it will called dynamic object. There is cache mechanism which I guess make it faster. But we still need to do another tests with different scenario.

I know that switch is faster, but I try to find another solution which will be more flexible but doesn't hurt performance as well.

**Comment by NickCraver** [comment]
@kkurni The only thing I can figure is you're compiling and running in `DEBUG` mode which disables almost all relevant optimizations in play. Here's a test that runs both: https://github.com/NickCraver/SwitchVsBinder

And here's me comparing the drastic difference the release optimizations make:
screen shot 2016-02-09 at 6 45 29 am

**Comment by kkurni** [comment]
Yes, you are correct. I tested using debug mode. But that performance still much better compare to reflection which originally took 2,495 ms. I don't think it cause exponential performance anymore. (We should test it with more iterations)
Do you think this performance reasonable to take?

**Comment by NickCraver** [comment]
@kkurni I don't think it's reasonable, no current reason list:
- Each provider would have to copy/paste that static code block into their code.
- Worse performance
- Less flexibility with the cases

If our argument for ~4x worse performance for "ease of use" when that ease is very arguable far less intuitive anyway - I don't think we've got a net win. If I'm a provider implementing the switch seems very intuitive and provides me all the flexibility I'm after. Copying a static constructor downstream everywhere is far less so.

**Comment by kkurni** [comment]
The provider should not override that static constructor / implementation of that callsite binder. The goal so that each provider just need to add any additional parameters in 1 place. 

Of course we still need to class that static to be a class constructor instead so that it will take the provider class parameter instead. (But this logic only happen in base class not in provider)

**Comment by NickCraver** [comment]
@kkurni How would each provider *not* have to do something here? The dictionary creation code only runs once and only looks at properties on the base class. The current code wouldn't include any added properties. IMO we're getting complicated to solve a simple problem which isn't a problem and performs better than the proposed solution. What if I have a static constructor myself? Even the initialization order rules aren't 100% defined or clear to *most* developers.

Please see it from the consumers point of view and take it as constructively as possible: if it's not intuitive to the designers, why would it be intuitive to the users?

**Comment by kkurni** [comment]
On second thought, it depends on how many more parameters that providers normally need to add ?
If it is only 3-5 more, than probably switch case will have no problems. but if it is more than 10+ more parameters, than automating this may be worth it.

Another option is in the base class we use "switch" but if a provider has 10+ more additional parameter, they can override this "switch" implementation with something else. or vice versa.

**Comment by kkurni** [comment]
@NickCraver. there won't be static constructor. it will be class constructor.
```
private Dictionary<string,CallSite<Func<CallSite, object, object>>> _dictionary = new Dictionary<string, CallSite<Func<CallSite, object, object>>>();
        public DbColumn()
        {
            foreach(var prop in this.GetType().GetProperties(BindingFlags.Instance | BindingFlags.Public))
            {
                var binder = Microsoft.CSharp.RuntimeBinder.Binder.GetMember(CSharpBinderFlags.None, prop.Name, typeof(DbColumn),
                new[] { CSharpArgumentInfo.Create(CSharpArgumentInfoFlags.None, null) });

                _dictionary.Add(prop.Name, CallSite<Func<CallSite, object, object>>.Create(binder));
            }

        }

        public object this[string propertyName]
        {
            get
            {
                var callsite = _dictionary[propertyName];
                return callsite.Target(callsite, this);
            }
        }
```

and the provider just need to add this.
```
public class SqlDbColumn
    {
        public string AnotherColumnName { get; set; }
        //
        //....
        //
    }
```

instead of
```
public class SqlDbColumn : DbColumn
    {
        public string AnotherColumnName { get; set; }
        //
        //....
        //

        public override object this[string propertyName]
        {
            get
            {
                switch (propertyName)
                {
                    case "AnotherColumnName":
                        return AnotherColumnName;

                }
                return base[propertyName];
            }
        }
    }
```

It depends on how many more parameters that providers normally need to add ?
If it is only 3-5 more, than probably switch case will have no problems. but if it is more than 10+ more parameters, than automating this may be worth it.

Another option is in the base class we use "switch" but if a provider has 10+ more additional parameter, they can override this "switch" implementation with something else. or vice versa.

I just try to find other alternatives because in my opinion forcing each provider to override object this[string propertyName] with "switch" case whenever they add more property is not intuitive.

**Comment by NickCraver** [comment]
@kkurni If the argument for a fix is this now runs *every* time, that's far more allocations and performance cost to factor in. That's certainly not a net win :-/

**Comment by kkurni** [comment]
Yes, unfortunately in constructor, there will reflection cost + allocations as well.

**Comment by NickCraver** [comment]
@kkurni perhaps blutness is best here: even in the 10 properties case (rare), you're arguing 20 lines of code saved is worth the runtime performance, allocation, and GC cost billions of times...and that's being pretty generous, this code will run far more than that.

IMO this problem is solved, and `nameof()` will soon eliminate the typos argument (https://github.com/dotnet/corefx/issues/3529#issuecomment-181950250). It's also trivial to unit test either way. To be honest: there's still a lot left to do like the entire database schema API, our time is better spent focusing on that.

**Comment by kkurni** [comment]
Ok, I agree with you.

@NickCraver just quick question regarding this weekly typed access feature.

As you mentioned before 
> This is a key use case, libraries do not know the specific type - that's the exact reason for this design. To allow strongly or weakly typed access, without requiring libraries to reference every possible provider

If each provider have their owned custom properties, will this still make sense to support this weakly typed access ?

e.g
It will end up checking null before getting any custom properties 
```
public void Process(DbColumn column)
 {
            if (column["specificSqlName"] != null)
            {
                // do something
            }

            if (column["specificSqlName2"] != null)
            {
                // do something else
            }
 }
```

How about if client can easily check the type of DbColumn and use strongly type access ?
```
        public void ProcessStrongType(DbColumn column)
        {
            if (column is SqlDbColumn)
            {
                Process(column.SpecificSqlName1);
                Process(column.SpecificSqlName12;
            }
        }
```

**Comment by NickCraver** [comment]
> If each provider have their owned custom properties, will this still make sense to support this weakly typed access ?

That's precisely *where* we want the weakly types access. In your second example, it would require every data access library to reference every provider to even do the cast. This would mean things like Dapper would have to reference SQL, MySQL, Oracle, Sqlite, etc... and custom providers are a no-go. The short version is: libraries cannot know about the specific types.

In applications where you're built on a specific provider and not supporting n (unlike a library), then strongly typed access may make more sense - the overall property + indexer design supports both scenarios well.

**Comment by kkurni** [comment]
Cool. Thanks for sharing this use case.

**Pull request merged**
