### PR TITLE
Remove trailing whitespace in System.Collections.Specialized

### PR DESCRIPTION
**Pull request by justinvp**

### CODE REVIEW

**Comment by weshaggard** [comment]
ok to test

**Comment by stephentoub** [comment]
LGTM

**Comment by weshaggard** [comment]
LGTM thanks @justinvp

**Comment by weshaggard** [comment]
@justinvp can you update the PR to get it to automatically merge?

**Comment by justinvp** [comment]
@weshaggard sorry, what do I need to update to get it to automatically merge?

**Comment by akoeplinger** [comment]
@justinvp rebase against master and force-push your branch to github.

**Comment by justinvp** [comment]
Done. Thanks.

**Comment by akoeplinger** [comment]
@justinvp hmm, the merge conflicts are still there. Are you sure you rebased against master?

**Comment by akoeplinger** [comment]
Ah, and make sure your master actually contains the latest changes from upstream master :)

**Comment by justinvp** [comment]
> make sure your local master actually contains the latest changes from upstream master

I thought it did, but I guess not; sorry! Should be good now.

**Pull request merged**
