### PR TITLE
Use corefx implementation of interop types for uapaot

### PR DESCRIPTION
**Pull request by jkotas**

### CODE REVIEW

**Comment by jkotas** [comment]
cc @stephentoub @shrah

**Comment by stephentoub** [comment]
@dotnet-bot test this please

**Comment by stephentoub** [comment]
@mmitche, is Jenkins down?

**Comment by karelz** [comment]
Jenkins is stuck - see #15781 cc @mmitche

**Comment by JonHanna** [comment]
@dotnet-bot test this please.

**Pull request merged**
