### PR TITLE
Add more tests for Enum.Parse/TryParse

### PR DESCRIPTION
**Pull request by stephentoub**
Additional coverage to help with https://github.com/dotnet/coreclr/pull/2933

### CODE REVIEW

**Comment by JonHanna** [comment]
LGTM

**Comment by jkotas** [comment]
> Unable to find an entry point named 'ToAscii' in DLL 'System.Globalization.Native'.

This failure is caused by me reverting the workaround in CoreCLR prematurely. I have put it back already.

**Comment by stephentoub** [comment]
> reverting the workaround in CoreCLR prematurely

Thanks. We can re-revert it on Monday after updating the package dependencies in corefx.

**Comment by stephentoub** [comment]
@dotnet-bot test this please

**Pull request merged**
