### PR TITLE
Port "Include framework references for .NET Framework facades" to release/1.0.0

### PR DESCRIPTION
**Pull request by mellinoe**
Port of #8791 to release.

### CODE REVIEW

**Comment by ericstj** [comment]
Do we need a similar fix for WCF?

**Comment by mellinoe** [comment]
> Do we need a similar fix for WCF?

I'm not sure. From the process that generated the ones in this PR, there was nothing to add for WCF. But that just means there are no facades in the targeting pack with matching names. It does seem like there should be something extra in this project, at least: https://github.com/dotnet/wcf/blob/master/src/System.ServiceModel.Http/pkg/System.ServiceModel.Http.pkgproj.

@roncain Do you think there are any of these properties missing in WCF?

**Comment by ericstj** [comment]
Suspect that's because you didn't evaluate the WCF pkgprojs.  See
image
That means we need some frameworkAssembly for those.  I imagine they're mostly in System.ServiceModel.

**Comment by mellinoe** [comment]
Oops, yes, you're right, I looked in the wrong folder. I will re-run my script and point it at WCF.

**Pull request merged**
