### PR TITLE
Merge System.Net.Sockets.Legacy tests into System.Net.Sockets

### LINKED ISSUE #7140: Merge System.Net.Sockets.Legacy.Tests into System.Net.Sockets.Tests
There is a lot of duplication between these two test collections, resulting in needing to make fixes in both places quite often.  We should just merge these and eliminate any duplicate testing.

### PR DESCRIPTION
**Pull request by ericeil**
This reduces duplication in the Sockets tests, and reduces the innermost development loop for Sockets changes to a single test assembly.

Fixes #7140.

@CIPop, please have a look.

### CODE REVIEW

**Comment by ericeil** [comment]
Note: this is two commits.  The first one merges the two test projects we had in System.Net.Sockets.Legacy, using `[Theory]` and `[InlineData]` to select the type of Async operation, rather than building the tests twice.  The second commit merges all of these tests into the main System.Net.Sockets tests.

**Comment by CIPop** [comment]
Thanks @ericeil! I like the new design that avoids recompilation. 
There are a lot of files that GH shows as deleted and it's a bit hard to check if any tests were lost.

LGTM if no tests got lost.

**Comment by stephentoub** [comment]
@dotnet-bot test this please

**Comment by stephentoub** [comment]
Several failures on OSX due to:
```
System.PlatformNotSupportedException : This platform does not support packet information for dual-mode sockets.  If packet information is not required, use Socket.Receive.  If packet information is required set Socket.DualMode to false.
```

**Comment by ericeil** [comment]
Added a commit to fix the OSX test failures.

**Comment by ericeil** [comment]
[CentOS failure](http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/centos7.1_debug_prtest/3998/): 
```
Build timed out (after 120 minutes). Marking the build as aborted.
```
@dotnet-bot test Innerloop CentOS7.1 Debug Build and Test please

**Pull request merged**
