### PR TITLE
[WIP]Update System.Runtime.WindowsRuntime.csproj

### PR DESCRIPTION
**Pull request by luqunl**
Try to see whether Eric's tool fix flow back from core-setup to corefx

### CODE REVIEW

**Comment by luqunl** [comment]
@dotnet-bot  test all

**Comment by luqunl** [comment]
@dotnet-bot help

**Comment by luqunl** [comment]
@dotnet-bot help

**Comment by luqunl** [comment]
@dotnet-bot test this please

**Comment by ericstj** [comment]
>error CS0117: 'SR' does not contain a definition for 'PlatformNotSupported_WindowsRuntime

You need to define that resource string in your resx

**Comment by luqunl** [comment]
Close this PR and use https://github.com/dotnet/corefx/pull/31780 instead fetch changes from my own fork.

**Pull request closed without merging**
