### PR TITLE
Adding Apis to DeflateStream and GZipStream

### PR DESCRIPTION
**Pull request by joperezr**
cc: @danmosemsft @stephentoub @weshaggard 

Adding:
- DeflateStream.BeginRead
- DeflateStream.EndRead
- DeflateStream.BeginWrite
- DeflateStream.EndWrite
- GZipStream.BeginRead
- GZipStream.EndRead
- GZipStream.BeginWrite
- GZipStream.EndWrite

For now, **all of those new Apis are commented out**, since they all are overrides of members in System.IO.Stream that don't exist in Core yet. I'll add those next and once we have packages ready to consume them, I'll come back and uncomment this code. 

related Issue: #9491

### CODE REVIEW

**Comment by justinvp** [comment]
Instead of adding back `DeflateStreamAsyncResult` and implementing the `Begin`/`End` methods, is there any reason the `Begin`/`End` methods couldn't be implemented by calling the `Task`-based methods?

**Comment by justinvp** [comment]
Perhaps consolidating the existing `ToApm` helpers in the repo into a more common location and making use of it here (https://github.com/dotnet/corefx/search?q=toapm).

See also: http://blogs.msdn.com/b/pfxteam/archive/2011/06/27/using-tasks-to-implement-the-apm-pattern.aspx

cc: @stephentoub

**Comment by stephentoub** [comment]
> Instead of adding back  DeflateStreamAsyncResult  and implementing the  Begin / End  methods, is there any reason the  Begin / End  methods couldn't be implemented by calling the  Task -based methods?

+1

For all of the APM methods we add back, I'd prefer wherever possible that we just wrap the XxAsync implementations rather than, e.g.
https://github.com/dotnet/corefx/commit/a1715b0aa2af05c550a492c2cff2eefe8615e29a#diff-4c78d6a515f6d590e30f3ad419a650e2R647

**Comment by joperezr** [comment]
Done

**Comment by justinvp** [comment]
👍

**Comment by stephentoub** [comment]
Since all of the code this is adding is commented out, I do question the value here. In the future for such cases, it'd probably be better to wait until it can just be added regularly. Especially since adding these will require more than just uncommenting, but also adding tests, probably bumping up a version dependency, etc. But since what you have doesn't hurt anything, go ahead with it. Thanks.

**Comment by danmosemsft** [comment]
I agree with Stephen (I didn't realize everything you changed would be commented :) ) but LGTM.

**Comment by joperezr** [comment]
Ok, I'll merge this for now, and will try to work from the bottom of the stack next time. I will send out a new PR that uncomments this and bumps the version of the contract, + some tests.

**Pull request merged**
