### PR TITLE
Update runtime IDs for new/upcoming RHEL/OL/Fedora releases

### PR DESCRIPTION
**Pull request by omajid**
I would have updated CentOS too, but CentOS does not include a minor version in runtime id.

The Fedora release is currently in development and should be released in about 3 months: https://fedoraproject.org/wiki/Releases/29/Schedule. I would like to start building .NET Core for it as soon as possible.

RHEL 7.5 has been released: https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/7/html/7.5_release_notes/index. Based on the release history (https://en.wikipedia.org/wiki/Red_Hat_Enterprise_Linux#RHEL_7) we should expect a 7.6 release in the future. I have added the same versions for other distributions with RHEL as their parent in the runtimeGroups.props file.

### CODE REVIEW

**Comment by joshfree** [comment]
Thanks @omajid

**Comment by joshfree** [comment]
@omajid would you mind opening PRs for this against the /release/2.1 and the /release/1.1.0 branches as well please?

/cc @leecow

**Comment by omajid** [comment]
@joshfree Thanks for merging. I have opened two PRs for release/2.1 and release/1.1.0. Should I open one for release/2.2 or release/1.0.0 as well?

**Comment by joshfree** [comment]
Thanks @omajid; just those long term servicing branches are fine.

**Pull request merged**
