### PR TITLE
Update README.md to include ubuntu15.10, rhel7.2, centos7.1 and opensuse13.2 outerloop badges.

### PR DESCRIPTION
**Pull request by Priya91**
cc @ellismg @stephentoub @joshfree @vijaykota

### CODE REVIEW

**Comment by ellismg** [comment]
FWIW, I would expect the Ubuntu 15.10 and openSUSE 13.2 outer loop runs to be on the floor as we will not install the correct version of the CLI (there's presently no CLI for Ubuntu 15.10 or openSUSE 13.2 for us to consume).  This would mean we can't run any managed code because we can't restore the tool runtime.

**Comment by Priya91** [comment]
@ellismg yeahh, the runs are failing becoz of no tools.. will change the outerloop runs for such oses to copy bits and test using run-test.sh to unblock.

**Comment by Priya91** [comment]
@dotnet-bot test ci please

**Comment by Priya91** [comment]
@dotnet-bot test ci please

**Comment by Priya91** [comment]
@ellismg @mmitche Can you guys please take a look. Thanks!

**Pull request merged**
