### PR TITLE
Add missing license headers to .cs files

### PR DESCRIPTION
**Pull request by stephentoub**
There are 77 .cs files in the repo lacking the standard license header we have on the other ~5400 .cs files.  This commit adds the missing ones.

### CODE REVIEW

**Comment by stephentoub** [comment]
cc: @joshfree, @weshaggard

**Comment by bartonjs** [comment]
LGTM

**Comment by weshaggard** [comment]
LGTM as well. Any ideas on how these got there? I would have expected any of our porting work to have run the code formatting tool.

**Comment by stephentoub** [comment]
Thanks, guys.  @weshaggard, I believe most of these were post-formatting tool, e.g. code was ported and run through the formatting tool, put on GitHub, and then additional files were added (such as during a Unix implementation or as part of adding more tests from scratch), and we missed during the code reviews that the files were missing headers.

**Pull request merged**
