### PR TITLE
Cleanup Array tests

### LINKED ISSUE #2336: Rename tests in System.Globalization
About 40-50% of the tests in System.Globalization do not have self descriptive names. They are currently named PosTest, NegTest etc.

### PR DESCRIPTION
**Pull request by hughbe**
The Array.* test files were removed because their functionality was
duplicated in Array.cs or I added tests that did the same thing in a
better way in Array.

This was not done to combine test files into a single class.

Increases coverage to over 90%

### CODE REVIEW

**Comment by hughbe** [comment]
Rebased to fix a merge conflict

**Comment by ianhays** [comment]
These are some good looking tests, thanks @hughbe. I'll remove my Array additions from #7562.

Only feedback I have is that I think we should add more cases to ```LastIndexOf_NonGeneric_TestData``` and ```LastIndexOf_Generic_TestData``` to cover the special-case for the empty array returning -1 i.e.

```
    public static IEnumerable<object[]> LastIndexOf_NonGeneric_TestData()
    {
        var stringArray = new string[] { null, null, "Hello", "Hello", "Goodbye", "Goodbye", null, null };
        yield return new object[] { stringArray, null, 7, 8, 7 };
        yield return new object[] { stringArray, "Hello", 7, 8, 3 };
        yield return new object[] { stringArray, "Goodbye", 7, 8, 5 };
        yield return new object[] { stringArray, "Nowhere", 7, 8, -1 };
        yield return new object[] { stringArray, "Hello", 2, 2, 2 };
        yield return new object[] { stringArray, "Hello", 3, 3, 3 };
        yield return new object[] { stringArray, "Goodbye", 7, 2, -1 };
        yield return new object[] { stringArray, "Goodbye", 7, 3, 5 };

        var stringArrayNoNulls = new string[] { "Hello", "Hello", "Goodbye", "Goodbye" };
        yield return new object[] { stringArrayNoNulls, null, 3, 4, -1 };

        var enumArray = new TestEnum[] { TestEnum.Case1, TestEnum.Case2, TestEnum.Case1 };
        yield return new object[] { enumArray, TestEnum.Case1, 2, 3, 2 };
        yield return new object[] { enumArray, TestEnum.Case3, 2, 3, -1 };

        var nullableArray = new int?[] { 0, null, 10, 10, 0 };
        yield return new object[] { nullableArray, null, 4, 5, 1 };
        yield return new object[] { nullableArray, 10, 4, 5, 3 };
        yield return new object[] { nullableArray, 100, 4, 5, -1 };

        yield return new object[] { new int[0], 0, 0, 0, -1 };
        yield return new object[] { new int[0], 0, -1, 0, -1 };
    }

    public static IEnumerable<object[]> LastIndexOf_Generic_TestData()
    {
        var intArray = new int[] { 7, 7, 8, 8, 9, 9 };
        yield return new object[] { intArray, 8, 5, 6, 3 };
        yield return new object[] { intArray, 8, 1, 1, -1 };
        yield return new object[] { intArray, 8, 3, 3, 3 };
        yield return new object[] { intArray, 7, 3, 2, -1 };
        yield return new object[] { intArray, 7, 3, 3, 1 };
        yield return new object[] { new int[0], 0, 0, 0, -1 };
        yield return new object[] { new int[0], 0, -1, 0, -1 };
    }
```

Other than that, LGTM.

**Comment by hughbe** [comment]
Good suggestion. I've added those tests in a new commit

**Comment by ianhays** [comment]
Thanks! LGTM.

**Comment by hughbe** [comment]
Test Innerloop Ubuntu Release Build and Test

**Pull request merged**
