### PR TITLE
Optimize Enumerable.Cast calls followed by ToArray or ToList, refactor Count

### PR DESCRIPTION
**Pull request by jamesqo**
This PR contains 3 changes:

- Segregate parts of `Enumerable.Count` so it is possible to call `Count` from an IIListProvider w/o going into an infinite loop. This is useful for iterators (like this one) where we can optimize `ToArray` or `ToList` but not `Count`.

- Optimize the iterator returned by `Cast` for non-generic ICollections; in `ToArray` and `ToList` we can preallocate an array before enumerating the items. Common BCL containers such as List/Queue/Array/etc. implement the non-generic interface, so the optimizations should benefit a lot of code.
  - GetCount can't be optimized since just returning the `.Count` of the source collection wouldn't actually verify that all of the elements in it were of type TResult. This isn't a problem for `ToArray` / `ToList` however, since we have to go through the entire collection anyway.

- Add extensive testing for the changes, including regression tests to make sure that `Skip`, `ElementAt`, `Last`, etc. aren't optimized.

@stephentoub, @VSadov, @JonHanna

### CODE REVIEW

**Comment by stephentoub** [comment]
@jamesqo, as I've mentioned before, there are practically an infinite number of possible optimizations one could add to LINQ.  Each of them comes with the expense of additional code to load, compile, execute, maintain, etc., and each one we add needs to have enough value to overcome that.  Can you help me to understand the value here?  The Cast operator is used with non-generic collections, which are few and far between these days, and which are typically implicitly less efficient than their generic counterparts.  What are the scenarios for optimizing Cast then that make this worthwhile?  I'm not asking for a microbenchmark; rather, I'd like to understand the macro scenarios where adding all of this complexity actually makes meaingful differences.

**Comment by jamesqo** [comment]
@stephentoub 

> The Cast operator is used with non-generic collections, which are few and far between these days, and which are typically implicitly less efficient than their generic counterparts.

I thought `Cast` was also frequently used when you have a generic IEnumerable in which you know all of the elements are of a certain type. For example consider you have an `IEnumerable<object>` in which you know all of the items are strings, or you have a method that returns a collection of either people or dogs, but the return type is `IEnumerable<IAnimal>` and its contents depends on some parameters passed to it at runtime.

[Here](https://gist.github.com/jamesqo/d0292d8deedbe6330b673cbc648bd1bc) are the results of grepping the Roslyn codebase for `Cast`. Most of the places it's used appear to be when the source is a generic enumerable.

**Comment by stephentoub** [comment]
> I thought Cast was also frequently used when you have a generic IEnumerable in which you know all of the elements are of a certain type. 

It can be used for that.  But if performance is an issue, it wouldn't typically be done, as the cast can be done as part of another operator.  For example, from your list of examples in Roslyn, there's an example like:
```
returnStatements.Cast<ReturnStatementSyntax>().Any(r => r.Expression != null)
```
If perf were an issue, the Cast operator wouldn't be used at all, e.g.
```
returnStatements.Any(r => ((ReturnStatementSyntax)r).Expression != null)
```
which eliminates all additional overhead from the Cast, rather than just trying to optimize it.

> Here are the results of grepping the Roslyn codebase for Cast. Most of the places it's used appear to be when the source is a generic enumerable.

Many of those results are false hits, including Roslyn's ```StaticCast```.  A bunch of others are in test code.    Can you highlight some cases where this change makes a measurable improvement to Roslyn?  If so, I'm much more inclined to be interested.

**Comment by stephentoub** [comment]
cc: @VSadov, do you have an opinion here?

**Comment by karelz** [comment]
@VSadov can you please comment?

Overall I would prefer to move justification & design discussions into issues and not have them in PRs.
If there is not agreement on what to do / take, I would suggest to close the PR, file a new issue and discuss the plan there. Then potentially reopen the PR based on the discussion result.

**Comment by VSadov** [comment]
In my experience "Cast" is actually a fairly common operator. It typically arises in scenarios that rely on covariant behavior of ```IEnumerable<T>```. Sometimes an API returns ```IEnumerable<Base>``` but we may know it actually contains ```Derived```.
So optimizing Cast may have some benefits.

@stephentoub @jamesqo - I agree with the point that, we need a sense of direction for fixes and for perf fixes in particular. It is not common for a perf fix to be just an unambiguous removal of inefficiency. More often the fix shifts complexity from one place to another and then there is always a question whether the trade of is profitable in scenarios that matter. 

It is easier to have this kind of discussion in a form of an issue, possibly with a linked prototype PR.

What are we trying to actually achieve here?

If we really want to optimize behavior of Cast iterator and the way it composes with other operators, perhaps we should consider implementing IPartition, not just IIListProvider?

Can we move the discussion into a corresponding issue?

**Comment by jamesqo** [comment]
@VSadov I have opened a new issue at #12629. Taking @karelz's suggestion to close this PR until we have a clear idea of what we want to do.

**Pull request closed without merging**
