### PR TITLE
Fix System.Text.Encodings.Web failure on Unix

### PR DESCRIPTION
**Pull request by stephentoub**
All of the tests in System.Text.Encodings.Web are passing on Unix.

However, during CI the test runner was failing with an error.  The problem turned out to be a confuence of the "-xml" flag being passed to the xunit runner, our temporary globalization implementation on Unix, and one of the System.Text.Encodings.Web tests using a [Theory] with [InlineData] containing an invalid surrogate pair.  With "-xml" specified, after all tests have been run xunit attempts to output information about each test to the XML log file, and for theories, it traces out parameter information as well.  In doing so it was encountering an exception when attempting to serialize out the surrogate pair.

I've temporarily rewritten that test to be a [Fact] with a loop instead of a [Theory] with [InlineData].  We can put it back to being a [Theory] once #846 is fixed.

### CODE REVIEW

**Comment by stephentoub** [comment]
cc: @ellismg, @KrzysztofCwalina, @mmitche

**Comment by ellismg** [comment]
Do you think the surrogate stuff is something to investigate adding to the dummy implementation if it is low cost?  Would it let us enable other stuff?

**Comment by stephentoub** [comment]
I'm not sure; this is the first I've hit it (or at least that I'm aware of hitting it). My guess is we'd be better off just investing in doing the real thing.

**Comment by ellismg** [comment]
Sounds good and looks good to me.

**Pull request merged**
