### PR TITLE
Add back missing System.Net.Security APIs

### PR DESCRIPTION
**Pull request by stephentoub**
Adds back the missing 30 methods on SslStream and NegotiateStream, all of which were the Begin/End and synchronous variants of the XxAsync methods.

Approach:
- Made the Begin/End methods public, and ensured they were doing the same validation as the XxAsync methods
- Added back synchronous methods with (minimal) implementation from desktop
- Extended a few of the existing test classes currently using XxAsync to run all of the tests with the Begin/End and synchronous variants as well

cc: @davidsh, @cipop, @ericeil, @danmosemsft, @joperezr

### CODE REVIEW

**Comment by stephentoub** [comment]
@dotnet-bot Test Outerloop Windows_NT Debug please
@dotnet-bot Test Outerloop Ubuntu14.04 Debug please
@dotnet-bot Test Outerloop OSX Debug please

**Comment by danmosemsft** [comment]
@karelz

**Comment by davidsh** [comment]
@stephentoub Thanks for helping out on these networking classes!

LGTM.

**Comment by stephentoub** [comment]
> Thanks for helping out on these networking classes!

:smile:

**Comment by stephentoub** [comment]
Test Innerloop Windows_NT Release Build and Test please ("Java / Jenkins hit a remoting error that caused the build to fail.")

**Comment by stephentoub** [comment]
@dotnet-bot Test Innerloop OSX Debug Build and Test please ("The plugin hasn't been performed correctly")

**Comment by CIPop** [comment]
LGTM 
Thanks @stephentoub for adding the APIs and also triggering the outerloop tests! :+1:

**Comment by stephentoub** [comment]
@dotnet-bot Test Innerloop Ubuntu14.04 Release Build and Test please (Jenkins aborted run)

**Pull request merged**
