### PR TITLE
Change SafeMemoryMappedFileHandle to use IntPtr.Zero instead of new IntPtr(0)

### PR DESCRIPTION
**Pull request by bbowyersmyth**
Avoid new pointer creation

### CODE REVIEW

**Comment by terrajobst** [comment]
@dotnet-bot okay to test

**Comment by svick** [comment]
Why do you think this is a change for the better? If you want to "avoid new pointer creation" for performance reasons, then I think that doesn't make sense, because `IntPtr` is a value type, so `new IntPtr(0)` should be virtually free.

Actually, the machine code generated for both variants is exactly the same for me. Which is especially weird considering the remark about efficiency in [the docs for `IntPtr.Zero`](http://msdn.microsoft.com/en-us/library/system.intptr.zero).

If it's about consistency, then I'm not sure whether it's better to be consistent with the other part of the same line (`new IntPtr(-1)`), or with the rest of the class (which uses `IntPtr.Zero`). But I don't think that's reason enough to make the change.

**Comment by mikedn** [comment]
It appears that `IntPtr.Zero` does generate better code, the code generated for `new IntPtr(0)` is different depending on what side of the bed the JIT wakes up :smile:. At least for x86, I haven't checked RyuJIT yet but I wouldn't be too surprised if it inherited the inconsistencies of the x86 JIT.

**Comment by mmitche** [comment]
test this please

**Comment by mmitche** [comment]
test this please

**Comment by bbowyersmyth** [comment]
IntPtr.Zero is only an advantage in comparison based operations where you can avoid a new copy being made.
This is also to make it consistent with the recent change from @stephentoub to SafePipeHandle. https://github.com/dotnet/corefx/commit/4d22f75d9b95c0e7cc18f54d94dacf463f8c682d

**Comment by stephentoub** [comment]
LGTM

**Pull request merged**
