### PR TITLE
Add System.Runtime.Numerics source and tests

### PR DESCRIPTION
**Pull request by mellinoe**
This change adds the source and test code for our System.Runtime.Numerics library. This library contains the BigInteger and Complex structures, as well as various number formatting helper classes (ToString() formatting) for the two types.

### CODE REVIEW

**Comment by mellinoe** [comment]
Thanks @Maxwe11, I fixed up the usage of $(CommonPath).

**Comment by krwq** [comment]
I only looked at the csproj files - looks good except that CommonPath..

**Comment by mellinoe** [comment]
CommonPath usage should be correct now, are you seeing something different?

**Comment by krwq** [comment]
Look at the tests .csproj, you got reference to:
..\..\Common\tests\XunitTraitsDiscoverers\XunitTraitsDiscoverers.csproj

I can't add comment as PR is too big

**Comment by mellinoe** [comment]
Okay, fixed the test project issue, will merge in assuming the CI build succeeds.

**Pull request merged**
