### PR TITLE
 Update brotli to v1.0.5 

### PR DESCRIPTION
**Pull request by kasper3**
Release notes: https://github.com/google/brotli/releases/tag/v1.0.5
Simply removed `src/Native/AnyOS/brotli` and extracted https://github.com/google/brotli/archive/v1.0.5.zip 's `brotli/c` directory there. Some new `.c` sources introduced in this release are added to `src/Native/Unix/System.IO.Compression.Native/CMakeLists.txt` and `src/Native/Windows/clrcompression/CMakeLists.txt`.

fixes https://github.com/dotnet/corefx/issues/30249

### CODE REVIEW

**Comment by kasper3** [comment]
test Packaging All Configurations x64 Debug Build

https://ci3.dot.net/job/dotnet_corefx/job/master/job/windows-TGroup_all+CGroup_Debug+AGroup_x64+TestOuter_false_prtest/13679/console failed:

```
Archiving logs in netci-archived-logs/**
[Pipeline] archiveArtifacts
Archiving artifacts
WARN: No artifacts found that match the file pattern "netci-archived-logs/**". Configuration error?
WARN: ‘netci-archived-logs/**’ doesn’t match anything, but ‘**’ does. Perhaps that’s what you mean?
[Pipeline] isUnix
[Pipeline] bat
[windows-TGrou---0d2c9ac4] Running batch script

D:\j\workspace\windows-TGrou---0d2c9ac4>taskkill /F /IM VBCSCompiler.exe 
ERROR: The process "VBCSCompiler.exe" not found.
[Pipeline] cleanWs
```

**Comment by stephentoub** [comment]
cc: @JeremyKuhne, @ianhays, @joshfree

**Comment by janvorli** [comment]
> should I create a subdirectory 1.0.5 under AnyOS/brotli and move the sources there

I think it would be enough to mention the version in the commit text. I did the same thing for libunwind in both coreclr and corert. You can always look at the git history to find that.

**Comment by kasper3** [comment]
Retrieving the version from commit history is bit indirect / complex as it is dependent on source control. If we download the source zip (e.g. https://github.com/dotnet/corefx/archive/release/2.1.zip), this is probably the only version we will not find out in sources. Extra nesting can be avoided by just renaming `brotli` to `brotli-1.0.5`, if that's a concern.
However, that's probably not a big deal, just a suggestion.

**Comment by janvorli** [comment]
More than the added indirection, the changing name is what I don't really like. It means that every time we update the library version, we would need to modify the build files to reflect that.
If the commit message doesn't sound like a usable solution, then I'd suggest adding a text file to the same folder as the brotli directory with info on where it came from. Say `brotli-version.txt` or something like that.

**Comment by kasper3** [comment]
@janvorli, I have added brotli-version.txt with additional release notes URL on second line. Let me know if that is not needed.

**Comment by janvorli** [comment]
@dotnet-bot test Windows x64 Debug Build please

**Pull request merged**
