### PR TITLE
Normalize separators with path root.

### PR DESCRIPTION
**Pull request by JeremyKuhne**
@nguerrera

### CODE REVIEW

**Comment by JeremyKuhne** [comment]
#4040

**Comment by nguerrera** [comment]
If this fixes #4040, can you also remove the [ActiveIssue] I added?

What was it about the coreclr upgrade that triggered this?

**Comment by JeremyKuhne** [comment]
I can't upgrade #4040 until we publish a new drop (there is a comment there). This broke because we don't test against what we build and we're missing an appropriate local test (to Runtime.Extensions).

**Comment by nguerrera** [comment]
OK. LGTM.

**Comment by stephentoub** [comment]
LGTM2

**Pull request merged**
