### PR TITLE
Bump file version of S.R.Metadata to match assembly version

### PR DESCRIPTION
**Pull request by nguerrera**

### CODE REVIEW

**Comment by nguerrera** [comment]
This is to unblock some issues involving taking the unofficial dev/metadata build and using it in msi that previously installed official 1.0.x.

cc @jhendrixMSFT @AlexGhiondea @jasonmalinowski

**Comment by jasonmalinowski** [comment]
:+1:

**Comment by AlexGhiondea** [comment]
LGTM

**Comment by stephentoub** [comment]
LGTM

**Pull request merged**
