### PR TITLE
Add System.Configuration shim

### PR DESCRIPTION
**Pull request by weshaggard**
@JeremyKuhne @danmosemsft @ericstj 

While helping a customer in consuming mysql desktop assembly I hit a missing dependency on System.Configuration which can be satisfied by our System.Configuration.ConfigurationManager OOB. This change adds that shim to the netcoreapp package which is a little odd because this shim only depends on S.C.ConfigurationManager which isn't part of the netcoreapp package, but we don't really have any other great way to ship that shim so I think it is still worth adding it here. 

Let me know what you guys think. Do you think it is worth having this shim?

### CODE REVIEW

**Comment by JeremyKuhne** [comment]
Seems ok to me.

**Comment by danmosemsft** [comment]
@weshaggard and I talked and it seems to me this gets us increased compat at little cost (slight disk size and oddness) so I think we should do this. he is also looking for others in this position.

**Comment by weshaggard** [comment]
I did a diff between net461 ref and our netcoreapp ref and found these are all the netfx refs that have at least some types supported in netcoreapp. So to maximize compat we should include shims for all of them.

**Comment by danmosemsft** [comment]
```
17:07:25 
17:07:25 D:\j\workspace\windows_nt_re---37265eab\Tools\Packaging.targets(1119,5): error : File System.Configuration, version 4.0.0.0 was included framework package Microsoft.Private.CoreFx.NETCoreApp/4.5.0-preview1-25319-0 but that version is not considered inbox in package index D:\j\workspace\windows_nt_re---37265eab\pkg\Microsoft.Private.PackageBaseline\packageIndex.json.  Please add it with approriate InboxOn entry for netcoreapp2.0 or suppress this message with PermitInbox suppression. [D:\j\workspace\windows_nt_re---37265eab\pkg\Microsoft.Private.CoreFx.NETCoreApp\Microsoft.Private.CoreFx.NETCoreApp.pkgproj]
17:07:25 D:\j\workspace\windows_nt_re---37265eab\Tools\Packaging.targets(1119,5): error : File 
```

**Comment by weshaggard** [comment]
>Is it feasible to have some kind of apicompat like diff that will flag any new ones ? As we will need more someday.

I don't know of any clever way to do that right now. I manually produced a diff and did some magic excel pivot tables to figure out this set.

**Pull request merged**
