### PR TITLE
Upgrade package versions to rc3-23722

### PR DESCRIPTION
**Pull request by stephentoub**
Trying to move to the latest.

### CODE REVIEW

**Comment by ellismg** [comment]
LGTM assuming a clean CI.  Thanks for doing this Steve.

**Comment by joshfree** [comment]
cc @Priya91

**Comment by Priya91** [comment]
LGTM!

**Comment by stephentoub** [comment]
> When I used this package version locally my tests hang for System.Net tests

@Priya91, which networking tests? I see hangs in the dynamic and vector tests (I've added a commit to revert the change that appears to be the cause), but not in the networking tests.  On which platform were you seeing them hang?

**Comment by stephentoub** [comment]
Test Innerloop Windows_NT Debug Build and Test please

**Comment by stephentoub** [comment]
Test Innerloop Ubuntu Debug Build and Test please
Test Innerloop Ubuntu Release Build and Test please
Test Innerloop OpenSUSE13.2 Debug Build and Test please
Test Innerloop OpenSUSE13.2 Release Build and Test please
Test Innerloop CentOS7.1 Debug Build and Test please
Test Innerloop CentOS7.1 Release Build and Test please

**Comment by stephentoub** [comment]
With the changes thus far, the Windows builds are now passing.  

The OpenSUSE and CentOS builds are hitting an unhandled exception in the System.Net.Security tests due to not being able to find System.Security.Principal.Windows.dll.  I'm assuming this is due to the issue fixed in https://github.com/dotnet/corefx/pull/5576 and that updating to today's packages will address this (hopefully).

The Ubuntu builds are hitting a failure not seen on the other Linux systems nor seen in current master builds.  43 of the System.Net.Http tests and 11 of the System.Net.Requests tests are failing with the error ```System.Net.Http.CurlException : Peer certificate cannot be authenticated with given CA certificates```.

**Comment by Priya91** [comment]
@stephentoub I was seeing it in net http functional tests, i was copying over bits to linux box and doing xunit.console.netcore.exe on the test dll. I am trying again now, with the fixed build scripts, i suspect that my local binary cache was corrupted, since I don't see those failures in the CI. 

Thanks for doing this :)

**Comment by stephentoub** [comment]
The cause of the networking failures:
https://github.com/dotnet/corefx/issues/5630

**Comment by ellismg** [comment]
@dotnet-bot test Innerloop Ubuntu Debug Build and Test please

**Comment by ellismg** [comment]
@dotnet-bot test Innerloop Ubuntu Release Build and Test please

**Comment by stephentoub** [comment]
Finally green :)

**Pull request merged**
