### PR TITLE
Remove RemoveEmptyFinalizers rule workaround

### PR DESCRIPTION
**Pull request by ViktorHofer**

### CODE REVIEW

**Comment by ViktorHofer** [comment]
Ok that requires also updating the [Microsoft.CodeAnalysis.FxCopAnalyzers](https://www.nuget.org/packages/Microsoft.CodeAnalysis.FxCopAnalyzers`) package. Currently we use a very old version 1.1.0 vs the available one 2.6.3.

**Comment by ViktorHofer** [comment]
Ok great 9430 errors 🐙

**Comment by ViktorHofer** [comment]
@safern do we have a tracking issue somewhere to update our analyzer packages?

**Comment by safern** [comment]
> @safern do we have a tracking issue somewhere to update our analyzer packages?

Nope. Most of them come from arcade as a transitive dependency for our custom analyzer package I believe.

**Comment by ViktorHofer** [comment]
I don't think so. We control the versions in Tools.props so I believe we should be able to use updated analyzers.

**Comment by ViktorHofer** [comment]
I will close this as I don't think we have resources to update the analyzers and fix/disable the errors anytime soon.

**Comment by stephentoub** [comment]
@viktorhofer, how do I do the update locally to see what the warnings are? Thanks.

**Comment by ViktorHofer** [comment]
See my branch: https://github.com/dotnet/corefx/commits/ViktorHofer-rules

**Pull request closed without merging**
