### PR TITLE
fix WebSocket socket descriptor leak in case of error on connection

### LINKED ISSUE #27765: WebSocket file descriptor leak when server returns error
**Description:**
WebSocket file descriptor leak when server returns error

**Environment:**
NETCore 2.0.5, 
Linux x64

**How to reproduce:**
Connect to a server which constantly returns errors with Websocket.
You will see that on Linux amount of file descriptors will drastically grow with each connection attempt.

The reason is that [here](https://github.com/dotnet/corefx/blob/release/2.0.0/src/System.Net.WebSockets.Client/src/System/Net/WebSockets/WebSocketHandle.Managed.cs) when `sslStream.AuthenticateAsClientAsync` or any other function throws error on connect `stream` will not be disposed.

### PR DESCRIPTION
**Pull request by sherlock1982**
Connect to a server which constantly returns errors with Websocket.
You will see that on Linux amount of file descriptors will drastically grow with each connection attempt.

The reason is that here when sslStream.AuthenticateAsClientAsync or any other function throws error on connect stream will not be disposed.

closes #27765

### CODE REVIEW

**Comment by stephentoub** [comment]
@sherlock1982, thank you for the fix!  This issue is already addressed in the 2.1 release (where this connection-related code is all replaced by usage of SocketsHttpHandler), and in general we're not taking a lot of changes into the 2.0 servicing branch, as 2.1 is already in preview and should be released in the near-ish future.  Is there a critical need for this to be serviced in 2.0?

**Comment by sherlock1982** [comment]
Well it depends on what a critical is. I have a service which accesses Microsoft speech recognition Websocket service. 
When my license or limit ends speech recognition no longer works. But I don't know when it's gonna be available again. So I send this requests periodically and I end up at file descriptor limit.

I made a custom build of this library with this fix only and I will need to do it again for next release. Which is a bit painful.
Maybe I can get a code from this library and compile it inside of my project which I haven't tried yet.
But my project is Windows/Linux so it will be more difficult to do.

**Comment by stephentoub** [comment]
@karelz, what is the plan here?

**Comment by karelz** [comment]
Sorry, the response dropped off my radar (we discussed it 3 weeks ago and I forgot to reply here - very sorry for that).

@sherlock1982 we're trying to keep 2.0.x fixes to minimum to reduce the chance of introducing new regressions and side-effects (servicing is in-place update). As such, we port only "impactful" low-risk bug fixes, using following criteria for "impactful":
1. The issue impacts smaller number of customers, but the impact is significant (e.g. no workaround at all, applications don't work at all, very difficult/expensive diagnostics/detection of the problem), or
2. The issue impacts larger set of customers without a good workaround.

These are the "servicing bar" criteria we have been using since .NET Core 1.0 (and very similar bar/logic is used also for .NET Framework servicing).
We realize that we do not have these criteria published anywhere publicly (probably something we should fix) - although you could find sprinkled hints and similar replies in a few issues on GitHub, when we got questions about back porting various fixes. I think this is the first time we see a PR from community submitting back port of a bug fixes without previous discussion on an issue.

This particular issue had so far 1 report. There is a workaround - custom library / copy code from CoreFX (although I admit quite far away from ideal workaround). And the bug is fixed in next 2.1 release (incl. upcoming Preview2).
Therefore we don't think the fix meets the bar above.

I will close the PR. If you think we misjudged the impact, or if you have further questions, please let us know. Thank you for understanding!

**Pull request closed without merging**
