### PR TITLE
Disable test System.Runtime.Tests.ProfileOptimizationTest/ProfileOptimization_CheckFileExists

### PR DESCRIPTION
**Pull request by MarcoRossignoli**
We temporarily disable test due to persistent failure on some legs.
Issue https://github.com/dotnet/corefx/issues/31792#issuecomment-428524788

/cc @danmosemsft @brianrob @rmkerr

### CODE REVIEW

**Comment by ViktorHofer** [comment]
Right, I mean adding that as a condition to PlatformDetection.cs and using it as a ConditionalFact in your test code.

**Comment by danmosemsft** [comment]
Or just for redhat69

**Comment by MarcoRossignoli** [comment]
> Or just for redhat69

@danmosemsft you mean https://github.com/dotnet/corefx/blob/master/src/CoreFx.Private.TestUtilities/src/System/PlatformDetection.Windows.cs#L42
I read now your comment, i've pushed amend...do i revert?

**Comment by MarcoRossignoli** [comment]
@ViktorHofer @rmkerr @danmosemsft amended!

**Pull request merged**
