### PR TITLE
adding packaging for sqlClient

### PR DESCRIPTION
**Pull request by Anipik**
change similar to https://github.com/dotnet/corefx/pull/42952

We updated the policy of always updating the baseline version.  AssemblyVersionInPackageVersion change is not therefore required but keeping it for consistency purposes

Associated code change https://github.com/dotnet/corefx/pull/43070

### CODE REVIEW

**Review by aik-jahoda — APPROVED** [review]
LGTM

**Comment by Anipik** [comment]
>   Restore completed in 34.71 sec for C:\h\w\A2B908CF\w\AE8B097D\u\netcoreapp3.0\project.csproj.
C:\h\w\A2B908CF\w\AE8B097D\u\netcoreapp3.1\project.csproj : error NU1102: Unable to find package Microsoft.NETCore.App.Runtime.win-x86 with version (= 3.1.17-servicing.21309.1)
C:\h\w\A2B908CF\w\AE8B097D\u\netcoreapp3.1\project.csproj : error NU1102:   - Found 1639 version(s) in https://dotnetfeed.blob.core.windows.net/dotnet-core/index.json [ Nearest version: 5.0.0-alpha.1.19528.5 ]
C:\h\w\A2B908CF\w\AE8B097D\u\netcoreapp3.1\project.csproj : error NU1102:   - Found 57 version(s) in https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet-public/nuget/v3/index.json [ Nearest version: 3.1.17 ]
C:\h\w\A2B908CF\w\AE8B097D\u\netcoreapp3.1\project.csproj : error NU1102:   - Found 0 version(s) in C:\h\w\A2B908CF\p\packages
C:\h\w\A2B908CF\w\AE8B097D\u\netcoreapp3.1\project.csproj : error NU1102: Unable to find package Microsoft.NETCore.App.Runtime.win-x64 with version (= 3.1.17-servicing.21309.1)
C:\h\w\A2B908CF\w\AE8B097D\u\netcoreapp3.1\project.csproj : error NU1102:   - Found 1639 version(s) in https://dotnetfeed.blob.core.windows.net/dotnet-core/index.json [ Nearest version: 5.0.0-alpha.1.19528.5 ]

@mmitche @wtgodbe do we need to push these runtime packs to these feeds ?

**Comment by mmitche** [comment]
> 3.1.17-servicing.21309.1

They should have been. let me check.

**Review by safern — APPROVED** [review]

**Review by safern — APPROVED** [review]

**Comment by wtgodbe** [comment]
@Anipik is this for this month's servicing train? CC @vseanreesermsft

**Comment by Anipik** [comment]
yes

**Pull request merged**
