### PR TITLE
Allow C# 6 to be used in corefx

### PR DESCRIPTION
**Pull request by stephentoub**
- Remove constraint from dir.props
- Augment coding guidelines

cc: @weshaggard

### CODE REVIEW

**Comment by justinvp** [comment]
:+1: :tada: :fireworks:

**Comment by JonHanna** [comment]
Shiny. :+1:

**Comment by stephentoub** [comment]
Test Innerloop OSX Debug Build and Test please
Test Innerloop Ubuntu Debug Build and Test please

**Comment by weshaggard** [comment]
@stephentoub did you want to add some more guidelines around specific C# 6.0 features? In particular something like "Do use nameof instead of constant string names when needing to pass the name of an identifier". I've not looked at the C# 6.0 feature list recently but it might be good to enumerate them and see if any explicit do's or don't's need to be called about about them.

**Comment by stephentoub** [comment]
> did you want to add some more guidelines around specific C# 6.0 features?

I think we can evolve the guidelines as cases arise.  There's not too much to be prescriptive about.  I can add your nameof one.

**Comment by weshaggard** [comment]
@stephentoub sounds good to me. Thanks for writing this up and thanks for everyone's patience before moving to C# 6.0.

**Comment by stephentoub** [comment]
Thanks, Wes.  When can this be merged, as soon as #6181 goes in (and the CI is green)?

**Comment by weshaggard** [comment]
Yes when #6181 is merged and CI is green. I think @joperezr actually already added part of your PR.

**Comment by stephentoub** [comment]
Oh, well if the LangVer part of the change is going in as part of #6181, then the only thing left here is doc changes that aren't technically gated on anything (nor does CI impact it) :smile:

**Comment by stephentoub** [comment]
Closing to let #6181 handle the LangVer change.

**Comment by joperezr** [comment]
@stephentoub I have includded the LanVer changes in my PR, but I didn't include the doc per your comment above. If you want me to do so, let me know.

**Comment by stephentoub** [comment]
> If you want me to do so, let me know.

Thanks, but I took care of the doc changes.

**Pull request closed without merging**
