### PR TITLE
Don't capture AsyncLocals into ODBC ConnPool

### PR DESCRIPTION
**Pull request by benaadams**
Contributes to #26064

### CODE REVIEW

**Comment by karelz** [comment]
@saurabh500 @corivera can you please take a look?

**Comment by karelz** [comment]
@saurabh500 @corivera ping?

**Comment by saurabh500** [comment]
@karelz there is a side discussion about this PR on https://github.com/dotnet/corefx/pull/26065 . Once that concludes this will be simple

**Comment by stephentoub** [comment]
Blocked on https://github.com/dotnet/corefx/pull/26065

**Comment by benaadams** [comment]
Rebased and used changes from #26065

**Pull request merged**
