### PR TITLE
Fix dotnet cli version number to a specific version

### PR DESCRIPTION
**Pull request by weshaggard**
While we would like to use 'Latest' as the version for dogfooding
purposes, we have to keep our builds unblocked and there is currently
a breaking change we have to react to. So to unblock we are fixing
to a particular version we know works.

FYI @ericstj @joperezr @stephentoub

### CODE REVIEW

**Comment by mellinoe** [comment]
LGTM

**Comment by stephentoub** [comment]
LGTM if fixes problem.

**Comment by Priya91** [comment]
LGTM!

**Comment by weshaggard** [comment]
CI is green so merging.

**Pull request merged**
