### PR TITLE
Removed obsolete System.Net.Http NETFX related files

### PR DESCRIPTION
**Pull request by davidsh**
Due to PR #23611, the master branch no longer builds a NETFX binary for
System.Net.Http. Instead this is now handled only in the release/2.0.0
branch as part of the "NETStandard support package".

This effectively means that we have already stopped OOB'ing
System.Net.Http on .NET Framework platforms as of .NET 4.7.1 since that
version of .NET Framework supports all NETStandard2.0 APIs.  And .NET
Framework versions prior to that (4.6.x, etc.) are handled with the OOB
System.Net.Http.dll that is part of the NETStandard support package.

### CODE REVIEW

**Comment by davidsh** [comment]
@ericstj @weshaggard @safern PTAL
cc: @karelz

**Comment by davidsh** [comment]
NETFX failure:
https://ci3.dot.net/job/dotnet_corefx/job/master/job/windows-TGroup_netfx+CGroup_Release+AGroup_x86+TestOuter_false_prtest/3946/console

From the Console output:

>13:17:25 Build FAILED.
13:17:25 
13:17:25 D:\j\workspace\windows-TGrou---2a8f9c29\Tools\tests.targets(473,5): warning :    System.Diagnostics.DiagnosticSource.Tests  Total: 47, Errors: 0, Failed: 3, Skipped: 0, Time: 98.077s [D:\j\workspace\windows-TGrou---2a8f9c29\src\System.Diagnostics.DiagnosticSource\tests\System.Diagnostics.DiagnosticSource.Tests.csproj]
13:17:25 D:\j\workspace\windows-TGrou---2a8f9c29\Tools\tests.targets(473,5): warning MSB3073: The command "D:\j\workspace\windows-TGrou---2a8f9c29\bin/tests/System.Diagnostics.DiagnosticSource.Tests/netfx-Windows_NT-Release-x86//RunTests.cmd D:\j\workspace\windows-TGrou---2a8f9c29\bin/testhost/netfx-Windows_NT-Release-x86/" exited with code 1. [D:\j\workspace\windows-TGrou---2a8f9c29\src\System.Diagnostics.DiagnosticSource\tests\System.Diagnostics.DiagnosticSource.Tests.csproj]
13:17:25 D:\j\workspace\windows-TGrou---2a8f9c29\Tools\tests.targets(473,5): warning :    System.Net.Http.Functional.Tests  Total: 310, Errors: 0, Failed: 3, Skipped: 12, Time: 65.019s [D:\j\workspace\windows-TGrou---2a8f9c29\src\System.Net.Http\tests\FunctionalTests\System.Net.Http.Functional.Tests.csproj]
13:17:25 D:\j\workspace\windows-TGrou---2a8f9c29\Tools\tests.targets(473,5): warning MSB3073: The command "D:\j\workspace\windows-TGrou---2a8f9c29\bin/tests/System.Net.Http.Functional.Tests/netfx-Windows_NT-Release-x86//RunTests.cmd D:\j\workspace\windows-TGrou---2a8f9c29\bin/testhost/netfx-Windows_NT-Release-x86/" exited with code 1. [D:\j\workspace\windows-TGrou---2a8f9c29\src\System.Net.Http\tests\FunctionalTests\System.Net.Http.Functional.Tests.csproj]
13:17:25 D:\j\workspace\windows-TGrou---2a8f9c29\Tools\tests.targets(481,5): error : One or more tests failed while running tests from 'System.Diagnostics.DiagnosticSource.Tests' please check D:\j\workspace\windows-TGrou---2a8f9c29\bin/tests/System.Diagnostics.DiagnosticSource.Tests/netfx-Windows_NT-Release-x86/testResults.xml for details! [D:\j\workspace\windows-TGrou---2a8f9c29\src\System.Diagnostics.DiagnosticSource\tests\System.Diagnostics.DiagnosticSource.Tests.csproj]
13:17:25 D:\j\workspace\windows-TGrou---2a8f9c29\Tools\tests.targets(481,5): error : One or more tests failed while running tests from 'System.Net.Http.Functional.Tests' please check D:\j\workspace\windows-TGrou---2a8f9c29\bin/tests/System.Net.Http.Functional.Tests/netfx-Windows_NT-Release-x86/testResults.xml for details! [D:\j\workspace\windows-TGrou---2a8f9c29\src\System.Net.Http\tests\FunctionalTests\System.Net.Http.Functional.Tests.csproj]
13:17:25 D:\j\workspace\windows-TGrou---2a8f9c29\dir.traversal.targets(77,5): error : (No message specified) [D:\j\workspace\windows-TGrou---2a8f9c29\src\tests.builds]
13:17:25     4 Warning(s)
13:17:25     3 Error(s)
13:17:25

**Comment by davidsh** [comment]
I don't understand these results.  It doesn't show what the failures are even though it says something failed:

>System.Net.Http.Functional.Tests Total: 310, Errors: 0, Failed: 3, Skipped: 12, Time: 65.019s 

@safern Can you help decode this?

There are also System.Diagnostics failures in htere unrelated to my change on both Linux and NETFX.

**Comment by davidsh** [comment]
Looks like the failures in System.Net.Http tests are not related to my change.  They are failing with errors connecting to the remote server:

```
      System.Net.Http.Functional.Tests.HttpClientHandlerTest.UseDefaultCredentials_SetToFalseAndServerNeedsAuth_StatusCodeUnauthorized(useProxy: True) [FAIL]
        System.Net.Http.HttpRequestException : An error occurred while sending the request.
        ---- System.Net.WebException : Unable to connect to the remote server
        -------- System.Net.Sockets.SocketException : A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond 40.118.166.132:80
        Stack Trace:
             at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
             at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
             at System.Net.Http.HttpClient.<FinishSendAsyncBuffered>d__58.MoveNext()
          --- End of stack trace from previous location where exception was thrown ---
             at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
             at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
          D:\j\workspace\windows-TGrou---2a8f9c29\src\System.Net.Http\tests\FunctionalTests\HttpClientHandlerTest.cs(237,0): at System.Net.Http.Functional.Tests.HttpClientHandlerTest.<UseDefaultCredentials_SetToFalseAndServerNeedsAuth_StatusCodeUnauthorized>d__29.MoveNext()
          --- End of stack trace from previous location where exception was thrown ---
             at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
             at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
          --- End of stack trace from previous location where exception was thrown ---
             at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
             at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
          --- End of stack trace from previous location where exception was thrown ---
             at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
             at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
          ----- Inner Stack Trace -----
             at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
             at System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)
          ----- Inner Stack Trace -----
             at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
             at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)
        Output:
          Uri: http://corefx-net.cloudapp.net/Echo.ashx?auth=negotiate
      System.Net.Http.Functional.Tests.HttpClientHandler_MaxConnectionsPerServer_Test.GetAsync_MaxLimited_ConcurrentCallsStillSucceed(maxConnections: 2, numRequests: 2, secure: True) [FAIL]
        System.Net.Http.HttpRequestException : An error occurred while sending the request.
        ---- System.Net.WebException : Unable to connect to the remote server
        -------- System.Net.Sockets.SocketException : A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond 40.118.166.132:80
        Stack Trace:
             at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
             at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
             at System.Net.Http.HttpClient.<FinishSendAsyncBuffered>d__58.MoveNext()
          --- End of stack trace from previous location where exception was thrown ---
             at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
             at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
          D:\j\workspace\windows-TGrou---2a8f9c29\src\System.Net.Http\tests\FunctionalTests\HttpClientHandlerTest.MaxConnectionsPerServer.cs(74,0): at System.Net.Http.Functional.Tests.HttpClientHandler_MaxConnectionsPerServer_Test.<GetAsync_MaxLimited_ConcurrentCallsStillSucceed>d__3.MoveNext()
          --- End of stack trace from previous location where exception was thrown ---
             at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
             at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
          --- End of stack trace from previous location where exception was thrown ---
             at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
             at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
          --- End of stack trace from previous location where exception was thrown ---
             at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
             at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
          ----- Inner Stack Trace -----
             at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
             at System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)
          ----- Inner Stack Trace -----
             at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
             at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)
      System.Net.Http.Functional.Tests.HttpClientHandler_MaxConnectionsPerServer_Test.GetAsync_MaxLimited_ConcurrentCallsStillSucceed(maxConnections: 3, numRequests: 2, secure: True) [FAIL]
        System.Net.Http.HttpRequestException : An error occurred while sending the request.
        ---- System.Net.WebException : Unable to connect to the remote server
        -------- System.Net.Sockets.SocketException : A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond 40.118.166.132:80
        Stack Trace:
             at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
             at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
             at System.Net.Http.HttpClient.<FinishSendAsyncBuffered>d__58.MoveNext()
          --- End of stack trace from previous location where exception was thrown ---
             at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
             at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
          D:\j\workspace\windows-TGrou---2a8f9c29\src\System.Net.Http\tests\FunctionalTests\HttpClientHandlerTest.MaxConnectionsPerServer.cs(74,0): at System.Net.Http.Functional.Tests.HttpClientHandler_MaxConnectionsPerServer_Test.<GetAsync_MaxLimited_ConcurrentCallsStillSucceed>d__3.MoveNext()
          --- End of stack trace from previous location where exception was thrown ---
             at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
             at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
          --- End of stack trace from previous location where exception was thrown ---
             at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
             at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
          --- End of stack trace from previous location where exception was thrown ---
             at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
             at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
          ----- Inner Stack Trace -----
             at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
             at System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)
          ----- Inner Stack Trace -----
             at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
             at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)
    Finished:    System.Net.Http.Functional.Tests
```

**Comment by davidsh** [comment]
@dotnet-bot Test Linux x64 Release Build
@dotnet-bot Test NETFX x86 Release Build

**Comment by safern** [comment]
Linux has System.Net.Requests and System.Net.Http.FunctionalTests failures 

https://mc.dot.net/#/user/davidsh/pr~2Fjenkins~2Fdotnet~2Fcorefx~2Fmaster~2F/test~2Ffunctional~2Fcli~2F/5f42888f2cc3e9388e55f8aa6cebd193c4a0afe0/workItem/System.Net.Http.Functional.Tests

https://mc.dot.net/#/user/davidsh/pr~2Fjenkins~2Fdotnet~2Fcorefx~2Fmaster~2F/test~2Ffunctional~2Fcli~2F/5f42888f2cc3e9388e55f8aa6cebd193c4a0afe0/workItem/System.Net.Requests.Tests

**Comment by davidsh** [comment]
All the linux CI failures are on SUSE.  And they are all of the "timeout" variety:

"System.Net.WebException : The operation has timed out."
or
"System.Threading.Tasks.TaskCanceledException : A task was canceled."

**Comment by davidsh** [comment]
Since the failures are unrelated to the PR, I will merge.

**Comment by stephentoub** [comment]
@davidsh, I see some ifdefs for NET46 in code in System.Net.Http.  Can those be cleaned up, too?

**Comment by davidsh** [comment]
>@davidsh, I see some ifdefs for NET46 in code in System.Net.Http. Can those be cleaned up, too?

Yes, those could be cleaned up.  They will always be false in the master branch since there is no longer a NETFX build config for this library.

**Pull request merged**
