### PR TITLE
System.Security.Cryptography.X509Certificates: Fix file casing in csproj

### PR DESCRIPTION
**Pull request by akoeplinger**
The file on disk has a different casing, fix the csproj to match so it works on case sensitive file systems.

### CODE REVIEW

**Comment by stephentoub** [comment]
LGTM

**Comment by jasonwilliams200OK** [comment]
Out of curiosity, why wasn't the CI build failing for Linux/OSX when the original PR was tested?

**Comment by akoeplinger** [comment]
@jasonwilliams200OK because the CI builds on Windows which has a case-insensitive file system.

**Comment by stephentoub** [comment]
It currently builds the managed Linux assemblies on Windows.

**Comment by stephentoub** [comment]
@dotnet-bot test this please

**Comment by jasonwilliams200OK** [comment]
Meaning no tests are actually run for Linux builds *on* Linux on CI; and 'passed Linux build' mean Linux binaries were only successfully built on Windows?
https://github.com/dotnet/corefx#net-core-libraries-corefx

**Comment by stephentoub** [comment]
No, tests are run; the binaries are built on Windows and then accessed from a Linux machine to execute the tests.

**Comment by jasonwilliams200OK** [comment]
:+1: Thank you @stephentoub.
I think until https://github.com/dotnet/coreclr/issues/170 is sorted out this is the lifestyle.. Are there blockers other than "`BclRewriter` not being xplat yet" to break the Windows dependency for \*nix/*bsd?

**Comment by stephentoub** [comment]
This is separate from that issue; the BclRewriter is not used for assemblies other than mscorlib.  The issue until very recently has been that we haven't had build system support for compiling managed code on Unix.  That's recently changed, though it's still nascent and not all of the corefx projects currently build with it correctly, so the CI system hasn't been updated to use it.  See the list of known issues at https://github.com/dotnet/corefx/blob/master/Documentation/linux-instructions.md.

**Pull request merged**
