### PR TITLE
Darc update from build '20190328.12'

### PR DESCRIPTION
**Pull request by ViktorHofer**
Ingesting updates in CoreFxTesting that help Mono to onboard.

### CODE REVIEW

**Comment by ViktorHofer** [comment]
cc @Anipik @ericstj @safern GenFacades error

**Comment by safern** [comment]
Seems like we need to do this update in @Anipik's PR branch to react to the GenFacades changes:

https://github.com/dotnet/corefx/pull/36126

**Comment by ViktorHofer** [comment]
I will reset the version of GenFacades meanwhile to unblock this PR.

**Comment by ericstj** [comment]
Looks like the usingtask statements got lost in the targets file refactor as well.

**Comment by ViktorHofer** [comment]
Closing in favor of https://github.com/dotnet/corefx/pull/36487

**Pull request closed without merging**
