### PR TITLE
Fixing NullReferenceException in MemberInitExpression interpretation

### PR DESCRIPTION
**Pull request by bartdesmet**
This fixes issue #4018.

### CODE REVIEW

**Comment by stephentoub** [comment]
@dotnet-bot test this please

**Comment by stephentoub** [comment]
@dotnet-bot test this please (#4037)

**Comment by stephentoub** [comment]
@dotnet-bot test this please (#4037)

**Comment by stephentoub** [comment]
@dotnet-bot test this please (#4037)

**Comment by stephentoub** [comment]
@dotnet-bot test this please (#4037)

**Comment by VSadov** [comment]
System.Runtime.Loader.Tests.AssemblyLoadContextTest.LoadAssemblyByPath_ValidUserAssembly [FAIL]
14:32:55       System.IO.IOException : The process cannot access the file '/tmp/System.Runtime.Loader.Test.Assembly.dll' because it is being used by another process.

**Comment by VSadov** [comment]
The failure is unlikely to be related to the change

**Comment by VSadov** [comment]
@dotnet-bot test this please

**Pull request merged**
