### PR TITLE
Changing the Min target group of System.Data Packages to 4.5.1

### LINKED ISSUE #6937: Fix ApiCompat issues for System.Data.Common
Remove ApiCompatBaseline.net45.txt once errors mentioned in it are resolved.

### PR DESCRIPTION
**Pull request by saurabh500**
The changes make the System.Data assemblies dependent on .Net framework 4.5.1 

The work done on System.Data was intended to target compatibility with .Net 4.5.1. As a result when built against .Net 4.5 there are ApiCompat issue.

The change changes the minimum target framework for System.Data.* to 451

Fixes #6937 and #6938 

cc @ericstj @venkat-raman251 @corivera

### CODE REVIEW

**Comment by saurabh500** [comment]
cc @justinvp

**Comment by saurabh500** [comment]
@dotnet-bot Test Innerloop Windows_NT Release Build and Test please

**Comment by saurabh500** [comment]
Build failing while building the pkg folder of System.Data.Common and SqlClient.
Looks like some additional changes are needed.

**Comment by ericstj** [comment]
You can build that locally you know...  Nothing special about the CI.

**Comment by saurabh500** [comment]
@ericstj Yes. I can repro this on the local machine. I sent the PR after building the Common and SqlClient src which built fine.
Pkg folder builds are failing for me currently.

**Pull request closed without merging**
