### PR TITLE
Implementing NegoState.Unix.cs 

### PR DESCRIPTION
**Pull request by shrutigarg**
It includes the implementation on NegoState.Unix pal on top of the common refactoring changes( https://github.com/dotnet/corefx/pull/5581) 
Please refer to the Commit 4 of this PR for reviewing.

Includes:
Implementation of NegoState.Unix.cs Methods.
Implementaion of SafeHandles to be used.

Tested locally as Linux client with windows server.

cc: @stephentoub , @bartonjs @vijaykota

### CODE REVIEW

**Comment by vijaykota** [comment]
cc: @joshfree for tracking #2483 

Pre-requisite for merging this PR is #5500 and #5581. Please ignore the 1st 3 commits which are from #5581. We are trying to get early feedback on the xplat implementation without gating on merge of the those PRs.

Note that Unix build is expected to fail since the .csproj includes files that are a part of #5500.

**Comment by davidsh** [comment]
cc: @CIPop

**Comment by bartonjs** [comment]
There really need to be automated tests for this.  At minimum for the golden path.  And they need to be enabled before the code gets merged.  PlatformNotSupportedException is (to me) better than it being horribly broken... and even if it works in this set of commits there's nothing to say that the next one won't break it, unless there's a test.

**Comment by vijaykota** [comment]
> cc: @CIPop 

Just to be clear, please review only the Unix portions of the code ie. 4th commit onwards. Anything impacting Windows will be part of #5581

**Comment by vijaykota** [comment]
> and is just a container-wrapper for a SafeGssCredHandle

2 reasons for this:
1. Both SecureChannel.cs and NTAuthentication.cs need the common classes SafeFreeCredential and SafeDeleteContext but have different functionality. So we need this base class definition and it doesn't make sense to make SafeGssCredHandle derive from it
2. When the NTLM changes are put in, SafeGssCredHandle will hold other info like username, domain etc.

**Comment by vijaykota** [comment]
> There really need to be automated tests for this

Agreed. Had a few offline discussions regarding this. We are going to move the development to a private branch. We expect to merge test code there once we finalize the test strategy.

And to ensure master is never broken, the contract is that we can merge from the private branch only after sufficient automated test coverage is there.

**Comment by vijaykota** [comment]
> When the NTLM changes are put in, SafeGssCredHandle will hold other info 

Sorry.. that should read "SafeFreeNegoCredentials"

**Comment by shrutigarg** [comment]
moved this to #5773 in dev/NegotiateStream branch .

**Comment by shrutigarg** [comment]
- [ ] fdg

**Pull request closed without merging**
