### PR TITLE
Make sure TcpClient properties do not throw when the underlying Socket is null

### LINKED ISSUE #9762: TcpClient.Connected throws NullReferenceException on Windows when there is no Socket
The following code throws `NullReferenceException` on .Net Core on Windows and on .Net Framework:

```c#
var client = new TcpClient();
client.Dispose();
Console.WriteLine(client.Connected);
```

On Unix, it writes `False`, as expected.

This is because `Connected` on Windows [just returns `Connected` of the underlying socket](https://github.com/dotnet/corefx/blob/v1.0.0/src/System.Net.Sockets/src/System/Net/Sockets/TCPClient.Windows.cs#L25), while [on Unix it checks for `null`](https://github.com/dotnet/corefx/blob/v1.0.0/src/System.Net.Sockets/src/System/Net/Sockets/TCPClient.Unix.cs#L164-L172).

This happens when accessing `Connected` while the underlying socket is `null`. That can happen after calling `Dispose()` and also after explicitly assigning `null` to `Client` (the underlying socket).

This also affects `Available` and `ExclusiveAddressUse`.

### PR DESCRIPTION
**Pull request by svick**
Fixes #9762

### CODE REVIEW

**Comment by svick** [comment]
cc: @CIPop

**Comment by stephentoub** [comment]
LGTM

**Comment by stephentoub** [comment]
cc: @ericeil for the Unix failure:
```
System.Net.Sockets.SocketException : Operation not supported
        Stack Trace:
              at System.Net.Sockets.Socket.GetSocketOption(SocketOptionLevel optionLevel, SocketOptionName optionName)
              at System.Net.Sockets.TcpClient.GetOption[T](T& location, Boolean& initialized, SocketOptionLevel level, SocketOptionName name)
              at System.Net.Sockets.TcpClient.get_ExclusiveAddressUseCore()
              at System.Net.Sockets.TcpClient.get_ExclusiveAddressUse()
              at System.Net.Sockets.Tests.TcpClientTest.ConnectedAvailableExclusiveAddressUse_NullClient()
```

**Comment by CIPop** [comment]
Test Innerloop Windows_NT Release Build and Test

**Comment by svick** [comment]
I believe the failure on Unix was correct, so I changed the test to get `ExclusiveAddressUse` only on Windows.

On the other hand, `Roundtrip_ExclusiveAddressUse_GetEqualsSet` should not have succeeded on Unix. For that, I have submitted a separate PR: #9895.

**Comment by stephentoub** [comment]
@svick, thanks for the fix.  Now that your other PR is merged, can you rebase this?

**Comment by svick** [comment]
@stephentoub Done.

**Comment by CIPop** [comment]
LGTM

**Comment by CIPop** [comment]
Thanks @svick!

**Pull request merged**
