### PR TITLE
Reduce test run time to help avoid timeouts in CI for outerloop tests

### PR DESCRIPTION
**Pull request by ahsonkhan**
Cannot reproduce the test failures locally, and hence trying to run in CI with XunitShowProgress enabled to see where the hang is happening.

From https://github.com/dotnet/corefx/issues/26748

cc @stephentoub, @AtsushiKan, cc @KrzysztofCwalina

### CODE REVIEW

**Comment by ahsonkhan** [comment]
@dotnet-bot help

**Comment by ahsonkhan** [comment]
@dotnet-bot test outerloop netcoreapp Windows_NT Release
@dotnet-bot test outerloop netcoreapp Windows_NT Debug
@dotnet-bot test outerloop netcoreapp Windows 7 Release
@dotnet-bot test outerloop netcoreapp Windows 7 Debug
@dotnet-bot test outerloop netcoreapp Ubuntu16.10 Release
@dotnet-bot test outerloop netcoreapp OSX10.12 Release

**Comment by ahsonkhan** [comment]
From https://ci.dot.net/job/dotnet_corefx/job/master/job/outerloop_netcoreapp_win7_release_prtest/27/

> 12:02:25   Executing in D:\j\workspace\outerloop_net---853d91cd\bin\tests\System.Memory.Tests\netcoreapp-Windows_NT-Release-x64\ 
12:02:25   Running tests... Start time: 12:02:25.84
...
12:03:26   === TEST EXECUTION SUMMARY ===
12:03:26      System.Memory.Tests  Total: 40996, Errors: 0, Failed: 0, Skipped: 0, Time: 51.116s
12:03:26   Finished running tests.  End time=12:03:18.12, Exit code = 0

> 12:08:53   Executing in D:\j\workspace\outerloop_net---853d91cd\bin\tests\System.Memory.Performance.Tests\netcoreapp-Windows_NT-Release-x64\ 
12:08:53   Running tests... Start time: 12:08:53.16
...
12:10:22   === TEST EXECUTION SUMMARY ===
12:10:23      System.Memory.Performance.Tests  Total: 425, Errors: 0, Failed: 0, Skipped: 0, Time: 89.173s
12:10:23   Finished running tests.  End time=12:10:23.13, Exit code = 0

I don't see any test hangs. The test just times out after 2 hours.

System.Linq.Parallel tests take around that long too. I think System.Collections.Performance.Tests is the biggest culprit, at around 400 seconds (also System.Net.Security).

**Comment by stephentoub** [comment]
> I don't see any test hangs. The test just times out after 2 hours.

Trying to parse this... you mean you see the tests fail and don't know which suit is causing it to do so?

**Comment by ahsonkhan** [comment]
> Trying to parse this... you mean you see the tests fail and don't know which suit is causing it to do so?

No, looking through the logs, I don't see any test failures. The entire build & test run just ends up taking longer than 2 hours in total.

> 13:31:58 
Build timed out (after 120 minutes). Marking the build as aborted.
13:31:58 
Build was aborted

**Comment by ahsonkhan** [comment]
On debug mode:
> System.Memory.Tests  Total: 40996, Errors: 0, Failed: 0, Skipped: 0, Time: 254.005s
> System.Memory.Performance.Tests  Total: 425, Errors: 0, Failed: 0, Skipped: 0, Time: 384.242s

I think we should exclude perf tests from running in debug mode. I am not sure how useful that data is.

**Comment by stephentoub** [comment]
@dotnet-bot test OuterLoop netcoreapp Windows 7 Debug x64 please

**Comment by ahsonkhan** [comment]
I have reduced the S.M outerloop test time by more than 50% by reducing the large allocation test cases:
Before - Time: 209.194s
After - Time: 91.848s

I am not sure what else I can do to resolve the issue. I can look further if we hit this issue again.

**Comment by ahsonkhan** [comment]
@dotnet-bot test outerloop netcoreapp Windows_NT Release
@dotnet-bot test outerloop netcoreapp Windows_NT Debug
@dotnet-bot test outerloop netcoreapp Windows 7 Release
@dotnet-bot test outerloop netcoreapp Windows 7 Debug
@dotnet-bot test outerloop netcoreapp Ubuntu16.10 Release
@dotnet-bot test outerloop netcoreapp OSX10.12 Release

**Comment by stephentoub** [comment]
@dotnet-bot test Outerloop Windows x64 Debug Build please

**Comment by ahsonkhan** [comment]
@dotnet-bot test outerloop netcoreapp Windows_NT Release
@dotnet-bot test outerloop netcoreapp Windows 7 Release
@dotnet-bot test outerloop netcoreapp Windows 7 Debug
@dotnet-bot test outerloop netcoreapp Ubuntu16.10 Release
@dotnet-bot test outerloop netcoreapp OSX10.12 Release

**Comment by ahsonkhan** [comment]
@stephentoub, @AtsushiKan, any feedback or can we merge this change in? I no longer see the 2 hour timeouts after this change.

**Pull request merged**
