### PR TITLE
Fix HttpClient on Unix handling of 0-len content with chunked upload

### PR DESCRIPTION
**Pull request by stephentoub**
When there's a disagreement between Content-Length and Transfer-Encoding being specified in the HttpRequestMessage, WinHttpHandler sanitizes the request to ensure it makes sense.  CurlHandler does the same thing, except it's currently doing it a bit too late in the send process: it should be doing it before the curl easy handle is configured based on the contents of the request, but it's currently doing it in the middle, after some configuration has already been done based on the content length.  The fix is simply to move the sanitization up earlier.  For the most part this didn't matter, but it was manifesting as incorrect handling of 0-length content with chunked uploads, where neither the content length nor chunks were being sent.

cc: @geoffkizer, @davidsh 
Fixes https://github.com/dotnet/corefx/issues/20419

### CODE REVIEW

**Comment by stephentoub** [comment]
@mmitch, more Java failures:
https://ci3.dot.net/job/dotnet_corefx/job/master/job/portable-windows-Config_Debug+OuterLoop_false_prtest/199/console
https://ci3.dot.net/job/dotnet_corefx/job/master/job/portable-windows-Config_Release+OuterLoop_false_prtest/200/console

**Comment by mmitch** [comment]
@stephentoub *handwave* I am not the @mmitch you are looking for
please ping somebody else for dotnet/corefx-related stuff :-)

**Comment by stephentoub** [comment]
Oops, my apologies @mmitch for the typo.

**Comment by stephentoub** [comment]
@dotnet-bot test this please (CI is being wonky)

**Comment by mmitche** [comment]
@stephentoub Thanks, looks like the Helix API or GitHub status is having issues, but the error handling needs to be better here

**Comment by mmitche** [comment]
@stephentoub I'm investigating the Innerloop Ubuntu16.04 arm Debug Cross Build failure.  Thinking that maybe docker isn't running

**Comment by stephentoub** [comment]
@mmitche, another failed fetch:
https://ci3.dot.net/job/dotnet_corefx/job/master/job/portable-windows-Config_Debug+OuterLoop_false_prtest/237/console

**Comment by stephentoub** [comment]
@mmitche, error on OSX:
https://ci3.dot.net/job/dotnet_corefx/job/master/job/GenPRTest/job/osx-Config_Debug+OuterLoop_false_prtest/6/console
```
ERROR: /jenkins/workspace/dotnet_corefx/master/GenPRTest/osx-Config_Debug+OuterLoop_false_prtest@script/buildpipeline/osx.groovy not found
```

**Comment by stephentoub** [comment]
@dotnet-bot help

**Comment by stephentoub** [comment]
@dotnet-bot test outerloop netcoreapp Ubuntu14.04 Debug
@dotnet-bot test outerloop netcoreapp OSX10.12 Debug
@dotnet-bot test outerloop netcoreapp RHEL7.2 Debug
@dotnet-bot test outerloop netcoreapp Windows_NT Debug

**Comment by mmitche** [comment]
@stephentoub that was @weshaggard working on the OSX stuff.  Please ignore.

**Pull request merged**
