### PR TITLE
Merge System.Reflection.Metadata changes from master to release/1.1.0

### PR DESCRIPTION
**Pull request by tmat**
Finalizes System.Reflection.Metadata public API surface for 1.1.0 release (https://github.com/dotnet/corefx/issues/12891).
No other SRM public API changes are planned for 1.1.0.

### CODE REVIEW

**Comment by tmat** [comment]
FYI @nguerrera

**Comment by nguerrera** [comment]
Have you validated somehow that we have everything? e.g. sanity check with folder diff of master and release/1.1.0?

**Comment by tmat** [comment]
Yes, I diffed against master.

**Comment by tmat** [comment]
Waiting with merge for the branch to open. ETA 10/17.

**Comment by karelz** [comment]
@tmat what is the value to have the changes in 1.1.0?

**Comment by tmat** [comment]
They are public surface breaking API changes. So, it's not an option to not have them in 1.1.0 and have them in 1.2.0.

**Comment by tmat** [comment]
(changes in public surface that was introduced since last release version)

**Comment by karelz** [comment]
OK, fixing regressions against 1.0.0 definitely makes sense.

**Comment by tmat** [comment]
They are not regressions - what I meant is that we introduced new public APIs since 1.0.0 and these changes alter that new API to its final form that we want to ship. If we shipped the API in its pre-release form in 1.1.0 we wouldn't be able to update it in 1.2.0, so it needs to happen now or never. Some of the changes are finishing functionality that was only partially implemented, so that it's now fully implemented for 1.1.0.

**Comment by karelz** [comment]
Got it now, thanks for explanation.

**Comment by karelz** [comment]
@stephentoub why *NO MERGE* label? Waiting on 1.1 to ship preview first? Or is there more to it?

**Comment by stephentoub** [comment]
> why NO MERGE label?

To avoid merging it per the above comments: "Waiting with merge for the branch to open. ETA 10/17."

**Comment by stephentoub** [comment]
@karelz, what's the status of the release/1.1.0 branch?

**Comment by karelz** [comment]
@gkhanna79 is 1.1.0 branch open for business?
/cc: @danmosemsft

**Comment by Petermarcu** [comment]
Still locked for 1.1.0 Preview until that ships. Should be any day.

**Comment by karelz** [comment]
1.1.0 branch is opened (in moderate Ask mode) as of yesterday. @tmat can you please get it in? (please send template)

**Pull request merged**
