### PR TITLE
Add net45.app as a 'supports' target

### PR DESCRIPTION
**Pull request by AArnott**

### CODE REVIEW

**Comment by ericstj** [comment]
If we are going to add more of these we should add a spec.  @pilchie @rchande what do you think about filling out the entire set?

**Comment by AArnott** [comment]
After reading the netstandard doc this morning, I was thinking we should have net452.app and the rest, yes.

**Comment by ellismg** [comment]
Do we have a plan here, yet?

**Comment by ericstj** [comment]
I covered this with https://github.com/dotnet/corefx/pull/9264

**Comment by ericstj** [comment]
Deleted this branch from the primary repo.  Please fork next time.

**Comment by AArnott** [comment]
Sorry. I'd heard several months back that the policy was MSFT team members should branch within the main repo so it is more visible what "Microsoft" was working on to the community. I didn't realize that had changed.

**Comment by ericstj** [comment]
That's never been the policy for CoreFx, though I had a hard time finding it written down in the contributing docs.  @terrajobst / @richlander / @weshaggard  can any of you point me to our external fork/PR policy docs?

**Pull request closed without merging**
