### PR TITLE
Add NetBSD support for the sysconf(_SC_NPROCESSORS_ONLN) call

### PR DESCRIPTION
**Pull request by krytarowski**
/usr/include/sys/unistd.h:#define       _SC_NPROCESSORS_ONLN    1002

### CODE REVIEW

**Comment by stephentoub** [comment]
LGTM

**Comment by stephentoub** [comment]
Test Innerloop OSX Debug Build and Test please
Test Innerloop OSX Release Build and Test please

**Comment by weshaggard** [comment]
@stephentoub This code path looks like it might be getting close to needing to go into a native shim. Isn't that how we have handled similar forks between distro's?

**Comment by stephentoub** [comment]
> @stephentoub This code path looks like it might be getting close to needing to go into a native shim. Isn't that how we have handled similar forks between distro's?

Not for tests.  There was initially a desire to keep the tests separate from the product code paths, and in general today tests are doing their own P/Invoking rather than calling to the shims.

But I commented in another PR that we should likely revisit that soon.

**Comment by weshaggard** [comment]
Ah sorry I did miss the fact this was a test I thought it was Enviroment.ProcessCount itself.

**Pull request merged**
