### PR TITLE
Test if AsymmetricDSASignature is passing on OSX

### PR DESCRIPTION
**Pull request by krwq**
https://github.com/dotnet/corefx/issues/16691

### CODE REVIEW

**Comment by krwq** [comment]
@dotnet-bot test Innerloop OSX10.12 Debug x64 Build and Test please

**Comment by krwq** [comment]
@dotnet-bot test Innerloop OSX10.12 Release x64 Build and Test please

**Comment by krwq** [comment]
@bartonjs PNSE is coming from DSASignatureDescription - are we planning to support it on OSX? Are there any workarounds? I'd just like to know if this is by design or something I should pursue fixing (I know DSA is not quite interesting for any new apps but I'm thinking of scenarios where someone had an old app and would like to just simply convert their project to work on different platforms)

**Comment by bartonjs** [comment]
@krwq Did you read the exception message?  `System.PlatformNotSupportedException : DSA keys can be imported, but new key generation is not supported on this platform.`

Did you look for prior art?  https://github.com/dotnet/corefx/issues/17001

**Comment by krwq** [comment]
@bartonjs I didn't know that creation is delayed until the key is being used, I'd expect this exception coming from DSA.Create() and not ComputeSignature. I think the delaying makes sense but I still find it confusing when looking at the exception

**Comment by bartonjs** [comment]
Yeah, the problem is that (until this week) importing a key required
```C#
using (DSA dsa = DSA.Create())
{
    dsa.ImportParameters(dsaParameters);
}
```

So Create() can't be what throws.

**Pull request closed without merging**
