### PR TITLE
Need to flow SerializeProjects=true to the child processes when doing CodeCoverage builds.

### PR DESCRIPTION
**Pull request by weshaggard**
Fixes https://github.com/dotnet/corefx/issues/5204

cc @stephentoub

### CODE REVIEW

**Comment by weshaggard** [comment]
@dotnet-bot Code Coverage Windows Debug

**Comment by weshaggard** [comment]
test code coverage

**Comment by weshaggard** [comment]
@stephentoub does the code coverage report http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/code_coverage_windows_prtest/5/Code_Coverage_Report/ look more along the lines as you are expecting?

**Comment by stephentoub** [comment]
Yup! Thanks, Wes.

**Pull request merged**
