### PR TITLE
Port infra  and test changes to release/3.0

### PR DESCRIPTION
**Pull request by ViktorHofer**
Infra and test changes only. No risk.

### CODE REVIEW

**Comment by ViktorHofer** [comment]
@Anipik do you know when the release/3.x branches will be open again?

**Comment by Anipik** [comment]
@ViktorHofer The branch is not open yet and we don't have any ETA on when it will be open.

**Comment by danmosemsft** [comment]
Can you briefly describe the changes (other than disabling the test)?

> No risk

No risk maybe to the contents of the binaries that go to customers but by risk we are usually thinking about any risk to the process of making product out of the branch. So infrastructure changes will always have risk. Disabling a test essentially has no risk.

**Comment by ViktorHofer** [comment]
> No risk maybe to the contents of the binaries that go to customers but by risk we are usually thinking about any risk to the process of making product out of the branch. So infrastructure changes will always have risk. Disabling a test essentially has no risk.

In this case it's really no risk as the infra change is about disabling some UWP and arm64 (Windows) legs which aren't relevant in the release/3.0 branch.

**Comment by ViktorHofer** [comment]
@wtgodbe is the branch open again?

**Comment by mmitche** [comment]
@ViktorHofer not yet.

**Comment by danmosemsft** [comment]
Can you explain why we need the .json change - I see it's to pick preview SDK's?

**Comment by ViktorHofer** [comment]
The json change allows to use a newer SDK than 3.0.100 to build. Actually I'm closing this PR now as CI council doesn't measure the 3.x branches anymore. I don't think there's much value left in back-porting all test and infra fixes.

**Pull request closed without merging**
