### PR TITLE
Port several WinHTTP PRs to release/1.0.0

### PR DESCRIPTION
**Pull request by stephentoub**
https://github.com/dotnet/corefx/pull/11159
https://github.com/dotnet/corefx/pull/11383
https://github.com/dotnet/corefx/pull/11481
https://github.com/dotnet/corefx/pull/11733

cc: @davidsh, @leecow, @gkhanna79, @Petermarcu

### CODE REVIEW

**Comment by davidsh** [comment]
Test OuterLoop Windows_NT Debug Build and Test
Test OuterLoop Ubuntu14.04 Debug Build and Test
Test OuterLoop OSX Debug Build and Test
Test OuterLoop CentOS7.1 Debug Build and Test

**Comment by davidsh** [comment]
Test OuterLoop Windows_NT Debug Build and Test
Test OuterLoop Ubuntu14.04 Debug Build and Test
Test OuterLoop OSX Debug Build and Test
Test OuterLoop CentOS7.1 Debug Build and Test

**Comment by stephentoub** [comment]
Failure in OuterLoop Windows_NT Debug is an unrelated process test failure:
```
System.InvalidOperationException : No process is associated with this object.
        Stack Trace:
           D:\j\workspace\outerloop_win---a104402d\src\System.Diagnostics.Process\src\System\Diagnostics\Process.cs(769,0): at System.Diagnostics.Process.EnsureState(State state)
           D:\j\workspace\outerloop_win---a104402d\src\System.Diagnostics.Process\src\System\Diagnostics\Process.cs(188,0): at System.Diagnostics.Process.get_HasExited()
           D:\j\workspace\outerloop_win---a104402d\src\System.Diagnostics.Process\tests\ProcessStartInfoTests.cs(395,0): at System.Diagnostics.Tests.ProcessStartInfoTests.TestUserCredentialsPropertiesOnWindows()
```

**Comment by stephentoub** [comment]
CentOS failure is the same unrelated OS issue we've been seeing frequently.

**Pull request merged**
