### PR TITLE
Shrink StringDictionary

### PR DESCRIPTION
**Pull request by lexware**

### CODE REVIEW

**Comment by sharwell** [comment]
:expressionless: You had me worried for a second that I missed another feature.

**Comment by mikedn** [comment]
Is this some kind of joke or what?!

**Comment by lexware** [comment]
@mikedn I'm failing to see the joke, it may be a small pull-request, but should provide the same output, just in a smaller amount of code.

**Comment by stephentoub** [comment]
@lexware, I believe @mikedn's comment is due to this not being valid C#.

**Comment by lexware** [comment]
Oh, I can guess this is from my inexperience in C#, I'll close the pull-request. Sorry for wasting everyones time, still strange the build was successful.

**Comment by stephentoub** [comment]
Regardless, @lexware, thank you for your interest in contributing!  It is indeed strange that this compiled successfully; I wasn't able to reproduce the problem (I get the expected error "A get or set accessor expected", but if you figure out what went wrong and it's a problem with the build system for this project, please do let us know.

**Comment by lexware** [comment]
I'll be sure to post a issue if I find out why it compiled successfully.

**Comment by akoeplinger** [comment]
Hmm, it does raise the error in the build:
>10:15:55 System\Collections\Specialized\StringDictionary.cs(67,13): error CS1014: A get or set accessor expected [C:\Jenkins\workspace\dotnet_corefx_windows_prtest\src\System.Collections.Specialized\src\System.Collections.Specialized.csproj]

Looks like this didn't translate into a failed build. @mmitche ?

**Comment by sharwell** [comment]
@lexware You should reopen this and change the title to "Automated build fails to report syntax errors" :+1:

**Comment by lexware** [comment]
Will have to open as an issue as I deleted the branch and can't reopen.

**Pull request closed without merging**
