### PR TITLE
Consistent exception on empty block expression

### LINKED ISSUE #3882: Exception on empty block expression inconsistent.
`Expression.Block()` throws an `ArgumentException`.

`Expression.Block(Enumerable.Repeat<ParameterExpression>(Expression.Parameter(typeof(int)), 1))` throws `InvalidOperaitonException`.

They should both throw `ArgumentException`.

### PR DESCRIPTION
**Pull request by JonHanna**
Fixes #3882

### CODE REVIEW

**Comment by JonHanna** [comment]
Fixes #3908 as well.

**Comment by stephentoub** [comment]
@dotnet-bot test this please (FindPackagesById errors)

**Comment by VSadov** [comment]
It does not seem like the inconsistency in exception types was intentional.

**Comment by VSadov** [comment]
LGTM

**Pull request merged**
