### PR TITLE
Cleanup StringBuilder tests

### LINKED ISSUE #6286: Cleanup System.Runtime.Tests
This is a meta-issue to track progress on cleaning up System.Runtime.Tests. I dumped a massive PR (#5490) which I'm splitting up into smaller ones
The following test files should be cleaned up, to add additional coverage, and follow test guidelines better:

- [x] String (#6296)
- [x] StringBuilder (#6295)
- [ ] Number primitives: byte, int, long etc.
- [ ] Floating primitives: float, double
- [x] Decimal (#6297)
- [x] Array (#6293)
- [ ] Array Segment
- [ ] Buffer
- [ ] DateTime
- [ ] DateTimeOffset
- [ ] TimeSpan
- [ ] Char
- [ ] DefaultValue and EditorBrowsable
- [ ] System.IO exceptions
- [x] Activator (#6294)
- [ ] Attribute
- [ ] System exceptions
- [ ] GC
- [x] Version (#6298)
- [x] Guid (#6299)
- [ ] Nullable
- [ ] Lazy
- [x] Pointers - IntPtr and UIntPtr (#6300)

After this:
- Add missing namespaces
- Rename tests as per #4535

### PR DESCRIPTION
**Pull request by hughbe**
Overhauls the entire test file, providing c.94% coverage.

### CODE REVIEW

**Comment by hughbe** [comment]
Test failures on OSX are unrelated: System.Runtime.Tests  Total: 2524, Errors: 0, Failed: 0, Skipped: 0, Time: 2.020s

**Comment by stephentoub** [comment]
Test Innerloop OSX Release Build and Test please

**Comment by stephentoub** [comment]
I'm going to leave comments here because GitHub won't let me comment on the file due to there being too many changes.

**Comment by stephentoub** [comment]
TestCtor_Empty, L18.  This should ```Assert.Same(string.Empty, builder.ToString())```.

**Comment by stephentoub** [comment]
TestCtor_Int, L26.  Same as above: anywhere we expect a 0-length string, we should do such a Same assert.

**Comment by stephentoub** [comment]
TestCtor_Int_Int, L46-47.  This should use Assert.InRange rather than two Assert.Trues.

**Comment by stephentoub** [comment]
TestCtor_Int_Int_Invalid, L55. The comment looks like it's referring to the wrong parameter.

**Comment by stephentoub** [comment]
TestCtor_String, L68.  Instead of ```value != null ? value : ""```, you can do ```value ?? ""```.

**Comment by stephentoub** [comment]
TestCtor_String_Int, L81.  Same as above, and anywhere else that pattern repeats.

**Comment by stephentoub** [comment]
TestItem_Get_Set, L132.  ```char c = char.Parse(i.ToString())``` would be better as ```char c = (char)(i + '0');```.

**Comment by stephentoub** [comment]
TestAppendFormat, L703.  All of these if/else conditions include ```values != null```... seems like it'd be simpler if that were separated out into a parent if.

**Comment by stephentoub** [comment]
L1473.  I may have missed it, but for these various Remove, Replace, etc. tests, do you have boundary cases for where the input string is empty, contains just one character, etc.?

**Comment by stephentoub** [comment]
> providing > 90% coverage

Nice.  What was it before your changes?

**Comment by stephentoub** [comment]
Overall, this LGTM.  Thanks for writing all these new tests!

**Comment by hughbe** [comment]
Thanks for the comments, I just pushed a PR feedback commit.

- Previous coverage: about 65% line, 45% branch from memory.
- New coverage: 94.3% line, 89.7% branch. 
That's an increase of almost 30%, and 45% in line and branch coverage respectively if my A Level maths doesn't fail me!

**Comment by JonHanna** [comment]
I'd make that a 45% and 99% increase as a percentage of what was there before, and pay a bit more heed to the 99% than the 45% (while still just a rough indicator, I like to see branches are being covered more than that lines are). Well done!

**Comment by hughbe** [comment]
Ah yes good maths ;)
Thanks!

**Comment by stephentoub** [comment]
@dotnet-bot test this please

**Pull request merged**
