### PR TITLE
Update buildtools to 807-03

### PR DESCRIPTION
**Pull request by stephentoub**
cc: @davidsh, @MattGal

### CODE REVIEW

**Comment by davidsh** [comment]
Ref: This is needed to pick up this change: https://github.com/dotnet/buildtools/pull/1016

**Comment by davidsh** [comment]
Looks like project.json needs to be changed also.

From @MattGal 

>Updating build tools is usually fine (unless it breaks the build) but you won't see your changes to that project unless you change this line: https://github.com/dotnet/corefx/blob/master/src/Common/test-runtime/project.json#L102

**Comment by MattGal** [comment]
As noted on the other thread, this is unnecessary and will not affect the version of xunit.runner.uwp used.

**Comment by stephentoub** [comment]
> As noted on the other thread, this is unnecessary (unless you have other changes to pick up, in which case go ahead...) and will not affect the version of xunit.runner.uwp used.

I'll close this then.   @mattgal, can you please submit a PR that makes the appropriate updates?

**Comment by stephentoub** [comment]
Also, the failed attempt to update the buildtools version shows that something is broken/inconsistent/needs to be fixed.  It'd be helpful for whoever made the relevant buildtools changes to update here as well, otherwise whoever comes along and tries to update it next is going to hit the same thing.

**Comment by MattGal** [comment]
I was just chatting with @ericstj  about this.  

Per Eric, there are currently two issues blocking taking new build tools, summarized by the following: 

https://github.com/dotnet/buildtools/commit/42226639044761504a6aaaa8e8580359765c0de0#commitcomment-18933001 ,
then this: https://github.com/dotnet/buildtools/commit/3a387dc25a68234913050d486167c3f9dab9510c 
requires a new CLI in CoreFx, which @dagood  is working on.

**Pull request closed without merging**
