### PR TITLE
Update BuildTools to 00822-03

### PR DESCRIPTION
**Pull request by ericstj**
/cc @weshaggard @hughbe

### CODE REVIEW

**Comment by ericstj** [comment]
@dotnet-bot test Innerloop CentOS7.1 Debug Build and Test
@dotnet-bot test Innerloop CentOS7.1 Release Build and Test

**Comment by ericstj** [comment]
Windows release failed with 
```
14:20:51      System.Net.NameResolution.Tests.GetHostByAddressTest.DnsObsoleteGetHostByAddress_LoopbackString_ReturnsSameAsLoopbackIP [FAIL]
14:20:52         System.Net.Sockets.SocketException : Either the application has not called WSAStartup, or WSAStartup failed
14:20:52         Stack Trace:
14:20:52            D:\j\workspace\windows_nt_re---37265eab\src\System.Net.NameResolution\src\System\Net\DNS.cs(186,0): at System.Net.Dns.InternalGetHostByAddress(IPAddress address, Boolean includeIPv6)
14:20:52            D:\j\workspace\windows_nt_re---37265eab\src\System.Net.NameResolution\src\System\Net\DNS.cs(109,0): at System.Net.Dns.GetHostByAddress(String address)
14:20:52            D:\j\workspace\windows_nt_re---37265eab\src\System.Net.NameResolution\tests\FunctionalTests\GetHostByAddressTest.cs(24,0): at System.Net.NameResolution.Tests.GetHostByAddressTest.DnsObsoleteGetHostByAddress_LoopbackString_ReturnsSameAsLoopbackIP()
```

/cc @CIPop looks to me like it could be a problem with EnsureSocketsAreInitialized

**Comment by ericstj** [comment]
@dotnet-bot test  Innerloop Windows_NT Release Build and Test

**Comment by CIPop** [comment]
> looks to me like it could be a problem with EnsureSocketsAreInitialized

/cc @ericeil 
Should be fixed with  #12084.

**Comment by ericstj** [comment]
Thanks, Seems to be working now.

**Comment by ericstj** [comment]
@dotnet-bot test Innerloop CentOS7.1 Debug Build and Test

**Pull request merged**
