### PR TITLE
Remove unused files in serialization

### PR DESCRIPTION
**Pull request by khdang**
Follow up from https://github.com/dotnet/corefx/commit/c2babe77ed4af3066ebc3bade23ea5b7eb277d19, removing unused files from serialization folder.

cc: @SGuyGe @shmao @zhenlan

### CODE REVIEW

**Comment by SGuyGe** [comment]
LGTM

**Comment by zhenlan** [comment]
LGTM

**Comment by stephentoub** [comment]
Test Innerloop OSX Debug Build and Test please (machine went offline during build)
Test Innerloop OSX Release Build and Test please (machine went offline during build)

**Comment by khdang** [comment]
Test Innerloop OSX Debug Build and Test please
Test Innerloop OSX Release Build and Test please

**Comment by khdang** [comment]
Test Innerloop OSX Release Build and Test please

**Pull request merged**
