### PR TITLE
Porting remaining System.ComponentModel.Composition tests

### PR DESCRIPTION
**Pull request by maryamariyan**
Ported test project has around 1500 tests now. 
Increases line/branch coverage to 88% and 80% respectively from 73% and 65%

Around 80 tests are still disabled on all platforms
another 70 tests are only disabled on unix and need troubleshooting 
(these disabled tests are linked with issue 25498.)

cc: @danmosemsft

### CODE REVIEW

**Comment by maryamariyan** [comment]
@danmosemsft I'm breaking down the last long commit to smaller commits for easier review

**Comment by danmosemsft** [comment]
Some of the tests failed with seg faults, and have dumps, eg.,
```
2017-12-12 05:12:00,228: INFO: proc(54): run_and_log_output: Output: Uploading dump file: /home/helixbot/dotnetbuild/work/e77c2fb6-5244-4437-8e27-6dd709101152/Work/d9eba0ea-a511-4f42-ac8b-ac8054aaf606/Unzip/core
2017-12-12 05:12:00,232: INFO: proc(54): run_and_log_output: Output: ~/dotnetbuild/work/e77c2fb6-5244-4437-8e27-6dd709101152/Work/d9eba0ea-a511-4f42-ac8b-ac8054aaf606/Unzip
```
https://mc.dot.net/#/user/maryamariyan/pr~2Fjenkins~2Fdotnet~2Fcorefx~2Fmaster~2F/test~2Ffunctional~2Fcli~2F/12cbeed85897de05d63181974602cd977ea30966/workItem/System.ComponentModel.Composition.Tests/wilogs

You can use the instructions @Anipik sent around last month to open this and see the callstack.

**Comment by safern** [comment]
This are the instructions on how to see the callstack: 

https://github.com/dotnet/corefx/blob/master/Documentation/debugging/unix-instructions.md#debugging-core-dumps-with-lldb

**Comment by maryamariyan** [comment]
@danmosemsft @safern Could you please guide me to the reason why osx and linux are failing and how I can fix this build?

**Comment by danmosemsft** [comment]
As you can see from the logs, the Linux runs are still having a segfault. if dumpling is not working correctly, you will have to run the tests locally. As all distros are hitting it consistently, it should not be hard to reproduce. It will be a fault either in some unsafe code in S.C.CM or its tests, or a runtime/PAL bug. The callstack will help.

For OSX it is also segfaulting, perhaps the same issue, but you will see in the log at least one real test faliure:
```
2017-12-13 03:40:22,415: INFO: proc(54): run_and_log_output: Output: Starting:    System.ComponentModel.Composition.Tests
2017-12-13 03:40:24,634: INFO: proc(54): run_and_log_output: Output: System.ArgumentException: ComposablePartDefinition of type 'System.ComponentModel.Composition.AttributedModel.ConcreteCPD' cannot be used in this context. Only part definitions produced by the ReflectionModelServices.CreatePartDefinition are supported.
2017-12-13 03:40:24,634: INFO: proc(54): run_and_log_output: Output: Parameter name: partDefinition
2017-12-13 03:40:24,634: INFO: proc(54): run_and_log_output: Output:    at System.ComponentModel.Composition.AttributedModelServices.CreatePart(ComposablePartDefinition partDefinition, Object attributedPart) in D:\j\workspace\windows-TGrou---f8ac6754\src\System.ComponentModel.Composition\src\System\ComponentModel\Composition\AttributedModelServices.cs:line 49
2017-12-13 03:40:24,634: INFO: proc(54): run_and_log_output: Output:    at System.ComponentModel.Composition.AttributedModel.AttributedModelServicesTests.<>c.<CreatePart_From_InvalidPartDefiniton_ShouldThrowArgumentException>b__2_0() in D:\j\workspace\windows-TGrou---f8ac6754\src\System.ComponentModel.Composition\tests\System\ComponentModel\Composition\AttributedModelServicesTests.cs:line 64
2017-12-13 03:40:24,651: INFO: proc(54): run_and_log_output: Output: requiredService: System.ComponentModel.Composition.Hosting.CompositionContainer+CompositionServiceShim
2017-12-13 03:40:24,651: INFO: proc(54): run_and_log_output: Output: optionalService: System.ComponentModel.Composition.Hosting.CompositionContainer+CompositionServiceShim
2017-12-13 03:40:26,447: INFO: proc(54): run_and_log_output: Output: Finished:    System.ComponentModel.Composition.Tests

```
If you don't have a Mac handy hopefully fixing the Linux issue and the test dumped above and OSX may go green.

**Comment by maryamariyan** [comment]
@dotnet-bot test OSX x64 Debug Build please

**Pull request merged**
