### PR TITLE
Move argument validation for some ImmutableList functions to ImmutableList.Node

### PR DESCRIPTION
**Pull request by jamesqo**
I am still breaking up parts of https://github.com/dotnet/corefx/pull/15382 into different PRs to make reviewing easier. In this PR, I've removed argument validation for a couple of `ImmutableList` functions. I did this since I noticed many functions validated their arguments twice, once in `ImmutableList` and once in `ImmutableList.Node`. It's simpler if we just omit validation for the former and let the `Node` class take care of it.

There were a few places where `ImmutableList` and `Node` validated arguments differently. For those cases, I copied and pasted the `ImmutableList` validation into the `Node` method to preserve exception behavior.

/cc @safern, @ianhays, @AArnott

### CODE REVIEW

**Comment by AArnott** [comment]
>  It's simpler if we just omit validation for the former and let the Node class take care of it.

The risk of this approach is that if `Node` throws argument exceptions, it will reference names of parameters as they are identified in the `Node` class's method rather than the public method that the user code called. As long as the parameter names are the same, IMO it's OK, but maintaining that will be difficult.

If we kept the validation on the outer methods that would avoid that problem -- but possibly create redundancy at the multiple entrypoints for a given Node method. I don't know how big of a problem *that* is though.

**Comment by jamesqo** [comment]
> As long as the parameter names are the same, IMO it's OK, but maintaining that will be difficult.

Not really, it should catch a maintainer's eye if the name of a parameter in a `Requires.Something(..., nameof(parameter))` call is changed.

**Comment by jamesqo** [comment]
> If we kept the validation on the outer methods that would avoid that problem -- but possibly create redundancy at the multiple entrypoints for a given Node method. I don't know how big of a problem that is though.

Someone might change the validation in `ImmutableList_1` and forget to change it in `Builder`, or vice versa. Plus, perf would be slightly worse-- if both classes just forward the arguments to `Node` then the initial method call (e.g. `ImmutableList_1.CopyTo`) will definitely be inlined, whereas right now there are 2 calls, one to `ImmutableList_1.CopyTo` and one to `Node.CopyTo`.

**Comment by AArnott** [comment]
OK, fair enough. I don't have time to review the diff now, but I hope to get to it perhaps later today.

**Comment by danmosemsft** [comment]
Thanks @jamesqo !

**Pull request merged**
