### PR TITLE
Updated the error message for missing dia sdk in build.cmd. Closes #2…

### PR DESCRIPTION
**Pull request by OzieGamma**
…5856

### CODE REVIEW

**Comment by OzieGamma** [comment]
First PR failed to trigger bots/tests. #25858

**Comment by OzieGamma** [comment]
I installed VS2015 and the installer correctly installed the DIA SDK.

**Comment by danmosemsft** [comment]
Sounds good to me but I don't know the history of this error @weshaggard OK w/ you?

**Comment by weshaggard** [comment]
Based on https://github.com/dotnet/coreclr/pull/14948, I think the issue is that this isn't always available with VS2017 not VS2015. That said I'm not even sure if it is needed for corefx I think this might be left over from a copy in coreclr.

**Comment by danmosemsft** [comment]
@mikem8361 have you any context on when the issue referenced in this error was fixed?

**Comment by OzieGamma** [comment]
The original message mentions coreclr as a fix (I changed it to the corefx documentation). Does the check need to be completely removed?

Changing the VS 2017 install does install the DIA SDK. I was missing it. So the check did catch that error. The error message just sent me down the wrong solution.

**Comment by mikem8361** [comment]
Sorry. No.

**Comment by danmosemsft** [comment]
OK we thought about this enough. merged. thanks for the change @OzieGamma

**Pull request merged**
