### PR TITLE
Cache evaluated console color strings

### LINKED ISSUE #761: Weird console problem on Mac OS X
It happens when I run [CoreClrHelloWorld](https://github.com/dotnet/corefxlab/blob/master/demos/CoreClrConsoleApplications/HelloWorld/HelloWorld.cs) console app to draw Linux logo on Mac OS X.
When I type `runtime_mac/corerun app/HelloWorld.exe linux` to run it, the console draw an incomplete penguin. See the below screen shot.

screen shot 2015-02-13 at 23 30 28
After that, the console is out of control. I can move cursor and type text in console. But the console does not respond any command. The console's background color and foreground color become gray. "Press ENTER to exit ..." does not appear.

screen shot 2015-02-13 at 23 33 00
Then I comment the following two line code in HelloWorld.cs.
```csharp
ConsoleColor cc =
    c == '*' ? ConsoleColor.Blue :
    c == '@' ? ConsoleColor.Black :
    c == '-' ? ConsoleColor.Yellow :
    ConsoleColor.White;
//Console.BackgroundColor = cc;
//Console.ForegroundColor = cc;
Console.Write(" ");
```
Compile and run it. The weird console problem disappear.
Afterwards,  I try to run HelloWorld.exe by mono.
```
mono app/HelloWorld.exe linux
```
The entire enguin is been showing.
```
Hello, Linux...
[Penguin]
Press ENTER to exit ...
```
The problem can be reproduced by following below command on Mac OS X.
```
git clone https://github.com/cnblogs-dudu/CoreClrHelloWorld.git
cd CoreClrHelloWorld
runtime_mac/corerun app/HelloWorld.exe linux
```

### PR DESCRIPTION
**Pull request by stephentoub**
Each time a call to Console.ForegroundColor or Console.BackgroundColor is made on Unix, we access the terminfo database to get the right evaluation string, evaluate it, and then write out the result.  But there are only 16 possible colors for each of foreground and background, and these strings are idempotent.  This commit just adds a small cache to avoid recomputing these strings every time.

Fixes #761 

cc: @pgavlin, @ellismg

### CODE REVIEW

**Comment by ellismg** [comment]
LGTM

**Comment by pgavlin** [comment]
LGTM as well. Thanks for doing this.

**Comment by cnblogs-dudu** [comment]
Great! It works well. Thanks.

**Comment by stephentoub** [comment]
Terrific :)

**Pull request merged**
