### PR TITLE
Update new libraries be be fully signed with Open key

### PR DESCRIPTION
**Pull request by weshaggard**
This cannot be merged until the associated PR in BuildTools https://github.com/dotnet/buildtools/pull/407 is published. I'm submitting the PR early to settle on the libraries we want to sign with this new open key.

Fixes https://github.com/dotnet/corefx/issues/5153 @davidfowl 

@terrajobst please take a look to see if there are any other libraries we should switch to using this new open key. 

FYI for the owners of the libraries
@sokket @KrzysztofCwalina @vancem @davmason @stephentoub

### CODE REVIEW

**Comment by weshaggard** [comment]
After the build tools update to 154 from https://github.com/dotnet/corefx/pull/5661 this should build now but I would still like confirmation from others about the list.

**Comment by terrajobst** [comment]
@weshaggard looks good to me. What is your plan with porting this to corefxlab? All libraries there should use the open key.

**Comment by weshaggard** [comment]
@terrajobst I don't currently have any plans to do that. @KrzysztofCwalina are you guys still using BuildTools in corefxlab? If so you can import the newer version to get access to the key.

**Comment by weshaggard** [comment]
Innerloop OpenSUSE13.2 Debug Build and Test

**Comment by weshaggard** [comment]
Innerloop OpenSUSE13.2 Debug Build and Test

**Comment by weshaggard** [comment]
@dotnet-bot test Innerloop OpenSUSE13.2 Debug Build and Test

**Comment by terrajobst** [comment]
Sounds good.

**Pull request merged**
