### PR TITLE
Added System.Runtime.ProfileOptimization

### PR DESCRIPTION
**Pull request by MarcoRossignoli**
closes https://github.com/dotnet/corefx/issues/30185

/cc @brianrob @jkotas @danmosemsft

### CODE REVIEW

**Comment by MarcoRossignoli** [comment]
from issue 

>This is applicable to CoreRT as well. We maintain same public surface across between different .NET Core runtimes.

@jkotas do we need also a PR on CoreRT with throw PNE?

**Comment by jkotas** [comment]
> @jkotas do we need also a PR on CoreRT throws PNE?

Yes - I have not realized that the API is not there. The implementation for CoreRT should be no-op.

**Comment by jkotas** [comment]
> .i think i need to move on netcoreapp only test

Correct.

**Comment by MarcoRossignoli** [comment]
@dotnet-bot test OSX x64 Debug Build please

**Comment by jkotas** [comment]
@dotnet-bot test this please

**Comment by jkotas** [comment]
@dotnet-bot test this please

**Pull request merged**
