### PR TITLE
Remove System.Security.SecureString from .NetCore

### PR DESCRIPTION
**Pull request by pallavit**
In the [API Review](https://github.com/dotnet/apireviews/pull/8) it was decides to remove SecureString support from .NetCore. First commit does that. However, with that commit, the project.json files started taking dependency on the latest xunit package beta3-00092  that ran into a complier issue

*CSC : error CS1705: Assembly 'Xunit.NetCore.Extensions' with identity 'Xunit.NetCore.Extensions, Version=999.999.999.999, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' uses 'xunit.core, Version=2.1.0.3168, Culture=neutral, PublicKeyToken=8d05b1bb7a6fdb6c' which has a higher version than referenced assembly 'xunit.core' with identity 'xunit.core, Version=2.1.0.3029, Culture=neutral, PublicKeyToken=8d05b1bb7a6fdb6c' [D:\OSS\corefx\src\System.ObjectModel\tests\System.ObjectModel.Tests.csproj]*

and so I updated the xunit package from beta3 to rc1 (2nd commit in the PR) to mitigate the issue.

### CODE REVIEW

**Comment by pallavit** [comment]
@weshaggard Could you please review the change.

**Comment by weshaggard** [comment]
@dotnet-bot test this please

**Comment by weshaggard** [comment]
@pallavit thanks for updating the lock files, can you please check the test failures.

**Comment by pallavit** [comment]
@dotnet-bot test this please

**Comment by pallavit** [comment]
I looked at the log and I am seeing issues that seem unrelated to my change. For example - 

*Unhandled Exception: System.IO.FileNotFoundException: Could not load file or assembly 'System.Diagnostics.TraceSource, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.*

*Starting:    System.IO.Compression.Tests
  Could not change deflater type to zlib: missing s_forcedTestingDeflaterType
  Could not change deflater type to zlib: missing s_forcedTestingDeflaterType*

When I try to run the tests locally, I don't see this issue. Are these issues known?

**Comment by weshaggard** [comment]
I wonder if that dependency was getting pulled in from a transitive closure dependency before but is not now. Have you tried cleaning our bin folder or perhaps your entire git repo (git clean -xdf) and testing?

**Comment by stephentoub** [comment]
@dotnet-bot test this please

**Comment by pallavit** [comment]
@stephentoub I have been able to repro this issue locally. Although this seems to be related to package lock file closure and not my change, I believe it was triggered due to an edit to the lock file. I have not had a chance to look at it but it is a genuine failure and I will take a look ASAP.

**Comment by stephentoub** [comment]
Thanks, @pallavit.

**Comment by pallavit** [comment]
#3536 limits the updates done to the lock files.

**Comment by stephentoub** [comment]
@pallavit, looks like this is going to need to be rebased

**Comment by pallavit** [comment]
I am closing this one, since I had to create a separate PR with limited updates to the lock files.

**Pull request closed without merging**
