### PR TITLE
Update XUnitExtensions

### PR DESCRIPTION
**Pull request by ViktorHofer**
Fixes https://github.com/dotnet/corefx/issues/32084

### CODE REVIEW

**Comment by ViktorHofer** [comment]
Verified locally:

image

**Comment by joperezr** [comment]
I would assume that the test errors on netfx are caused by this change?

**Comment by ViktorHofer** [comment]
> I would assume that the test errors on netfx are caused by this change?

Right, it seems the failing tests are the ones that didn't run before on netfx (with our custom runner).

**Comment by ViktorHofer** [comment]
@JeremyKuhne netfx tests are now running correctly and failing because of `HasLegacyIoBehavior` reports false but the error message indicates that the legacy behavior is active. We are using net472. Can you please take a look?

**Comment by JeremyKuhne** [comment]
@ViktorHofer `AreOsLongPathsEnabled` is also needed for the long path ones that are failing. `AreAllLongPathsAvailable` is the one that wraps the two. Tests that use `\\?\` should be working with `!AreLongPathsBlocked` (they don't need the OS switch).

**Pull request merged**
