### PR TITLE
Fat package conversion for System.Reflection.TypeExtensions

### PR DESCRIPTION
**Pull request by chcosta**
cc @ericstj

### CODE REVIEW

**Comment by ericstj** [comment]
LGTM!

**Comment by ericstj** [comment]
@dotnet-bot test this please

**Comment by chcosta** [comment]
I'm investigating this failure to see if I can get a local repro on Ubuntu.

**Comment by ericstj** [comment]
Lets just rerun.  UNIX builds were broken yesterday due to core CLR regression.

**Comment by chcosta** [comment]
@dotnet-bot test this please

**Pull request merged**
