### PR TITLE
Add new MediaTypeNames

### LINKED ISSUE #26201: Add application/json to System.Net.Mime.MediaTypeNames.Application
# API Proposal
(Added by @karelz based on original issue)

Add `application/json` MIME type (based on JSON RFC 4627 - https://www.ietf.org/rfc/rfc4627.txt)
```diff
namespace System.Net.Mime
{
    public static class MediaTypeNames
    {
        public static class Application
        {
            public const string Soap = "application/soap+xml";
            public const string Octet = "application/octet-stream";
            public const string Rtf = "application/rtf";
            public const string Pdf = "application/pdf";
            public const string Zip = "application/zip";
+           public const string Json = "application/json";
+           public const string Xml = "application/xml"
        }
    }
}
```

## Motivation

Common StackOverflow question: https://stackoverflow.com/questions/477816/what-is-the-correct-json-content-type (8.6K upvotes)

# Original report

The `MediaTypeNames` class contains constants for common mime types. Surprisingly, it doesn't contain the type for JSON, which is both extremely common and frequently confused (https://stackoverflow.com/questions/477816/what-is-the-correct-json-content-type). Would it be worth adding a constant entry for this?

### PR DESCRIPTION
**Pull request by MarcoRossignoli**
fixes #26201

### CODE REVIEW

**Comment by stephentoub** [comment]
Thanks

**Comment by Macadoshis** [comment]
I can't figure out why it took so much time to have such a basic and needed feature embedded in the SDK :/

not here to troll, but for instance java includes it since JDK6 (2011 !)
https://docs.oracle.com/javaee/6/api/javax/ws/rs/core/MediaType.html

**Comment by IanKemp** [comment]
Will this be in .NET Standard 2.1?

**Comment by MarcoRossignoli** [comment]
@IanKemp better to ask here https://github.com/dotnet/standard/issues for quick response.

**Pull request merged**
