### PR TITLE
Cache MethodInfo instances used in ExpandoObject

### PR DESCRIPTION
**Pull request by JonHanna**
At least one of these methods are obtained for almost every operation on an `ExpandoObject` used as dynamic, so caching them is sensible.

Since the most common use-cases for `ExpandoObject` would involve all of these (bar perhaps `ExpandoTryDeleteValue`) they're each obtained immediately, rather than lazy-loaded.

### CODE REVIEW

**Comment by JonHanna** [comment]
@bartdesmet PTAL. This is following your lead with queryable recently.

**Comment by bartdesmet** [comment]
LGTM; I also don't think we need lazy instantiation of these reflection objects because there are few of them and they're declared a static in `ExpandoObject`.

**Comment by VSadov** [comment]
LGTM

**Comment by JonHanna** [comment]
Aside from one, the only reason I can think of for having triggered those constructors and not hit all of those methods is that you're writing unit tests to test it's IDictionary implementation :)

**Pull request merged**
