### PR TITLE
Fix binclash in System.Net.Primitives

### PR DESCRIPTION
**Pull request by chcosta**
cc @ericstj, @stephentoub

### CODE REVIEW

**Comment by stephentoub** [comment]
cc: @davidsh 
LGTM

**Comment by davidsh** [comment]
LGTM

**Comment by ericstj** [comment]
LGTM.  We should probably fix either the logger or the pkgproj to enable detection.  Simple fix for pkgproj would be to set TargetPath to NuspecOutputPath (don't use the package output path since that requires running targets).

**Comment by chcosta** [comment]
I've created a new issue to track fixing the detection.

**Comment by stephentoub** [comment]
@dotnet-bot test this please

**Comment by stephentoub** [comment]
@dotnet-bot test this please

**Pull request merged**
