### PR TITLE
Exclude unreachable members in System.Linq.Expressions from coverage.

### PR DESCRIPTION
**Pull request by JonHanna**
All such members are entirely unreachable, and coverage including them is not
informative.

### CODE REVIEW

**Comment by JonHanna** [comment]
The smallest of steps on #1198, but worth doing and doesn't fit in well with any change focusing on a particular part of the assembly.

**Comment by stephentoub** [comment]
I don't love using ExcludeFromCodeCoverage in this way, but I'm ok with it.  I did just open a PR #3879 to help ensure these attributes don't show up in the release builds.

cc: @VSadov

**Comment by JonHanna** [comment]
I obviously enough do like using it, but that change is a great idea. There is value sometimes in running tests against release builds, and sometimes on running coverage on those, but since this `internal` version of the attribute isn't used that way, and doesn't depend on another assembly the way the System.dll version does, that's a great ida.

**Comment by stephentoub** [comment]
@VSadov, up to you whether you want to take this.

**Comment by stephentoub** [comment]
@VSadov, do you want to merge this or should we close it?

**Comment by VSadov** [comment]
LGTM

**Pull request merged**
