### PR TITLE
Add System.Reflection.Metadata.Test.Desktop, which targets FX 4.6 and  Xunit 1.9.2

### PR DESCRIPTION
**Pull request by tmat**
This makes it possible to run and debug tests in VS.

Caveats: can't use Theory attribute since it's not available in Xunit 1.9.2

### CODE REVIEW

**Comment by nguerrera** [comment]
Why can't we use xunit 2.0?

**Comment by tmat** [comment]
I guess we could. Roslyn is using 1.9.2 not sure why.

**Comment by nguerrera** [comment]
Looks OK to me. Waiting on CI.

**Comment by akoeplinger** [comment]
> Caveats: can't use Theory attribute since it's not available in Xunit 1.9.2

This feature was available through the xunit extensions package in 1.x.

Apart from that, the new project doesn't follow the other corefx project conventions (packages.config instead of project.json, hardcoding the snk, importing Microsoft.CodeSharing.* targets that aren't yet available on other platforms afaik). Is that expected or just a temporary thing?

**Comment by tmat** [comment]
@akoeplinger  This is expected and temporary until it is possible to run and debug Core CLR targeted tests properly from VS.

**Comment by tmat** [comment]
The issues with running tests from VS are tracked by https://github.com/dotnet/corefx/issues/1597.

**Pull request merged**
