### PR TITLE
Enable some threading overlapped tests on Unix

### PR DESCRIPTION
**Pull request by kouvel**
- Port of https://github.com/dotnet/corefx/pull/19782
- Depends on https://github.com/dotnet/coreclr/pull/11616
- Tests for and closes https://github.com/dotnet/corefx/issues/19785

### CODE REVIEW

**Comment by kouvel** [comment]
This is a port to the release/2.0.0 branch.

@alexperovich @stephentoub

**Comment by stephentoub** [comment]
I don't think we need this; I believe all of master should be going to 2.0 soon now that the preview has shipped.  @danmosemsft, @karelz, is that correct?

**Comment by karelz** [comment]
That's correct. We should integrate into rel/2.0.0 today.

**Comment by kouvel** [comment]
I understood that master is locked down until the integration into release/2.0.0 is completed. So wouldn't this (and mainly https://github.com/dotnet/corefx/pull/19786) need to be merged into release/2.0.0 separately after that point?

**Comment by karelz** [comment]
master is not fully locked down, we just delay high-risk non-essential PRs - see https://github.com/dotnet/corefx/issues/17619#issuecomment-296872132 and https://github.com/dotnet/corefx/issues/17619#issuecomment-300012102

It was also communicated in my regular internal emails about .NET Core 2.0 ;-)

**Comment by kouvel** [comment]
Ok sounds good. The tests can't be merged into master in time because they will need updated packages. I'll update this PR and the original PR on master after the integration and updated packages.

**Comment by stephentoub** [comment]
I merged #19782.  Since I don't believe we've forked for 2.0 yet, I believe that means this PR is no longer needed.

**Comment by kouvel** [comment]
Yes it looks like it hasn't forked yet, thanks!

**Pull request closed without merging**
