### PR TITLE
Update windows-instructions.md for Debug or Release

### PR DESCRIPTION
**Pull request by hughbe**
I had a hard time figuring out the command to run some tests in Release, so I updated the docs to show the method

### CODE REVIEW

**Comment by JonHanna** [comment]
Some have to be release builds for particular platforms only (I don't know which).

**Comment by hughbe** [comment]
@JonHanna that seems like a strange restriction on these libraries - any ideas why?

**Comment by JonHanna** [comment]
No, but I also think I might have it wrong as I was thinking of `Configuration` rather than `ConfigurationGroup`. Precisely what we need these docs for :smile:

**Comment by hughbe** [comment]
> Precisely what we need these docs for

Good to know I helped there! ;)

**Comment by ianhays** [comment]
The Configuration/ConfigurationGroup thing confused me for a while; this looks like a good addition. It also reminded me I need to update the instructions for running Outerloop since you can now do ```/p:Outerloop=true``` to run the outerloop <b>and</b> innerloop tests, whereas ```/p:WithCategories=OuterLoop``` will run only the outerloop tests.

**Comment by stephentoub** [comment]
LGTM

**Comment by hughbe** [comment]
@ianhays if it is not too much effort could you also add a short sentence clarifying the difference between outer loop and Innerloop tests? Thanks

**Comment by ianhays** [comment]
Sure thing @hughbe, good suggestion. Added here: **https://github.com/dotnet/corefx/pull/7549**

**Pull request merged**
