### PR TITLE
Port test case

### PR DESCRIPTION
**Pull request by pgovind**
Port of the test case from https://github.com/dotnet/runtime/pull/46057/

cc @Anipik @safern

### CODE REVIEW

**Comment by pgovind** [comment]
I've forgotten how we used to make coreclr+corefx changes. I think the current CI failures are because coreclr doesn't have the required changes yet and once https://github.com/dotnet/coreclr/pull/28118 is merged, CI should be green

**Comment by danmoseley** [comment]
@pgovind yes, that's right. This CI will fail and when the coreclr change is approved and merged and there's been a build and this repo ingested it, you would rerun this CI then hit merge on this one. 

This means that to test your coreclr change, you'll need to follow the instructions here https://github.com/dotnet/corefx/blob/release/3.1/Documentation/project-docs/developer-guide.md#testing-with-private-coreclr-bits to run the tests in this PR locally against the implementation in your coreclr PR built locally. 

What a pain eh? How did our predecessors live without a merged repo!

**Comment by danmoseley** [comment]
As an alternative you can use "brute force". Run these tests (of course they will fail). go to the folder that the tests are loading the CLR from (it shold be in the console output) and ake the coreclr.dll and System.Private.Corelib.dll you built from your coreclr change into that folder. then run the test and it should pass.

(Both coreclr.dll and System.Private.Corelib.dll as you can't patch one without patching the other)

**Review by GrabYourPitchforks — APPROVED** [review]

**Comment by GrabYourPitchforks** [comment]
The coreclr half of the change was checked in 4 days ago, but it looks like maestro hasn't updated this repo's dependencies yet. Are we waiting for some automated process to kick off, or is this a manual process?

**Comment by Anipik** [comment]
> The coreclr half of the change was checked in 4 days ago, but it looks like maestro hasn't updated this repo's dependencies yet. Are we waiting for some automated process to kick off, or is this a manual process?

the dependency update change is happening on the internal side and its not ported to public side. This pr should be created on the internal side.

**Comment by aik-jahoda** [comment]
Does this one target March release? It is approved by reviewers, but it doesn't have approve label

**Comment by Anipik** [comment]
> Does this one target March release? It is approved by reviewers, but it doesn't have approve label

So this adds the test for the change we shipped last feb. This dont need a label as its test only change. However we should see if you could get it merged by EOD (but not a blocking change)
@pgovind can you make sure the test works.

**Comment by pgovind** [comment]
> can you make sure the test works.

Yup, I'll run this locally today and let you know!

**Comment by pgovind** [comment]
> can you make sure the test works.

Can confirm that this test case passes locally. Ok to merge.

@aik-jahoda @Anipik

**Comment by safern** [comment]
closed and re-open to trigger CI again.

**Comment by Anipik** [comment]
awesome, branch is closed but we can merge it next time

**Review by GrabYourPitchforks — APPROVED** [review]

**Review by Anipik — APPROVED** [review]

**Pull request merged**
