### PR TITLE
RC2: Porting System.Net.Primitives contract change

### PR DESCRIPTION
**Pull request by CIPop**
Porting the fix for #4927 (PR:  #5569)

The code changes also include small fixes for the sln and csproj files that will allow developers to run the tests in Visual Studio (mostly VS generated changes, ensuring that the GUIDs are unique and the SLN matches the csproj information).

@leecow @ellismg PTAL
/cc: @davidsh @stephentoub

### CODE REVIEW

**Comment by CIPop** [comment]
Test Innerloop OSX Debug Build and Test

**Comment by CIPop** [comment]
Test Innerloop OSX Release Build and Test

**Comment by CIPop** [comment]
I can't access the logs for the OSX Debug/Release results: pages don't load:
http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/osx_debug_prtest/214/
http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/osx_release_prtest/215/

**Comment by CIPop** [comment]
CI reports finally loaded: OSX Debug:

```
00:16:53 === TEST EXECUTION SUMMARY ===
00:16:53    System.IO.MemoryMappedFiles.Tests  Total: 342, Errors: 0, Failed: 0, Skipped: 0, Time: 7.944s
00:16:56    DeletedTests.FileSystemWatcher_Deleted_Negative [FAIL]
00:16:56       Should not observe a deleted event within 500ms
00:16:56       Expected: False
00:16:56       Actual:   True
00:16:56       Stack Trace:
00:16:57             at Utility.ExpectNoEvent(WaitHandle eventOccurred, String eventName, Int32 timeout)
00:16:57             at DeletedTests.FileSystemWatcher_Deleted_Negative()
00:16:59 Finished:    System.IO.FileSystem.Tests
00:16:59 
00:16:59 === TEST EXECUTION SUMMARY ===
00:16:59    System.IO.FileSystem.Tests  Total: 2029, Errors: 0, Failed: 0, Skipped: 0, Time: 7.687s
00:17:03 Finished:    System.IO.FileSystem.Watcher.Tests
00:17:03 
00:17:03 === TEST EXECUTION SUMMARY ===
00:17:03    System.IO.FileSystem.Watcher.Tests  Total: 58, Errors: 0, Failed: 1, Skipped: 0, Time: 17.725s
00:17:04 error: One or more tests failed while running tests from 'System.IO.FileSystem.Watcher.Tests'.  Exit code 1.
```

**Comment by CIPop** [comment]
I believe that the other failure is in XDocument although I can't find any report line saying `Errors: 1`.

```
23:53:19    System.Xml.XDocument.TreeManipulation.Tests  Total: 2, Errors: 0, Failed: 0, Skipped: 0, Time: 0.988s
23:53:19 Mismatch : expected: <Root><![CDATA[test ]]]]><![CDATA[> test]]></Root>
23:53:19  actual: <Root><![CDATA[test ]]]]><![CDATA[> test]]></Root>
23:53:19 Mismatch : expected: <Root><!--test - - --></Root>
23:53:19  actual: <Root>
23:53:19   <!--test - - -->
23:53:19 </Root>
23:53:19 Mismatch : expected: <Root><?badpi text ? >?></Root>
23:53:19  actual: <Root>
23:53:19   <?badpi text ? >?>
23:53:19 </Root>
23:53:19 Finished:    System.Xml.XDocument.xNodeBuilder.Tests
```

**Comment by ellismg** [comment]
@dotnet-bot test Innerloop OSX Release Build and Test please

**Pull request merged**
