### PR TITLE
Add Utf8 Decoder fallback test

### PR DESCRIPTION
**Pull request by tarekgh**
This is the test for the fix of the issue #29898 which is fixed in the PR https://github.com/dotnet/coreclr/pull/18387

### CODE REVIEW

**Comment by tarekgh** [comment]
Please don't merge before getting the fix from coreclr.

**Comment by stephentoub** [comment]
> Please don't merge before getting the fix from coreclr.

Presumably it's not mergable until then anyway, as the test will only pass when that updated coreclr arrives?

**Comment by tarekgh** [comment]
> Presumably it's not mergable until then anyway, as the test will only pass when that updated coreclr arrives?

Yes, this test will start to pass after we get the updated coreclr with the fix.

**Comment by tarekgh** [comment]
@dotnet-bot test this please

**Pull request merged**
