### PR TITLE
Move to buildtools 115

### LINKED ISSUE #4227: Code coverage broken on Windows
It appears recent buildtools changes result in a corrupted path while trying to invoke OpenCover, causing code coverage to fail with a "The filename, directory name, or volume label syntax is incorrect." error.

### PR DESCRIPTION
**Pull request by ellismg**
Pick up the fix for how we build the command line to corerun.

Fixes #4227

### CODE REVIEW

**Comment by ellismg** [comment]
/cc @stephentoub 

Verified locally that /p:Coverage=True /t:BuildAndTest runs the Coverage target correctly.

**Comment by weshaggard** [comment]
LGTM

**Comment by stephentoub** [comment]
@dotnet-bot test this please

**Comment by stephentoub** [comment]
Thanks, Matt. LGTM.

**Pull request merged**
