### PR TITLE
https://github.com/dotnet/wcf/issues/1340 - DataContract special-hand…

### PR DESCRIPTION
**Pull request by mlacouture**
Fix for issue#1340 affecting dotnet-svcutil.exe. DC special-handling of KeyValuePair generic type: data contracts for the adapter and the original type do not get the same StableName (contract name).

### CODE REVIEW

**Comment by jasonwilliams200OK** [comment]
:+1: 
Issue URL: dotnet/wcf#1340.

**Comment by mlacouture** [comment]
looked into the debug build/test failures, they seem to be transient (wcf services not available) given that the other tests which access the same services succeed.

**Comment by zhenlan** [comment]
cc: @shmao @mconnew for code review

@mlacouture are there some tests we can add?

**Comment by shmao** [comment]
The changes probably would have conflicts after #10798 got merged. @mlacouture , you may need to rebase the changes onto the latest master.

**Pull request closed without merging**
