### PR TITLE
Fix IPv6 address parsing when last number is too long

### PR DESCRIPTION
**Pull request by stephentoub**
When given an IPv6 address where the last number has more than four digits, rather than failing the parse we end up just using the last four digits.  The last commit fixes that.  The first three commits add a bunch more test cases, fix some duplication, and fix a test issue recently introduced where the IPAddress parsing tests weren't running on netfx.

Fixes https://github.com/dotnet/corefx/issues/23639
cc: @davidsh, @geoffkizer, @joseph-newton

### CODE REVIEW

**Comment by stephentoub** [comment]
@dotnet-bot test OSX x64 Debug Build please ("ERROR: Error fetching remote repo 'origin'", FYI @dotnet/dnceng)

**Comment by stephentoub** [comment]
Thanks for the review, @davidsh.

**Comment by davidsh** [comment]
@stephentoub Are you planning to backport to 2.0.x servicing branch?  Since this broke in 2.0, I think it should be backported.

cc: @karelz

**Comment by stephentoub** [comment]
> I think it should be backported.

I agree.

**Pull request merged**
