### PR TITLE
Fix HttpClientHandler on UAP to use WinRT NoCache enum

### LINKED ISSUE #7877: Use HttpCacheReadBehavior.NoCache on Windows 10
From HttpClientHandler.cs:

``` csharp
            // The .NET Desktop System.Net Http APIs (based on HttpWebRequest/HttpClient) uses no caching by default.
            // To preserve app-compat, we turn off caching (as much as possible) in the WinRT HttpClient APIs.
            // TODO: use RTHttpCacheReadBehavior.NoCache when available in the next version of WinRT HttpClient API.
            this.rtFilter.CacheControl.ReadBehavior = RTHttpCacheReadBehavior.MostRecent; 
            this.rtFilter.CacheControl.WriteBehavior = RTHttpCacheWriteBehavior.NoCache;
```

It looks like `RTHttpCacheReadBehavior.NoCache` is supported on Windows 10; we should consider using it.

### PR DESCRIPTION
**Pull request by davidsh**
Since System.Net.Http APIs default to not using any cache, we need to
turn off caching at the WinRT layer. If supported, we set the
CacheControl.ReadBehavior to use the NoCache enum value. Otherwise,
we use the next best enum option.

Removed some unneeded try/catch handling when we previously
needed to handle compiling with older SDKs and trap JIT errord.
This is no longer needed for NETStandard20.

Fixed some typos from a previous PR.

Fixes #7877

### CODE REVIEW

**Comment by davidsh** [comment]
@mmitche The "Linux x64 Release Build" has been running 11 hours:
https://ci3.dot.net/job/dotnet_corefx/job/master/job/linux-TGroup_netcoreapp+CGroup_Release+AGroup_x64+TestOuter_false_prtest/609/

**Comment by mmitche** [comment]
+@dotnet/dnceng This is another instance.

@davidsh We are having issues with the scale sets right now.  You an see from the blue ocean link that it's just waiting on fedora; https://ci3.dot.net/blue/organizations/jenkins/dotnet_corefx%2Fmaster%2Flinux-TGroup_netcoreapp%2BCGroup_Release%2BAGroup_x64%2BTestOuter_false_prtest/detail/linux-TGroup_netcoreapp%20CGroup_Release%20AGroup_x64%20TestOuter_false_prtest/609/pipeline

Also visibile in the log: https://ci3.dot.net/job/dotnet_corefx/job/master/job/linux-TGroup_netcoreapp+CGroup_Release+AGroup_x64+TestOuter_false_prtest/609/console

**Comment by davidsh** [comment]
@dotnet-bot Test Linux x64 Release Build

**Comment by sunandabalu** [comment]
Fedora queue is redeployed, please retry the blocked/failing build.

**Pull request merged**
