### PR TITLE
[release/2.2] Fix Timer rooting issue with SocketsHttpHandler

### LINKED ISSUE #31262: SocketsHttpHandler roots Timer - leads to higher memory usage
I have just discovered the cause of an annoying memory leak was that one of our libraries what creating a new HttpClient in every request and not disposing it (gaah).  When using WinHttpHandler, the cost was a few hundred managed bytes per HttpClient.  With SocketsHttpHandler, the cost was more like 22KB and some increasingly long TimerQueueTimer chains in HttpConnectionPoolManager (that showed up in the memory snapshot.

I have some suggestions to help detect/minimise such leaks in the future.  I couldn't really come up with anything solid, but hopefully, you can.

1. Do you think it would be possible for the DiagnosticsHandler or some other component to track the number of HttpClients instances and log a warning if the number gets above a certain level?  

2. Instead of creating an Infinite timer (see below), would it be better to just dispose the timer entirely when it isn't in use?  I'm not 100% sure why unreferenced handlers aren't being released from memory but this is probably holding the reference.  _cleaningTimer = new Timer(s => ((HttpConnectionPoolManager)s).RemoveStalePools(), this, Timeout.Infinite, Timeout.Infinite);  (I imagine there is a performance cost to this, but I am not sure how much)
               
3. Would it be ok for HttpMessageInvoker to have a Finalizer that tidies up the HttpMessageHandler (if _disposeHandler is true)?

hopefully, some of that is helpful, but I am not sure there is any proper solution to this other than just having everyone dispose their objects properly (or not create loads of HttpClients to begin with).  thanks ;-)

btw: for testing this my TargetFramework is netcoreapp2.1

### PR DESCRIPTION
**Pull request by stephentoub**
Port #32793 to release/2.2.

Fixes #31262

### CODE REVIEW

**Comment by stephentoub** [comment]
@dotnet-bot test OSX x64 Debug Build please (unrelated collections failure)

**Comment by karelz** [comment]
Approved for 2.2 servicing by shiproom - see details: https://github.com/dotnet/corefx/pull/32804#issuecomment-430354912

**Comment by stephentoub** [comment]
@karelz, do I merge when CI is green, or does someone else handle that?

**Comment by stephentoub** [comment]
@dotnet-bot test OSX x64 Debug Build please (infrastructure failures running unrelated component model tests)

**Comment by karelz** [comment]
I believe you can merge once CI is green. @vivmishra to double-check that 2.2 branch is not in some weird lock down mode.

**Comment by karelz** [comment]
@danmosemsft might also know more about the process here ...

**Comment by danmosemsft** [comment]
Anyone feel free to merge this when it's green. The only reason we don't just tell everyone to merge on athletically is sometimes the branch is closed. Right now it's open.

**Comment by stephentoub** [comment]
@dotnet-bot test OSX x64 Debug Build please (release/2.2 macOS legs seem to be having a lot of trouble getting clean... this one failed because of a connection refused issue in an unrelated HttpListener test)

**Pull request merged**
