### PR TITLE
Do not ignore predefine flags

### PR DESCRIPTION
**Pull request by jyoungyun**
The CMAKE_CXX_FLAGS may have content that comes from outside CMakeLists.
The existing line destroys those settings silently.

Related issue: #17328

### CODE REVIEW

**Comment by jyoungyun** [comment]
@dotnet-bot help

**Comment by jyoungyun** [comment]
@dotnet-bot test innerloop Tizen armel Release
@dotnet-bot test innerloop Ubuntu14.04 arm Debug

**Comment by hqueue** [comment]
Thank you for the fix! It was quite inconvenient when to apply custom options for test.

**Pull request merged**
