### PR TITLE
Make fields readonly in System.IO.MemoryMappedFiles

### PR DESCRIPTION
**Pull request by Maxwe11**

### CODE REVIEW

**Comment by terrajobst** [comment]
@dotnet-bot okay to test

**Comment by mmitche** [comment]
test this please

**Comment by mmitche** [comment]
test this please

**Comment by stephentoub** [comment]
LGTM

**Comment by Maxwe11** [comment]
Fixed in #441 so you are free to close

**Comment by stephentoub** [comment]
Ok, thanks, @Maxwe11.

**Pull request closed without merging**
