### PR TITLE
Synchronize FormatProvider.Number.cs with corert

### PR DESCRIPTION
**Pull request by jkotas**

### CODE REVIEW

**Comment by jkotas** [comment]
The file is identical between this PR and https://github.com/dotnet/corert/pull/2151

**Comment by stephentoub** [comment]
@dotnet-bot test this please

**Comment by jkotas** [comment]
@mellinoe @varocarbas @tsolarin PTLA

**Comment by jkotas** [comment]
@dotnet-bot test this please

**Comment by stephentoub** [comment]
@dotnet-bot test this please (fixed build break)

**Comment by stephentoub** [comment]
@dotnet-bot Test Innerloop CentOS7.1 Debug Build and Test please (error restoring build tools)
@dotnet-bot Test Innerloop CentOS7.1 Release Build and Test please (error restoring build tools)

**Comment by jkotas** [comment]
@dotnet-bot test Innerloop CentOS7.1 Debug Build and Test please
@dotnet-bot test Innerloop CentOS7.1 Release Build and Test please
@dotnet-bot test Linux ARM Emulator SoftFP Debug Cross Build please
@dotnet-bot test Linux ARM Emulator SoftFP Release Cross Build please

**Pull request merged**
