### PR TITLE
Fix path to sni.dll

### PR DESCRIPTION
**Pull request by chcosta**
/cc @ericstj, @weshaggard

### CODE REVIEW

**Comment by ericstj** [comment]
Can we please not put TFS paths in CoreFx source?  I'd expect us to just set the internal override to point to this path.

**Comment by chcosta** [comment]
If we don't set WinNativePath to the root, then we'll need to have two separate variables here...

https://github.com/dotnet/corefx/blob/master/src/Native/pkg/runtime.native.System.IO.Compression/win/runtime.native.System.IO.Compression.pkgproj#L12

https://github.com/dotnet/corefx/blob/master/src/Native/pkg/runtime.native.System.IO.Compression/win/runtime.native.System.IO.Compression.pkgproj#L16

**Comment by ericstj** [comment]
/cc @ianhays maybe we need that anyways.  Right now the compression package would never pick up the native bits built from the open, right?
https://github.com/dotnet/corefx/tree/master/src/Native/Windows/clrcompression

**Comment by weshaggard** [comment]
I agree we should fix the clrcompression package. I just chatted with @ianhays about how to fix it. So I"m going to close this PR.

**Pull request closed without merging**
