### PR TITLE
Fix init-tools.sh

### PR DESCRIPTION
**Pull request by natemcmaster**
Cannot build on linux or osx due to bugs in init-tools.sh

### CODE REVIEW

**Comment by ellismg** [comment]
LGTM.  Thanks for making these fixes.  /cc @joperezr

**Comment by natemcmaster** [comment]
See also https://github.com/dotnet/buildtools/pull/391

**Comment by stephentoub** [comment]
LGTM

**Comment by joperezr** [comment]
Thanks for fixing it Nate!

**Pull request merged**
