### PR TITLE
CoreFx #14486 Remove argument validation in DangerousCreate

### LINKED ISSUE #14486: Span: DangerousCreate should avoid argument validation
For Span/ReadOnlySpan DangerousCreate method, should we remove the following test cases to increase performance:
* SpanTests - DangerousCreateNullObject
* SpanTests - DangerousCreateBadLength
* ReadOnlySpanTests - DangerousCreateNullObject
* ReadOnlySpanTests - DangerousCreateBadLength

It was suggested that the Fast and Slow Span implementations should not do the check/throw on null object or negative lengths to speed up creation of the instance of Span/ReadOnlySpan.

That is, these checks should be removed:
```C#
        public static ReadOnlySpan<T> DangerousCreate(object obj, ref T objectData, int length)
        {
            if (obj == null)
                ThrowHelper.ThrowArgumentNullException(ExceptionArgument.obj);
            if (length < 0)
                ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument.length);
```

Should they be removed?

### PR DESCRIPTION
**Pull request by WinCPP**
Fixes #14486 

@ahsonkhan @karelz Kindly review.

### CODE REVIEW

**Comment by WinCPP** [comment]
For the failing check "Innerloop OSX10.12 Debug x64", following errors appear to be unrelated to the code change. Is this known issue? Kindly advise what I should do. Thanks!

```
13:49:17 /Users/dotnet-bot/j/workspace/dotnet_corefx/master/osx10.12_debug_prtest/src/Native/Unix/System.Security.Cryptography.Native.Apple/pal_keychain.cpp:253:117: error: null passed to a callee that requires a non-null argument [-Werror,-Wnonnull]
13:49:17             SecKeychainItemCreateCopy(reinterpret_cast<SecKeychainItemRef>(privateKey), keychain, nullptr, &itemCopy);
13:49:17                                                                                                   ~~~~~~~           ^
13:49:17 /Users/dotnet-bot/j/workspace/dotnet_corefx/master/osx10.12_debug_prtest/src/Native/Unix/System.Security.Cryptography.Native.Apple/pal_keychain.cpp:272:116: error: null passed to a callee that requires a non-null argument [-Werror,-Wnonnull]
13:49:17         status = SecKeychainItemCreateCopy(reinterpret_cast<SecKeychainItemRef>(cert), keychain, nullptr, &itemCopy);
13:49:17                                                                                                  ~~~~~~~           ^
13:49:17 2 errors generated.
```

**Comment by ahsonkhan** [comment]
> Kindly advise what I should do. Thanks!

The CI is flaky and the failure seems unrelated.
Just re-run the failing test.

@dotnet-bot test Innerloop OSX10.12 Debug x64 Build and Test please

**Comment by ahsonkhan** [comment]
LGTM.

@jkotas, thoughts? Should we make a similar change in coreclr? 
https://github.com/dotnet/coreclr/blob/master/src/mscorlib/src/System/Span.cs#L147
https://github.com/dotnet/coreclr/blob/master/src/mscorlib/src/System/ReadOnlySpan.cs#L130

**Comment by shiftylogic** [comment]
@dotnet-bot test Innerloop OSX10.12 Debug x64 Build and Test

**Comment by ahsonkhan** [comment]
@WinCPP, maybe explicitly add to the xml comments that we don't do null checks on the object or bound checks on the length.

**Comment by ahsonkhan** [comment]
Fixes part of #1314

**Pull request merged**
