### PR TITLE
Expose RegexRunner in System.Text.RegularExpressions contract.

### PR DESCRIPTION
**Pull request by Priya91**
pending API Review.

#5079 

cc @weshaggard @mjsabby

### CODE REVIEW

**Comment by justinvp** [comment]
Exposing `RegexRunner` alone will not address #340.

There are really two issues:
 1. Support `RegexOptions.Compiled` option (which would compile the regex internally using something like ref emit, if available)
 2. Support precompiled `Regex`s

This change will mostly help with 2, but additional changes to `Regex` are required, such as allowing subclasses to specify the regex runner factory, and exposing some `Regex` fields as protected and changing their types back to the legacy Hashtable from Dictionary to match the desktop framework so they can be set by subclasses. Or alternatively, adding a new protected constructor that is a better design and does not depend on the legacy collections. See [comment](https://github.com/dotnet/corefx/issues/340#issuecomment-68611925) for details.

**Comment by mjsabby** [comment]
@Priya91 Thanks for sending this out!

The Regex class needs the following TypeRef's to be exposed

pattern
roptions
internalMatchTimeout
factory
caps
capnames
capslist
capsize
InitializeReferences
ValidateMatchTimeout

The factory field refers to the System.Text.RegularExpressions.RegexRunnerFactory, which we can add back:

   abstract public class RegexRunnerFactory {
        protected RegexRunnerFactory() {}
        abstract protected internal RegexRunner CreateInstance();
    }

capnames and caps are Hashtables but this is where I think it's ok to break compability, otherwise we'll be bringing in the NonGeneric mess into System.Text.RegularExpressions

So the tooling advice here can be in addition to changing AssemblyRef's, you also need to change the TypeRef's from Hashtable to Dictionary<string, int> (capnames) and Dictionary<int, int> (caps)

I will admit that the suggested protected constructor option is a better design. However, making tooling that has to change the odd AssemblyRef's and those two pesky TypeRef's is much easier than changing the generated code more significantly.

Furthermore, I am not actually opposed to adding a protected constructor in addition to doing the work of exposing the missing protected fields/methods.

**Comment by justinvp** [comment]
If we go with the protected constructor design, we wouldn't have to expose those fields or methods on `Regex`, and wouldn't have to deal with the non-generic collection dependency mess, nor would we have to expose `RegexRunnerFactory` as the protected constructor could have a parameter that takes `Func<RegexRunner>`. Changing the tooling to call a protected constructor vs. set those fields and call those methods wouldn't be that much more work, IMO. If there is a cost/resource issue related to updating the tooling within Microsoft, I'd be happy to help with the tooling implementation.

**Comment by Priya91** [comment]
@justinvp @mjsabby Yes we need to expose other types and internal fields to make the compiled regex work with .net core. I'll be putting a proposal soon in this PR. This PR will be a work in progress till then. Thanks for the feedback.

**Comment by stephentoub** [comment]
> This PR will be a work in progress till then

In general I believe our process is that we don't open PRs until the associated API reviews have been completed.  I'm going to close this until then, at which point it can be re-opened. Thanks.

**Pull request closed without merging**
