### PR TITLE
Fix DiagnosticListener stress test

### PR DESCRIPTION
**Pull request by stephentoub**
The stress test has a variety of problems with it.  For example, it's sharing the same `list` of active listeners across all threads by accidentally capturing it into the lambda that's used with all threads, it's accidentally capturing the `i` variable that changes based on loop iteration and thus is often going to be viewed as the same value for all of the threads, etc.  These cause failures as multiple threads are mutating non-thread-safe types and as state is being read inconsistently.  I've cleaned up the test.

Fixes https://github.com/dotnet/corefx/issues/6872
cc: @vancem

### CODE REVIEW

**Comment by stephentoub** [comment]
@dotnet-bot test Outerloop Windows_NT Debug please

**Comment by stephentoub** [comment]
@dotnet-bot test OuterLoop Windows_NT Debug x64 please (https://github.com/dotnet/corefx/issues/16981)

**Comment by stephentoub** [comment]
@dotnet-bot test OuterLoop Windows_NT Debug x64 please (#16981)

**Comment by stephentoub** [comment]
@dotnet-bot test OuterLoop Windows_NT Debug x64 please (#16981, and I've disabled the offending test)

**Comment by vancem** [comment]
First, thanks for looking into this.

> However, iteration of subscribed listeners happens outside of the lock

I actually don't see this.   From what I can tell all uses of s_allListeners and the _next field are under the s_lock.   (what am I missing?)  The only place we iterate is in ALlListenerObservable.Subscribe and that is clearly under a lock.

I agree that nulling out the _next field is not necessary, but if there is a race associated with that statement, there is probably also a race with the cur._next = _next statement a few lines above, so I want to figure out if we really have a problem nor not.

Is it possible it was just that StressTest was bad?

**Comment by stephentoub** [comment]
> From what I can tell all uses of s_allListeners and the _next field are under the s_lock

Hmm.  I swear I saw iteration happening without the lock, but I agree, from the source, there doesn't appear to be any way that could happen.  So I was wrong about that being part of the cause. and it was just all of the inappropriately-shared-state in the test.

> but if there is a race associated with that statement, there is probably also a race with the cur._next = _next statement a few lines above

I thought about that, but I didn't think it would be problematic.  The problem which could occur if we null out _next is that code which already has a reference to the node would then stop iterating the rest of the list that is still there.  With updating cur._next to be _next, if someone already had a reference to the node, the worst that might happen is someone could iterate through a node that's concurrently/already been removed; at least for this particular test, that wouldn't have caused problems... but maybe it could violate some other assumptions. Regardless, you appear to be right that we're never iterating without the lock, so that's moot.

**Pull request merged**
