### PR TITLE
Update StringBuilder.AppendJoin to approved API

### LINKED ISSUE #3419: StringBuilder.AppendJoin (appending lists to StringBuilder)
#### Background

Let's say you want to build a string that contains a separated list (e.g. list of filenames, messages, or anything else).

If it is the only thing you want, you can use `string.Join`. However what if you want to append something else? If you `Concat` with the result of `string.Join`, that means that you unnecessarily allocated an intermediate joined string, which can be rather large (depending on the original collection).

On the other hand, `StringBuilder` would require something like:

``` csharp
var builder = new StringBuilder("Names: ");
for (var i = 0; i < names.Length; i++) {
    if (i > 0) { // this becomes even more involved if `names` is `IEnumerable`
        builder.Append(", ");
    }
    builder.Append(names[i]);
}
```

That can be abstracted into an extension method, however I believe that extension would be general and useful enough to benefit from being in NetFX.
#### API Design

(updated based on API review, second pass -- see https://github.com/dotnet/corefx/issues/3419#issuecomment-273254581)

``` csharp
public class StringBuilder {
    public StringBuilder AppendJoin(string separator, params object[] values);
    public StringBuilder AppendJoin<T>(string separator, IEnumerable<T> values);
    public StringBuilder AppendJoin(string separator, params string[] value);

    public StringBuilder AppendJoin(chat separator, params object[] values);
    public StringBuilder AppendJoin<T>(char separator, IEnumerable<T> values);
    public StringBuilder AppendJoin(char separator, params string[] value);

    // string.Join overloads NOT taken:
    //public StringBuilder AppendJoin(string separator, IEnumerable<string> values);
    //public StringBuilder AppendJoin(string separator, string[] values, int startIndex, int count);
    //public StringBuilder AppendJoin(char separator, IEnumerable<string> values);
    //public StringBuilder AppendJoin(char separator, string[] values, int startIndex, int count);
    // REJECTED in the first API review round:
    //public StringBuilder AppendJoin<T>(string separator, T[] values, int startIndex, int count);
    //public StringBuilder AppendJoin<T>(string separator, params T[] values);
    //public StringBuilder AppendJoin<T>(char separator, params T[] values);
}
```

Note: Motivation for the API approval update is described in https://github.com/dotnet/corefx/issues/3419#issuecomment-273254581 -- adjusting to follow proven working form of 'string.Join', correctly working with most-used overload calls - see usage example in https://github.com/dotnet/corefx/issues/5552#issuecomment-268395367.

#### Compatibility

Potential source-level issue if someone is already using an extension method with the same name.

### PR DESCRIPTION
**Pull request by jnm2**
Closes #3419

Dependent on https://github.com/dotnet/coreclr/pull/11059

I aimed to cover every code path.

### CODE REVIEW

**Comment by hughbe** [comment]
Thanks for doing this. Can we add the following tests?
- empty string in values
- object.ToString throws
- object.ToString returns null

**Comment by jnm2** [comment]
Sure. I don't understand why you'd test throwing from ToString and not GetEnumerator, MoveNext, Current and Dispose. That's a lot of test double overhead for an unlikely circumstance where StringBuilders would somehow interact at all with exceptions in user code.

**Comment by hughbe** [comment]
I just remember seeing a similar test in the test suite for other APIs. Also there was some discussion a while ago about stringbuilder becoming corrupted if such an exception is thrown (I know this is a string API but might be worth it)

**Comment by hughbe** [comment]
Oh, and a test for An ArgumentException thrown when we exceed the capacity of the stringbuilder (there are some similar tests in the test suite that you can look at) would be nice.

**Comment by danmosemsft** [comment]
Waiting on CoreCLR.

**Comment by danmosemsft** [comment]
@dotnet-bot test this please

**Comment by jnm2** [comment]
I'll look at how to effectively test exceptions and capacity tomorrow.

**Comment by danmosemsft** [comment]
To fix build, updated baselines for uap, and conditionalized tests for netcoreapp. Also rebased on master to pick up the CLR change.
@jnm2 to rebase I had to force push, so please stash and pull before working further.

**Comment by danmosemsft** [comment]
@jnm2 I'll merge as soon as you add whichever of @hughbe 's suggested tests that you believe are worthwhile.

Just kicking this along since I want to get it in 2.0. :)

**Comment by jnm2** [comment]
@danmosemsft I'm having problems building corefx after removing the env variable `CoreCLROverridePath` and restarting. I'll start a fresh clone.

**Comment by jnm2** [comment]
@danmosemsft @hughbe I'm going to pass on the throwing-`.ToString()` tests unless you have strong objections, for the original [reasons](https://github.com/dotnet/corefx/pull/18699#issuecomment-296009783) and also because I can't come up with a good theory of what such a worthwhile test would check for. There don't seem to be any other tests that do this.

If you're okay with that, I think the PR is ready.

**Comment by hughbe** [comment]
Sure, thanks!

**Comment by danmosemsft** [comment]
@jnm2 
>I'm having problems building corefx after removing the env variable CoreCLROverridePath and restarting. I'll start a fresh clone.

When picking up a new CLR (which is what pulling did) or other meta-stuff I sometimes get wiered errors and clean and build seems inevitable. BAsically the build isn't incremental in that situation.

**Comment by danmosemsft** [comment]
Thanks @jnm2 now you own some methods on StringBuilder! ;)

If you want to continue, there are of course many other 2.0 issues:
https://github.com/dotnet/corefx/issues?q=is%3Aopen+is%3Aissue+milestone%3A2.0.0
https://github.com/dotnet/corefx/issues?q=is%3Aopen+is%3Aissue+milestone%3A2.0.0+label%3Aup-for-grabs

We are also still taking non 2.0 changes into master as long as they are acceptable risk and don't add new API.

**Comment by jnm2** [comment]
@danmosemsft I'd like to get https://github.com/dotnet/corefx/issues/17917#issuecomment-296070878 and https://github.com/dotnet/corefx/issues/17917#issuecomment-296170409 sorted or `GetValueOrDefault` will be a pain in 2.0.

**Pull request merged**
