### PR TITLE
Use RuntimeInformation across corefx for platform detection

### PR DESCRIPTION
**Pull request by stephentoub**
This commit deletes our temporary Interop.PlatformDetection.cs mechanism and replaces usage of it with usage of System.Runtime.InteropServices.RuntimeInformation.dll.

### CODE REVIEW

**Comment by stephentoub** [comment]
cc: @Priya91, @ellismg 

@ianhays, there was one usage of Interop.IsLinux in a FileSystem tests file that appeared to be stale (it wasn't included in the .csproj, and it was still following the old style).  I've deleted it as part of this change; please let me know if that's not the right answer.

**Comment by bartonjs** [comment]
LGTM

**Comment by ianhays** [comment]
LGTM!

@stephentoub FileInfo/Create_str.cs can be safely removed. I renamed it to Create.cs and I suppose the deletion didn't get committed along with the addition.

**Comment by Priya91** [comment]
LGTM

**Comment by stephentoub** [comment]
Thanks, all.

**Pull request merged**
