### PR TITLE
Refactor System.Linq

### LINKED ISSUE #1149: Refactor System.Linq
Following @stephentoub comment here:

https://github.com/dotnet/corefx/issues/1143#issuecomment-81683842

I am filing this issue to track doing some refactoring in System.Linq. Currently, everything is in one file which has about 3.2k lines and around 20 classes and interfaces. It is good if this can be refactored to make the code easier to follow.

### PR DESCRIPTION
**Pull request by JonHanna**
Move classes into separate files.

Split Enumerable among several files.

Remove redundant references to generic types or namespaces.

Fixes #1149

@stephentoub since you suggested to @VSadov that splitting this file might be useful at https://github.com/dotnet/corefx/pull/5820#discussion_r52452253

### CODE REVIEW

**Comment by JonHanna** [comment]
The changes to Enumerable.cs are hard to see through github, which is ironic since part of the point is to make extensive changes to Linq easier to see. However, its remnants are so small that viewing the entire file makes it quickly clear what's been done.

**Comment by JonHanna** [comment]
Test  Innerloop OSX Release Build and Test

**Comment by VSadov** [comment]
LGTM 
I think the granularity is reasonable. At first I thought - "OMG, 43 files?"   :-)

**Comment by JonHanna** [comment]
Yeah, I'd made a stab at doing this a couple of months ago and gave up when I was thinking "OMG, over 20 files and I'm nowhere near through it and it's not really necessary", but 5000+ lines is not good. I've already spotted where I missed something that should have been obvious due to that size.

**Comment by rstm** [comment]
to much diif dude

**Comment by JonHanna** [comment]
Test Innerloop OSX Debug Build and Test
Test Innerloop OpenSUSE13.2 Debug Build and Test

**Comment by JonHanna** [comment]
Test Innerloop OSX Debug Build and Test
Test Innerloop OpenSUSE13.2 Debug Build and Test

**Comment by stephentoub** [comment]
I pulled this down locally and diff'd each file against the original Enumerable.cs.

LGTM

**Pull request merged**
