### PR TITLE
Downgrade CLI version to 2.1.401-preview-009081.

### PR DESCRIPTION
**Pull request by eerhardt**
We temporarily needed to bump the CLI version to 3.0 builds because of https://github.com/dotnet/core-setup/issues/4291. But now that we have a 2.1 servicing build with this change, we can downgrade to that build.

### CODE REVIEW

**Comment by eerhardt** [comment]
I just took the version that came from https://github.com/dotnet/versions/tree/master/build-info/dotnet/product/cli/release/2.1#built-repositories

/cc @mmitche @nguerrera - can you confirm that the `2.1.3` runtime release will go with the `2.1.401` SDK?

**Comment by eerhardt** [comment]
test UWP NETNative x86 Release Build

build failure was:

```
MSBUILD : error MSB4166: Child node "3" exited prematurely. Shutting down. Diagnostic information may be found in files in "C:\Users\dotnet-bot\AppData\Local\Temp\" and will be named MSBuild_*.failure.txt. This location can be changed by setting the MSBUILDDEBUGPATH environment variable to a different directory.
```

**Comment by mmitche** [comment]
@eerhardt Yes that is the case.

**Comment by eerhardt** [comment]
@weshaggard - are you OK with me merging this?

/cc @ViktorHofer - FYI this is downgrading our CLI version to the `2.1` servicing nightly build.  When `2.1.3` ships, we can make this the stable version.

**Comment by ViktorHofer** [comment]
@eerhardt as 2.1.401 is now stable, you probably want to update the version.

**Pull request merged**
