### PR TITLE
System.Net.Mail.SmtpClient - make ClientDomain public proposal.

### PR DESCRIPTION
**Pull request by prostakov**

### CODE REVIEW

**Comment by davidsh** [comment]
cc: @karelz  - This is a public API change.  The API change process needs to be followed.

**Comment by prostakov** [comment]
Maybe someone could please explain why this property was hidden and made internal in the first place? Is there maybe some way around it?

**Comment by filipnavara** [comment]
I think you are asking a wrong question. Why would the property not be internal? What are the use cases for overriding the default value? Are you concerned that the host name is leaked?

This API comes from full .Net Framework and it handles only simple use cases and is not generally recommended anymore. While there may be good reasons to extend it you may also consider using 3rd-party libraries such as MailKit, which are recommended replacement.

I checked the code and I found it a bit unusual that it doesn't fallback to the "[xxx.xxx.xxx.xxx]" IP address based syntax and instead relies on tricks to strip non-ASCII characters, but that's for another discussion.

**Comment by prostakov** [comment]
I'm already testing MailKit. Thank you. I will close this PR.

**Pull request closed without merging**
