### PR TITLE
Move routing and failover message ONLY for Login Timeout Error

### PR DESCRIPTION
**Pull request by kkurni**
During Timeout this routing and failover message always included in the error message even if it is not "Login Timeout error"
This was caused confusion as this Routing and Failover message was specifically detailed for Login Timeout.

Changes :
     Fix the condition to include the failover and routing message ONLY in "Login Timeout"

### CODE REVIEW

**Comment by kkurni** [comment]
CC @corivera @saurabh500 @nadiatk

**Comment by saurabh500** [comment]
LGTM

**Comment by kkurni** [comment]
@dotnet-bot 
Test Innerloop OSX Debug Build and Test please

**Comment by stephentoub** [comment]
Test Innerloop OSX Debug Build and Test please

**Pull request merged**
