### PR TITLE
add task support to servicebase

### PR DESCRIPTION
**Pull request by SimonCropp**
This is a breaking change and would require a v5 of the System.ServiceProcess.ServiceController  nuget  to be released. please let me know if u want me to attempt to make it backwards compat so as to not require a v5. my preference would be to go with breaking change and keep the codebase and API simpler as a result.

### CODE REVIEW

**Comment by stephentoub** [comment]
> please let me know if u want me to attempt to make it backwards compat

Yes, it cannot be a breaking change. Please propose new APIs as an issue that can be discussed. Thanks for the interest.

**Comment by SimonCropp** [comment]
prob remove this from the milestone?

**Comment by karelz** [comment]
@SimonCropp the milestone was right, the PR was closed in 2.1 timeframe.

**Comment by SimonCropp** [comment]
Closed. Not merged

**Pull request closed without merging**
