### PR TITLE
Remove old Nano testing

### PR DESCRIPTION
**Pull request by mmitche**
Removes old nano testing, in favor of new pipelines
(@dotnet-bot test portable windows debug pipeline)
(@dotnet-bot test portable windows release pipeline)

### CODE REVIEW

**Comment by mmitche** [comment]
@dotnet-bot test ci please

**Comment by mmitche** [comment]
@dotnet-bot help

**Comment by karelz** [comment]
@mmitche do we need to make similar change in rel/2.0.0 branch?

**Comment by mmitche** [comment]
@karelz Yes please  This change can just be cherry-picked.

**Comment by karelz** [comment]
Great, can you please file a bug and submit shiproom request for the port?
Infra/test-only things are still "Tell mode"

**Pull request merged**
