### PR TITLE
Clear SSL error queue after MultiDestroy and MultiRemoveHandle

### PR DESCRIPTION
**Pull request by pjanotti**
Part 3 of separating PR #28862: Clear SSL error queue after MultiDestroy and MultiRemoveHandle (CurlHandler).

These methods wrap calls to SSL_shutdown that can leave unwanted errors on the SSL error queue. 

There is no return to indicate if an error happened, so whenever MultiDestroy and MultiRemoveHandle are called a corresponding call to ErrClearError was added.

### CODE REVIEW

**Comment by pjanotti** [comment]
@dotnet-bot test Outerloop Linux x64 Release Build
@dotnet-bot test Outerloop Linux x64 Debug Build

Failures on System.Net.Http.Functional.Tests.PlatformHandler_HttpClientHandler_ServerCertificates_Test/NoCallback_RevokedCertificate_NoRevocationChecking_Succeeds looking...

**Comment by pjanotti** [comment]
Failure ProcessStart_OpenFileOnLinux_UsesSpecifiedProgram(programToOpenWith: \"nano\") not related.

**Comment by pjanotti** [comment]
@karelz @stephentoub I have to go offline, but, everything seems correct here, I am going take a leap and merge it.

**Comment by karelz** [comment]
Thanks @pjanotti!

**Pull request merged**
