### PR TITLE
Add tests for Regex collections throwing IndexOutOfRangeExceptions in their CopyTo implementations

### PR DESCRIPTION
**Pull request by hughbe**
- We don't support non-zero lower bounds
- We don't support multidimensional arrays
- We don't support invalid index

/cc @Priya91 @stephentoub

### CODE REVIEW

**Comment by danmosemsft** [comment]
Does this change the types of any exceptions previously thrown? If so, that could break existing code (which works fine on desktop). I'm not sure how strict a compat line we're holding to here.

**Comment by hughbe** [comment]
Aye it does, but the implementation has a bug in that it doesn't validate params. I'm not sure about the likelihood of this getting merged tbh, as #8548 was rejected. On the one hand, this is a bigger issue (in that the mentioned PR only checks GetLowerBound) but on the other hand, this means compat is broken more. I wouldn't hold my breath on this getting merged!

**Comment by danmosemsft** [comment]
I think these are the relevant documents below.

[Breaking change rules](https://github.com/dotnet/corefx/blob/master/Documentation/coding-guidelines/breaking-change-rules.md)
[Breaking changes](https://github.com/dotnet/corefx/blob/master/Documentation/coding-guidelines/breaking-changes.md)

Post 1.0, we're going to be particularly interested in making it easier to port code from other .NET distributions (such as Xamarin apps) and as such I'd imagine we might be stricter if anything.

**Comment by hughbe** [comment]
Yeah I've read the breaking change rules - just throwing this out there in case we want to fix this - a similar PR of mine was merged earlier

**Comment by danmosemsft** [comment]
Ah, OK. What was the similar PR? (Just for my education)

**Comment by hughbe** [comment]
#8065

**Comment by hughbe** [comment]
I'm gonna change this PR into a test-only PR, and revert my product changes. As we reach the 1.0 (RTM) deadline, I don't want to waste your time with compat reviews, and I'm almost certain at this point the changes aren't feasible. Maybe for 1.1.

**Comment by hughbe** [comment]
Tests Innerloop CentOS7.1 Debug Build and Test
Tests Innerloop OSX Debug Build and Test

**Comment by hughbe** [comment]
Tests Innerloop CentOS7.1 Debug Build and Test
Tests Innerloop OSX Debug Build and Test

**Comment by hughbe** [comment]
Test Innerloop CentOS7.1 Debug Build and Test
Test Innerloop OSX Debug Build and Test

**Comment by stephentoub** [comment]
LGTM.  Thanks, @hughbe.

**Pull request merged**
