### PR TITLE
Moving StopWatch to `src\Common\src\Corelib`

### PR DESCRIPTION
**Pull request by VSadov**
This is the first step of the following plan to move StopWatch to corlib.

- [x] PR in corefx to move Stopwatch to src\Common\src\Corelib.
- [x] Wait for mirror bot to open PR to bring changes to coreclr.
- [x] Update Corelib to include Stopwatch.
- [x] Wait for bot to open PR in corefx bringing updated build of corelib with Stopwatch
- [x] Add a commit to that PR which removes Stopwatch.*.cs from System.Runtime.Extensions build.

See motivation and discussion in: https://github.com/dotnet/coreclr/pull/27175

### CODE REVIEW

**Comment by VSadov** [comment]
CC: @stephentoub , @jkotas

**Review by stephentoub — APPROVED** [review]

**Comment by VSadov** [comment]
@stephentoub - how soon after the merge should I expect the mirror bot changes?

**Comment by stephentoub** [comment]
Assuming the tool is up and running (which can be a large assumption unfortunately), almost immediately.  If it doesn't show up within a few hours, you can ping @Anipik or @safern and one of them should hopefully be able to help get it unstuck.

**Review by jkotas — APPROVED** [review]

**Comment by safern** [comment]
It was up and running today, as soon as this is merged I’ll make sure it is mirrored.

**Comment by VSadov** [comment]
https://github.com/dotnet/coreclr/pull/27410

**Comment by safern** [comment]
>Assuming the tool is up and running (which can be a large assumption unfortunately)

LOL, lately it was down a lot of times because there was a handle to a file that was preventing the mirror from reseting branches or checking out new ones. I fixed that yesterday as found out that was the issue and apparently it has been running for 24hrs straight now 😄 -- please let me know if for some reason it misses any other commit.

**Comment by VSadov** [comment]
@safern - the bot that mirrors the other way (from clr to FX) seems to be delayed. Not sure if that is the same bot...

**Comment by safern** [comment]
Yes it is the same bot. There was a merge conflict in some of the changes that went into corert -> corefx, I'm fixing those. Should be unblocked soon.

**Comment by VSadov** [comment]
@safern - Thanks!  I think this is the PR that I am waiting for: https://github.com/dotnet/corefx/pull/42121

**Comment by VSadov** [comment]
I will deal with Stopwatch in https://github.com/dotnet/corefx/pull/42121

**Comment by VSadov** [comment]
I have pushed a commit that removes StopWatch from System.Runtime.Extensions build

**Pull request merged**
