### PR TITLE
Add GetSystemTimeAsTicks to System.Native

### PR DESCRIPTION
**Pull request by alexperovich**
This is needed by coreclr and corert for DateTime UtcNow

### CODE REVIEW

**Comment by stephentoub** [comment]
coreclr's implementation was recently updated in order to improve precision/accuracy:
https://github.com/dotnet/coreclr/pull/9736
We should not regress that.

**Comment by stephentoub** [comment]
The coreclr implementation uses clock_gettime(CLOCK_REALTIME) for UtcNow:
https://github.com/dotnet/coreclr/blob/3fe022eb723479d0b7acf17856e76a1973668ca6/src/pal/src/file/filetime.cpp#L513
It can provide a more precise/accurate result when available.

**Comment by alexperovich** [comment]
> The coreclr implementation was recently updated to use clock_gettime(CLOCK_REALTIME) for UtcNow:
> dotnet/coreclr#9772
> We should avoid regressing that.

I will add this, where is the bit in the CMake goo that makes HAVE_WORKING_CLOCK_GETTIME work?

**Comment by stephentoub** [comment]
Thanks.
https://github.com/dotnet/coreclr/blob/6ee7c2074cb6e9be0425af981c08593fd505f723/src/pal/src/config.h.in#L92
https://github.com/dotnet/coreclr/blob/72c57d9d9fd2d4cd8c96f124d132d316c8ef6013/src/pal/src/configure.cmake#L385-L392

**Comment by stephentoub** [comment]
We also have something similar (but not the same) in CoreFx already that you can basically copy and modify:
https://github.com/dotnet/corefx/blob/8f671cbbe8a79a3c755fe91579fb273e11e97376/src/Native/Unix/configure.cmake#L340

**Comment by alexperovich** [comment]
OSX failing with #17487 

@dotnet-bot test Innerloop OSX10.12 Debug x64 Build and Test please

**Pull request merged**
