### PR TITLE
Correcting OdbcIsAvailable condition check for windows

### LINKED ISSUE #24630: Test: System.Data.Odbc.Tests.DependencyCheckTest/OdbcConnection_OpenWhenOdbcNotInstalled_ThrowsException failed with "Xunit.Sdk.ThrowsException"
Opened on behalf of @Jiayili1

The test `System.Data.Odbc.Tests.DependencyCheckTest/OdbcConnection_OpenWhenOdbcNotInstalled_ThrowsException` has failed.

Assert.Throws() Failure\r
    Expected: typeof(System.DllNotFoundException)\r
    Actual:   (No exception was thrown)

        Stack Trace:

           at System.Data.Odbc.Tests.DependencyCheckTest.OdbcConnection_OpenWhenOdbcNotInstalled_ThrowsException()
Build : Master - 20171013.01 (Core Tests)
Failing configurations:
- Windows.10.Amd64.Core-x86
  - Release
- Windows.10.Amd64.Core-x64
  - Release

Detail: https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Fcli~2F/build/20171013.01/workItem/System.Data.Odbc.Tests/analysis/xunit/System.Data.Odbc.Tests.DependencyCheckTest~2FOdbcConnection_OpenWhenOdbcNotInstalled_ThrowsException

### PR DESCRIPTION
**Pull request by maryamariyan**
Fixes #24630

cc: @danmosemsft

### CODE REVIEW

**Comment by maryamariyan** [comment]
@danmosemsft  I suspect this would failed for Windows.10.Amd64.Core-x64-Release

Reference:
https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Fcli~2F/build/20171013.01/workItem/System.Data.Odbc.Tests/analysis/xunit/System.Data.Odbc.Tests.DependencyCheckTest~2FOdbcConnection_OpenWhenOdbcNotInstalled_ThrowsException

**Comment by danmosemsft** [comment]
@maryamariyan interesting, that means that they install odbc32.dll only for 64 bit processes on that SKU. OK, then you can tweak your condition -- 

```c#
PlatformDetection.IsNotWindowsNanoServer && 
(PlatformDetection.IsNotWindowsServerCore || Environment.Is64BitProcess ) // Installed on Server Core only for 64 bit
```

It might make sense to break this condition up into bits.

Incidentally note that the "IsNot" makes this condition harder to read. In general avoid any "negated" boolean identifiers. eg 

```c#
!PlatformDetection.IsWindowsNanoServer && 
(!PlatformDetection.IsWindowsServerCore || Environment.Is64BitProcess ) // Installed on Server Core only for 64 bit
```

**Comment by danmosemsft** [comment]
BTW, the reason we have PlatformDetection.IsNotXXXX (despite my preference above against negated) is because there is no way to have a `!` operator in an attribute value like `[ConditionalFact(typeof(PlatformDetection), nameof(PlatformDetection.IsNotWindowsServerCore))]`

**Comment by maryamariyan** [comment]
@dotnet-bot test OSX x64 Debug Build please (test hung)

**Comment by maryamariyan** [comment]
@dotnet/dnceng can you please help troubleshoot why OSX x64 Debug build is hung?

The last line in jenkins console output is:
"Still waiting to schedule task
All nodes of label ‘osx-10.12||OSX.1012.Amd64.Open’ are offline "

**Comment by ravimeda** [comment]
Refer https://github.com/dotnet/core-eng/issues/1900

**Pull request merged**
