### PR TITLE
Fix build break in System.Data.Common

### PR DESCRIPTION
**Pull request by stephentoub**
cc: @saurabh500

### CODE REVIEW

**Comment by ericstj** [comment]
Not sure this is the correct fix.  I believe these types are supposed to be OOB and therefore should be shared with the desktop build.

**Comment by stephentoub** [comment]
Ok.  I'll close this.  @ericstj, can you please make the correct fix then?

**Comment by stephentoub** [comment]
(Alternatively, we can merge this and then deal with fixing the OOB issues... I'd rather have a passing build and issues to address than a broken one.)

**Comment by ericstj** [comment]
Looks like DBColumn.cs needs to be included in the facade compilation.

**Comment by stephentoub** [comment]
> Looks like DBColumn.cs needs to be included in the facade compilation.

I don't know what that means with respect to what changes are needed.  Can you make the fix? (Either that or we let this PR go through and then @saurabh500 can fix it up appropriately after... this shouldn't have been merged without going through a Jenkins build pass.)

**Pull request closed without merging**
