### PR TITLE
BuildTools-404-01

### PR DESCRIPTION
**Pull request by ericstj**
Update buildtools to the latest version to resolve some warnings when restoring buildtools.

Also fix up some workarounds added in the recent Crypto changes.

/cc @weshaggard @steveharter @bartonjs

### CODE REVIEW

**Comment by weshaggard** [comment]
:+1:

**Comment by joperezr** [comment]
LGTM. Thanks for fixing the warnings :smile:

**Comment by bartonjs** [comment]
LGTM.

**Comment by steveharter** [comment]
LGTM. I previously created my own issue to remove the temp bcrypt exceptions -- I'll close that (https://github.com/dotnet/corefx/issues/8264)

**Pull request merged**
