### PR TITLE
Fixing ExpressionStringBuilder for Power and Convert[Checked]

### PR DESCRIPTION
**Pull request by bartdesmet**
This fixes issue #11415. CC @VSadov.

### CODE REVIEW

**Comment by khellang** [comment]
Heh. Nice :smile: I just stopped by to file an issue/send a PR for this, after being reminded by [this talk](https://vimeo.com/180585259) (around the 18min. mark). It always bothered me that `Convert` didn't include the type in the string representation. :shipit:

**Comment by bartdesmet** [comment]
Test Innerloop CentOS7.1 Release Build and Test please (error MSB4018: The "VerifyDependencies" task failed unexpectedly.)

**Comment by stephentoub** [comment]
LGTM

**Comment by bartdesmet** [comment]
@VSadov, @stephentoub - This is ready to merge; no conflicts.

**Pull request merged**
