### PR TITLE
Remove a few allocations

### PR DESCRIPTION
**Pull request by stephentoub**
This is from @bbartels.  I've brought over the relevant changes from https://github.com/dotnet/corefx/pull/36838 that are fine to commit.

### CODE REVIEW

**Review by maryamariyan — APPROVED** [review]

**Review by GrabYourPitchforks — APPROVED** [review]

**Comment by bbartels** [comment]
@stephentoub The allocation for DirectoryEntry.Guid did not seem to have made its way to the PR (https://github.com/dotnet/runtime/blob/master/src/libraries/System.DirectoryServices/src/System/DirectoryServices/DirectoryEntry.cs#L195)  and sadly for some reason I cannot see the changes of the original PR (I guess to do with the dotnet/runtime move?). Is there a way to access the original changes?

**Comment by stephentoub** [comment]
@bbartels, which change, this one?
https://github.com/dotnet/corefx/commit/5311283ea9c309c8a1406ba930564e40f50e2e62

**Comment by bbartels** [comment]
That's the one, yes, how were you able to navigate to that commit? For me it states 0 commits and 0 files changed on the PR.

**Comment by stephentoub** [comment]
image

**Comment by bbartels** [comment]
Ah I see, thank you. Should I still submit a PR in dotnet/runtime for the ones that weren't merged in this PR, such as the one mentioned?

**Comment by stephentoub** [comment]
I purposefully left out ones I didn't see as being meaningful / having test coverage / etc.  If you think there are ones that should be included, though, feel free to open a PR and we can discuss.  Thanks.

**Comment by bbartels** [comment]
I see, okay, I will evaluate which ones I deem to provide value and if I do find ones I'll submit one! Thanks for the clarification!

**Pull request merged**
