### PR TITLE
Update to next buildtools version

### PR DESCRIPTION
**Pull request by mmitche**
Fixes issue with perf tools path

### CODE REVIEW

**Comment by pharring** [comment]
Is this something I should have done on my recent change? If so, sorry.
:+1:

**Comment by mmitche** [comment]
@pharring Nope I got both sets of changes in this.

**Comment by ellismg** [comment]
LGTM.  Can you ensure the timeouts in the machine were not due to something here before merging @mmitche?

**Comment by mmitche** [comment]
Appears not.

**Pull request merged**
