### PR TITLE
Disable crashing Ssl stream test on Windows

### PR DESCRIPTION
**Pull request by ViktorHofer**
https://github.com/dotnet/corefx/issues/38824

cc @bartonjs

### CODE REVIEW

**Comment by stephentoub** [comment]
@viktorhofer, are you sure it's just this one test? Isn't it an underlying issue that could affect any crypto-related test? We should not be disabling every test in these suites one-by-one like this if so.

**Comment by bartonjs** [comment]
It's anything that loads a PFX.  The intermittencies will go away as soon as we move to a higher (or lower) release of Windows 10.

I don't know how you singled out this one test, but it's a race condition deep inside crypt32!PFXImportCertStore.

A sneaky way to mitigate it (which I just now thought of) is to have our xUnit discoverer class do a PFX import and a PFX export in a cctor.  The PFX telemetry initializer then doesn't have a parallel first run, no race condition, happiness.

**Comment by ViktorHofer** [comment]
> I don't know how you singled out this one test, but it's a race condition deep inside crypt32!PFXImportCertStore.

That's the callee that showed up in the dump.

> It's anything that loads a PFX. The intermittencies will go away as soon as we move to a higher (or lower) release of Windows 10.

I will make sure that we move away from RS4 on all all architectures. Currently we run on it on x64 and arm64.

**Comment by ViktorHofer** [comment]
> A sneaky way to mitigate it (which I just now thought of) is to have our xUnit discoverer class do a PFX import and a PFX export in a cctor. The PFX telemetry initializer then doesn't have a parallel first run, no race condition, happiness.

I explored that option but there's not a "single" discoverer where we can plumb that in and it doesn't really belong there. If others are using the XUnitExtensions library as well they would be surprised why we are doing PFX import/exports. I tend towards updating the OS itself as it doesn't sound like this will be serviced back into RS4.

**Pull request closed without merging**
