### PR TITLE
Add NugetTargetMoniker to test projects and update remaining project …

### PR DESCRIPTION
**Pull request by karajas**
…references to pkgproj

Update System.Data.SqlClient ManualTests to use new test layout.

/cc @ericstj

### CODE REVIEW

**Comment by karajas** [comment]
Most test projects are now compiled with the appropriate contracts. These are the following tests that require changes to the test code to compile against contracts instead of implementations...

System.Diagnostics.Debug
System.Xml.XmlSerializer 
System.Xml.XDocument/ TreeManipulation 

System.Linq has a minimum support of netstandard 1.6 (https://github.com/dotnet/corefx/blob/master/Documentation/architecture/net-platform-standard.md needs to be updated.)

System.Private.Uri does not have a netstandard contract and is a part of shared framework.

**Comment by karajas** [comment]
@dotnet-bot test Innerloop OSX Release Build and Test

**Comment by karajas** [comment]
@weshaggard @ericstj PTAL

**Comment by tarekgh** [comment]
LGTM. thanks.

**Pull request merged**
