### PR TITLE
Removing initialization of "AgentToolsPath"

### PR DESCRIPTION
**Pull request by JohnTortugo**
The agent pool will have the environment variable defined.

### CODE REVIEW

**Comment by jcagme** [comment]
Cesar found out that if the variable is defined in the build definition it will override the value in the environment variable causing the scripts not to be executed so we could either map it to the same value we are setting the environment variable to (which will need an update if we change it), delete it or add some extra logic to the inline script to deal with this scenario

**Comment by weshaggard** [comment]
While that is kind of unfortunate it is a good enough reason for me. I'm good with removing the declarations.

**Comment by weshaggard** [comment]
As a follow-up question I assume you need to update the inline PS scripts to use `$env:AgentToolsPath` now instead of `$(AgentToolsPath)`, correct?

**Comment by MattGal** [comment]
Actually as long as the value in question is not treated as a VSTS secret, both of those will work.

**Comment by weshaggard** [comment]
Does VSTS automatically expand all properties that are environment variables as well? If VSTS isn't doing it I don't think powershell will interpret that as an environment variable.

**Comment by MattGal** [comment]
@weshaggard if you can see these builds, I've done some experiments

https://devdiv.visualstudio.com/DefaultCollection/Personal/_build/index?buildId=1626163&_a=summary - uses both the $(foo) and $Env:foo syntax, picks up value from VSTS build definition's property. 

https://devdiv.visualstudio.com/DefaultCollection/Personal/_build/index?buildId=1628477&_a=summary - picks up the same values in the same way, but with the VSTS setting unset

PS in question is just : 
``` ps1
Write-Output "The value of some AgentToolsPath is $(AgentToolsPath)"
Write-Output "The value of some AgentToolsPath from the environment is $Env:AgentToolsPath"

```

**Comment by jcagme** [comment]
> As a follow-up question I assume you need to update the inline PS scripts to use $env:AgentToolsPath now instead of $(AgentToolsPath), correct?

This is what we use in the initial set of build definitions making use of AgentToolsPath and it is working fine so far.

**Comment by MattGal** [comment]
Agree, my point earlier is that either works the same for any non-secret

**Comment by weshaggard** [comment]
It is great that it works but I'm still unsure why. We aren't defining AgentToolsPath in the variable section or while queuing so unless VSTS parses all the variables in all the tasks and prompts anything it sees with the pattern `$(...)` I don't know how it would know it was a variable. Or unless VSTS prompts all environment variables to be VSTS variables I have no idea how it would work.

**Comment by weshaggard** [comment]
See https://devdiv.visualstudio.com/DefaultCollection/Personal/_build/index?buildId=1628582&_a=summary where I used `$(AgentToolsPath1)` which is another undefined env variable and see how it errors. So I still believe if we aren't going to define the variable we should switch to using `$env:AgentToolsPath` otherwise these steps will error on any machine that doesn't have the env variable defined.

**Comment by weshaggard** [comment]
I would not like to make the assumption that AgentToolsPath is defined in the env for all our agents as this is an optional extension point. I chatted with @jcagme and he is going to switch to using `$env:AgentToolsPath`.

**Pull request merged**
