### PR TITLE
Import XML Doc Comments for System.ComponentModel.EventBasedAsync

### PR DESCRIPTION
**Pull request by cartermp**
/cc @mairaw @Priya91

### CODE REVIEW

**Comment by mairaw** [comment]
In this case where we have the same classes in both files and no extra APIs, should we keep the comments in just one of the files?

**Comment by cartermp** [comment]
Good question.  In this case one of the partial `BackgroundWorker` classes does implement `IDisposable`, so there is some significance.  I don't think it's too bad to have the same `<summary>` for both of them in this case.

**Comment by mairaw** [comment]
That's fine. But I'm thinking of how docfx detects the content and what if we need to make edits? Do we have to update it in two places? It becomes a maintenance nightmare.

**Comment by cartermp** [comment]
That's true.  I see options here:

1. Merge the definition in the `Manual.cs` file with the other one.
2. Remove the `<summary>` comment in the `Manual.cs` file.

The second option is certainly easier.

**Comment by mairaw** [comment]
In this case, the #2 option seems to work since you have everything in the other file. That distinction is not that clear for cases like System.Reflection.Emit where the APIs are literally broken into the 2 files.

**Comment by cartermp** [comment]
Done.

**Comment by cartermp** [comment]
Closing this out as we have a different plan for reference docs now.

**Pull request closed without merging**
