### PR TITLE
Delete duplicative exception add in SourceCore

### PR DESCRIPTION
**Pull request by stephentoub**
Fixes https://github.com/dotnet/corefx/issues/42032

### CODE REVIEW

**Comment by stephentoub** [comment]
@bartonjs, there are a lot of crypto tests failing here on Linux that are unrelated to my changes:
https://github.com/dotnet/corefx/pull/42035/checks?check_run_id=271634192
Are these known?  There are a variety of error messages, but presumably the root causes are all the same.  Machine configuration issue?  Some bad change that got merged?

**Comment by bartonjs** [comment]
The failures seem to all be on SLES15.  If they're not failing on any other PRs then I'd say that someone has corrupted the OpenSSL on this machine.  If they are then SLES15 seems to have a bad build of OpenSSL (or something super weird is going on)

**Comment by bartonjs** [comment]
Assuming I interpreted the failures correctly, `Interop+Crypto+OpenSslCryptographicException : error:10102082:elliptic curve routines:ec_key_simple_check_key:wrong order` was seen on one CoreCLR PR (Ubuntu 18.04) and this CoreFX PR (SLES15).

#42048 showed master hitting `Interop+Crypto+OpenSslCryptographicException : error:1010207B:elliptic curve routines:ec_key_simple_check_key:invalid private key` on Ubuntu 18.04, and that was also hit by the same CoreCLR PR.

`System.Security.Cryptography.EcDiffieHellman.Tests.ECDhKeyFileTests.ReadWriteNistP521Pkcs8` should be deterministic, and exactly the same as `System.Security.Cryptography.EcDsa.Tests.ECDsaKeyFileTests.ReadWriteNistP521Pkcs8`... which didn't fail.

So... memory corruption? Possibly an array pool rent/return violation?

**Comment by stephentoub** [comment]
@tarekgh, I'll consider your having put up an identical PR as approval for this one :)

**Pull request merged**
