### PR TITLE
Change namespace used in System.Linq.Expressions.Tests

### PR DESCRIPTION
**Pull request by JonHanna**
To be consistently System.Linq.Expressions.Tests as per #2898

CC: @bartdesmet since you're adding tests here

### CODE REVIEW

**Comment by stephentoub** [comment]
LGTM
cc: @VSadov

**Comment by JonHanna** [comment]
Test  Innerloop Windows_NT Debug Build and Tes

**Comment by JonHanna** [comment]
Test Innerloop Windows_NT Debug Build and Test

**Comment by stephentoub** [comment]
Test Innerloop Ubuntu Release Build and Test please
Test Innerloop CentOS7.1 Release Build and Test please

**Pull request merged**
