### PR TITLE
Fix CFDAta leak in native Apple crypto lib dotnet/corefx#33419

### LINKED ISSUE #33419: CFData object leaks inside of `AppleCryptoNative_X509GetContentType`
The `CFData` allocated at https://github.com/dotnet/corefx/blob/810a623ac01236a7fabeabab9c3471fd1d2ede4d/src/Native/Unix/System.Security.Cryptography.Native.Apple/pal_x509.c#L86
```C
CFDataRef cfData = CFDataCreateWithBytesNoCopy(NULL, pbData, cbData, kCFAllocatorNull);
```

is never de-allocated. PR will be coming shortly.

### PR DESCRIPTION
**Pull request by jlennox**
Fixes #33419

### CODE REVIEW

**Review by stephentoub — APPROVED** [review]

**Comment by stephentoub** [comment]
cc: @bartonjs

**Review by bartonjs — APPROVED** [review]

**Comment by stephentoub** [comment]
Thanks!

**Comment by stephentoub** [comment]
Thanks!

**Comment by jlennox** [comment]
@stephentoub I've been interested in becoming a steady contributor to the .net projects and was hoping for some general advice on where to begin. Would you be willing to email me? JLennox@gmail.com Thank you.

**Pull request merged**
