### PR TITLE
Fixed typo in GetHostAddressesAsync test for Dns class

### PR DESCRIPTION
**Pull request by drieseng**
Fixed typo in GetHostAddressesAsync() test.

### CODE REVIEW

**Comment by stephentoub** [comment]
Good catch. LGTM.

**Comment by davidsh** [comment]
cc: @himadrisarkar @CIPop

**Comment by stephentoub** [comment]
Test Innerloop Windows_NT Debug Build and Test please

**Comment by CIPop** [comment]
LGTM Thanks @drieseng!

**Pull request merged**
