### PR TITLE
Disable Failed Globalization tests for Ubuntu 16.04

### PR DESCRIPTION
**Pull request by tarekgh**
There is other issue #2103 tracking to get this working so for now we are disabling the tests

### CODE REVIEW

**Comment by tarekgh** [comment]
#8180

**Comment by tarekgh** [comment]
CC @ellismg

**Comment by tarekgh** [comment]
@dotnet-bot test Ubuntu16.04 please

**Comment by ellismg** [comment]
LGTM.  I believe there are other issues blocking a clean Ubuntu 16.04 CI, but if the failing globalization tests pass, I'm happy.

**Comment by tarekgh** [comment]
looks Ubuntu 16.04 runs is not working either 

```
dotnet_corefx » master » ubuntu16.04_debug_tst_prtest #1 completed  : FAILURE
```

I would say merge the change and look for the next successful runs if the problem still exist.

**Comment by tarekgh** [comment]
test Innerloop Ubuntu16.04 please

**Comment by ellismg** [comment]
The globalization tests are passing now on 16.04 (if you drill into the logs you can see the failure is due to an HTTP test).

**Comment by tarekgh** [comment]
good. I'll merge the change then. thanks @ellismg for your help.

**Pull request merged**
