### PR TITLE
Fix for SymmetricExcept when using equality comparer.

### PR DESCRIPTION
**Pull request by jasonwoods-7**

### CODE REVIEW

**Comment by stephentoub** [comment]
LGTM.

cc: @AArnott

**Comment by stephentoub** [comment]
db, test this please

**Comment by AArnott** [comment]
Neither the pull request description nor the commit message actually explains the problem or just how it's "fixed". I would be in favor of beefing this up a bit. :)

**Comment by AArnott** [comment]
LGTM

**Pull request merged**
