### PR TITLE
Fix ArgumentNullException in case of IValidatableObject returns null 

### PR DESCRIPTION
**Pull request by FSou1**
- GetObjectValidationErrors method was updated with checking validate results for null;
- A several unit tests were appended;

(#25495)

### CODE REVIEW

**Comment by ajcvickers** [comment]
@FSou1 I think the test may be failing because even though this fixes the bug on .NET Core, it still exists in .NET Framework. You may need to add an attribute like this to the test:
```C#
[SkipOnTargetFramework(~TargetFrameworkMonikers.NetFramework, "Null check not present in .NET Framework")]
```
I believe that the process is then that this fix will be considered for porting to ,NET Framework in the future. @karelz should be able to confirm.

**Comment by karelz** [comment]
If you mark the bug with netfx-port-consider, it will be considered in some future time (assuming it passes compat bar which is pretty high on .NET Framework).

Please make sure this is a fix we want - we will diverge between platforms, so it should be worth it.

**Comment by FSou1** [comment]
@ajcvickers @karelz I'm going to mark the PR and the issue with a "netfx-port-consider" label and failed tests with the attribute.

Would you mind helping me to determine which tests were failed? Is there a way too view the testResult.xml?

> One or more tests failed while running tests from 'System.ComponentModel.Annotations.Tests' please check D:\j\workspace\windows-TGrou---2a8f9c29\bin/tests/System.ComponentModel.Annotations.Tests/netfx-Windows_NT-Release-x86/**testResults**.xml for details!

**Comment by karelz** [comment]
Did you look at the full log? (Details -> Console Output -> Full Log)

```
11:56:40       System.ComponentModel.DataAnnotations.Tests.ValidatorTests.TryValidateObject_IValidatableObject_Null [FAIL]
11:56:40     Discovered:  System.Drawing.Primitives.Tests
11:56:40     Starting:    System.Drawing.Primitives.Tests
11:56:40         System.ArgumentNullException : Value cannot be null.
11:56:41         Parameter name: source
11:56:41         Stack Trace:
11:56:41              at System.Linq.Enumerable.Where[TSource](IEnumerable`1 source, Func`2 predicate)
11:56:41              at System.ComponentModel.DataAnnotations.Validator.GetObjectValidationErrors(Object instance, ValidationContext validationContext, Boolean validateAllProperties, Boolean breakOnFirstError)
11:56:41              at System.ComponentModel.DataAnnotations.Validator.TryValidateObject(Object instance, ValidationContext validationContext, ICollection`1 validationResults, Boolean validateAllProperties)
11:56:41              at System.ComponentModel.DataAnnotations.Tests.ValidatorTests.TryValidateObject_IValidatableObject_Null()
11:56:41       System.ComponentModel.DataAnnotations.Tests.ValidatorTests.ValidateObject_IValidatableObject_Null [FAIL]
11:56:41         System.ArgumentNullException : Value cannot be null.
11:56:41         Parameter name: source
11:56:41         Stack Trace:
11:56:41              at System.Linq.Enumerable.Where[TSource](IEnumerable`1 source, Func`2 predicate)
11:56:41              at System.ComponentModel.DataAnnotations.Validator.GetObjectValidationErrors(Object instance, ValidationContext validationContext, Boolean validateAllProperties, Boolean breakOnFirstError)
11:56:41              at System.ComponentModel.DataAnnotations.Validator.ValidateObject(Object instance, ValidationContext validationContext, Boolean validateAllProperties)
11:56:41              at System.ComponentModel.DataAnnotations.Tests.ValidatorTests.ValidateObject_IValidatableObject_Null()
11:56:42     Finished:    System.ComponentModel.Annotations.Tests
11:56:42     Discovered:  System.Collections.NonGeneric.Tests
11:56:42   === TEST EXECUTION SUMMARY ===
11:56:42     Starting:    System.Collections.NonGeneric.Tests
11:56:42 D:\j\workspace\windows-TGrou---2a8f9c29\Tools\tests.targets(484,5): warning :    System.ComponentModel.Annotations.Tests  Total: 529, Errors: 0, Failed: 2, Skipped: 0, Time: 1.972s [D:\j\workspace\windows-TGrou---2a8f9c29\src\System.ComponentModel.Annotations\tests\System.ComponentModel.Annotations.Tests.csproj]
```

BTW: You can run NetFX tests locally as well - the info is buried in developer docs somewhere.

**Comment by FSou1** [comment]
Exactly. How did you catch it?

**Comment by FSou1** [comment]
Exactly.

I'm a little bit confused why didn't this attribute ignore the test?

**Comment by karelz** [comment]
You skip the test on all NON-Framework platforms. You need to skip it only on Framework - remove the \~ character.

**Comment by FSou1** [comment]
@karelz Looks like there aren't any conflicts.

**Pull request merged**
