### PR TITLE
Add some new MediaTypeNames

### LINKED ISSUE #24895: System.Net.Mime.MediaTypeNames missing types
https://github.com/dotnet/corefx/blob/3f0bd5d8c3d019ad8b1561395030a58bc38ddfe9/src/System.Net.Mail/ref/System.Net.Mime.cs#L44

I tried using `System.Net.Mime.MediaTypeNames` in my asp net core api to remove "magic strings"

```c#
[Consumes(System.Net.Mime.MediaTypeNames.Application...)]
public IActionResult Post(...)
{ ... }
```

But it's missing quite a few MIME types.

These come to mind:

> text/css
> text/javascript
> 
> application/json
> application/json-patch+json
> application/xml
> application/javascript
> application/x-www-form-urlencoded
> 
> multipart/form-data
> multipart/byteranges
> 
> image/png
> image/bmp
> image/webp
> image/svg+xml
> 
> audio/midi
> audio/mpeg
> audio/webm
> audio/ogg
> audio/wav
> 
> video/webm
> video/ogg

### PR DESCRIPTION
**Pull request by ryans610**
Fix #24895 and add some commonly used MediaTypeNames.

### CODE REVIEW

**Comment by danmosemsft** [comment]
Will need API review...

**Comment by stephentoub** [comment]
Thank you for the PR, but the associated issue has not had any APIs approved yet.  New APIs need to follow the process outlined at https://github.com/dotnet/corefx/blob/master/Documentation/project-docs/api-review-process.md.  As such, I'm closing this for now.

**Comment by ryans610** [comment]
> Thank you for the PR, but the associated issue has not had any APIs approved yet. New APIs need to follow the process outlined at https://github.com/dotnet/corefx/blob/master/Documentation/project-docs/api-review-process.md. As such, I'm closing this for now.

Copy that, sorry.

**Comment by danmosemsft** [comment]
No problem @ryans610 we appreciate the interest and would welcome more issues and contributions. For API requests, it is always necessary to get an issue approved first, for other PR's we recommend an issue first unless it is some trivial/obvious thing.

**Pull request closed without merging**
