### PR TITLE
Compilation types through attribute: New and MemberInit tests.

### PR DESCRIPTION
**Pull request by JonHanna**
One that can actually be reviewed directly on github :smile:

### CODE REVIEW

**Comment by JonHanna** [comment]
Test Innerloop Ubuntu Debug Build and Test
Test Innerloop Ubuntu Release Build and Test 
(Timeouts)

**Comment by JonHanna** [comment]
Test Innerloop CentOS7.1 Debug Build and Test
Test Innerloop CentOS7.1 Release Build and Test
(Dead links on test details)

**Comment by JonHanna** [comment]
Test Innerloop CentOS7.1 Debug Build and Test
Test Innerloop CentOS7.1 Release Build and Test

**Comment by JonHanna** [comment]
Test Innerloop CentOS7.1 Debug Build and Test
Test Innerloop CentOS7.1 Release Build and Test

**Comment by stephentoub** [comment]
LGTM

**Pull request merged**
