### PR TITLE
Enabling tests for GetPathRoot

### LINKED ISSUE #27552: Several FileSystem and Path tests failing with latest coreclr
```
2018-02-28 13:24:45,135: INFO: proc(54): run_and_log_output: Output:    System.IO.Tests.PathTests_Windows.GetPathRoot_Span(value: \"C:\\\\\\\\\", expected: \"C:\\\\\") [FAIL]
2018-02-28 13:24:45,135: INFO: proc(54): run_and_log_output: Output:       Assert.Equal() Failure
2018-02-28 13:24:45,135: INFO: proc(54): run_and_log_output: Output:                    ↓ (pos 3)
2018-02-28 13:24:45,135: INFO: proc(54): run_and_log_output: Output:       Expected: C:\
2018-02-28 13:24:45,135: INFO: proc(54): run_and_log_output: Output:       Actual:   C:\\
2018-02-28 13:24:45,135: INFO: proc(54): run_and_log_output: Output:                    ↑ (pos 3)
2018-02-28 13:24:45,135: INFO: proc(54): run_and_log_output: Output:       Stack Trace:
2018-02-28 13:24:45,244: INFO: proc(54): run_and_log_output: Output:          D:\j\workspace\windows-TGrou---74aa877a\src\System.Runtime.Extensions\tests\System\IO\PathTests_Windows.netcoreapp.cs(17,0): at System.IO.Tests.PathTests_Windows.GetPathRoot_Span(String value, String expected)
2018-02-28 13:24:45,244: INFO: proc(54): run_and_log_output: Output:    System.IO.Tests.PathTests_Windows.GetPathRoot_Span(value: \"C:\\\\\\\\foo2\", expected: \"C:\\\\\") [FAIL]
2018-02-28 13:24:45,244: INFO: proc(54): run_and_log_output: Output:       Assert.Equal() Failure
2018-02-28 13:24:45,244: INFO: proc(54): run_and_log_output: Output:                    ↓ (pos 3)
2018-02-28 13:24:45,244: INFO: proc(54): run_and_log_output: Output:       Expected: C:\
2018-02-28 13:24:45,244: INFO: proc(54): run_and_log_output: Output:       Actual:   C:\\
2018-02-28 13:24:45,244: INFO: proc(54): run_and_log_output: Output:                    ↑ (pos 3)
2018-02-28 13:24:45,244: INFO: proc(54): run_and_log_output: Output:       Stack Trace:
2018-02-28 13:24:45,244: INFO: proc(54): run_and_log_output: Output:          D:\j\workspace\windows-TGrou---74aa877a\src\System.Runtime.Extensions\tests\System\IO\PathTests_Windows.netcoreapp.cs(17,0): at System.IO.Tests.PathTests_Windows.GetPathRoot_Span(String value, String expected)
2018-02-28 13:24:45,244: INFO: proc(54): run_and_log_output: Output:    System.IO.Tests.PathTests_Windows.GetPathRoot_Span(value: \"\\\\\\\\test\\\\unc\\\\path\\\\to\\\\something\", expected: \"\\\\\\\\test\\\\unc\") [FAIL]
2018-02-28 13:24:45,260: INFO: proc(54): run_and_log_output: Output:       Assert.Equal() Failure
2018-02-28 13:24:45,260: INFO: proc(54): run_and_log_output: Output:                           ↓ (pos 10)
2018-02-28 13:24:45,260: INFO: proc(54): run_and_log_output: Output:       Expected: \\test\unc
2018-02-28 13:24:45,260: INFO: proc(54): run_and_log_output: Output:       Actual:   \\test\unc\
2018-02-28 13:24:45,260: INFO: proc(54): run_and_log_output: Output:                           ↑ (pos 10)
2018-02-28 13:24:45,260: INFO: proc(54): run_and_log_output: Output:       Stack Trace:
2018-02-28 13:24:45,260: INFO: proc(54): run_and_log_output: Output:          D:\j\workspace\windows-TGrou---74aa877a\src\System.Runtime.Extensions\tests\System\IO\PathTests_Windows.netcoreapp.cs(17,0): at System.IO.Tests.PathTests_Windows.GetPathRoot_Span(String value, String expected)
2018-02-28 13:24:45,260: INFO: proc(54): run_and_log_output: Output:    System.IO.Tests.PathTests_Windows.GetPathRoot_Span(value: \"\\\\\\\\a\\\\b\\\\c\\\\d\\\\e\", expected: \"\\\\\\\\a\\\\b\") [FAIL]
2018-02-28 13:24:45,260: INFO: proc(54): run_and_log_output: Output:       Assert.Equal() Failure
2018-02-28 13:24:45,260: INFO: proc(54): run_and_log_output: Output:                      ↓ (pos 5)
2018-02-28 13:24:45,260: INFO: proc(54): run_and_log_output: Output:       Expected: \\a\b
2018-02-28 13:24:45,260: INFO: proc(54): run_and_log_output: Output:       Actual:   \\a\b\
2018-02-28 13:24:45,260: INFO: proc(54): run_and_log_output: Output:                      ↑ (pos 5)
2018-02-28 13:24:45,260: INFO: proc(54): run_and_log_output: Output:       Stack Trace:
2018-02-28 13:24:45,260: INFO: proc(54): run_and_log_output: Output:          D:\j\workspace\windows-TGrou---74aa877a\src\System.Runtime.Extensions\tests\System\IO\PathTests_Windows.netcoreapp.cs(17,0): at System.IO.Tests.PathTests_Windows.GetPathRoot_Span(String value, String expected)
2018-02-28 13:24:45,260: INFO: proc(54): run_and_log_output: Output:    System.IO.Tests.PathTests_Windows.GetPathRoot_Span(value: \"\\\\\\\\a\\\\b\\\\\", expected: \"\\\\\\\\a\\\\b\") [FAIL]
2018-02-28 13:24:45,260: INFO: proc(54): run_and_log_output: Output:       Assert.Equal() Failure
2018-02-28 13:24:45,260: INFO: proc(54): run_and_log_output: Output:                      ↓ (pos 5)
2018-02-28 13:24:45,260: INFO: proc(54): run_and_log_output: Output:       Expected: \\a\b
2018-02-28 13:24:45,260: INFO: proc(54): run_and_log_output: Output:       Actual:   \\a\b\
2018-02-28 13:24:45,260: INFO: proc(54): run_and_log_output: Output:                      ↑ (pos 5)
2018-02-28 13:24:45,260: INFO: proc(54): run_and_log_output: Output:       Stack Trace:
2018-02-28 13:24:45,260: INFO: proc(54): run_and_log_output: Output:          D:\j\workspace\windows-TGrou---74aa877a\src\System.Runtime.Extensions\tests\System\IO\PathTests_Windows.netcoreapp.cs(17,0): at System.IO.Tests.PathTests_Windows.GetPathRoot_Span(String value, String expected)
2018-02-28 13:24:45,260: INFO: proc(54): run_and_log_output: Output:    System.IO.Tests.PathTests_Windows.GetPathRoot_Span(value: \"\\\\\\\\?\\\\UNC\\\\test\\\\unc\\\\path\\\\to\\\\something\", expected: \"\\\\\\\\?\\\\UNC\\\\test\\\\unc\") [FAIL]
2018-02-28 13:24:45,260: INFO: proc(54): run_and_log_output: Output:       Assert.Equal() Failure
2018-02-28 13:24:45,260: INFO: proc(54): run_and_log_output: Output:                                 ↓ (pos 16)
2018-02-28 13:24:45,260: INFO: proc(54): run_and_log_output: Output:       Expected: \\?\UNC\test\unc
2018-02-28 13:24:45,260: INFO: proc(54): run_and_log_output: Output:       Actual:   \\?\UNC\test\unc\
2018-02-28 13:24:45,260: INFO: proc(54): run_and_log_output: Output:                                 ↑ (pos 16)
2018-02-28 13:24:45,260: INFO: proc(54): run_and_log_output: Output:       Stack Trace:
2018-02-28 13:24:45,260: INFO: proc(54): run_and_log_output: Output:          D:\j\workspace\windows-TGrou---74aa877a\src\System.Runtime.Extensions\tests\System\IO\PathTests_Windows.netcoreapp.cs(17,0): at System.IO.Tests.PathTests_Windows.GetPathRoot_Span(String value, String expected)
2018-02-28 13:24:45,276: INFO: proc(54): run_and_log_output: Output:    System.IO.Tests.PathTests_Windows.GetPathRoot_Span(value: \"\\\\\\\\?\\\\UNC\\\\a\\\\b2\\\\\", expected: \"\\\\\\\\?\\\\UNC\\\\a\\\\b2\") [FAIL]
2018-02-28 13:24:45,276: INFO: proc(54): run_and_log_output: Output:       Assert.Equal() Failure
2018-02-28 13:24:45,276: INFO: proc(54): run_and_log_output: Output:                             ↓ (pos 12)
2018-02-28 13:24:45,276: INFO: proc(54): run_and_log_output: Output:       Expected: \\?\UNC\a\b2
2018-02-28 13:24:45,276: INFO: proc(54): run_and_log_output: Output:       Actual:   \\?\UNC\a\b2\
2018-02-28 13:24:45,276: INFO: proc(54): run_and_log_output: Output:                             ↑ (pos 12)
2018-02-28 13:24:45,276: INFO: proc(54): run_and_log_output: Output:       Stack Trace:
2018-02-28 13:24:45,276: INFO: proc(54): run_and_log_output: Output:          D:\j\workspace\windows-TGrou---74aa877a\src\System.Runtime.Extensions\tests\System\IO\PathTests_Windows.netcoreapp.cs(17,0): at System.IO.Tests.PathTests_Windows.GetPathRoot_Span(String value, String expected)
2018-02-28 13:24:45,276: INFO: proc(54): run_and_log_output: Output:    System.IO.Tests.PathTests_Windows.GetPathRoot_Windows(value: \"\\\\\\\\test\\\\unc\\\\path\\\\to\\\\something\", expected: \"\\\\\\\\test\\\\unc\") [FAIL]
2018-02-28 13:24:45,276: INFO: proc(54): run_and_log_output: Output:       Assert.Equal() Failure
2018-02-28 13:24:45,276: INFO: proc(54): run_and_log_output: Output:                           ↓ (pos 10)
2018-02-28 13:24:45,276: INFO: proc(54): run_and_log_output: Output:       Expected: \\test\unc
2018-02-28 13:24:45,276: INFO: proc(54): run_and_log_output: Output:       Actual:   \\test\unc\
2018-02-28 13:24:45,276: INFO: proc(54): run_and_log_output: Output:                           ↑ (pos 10)
2018-02-28 13:24:45,276: INFO: proc(54): run_and_log_output: Output:       Stack Trace:
2018-02-28 13:24:45,276: INFO: proc(54): run_and_log_output: Output:          D:\j\workspace\windows-TGrou---74aa877a\src\System.Runtime.Extensions\tests\System\IO\PathTests_Windows.cs(48,0): at System.IO.Tests.PathTests_Windows.GetPathRoot_Windows(String value, String expected)
2018-02-28 13:24:45,276: INFO: proc(54): run_and_log_output: Output:    System.IO.Tests.PathTests_Windows.GetPathRoot_Windows(value: \"\\\\\\\\a\\\\b\\\\c\\\\d\\\\e\", expected: \"\\\\\\\\a\\\\b\") [FAIL]
2018-02-28 13:24:45,276: INFO: proc(54): run_and_log_output: Output:       Assert.Equal() Failure
2018-02-28 13:24:45,276: INFO: proc(54): run_and_log_output: Output:                      ↓ (pos 5)
2018-02-28 13:24:45,276: INFO: proc(54): run_and_log_output: Output:       Expected: \\a\b
2018-02-28 13:24:45,276: INFO: proc(54): run_and_log_output: Output:       Actual:   \\a\b\
2018-02-28 13:24:45,276: INFO: proc(54): run_and_log_output: Output:                      ↑ (pos 5)
2018-02-28 13:24:45,276: INFO: proc(54): run_and_log_output: Output:       Stack Trace:
2018-02-28 13:24:45,276: INFO: proc(54): run_and_log_output: Output:          D:\j\workspace\windows-TGrou---74aa877a\src\System.Runtime.Extensions\tests\System\IO\PathTests_Windows.cs(48,0): at System.IO.Tests.PathTests_Windows.GetPathRoot_Windows(String value, String expected)
2018-02-28 13:24:45,276: INFO: proc(54): run_and_log_output: Output:    System.IO.Tests.PathTests_Windows.GetPathRoot_Windows(value: \"\\\\\\\\a\\\\b\\\\\", expected: \"\\\\\\\\a\\\\b\") [FAIL]
2018-02-28 13:24:45,276: INFO: proc(54): run_and_log_output: Output:       Assert.Equal() Failure
2018-02-28 13:24:45,276: INFO: proc(54): run_and_log_output: Output:                      ↓ (pos 5)
2018-02-28 13:24:45,276: INFO: proc(54): run_and_log_output: Output:       Expected: \\a\b
2018-02-28 13:24:45,276: INFO: proc(54): run_and_log_output: Output:       Actual:   \\a\b\
2018-02-28 13:24:45,276: INFO: proc(54): run_and_log_output: Output:                      ↑ (pos 5)
2018-02-28 13:24:45,276: INFO: proc(54): run_and_log_output: Output:       Stack Trace:
2018-02-28 13:24:45,276: INFO: proc(54): run_and_log_output: Output:          D:\j\workspace\windows-TGrou---74aa877a\src\System.Runtime.Extensions\tests\System\IO\PathTests_Windows.cs(48,0): at System.IO.Tests.PathTests_Windows.GetPathRoot_Windows(String value, String expected)
2018-02-28 13:24:45,276: INFO: proc(54): run_and_log_output: Output:    System.IO.Tests.PathTests_Windows.GetPathRoot_Windows(value: \"\\\\\\\\?\\\\UNC\\\\test\\\\unc\\\\path\\\\to\\\\something\", expected: \"\\\\\\\\?\\\\UNC\\\\test\\\\unc\") [FAIL]
2018-02-28 13:24:45,276: INFO: proc(54): run_and_log_output: Output:       Assert.Equal() Failure
2018-02-28 13:24:45,276: INFO: proc(54): run_and_log_output: Output:                                 ↓ (pos 16)
2018-02-28 13:24:45,276: INFO: proc(54): run_and_log_output: Output:       Expected: \\?\UNC\test\unc
2018-02-28 13:24:45,276: INFO: proc(54): run_and_log_output: Output:       Actual:   \\?\UNC\test\unc\
2018-02-28 13:24:45,276: INFO: proc(54): run_and_log_output: Output:                                 ↑ (pos 16)
2018-02-28 13:24:45,276: INFO: proc(54): run_and_log_output: Output:       Stack Trace:
2018-02-28 13:24:45,276: INFO: proc(54): run_and_log_output: Output:          D:\j\workspace\windows-TGrou---74aa877a\src\System.Runtime.Extensions\tests\System\IO\PathTests_Windows.cs(48,0): at System.IO.Tests.PathTests_Windows.GetPathRoot_Windows(String value, String expected)
2018-02-28 13:24:45,276: INFO: proc(54): run_and_log_output: Output:    System.IO.Tests.PathTests_Windows.GetPathRoot_Windows(value: \"\\\\\\\\?\\\\UNC\\\\a\\\\b2\\\\\", expected: \"\\\\\\\\?\\\\UNC\\\\a\\\\b2\") [FAIL]
2018-02-28 13:24:45,276: INFO: proc(54): run_and_log_output: Output:       Assert.Equal() Failure
2018-02-28 13:24:45,276: INFO: proc(54): run_and_log_output: Output:                             ↓ (pos 12)
2018-02-28 13:24:45,276: INFO: proc(54): run_and_log_output: Output:       Expected: \\?\UNC\a\b2
2018-02-28 13:24:45,276: INFO: proc(54): run_and_log_output: Output:       Actual:   \\?\UNC\a\b2\
2018-02-28 13:24:45,276: INFO: proc(54): run_and_log_output: Output:                             ↑ (pos 12)
2018-02-28 13:24:45,276: INFO: proc(54): run_and_log_output: Output:       Stack Trace:
2018-02-28 13:24:45,292: INFO: proc(54): run_and_log_output: Output:          D:\j\workspace\windows-TGrou---74aa877a\src\System.Runtime.Extensions\tests\System\IO\PathTests_Windows.cs(48,0): at System.IO.Tests.PathTests_Windows.GetPathRoot_Windows(String value, String expected)
```
and
```
2018-02-28 13:24:34,276: INFO: proc(54): run_and_log_output: Output:    System.IO.Tests.FileInfo_Directory.UNCShares [FAIL]
2018-02-28 13:24:34,276: INFO: proc(54): run_and_log_output: Output:       Assert.Equal() Failure
2018-02-28 13:24:34,276: INFO: proc(54): run_and_log_output: Output:                                    ↓ (pos 19)
2018-02-28 13:24:34,276: INFO: proc(54): run_and_log_output: Output:       Expected: \\Machine\Directory
2018-02-28 13:24:34,276: INFO: proc(54): run_and_log_output: Output:       Actual:   \\Machine\Directory\
2018-02-28 13:24:34,276: INFO: proc(54): run_and_log_output: Output:                                    ↑ (pos 19)
2018-02-28 13:24:34,292: INFO: proc(54): run_and_log_output: Output:       Stack Trace:
2018-02-28 13:24:34,401: INFO: proc(54): run_and_log_output: Output:          D:\j\workspace\windows-TGrou---74aa877a\src\System.IO.FileSystem\tests\FileInfo\Directory.cs(55,0): at System.IO.Tests.FileInfo_Directory.UNCShares()
2018-02-28 13:24:38,369: INFO: proc(54): run_and_log_output: Output:    System.IO.Tests.FileInfo_DirectoryName.UNCShares [FAIL]
2018-02-28 13:24:38,369: INFO: proc(54): run_and_log_output: Output:       Assert.Equal() Failure
2018-02-28 13:24:38,369: INFO: proc(54): run_and_log_output: Output:                                    ↓ (pos 19)
2018-02-28 13:24:38,369: INFO: proc(54): run_and_log_output: Output:       Expected: \\Machine\Directory
2018-02-28 13:24:38,369: INFO: proc(54): run_and_log_output: Output:       Actual:   \\Machine\Directory\
2018-02-28 13:24:38,369: INFO: proc(54): run_and_log_output: Output:                                    ↑ (pos 19)
2018-02-28 13:24:38,369: INFO: proc(54): run_and_log_output: Output:       Stack Trace:
2018-02-28 13:24:38,369: INFO: proc(54): run_and_log_output: Output:          D:\j\workspace\windows-TGrou---74aa877a\src\System.IO.FileSystem\tests\FileInfo\Directory.cs(55,0): at System.IO.Tests.FileInfo_Directory.UNCShares()
```

### PR DESCRIPTION
**Pull request by Anipik**
Fixes #27552

### CODE REVIEW

**Comment by Anipik** [comment]
@danmosemsft can I merge this one ?

**Comment by danmosemsft** [comment]
We should wait for Mac results

**Comment by Anipik** [comment]
@danmosemsft these tests are just for windows platform. and isnt the OSX build broken ?

**Comment by Anipik** [comment]
@dotnet-bot test OSX x64 Debug Build

**Comment by danmosemsft** [comment]
It may be but there is no reason for hurry and it is risky to get in the habit of bypassing checks. It tends to cost later.

**Pull request merged**
