### PR TITLE
Interpreted cast exception

### LINKED ISSUE #7169: Expression.Convert() incorrect in interpreter with enum types.
Given an enum type `E`, a long-backed enumtype `El` and a value of type `E` called `e` then `Expression.Convert()` will be treated differently in the compiler and the interpreter.

```C#
// comparable numerical value to e on all
Expression.Convert(Expression.Constant(e, typeof(E)), typeof(El))

// InvalidCastException in compiler.
// comparable numerical value to e in interpreter
Expression.Convert(Expression.Constant(e, typeof(object)), typeof(El))
Expression.Convert(Expression.Constant(e, typeof(Enum)), typeof(El))

// InvalidCastException in compiler.
// ArgumentException in interpreter.
Expression.Convert(Expression.Constant("hello"), typeof(El))
```

Aside from the compiler winning on the grounds of precedence, it would appear to be correct on each count here, with the `ArgumentException` being plainly wrong. There is a bit of a risk to fixing the second case, as it could cause a throw in working code, though it's perhaps better to nip it in the bud.

### PR DESCRIPTION
**Pull request by JonHanna**
Convert to enumerable types correctly in interpreter.

Fixes #7169.

Also:

Compilation types through attribute in casting tests.

Change verification of exceptions to test specific inputs having specific exceptions, rather than try-and-repeat: Less exceptions thrown and caught, better-defined tests.

Add some extra cases to enumerable casting tests.

(These test changes led to finding this issue)

cc @stephentoub, @VSadov

### CODE REVIEW

**Comment by JonHanna** [comment]
Test Innerloop CentOS7.1 Release Build and Test
Test Innerloop Windows_NT Debug Build and Test
("There was an I/O error during the build." cc @mmitche)

**Comment by JonHanna** [comment]
Test  Innerloop Windows_NT Debug Build and Test

**Comment by JonHanna** [comment]
I'm going to have to split this up further to get in under the diff viewing limits.

**Comment by JonHanna** [comment]
Actually. Question for @stephentoub, @VSadov and anyone else likely to be reviewing this. Three of the test files here have too many changes to see via github. Those changes are rather mechanical in a reviewed-it-once-reviewed-it-all sort of way. Does the view given by https://github.com/dotnet/corefx/pull/7170.patch suffice for this?

I'm hoping to make a bunch of similar changes to the tests soon, and splitting them into multiple commits to make sure there's a viewable diff each time will be excessive in a different way.

**Comment by JonHanna** [comment]
Test Innerloop Ubuntu Release Build and Test 
(Timeout: http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/ubuntu_release_prtest/3970/)

**Comment by VSadov** [comment]
Looks good. I wonder about impact on how long it takes to run tests?

**Comment by JonHanna** [comment]
Swings and roundabouts: Obviously I'm doubling up on a lot of tests, and intend to have doubled up on pretty much all of them by building on  #6906. At the same time I'm cutting down a lot of (machine-generated?) code that tests for an exception twice into either code that tests for a particular exception, or doesn't test for it at all (when it clearly shouldn't happen).

I imagine this will still be a nett increase in time, but bringing with it a great increase in test coverage.

I'm hoping we can clear out some of the current cross-tests down the line, if they can clearly be shown to be duplicates, and have some big wins in that that compensate for that nett increase.

**Comment by VSadov** [comment]
As I remember the increase in test time was an issue with cross-tests. That is expected cost of increased coverage, but this approach is different and does remove some code and is more targeted to particular scenarios so there is less chance of an overlap.

I considering making similar changes myself, but had concerns about test time and inability to move Theories partially to the outer loop.

After several more interpreter parity bugs found via real apps, I think that increase in coverage is worth the test time unless increase is really severe.

I was mostly curious if there is a serious observable increase (or otherwise). 
Like if it took 5min before and now takes 15min, I'd notice that by just running tests locally. While if t were 1min to 3min change, I'd probably not care.

**Comment by JonHanna** [comment]
Not enough to be noticeable with any single batch of changes, no. (But then I have 4 hyper-threaded cores, so I'd have to push things out past the longest-running collections to make an appreciable difference).

On the general matter of the times of the expressions tests, I've said before I think we have both too many and not enough, in that they take too long, but new tests keep finding new issues so we're far from the point where the tests are just guarding against regressions and we could argue we'd gone too far.

I do recall that it seems to spend a lot of time in a few particularly convoluted tests, which could perhaps be improved. Since applying this approach throughout will mean looking at tests I've previously ignored, some inefficiencies may become apparent.

**Pull request merged**
