### PR TITLE
Add Ubuntu 18.10 (Cosmic Cuttlefish)

### LINKED ISSUE #32282: Add Ubuntu 18.10 (Cosmic Cuttlefish) to the RID graph & to Jenkins CI
`pkg\Microsoft.NETCore.Platforms\runtimeGroups.props` needs to be updated for 18.10 which comes out Thursday October 18.

related https://github.com/dotnet/core-eng/issues/4193

### PR DESCRIPTION
**Pull request by joshfree**
Add Ubuntu 18.10 to Microsoft.NETCore.Platforms

Fixes #32282

### CODE REVIEW

**Comment by joshfree** [comment]
[OSX x64 Debug Build - System.Net.HttpListener.Tests](https://mc.dot.net/#/user/joshfree/pr~2Fjenkins~2Fdotnet~2Fcorefx~2Frelease~2F2.1~2F/test~2Ffunctional~2Fcli~2F/a084ec96c9fa64220cb2f7e43650afce9cf233b3/workItem/System.Net.HttpListener.Tests/analysis/xunit/System.Net.Tests.HttpListenerResponseHeadersTests~2FStatusDescription_GetWithCustomStatusCode_ReturnsExpected(statusCode:%20207,%20expectedDescription:%20%5C%22Multi-Status%5C%22))
```
System.Net.Tests.HttpListenerResponseHeadersTests/StatusDescription_GetWithCustomStatusCode_ReturnsExpected(statusCode: 207, expectedDescription: \"Multi-Status\")

Unhandled Exception of Type System.Net.Internals.SocketExceptionFactory+ExtendedSocketException
Message :
System.Net.Internals.SocketExceptionFactory+ExtendedSocketException : Connection refused 127.0.0.1:1299
```

@dotnet-bot test OSX x64 Debug Build

**Comment by joshfree** [comment]
@dotnet-bot test Windows x86 Release Build please

This failure was a System.IO.Pipelines test timeout tracked by https://github.com/dotnet/corefx/issues/31349

**Comment by ericstj** [comment]
*nice to have*  typically we add new supported RIDs to https://github.com/dotnet/buildtools/blob/5ab6e36f4e1d303f54666479fa4eff42dc4f0adc/src/Microsoft.DotNet.Build.Tasks.Packaging/src/PackageFiles/Packaging.targets#L927

**Comment by weshaggard** [comment]
@danmosemsft this needs packaging work in order to ship. Microsoft.NETCore.Platforms needs to be versioned and added to the package build.

**Comment by danmosemsft** [comment]
Ah, of course. @joshfree could you please take care of that? If we have it soon we can consider it part of the same approval.

**Comment by joshfree** [comment]
@weshaggard can you send me a pointer to the doc?

**Comment by danmosemsft** [comment]
Maybe this? https://github.com/dotnet/corefx/blob/master/Documentation/project-docs/library-servicing.md

**Pull request merged**
