### PR TITLE
Removing microsoft.private.corefx.uap

### PR DESCRIPTION
**Pull request by Anipik**

### CODE REVIEW

**Comment by ericstj** [comment]
Can you also remove https://github.com/dotnet/corefx/blob/80adc8b87163dfe77d5b4262ea7970cc2de87f46/Directory.Build.targets#L63-L68 
https://github.com/dotnet/corefx/blob/80adc8b87163dfe77d5b4262ea7970cc2de87f46/Directory.Build.targets#L41
And UAP from here: 
https://github.com/dotnet/corefx/blob/80adc8b87163dfe77d5b4262ea7970cc2de87f46/Directory.Build.targets#L102

THese are the places responsible for building out the content of those packages.

**Comment by Anipik** [comment]
```
<BinPlaceConfiguration Condition="'$(BuildAllConfigurations)' == 'true'" Include="netcoreapp-$(_bc_OSGroup);uap-Windows_NT">
```
uap-Windows_NT is required here for build manual shims for uap config. @ericstj am  I missing something here ?

**Comment by ericstj** [comment]
If you're finding we still build things that depend on that runtime path in the all configurations build then leave it around.  I was being optimistic in my suggestions.

**Comment by Anipik** [comment]
@ericstj  is it fine to merge this one ?

**Review by ViktorHofer — APPROVED** [review]

**Comment by ViktorHofer** [comment]
Congrats, you broke the build: https://dnceng.visualstudio.com/internal/_build/results?buildId=364066 😁

**Comment by ericstj** [comment]
And @ViktorHofer fixed it: https://github.com/dotnet/corefx/commit/0a51b2d9b191a12768d4d1410d0c200bba558522

**Pull request merged**
