### PR TITLE
Remove compat pack

### PR DESCRIPTION
**Pull request by ViktorHofer**
Fixes https://github.com/dotnet/corefx/issues/40656

cc @ericstj

### CODE REVIEW

**Comment by ViktorHofer** [comment]
@ericstj @joperezr how should we deal with the System.Text.Json dependency on the compat packages?

**Comment by joperezr** [comment]
You shouldn't delete these yet, until they go stable. Once they do, we can add them to one of our depprojs so that they get restored and System.Text.Json will move to just reference those instead.

**Comment by joperezr** [comment]
Or the other option as well, once they go stable, would be to harvest the netstandard2.0 asset from the system.text.json package. Any option should be fine, but both options mean we should wait till we have stable versions before we make this change.

**Comment by ViktorHofer** [comment]
OK sounds good. When I submitted the PR I didn't know about the System.Text.Json dependency otherwise I would have waited. I will keep this PR idle meanwhile and we can continue working on it in early October. Harvesting the netstandard2.0 asset from system.text.json makes sense if we don't plan to evolve it. Otherwise harvesting the compat ones is fine as well.

**Comment by ericstj** [comment]
We shouldn't harvest the `netstandard2.0` asset: that freezes System.Text.Json surface area.  That would break the current writable dom work.

We should copy the compat pack packages here: https://github.com/dotnet/corefx/blob/a533a0fad2c101881945824570dc21845783366a/eng/restore/binplacePackages/binplacePackages.depproj#L29

I'm OK with doing it now if we have an issue to follow up updating to RTM.  I'm also OK just waiting.

**Pull request closed without merging**
