### PR TITLE
Make outerloop ubuntu14.04 runs to be run as sudo.

### PR DESCRIPTION
**Pull request by Priya91**
cc @mmitche @vijaykota 

This PR makes the outerloop ubuntu14.04 runs to be run on newly created auto-image 201626test, to enable the tests to be run as sudo, to prevent outerloop test failures due to lack of admin permissions. If these changes pass, similar changes will be made to other outerloop OSes.

### CODE REVIEW

**Comment by vijaykota** [comment]
Changes look good to me. Thanks!

**Comment by Priya91** [comment]
@dotnet-bot Test Innerloop OSX Debug Build and Test

**Comment by mmitche** [comment]
@Priya91 Your changes have no effect on those cofnigurations, so no reason to retry them.

@dotnet-bot test ci please

LGTM if that passes.

**Comment by Priya91** [comment]
@mmitche Thanks! that was quick :) It passed.

**Pull request merged**
