### PR TITLE
Misc. cleanup of stack spiller code in System.Linq.Expressions

### PR DESCRIPTION
**Pull request by bartdesmet**
When working on https://github.com/dotnet/corefx/issues/11740, I bunch of things in `StackSpiller` caught my eye, so I decided to do some cleanup:
- Move classes into separate files, e.g. `ChildRewriter`.
- Add XML doc comments to non-trivial components.
- Mark inner classes as `sealed`.
- Mark some fields as `readonly`.
- Fix some comments.
- Use some C# 6.0 features in places.
- Ensure `var` usage consistency.
- Remove unused parameters and code analysis suppressions.

No semantic changes were made; this is mostly moving code around into separate files, addressing stylistic oddities, and adding documentation.

~~Once this is merged, the move of `ChildRewriter` to a separate file will cause a merge conflict / rebase requirement for https://github.com/dotnet/corefx/pull/12786. I'll deal with that.~~

### CODE REVIEW

**Comment by bartdesmet** [comment]
Test Innerloop Ubuntu14.04 Debug Build and Test please (build timeout)

**Comment by bartdesmet** [comment]
CC @VSadov, @stephentoub

**Comment by karelz** [comment]
@VSadov @OmarTawfik can you please review the change?

**Comment by karelz** [comment]
@VSadov @OmarTawfik ping?

**Comment by karelz** [comment]
@VSadov @OmarTawfik ping again? This is getting stale :(

**Pull request merged**
