### PR TITLE
Added package projects to resource reader and writer

### PR DESCRIPTION
**Pull request by KrzysztofCwalina**

### CODE REVIEW

**Comment by KrzysztofCwalina** [comment]
@weshaggard, @ericstj

**Comment by stephentoub** [comment]
FYI, build failure:
```
10:40:17 d:\j\workspace\dotnet_corefx\windows_nt_debug_prtest\packages\Microsoft.DotNet.BuildTools.1.0.25-prerelease-00144\lib\Packaging.targets(849,5): error : System.Resources.Reader should not be supported on WindowsPhone,Version=v8.0 but has both compile and runtime assets. [d:\j\workspace\dotnet_corefx\windows_nt_debug_prtest\src\System.Resources.Reader\pkg\System.Resources.Reader.pkgproj]
10:40:18 d:\j\workspace\dotnet_corefx\windows_nt_debug_prtest\packages\Microsoft.DotNet.BuildTools.1.0.25-prerelease-00144\lib\Packaging.targets(849,5): error : System.Resources.Writer should not be supported on WindowsPhone,Version=v8.0 but has both compile and runtime assets. 
```

**Comment by KrzysztofCwalina** [comment]
@dotnet-bot test this please

**Comment by ericstj** [comment]
Did you set packagetargetframework property in the projects themselves?

**Comment by ericstj** [comment]
Have a look at this: https://github.com/ericstj/corefx/commit/f5adba998542e811917638391ec84ea2c82bcd87

**Comment by KrzysztofCwalina** [comment]
@ericstj, thanks. I updated this PR.

**Comment by ericstj** [comment]
LGTM

**Pull request merged**
