### PR TITLE
Add setup and cleanup extension points to build script.

### PR DESCRIPTION
**Pull request by StephenBonikowsky**
* In WCF repo we need to do some setup and cleanup steps.
* Adding generic setup and cleanup extension points to the build script here in corefx to support WCF (and others) who may need them.
* Also updating the "set BUILDERRORLEVEL=%ERRORLEVEL% after the BuildManaged msbuild call to use '!' instead of '%' to gain the benefit of EnableDelayedExpansion which is necessary in WCF repo.

### CODE REVIEW

**Comment by StephenBonikowsky** [comment]
@weshaggard 
@mellinoe

**Comment by mellinoe** [comment]
I'd prefer this sort of thing go into the actual build engine, rather than into `build.cmd`. Is our build not flexible to set something like this up in the top-level build project, for example? Putting stuff like this into `build.cmd` can be bad because of things like:

* Divergence between `cmd` and `sh`. Even if you added something analogous to `build.sh`, that still implies implementing the pre/post scripts at least twice.
* Scripts are more awkward for ordering. MSBuild handles ordering and target dependency resolution, but this is all by hand in a script which is more confusing and error prone.
* `build.cmd` now behaves differently from `msbuild build.proj`.

**Comment by mellinoe** [comment]
I'm also curious as to how this will play with partial builds. Are the setup-cleanup steps required for some particular portion of the build, i.e. tests? MSBuild would also be a better place to handle a more complicated conditional seutp-cleanup process.We could make "setup" a pre-target for any test, and make "cleanup" a post-target. During traversal builds we could disable the intermediate "cleanups" between tests, or something like that. It would be difficult to implement this with scripts.

**Comment by StephenBonikowsky** [comment]
Yes, currently we need this to setup for a Service needed by our OuterLoop tests and then some related cleanup. It isn't done per test though.

Adding @roncain @iamjasonp and @hongdai who have been working on updating this part of our infrastructure.

**Comment by weshaggard** [comment]
I agree with @mellinoe that I would prefer these be targets in msbuild and not in the scripts themselves. We are soon going to be making some changes to make these scripts dead simple and eliminate most of the logic in them.

**Comment by StephenBonikowsky** [comment]
Ok, I'll start working on it.

**Comment by iamjasonp** [comment]
> We could make "setup" a pre-target for any test, and make "cleanup" a post-target. During traversal builds we could disable the intermediate "cleanups" between tests, or something like that. It would be difficult to implement this with scripts.

It's slightly more complicated than that. 

Our setup scripts modify system state - for example, installing certificates, setting up firewall ports, etc. They only need to be done for Outerloop tests; innerloop tests don't require any additional setup. 

We currently care about doing these setup steps only when we're doing our outerloop tests, and the idea is that we do this type of setup once per outerloop test run (we can probably get away with "setup one or more times" if it's too hard to enforce exactly once). 

Our cleanup steps are currently designed to be done _exactly_ once at the completion of test runs on a machine (we don't test in parallel)

Also note that our setup steps differ between platforms - for example, setting up certificates on MacOS and Ubuntu and Windows all require different commands run.

**Comment by StephenBonikowsky** [comment]
Going to close this PR and start looking into adding setup and cleanup steps within msbuild.

**Pull request closed without merging**
