### PR TITLE
Adding OnesComplement node support in the expression interpreter

### PR DESCRIPTION
**Pull request by bartdesmet**
Adding OnesComplement node support in the expression interpreter. This fixes issue #3737.

cc @VSadov

### CODE REVIEW

**Comment by bartdesmet** [comment]
Seems to be missing one commit; you can hold off on reviewing until the next iteration.

**Comment by VSadov** [comment]
is this complete now?

**Comment by bartdesmet** [comment]
Yes, it is now.

**Comment by VSadov** [comment]
LGTM

**Pull request merged**
