### PR TITLE
Don't catch all failures in HttpListenerResponse.Close tests

### LINKED ISSUE #20156: [HttpListener] HttpListenerResponse.Close(byte[], bool) does not properly shutdown all the time
```cs
[InlineData(true)]
[InlineData(false)]
// The managed implementation should set ContentLength to -1 after sending headers.
[ConditionalTheory(nameof(Helpers) + "." + nameof(Helpers.IsWindowsImplementation))] // [ActiveIssue(19973, TestPlatforms.AnyUnix)]
public async Task CloseResponseEntity_ChunkedNotSentHeaders_ModifiesContentLength(bool willBlock)
{
    using (HttpListenerResponse response = await GetResponse())
    {
        response.SendChunked = true;

        response.Close(new byte[] { (byte)'a' }, willBlock);
        Assert.Equal(-1, response.ContentLength64);

        // If we're non-blocking then it's not guaranteed that we received this when we read from the socket.
        try
        {
            string clientResponse = GetClientResponse(126);
            Assert.EndsWith("\r\n1\r\na\r\n0\r\n\r\n", clientResponse);
        }
        catch (SocketException)
        {
            // Most of the time, the Socket can read the content send after calling Close(byte[], bool), but
            // occassionally this test fails as the HttpListenerResponse closes before the Socket can receive all
            // content. If this happens, just ignore the failure and carry on.
            // The exception message is: "An existing connection was forcibly closed by the remote host."
            // Although part of this test is to ensure that the connection isn't forcibly closed when closing,
            // we want to avoid intermittent failures.
        }
    }
}
```

From @stephentoub in #19880:

> This is in both the Windows and managed implementation, or just the managed one? This sounds like a bug. It should be possible for the server to close the connection and still have the client receive all of the data sent before that, assuming the server is doing a proper shutdown of the connection.

### PR DESCRIPTION
**Pull request by hughbe**
Fixes #20156

For the reasoning, see #20156

### CODE REVIEW

**Comment by stephentoub** [comment]
@mmitche, FYI on these failures:
https://ci3.dot.net/job/dotnet_corefx/job/master/job/portable-linux-Config_Debug+OuterLoop_false_prtest/631/
```
Using context: Portable Linux x64 Debug Build
hudson.AbortException: Fail: the returned code 500 is not in the accepted range: [[100‥399]]
	at jenkins.plugins.http_request.HttpRequestExecution.responseCodeIsValid(HttpRequestExecution.java:300)
	at jenkins.plugins.http_request.HttpRequestExecution.processResponse(HttpRequestExecution.java:310)
	at jenkins.plugins.http_request.HttpRequestExecution.authAndRequest(HttpRequestExecution.java:221)
	at jenkins.plugins.http_request.HttpRequestExecution.call(HttpRequestExecution.java:187)
```

**Comment by mmitche** [comment]
@stephentoub Those 500s are coming from Helix I think.
@dotnet/eng-first FYI
@MattGal FYI looks like there might some issue with the Helix API.
@karajas Since this is inside the wait loop, we should probably catch + continue in cases like this.  There is an overall bailout timeout wrapper.

**Comment by mmitche** [comment]
@dotnet-bot test Portable Linux x64 Debug Build

**Comment by danmosemsft** [comment]
If you expect thes may be flaky, and want to see, please make them outer loop. There is no reason to let them block CI jobs.

**Comment by hughbe** [comment]
I've renamed the commit. I meant renabled because in effect they're disabled right now.

I've also moved them to outerloop

**Comment by davidsh** [comment]
>I've also moved them to outerloop

Does that mean that this PR should then run the outerloop to verify in CI?

**Comment by hughbe** [comment]
Sure
@dotnet-bot help

**Comment by hughbe** [comment]
@dotnet-bot help

**Comment by hughbe** [comment]
@dotnet-bot test outerloop netcoreapp Windows_NT Debug
@dotnet-bot test outerloop netcoreapp Windows_NT Release

**Comment by MattGal** [comment]
@mmitche I will look at this when I get a chance.  Is there a way for me to get a specific time range for the logs mentioned?  It does indeed seem like the API fell over for a while there but the last time it logged (22:59:36) was way above the 500s.

@ChadNedzlek  may be interested as well.

**Pull request merged**
