### PR TITLE
Refactor System.Diagnostics.Process with a PAL layer

### PR DESCRIPTION
**Pull request by stephentoub**
This PR updates System.Diagnostics.Process with a PAL layer, refactoring the existing code to separate out the Windows functionality and add a set of corresponding Unix files (with stubbed out functionality). The change is primarily about moving functionality around.  Any new files added were populated with existing code from other existing files.  I also opportunistically cleaned up things in code I was touching, e.g. replacing try/finally blocks with usings where appropriate, getting rid of some unnecessary delegate types, removing unused namespace usings and renaming fields improperly named based on our naming conventions, etc., but I didn't make an end-to-end pass through all of the code to do such cleanups.

### CODE REVIEW

**Comment by stephentoub** [comment]
@ellismg, FYI.

**Comment by ellismg** [comment]
FYI, I did my pass over the files and made some comments.  Think we need a few small fixes before we merge this (at a minimum, some changes to field names).

**Comment by stephentoub** [comment]
Thanks, @ellismg.  I've addressed all of your feedback.

**Comment by ellismg** [comment]
LGTM.  Thanks, Steve.

**Comment by stephentoub** [comment]
Thanks.  @richamsft, I also validated this successfully against #333 locally, since the tests haven't been committed yet.

**Pull request merged**
