### PR TITLE
Update Buildtools

### PR DESCRIPTION
**Pull request by wtgodbe**
CC @weshaggard @joperezr @eerhardt 

Takes changes from https://github.com/dotnet/buildtools/pull/2048

### CODE REVIEW

**Comment by wtgodbe** [comment]
Will wait for CI

**Comment by ahsonkhan** [comment]
Are maestro auto-PRs broken?

**Comment by eerhardt** [comment]
@stephentoub @ahsonkhan - I was going to look at what happened to the auto-PRs.  Do you guys know?  This doesn't look updated for the past week...

**Comment by eerhardt** [comment]
FYI - @mmitche and I are investing what happened to the auto-PRs.  Will update when we know more.

**Pull request merged**
