### PR TITLE
Fix System.Runtime.Extensions tests for uap

### PR DESCRIPTION
**Pull request by danmosemsft**

### CODE REVIEW

**Comment by danmosemsft** [comment]
@safern updated.

**Comment by safern** [comment]
Might be worth adding "disabled-test" label to the issues associated to this disabled tests.

**Comment by danmosemsft** [comment]
Yeah, I'll clean that up later -- actually I'll ask vendors to do so. right now, speed is of the essence as we should have gotten to green already.

**Comment by safern** [comment]
Sounds good.

**Pull request merged**
