### PR TITLE
Fix WebSocketException.SetErrorCodeOnError to only set on error

### PR DESCRIPTION
**Pull request by stephentoub**
- Fix WebSocketException.SetErrorCodeOnError... it was setting it always rather than only on error, resulting in different behavior from desktop (http://referencesource.microsoft.com/#System/net/System/Net/WebSockets/WebSocketException.cs,197)
- As long as I was fixing that, I fixed the order of the arguments to Assert.Equal in the tests, as well as changing a few Equal calls to Same calls, and marking a few tests as [Fact]s so that they actually ran.

Fixes https://github.com/dotnet/corefx/issues/10913
cc: @cipop, @davidsh, @ericeil, @anurse

### CODE REVIEW

**Comment by davidsh** [comment]
On Desktop, it appears that .HResult has a default value of E_FAIL.

The current CoreFx code might be different from Desktop right now, but isn't the default now probably SUCCESS  (i.e. 0)?

In my mind, I don't understand why Desktop was written that way other than the comment in the code:

```c#
// Set the error code only if there is an error (i.e. nativeError >= 0). Otherwise the code messes up on deserialization as the Exception..ctor() throws on setting HResult to 0. The default for HResult is -2147467259.
```

Maybe CoreFx is the better way to do it?

**Comment by stephentoub** [comment]
> On Desktop, it appears that .HResult has a default value of E_FAIL.

Correct.

> The current CoreFx code might be different from Desktop right now, but isn't the default now probably SUCCESS (i.e. 0)?

The corefx code is different from desktop, which is what this was fixing.  This code:
```C#
using System;
using System.Net.WebSockets;

class Program
{
    static void Main()
    {
        Console.WriteLine(new WebSocketException(1).HResult);
        Console.WriteLine(new WebSocketException(0).HResult);
        Console.WriteLine(new WebSocketException(-1).HResult);
    }
}
```
outputs this on desktop:
```
-2147467259
-2147467259
-1
```
and this currently (before this PR) on corefx:
```
1
0
-1
```

> I don't understand why Desktop was written that way 

+1.  But it was. :smile:  Unless we have a good reason to diverge, we should be consistent, right?

**Comment by ericeil** [comment]
LGTM

**Comment by anurse** [comment]
LGTM. I'll update my existing PR to aspnet/WebSockets to include this change when it is merged in.

**Comment by stephentoub** [comment]
> I'll update my existing PR to aspnet/WebSockets to include this change when it is merged in.

I cc'd you just as an FYI... you shouldn't need to do anything in aspnet/Websockets.

**Comment by anurse** [comment]
Ah you're right, we don't pull in WebSocketException.

**Comment by davidsh** [comment]
>+1. But it was. :smile: Unless we have a good reason to diverge, we should be consistent, right?

Let's just go with desktop equivalence for now.

LGTM.

**Comment by stephentoub** [comment]
Ok, sounds good.

**Pull request merged**
