### PR TITLE
Test netstandardapp1.0

### PR DESCRIPTION
**Pull request by ericstj**
This makes all the tests resolve using NETCoreApp1.0 instead of
DNXCore50.  I've removed the netstandard1.6 import since that is no
longer needed.  I've also removed the workarounds from tests that were
targeting netcoreapp1.0 on their own.  For restore compat I've added an
DNXCore50 import to every test project.  These can be removed once
test-runtime packages are updated to target NETCoreApp1.0.

I've updated all the test scripts which were assuming DNXCore50 as well
as docs which referred to this path.
h

### CODE REVIEW

**Comment by ericstj** [comment]
@dotnet-bot test  Innerloop Windows_NT Release Build and Test

**Comment by ericstj** [comment]
@dotnet-bot test Innerloop Windows_NT Release Build and Test

**Comment by ericstj** [comment]
@dotnet-bot test  Innerloop CentOS7.1 Debug Build and Test
@dotnet-bot test  Innerloop CentOS7.1 Release Build and Test 
@dotnet-bot test  Innerloop Windows_NT Debug Build and Test

**Comment by ericstj** [comment]
@dotnet-bot test Innerloop Windows_NT Release Build and Test
@dotnet-bot test Innerloop OSX Release Build and Test
@dotnet-bot test Innerloop OSX Debug Build and Test
- AppContext failure

**Comment by ericstj** [comment]
Centos failing Guid tests, which @ellismg is working on: https://github.com/dotnet/corefx/pull/8840

**Comment by ellismg** [comment]
LGTM, thanks for this, Eric.

**Comment by ellismg** [comment]
@dotnet-bot test Innerloop CentOS7.1 Debug Build and Test please
@dotnet-bot test Innerloop CentOS7.1 Release Build and Test please

**Comment by ellismg** [comment]
@dotnet-bot test Innerloop OSX Debug Build and Test please (build machine went offline during build)

**Pull request merged**
