### PR TITLE
[Arm64/Unix] Add OfficialBuildRID linux-arm64

### PR DESCRIPTION
**Pull request by sdmaclea**

### CODE REVIEW

**Comment by sdmaclea** [comment]
@dotnet/arm64-contrib Not sure if this is too soon, but like to hear what is required before this can be merged.

One of many steps to resolve #10458 and get cli support on linux-arm64

**Comment by karelz** [comment]
@eerhardt are you the right person to code review such change? Or is it @janvorli?

**Comment by eerhardt** [comment]
I can take a look, or @weshaggard or @ericstj would be capable as well.

**Comment by gkhanna79** [comment]
This change looks fine - but have we added support to build the corresponding packages as part of the arm64 build @sdmaclea ?

**Comment by gkhanna79** [comment]
Likewise for CoreCLR as well?

**Comment by sdmaclea** [comment]
@gkhanna79 I do not know.  Is there something I should look for?  artifacts in the CI runs?  Code in *.groovy scripts?

**Comment by gkhanna79** [comment]
@sdmaclea When CoreCLR is built, we produce nuget packages for it using infra at https://github.com/dotnet/coreclr/blob/master/src/.nuget/packages.builds. You should ensure that it is happening for CoreCLR linux-arm64 builds.

**Comment by sdmaclea** [comment]
@jashook Looks like based on comments here https://github.com/dotnet/coreclr/blob/master/netci.groovy#L1707 arm64 linux does not have corefx ci running.  So I expect this PR is blocked by that?

**Comment by sdmaclea** [comment]
Added issue #21384 assuming linux-arm64 native builds are not occurring in CI.

**Comment by karelz** [comment]
@sdmaclea what is status of this PR? Do you plan to move it forward? Is it blocked on anything?

**Comment by sdmaclea** [comment]
@karelz I think the patch is functionally complete and correct.  However, I think it will break your release flow as corefx Arm64 binaries are not being built in CI (#12384).  I could take a shot at drafting the change to netci.groovy, but I would unable to test and also might be blocked by missing packages on your Ubuntu 16.04 machines (where I'd like to build arm64).  I think @jashook or another .NET CI expert would likely have more success.

**Comment by sdmaclea** [comment]
@wtgodbe Does the same apply here?  CI builds of arm64 native are not required before adding the RID?

**Comment by wtgodbe** [comment]
I'm less certain about CoreFX, @weshaggard or @jashook may know more here.

**Comment by weshaggard** [comment]
>@wtgodbe Does the same apply here? CI builds of arm64 native are not required before adding the RID?

I don't think CI is a requirement but we do need to ensure that we can actually build and are setup to produce an official build for arm64. @wtgodbe @jashook are one of you guys working on that?

**Comment by sdmaclea** [comment]
@weshaggard @jashook @wtgodbe I regularly cross build the native components regularly with
```
ROOTFS_DIR=<path>/arm64-xenial-rootfs
./build-native.sh -${buildType} -buildArch=arm64 -portableBuild
```

Once the ROOTFS had all the necessary packages, it has not failed since 1/2017.

**Comment by wtgodbe** [comment]
@weshaggard I can look into adding linux arm64 builds for CoreCLR if desired

**Comment by sdmaclea** [comment]
@weshaggard @karelz  Based on @weshaggard 's comment above, I believe this can be merged w/o breaking anything.

**Comment by weshaggard** [comment]
@wtgodbe can you please be sure there are issues for linux-arm64 for all our repo's (coreclr/corefx/core-setup)?

**Comment by wtgodbe** [comment]
@weshaggard https://github.com/dotnet/core-setup/issues/2969 https://github.com/dotnet/coreclr/issues/13212 https://github.com/dotnet/corefx/issues/22924

**Pull request merged**
