### PR TITLE
Deleting Logging.cs file and references

### LINKED ISSUE #5144: System.Net Logging Tracking Items
Tracking Items for https://github.com/dotnet/corefx/pull/5101

Formatting in *EventSource classes:
- [ ] Make constants have PascalCasing.
- [ ] Correctly separate arguments of methods in different lines (when needed).
- [ ] Add spaces needed in the attributes of the methods when not correctly aligned.
- [ ] New lines after if/else blocks (mainly after the IsEnabled check).

Dump Methods in SocketsEventSource:
- [ ] Analyse if the method type is necessary.Change if possible to receive a Socket (hash).
- [ ] Analyse if copying the buffer when it is received as an IntPtr to a byte [] is necessary. 
        Update: After trying in different ways, I couldn't make the event method work without making a copy to a byte[]. When using the predefined WriteEvent it would only log the address and not the array. I could not make an override method work properly. 

Keywords:
- [ ] Analyse if the right keywords are used for each event.

Logging.cs class
- [ ] Look for all the references done to this class in all projects and change calls to hash methods instead to LoggingHash.
- [ ] Delete Logging.cs (in both S:\corefx\src\Common\src\System\Net\Logging AND S:\corefx\src\common\src\system\net) 

Keep in sync with Localization:
- [ ]  https://github.com/dotnet/corefx/issues/5126

Testing
- [ ] Add some automated tests for the new EventSources created.

Compatibility
- [ ] Due to possible incompatibility between different versions of NetEventSource packaged inside distinct dlls, this class should not be changed in the future:

> The minute you have multiple copies of an EventSource that claim to be the same identity, you have the problem of who to 'believe' at runtime (each will send out a manifest for the events). Sure if they are the same, you are OK, but if they are in different modules, there is a pretty good chance they will ship at different times, and thus you might have machines that have one copy that is older than another. This creates a bunch of subtle error modes (new events may not be recognized) that would be very difficult to diagnose. We are trying to avoid subtlety like this.

Performance
- [x] Update System.Net.Sockets to avoid allocations/work at call sites when logging is disabled
- [x] Update System.Net.Security accordingly
- [x] Update System.Net.Ping accordingly
- [x] Update the rest of System.Net.\* accordingly
- [x] Remove GlobalLog.Assert(bool, ...) as it leads to bad habits

### PR DESCRIPTION
**Pull request by josguil**
Substituting Logging calls to EventSource calls, or calls to
LoggingHash.

Fix #5144

### CODE REVIEW

**Comment by josguil** [comment]
@CIPop @davidsh @stephentoub @pgavlin @weshaggard @ericstj PTAL.

**Comment by davidsh** [comment]
>Rather than passing around `this`, getting object names, etc., how about just using [CallerNameAttribute] and other such attributes where the compiler fills in the caller information for you?

+1

See for example:
https://msdn.microsoft.com/en-us/library/system.runtime.compilerservices.callermembernameattribute(v=vs.110).aspx

**Comment by josguil** [comment]
>NetEventSource is being included in multiple assemblies? Does that mean that each assembly could end up having an EventSource with the same ID?

Yes, NetEventSource is included in multiple assemblies. If by ID you mean either the name or the GUID, each assembly will log to the same NetEventSource listener, since the GUID is the same.

**Comment by josguil** [comment]
>Rather than passing around this, getting object names, etc., how about just using [CallerNameAttribute] and other such attributes where the compiler fills in the caller information for you?

Ok, I think for most of the "this" usages, I can do the change. But I think on the ones that need specifically the object name where the method call happens and not just the method it's not possible.

**Comment by stephentoub** [comment]
> Yes, NetEventSource is included in multiple assemblies. If by ID you mean either the name or the GUID, each assembly will log to the same NetEventSource listener, since the GUID is the same.

@vancem, is this the recommended approach, having event sources with the same name/GUID in multiple assemblies?

**Comment by vancem** [comment]
EventSource are not designed to be multi-instance.   The problem is the minute you have two EventSources that claim to be the same what happens when they are not (they each define different events/manifests?).   To avoid this problem EventSource enforces that only one EventSource can live in a given AppDomain (we would have liked to say machine wide, but that is harder).    If you try to do this you will get a exception when you turn on the EventSource (in general we try to do as little as possible when the EventSource is actually created, and instead do all that work when it is first turned on.  It is unfortunate that this defers finding errors like this but pay-for-play is more important).  

The guidance is that you should always create a static variable and initialize it with your EventSource.   Normal static variable initialization rules insure that get exactly one initialization.   

It sounds like the code is being cloned in multiple assemblies.  The 'obvious' thing to do is to have different names for each of the clones.   If that is not what you want from a logging perspective, then you have to set it up so that the clones cooperate to have only one (but notice, at that point logically both clones depend on a single 'parent' that contains EventSource (and versioning becomes a pain if assemblies version at different rates).

**Comment by josguil** [comment]
@vancem @stephentoub 

Thank you very much for your input Vance. Currently, we have one .cs file for NetEventSource. This is used by System.Net.Sockets and System.Net.Http (and some more). Each of those components only have one instance of NetEventSource and can be built independently. We'd like to continue having one common Event Source that registers events for those. This is because we don't want to duplicate the code for common events like Enter and Exit over each of our Event Sources, nor create a lot more of extra Event Sources (if we go that way, the we'll need to create a RequestsEventSource because of 2 logging lines in that project, and that's not the only project where a new event source would be needed because of a few couple of logging lines). What is the best approach? Can we stretch the AppDomain definition and say each System.Net component define its own AppDomain and therefore it's ok to have this common EventSource?

I also have to say this is not the only common Event Source. The Event Source currently used by GlobalLogging, "EventSourceLogging", is also common to many of the System.Net components. So, if this is a big problem, then we also need to modify the event Source used in Global Logging. And just in case you're wondering this, the difference between "EventSourceLogging" and "NetEventSource" is that GlobalLogging is more free in it's format.

**Comment by vancem** [comment]
@josguil 

First, there is an issue of simply what the code does.   Today, if you try to call an EventSource constructor with the same name twice in an AppDomain it will throw an exception when the EventSource is turned on.   Thus you get incorrect behavior.   This is a simple fact about the current implementation and there is no 'wiggle room' in the sense that the code does what it does.  You can debate why it is that way, but it does not change the fact that you have the constraint.   

However in this case there is a good reason the code does what it does.   The minute you have multiple copies of an EventSource that claim to be the same identity, you have the problem of who to 'believe' at runtime (each will send out a manifest for the events).   Sure if they are the same, you are OK, but if they are in different modules, there is a pretty good chance they will ship at different times, and thus you might have machines that have one copy that is older than another.   This creates a bunch of subtle error modes (new events may not be recognized) that would be very difficult to diagnose.  We are trying to avoid subtlety like this.   

Generally the right answer is to 'keep things simple'.  The concept is that you have a contract between the supplier and the consumer of events.  Thus if you have things that version at different rates, and one module can't depend on the other, then it really is telling you that you need two contracts (since they will not in general be identical (as one versions without the other versioning).    It is OK to share code, but you need something so that logically they are independent things (e.g. they each of different names).   This can be #ifdefs in the code, or using the EventSource(string, EventSourceSettings.ETWManifestFormat) constructor, so that you append the module name or something that insures that the name is unique.   

Alternatively, if you really are sharing the logging 'shape' among many assemblies, then that argues that your EventSource (and its contact) are shared.  Thus you should put it in one of your 'base' assemblies and simply refer to It from the others.    However you have to be careful about versioning to insure that if you use newly added logging events, that you require the correct version of the 'base' assembly that has the EventSource (this is no different than your module requiring new API surface from another module).  

The need to add new API surface can be reduced by keeping the logging contract 'generic'.   In particular it is not important that you have one distinct event method per instrumentation site.  What is important is that events that are likely to be processed in the same way share the same schema.    Thus it is OK to have a LogMessage(string) event, as long as 'string' is only meant for human consumption (processors don't need to parse it).   Having such generic contracts make it possible to add more logging without needing to update the EventSource.

**Comment by davidsh** [comment]
LGTM...But this PR needs to be rebased to resolve merge conflicts.

**Comment by josguil** [comment]
@dotnet-bot test this please

**Comment by josguil** [comment]
@dotnet-bot test this please 

(I think there were some problems with CI last time)

**Comment by CIPop** [comment]
Not sure why the CentOS and Ubuntu are failing. Looks like an infrastructure issue as I can't find any logs at this link:
http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/centos7.1_debug_prtest/855/?auto_refresh=false

**Comment by josguil** [comment]
Test Innerloop CentOS7.1 Debug Build and Test

**Comment by josguil** [comment]
Test Innerloop CentOS7.1 Release Build and Test

**Comment by josguil** [comment]
Test Innerloop Ubuntu Debug Build and Test

**Comment by raunakpandya** [comment]
@vancem 

>>> It is OK to share code, but you need something so that logically they are independent things (e.g. they each of different names). This can be #ifdefs in the code, or using the EventSource(string, EventSourceSettings.ETWManifestFormat) constructor, so that you append the module name or something that insures that the name is unique. 

Regarding the workaround you mentioned above, I tried placing the EventSource attribute declared above the common file under ifdef with different Name values but it still didn't seem to work. Am I doing something wrong?

**Comment by vancem** [comment]
Sorry for letting this slide.  If this is still an open question, about how to share code with EventSource we you should send me off line what you did and describe how it did not work and we can go from there...

**Pull request merged**
