### PR TITLE
Fix test project build warnings about dependency conflicts

### PR DESCRIPTION
**Pull request by stephentoub**
Several project.json files were still referencing the old xunit assemblies, causing such warnings during build.  Another had inconsistent versions of dependent libraries.

Fixing build warnings post #2798

cc: @ericstj, @weshaggard

### CODE REVIEW

**Comment by stephentoub** [comment]
@dotnet-bot test this please

**Comment by ericstj** [comment]
Build timed out... @dotnet-bot test this please

**Comment by ericstj** [comment]
Changes LGTM, let's see if we can get a passing CI

**Comment by stephentoub** [comment]
> let's see if we can get a passing CI

We've had a rash of problems this weekend. I spent the morning knocking them off, and this issue I've narrowed down to a hang in one test, which I'll disable shortly. That should get this passing, along with some of the other failing PRs.

**Comment by ericstj** [comment]
Might be fallout from my buildtools update.  It changed test arch to x64 and updated to the latest mscorlib/coreclr.

**Comment by stephentoub** [comment]
@dotnet-bot test this please

**Pull request merged**
