### PR TITLE
Update branding for 2.1.5

### PR DESCRIPTION
**Pull request by mmitche**

### CODE REVIEW

**Comment by mmitche** [comment]
@weshaggard PTAL

**Comment by weshaggard** [comment]
Sorry you also need to clear out the packages.builds file https://github.com/dotnet/corefx/blob/release/2.1/src/packages.builds#L26.

**Comment by mmitche** [comment]
@weshaggard @wtgodbe I think I got the packages.builds right.  I think the only thing that should be in there would be the newer fixes for System.Drawing Common.

**Comment by weshaggard** [comment]
Yes the change looks correct.

**Comment by weshaggard** [comment]
OSX machines still pending but all other legs pass and I don't expect this change to impact OSX in particular so merge.

**Pull request merged**
