### PR TITLE
[ARM/CI] Add arm-hardfp build to CI

### PR DESCRIPTION
**Pull request by wateret**
Now we have both hardfp and softfp build for ARM.

Related Issue : #12545

### CODE REVIEW

**Comment by stephentoub** [comment]
Can we avoid having all four legs on every PR?  The vast majority of PRs are not going to break any of these legs, nevermind be specialized enough to break one of them but not the others.

**Comment by wateret** [comment]
@stephentoub I removed hardfp build for prtest so there will be only 2 legs just like it is now. Is that what you meant?

**Comment by wateret** [comment]
@jashook Please let me know when my work for captured CI is applied. This PR must be merged after it is done.

**Comment by stephentoub** [comment]
@dotnet-bot test ci please

**Comment by stephentoub** [comment]
> Please let me know when my work for captured CI is applied. This PR must be merged after it is done.

@wateret, does this comment mean we shouldn't merge this now?

**Comment by wateret** [comment]
@stephentoub No we shouldn't yet. The rootfs for HardFP must be applied to CI, so please merge it after @jashook answers that it is done.

**Comment by stephentoub** [comment]
@jashook, could you comment?

**Comment by jashook** [comment]
This has been successfully merged. The changes that were made should have been captured.

**Comment by wateret** [comment]
@stephentoub Could you merge this please?

**Pull request merged**
