### PR TITLE
Enable tons of System.Runtime tests for uap

### PR DESCRIPTION
**Pull request by ViktorHofer**
as discussed.

### CODE REVIEW

**Comment by stephentoub** [comment]
I assume you verified locally these all pass?

**Comment by ViktorHofer** [comment]
Of course 🐰 no, in fact, the uapaot build is running right now locally and will take more time.

**Comment by ViktorHofer** [comment]
@dotnet-bot test CROSS Check

**Comment by ViktorHofer** [comment]
@dotnet-bot test CROSS Check

**Comment by ViktorHofer** [comment]
@dotnet/dnceng Cross check failing and not retriggering.

**Comment by ViktorHofer** [comment]
All tests are passing locally on uap.

**Comment by ViktorHofer** [comment]
@dotnet/dnceng worked by restarting it in Jenkins.

**Pull request merged**
