### PR TITLE
Fix EncryptedXmlTest.GetDecryptionIV_StringNull and expand ExcryptedXmlTest

### PR DESCRIPTION
**Pull request by anthonylangsworth**
Fix for `EncryptedXmlTest.GetDecryptionIV_StringNull` mentioned in #16685. Also cleaned up the tests a bit.

CC @krwq

### CODE REVIEW

**Comment by karelz** [comment]
We should not take any fixes / features until we have very good code coverage. @krwq are we there yet?

**Comment by anthonylangsworth** [comment]
@krwq Actually, I think I was meant to merge this into one of your branches. Is that correct?

**Comment by krwq** [comment]
@karelz I'm not seeing any desktop changes here - only test fixes
@anthonylangsworth - Thank you for sending this! I think it is better to have separate PR whenever possible so no one gets blocked on anyone 😉

**Comment by karelz** [comment]
Test fixes are fine. I thought it is product code change. Sorry for confusion.
And thanks @anthonylangsworth for your contribution!

**Comment by karelz** [comment]
BTW: What confused me was the linked issue #16685 which is enhancement, not test enhancement.

**Pull request merged**
