### PR TITLE
Rename OfflineBuild property to DotNetBuildOffline

### PR DESCRIPTION
**Pull request by ericstj**
This will also need to go to `release/3.0`

### CODE REVIEW

**Comment by dseefeld** [comment]
@ericstj I created a patch in source-build locally with this change in it to test building source-build and the resulting tarball.  On tarball build, I'm seeing an error:

`/src/tb-release3.0/src/corefx.1719a3fe2a5c81b67a4909787da4a02fb0d0d419/eng/notSupported.SourceBuild.targets(17,5): error : Error NotSupportedSourceFile '/src/tb-release3.0/src/generatedSrc/Microsoft.Win32.Registry.AccessControl/netcoreapp-Linux/Microsoft.Win32.Registry.AccessControl.notsupported.cs' did not exist under DotNetSourceBuildIntermediatePath. [/src/tb-release3.0/src/corefx.1719a3fe2a5c81b67a4909787da4a02fb0d0d419/src/Microsoft.Win32.Registry.AccessControl/src/Microsoft.Win32.Registry.AccessControl.csproj]`

Any suggestions on how to troubleshoot this?

**Comment by ericstj** [comment]
@dseefeld are you doing two pass build?  The first pass specifying `DotNetBuildFromSource=true;DotNetSourceBuildIntermediatePath=somePath`.  The second pass specifying  `DotNetBuildFromSource=true;DotNetSourceBuildIntermediatePath=somePath;DotNetBuildOffline=true`?

If so, then the thing to check would be that the files are being written correctly to `somepath` and that you pass the same path into the second pass of the build.

**Comment by ericstj** [comment]
Took a look at some logs shared offline and found the problem.  The path specified for DotNetSourceBuildIntermediatePath in the first pass was different than the one for the second pass.  They need to be the same in order to share the generated source.

**Comment by dseefeld** [comment]
@ericstj In the initial build, we're passing a path to generate the code to via `DotNetSourceBuildIntermediatePath`.  When we generate the tarball, we copy the src to a directory under ./src and then pass that path in `DotNetSourceBuildIntermediatePath`.  I compared the two directories just to be sure and the contents are identical.  The source that the error is complaining about `Microsoft.Win32.Registry.AccessControl/netcoreapp-Linux/Microsoft.Win32.Registry.AccessControl.notsupported.cs` does not exist.

**Comment by ericstj** [comment]
Chatted with @dseefeld offline and the latest change addresses the failure he was seeing.  Will merge this once green and port to release/3.0.

**Comment by karelz** [comment]
This PR went into master - fixing milestone to 5.0.
It was later ported into release/3.0 branch in PR #39979.

**Pull request merged**
