### PR TITLE
Improve XML comments with texts from MSDN

### PR DESCRIPTION
**Pull request by jbe2277**

### CODE REVIEW

**Comment by stephentoub** [comment]
@davkean, did I understand correctly that we were going to do some automated sweep to update all XML doc comments based on existing MSDN docs?

**Comment by davkean** [comment]
Yes, this will be automatically done.

**Comment by jbe2277** [comment]
Auto update of all XML doc comments makes sense. Therefore, this pull request can be ignored.

**Comment by weshaggard** [comment]
Thanks @jbe2277 for the understanding. I'm going to close this PR.

**Pull request closed without merging**
