### PR TITLE
Revert "Stop Expression.TypeEquals throwing on Nullable<T> parameter."

### PR DESCRIPTION
**Pull request by stephentoub**
Reverts dotnet/corefx#5273
Fixes https://github.com/dotnet/corefx/issues/5610
cc: @VSadov, @JonHanna, @joshfree

### CODE REVIEW

**Comment by stephentoub** [comment]
Test Innerloop CentOS7.1 Debug Build and Test please

**Comment by stephentoub** [comment]
Test Innerloop CentOS7.1 Debug Build and Test please

**Comment by mellinoe** [comment]
LGTM. We need some extra tests in the library to catch this issue in the future.

**Comment by JonHanna** [comment]
LGTM

I could submit a fix to the specific bug, but it probably makes more sense to do this and then re-submit a fix for #5272 that not only doesn't include the bug, but also adds a check for it.

**Comment by JonHanna** [comment]
@mellinoe when I revisit the worthwhile part of this PR I'll include a test that would hit it's bug.

**Comment by VSadov** [comment]
LGTM. 
Yes, lets accept this change and then redo original fix with more tests.

**Comment by JonHanna** [comment]
If nothing else it points to a gap in the `TypeEqual` tests, on a permutation I thought I'd covered.

**Comment by weshaggard** [comment]
@stephentoub are you working to get this change into the release branch?

**Comment by stephentoub** [comment]
> @stephentoub are you working to get this change into the release branch

I haven't been, no.

**Comment by weshaggard** [comment]
OK I will add this change to my package update as it is blocking the update to the packages in the release branch.

**Comment by stephentoub** [comment]
Wait, I misunderstood the question. Yes, I already submitted https://github.com/dotnet/corefx/pull/5636.

**Pull request merged**
