### PR TITLE
Fix System.Net.Http.Native build on CentOS

### PR DESCRIPTION
**Pull request by stephentoub**
The default install has an older libcurl that doesn't have CURL_HTTP_VERSION_2_0 defined.

cc: @mmitche, @eerhardt

### CODE REVIEW

**Comment by eerhardt** [comment]
One overall question:  What is the expected behavior in managed code on CentOS when a caller is requesting HTTP/2?  Are we doing the appropriate runtime checking for v2 support in libcurl and throwing a good exception?

**Comment by stephentoub** [comment]
> Are we doing the appropriate runtime checking for v2 support in libcurl and throwing a good exception?

We fall back to using the libcurl default (1.1) if 2.0 isn't available.

**Comment by eerhardt** [comment]
OK - LGTM.

**Comment by stephentoub** [comment]
Thanks, Eric.

**Pull request merged**
