### PR TITLE
Remove Microsoft.VisualBasic.{ApplicationServices,Devices,MyServices}

### PR DESCRIPTION
**Pull request by cston**
## Description

A number of types in Microsoft.VisualBasic.Core.dll are only partially ported in .NET Core 3.0 and some of those types have dependencies on `System.Windows.Forms` in the code that remains to be ported. 
 
The types that will depend on WinForms should be removed from dotnet/corefx in 3.0 to avoid layering issues or breaking changes when those types are fully ported (in dotnet/winforms presumably) in a later release.

Specifically, the types in `Microsoft.VisualBasic.{ApplicationServices,Devices,MyServices}` should be removed.

## Customer Impact

The types in `Microsoft.VisualBasic.{ApplicationServices,Devices,MyServices}` were added to Microsoft.VisualBasic.Core.dll in .NET Core 3.0, so this represents a breaking change from earlier previews.

The types in those namespaces will not be available in .NET Core 3.0.

## Regression?

No, the types were added in .NET Core 3.0.

## Risk

Medium risk. Removing types will require changes to the SDK: see https://github.com/dotnet/sdk/pull/3513.

### CODE REVIEW

**Comment by stephentoub** [comment]
Presumably this is a must-have for 3.0? These were only added in 3.0 right?

@danmosemsft, for things that are "do it in 3.0 or else never", should we instead start with PRs to release/3.0 and then port to master?

**Comment by cston** [comment]
@stephentoub, I believe these namespaces were added in 3.0, specifically in https://github.com/dotnet/corefx/pull/31185 and https://github.com/dotnet/corefx/pull/37085.

**Comment by danmosemsft** [comment]
> @danmosemsft, for things that are "do it in 3.0 or else never", should we instead start with PRs to release/3.0 and then port to master

If you want but does it matter?

**Comment by stephentoub** [comment]
> does it matter?

It would otherwise get checked into master, and then if it didn't pass ask mode, backed out of master, because if it's not in 3.0, it would be a breaking change to do in 5.0

**Comment by danmosemsft** [comment]
Fair enough

**Comment by danmosemsft** [comment]
@cton this will need the ask mode template and the "ask-mode" label  - example https://github.com/dotnet/corefx/pull/40043#issuecomment-518413505

**Comment by danmosemsft** [comment]
This was approved by tactics, you can merge when we open for Preview 9 assuming reviewed/green

**Comment by cston** [comment]
@jaredpar, @333fred, @nguerrera, please review this change for 3.0.

**Comment by wtgodbe** [comment]
As per @cston, we should not merge this until we have approval on https://github.com/dotnet/sdk/pull/3513

**Comment by nguerrera** [comment]
https://github.com/dotnet/sdk/pull/3513 has been approved and merged, so this should be ok to merge.

**Pull request merged**
