### PR TITLE
Set exit codes for wrapper scripts if there is an error.

### PR DESCRIPTION
**Pull request by chcosta**
VSO will not report errors unless either the exit code is set or the "Fail on standard error" option is set and text is redirected to the error stream.  This change sets exit codes for scripts which were not explicitly setting them.

/cc @weshaggard , @maririos 

@weshaggard , is there a reason not to both set the exit codes AND redirect the error text to the error stream?  Setting the exit codes should unblock my needs though.

### CODE REVIEW

**Comment by chcosta** [comment]
@dotnet-bot test Innerloop Windows_NT Debug Build and Test
@dotnet-bot test Innerloop Windows_NT Release Build and Test

**Comment by weshaggard** [comment]
>@weshaggard , is there a reason not to both set the exit codes AND redirect the error text to the error stream? Setting the exit codes should unblock my needs though.

I have no issues redirecting the error messages to both the std out and std err.

**Comment by weshaggard** [comment]
LGTM

**Comment by maririos** [comment]
LGTM

**Pull request merged**
