### PR TITLE
Upgrade dotnet cli version

### PR DESCRIPTION
**Pull request by dagood**
This upgrade takes fix to https://github.com/NuGet/Home/issues/2416 and adds `--infer-runtimes` for futureproofing.

(I'm also going to be upgrading wcf, coreclr, and buildtools.)

Open question: is that the right version of dotnet CLI to install? (dev vs. shared framework?)

/cc @eerhardt @ericstj @mmitche

### CODE REVIEW

**Comment by eerhardt** [comment]
> Open question: is that the right version of dotnet CLI to install? (dev vs. shared framework?)

You want "dev" because that has the actual "CLI" in it and it contains the shared framework.  The other installer (dotnet-win-*arch*.*version*.exe) only contains the shared framework.  So you can't do things like `dotnet restore` with it.

**Comment by stephentoub** [comment]
@dotnet-bot test this please

**Comment by dagood** [comment]
This now uses version 002111 which seems more likely to be available for all platforms. (The 002115 version I saw first wasn't.)

I've briefly tested on Windows and OSX. I don't know for sure about Linux and other platforms but this PR is probably good now.

**Comment by stephentoub** [comment]
LGTM.  Let's get these merged to help unblock CI.

**Pull request merged**
