### PR TITLE
Fix passing null for credentials in SqlConnectionPoolKey in master

### PR DESCRIPTION
**Pull request by AfsanehR**
Fixes #34260

### CODE REVIEW

**Comment by danmosemsft** [comment]
@dotnet-bot test linux arm64 release build please

**Comment by AfsanehR** [comment]
@dotnet-bot test linux arm64 release build please

**Comment by AfsanehR** [comment]
@dotnet-bot  test Linux x64 Release Build

**Comment by keeratsingh** [comment]
Looks good. Approved.

**Pull request merged**
