### PR TITLE
[System.Private.Xml.Linq] Rename FunctionalTests classes

### PR DESCRIPTION
**Pull request by MaximLipnin**
It allows to fix build issues and makes easier import System.Private.Xml.Linq tests to Mono (https://github.com/mono/mono/issues/8122).

### CODE REVIEW

**Comment by krwq** [comment]
@MaximLipnin I do not see any value of this PR in corefx but if it helps mono and there is no functional changes in the tests I'm fine with merging this.

If there is any test logic changes please add comments as this PR is large enough it is easy to miss something

**Comment by MaximLipnin** [comment]
@krwq It looks like there were no problems with tests in import tasks related to other corefx parts. But System.Private.Xml.Linq has a bit more complicated test infrastructure with several test projects which, in their turn, contain many identically named partial classes (FunctionalTests) in the same namespace. At the moment in mono I have to use all corefx test source code in a single project that leads to some build issues like duplicated class names. So one of possible solution is to rename corefx classes that allows to fix the build issues and run imported corefx tests in mono. 

As for PR I just renamed FunctionalTest classes to some unique names and removed partial keyword because it doesn't make sense after renaming. Also I updated reference objects where it needed. There are no any changes in test logic.

I understand that this PR doesn't have any value for corefx. So if you have any concern about it please let me know.

**Comment by pjanotti** [comment]
LGTM. @MaximLipnin are there any other similar blockers or this is a special case?

**Comment by MaximLipnin** [comment]
@dotnet-bot test Linux x64 Release Build
@dotnet-bot test Linux-musl x64 Debug Build
@dotnet-bot test Packaging All Configurations x64 Debug Build

**Comment by MaximLipnin** [comment]
@dotnet-bot test Packaging All Configurations x64 Debug Build

**Comment by pjanotti** [comment]
Some tests in this project are Outerloop, so let's run some Outerloops before merging this one.

@dotnet-bot test Outerloop Linux x64 Debug Build
@dotnet-bot test Outerloop Windows x64 Debug Build
@dotnet-bot test Outerloop OSX x64 Debug Build

**Comment by pjanotti** [comment]
Failure on Linux x64 Release are unrelated to these changes. If passes outer loop below we will merge it.

@dotnet-bot test Outerloop Linux x64 Debug Build
@dotnet-bot test Outerloop Windows x64 Debug Build
@dotnet-bot test Outerloop OSX x64 Debug Build

**Comment by pjanotti** [comment]
Passed outerloop, merging...

**Pull request merged**
