### PR TITLE
Temporarily changing System.Runtime.Extensions perf tests to run as netcoreapp1.1 to unblock official build

### PR DESCRIPTION
**Pull request by joperezr**
cc: @chcosta @weshaggard @markwilkie @Chrisboh

### CODE REVIEW

**Comment by weshaggard** [comment]
LGTM

**Comment by weshaggard** [comment]
I've got to run right now but can someone please merge this before 6PM once the CI passes? (Thanks @stephentoub :))

**Comment by joperezr** [comment]
> I've got to run right now but can someone please merge this before 6PM once the CI passes? 

I'll take care of this.

**Comment by joperezr** [comment]
@weshaggard actually I'm not sure all of the CI's would be done by 6PM given that my OSXs builds are still in queue to get started and they usually take more than 1 hour. I'll wait to right before 6PM and if I don't see any reds and at least one CI is done I'll merge it.

**Comment by stephentoub** [comment]
> Thanks @stephentoub :)

Heh :)

**Comment by joperezr** [comment]
The Centos error was not related to this PR and the rest of the builds haven't finished. Merging this now so that it gets picked up by 6pm build.

**Pull request merged**
