### PR TITLE
Move NETStandard docs and rename, add doc for NETStandardApp

### PR DESCRIPTION
**Pull request by ericstj**
/cc @Petermarcu @richlander @davidfowl 

Is .NET Platform Standard the right terminology?  Folks have been referring to this as .NET Standard or .NET Standard Platform so the inversion of words is just confusing, especially when platform doesn't show up in any of the actual monikers.

### CODE REVIEW

**Comment by akoeplinger** [comment]
If you rename project-docs/standard-platform.md then a lot of links will break. It's better to leave it and point to the new doc, at least for some time.

**Comment by davidfowl** [comment]
+1

**Comment by ericstj** [comment]
OK, can I remove the content of the doc at the old location or do I need to preserve #links?

Also, can you comment on the platform question @davidfowl?  A couple folks have asked me about this and I raised a similar concern in https://github.com/dotnet/corefx/pull/5729.

**Comment by ericstj** [comment]
ping.
@dotnet-bot please test  Innerloop Ubuntu Release Build and Test

**Comment by ericstj** [comment]
ping

**Comment by ericstj** [comment]
@davidfowl this is getting merged unless I hear feedback in the next 24 hours.  @richlander is this new name and location satisfactory?

**Comment by richlander** [comment]
LGTM

It would be a good idea to do the forward pointer thing. It's cheap.

**Comment by ericstj** [comment]
@richlander I did add a pointer in the file.  Is there someway to have github do an HTTP redirect?

**Comment by richlander** [comment]
@ericstj  Fine q. I am doubtful. I'm not even sure that it's the right option.

I'd be happy for us to put a "This file has move to here" for now and then delete the file in a couple months. I don't see a need to keep the redirect forever. I'm fine if the link breaks for old links. While GitHub blurs the lines a lot, this is a repo not a website.

**Comment by ericstj** [comment]
Ok, I have the pointer: https://github.com/dotnet/corefx/pull/5669/files#diff-186ce82c6e4a26452b42d327633d5dfdR1.  I'll go ahead an merge this.

**Comment by akoeplinger** [comment]
+1. Just saw that there are a few docs in other repos point to the old file: https://github.com/search?utf8=%E2%9C%93&q=standard-platform+org%3Adotnet&type=Code&ref=searchresults

**Comment by cartermp** [comment]
@akoeplinger thanks for bringing that up!  We'll have to adjust some links in the core-docs content.

**Pull request merged**
