### PR TITLE
[Port to RTM]These changes fix the Windows Nano Server Test run.

### PR DESCRIPTION
**Pull request by Priya91**
cc @joshfree

### CODE REVIEW

**Comment by Priya91** [comment]
@dotnet-bot Test Windows Nano Server 2016 Release

**Comment by Priya91** [comment]
@dotnet-bot Test outerloop Windows Nano 2016 Release

**Comment by Priya91** [comment]
fixes #9168

**Comment by joshfree** [comment]
@Priya91 please take a look at failing CI

**Comment by Priya91** [comment]
@joshfree The CI is failing with this bug #9198

**Comment by joshfree** [comment]
Approved Test-Only changes

**Pull request merged**
