### PR TITLE
Build native before building managed on Unix.

### PR DESCRIPTION
**Pull request by Priya91**
cc @dagood @kapilash

### CODE REVIEW

**Comment by Priya91** [comment]
@dotnet-bot test outerloop ubuntu14.04 debug

**Comment by stephentoub** [comment]
LGTM

**Comment by dagood** [comment]
LGTM, but wasn't it OSX outerloop with the errors? Maybe it's the same on Ubuntu, but I'll kick this off in case it's useful: @dotnet-bot test OuterLoop OSX Debug

**Comment by Priya91** [comment]
@dagood This is not intended to fix any errors. In CI we use run-test.sh script on innerloop unix runs, which points to the native bins. Only the outerloop ubuntu14.04 and OSX runs use the build.sh. And build.sh is not using the locally built native shims, that's why we are not seeing problems with the reversed order. It should be using the nuget ones, going through the build logs. And TestWithLocalLibraries is not applying to the native shims, as seen from ```publishtest.targets```. This is a first step to use the locally built native shims with that msbuild option. Will sync up with @ericstj on this.

**Comment by dagood** [comment]
Ah, alright, thanks.

**Comment by kapilash** [comment]
Thanks @Priya91

**Pull request merged**
