### PR TITLE
Updating the Roslyn Toolset to 3.0.0-beta3-final

### PR DESCRIPTION
**Pull request by tannergooding**
CC. @jaredpar, @agocke, @jkotas, @danmosemsft, @eerhardt, @safern, @ericstj

The beta3 package was pushed up to NuGet today.

### CODE REVIEW

**Comment by tannergooding** [comment]
I've updated the `Versions.Details.xml` file. It would be nice to eventually get this automated 😄

**Comment by tannergooding** [comment]
@safern, the `Send To Helix` step is failing, even after a couple of retries.

**Comment by safern** [comment]
> @safern, the `Send To Helix` step is failing, even after a couple of retries.

Yeah, it fails when there are test failures, in this case, it is failing to download the zip file needed to run the tests. I'm taking a look already.

**Comment by safern** [comment]
Tracking issue: https://github.com/dotnet/core-eng/issues/5241

**Comment by safern** [comment]
It seems like the issue was with a corrupt machine that @MattGal just confirmed it is already dead. So he said we can try again and see if it reproes again in another machine (it shouldn't). I'm rerunning the job.

**Comment by safern** [comment]
Ok, so the issue is fixed. There are no more failures related to downloading the archive. However there where 4 other failures due to networking flaky tests where it couldn't reach the service. I think we can merge this PR.

**Pull request merged**
