### PR TITLE
Fix System.Diagnostics.Process failures with disabled Remote Registry service

### PR DESCRIPTION
**Pull request by jkotas**

### CODE REVIEW

**Comment by jkotas** [comment]
The Remote Registry service is disabled by default in the latest Windows 10 that caused this test to fail with "System.InvalidOperationException : Couldn't connect to remote machine." error.

**Comment by drieseng** [comment]
Wouldn't it be better to detect that the service is not running, and add a condition to the tests that rely on this service?

That said, I see that this test already silently drops other exceptions :(

**Comment by jkotas** [comment]
Other tests in this file provide comprehensive coverage for `Process.GetProcesses` with machine name specified.

This tests does not add interesting managed code coverage. It is adding coverage for underlying OS and the validation that it does it very weak (just that it does not crash and that the result is not empty). I was considering to just deleting this test...

**Comment by jkotas** [comment]
I have made the test to look the same as other tests in this file that depend on performance counters.

**Pull request merged**
