### PR TITLE
Cleanup System.Net.Requests tests

### PR DESCRIPTION
**Pull request by davidsh**
Switch remaining tests to use the new test server.
Fix up 'var' usage.
Use 'async Task' pattern and 'await' instead of GetResult() for tests.

### CODE REVIEW

**Comment by davidsh** [comment]
@CIPop @stephentoub PTAL

**Comment by davidsh** [comment]
CI failure: http://dotnet-ci.cloudapp.net/job/dotnet_corefx_prtest/6242/

GitHub Timeout

Timeout cloning repo from GitHub.

**Comment by davidsh** [comment]
@dotnet-bot test this please

**Comment by davidsh** [comment]
CI failure: http://dotnet-ci.cloudapp.net/job/dotnet_corefx_prtest/6245/

GitHub Mac timeout
Linux unspecified crash

**Comment by davidsh** [comment]
@dotnet-bot test this please

**Comment by stephentoub** [comment]
@dotnet-bot test this please (GitHub timeout)

**Comment by stephentoub** [comment]
LGTM

**Pull request merged**
