### PR TITLE
ARM-CI: Enable build of managed components

### PR DESCRIPTION
**Pull request by prajwal-aithal**
To ensure that the native and managed components
are built on the same source code, enable managed
build as well. Tests are not needed

Signed-off-by: Prajwal A N <an.prajwal@samsung.com>

### CODE REVIEW

**Comment by prajwal-aithal** [comment]
@jashook @Priya91 I have test this change on my local emulator version. Can we merge this immediately for me to check that it works on the current emulator version in the CI system?

**Comment by prajwal-aithal** [comment]
cc: @myungjoo @leemgs

**Comment by prajwal-aithal** [comment]
@dotnet-bot test CI please

**Comment by prajwal-aithal** [comment]
I confirm that this PR works as expected on the emulator.

**Comment by Priya91** [comment]
LGTM

**Pull request merged**
