### PR TITLE
Changed internal value to readonly for primitive types

### PR DESCRIPTION
**Pull request by tgiphil**
See PR in CoreCLR: https://github.com/dotnet/coreclr/pull/18645

### CODE REVIEW

**Comment by jkotas** [comment]
@dotnet-bot test this please

**Comment by karelz** [comment]
@pjanotti can you please help to move the PR forward?

**Comment by jkotas** [comment]
@dotnet-bot test this please

**Comment by jkotas** [comment]
Will close & reopen to reset the CI

**Comment by jkotas** [comment]
@tgiphil Looks like you have missed marking Single and Double as readonly. Could you please submit PR to CoreCLR repo to fix it?

**Comment by tgiphil** [comment]
Done. See https://github.com/dotnet/coreclr/pull/19052.

**Comment by danmosemsft** [comment]
@dotnet-bot test this please

**Comment by pjanotti** [comment]
Still hitting ApiCompat issues:

Packaging All Configurations x64 Debug Build:

```
D:\j\workspace\windows-TGrou---0d2c9ac4\Tools\ApiCompat.targets(58,5): error : TypeCannotChangeClassification : Type 'System.Double' is marked as readonly in the contract so it must also be marked readonly in the implementation. [D:\j\workspace\windows-TGrou---0d2c9ac4\src\System.Runtime\src\System.Runtime.csproj]
D:\j\workspace\windows-TGrou---0d2c9ac4\Tools\ApiCompat.targets(58,5): error : TypeCannotChangeClassification : Type 'System.Single' is marked as readonly in the contract so it must also be marked readonly in the implementation. [D:\j\workspace\windows-TGrou---0d2c9ac4\src\System.Runtime\src\System.Runtime.csproj]
D:\j\workspace\windows-TGrou---0d2c9ac4\Tools\ApiCompat.targets(72,5): error : ApiCompat failed for 'D:\j\workspace\windows-TGrou---0d2c9ac4\bin\Windows_NT.AnyCPU.Debug\System.Runtime\uapaot\System.Runtime.dll' [D:\j\workspace\windows-TGrou---0d2c9ac4\src\System.Runtime\src\System.Runtime.csproj]
```

Tizen armel Debug Build:
```
/opt/corefx/Tools/ApiCompat.targets(58,5): error : TypeCannotChangeClassification : Type 'System.Boolean' is marked as readonly in the contract so it must also be marked readonly in the implementation. [/opt/corefx/src/System.Runtime/src/System.Runtime.csproj]
/opt/corefx/Tools/ApiCompat.targets(58,5): error : TypeCannotChangeClassification : Type 'System.Byte' is marked as readonly in the contract so it must also be marked readonly in the implementation. [/opt/corefx/src/System.Runtime/src/System.Runtime.csproj]
/opt/corefx/Tools/ApiCompat.targets(58,5): error : TypeCannotChangeClassification : Type 'System.Char' is marked as readonly in the contract so it must also be marked readonly in the implementation. [/opt/corefx/src/System.Runtime/src/System.Runtime.csproj]
/opt/corefx/Tools/ApiCompat.targets(58,5): error : TypeCannotChangeClassification : Type 'System.Double' is marked as readonly in the contract so it must also be marked readonly in the implementation. [/opt/corefx/src/System.Runtime/src/System.Runtime.csproj]
/opt/corefx/Tools/ApiCompat.targets(58,5): error : TypeCannotChangeClassification : Type 'System.Int16' is marked as readonly in the contract so it must also be marked readonly in the implementation. [/opt/corefx/src/System.Runtime/src/System.Runtime.csproj]
/opt/corefx/Tools/ApiCompat.targets(58,5): error : TypeCannotChangeClassification : Type 'System.Int32' is marked as readonly in the contract so it must also be marked readonly in the implementation. [/opt/corefx/src/System.Runtime/src/System.Runtime.csproj]
/opt/corefx/Tools/ApiCompat.targets(58,5): error : TypeCannotChangeClassification : Type 'System.Int64' is marked as readonly in the contract so it must also be marked readonly in the implementation. [/opt/corefx/src/System.Runtime/src/System.Runtime.csproj]
/opt/corefx/Tools/ApiCompat.targets(58,5): error : TypeCannotChangeClassification : Type 'System.IntPtr' is marked as readonly in the contract so it must also be marked readonly in the implementation. [/opt/corefx/src/System.Runtime/src/System.Runtime.csproj]
/opt/corefx/Tools/ApiCompat.targets(58,5): error : TypeCannotChangeClassification : Type 'System.SByte' is marked as readonly in the contract so it must also be marked readonly in the implementation. [/opt/corefx/src/System.Runtime/src/System.Runtime.csproj]
/opt/corefx/Tools/ApiCompat.targets(58,5): error : TypeCannotChangeClassification : Type 'System.Single' is marked as readonly in the contract so it must also be marked readonly in the implementation. [/opt/corefx/src/System.Runtime/src/System.Runtime.csproj]
/opt/corefx/Tools/ApiCompat.targets(58,5): error : TypeCannotChangeClassification : Type 'System.UInt16' is marked as readonly in the contract so it must also be marked readonly in the implementation. [/opt/corefx/src/System.Runtime/src/System.Runtime.csproj]
/opt/corefx/Tools/ApiCompat.targets(58,5): error : TypeCannotChangeClassification : Type 'System.UInt32' is marked as readonly in the contract so it must also be marked readonly in the implementation. [/opt/corefx/src/System.Runtime/src/System.Runtime.csproj]
/opt/corefx/Tools/ApiCompat.targets(58,5): error : TypeCannotChangeClassification : Type 'System.UInt64' is marked as readonly in the contract so it must also be marked readonly in the implementation. [/opt/corefx/src/System.Runtime/src/System.Runtime.csproj]
/opt/corefx/Tools/ApiCompat.targets(58,5): error : TypeCannotChangeClassification : Type 'System.UIntPtr' is marked as readonly in the contract so it must also be marked readonly in the implementation. [/opt/corefx/src/System.Runtime/src/System.Runtime.csproj]
/opt/corefx/Tools/ApiCompat.targets(72,5): error : ApiCompat failed for '/opt/corefx/bin/Unix.AnyCPU.Debug/System.Runtime/netcoreapp/System.Runtime.dll' [/opt/corefx/src/System.Runtime/src/System.Runtime.csproj]
```

UWP NETNative x86 Release Build:

```
D:\j\workspace\windows-TGrou---c60886e1\Tools\ApiCompat.targets(58,5): error : TypeCannotChangeClassification : Type 'System.Double' is marked as readonly in the contract so it must also be marked readonly in the implementation. [D:\j\workspace\windows-TGrou---c60886e1\src\System.Runtime\src\System.Runtime.csproj]
D:\j\workspace\windows-TGrou---c60886e1\Tools\ApiCompat.targets(58,5): error : TypeCannotChangeClassification : Type 'System.Single' is marked as readonly in the contract so it must also be marked readonly in the implementation. [D:\j\workspace\windows-TGrou---c60886e1\src\System.Runtime\src\System.Runtime.csproj]
D:\j\workspace\windows-TGrou---c60886e1\Tools\ApiCompat.targets(72,5): error : ApiCompat failed for 'D:\j\workspace\windows-TGrou---c60886e1\bin\Windows_NT.AnyCPU.Release\System.Runtime\uapaot\System.Runtime.dll' [D:\j\workspace\windows-TGrou---c60886e1\src\System.Runtime\src\System.Runtime.csproj]
```

**Comment by jkotas** [comment]
> Tizen armel Debug Build

These failures are caused by Tizen build picking up state CoreCLR build. Looks like an infrastructure problem. @tgiphil Could you please rebase the change against the current master to see whether it helps?

> UWP NETNative x86 Release Build:

This is blocked by ProjectN codeflow latency. It will get fixed on its own once the ProjectN bits with this change reach CoreFX. It can be worked around by adding the two warnings to https://github.com/dotnet/corefx/blob/master/src/System.Runtime/src/ApiCompatBaseline.uapaot.txt .

**Comment by tgiphil** [comment]
@jkotas Rebased to corefix/master (git rebase corefx/master) and updated ApiCompatBaseline.uapaot.txt.

Feel free to make additional changes, if you want to push this faster than I can respond.

**Comment by jkotas** [comment]
@dotnet-bot test Linux arm Release Build  please

**Pull request merged**
