### PR TITLE
Allow Tool host CLI to be copied from local directory

### PR DESCRIPTION
**Pull request by mellinoe**
This helps folks who want to copy a local version of the CLI (perhaps a bootstrap version for a new distro) to be used as the Tools host.

@ellismg , @janvorli

### CODE REVIEW

**Comment by mellinoe** [comment]
https://github.com/dotnet/corefx/pull/12555/files?w=1

**Comment by ellismg** [comment]
I had made similar changes in https://github.com/dotnet/coreclr/pull/7554/commits/b8a043ab6743a3f41518a5da82100a400300cbc7 for both buildtools and dotnetcli.  The major difference was I expected an environment variable that was a folder which had sub-folders corresponding to the different versions (I wanted this for cases where repos didn't unify on the same version).

Is doing something like that acceptable?

**Comment by mellinoe** [comment]
@ellismg That change seems fine to me. It'll be a bit more awkward needing to put the stuff into a particular folder structure, but it's not a big deal. Were you planning on making those changes in master as well, or just as a targeted thing for rel/1.1.0?

**Comment by ellismg** [comment]
@mellinoe 

> Were you planning on making those changes in master as well, or just as a targeted thing for rel/1.1.0?

I was going to bring them into master as well.  I can open a PR a little later today if you'd like?

**Comment by mellinoe** [comment]
Sounds good. I am going to close this in favor of that.

**Pull request closed without merging**
