### PR TITLE
Add Español Windows 19H1 queue in PRs

### PR DESCRIPTION
**Pull request by ViktorHofer**

### CODE REVIEW

**Comment by MattGal** [comment]
@ViktorHofer there was a small problem that I've since fixed, I clicked rerun and it should be OK now.

**Comment by safern** [comment]
damn it I forgot to include corefx-ci in my comment and ran outerloop, oh well, more coverage 😄

**Review by safern — APPROVED** [review]

**Review by stephentoub — APPROVED** [review]

**Review by MattGal — APPROVED** [review]
Seems fine, make sure you meant to get rid of english...

**Comment by safern** [comment]
> Seems fine, make sure you meant to get rid of english...

Seems like this is what we had before: https://github.com/dotnet/corefx/commit/6549a93fb462f581696af11a3be076d36309dc7e

**Comment by MattGal** [comment]
Just a heads up, both of these Client SKUs are VERY slow to provision as Azure VMs, and you might consider if you haven't had specific scenarios where stuff was broken just for a Client SKU not using these for CI.

**Comment by stephentoub** [comment]
@MattGal, are there equivalent server SKUs available?

**Comment by MattGal** [comment]
@stephentoub we don't directly have such images but I'll chat with DDFUN folks about whether they already have spanish base Server SKUs available (I don't believe the Azure gallery does, unfortunately)

**Comment by stephentoub** [comment]
Thanks.  Doesn't have to be Spanish; just not English.

**Comment by ViktorHofer** [comment]
> Just a heads up, both of these Client SKUs are VERY slow to provision as Azure VMs

I just noticed this in our builds again. @MattGal any update regarding Server SKUs for 19H1/2?

**Comment by ViktorHofer** [comment]
Let's move the discussion over to https://github.com/dotnet/corefx/issues/41853

**Comment by MattGal** [comment]
I know we have folks working to move all the build agents to server SKUs but I am unsure if there's an issue for plain queues like that, so I created https://github.com/dotnet/core-eng/issues/8143.

**Pull request merged**
