### PR TITLE
Build Platforms package for 2.2.5

### PR DESCRIPTION
**Pull request by wtgodbe**
We should catch this package up for the external folks who depend on the 2.2.0 version of it, which has missed some of the recent RID graph changes in release/2.1. This will also help out the folks who depend on M.NC.App 2.2 (see https://github.com/aspnet/EntityFrameworkCore/issues/14504, https://github.com/dotnet/core-setup/issues/5562).

Don't merge until branches open for 2.2.5.

CC @ericstj @dagood @mmitche 

#### Description 
We shipped `M.NC.Platforms` out of 2.2 & 2.1 initially, and have since only shipped updates out of 2.1. We should ship an update out of 2.2 to "catch up" the folks who depend on the 2.2.0 version of the package.

#### Customer Impact 
Customers depending on 2.2.0 will get the latest version of the RID graph

The workaround for them would be to 'downgrade' to the latest 2.1 package instead of targeting 2.2. If they want to keep targeting 2.2, we'd need to provide an updated version of the 2.2 package.

#### Regression? 
None

#### Packaging reviewed?  
Yes

#### Risk 
Low

This does set the precedent that we may have to ship another version of Platforms out of 2.2 in the future. I don't believe we could break anyone by shipping this update, any potential problems should have already been exposed when we shipped the 2.1 versions of the package.

### CODE REVIEW

**Comment by wtgodbe** [comment]
@danmosemsft does this need to go through shiproom?

**Comment by danmosemsft** [comment]
> Customer Impact
> Customers depending on 2.2.0 will get the latest version of the RID graph

@wtgodbe What is the impact the customer experiences. For example, it seems it is causing the crash in https://github.com/aspnet/EntityFrameworkCore/issues/14504 ? Is there a workaround?

> Risk
> None

This is rarely true 😎 Can we think of any potentially negative consequences of taking this fix? Any way it might break someone? Or is the risk essentially just the (non zero) risk of any code change?

**Comment by wtgodbe** [comment]
> @wtgodbe What is the impact the customer experiences. For example, it seems it is causing the crash in aspnet/EntityFrameworkCore#14504 ? Is there a workaround?

The workaround for them would be to 'downgrade' to the latest 2.1 package instead of targeting 2.2. If they want to keep targeting 2.2, we'd need to provide an updated version of the 2.2 package.

> This is rarely true 😎 Can we think of any potentially negative consequences of taking this fix? Any way it might break someone? Or is the risk essentially just the (non zero) risk of any code change?

This does set the precedent that we may have to ship another version of Platforms out of 2.2 in the future. I don't believe we could break anyone by shipping this update, any potential problems should have already been exposed when we shipped the 2.1 versions of the package.

**Comment by vivmishra** [comment]
Approved for 2.2.5
Wait for branch to open.

**Comment by joperezr** [comment]
We need to do the same thing for 2.1 release branch. Also, we need to update core-setup so that the Microsoft.NETCore.App package depends on these new versions of the platforms package. @wtgodbe is that in your backlog?

**Comment by wtgodbe** [comment]
@joperezr this update is just to 'catch up' 2.2 so that Platforms is shipping the same content in both branches, since we shipped a 2.2.0 version of Platforms in November. We just shipped a 'latest' version of Platforms with 2.1.10. Maestro/ProdCon will take care of updating core-setup once we've built the package.

**Pull request merged**
