### PR TITLE
Enable Server GC for Ubuntu Debug CI builds on PRs

### PR DESCRIPTION
**Pull request by wtgodbe**

### CODE REVIEW

**Comment by wtgodbe** [comment]
@stephentoub @mmitche does this look OK to you guys?

**Comment by wtgodbe** [comment]
@dotnet-bot test CI please

**Comment by mellinoe** [comment]
What is this for, exactly? Is it to speed up the PR tests or something like that? Why only Ubuntu/Debug?

**Comment by wtgodbe** [comment]
@mellinoe It's to test server GC performance vs. workstation GC - @sergiy-k should be able to explain it better

**Comment by stephentoub** [comment]
> It's to test server GC performance

I was assuming this was about exercising/stressing both flavors of the GC, rather than about testing perf (which I don't think this does).

> Why only Ubuntu/Debug?

Assuming we're not going to run the full matrix of all possible combinations of everything in CI, I think it makes sense to use server GC for some jobs and workstation GC for others.

**Comment by wtgodbe** [comment]
Stephen's explanation is correct

**Comment by mellinoe** [comment]
That sounds reasonable to me. We want to make sure we get some coverage of both GC modes, and Ubuntu/Debug is as good a configuration as any to use.

**Comment by stephentoub** [comment]
@dotnet-bot test this please

**Comment by wtgodbe** [comment]
@mmitche PTAL

**Comment by mmitche** [comment]
LGTM.

**Pull request merged**
