### PR TITLE
Fix PauseAndContinue failure?

### LINKED ISSUE #27071: ServiceProcess test failures, including PauseAndContinue
This has failed the last three builds (2/11 - 2/12) - [MC test results link](https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Fcli~2F/build/20180212.05/workItem/System.ServiceProcess.ServiceController.Tests/analysis/xunit/System.ServiceProcess.Tests.ServiceControllerTests~2FPauseAndContinue)

The test `System.ServiceProcess.Tests.ServiceControllerTests/PauseAndContinue` has failed.

System.ComponentModel.Win32Exception : Could not find service 

        Stack Trace:

           at System.ServiceProcess.Tests.TestServiceInstaller.DeleteService() in E:\A\_work\1424\s\corefx\src\System.ServiceProcess.ServiceController\tests\System.ServiceProcess.ServiceController.TestService\TestServiceInstaller.cs:line 186
       at System.ServiceProcess.Tests.TestServiceInstaller.RemoveService() in E:\A\_work\1424\s\corefx\src\System.ServiceProcess.ServiceController\tests\System.ServiceProcess.ServiceController.TestService\TestServiceInstaller.cs:line 133
       at System.ServiceProcess.Tests.TestServiceProvider.DeleteTestServices() in E:\A\_work\1424\s\corefx\src\System.ServiceProcess.ServiceController\tests\TestServiceProvider.cs:line 139
       at System.ServiceProcess.Tests.TestServiceProvider.DeleteTestServices() in E:\A\_work\1424\s\corefx\src\System.ServiceProcess.ServiceController\tests\TestServiceProvider.cs:line 149
       at System.ServiceProcess.Tests.ServiceControllerTests.Dispose() in E:\A\_work\1424\s\corefx\src\System.ServiceProcess.ServiceController\tests\ServiceControllerTests.cs:line 184
       at ReflectionAbstractionExtensions.DisposeTestClass(ITest test, Object testClass, IMessageBus messageBus, ExecutionTimer timer, CancellationTokenSource cancellationTokenSource) in C:\BuildAgent\work\cb37e9acf085d108\src\xunit.execution\Extensions\ReflectionAbstractionExtensions.cs:line 76
Build : Master - 20180212.05 (Core Tests)
Failing configurations:
- Windows.10.Amd64-x64
  - Release

### PR DESCRIPTION
**Pull request by danmosemsft**
Attempt to fix #27071

I cannot repro, at least when I run the test library (or test) individually, on the repro machine, even looping. Nor can I come up with a good theory why this particular test sporadically fails in cleanup.

I increased the time we wait for the service to stop from 30 sec to 120 sec in case it is machine slowness. (On the repro machine, it usually takes less than 1 sec)

I also added explicit verification of the state of the test service in this test.

### CODE REVIEW

**Comment by danmosemsft** [comment]
@dotnet-bot test NETFX x86 Release Build (timed out)

**Comment by danmosemsft** [comment]
@dotnet-bot test Windows x86 Release Build (http test)

**Comment by danmosemsft** [comment]
@dotnet-bot test Linux x64 release build

**Comment by Anipik** [comment]
@danmosemsft could this be due to the reason that in all other tests, we are stopping the service and then remove the service in cleanup ?
In this tests we are trying to remove a running service

**Comment by danmosemsft** [comment]
@Anipik hmm, possibly. Of course, we are trying to stop the service in the cleanup.

**Comment by danmosemsft** [comment]
I'll explicitly stop also.

**Comment by danmosemsft** [comment]
Merging because this library does not build on Linux.

**Pull request merged**
