### PR TITLE
Add command line install

### PR DESCRIPTION
**Pull request by MisinformedDNA**

### CODE REVIEW

**Comment by ahsonkhan** [comment]
From https://github.com/dotnet/corefxlab/issues/2217#issuecomment-382048814
> OK, despite adding all the "Individual Components" [listed](https://github.com/MisinformedDNA/corefx/blob/e9fcc23ffc5e73d062536b2473ccda66a74315ba/Documentation/building/windows-instructions.md#visual-studio-2017---individual-components-based-install), I tried just adding the workload ".NET Core cross-platform development" and now the solution loads fine. So there is some unlisted individual component(s) that was previously not needed (or didn't exist), but is now needed with 2.1.

Do we need to update the instructions?

cc @danmosemsft, @karelz, @stephentoub 

@MisinformedDNA, does this additional step resolve the project migration issue you were seeing?

**Comment by MisinformedDNA** [comment]
Yes, installing just the "Individual Components" caused a migration issue for projects in VS2017 Preview 3, but adding the ".NET Core cross-platform development" workload resolved it. This PR matches the existing documentation, but for a command line install, but something is missing from both. We should update the instructions within "Individual Components" to require the ".NET Core cross-platform development" workload, or we should determine what individual components are missing and add them to the documentation. Whatever we add to the "Individual Components" should also be added to the "Command Line" section.

**Comment by karelz** [comment]
Latest version of the doc is on wiki IMO: https://github.com/dotnet/corefx/wiki/Development-environment-setup-for-Windows
Why do we need the command-line install? Who and when uses that? I would rather prefer to keep just one way of doing that - it is easier to maintain.

**Comment by MisinformedDNA** [comment]
We should definitely centralize on either the repo documentation or the wiki. All the main links in the wiki just go back to the documentation.

But specific to this PR, the command-line install is useful when you don't want to manually look for all the correct checkboxes. It gives assurance that you installed the right features. I create a VM and then installed the Preview and having the command line made things super simple. Automation FTW!

Further, we already have two ways to install, "Workloads" or "Individual Components", so this is actually a third. That might hurt my case, but my biased opinion is that command line install is more useful than trying to pick out individual components from a huge list.

**Comment by ahsonkhan** [comment]
> Latest version of the doc is on wiki IMO

The "**Visual Studio 2017 - 'Individual components' based install**" lists in both documents are essentially identical. @MisinformedDNA, installed the individual components listed and was not able to open the corefxlab .NET Core projects.

image

image

I think we need to list the .NET Core development workload as required, or list the additional individual components necessary (4.6.1 targeting pack? .NET Core Runtime?).

**Otherwise, the projects fail to load:**
image

**Comment by karelz** [comment]
wiki is temporary easy-to-edit (no PRs) way to edit docs - see its descriptions. wiki is also linked from main repo page. The goal is to overwrite the project-docs with the wiki content at some point. Few pages are ready, we just didn't do it yet. When it happens, I expect the old and bloated content in project-docs to be overridden unless added recently.

I assume the script may be useful for automating local build machine setup in Docker/VM. That would make sense. We should make the title reflect that.

**Comment by krwq** [comment]
I think this should belong to some kind of building instructions FAQ and keep instructions to only essentials.

**Comment by stephentoub** [comment]
@karelz, what's the plan for this PR?  Can we get it merged or closed as is appropriate?  It's been two months.

**Comment by karelz** [comment]
Thanks for your contribution @MisinformedDNA! And sorry for the XXL delay :(

**Pull request merged**
