### PR TITLE
Re-enable a Sockets Functional test for UAP mode

### PR DESCRIPTION
**Pull request by caesar1995**
Contributes to: #21018

### CODE REVIEW

**Comment by davidsh** [comment]
@caesar1995 FYI, the "disabled-test" label is not used on a PR in general. It is also put on an ActiveIssue to signify that the issue is still open but the test repro'ing it has been disabled.

**Comment by caesar1995** [comment]
@dotnet-bot help

**Comment by caesar1995** [comment]
@dotnet-bot test outerloop netcoreapp Windows 7 Release
@dotnet-bot test outerloop netcoreapp Windows_NT Debug

@dotnet-bot test outerloop netcoreapp Ubuntu16.10 Debug
@dotnet-bot test outerloop netcoreapp OSX10.12 Debug

**Comment by caesar1995** [comment]
@dotnet-bot test OuterLoop netcoreapp Windows_NT Debug x64 (System.Diagnostics.Tests.ProcessStartInfoTests.StartInfo_TextFile_ShellExecute [FAIL])
@dotnet-bot test Windows x64 Debug Build (https://mc.dot.net/#/user/caesar1995/pr~2Fjenkins~2Fdotnet~2Fcorefx~2Fmaster~2F/test~2Ffunctional~2Fcli~2F/e56f6ae41e565488128faeef0b503a8fdae99f05/workItem/System.Globalization.Extensions.Tests)

@dotnet-bot test Outerloop NETFX x86 Release Build

**Comment by caesar1995** [comment]
@dotnet-bot test OuterLoop netcoreapp OSX10.12 Debug x64 (#20746)
@dotnet-bot test OuterLoop netcoreapp Windows_NT Debug x64 (#20388)
@dotnet-bot test Outerloop NETFX x86 Release Build (seems related to System.Diagnostics.Process.Tests, I don't understand the log https://ci3.dot.net/job/dotnet_corefx/job/master/job/windows-TGroup_netfx+CGroup_Release+AGroup_x86+TestOuter_true_prtest/1/consoleText)
@dotnet-bot test Windows x64 Debug Build  (#10786, but the issue is closed. This occurs on Windows.10.Nano.Amd64.Open)

**Comment by caesar1995** [comment]
@dotnet-bot test OuterLoop netcoreapp Windows_NT Debug x64 (#20388)
@dotnet-bot test Outerloop NETFX x86 Release Build (seems related to System.Diagnostics.Process.Tests)

**Comment by caesar1995** [comment]
These two tests are just keeping failing...

@dotnet-bot test OuterLoop netcoreapp Windows_NT Debug x64 (#20388)
@dotnet-bot test Outerloop NETFX x86 Release Build (seems related to System.Diagnostics.Process.Tests)

**Comment by caesar1995** [comment]
@dotnet-bot test OuterLoop netcoreapp Windows_NT Debug x64 (#20388)
@dotnet-bot test Outerloop NETFX x86 Release Build (seems related to System.Diagnostics.Process.Tests)

**Comment by caesar1995** [comment]
@mmitche What's going on with these two builds...

@dotnet-bot test OuterLoop netcoreapp Windows_NT Debug x64 (#20388)
@dotnet-bot test Outerloop NETFX x86 Release Build (seems related to System.Diagnostics.Process.Tests)

**Comment by caesar1995** [comment]
I start to question about my changes in this PR. 

-.-

@dotnet-bot test OuterLoop netcoreapp Windows_NT Debug x64 (#20388)
@dotnet-bot test Outerloop NETFX x86 Release Build (seems related to System.Diagnostics.Process.Tests)

**Comment by caesar1995** [comment]
My script has run this test `MulticastInterface_Set_AnyInterface_Succeeds` for 100 times. No failure.

I will go ahead and merge.

**Pull request merged**
