### PR TITLE
Fix tests for path validation changes on Windows And Unix

### LINKED ISSUE #25665: Many tests failing after path validation updates
Search for `[ActiveIssue(25665)]` in the tests.

### PR DESCRIPTION
**Pull request by Anipik**
The Null check was added to GetFullPath function in the coreclr. These tests are in respond to that.
Fixes #25665

### CODE REVIEW

**Comment by Anipik** [comment]
@danmosemsft  Can you suggest something to correct this error
19:46:38   System.Threading.Tasks.Dataflow -> D:\j\workspace\windows-TGrou---0d2c9ac4\bin/packages/Debug/specs/System.Threading.Tasks.Dataflow.nuspec
19:46:38 
19:46:38 Build FAILED.
19:46:38 
19:46:38 D:\j\workspace\windows-TGrou---0d2c9ac4\Tools\Packaging.targets(427,5): error : Cannot harvest package 'Microsoft.XmlSerializer.Generator' version '1.0.0' because D:\j\workspace\windows-TGrou---0d2c9ac4\packages/Microsoft.XmlSerializer.Generator\1.0.0 does not exist.  Harvesting is needed to redistribute assets and ensure compatiblity with the previous release.  You can disable this by setting HarvestStablePackage=false. [D:\j\workspace\windows-TGrou---0d2c9ac4\src\Microsoft.XmlSerializer.Generator\pkg\Microsoft.XmlSerializer.Generator.pkgproj]
19:46:38     0 Warning(s)
19:46:38     1 Error(s)

**Comment by Anipik** [comment]
@dotnet-bot test Alpine.3.6 x64 Debug Build

**Comment by Anipik** [comment]
@dotnet-bot test Packaging All Configurations x64 Debug Build

**Comment by danmosemsft** [comment]
Other failures are unrelated and not relevant.

**Comment by Anipik** [comment]
@dotnet-bot test Packaging All Configurations x64 Debug Build

**Comment by Anipik** [comment]
I am merging this as Wes has disabled the default alpine build   https://github.com/dotnet/corefx/commit/25db335c8dc7f3792d97a954592c3105cd3c4127

**Pull request merged**
