### PR TITLE
Enable Reflection-based Serialization to Call Static Parse Method.

### LINKED ISSUE #21143: DCJS_GetOonlyDictionary_UseSimpleDictionaryFormat Failed in ReflectionOnly on Uapaot
```
     DataContractJsonSerializerTests.DCJS_GetOonlyDictionary_UseSimpleDictionaryFormat [FAIL]
        $BlockedFromReflection_0_1dac0683 : This object cannot be invoked because it was metadata-enabled for browsing only: 'System.Boolean.Parse(System.String)' For more informati
  on, please visit  http://go.microsoft.com/fwlink/?LinkID=616867
        Stack Trace:
           f:\dd\ndp\fxcore\CoreRT\src\System.Private.Reflection.Core\src\Internal\Reflection\Core\Execution\ExecutionEnvironment.cs(130,0): at Internal.Reflection.Core.Execution.Ex
  ecutionEnvironment.GetMethodInvoker($RuntimeTypeInfo declaringType, $QMethodDefinition methodHandle, $RuntimeTypeInfo[] genericMethodTypeArguments, MemberInfo exceptionPertainant)
           f:\dd\ndp\fxcore\CoreRT\src\System.Private.Reflection.Core\src\System\Reflection\Runtime\MethodInfos\NativeFormat\NativeFormatMethodCommon.cs(42,0): at System.Reflection.
  Runtime.MethodInfos.NativeFormat.NativeFormatMethodCommon.GetUncachedMethodInvoker($RuntimeTypeInfo[] methodArguments, MemberInfo exceptionPertainant)
           f:\dd\ndp\fxcore\CoreRT\src\System.Private.Reflection.Core\src\System\Reflection\Runtime\MethodInfos\RuntimeNamedMethodInfo.cs(304,0): at System.Reflection.Runtime.Method
  Infos.RuntimeNamedMethodInfo$1<System.Reflection.Runtime.MethodInfos.NativeFormat.NativeFormatMethodCommon>.get_UncachedMethodInvoker()
           f:\dd\ndp\fxcore\CoreRT\src\System.Private.Reflection.Core\src\System\Reflection\Runtime\MethodInfos\RuntimeMethodInfo.cs(357,0): at System.Reflection.Runtime.MethodInfos
  .RuntimeMethodInfo.get_MethodInvoker()
           f:\dd\ndp\fxcore\CoreRT\src\System.Private.Reflection.Core\src\System\Reflection\Runtime\MethodInfos\RuntimeMethodInfo.cs(191,0): at System.Reflection.Runtime.MethodInfos
  .RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
           D:\OSS\corefx-1\corefx\src\System.Private.DataContractSerialization\src\System\Runtime\Serialization\Json\ReflectionJsonFormatReader.cs(196,0): at System.Runtime.Serializ
  ation.Json.ReflectionJsonReader.ReadSimpleDictionary($XmlReaderDelegator xmlReader, $XmlObjectSerializerReadContext context, $CollectionDataContract collectionContract, Type keyVa
  lueType, Object dictionary)
           D:\OSS\corefx-1\corefx\src\System.Private.DataContractSerialization\src\System\Runtime\Serialization\Json\ReflectionJsonFormatReader.cs(126,0): at System.Runtime.Serializ
  ation.Json.ReflectionJsonReader.ReflectionReadSpecialCollection($XmlReaderDelegator xmlReader, $XmlObjectSerializerReadContext context, $CollectionDataContract collectionContract,
   Object resultCollection)
           D:\OSS\corefx-1\corefx\src\System.Private.DataContractSerialization\src\System\Runtime\Serialization\ReflectionReader.cs(60,0): at System.Runtime.Serialization.Reflection
  Reader.ReflectionReadGetOnlyCollection($XmlReaderDelegator xmlReader, $XmlObjectSerializerReadContext context, $XmlDictionaryString collectionItemName, $XmlDictionaryString collec
  tionItemNamespace, $CollectionDataContract collectionContract)
           D:\OSS\corefx-1\corefx\src\System.Private.DataContractSerialization\src\System\Runtime\Serialization\Json\ReflectionJsonFormatReader.cs(47,0): at System.Runtime.Serializa
  tion.Json.ReflectionJsonCollectionReader.ReflectionReadGetOnlyCollection($XmlReaderDelegator xmlReader, $XmlObjectSerializerReadContextComplexJson context, $XmlDictionaryString em
  ptyDictionaryString, $XmlDictionaryString itemName, $CollectionDataContract collectionContract)
           Invoke(16707566,0): at System.Runtime.Serialization.Json.JsonFormatClassWriterDelegate.Invoke($XmlWriterDelegator xmlWriter, Object obj, $XmlObjectSerializerWriteContextC
  omplexJson context, $ClassDataContract dataContract, $XmlDictionaryString[] memberNames)
```

### PR DESCRIPTION
**Pull request by shmao**
The issue was that, on uapaot, reflection-based serialization cannot invoke primitive types's static `Parse` method due to reflection on primitive types being blocked.

Fix #21143

### CODE REVIEW

**Comment by shmao** [comment]
@dotnet-bot test Portable Linux x64 Release Build

**Comment by shmao** [comment]
@dotnet-bot test Portable Linux x64 Release Build

**Comment by shmao** [comment]
@dotnet-bot test OSX x64 Debug Build

**Comment by shmao** [comment]
@dotnet-bot help (testing)

**Comment by shmao** [comment]
@dotnet-bot test innerloop PortableLinux Release

**Comment by shmao** [comment]
@dotnet-bot test Portable Linux x64 Release Build please

**Comment by shmao** [comment]
I'm not sure why Portable Linux x64 Release Build failed. The detail page is gone. I couldn't restart the leg. But as other Linux tests passed, I don't think the failure was related to the issue.

**Comment by mconnew** [comment]
:shipit:

**Pull request merged**
