### PR TITLE
System.Reflection.Metadata: Update reference to immutable to the latest

### PR DESCRIPTION
**Pull request by tmat**

### CODE REVIEW

**Comment by tmat** [comment]
@nguerrera

**Comment by nguerrera** [comment]
LGTM, but I'd defer to @weshaggard and @ericstj for sign-off.

**Comment by ericstj** [comment]
Talked to @tmat offline.  The purpose of this change is to avoid the need bindingRedirects when consuming this library on desktop.

That's OK but will create a new baseline for servicing.  So if we were to ever service this component we'd have to either ship separate builds of this binary for stable versions before this change and after, or include S.C.I 1.2.0 in the patch bundle.  No objections to doing this, just pointing out the tradeoff here.

I'd say lets move forward with this since it simplifies the common scenario today.  LGTM

**Comment by tmat** [comment]
Thanks for quick review.

**Pull request merged**
