### PR TITLE
Cleanup NameValueCollection tests

### PR DESCRIPTION
**Pull request by hughbe**
- Take advantage of xunit
- Shorten tests
- Remove duplicate tests

Coverage remains at 100%
/cc @ianhays

### CODE REVIEW

**Comment by hughbe** [comment]
Test Innerloop CentOS7.1 Release Build and Test
Test Innerloop Windows_NT Debug Build and Test

**Comment by hughbe** [comment]
Test Innerloop CentOS7.1 Release Build and Test

**Comment by hughbe** [comment]
Test Innerloop CentOS7.1 Debug Build and Test

**Comment by ianhays** [comment]
Looks good as always. Thanks, Hugh!

**Pull request merged**
