### PR TITLE
Add DisableWarning parameter when compile the sgen generated code.

### LINKED ISSUE #25616: Suppress compiler warnings from XmlSerializer.Generator
When using the new XmlSerializer.Generator, there is a lot of warnings like:

    warning CS0219: The variable 'tmp' is assigned but its value is never used 
    warning CS0219: The variable 'a_2' is assigned but its value is never used

see: https://ci.appveyor.com/project/ublsharp/ublsharp/build/108

Looking at the msbuild targets here https://github.com/dotnet/corefx/blob/master/src/Microsoft.XmlSerializer.Generator/pkg/build/Microsoft.XmlSerializer.Generator.targets#L16 I see there's no way to pass nowarn/DisabledWarnings to the Csc tasks. 

Any way to take a variable here? 

On a side-note, should I even be doing this (including the sgen dll with the nuget packge), or is that something for the package consumer? What are the recommendations?

### PR DESCRIPTION
**Pull request by huanwu**
Disable the warning when compile the sgen generated code. Will disable the warning 219 and 162 by default. The customer can also customize the warning they want to disable by adding the following parameter in their project. 

```
<PropertyGroup>
  <SerializationAssemblyDisabledWarnings>215;313</SerializationAssemblyDisabledWarnings>
</PropertyGroup>

```
Fix #25616 

@shmao @zhenlan @mconnew

### CODE REVIEW

**Comment by shmao** [comment]
LGTM. I just wondered if `SerializationAssemblyDisabledWarnings` would be a good name.

**Comment by zhenlan** [comment]
`SerializationDisabledWarnings`? @mconnew may have a better idea of naming.

**Comment by zhenlan** [comment]
BTW, do we have a repro of the issue?

**Comment by huanwu** [comment]
@zhenlan Yes, I can repro it when to serialize all our serialization test types.

**Comment by zhenlan** [comment]
@huanwu can you please finalize the naming with @mconnew and merge the PR?

**Comment by huanwu** [comment]
@dotnet-bot test OSX x64 Debug Build

**Comment by huanwu** [comment]
@dotnet-bot test Windows x86 Release Build

**Pull request merged**
