### PR TITLE
Fixed Bugs with DateTime Parsing

### LINKED ISSUE #24894: DateTimeParser in class Atom10FeedFormatter return wrong result.
Atom10FeedFormatter can not convert `string dateTimeString = "2017-10-11T11:25:55Z";` to class `DateTimeOffset` when load from feed file.
The DateTimeParser use the codes are as below ([source](https://github.com/dotnet/corefx/blob/master/src/System.ServiceModel.Syndication/src/System/ServiceModel/Syndication/DateTimeHelper.cs#L59)):
```
public static Func<string, string, string, DateTimeOffset> CreateAtom10DateTimeParser()
{
    return (dateTimeString, localName, ns) =>
    {
        DateTimeOffset dto;
        if (Rfc3339DateTimeParser(dateTimeString, out dto))
        {
            return dto;
        }

        // Unable to parse - using a default date;
        return new DateTimeOffset();
    };
}

private static bool Rfc3339DateTimeParser(string dateTimeString, out DateTimeOffset dto)
{
    // RFC3339 uses the W3C Profile of ISO 8601 so using the date time format string "O" will achieve this.
    return DateTimeOffset.TryParseExact(dateTimeString, "O", null as IFormatProvider, DateTimeStyles.AllowWhiteSpaces, out dto);
}
```
The format **"O"** in code:
```
DateTimeOffset.TryParseExact(dateTimeString, "O", null as IFormatProvider,DateTimeStyles.AllowWhiteSpaces, out dto);
```
Can not parse the `dateTimeString = "2017-10-11T11:25:55Z"`.
It think it maybe relate to PR #24613.

### PR DESCRIPTION
**Pull request by shmao**
The bug was that `Rfc3339DateTimeParser` couldn't parse string like `2003-12-13T18:30:02Z`. The fix was to use the original `Atom10FeedFormatter.DateFromString`.

Fix #24894

### CODE REVIEW

**Comment by mconnew** [comment]
Atom uses RFC3339 which says basically use the W3C profile of ISO1860. These changes will fail to parse `2017-10-11T11:25:55.120Z` which is a valid RFC3339 formatted time. The code you are replacing uses "O" as the formatting string. This is defined as using the format string `yyyy'-'MM'-'dd'T'HH':'mm':'ss'.'fffffffK`. The reason this was failing is because this was designed to be use for roundtrip serializing and *requires* 7 digits of precision on the fractional part. If the lowercase f is replaced with an upper case F, it becomes optional.  So we should add a format with `.FFFFFFFK` added.  
Also the difference between Z and zzz can be eliminated as we're using DateTimeOffset instead of DateTime. When using DateTimeOffset, the single formatting character K deals with both. Here's some experiments using the interactive commandline csharp prompt:  
```csharp
> DateTimeOffset.TryParseExact("2017-10-11T11:25:55Z", "yyyy-MM-ddTHH:mm:ssK", null as IFormatProvider, DateTimeStyles.AllowLeadingWhite | DateTimeStyles.AllowTrailingWhite, out dto)
true
> dto
[10/11/2017 11:25:55 AM +00:00]
> DateTimeOffset.TryParseExact("  2017-10-11T11:25:55Z  ", "yyyy-MM-ddTHH:mm:ssK", null as IFormatProvider, DateTimeStyles.AllowLeadingWhite | DateTimeStyles.AllowTrailingWhite, out dto)
true
> dto
[10/11/2017 11:25:55 AM +00:00]
> DateTimeOffset.TryParseExact("2017-10-11T11:25:55-01:00", "yyyy-MM-ddTHH:mm:ssK", null as IFormatProvider, DateTimeStyles.AllowLeadingWhite | DateTimeStyles.AllowTrailingWhite, out dto)
true
> dto
[10/11/2017 11:25:55 AM -01:00]
> DateTimeOffset.TryParseExact("2017-10-11T11:25:55.120Z", "yyyy-MM-ddTHH:mm:ss.FFFFFFFK", null as IFormatProvider, DateTimeStyles.AllowLeadingWhite | DateTimeStyles.AllowTrailingWhite, out dto)
true
> dto
[10/11/2017 11:25:55 AM +00:00]
> DateTimeOffset.TryParseExact("  2017-10-11T11:25:55.120-01:00  ", "yyyy-MM-ddTHH:mm:ss.FFFFFFFK", null as IFormatProvider, DateTimeStyles.AllowLeadingWhite | DateTimeStyles.AllowTrailingWhite, out dto)
true
> dto
[10/11/2017 11:25:55 AM -01:00]
```

You can also see that specifying `DateTimeStyles.AllowLeadingWhite | DateTimeStyles.AllowTrailingWhite` means you don't need to worry about trimming it first. My original change mistakenly used `DateTimeStyles.AllowWhiteSpaces` which also allows spaces added between components. E.g. "2017 - 10 - 11".

**Comment by shmao** [comment]
I tried `"yyyy-MM-ddTHH:mm:ss.FFFFFFFK"` on my machine, and all tests passed. 

>  So we should add a format with .FFFFFFFK added.

Did you mean we should add the format in addition to `Rfc3339LocalDateTimeFormat` and `Rfc3339UTCDateTimeFormat`? Or did you mean we can just replace the `"O"` with that format?

Some tests are failing on Unix. I believed it's a test issue. I'm investigating it.

**Comment by mconnew** [comment]
I'm saying that `"yyyy-MM-ddTHH:mm:sszzz"` and `"yyyy-MM-ddTHH:mm:ssZ"` can be replaced with the single pattern `"yyyy-MM-ddTHH:mm:ssK"`. This alone isn't enough though as none of them work when you have fractional seconds. So in addition we also need `"yyyy-MM-ddTHH:mm:ss.FFFFFFFK"`. That alone wouldn't be sufficient as it requires fractional seconds as although F is optional, the period is not. "O" is broken as it requires fractional seconds, and requires exactly 7 digits.

**Comment by shmao** [comment]
@dotnet-bot  test this please

**Comment by shmao** [comment]
@dotnet-bot test Windows x64 Debug Build
> System.Diagnostics.EventLog.Tests failed

**Comment by mconnew** [comment]
As the RSS date time parser also checks the atom one, can you replace the implementation in Rfc3339DateTimeParser with the code from the anonymous delegate and have CreateAtom10DateTimeParser call that?

**Comment by shmao** [comment]
System.Diagnostics.EventLog.Tests failed on Windows x86 Release Build. It's not related to the fix.

**Comment by shmao** [comment]
@dotnet-bot test Windows x86 Release Build

**Pull request merged**
