### PR TITLE
NOMERGE: failing some tests intentionally to see call stacks

### PR DESCRIPTION
**Pull request by joperezr**
cc: @MattGal 

Do not merge this PR as it is only to validate right call stacks on failing tests. This is an investigation related to issue #22979

### CODE REVIEW

**Comment by danmosemsft** [comment]
@joperezr I think even intentoinal bugs need to be built locally :)

**Comment by joperezr** [comment]
lol, yeah! I should've tested it locally first. Sorry for the trouble

**Comment by stephentoub** [comment]
@joperezr, do you still need this?

**Comment by joperezr** [comment]
haven't finished debugging what's wrong but we can close this for now as we have enough info to do some more investigation. Will reopen if needed.

**Pull request closed without merging**
