### PR TITLE
Update BuildTools to 1.0.26-prerelease-00715-01

### PR DESCRIPTION
**Pull request by ericstj**
Bring over fixes to buildtools.

### CODE REVIEW

**Comment by stephentoub** [comment]
LGTM

**Comment by weshaggard** [comment]
@ericstj did you want to also do some clean-up of the Validation files as part of this?

**Comment by ericstj** [comment]
@weshaggard sure I can do that.

**Comment by weshaggard** [comment]
LGTM

**Comment by ericstj** [comment]
@dotnet-bot test Innerloop Windows_NT Debug Build and Test

**Comment by ericstj** [comment]
@dotnet-bot test Innerloop Windows_NT Release Build and Test

**Pull request merged**
