### PR TITLE
System.Diagnostics.EventLog.Tests fails 2 tests in non-English Windows

### PR DESCRIPTION
**Pull request by AlexRadch**
See https://github.com/dotnet/corefx/issues/27646

### CODE REVIEW

**Comment by AlexRadch** [comment]
@Anipik I have Windows with non-English interface language. And I can switch to English if required.

**Comment by Anipik** [comment]
The tests run for English interface so I don't think switching will be required

**Comment by AlexRadch** [comment]
@dotnet-bot test OSX x64 Debug Build please

**Comment by danmosemsft** [comment]
Thanks @AlexRadch

**Comment by danmosemsft** [comment]
OSX failure in Http tests.

**Pull request merged**
