### PR TITLE
Add method KeyedCollection<,>::TryGetValue(TKey, out TItem)

### LINKED ISSUE #4690: Add bool TryGetValue(TKey, out TItem) method to a KeyedCollection<,> class
Suggested TryGetValue method allows to check a collection for an "item" with specific "key" and get item if it exists in the collection.
Similar that occur in the [Dictionary<,>](https://msdn.microsoft.com/en-us/library/bb299639.aspx).

``` cs
public bool TryGetValue(TKey key, out TItem item)
{
    if (key == null)
    {
        throw new ArgumentNullException("key");
    }

    if (_dict != null)
    {
        return _dict.TryGetValue(key, out item);
    }

    foreach (TItem itemInItems in Items)
    {
        TKey keyInItems = GetKeyForItem(itemInItems);
        if (keyInItems != null && _comparer.Equals(key, keyInItems))
        {
            item = itemInItems;
            return true;
        }
    }

    item = default(TItem);
    return false;
}
```

If some existing derived type "MyKeyedCollection<,>" already contains the same method, only warning occurred in compilation:

> warning CS0108: 'MyKeyedCollection<TKey, TItem>. TryGetValue(TKey, out TItem)' hides inherited member 'KeyedCollection<TKey, TItem>. TryGetValue(TKey, out TItem)'. Use the new keyword if hiding was intended.

### PR DESCRIPTION
**Pull request by ViIvanov**
Fixes #4690 "Add bool TryGetValue(TKey, out TItem) method to a KeyedCollection<,> class"

### CODE REVIEW

**Comment by ianhays** [comment]
You need to do what @Priya91 mentioned in https://github.com/dotnet/corefx/issues/4690 and conditionally include this new API when building for netcoreapp11

**Comment by ViIvanov** [comment]
@ianhays Thank you.

As I can see, in comparison with project System.Collections, System.ObjectModel does not contains a some staff for netcoreapp11: for examlpe, I can see differences in ref/project.json files ([System.Collections/ref/project.json](https://github.com/dotnet/corefx/blob/cf813aa85dd2949798900028370da550c81a456f/src/System.Collections/ref/project.json#L7), [System.ObjectModel/ref/project.json](https://github.com/dotnet/corefx/blob/master/src/System.ObjectModel/ref/project.json)).

Should I copy all this stuff to System.ObjectModel?

**Comment by Priya91** [comment]
@ViIvanov I made the packaging changes in this commit [here](https://github.com/Priya91/corefx-1/commit/92e7c924d0a3c9a3567b25f09540b7a8b20cf749).. You can cherry-pick this commit to this PR.. The packaging story is pretty complicated, took me a few tries to figure this out :) 

cc @weshaggard @joperezr Can you please verify the changes.. Thanks!

**Comment by weshaggard** [comment]
@Priya91 yes your commit looks correct.

**Comment by ViIvanov** [comment]
Thanks, @Priya91 

Now test project compiled successfully. I will try to fix some warnings and 
```
  .\Tools\packageresolve.targets(79,5): warning : Your project is not referencing the ".NETCoreApp,Version=v1.1" framework. 
Add a reference to ".NETCoreApp,Version=v1.1" in the "frameworks" section of your project.json,
and then re-run NuGet restore. [.\src\System.ObjectModel\ref\System.ObjectModel.csproj]
```
will update PR later.

**Comment by ViIvanov** [comment]
@Priya91, @karelz May be, this PR is ready for merge? Please tell me if I can do anything else for this.

**Comment by karelz** [comment]
@Priya91?

**Comment by Priya91** [comment]
Taking a look..

**Comment by Priya91** [comment]
Thanks @ViIvanov

**Comment by weitzhandler** [comment]
Can we have `KeyedCollection` implement `IDictionary<TKey, TItem>`?

**Pull request merged**
