### PR TITLE
[** No Merge**] Turn on Windows dumpling and fail some tests on purpose

### PR DESCRIPTION
**Pull request by mellinoe**
Don't merge. I'm just making sure things are working properly first before submitting this for real.

### CODE REVIEW

**Comment by danmosemsft** [comment]
@dotnet-bot help please (just borrowing your PR for a sec)

**Comment by mellinoe** [comment]
All of the windows jobs are giving a ton of warnings about an insecure version of python being used 😞 . I'll need to do another round of image updating.

**Comment by mellinoe** [comment]
Trying this again with updated Windows images.

**Comment by mellinoe** [comment]
It's looking good. Going to submit just the Dumpling changes separately.

**Pull request closed without merging**
