### PR TITLE
Add "local" code coverage badge to README.md

### PR DESCRIPTION
**Pull request by stephentoub**
The cc badge is without TestWithLocalLibraries=true, and the local cc badge is with TestWithLocalLibraries=true.

cc: @ellismg, @Priya91

### CODE REVIEW

**Comment by stephentoub** [comment]
test Innerloop CentOS7.1 Debug Build and Test please
test Innerloop Windows_NT Debug Build and Test please

**Comment by ellismg** [comment]
Looks fine, except I don't really know how anyone would understand what the badges mean.

A side note, what's the difference between the local libraries version and the regular on.  I would expect the local libraries version would give us a better picture of what coverage really is?

**Comment by stephentoub** [comment]
> except I don't really know how anyone would understand what the badges mean

I couldn't come up with anything better that would keep them fitting in a reasonable layout.  Suggestions?

> what's the difference between the local libraries version and the regular on. I would expect the local libraries version would give us a better picture of what coverage really is?

in the regular one, when running SomeLibrary.Tests, we only get coverage for SomeLibrary, and not for all of the libraries SomeLibrary depends on.  With the local one, we get coverage data not only for SomeLibrary but also for its dependencies.  Whether that's a "better picture" is I think really more about what question one's trying to answer.  If you want to know "what code is executed while running every test in the repo", then yes.  But if you want to know "what code is executed while I'm validating the behaviors of that code", I'd argue no.  For example, we have close to 0 tests for the Microsoft.CSharp.dll library, and if you look at the regular report, code coverage is effectively 0%.  But Microsoft.CSharp is used by System.Dynamic.Runtime, and so if you also include the coverage of Microsoft.CSharp that's achieved indirectly via System.Dynamic.Runtime, the coverage shows up at 72%.  And while it's great to know that we actually are executing that code more than was previously evident, I'm not convinced it's an accurate picture, e.g. there are no asserts as part of that verifying this or that property or return value of code in Microsoft.CSharp.

If you think that's too fine a distinction, I could simply replace the existing runs/badge with one that has /p:TestWithLocalLibraries=true.  But it seemed there was value in having both, and if we were going to have both, seemed like a good idea to have the badge.

Thoughts?

**Comment by ellismg** [comment]
>If you think that's too fine a distinction, I could simply replace the existing runs/badge with one that has /p:TestWithLocalLibraries=true. But it seemed there was value in having both, and if we were going to have both, seemed like a good idea to have the badge.

I think having both is reasonable.  If you wanted to change the way the jobs were set up and have one flow job that kicked off both the code coverage and code coverage (with local libraries) jobs, and then put a badge up for that, maybe that would be less confusing.  The badge today just tells us if the jobs passed or not (nothing about code coverage).

You could drill into the the sub-runs from the Jenkins results page.

Your call.  I can't think of better names for any of this stuff either.  LGTM if you just want to merge this.

**Comment by stephentoub** [comment]
Ok, thanks, Matt.  I'm going to merge this for now, and if we can come up with a better story, we can certainly switch to it.  I'm hesitant to combine them into a single badge, at least right now, as I like the feature of clicking on the badge and being taken directly to the most recent report.

**Pull request merged**
