### PR TITLE
Ignore EPIPE errors on Unix when writing to Console

### LINKED ISSUE #4219: [System.Console] Behavior of piping into a bad/nonexistent program on Unix
Right now, if you try to pipe a program's output into a non-existent program on Unix, you will get an IOException on the first call to Console.Write(Line) (and probably other paths):

````
Unhandled Exception: System.IO.IOException: Broken pipe
   at Interop.CheckIo(Int64 result, String path, Boolean isDirectory, Func`2 errorRewriter)
   at System.ConsolePal.Write(Int32 fd, Byte[] buffer, Int32 offset, Int32 count)
   at System.ConsolePal.UnixConsoleStream.Write(Byte[] buffer, Int32 offset, Int32 count)
   at System.IO.StreamWriter.Flush(Boolean flushStream, Boolean flushEncoder)
   at System.IO.SyncTextWriter.WriteLine(String value)
   at System.Console.WriteLine(String value)
````

I chatted with Stephen briefly and we thought that it might be sensible to just ignore this particular exception (in Interop.CheckIO) and allow the program to continue. That is, if we are able to easily detect such a case, and are still able to correctly throw if some other error occurs. How do others feel about this? This seems to be in line with what other programs do if piped into a bad program.

### PR DESCRIPTION
**Pull request by stephentoub**
If you pipe from a managed app to another app that ends (or doesn't exist to begin with), attempting to write to it via Console will throw an exception due to the pipe getting broken.

This commit just changes Console's Write to ignore EPIPE (broken pipe) errors.  For now I still have it throw an other failures, but we could choose to add additional ignored errno values to the list, or simply not throw for anything.

Fixes #4219 
cc: @mellinoe, @ellismg

### CODE REVIEW

**Comment by ellismg** [comment]
Seems reasonable.

**Comment by ellismg** [comment]
LGTM

**Comment by mellinoe** [comment]
LGTM, thanks for the quick fix

**Comment by stephentoub** [comment]
Thanks, guys.

**Pull request merged**
