### PR TITLE
Fully import legacy Sum tests.

### PR DESCRIPTION
**Pull request by JonHanna**
Convert Sum tests imported in #2874 into a more directly XUnit-ian style,
merging them with those already present.

The following were omited as duplicated by existing methods:

Sum10a.Test10a -> SumOfFloat_SourceIsEmptyCollection_ZeroReturned
Sum10e.Test10e -> SumOfFloat_SourceSumsToOverflow_InfinityReturned
Sum10h.Test10h -> SumOfNullableOfFloat_SourceIsNull_ArgumentNullExceptionThrown
‎Sum1a.Test1a -> SumOfInt_SourceIsEmptyCollection_ZeroReturned
Sum1c.Test1c -> SumOfInt_SourceIsNotEmpty_ProperSumReturned
Sum1d.Test1d -> SumOfInt_SourceSumsToOverflow_OverflowExceptionThrown
Sum2a.Test2a -> SumOfNullableOfInt_SourceIsEmptyCollection_ZeroReturned
Sum2c.Test2c -> SumOfNullableOfInt_SourceIsNotEmpty_ProperSumReturned
Sum2e.Test2e -> SumOfNullableOfInt_SourceSumsToOverflow_OverflowExceptionThrown
Sum3a.Test3a -> SumOfLong_SourceIsEmptyCollection_ZeroReturned
Sum3c.Test3c -> SumOfLong_SourceIsNotEmpty_ProperSumReturned
Sum3d.Test3d -> SumOfLong_SourceSumsToOverflow_OverflowExceptionThrown
Sum4a.Test4a -> SumOfNullableOfLong_SourceIsEmptyCollection_ZeroReturned
Sum4c.Test4c -> SumOfNullableOfLong_SourceIsNotEmpty_ProperSumReturned
Sum4e.Test4e -> SumOfNullableOfLong_SourceSumsToOverflow_OverflowExceptionThrown
Sum5a.Test5a -> SumOfDouble_SourceIsEmptyCollection_ZeroReturned
Sum5d.Test5d -> SumOfDouble_SourceSumsToOverflow_InfinityReturned
Sum6a.Test6a -> SumOfNullableOfDouble_SourceIsEmptyCollection_ZeroReturned
Sum6c.Test6c -> SumOfNullableOfDouble_SourceIsNotEmpty_ProperSumReturned
Sum6e.Test6e -> SumOfNullableOfDouble_SourceSumsToOverflow_InfinityReturned
Sum7a.Test7a -> SumOfDecimal_SourceIsEmptyCollection_ZeroReturned
Sum7c.Test7c -> SumOfDouble_SourceIsNotEmpty_ProperSumReturned
Sum7d.Test7d -> SumOfDecimal_SourceSumsToOverflow_OverflowExceptionThrown
Sum8a.Test8a -> SumOfNullableOfDecimal_SourceIsEmptyCollection_ZeroReturned
Sum8c.Test8c -> SumOfNullableOfDouble_SourceIsNotEmpty_ProperSumReturned
Sum8e.Test8e -> SumOfNullableOfDecimal_SourceSumsToOverflow_OverflowExceptionThrown
Sum9a.Test9a -> SumOfNullableOfFloat_SourceIsEmptyCollection_ZeroReturned
Sum9c.Test9c -> SumOfFloat_SourceIsNotEmpty_ProperSumReturned
Sum9d.Test9d -> SumOfFloat_SourceSumsToOverflow_InfinityReturned
Sum9g.Test9g -> SumOfFloat_SourceIsNull_ArgumentNullExceptionThrown

Also strengthen existing tests in changing IsInfinity checks to IsPositiveInfinity to be more specific, and checking parameter names when ArgumentNullException is thrown.

### CODE REVIEW

**Comment by stephentoub** [comment]
@JonHanna, this regresses slightly both branch and line coverage.  Can you investigate why?

**Comment by JonHanna** [comment]
Hmm. And just when I was congratulating myself on finishing the set. One of the duplicates must not have been as duplicate as I thought. I'll check that in the morning.

**Comment by stephentoub** [comment]
You deserve much congratulations for all of your contributions here... let's just finish on a high-note :smile:

**Comment by stephentoub** [comment]
Actually, looks like a false alarm.  I must have somehow been comparing the wrong things, as I just did it again and the coverage all looks fine.

**Comment by stephentoub** [comment]
LGTM

**Comment by JonHanna** [comment]
At the time the master branch should have had better branch coverage than the branch of this PR because other PRs had increased the branch coverage. That wouldn't explain a difference in line coverage though.

**Pull request merged**
