### PR TITLE
System.Resources.ReaderWriter has been superseded by System.Resources…

### PR DESCRIPTION
**Pull request by KrzysztofCwalina**
….Reader and Writer

We broke System.Resources.ReaderWriter into two separate packages System.Resources.Reader and System.Resources.Writer
Now that dependents have been updated to use the new packages, we can remove this one.

The APIs in the new packages are identical to the APIs in the combined package.

### CODE REVIEW

**Comment by KrzysztofCwalina** [comment]
@joshfree, @Eilon, @tarekgh

**Comment by tarekgh** [comment]
CC @ramarag @gkhanna79 the resources owners. 

the change LGTM.

**Comment by ericstj** [comment]
Failure on CentOs is 
```
12:22:16    System.IO.Pipes.Tests.NamedPipeTest_Simple_ServerIn_ClientOut.OperationsOnUnconnectedClient [FAIL]
12:22:16       System.UnauthorizedAccessException : Access to the path '/tmp/.dotnet/corefx' is denied.
12:22:16       ---- System.IO.IOException : Permission denied
12:22:16       Stack Trace:
12:22:16             at System.IO.Pipes.PipeStream.CreateDirectory(String directoryPath)
12:22:16             at System.IO.Pipes.PipeStream.EnsurePipeDirectoryPath()
```
@stephentoub is this related to your fix: https://github.com/dotnet/corefx/commit/a1e1da0d3fd8eaff17da576beb63814f0d21e3f2

**Comment by stephentoub** [comment]
> @stephentoub is this related to your fix:  a1e1da0 

I *think* this VM has an existing tmp/.dotnet/corefx folder on it from before my change, which is then causing conflicts with my change.  If that's true, I see two options:
- Delete the VM(s) and let it(them) get auto-recreated
- Add code that tries to deal with a corefx tmp folder with the wrong permissions

I'll try starting with the first (though I may miss a few that'll need to be deleted subsequently), and regardless we can look into whether the latter is reasonable.

**Comment by stephentoub** [comment]
Test Innerloop CentOS7.1 Release Build and Test please

**Comment by Eilon** [comment]
@KrzysztofCwalina thanks, I checked the current ASP.NET codebase and this package is not referenced at all, so we're good to go. Thanks!

**Comment by ericstj** [comment]
/cc @weshaggard @piotrpMSFT
Normally when we do something like this we'll type forward to the new contracts for compat, but since this has never shipped stable we can delete it.  We should doc this as a breaking change somewhere.  Otherwise folks are likely to just get an older build of ReaderWriter and not realize they need to do something.

A cursory GH search yields 253 hits in project.json: https://github.com/search?utf8=%E2%9C%93&q=%22System.Resources.ReaderWriter%22+filename%3Aproject.json&type=Code&ref=searchresults
Including in CLI:
https://github.com/dotnet/cli/blob/rel/1.0.0-preview1/src/dotnet/project.json#L40

**Pull request merged**
