### PR TITLE
[NO MERGE] Test PR HttpListener  for UAP test

### PR DESCRIPTION
**Pull request by caesar1995**
The purpose of this PR is to test CI for running HttpListener tests in UAP mode.

Tests passed locally on my machine.

@CIPop @davidsh @DavidGoll

### CODE REVIEW

**Comment by caesar1995** [comment]
@dotnet-bot Test Outerloop UWP CoreCLR x64 Debug Build

**Comment by CIPop** [comment]
Thanks @caesar1995 : I will diff this with https://github.com/dotnet/corefx/pull/22114.

**Comment by caesar1995** [comment]
The UWP NETNative x86 Release Build passed in CI, and I didn't expect that. 

In #22056, the `SetCookie_CookieDoesntExist_ThrowsArgumentException` throws `NullReferenceException `. However, the test runs fine in CI and passes. (I removed the [ActiveIssue] label)
@CIPop

**Comment by CIPop** [comment]
@dotnet-bot Test Outerloop Windows x86 Release Build
	@dotnet-bot Test Outerloop Linux x64 Release Build
	@dotnet-bot Test Outerloop UWP CoreCLR x64 Debug Build
	@dotnet-bot test Outerloop UWP NETNative x86 Release Build

**Comment by CIPop** [comment]
@caesar1995 I found a few tests closed against #22110 that worked for you. 
All these are failing intermittently on my box on UAPAOT only. I will investigate these next.

**Comment by caesar1995** [comment]
@CIPop ok, thank you!

**Pull request closed without merging**
