### PR TITLE
Removing properties not relevant to code formatting

### LINKED ISSUE #1511: Remove properties not relevant to code formatting from corefx.vssettings
Looks like we have a few properties that are unrelated to formatting in corefx.vssettings such as:

```
<PropertyValue name="HighlightReferences">0</PropertyValue>
<PropertyValue name="ProgressDialogDelaySeconds">2</PropertyValue>
```
We should remove them so that only C# formatting settings are in that file.

### PR DESCRIPTION
**Pull request by bigodera**
Edited corefx.vssetings file leaving just C# code formatting related properties, the ones that contain Formatting_*, Indent_*, NewLines_*, Space_*, and Wrapping_ in their names.

Fix #1511

### CODE REVIEW

**Comment by Maxwe11** [comment]
@dotnet-bot test this please

**Comment by ellismg** [comment]
Thanks a ton for doing this.  I made a few quick comments about settings that you are removing and that we might want to keep.

**Comment by bigodera** [comment]
Right @ellismg, done!

**Comment by Maxwe11** [comment]
@bigodera squash commits, it's not good to make changes and revert (some of) them in same PR

**Comment by ellismg** [comment]
LGTM after squashing.

**Comment by stephentoub** [comment]
Thanks, @bigodera.  LGTM after squashing, too.

**Comment by bigodera** [comment]
Squashed them, just not sure if I did it right.

**Comment by ellismg** [comment]
Doesn't look like the right thing happened, there should only be one commit.  Can you please try the following?

```
git reset --hard 8163928648cd2cbd2319f1c3f4be177a03fd0e5d
```

This resets your branch's HEAD pointer to your second commit (which added back the using properties).

```
git rebase -i HEAD~2
```

Make sure the first line is marked as "pick" and the second is marked as "fixup".  Save the file and exit.

This tells git to keep your initial change and then merge the second change into the first, discarding the commit message.

At this point, `git log` should show one commit.

Update the PR by doing:

`git push origin +issue-1511`

The + is necessary since your local version of the branch and the remote version (on github) have diverged history, it tells git to do a "force push" of that branch.

**Comment by bigodera** [comment]
Did it, @ellismg.
Also, thank you for the explanation.

**Comment by mmitche** [comment]
@bigodera I think the machine the windows release tests are running on is hosed.  I'm looking into it but I think your PR is okay.

**Comment by stephentoub** [comment]
Thanks, @bigodera. Looks good.

**Pull request merged**
