### PR TITLE
Update buildtools, enable dumpling on Windows CI jobs

### PR DESCRIPTION
**Pull request by mellinoe**
This turns on Dumpling for all CI runs (not just Unix), and passes `%TMP%\CoreRunCrashDumps` as the folder to be searched for crash dumps. Our CI machines are set up to put crash dumps in that folder. I needed to reset the startup scripts for the images to actually capture `dotnet.exe`, though, as they were only capturing `corerun.exe` before. So it may take some time for that change to propagate to the active agents.

Buildtools is updated along with this.

@karelz @danmosemsft

### CODE REVIEW

**Comment by danmosemsft** [comment]
LGTM

How are we dealling with the issue we talked about of multiple dumps?

**Comment by mellinoe** [comment]
I've tried to account for it as much as I could, so right now we are only gathering crash dumps if the test itself actually failed (by checking the exit code), and if the dump file's timestamp is later than a timestamp taken before the tests were started. So we should only ever gather extra dump files if two test projects running in parallel fail at around the same time.

**Comment by mellinoe** [comment]
Need to fix up the python script slightly, which involves updating buildtools again. Don't merge just yet.

**Comment by mellinoe** [comment]
Looks like this image doesn't have the "requests" package for python installed. I'll fix that.

**Comment by mellinoe** [comment]
It's going to take me a while to go through and update all of the images, so I will just close this and re-open once that is all finished.

**Pull request closed without merging**
