### PR TITLE
troubleshooting OleDb failures

### PR DESCRIPTION
**Pull request by maryamariyan**
- re-enable running oledb tests
- fix OleDbTestBase implementation
- add missing using statements
- disable running tests in parallel
- cleanup tests 

Fixes: https://github.com/dotnet/corefx/issues/37538

### CODE REVIEW

**Comment by maryamariyan** [comment]
@saurabh500 Fixes the SEHException failues and re-enables OLEDB tests.
The OleDbTestBase class contains fields command, connection, transaction that can be used for each test.
I disabled tests running in parallel and made sure there is only one OleDbConnection being used at each time for any test.

**Comment by danmosemsft** [comment]
Do you know exactly why the SEHException was happening? Or it just seems somehow one of your changes fixed it?

**Comment by maryamariyan** [comment]
I waited for the result of CI reports on each commit before pushing up the next commit to see which one fixes it.
Pretty much I think the fix had to do with the combination of (1) making sure the disposable objects are getting used and disposed of properly and also (2) especially in the OleDbConnection tests I made sure there is only one connection open at a time to reduce complication.

**Comment by danmosemsft** [comment]
Makes sense. thanks!

**Pull request merged**
