### PR TITLE
update versions in layout\dir.proj. also comment out uap10.0.

### PR DESCRIPTION
**Pull request by weshaggard**
cc @danmosemsft @joperezr 

For some reason the changes in this file didn't make it with the dev/api merge so I just cherry-picked @danmosemsft's commit.

### CODE REVIEW

**Comment by weshaggard** [comment]
@stephentoub have you seen issues with the System.Transation tests http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/master/job/ubuntu14.04_release_prtest/187/testReport/junit/System.Transactions.Tests/CloneTxTests/Run_cloneType__Normal__isoLevel__Serializable__forcePromote__False__completeClone__False__expectedStatus__Committed_/? 

I didn't see any existing issues in corefx and this PR wouldn't cause that issue, as it doesn't touch any code.

**Comment by stephentoub** [comment]
> @stephentoub have you seen issues with the System.Transation tests

I've seen one failure several times:
https://github.com/dotnet/corefx/issues/11737
I disabled that test this morning:
https://github.com/dotnet/corefx/pull/11745
Yours is a different one, though.

cc: @jimcarley

**Comment by weshaggard** [comment]
Merged but @jimcarley it would be appreciated if you can look in to the transactions test failure. We want to make sure tests in our CI are reliable.

**Comment by jimcarley** [comment]
Okay. I have fallen behind a bit. I will look into these soon.

**Pull request merged**
