### PR TITLE
Remove dead code from System.Runtime

### PR DESCRIPTION
**Pull request by alexanderkozlenko**
Remove unused private fields, methods, nested types and resource strings.

### CODE REVIEW

**Comment by davidsh** [comment]
@CIPop @stephentoub PTAL

**Comment by CIPop** [comment]
LGTM

**Comment by mellinoe** [comment]
Could you update your branch with dotnet/master? It looks like at least the failure in the OpenSUSE builds is a bit out of date wrt our current source code.

**Comment by stephentoub** [comment]
@alexanderkozlenko, thanks for doing this, but it looks like you've submitted your PR against the future rather than master branch.  Can you close this PR and resubmit against master?

**Pull request closed without merging**
