### PR TITLE
[release/1.0.0] Check if process has started, before checking for exit.

### LINKED ISSUE #12696: [1.0.0] TestUserCredentialsPropertiesOnWindows failing on Windows (v1.0 only)
```
System.Diagnostics.Tests.ProcessStartInfoTests.TestUserCredentialsPropertiesOnWindows [FAIL]
        System.InvalidOperationException : No process is associated with this object.
        Stack Trace:
           D:\j\workspace\outerloop_win---2155886e\src\System.Diagnostics.Process\src\System\Diagnostics\Process.cs(779,0): at System.Diagnostics.Process.EnsureState(State state)
           D:\j\workspace\outerloop_win---2155886e\src\System.Diagnostics.Process\src\System\Diagnostics\Process.cs(189,0): at System.Diagnostics.Process.get_HasExited()
           D:\j\workspace\outerloop_win---2155886e\src\System.Diagnostics.Process\tests\ProcessStartInfoTests.cs(393,0): at System.Diagnostics.Tests.ProcessStartInfoTests.TestUserCredentialsPropertiesOnWindows()
```

Examples:
https://ci.dot.net/job/dotnet_corefx/job/release_1.0.0/job/outerloop_windows_nt_release/13/
https://ci.dot.net/job/dotnet_corefx/job/release_1.0.0/job/outerloop_windows_nt_debug/12/
https://ci.dot.net/job/dotnet_corefx/job/release_1.0.0/job/outerloop_win10_release/12/
https://ci.dot.net/job/dotnet_corefx/job/release_1.0.0/job/outerloop_win10_debug/12/
https://ci.dot.net/job/dotnet_corefx/job/release_1.0.0/job/outerloop_windows_nt_release/12/
https://ci.dot.net/job/dotnet_corefx/job/release_1.0.0/job/outerloop_windows_nt_debug/11/
https://ci.dot.net/job/dotnet_corefx/job/release_1.0.0/job/outerloop_win10_release/11/
https://ci.dot.net/job/dotnet_corefx/job/release_1.0.0/job/outerloop_win10_debug/11/
http://ci.dot.net/job/dotnet_corefx/job/release_1.0.0/job/outerloop_windows_nt_release/11/
...

### PR DESCRIPTION
**Pull request by Priya91**
fixes #12696 

porting the test fix from master to release/1.0.0

cc @karelz @danmosemsft @leecow

### CODE REVIEW

**Comment by Priya91** [comment]
@dotnet-bot test Innerloop CentOS7.1 Release Build and Test

**Comment by Priya91** [comment]
Merge PR after release/1.0.0 is open

**Comment by stephentoub** [comment]
> after release/1.0.0 is open 

@karelz, when is that happening?

**Comment by gkhanna79** [comment]
Please holdoff on this merge until 1.0.X branches reopen.

CC @leecow

**Comment by stephentoub** [comment]
> Please holdoff on this merge until 1.0.X branches reopen.

Which is when?

**Comment by gkhanna79** [comment]
The branch is in Escrow and expect it to open in the week of 12/5.

**Comment by Priya91** [comment]
@gkhanna79 Can this be merged now?

**Comment by ellismg** [comment]
1.0.3 has shipped now, so this should be safe to merge (I'd ping @gkhanna79 or Shiproom to confirm)

**Comment by gkhanna79** [comment]
Yes, this can be merged if shiproom approval is in place.

**Comment by karelz** [comment]
Seems that @Priya91 already got the approval -- see https://github.com/dotnet/corefx/pull/13732#issuecomment-261126664
@Priya91 can you please merge it?

**Pull request merged**
