### PR TITLE
Avoid calling Array.Clear on the entire _array when Queue is already empty.

### PR DESCRIPTION
**Pull request by DmitryKakurin**
Now for non-generic Queue.

### CODE REVIEW

**Comment by stephentoub** [comment]
Thanks.  The change LGTM. 

Two things:
1. Can you please rebase away the merge commit?
2. Can you please double-check that there's a test covering the empty clear case, and if there isn't, add one?  (I did that for the generic queue here: https://github.com/dotnet/corefx/pull/3158)

**Comment by DmitryKakurin** [comment]
Done, please take another look.

**Comment by mmitche** [comment]
@dotnet-bot test this please (one of the test machines appears to be down)

**Comment by stephentoub** [comment]
LGTM. Thanks, @DmitryKakurin.

**Pull request merged**
