### PR TITLE
Disable test build when skiptests is provided

### LINKED ISSUE #10082: build.sh build all the tests even if skiptests is turned on
It seems that there is no way to suppress the build of test suites in build.sh. It always builds all the tests even if skiptests is turned on.

### PR DESCRIPTION
**Pull request by parjong**
To fix #10082

### CODE REVIEW

**Comment by parjong** [comment]
@dotnet-bot Test Innerloop CentOS7.1 Release Build and Test please

**Comment by joperezr** [comment]
Thanks for your contribution! I'm not sure if it's a good idea to skip building the tests with this property though, because we actively use skiptests property in some of our workflows and I believe that in those cases we do want the tests to at least build. @maririos is doing some changes on how to interact with the workflow, so almost all of this script will be nuked anyways, so maybe she can take a look and see if we want to add an extra property to skip building the tests?

**Comment by maririos** [comment]
@parjong A while ago I though about doing the same, but because of those dependencies that we have and that @joperezr pointed out, I ended up creating the `buildTests` variable.
Instead of disabling building the tests when people call `skiptests` we should just add another option so that we have the flexibility to build and run as a separate step.

I'm working on changing the dev workflow scripts (PR #9977 ), but I'm taking into account this behavior so we are still going to be able to skip building tests :)

Thanks for the contribution!

**Comment by parjong** [comment]
@joperezr @maririos Thanks for your comment and effort. I'll wait PR #9977 :+1: 

For me, this feature is necessary to reduce build time, but anyway I can do it locally on my side. I'll be happy if PR #9977 will allow me not to build tests at all. In addition, if PR #9977 allows us not to build  all the windows related DLL(s) when we targets to non-windows OS, I'll love it :+1:

**Comment by parjong** [comment]
@joperezr @maririos Do you want me to close this PR? If you want, I want to close this PR.

**Comment by joperezr** [comment]
Sure. I'll go ahead and close this one then.

**Comment by maririos** [comment]
@parjong PR #9977 will allow you to do those things, and for example if you only want to build the binaries but you don't want to restore the packages, build tests or build the packages, you could totally do that with one command `build-managed.cmd -binaries` :)

**Pull request closed without merging**
