### PR TITLE
Fixing a typo in developer-guide.md

### PR DESCRIPTION
**Pull request by gsfreema**
The words 'are' and 'and' were mistyped and need to be switched.  This
is the same issue that was just fixed in coreclr.

Please forgive the fact that I'm new to this process, and I'm not 
sure if there is something special I'm supposed to do to handle
merge commits to my fork so that they don't appear in PRs.  Any info
here would be appreciated.  Thank you.

### CODE REVIEW

**Comment by JonHanna** [comment]
> and I'm not
sure if there is something special I'm supposed to do to handle
merge commits to my fork so that they don't appear in PRs

You can squash the commits, so that the branch then looks like it is just one commit ahead, which will be the one with the fix. Then push again with the `--force-with-lease` option (if you use TortoiseGit this is the "known changes" option in the push dialogue) and the branch gets rewritten as if that was the only commit it had.

**Comment by stephentoub** [comment]
Other than needing squashing, LGTM.  Thanks for the fix.

**Comment by gsfreema** [comment]
This PR has left me feeling that I need a lot more experience with git.  I hope I have everything correct now.  Thanks for all the help.

**Comment by stephentoub** [comment]
Thanks.

**Pull request merged**
