### PR TITLE
Update enum tests

### PR DESCRIPTION
**Pull request by TylerBrinkley**
Update enum tests for [coreclr#22161](https://github.com/dotnet/coreclr/pull/22161).

### CODE REVIEW

**Comment by stephentoub** [comment]
> Update enum tests for coreclr#22161.

Can you elaborate on these changes?  Are you adding tests that previously worked and continue to work, i.e. increasing code coverage?  Are you changing the tests to accommodate things that used to throw and to don't throw?  Or that used to not throw and now throw?

**Comment by TylerBrinkley** [comment]
Yes, sorry I should have been more clear. These changes are to accommodate things that used to throw and now don't as well as the few breaking changes mentioned in https://github.com/dotnet/coreclr/pull/22161 regarding parameter names in thrown exceptions.

**Comment by karelz** [comment]
@TylerBrinkley what is status of this PR - there is no update for 1+ month. Are you blocked on something?

**Comment by TylerBrinkley** [comment]
@karelz This PR is blocked on https://github.com/dotnet/coreclr/pull/22161. If/when that is approved then this PR can be merged assuming the changes are acceptable.  These changes are to accommodate things that used to throw and now don't with the Enum implementation as well as the few breaking changes mentioned in dotnet/coreclr#22161 regarding parameter names in thrown exceptions.

**Comment by karelz** [comment]
Given that the CoreCLR PR is still open, I suggest to close this one until the dependening one is merged. Is that ok @TylerBrinkley?

**Comment by TylerBrinkley** [comment]
Sure, that's fine with me.

**Comment by karelz** [comment]
Thanks! That will help us keep some sanity in opened PRs and avoid accidental pings on this one ;)

**Pull request closed without merging**
