### PR TITLE
Expose {ReadOnly}Memory from System.Runtime

### PR DESCRIPTION
**Pull request by ahsonkhan**
Part of https://github.com/dotnet/corefxlab/issues/1711

Adding the following types:
- Memory\<T\>
- ReadOnlyMemory\<T\>
- OwnedMemory\<T\>
- MemoryHandle
- IRetainable

Order of changes:
1) Add to mscorlib (https://github.com/dotnet/coreclr/pull/13583).
2) After the type has been added to mscorlib, add impl (for portable) and type forwarders to System.Memory (https://github.com/dotnet/corefx/pull/23701) and System.Runtime (this PR) here in corefx.
3) Remove impl from corefxlab and update uses/references in Pipelines/Buffers.Experimental.
4) Other changes/additions like review/add APIs from MemoryExtensions

cc @shiftylogic, @KrzysztofCwalina, @davidfowl, @jkotas, @stephentoub, @AtsushiKan, @ericstj

### CODE REVIEW

**Comment by ahsonkhan** [comment]
I am not sure how to resolve this error:
System.Runtime.cs(3815,108): error CS0234: The type or namespace name 'GCHandle' does not exist in the namespace 'System.Runtime.InteropServices' (are you missing an assembly reference?) [D:\GitHub\Fork\corefx\src\System.Runtime\ref\System.Runtime.csproj]

GCHandle was not in .NET Standard 1.0 (it was added in .NET Standard 1.1). 
https://github.com/dotnet/standard/blob/master/docs/versions/netstandard1.1_diff.md
Any ideas?

**Comment by stephentoub** [comment]
> Any ideas?

GCHandle is currently defined in System.Runtime.InteropServices:
https://github.com/dotnet/corefx/blob/bffef76f6af208e2042a2f27bc081ee908bb390b/src/System.Runtime.InteropServices/ref/System.Runtime.InteropServices.cs#L259
Presumably it'll need to be forwarded down to System.Runtime.
cc: @weshaggard

**Comment by weshaggard** [comment]
>Presumably it'll need to be forwarded down to System.Runtime.

Yes it would need to be moved down to resolve this dependency.

@ahsonkhan have these APIs been reviewed and approved yet? If so can you point me to the issue for that if not can you please file an issue to track the review of these APIs?

**Comment by ahsonkhan** [comment]
> have these APIs been reviewed and approved yet? If so can you point me to the issue for that

Yes, we had the API review iterations offline back in June and it was approved. I don't have an API specific issue (this is the issue for moving the types to corefx - https://github.com/dotnet/corefxlab/issues/1711).

cc @terrajobst 

> if not can you please file an issue to track the review of these APIs?

Should I file an issue regardless?

**Comment by mmitche** [comment]
@dotnet-bot test this please (accidentlaly deleted VMs while in use)

**Comment by ahsonkhan** [comment]
Is the PR good to go?

**Comment by stephentoub** [comment]
Thanks, @ahsonkhan. LGTM.

**Pull request merged**
