### PR TITLE
Remove personal copyright from License Headers

### PR DESCRIPTION
**Pull request by JonHanna**
Change all license headers © Jon Hanna to .NET Foundation and Contributors.

Change all license headers © .NET Foundation and contributors. (lower case) to
.NET Foundation and Contributors to match form in project license file.

### CODE REVIEW

**Comment by JonHanna** [comment]
Test Innerloop Ubuntu Debug Build and Test please
("No space left on device" so this will likely just fail too, but maybe there's another machine).

**Comment by stephentoub** [comment]
https://github.com/dotnet/corefx/pull/5723 changes the entire repo to match the new guidance.

**Comment by JonHanna** [comment]
Cool. I would think you'd need the permission of anyone mentioned in a copyright notice to change that notice, in which case I hereby allow any such changes that relate to mine.

**Comment by stephentoub** [comment]
@richlander?

**Pull request closed without merging**
