### PR TITLE
 Fix Loop in System.Private.Uri

### PR DESCRIPTION
**Pull request by wtgodbe**
Ports https://github.com/dotnet/corefx/commit/6da61ff4d24c7875087cb6afe93140ba0e3a6532 to master

CC @karelz @davidsh

### CODE REVIEW

**Comment by davidsh** [comment]
I assume this is the same as #37733?

**Comment by wtgodbe** [comment]
@davidsh yes, that PR wasn't updating when I pushed a new commit (for some reason), so I just closed it & reopened this PR against the same branch.

**Comment by davidsh** [comment]
Please run all Outerloop tests as well.

**Comment by davidsh** [comment]
@wtgodbe You can't put all 3 azp commands in one comment, https://github.com/dotnet/corefx/pull/38076#issuecomment-497507984

You need to do each one at a time.  Or do "/azp run" which runs all inner and outerloop

**Comment by wtgodbe** [comment]
Outerloop failures are unrelated, merging

**Pull request merged**
