### PR TITLE
Pass CancellationToken to DbDataReader

### PR DESCRIPTION
**Pull request by campersau**
looks like this was missed in https://github.com/dotnet/corefx/pull/36123

### CODE REVIEW

**Comment by campersau** [comment]
Yes, I can add some tests but it may take a while for me to setup the environment. <sub>I just edited it through github 😄 </sub>

**Comment by campersau** [comment]
@stephentoub added tests

**Comment by stephentoub** [comment]
cc: @roji

**Comment by roji** [comment]
Indeed, thanks for catching this... Will do an extra pass to make sure this isn't a problem elsewhere. Will also add cancellation tests for all other async APIs.

**Comment by roji** [comment]
cc @divega @ajcvickers

**Comment by roji** [comment]
Note #38453 which generalizes cancellation token tests to the entire async API surface.

**Pull request merged**
