### PR TITLE
Remove buffer argument from WebSocket.CreateFromStream

### PR DESCRIPTION
**Pull request by stephentoub**
Fixes https://github.com/dotnet/corefx/issues/28138
cc: @davidfowl, @pakrym, @karelz

### CODE REVIEW

**Comment by davidfowl** [comment]
> 10:25:32 System/Net/Managed/WebSockets/HttpWebSocket.Managed.cs(66,45): error CS1501: No overload for method 'CreateFromStream' takes 5 arguments [/mnt/j/workspace/dotnet_corefx/master/linux-TGroup_netcoreapp+CGroup_Release+AGroup_x64+TestOuter_false_prtest/src/System.Net.HttpListener/src/System.Net.HttpListener.csproj]

HttpListener needs to be updated

**Comment by stephentoub** [comment]
Windows failures are unrelated, but re-running anyway
@dotnet-bot test Windows x64 Debug Build please
@dotnet-bot test Windows x86 Release Build please

**Comment by stephentoub** [comment]
Windows failures are https://github.com/dotnet/corefx/issues/28631

**Pull request merged**
