### PR TITLE
Adding some more System.Math tests to cover areas where other platforms may differ from windows

### PR DESCRIPTION
**Pull request by tannergooding**
These are all scenarios which have custom handling in PAL but did not have explicit coverage here to validate the behavior is consistent across all platforms (including Windows).

### CODE REVIEW

**Comment by tannergooding** [comment]
FYI. @stephentoub 

These are the other 12 tests I mentioned in #9065 and should not be merged until https://github.com/dotnet/coreclr/pull/5399 goes in and is being consumed by CoreFX.

This also removes the `[ActiveIssue(9053)]` (is there an attribute used to track past issues associated with a test?) attribute from `MathTests.Pow`, since #9053 will be resolved when this goes in.

**Comment by stephentoub** [comment]
Thanks, @tannergooding.

> is there an attribute used to track past issues associated with a test?

No

**Comment by stephentoub** [comment]
LGTM

**Comment by tannergooding** [comment]
Test Innerloop Windows_NT Release Build and Test please

`System.Net.Security.Tests.ServerNoEncryptionTest.ServerNoEncryption_ClientAllowNoEncryption_ConnectWithNoEncryption` failure due to closed transport stream.

**Comment by tannergooding** [comment]
Non-Windows failures are expected. `pow(-0, -1)` is failing because it returns `double.PositiveInfinity` instead of the expected `double.NegativeInfinity`.

https://github.com/dotnet/coreclr/pull/5399 resolves the issue in the `PAL_pow` implementation by special casing the scenario to return the expected result.

**Comment by stephentoub** [comment]
@dotnet-bot test this please

**Comment by tannergooding** [comment]
Test Innerloop OSX Release Build and Test please

Previous run failed due to Java/Jenkins remoting error: http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/master/job/osx_release_prtest/1794/

**Comment by tannergooding** [comment]
Test Innerloop OSX Release Build and Test please

Previous run failed because machine went offline while uploading the test results: http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/master/job/osx_release_prtest/1801/

@mmitche, this is the second occurence of this failure. The first was on MacPro12 the second on MacPro3

**Comment by tannergooding** [comment]
@stephentoub, All tests are passing.

**Comment by stephentoub** [comment]
Thanks.

**Pull request merged**
