### PR TITLE
Testing CI system for crashing a test actually failing CI

### PR DESCRIPTION
**Pull request by weshaggard**
Testing for https://github.com/dotnet/corefx/issues/20172

### CODE REVIEW

**Comment by weshaggard** [comment]
This PR should fail all the test runs but it likely will not. We will need https://github.com/dotnet/buildtools/pull/1512 to have these fail as expected.

**Comment by weshaggard** [comment]
As expected the CI says success, https://ci.dot.net/job/dotnet_corefx/job/master/job/windows_nt_debug_prtest/8319/consoleFull, when it should have failed. 

I will be pushing a buildtools update to this branch soon to show that it fails correctly, then I will revert my break and just merge the buildtools change.

**Comment by weshaggard** [comment]
@mellinoe @safern is it a known issue that that the netfx debug test builds hang on a crash (https://ci.dot.net/job/dotnet_corefx/job/master/job/netfx_windows_nt_debug_prtest/614/)?

**Comment by weshaggard** [comment]
@dotnet-bot test Innerloop netfx Windows_NT Debug x86 Build and Test please

**Comment by safern** [comment]
> @mellinoe @safern is it a known issue that that the netfx debug test builds hang on a crash 

Not that I'm aware of.

**Comment by weshaggard** [comment]
@dotnet-bot test Innerloop Windows_NT Debug x86 Build and Test please

**Comment by weshaggard** [comment]
Successfully failed now after BuildTools change. https://ci.dot.net/job/dotnet_corefx/job/master/job/windows_nt_debug_prtest/8325/ Now I'm going to update this PR to just be the BuildTools change and remove my break.

**Comment by weshaggard** [comment]
This is ready to merge once CI is green.

**Comment by weshaggard** [comment]
@dotnet-bot test Innerloop Tizen armel Debug Cross Build please

**Comment by danmosemsft** [comment]
Thanks for fixing this @weshaggard ! Hopefully it will get into 2.0

**Pull request merged**
