### PR TITLE
Update packages to rc3-23929-00

### PR DESCRIPTION
**Pull request by stephentoub**
cc: @weshaggard, @ericstj, @eerhardt 
(Looks like Eric's script hasn't been turned on yet, so I'm bumping us up in the interim.)

### CODE REVIEW

**Comment by eerhardt** [comment]
> Looks like Eric's script hasn't been turned on yet, so I'm bumping us up in the interim.

It's slowly coming.  The ps1 script is in the repo now, which was step 1.

We need to make something to invoke it now, which I'm working on.

**Comment by eerhardt** [comment]
:shipit: when CI passes.

**Comment by stephentoub** [comment]
Awesome.  Great to see it coming along.  Thanks, Eric.

**Comment by stephentoub** [comment]
@dotnet-bot test this please

**Comment by stephentoub** [comment]
@dotnet-bot test this please

**Pull request closed without merging**
