### PR TITLE
add buffer configuration variations to Socket stress test

### PR DESCRIPTION
**Pull request by geoffkizer**
Instead of always using a single buffer for Send/Receive, randomly pick between single buffer and multiple buffer configurations.

I was hoping to repro #16213 with this, but I wasn't able to.  Still, seems like a good thing to do.

@stephentoub @davidsh @CIPop @Priya91

### CODE REVIEW

**Comment by geoffkizer** [comment]
@dotnet-bot test outerloop OSX Debug
@dotnet-bot test outerloop OSX Release
@dotnet-bot test outerloop Ubuntu14.04 Debug
@dotnet-bot test outerloop Ubuntu14.04 Release
@dotnet-bot test outerloop Windows_NT Debug
@dotnet-bot test outerloop Windows_NT Release

**Comment by zabulus** [comment]
Randomizing of input values is not good idea for tests, because it's hard to reproduce a future test failure, tests start act non-deterministically. I suggest at least add fixed seed for the added Random objects. Or maybe dump random seed to log, to help in further reproducing.

**Comment by geoffkizer** [comment]
This is a stress test; randomization is good.  It's already quite nondeterministic.

I do wonder whether we should have a specific way to categorize stress tests, though.

In general we need better and more thorough stress tests for Sockets.

**Comment by zabulus** [comment]
> randomization is good. It's already quite nondeterministic.

My concern more about reproducing a failure of the test. In case it fails, how the one can reproduce the failure to debug the cause?

**Comment by geoffkizer** [comment]
You can't expect stress tests to be reproducible in the same way we expect unit tests to be. 

Ideally, we catch as many issues as we can via unit tests.  Stress testing finds issues that, by their nature, are hard to find and hard to reproduce.  Debugging them can certainly be challenging, but that doesn't mean we shouldn't do stress testing.

**Pull request merged**
