### PR TITLE
Change to build each commit

### PR DESCRIPTION
**Pull request by mmitche**
Will disable the scheduled triggers after this.

### CODE REVIEW

**Comment by safern** [comment]
> Will disable the scheduled triggers after this.

Why? Do we really want to have an official build in corefx per commit? It seems like too much overhead for corefx. We merge a lot of commits in our daily basis. cc: @danmosemsft @ericstj

**Comment by danmosemsft** [comment]
In 2018 we averaged 25 commits a day into master, 7 days a week.

**Comment by mmitche** [comment]
Primarily, that's what the other repos are doing, and it will improve the rate at which builds flow to the other repos. This is important around preview build time.  We can leave it as is, but it will make things a bit slower.  That does mean that someone will need to manually trigger this build when we have bits that need to flow at the end of release cycles.

**Comment by mmitche** [comment]
BTW I don't think you're averaging 25 PRs merged per day. GitHub is counting more than just the PR merge commits.  AzDO will batch commits together, so the number won't be that high.

**Comment by safern** [comment]
> Primarily, that's what the other repos are doing, and it will improve the rate at which builds flow to the other repos. This is important around preview build time. We can leave it as is, but it will make things a bit slower. That does mean that someone will need to manually trigger this build when we have bits that need to flow at the end of release cycles.

Another option is have more triggers a day. Like 5 am, 11am, 4pm and 8pm if there has been a commit in between?

**Comment by mmitche** [comment]
That's probably fine too

**Comment by safern** [comment]
> That's probably fine too

Let's start with more triggers and if we see that we're in the need of triggering manual builds to accelerate the rate which builds flow,  then we can try per commit builds. How does that sound?

**Comment by safern** [comment]
I will merge this and add the new triggers. If we find this is necessary we can then just stop overriding this property from the build definition and remove the scheduled triggers.

**Pull request merged**
