### PR TITLE
Fix XmlSerializer(Type type, Types[] extraTypes) on UWP

### LINKED ISSUE #19811: XmlSerializerTests.Xml_KnownTypesThroughConstructorWithArrayProperties Failed
Test `XmlSerializerTests.Xml_KnownTypesThroughConstructorWithArrayProperties` failed on UWP when using Sg.

```
      <test name="XmlSerializerTests.Xml_KnownTypesThroughConstructorWithArrayProperties" type="XmlSerializerTests" method="Xml_KnownTypesThroughConstructorWithArrayProperties" time="0.0046081" result="Fail">
        <failure exception-type="System.InvalidCastException">
          <message><![CDATA[System.InvalidCastException : Specified cast is not valid.]]></message>
          <stack-trace><![CDATA[   at XmlSerializerTests.Xml_KnownTypesThroughConstructorWithArrayProperties() in d:\OSS\corefx-1\corefx\src\System.Private.Xml\tests\XmlSerializer\XmlSerializerTests.cs:line 2101
   at _$ILCT$.$ILT$ReflectionDynamicInvoke$.InvokeRetV(Object thisPtr, IntPtr methodToCall, ArgSetupState argSetupState, Boolean targetIsThisCall)
   at System.InvokeUtils.CalliIntrinsics.Call(IntPtr dynamicInvokeHelperMethod, Object thisPtr, IntPtr methodToCall, ArgSetupState argSetupState, Boolean isTargetThisCall)
   at System.InvokeUtils.CallDynamicInvokeMethod(Object thisPtr, IntPtr methodToCall, Object thisPtrDynamicInvokeMethod, IntPtr dynamicInvokeHelperMethod, IntPtr dynamicInvokeHelperGenericDictionary, Object targetMethodOrDelegate, Object[] parameters, BinderBundle binderBundle, Boolean invokeMethodHelperIsThisCall, Boolean methodToCallIsThisCall) in f:\dd\ndp\fxcore\CoreRT\src\System.Private.CoreLib\src\System\InvokeUtils.cs:line 400]]></stack-trace>
        </failure>
      </test>
```

### PR DESCRIPTION
**Pull request by shmao**
On UWP, if one used `XmlSerializer(Type type, Types[] extraTypes)` to create serializer for `type`, UWP toolchain would pre-generate the serializer for the type and make the `extraTypes` as the type's known types. To achieve the latter, UWP toolchain uses one `XmlReflectionImporter` to import *all types* (all types require serialization in the app) so that the `extraTypes` would be treated as known types. But there're some problems with this.

1. The type would have more known types than those included by `extraTypes`.
2. There might be type conflicts as the importer imports all types and the type scope grows.
And etc.

The fix is to make the constructor to always use reflection based serialization.

Fix #19811

### CODE REVIEW

**Comment by shmao** [comment]
@dotnet-bot test Innerloop netfx Windows_NT Debug x86 Build and Test
@dotnet-bot test Innerloop netfx Windows_NT Release x64 Build and Test 
@dotnet-bot test Portable Windows x64 Release Build
@dotnet-bot test Win x64 tests - Debug - Windows.10.Nano.Amd64.Open

**Comment by shmao** [comment]
@dotnet-bot test Portable Windows x64 Release Build 
@dotnet-bot test Win x64 tests - Debug - Windows.10.Nano.Amd64.Open

**Comment by shmao** [comment]
@dotnet-bot test Portable Windows x64 Release Build 
@dotnet-bot test Win x64 tests - Debug - Windows.10.Nano.Amd64.Open

**Comment by mconnew** [comment]
:+1:

**Comment by shmao** [comment]
> System.Diagnostics.Process.Tests failed.

I'm not sure why `Win x64 tests - Debug - Windows.10.Nano.Amd64.Open` didn't restart. But the failed test was not related to the change.

I'm merging the PR. Thanks for reviewing the changes, @mconnew

**Pull request merged**
