### PR TITLE
Remove unnecessary else from WebSocket.cs

### PR DESCRIPTION
**Pull request by petvas**
return in if, else is not necessary

### CODE REVIEW

**Comment by caesar1995** [comment]
What optimization this change can achieve?

**Comment by petvas** [comment]
@caesar1995 "no else after return" rule, make the method flatter and now the 1st if is a GuardClause, I think it is easier to read and understand the code in this way.

**Comment by stephentoub** [comment]
I don't have a strong opinion on whether to take this change.  But this is purely a matter of stylistic preference; some folks prefer it the original way, others prefer it the revised way.  There is zero impact here on code quality, i.e. this is not an optimization.

**Comment by davidsh** [comment]
>But this is purely a matter of stylistic preference; some folks prefer it the original way, others prefer it the revised way.

IMHO, having less code is easier to maintain and helps keep the codebase healthy.  And I agree that having an 'else' clause that isn't needed is something that should be removed.

**Comment by davidsh** [comment]
@dotnet-bot test Outerloop Windows x64 Debug Build
@dotnet-bot test Outerloop Linux x64 Debug Build
@dotnet-bot test Outerloop NETFX x86 Debug Build
@dotnet-bot test Outerloop UWP CoreCLR x64 Debug Build
@dotnet-bot test Outerloop OSX x64 Debug Build

**Pull request merged**
