### PR TITLE
Initial commit of System.Collections tests

### PR DESCRIPTION
**Pull request by FiveTimesTheFun**

### CODE REVIEW

**Comment by FiveTimesTheFun** [comment]
Submission containing materials of a third party: Microsoft Corporation.

**Comment by FiveTimesTheFun** [comment]
No problem @dnfclas.

**Comment by nguerrera** [comment]
@FiveTimesTheFun Is it ok to call DNFBOT that? :smirk:

**Comment by FiveTimesTheFun** [comment]
I hope so, I hope it(?) will correct me otherwise.

**Comment by ellismg** [comment]
I made it through a few files and gave a bunch of comments.  The diff makes the github site very slow, so I think I will need to take a look offline and then post a bunch of comments back.

I assume everything I am going to find is going to be "cosmetic" issues with the test, so you're probably okay to go in sooner.  I just want to encourage us to write our tests in a more modern style (I understand we are mechanically converting existing assets which are quite old).

**Comment by FiveTimesTheFun** [comment]
Thanks @ellismg for the good notes.  I agree with what you've written, although I agree it was difficult to go through in the github UI due to the size of the commit (perhaps line numbers in your comments would help, so I can look at the code in another editor while reading your notes in the conversation view).  You didn't even get to the tests that used "Driver" classes as a legacy from being converted from old-tree to ToF to xunit.

As you pointed out this was a straight mechanical port.  I believe there's real value in regression protection and developer efficiency in simplifying and modernizing these existing tests.  While believing that, I still think there's value from starting with a straight mechanical port.  I believe more useful reliable coverage sooner is better than less.  I also believe that a straight port provides a stable baseline for future changes to be evaluated against, and I believe it's appropriate for that baseline to be the same code that has provided regression protection in previous releases.  A compiling and passing port as a baseline also aids in future refactoring while reducing the risk of test regressions being introduced.

I've opened a GitHub issue https://github.com/dotnet/corefx/issues/754 to track work to these tests, and mentioning it here should provide a link that will keep track the notes you've already made.

I'll wait for a more definitive LGTM before merging in these ported assets :)

**Comment by ellismg** [comment]
As we discussed offline, your approach is reasonable given the constraints of the team.  I skimmed the tests and the static stuff scared me a little.  Once you've gotten 1000 clean test runs in a row, consider this a LGTM, and we'll work on paying down more debt later.

**Comment by FiveTimesTheFun** [comment]
Thanks @ellismg .  While I didn't see any failures related to the static state, I agree with you it doesn't look good, and I could see how it could cause a test failure in one area to look like a test failure in another.  Because of that I've removed a lot of the static state and updated the pull request.  I also disabled a test that I'm looking at that failed twice in the 1000 run, but I don't immediately see why.  I broke in windbg and didn't understand the state I was seeing, the test not using any static state that I could see.

**Comment by ellismg** [comment]
LGTM.

**Comment by FiveTimesTheFun** [comment]
Thanks Matt.

**Pull request merged**
