### PR TITLE
Cherry-picking test fix for System.IO.FileSystem from master to release2.2

### LINKED ISSUE #30742: TimesIncludeMillisecondPart_OSX test fails locally on macOS
This test is not failing on CI but does fail on locally on mac OS. 

We need to either remove or disable the test.

Here's the callstack:
```
     System.IO.Tests.DirectoryInfo_GetSetTimes.TimesIncludeMillisecondPart_OSX [FAIL]
        Assert.All() Failure: 9 out of 9 items in the collection did not pass.
        [8]: Xunit.Sdk.EqualException: Assert.Equal() Failure
             Expected: 0
             Actual:   796
                at Xunit.Assert.Equal[T](T expected, T actual, IEqualityComparer`1 comparer)
                at System.IO.Tests.BaseGetSetTimes`1.<>c__DisplayClass11_0.<TimesIncludeMillisecondPart_OSX>b__0(TimeFunction function) in /Users/maryam/CodeHub/corefx/src/System.IO.FileSystem/tests/Base/BaseGetSetTimes.cs:line 149
                at Xunit.Assert.All[T](IEnumerable`1 collection, Action`1 action)
...
```

cc: @danmosemsft

### PR DESCRIPTION
**Pull request by maryamariyan**
Updating test to assert milisecond granularity for (#30763)

- non any linux or
- OSX non-HFS driver formats

Fixes #30742

cc: @danmosemsft @eerhardt @jkotas

### CODE REVIEW

**Comment by maryamariyan** [comment]
This PR cherry picks PR https://github.com/dotnet/corefx/pull/30763 to release/2.2 branch

**Comment by maryamariyan** [comment]
@dotnet-bot test OSX x64 Debug Build

**Comment by Anipik** [comment]
These tests have changed again. The release version of the PR is https://github.com/dotnet/corefx/pull/31046 The PR is blocked because the  servicing 2.1.4  is not opened yet

**Comment by maryamariyan** [comment]
**Shiproom template**

**Description**
Currently 4 System.IO.FileSystem tests fail on this branch. this PR which cherry-picks a PR from master will help fix them.

**Customer Impact**
no impact. This now helps run all tests successfully for corefx in non HFS mac systems

**Regression?**
No regression

**Risk**
Low risk because this change is already in master and also because it is just a test fix to System.IO.FileSystem.

**Pull request merged**
