### PR TITLE
Re-enable StyleCop warnings SA1028 and SA1518 (trailing whitespace and blank lines)

### PR DESCRIPTION
**Pull request by stephentoub**
Mechanical/automated change.  The only manual changes were a) removing the two rules from the CodeAnalysis.ruleset file, b) removing spaces from one line of a .targets file that is used to generate a .cs file, and c) reverting the changes in a few test files where the naive replacement happened in the middle of a verbatim string where the whitespace actually mattered.

Changes were made via:
```C#
using System;
using System.IO;

class Program
{
    static void Main()
    {
        foreach (string path in Directory.EnumerateFiles(@"d:\repos\corefx\src\", "*.cs", SearchOption.AllDirectories))
        {
            bool modified = false;
            string[] lines = File.ReadAllLines(path);

            // Remove whitespace from end of lines
            for (int i = 0; i < lines.Length; i++)
            {
                string line = lines[i];
                int spaces = 0;
                for (int c = line.Length - 1; c >= 0; c--)
                {
                    if (!char.IsWhiteSpace(line[c])) break;
                    spaces++;
                }
                if (spaces > 0)
                {
                    lines[i] = line.Substring(0, line.Length - spaces);
                    modified = true;
                }
            }

            // Remove ending blank lines
            int endingBlankLines = 0;
            for (int i = lines.Length - 1; i >= 0; i--)
            {
                if (!string.IsNullOrWhiteSpace(lines[i])) break;
                endingBlankLines++;
            }
            if (endingBlankLines > 0)
            {
                lines = lines.AsSpan(0, lines.Length - endingBlankLines).ToArray();
                modified = true;
            }

            if (modified)
            {
                File.WriteAllLines(path, lines);
                Console.WriteLine(path);
            }
        }
    }
}
```

cc: @safern, @ViktorHofer

### CODE REVIEW

**Comment by danmosemsft** [comment]
That's pretty cool, that we will never have trailing ws again...

**Comment by ViktorHofer** [comment]
unfortunately that's not guaranteed for msbuild files 😥

**Comment by sharwell** [comment]
The code fix for this will correctly account for verbatim string literals with embedded trailing whitespace. What steps are we taking here to verify correctness for that?

**Comment by sharwell** [comment]
Also, it's possible for File APIs to make subtle changes to characters in files that were not encoded in the expected manner. Are we certain that all files in the repository are UTF-8 with BOM and/or have some other verification mechanism to ensure that only whitespaces are handled here?

**Comment by stephentoub** [comment]
> The code fix for SA1028 will correctly account for verbatim string literals with embedded trailing whitespace. 

Show me how to run the code fix over hundreds of discrete projects today with minimal fuss, and I'll do that instead.

> What steps are we taking here to verify correctness for that?

a) In product src we have very little use of verbatim strings in product src, and basically none that spans lines.
b) Tests.

**Pull request merged**
