### PR TITLE
Added tests for XmlLicenseTransform (coverage 93.9%)

### PR DESCRIPTION
**Pull request by StanislavUshakov**
Added tests and test data for XmlLicenseTransform.
Overall code coverage for System.Security.Cryptography.Xml is 70.4%

Part of #16781

### CODE REVIEW

**Comment by danmosemsft** [comment]
@mmitche some docker image missing for arm?

**Comment by StanislavUshakov** [comment]
@dotnet-bot test Innerloop Ubuntu16.04 arm Debug Cross Build

**Comment by mmitche** [comment]
@danmosmsft No idea, I haven't touched the config of that stuff in forever.

**Comment by krwq** [comment]
Nice @StanislavUshakov - I've just added similar PR

**Comment by StanislavUshakov** [comment]
@krwq Actually I used a valid license file with type .xrm-ms for the structure reference and then substituted the RSA key/value with the Mono One and other real stuff with the testing one.

**Comment by krwq** [comment]
Ok, I'm merging this and resolve conflicts in my PR - thank you again for contributing!

**Comment by StanislavUshakov** [comment]
Thank you @krwq for the quick review

**Pull request merged**
