### PR TITLE
Don't use FromApp apis in UAP

### PR DESCRIPTION
**Pull request by JeremyKuhne**
@safern will amend this PR with the package changes

cc: @joshfree, @davidwrighton, @botaberg, @zamont, @nattress, @danmosemsft

### CODE REVIEW

**Comment by safern** [comment]
> @safern will amend this PR with the package changes

Done.

**Comment by danmosemsft** [comment]
Hold on merging the rollbacks while until I get confirmation from release owners.

**Comment by JeremyKuhne** [comment]
This change will need the updated CoreCLR to work for UAP.  See https://github.com/dotnet/coreclr/pull/13595.

**Comment by joshfree** [comment]
We have confirmation.  Please merge once CI passes.

**Comment by JeremyKuhne** [comment]
@dotnet-bot test this please

**Pull request merged**
