### PR TITLE
Include the ArchGroup in innerloop CI jobs on Jenkins.

### PR DESCRIPTION
**Pull request by mellinoe**
This will help distinguish which architecture each CI job is configured to build for.

### CODE REVIEW

**Comment by mellinoe** [comment]
@dotnet-bot Test CI please

**Comment by mellinoe** [comment]
Example names:

Innerloop Windows_NT Debug (x86) Build and Test
Innerloop Windows_NT Release (x64) Build and Test
Innerloop Ubuntu14.04 Debug (x64) Build and Test
Innerloop Ubuntu14.04 Release (x64) Build and Test
Innerloop RHEL7.2 Debug (x64) Build and Test

Thoughts / Questions:

* Take out the parentheses? Looks like some other jobs already list the architecture group, and don't have it in parentheses.
* Do this for outer loop jobs, too?

@stephentoub @danmosemsft

**Comment by mellinoe** [comment]
Fixes https://github.com/dotnet/corefx/issues/16850

**Comment by danmosemsft** [comment]
Can you please also update the badges in README.md to show the bitness? That may mean extra columns, or annotations, whichever is easier/less confusing.

**Comment by danmosemsft** [comment]
Incidentally does it make sense to rename ` Windows_NT` to `Windows Server 2012 R2` or whatever it is?

**Comment by danmosemsft** [comment]
Yes, for outer loop jobs too please. thanks for doing this.

**Comment by mellinoe** [comment]
> Incidentally does it make sense to rename Windows_NT to Windows Server 2012 R2 or whatever it is?

Yeah, I think so. That is always confusing.

**Comment by stephentoub** [comment]
Thanks, @mellinoe

**Comment by mellinoe** [comment]
It turns out that the `Windows_NT` nomenclature goes down a bit further than this script (into the CI image labels, etc.). I could add a mapping for it to make the CI job names prettier, but we probably just want to rename it everywhere it's used to avoid confusion.

I made the other changes, though.

**Comment by mellinoe** [comment]
@dotnet-bot Test CI please

**Comment by danmosemsft** [comment]
@mellinoe were you going to edit README.md as well? The columns on the homepage all say 64 bit.
Either adding a 32 bit column with selected badges in or annotating the entries somehow.

**Pull request merged**
