### PR TITLE
Update build tools to latest version.

### PR DESCRIPTION
**Pull request by jhendrixMSFT**

### CODE REVIEW

**Comment by ericstj** [comment]
This overlaps with https://github.com/dotnet/corefx/pull/6974 but is fine to submit seperately.

**Comment by ericstj** [comment]
LGTM

**Comment by jhendrixMSFT** [comment]
@dotnet-bot test this please

**Comment by stephentoub** [comment]
Test Innerloop CentOS7.1 Release Build and Test please

**Pull request merged**
