### PR TITLE
Add Issue Guide link to ReadMe.md

### PR DESCRIPTION
**Pull request by weshaggard**
This tweaks our guide section a little and adds a link to our newly created issue guide.

### CODE REVIEW

**Comment by ellismg** [comment]
LGTM.  Do you think it makes sense to have the link for "feature approved" items (larger work items which are still up for grabs) in the readme or the issues wiki?

**Comment by weshaggard** [comment]
@ellismg I did this PR from the github UI so I don't know how to actually make more commits (without pulling down into my local repo) but after I merge this I will add a comment about feature approved as well.

**Comment by akoeplinger** [comment]
@weshaggard FYI, you just need to click "edit" again on the file in your fork (in the `patch-1` branch that gets automatically created).

**Comment by weshaggard** [comment]
@alexperovich thanks I will give that a try next time.

**Pull request merged**
