### PR TITLE
Disable multiple connect attempts per socket on Linux.

### LINKED ISSUE #5754: Linux workaround for multiple connect attempts per socket does not work
On Linux, we attempt to re-use a socket for multiple connection attempts by "connecting" the socket to an invalid address between each "real" connect attempt.  See [PrimeForNextConnectAttempt](https://github.com/dotnet/corefx/blob/ac67ffac987d0c27236c4a6cf1255c2bcbc7fe7d/src/System.Net.Sockets/src/System/Net/Sockets/SocketPal.Unix.cs#L525).  This does not work as intended.  In the current implementation, the raw call to `connect()` cases any pending call to `epoll_wait()` to wake up and mark the socket as connected; any subsequent connect attempt on a non-blocking socket (or an Async connect attempt) then appears to succeed immediately, whether it did in fact or not.

This is causing some tests (e.g., `System.Net.Sockets.Tests.DualMode.ConnectV4V6IPAddressListToV6Host_Success`) to appear to succeed, even though the connection is never successfully established.  Once #5472 is merged, this test will hang, as the non-blocking connect will now be blocking, and this bug will no longer mask the underlying issue.  

I tried fixing this in the blocking case, by adding a call to `PrimeForNextConnectAttempt` after a blocking `connect` fails, and discovered that this also does not work.  The subsequent connect attempt simply blocks until it times out.

If I disable this feature entirely, forcing Socket methods that connect to address lists to use multiple sockets instead, then the test passes.

### PR DESCRIPTION
**Pull request by ericeil**
The Linux implementation of multiple connect attempts per socket does not work correctly, per #5754.  This change disables multiple connect attempts on all Unix platforms (since Linux was the only one that claimed to support it).

Fixes #5754

@pgavlin , @stephentoub

### CODE REVIEW

**Comment by ericeil** [comment]
This should unblock #5472 also.

**Comment by stephentoub** [comment]
@dotnet-bot test this please

**Comment by stephentoub** [comment]
@ericeil, I think you might need to do this in two stages: first remove usage of the native method from the managed code, and then once we have a System.Net.Sockets package that contains the fix, subsequently remove the now dead code from the native shim.

**Comment by stephentoub** [comment]
LGTM

**Comment by pgavlin** [comment]
LGTM as well.

**Pull request merged**
