### PR TITLE
Branchify the corefx repo

### PR DESCRIPTION
**Pull request by mmitche**

### CODE REVIEW

**Comment by mmitche** [comment]
@dotnet-bot test ci please

**Comment by mmitche** [comment]
@dotnet-bot test ci please

**Comment by mmitche** [comment]
@dotnet-bot test ci please

**Comment by mmitche** [comment]
@dotnet-bot test ci please

**Comment by mmitche** [comment]
@dotnet-bot test ci please

**Comment by mmitche** [comment]
@dotnet-bot test ci please

**Comment by mmitche** [comment]
@dotnet-bot test ci please

**Comment by ellismg** [comment]
Looks good to me assuming the generated jobs looks reasonable to you.

**Comment by ellismg** [comment]
Big thanks for getting this turned around so quickly!

**Comment by mmitche** [comment]
@dotnet-bot test ci please

**Pull request merged**
