### PR TITLE
[release/3.1] Revert changes to EncoderNLS/DecoderNLS.Convert unit tests

### PR DESCRIPTION
**Pull request by GrabYourPitchforks**
These are the unit test changes to accompany https://github.com/dotnet/coreclr/pull/27996, which was committed to the __release/3.1__ branch in the _coreclr_ repo.

This _corefx_ PR isn't a functional product change. It's just updating the unit tests to reflect the incoming _coreclr_ changes. Once a nightly _coreclr_ build is created and it works its way into this repo, this PR will resolve the resulting unit test failures and will unblock future work in this repo.

### CODE REVIEW

**Review by danmoseley — APPROVED** [review]

**Review by tarekgh — APPROVED** [review]

**Comment by jamshedd** [comment]
Approved for Feb.

**Comment by ericstj** [comment]
If https://github.com/dotnet/corefx/pull/42832 merges, this can be closed.

**Comment by GrabYourPitchforks** [comment]
Thanks for taking care of it @ericstj. :)

**Comment by GrabYourPitchforks** [comment]
Went in as https://github.com/dotnet/corefx/commit/d658fef8c064c2f3ea4f57ab6544abb998ab3b57.

**Pull request closed without merging**
