### PR TITLE
Change the semantics of Span ToString to return the contents for T=char

### PR DESCRIPTION
**Pull request by ahsonkhan**
Fixes https://github.com/dotnet/corefx/issues/26584

Related PR: https://github.com/dotnet/coreclr/pull/16143

This PR supersedes https://github.com/dotnet/corefx/pull/26663

It is blocked:
After https://github.com/dotnet/coreclr/pull/16087 is merged and CoreFX is updated to use the new coreclr version, this PR can be merged.

cc @pakrym, @jkotas, @stephentoub, @dotnet/corefxlab-contrib

### CODE REVIEW

**Comment by ahsonkhan** [comment]
I don't understand why I am seeing these compiler errors for netfx when I do:
```C#
Assert.Equal("System.Span<int>[3]", span.ToString());
```
```text
Span\ToString.cs(17,49): error CS0029: Cannot implicitly convert type 'System.Span<int>' to 'System.ValueType'
```

Where is the implicit conversion happening?

**Comment by jkotas** [comment]
> Where is the implicit conversion happening?

There is implicit conversion because of System.Memory reference assembly is missing the ToString overload.

**Comment by ahsonkhan** [comment]
> There is implicit conversion because of System.Memory reference assembly is missing the ToString overload.

Yes! For both Span and Memory.

Also, ReadOnlyMemory in S.Runtime ref is also missing it: https://github.com/dotnet/corefx/blob/master/src/System.Runtime/ref/System.Runtime.cs#L1933

**Comment by pakrym** [comment]
Visual Studio treats strings and ToString differently when returning non printable characters - it escapes them in strings but not ToString results, for example:

image

Does the same thing happen to spans in your change?

**Comment by ahsonkhan** [comment]
> Does the same thing happen to spans in your change?

**Comment by khellang** [comment]
You can force the debugger to show the raw output, using `[DebuggerDisplay]`:

```csharp
[DebuggerDisplay("{ToString(),raw}")]
public class c
{
    public override string ToString()
    {
        return "\r\b\0";
    }
}
```

Ouput: 

image

**Comment by ahsonkhan** [comment]
> You can force the debugger to show the raw output

I will make this change outside this PR (along with removing the redundant DebuggerDisplay property - https://github.com/dotnet/corefx/blob/4f36d83d003e61b42f693eefd521a67fbe0cef59/src/System.Memory/src/System/Span.Portable.cs#L110).

**Comment by ahsonkhan** [comment]
@dotnet-bot test this please

**Comment by ahsonkhan** [comment]
@dotnet-bot test UWP CoreCLR x64 Debug Build

**Comment by jkotas** [comment]
UWP failure is https://github.com/dotnet/corefx/issues/26802  (CI have not picked up the new pipeline definition for existing PRs)

**Pull request merged**
