### PR TITLE
Update BuildTools version to 1.0.26-prerelease-00516-05

### PR DESCRIPTION
**Pull request by karajas**

### CODE REVIEW

**Comment by karajas** [comment]
@dotnet-bot test Innerloop CentOS7.1 Debug Build and Test

**Comment by karajas** [comment]
@dotnet-bot test Innerloop Ubuntu14.04 Debug Build and Test

**Comment by dsgouda** [comment]
@dotnet-bot Test Innerloop CentOS7.1 Debug Build and Test  please

**Comment by karajas** [comment]
@dotnet-bot test Innerloop CentOS7.1 Debug Build and Test

**Pull request merged**
