### PR TITLE
Change arm64 build to use public VS tools instead of private toolset

### PR DESCRIPTION
**Pull request by BruceForstall**

### CODE REVIEW

**Comment by BruceForstall** [comment]
@dotnet-bot help

**Comment by BruceForstall** [comment]
Related: https://github.com/dotnet/coreclr/pull/18817

**Comment by BruceForstall** [comment]
@RussKeldorph @jashook @weshaggard Looks like corefx CI doesn't do Windows arm32 or Windows arm64 builds or tests? And in fact, they aren't even triggerable?

**Comment by RussKeldorph** [comment]
That is my understanding.

**Comment by weshaggard** [comment]
>@RussKeldorph @jashook @weshaggard Looks like corefx CI doesn't do Windows arm32 or Windows arm64 builds or tests? And in fact, they aren't even triggerable?

I think that is correct as well. Please ensure to also verify the official builds with your changes to ensure the necessary VS toolset is on the machines.

**Comment by BruceForstall** [comment]
Related change in coreclr: https://github.com/dotnet/coreclr/pull/19115

**Comment by BruceForstall** [comment]
@weshaggard @RussKeldorph This is ready to review

**Comment by BruceForstall** [comment]
I'm going to merge this to unblock our corefx-testing-in-coreclr. Please feel free to review and I'll adjust later if necessary.

**Pull request merged**
