### PR TITLE
Rename the local variable queue to stack.

### PR DESCRIPTION
**Pull request by kseo**
It is an instance of ImmutableStack.

### CODE REVIEW

**Comment by stephentoub** [comment]
@dotnet-bot test this please (networking failure)

**Comment by stephentoub** [comment]
LGTM

**Comment by stephentoub** [comment]
@dotnet-bot test this please

**Comment by stephentoub** [comment]
@dotnet-bot test this please

**Comment by stephentoub** [comment]
@dotnet-bot test this please (#3532)

**Comment by JonHanna** [comment]
@dotnet-bot  test this please.

**Pull request merged**
