### PR TITLE
Consolidate Graphics across Windows & Unix

### PR DESCRIPTION
**Pull request by qmfrederik**
A lot of the methods in `Graphics` are thin wrappers around GDI+.

This PR attempts to consolidate a lot of the code shared between `Graphics.Windows.cs` and `Graphics.Unix.cs` into `Graphics.cs`

### CODE REVIEW

**Comment by safern** [comment]
Thanks @qmfrederik for the clean-up, given the size of the PR and the risk that it involves, I think we should hold this up post 3.0. So I will mark as NO MERGE and we can try getting it in later on July.

**Comment by qmfrederik** [comment]
@safern Sure. Does that mean this would still make it for 3.1?

Just some notes regarding risk:
* I always copied from `Graphics.Windows.cs` to `Graphics.cs`. Even if there were some subtle differences while I thought the Unix and Windows implementation were equal, this would impact Unix only.
* Again, at least on Windows, there's ample test coverage of these methods.

But it's still a large diff, nonetheless.

There's still room for improvement. I'll probably expand this PR further when I find the time. A good indication of the work remaining is `GdiPlusNative`. Almost all code there should eventually be shared across Windows & Unix, as libgdiplus attempts to be API compatible with GDI+.

**Comment by qmfrederik** [comment]
Closing in favor of #39945

**Pull request closed without merging**
