### PR TITLE
Port to RC2: Windows 7 Globalization Test Fixes.

### PR DESCRIPTION
**Pull request by ellismg**
#7139

### CODE REVIEW

**Comment by stephentoub** [comment]
Test Innerloop OSX Debug Build and Test please
Test Innerloop OSX Release Build and Test please

**Comment by stephentoub** [comment]
@dotnet-bot test this please

**Comment by ellismg** [comment]
@dotnet-bot test Innerloop CentOS7.1 Release Build and Test please

**Comment by ellismg** [comment]
@dotnet-bot test Innerloop Windows_NT Release Build and Test please

**Pull request merged**
