### PR TITLE
Update buildtools version

### PR DESCRIPTION
**Pull request by mmitche**
Update buildtools to get newer versions of code coverage report tooling

### CODE REVIEW

**Comment by stephentoub** [comment]
#1237 is trying to change the build tools version to 19, whereas this is changing it to 21.  I'm assuming this one is correct and the other PR should be closed?  Otherwise LGTM.

**Comment by weshaggard** [comment]
Lets merge #1237 so we don't throw off the mirroring and then you can update to 21 @mmitche.

**Comment by weshaggard** [comment]
I just merged that so you will need to update the PR to deal with the conflict and then resubmit.

**Comment by mmitche** [comment]
Thanks. @weshaggard still 21?

**Pull request merged**
