### PR TITLE
reenable operation cache

### PR DESCRIPTION
**Pull request by geoffkizer**
Trying to reproduce the issue @stephentoub saw with the operation cache.

### CODE REVIEW

**Comment by geoffkizer** [comment]
@dotnet-bot test Outerloop Linux x64 Debug Build please

**Comment by geoffkizer** [comment]
Issue is #25439

**Comment by geoffkizer** [comment]
Linux outerloop has been running for almost 7 hours. 

@dotnet/dnceng, what's going on here?

**Comment by ravimeda** [comment]
Fedora 26 queue hasn't been processing any jobs. Please refer to https://github.com/dotnet/core-eng/issues/2317

**Comment by ravimeda** [comment]
@dotnet-bot test Outerloop Linux x64 Debug Build please

**Comment by geoffkizer** [comment]
@stephentoub Didn't see any failures here... can you take a look at the change and make sure I haven't done anything stupid?

**Comment by geoffkizer** [comment]
There are very few intervening changes in the code here.  The only interesting one looks like https://github.com/dotnet/corefx/commit/40cbd5636851093309b841db4d53af369b7ef1c6#diff-964d3fe5959fe50f58eeb00103f7781b, but even so I don't know how this would change the behavior here.

Maybe an underlying bug in the Memory stuff got fixed?

**Comment by geoffkizer** [comment]
Or possibly this change?
 https://github.com/dotnet/corefx/commit/79d708b2faf8a75089b1873fbb101b0a957c1fbd#diff-d9d70ff883ac3da965dd43638f6be9f5

**Comment by stephentoub** [comment]
@geoffkizer, I don't know what changed, but I'm no longer able to repro either.  Let's go ahead with it.

**Comment by geoffkizer** [comment]
Sounds good to me.  I pushed a new commit with comments cleaned up.

**Pull request merged**
