### PR TITLE
Update the Index and Range interfaces and tests

### PR DESCRIPTION
**Pull request by tarekgh**

### CODE REVIEW

**Comment by tarekgh** [comment]
This depends on https://github.com/dotnet/coreclr/pull/24036

**Comment by tarekgh** [comment]
CC @stephentoub @agocke @terrajobst @GrabYourPitchforks @joshfree @jkotas

**Comment by GrabYourPitchforks** [comment]
`Utf8String` changes LGTM. Thanks!

**Comment by terrajobst** [comment]
Why is this marked NO MERGE? PResumably because we want to wait for https://github.com/dotnet/coreclr/pull/24036 but this is just excluding APIs, so why would it matter?

**Comment by tarekgh** [comment]
> Why is this marked NO MERGE? PResumably because we want to wait for dotnet/coreclr#24036 but this is just excluding APIs, so why would it matter?

I am expecting the api compat checks will fail before getting the updated bits from coreclr. I am not expecting a compilation/runtime failure though. let's wait for the CI to see if this is the case or we can just merge it if it comes green.

**Comment by tarekgh** [comment]
@terrajobst I confirmed the api compat failed because we have added the Slice method to Utf8String. I can fix that in this PR but this will cause it to break again when getting the updated coreclr bits.

**Comment by tarekgh** [comment]
linking to the compiler fix https://github.com/dotnet/roslyn/pull/35004

**Comment by terrajobst** [comment]
> let's wait for the CI to see if this is the case or we can just merge it if it comes green.

Makes sense. I'll wait untilt he CoreFX change is in so that I can update .NET Standard accordingly.

**Comment by tarekgh** [comment]
Closing this one as the commits included here are picked up in the PR https://github.com/dotnet/corefx/pull/36976

**Pull request closed without merging**
