### PR TITLE
Update build tools

### PR DESCRIPTION
**Pull request by ericstj**
Update to the latest buildtools and deal with compiler breaking changes.

This is splitting out the buildtools update portion from https://github.com/dotnet/corefx/pull/23513.

### CODE REVIEW

**Comment by weshaggard** [comment]
FYI @joperezr who is also looking at a compiler update.

@joperezr it would be good to understand why in some cases we are already using the new compiler just but updating the msbuild we are using. Something seems to be off as I wouldn't have expected that to cause us to use a different compiler.

**Comment by ericstj** [comment]
We're using a new compiler because of this: https://github.com/dotnet/buildtools/commit/f99e5ef88ac3e6b909676619a309147283f7c241#diff-4e041e6755f6b11ef1de3599b2a087eeR21

That was merged at the same time as the msbuild update.

**Comment by weshaggard** [comment]
I think that is only a partial compiler update then. See https://github.com/dotnet/buildtools/commit/a3c610cfb102bb28e3e7cc6ebef3591ae4c9e89e where we needed to update some other locations as well in the past.

**Comment by ericstj** [comment]
I'll go and fix the compiler update separately.

**Pull request merged**
