### PR TITLE
[release/3.1] Remove the use of dotnet-core

### PR DESCRIPTION
**Pull request by mmitche**

### CODE REVIEW

**Review by Anipik — APPROVED** [review]

**Comment by adamsitnik** [comment]
FWIW I can repro locally the issue reported by the CI:

```log
D:\projects\corefx\src\System.Windows.Extensions\tests\System.Windows.Extensions.Tests.csproj : error NU1101: Unable to find package System.Windows.Extensions.TestData. No packages exist with this id in source(s): dotnet-eng, dotnet-public, dotnet-tools, dotnet3, dotnet3.1, dotnet3.1-transport [D:\projects\corefx\src\tests.proj]
```

(I am trying to backport https://github.com/dotnet/runtime/pull/57479 to 3.1 and can't build corefx)

**Comment by adamsitnik** [comment]
The error no longer occurs, I can build the repo using the changes from this PR

**Comment by safern** [comment]
@mmitche what's the status of this, should we merge?

**Comment by mmitche** [comment]
> @mmitche what's the status of this, should we merge?

It would be good to, but there needs to be investigation of the error. I assume it would break the official build.

**Comment by carlossanlop** [comment]
@mmitche friendly ping in case you think we should take this change for the next servicing release. Deadline is Monday 03/14 (I'm assuming the same deadline applies to infra changes).

**Comment by mmitche** [comment]
@carlossanlop Yeah we should take this for this servicing release.

**Pull request closed without merging**
