### PR TITLE
Recombine files ProcessTests.cs and ProcessTests.netcoreapp.cs

### LINKED ISSUE #41821: Consolidate files which were split by tfms which aren't supported anymore
In example `ProcessTests.netcoreapp.cs` should be consolidated with `ProcessTests.cs`. As we just removed UWP we have multiple places to clean-up.

cc @stephentoub

### PR DESCRIPTION
**Pull request by Marusyk**
Contributes #41821

Should I consolidate other netcoreapp.cs files?

Please review
Thank you in advance

### CODE REVIEW

**Comment by safern** [comment]
Thanks @Marusyk, yes it would be really nice if we could consolidate all .netcoreapp.cs files where it's project is no longer cross-compiled and it's only tfm in `Configurations.props` is `netcoreapp`.

**Comment by safern** [comment]
@Marusyk I changed the "Fixes" to contributes as this at the current state doesn't fixes the issue completely as we should consolidate all files in the repo as I described in my earlier comment. If it is OK with you, let's merge this PR as is, as it looks good and then we can contribute to that issue on other PRs or just fix it in one PR... I don't know if you're already working on fixing them all at once.

**Review by stephentoub — APPROVED** [review]
Thanks!

**Comment by Marusyk** [comment]
Thank you,

yes, I'm working on other tests. I'll prepare a new PR for all them

**Pull request merged**
