### PR TITLE
Switch to pulling the targets from build tools common target

### PR DESCRIPTION
**Pull request by weshaggard**
This moves most of the targets out of the corefx repo targets and into the build tools targets. We want to minimize the amount of bootstrapping code/targets that are needed in an individual repo to consume build tools so it becomes easy for other repo's to start using and pick-up changes to our common build tools.

### CODE REVIEW

**Comment by weshaggard** [comment]
@mmitche What is the easiest way to test a code coverage run with this PR? I've done a local build but I'm not sure how to trigger a CI build for it.

**Comment by weshaggard** [comment]
Actually my local coverage builds are failing I'm going to investigate this further. If I need to make more updates I will also pull in changes from PR https://github.com/dotnet/corefx/pull/1116 @mmitche

**Comment by stephentoub** [comment]
> What is the easiest way to test a code coverage run with this PR?

The way I've done it in the past is to add a commit that changes the condition for code coverage to not need Coverage=true. Then once it's done I remove that commit. I don't think we currently have a better way, but Matt can say for sure.

**Comment by mmitche** [comment]
@stephentoub Private jobs coming soon :-D

**Comment by stephentoub** [comment]
@mmitche, excellent! :smile:

**Pull request merged**
