### PR TITLE
ObservableCollection: Avoid SimpleMonitor allocation

### PR DESCRIPTION
**Pull request by justinvp**
I was a little sad to see the optimization from #12705 reverted in 6393248c7a986476f1e2d9dc4b1e5aff96459690 for serialization compat.

This PR adds back the optimization, but in terms of `SimpleMonitor`, maintaining serialization compat with desktop.

~~I didn't included the `[TypeForwardedFrom]` attributes in this PR as they're being added in #20599~~ (Edit: added a commit that includes them). However, if I do temporarily add the attribute to a private copy of `ObservableCollection<T>` (and its private `SimpleMonitor`) in a one-off console project, the collection serializes to the exact same bytes as desktop.

cc: @stephentoub, @ViktorHofer

### CODE REVIEW

**Comment by stephentoub** [comment]
> I was a little sad to see the optimization from #12705 reverted in 6393248 for serialization compat.

Yes, sorry, necessary evil :frowning:

**Comment by ViktorHofer** [comment]
I'm very sorry that we had to revert your change! Thanks for improving the codebase again 👍

**Comment by justinvp** [comment]
@dotnet-bot test Innerloop OSX10.12 Release x64 Build and Test please (Cannot delete workspace: remote file operation failed)

**Comment by justinvp** [comment]
@dotnet-bot test Innerloop OSX10.12 Release x64 Build and Test please (Cannot delete workspace: remote file operation failed)

**Comment by ViktorHofer** [comment]
LGTM.

**Pull request merged**
