### PR TITLE
[release/3.1] Fix cast in CacheMemoryMonitor (#41776)

### PR DESCRIPTION
**Pull request by omajid**
Avoid overflow.

cc @stephentoub

### CODE REVIEW

**Comment by stephentoub** [comment]
Who is this impacting that it needs to be serviced?

**Comment by omajid** [comment]
@stephentoub No customer impact that I know of. It was flagged by one of our security folks suggesting that preventing the overflow and hardening this code is a good idea for the sake of security.

**Comment by stephentoub** [comment]
Please email me with more details about the security concern.

**Comment by omajid** [comment]
I am closing this PR. Sorry about the noise.

**Pull request closed without merging**
