### PR TITLE
Add rel-notes and project URL to nupkgs

### LINKED ISSUE #8758: link to the release notes github tag from the nuspec files
New bug copied from conversation @ https://github.com/dotnet/corefx/issues/1706

from @akoeplinger --

> The only other suggestion I'd have is adding the link to the releaseNotes tag into the nuspec for the packages as well, so they show up on nuget.org.

### PR DESCRIPTION
**Pull request by ericstj**
This is a 1.0.0-RTM specific link for relnotes.

/cc @joshfree @leecow @weshaggard

Fixes #8758

### CODE REVIEW

**Comment by ericstj** [comment]
@weshaggard is release/1.0.0 missing some ApiCompat infra fixes?  In the ubuntu logs I'm seeing http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/release_1.0.0/job/ubuntu14.04_release_prtest/54/consoleFull.

**Comment by ericstj** [comment]
This is the buildtools PR that caused the break https://github.com/dotnet/buildtools/pull/737

**Comment by ericstj** [comment]
/cc @ellismg 
I believe these errors were previously hidden behind this problem: https://github.com/dotnet/buildtools/pull/750

**Comment by ellismg** [comment]
In master, I had to disable ApiCompat on Unix because of these issues.  #8899 tracks fixing this, you should just update dir.props to disable running ApiCompat on Unix in release/1.0.0

**Comment by joshfree** [comment]
OS X failure tracked with https://github.com/dotnet/corefx/issues/9017
/cc @ericeil

**Comment by joshfree** [comment]
@dotnet-bot test Innerloop OSX Debug Build and Test please

**Comment by joshfree** [comment]
2nd OS X failure was a CI machine going offline mid build -- https://github.com/dotnet/corefx/issues/9018 @mmitche

**Comment by joshfree** [comment]
@dotnet-bot test Innerloop OSX Debug Build and Test please

**Comment by ericstj** [comment]
@dotnet-bot test Innerloop OSX Debug Build and Test

**Pull request merged**
