### PR TITLE
Enable Tasks.Extensions tests on uap

### PR DESCRIPTION
**Pull request by kouvel**

### CODE REVIEW

**Comment by joperezr** [comment]
Have you tried running the tests in uapaot? Those won't run as part of CI so it would be good to know if they will fail.

**Comment by joperezr** [comment]
Also, do you mind fixing the .csproj's as well? Specifically the configurations section so that building in VS still works correctly.

**Comment by kouvel** [comment]
Sorry forgot to check the csproj files, will fix. As for uapaot, last I tried I wasn't able to run tests successfully on that, I thought the CI would do it, but I'll try to figure it out.

**Comment by kouvel** [comment]
Seeing error in uapaot, need to check

**Comment by joperezr** [comment]
thanks for checking, basically just check if this is a product bug or if the test should even run at all in uapaot, if it should not, then it's fine to just add a `SkipOnTargetFramework` for uap on that test.

**Comment by joperezr** [comment]
also BTW, UAP F5 tests DO run as part of CI, the only ones we don't run yet are the uapaot ones.

**Comment by kouvel** [comment]
Looks like a genuine failure, disabled one test on uapaot

**Pull request merged**
