### PR TITLE
Delete obsolete .builds file

### PR DESCRIPTION
**Pull request by stephentoub**
cc: @sokket

### CODE REVIEW

**Comment by sokket** [comment]
Why is that builds file no longer needed, just out of curiosity? 

LGTM

**Comment by stephentoub** [comment]
> Why is that builds file no longer needed, just out of curiosity?

Because it's about a project that was deleted a month ago.
https://github.com/dotnet/corefx/pull/6840
I'm not sure why this file got checked in after that project was deleted.

Or am I misunderstanding?

**Comment by sokket** [comment]
Ah weird...cool, thanks for finding this :) LGTM

**Comment by stephentoub** [comment]
Ok, thanks.

**Pull request merged**
