### PR TITLE
Only strip initial ? in HttpUtility.ParseQueryString once.

### LINKED ISSUE #23574: HttpUtility.ParseQueryString incorrect if first item's name begins with a question mark
If a query-string's first name-value pair begins with a question mark then the initial question mark is stripped twice, so the name in the parsed collection is incorrect.

E.g. with `??name=value&x=y` the result is a collection where `["name"] == "value"` while if it isn't the first element, as in `?x=y&?name=value` then it has the correct result of `["?name"] == "value"`

### PR DESCRIPTION
**Pull request by JonHanna**
Fixes #23574

### CODE REVIEW

**Comment by JonHanna** [comment]
Test UWP CoreCLR x64 Debug Build

https://ci3.dot.net/job/dotnet_corefx/job/master/job/windows-TGroup_uap+CGroup_Debug+AGroup_x64+TestOuter_false_prtest/2769/console Deleting project workspace...Cannot delete workspace

**Comment by davidsh** [comment]
cc: @karelz @danmosemsft 
These changes will make this more app-compat with NETFX. But are breaking from .NET Core 2.0.  My recommendation is to mark this for servicing backport to .NET Core 2.0.

**Comment by JonHanna** [comment]
Test UWP CoreCLR x64 Debug Build

Failure deleting workspace again.
https://ci3.dot.net/job/dotnet_corefx/job/master/job/windows-TGroup_uap+CGroup_Debug+AGroup_x64+TestOuter_false_prtest/2771/

**Comment by davidsh** [comment]
@dotnet-bot Test UWP CoreCLR x64 Debug Build

**Comment by karelz** [comment]
Closing in favor of #23591 which carries same fix.

**Pull request closed without merging**
