### PR TITLE
Add tests for unbox expressions and remove incorrect assertion

### LINKED ISSUE #3873: Incorrect assertions on compiling unbox expression
`EmitUnboxUnaryExpression(Expression expr)` and `AddressOf(UnaryExpression node, Type type)` (only ever called on an unboxing expression) both assert that the value of the node is not a nullable type.

Unboxing to nullable types is valid, and indeed works in release builds where these assertions aren't tested.

The assertions cause attempts to test this valid use of unboxing to crash.

### PR DESCRIPTION
**Pull request by JonHanna**
Fixes #3873 as the incorrect assertions would cause these tests to fail
incorrectly, and the assertions should only affect such tests.

### CODE REVIEW

**Comment by JonHanna** [comment]
@dotnet-bot test this, please.

**Comment by JonHanna** [comment]
@dotnet-bot test this, please.

**Comment by stephentoub** [comment]
LGTM

cc: @VSadov

**Comment by JonHanna** [comment]
The fix to #3873 was included in #4025, and since that's been merged in, this no longer covers that.

**Comment by VSadov** [comment]
test this please

**Pull request merged**
