### PR TITLE
Fix UriParser static table thread safety

### PR DESCRIPTION
**Pull request by stephentoub**
There are two static Dictionaries in UriParser that are read without holding a lock and modified while holding a lock; while it is safe for any number of readers to be concurrently accessing a dictionary, it is not safe for any positive number of readers to be doing so while there's at least one writer.  Based on how this code is written, my assumption is that at some point is was implemented using Hashtable, which does make such a situation safe.  As such, I'm fixing it by just switching back to using Hashtable; in the process, I'm also removing the static cctor and fixing a few readonly statics to instead be const.

I considered a few alternate implementations, including using an immutable dictionary, but this approach is simple and fast enough, and doesn't incur some of the costs other schemes would.

Fixes https://github.com/dotnet/corefx/issues/29360
cc: @rmkerr, @davidsh, @danmosemsft

### CODE REVIEW

**Comment by davidsh** [comment]
>I considered a few alternate implementations, including using an immutable dictionary, but this approach is simple and fast enough, and doesn't incur some of the costs other schemes would.

Are there any performance considerations here?  Have you checked before/after perf to make sure we don't have any regressions?

**Comment by stephentoub** [comment]
> Have you checked before/after perf to make sure we don't have any regressions?

Yes.  There's a small impact when doing something that purely measures the cost of reading from these tables, e.g. a microbenchmark on `UriParser.IsWellKnown` increases on my machine from ~47ns to ~50ns.  However, that's both small and not an operation that's frequently done on a hot path.  A more common thing to do is use `new Uri(...)`, and there's no measurable impact there, as this is in the noise compared to its cost.

I explored a few alternatives.  The best alternative from a read-access speed perspective is to continue to use `Dictionary<>` but to treat it as immutable, e.g. where any write to the dictionary actually first clones it, mutates the clone, and then publishes that new dictionary back as the instance.  This avoids any such impact on read performance, but at a significant cost any time a new scheme is encountered.  That should be a fairly rare occurrence, and so I strongly considered that route, but in the end decided that this small hit to read perf was close to noise enough that it wasn't worth the complication, or the risk if a workload actually did have lots of new schemes (the worst of which would be one that repeatedly hit a new scheme, so frequently that it caused the implementation to drop its "temp" table, and did that repeatedly).  Another alternative would be to take a dependency on either ConcurrentDictionary or ImmutableDictionary, but both of those similarly add some cost to the read path and increase the cost of the write path with allocations.

**Comment by stephentoub** [comment]
Actually, I take that last comment about `new Uri(...)` back... running the numbers again and I'm getting more measurable results.  Taking another look...

**Comment by stephentoub** [comment]
So there's no impact on `new Uri(...)` when the scheme is one of the 16 that's hard-coded, e.g. http, https, ws, etc (this change actually improves that case by ~5% on my machine, I believe because of the static cctor removal).  However, there's an ~6% regression on my machine for `new Uri(...)` with an unknown scheme, e.g. `abcd://hello.com`, due to the cost of accessing the Hashtable vs the Dictionary (and the cast for the former).

As noted, I could eliminate that small impact for an unknown scheme by instead going with an approach like:
https://github.com/stephentoub/corefx/commit/afc54f778ee616e9ba8ad7bd23fb8d170a80760f
but at very measurable expense when either table needs to be written (which "should" be rare).

Do you have a preference?

**Comment by davidsh** [comment]
>Do you have a preference?

Thanks for double-checking performance.

>So there's no impact on new Uri(...) when the scheme is one of the 16 that's hard-coded, e.g. http, https, ws, etc (this change actually improves that case by ~5% on my machine, I believe because of the static cctor removal). However, there's an ~6% regression on my machine for new Uri(...) with an unknown scheme, e.g. abcd://hello.com, due to the cost of accessing the Hashtable vs the Dictionary (and the cast for the former).

I am fine with this approach since unknown Uri's are very rare.

**Pull request merged**
