### PR TITLE
Removed SNIMarsManager, and modified TdsParserStateObjectManaged so that it manages its own SNIMarsConnection if MARS is enabled. This prevents SNIMarsConnections from accumulating forever in a static SNIMarsManager singleton. (#22709)

### PR DESCRIPTION
**Pull request by corivera**
Porting change to release/2.0.0.

Shiproom approval pending.

### CODE REVIEW

**Comment by danmosemsft** [comment]
Thanks. I'll let @geleems review this one. It will need a shiproom mail today.

**Comment by danmosemsft** [comment]
@joperezr since @geleems is out could you help @corivera with a CR on this one so we can get it to shiproom today?

**Comment by weshaggard** [comment]
>@weshaggard is the 2.0 build brken:

I've seen this in the auto-pr recently I think the Tizen builds maybe broken. I ping some of the Tizen folks to have a look but I'm not sure they have yet. I wouldn't block on the Tizen legs for release/2.0.0 branch.

**Comment by danmosemsft** [comment]
OK @corivera you can ignore the tizen legs. Just need CR

**Comment by weshaggard** [comment]
You need to version the package and add it to the list which we build otherwise this will not be shipped.

**Pull request merged**
