### PR TITLE
Include all service types while querying using ServiceController.

### LINKED ISSUE #8090: System.ServiceProcess.ServiceController Throws InvalidOperationException for Valid Service
There is a behavioral difference in the ServiceController constructor when handling a kernel mode driver between .Net 4.5 and CoreCLR. The ServiceController works as expected in .Net 4.5, but fails to properly construct a ServiceController object in CoreCLR; throwing an InvalidOperationException during subsequent use.

I verified that the process is present and running on the system:

sc.exe query tcpip

SERVICE_NAME: tcpip
        TYPE               : 1  KERNEL_DRIVER
        STATE              : 4  RUNNING
                                (STOPPABLE, NOT_PAUSABLE, IGNORES_SHUTDOWN)
        WIN32_EXIT_CODE    : 0  (0x0)
        SERVICE_EXIT_CODE  : 0  (0x0)
        CHECKPOINT         : 0x0
        WAIT_HINT          : 0x0

The following code triggers the exception. In this case, nameOfService == "tcpip" and computerName == ".". The exception is thrown when executing "sc.Status."

`            try
            {
                ServiceController sc = new ServiceController(nameOfService, computerName);
                ServiceControllerStatus tmp = sc.Status; // this will throw if the service doesn't exist

                // no exceptions = this is an existing, valid service = add
                listOfValidServices.Add(sc);
            }
            catch (InvalidOperationException)
            {
            }
            catch (ArgumentException)
            {
            }
`
Exception:
System.InvalidOperationException {"Service TCPIP was not found on computer '.'."}

### PR DESCRIPTION
**Pull request by Priya91**
cc @karelz @mirichmo

fixes #8090

### CODE REVIEW

**Comment by stephentoub** [comment]
LGTM.  Is there a test we can / should add for this?

**Comment by Priya91** [comment]
>  Is there a test we can / should add for this?

hmm maybe, in the native test service, we can create a service of type kernel? Will experiment.

**Comment by Priya91** [comment]
@stephentoub Added test by reusing other managed apis to exercise the changed codepath.

**Comment by stephentoub** [comment]
Thanks, Priya. LGTM.

**Pull request merged**
