### PR TITLE
Add (disabled) test for dropping Http2ReadStream

### PR DESCRIPTION
**Pull request by stephentoub**
The test may need tweaking as we enable the functionality.
https://github.com/dotnet/corefx/issues/39420

### CODE REVIEW

**Comment by geoffkizer** [comment]
This test is great, but... couldn't it be non-HTTP2 specific?

**Comment by stephentoub** [comment]
> couldn't it be non-HTTP2 specific?

We want to validate that we receive a RstStream frame. At least I assume we do. How do we do that without being version specific?

**Comment by geoffkizer** [comment]
> We want to validate that we receive a RstStream frame. At least I assume we do. How do we do that without being version specific?

We want to validate that the request is cancelled. In HTTP2, this means receiving a RST_STREAM. In HTTP/1.1, it means closing/resetting the connection. In HTTP3, it will mean something else (resetting the QUIC stream, most likely).

So we need an abstraction in GenericLoopbackServer like WaitForRequestCancelledAsync, that does the appropriate thing for each protocol version.

Something like this would be useful for a bunch of other scenarios as well... early dispose on the response body, request cancellation, exception during request body send, etc... I know @wfurt is looking at generalizing the cancellation tests, so perhaps he's got something here already.

**Comment by stephentoub** [comment]
@geoffkizer, makes sense.  In doing so I found https://github.com/dotnet/corefx/issues/39466.

**Comment by stephentoub** [comment]
Replaced by https://github.com/dotnet/corefx/pull/39471

**Pull request closed without merging**
