### PR TITLE
enable MaxConnectionsPerServer_WaitingConnectionsAreCancelable test again

### LINKED ISSUE #32000: System.Net.Http.Functional.Tests timing out
https://mc.dot.net/#/user/filipnavara/pr~2Fjenkins~2Fdotnet~2Fcorefx~2Fmaster~2F/test~2Ffunctional~2Fcli~2F/68ed63990b09ad9ceea911374da90acb1b042a89/workItem/System.Net.Http.Functional.Tests/wilogs currently show timeouts being hit on

* RedHat.74.Amd64.Open-x64:Release
* Centos.74.Amd64.Open-x64:Release

The failed runs all indicate that the xunit process made progress, then stopped printing to the console, and 20 minutes later the executor terminated the process.  The logs show the automated reruns happened on different machines, and reproduced.

Snippets from one of the runs console.log:
```
2018-08-28 09:37:46,047: INFO: proc(54): run_and_log_output: Output: xUnit.net Console Runner v2.4.1-pre.build.4059 (64-bit .NET Core 4.6.26827.04)
2018-08-28 09:37:46,142: INFO: proc(54): run_and_log_output: Output: [37m  Discovering: System.Net.Http.Functional.Tests
2018-08-28 09:37:46,402: INFO: proc(54): run_and_log_output: Output: [m[37m  Discovered:  System.Net.Http.Functional.Tests
2018-08-28 09:37:46,403: INFO: proc(54): run_and_log_output: Output: [m[37m  Starting:    System.Net.Http.Functional.Tests
2018-08-28 09:37:47,133: INFO: proc(54): run_and_log_output: Output: [m[33;1m    System.Net.Http.Functional.Tests.SocketsHttpHandler_HttpClient_SelectedSites_Test.RetrieveSite_Succeeds [SKIP]
2018-08-28 09:37:47,133: INFO: proc(54): run_and_log_output: Output: [m[37m      Condition(s) not met: "IsSelectedSitesTestEnabled"
2018-08-28 09:37:47,133: INFO: proc(54): run_and_log_output: Output: [m[33;1m    System.Net.Http.Functional.Tests.SocketsHttpHandler_HttpClient_SelectedSites_Test.RetrieveSite_Debug_Helper [SKIP]
2018-08-28 09:37:47,134: INFO: proc(54): run_and_log_output: Output: [m[37m      Condition(s) not met: "IsSelectedSitesTestEnabled"
2018-08-28 09:37:47,134: INFO: proc(54): run_and_log_output: Output: [m[33;1m    System.Net.Http.Functional.Tests.PlatformHandler_HttpClient_SelectedSites_Test.RetrieveSite_Succeeds [SKIP]
2018-08-28 09:37:47,134: INFO: proc(54): run_and_log_output: Output: [m[37m      Condition(s) not met: "IsSelectedSitesTestEnabled"
2018-08-28 09:37:47,134: INFO: proc(54): run_and_log_output: Output: [m[33;1m    System.Net.Http.Functional.Tests.PlatformHandler_HttpClient_SelectedSites_Test.RetrieveSite_Debug_Helper [SKIP]
2018-08-28 09:37:47,134: INFO: proc(54): run_and_log_output: Output: [m[37m      Condition(s) not met: "IsSelectedSitesTestEnabled"
2018-08-28 09:37:47,493: INFO: proc(54): run_and_log_output: Output: [m[33;1m    System.Net.Http.Functional.Tests.PlatformHandler_HttpClientMiniStress.MakeAndFaultManyRequests [SKIP]
2018-08-28 09:37:47,493: INFO: proc(54): run_and_log_output: Output: [m[37m      Condition(s) not met: "IsStressModeEnabled"
2018-08-28 09:37:47,494: INFO: proc(54): run_and_log_output: Output: [m[33;1m    System.Net.Http.Functional.Tests.PlatformHandler_HttpClientMiniStress.UnreadResponseMessage_Collectible [SKIP]
2018-08-28 09:37:47,494: INFO: proc(54): run_and_log_output: Output: [m[37m      Condition(s) not met: "IsStressModeEnabled"
2018-08-28 09:37:47,494: INFO: proc(54): run_and_log_output: Output: [m[33;1m    System.Net.Http.Functional.Tests.PlatformHandler_HttpClientMiniStress.SingleClient_ManyGets_Async [SKIP]
2018-08-28 09:37:47,494: INFO: proc(54): run_and_log_output: Output: [m[37m      Condition(s) not met: "IsStressModeEnabled"
2018-08-28 09:37:47,495: INFO: proc(54): run_and_log_output: Output: [m[33;1m    System.Net.Http.Functional.Tests.PlatformHandler_HttpClientMiniStress.CreateAndDestroyManyClients [SKIP]
2018-08-28 09:37:47,495: INFO: proc(54): run_and_log_output: Output: [m[37m      Condition(s) not met: "IsStressModeEnabled"
2018-08-28 09:37:47,495: INFO: proc(54): run_and_log_output: Output: [m[33;1m    System.Net.Http.Functional.Tests.PlatformHandler_HttpClientMiniStress.ManyClients_ManyPosts_Async [SKIP]
2018-08-28 09:37:47,495: INFO: proc(54): run_and_log_output: Output: [m[37m      Condition(s) not met: "IsStressModeEnabled"
2018-08-28 09:37:47,495: INFO: proc(54): run_and_log_output: Output: [m[33;1m    System.Net.Http.Functional.Tests.PlatformHandler_HttpClientMiniStress.ManyClients_ManyGets [SKIP]
2018-08-28 09:37:47,496: INFO: proc(54): run_and_log_output: Output: [m[37m      Condition(s) not met: "IsStressModeEnabled"
2018-08-28 09:37:47,496: INFO: proc(54): run_and_log_output: Output: [m[33;1m    System.Net.Http.Functional.Tests.PlatformHandler_HttpClientMiniStress.SingleClient_ManyGets_Sync [SKIP]
2018-08-28 09:37:47,496: INFO: proc(54): run_and_log_output: Output: [m[37m      Condition(s) not met: "IsStressModeEnabled"
2018-08-28 09:37:48,960: INFO: proc(54): run_and_log_output: Output: [m[33;1m    System.Net.Http.Functional.Tests.SocketsHttpHandler_HttpClientEKUTest.HttpClient_ClientEKUServerAuth_Fails [SKIP]
2018-08-28 09:37:48,960: INFO: proc(54): run_and_log_output: Output: [m[37m      Condition(s) not met: "CanTestCertificates"
2018-08-28 09:37:48,960: INFO: proc(54): run_and_log_output: Output: [m[33;1m    System.Net.Http.Functional.Tests.SocketsHttpHandler_HttpClientEKUTest.HttpClient_NoEKUServerAuth_Ok [SKIP]
2018-08-28 09:37:48,961: INFO: proc(54): run_and_log_output: Output: [m[37m      Condition(s) not met: "CanTestCertificates"
2018-08-28 09:37:48,961: INFO: proc(54): run_and_log_output: Output: [m[33;1m    System.Net.Http.Functional.Tests.SocketsHttpHandler_HttpClientEKUTest.HttpClient_NoEKUClientAuth_Ok [SKIP]
2018-08-28 09:37:48,961: INFO: proc(54): run_and_log_output: Output: [m[37m      Condition(s) not met: "CanTestClientCertificates"
2018-08-28 09:37:48,961: INFO: proc(54): run_and_log_output: Output: [m[33;1m    System.Net.Http.Functional.Tests.SocketsHttpHandler_HttpClientEKUTest.HttpClient_ServerEKUClientAuth_Fails [SKIP]
2018-08-28 09:37:48,961: INFO: proc(54): run_and_log_output: Output: [m[37m      Condition(s) not met: "CanTestClientCertificates"
2018-08-28 09:37:48,962: INFO: proc(54): run_and_log_output: Output: [m[33;1m    System.Net.Http.Functional.Tests.PlatformHandler_HttpClientEKUTest.HttpClient_ServerEKUClientAuth_Fails [SKIP]
2018-08-28 09:37:48,962: INFO: proc(54): run_and_log_output: Output: [m[37m      Condition(s) not met: "CanTestClientCertificates"
2018-08-28 09:37:48,962: INFO: proc(54): run_and_log_output: Output: [m[33;1m    System.Net.Http.Functional.Tests.PlatformHandler_HttpClientEKUTest.HttpClient_NoEKUClientAuth_Ok [SKIP]
2018-08-28 09:37:48,962: INFO: proc(54): run_and_log_output: Output: [m[37m      Condition(s) not met: "CanTestClientCertificates"
2018-08-28 09:37:48,962: INFO: proc(54): run_and_log_output: Output: [m[33;1m    System.Net.Http.Functional.Tests.PlatformHandler_HttpClientEKUTest.HttpClient_NoEKUServerAuth_Ok [SKIP]
2018-08-28 09:37:48,963: INFO: proc(54): run_and_log_output: Output: [m[37m      Condition(s) not met: "CanTestCertificates"
2018-08-28 09:37:48,963: INFO: proc(54): run_and_log_output: Output: [m[33;1m    System.Net.Http.Functional.Tests.PlatformHandler_HttpClientEKUTest.HttpClient_ClientEKUServerAuth_Fails [SKIP]
2018-08-28 09:37:48,963: INFO: proc(54): run_and_log_output: Output: [m[37m      Condition(s) not met: "CanTestCertificates"
2018-08-28 09:37:49,923: INFO: proc(54): run_and_log_output: Output: [m[33;1m    System.Net.Http.Functional.Tests.SocketsHttpHandler_HttpClientMiniStress.MakeAndFaultManyRequests [SKIP]
2018-08-28 09:37:49,924: INFO: proc(54): run_and_log_output: Output: [m[37m      Condition(s) not met: "IsStressModeEnabled"
2018-08-28 09:37:49,924: INFO: proc(54): run_and_log_output: Output: [m[33;1m    System.Net.Http.Functional.Tests.SocketsHttpHandler_HttpClientMiniStress.ManyClients_ManyPosts_Async [SKIP]
2018-08-28 09:37:49,924: INFO: proc(54): run_and_log_output: Output: [m[37m      Condition(s) not met: "IsStressModeEnabled"
2018-08-28 09:37:49,924: INFO: proc(54): run_and_log_output: Output: [m[33;1m    System.Net.Http.Functional.Tests.SocketsHttpHandler_HttpClientMiniStress.SingleClient_ManyGets_Sync [SKIP]
2018-08-28 09:37:49,924: INFO: proc(54): run_and_log_output: Output: [m[37m      Condition(s) not met: "IsStressModeEnabled"
2018-08-28 09:37:49,924: INFO: proc(54): run_and_log_output: Output: [m[33;1m    System.Net.Http.Functional.Tests.SocketsHttpHandler_HttpClientMiniStress.UnreadResponseMessage_Collectible [SKIP]
2018-08-28 09:37:49,925: INFO: proc(54): run_and_log_output: Output: [m[37m      Condition(s) not met: "IsStressModeEnabled"
2018-08-28 09:37:49,925: INFO: proc(54): run_and_log_output: Output: [m[33;1m    System.Net.Http.Functional.Tests.SocketsHttpHandler_HttpClientMiniStress.ManyClients_ManyGets [SKIP]
2018-08-28 09:37:49,925: INFO: proc(54): run_and_log_output: Output: [m[37m      Condition(s) not met: "IsStressModeEnabled"
2018-08-28 09:37:49,925: INFO: proc(54): run_and_log_output: Output: [m[33;1m    System.Net.Http.Functional.Tests.SocketsHttpHandler_HttpClientMiniStress.SingleClient_ManyGets_Async [SKIP]
2018-08-28 09:37:49,926: INFO: proc(54): run_and_log_output: Output: [m[37m      Condition(s) not met: "IsStressModeEnabled"
2018-08-28 09:37:49,926: INFO: proc(54): run_and_log_output: Output: [m[33;1m    System.Net.Http.Functional.Tests.SocketsHttpHandler_HttpClientMiniStress.CreateAndDestroyManyClients [SKIP]
2018-08-28 09:37:49,926: INFO: proc(54): run_and_log_output: Output: [m[37m      Condition(s) not met: "IsStressModeEnabled"
2018-08-28 09:37:53,811: INFO: proc(54): run_and_log_output: Output: [m[33;1m    System.Net.Http.Functional.Tests.SocketsHttpHandler_HttpClientHandlerTest.Ctor_ExpectedDefaultPropertyValues_UapPlatform [SKIP]
2018-08-28 09:37:53,811: INFO: proc(54): run_and_log_output: Output: [m[37m      Condition(s) not met: "IsUap"
2018-08-28 09:37:53,925: INFO: proc(54): run_and_log_output: Output: [m[33;1m    System.Net.Http.Functional.Tests.PlatformHandler_HttpClientHandlerTest.Ctor_ExpectedDefaultPropertyValues_UapPlatform [SKIP]
2018-08-28 09:37:53,925: INFO: proc(54): run_and_log_output: Output: [m[37m      Condition(s) not met: "IsUap"
```

(log terminates)

And run_client.py:

```
2018-08-28 09:37:44,283: INFO: executor(112): run: Successfully downloaded work item payload
2018-08-28 09:37:44,283: INFO: executor(463): _execute_command: running chmod +x $HELIX_WORKITEM_PAYLOAD/*.sh && $HELIX_PYTHONPATH $HELIX_CORRELATION_PAYLOAD/RunnerScripts/scriptrunner/scriptrunner.py --script RunTests.sh $HELIX_CORRELATION_PAYLOAD in /home/helixbot/dotnetbuild/work/a01a5d92-9983-471e-a012-334328feca8f/Work/95b27b09-8f38-4fae-b2a7-a3e5f646d4b6/Exec max 1200 seconds
2018-08-28 09:38:28,804: INFO: servicebusrepository(86): renew_workitem_lock: Entering renew_workitem_lock for https://nethelix.servicebus.windows.net/centos.74.amd64.open/messages/89187500/6b012b36-ef7b-43c3-b6c1-1951676536ab
2018-08-28 09:38:28,914: INFO: saferequests(90): request_with_retry: Response complete with status code '200'

<snip />

2018-08-28 09:57:16,851: INFO: servicebusrepository(86): renew_workitem_lock: Entering renew_workitem_lock for https://nethelix.servicebus.windows.net/centos.74.amd64.open/messages/89187500/6b012b36-ef7b-43c3-b6c1-1951676536ab
2018-08-28 09:57:16,990: INFO: saferequests(90): request_with_retry: Response complete with status code '200'
2018-08-28 09:57:16,990: INFO: servicebusrepository(99): renew_workitem_lock: renew_workitem_lock Status Code: 200
2018-08-28 09:57:44,286: ERROR: job(44): kill: Job running for too long. Killing...
2018-08-28 09:57:44,301: ERROR: executor(474): _execute_command: Executor timed out after 1200 seconds and was killed.
```

### PR DESCRIPTION
**Pull request by wfurt**
fixes #32000

### CODE REVIEW

**Comment by wfurt** [comment]
@dotnet-bot test Outerloop Windows x64 Debug Build
@dotnet-bot test Outerloop Linux x64 Debug Build
@dotnet-bot test Outerloop OSX x64 Debug Build

**Comment by davidsh** [comment]
It would be nice to include in PR's like this why the test is being enabled.  I.e. adding some comments to the commit / PR like "Re-enable test since the problem was infrastructure related". etc.

**Comment by wfurt** [comment]
Original root cause should be fixed by #32297.

**Comment by stephentoub** [comment]
This appears to still be broken:
```
[Long Running Test] 'System.Net.Http.Functional.Tests.PlatformHandler_HttpClientHandler_Cancellation_Test.MaxConnectionsPerServer_WaitingConnectionsAreCancelable', Elapsed: 00:17:56
```

There's also some kind of other failure happening, but it doesn't look related:
```
2018-10-17 01:39:45,496: INFO: proc(55): run_and_log_output: Output: [m[37m      System.AggregateException : One or more errors occurred. (Cannot access a disposed object.
2018-10-17 01:39:45,496: INFO: proc(55): run_and_log_output: Output: [m[37m      Object name: 'listener'.)
2018-10-17 01:39:45,496: INFO: proc(55): run_and_log_output: Output: [m[37m      ---- System.ObjectDisposedException : Cannot access a disposed object.
2018-10-17 01:39:45,496: INFO: proc(55): run_and_log_output: Output: [m[37m      Object name: 'listener'.
2018-10-17 01:39:45,497: INFO: proc(55): run_and_log_output: Output: [m[30;1m      Stack Trace:
2018-10-17 01:39:45,500: INFO: proc(55): run_and_log_output: Output: [m[37m        /root/coreclr/src/System.Private.CoreLib/src/System/Threading/Tasks/Task.cs(2837,0): at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
2018-10-17 01:39:45,501: INFO: proc(55): run_and_log_output: Output: [m[37m        /root/coreclr/src/System.Private.CoreLib/src/System/Threading/Tasks/Task.cs(2708,0): at System.Threading.Tasks.Task.Wait()
2018-10-17 01:39:45,501: INFO: proc(55): run_and_log_output: Output: [m[37m        /mnt/j/workspace/dotnet_corefx/master/linux-TGroup_netcoreapp+CGroup_Debug+AGroup_x64+TestOuter_true_prtest/src/System.Net.Http/tests/FunctionalTests/NtAuthTests.cs(57,0): at System.Net.Http.Functional.Tests.NtAuthServer.Dispose()
2018-10-17 01:39:45,502: INFO: proc(55): run_and_log_output: Output: [m[37m        /mnt/j/workspace/dotnet_corefx/master/linux-TGroup_netcoreapp+CGroup_Debug+AGroup_x64+TestOuter_true_prtest/src/System.Net.Http/tests/FunctionalTests/NtAuthTests.cs(95,0): at System.Net.Http.Functional.Tests.NtAuthServers.Dispose()
2018-10-17 01:39:45,502: INFO: proc(55): run_and_log_output: Output: [m[37m        ----- Inner Stack Trace -----
2018-10-17 01:39:45,502: INFO: proc(55): run_and_log_output: Output: [m[37m        /mnt/j/workspace/dotnet_corefx/master/linux-TGroup_netcoreapp+CGroup_Debug+AGroup_x64+TestOuter_true_prtest/src/System.Net.HttpListener/src/System/Net/Managed/ListenerAsyncResult.Managed.cs(197,0): at System.Net.ListenerAsyncResult.GetContext()
2018-10-17 01:39:45,503: INFO: proc(55): run_and_log_output: Output: [m[37m        /mnt/j/workspace/dotnet_corefx/master/linux-TGroup_netcoreapp+CGroup_Debug+AGroup_x64+TestOuter_true_prtest/src/System.Net.HttpListener/src/System/Net/Managed/HttpListener.Managed.cs(347,0): at System.Net.HttpListener.EndGetContext(IAsyncResult asyncResult)
2018-10-17 01:39:45,505: INFO: proc(55): run_and_log_output: Output: [m[37m        /mnt/j/workspace/dotnet_corefx/master/linux-TGroup_netcoreapp+CGroup_Debug+AGroup_x64+TestOuter_true_prtest/src/System.Net.HttpListener/src/System/Net/HttpListener.cs(290,0): at System.Net.HttpListener.<>c.<GetContextAsync>b__44_1(IAsyncResult iar)
2018-10-17 01:39:45,505: INFO: proc(55): run_and_log_output: Output: [m[37m        /root/coreclr/src/System.Private.CoreLib/src/System/Threading/Tasks/FutureFactory.cs(529,0): at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
2018-10-17 01:39:45,506: INFO: proc(55): run_and_log_output: Output: [m[37m        --- End of stack trace from previous location where exception was thrown ---
2018-10-17 01:39:45,506: INFO: proc(55): run_and_log_output: Output: [m[37m        /mnt/j/workspace/dotnet_corefx/master/linux-TGroup_netcoreapp+CGroup_Debug+AGroup_x64+TestOuter_true_prtest/src/System.Net.Http/tests/FunctionalTests/NtAuthTests.cs(34,0): at System.Net.Http.Functional.Tests.NtAuthServer.<.ctor>b__4_0()
2
```

**Pull request closed without merging**
