### PR TITLE
[WIP] Clean up System.Threading.Tasks tests

### PR DESCRIPTION
**Pull request by Clockwork-Muse**
Removes all instances of `Assert.True(false, ...`, per #516 .
Updates test namespaces, per #2898 .
Removes the internal test framework, per #3133 .

Some tests have been expanded slightly (ie, data-driven tests tend to have a few extra cases), but a full expansion hasn't been performed (ie; `WaitAll`/`WaitAny` _still_ don't have exception/cancellation tests).

This PR currently also extracts a test exception used in PLINQ to common/tests, which should probably be pulled into a separate PR when this one is ready to go.

### CODE REVIEW

**Comment by stephentoub** [comment]
cc: @mellinoe, @AlfredoMS 

Thanks, @Clockwork-Muse.  I'm going to wait to review this until it's no longer "[WIP]" and you're done with whatever changes you plan as part of the PR.

**Comment by Clockwork-Muse** [comment]
@stephentoub - thanks, that's about what I figured.

Some of my recent changes (diff is c0771ed) assume that `TaskCreationOptions.LongRunning` probably isn't necessary for most of our tests, when attempting to test cancellation/waiting behavior for threads.  Is this correct, or is there something more I should be aware of?  It seems to have been added haphazardly, what with being on some of the fastest-running test tasks...

**Comment by stephentoub** [comment]
> It seems to have been added haphazardly, what with being on some of the fastest-running test tasks

It's possible it's haphazard and that some aren't necessary, but it's also likely it was done for a purpose.  LongRunning is implemented to use a dedicate new thread rather than using a thread from the pool, and tests often take advantage of that if they need to ensure that the thing being queued doesn't use a thread from the pool.

**Comment by Clockwork-Muse** [comment]
@stephentoub - yes, I'm aware that's the underlying behavior.  I just wasn't anticipating it making any difference from `Wait`'s perspective.  Which probably means it needs to be added to more cases, then...

**Comment by stephentoub** [comment]
@Clockwork-Muse, is this still a work in progress?  If so, I suggest we close the PR until you're ready to have it reviewed.

**Comment by Clockwork-Muse** [comment]
@stephentoub - yeah, this is taking a bit longer than I initially expected, been busier at work.

**Comment by stephentoub** [comment]
Thanks, @Clockwork-Muse.

**Pull request closed without merging**
