### PR TITLE
Fix race in the StackTraceSymbols.CoreCLR.cs metadata provider cache.

### PR DESCRIPTION
**Pull request by mikem8361**
Issue #19698.

### CODE REVIEW

**Comment by mikem8361** [comment]
@dotnet-bot test please

**Comment by karelz** [comment]
@mikem8361 how is this PR related to issue #19698? (mentioned in top post) - naively it seems irrelevant.
Also, this PR is marked with 2.2 milestone, but master is in 3.0. Do you plan to port it into 2.2?

**Comment by mikem8361** [comment]
I put the wrong issue in the PR. It is https://github.com/dotnet/coreclr/issues/19698. The fix is in master and release/2.2.

**Comment by mikem8361** [comment]
The 2.2 PR https://github.com/dotnet/corefx/pull/32016

**Comment by karelz** [comment]
@mikem8361 thanks for clarification - I updated top post with correct issue and used the form "Fixes #abc" to clarify relationship to the issue. Thanks!

BTW: I also fixed milestone of this PR (it ended up in master = 3.0).

**Pull request merged**
