### PR TITLE
Fix #1339: Change encoding of .cs files to utf-8 without BOM

### LINKED ISSUE #1339: Make encoding of .cs files consistent
Here's a list of the .cs files that aren't ASCII/UTF8 in the repo:

```
$ find . -name *.cs -type f -exec file --mime {} \; | grep -v "charset=us-ascii" | grep -v "charset=utf-8"
./src/Common/tests/SystemXml/XmlCoreTest/TestData.g.cs: text/plain; charset=utf-16le
./src/Common/tests/SystemXml/XmlCoreTest/CustomWriter.cs: text/plain; charset=utf-16le
./src/Common/tests/SystemXml/XmlCoreTest/FilePathUtil.cs: text/plain; charset=utf-16le
./src/Common/tests/SystemXml/XmlCoreTest/AsyncUtil.cs: text/plain; charset=utf-16le
./src/Common/tests/SystemXml/ModuleCore/interop.cs: text/plain; charset=utf-16le
./src/Common/tests/SystemXml/ModuleCore/ctestcase.cs: text/plain; charset=utf-16le
./src/Common/tests/SystemXml/ModuleCore/cmodinfo.cs: text/plain; charset=utf-16le
./src/Common/tests/SystemXml/ModuleCore/ctestbase.cs: text/plain; charset=utf-16le
./src/Common/tests/SystemXml/ModuleCore/ctestexception.cs: text/plain; charset=utf-16le
./src/Common/tests/SystemXml/ModuleCore/cparser.cs: text/plain; charset=utf-16le
./src/Common/tests/SystemXml/ModuleCore/ctestmodule.cs: text/plain; charset=utf-16le
./src/Common/tests/SystemXml/ModuleCore/cltmconsole.cs: text/plain; charset=utf-16le
./src/Common/tests/SystemXml/ModuleCore/cvariation.cs: text/plain; charset=utf-16le
./src/System.Xml.ReaderWriter/tests/Readers/ReaderSettings/TCMaxSettings.cs: text/plain; charset=utf-16le
./src/System.Xml.ReaderWriter/tests/Readers/ReaderSettings/TCCreateOverloads.cs: text/plain; charset=utf-16le
./src/System.Xml.ReaderWriter/tests/Readers/ReaderSettings/TCLineInfo.cs: text/plain; charset=utf-16le
./src/System.Xml.ReaderWriter/tests/Readers/ReaderSettings/FilterSettings.cs: text/plain; charset=utf-16le
./src/System.Xml.ReaderWriter/tests/Readers/ReaderSettings/TCConformanceSettings.cs: text/plain; charset=utf-16le
./src/System.Xml.ReaderWriter/tests/Readers/ReaderSettings/TCOneByteStream.cs: text/plain; charset=utf-16le
./src/System.Xml.ReaderWriter/tests/Readers/ReaderSettings/MaxSettings.cs: text/plain; charset=utf-16le
./src/System.Xml.ReaderWriter/tests/Readers/ReaderSettings/CReaderTestModule.cs: text/plain; charset=utf-16le
./src/System.Xml.ReaderWriter/tests/Readers/ReaderSettings/ReaderSettings.cs: text/plain; charset=utf-16le
./src/System.Xml.ReaderWriter/tests/Readers/ReaderSettings/TCCloseInput.cs: text/plain; charset=utf-16le
./src/System.Xml.ReaderWriter/tests/Readers/ReaderSettings/TCReaderSettings.cs: text/plain; charset=utf-16le
./src/System.Xml.ReaderWriter/tests/Readers/ReaderSettings/Interactions.cs: text/plain; charset=utf-16le
./src/System.Xml.ReaderWriter/tests/Readers/ReaderSettings/TCFilterSettings.cs: text/plain; charset=utf-16le
./src/System.Xml.ReaderWriter/tests/Readers/ReaderSettings/ConformanceSettings.cs: text/plain; charset=utf-16le
./src/System.Xml.ReaderWriter/tests/Readers/ReaderSettings/CreateOverloads.cs: text/x-pascal; charset=utf-16le
./src/System.Xml.ReaderWriter/tests/Readers/ReaderSettings/TCDtdProcessingCoreReader.cs: text/plain; charset=utf-16le
./src/System.Xml.ReaderWriter/tests/Readers/WrappedReader/InheritedCases.cs: text/plain; charset=utf-16le
./src/System.Xml.ReaderWriter/tests/Writers/XmlWriterApi/WriteEndDocumentOnCloseTest.cs: text/plain; charset=utf-16le
./src/System.Xml.ReaderWriter/tests/Writers/XmlWriterApi/TCFlushClose.cs: text/plain; charset=utf-16le
./src/System.Xml.ReaderWriter/tests/Writers/XmlWriterApi/TCDocType.cs: text/plain; charset=utf-16le
./src/System.Xml.ReaderWriter/tests/Writers/XmlWriterApi/TCWriterWithMemoryStream.cs: text/plain; charset=utf-16le
./src/System.Xml.ReaderWriter/tests/Writers/XmlWriterApi/TCErrorConditionWriter.cs: text/plain; charset=utf-16le
./src/System.Xml.ReaderWriter/tests/Writers/XmlWriterApi/TCWriteNode_XmlReader.cs: text/plain; charset=utf-16le
./src/System.Xml.ReaderWriter/tests/Writers/XmlWriterApi/TCFragmentCL.cs: text/plain; charset=utf-16le
./src/System.Xml.ReaderWriter/tests/Writers/XmlWriterApi/TCNewLineOnAttributes.cs: text/plain; charset=utf-16le
./src/System.Xml.ReaderWriter/tests/Writers/XmlWriterApi/TCOmitXmlDecl.cs: text/plain; charset=utf-16le
./src/System.Xml.ReaderWriter/tests/Writers/XmlWriterApi/EndOfLineHandlingTests.cs: text/plain; charset=utf-16le
./src/System.Xml.ReaderWriter/tests/Writers/XmlWriterApi/TCFullEndElement.cs: text/plain; charset=utf-16le
./src/System.Xml.ReaderWriter/tests/Writers/XmlWriterApi/CommonTests.cs: text/plain; charset=utf-16le
./src/System.Xml.ReaderWriter/tests/Writers/XmlWriterApi/TCAttribute.cs: text/plain; charset=utf-16le
./src/System.Xml.ReaderWriter/tests/Writers/XmlWriterApi/TCErrorState.cs: text/plain; charset=utf-16le
./src/System.Xml.ReaderWriter/tests/Writers/XmlWriterApi/TCEOFHandling.cs: text/plain; charset=utf-16le
./src/System.Xml.ReaderWriter/tests/Writers/XmlWriterApi/ErrorCondition.cs: text/plain; charset=utf-16le
./src/System.Xml.ReaderWriter/tests/Writers/XmlWriterApi/TCDefaultWriterSettings.cs: text/plain; charset=utf-16le
./src/System.Xml.ReaderWriter/tests/Writers/XmlWriterApi/TCNamespaceHandling.cs: text/plain; charset=utf-16le
./src/System.Xml.ReaderWriter/tests/Writers/XmlWriterApi/TCWriteEndDocumentOnCloseTest.cs: text/plain; charset=utf-16le
./src/System.Xml.ReaderWriter/tests/Writers/XmlWriterApi/TCNewLineHandling.cs: text/plain; charset=utf-16le
./src/System.Xml.ReaderWriter/tests/Writers/XmlWriterApi/TCIndent.cs: text/plain; charset=utf-16le
./src/System.Xml.ReaderWriter/tests/Writers/XmlWriterApi/ReaderParamTestCase.cs: text/plain; charset=utf-16le
./src/System.Xml.ReaderWriter/tests/Writers/RwFactory/WriterFactory.cs: text/plain; charset=utf-16le
./src/System.Xml.ReaderWriter/tests/Writers/RwFactory/CXmlDriverParam.cs: text/plain; charset=utf-16le
./src/System.Xml.ReaderWriter/tests/Writers/RwFactory/ReaderFactory.cs: text/plain; charset=utf-16le
./src/System.Xml.ReaderWriter/tests/Writers/RwFactory/CXmlDriverEngine.cs: text/plain; charset=utf-16le
./src/System.Xml.ReaderWriter/tests/Writers/RwFactory/CRWFactory.cs: text/plain; charset=utf-16le
./src/System.Xml.ReaderWriter/tests/Writers/RwFactory/CXmlDriverModule.cs: text/plain; charset=utf-16le
./src/System.Xml.ReaderWriter/tests/XmlConvert/XmlBaseCharConvertTests.cs: text/plain; charset=utf-16le
./src/System.Xml.ReaderWriter/tests/XmlConvert/XmlConvertTests.cs: text/plain; charset=utf-16le
./src/System.Xml.ReaderWriter/tests/XmlConvert/XmlDigitCharConvertTests.cs: text/plain; charset=utf-16le
./src/System.Xml.ReaderWriter/tests/XmlConvert/XmlBaseCharConvertTests2.cs: text/plain; charset=utf-16le
./src/System.Xml.ReaderWriter/tests/XmlConvert/XmlIdeographicCharConvertTests1.cs: text/plain; charset=utf-16le
./src/System.Xml.ReaderWriter/tests/XmlConvert/XmlEmbeddedNullCharConvertTests1.cs: text/plain; charset=utf-16le
./src/System.Xml.ReaderWriter/tests/XmlConvert/XmlCombiningCharConvertTests1.cs: text/plain; charset=utf-16le
./src/System.Xml.ReaderWriter/tests/XmlConvert/XmlEmbeddedNullCharConvertTests3.cs: text/plain; charset=utf-16le
./src/System.Xml.ReaderWriter/tests/XmlConvert/XmlIdeographicCharConvertTests.cs: text/plain; charset=utf-16le
./src/System.Xml.ReaderWriter/tests/XmlConvert/ToTypeTests.cs: text/plain; charset=utf-16le
./src/System.Xml.ReaderWriter/tests/XmlReaderLib/TCMoveToElement.cs: text/plain; charset=utf-16le
./src/System.Xml.ReaderWriter/tests/XmlReaderLib/TCMoveToFirstAttribute.cs: text/plain; charset=utf-16le
./src/System.Xml.ReaderWriter/tests/XmlReaderLib/TCReadAttributeValue.cs: text/plain; charset=utf-16le
./src/System.Xml.ReaderWriter/tests/XmlReaderLib/TCAttributeTest.cs: text/plain; charset=utf-16le
./src/System.Xml.ReaderWriter/tests/XmlReaderLib/TCReadValue.cs: text/plain; charset=utf-16le
./src/System.Xml.ReaderWriter/tests/XmlReaderLib/TCSkip.cs: text/plain; charset=utf-16le
./src/System.Xml.ReaderWriter/tests/XmlReaderLib/TCNamespace.cs: text/plain; charset=utf-16le
./src/System.Xml.ReaderWriter/tests/XmlReaderLib/CXmlReaderEntityTest.cs: text/plain; charset=utf-16le
./src/System.Xml.ReaderWriter/tests/XmlReaderLib/TCReadToDescendant.cs: text/plain; charset=utf-16le
./src/System.Xml.ReaderWriter/tests/XmlReaderLib/TCBufferBoundaries.cs: text/plain; charset=utf-16le
./src/System.Xml.ReaderWriter/tests/XmlReaderLib/CXmlReaderReadEtc.cs: text/plain; charset=utf-16le
./src/System.Xml.ReaderWriter/tests/XmlReaderLib/TCResolveEntity.cs: text/plain; charset=utf-16le
./src/System.Xml.ReaderWriter/tests/XmlReaderLib/CDataReader.cs: text/plain; charset=utf-16le
./src/System.Xml.ReaderWriter/tests/XmlReaderLib/ReadBase64.cs: text/plain; charset=utf-16le
./src/System.Xml.ReaderWriter/tests/XmlReaderLib/TCDispose.cs: text/plain; charset=utf-16le
./src/System.Xml.ReaderWriter/tests/XmlReaderLib/TCIsStartElement.cs: text/plain; charset=utf-16le
./src/System.Xml.ReaderWriter/tests/XmlReaderLib/TCXmlns.cs: text/plain; charset=utf-16le
./src/System.Xml.ReaderWriter/tests/XmlReaderLib/CXMLGeneralTest.cs: text/plain; charset=utf-16le
./src/System.Private.DataContractSerialization/src/System/Xml/XmlUTF8TextReader.cs: application/octet-stream; charset=binary
```

While the encoding should theoretically not matter, some third-party tools don't cope with those well, see e.g. the issue @MattWhilden raised for linguist https://github.com/github/linguist/issues/2310 and GitHub's diff in https://github.com/dotnet/corefx/pull/1338#issuecomment-90667234.

We should investigate converting those to utf8 to make them consistent with the other files, or teaching the codeformatter to do so.

### PR DESCRIPTION
**Pull request by krwq**
Conversion script:
For each .cs file:
- Read all bytes
- Analyze BOM to get encoding
- If encoding not any of those then end: Encoding.UTF32;  Encoding.BigEndianUnicode; Encoding.Unicode
- Get string from bytes read from the file (encoding.GetString(bytes))
- Get utf-8 (no BOM) bytes from the string ((new Utf8Encoding(false)).GetBytes(str))
- Save to file

I'm not sure to reliably check if we didn't lose anything although I did run all tests (including outerloop) and made sure no test is testing anything related to encoding (looking at the file name)

### CODE REVIEW

**Comment by akoeplinger** [comment]
Hmm, the files still have a BOM for me when I checkout your branch. But at least they are in UTF8 now :)

**Comment by krwq** [comment]
Hmm interesting, I will try to remove BOM although it seems that it keeps adding BOM even when I ask him not to:
```csharp
                        Encoding utf8NoBOM = new UTF8Encoding(false);
                        File.WriteAllText(path, content, utf8NoBOM);
```

**Comment by akoeplinger** [comment]
@krwq don't bother to invest much time in it, there are many files with a BOM in the repo and this didn't cause any problems yet ;)

**Comment by krwq** [comment]
I already converted every single file since I'm doing it already :P Let me just finish running tests :)

**Comment by stephentoub** [comment]
LGTM.  @ellismg, any concerns with this?

**Comment by ellismg** [comment]
Nope.  Seems like a good idea to me.

**Comment by stephentoub** [comment]
@krwq, looks like you'll need to resolve conflicts or rebase before we can merge in the UI.

**Comment by krwq** [comment]
Done, will merge after the merge build is finished.

**Comment by krwq** [comment]
@dotnet-bot test this please

**Comment by krwq** [comment]
@dotnet-bot test this please

**Comment by krwq** [comment]
@dotnet-bot test this please

**Comment by krwq** [comment]
@dotnet-bot abort testing

**Comment by krwq** [comment]
@dotnet-bot test this please

**Comment by sharwell** [comment]
:exclamation: The files need a byte order mark.

**Comment by sharwell** [comment]
If you don't put a byte order mark and the files do not contain any characters outside of 7-bit ASCII, then many Windows editors will treat them as CP1252 instead of UTF-8 if someone adds a character which is supported in CP1252. **If this happens the file will not be a valid UTF-8 file.**

Adding the byte order mark *guarantees* that this situation will not happen. While the byte order mark for a UTF-8 file is optional (viewed as pointless by some), it is an important part of ensuring that all editors treat the files in the repository equally.

**Comment by sharwell** [comment]
Example situation that looks innocent but would break the code:

A new developer opens a source file in their favorite text editor (might not be Visual Studio), and adds a reference to §x.y of ECMA-335. The § gets saved back as 0xA7 (single byte CP1252 because that's the default on most US Windows installations), and now you have a file that isn't valid UTF-8. Maybe the diff will show it, but maybe it won't. But you can be sure the next time you try to read the file as UTF-8 you will get an exception, because the UTF-8 encoding for § is two bytes (0xC2 0xA7).

**Comment by ellismg** [comment]
/cc: @jaredpar.  IIRC, Roslyn has moved to a UTF-8 No BOM world as well.

**Comment by krwq** [comment]
@sharwell, I thought we already added a guideline to use \uXXXX
after this:
https://github.com/dotnet/corefx/issues/77

**Comment by krwq** [comment]
@dotnet-bot test this please

**Comment by sharwell** [comment]
@krwq The escape sequence guideline would be a workaround for a problem that is already solved. Also, it still leaves you explaining to people what they can and can't do. If you put the BOM back, everything will just always work and no one has to think about it.

**Comment by krwq** [comment]
I think that encoding is something which we can easily lose so we shouldn't be using any special characters anyway. I don't have a strong opinion if we should be using BOM or not but I believe we should be consistent with whatever we choose.

**Comment by stephentoub** [comment]
@dotnet-bot test this please

**Comment by dsplaisted** [comment]
Based on @sharwell's comments, it seems to me like we should have the BOM.

**Comment by tarekgh** [comment]
I think we should have the BOM too. for Roslyn, I think they still use 1252 encoding for compatibility. as long as the BOM not hurting then it is good idea to keep it.

**Comment by krwq** [comment]
If no objections will update PR in 1-2 days (let's make sure everyone agrees)

**Comment by jasonmalinowski** [comment]
Visual Studio defaults to adding BOMs. Enforcing no-BOM would be fighting against it and might cause lots of pain. Yes, we need a way to make that configurable, but that's the world for now.

**Comment by ellismg** [comment]
Does this mean that we are going to require every file in the repo to have a BOM or we will continue to be inconsistent?  Most other editors default to writing UTF8 without a BOM (Including the newly released Visual Studio Code).

Given that VS always writes it and we don't want to swim up stream, I would be fine keeping the existing BOMs (and allow new ones to be introduced) under the following conditions:

1. We continue to not use non ASCII characters, and enforce this either via tooling or PRs.
2. We don't include the addition or removal of a BOM in diffs.

Alternately we make a guideline that we ALWAYS use a BOM and ask folks to configure their editors appropriately (.editorconfig might be able to help here, although they say to shy away from the utf-with-bom encoding directive) and write some bots or something to go clean up the inevitable mistakes.

Thoughts?

**Comment by jasonmalinowski** [comment]
So as far as BOM vs. not-BOM, I don't really care. My preference is we get a time machine and invent UTF-8 100 years ago and just get everybody to use it from day 1 of computing. But alas...

If VS adds BOMs, and non-VS doesn't add BOMs, honestly just use your gut to decide which group will hate you less and go with that. I don't have a good sense of which editors people are using for corefx, but that'd inform the decision.

**Comment by jaredpar** [comment]
The policy Roslyn adopted was simply:

> If it needs a BOM to correctly decode the file then add a BOM, else please consider removing the BOM. 

The reason we adopted this policy was because it was already the defacto policy in the code base.  Even though Roslyn is a product primarily written in Visual Studio the majority of files we were looking at didn't have a BOM.  

Could be we simply tested incorrectly.  But we've had a soft policy of removing BOMs for ~6 months now and there haven't been any real issues with it.

**Comment by akoeplinger** [comment]
I think we shouldn't modify the the files that already have a BOM. As @jasonmalinowski says, VS automatically adds a BOM for new files and other tools don't, so we're always going the be inconsistent.
@jaredpar out of interest, I ran `$ grep -rl $'\xEF\xBB\xBF' . | wc -l` against roslyn and it told me 6809 files have a BOM there.

The main reason for this PR and #1339 was moving off of UTF-16, we should focus on that until BOM/no-BOM becomes a problem.

**Comment by jasonwilliams200OK** [comment]
@krwq, I think the verdict is to have files with BOM (VS way) is the way for now. Please rebase and merge this, so at least one weird issue is solved: https://github.com/github/linguist/issues/2310 [GH-ligust's misclassification of .cs file with UTF-16 and hence the incorrect language stats in homepage of this repo].

**Comment by stephentoub** [comment]
@krwq, should we close this out for now?  Lots has changed in the repo since this was opened.

**Comment by mellinoe** [comment]
I know Krzysztof is on vacation this week, but yeah, we should probably close this and then re-open it on against all of the new stuff if we still want to do it.

**Comment by stephentoub** [comment]
Ok, I'm closing this out for now.  Thanks.

**Pull request closed without merging**
