### PR TITLE
Stabilize ExitTime test

### PR DESCRIPTION
**Pull request by danmosemsft**
Fix https://github.com/dotnet/corefx/issues/22205

System clock went backwards up to 45ms after we snapshotted it.

### CODE REVIEW

**Comment by danmosemsft** [comment]
@dotnet/dnceng `[Pipeline] End of Pipeline
Setting status of 080df6386a5a11115515a3eb9736ce44f3075f6c to FAILURE with url https://ci3.dot.net/job/dotnet_corefx/job/master/job/osx-TGroup_netcoreapp+CGroup_Debug+AGroup_x64+TestOuter_false_prtest/1333/ and message: 'Build finished. '
Using context: OSX x64 Debug Build
java.nio.channels.ClosedChannelException
	at org.jenkinsci.remoting.protocol.impl.ChannelApplicationLayer.onReadClosed(ChannelApplicationLayer.java:208)
	at org.jenkinsci.remoting.protocol.ApplicationLayer.onRecvClosed(ApplicationLayer.java:222)
	at org.jenkinsci.remoting.protocol.ProtocolStack$Ptr.onRecvClosed(ProtocolStack.java:832)
	at org.jenkinsci.remoting.protocol.FilterLayer.onRecvClosed(FilterLayer.java:287)`

**Comment by danmosemsft** [comment]
@dotnet-bot test OSX x64 Debug Build please (infra)

**Comment by stephentoub** [comment]
> System clock went backwards up to 45ms after we snapshotted it.

This is a theory or fact? If the latter, just curious how you determined that.

**Comment by dleeapho** [comment]
@maririos PTAL CI failure. Your tracking issue: https://github.com/dotnet/core-eng/issues/1231

**Comment by danmosemsft** [comment]
@stephentoub I just did `(new DateTime(636355038728165136) - new DateTime(636355038727555168)).Milliseconds` using the values logged in the failure. End time was 60ms _before_ the start. But the test had wound the start back 25ms so the separation was actually 85ms (I mistyped 45)

**Pull request merged**
