### PR TITLE
Building manual System facade for serialization support

### PR DESCRIPTION
**Pull request by ViktorHofer**
Required for the types mentioned in System.forwards.cs.
Relates to https://github.com/dotnet/corefx/pull/20870

cc @danmosemsft @ericstj @jkotas @morganbr

### CODE REVIEW

**Comment by ViktorHofer** [comment]
> 06:51:07 D:\j\workspace\uapaot_debug_---28c5216e\external\test-runtime\XUnit.Runtime.depproj(160,5): warning : Could not find the TestILC Tools at 'D:\j\workspace\uapaot_debug_---28c5216e\packages\TestILC.amd64ret\1.0.0-beta-25413-00\TestILC'. Please run sync.

@weshaggard any idea?

**Comment by danmosemsft** [comment]
@dotnet-bot test Vertical uapaot Build please (nuget?)

**Comment by weshaggard** [comment]
@ViktorHofer that is an related warning.

The most likely issue here is that genfacades is seeing duplicated types. I hit this with mscorlib as well and needed to remove some duplicate types. To figure out the set do a uapaot build locally and then rebuild System shim project to see the issues.

**Comment by ViktorHofer** [comment]
Thanks Wes. I get 10 duplicate type errors. I will do the same as you did for mscorlib.

**Comment by ViktorHofer** [comment]
CI should now get green.

Exluded types for uapaot // cc @jkotas to track

**Comment by ViktorHofer** [comment]
@dotnet-bot test Vertical uapaot Build

**Comment by ViktorHofer** [comment]
@dotnet-bot test Portable Linux x64 Release Build

_Timeout issue_

**Pull request merged**
