### PR TITLE
Putting back net46 specific dependencies (for Desktop Runs) 

### PR DESCRIPTION
**Pull request by MattGal**
By updating to fixed TestSuite and updating BuildToolsVersion (For publishtest.targets)

@karajas  @ericstj

### CODE REVIEW

**Comment by MattGal** [comment]
@dotnet-bot  Test this please

**Comment by MattGal** [comment]
@dotnet-bot  Test this please

**Comment by MattGal** [comment]
@dotnet-bot Test this please

**Comment by MattGal** [comment]
@dotnet-bot  Build And Test Innerloop OSX Debug please

**Comment by MattGal** [comment]
@dotnet-bot help

**Comment by MattGal** [comment]
@dotnet-bot test Innerloop OSX Debug Build and Test

**Comment by weshaggard** [comment]
Can you point me at the interesting build tools changes that this includes?

**Comment by weshaggard** [comment]
Nevermind I found it https://github.com/dotnet/buildtools/pull/1147

**Pull request merged**
