### PR TITLE
Update build tools to latest build to pick up fixes.

### PR DESCRIPTION
**Pull request by jhendrixMSFT**

### CODE REVIEW

**Comment by stephentoub** [comment]
LGTM

**Comment by jhendrixMSFT** [comment]
@dotnet-bot test this please

**Comment by jhendrixMSFT** [comment]
@dotnet-bot test Innerloop OSX Debug Build and Test please

**Comment by jhendrixMSFT** [comment]
@dotnet-bot test Innerloop OSX Release Build and Test please

**Comment by jhendrixMSFT** [comment]
@dotnet-bot test Innerloop Windows_NT Release Build and Test please

**Comment by jhendrixMSFT** [comment]
@dotnet-bot test Innerloop CentOS7.1 Debug Build and Test please

**Comment by jhendrixMSFT** [comment]
@dotnet-bot test Innerloop OSX Debug Build and Test please

**Comment by stephentoub** [comment]
Test Innerloop OSX Release Build and Test please

**Comment by stephentoub** [comment]
Test. Innerloop CentOS7.1 Debug Build and Test please

**Comment by jhendrixMSFT** [comment]
@dotnet-bot test Innerloop Windows_NT Release Build and Test please

**Comment by stephentoub** [comment]
Test Innerloop CentOS7.1 Debug Build and Test please

**Comment by stephentoub** [comment]
Test Innerloop CentOS7.1 Release Build and Test please

**Pull request merged**
