### PR TITLE
Use AsnReader.ThrowIfNotEmpty instead of explicit checks.

### PR DESCRIPTION
**Pull request by filipnavara**
/cc @bartonjs

### CODE REVIEW

**Comment by bartonjs** [comment]
While the change seems like reasonable cleanup (I assume it was all written before I added ThrowIfNotEmpty), it seems sort of out of the blue.  I'm curious why it came up.

**Comment by filipnavara** [comment]
I am trying to see how `AsnReader` stacks up compared to `DerSequenceReader`. I have rewritten small parts of the `X509Certificates` code using `AsnReader` to see if that's feasible and beneficial change.

So far my feelings are a bit mixed up. It's weird to have methods like `TryReadInt32` that sometimes return `false` and other times throw exceptions. In (nearly) every case I still need to do `throw new CryptographicException(SR.Cryptography_Der_Invalid_Encoding);` if `false` is returned. In fact the only current use outside of the serializer does that too. Methods like `GetNamedBitListValue` seemed like a great help until I discovered that the `X509KeyUsageFlags` enum has reverse bit order.

**Comment by filipnavara** [comment]
My naïve expectation was that `TryReadInt32` would throw if there's too big integer and return `false` if there is something else than integer. The method works exactly the opposite way though. So writing code that reads a sequence of optional fields becomes a mess of `PeekTag`s and `TryRead<whatever>` and `throw`s. Not a very friendly API for that use case:

```c#
            // BasicConstraints ::= SEQUENCE {
            //   cA BOOLEAN DEFAULT FALSE,
            //   pathLenConstraint INTEGER(0..MAX) OPTIONAL }

            AsnReader constraints = new AsnReader(encoded, AsnEncodingRules.DER);

            if (!constraints.HasData)
            {
                certificateAuthority = false;
                hasPathLengthConstraint = false;
                pathLengthConstraint = 0;
                return;
            }

            if (constraints.PeekTag().TagValue == (int)UniversalTagNumber.Boolean)
            {
                certificateAuthority = constraints.ReadBoolean();
            }
            else
            {
                certificateAuthority = false;
            }

            if (constraints.HasData)
            {
                if (!constraints.TryReadInt32(out pathLengthConstraint))
                {
                    throw new CryptographicException(SR.Cryptography_Der_Invalid_Encoding);
                }
                hasPathLengthConstraint = true;
            }
            else
            {
                pathLengthConstraint = 0;
                hasPathLengthConstraint = false;
            }

            constraints.ThrowIfNotEmpty();
``` 

The `AsnSerializer` usage, in general, looks much nicer, but it doesn't really work well for cases like X.500 names. There are strings that could be encoded in more than one way (PrintableString, UTF8, T61, etc.) and as far as I can see that's not supported by the [de]serialization.

**Comment by bartonjs** [comment]
> Methods like GetNamedBitListValue seemed like a great help until I discovered that the X509KeyUsageFlags enum has reverse bit order.

Yep, that was a bit of a design dilemma.  Make the one usage of it work easily, or make it make sense to the way people write enums in .NET.  (The .NET value for Key Usage is a blind copy of the Windows value, and they just did a "copy this memory into a 32-bit buffer and hope that we never ever add a 33rd bit to this enum" implementation.)

So I had several modes.  Then we simplified it.

```
Consider a NamedBitList defined as

  SomeList ::= BIT STRING {
    a(0), b(1), c(2), d(3), e(4), f(5), g(6), h(7), i(8), j(9), k(10)
  }

The BIT STRING encoding of (a | j) is
  unusedBitCount = 6,
  contents: 0x80 0x40  (0b10000000_01000000)

A reasonable C# exposure of this structure is

[Flags]
enum SomeList : ushort
{
    A = 1,
    B = 1 << 1,
    C = 1 << 2,
    ...
}

In NamedZeroIsOne we will make that enum work.

In NamedZeroIs128LittleEndian the enum would be

[Flags]
enum SomeList : ushort
{
    A = 0x80,
    B = 0x40,
    C = 0x20,
    ...
    H = 0x01,
    I = 0x8000,
    ...
}

In NamedZeroIs128BigEndian the enum would be

[Flags]
enum SomeList : ushort
{
    A = 0x8000,
    B = 0x4000,
    C = 0x2000,
    ...
    H = 0x0100,
    I = 0x0080,
    ...
}

NamedZeroIs128BigEndian is the most brittle, because if additional
values increase the number of bytes required in the encoding everything
needs to be renumbered.

NamedZeroIs128LittleEndian requires a bit of mental gymnastics to understand,
but it is (up to 64 bits) a sensibly extensible model.

NamedZeroIsOne matches the way that enumerations grow in C#, but it happens
to be exactly backward from the storage mechanism.

(There should be a fourth ordering, where bits increase in value left to right,
but bytes decrease in value.  But it's not obvious why anyone would want it, or
what to call it)
```

**Comment by bartonjs** [comment]
@dotnet-bot Test NETFX x86 Release Build please (#31349)
Test Windows x64 Debug Build (Nano fireball for `System.IO.Pipes.Performance.Tests`)

**Comment by filipnavara** [comment]
Thanks for the detailed explanation. I know I probably hit the worst cases possible for `AsnReader` that you can find (DEFAULT+OPTIONAL and the Printable/UTF8/T61 strings) and that was intentional. 

> All of the Span methods we added in .NET Core 2.1 are "return false if the destination is too small".

I guess that's fine. However the convenience methods `TryReadInt32`, `TryReadUInt32` and other similar ones use the `Span` only internally so it's not obvious that they follow this pattern. I question whether the methods make sense in the first place. All usages I found throw `CryptographicException(SR.Cryptography_Der_Invalid_Encoding)` when `false` is returned. It would be more convenient to offer just `ReadInt32` and `ReadUInt32` methods and throw the exception there instead. It wouldn't require the caller to keep one more resource string and it would make every usage tidy.

If I decide to cleanup/share some of the X509 changes do you have some strong preference for using the `AsnSerializer` or `AsnReader`? I don't know what are the performance characteristics of either and whether it should count towards the decision.

**Comment by bartonjs** [comment]
They're there for 32-bit processors, really.

```
if (reader.TryReadInt32(out int registerSized))
{
    return checked(registerSized * multiplier);
}

if (reader.TryReadInt64(out long ugh))
{
    return checked(ugh * multiplier);
}

BigInteger whatInTheWorld = reader.ReadInteger();
return whatInTheWorld * multiplier;
```

Non-Try- ReadInt32 seems like a reasonable thing to add to the class, though.

> do you have some strong preference for using the AsnSerializer or AsnReader?

For reading:  Use the serializer when you can, the reader when you have no other choice.  (The serializer stops you from forgetting ThrowIfNotEmpty).

For writing: The serializer is annoying when you walk through an ASN ANY.  If you don't have one of those, use the serializer.  If you have exactly one of those, it's a judgment call.  If you have more than one of those, the AsnWriter is probably nicer code and more performant.

> The AsnSerializer usage, in general, looks much nicer, but it doesn't really work well for cases like X.500 names. There are strings that could be encoded in more than one way (PrintableString, UTF8, T61, etc.) and as far as I can see that's not supported by the [de]serialization.

```C#
[Choice]
internal struct DirectoryString
{
    [T61String]
    public string T61String;

    [PrintableString]
    public string PrintableString;

    [UniversalString]
    public string UniversalString;

    [Utf8String]
    public string Utf8String;

    [BMPString]
    public string BMPString;

    public string GetValue() => Utf8String ?? PrintableString ?? BMPString ?? UniversalString ?? T61String;
}
```

The SEQUENCE OF { SET OF { SEQUENCE  { } } } nature of X500Name is annoying for the serializer, but the normal hack for it is to declare an otherwise pointless type as [Choice] so you can slap in another attribute.

```C#
[Choice]
internal struct RelativeDistinguishedName
{
     [SetOf]
    public AttributeTypeAndValue AttributeTypeAndValues;
}
```

Though I came up with that trick after I decided "sad, it can't do X500DistinguishedName", so I haven't actually tried it in this context.

**Pull request merged**
