### PR TITLE
WIP: Update CoreFx to CMake 3.14.

### PR DESCRIPTION
**Pull request by jkoritzinsky**
Update CoreFx build images to have CMake 3.14 and update the build to require CMake 3.14 so we have a consistent toolset for the consolidated repository.

### CODE REVIEW

**Comment by stephentoub** [comment]
I thought I remember seeing recently that we actually need at least 3.16 rc1. @safern?

**Comment by jkoritzinsky** [comment]
I believe that is the case to remove one of the warnings during the build.

If that's the case, we'll have to get the CMake version in the Windows images updated and the docker images re-built with newer versions of CMake, likely after 3.16 is released (since the Kitware APT feed looks like it doesn't include pre-releases).

**Comment by jkoritzinsky** [comment]
Yep just confirmed on the CMake repo on GitLab that the fix for the Install target landed in a 3.16 release.

**Comment by safern** [comment]
Right. The minimum required version in corefx is 3.16-rc1.

**Comment by jkoritzinsky** [comment]
I'll close this for now since we're going to need new images anyway when CMake 3.16 comes out.

**Comment by ViktorHofer** [comment]
Thanks for the PR anyway. When cmake 3.16 comes out we come back to this effort. Probably in a week or two.

**Comment by jkoritzinsky** [comment]
The fix for MSB8065 was back-ported to CMake 3.15.5, which was just released. I'll start poking to get it installed on the docker images and available for the Windows builds and then open a new PR.

**Comment by ViktorHofer** [comment]
Awesome. I think we need this version also in our native toolset boostrapping registry. Can you make sure it's there as well?

**Comment by jkoritzinsky** [comment]
I need to figure out how to do that, but yes that's on my list of things to do.

**Comment by danmosemsft** [comment]
I don't know anything about the issue, but I noticed in https://github.com/dotnet/corefx/issues/41077#issuecomment-539216388 they mentioned part of the fix was in 3.16.

**Comment by jkoritzinsky** [comment]
They backported the second part of the fix to 3.15.5

**Pull request closed without merging**
