### PR TITLE
Added netcore50aot to System.Private.DataContractSerialization

### PR DESCRIPTION
**Pull request by venkat-raman251**
Old PR #5448.

### CODE REVIEW

**Comment by mellinoe** [comment]
Innerloop CentOS7.1 Release Build and Test

**Comment by venkat-raman251** [comment]
Innerloop CentOS7.1 Release Build and Test

**Comment by venkat-raman251** [comment]
@dotnet-bot Test Innerloop CentOS7.1 Release Build and Test

**Comment by venkat-raman251** [comment]
@dotnet-bot Test Innerloop CentOS7.1 Release Build and Test

**Comment by venkat-raman251** [comment]
@mellinoe ,@weshaggard : can this be merged?

**Comment by weshaggard** [comment]
LGTM

**Pull request merged**
