### PR TITLE
Enable some System.Net tests for OSX/*nix.

### PR DESCRIPTION
**Pull request by pgavlin**
- The NameResolution functional tests were disabled on all *nixes.
- The NameResolution PAL tests have been switched to the more modern
  style.
- The Sockets.Legacy tests were disabled for OS X when using
  run-test.sh.

### CODE REVIEW

**Comment by pgavlin** [comment]
@stephentoub PTAL

**Comment by stephentoub** [comment]
LGTM. Thanks, Pat.

**Comment by pgavlin** [comment]
@dotnet-bot test this please

**Comment by stephentoub** [comment]
``
14:07:09    System.Net.NameResolution.Tests.DnsTests.GetHostEntryAsyncWithAddress [FAIL]
14:07:09       System.ArgumentNullException : Value cannot be null.
14:07:09       Parameter name: address
14:07:09    System.Net.NameResolution.Pal.Tests  Total: 13, Errors: 0, Failed: 0, Skipped: 0, Time: 0.771s
14:07:09       Stack Trace:
14:07:10             at System.Net.Dns.HostResolutionBeginHelper(IPAddress address, Boolean flowContext, Boolean includeIPv6, AsyncCallback requestCallback, Object state)
14:07:10             at System.Net.Dns.BeginGetHostEntry(IPAddress address, AsyncCallback requestCallback, Object stateObject)
14:07:10             at System.Net.Dns.<GetHostEntryAsync>b__9(IPAddress arg, AsyncCallback requestCallback, Object stateObject)
14:07:10             at System.Threading.Tasks.TaskFactory`1.FromAsyncImpl[TArg1](Func`4 beginMethod, Func`2 endFunction, Action`1 endAction, TArg1 arg1, Object state, TaskCreationOptions creationOptions)
14:07:10             at System.Threading.Tasks.TaskFactory`1.FromAsync[TArg1](Func`4 beginMethod, Func`2 endMethod, TArg1 arg1, Object state)
14:07:10             at System.Net.Dns.GetHostEntryAsync(IPAddress address)
14:07:10             at System.Net.NameResolution.Tests.DnsTests.<>c__DisplayClass1.<GetHostEntryAsyncWithAddress>b__0()
14:07:10             at System.Net.NameResolution.Tests.DnsTests.GetHostEntryAsync(Func`1 getHostEntryFunc)
14:07:10             at System.Net.NameResolution.Tests.DnsTests.<GetHostEntryAsyncWithAddress>d__3.MoveNext()
14:07:10          --- End of stack trace from previous location where exception was thrown ---
14:07:10             at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
14:07:10             at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
14:07:10          --- End of stack trace from previous location where exception was thrown ---
14:07:10             at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
14:07:10             at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
14:07:10          --- End of stack trace from previous location where exception was thrown ---
14:07:10             at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
14:07:10             at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
```

**Comment by pgavlin** [comment]
That's odd. I cannot repro the failure locally.

**Comment by stephentoub** [comment]
I've hit something similar locally on Linux.  I think what was happening is that in this code https://github.com/dotnet/corefx/blob/master/src/System.Net.NameResolution/tests/FunctionalTests/TestSettings.cs , ResolveHost was returning null because it couldn't find a matching address family.  Not sure if it's the same issue here, but it seems like it could be.

**Comment by pgavlin** [comment]
Oh, that would make sense: `localhost` is not always configured to resolve to an IPv6 address on *nix. This is an instance of #4002; I'll update the test to accommodate this.

**Pull request merged**
