### PR TITLE
Merging internal commits for release/3.1

### PR DESCRIPTION
**Pull request by vseanreesermsft**

### CODE REVIEW

**Comment by bartonjs** [comment]
@mmitche 

```
.packages\microsoft.dotnet.helix.sdk\2.0.0-beta.21552.6\tools\Microsoft.DotNet.Helix.Sdk.MonoQueue.targets(47,5): error : (NETCORE_ENGINEERING_TELEMETRY=Test) ArgumentException: Unknown QueueId. Check that authentication is used and user is in correct groups.
   at Microsoft.DotNet.Helix.Client.HelixApi.HandleFailedRequest(RestApiException ex) in /_/src/Microsoft.DotNet.Helix/Client/CSharp/HelixApi.cs:line 33
   at Microsoft.DotNet.Helix.Client.Job.OnNewFailed(HttpRequestMessage req, HttpResponseMessage res) in /_/src/Microsoft.DotNet.Helix/Client/CSharp/generated-code/Job.cs:line 211
   at Microsoft.DotNet.Helix.Client.Job.NewInternalAsync(JobCreationRequest body, String idempotencyKey, CancellationToken cancellationToken) in /_/src/Microsoft.DotNet.Helix/Client/CSharp/generated-code/Job.cs:line 279
   at Microsoft.DotNet.Helix.Client.Job.NewAsync(JobCreationRequest body, String idempotencyKey, CancellationToken cancellationToken) in /_/src/Microsoft.DotNet.Helix/Client/CSharp/generated-code/Job.cs:line 192
   at Microsoft.DotNet.Helix.Client.HelixApi.RetryAsync[T](Func`1 function, Action`1 logRetry, Func`2 isRetryable, CancellationToken cancellationToken)
   at Microsoft.DotNet.Helix.Client.JobDefinition.SendAsync(Action`1 log) in /_/src/Microsoft.DotNet.Helix/JobSender/JobDefinition.cs:line 217
   at Microsoft.DotNet.Helix.Sdk.SendHelixJob.ExecuteCore(CancellationToken cancellationToken) in /_/src/Microsoft.DotNet.Helix/Sdk/SendHelixJob.cs:line 233
   at Microsoft.DotNet.Helix.Sdk.HelixTask.Execute() in /_/src/Microsoft.DotNet.Helix/Sdk/HelixTask.cs:line 53
RestApiException: The response contained an invalid status code 400 Bad Request

Body: {"Message":"Unknown QueueId. Check that authentication is used and user is in correct groups.","ActivityId":"8b98852e9d4f8641a29ed3caabc19d8f"}
```

Does that mean we need to update the queue we're sending something to?  Or just keep jamming on retry?

**Comment by mmitche** [comment]
> @mmitche
> 
> ```
> .packages\microsoft.dotnet.helix.sdk\2.0.0-beta.21552.6\tools\Microsoft.DotNet.Helix.Sdk.MonoQueue.targets(47,5): error : (NETCORE_ENGINEERING_TELEMETRY=Test) ArgumentException: Unknown QueueId. Check that authentication is used and user is in correct groups.
>    at Microsoft.DotNet.Helix.Client.HelixApi.HandleFailedRequest(RestApiException ex) in /_/src/Microsoft.DotNet.Helix/Client/CSharp/HelixApi.cs:line 33
>    at Microsoft.DotNet.Helix.Client.Job.OnNewFailed(HttpRequestMessage req, HttpResponseMessage res) in /_/src/Microsoft.DotNet.Helix/Client/CSharp/generated-code/Job.cs:line 211
>    at Microsoft.DotNet.Helix.Client.Job.NewInternalAsync(JobCreationRequest body, String idempotencyKey, CancellationToken cancellationToken) in /_/src/Microsoft.DotNet.Helix/Client/CSharp/generated-code/Job.cs:line 279
>    at Microsoft.DotNet.Helix.Client.Job.NewAsync(JobCreationRequest body, String idempotencyKey, CancellationToken cancellationToken) in /_/src/Microsoft.DotNet.Helix/Client/CSharp/generated-code/Job.cs:line 192
>    at Microsoft.DotNet.Helix.Client.HelixApi.RetryAsync[T](Func`1 function, Action`1 logRetry, Func`2 isRetryable, CancellationToken cancellationToken)
>    at Microsoft.DotNet.Helix.Client.JobDefinition.SendAsync(Action`1 log) in /_/src/Microsoft.DotNet.Helix/JobSender/JobDefinition.cs:line 217
>    at Microsoft.DotNet.Helix.Sdk.SendHelixJob.ExecuteCore(CancellationToken cancellationToken) in /_/src/Microsoft.DotNet.Helix/Sdk/SendHelixJob.cs:line 233
>    at Microsoft.DotNet.Helix.Sdk.HelixTask.Execute() in /_/src/Microsoft.DotNet.Helix/Sdk/HelixTask.cs:line 53
> RestApiException: The response contained an invalid status code 400 Bad Request
> 
> Body: {"Message":"Unknown QueueId. Check that authentication is used and user is in correct groups.","ActivityId":"8b98852e9d4f8641a29ed3caabc19d8f"}
> ```
> 
> Does that mean we need to update the queue we're sending something to? Or just keep jamming on retry?

I'm thinking one of the target queues is no longer available. I think it's `Windows.Nano.1809.Amd64.Open`, and should be removed. /cc @dotnet/dnceng

**Comment by bartonjs** [comment]
It looks like other Windows configurations ran seem to have hit two distinct failures, `System.IO.Ports.Tests.OpenDevices.OpenDevices01` failed with an access denied error (or, rather, "unknown error 5"), and a slightly scary sounding `System.SpanTests.SpanTests.TestMatchFour_Char` failure.

Since the queue error isn't caused by this syncup, it feels like we should just take the merge and fix things directly on the release/3.1 branch.  Thoughts?

**Comment by vseanreesermsft** [comment]
We can merge it. That's fine. I did add a change removing the nano queue. We can revert that first if necessary.

**Comment by jozkee** [comment]
> System.IO.Ports.Tests.OpenDevices.OpenDevices01 failed with an access denied error (or, rather, "unknown error 5")

Known intermittent issue https://github.com/dotnet/runtime/issues/62068, you can ignore.

**Comment by michellemcdaniel** [comment]
> I'm thinking one of the target queues is no longer available. I think it's `Windows.Nano.1809.Amd64.Open`, and should be removed. /cc @dotnet/dnceng

Yeah, that queue is definitely gone. I think we have some docker containers that could be used, but otherwise it should be removed.

**Comment by ericstj** [comment]
> Known intermittent issue https://github.com/dotnet/runtime/issues/62068, you can ignore.

We shouldn't ignore these.  I'll put up a separate PR to bring the test fix back. https://github.com/dotnet/runtime/pull/66352/commits/100618b097f131246e1a14927189c85ffd06a4f9.  Posted https://github.com/dotnet/corefx/pull/43137

**Comment by ericstj** [comment]
Builds are succeeding.  All failures here are tests.  Thanks for merging @vseanreesermsft 

`System.IO.Ports.Tests.OpenDevices.OpenDevices01` will be addressed in https://github.com/dotnet/corefx/pull/43137

OSX failures:
`System.Drawing.Tests.FontFamilyTests.Families_Get_ReturnsExpected` is https://github.com/dotnet/runtime/issues/40937 -- that needs to be ported to 3.1
`System.Security.Cryptography.X509Certificates.Tests.CollectionTests.X509ChainElementCollection_IndexerVsEnumerator`
`System.Security.Cryptography.X509Certificates.Tests.ChainTests.VerifyExpiration_LocalTime` 
`System.Security.Cryptography.X509Certificates.Tests.ChainTests.BuildChain`
Not sure about these.  @bartonjs have a look if you can notice a test fix to port.

**Comment by MattGal** [comment]
> > I'm thinking one of the target queues is no longer available. I think it's `Windows.Nano.1809.Amd64.Open`, and should be removed. /cc @dotnet/dnceng
> 
> Yeah, that queue is definitely gone. I think we have some docker containers that could be used, but otherwise it should be removed.

If you want to send work to similar queues, you'd use
`(windows.nano.1809.amd64)windows.10.amd64.serverrs5@mcr.microsoft.com/dotnet-buildtools/prereqs:nanoserver-1809-helix-amd64-20200804014859-56c6673` for internal, 
and
`(windows.nano.1809.amd64.open)windows.10.amd64.serverrs5.open@mcr.microsoft.com/dotnet-buildtools/prereqs:nanoserver-1809-helix-amd64-20200804014859-56c6673` for public. 

(What this means is using the newer docker-based means of referencing Nano on a normal Windows, versus actually running Helix in Nano, which was problematic)

That said, I don't think we'd be fixing any issues arising from only being broken on Nano, so the "right thing to do" is likely to remove usage.

**Comment by bartonjs** [comment]
> System.Security.Cryptography.X509Certificates.Tests.ChainTests.BuildChain (etc)
Not sure about these. @bartonjs have a look if you can notice a test fix to port.

Opened the porting PR several weeks ago, it just never got reviewed/merged (https://github.com/dotnet/corefx/pull/43132)

**Pull request merged**
