### PR TITLE
Ref/tests for TryGetFullPath [WIP]

### PR DESCRIPTION
**Pull request by Anipik**
Fixes:-  dotnet/corefx#28258
Implementation:- PR https://github.com/dotnet/coreclr/pull/17429
RemoveRelativeSegments:- dotnet/corefx#28835

### CODE REVIEW

**Comment by danmosemsft** [comment]
Is a perf test interesting? Look at what we have for the existing method, on benchview.

**Comment by Anipik** [comment]
Some string allocations should get reduced due to use of Value string builder everywhere.
@danmosemsft Will the results be available without the coreclr being getting updated ?

**Comment by danmosemsft** [comment]
Perf test would be a long term addition. Yes it won't work until coreclr is picked up.

**Comment by danmosemsft** [comment]
@Anipik is this unblocked now?

**Comment by Anipik** [comment]
@JeremyKuhne is still working on finalizing whether we should use ValueStringBuilder or not.

**Comment by Anipik** [comment]
Closing it until the api gets reviewed again

**Pull request closed without merging**
