### PR TITLE
Don't atomise strings in Microsoft.CSharp

### PR DESCRIPTION
**Pull request by JonHanna**
The static compiler sees a lot of identical strings in quick succession as it parses tokens, and as such benefits immensely from atomising.

Dynamic compilation works with smaller units, and its atomising lives in memory forever, rather than for a compilation operation.

As such the benefits of atomising are less and the costs greater. Use strings directly, instead.

Since much of the benefit of the predefined names is in seeding this set, use strings directly in that case, too.

It's hard to determine how best to measure performance impact. I used a case that did a few different dynamic operations:

```C#
private static int dump;

[Benchmark]
public void TempPerformanceTest()
{
    foreach (var iteration in Benchmark.Iterations)
    {
        using (iteration.StartMeasurement())
        {
            for (int i = 0; i < 1000000; i++)
            {
                dynamic x = 23;
                dynamic y = 47;
                dynamic z = x * y;
                dynamic s = z.ToString();
                dynamic bu = new Uri("http://example.net/");
                dynamic u = new Uri(bu, s + s.Length);
                dynamic p = u.AbsolutePath;
                dynamic b = string.IsNullOrWhiteSpace(p);
                dynamic r = b ? x : y;
                dump = r;
            }
        }
    }
}
```

### Before
|Test Name|Metric|Iterations|AVERAGE|STDEV.S|MIN|MAX|
|---------|------|----------|-------|-------|---|---|
Microsoft.CSharp.RuntimeBinder.Tests.TempPerformance.TempPerformanceTest|Duration|4|2878.11260689472|151.795343740538|2711.06853438242|3020.87581481642
Microsoft.CSharp.RuntimeBinder.Tests.TempPerformance.TempPerformanceTest|Duration|4|2648.36714824399|10.0406400805859|2637.46739684668|2661.6017775862
Microsoft.CSharp.RuntimeBinder.Tests.TempPerformance.TempPerformanceTest|Duration|4|2736.14701287239|124.428088134655|2665.10479426716|2922.5105092833
Microsoft.CSharp.RuntimeBinder.Tests.TempPerformance.TempPerformanceTest|Duration|4|2718.26595309438|131.364382921837|2633.53285926681|2913.24330641109
Microsoft.CSharp.RuntimeBinder.Tests.TempPerformance.TempPerformanceTest|Duration|3|3407.81461799982|656.868131469811|2668.76362498082|3925.08470638618
||||||
|Ave, Max, Min of above|||2877.74146782106||2633.53285926681|3925.08470638618|

### After
|Test Name|Metric|Iterations|AVERAGE|STDEV.S|MIN|MAX|
|---------|------|----------|-------|-------|---|---|
|Microsoft.CSharp.RuntimeBinder.Tests.TempPerformance.TempPerformanceTest|Duration|4|2850.54017086362|182.223336989238|2735.97218859469|3122.08495970061|
|Microsoft.CSharp.RuntimeBinder.Tests.TempPerformance.TempPerformanceTest|Duration|4|2642.93826545393|43.5051180165349|2589.54291906861|2691.64449582264|
|Microsoft.CSharp.RuntimeBinder.Tests.TempPerformance.TempPerformanceTest|Duration|4|3004.94557938328|231.242920652251|2830.25040807882|3341.45525641438|
|Microsoft.CSharp.RuntimeBinder.Tests.TempPerformance.TempPerformanceTest|Duration|4|2653.03935330645|61.1607418566276|2587.7883784191|2734.57779295487|
|Microsoft.CSharp.RuntimeBinder.Tests.TempPerformance.TempPerformanceTest|Duration|4|2750.33040505584|165.351254692047|2588.9093997381|2935.01715120632|
|||||||
|Ave, Max, Min of above|||2780.35875481262||2587.7883784191|3341.45525641438|

The two are within each other's margin of error, but there is an average improvement of around 3%, along with the assembly no longer holding atomised strings in memory indefinitely, and the result being IMO simpler.

### CODE REVIEW

**Comment by JonHanna** [comment]
I should do some perf tests with just the individual operations in that mixed one. Will do so this evening.

**Comment by VSadov** [comment]
Need to think about this. 

There is another point - most strings that we see in the binder are created from string literals. They are either loaded by the binder (predefined ones) or by the invoking code (names of args in source, etc), but in many cases those are still compile time literals to the calling code and therefore are also loaded from metadata.
I wonder if those are interned anyways by the `ldstr` so we have the same benefits of minimizing memory impact and cheaper equality even if we do not intern them.

If we have any case where we may operate with computed/generated strings, like from a concat/stringbuilder, then we may consider a small fixed size cache for those.

**Comment by JonHanna** [comment]
Non-interned strings can come in from type names. I think it should be possible to change the lookups on types to not go via strings with several advantages, which would leave only cases where non-interned strings were very unusual (possible if one went out of one's way, but not happening in most real code).

**Comment by VSadov** [comment]
I need to take a short break from these. Will be able to review some time next week.

**Comment by JonHanna** [comment]
>  I think it should be possible to change the lookups on types to not go via strings with several advantages, which would leave only cases where non-interned strings were very unusual

By that same token, the difference between whether we atomise or not would be different in that case, and should be compared after it's either done or abandoned as not being such a good idea after all. I'm going to close this for now, and look at the costs and benefits of this after other changes have been made.

**Pull request closed without merging**
