### PR TITLE
Improve CoreLib test coverage

### PR DESCRIPTION
**Pull request by jkotas**
Contributes to https://github.com/dotnet/coreclr/issues/12782

### CODE REVIEW

**Comment by jkotas** [comment]
Related CoreCLR PR: https://github.com/dotnet/coreclr/pull/20693

**Comment by stephentoub** [comment]
@dotnet/dnceng:
https://ci3.dot.net/job/dotnet_corefx/job/master/job/linux-TGroup_netcoreapp+CGroup_Release+AGroup_arm64+TestOuter_false_prtest/7393/consoleText
https://ci3.dot.net/job/dotnet_corefx/job/master/job/linux-TGroup_netcoreapp+CGroup_Release+AGroup_x64+TestOuter_false_prtest/18105/consoleText
https://ci3.dot.net/job/dotnet_corefx/job/master/job/linux-musl-TGroup_netcoreapp+CGroup_Debug+AGroup_x64+TestOuter_false_prtest/5895/consoleText
```
Error response from daemon: Get https://registry-1.docker.io/v2/microsoft/dotnet-buildtools-prereqs/manifests/rhel7_prereqs_2: received unexpected HTTP status: 503 Service Unavailable
```

**Comment by MattGal** [comment]
@stephentoub not much we can do for 503s from docker.io.  I'll definitely keep an eye on it, and create an FR issue / support ticket with them if it continues to affect us.

**Comment by stephentoub** [comment]
The Packaging All Configurations build failed with:
```
System\Runtime\CompilerServices\AttributesTests.cs(175,17): error CS0246: The type or namespace name 'IsByRefLikeAttribute' could not be found (are you missing a using directive or an assembly reference?) [D:\j\workspace\windows-TGrou---0d2c9ac4\src\System.Runtime\tests\System.Runtime.Tests.csproj]
System\Runtime\CompilerServices\AttributesTests.cs(181,17): error CS0246: The type or namespace name 'IsReadOnlyAttribute' could not be found (are you missing a using directive or an assembly reference?) [D:\j\workspace\windows-TGrou---0d2c9ac4\src\System.Runtime\tests\System.Runtime.Tests.csproj]
    0 Warning(s)
    2 Error(s)
```

**Pull request merged**
