### PR TITLE
Merging master -> dev/api branch

### PR DESCRIPTION
**Pull request by joperezr**
Merging master into dev/api branch.

@weshaggard @danmosemsft @stephentoub

### CODE REVIEW

**Comment by stephentoub** [comment]
Were the only conflicts you had to handle in the project.json files?

**Comment by joperezr** [comment]
No, the json file changes where after resolving the conflicts, for some reason there is no easy way to take a look only at the merge conflicts here, but if you pull my branch and check commit 9c80fc6b6b80ff832a911b022d6e1b88fa62fada you can see what changed. Basically, it was System.IO.pkgproj changes, and the test project.json for System.IO and System.Runtime.Extensions. They were all expected.

**Comment by danmosemsft** [comment]
LGTM if CI passes of course.

**Comment by joperezr** [comment]
Merging after succesfull CI.

**Pull request merged**
