### PR TITLE
CA2002: Do not lock on objects with weak identity

### PR DESCRIPTION
**Pull request by zerhacken**
This commit changes 'lock (this)' usage into a lock on a private
object which only instance is knowledgeable about.

### CODE REVIEW

**Comment by stephentoub** [comment]
Thanks for the contribution, @zerhacken.  

While I agree with the goal here, I don't think it's a change we should take as is.  For PLINQ, asynchronous channels are not exposed publicly, so while it's possible that other internal code could access the lock, there's not risk that code external to PLINQ would use it, and your change results in an extra allocation per channel. Same for XHashtable, though I think there's likely less of a performance risk.  For XmlElementList, there could be performance implications to an extra allocation per list.  And since some of these types, e.g. Process, have shipped, it's theoretically possible someone could have taken a dependency on the observable behavior of the instance being used as as lock; changing what synchronization object is used internally could theoretically break someone, even though it's a poor thing to take a dependency on.

That said, I'm open to the opinions of others.

**Comment by zerhacken** [comment]
@stephentoub its sort of a dilemma, regarding theoretically breaking user code I would argue that they shouldn't have been depending on this in the first place. The performance part is of course a trade off where I lean towards avoiding using 'lock (this)' since it opens up for nastiness. I must admit I didn't test the performance implications.

Would you prefer if I purely fixed up XHashtable.cs?

**Comment by stephentoub** [comment]
@zerhacken, I would actually prefer we not make any of these changes.  

The only value to making this change to XHashtable now is to prevent possible future misuse, and we'd be doing so now at the expense of an extra object allocation per instance of XHashtable.  It just doesn't seem like a worthwhile tradeoff, especially since we haven't done any analysis to show whether there actually is a performance impact or not.  And while I don't know this for sure, I think it's relatively unlikely that we'll see masses of new code written in System.Xml.Linq that would interact with this via locking and suffer as a result.

Again, I agree with both you and CA2002 that lock(this) is a poor practice, and for any new code getting contributed, we should absolutely avoid the practice.  But for this existing code, I don't believe we have enough data to say that this is a worthwhile change, in some cases because of performance concerns and in some cases because of compat concerns.

As noted, though, I'm open to dissenting opinions from others.  Anyone else on the CoreFX team want to chime in?

**Comment by nguerrera** [comment]
I completely agree with @stephentoub for XHashtable and PLinq.

I'd be willing to consider fixing Process. I'd say the compat risk is bucket 3 ("unlikely grey area") as defined by https://github.com/dotnet/corefx/wiki/Breaking-Changes

Still, I'm not sure the risk is worth the benefit. I'd be curious to hear what @davkean thinks...

**Comment by ellismg** [comment]
One thing I'd like to understand here is if App Domains are something that .NET Core supports.  The concept of "weak identity" which this rule is trying to protect from doesn't exist in a single app domain world.

I do understand that locking on "this" (or any other object that is exposed to third parties) is dangerous because some other thread could have locked on the same thing, but CA2002 seems focused just on types that could bleed across app domain boundaries.

@stephentoub If we establish some rule where you never lock on "this" what is the guidance for cases XHashtable and others that don't want to burn another object just for locking?  Do we bless doing this as long as the objects aren't exposed to third parties?

**Comment by mikedn** [comment]
The title of this PR is actually wrong, code like the one you have in XHashtable doesn't raise C2002. In fact, `lock(this)` doesn't raise any code analysis warnings.

IMO there's no reason to avoid `lock (this)` for internal types. Even for public types this restriction is debatable, you'll only have problems if the code inside the lock calls out unknown code or takes a significant amount of time.

**Comment by stephentoub** [comment]
> The title of this PR is actually wrong, code like the one you have in XHashtable doesn't raise C2002

@mikedn is correct... I hadn't actually looked at CA2002 to see what it was.  Not only is CA2002 not about lock(this), but the types being locked on in this change don't actually have weak identity, which @ellismg also points out.

> If we establish some rule where you never lock on "this" what is the guidance for cases XHashtable and others that don't want to burn another object just for locking? Do we bless doing this as long as the objects aren't exposed to third parties?

It's difficult to have a hard-and-fast rule here, because there are often corner cases.  In general, lock(this) should be avoided.  It should be avoided in instances that are publicly exposed, as it's effectively leaking private state.  For types/instances that aren't exposed, it's still preferable not to lock(this), as you internally run the risk of unintended synchronization, but it's less of an imperative (just as code is often a bit more liberal in exposing state that should be private instead internal).  In many cases, an extra object to use as the lock doesn't matter.  For cases where it's more performance sensitive, in my experience in many cases the instance often already has some other readonly object that it can use as the syncobj; in such cases, I've taken to creating a private property named SyncObj or Gate or something like that, where the property just returns that other field, and then I put a comment on the field highlighting that it's also being used as a lock.  This has its own issues, of course, but in places where I've used it, it's struck a nice balance.  Worst case, an internal instance can just lock(this)... it's a tradeoff, but one that's appropriate in limited circumstances.

> you'll only have problems if the code inside the lock calls out unknown code or takes a significant amount of time

Which is exactly why I raised concerns about back compat with the Process change in this PR... in at least one of the cases, it's calling out to an event handler while holding the lock.

>  there's no reason to avoid lock (this) for internal types

That's fair.  But as noted above, I still believe a best practice is to avoid this by default; there are cases where it's the best option, but in general I think we should strive to avoid it, if for no other reason than defense in depth and helping to avoid accidental misuses.  For example, just because a type is internal doesn't means instances of it aren't exposed publicly, either just typed as object or typed as some base type that is public (such as in the XmlElementList example in this PR, where it's internal but its base type is public and instances of XmlElementList actually are exposed out).  The ability to publish such objects of internal types just makes the issue more subtle.

Anyway, my $.02.

**Comment by mikedn** [comment]
Ugh, I didn't pay too much attention to the Process class lock previously, I only looked at the xml stuff. What Process does is bad no matter what, even with this change deadlocks can still occur.

Assume that an application keeps some Process objects in a collection, maybe a Dictionary that associates additional data to each process object. At some point the application wants to close all processes and in doing so it locks the collection and calls Dispose on every process in the collection. Dispose will need to lock `this` (or `_lockable` in this PR) in StopWatchingForExit. This can happen while the exited event is raised on another thread with the same lock held. What happens if the application is trying to lock the process collection when processing the event? Deadlock, of course. 

It seems to me that `lock(this)` or not the `Process` class is leaking private state anyway.

To be clear, I'm not against a recommendation to avoid `lock(this)`, I usually avoid it too. But it looks like `lock(this)` is special cased when in reality it's not that special. Do you call arbitrary code with a lock held? You better know what you're doing. Do you use the same lock to control access to distinct resources? You better know what you're doing. The `Process` class is guilty of both.

**Comment by stephentoub** [comment]
> What Process does is bad no matter what, even with this change deadlocks can still occur

Yup, no question.  My point was just that code could have taken a dependency on the synchronization involved here.  You're correctly also pointing out that code today could deadlock.

> Do you call arbitrary code with a lock held? You better know what you're doing. Do you use the same lock to control access to distinct resources? You better know what you're doing.

Completely agree.

> But it looks like lock(this) is special cased when in reality it's not that special.

I think it's special simply because it's guaranteed that code outside of the class will have access to the lock, just as if a public field on the type were used as the lock instead.  Other than that, we're on the same page.

Thanks.

**Comment by stephentoub** [comment]
@zerhacken, thanks for the contribution.  Based on the discussion, I'm going to close out this PR.  We'd welcome additional PRs/issues from you in the future for anything else that you think needs to be addressed.

**Pull request closed without merging**
