### PR TITLE
Remove expression catalog tests from expressions tests

### LINKED ISSUE #7814: Remove expression catalog tests from expressions tests
There are currently many tests run from src\System.Linq.Expressions\tests\Interpreter\* that invoke expressions via both the compiler and interpreter to ensure they give the same results. The same set of expressions is also used in testing a no-op visitor.

These are very time-consuming; removing them reduces run time from around 2m 50s on my machine to around 30s.

They also give a false sense of coverage; a flaw within the expression itself would lead a correctly implemented compiler and interpreter to give the same incorrect result, so the coverage the tests lead to give a false impression of what branches are actually checked by tests.

The drop in coverage makes it not a no-brainer clear win, but I think ultimately more of a boon toward the purpose of #1198 than the decrease in running time, even if it does take a step back in the metric.

### PR DESCRIPTION
**Pull request by JonHanna**
Remove all the interpreter tests using them. Move NoOpVisitor into
HelperTypes.cs and use it where `Update()` returning the same instance
is currently tested.

Fixes #7814. Reduces test run times by over 80%, and stops coverage being
reported on code where the results aren't actually verified as being correct.

### CODE REVIEW

**Comment by JonHanna** [comment]
Test Innerloop OSX Debug Build and Test
Test Innerloop OSX Release Build and Test mx

**Comment by stephentoub** [comment]
cc: @bartdesmet, @VSadov

**Comment by JonHanna** [comment]
Test Innerloop OSX Debug Build and Test

**Comment by hughbe** [comment]
I'm definitely for this change if the tests don't really test anything - running the tests before this change was painfully long!

**Comment by JonHanna** [comment]
Well, "don't really test anything" would be an overstatement, but they definitely don't test as thoroughly as they could. Even if we ended up taking as long again, I'd much rather be more explicit in the testing, but the decrease in speed is certainly a great boon.

**Comment by hughbe** [comment]
@JonHanna I see - once they are readded is there an argument for making these tests `OuterLoop`?

**Comment by JonHanna** [comment]
Oh, I don't mean re-add the tests we have. I mean add tests covering what these cover, but more thoroughly checking the results are as expected, rather than just that the two compilation types have the same result.

**Comment by VSadov** [comment]
Considering that these test have found all the bugs they could find and if any new changes are accompanied with corresponding tests it seems ok to remove these. 
These test may no longer be serving enough purpose for the 80% extra test time.

Curious by how much this would reduce code coverage. Even assuming that "coverage" does not correspond to "test" for some scenarios, it would be interesting how much of a formal reduction in CC this would do.

**Comment by stephentoub** [comment]
Test code coverage please

**Comment by stephentoub** [comment]
> Curious by how much this would reduce code coverage. Even assuming that "coverage" does not correspond to "test" for some scenarios, it would be interesting how much of a formal reduction in CC this would do.

Before the change, 79.7% line coverage and 72.7% branch coverage.
After the change, 76.8% line coverage and 69.8% branch coverage.

**Comment by stephentoub** [comment]
@VSadov, given the significant drop in execution time and the minimal drop in coverage, shall we merge?

**Comment by VSadov** [comment]
@stephentoub - yes, i think we should take the change

**Comment by VSadov** [comment]
LGTM

**Comment by JonHanna** [comment]
While I'm still being kept away from contributing here by various things, I intend to bring all of that coverage back over the next few months, with more thoroughly checked tests that don't take as long to run.

**Pull request merged**
