### PR TITLE
Fix almost all remaining test issues on Linux

### PR DESCRIPTION
**Pull request by stephentoub**
This PR gets us to an almost clean state with running our inner loop tests on Linux.  The commits in this PR address this in a variety of ways:
- Some tests found real issues in the libraries.  Those product bugs have been fixed.
- Some tests were very Win32-specific.  Those have been annotated as [PlatformSpecific].
- Some tests should eventually work on Unix but currently don't due to missing features, typically related to globalization.  Those have been annotated as [ActiveIssue].
- Some tests were mostly platform-independent but had pieces that were platform-specific; those have been modified to either not rely at all on the platform-specific piece (where it wasn't really necessary) or to use a platform-detection feature to change the behavior of the test based on the current platform on which the test is running.

With these changes, we're *almost* clean (the holdouts are the FileSystem tests).  Running this command on Linux with the tests on GitHub as of this PR:
```
./corerun xunit.console.netcore.exe *.Tests.dll -notrait category=outerloop -notrait category=nonlinuxtests
```
yields the following results
```
=== TEST EXECUTION SUMMARY ===
   Microsoft.Win32.Primitives.Tests                  Total:     1, Errors: 0, Failed:   0, Skipped: 0, Time:   0.347s
   System.Collections.Concurrent.Tests               Total:   130, Errors: 0, Failed:   0, Skipped: 0, Time:   6.777s
   System.Collections.Immutable.Tests                Total:   611, Errors: 0, Failed:   0, Skipped: 0, Time:   4.824s
   System.Collections.NonGeneric.Tests               Total:   200, Errors: 0, Failed:   0, Skipped: 0, Time:   1.514s
   System.Collections.Specialized.Tests              Total:   141, Errors: 0, Failed:   0, Skipped: 0, Time:   1.239s
   System.Collections.Tests                          Total:  1283, Errors: 0, Failed:   0, Skipped: 0, Time:  44.889s
   System.ComponentModel.Annotations.Tests           Total:   272, Errors: 0, Failed:   0, Skipped: 0, Time:   1.088s
   System.ComponentModel.EventBasedAsync.Tests       Total:     9, Errors: 0, Failed:   0, Skipped: 0, Time:   0.465s
   System.ComponentModel.Primitives.Tests            Total:     1, Errors: 0, Failed:   0, Skipped: 0, Time:   0.007s
   System.ComponentModel.Tests                       Total:     2, Errors: 0, Failed:   0, Skipped: 0, Time:   0.007s
   System.ComponentModel.TypeConverter.Tests         Total:    97, Errors: 0, Failed:   0, Skipped: 0, Time:   0.301s
   System.Console.Tests                              Total:    27, Errors: 0, Failed:   0, Skipped: 0, Time:   0.212s
   System.Diagnostics.Debug.Tests                    Total:    17, Errors: 0, Failed:   0, Skipped: 0, Time:   0.104s
   System.Diagnostics.FileVersionInfo.Tests          Total:     1, Errors: 0, Failed:   0, Skipped: 0, Time:   0.053s
   System.Diagnostics.Process.Tests                  Total:    34, Errors: 0, Failed:   0, Skipped: 0, Time:   0.138s
   System.Diagnostics.TextWriterTraceListener.Tests  Total:    11, Errors: 0, Failed:   0, Skipped: 0, Time:   0.173s
   System.Diagnostics.TraceSource.Tests              Total:   246, Errors: 0, Failed:   0, Skipped: 0, Time:   0.813s
   System.Globalization.Extensions.Tests             Total:     1, Errors: 0, Failed:   0, Skipped: 0, Time:   0.002s
   System.IO.FileSystem.DriveInfo.Tests              Total:     4, Errors: 0, Failed:   0, Skipped: 0, Time:   0.096s
   System.IO.FileSystem.Primitives.Tests             Total:     4, Errors: 0, Failed:   0, Skipped: 0, Time:   0.007s
   System.IO.FileSystem.Tests                        Total:   560, Errors: 0, Failed: 110, Skipped: 0, Time:   3.595s
   System.IO.FileSystem.Watcher.Tests                Total:    45, Errors: 0, Failed:   0, Skipped: 0, Time:   3.857s
   System.IO.MemoryMappedFiles.Tests                 Total:     6, Errors: 0, Failed:   0, Skipped: 0, Time:   0.473s
   System.IO.MemoryMappedViewAccessor.Tests          Total:     5, Errors: 0, Failed:   0, Skipped: 0, Time:   0.334s
   System.IO.MemoryMappedViewStream.Tests            Total:     5, Errors: 0, Failed:   0, Skipped: 0, Time:   0.183s
   System.IO.Pipes.Tests                             Total:     8, Errors: 0, Failed:   0, Skipped: 0, Time:   0.119s
   System.IO.UnmanagedMemoryStream.Tests             Total:    23, Errors: 0, Failed:   0, Skipped: 0, Time:   0.153s
   System.Linq.Expressions.Tests                     Total:  4354, Errors: 0, Failed:   0, Skipped: 7, Time:  49.661s
   System.Linq.Parallel.Tests                        Total:   124, Errors: 0, Failed:   0, Skipped: 0, Time:  30.690s
   System.Linq.Queryable.Tests                       Total:   123, Errors: 0, Failed:   0, Skipped: 0, Time:   0.657s
   System.Linq.Tests                                 Total:    13, Errors: 0, Failed:   0, Skipped: 0, Time:   0.237s
   System.Numerics.Vectors.Tests                     Total:  1040, Errors: 0, Failed:   0, Skipped: 0, Time:  12.112s
   System.ObjectModel.Tests                          Total:    56, Errors: 0, Failed:   0, Skipped: 0, Time:   0.241s
   System.Reflection.Metadata.Tests                  Total:    94, Errors: 0, Failed:   0, Skipped: 0, Time:   1.989s
   System.Resources.ResourceWriter.Tests             Total:     7, Errors: 0, Failed:   0, Skipped: 0, Time:   0.048s
   System.Runtime.Extensions.Tests                   Total:   433, Errors: 0, Failed:   0, Skipped: 0, Time:   0.865s
   System.Runtime.Numerics.Tests                     Total:   253, Errors: 0, Failed:   0, Skipped: 0, Time:  17.109s
   System.Runtime.Serialization.Json.Tests           Total:    69, Errors: 0, Failed:   0, Skipped: 0, Time:   1.077s
   System.Runtime.Serialization.Xml.Tests            Total:    93, Errors: 0, Failed:   0, Skipped: 0, Time:   1.609s
   System.Runtime.Tests                              Total:   648, Errors: 0, Failed:   0, Skipped: 0, Time:   2.816s
   System.Text.Encoding.CodePages.Tests              Total:     9, Errors: 0, Failed:   0, Skipped: 0, Time:   0.314s
   System.Text.RegularExpressions.Tests              Total:    31, Errors: 0, Failed:   0, Skipped: 0, Time:   0.301s
   System.Threading.Tasks.Dataflow.Tests             Total:   282, Errors: 0, Failed:   0, Skipped: 0, Time:  11.671s
   System.Threading.Tasks.Parallel.Tests             Total:   125, Errors: 0, Failed:   0, Skipped: 0, Time:  13.874s
   System.Xml.RW.XmlReader.Read.Tests                Total:   667, Errors: 0, Failed:   0, Skipped: 0, Time:   0.605s
   System.Xml.RW.XmlSystemPathResolver.Tests         Total:     4, Errors: 0, Failed:   0, Skipped: 0, Time:   0.013s
   System.Xml.RW.XmlWriter.Tests                     Total:     5, Errors: 0, Failed:   0, Skipped: 0, Time:   0.058s
   System.Xml.XDocument.Axes.Tests                   Total:    35, Errors: 0, Failed:   0, Skipped: 0, Time:   0.166s
   System.Xml.XPath.Tests                            Total:  1447, Errors: 0, Failed:   0, Skipped: 0, Time:   3.263s
   System.Xml.XPath.XDocument.Tests                  Total:  1447, Errors: 0, Failed:   0, Skipped: 0, Time:  11.608s
   System.Xml.XPath.XmlDocument.Tests                Total:  1447, Errors: 0, Failed:   0, Skipped: 0, Time:   3.738s
   System.Xml.XmlDocument.Tests                      Total:   527, Errors: 0, Failed:   0, Skipped: 0, Time:   0.620s
   System.Xml.XmlSerializer.Tests                    Total:    58, Errors: 0, Failed:   0, Skipped: 0, Time:   1.705s
                                                            -----          -          ---           -        --------
                                               GRAND TOTAL: 17135          0          110           7        238.817s (262.083s)
```

Note that this does not include any changes for System.Dynamics.Tests.dll, for which tests are causing the runtime to assert, nor of course does it include tests libraries that are Win32-specific (e.g. Microsoft.Win32.Registry).

I will follow this up with fixes for the FileSystem tests (and any product fixes found as a result).

### CODE REVIEW

**Comment by stephentoub** [comment]
cc: @ellismg, @Priya91, @sokket

**Comment by stephentoub** [comment]
@dotnet-bot test this please

**Comment by stephentoub** [comment]
@mmitche, once this gets checked in, you should be able to enable our tests in the CI system for Linux for all inner loop tests but System.IO.FileSystem.Tests.dll and System.Dynamic.Runtime.Tests.dll.

**Comment by akoeplinger** [comment]
Congrats on the progress! :sparkles:

**Comment by stephentoub** [comment]
Thanks, @akoeplinger  :smile:

**Comment by krwq** [comment]
Looks good! :+1:  Really good progress, Thanks!

**Comment by sokket** [comment]
Looks good! Do the tests that are marked for OSX run and pass there as well? Or are they ones that are expected to pass but we still have work to get them running and passing on OSX?

**Comment by stephentoub** [comment]
@sokket, in most cases where you see PlatformID.OSX it's because the tests are being temporarily disabled there rather than enabled there, and in such cases I did so because I expect they'll fail on any non-Windows system.  That said, we'll want to revisit these when we do a pass for Mac once we're clean on Linux, as I was in a Linux mindset while doing this, and it's possible where we have custom OSX implementations I may have been overly cautious.

**Comment by sokket** [comment]
Ah my mistake! Cool, sounds good to me :)

**Comment by stephentoub** [comment]
Thanks, all.  I'm going to go ahead and merge this.  I'll happily address any further feedback in subsequent PRs.

**Pull request merged**
