### PR TITLE
Update coding style to discuss order of modifiers

### PR DESCRIPTION
**Pull request by stephentoub**
Fixes https://github.com/dotnet/corefx/issues/5620#event-523062924
cc: @Davidsh, @NickCraver, @ellismg

### CODE REVIEW

**Comment by NickCraver** [comment]
LGTM

**Comment by bartonjs** [comment]
LGTM.

**Comment by davidsh** [comment]
cc: @CIPop

**Comment by davidsh** [comment]
LGTM

**Comment by weshaggard** [comment]
LGTM

**Pull request merged**
