### PR TITLE
Allow NetSecurityNative to use heimdal libraries

### LINKED ISSUE #8263: Fix gssapi header configuration work to pick heimdal libraries
Today, on Unix platforms, the [native layer of NegotiateStream](https://github.com/dotnet/corefx/blob/master/src/Native/System.Net.Security.Native/pal_gssapi.cpp#L9) class looks for the presence of either ```Gss.h``` or some mit-krb5 specific headers. 
This approach works for OSX and Linux. OSX has ```Gss.h``` built-in and most flavors of linux have mit-krb5 headers available.

This is a problem for other platforms where heimdal libraries are available OOB.
CF: #7813

### PR DESCRIPTION
**Pull request by kapilash**
This PR introduces a change in the build configuration to allow using heimdal headers and libraries via CMake option ```HeimdalGssApi```.

The following will make the corefx build system to look for Heimdal specific libraries

    ./build.sh cmakeargs -DHeimdalGssApi=ON

This is to fix #8263

### CODE REVIEW

**Comment by krytarowski** [comment]
It worked for me on NetBSD!

**Comment by stephentoub** [comment]
LGTM

**Comment by stephentoub** [comment]
@kapilash, the title of the PR says "Do Not Merge".  Are you still working on it?

**Comment by kapilash** [comment]
Thanks for validating @krytarowski

**Pull request merged**
