### PR TITLE
Fixed netfx System.Configuration.ConfigurationManager.Tests on non English Windows

### PR DESCRIPTION
**Pull request by AlexRadch**
Fixed netfx System.Configuration.ConfigurationManager.Tests on non English Windows
```
             MonoTests.System.Configuration.ConfigurationErrorsExceptionTest.Constructor1 [FAIL]
               #2:Выдано исключение типа "System.Configuration.ConfigurationErrorsException".
               Expected: True
               Actual:   False
               Stack Trace:
                    в Xunit.Assert.True(Nullable`1 condition, String userMessage) в C:\BuildAgent\work\cb37e9acf085d108\src\xunit.assert\Asserts\BooleanAsserts.cs:строка 90
                    в MonoTests.System.Configuration.ConfigurationErrorsExceptionTest.Constructor1()
             System.ConfigurationTests.TimeSpanValidatorAttributeTests.MaxValueString_TooBig [FAIL]
               Assert.Equal() Failure
                          (pos 0)
               Expected: The upper range limit value must be great···
               Actual:   Значение верхнего предела диапазона должн···
                          (pos 0)
               Stack Trace:
                    в Xunit.Assert.Equal(String expected, String actual, Boolean ignoreCase, Boolean ignoreLineEndingDifferences, Boolean ignoreWhiteSpaceDifferences) в C:\BuildAgent\work\cb37e9acf085d108\src\xunit.assert\Asserts\StringAsserts.cs:строка 239
                    в Xunit.Assert.Equal(String expected, String actual) в C:\BuildAgent\work\cb37e9acf085d108\src\xunit.assert\Asserts\StringAsserts.cs:строка 170
                    в System.ConfigurationTests.TimeSpanValidatorAttributeTests.MaxValueString_TooBig()
             System.ConfigurationTests.TimeSpanValidatorAttributeTests.MinValueString_TooSmall [FAIL]
               Assert.Equal() Failure
                          (pos 0)
               Expected: The upper range limit value must be great···
               Actual:   Значение верхнего предела диапазона должн···
                          (pos 0)
               Stack Trace:
                    в Xunit.Assert.Equal(String expected, String actual, Boolean ignoreCase, Boolean ignoreLineEndingDifferences, Boolean ignoreWhiteSpaceDifferences) в C:\BuildAgent\work\cb37e9acf085d108\src\xunit.assert\Asserts\StringAsserts.cs:строка 239
                    в Xunit.Assert.Equal(String expected, String actual) в C:\BuildAgent\work\cb37e9acf085d108\src\xunit.assert\Asserts\StringAsserts.cs:строка 170
                    в System.ConfigurationTests.TimeSpanValidatorAttributeTests.MinValueString_TooSmall()
```
See https://github.com/dotnet/corefx/issues/28136 also

### CODE REVIEW

**Comment by AlexRadch** [comment]
@dotnet-bot test OSX x64 Debug Build

**Comment by AlexRadch** [comment]
@dotnet-bot test

**Comment by danmosemsft** [comment]
Seems a pity that non Netfx runs have to have the overhead of Remote invoke. Hmm

**Comment by AlexRadch** [comment]
> Seems a pity that non Netfx runs have to have the overhead of Remote invoke. Hmm

What kind optimizations we  need?

**Comment by AlexRadch** [comment]
@dotnet-bot test Linux x64 Release Build

**Comment by AlexRadch** [comment]
@dotnet-bot test OSX x64 Debug Build

**Comment by AlexRadch** [comment]
@dotnet-bot test Windows x86 Release Build

**Comment by AlexRadch** [comment]
@dotnet-bot test OSX x64 Debug Build

**Pull request merged**
