### PR TITLE
Condition imports so that users get the right message to run init-tools before building

### PR DESCRIPTION
**Pull request by joperezr**
Thanks for reporting this issue @bdenison99! With this PR you will get the right error message saying that you need to run init-tools before building an individual project.

cc: @weshaggard @maririos @bdenison99

fixes: #8070

### CODE REVIEW

**Comment by bdenison99** [comment]
Thank you!

**Comment by maririos** [comment]
LGTM

**Comment by joperezr** [comment]
@dotnet-bot test Innerloop OSX Debug Build and Test please

**Comment by weshaggard** [comment]
Do we have any other clever ways to do this without conditional imports? I only worry that we will just keep regressing this scenario overtime. 

@bdenison99 can you elaborate on how you were building? You must not have called build.cmd.

**Comment by mellinoe** [comment]
You get the error message if you clone the repo and open a solution without running init-tools.cmd, or clean your repository and do the same. Without the error message about running init-tools, it's kind of confusing as to why opening the solution file wouldn't just work.

> Do we have any other clever ways to do this without conditional imports? I only worry that we will just keep regressing this scenario overtime.

Perhaps a better solution (for the future, not necessarily now) would be to have a single "entry-point" target for buildtools, and the rest are imported transitively from that? Obviously still not foolproof, but it would probably be easier to ensure that we only ever import the "entry-point" from corefx and no others.

**Comment by weshaggard** [comment]
>Perhaps a better solution (for the future, not necessarily now) would be to have a single "entry-point" target for buildtools, and the rest are imported transitively from that? Obviously still not foolproof, but it would probably be easier to ensure that we only ever import the "entry-point" from corefx and no others.

I think we should keep the entry points minimal but I don't think we can keep it to just 1 because of ordering issues. We will likely need to have 1 per targets/props file that remains in the repo itself. 

By the way I'm not against this and I agree the experience is better I was just trying to understand if we have other options.

**Comment by joperezr** [comment]
Since the error happens on load, I'm not sure on how to get a clever way of fixing this other than minimizing the entry points of buildtools.

**Comment by weshaggard** [comment]
LGTM

**Pull request merged**
