### PR TITLE
Merge branch master -> dev/api

### PR DESCRIPTION
**Pull request by joperezr**
cc: @weshaggard @stephentoub @danmosemsft 

This PR merges branch master into dev/api. There were a bunch of changes required in order to get a succesfull build post-merge because of the changes that were made into dev/xml branch and were incorporated into dev/api. All of these set of required changes are in f03238e.

Ideally we would like to merge this as soon as possible, as any additional changes that are done to dev/api will cause merge conflicts with this PR, so please try not to merge current PRs into dev/api until this one is merged.

This will also enable us to test netcoreapp1.1 new apis in the dev/api branch.

### CODE REVIEW

**Comment by stephentoub** [comment]
Thanks for doing this, Jose.  I skimmed through the last commit; looks fine to me.

**Comment by stephentoub** [comment]
The CentOS runs both failed due to the following error while running the 'System.Runtime.Serialization.Json.Tests tests:
```
  System.IO.FileLoadException: Could not load file or assembly 'System.Runtime, Version=4.2.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
```

**Comment by weshaggard** [comment]
LGTM once CI passes.

Those test failures are likely showing only on CentOS because we run test with local built libraries on that platform. Which usually indicates some assembly versioning between the packages and live builds disagreeing.

**Comment by joperezr** [comment]
Looking into the CI failures...

**Pull request merged**
