### PR TITLE
Updating uap and uapaot baseline files

### PR DESCRIPTION
**Pull request by joperezr**
FYI: @weshaggard @danmosemsft @joshfree 

Looks like the change on the version of the AccessControl is because our mscorlib facade depends on that version now, which is generated by GenFacades. I didn't dig deep into what triggered this change, but once I know more I'll log an issue for that.

### CODE REVIEW

**Comment by danmosemsft** [comment]
Was it https://github.com/dotnet/corefx/pull/17363 ? 

Is it a problem that it says it can't find the assembly?

**Comment by joperezr** [comment]
>Is it a problem that it says it can't find the assembly?

I believe that the change you pointed out is what caused it, which I guess it's expected then. Yeah it can't find it but it couldn't find it before either, so it just updated the assembly version it was looking for which is why I noticed it.

**Comment by weshaggard** [comment]
Yes the version number change was intentional for the shims. It shouldn't be a problem here. As you say the real trouble is that AccessControl is referenced at all by this shim when building it for uap. It might be worth looking at that to make sure it is correct.

**Comment by joperezr** [comment]
> It might be worth looking at that to make sure it is correct

That will be fixed. Today we need it for DirectoryServices and DyrectoryServices.AccountManagement but that dependency will be broken in the future

**Pull request merged**
