### PR TITLE
Disabled Sgen Tests.

### PR DESCRIPTION
**Pull request by shmao**
The Sgen tests failed on CI occasionally. Disabled the tests for now to unblock CI.

Fix https://github.com/dotnet/corefx/issues/23425

/cc: @huanwu

### CODE REVIEW

**Comment by stephentoub** [comment]
Thanks, @shmao

**Comment by shmao** [comment]
OSX leg failed on System.Net.HttpListener.Tests. 

> 12:45:30 /Users/dotnet-bot/j/workspace/dotnet_corefx/master/osx-TGroup_netcoreapp+CGroup_Debug+AGroup_x64+TestOuter_false_prtest/Tools/tests.targets(453,5): error : One or more tests failed while running tests from '**System.Net.HttpListener.Tests**' please check /Users/dotnet-bot/j/workspace/dotnet_corefx/master/osx-TGroup_netcoreapp+CGroup_Debug+AGroup_x64+TestOuter_false_prtest/bin/OSX.AnyCPU.Debug/System.Net.HttpListener.Tests/netstandard/testResults.xml for details! [/Users/dotnet-bot/j/workspace/dotnet_corefx/master/osx-TGroup_netcoreapp+CGroup_Debug+AGroup_x64+TestOuter_false_prtest/src/System.Net.HttpListener/tests/System.Net.HttpListener.Tests.csproj]

**Comment by shmao** [comment]
@dotnet-bot test OSX x64 Debug Build

**Comment by danmosemsft** [comment]
That is https://github.com/dotnet/corefx/issues/23427. I'm going to merge this, as it's causing issues to others.

**Pull request merged**
