### PR TITLE
[ARM/Linux/CI] Fix arm32 build break

### PR DESCRIPTION
**Pull request by wateret**
Related Issue: #15215

### CODE REVIEW

**Comment by wateret** [comment]
@dotnet-bot help

**Comment by wateret** [comment]
@dotnet-bot test innerloop linuxarmemulator SoftFP Debug

**Comment by wateret** [comment]
cc: @hseok-oh

**Comment by hseok-oh** [comment]
@wateret We must fix CoreCLR test script (tests/runtests.sh) because native bin directory changed from `Linux.armel.<configure>/Native` to `Linux.armel.<configure>/native`
(fix from `$coreFxNativeBinDir/Native/` to `$coreFxNativeBinDir/native/`)

**Comment by hseok-oh** [comment]
Building `CoreFx.Tools` before calling `build-managed.sh` is removed by #15341.

**Comment by wateret** [comment]
@dotnet-bot test innerloop linuxarmemulator SoftFP Debug

**Comment by wateret** [comment]
@dotnet-bot test innerloop linuxarmemulator SoftFP Debug
@dotnet-bot test innerloop linuxarmemulator SoftFP Release

**Comment by wateret** [comment]
@mellinoe Please take a look.

**Comment by mellinoe** [comment]
LGTM.

**Pull request merged**
