### PR TITLE
Update BuildTools version to 00420-01

### PR DESCRIPTION
**Pull request by weshaggard**
Need fix https://github.com/dotnet/buildtools/pull/737.

### CODE REVIEW

**Comment by ellismg** [comment]
@dotnet-bot test Innerloop Windows_NT Release Build and Test please (EventListener known issue)

**Comment by weshaggard** [comment]
@dotnet-bot test Innerloop OSX Release Build and Test
@dotnet-bot test Innerloop Windows_NT Release Build and Test

**Comment by stephentoub** [comment]
LGTM

**Comment by weshaggard** [comment]
the OSX and Windows_NT Release legs seem to be getting stuck in infrastructure issues. I don't believe my change should impact them so I'm going to merge. I will watch the outer CI builds.

**Pull request merged**
