### PR TITLE
Update packages23908

### PR DESCRIPTION
**Pull request by ericstj**
This also contains the fix from https://github.com/dotnet/corefx/pull/6747 which was required for a successful build.

### CODE REVIEW

**Comment by ericstj** [comment]
Rebased out https://github.com/dotnet/corefx/pull/6747 since it was merged.

**Comment by stephentoub** [comment]
LGTM

**Comment by ericstj** [comment]
Thanks.

**Comment by ericstj** [comment]
Fixes dotnet#6718

**Pull request merged**
