### PR TITLE
Upgrade package versions to rc3-23901

### PR DESCRIPTION
**Pull request by stephentoub**

### CODE REVIEW

**Comment by stephentoub** [comment]
Test Innerloop Ubuntu Debug Build and Test please

**Comment by stephentoub** [comment]
Test Innerloop Ubuntu Debug Build and Test please

**Comment by dagood** [comment]
@dotnet-bot test Innerloop OSX Debug Build and Test please

`git bisect` points to this as being the merged commit that caused https://github.com/dotnet/corefx/issues/6760, but I have a theory why this got through CI before:

An ongoing problem with upgrading packages is that the major.minor.patch version may go out of sync when the prerelease specifier is updated. This happens when the builds go from `4.0.0-rc3-01` to, say, `4.1.0-rc3-02`. But just running `UpdateInvalidPackageVersions` changes `4.0.0-rc3-01` to `4.0.0-rc3-02`. Then, since `4.0.0-rc3-02` doesn't exist, NuGet tries to find a match using `4.0.0-rc3-02` as the "least" version. This makes the build dependent on which packages are available on the source feed, which means that builds can break without a pull request being involved.

There are 39 errors of this type in corefx right now, according to a rough tool I made that checks the lockfiles to see what's restored vs. requested. I have my doubts this is a full explanation because the list I'm seeing doesn't match with the list of restore errors, but it's the best possibility I see right now. If CI turns red then that's at least evidence that the environment does affect restore errors. (Unless CI tries to merge... the last build 404s (http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/osx_debug_prtest/1987/) so I can't directly re-run it.)

I think I should make getting the lockfile validation tool into buildtools a higher priority. Even if this error isn't caused by the package restore issue I'm describing, it's a big issue for build repro and stability.

/cc @ericstj

**Comment by dagood** [comment]
@dotnet-bot retest Innerloop OSX Debug Build and Test please

**Pull request merged**
