### PR TITLE
Add SystemNative_ThreadInterruptionRequested() to all `EINTR` loops.

### PR DESCRIPTION
**Pull request by baulig**
In Mono, we need a way of interrupting `errno == EINTR` loops on thread abort and runtime shutdown.  We could either break all those loops and always return to managed on `EINTR` - or call a special function that will check whether it is safe to loop.

This should fix the problem outlined in https://github.com/mono/mono/issues/14737.

### CODE REVIEW

**Comment by jkotas** [comment]
This should not be needed in the .NET 5 Mono that is unified with .NET Core. .NET Core does not support Thread.Abort or appdomain unloading during shutdown, so .NET 5 Mono does not need to support that either. 

Can you make this change in the legacy Mono code base only?

**Comment by jkotas** [comment]
> We are currently investigating whether or not we might replace the Socket code in the legacy Mono code base with the one from CoreFX

The CoreFX code is not robust against thread aborts and appdomain unloads. If you are going to use the CoreFX code for legacy Mono and you need it to be robust against thread aborts and appdomain unloads, you will need fixes in many more places than this. Number of those fixes will be very intrusive and it would not be acceptable to upstream them back to CoreFX.

**Comment by davidsh** [comment]
Based on the comments above, shouldn't this PR be closed?

**Comment by karelz** [comment]
@baulig are you ok with closing?

**Comment by stephentoub** [comment]
Closing per the discussion.  Thanks.

**Pull request closed without merging**
