### PR TITLE
Bump buildtools version

### PR DESCRIPTION
**Pull request by mmitche**
Pulls in newer version which references newer version of xunit (containing fixes for Linux execution)

@stephentoub

### CODE REVIEW

**Comment by stephentoub** [comment]
LGTM

**Comment by eatdrinksleepcode** [comment]
See my note on dotnet/#116 about incremental builds getting slower due to the diagnostic msbuild output. My intent was to lower the logging level to the log file and/or make it configurable before ingesting that change.

**Comment by mmitche** [comment]
@eatdrinksleepcode Is that the right link? I'm not seeing your note.

**Comment by eatdrinksleepcode** [comment]
Whoops, should be dotnet/buildtools#116 (I think, on my phone so I don't have preview).

**Comment by weshaggard** [comment]
@eatdrinksleepcode that can still be done after this update, as it isn't making anything worse. It is worth opening an in CoreFX to discuss how we want to go about that.

**Comment by eatdrinksleepcode** [comment]
@weshaggard That's the tricky thing though: it actually *does* make it worse, for reasons I don't understand. I will file an issue describing the problem.

**Pull request merged**
