### PR TITLE
Fix tests to catch exceptions from CanCreateSymbolicLinks

### PR DESCRIPTION
**Pull request by stephentoub**
It's failing on some platforms.
cc: @tijoytom, @danmosemsft

### CODE REVIEW

**Comment by danmosemsft** [comment]
If this if going to cause tests to skip (because this returns false) that ought to run , we should have an issue to track making sure they do run before we ship.

Lgtm

**Comment by stephentoub** [comment]
> we should have an issue to track making sure they do run before we ship.

That's why I included the relevant issue number in the comment :)

**Comment by stephentoub** [comment]
@mmitche, can you tell why this failed?
https://ci3.dot.net/job/dotnet_corefx/job/master/job/portable-linux-Config_Release+OuterLoop_false_prtest/364/

**Comment by mmitche** [comment]
@stephentoub I can't....huh...

@dotnet-bot test Portable Linux x64 Release Build

**Pull request merged**
