### PR TITLE
Pick up newer version of microsoft.xunit.runner.uwp

### PR DESCRIPTION
**Pull request by MattGal**
@davidsh  this is what I was talking about.  

@crummel 
I'm not totally sure how this works currently as I don't always get it copied into my test execution folder, can you comment how these support files get copied in with the test?

### CODE REVIEW

**Comment by stephentoub** [comment]
Errors:
```
Running: D:\j\workspace\windows_nt_de---4526f5ff\Tools\msbuild.cmd /nologo /verbosity:minimal /clp:Summary /maxcpucount /nodeReuse:false /l:BinClashLogger,Tools\net45\Microsoft.DotNet.Build.Tasks.dll;LogFile=binclash.log /p:OSGroup=Windows_NT /p:TargetOS=Windows_NT /p:ConfigurationGroup=Debug  /flp:v=normal  /flp2:warningsonly;logfile=msbuild.wrn  /flp3:errorsonly;logfile=msbuild.err  /p:WithoutCategories=IgnoreForCI
  [12:18:25.21] Verifying all auto-upgradeable dependencies...
D:\j\workspace\windows_nt_de---4526f5ff\Tools\VersionTools.targets(47,5): error : Dependency verification errors detected. To automatically fix based on dependency rules, run the msbuild target 'UpdateDependencies' [D:\j\workspace\windows_nt_de---4526f5ff\build.proj]
D:\j\workspace\windows_nt_de---4526f5ff\Tools\VersionTools.targets(47,5): error : Dependencies invalid: In 'D:\j\workspace\windows_nt_de---4526f5ff\src\Common\test-runtime\project.json', 'microsoft.xunit.runner.uwp 1.0.3-prerelease-00807-03' must be '1.0.3-prerelease-00614-01' (uwpRunnerVersion) [D:\j\workspace\windows_nt_de---4526f5ff\build.proj]

D:\j\workspace\windows_nt_de---4526f5ff\Tools\VersionTools.targets(47,5): error : Dependency verification errors detected. To automatically fix based on dependency rules, run the msbuild target 'UpdateDependencies' [D:\j\workspace\windows_nt_de---4526f5ff\build.proj]
D:\j\workspace\windows_nt_de---4526f5ff\Tools\VersionTools.targets(47,5): error : Dependencies invalid: In 'D:\j\workspace\windows_nt_de---4526f5ff\src\Common\test-runtime\project.json', 'microsoft.xunit.runner.uwp 1.0.3-prerelease-00807-03' must be '1.0.3-prerelease-00614-01' (uwpRunnerVersion) [D:\j\workspace\windows_nt_de---4526f5ff\build.proj]
```

**Comment by MattGal** [comment]
@stephentoub  oddly I don't hit that but should be an easy fix.

**Comment by stephentoub** [comment]
Thanks, @MattGal!

**Comment by MattGal** [comment]
I learned one more thing from chatting with @crummel , which is that if you want the test to not cause msbuild errors (via its exit code, after "successfully" running tests), you need to not have your developer command prompt running as Admin.

**Comment by davidsh** [comment]
>I learned one more thing from chatting with @crummel , which is that if you want the test to not cause msbuild errors (via its exit code, after "successfully" running tests), you need to not have your developer command prompt running as Admin.

I'm not running elevated and yet I still get "Build Failed", for example, even though I ran 26 test cases all successfully.

**Comment by davidsh** [comment]
```
  Activating: 83d69682-e725-49c7-9ca1-c1cfe634ee29_72dnfjthn8s16!App
  UWP Install HRESULT: 0
  Running XunitUwpRunner in process 5740 at 9/7/2016 7:52:16 PM -07:00
  Finished waiting for 5740 at 9/7/2016 7:52:19 PM -07:00, clean exit: True
  Copying C:\Users\dshulman\AppData\Local\Packages\83d69682-e725-49c7-9ca1-c1cfe634ee29_72dnfjthn8s16\LocalState\testResults.xml to test directory
  === TEST EXECUTION SUMMARY ===
  name="System.Net.Http.Functional.Tests.dll" total="30" errors="0" failed="0" skipped="0" time="0.443"
  Finished running tests. passed="30"
EXEC : warning LOG:  [s:\GitHub\corefx\src\System.Net.Http\tests\FunctionalTests\System.Net.Http.Functional.Tests.csproj]
  The previous error was converted to a warning because the task was called with ContinueOnError=true.
  Args: System.String[]
  testCasesToRun: 26
  finished running tests

  Cleaning up...
  Finished running tests.  End time=19:52:20.26, Exit code = 0
s:\GitHub\corefx\Tools\tests.targets(261,5): warning MSB3073: The command "s:\GitHub\corefx\bin/tests/Windows_NT.AnyCPU.Debug/System.Net.Http.Functional.Tests/
netcore50/RunTests.cmd s:\GitHub\corefx\packages/" exited with code -1. [s:\GitHub\corefx\src\System.Net.Http\tests\FunctionalTests\System.Net.Http.Functional.
Tests.csproj]
  The previous error was converted to a warning because the task was called with ContinueOnError=true.
  Build continuing because "ContinueOnError" on the task "Exec" is set to "true".
s:\GitHub\corefx\Tools\tests.targets(270,5): error : One or more tests failed while running tests from 'System.Net.Http.Functional.Tests' please check log for
details! [s:\GitHub\corefx\src\System.Net.Http\tests\FunctionalTests\System.Net.Http.Functional.Tests.csproj]
Done Building Project "s:\GitHub\corefx\src\System.Net.Http\tests\FunctionalTests\System.Net.Http.Functional.Tests.csproj" (BuildAndTest target(s)) -- FAILED.


Build FAILED.

"s:\GitHub\corefx\src\System.Net.Http\tests\FunctionalTests\System.Net.Http.Functional.Tests.csproj" (BuildAndTest target) (1) ->
(ResolveAssemblyReferences target) ->
  C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.Common.CurrentVersion.targets(1820,5): warning MSB3277: Found conflicts between different versions of the s
ame dependent assembly that could not be resolved.  These reference conflicts are listed in the build log when log verbosity is set to detailed. [s:\GitHub\cor
efx\src\System.Net.Http\tests\FunctionalTests\System.Net.Http.Functional.Tests.csproj]


"s:\GitHub\corefx\src\System.Net.Http\tests\FunctionalTests\System.Net.Http.Functional.Tests.csproj" (BuildAndTest target) (1) ->
(CopyTestToTestDirectory target) ->
  s:\GitHub\corefx\Tools\publishtest.targets(48,5): warning : Your project.json doesn't have a runtimes section. You should add '"runtimes": { "win7-x64": { }
}' to your project.json and then re-run NuGet restore. [s:\GitHub\corefx\src\System.Net.Http\tests\FunctionalTests\System.Net.Http.Functional.Tests.csproj]
  s:\GitHub\corefx\Tools\publishtest.targets(48,5): warning : Your project.json doesn't have a runtimes section. You should add '"runtimes": { "win7-x64": { }
}' to your project.json and then re-run NuGet restore. [s:\GitHub\corefx\src\System.Net.Http\tests\FunctionalTests\System.Net.Http.Functional.Tests.csproj]


"s:\GitHub\corefx\src\System.Net.Http\tests\FunctionalTests\System.Net.Http.Functional.Tests.csproj" (BuildAndTest target) (1) ->
(RunTestsForProject target) ->
  EXEC : warning LOG:  [s:\GitHub\corefx\src\System.Net.Http\tests\FunctionalTests\System.Net.Http.Functional.Tests.csproj]
  s:\GitHub\corefx\Tools\tests.targets(261,5): warning MSB3073: The command "s:\GitHub\corefx\bin/tests/Windows_NT.AnyCPU.Debug/System.Net.Http.Functional.Test
s/netcore50/RunTests.cmd s:\GitHub\corefx\packages/" exited with code -1. [s:\GitHub\corefx\src\System.Net.Http\tests\FunctionalTests\System.Net.Http.Functiona
l.Tests.csproj]


"s:\GitHub\corefx\src\System.Net.Http\tests\FunctionalTests\System.Net.Http.Functional.Tests.csproj" (BuildAndTest target) (1) ->
(RunTestsForProject target) ->
  s:\GitHub\corefx\Tools\tests.targets(270,5): error : One or more tests failed while running tests from 'System.Net.Http.Functional.Tests' please check log fo
r details! [s:\GitHub\corefx\src\System.Net.Http\tests\FunctionalTests\System.Net.Http.Functional.Tests.csproj]

    5 Warning(s)
    1 Error(s)
```

**Comment by weshaggard** [comment]
>I learned one more thing from chatting with @crummel , which is that if you want the test to not cause msbuild errors (via its exit code, after "successfully" running tests), you need to not have your developer command prompt running as Admin.

Even if that is a reason it isn't a valid reason and is just plain busted, and we need to fix it.

**Pull request merged**
