### PR TITLE
CultureInfoConverter added

### LINKED ISSUE #24755: Parse CultureInfo no longer supported in .NET Core
@viktor-morin commented on [Thu Oct 19 2017](https://github.com/dotnet/core/issues/1035)

Hi!

I reported an error using Newtonsoft.Json where I recieved that the error was in .NET Core and not Newtonsoft.Json itself. Copy paste the issue here below:

We are now changing to .NET Core and we get following error when trying to parse a following class:

`Dictionary<CultureInfo,string>`

> ArgumentException: Could not cast or convert from System.String to System.Globalization.CultureInfo.
> Newtonsoft.Json.Utilities.ConvertUtils.EnsureTypeAssignable(object value, Type initialType, Type targetType)
> JsonSerializationException: Error converting value "en-US" to type 'System.Globalization.CultureInfo'. Path 'Name.en-US', line 1, position 17.
> Newtonsoft.Json.Serialization.JsonSerializerInternalReader.EnsureType(JsonReader reader, object value, CultureInfo culture, JsonContract contract, Type targetType)
> JsonSerializationException: Could not convert string 'en-US' to dictionary key type 'System.Globalization.CultureInfo'. Create a TypeConverter to convert from the string to the key type object. Path 'Name.en-US', line 1, position 17.
> Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateDictionary(IDictionary dictionary, JsonReader reader, JsonDictionaryContract contract, JsonProperty containerProperty, string id)

This is working in .NET Framwork.

Link to original post:
[https://github.com/JamesNK/Newtonsoft.Json/issues/1457](https://github.com/JamesNK/Newtonsoft.Json/issues/1457)

[@danmosemsft edited to make link clickable]

### PR DESCRIPTION
**Pull request by Anipik**
* Culture Converter added

* space formatting

* Expected and actual argument reordered

* Removed to string

* Reference Converter and its test added

* fixing reference Converter

* Skipping test on framework

* CultureInfo added with others

* Removed Reference Connverter

Porting PR #24855 from master to release/2.0.0 branch
Fixes #24755
Related: https://github.com/JamesNK/Newtonsoft.Json/issues/1457

### CODE REVIEW

**Comment by danmosemsft** [comment]
@Anipik please roll in the test for it also.

**Comment by danmosemsft** [comment]
Also please add the link to the original issue

**Comment by Anipik** [comment]
@danmosemsft  its already in the commit.. you can see the change in the typedescriptors.tests in the commit

**Comment by danmosemsft** [comment]
@Anipik my bad - you're right.

**Pull request merged**
