### PR TITLE
[WIP] Add FastEquals extension method on EqualityComparer<T> to improve perf

### PR DESCRIPTION
**Pull request by jamesqo**
/cc @jkotas @benaadams 

This PR adds a new `ComparerUtilities` class, which adds an extension method `FastEquals` to `IEqualityComparer<T>`. `FastEquals` checks if the comparer is the default equality comparer and if `T` is a well-known type, and if so avoids a virtual method call to `Equals()`. Similarly, `ComparerUtilities.DefaultEquals()` replaces usages of `EC<T>.Default.Equals()`.

After hours of tinkering this morning, I finally got the code in `DefaultEquals` / `FastEquals` to inline without regressing the asm for any of the test cases. That is, for well-known types it folds into a single instruction, while for other types it generates the exact same code as before. So, aside from the increased JIT time, the perf is essentially free.

So far, I've modified nearly all the types in System.Collections to use this API. I also plan on doing the following before un-WIPing this PR:

- [ ] Having System.Collections.{Concurrent,Immutable} and System.Linq use the API
- [ ] Making sure there is no asm regression for desktop-- [it doesn't seem like it optimizes the `typeof` trick in generic methods](https://github.com/dotnet/coreclr/issues/13514#issuecomment-323987735)
- [ ] Adding `FastGetHashCode`, `FastCompare`
- [ ] Publishing perf measurements

### CODE REVIEW

**Comment by omariom** [comment]
Though I completely for it but [JIT can provide a universal approach](https://github.com/dotnet/coreclr/issues/6688)

**Comment by jkotas** [comment]
Doesn't this break custom comparers? Consider:

```
```
class OddEvenComparer : IEqualityComparer<int>
{
    public bool Equals(int x, int y)
    {
        return (x & 1) == (y & 1);
    }

    public int GetHashCode(int obj)
    {
        return (x & 1);
    }
}

new HashSet(OddEvenComparer())
```

**Comment by jkotas** [comment]
> Though I completely for it but JIT can provide a universal approach

This optimization is partial manual de-virtualization. It is different from the issue of equality comparer intrinsics. But still, it would be best to leave it to the JIT and runtime to figure it out, ideally in combination with tiered JITing.

**Comment by jkotas** [comment]
> inline without regressing the asm for any of the test cases.

Have you tried test cases like:

```
class FirstCharEqualityComparer : IEqualityComparer<string>
{
    public bool Equals(string x, string y)
    {
        return x[0] == y[0];
    }

    public int GetHashCode(string obj)
    {
        return obj[0];
    }
}
```

**Comment by jamesqo** [comment]
> I would expect this one to regress quite a bit.

"Quite a bit"? It's a single extra check against a static field for non-default comparers with well-known types. I doubt it will make much of a difference. I'll run perf measurements later, of course, but can you tell me why you think this extra check would have significant impact?

**Comment by jkotas** [comment]
static fields in shared generic types are not fast.

**Comment by jamesqo** [comment]
@jkotas By "shared generic types" do you mean reference types like `string`, for which generic code is shared? I thought you might be right for a second since I had only tested asm for `int`, `int?`, and `long`, all of which are value types. However, I just wrote up this program and viewed the asm:

```cs
class Program
{
    public static void Main(string[] args)
    {
        var c1 = EqualityComparer<int>.Default; // First access to init the field and prevent a call
        var c2 = EqualityComparer<string>.Default; // First access to init the field and prevent a call

        AccessIntComparer(c1);
        AccessStringComparer(c2);
    }

    [MethodImpl(MethodImplOptions.NoInlining)]
    static void AccessIntComparer(IEqualityComparer<int> comparer)
    {
        Console.WriteLine(EqualityComparer<int>.Default == comparer);
    }

    [MethodImpl(MethodImplOptions.NoInlining)]
    static void AccessStringComparer(IEqualityComparer<string> comparer)
    {
        Console.WriteLine(EqualityComparer<string>.Default == comparer);
    }
}
```

Accessing both `EC<int>.Default` and `EC<string>.Default` generate the exact same instructions, both of which seem very cheap to me:


```asm
        Console.WriteLine(EqualityComparer<int>.Default == comparer);
00007FFA6E470570  sub         rsp,28h  
00007FFA6E470574  mov         rax,2B1C0F82860h  
00007FFA6E47057E  cmp         qword ptr [rax],rcx  
00007FFA6E470581  sete        cl  
00007FFA6E470584  movzx       ecx,cl  
00007FFA6E470587  call        00007FFA6E470328  ; from Console.WriteLine
00007FFA6E47058C  nop  
00007FFA6E47058D  add         rsp,28h  
00007FFA6E470591  ret  

        Console.WriteLine(EqualityComparer<string>.Default == comparer);
00007FFA6E471E00  sub         rsp,28h  
00007FFA6E471E04  mov         rax,2B1C0F827F0h  
00007FFA6E471E0E  cmp         qword ptr [rax],rcx  
00007FFA6E471E11  sete        cl  
00007FFA6E471E14  movzx       ecx,cl  
00007FFA6E471E17  call        00007FFA6E471E60  ; from Console.WriteLine
00007FFA6E471E1C  nop  
00007FFA6E471E1D  add         rsp,28h  
00007FFA6E471E21  ret  
```

**Comment by jkotas** [comment]
The access from non-generic code has different perf characteristic than the access from generic code. You should look at the code that actually gets generated for the collection methods.

**Comment by jamesqo** [comment]
@jkotas Thank you for the advice. One solution perhaps would be to use `null` as the sentinel value for the default comparer, although that would require some more effort, as then we'd have to make sure all the `_comparer` fields get set to null and never `EqualityComparer<T>.Default` instead of the other way around.

I'm going to close this PR for now because it's WIP and I have a lot of other PRs open, which is distracting. @jkotas @omariom Thanks both of you for the useful initial feedback.

**Pull request closed without merging**
