### PR TITLE
Revisiting use of var in System.Linq.Expressions test code

### PR DESCRIPTION
**Pull request by bartdesmet**
Using explicit types where the type is not immediately obvious. Automated code rewrite using a Roslyn code fix provider.

### CODE REVIEW

**Comment by bartdesmet** [comment]
I can share the tool. I just threw it together a few weeks ago. Any preferred place to share such quick-n-dirty tools?

**Comment by karelz** [comment]
Here's our [.NET Codeformatter](https://github.com/dotnet/codeformatter) - would it fit there?
cc: @davkean @Priya91

**Comment by bartdesmet** [comment]
Thanks! Will have a look at it over the holiday season.

**Comment by Priya91** [comment]
Yeah, codeformatter is a good place to add this type of rule.

**Pull request merged**
