### PR TITLE
[release/3.0] HTTP2: Ensure we never send EndStream after RST_STREAM #39834

### LINKED ISSUE #39586: HTTP2: Hang when sending multiple requests from a HttpClient
I'm not sure what the cause of this hang is, it appears to happen at HttpClient.SendAsync when the client has made at least one previous call.

Repro:
1. `git clone https://github.com/JamesNK/grpc-dotnet.git`
2. `git checkout jamesnk/hang-multiple-calls`
3. `dotnet test test\FunctionalTests --filter Name~DuplexStream_SendToUnimplementedMethodAfterResponseReceived_Hang`

Logic in the test is like:
1. Client makes HTTP/2 duplex call to the server
2. Server immediately returns 200 and ends request.
3. Client inspects headers.
4. Client completes request stream.
5. Go to 1.

It consistently hangs making the second or third call.

```
.NET Core SDK (reflecting any global.json):
 Version:   3.0.100-preview8-013248
 Commit:    135af55c46
```

### LINKED ISSUE #39819: HTTP2: Race between response body Dispose and request body completion
Found during GRPC stress.

If the client finishes sending the request body at approximately the same time that it disposes the response body without reading to the end, then there's a race between sending EndStream for the request body and RST_STREAM caused by the dispose. If the RST_STREAM ends up getting sent first, then this is a protocol violation.

### PR DESCRIPTION
**Pull request by geoffkizer**
GRPC stress issue. Port of PR #39834.

Fixes #39586 
Fixes #39819 

There's a timing gap currently which can result in us sending EndStream on the request body after we've already sent RST_STREAM, which is not allowed.

Fix this by ensuring we never send EndStream if we've already sent RST_STREAM.

cc @danmosemsft

### CODE REVIEW

**Comment by wtgodbe** [comment]
@geoffkizer @danmosemsft is this a preview8 blocker?

**Comment by geoffkizer** [comment]
@wtgodbe I don't know what the criteria are for being a preview8 blocker.

**Comment by danmosemsft** [comment]
This can wait to Preview 9. @geoffkizer this will need to go to ask mode though, could you please fill this out in this PR? Don't need lots of detail:

#### Description
		
#### Customer Impact
		
#### Regression?
		
#### Risk

**Comment by geoffkizer** [comment]
Description
Fix a race between request body completion and response body disposal that would occasionally cause us to send EndStream after RST_STREAM, which is a protocol violation per RFC.

Customer Impact
Causes occasional failures when using GRPC, other other HTTP duplex use.

Regression?
No

Risk
Low

**Comment by leecow** [comment]
tactics approved - wait to merge for @wtgodbe go ahead.

**Comment by wtgodbe** [comment]
Branch is open, merging

**Pull request merged**
