### PR TITLE
Optimize RemoveAt() method in OrderedDictionary class

### PR DESCRIPTION
**Pull request by iSazonov**
Continue #32001 to address unresolved comment.

/cc @danmosemsft @safern 

@safern Insert() have 'index > Count' not 'index >= Count' check so I leave it as is.

### CODE REVIEW

**Comment by safern** [comment]
> @safern Insert() have 'index > Count' not 'index >= Count' check so I leave it as is.

Fair enough.

**Comment by danmosemsft** [comment]
@dotnet-bot test Packaging All Configurations x64 Debug Build  OSX x64 Debug Build

**Comment by danmosemsft** [comment]
@dotnet-bot test OSX x64 Debug Build

**Comment by safern** [comment]
All configurations is a known issue, it is going to be fixed once: https://github.com/dotnet/corefx/pull/31994 is merged

**Pull request merged**
