### PR TITLE
Dont Ignore the Arcade Cross x86 folder

### PR DESCRIPTION
**Pull request by deinok**

### CODE REVIEW

**Comment by weshaggard** [comment]
@deinok is there a reason this is interesting to you? We shouldn't be making changes to any files under eng/common as they are centrally managed in http://github.com/dotnet/arcade repo.

**Comment by deinok** [comment]
ref: https://github.com/dotnet/arcade/pull/1165

Yes, notice that inside the two `cross` folders exist the apt sources to bootstrap the crossrootfs.
Ignoring `x86/` on .gitignore causes that the sync of arcade with corefx ignore the eng/common/cross/x86

So, there are two solutions:
* Initialize by hand the eng/common/cross/x86 folder and ignore the .gitignore for just one commit.
* Set an exception in the .gitignore and wait for a resync from arcade.

I'm missing something?

**Comment by weshaggard** [comment]
The .gitignore is only interesting in cases where you want git to detect changes to files. You don't need to update the .gitignore file to have git sync down changes to those files only to pend changes. Given that we are planning to make edits to these only in arcade it makes sense to have this change in the arcade repo but I don't think it is necessary in the consuming repo's.

**Comment by weshaggard** [comment]
That being said just like I just commented in your arcade PR I don't think having the x86 or x64 entries in the .gitignore file is very interesting and we should consider removing those completely instead of adding exceptions like this.

**Comment by weshaggard** [comment]
Our current arcade update was broken for other reasons but as part of that I removed the x86 and x64 entries from the .gitignore file. See https://github.com/dotnet/corefx/pull/33135. 

Thanks @deinok for trying to help with this issue.

**Pull request closed without merging**
