### PR TITLE
Obsolete old HTTP implementation

### PR DESCRIPTION
**Pull request by xsoheilalizadeh**
As @jskeet noted in his book:
> HttpClient is in some senses the new and improved WebClient; it’s
the preferred HTTP API for .NET 4.5 onward, and it contains only asynchronous
operations.

If HttpClient is a newer and improved version of WebClient why we don't suggest to developers to use the HttpClient in summary or make them obsolete.

- [x] Codes
- [ ] Documents

## Codes
Currently, I've made HttpWebRequest and WebClient obsolete.

## Documents
In the [dotnet/docs][1] repo, we have a lot of sections that use WebClient and HttpWebRequest.
Shall I replace all of them with HttpClient? If it needs, I want to submit a PR to the docs.

cc. @karelz

[1]:https://github.com/dotnet/docs/search?p=3&q=WebClient&unscoped_q=WebClient

### CODE REVIEW

**Comment by karelz** [comment]
I am not sure we should be adding that attribute. I thought we were talking about docs clarification.
For obsoletion we have better mechanism in https://github.com/dotnet/platform-compat ... less intrusive, we just need to productize it.
cc @terrajobst @danmosemsft @stephentoub for thoughts ...

**Comment by danmosemsft** [comment]
https://github.com/dotnet/platform-compat seems the right place.

As per separate email, @Lxiamail is figuring out what to do with that tool (maybe merge with apicompat into a single offering)

**Comment by Lxiamail** [comment]
If we don't want customers to use WebClient on .NET Core anymore in any scenario, adding Obsolete attribute seems the right thing to do so that devs who use it will get warning or even an error at build time by default. Since [https://github.com/dotnet/platform-compat](https://github.com/dotnet/platform-compat) is not installed by default, people won't be able to get warning/error by default.
If we think WebClient is still okay to use, but httpClient is more recommended approach, we should flag it by [https://github.com/dotnet/platform-compat](https://github.com/dotnet/platform-compat) and add recommended changes to related APIs in [APIPort](https://github.com/microsoft/dotnet-apiport). @karelz can you come up with a text content of recommended change for WebClient APIs. I can add it to these two tools.
In addition, feel like a doc, blog or tutorial with concrete migration guidance would be very helpful. If we have such doc, we can add the doc link to both [https://github.com/dotnet/platform-compat](https://github.com/dotnet/platform-compat) and [APIPort](https://github.com/microsoft/dotnet-apiport) so that developers have more context of how to make the migration.

For longer term, we will do more functional enhancement or consolidation with these two tools, but that shouldn't block us to flag the APIs with recommended change messages today.

**Comment by stephentoub** [comment]
> adding Obsolete attribute seems the right thing to do so that devs who use it will get warning or even an error at build time by default

Which is exactly the problem we've always faced with Obsolete: a warning or an error that you get on upgrade, even if your code was working just fine, and no fine-grained way to suppress just the obsoletion of one API.

@xsoheilalizadeh, thank you for the PR and for trying to help out here.  However, the plan should be discussed and decided outside of such a PR, as it has much broader implications.  It sounds like @Lxiamail is working on it and she can follow-up with details on where such discussions will happen.

**Pull request closed without merging**
