### PR TITLE
Add support to produce WebAssembly runtime assets

### PR DESCRIPTION
**Pull request by safern**
I reverted my original PR as it conflicted with something that broke it while I merged it. I will add an extra commit to fix it here.

cc: @ericstj @ViktorHofer @jkotas @stephentoub

### CODE REVIEW

**Comment by safern** [comment]
This was the commit that broke the build: https://github.com/dotnet/corefx/commit/8bd0eb37f048375f038954fe444f7abd7b5681b6

**Comment by jkotas** [comment]
> This was the commit that broke the wasm build: 8bd0eb3

Side-effect of the build pretending that WASM is Linux ?

**Comment by safern** [comment]
> Side-effect of the build pretending that WASM is Linux ?

I don’t think so it was the native build the one that broke.

> src/Native/Unix/System.Native/pal_interfaceaddresses.c(349,21): error G4DD96399: implicit declaration of function 'ioctl' is invalid in C99 [-Werror,-Wimplicit-function-declaration]

**Comment by safern** [comment]
@wfurt I'm fixing the import for ioctl.h here to be included always here: https://github.com/dotnet/corefx/pull/42128/commits/0f4913e316de75cdf72dc8f9e50a95437409440e

**Comment by wfurt** [comment]
Thanks for fixing the ioctl error @safern. That change looks ok to me. As we talked offline, targeting Unix will need more investigation to see what actually works and what does not.

**Comment by safern** [comment]
Merging as this was already approved and @wfurt signed-off for the `ioctl` error fix.

**Pull request merged**
