### PR TITLE
Upgrade dotnet CLI version

### PR DESCRIPTION
**Pull request by dagood**
Upgrade dotnet CLI to most recent version, which includes the fix to https://github.com/NuGet/Home/issues/2102. It recently affected corefx: https://github.com/dotnet/corefx/issues/6820.

/cc @Priya91 @weshaggard @ericstj

### CODE REVIEW

**Comment by stephentoub** [comment]
LGTM

**Comment by dagood** [comment]
@dotnet-bot test outerloop osx debug

**Comment by weshaggard** [comment]
LGTM

Please make sure the TFS build correctly supports this.

**Comment by dagood** [comment]
Confirmed it works in TFS for a clean ToolRuntime init. Thanks!

The OSX outerloop failures are the same as in https://github.com/dotnet/corefx/pull/6839, so I'll merge this in.

**Pull request merged**
