### PR TITLE
Update outerloop badges to new location

### PR DESCRIPTION
**Pull request by mmitche**
PTAL @stephentoub

### CODE REVIEW

**Comment by mmitche** [comment]
Also added the win7, win8 and win10 badges.

**Comment by justinvp** [comment]
nit: The header says "Windows 10, 8, 7" but the order of the badges are 7, 8, 10. Should the order of the badges be changed to match the header, e.g. 10, 8, 7?

**Comment by stephentoub** [comment]
Nit: I'd been trying to keep things symmetrical and with an equal number of badges in each column.  But I don't have a good suggestion for how to rectify that here, and it's not a big deal.

**Comment by stephentoub** [comment]
LGTM

**Comment by mmitche** [comment]
@justinvp Dang missed that comment.  Will fix.

**Pull request merged**
