### PR TITLE
Improved readability

### PR DESCRIPTION
**Pull request by weitzhandler**
Using pattern matching

### CODE REVIEW

**Comment by karelz** [comment]
@weitzhandler thanks for your contribution!

If you're interested in further contributions, please check our [contributions docs](https://github.com/dotnet/corefx/wiki/New-contributor-Docs) (it's editable wiki, so feel free to help us improve it) - also linked from our main page.
If you want to pick good starter issues, I would suggest [label:easy](https://github.com/dotnet/corefx/labels/easy) or [up-for-grabs](https://github.com/dotnet/corefx/issues?utf8=%E2%9C%93&q=is%3Aopen%20label%3Aup-for-grabs%20-label%3Aapi-needs-work%20no%3Aassignee) in general. Overall we currently suggest contributors to help us land .NET Core 2.0 by May 10 - see #17619 for details.
If you have any questions or suggestions, please don't hesitate to ask (feel free to mention me directly). Thanks!

**Comment by karelz** [comment]
@dotnet-bot Innerloop Ubuntu14.04 Release x64 Build and Test

**Comment by karelz** [comment]
@dotnet-bot help

**Comment by karelz** [comment]
@dotnet-bot test Innerloop Ubuntu14.04 Release x64 Build and Test

**Comment by karelz** [comment]
Previous run hit unrelated issue: https://github.com/dotnet/corefx/issues/18431#issuecomment-294709768

**Comment by ViktorHofer** [comment]
@karelz I think for a code refactoring change were chances to break anything are zero we don't need the area owner approvals. I would just merge it

**Comment by karelz** [comment]
Agreed, I was waiting on the tests to pass.

**Pull request merged**
