### PR TITLE
Use C#7 is expression to remove additional cast

### PR DESCRIPTION
**Pull request by Kahbazi**

### CODE REVIEW

**Comment by ViktorHofer** [comment]
Based on @jnm2's comment let us close this for now and revisit it when C#8 is being used in corefx.

**Comment by Kahbazi** [comment]
@ViktorHofer  Can we reopen this PR since now C# 8.0 is being used?

https://github.com/dotnet/core/commit/1fdca14e41b92c32a43e34ed56d24328a74ae6de

**Comment by ViktorHofer** [comment]
Sure

**Comment by ViktorHofer** [comment]
@dotnet-bot test this please

**Comment by karelz** [comment]
The only failure is unrelated: https://mc.dot.net/#/user/Kahbazi/pr~2Fjenkins~2Fdotnet~2Fcorefx~2Fmaster~2F/test~2Ffunctional~2Fcli~2F/df49a3168009ac0a3c1b9173756283d52fdf691e/workItem/System.Runtime.Tests/analysis/xunit/System.Tests.TimeZoneInfoTests~2FTimeZoneInfo_DisplayNameStartsWithOffset

It was addressed in #34106
I think we can merge @ViktorHofer

**Comment by ViktorHofer** [comment]
No, we can't merge PRs which didn't run recently as that can break builds. We had that once in the past and I definitely don't want to see that again...

**Comment by stephentoub** [comment]
Has the originally cited issue actually been address (e.g. is the corefx repo actually building with a compiler that has the mentioned fix)?  And if yes, does this PR actually make a positive impact on the resulting IL or asm?  At the moment at least it seems to increase the size of the IL, with no discernable impact on performance.

**Comment by Kahbazi** [comment]
@stephentoub you are right using is-expression will increase the size of IL but on the other hand it will decrease the Jit Assembly and has fewer operations.

```
using System;
public class C 
{
    public void IsExpression(A a) 
    {
    	if (a is B b)
    		Console.WriteLine(b);
    }
    
    public void Cast(A a) 
    {
    	if (a is B)
    		Console.WriteLine((B)a);
    }
}

public class A {}

public class B : A {}
```

```
C.IsExpression(A)
    L0000: mov ecx, 0x1b0b176c
    L0005: call 0x73cfc540
    L000a: test eax, eax
    L000c: jz L0015
    L000e: mov ecx, eax
    L0010: call System.Console.WriteLine(System.Object)
    L0015: ret

C.Cast(A)
    L0000: push esi
    L0001: mov esi, edx
    L0003: mov edx, esi
    L0005: mov ecx, 0x1b0b176c
    L000a: call 0x73cfc540
    L000f: test eax, eax
    L0011: jz L001a
    L0013: mov ecx, esi
    L0015: call System.Console.WriteLine(System.Object)
    L001a: pop esi
    L001b: ret
```

**Comment by danmosemsft** [comment]
The generated code looks inefficient. Could you open a bug in the coreclr repo for that? In general we prefer not to work around codegen unless we have data demonstrating its perf critical and it's clear there isn't going to be a near term fix to the codegen.

**Comment by Kahbazi** [comment]
@danmosemsft  Just so the issue that I want to open is more clear to me, based on https://sharplab.io this is what happens to is-expression

**C# 8**
```
public void IsExpression(A a) 
{
    if (a is B b)
        Console.WriteLine(b);
}
```
**C#**
```
public void IsExpression(A a)
{
    B value;
    if ((value = (a as B)) != null)
    {
        Console.WriteLine(value);
    }
}
```
**IL**
```
    .method public hidebysig 
        instance void IsExpression (
            class A a
        ) cil managed 
    {
        // Method begins at RVA 0x2050
        // Code size 17 (0x11)
        .maxstack 2
        .locals init (
            [0] class B
        )

        IL_0000: ldarg.1
        IL_0001: isinst B
        IL_0006: dup
        IL_0007: stloc.0
        IL_0008: brfalse.s IL_0010

        IL_000a: ldloc.0
        IL_000b: call void [mscorlib]System.Console::WriteLine(object)

        IL_0010: ret
    } // end of method C::IsExpression
```
**JIT Asm**
```
C.IsExpression(A)
    L0000: mov ecx, 0x1b4b1784
    L0005: call 0x73cfc540
    L000a: test eax, eax
    L000c: jz L0015
    L000e: mov ecx, eax
    L0010: call System.Console.WriteLine(System.Object)
    L0015: ret
```

The generated code in which one of these steps is not inefficient? I'm guessing JIT since you've mentioned coreclr, but I just want to be sure.

**Comment by Kahbazi** [comment]
@ViktorHofer Is there anything that I should do for this PR to get merged?

**Comment by ViktorHofer** [comment]
I think @danmosemsft and @stephentoub are the right people to answer that.

**Comment by danmosemsft** [comment]
@dotnet-bot test this please 

sorry for delay. if this is green, we can merge it.

**Comment by Kahbazi** [comment]
@ViktorHofer most of the builds are green. Is it good enough for merge?

**Comment by ViktorHofer** [comment]
@dotnet-bot test this please

**Comment by ViktorHofer** [comment]
thanks for your contribution @Kahbazi

**Pull request merged**
