### PR TITLE
Fix IDbParamter.Precision for SqlClient

### LINKED ISSUE #23899: IDbDataParameter.Precision is broken for SqlClient 4.3.0
The implementations of IDbParameter.Precision and IDBParameter.Scale in System.Data.Common.DbParameter got replaced with dummy implementations by commit  7888677b3c53596085c2fa53860d9a0519eeecfd.

This demo application reproduces the problem in .NET Core 2.0 but works just fine in .NET Core 1.1. Expected output: 19; got 0.
[Program.zip](https://github.com/dotnet/corefx/files/1289338/Program.zip)

### PR DESCRIPTION
**Pull request by joshudson**
Fixes #23899

### CODE REVIEW

**Comment by corivera** [comment]
These specific changes likely aren't necessary, since Framework DbParameter has the same code and does not exhibit the same Precision problems. Looking into it.

**Comment by jhudsoncedaron** [comment]
I tracked it down by reflection. The .NET Framework version of System.Data.SqlClient.SqlParameter re-implements IDbDataParameter which is a worse way.

**Comment by corivera** [comment]
Post the comments in https://github.com/dotnet/corefx/issues/23899 to keep the discussion in one place.

**Comment by danmosemsft** [comment]
@joshudson you mention reflectoin, just in case you aren't aware, there is an online .NET Framework source browser with find refernces: http://referencesource.microsoft.com/#System.Data/System/Data/Common/DBParameter.cs,9893646b3deb0d3a

**Comment by danmosemsft** [comment]
Same for .NET Core is source.dot.net.

**Comment by karelz** [comment]
@danmosemsft I assume you marked it 2.0.x by accident as the PR is against master (2.1). If not, let's create issue for 2.0.x.

**Comment by karelz** [comment]
I updated title and description.

@corivera do you want to reject the change or push it further? What is the next step?

**Comment by jhudsoncedaron** [comment]
A more detailed analysis indicated that SqlClient is not likely to be the only broken DB client, just the only one known to us.

**Comment by corivera** [comment]
@karelz This doesn't seem like the correct change to make, since Framework uses the same code this PR is removing. This issue doesn't repro in master, so we can address it in the next servicing window.

**Pull request closed without merging**
