### PR TITLE
Update infra owners

### PR DESCRIPTION
**Pull request by ericstj**

### CODE REVIEW

**Review by maryamariyan — APPROVED** [review]

**Comment by ViktorHofer** [comment]
Duplicate https://github.com/dotnet/corefx/pull/41615 😂

**Review by Anipik — APPROVED** [review]

**Review by ViktorHofer — APPROVED** [review]

**Comment by ericstj** [comment]
> Duplicate #41615 😂

Can we merge this instead?  Discussed with @karelz about this already before proposing.

**Comment by ViktorHofer** [comment]
Sure

**Review by safern — COMMENTED** [review]
LGTM

**Pull request merged**
