### PR TITLE
Pre/PostInc/DecrementAssign tests.

### PR DESCRIPTION
**Pull request by JonHanna**
Add tests for PreDecrementAssign, PreIncrementAssign, PostDecrementAssign
& PostIncrementAssign.

Including add a couple of assertions.

### CODE REVIEW

**Comment by VSadov** [comment]
test this please

**Comment by JonHanna** [comment]
Test this please

**Comment by JonHanna** [comment]
Test Innerloop Ubuntu Debug Build and Test
Test Innerloop Ubuntu Release Build and Test

**Comment by JonHanna** [comment]
Innerloop Ubuntu Debug Build and Test

**Comment by JonHanna** [comment]
Test Innerloop Ubuntu Debug Build and Test

**Comment by VSadov** [comment]
LGTM, needs resolving against recent changes

**Comment by JonHanna** [comment]
Resolved.

**Pull request merged**
