### PR TITLE
changing namespace for json serializer

### PR DESCRIPTION
**Pull request by Anipik**
Fixes https://github.com/dotnet/corefx/issues/37896

### CODE REVIEW

**Comment by Anipik** [comment]
@ahsonkhan  The ci is finally running for this change

**Comment by wtgodbe** [comment]
@ahsonkhan @Anipik any thoughts on the failures here?

**Comment by ahsonkhan** [comment]
> any thoughts on the failures here?

Yes. The namespace of this file needs to be changed to match. That file isn't getting updated in this PR. https://github.com/dotnet/corefx/blob/cfa4dda9ee426ad13e42fd086c5102fabf77e5bc/src/System.Text.Json/src/System/Text/Json/Serialization/JsonSerializer.Read.Utf8JsonReader.cs#L8

**Comment by Anipik** [comment]
i will change the namespace for the newly added overload

**Comment by Anipik** [comment]
closing in favour of https://github.com/dotnet/corefx/pull/38120

**Pull request closed without merging**
