### PR TITLE
Enable clearing initlocals when running dotnet msbuild.

### LINKED ISSUE #27045: ILLink initlocals custom step fails when building on Unix
Adding
```XML
<ILLinkClearInitLocals>true</ILLinkClearInitLocals>
```
to a corefx .csproj works fine on Windows but fails to build on Linux with the error:
```
IL Linker
Error: Step type 'ILLink.CustomSteps.ClearInitLocalsStep,ILLink.CustomSteps' not found.
illink [options] -x|-a|-i file
   --about             About the IL Linker
   --version           Print the version number of the IL Linker
   --skip-unresolved   Ignore unresolved types and methods (true or false)
   --dump-dependencies Dump dependencies for the linker analyzer tool
   -out                Specify the output directory, default to `output'
   -c                  Action on the core assemblies, skip, copy, copyused, addbypassngen, addbypassngenused or link, default to skip
   -u                  Action on the user assemblies, skip, copy, copyused, addbypassngen, addbypassngenused or link, default to link
   -p                  Action per assembly
   -s                  Add a new step to the pipeline.
   -t                  Keep assemblies in which only type forwarders are referenced.
   -d                  Add a directory where the linker will look for assemblies
   -b                  Generate debug symbols for each linked module (true or false)
   -g                  Generate a new unique guid for each linked module (true or false)
   -v                  Keep memebers needed by debugger attributes (true or false)
   -h                  List of reflection heuristics separated with a comma.
                       Supported heuristics:
                         LdtokenTypeMethods:   mark all methods of types whose token is used
                                               in an ldtoken instruction
                         LdtokenTypeFields:    mark all fields of types whose token is used
                                               in an ldtoken instruction
                         InstanceConstructors: mark all instance constructors in types
                                               where an instance member has been marked but
                                               none of the instance constructors have been marked
   -l                  List of i18n assemblies to copy to the output directory
                         separated with a comma: none,all,cjk,mideast,other,rare,west
                         default is all
   -x                  Link from an XML descriptor
   -a                  Link from a list of assemblies
   -r                  Link from a list of assemblies using roots visible outside of the assembly
   -i                  Link from an mono-api-info descriptor
   -z                  Include default preservations (true or false), default to true

Command execution failed with exit code 1.
```
cc: @sbomer, @JosephTremoulet

### PR DESCRIPTION
**Pull request by erozenfeld**
Linker step to clear initlocals was only enabled in Windows builds that use
desktop msbuild. dotnet msbuild has a bug in assembly loading: https://github.com/Microsoft/msbuild/issues/3016
that was preventing ILLink.CustomSteps from loading by a Type.GetType() call. This PR adds a workaround by appending ILLink.CustomSteps version to the string that is eventually passed to Type.GetType().

Fixes #27045.

@ericstj  @stephentoub PTAL

### CODE REVIEW

**Comment by erozenfeld** [comment]
@dotnet-bot test Linux x64 Release Build

**Comment by danmosemsft** [comment]
Yay for teamwork on this one!

**Comment by erozenfeld** [comment]
@dotnet-bot test Linux x64 Release Build

**Comment by stephentoub** [comment]
@dotnet-bot test Outerloop Linux x64 Release Build

**Comment by stephentoub** [comment]
Some of these Linux failures look legit.  In particular, the System.Net.Sockets failures are all in tests related to ReceiveMessageFrom, and ReceiveMessageFrom uses a few stackallocs (that said, it's not obvious to me why those stackalloc'd bytes would need to be cleared, as they're meant to be used as output space, so maybe that's not actually it).

For now, I'm going to run the tests again, and then assuming they still fail, let's make the setting of ILLinkClearInitLocals in System.Net.Sockets conditional on it being the Windows build, and I can investigate subsequently this particular failure.

**Comment by stephentoub** [comment]
@dotnet-bot test Outerloop Linux x64 Release Build please

**Comment by erozenfeld** [comment]
@stephentoub What about System.Security.Cryptography.Pkcs.Tests
and System.Net.WebSockets.Client.Tests failures? Are they unrelated?

**Comment by stephentoub** [comment]
The System.Diagnostics.Process failures are all https://github.com/dotnet/corefx/issues/27365; unrelated.

The System.Runtime.Environment failures are all https://github.com/dotnet/corefx/issues/27366; unrelated.

The System.Security.Cryptography.Pkcs failures were just fixed by https://github.com/dotnet/corefx/pull/27356; unrelated.

The System.Net.WebSockets.Client failure isn't known, but I don't believe it's related.  It looks like it falls into the larger bucket of failures we know about where we have transient issues connecting to a remote endpoint in the cloud.  Still... probably worth re-running just to see if it shows up again.

**Comment by stephentoub** [comment]
@dotnet-bot test Outerloop Linux x64 Release Build please please

**Comment by erozenfeld** [comment]
I pushed a change to make the setting of ILLinkClearInitLocals in System.Net.Sockets conditional on it being the Windows build.

**Comment by erozenfeld** [comment]
@dotnet-bot test Outerloop Linux x64 Release Build please please

**Comment by erozenfeld** [comment]
@stephentoub Are System.Net.Http.Functional failures known?

**Comment by erozenfeld** [comment]
@dotnet-bot test Linux x64 Release Build

**Comment by stephentoub** [comment]
> Are System.Net.Http.Functional failures known?

Yeah, those are https://github.com/dotnet/corefx/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+GetAsync_AllowedSSLVersion_Succeeds.

This looks good.  Thanks!

**Pull request merged**
