### PR TITLE
Add XunitShowProgress to System.Memory.Tests to find bad test

### PR DESCRIPTION
**Pull request by stephentoub**
https://github.com/dotnet/corefx/issues/25254

### CODE REVIEW

**Comment by stephentoub** [comment]
@dotnet-bot test Outerloop Windows x64 Debug Build please
@dotnet-bot test Outerloop Windows x86 Release Build please

**Comment by stephentoub** [comment]
@danmosemsft, thanks for adding the XunitShowProgress flag support in buildtools.  It's helpful.  Note that I'd added the -showProgress flag to our clone of the xunit console runner; when we move to the real one, hopefully soon, we should find a way to do an equivalent XunitShowProgress thing for CI.

**Comment by benaadams** [comment]
[`CopyToLargeSizeTest`](https://github.com/dotnet/corefx/blob/master/src/System.Memory/tests/Span/CopyTo.cs#L200-L217)? also a > 4GB test

**Comment by benaadams** [comment]
```
2017-11-15 15:46:24,269: INFO: proc(54): run_and_log_output: Output:    System.SpanTests.SpanTests.SequenceEqualNoMatch_Byte [STARTING]
2017-11-15 15:46:24,269: INFO: proc(54): run_and_log_output: Output:    System.SpanTests.SpanTests.SequenceEqualNoMatch_Byte [FINISHED] Time: 0.0006128s
2017-11-15 15:46:24,285: INFO: proc(54): run_and_log_output: Output:    System.SpanTests.SpanTests.TryCopyToShorter [STARTING]
2017-11-15 15:46:24,285: INFO: proc(54): run_and_log_output: Output:    System.SpanTests.SpanTests.TryCopyToShorter [FINISHED] Time: 0.0004579s
2017-11-15 15:46:24,285: INFO: proc(54): run_and_log_output: Output:    System.SpanTests.SpanTests.IndexOfSequenceZeroLengthValue [STARTING]
2017-11-15 15:46:24,285: INFO: proc(54): run_and_log_output: Output:    System.SpanTests.SpanTests.IndexOfSequenceZeroLengthValue [FINISHED] Time: 0.0003133s
2017-11-15 15:46:24,285: INFO: proc(54): run_and_log_output: Output:    System.SpanTests.SpanTests.OnStartsWithOfEqualSpansMakeSureEveryElementIsCompared [STARTING]
2017-11-15 15:46:24,285: INFO: proc(54): run_and_log_output: Output:    System.SpanTests.SpanTests.OnStartsWithOfEqualSpansMakeSureEveryElementIsCompared [FINISHED] Time: 0.0081576s
2017-11-15 15:46:24,285: INFO: proc(54): run_and_log_output: Output:    System.SpanTests.SpanTests.CopyToLargeSizeTest(bufferSize: 4294967296) [STARTING]
```
Wonder if they are better as MemoryMapped files pretending to be big allocations?

**Comment by stephentoub** [comment]
>  CopyToLargeSizeTest?

Yes, I have a PR at https://github.com/dotnet/corefx/pull/25272 disabling it.

**Pull request closed without merging**
