### PR TITLE
Use the real debian.8-x64 RID for debian

### PR DESCRIPTION
**Pull request by ellismg**

### CODE REVIEW

**Comment by ellismg** [comment]
/cc @Priya91 

After this merges, and the jobs are updated, I will send a PR to remove the debian.8.2 entries from our project.json's.

**Comment by ellismg** [comment]
@dotnet-bot test ci please

**Comment by stephentoub** [comment]
Test Innerloop CentOS7.1 Release Build and Test please
Test Innerloop OSX Debug Build and Test please
Test Innerloop OSX Release Build and Test please
Test Innerloop Ubuntu14.04 Debug Build and Test please

**Comment by stephentoub** [comment]
LGTM

**Comment by gkhanna79** [comment]
@ellismg Are you driving similar changes for packages generated out of all the repos?

**Comment by ellismg** [comment]
We have been generating packages with the debian.8 for months.  I am cleaning up the use of debian.8.2 across all our repos.

**Pull request merged**
