### PR TITLE
Make BigInteger implement IComparable implicitly

### PR DESCRIPTION
**Pull request by danmosemsft**
Fix https://github.com/dotnet/corefx/issues/11548

This is the only diff in System.Numerics namespace.

@joperezr

### CODE REVIEW

**Comment by joperezr** [comment]
@dotnet-bot test this please

**Comment by joperezr** [comment]
Should we also update the ref assembly in here to make it implicit? If we don't do that, then people will still only have access to the method through the interface at compile-time.

**Comment by danmosemsft** [comment]
Doh.

**Comment by danmosemsft** [comment]
@dotnet-bot test this please

**Comment by joperezr** [comment]
LGTM.

**Comment by stephentoub** [comment]
LGTM2

**Pull request merged**
