### PR TITLE
Disabling benchmark due to issue #29308

### PR DESCRIPTION
**Pull request by jorive**
The benchmark has been failing for few days now and it's blocking the performance run results to be uploaded.

### CODE REVIEW

**Comment by jorive** [comment]
@dotnet-bot test Windows_NT perf

**Comment by jorive** [comment]
@dotnet/rap-team PTAL

**Comment by DrewScoggins** [comment]
LGTM. Just make sure that the test gets skipped in the test here, https://ci2.dot.net/job/dotnet_corefx/job/perf/job/master/job/perf_windows_nt_release_prtest/31/.

**Comment by DrewScoggins** [comment]
Test run worked, and that test was skipped. LGTM

**Comment by danmosemsft** [comment]
@jorive how can I tell when a perf run fails for an issue like this? Does mail go out?

**Comment by jorive** [comment]
@danmosemsft Currently there is a non-automatic email sent out to the DotNet Rap team.

**Comment by jorive** [comment]
@DrewScoggins The run timeout because it took too long to run Profile and Diagnostic. I could increase the default runtime on the `perf.groovy`. What do you think?

**Pull request merged**
