### PR TITLE
Fix build break on machines with recent VS 2015 CTP

### PR DESCRIPTION
**Pull request by nguerrera**
Two separate parts:

2bc73d7 contains the necessary and sufficient fix.
ce6487e is a defensive change against a class of related issues.

### CODE REVIEW

**Comment by stephentoub** [comment]
LGTM.  Thanks for fixing.

**Comment by weshaggard** [comment]
LGTM. We have to use <Private>false</Private> for a number of other references when we start enabling the correct version for a number of assemblies that clash with the GAC. 

By the way I assume the issue is that VS2015 now puts Immutable into the GAC, but as far as I know it is shipping in the framework?

**Comment by nguerrera** [comment]
Right, it ships with VS, not the framework.

**Pull request merged**
