### PR TITLE
Fix package restore error

### PR DESCRIPTION
**Pull request by ellismg**
Please don't merge this as is.  I am just trying to get a CI run.

### CODE REVIEW

**Comment by krwq** [comment]
Thanks for fixing this! I don't have enough context to say if it is the right way to fix it although it fixes the break and the tests are still running so LGTM.

**Comment by ellismg** [comment]
The initial PR worked so I just updated the comment and repushed.  @ericstj can you please take a look?  I basically did what you said we should do.

**Comment by ellismg** [comment]
http://dotnet-ci.cloudapp.net/job/dotnet_corefx_prtest/998/ is the test job that validated the previous iteration.

**Comment by ericstj** [comment]
Looks good to me.  Thanks for fixing this.  Sorry I couldn't get to it, caring for a sick toddler here.

**Comment by mellinoe** [comment]
I have a very similar potential fix implemented, except in the partial facade targets in buildtools. I didn't see that we copy NuGet.Config somewhere else in dir.targets, so actually that looks like a better place to put it

**Pull request merged**
