### PR TITLE
WIP: Fix some links

### PR DESCRIPTION
**Pull request by MattGal**
@weshaggard @ericstj 

Still trying to convince myself whether this solves the problem of the System.Private.Xml tests or not.  Please do not merge.

### CODE REVIEW

**Comment by weshaggard** [comment]
Looks like a bunch of XML tests failed on Windows (note I think they are configured currently to only run on windows). So I suspect the SupplementalData item didn't work as expected.

**Comment by MattGal** [comment]
@weshaggard Agreed... would you prefer I figure out how to make SupplementalTestData work properly here or (as discussed in person) switch back to Content, set the "Link" property to True and suppress from Visual studio?

Also, can you confirm that this is a bug?  https://github.com/dotnet/buildtools/blob/7087e50b2f4f16b124225c663a30668b6f082bd6/src/Microsoft.DotNet.Build.Tasks/PackageFiles/publishtest.targets#L201  ... I would expect the property used here to be **CreateHardLinksForCopyTestToTestDirectoryIfPossible** .   While I haven't repro'ed CI's problem yet (probably need to just delete my bin dir locally) given these variables are at odds by default on Windows it may be relevant.

**Comment by weshaggard** [comment]
Yes lets see if we can get supplemental data to work for our purposes here. As for the bug I suppose we should use the one we are using everywhere else in that target which looks like it should be CreateHardLinksForCopyTestToTestDirectoryIfPossible.

**Comment by MattGal** [comment]
@dotnet-bot Test Ubuntu14.04 Release please

**Comment by MattGal** [comment]
@dotnet-bot Build and Test Ubuntu14.04 Release please

**Comment by MattGal** [comment]
@weshaggard I believe this is now OK to merge, and will allow us (after fixing the build tools variable choice bug mentioned earlier) to remove the workaround from daily test builds.

**Comment by weshaggard** [comment]
Thanks @MattGal

**Pull request merged**
