### PR TITLE
Readjust a Sockets test to accommodate OS X.

### LINKED ISSUE #4003: Socket_SendToAsyncV4IPEndPointToV4Host_Throws_Unix fails on OSX.

### PR DESCRIPTION
**Pull request by pgavlin**
OS X returns yet another different error code when an IPv4 socket address is
passed to recvmsg on an IPv6-only socket.

Fixes #4003.

### CODE REVIEW

**Comment by pgavlin** [comment]
@stephentoub PTAL

**Comment by pgavlin** [comment]
The System.Globalization tests crashed (file #4142).

**Comment by pgavlin** [comment]
@dotnet-bot test this please

**Comment by stephentoub** [comment]
LGTM

**Pull request merged**
