### PR TITLE
Re-enable xunit warning 2003

### PR DESCRIPTION
**Pull request by stephentoub**
cc: @ViktorHofer 

Contributes to https://github.com/dotnet/corefx/issues/39697

### CODE REVIEW

**Comment by stephentoub** [comment]
@Chrisboh, @mjanecke, I can't tell from either MC or Azure DevOps why the Linux leg here is canceled.  Where should I be looking to determine that?

**Comment by mjanecke** [comment]
@MattGal believes he's seen this issue before and is investigating it. He'll reply on this thread with his findings.

**Comment by MattGal** [comment]
@stephentoub  this is the second time I've seen this issue and I believe it's actually a bug in either Arcade functionality or msbuild logging.  Some notes:

-  All the Helix runs started and finished within 27 minutes.  If you have Kusto access you can see this here: (mostly in the case where a PR is urgent and you just want to see if stuff worked)
```
Jobs 
| where Source == "pr/dotnet/corefx/refs/pull/39696/merge" and Type == "test/functional/cli//" and Build == "20190723.10" and Properties contains "Debug" and Properties contains "x64"
| order by Finished desc  
```
- Immediately after the last Helix job enqueues (2019-07-23T15:34:06.5761562Z) the process seems to hang until killed;  it does not even successfully print out the other 6 correlation ids of the Helix runs affected. 

I'm opening an Arcade bug which I'll link here for you to follow along with.

**Comment by stephentoub** [comment]
Thanks, @MattGal.

**Pull request merged**
