### PR TITLE
Removing Span NonPortableCast API

### PR DESCRIPTION
**Pull request by ahsonkhan**
Part of https://github.com/dotnet/corefxlab/issues/1314 / https://github.com/dotnet/corefxlab/issues/1292

### CODE REVIEW

**Comment by omariom** [comment]
Why?
It is quite convenient in the following case:
```C#
Span<byte> memory = ...
Span<Message> messages = memory.NonPortableCast<Message>();
ref Message msg = ref messages[0];
...
```

**Comment by ahsonkhan** [comment]
@omariom, can you give more context and code snippet around that usage?
Why would you need to cast a span of Message into a span of byte?

The NonPortableCast only casts a span of one primitive type to another anyway, i.e.
https://github.com/dotnet/corefx/blob/944e5ab1493e56c1e2864628e650fee23b1138da/src/System.Memory/src/System/Span.cs#L525-L538

**Comment by omariom** [comment]
@ahsonkhan 
\cc @KrzysztofCwalina 

That's the opposite - treating a span of bytes  as a bunch of messages. It is convenient when you read something of fixed size from a network buffer or a memory mapped file.
See @jaredpar's [comment](https://github.com/dotnet/coreclr/issues/5851#issuecomment-227294196) 

I may have missed a discussion on NonPortableCast.

**Comment by ahsonkhan** [comment]
cc @jkotas, do we want to keep NonPortableCast?

@omariom, in your example, is `Message` a struct?

**Comment by jkotas** [comment]
>  It is convenient when you read something of fixed size from a network buffer 

It is non-portable code. If you look at my earlier comments about this API, you will see that I was never fan of this method ... so I am perfectly fine with non-having it.

`T Read/Write<[Primitive]T>(this Span<byte> slice)` APIs and similar APIs currently in corefxlab are the proper portable replacements.

**Comment by omariom** [comment]
@ahsonkhan 
Yes. Non ROCR struct.

@jkotas
Alternative would be to use `Unsafe`s methods?

**Comment by ahsonkhan** [comment]
The APIs have been reviewed: https://github.com/dotnet/corefx/issues/17414

**Comment by shiftylogic** [comment]
I had a conversation with @jkotas this morning. It seems that having NonPortableCast might be less evil than seeing every library developer using Span<T> have to implement the cast in an even less efficient way than this method is able to do.

In the process of building other library code, I'm seeing many scenarios where doing this cast is very helpful. For instance, in a public surface function that takes a buffer from a caller and needs to place data into the buffer using a specific encoding (such as UTF-16), the implementation will very likely do the work to perform a similar cast on their own. Implementing this cast is slightly tricky and will potentially exist / be used in many places throughout the code.

**Comment by jkotas** [comment]
Let's keep the NonPortableCast then.

**Comment by ahsonkhan** [comment]
Since we are keeping NonPortableCast, closing this PR.

**Comment by Mirandatz** [comment]
I just wanted to leave this here for reference: my team loved this method.
It's clear, concise, performant enough and doesn't require us to change the build options to allow unsafe code (we were using pointers before).

I'm absolutely sure many devs out there will love this method.

**Pull request closed without merging**
