### PR TITLE
Fix GregorianCalendar param name tests

### PR DESCRIPTION
**Pull request by hughbe**
From https://github.com/dotnet/coreclr/pull/22582

/cc @tarekgh @jkotas @stephentoub

### CODE REVIEW

**Comment by tarekgh** [comment]
This is failing. 

https://mc.dot.net/#/user/hughbe/pr~2Fjenkins~2Fdotnet~2Fcorefx~2Fmaster~2F/test~2Ffunctional~2Fcli~2F/b4235abae6f3ea4968a586fad28653e61a222ba1/workItem/System.Globalization.Calendars.Tests/analysis/xunit/System.Globalization.Tests.GregorianCalendarArabicTests~2FCalendarType_SetInvalidValue_ThrowsArgumentOutOfRangeException(type:%200)

```
 Xunit.Sdk.EqualException
OSX.1013.Amd64.Open-x64-Debug
Get Repro environment
Unhandled Exception of Type Xunit.Sdk.EqualException
Message :
Assert.Equal() Failure
          ↓ (pos 0)
Expected: value
Actual:   m_type
          ↑ (pos 0)
Stack Trace :
   at System.AssertExtensions.Throws[T](String netCoreParamName, String netFxParamName, Func`1 testCode) in /Users/dotnet-bot/j/workspace/dotnet_corefx/master/osx-TGroup_netcoreapp+CGroup_Debug+AGroup_x64+TestOuter_false_prtest/src/CoreFx.Private.TestUtilities/src/System/AssertExtensions.cs:line 58
   at System.Globalization.Tests.GregorianCalendarTestBase.CalendarType_SetInvalidValue_ThrowsArgumentOutOfRangeException(GregorianCalendarTypes type) in /Users/dotnet-bot/j/workspace/dotnet_corefx/master/osx-TGroup_netcoreapp+CGroup_Debug+AGroup_x64+TestOuter_false_prtest/src/System.Globalization.Calendars/tests/System/Globalization/GregorianCalendarTests.cs:line 53

```

**Comment by stephentoub** [comment]
@tarekgh, it depends on a change that hasn't come from coreclr into corefx yet.

**Comment by tarekgh** [comment]
@stephentoub I thought we can just check both possible values. but it is ok to wait then.

**Comment by tarekgh** [comment]
@hughbe looks there is some compilation errors:

```
05:00:27 
shared\System\Globalization\CultureData.Windows.cs(231,122): error CS0103: The name 'LOCALE_NOUSEROVERRIDE' does not exist in the current context [D:\j\workspace\x64_checked_w---43686a05\src\System.Private.CoreLib\System.Private.CoreLib.csproj]
05:00:27 shared\System\Globalization\CultureData.Windows.cs(336,27): error CS0103: The name 'LOCALE_NOUSEROVERRIDE' does not exist in the current context [D:\j\workspace\x64_checked_w---43686a05\src\System.Private.CoreLib\System.Private.CoreLib.csproj]
05:00:27 shared\System\Globalization\CultureData.Windows.cs(516,66): error CS0103: The name 'LOCALE_SISO3166CTRYNAME' does not exist in the current context [D:\j\workspace\x64_checked_w---43686a05\src\System.Private.CoreLib\System.Private.CoreLib.csproj]
05:00:39   SOS.NETCore -> D:\j\workspace\x64_checked_w---43686a05\bin\Product\Windows_NT.x64.Checked\SOS.NETCore.dll
05:00:39 
05:00:39 Build FAILED.
05:00:39 
05:00:39 


```

**Pull request closed without merging**
