### PR TITLE
Re-enable failing httplistener tests on osx.

### LINKED ISSUE #19593: System.Net.Tests.HttpListenerPrefixCollectionTests.Add_InvalidPrefixNotStarted_ThrowsHttpListenerExceptionOnStart(uriPrefix: \"http://a08196d3572648a99e9d3669ecdda58c/\") fails in CI on mac OSX
As discussed in https://github.com/dotnet/corefx/pull/19579

```cs

public static IEnumerable<object[]> InvalidPrefix_TestData()
{
    // [ActiveIssue()]
    if (!PlatfomDetection.IsOSX)
    {
        yield return new object[] { $"http://{Guid.NewGuid().ToString("N")}/" };
    }
}

[Theory]
[MemberData(nameof(InvalidPrefix_TestData))]
public void Add_InvalidPrefixNotStarted_ThrowsHttpListenerExceptionOnStart(string uriPrefix)
{
    var listener = new HttpListener();
    listener.Prefixes.Add(uriPrefix);

    Assert.Equal(1, listener.Prefixes.Count);
    Assert.True(listener.Prefixes.Contains(uriPrefix));
    Assert.Throws<HttpListenerException>(() => listener.Start());
}
```

This test fails with mac OSX: 

```
MESSAGE:
Assert.Throws() Failure\nExpected: typeof(System.Net.HttpListenerException)\nActual: (No exception was thrown)
+++++++++++++++++++
STACK TRACE:
at System.Net.Tests.HttpListenerPrefixCollectionTests.Add_InvalidPrefixNotStarted_ThrowsHttpListenerExceptionOnStart(String uriPrefix) in /Users/dotnet-bot/j/workspace/dotnet_corefx/master/osx10.12_debug_prtest/src/System.Net.HttpListener/tests/HttpListenerPrefixCollectionTests.cs:line 264
```

### PR DESCRIPTION
**Pull request by Priya91**
cc @hughbe @stephentoub 

fixes #19593 #19986

### CODE REVIEW

**Comment by Priya91** [comment]
The test passes locally throwing HttpListenerException, because the socket connection throws Permission denied error. This is because when we are not able to resolve the host to a specific ipaddress, the httplistener listens to IPAddress.Any, which is 0.0.0.0, and from documentation indicates all ipaddresses on the interface. Hence the httplistener server listens to all ipaddresses. This test passes for other OSes because the innerloop runs may not be elevated or run as sudo, and in non-elevated/non-sudo environment listening to 0.0.0.0 results in socket error 13, permission denied. But while run in elevated/sudo environment, the test fails as it doesn't throw httplistenerexception on Windows, linux and OSX. Hence removing this incorrect test case.

Also note, that when passing http://0.0.0.0/ case directly, windows httpApi throws request not supported error. I'm not sure how the native httpapi interprets hostnames that can't be resolved to an ipaddress. cc @CIPop @davidsh Do you know how to get which endpoint the httplistener is listening to? 

@mmitche Are the OSX innerloop runs execute the build-tests script in a sudo environment?

**Comment by mmitche** [comment]
@Priya91 They are.  This is tracked to be fixed as part of a larger change in how we provision machines, unless it's critical we do so now.

**Comment by CIPop** [comment]
> Do you know how to get which endpoint the httplistener is listening to, to verify that hostname that can't be resolved is actually listening on 0.0.0.0 on windows?

The binding is specified by the application through the `Prefixes` property. Since the app is specifying it, wouldn't you already know it? Bindings are not IP addresses but URIs and the syntax is described here:
https://msdn.microsoft.com/en-us/library/system.net.httplistenerprefixcollection.add(v=vs.110).aspx#Anchor_2

**Comment by Priya91** [comment]
> This is tracked to be fixed as part of a larger change in how we provision machines, unless it's critical we do so now.

Thanks @mmitche ! It's not critical, asked to understand why the test fails only on osx. It makes sense now. Thanks!

**Pull request merged**
