### PR TITLE
Enable WaitHandle.SignalAndWait tests on Unix

### PR DESCRIPTION
**Pull request by kouvel**
Depends on https://github.com/dotnet/coreclr/pull/16383
Fixes https://github.com/dotnet/coreclr/issues/10441

### CODE REVIEW

**Comment by kouvel** [comment]
@dotnet-bot test this please

**Comment by kouvel** [comment]
@dotnet-bot test this

**Comment by kouvel** [comment]
@dotnet-bot test this please

**Comment by kouvel** [comment]
@dotnet-bot test this please

**Comment by stephentoub** [comment]
@dotnet-bot test this please

**Comment by stephentoub** [comment]
@dotnet/dnceng, this Windows leg has been running for 11 hours:
https://ci3.dot.net/job/dotnet_corefx/job/master/job/windows-TGroup_netcoreapp+CGroup_Release+AGroup_x86+TestOuter_false_prtest/8849/
any idea what's up?

**Comment by stephentoub** [comment]
Also, @dotnet/dnceng, the Linux leg is showing with a green check mark, but when I look at the results page, it shows a bunch of failures on Linux for the tests in this PR:
https://mc.dot.net/#/user/kouvel/pr~2Fjenkins~2Fdotnet~2Fcorefx~2Fmaster~2F/test~2Ffunctional~2Fcli~2F/cefd247dfee8d6c40e8c3dd2d7b9a8e1f1e10d03/workItem/System.Runtime.Tests
image

**Comment by Chrisboh** [comment]
@stephentoub I am still looking into the back up but the linux errors are interesting.  The Jenkins job that is doing the monitoring isn't paying attention to the distro's that failed.

image


This is why you are seeing the green check mark plus failures.  @mmitche what controls what should and should not be paid attention to by the Jenkins job?

**Comment by mmitche** [comment]
@Chrisboh Jenkins should be showing a red check if any distro failed.  It monitors the submitted job info for each queue and asks Helix for the results.

**Comment by MattGal** [comment]
While I have no idea how the commit hash didn't change, I removed Centos and RedHat 7.3 from CI about 3 days ago, before the 2/23 runs listed started:

https://github.com/dotnet/corefx/blame/master/buildpipeline/linux.groovy

Chatting with @mmitche  to understand how commit hash did not change somehow.

**Comment by MattGal** [comment]
@stephentoub here's your final analysis:

**Long Windows run:**
This run was "stuck" in the none status for 1 item:
05:39:45 [Windows.7.Amd64.Open] [{"Key":{"job.name":"aee3e7ce-72e1-4614-b2d9-19887ea5263f"},"Data":{"Analysis":[{"Name":"xunit","Status":{"skip":1386,"fail":0,"pass":306260}}],"WorkItemStatus":{"none":1,"pass":251}}}]

- Kusto says System.Threading.Channels.Performance.Tests is two work items.  No issues actually happened with it, rather Kusto ingestion did it twice:
WorkItems | where JobId == 2580050 | where FriendlyName == 'System.Threading.Channels.Performance.Tests'

TODO:  Raid issue on core-eng (in progress).  Serious Kusto Ingestion bug

**Linux failing but not failing :** 

The 7.3 runs are from V-day. I removed 7.3 from the .groovy between V-day and now:
https://github.com/dotnet/corefx/blame/master/buildpipeline/linux.groovy 

But, this file:
https://github.com/dotnet/dotnet-ci/blob/master/vars/getCommitForPR.groovy#L10  
picks the commit hash of the SOURCE branch of the PR, not the commit hash.  Thus every time that a new build is spun, we end up with the latest possible groovy file.  This is desirable otherwise every time you re-run tests if the commit changed you'd be looking at a different page on Mission Control.

**Comment by MattGal** [comment]
Follow-up:  The issue that caused the super long Win 7 run is fixed and rolled out via hotfix.  Thanks for calling this out @stephentoub !

**Comment by stephentoub** [comment]
Thanks for following up!

**Pull request merged**
