### PR TITLE
Reduce dependencies

### PR DESCRIPTION
**Pull request by ericstj**
Remove unused dependencies.

### CODE REVIEW

**Comment by stephentoub** [comment]
@ericstj, this has compilation errors of the form:
```
System.IO.Compression.ZipFile.cs(8,11): error CS0012: The type 'System.IO.Stream' is defined in an assembly that is not referenced. You must add a reference to assembly 'System.IO, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. [d:\j\workspace\dotnet_corefx_windows_debug_prtest\src\System.IO.Compression.ZipFile\ref\System.IO.Compression.ZipFile.csproj]
```

**Comment by ericstj** [comment]
Yeah, not sure why I'm not seeing those locally.  Expect compiler differences.  Fix is coming.

**Comment by stephentoub** [comment]
> Yeah, not sure why I'm not seeing those locally. Expect compiler differences.

Yeah, I expect it's another case of a difference between the native C# 5 compiler being used in CI and the managed C# 6 compiler most of us have installed and that's being used for builds internally.  We hit this a fair amount, where PRs fail due to things that should work and actually worked locally.
cc: @weshaggard

**Comment by weshaggard** [comment]
@stephentoub @mmitche Do you suspect that our Jenkins CI is using the C# 5 native compiler? I wouldn't expect that to be the case but if it is we should see about trying to address it. Things like this is definitely part of my worry about moving to C# 6.0 right now.

**Comment by stephentoub** [comment]
> Do you suspect that our Jenkins CI is using the C# 5 native compiler?

Yes!  That's what I've been screaming for months :smile:

**Comment by mmitche** [comment]
@weshaggard Yeah it's just the plain out of the box 2015 RTM compiler.  However, couldn't we change the build process to pull roslyn from nuget?

**Comment by stephentoub** [comment]
@mmitche, you mean 2013, not 2015, right?

**Comment by mmitche** [comment]
Errr....depends on what's being launched in the build script.

**Comment by stephentoub** [comment]
> depends on what's being launched in the build script

Microsoft Visual Studio 12.0, aka 2013, e.g.
```
d:\j\workspace\dotnet_corefx_windows_release_prtest>"C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\vcvarsall.bat" x86   && build.cmd /p:OSGroup=Windows_NT /p:Configuration=Release   && C:\Packer\Packer.exe .\bin\build.pack .\bin 
```

**Comment by weshaggard** [comment]
>Yes! That's what I've been screaming for months
I know you have been screaming for supporting C# 6.0 for months but I didn't realize our Jenkins machines were still using VS 2013. I was under the impression from @mmitche that we are using VS 2105 for those. We should definitely fix this @mmitche what would it take to get our CI system using VS 2015.

As for the general plan we do intend to pull in the Roslyn compiler as a dependency of the build as part of the work we are doing right now to switch to the .NET Core version of msbuild. Once that work gets completed we will be in a much better position to control which compiler we are using and I will likely start allowing C# 6.0 :)

**Comment by mmitche** [comment]
@weshaggard Just changing the job configuration to call VS 2015 instead of 2013 which it currently does.  Rather than doing this all manually this is probably best to package along with the move to netci.groovy for the CoreFx repo (though I don't have this scheduled at the moment)

**Comment by ericstj** [comment]
Discussion here is great, but can it be moved to an issue?  I'd like to merge this before it gets stale.

**Comment by stephentoub** [comment]
LGTM

**Comment by weshaggard** [comment]
Sorry about taking over the thread :)

@mmitche aren't we already using the netci.groovy script for our CI and isn't already using VS 2015, https://github.com/dotnet/corefx/blob/master/netci.groovy#L14

**Comment by mmitche** [comment]
Not for all of the corefx jobs, just a few right now.

Sent from my Windows Phone
________________________________

**Pull request merged**
