### PR TITLE
Fix FormatterServices.GetUninitializedObject allows allocating byref-like objects

### PR DESCRIPTION
**Pull request by jkotas**
Add regression test for https://github.com/dotnet/coreclr/issues/9739

### CODE REVIEW

**Comment by danmosemsft** [comment]
LGTM

**Comment by jkotas** [comment]
Waiting for https://github.com/dotnet/coreclr/pull/9754

**Comment by stephentoub** [comment]
Blocked on https://github.com/dotnet/corefx/pull/16454 being merged

**Comment by jkotas** [comment]
@dotnet-bot test this please

**Pull request merged**
