### PR TITLE
Implement basic cancellation for the async IO in sslstream.

### LINKED ISSUE #25206: Support cancellation on SslStream.AuthenticateAs*Async methods
cc: @Priya91 
Previous attempt in https://github.com/dotnet/corefx/pull/24857 reverted in https://github.com/dotnet/corefx/pull/25203 due to it causing a failing outerloop test SslStream_StreamToStream_WriteAsync_ReadAsync_Pending_Success (outerloop tests weren't run on the original PR).

### PR DESCRIPTION
**Pull request by Priya91**
cc @stephentoub @wfurt @karelz 

@Drawaes @Tratcher  Can you help running this commit with the asp.net benchmark runs, to ensure this change doesn't cause perf issues?

fixes #25206

### CODE REVIEW

**Comment by Priya91** [comment]
@dotnet-bot test outerloop windows x64 debug please
@dotnet-bot test outerloop linux x64 debug please
@dotnet-bot test outerloop osx x64 debug please

**Comment by Drawaes** [comment]
Using Azure Ubuntu 16 with 16 cores and the same for a load gen (WRK PlainText Techempower style)

|Branch|RPS|Latency|
|--|--|--|
|Cancel|638831|7.25ms|
|Master|663735|4.38ms|

It could be azure fluctuations but I did 6 tests, 3 for this branch, 3 for master, then 3 for this branch etc. I took out the first run of each (the master was still ahead but for both the first is always lower) and then took the average of the two, then I took the best of the two averages. This is what I normally do for my branches to try to get a stable number and avoid major "cloudness" in my benchmarks.  It is normally pretty much in line with what I get when I test on physical machines (not the actual numbers but the relative numbers).

It probably needs another round, maybe on bigger and small, plus on windows to call it. I might get time to do windows tomorrow.

**Comment by stephentoub** [comment]
If the test being used is passing in a cancelable token, it makes sense that there could be a small (opt-in) hit, as now the stream wrapped by the SslStream will receive the token and register with it where as before it never would.

**Comment by Drawaes** [comment]
I don't know what ASPNET uses for SslStream, I can't remember and would have to go look

**Comment by Drawaes** [comment]
Doesn't look like cancelation is supported

https://github.com/aspnet/KestrelHttpServer/blob/dev/src/Kestrel.Core/Adapter/Internal/AdaptedPipeline.cs#L131

**Comment by Tratcher** [comment]
@halter73 I assume that's because we knew cancellation wasn't implemented at the lower layers?

**Comment by Priya91** [comment]
@dotnet-bot test outerloop windows x64 debug please
@dotnet-bot test outerloop linux x64 debug please
@dotnet-bot test outerloop osx x64 debug please

**Comment by Priya91** [comment]
@dotnet-bot test outerloop linux x64 debug build please
@dotnet-bot test outerloop windows x64 debug build please
@dotnet-bot test outerloop osx x64 debug build please

**Comment by Drawaes** [comment]
@Tratcher that is more than likely (although that is supposed to be a generic adapter, it was actually really only probably used 1x. Even if I used it to make a NTLM/Kerb adapter ;) ).

My question really is, why the 5% drop in perf if it's not being used? And if you do use it, what will the drop be then?

**Comment by wfurt** [comment]
It looks ok to me. Let me know @Priya91 if you want to setup it up for perf testing. I have not seen anything looking suspicious and we can take it apart if we can reproduce @Drawaes results.

**Comment by Priya91** [comment]
@Drawaes Can you share the asp.net test app that you are using for the tests?

**Comment by Drawaes** [comment]
https://github.com/aspnet/benchmarks

**Comment by Drawaes** [comment]
Using the plaintext as it takes out any extra memory or processing overhead and pretty much just tests "read request", "respond with precanned array"

**Comment by halter73** [comment]
@Tratcher Correct. We observe cancelation tokens passed to Request.Body.ReadAsync/WriteAsync, but instead of passing through to SslStream.ReadAsync/WriteAsync, we abort the underlying socket.

**Comment by Drawaes** [comment]
Is there a massive upside to doing it any other way, especially as there is a perf penalty for it anyway?

**Comment by halter73** [comment]
@Drawaes It's mostly a correctness issue. When using connection adapters, we don't want a buggy stream/adapter implementation causing connections not to abort, so we bypass the stream for cancelations.

**Comment by Drawaes** [comment]
@halter73 I meant "is there an upside to not doing it the way that ASP.NET currently does it?" I am wondering where the pressure to implement the cancelation in SslStream is while the innards are still a mix of APM and Async, I would say that asp.net is the major user, but I am not privy to other uses. I know that my "custom" protocol implementations do the same, they kill the socket underneath it.

**Comment by stephentoub** [comment]
The value in respecting the cancellation is in playing nicely with the rest of the system using it, in whatever scenario it's being used.

And there shouldn't be a measurable perf penalty.  If there really is, someone should look at a profile with and without the change to narrow down where it's coming from.

**Comment by Drawaes** [comment]
I agree that in the long term it should respect the contract (cancellation).

I really don't understand why there is a perf difference, looking at the code I can't see why there should be, I would be interested to see if the results are repeatable by someone else, or if I have something wrong with my test method.

**Comment by Priya91** [comment]
With help of @sebastienros from asp.net, we got the perf numbers on windows azure machines with plaintext ssl, and there is indeed a 3.8% drop. Note, that the old dll is from latest runtime, so there can be other changes from that and this-branch that can be responsible. @sebastienros is setting up infra to be able to easily test incremental changes by replacing a single dll, with that, we should be able to narrow down what's happening here.

cc @karelz @wfurt @geoffkizer @stephentoub 

Below are the numbers from 3 runs, after warmup of 2 times:

Plaintext/SSL/Windows/Sockets/latest-runtime | 32 threads and 256   connections | 32 threads and 256   connections | 32 threads and 256   connections
-- | -- | -- | --
  | Thread Stats   Avg        Stdev     Max   +/- Stdev | Thread Stats   Avg        Stdev     Max   +/- Stdev | Thread Stats   Avg        Stdev     Max   +/- Stdev
  | Latency     3.89ms     25.32ms   1.93s    99.87% | Latency     3.81ms     16.01ms   1.24s    99.76% | Latency     4.46ms     36.92ms   2.39s    99.80%
  | Req/Sec     2.44k     269.39    10.26k    95.21% | Req/Sec     2.45k     196.26     5.32k    92.04% | Req/Sec     2.41k     226.97     5.91k    91.76%
  | Latency   Distribution | Latency   Distribution | Latency   Distribution
  | 50%    3.26ms | 50%    3.25ms | 50%    3.29ms
  | 75%    3.44ms | 75%    3.42ms | 75%    3.46ms
  | 90%    3.62ms | 90%    3.59ms | 90%    3.65ms
  | 99%    6.19ms | 99%    6.22ms | 99%    6.85ms
  | 1177574 requests   in 15.10s, 148.24MB read | 1184395 requests   in 15.09s, 149.10MB read | 1167576 requests   in 15.10s, 146.98MB read
  | Requests/sec:  78000.83 | Requests/sec:  78473.36 | Requests/sec:  77324.03
  | Transfer/sec:      9.82MB | Transfer/sec:      9.88MB | Transfer/sec:      9.73MB
  |   |   |  
Plaintext/SSL/Windows/Sockets/this-branch |   |   |  
  | 32 threads and 256   connections | 32 threads and 256   connections | 32 threads and 256   connections
  | Thread Stats   Avg        Stdev     Max   +/- Stdev | Thread Stats   Avg        Stdev     Max   +/- Stdev | Thread Stats   Avg        Stdev     Max   +/- Stdev
  | Latency     3.85ms     13.27ms 922.12ms   99.72% | Latency     3.58ms      5.48ms 456.11ms   99.52% | Latency     4.72ms     23.64ms   1.22s    99.44%
  | Req/Sec     2.35k     235.13     7.61k    93.68% | Req/Sec     2.36k     251.62     9.25k    95.21% | Req/Sec     2.36k     226.40     5.32k    92.04%
  | Latency   Distribution | Latency   Distribution | Latency   Distribution
  | 50%    3.35ms | 50%    3.33ms | 50%    3.32ms
  | 75%    3.55ms | 75%    3.54ms | 75%    3.54ms
  | 90%    3.79ms | 90%    3.76ms | 90%    3.77ms
  | 99%    6.77ms | 99%    6.26ms | 99%    8.77ms
  | 1135080 requests   in 15.10s, 142.89MB read | 1140909 requests   in 15.10s, 143.62MB read | 1140913 requests   in 15.10s, 143.62MB read
  | Requests/sec:  75193.56 | Requests/sec:  75569.75 | Requests/sec:  75562.84
  | Transfer/sec:      9.47MB | Transfer/sec:      9.51MB | Transfer/sec:      9.51MB

**Comment by Drawaes** [comment]
So my test was "build the latest master" and then build your branch. I am not sure if that is what you meant by "build the latest runtime?". If your fork isn't up to date, might be worth rebasing it so we can compare apples and orange.

**Comment by sebastienros** [comment]
Base runtime was `2.1.0-preview1-26016-05` which we took in last Friday. The difference between the two runs is just with a newly built `System.Net.Security.dll`

**Comment by Drawaes** [comment]
I would guess there is no difference in the base then, I haven't seen any other commits. Normally what I do for my "baseline" is take the build version. Then Build System.Net.Security with the "base master" eg @Priya91 master. Then the changed to get the diff.

As I said though in this case I don't think there will be any changes that have gone in, but using the above you are sure that you only got your changes and commits between the two. Anyway you confirm my results on Ubuntu.

**Comment by stephentoub** [comment]
@Drawaes or @Priya91, have you profiled with/without the change to see if you can see where the extra 3.8% is going?

**Comment by Priya91** [comment]
I tried using the visual studio profile on a simple sslstream handshake test (which is where the cancellation is implemented), there was no major difference in numbers for with/without change. Working on doing this with the asp.net benchmark app.

**Comment by karelz** [comment]
@Priya91 I would recommend to close the PR until we have clear path forward. It seems to be blocked now.

**Comment by stephentoub** [comment]
> Working on doing this with the asp.net benchmark app.

Anything interesting here?

**Comment by Priya91** [comment]
I havent spent much more time on this, @Tratcher Can you help with collecting perf view or some diagnostic data from the asp.net benchmark runs? From what I understood interacting with Sebastian is that the benchmark runs don't provide any debug data, just the results. 

Closing this PR for the time being.

**Comment by Tratcher** [comment]
@sebastienros are you still working with @Priya91 on this?

**Comment by sebastienros** [comment]
I implemented this feature very recently and now you can get a PerfView trace (windows servers only) and also give it your custom locally built corefx assembly. This way you get the traces with and without the changes. This can be repeated as much as you need.

**Pull request closed without merging**
