### PR TITLE
Fix TypeScope.GetEnumeratorElementType.

### LINKED ISSUE #17447: TypeScope.GetEnumeratorElementType Fails on Uapaot
[`System.Xml.Serialization.TypeScope.GetEnumeratorElementType`](https://github.com/dotnet/corefx/blob/master/src/System.Private.Xml/src/System/Xml/Serialization/Types.cs#L1292) is failing on uapaot as it does reflection on IEnumerable types but the metadata info for IEnumerable was reduced by UWP toolchain. 5 XmlSerializer tests failed on uapaot due to the issue. Here's the output of one of the failed tests,

```
<test name="XmlSerializerTests.Xml_SimpleCollectionDataContract" type="XmlSerializerTests" method="Xml_SimpleCollectionDataContract" time="0.0001254" result="Fail">
  <failure exception-type="System.InvalidOperationException">
    <message><![CDATA[System.InvalidOperationException : XmlNoAddMethod, SerializationTypes.SimpleCDC, System.Object, IEnumerable]]></message>
    <stack-trace><![CDATA[   at System.Xml.Serialization.TypeScope.GetEnumeratorElementType(Type type, $TypeFlags& flags) in D:\OSS\corefx-1\corefx\src\System.Private.Xml\src\System\Xml\Serialization\Types.cs:line 1304
at System.Xml.Serialization.TypeScope.ImportTypeDesc(Type type, MemberInfo memberInfo, Boolean directReference) in D:\OSS\corefx-1\corefx\src\System.Private.Xml\src\System\Xml\Serialization\Types.cs:line 934
at System.Xml.Serialization.TypeScope.GetTypeDesc(Type type, MemberInfo source, Boolean directReference, Boolean throwOnError) in D:\OSS\corefx-1\corefx\src\System.Private.Xml\src\System\Xml\Serialization\Types.cs:line 724
at System.Xml.Serialization.ModelScope.GetTypeModel(Type type, Boolean directReference) in D:\OSS\corefx-1\corefx\src\System.Private.Xml\src\System\Xml\Serialization\Models.cs:line 44
at System.Xml.Serialization.XmlReflectionImporter.ImportTypeMapping(Type type, $XmlRootAttribute root, String defaultNamespace) in D:\OSS\corefx-1\corefx\src\System.Private.Xml\src\System\Xml\Serialization\XmlReflectionImporter.cs:line 162
at System.Xml.Serialization.XmlSerializer..ctor(Type type, String defaultNamespace) in D:\OSS\corefx-1\corefx\src\System.Private.Xml\src\System\Xml\Serialization\XmlSerializer.cs:line 287
at XmlSerializerTests.SerializeAndDeserialize<System.__Canon>(__Canon value, String baseline, Func$1<$XmlSerializer> serializerFactory, Boolean skipStringCompare, $XmlSerializerNamespaces xns) in D:\OSS\corefx-1\corefx\src\System.Private.Xml\tests\XmlSerializer\XmlSerializerTests.cs:line 3097
at XmlSerializerTests.Xml_SimpleCollectionDataContract() in D:\OSS\corefx-1\corefx\src\System.Private.Xml\tests\XmlSerializer\XmlSerializerTests.cs:line 992
at _$ILCT$.$ILT$ReflectionDynamicInvoke$.InvokeRetV(Object thisPtr, IntPtr methodToCall, ArgSetupState argSetupState, Boolean targetIsThisCall)
at System.InvokeUtils.CalliIntrinsics.Call(IntPtr dynamicInvokeHelperMethod, Object thisPtr, IntPtr methodToCall, ArgSetupState argSetupState, Boolean isTargetThisCall)
at System.InvokeUtils.CallDynamicInvokeMethod(Object thisPtr, IntPtr methodToCall, Object thisPtrDynamicInvokeMethod, IntPtr dynamicInvokeHelperMethod, IntPtr dynamicInvokeHelperGenericDictionary, Object targetMethodOrDelegate, Object[] parameters, BinderBundle binderBundle, Boolean invokeMethodHelperIsThisCall, Boolean methodToCallIsThisCall) in f:\dd\ndp\fxcore\CoreRT\src\System.Private.CoreLib\src\System\InvokeUtils.cs:line 400]]></stack-trace>
  </failure>
</test>
```

### PR DESCRIPTION
**Pull request by shmao**
[`System.Xml.Serialization.TypeScope.GetEnumeratorElementType`](https://github.com/dotnet/corefx/blob/master/src/System.Private.Xml/src/System/Xml/Serialization/Types.cs#L1292) is failing on uapaot as it does reflection on IEnumerable types but the metadata info for IEnumerable was reduced by UWP toolchain. 5 XmlSerializer tests failed on uapaot due to the issue. 

The fix is to modify System.Private.Xml's embedded rd.xml to keep the required metadata.

Fixed #17447

### CODE REVIEW

**Comment by shmao** [comment]
XmlSerializer uses reflection to get System.DBNull.Value. I added DBNull in rd.xml as well.

**Comment by morganbr** [comment]
Before we take this one, can you please tell us more about the cases where it does that? Is there a specific set of types with special handling or does it just depend on the input? In general, adding this for IEnumerable would affect all apps, so it would be good to better understand the reason and implications.

**Comment by shmao** [comment]
@morganbr XmlSerializer gets an IEnumerable's array element type by reflecting  the IEnumerable's enumerator's return type when parsing the IEnumerable. This happens to any IEnumerable types to be serialized. 

The parsing method, XmlReflectionImporter.ImportTypeMapping(), didn't run on uapaot runtime previously as it's done by sg.exe. The reflection based serialization, however, needs to parse types at runtime and thus we started to need the metadata for IEnumerable.

**Comment by mconnew** [comment]
:shipit:

**Comment by morganbr** [comment]
@shmao , this is potentially a large size regression. Please revert this unless you can show that it's not affecting size.

**Comment by shmao** [comment]
@morganbr Ok. I will revert this.

**Pull request merged**
