### PR TITLE
Adding fallback logic to NTLM

### PR DESCRIPTION
**Pull request by shrutigarg**
This includes
 implementing the NTLM logic for OSX/Linux.
fallback logic to ntlm if Kerberos fails.

tested locally as linux client against windows server.
ongoing testing with OSX client , will update here once testing is done. 

Please refer to commit 5 for the changes.. other commits are maintained and reviewed separately in separate PRs. 
cc @stephentoub @bartonjs @vijaykota

### CODE REVIEW

**Comment by vijaykota** [comment]
cc: @joshfree for tracking #2483 

This PR is dependent on other PRs - dev/negotiatestream equivalents of #5500, #5581 and #5726 Hence adding the "needs extra testing" label

**Comment by vijaykota** [comment]
Also depends on the code of #5728. Without the pre-requisite PRs, the build is expected to fail

**Comment by stephentoub** [comment]
Shouldn't those PRs be closed and new ones opened to this branch so they can be merged in?

**Comment by shrutigarg** [comment]
yes. in progress of moving those here.

**Comment by stephentoub** [comment]
Ok, good, thanks.  I misunderstood the comments about the dependencies.

**Comment by vijaykota** [comment]
Yes.. the real dependencies are the <b>equivalent</b> PRs. We will update those no.s once the move is complete

**Comment by shrutigarg** [comment]
updated the PR numbers (of all dependent PRs) for this branch

**Comment by shrutigarg** [comment]
Ping @stephentoub @bartonjs @vijaykota

**Comment by shrutigarg** [comment]
ping

**Comment by bartonjs** [comment]
I looked only at commits 5 and higher.  I'm not quite understanding how this is supposed to work, though.  If this PR is merged then the other commits also get merged.  Since they're not being reviewed here that seems bad.

Some of the Heimdal references didn't seem familiar, and I was having a hard time searching them out.  So... I guess I'm really confused as to the macro-plan here.

**Comment by vijaykota** [comment]
>  If this PR is merged then the other commits also get merged

We have labelled it with "needs-extra-testing" to prevent such a merge. Once this PR's dependencies are merged, we will do a rebase and remove the label.

**Comment by stephentoub** [comment]
> synced and rebased

CI is reporting there are still merge conflicts.

**Comment by shrutigarg** [comment]
@stephentoub That is supposed to fail as this PR depends on the shim changes of #5919 .. This will go after #5919 goes in.

**Comment by stephentoub** [comment]
> That is supposed to fail

I'm not saying the problem is that they're failing.  I'm saying it's reporting merge conflicts:
```
GitHub pull request #5770 of commit 7fa5d82a155bde1d6b6d7d6dbbcfb9ff68af8ccf, has merge conflicts.
```
Why is that expected?

**Comment by shrutigarg** [comment]
I don't know why it is coming only in **Ubuntu Debug **..  on other flavors it is fine.. not sure what needs to be done at my end,.

**Comment by vijaykota** [comment]
Closing this since we don't want to pursue the libheimntlm option. The fallback logic here is closely tied to it.

**Pull request closed without merging**
