### PR TITLE
Update BuildToolsVersion.txt

### PR DESCRIPTION
**Pull request by MattGal**
Pick up buildtools changes to allow AnyOS + Currently targeted build to get used for .NET Helix Test execution

### CODE REVIEW

**Comment by MattGal** [comment]
@dotnet-bot test this please

**Comment by MattGal** [comment]
@dotnet-bot test this please

**Comment by mmitche** [comment]
@dotnet-bot test Innerloop CentOS7.1 Release Build and Test

**Comment by joperezr** [comment]
@dotnet-bot test Innerloop CentOS7.1 Debug Build and Test

**Pull request merged**
