### PR TITLE
Enable reflection for DataflowEtwProvider and fix #20592.

### LINKED ISSUE #20592: System.Threading.Tests TestEtw disabled.
System.Threading.Tests -method System.Threading.Tests.EtwTests.TestEtw

Events that should be firing aren't.

### PR DESCRIPTION
**Pull request by AntonLapounov**

### CODE REVIEW

**Comment by jkotas** [comment]
Even better would be to disable reflection blocking for this assembly, so it is treated as ordinary nuget  package. This is ordinary assembly built on top netstandard. It just happens to live corefx. The unnatural gimmicks done for the core framework should not apply to it.

**Comment by AntonLapounov** [comment]
Will create a new PR.

**Comment by brianrob** [comment]
@stephentoub, for my own info, can you comment on when visibility is an issue and we want reflection blocking enabled vs. when we don't?

**Comment by stephentoub** [comment]
> can you comment on when visibility is an issue

If it's public, folks could access it directly, as with any public type.  In many cases there's a contract folks are supposed to reference, but a) not always (sometimes the implementation is what you reference) and b) nothing forces that.  We want to minimize the chances that code will accidentally take a compilation dependency on types that were never meant to be public, that haven't been through API reviews, that we'd like the flexibility to change later, etc.

> and we want reflection blocking enabled vs. when we don't?

See https://github.com/dotnet/corefx/pull/22283#issuecomment-315531146.

**Pull request closed without merging**
