### PR TITLE
Remove dead code from System.Private.DataContractSerialization

### PR DESCRIPTION
**Pull request by alexanderkozlenko**
Remove unused private fields, properties, methods, types, and resource strings.

### CODE REVIEW

**Comment by mellinoe** [comment]
@SGuyGe , @khdang

**Comment by SGuyGe** [comment]
1. What's the purpose of this change? Code cleanup? Or to improve code coverage?
2. How did you determine the dead code in an assembly?

**Comment by alexanderkozlenko** [comment]
1. The purpose of this change is code cleanup, this is related to issue #652.
2. I searched for unused private type members and related resource strings.

**Comment by SGuyGe** [comment]
I see. Searching for unused privates might not be enough though, chances are some might be missed. FxCop would be a better way to identify these as Krzysztof mentioned in #652. 
@krwq: Krzysztof could you share how to run FxCop on NetCore libraries? Is there any difference from running it on desktop .NET?

**Comment by stephentoub** [comment]
@SGuyGe, are you concerned that:
1. Some of the code being removed may not actually be dead.
2. There may be some other dead code that's not being removed here.
3. Both (1) and (2).

If (2), I suggest we go ahead with the PR to clean up at least some dead code, and additional dead code can be removed later (doesn't need to be all or nothing).

If (1) or (3), obviously this shouldn't be merged, but it'd be good to understand why in that case the code is building and tests are passing.

**Comment by SGuyGe** [comment]
@stephentoub My major concern is (2) and I'm less concerned about (1). I agree it doesn't need to be all or nothing. Still, it's good to find out a systematic and reliable approach to do this.

**Comment by stephentoub** [comment]
> Still, it's good to find out a systematic and reliable approach to do this.

Definitely.  I just don't think we should block removing some dead code on such a systematic approach being in place.

**Comment by stephentoub** [comment]
That said, @SGuyGe, you and @khdang should make a call on whether to merge this.

**Comment by SGuyGe** [comment]
LGTM

**Pull request merged**
