### PR TITLE
[release/2.1] Don't close connection for responses to NT auth using 100continue

### LINKED ISSUE #30760: [release/2.1] Expect100Continue with Windows auth and request body > 1024 bytes fails
In this code: https://github.com/dotnet/corefx/blob/7ee84596d92e178bce54c986df31ccc52479e772/src/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/HttpConnection.cs#L534-L549
If the Expect100Continue header is set, and the response code is >= 300 and there's a request body with known length greater than 1024 bytes, if the request body hasn't begun to be sent yet, it sets `_connectionClose` to `true`. When using authentication, the challenge response comes with an HTTP status code of 401. As `(401 >= 300)` evaluates to true, whenever using authentication with request body size > 1024 bytes, `_connectionClose` will be set to `true`. In this code: https://github.com/dotnet/corefx/blob/7ee84596d92e178bce54c986df31ccc52479e772/src/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/AuthenticationHelper.NtAuth.cs#L68-L75
If there was a valid authentication challenge and a response is available to send, a call is made to `HttpConnection.DrainResponseAsync`. In that method: https://github.com/dotnet/corefx/blob/7ee84596d92e178bce54c986df31ccc52479e772/src/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/HttpConnection.cs#L1528-L1531
If `_connectionClose` is true, it throws and aborts the request.  
This is breaking Windows authentication for WCF with requests which are larger than 1024.

### PR DESCRIPTION
**Pull request by davidsh**
Port fix from PR #38744 (.NET Core 3.0) to release/2.1 LTS branch.

Fixes #30760

### CODE REVIEW

**Comment by davidsh** [comment]
#### Description

Sending an HTTP POST/PUT request with more than 1024 bytes to a server that requires enterprise authentication will fail with an exception.

#### Customer Impact

This is blocking key scenarios for enterprise customers including WCF customers which reported this issue.

#### Regression?

Yes from .NET Core 2.0 (and .NET Framework) which didn't use SocketsHttpHandler.

#### Risk

Minimal.

**Comment by davidsh** [comment]
cc: @mconnew @danmosemsft @karelz @stephentoub @wfurt

**Comment by davidsh** [comment]
@dotnet-bot test Outerloop Windows x64 Debug Build
@dotnet-bot test Outerloop Linux x64 Debug Build

**Comment by davidsh** [comment]
@dotnet-bot test Outerloop Windows x64 Debug Build

**Comment by StephenBonikowsky** [comment]
@davidsh What's the status on this PR? Can it be merged?

**Comment by davidsh** [comment]
>@davidsh What's the status on this PR? Can it be merged?

It cannot be merged yet.  It, along with other release/2.1 PRs are waiting for shiproom approval.

**Comment by StephenBonikowsky** [comment]
Ok, thanks.

**Comment by vivmishra** [comment]
Approved for 2.1.13 and 2.2.7

**Pull request merged**
