### PR TITLE
Move Span APIs that allow skipping visibility checks to MemoryMarshal

### PR DESCRIPTION
**Pull request by ahsonkhan**
Resolves https://github.com/dotnet/corefx/issues/27094

**TODO:** Remove AsBytes extension method once all calls have been changed to MemoryMarshal

Depends on the PR from coreclr (along with the mirror PR) - https://github.com/dotnet/coreclr/pull/17087 / https://github.com/dotnet/coreclr/pull/17106. It will fail CI until then.

cc @jkotas, @KrzysztofCwalina, @dotnet/corefxlab-contrib

### CODE REVIEW

**Comment by jkotas** [comment]
@dotnet-bot test this please

**Comment by joshfree** [comment]
```
09:05:16 Build FAILED.
09:05:16 
09:05:16 Perf.Span.BinaryReadAndWrite.cs(29,38): error CS0103: The name 'ReadMachineEndian' does not exist in the current context [D:\j\workspace\windows-TGrou---74aa877a\src\System.Memory\tests\Performance\System.Memory.Performance.Tests.csproj]
09:05:16 Perf.Span.BinaryReadAndWrite.cs(64,38): error CS0103: The name 'ReadMachineEndian' does not exist in the current context [D:\j\workspace\windows-TGrou---74aa877a\src\System.Memory\tests\Performance\System.Memory.Performance.Tests.csproj]
09:05:16     0 Warning(s)
09:05:16     2 Error(s)
09:05:16 
09:05:16 Time Elapsed 00:01:16.06
09:05:16 Command execution failed with exit code 1.
```

**Comment by stephentoub** [comment]
@dotnet-bot test this please

**Comment by ahsonkhan** [comment]
Closing this PR as the commits got cherry-picked into the mirror PR - https://github.com/dotnet/corefx/pull/28384

**Pull request closed without merging**
