### PR TITLE
Backup wiki information before documentation consolidation

### PR DESCRIPTION
**Pull request by carlossanlop**
Before we merge the repos, and potentially lose all the information located in the [wiki](https://github.com/dotnet/corefx/wiki) (the wiki has its own repo), we need to make sure we backup those `*.md` files here.

This is the first step of the documentation consolidation effort I proposed and described here: https://github.com/dotnet/corefx/issues/36057#issuecomment-540237320

I added a `README.md` file to describe the root of the wiki folder, so any visitors know what we're doing.

CC @ViktorHofer @karelz @wtgodbe please review.

Also CC @scalablecory who has been actively modifying [this HTTP2 wiki document](https://github.com/dotnet/corefx/wiki/HTTP-2-Implementation-Status). If you prefer to move this file to another location within the Documentation folder of the corefx repo, please let me know.

### CODE REVIEW

**Comment by jkotas** [comment]
We should not be committing these documents - most of which are outdated and misleading - to master. It is just going to cause confusion.

What is the problem you are trying to solve with this?

**Comment by jkotas** [comment]
> Before we merge the repos, and potentially lose all the information located in the wiki (the wiki has its own repo),

We are not going to lose any of this information. This information is still going to be here in corefx repo.

**Comment by ViktorHofer** [comment]
The CoreFx repo will stay as is and be archived but we still want to disable the wiki feature. That's orthogonal to the merge. I recommend to move necessary over and then disable it. There should not be a need for a backup folder.

**Comment by karelz** [comment]
@ViktorHofer do we have the original wiki content somewhere? It seems only text is here, but pictures are missing :(

**Comment by ViktorHofer** [comment]
Yes, here's the wiki clone: https://microsoft-my.sharepoint.com/:u:/p/vihofer/EfekSugu7JJHrC5_QwEbL_QBOtuFpLDwCI7H2JPrYJ7A0w?e=gxIFvw

**Comment by karelz** [comment]
Awesome, thanks!

**Pull request closed without merging**
