### PR TITLE
Revert changes in PR 7188

### PR DESCRIPTION
**Pull request by mellinoe**
The newest version of MSBuild has fixed the embedded resource culture issue that was preventing us from using periods in embedded resource names. This reverts the changes to the System.Reflection.Metadata tests which removed the periods from some embedded resource file names in the test assembly.

I've validated this locally on my Ubuntu 15.04 box. I'll run the outer-loop tests as well to make sure they work there as well.

@tmat

### CODE REVIEW

**Comment by mellinoe** [comment]
@dotnet-bot Test outerloop Ubuntu14.04 debug

**Comment by mellinoe** [comment]
The Outerloop metadata tests succeeded without issue.

**Comment by stephentoub** [comment]
@dotnet-bot test this please

**Comment by stephentoub** [comment]
Test Innerloop OSX Debug Build and Test please
Test Innerloop OSX Release Build and Test please

**Comment by mmitche** [comment]
@stephentoub I may have found the bug, or at least the trigger point (since the bug shouldn't have shown up).

@dotnet-bot test OuterLoop Ubuntu14.04 Debug

**Comment by mmitche** [comment]
@dotnet-bot test OuterLoop Ubuntu14.04 Debug

**Comment by stephentoub** [comment]
@dotnet-bot test OuterLoop Ubuntu14.04 Debug

**Comment by mellinoe** [comment]
Outerloop tests all passed except for one CompareInfo test (https://github.com/dotnet/corefx/issues/7299).

**Pull request merged**
