### PR TITLE
Extract PlatformDetection to a common test helper

### PR DESCRIPTION
**Pull request by hughbe**
Although PlatformDetection in System.Globalization.Extensions is a subset of PlatformDetection in System.Globalization, there's still duplicated code there. 
Unfortunately, a dependency on System.IO.FileSystem has to be added to System.Globalization.Extensions.Tests, but this is a test project, so isn't such a big deal.

/cc @tarekgh @stephentoub

### CODE REVIEW

**Comment by tarekgh** [comment]
@hughbe, excellent job, thank you. LGTM

**Comment by hughbe** [comment]
Cheers. Im sure there are also other places this can be used in ofher test projects too

**Comment by hughbe** [comment]
Test Innerloop Windows_NT Release Build and Test please
Test Innerloop CentOS7.1 Debug Build and Test please

**Comment by stephentoub** [comment]
Test Innerloop Windows_NT Release Build and Test please
Test Innerloop CentOS7.1 Debug Build and Test please

(service unavailable)

**Comment by stephentoub** [comment]
Test Innerloop Windows_NT Release Build and Test please
Test Innerloop CentOS7.1 Debug Build and Test please

(service unavailable)

**Comment by stephentoub** [comment]
LGTM

**Pull request merged**
