### PR TITLE
Disable SqlClient tests that use TestTdsServer, since TestTdsServer has some issues that can cause connection test timeouts and other failures. (#23453)

### PR DESCRIPTION
**Pull request by corivera**
Porting change to release/uwp6.0. Shiproom approval pending.

### CODE REVIEW

**Comment by danmosemsft** [comment]
```
SqlConnectionBasicTests.cs(27,26): error CS1503: Argument 1: cannot convert from 'System.Type' to 'string' [/mnt/j/workspace/dotnet_corefx/release_uwp6.0/linux-TGroup_netcoreapp+CGroup_Release+AGroup_x64+TestOuter_false_prtest/src/System.Data.SqlClient/tests/FunctionalTests/System.Data.SqlClient.Tests.csproj]
```

**Comment by corivera** [comment]
Looking into test failures

**Comment by corivera** [comment]
@dotnet-bot Test Windows x64 Debug Build please
@dotnet-bot Test Windows x86 Release Build please
@dotnet-bot Test UWP CoreCLR x64 Debug Build please
@dotnet-bot Test Linux x64 Release Build please

**Comment by corivera** [comment]
Tests are failing because of java NullPointerExceptions after some HTTP requests in the Helix workflow.

**Comment by danmosemsft** [comment]
@dotnet/dnceng can you help us figure out why these builds are timing out? Note the `java.lang.NullPointerException` which may not be relevant.

**Comment by ChadNedzlek** [comment]
@danmosemsft There is currently an outage in CI. It will be resolved in a few hours

**Comment by danmosemsft** [comment]
@ChadNedzlek could you send broad email when such outages occur? to .NET and .NET native dev teams for example.

**Comment by mmitche** [comment]
@danmosemsft You were on that mail, though it was not marked as !

**Comment by corivera** [comment]
@dotnet-bot Test Windows x64 Debug Build please
@dotnet-bot Test Windows x86 Release Build please
@dotnet-bot Test UWP CoreCLR x64 Debug Build please
@dotnet-bot Test Linux x64 Release Build please

**Pull request merged**
