### PR TITLE
Add Fedora 23 Badges

### PR DESCRIPTION
**Pull request by ellismg**
Clean up some test issues and add badges.  I did private runs to ensure that outerloop is now clean and once this merges I'll kick new runs on all the Fedora queues to pick up the changes.

### CODE REVIEW

**Comment by ellismg** [comment]
@dotnet-bot test Fedora23 Release Build and Test

**Comment by stephentoub** [comment]
LGTM

**Comment by ellismg** [comment]
@dotnet-bot Test Fedora23 Release Build and Test please (Looks like on each leg a different test failed to talk to the corefx remote testing web server)

**Comment by ellismg** [comment]
@dotnet-bot test OSX Debug Build and Test Please (#8636)

**Comment by joshfree** [comment]
LGTM.  Thanks @ellismg

**Comment by joshfree** [comment]
could you port this to /release/1.0.0 too?

**Pull request merged**
