### PR TITLE
Fix SSE2 and SSE4.1 APIs

### PR DESCRIPTION
**Pull request by fiigii**
Reflect mscorlib change https://github.com/dotnet/coreclr/pull/15160

### CODE REVIEW

**Comment by joperezr** [comment]
@dotnet-bot test this please (coreclr change has been merged)

**Comment by joperezr** [comment]
One thing though, should we add tests for these?

**Comment by fiigii** [comment]
@joperezr Tests are being added in CoreCLR, please see this folder https://github.com/dotnet/coreclr/tree/master/tests/src/JIT/HardwareIntrinsics

**Comment by eerhardt** [comment]
Looks like we will have to wait until the CoreCLR change makes its way over to CoreFX.  I'll retest when I see that happen.

**Comment by fiigii** [comment]
@eerhardt Thank you!

**Comment by jkotas** [comment]
Cherry picked into #25455

**Pull request closed without merging**
