### PR TITLE
add SocketFlags.MaxIOVectorLength

### PR DESCRIPTION
**Pull request by geoffkizer**
Fixes issue #12464.

### CODE REVIEW

**Comment by geoffkizer** [comment]
@CIPop, @ericeil

**Comment by stephentoub** [comment]
@dotnet-bot test this please (Jenkins rebooted)

**Comment by stephentoub** [comment]
What is the expected behavior if MaxIOVectorLength is specified?  Is it the same for Windows and Unix?  Should we add a test for that?

**Comment by geoffkizer** [comment]
@stephentoub It has no effect.  From MSDN:

Provides a standard value for the number of WSABUF structures that are used to send and receive data. This value is not used or supported on .NET Framework 4.5.

[MSDN link](https://msdn.microsoft.com/en-us/library/system.net.sockets.socketflags(v=vs.110).aspx)

On reflection, I do wonder why this isn't just defined as 0, if it does nothing.

**Comment by stephentoub** [comment]
> It has no effect

Have you tried specifying it on Unix? I'd expect based on the current shim that you'd get a not supported exception. If I'm right and it needs to be a nop, that needs to be fixed, and we need a test for it.

> I do wonder why this isn't just defined as 0, if it does nothing.

The option doesn't make sense to begin with. But now that we have it, making it 0 would be a breaking change, e.g. a switch statement that had both it and None would no longer compile.

**Comment by geoffkizer** [comment]
@stephentoub Your point is well taken.  Passing this flag down to platform socket APIs seems like a bad idea.  Even if this works everywhere today (and I haven't tested it everywhere), there's no guarantee it will work in the future.

That said, trying to strip this flag off everywhere before we call into platform APIs seems rather brittle, so that's not a great solution either.

The fact that this flag exists at all seems to be a bug.  See http://blog.stephencleary.com/2010/06/on-lighter-note-socketflagsmaxiovectorl.html.

Given that, I'm inclined to just remove this and accept the breaking change.  

Do we have usage data on this enum value?  I suspect it's virtually nil.

**Comment by stephentoub** [comment]
> Given that, I'm inclined to just remove this and accept the breaking change.

cc: @weshaggard 

>  Passing this flag down to platform socket APIs seems like a bad idea

If it's ignored on Windows, I was actually suggesting we just ignore it on Unix. I believe that would simply mean adding it to this line:
https://github.com/dotnet/corefx/blob/2f27378ea994286fdcb692bd44debe0d18936662/src/Native/Unix/System.Native/pal_networking.cpp#L1599
so that we don't return an ENOTSUP for it.

**Comment by geoffkizer** [comment]
Even on Windows, it's suspect to pass this flag down, since it's not actually a real socket flag.  (It defines the max # of iovecs you can pass to APIs like Send.)

**Comment by stephentoub** [comment]
> Even on Windows, it's suspect to pass this flag down

Sure, but what's the behavior if you do?

**Comment by geoffkizer** [comment]
On Windows, it's ignored.

**Comment by geoffkizer** [comment]
This will be removed from netstandard 2.0 (see discussion above).

**Comment by geoffkizer** [comment]
Netstandard issue: https://github.com/dotnet/standard/issues/82

**Pull request closed without merging**
