### PR TITLE
add QuicConnection.NegotiatedApplicationProtocol stub

### PR DESCRIPTION
**Pull request by geoffkizer**
Based on SslStream.NegotiatedApplicationProtocol

### CODE REVIEW

**Review by stephentoub — APPROVED** [review]
I assume we're going to review the API all-up later.

**Review by Tratcher — APPROVED** [review]
Eventually this will need to expose all of the TLS results currently listed on SslStream. E.g. CipherAlgorithm, CipherStrength, Local & Remote certificate, SslProtocol, etc..

**Review by scalablecory — APPROVED** [review]

**Comment by geoffkizer** [comment]
> Eventually this will need to expose all of the TLS results currently listed on SslStream. E.g. CipherAlgorithm, CipherStrength, Local & Remote certificate, SslProtocol, etc..

Yep.

**Comment by geoffkizer** [comment]
> I assume we're going to review the API all-up later.

Yep. Though if you have feedback on the API, it's good to hear it sooner rather than later.

There is an all-up issue for System.Net.Quic APIs, #42205. I'll add this property over there.

**Pull request merged**
