### PR TITLE
Disable nuget package generation in x-plat builds.

### PR DESCRIPTION
**Pull request by mellinoe**
Temporary workaround for https://github.com/dotnet/corefx/issues/5233.

@ericstj , @weshaggard

### CODE REVIEW

**Comment by mellinoe** [comment]
Part of 5199

**Comment by weshaggard** [comment]
I'm not sure I like where this is going. It is moving in the opposite direction that we want to go which is to build these packages on the native OS's. Is there any other ways to make this work?

**Comment by mellinoe** [comment]
Sure, there are ways to make it work, but those require buildtools changes, etc. which I believe @ericstj is working on. This is currently broken and has been for weeks, so I think we should just disable it for now and we can re-enable it when it works.

**Comment by ericstj** [comment]
I have a buildtools PR already that fixes it. https://github.com/dotnet/buildtools/pull/399

**Comment by mellinoe** [comment]
Okay, I'm fine with waiting for that change as it looks ready to merge already. Sorry that I missed the PR, I thought I had checked buildtools.

**Pull request closed without merging**
