### PR TITLE
Remove temporary shim methods

### PR DESCRIPTION
**Pull request by eerhardt**
Removing the temporary shim methods that were left in to keep the CI running.

Along with this, I needed to bump the runtime version in all the project.json files to the latest.

@ellismg @stephentoub @sokket

### CODE REVIEW

**Comment by ellismg** [comment]
11c4886 concerns me, the version it specifies should be coming from the dotnet-core-rel feed (packages from master are now rc3-XXXXX), but I didn't think we used that feed during restoration.  I'm not really sure how this is working.  @weshaggard Do you know what's going on here?

**Comment by weshaggard** [comment]
@eerhardt can you look at one of your generated project.lock.json files to see which version of the packages these are actually resolving to? In some cases if it cannot find the exact version it pick another closer one.

**Comment by eerhardt** [comment]
> In some cases if it cannot find the exact version it pick another closer one. 

It looked like it was doing just that.  Some of my project.lock.json files had rc3-23720, some had rc2-23712 (the old one that must have been cached).

I updated the version to a real build - rc2-23715.

**Comment by eerhardt** [comment]
@ellismg @weshaggard @stephentoub - is this OK to merge?  I'd like to get these old signatures out of the code base.

**Comment by weshaggard** [comment]
As long as CI stays green I'm good. Is this something we need to try and get in for RC2?

**Comment by eerhardt** [comment]
> Is this something we need to try and get in for RC2?

It doesn't HAVE to be, as there is no external behavior difference. But the reason we changed all the signatures was to ensure the .NetNative build could link all the code together successfully without naming collisions. So it might be good to get it into RC2.

**Comment by ellismg** [comment]
We should take this in for RC2.  CoreRT is going to be picking up RC2 versions of these assemblies and they will not want to see the additional exports.

**Pull request merged**
