### PR TITLE
Port to RC1: Ignore EPIPE errors on Unix when writing to Console

### PR DESCRIPTION
**Pull request by stephentoub**
If you pipe from a managed app to another app that ends (or doesn't exist to begin with), attempting to write to it via Console will throw an exception due to the pipe getting broken.

This commit just changes Console's Write to ignore EPIPE (broken pipe) errors.  For now I still have it throw an other failures, but we could choose to add additional ignored errno values to the list, or simply not throw for anything.

### CODE REVIEW

**Comment by mmitche** [comment]
@dotnet-bot test code formatter check

**Comment by joshfree** [comment]
Thanks @stephentoub. LGTM

**Comment by stephentoub** [comment]
test code formatter check

**Comment by stephentoub** [comment]
test code formatter check

**Pull request merged**
