### PR TITLE
Update build badges to point to release branch.

### PR DESCRIPTION
**Pull request by Priya91**
cc @ellismg @joshfree

### CODE REVIEW

**Comment by ellismg** [comment]
Thanks, Priya.  We will need to rebase this on top of release/1.0.0 once we reset the branch to the final sync point.

**Comment by Priya91** [comment]
@ellismg Sure, there also seems to some problem with netci.. the coreclr artifacts are getting copied from wrong location, branch name is read as release/1.0.0, instead of finding path release_1.0.0.. Investigating..

**Comment by Priya91** [comment]
Port changes to fix failures in CI about not finding coreclr jobs.

**Comment by Priya91** [comment]
@dotnet-bot test ci please

**Comment by Priya91** [comment]
Ok , need another commit from master. Will reopen this PR after master is synced with release

**Pull request closed without merging**
