### PR TITLE
Switch System.Runtime.Extensions to use BitConverter.cs in corefx

### PR DESCRIPTION
**Pull request by stephentoub**
The System.Runtime.Extensions.dll partial facade is currently forwarding to the System.BitConverter class in mscorlib.  This PR changes it to use the BitConverter.cs in corefx.  To help verify nothing broke in doing so, I increased the test coverage for BitConverter.  I also did a bit of code cleanup in the BitConverter.cs file, e.g. using Debug.Assert instead of Contract.Assert, using "string" instead of "String", eliminating some unnecessary branches, ensuring we're including a parameter name in ArgumentExceptions, consolidating how we throw exceptions (matching what's done in mscorlib), etc.

### CODE REVIEW

**Comment by stephentoub** [comment]
cc: @mellinoe

**Comment by ellismg** [comment]
db test this please

**Comment by mellinoe** [comment]
LGTM, there shouldn't be any need to use the one in mscorlib for this.

**Comment by stephentoub** [comment]
Thanks, guys.

**Pull request merged**
