### PR TITLE
Centralize case-sensitive PlatformID checks in FileSystem tests

### PR DESCRIPTION
**Pull request by stephentoub**
Replaces https://github.com/dotnet/corefx/pull/6639 and https://github.com/dotnet/corefx/pull/6620

cc: @ianhays, @krytarowski

### CODE REVIEW

**Comment by ianhays** [comment]
LGTM. I do wonder if this tag might be useful in Common though so it could also potentially be used in other test libraries e.g. Path tests.

**Comment by stephentoub** [comment]
Thanks, Ian.

>  I do wonder

Potentially.  We can clean those up separately, potentially moving this into a central location if it makes sense.  I was mostly interested in having this once per test project rather than once per test... if it's worthwhile to extend it to be once for the whole repo, we can do that, too.

**Comment by stephentoub** [comment]
Test Innerloop OSX Debug Build and Test please

**Comment by krytarowski** [comment]
Thank you!

**Pull request merged**
