### PR TITLE
Adding support for ncurses 6.1 TERM format on System.Console (#27109)

### PR DESCRIPTION
**Pull request by joperezr**
Backporting #27109 to release/1.1.0 branch.

FYI: @stephentoub @danmosemsft @joshfree @Petermarcu

### CODE REVIEW

**Comment by danmosemsft** [comment]
Any more merging beyond what you did for 2.0?

**Comment by joperezr** [comment]
Nope, actually exact same two files, exact same two conflicts, which is why I didn't mention it here either, sorry.

**Comment by danmosemsft** [comment]
OK!

**Comment by joperezr** [comment]
Seems like both OSX builds actually succeeded, they just failed at the step of copying results from the tests.

**Pull request merged**
