### PR TITLE
Add dotnet-core-rel feed info to README.md

### PR DESCRIPTION
**Pull request by stephentoub**
cc: @joshfree, @ellismg

### CODE REVIEW

**Comment by davidsh** [comment]
Do we really publish the final "release" builds here:
www.myget.org/gallery/dotnet-core-rel ?

I thought that feed was the "release candidate" feed for the "release" builds that we actually finally publish to NuGet.  Does the dotnet-core-rel feed get a final "update" when we snap to NuGet?  @joshfree would be best to answer.

**Comment by stephentoub** [comment]
> Do we really publish the final "release" builds here

I was simply choosing a short description.  If you have a suggestion for a better description, I can change it.

**Comment by davidsh** [comment]
Once @joshfree clarifies how the dotnet-rel feed is actually used, then I can suggest revisions. :)

At this point, I raised the question because it is unclear about the timeliness of the packages on that feed.

**Comment by weshaggard** [comment]
CC @ericstj @dagood 
I wouldn't add this to the readme as I suspect we are going to discontinue using it because it was causing us some issues with package clashing in local package caches between our dev and rel feeds.

**Comment by stephentoub** [comment]
Ok, I'll close this then.

**Pull request closed without merging**
