### PR TITLE
Add missing members to SecurityContext

### PR DESCRIPTION
**Pull request by danmosemsft**
Fix https://github.com/dotnet/corefx/issues/18077

### CODE REVIEW

**Comment by danmosemsft** [comment]
Actually @morganbr should we be just no-opping instead of throwing in SecurityContext? Across CAS we no-op everywhere except for `Deny()` which IIRC was the one case where code could expect behavior even on a platform that had CAS disabled.
If you can confirm SecurityContext is not in that category, I"ll make it all no-ops.

**Comment by morganbr** [comment]
I believe SecurityContext is important for flowing impersonation between threads

**Comment by danmosemsft** [comment]
@stephentoub do you concur that it's best for SecurityContext.* to throw?

**Comment by stephentoub** [comment]
I think it makes sense to start by throwing.  We can easily go from throwing-to-nonthrowing in the future if it's deemed important.  And by throwing we minimize any concerns related to security assumptions.

**Comment by morganbr** [comment]
@danmosemsft @stephentoub, how will we handle impersonation if we don't have SecurityContext taking care of it?

**Comment by stephentoub** [comment]
We don't. Impersonation doesn't flow in core.
cc: @kouvel

**Pull request merged**
