### PR TITLE
Moves utilities into the dotnet-ci repo

### PR DESCRIPTION
**Pull request by mmitche**

### CODE REVIEW

**Comment by mmitche** [comment]
test ci please

**Comment by mmitche** [comment]
test code coverage please

**Comment by mmitche** [comment]
@dotnet-bot test code coverage please

**Comment by mmitche** [comment]
@dotnet-bot test ci please

**Comment by stephentoub** [comment]
I see you moved them to https://github.com/dotnet/dotnet-ci/pull/76/files.  LGTM.

**Comment by mmitche** [comment]
test ci please

**Comment by mmitche** [comment]
test ci please

**Comment by mmitche** [comment]
test ci please

**Pull request merged**
