### PR TITLE
Update build tools.  Contains changes to support FreeBSD in xunit.

### PR DESCRIPTION
**Pull request by mmitche**
Float package versions to get the latest version of the netcore extensions (has FreeBSD support)

/cc @jasonwilliams200OK @ericstj

### CODE REVIEW

**Comment by ericstj** [comment]
How'd you do this?  I would have expected to see this diff: https://github.com/ericstj/corefx/commit/af21be2143a27389fd6a610cca17c606744a8d40

**Comment by jasonwilliams200OK** [comment]
Thanks @mmitche! :+1: 
@ghuntley, after this is merged, someone can take a stab at https://github.com/dotnet/corefx/issues/1626#issuecomment-112572984.

**Comment by mmitche** [comment]
Deleted every project.lock.json then restored them with /t:RestorePackages /p:LockDependencies=true.  I couldn't see any other way to unlock them to float them.

**Comment by mmitche** [comment]
@ericstj This is because I wasn't quite at the head of the upstream tree when I did the change.  Let me redo this.

**Comment by mmitche** [comment]
Added a few extra, including the System.Net.Http lock update for the extensions

**Comment by ericstj** [comment]
That looks better.

You don't actually need to delete them.  You just need to run build /t:RestorePackages /p:LockDependencies=true.  

It looks like this deleted src/System.Net.Http/tests/UnitTests/project.lock.json. I think that is OK and just a cleanup from https://github.com/dotnet/corefx/commit/36b6d6bfffe8e4994820109636af96cb9e6f39cb.

:shipit:

**Pull request merged**
