### PR TITLE
Remove special-cases tests TKey string Dictionary<TKey,TValue>

### PR DESCRIPTION
**Pull request by MarcoRossignoli**
Contributes #26033 

@maryamariyan is there other places where remove?

@jkotas wrote "Wait for the matching corefx change to go through as well."

Is there a way to understand when CI will use new CoreCLR?

### CODE REVIEW

**Comment by stephentoub** [comment]
> Is there a way to understand when CI will use new CoreCLR?

When new builds are available, you'll see "auto-update PRs" to get created by @dotnet-maestro-bot:
https://github.com/dotnet/corefx/pulls?utf8=%E2%9C%93&q=is%3Apr+author%3Adotnet-maestro-bot

**Comment by stephentoub** [comment]
@dotnet-bot test this please

**Comment by MarcoRossignoli** [comment]
@dotnet-bot test UWP CoreCLR x64 Debug Build

**Comment by MarcoRossignoli** [comment]
@dotnet-bot test UWP CoreCLR x64 Debug Build

**Comment by jkotas** [comment]
UWP leg failure is expected (#26802)

**Comment by jkotas** [comment]
@MarcoRossignoli Thanks!

**Pull request merged**
