### PR TITLE
Add Narrow, Widen, and Conversion methods to System.Numerics.Vectors.

### PR DESCRIPTION
**Pull request by mellinoe**
This exposes the new functions approved in #15957 .

@sivarv , @CarolEidt , @benaadams

### CODE REVIEW

**Comment by benaadams** [comment]
> System.OverflowException : Arithmetic operation resulted in an overflow.

**Comment by saucecontrol** [comment]
It's great to see these implemented.  Is the intrinsic support already in RyuJIT, or are there cases where `Vector.IsHardwareAccelerated` would return true but these methods would run the C# implementation?

**Comment by mellinoe** [comment]
@saucecontrol The RyuJIT work is still ongoing; I'm not sure which parts have been merged in already and which parts are still in progress. See https://github.com/dotnet/coreclr/issues/9317

**Comment by mellinoe** [comment]
Merging this to help out the JIT folks implementing the intrinsics.

**Pull request merged**
