### PR TITLE
Cleanup Negative tests for KoreanCalendar

### PR DESCRIPTION
**Pull request by hughbe**
- Remove duplicate tests
- Stop using random data that really confuses the code

### CODE REVIEW

**Comment by hughbe** [comment]
Contributes to #2336

**Comment by stephentoub** [comment]
@hughbe, should I assume that this PR is going to be completely overhauled with the CalendarHelper from the ThaiBuddhistCalendar PR and that this can be closed in the meantime?

**Comment by hughbe** [comment]
You probably don't need to close it - I'll rebase it once #6696  is merged.

Also, KoreanCalendar has more tests than ThaiBuddistCalendar, so I might need to change CalendarHelpers a little bit

**Comment by stephentoub** [comment]
> I'll rebase it once #6696 is merged

It's not just rebasing, though, right?  Won't most of it change based on rewriting it to use CalendarHelpers?  And until that happens, this PR shouldn't be reviewed because it's not what the change would actually be?

**Comment by hughbe** [comment]
Fair

**Pull request closed without merging**
