### PR TITLE
OpenCover performance improvements

### PR DESCRIPTION
**Pull request by sawilde**
As discussed here https://github.com/OpenCover/opencover/issues/268 when dealing with System.Linq.Parallel tests

### CODE REVIEW

**Comment by stephentoub** [comment]
Thanks, Shaun.  Two things:

1) The version number in the ```src\.nuget\packages.config``` file also needs to be updated:
https://github.com/dotnet/corefx/blob/master/src/.nuget/packages.config#L4

2) I'm seeing several AVs now, in other tests.  There does seem to be something wrong with OpenCover that's causing these.  Here's an example from the log:

```
 Discovering: System.Diagnostics.TextWriterTraceListener.Tests
  Discovered:  System.Diagnostics.TextWriterTraceListener.Tests
  Starting:    System.Diagnostics.TextWriterTraceListener.Tests

  Unhandled Exception: Unhandled Exception: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
     at System.Diagnostics.DelimitedListTraceListener..ctor(TextWriter writer)
     at System.Diagnostics.TextWriterTraceListenerTests.DelimiterWriteMethodTests.RunTest()
     --- End of inner exception stack trace ---
     at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
     at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
     at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
     at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
     at Xunit.Sdk.TestInvoker`1.<>c__DisplayClassc.<<InvokeTestMethodAsync>b__9>d__e.MoveNext()
     at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[TStateMachine](TStateMachine& stateMachine)
     at Xunit.Sdk.TestInvoker`1.<>c__DisplayClassc.<InvokeTestMethodAsync>b__9()
     at Xunit.Sdk.ExecutionTimer.<AggregateAsync>d__0.MoveNext()
     at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[TStateMachine](TStateMachine& stateMachine)
     at Xunit.Sdk.ExecutionTimer.AggregateAsync(Func`1 asyncAction)
     at Xunit.Sdk.TestInvoker`1.<>c__DisplayClassc.<InvokeTestMethodAsync>b__8()
     at Xunit.Sdk.ExceptionAggregator.<RunAsync>d__0.MoveNext()
     at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[TStateMachine](TStateMachine& stateMachine)
     at Xunit.Sdk.ExceptionAggregator.RunAsync(Func`1 code)
     at Xunit.Sdk.TestInvoker`1.<InvokeTestMethodAsync>d__17.MoveNext()
     at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](TStateMachine& stateMachine)
     at Xunit.Sdk.TestInvoker`1.InvokeTestMethodAsync(Object testClassInstance)
     at Xunit.Sdk.TestInvoker`1.<<RunAsync>b__0>d__4.MoveNext()
     at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](TStateMachine& stateMachine)
     at Xunit.Sdk.TestInvoker`1.<RunAsync>b__0()
     at Xunit.Sdk.ExceptionAggregator.<RunAsync>d__3`1.MoveNext()
     at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](TStateMachine& stateMachine)
     at Xunit.Sdk.ExceptionAggregator.RunAsync[T](Func`1 code)
     at Xunit.Sdk.TestInvoker`1.RunAsync()
     at Xunit.Sdk.XunitTestRunner.<InvokeTestMethodAsync>d__6.MoveNext()
     at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](TStateMachine& stateMachine)
     at Xunit.Sdk.XunitTestRunner.InvokeTestMethodAsync(ExceptionAggregator aggregator)
     at Xunit.Sdk.XunitTestRunner.<InvokeTestAsync>d__0.MoveNext()
     at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](TStateMachine& stateMachine)
     at Xunit.Sdk.XunitTestRunner.InvokeTestAsync(ExceptionAggregator aggregator)
     at Xunit.Sdk.TestRunner`1.<>c__DisplayClass3.<RunAsync>b__1()
     at Xunit.Sdk.ExceptionAggregator.<RunAsync>d__3`1.MoveNext()
     at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](TStateMachine& stateMachine)
     at Xunit.Sdk.ExceptionAggregator.RunAsync[T](Func`1 code)
     at Xunit.Sdk.TestRunner`1.<RunAsync>d__5.MoveNext()
     at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](TStateMachine& stateMachine)
     at Xunit.Sdk.TestRunner`1.RunAsync()
     at Xunit.Sdk.XunitTestCaseRunner.RunTestAsync()
     at Xunit.Sdk.TestCaseRunner`1.<RunAsync>d__0.MoveNext()
     at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](TStateMachine& stateMachine)
     at Xunit.Sdk.TestCaseRunner`1.RunAsync()
     at Xunit.Sdk.XunitTestCase.RunAsync(IMessageBus messageBus, Object[] constructorArguments, ExceptionAggregator aggregator, CancellationTokenSource cancellationTokenSource)
     at Xunit.Sdk.XunitTestMethodRunner.RunTestCaseAsync(IXunitTestCase testCase)
     at Xunit.Sdk.TestMethodRunner`1.<RunTestCasesAsync>d__4.MoveNext()
     at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](TStateMachine& stateMachine)
     at Xunit.Sdk.TestMethodRunner`1.RunTestCasesAsync()
     at Xunit.Sdk.TestMethodRunner`1.<RunAsync>d__0.MoveNext()
     at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](TStateMachine& stateMachine)
     at Xunit.Sdk.TestMethodRunner`1.RunAsync()
     at Xunit.Sdk.XunitTestClassRunner.RunTestMethodAsync(ITestMethod testMethod, IReflectionMethodInfo method, IEnumerable`1 testCases, Object[] constructorArguments)
     at Xunit.Sdk.TestClassRunner`1.<RunTestMethodsAsync>d__9.MoveNext()
     at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](TStateMachine& stateMachine)
     at Xunit.Sdk.TestClassRunner`1.RunTestMethodsAsync()
     at Xunit.Sdk.TestClassRunner`1.<RunAsync>d__2.MoveNext()
     at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](TStateMachine& stateMachine)
     at Xunit.Sdk.TestClassRunner`1.RunAsync()
     at Xunit.Sdk.XunitTestCollectionRunner.RunTestClassAsync(ITestClass testClass, IReflectionTypeInfo class, IEnumerable`1 testCases)
     at Xunit.Sdk.TestCollectionRunner`1.<RunTestClassesAsync>d__7.MoveNext()
     at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](TStateMachine& stateMachine)
     at Xunit.Sdk.TestCollectionRunner`1.RunTestClassesAsync()
     at Xunit.Sdk.TestCollectionRunner`1.<RunAsync>d__0.MoveNext()
     at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](TStateMachine& stateMachine)
     at Xunit.Sdk.TestCollectionRunner`1.RunAsync()
     at Xunit.Sdk.XunitTestAssemblyRunner.RunTestCollectionAsync(IMessageBus messageBus, ITestCollection testCollection, IEnumerable`1 testCases, CancellationTokenSource cancellationTokenSource)
     at Xunit.Sdk.XunitTestAssemblyRunner.<>c__DisplayClassb.<>c__DisplayClassd.<RunTestCollectionsAsync>b__2()
     at System.Threading.Tasks.Task`1.InnerInvoke()
     at System.Threading.Tasks.Task.Execute()
     at System.Threading.Tasks.Task.ExecutionContextCallback(Object obj)
     at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
     at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
     at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
     at System.Threading.Tasks.Task.ExecuteEntry(Boolean bPreventDoubleExecution)
     at System.Threading.Tasks.SynchronizationContextTaskScheduler.PostCallback(Object obj)
     at Xunit.Sdk.MaxConcurrencySyncContext.<>c__DisplayClass3.<WorkerThreadProc>b__2(Object _)
     at System.Threading.ExecutionContext.Run(ExecutionContext context, Action`1 callback, Object state)
     at Xunit.Sdk.MaxConcurrencySyncContext.WorkerThreadProc()
     at System.Threading.Tasks.Task.InnerInvoke()
     at System.Threading.Tasks.Task.Execute()
     at System.Threading.Tasks.Task.ExecutionContextCallback(Object obj)
     at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
     at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
     at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
     at System.Threading.Tasks.Task.ExecuteEntry(Boolean bPreventDoubleExecution)
     at System.Threading.Tasks.ThreadPoolTaskScheduler.LongRunningThreadWork(Object obj)
     at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
     at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
     at System.Threading.ThreadHelper.ThreadStart(Object obj)
```

**Comment by sawilde** [comment]
Thanks

Hmmm - may need to try without the -oldstyle flag then

**Comment by sawilde** [comment]
Okay I get no exceptions with or without the `-oldstyle` flag whilst using the nuget package.

**Comment by stephentoub** [comment]
Thanks, Shaun.  I'll see if there's any way to get a more stable repro.  Thus far I've only been able to reproduce this particular case of it in the lab (hence my "Do not merge" PRs).  I've been able to consistently reproduce the AV with the Process tests, however... I do wonder if they're the same root cause.

**Comment by stephentoub** [comment]
I'm going to go ahead and merge this.  I don't think the AVs are coming from this update; if anything to do with OpenCover, I think they're from before this update, and since this brings perf improvements and it'll be easier to diagnose any potential issues while using the latest version, I'm going to merge this in.  Thanks, Shaun.

**Comment by sawilde** [comment]
I also had a look and felt but couldn't identify anything I used with and without the `-oldstyle` switch.

I managed to get it to repeat but not consistently so I don't think it is instrumentation related. 

I then had a look at the tests and the process being used as a target and I am thinking the overhead of the profiler on the target app during the test is introducing a race condition - Kill is quite vicious and sometimes the runtime does not call `::Shutdown` along the way (this is one of the reasons I used the shared buffer). If we don't need to profile the test app we could disable the profiling of it by setting `Cor_Enable_Profiling` to 0 (which I believe you have done so in the past. I also noted that if I changed the [Sleep](https://github.com/dotnet/corefx/blob/master/src/System.Diagnostics.Process/tests/ProcessTest_ConsoleApp/ProcessTest_ConsoleApp.cs#L44) to 1000d then I couldn't repeat as often.

In the meantime I'll look into adding an exclude process filter to OpenCover - something I've needed in the past but these tests are an exception.

I also note that the tests sometimes have their expect/actual incorrectly swapped around which leads to some odd outputs when they do fail.

**Pull request merged**
