### PR TITLE
Add regression test for dotnet/coreclr#2531

### PR DESCRIPTION
**Pull request by ellismg**
Ensure that en-US-POSIX does not get Turkish casing behavior.

### CODE REVIEW

**Comment by ellismg** [comment]
This will fail on Unix until dotnet/coreclr#2548 has been merged.

**Comment by mellinoe** [comment]
LGTM

**Comment by stephentoub** [comment]
LGTM

**Comment by ellismg** [comment]
@dotnet-bot test this please (pick up coreclr with fix)

**Pull request merged**
