### PR TITLE
[Release/3.1] Enable closure testing for 3.1

### PR DESCRIPTION
**Pull request by Anipik**
@wtgodbe is 3.1 branch open for changes ?

### CODE REVIEW

**Review by safern — APPROVED** [review]

**Comment by wtgodbe** [comment]
The branch is still closed for preview3. If this is approved for GA I’ll merge it on Friday, otherwise it’ll get merged for 3.1.1 in a couple of weeks

**Comment by ericstj** [comment]
@wtgodbe this is test only so I don't think it needs approval.

**Comment by wtgodbe** [comment]
Will merge Monday morning with the other GA changes

**Comment by safern** [comment]
@Anipik @wtgodbe @ericstj I added my port for: https://github.com/dotnet/corefx/pull/42496 here in: 1b0e47379f94a79f156fbe32187b38527382b79d

I had to add it here because these two PRs conflicted, so it was easier to just push here and merge 1 PR without having to merge conflicts.

**Pull request merged**
