### PR TITLE
Throw NullReferenceException for field dereferences in expression interpreter

### PR DESCRIPTION
**Pull request by bartdesmet**
This fixes issue #3217.

Note: I'm experiencing issues running tests reliably when specifying "/p:IsInterpreting=true" for the build of System.Linq.Expressions. Also, should we add a RegressionTests.cs file with the name of test methods referring to the issues here in GitHub, or should we add the tests to the proper file (most of which seem machine-generated, so that may cause issues).

### CODE REVIEW

**Comment by stephentoub** [comment]
cc: @VSadov

**Comment by VSadov** [comment]
@bartdesmet  code changes look good
in other projects (like Roslyn), we just add regular tests and add an attribute like 

```
        [Fact, WorkItem(4471, "https://github.com/dotnet/roslyn/issues/4471")]
```

I think we should start similar practice here.

**Comment by VSadov** [comment]
Note that Jenkins will not run interpreter right now. I do not know yet what would be the best way to enable that. 
It is tracked by https://github.com/dotnet/corefx/issues/2756 
Need to do changes like this, raise the importance of that workitem.

**Comment by stephentoub** [comment]
@dotnet-bot test this please

**Comment by VSadov** [comment]
Fixes #3217

**Pull request merged**
