### PR TITLE
Disable regex cache tests using reflection for uapaot

### PR DESCRIPTION
**Pull request by ViktorHofer**
Fixes https://github.com/dotnet/corefx/issues/29019

& remove dead code I overlooked last time.

### CODE REVIEW

**Comment by ViktorHofer** [comment]
cc @artkpv

**Comment by ViktorHofer** [comment]
@dotnet-bot test NETFX x86 Release Build

_please do not merge yet, I need to quickly verify the fix locally_

**Comment by MichalStrehovsky** [comment]
Is the RD.XML really needed after the change in `Regex.Cache.Tests.cs`? The .NET Native compiler should be able to see through this usage and do the metadata enablement for you (we do analyze both the `typeof` and the `GetField` with an obvious string passed to it).

**Comment by ViktorHofer** [comment]
the tests started failing directly after we merged the change into master and it points to the code line where we use reflection. I'm pretty sure that's the reason for the failing test. Can verify later.

**Comment by MichalStrehovsky** [comment]
I was referring to the deletion of the `string cacheFieldName = PlatformDetection.IsFullFramework ? "cacheSize" : "s_cacheCount";` line - I don't think the compiler was able to analyze that the following line is going to reflect on `Regex.s_cacheCount", but the change you're doing now should make this pretty analyzable. If the RD.XML is still needed with that change, I would consider it a compiler bug.

**Comment by ViktorHofer** [comment]
I see. Let me test that change. Thanks

**Comment by ViktorHofer** [comment]
@MichalStrehovsky neither with the rd.xml nor without I still get the NullReferenceException. Any idea what's happening here? `.GetField("s_cacheCount", BindingFlags.NonPublic | BindingFlags.Static)` returns null. Is there anything else required for static fields?

**Comment by MichalStrehovsky** [comment]
Oh, wait. I was assuming the RD.XML actually worked :).

If the `Regex` type is the actual Regex type from the framework and this is trying to reflect on a nonpublic field on it, this won't work with .NET Native.

We block reflection on nonpublic framework API surface to save disk space. Not generating metadata for these (storing the names, offsets, and types of fields) results in nice savings.

**Comment by ViktorHofer** [comment]
> If the Regex type is the actual Regex type from the framework and this is trying to reflect on a nonpublic field on it, this won't work with .NET Native.

I thought that by putting the field and type into the rd.xml its metadata won't be removed... Am I missing something here?

**Comment by MichalStrehovsky** [comment]
> I thought that by putting the field and type into the rd.xml its metadata won't be removed...

I don't know much about CoreFX build, but I think by default CoreFX assemblies opt into reflection blocking. Internal implementation details of the assemblies can never be opted into reflection. This is controlled by the `BlockReflectionAttribute` MSBuild property. The blocking policy trumps RD.XML for several reasons. It's an important size optimization, so I would suggest just disabling the test on UAPAOT (we really don't want to take the size on disk regression from allowing metadata generation just to make tests work).

**Comment by ViktorHofer** [comment]
I see. I agree, disabling the tests seems appropriate here.

**Comment by ViktorHofer** [comment]
@dotnet-bot test OSX x64 Debug Build

**Comment by ViktorHofer** [comment]
Unrelated test failures. Merging.

**Pull request merged**
