### PR TITLE
Update package versions to rc3-23727

### PR DESCRIPTION
**Pull request by stephentoub**

### CODE REVIEW

**Comment by ericstj** [comment]
We should start doing this regularly with @dotnet-bot, similar to the mirror.  Each time there is a new set of packages run the update and submit a PR.  If it is green we merge it. Seem reasonable?   /cc @dagood

**Comment by stephentoub** [comment]
Yes, please!  I believe @weshaggard was investigating something similar.

**Comment by dagood** [comment]
Yep, Wes asked me a few questions about automated package publish last week to start getting that set up. I don't see any problems with the idea.

**Comment by stephentoub** [comment]
(OS X runs failing due to https://github.com/dotnet/corefx/issues/5732)

**Comment by weshaggard** [comment]
Yes I'm looking into this I have a local script working but haven't had the chance to integrate it into the package publishing automation yet. Also I've been mostly focused on doing that for the release branch but I can look into it for the dev branch as well.

**Pull request merged**
