### PR TITLE
Correct ArgumentOutOfRangeException on out of range block expression index

### LINKED ISSUE #3881: Block.Expressions sometimes throws incorrect exception on out-of-range
Given:

    BlockExpression block = Expression.Block(Expression.Empty(), Expression.Constant(3));

One would expect `block.Expressions[-1]`, `block.Expressions[2]`, etc. to throw `ArgumentOutOfRangeException`. Instead they throw `InvalidOperationException`.

This depends on the factory used, so some cases will throw the correct exception, which is perhaps worse as this is then inconsistent.

### PR DESCRIPTION
**Pull request by JonHanna**
Fixes #3881

### CODE REVIEW

**Comment by stephentoub** [comment]
@dotnet-bot test this please (FindPackagesById errors)

**Comment by JonHanna** [comment]
@dotnet-bot test this, please.

**Comment by JonHanna** [comment]
Test Innerloop Windows_NT Release Build and Test

**Comment by stephentoub** [comment]
The mechanics of this change LGTM.

But, @VSadov, is this something we want to change, i.e. do we want to change the exception type used here?

**Comment by JonHanna** [comment]
Aside from `ArgumentOutOfRangeException` seeming the natural choice in terms of how it is normally used, it currently is the exception thrown here in some cases, depending on which factory was used to produce the `BlockExpression`. I think that inconsistency is worse than whether the type thrown is considered incorrect.

**Comment by VSadov** [comment]
I think dependencies on actual exception type in a case of an error is uncommon so this is unlikely to be breaking. There are some advantages in being consistent though.
LGTM

**Pull request merged**
