### PR TITLE
Fix compile assembly on netfx for crypto-xml

### PR DESCRIPTION
**Pull request by krwq**
Fixes: https://github.com/dotnet/corefx/issues/19420

### CODE REVIEW

**Comment by danmosemsft** [comment]
@krwq you have to add references like
```
  <ItemGroup Condition="'$(IsPartialFacadeAssembly)'  == 'true'">
    <Reference Include="mscorlib" />
    <Reference Include="System" />
    <Reference Include="System.Core" />
    <Reference Include="System.Xml" />
  </ItemGroup>

```
similar to what was done in 45402b53fb2a53e7c9b0b8e818aa0f5349714786

**Comment by danmosemsft** [comment]
I pushed what I think is the fix...

**Comment by danmosemsft** [comment]
@dotnet-bot test innerloop OSX10.12 Debug x64 Build and Test please (https://github.com/dotnet/corefx/issues/19435)

**Comment by krwq** [comment]
Thank you @danmosemsft! It's slightly mysterious to me how are you able to push to my fork though 😉 (are PR branches open to collaborators of master repo?)

**Comment by danmosemsft** [comment]
@krwq by default, any collaborator can push to a PR. There's a setting somewhere to flip that, not sure where. But it's very handy!

**Pull request merged**
