### PR TITLE
Port fix to NRE when regex MatchEvaluator returns null

### PR DESCRIPTION
**Pull request by danmosemsft**
Fixes https://github.com/dotnet/corefx/pull/39779

Porting to 3.0 because this is a regression from .NET Framework and from previous .NET Core releases, and it may be fairly common to return null from a MatchEvaluator.

### CODE REVIEW

**Comment by danmosemsft** [comment]
@mattgal seems like the same issue again in this job.
```
/Users/vsts/agent/2.154.3/work/1/s/.packages/microsoft.dotnet.helix.sdk/2.0.0-beta.19365.4/tools/Microsoft.DotNet.Helix.Sdk.MultiQueue.targets(67,5): error : Work item System.Xml.Xsl.XslTransformApi.Tests in job 79272534-5108-47eb-a2fe-d357505786e0 has failed, logs available here: https://helix.dot.net/api/2018-03-14/jobs/79272534-5108-47eb-a2fe-d357505786e0/workitems/System.Xml.Xsl.XslTransformApi.Tests/console. [/Users/vsts/agent/2.154.3/work/1/s/eng/sendtohelix.proj]
##[error].packages/microsoft.dotnet.helix.sdk/2.0.0-beta.19365.4/tools/Microsoft.DotNet.Helix.Sdk.MultiQueue.targets(67,5): error : (NETCORE_ENGINEERING_TELEMETRY=) Work item System.Xml.Xsl.XslTransformApi.Tests in job 79272534-5108-47eb-a2fe-d357505786e0 has failed, logs available here: https://helix.dot.net/api/2018-03-14/jobs/79272534-5108-47eb-a2fe-d357505786e0/workitems/System.Xml.Xsl.XslTransformApi.Tests/console.
```

**Comment by danmosemsft** [comment]
Still failing. I am going to merge this on the basis that (1) it is very unlikely there is a mac specific issue and (2) the same leg passed with this change in master.

**Comment by MattGal** [comment]
@danmosemsft I'm continuing to search for the rogue machine, apologies.

**Comment by MattGal** [comment]
@danmosemsft  / @ilyas1974 we'll pick this up again next week, I have not found the naughty mac yet (as whichever machine this is seems to be a black hole of data :( )

**Comment by danmosemsft** [comment]
Sure, thanks @mattgal

**Pull request merged**
