### PR TITLE
[WIP - do not merge] SSL Alerts

### PR DESCRIPTION
**Pull request by CIPop**
This is a prototype, not fully tested for the implementation of TLS Alerts.
The prototype requires that a new API is added to System.Net.Security (currently 4.0.0.0, netstandard1.3):

``` 
public virtual System.Threading.Tasks.Task ShutdownAsync();
```

There are other APIs planned to be added to this contract.

@ericstj @weshaggard is there documentation other contract examples in this situation? 
I believe that I need to switch the version to 4.1.0 first but I'm not entirely sure what changes are required for the builds and .pkgproj for this to build.

/cc: @davidsh @stephentoub

### CODE REVIEW

**Comment by CIPop** [comment]
Currently, build is failing with:

```
"S:\c2\src\system.net.security\System.Net.Security.sln" (rebuild target) (1) ->
"S:\c2\src\system.net.security\tests\FunctionalTests\System.Net.Security.Tests.csproj" (Rebuild target) (4) ->
"S:\c2\src\system.net.security\pkg\System.Net.Security.pkgproj" (GetPackageAssets target) (5:2) ->
"S:\c2\src\system.net.security\src\System.Net.Security.builds" (Build target) (6) ->
"S:\c2\src\system.net.security\src\System.Net.Security.csproj" (Build target) (3:4) ->
(ValidateApiCompatForSrc target) ->
  S:\c2\Tools\ApiCompat.targets(55,5): error : MembersMustExist : Member 'System.Net.Security.SslStream.ShutdownAsync()' does no
t exist in the implementation but it does exist in the contract. [S:\c2\src\system.net.security\src\System.Net.Security.csproj]
  S:\c2\Tools\ApiCompat.targets(69,5): error : ApiCompat failed for 'S:\c2\bin\Windows_NT.AnyCPU.Debug\System.Net.Security\net46
\System.Net.Security.dll' [S:\c2\src\system.net.security\src\System.Net.Security.csproj]


"S:\c2\src\system.net.security\System.Net.Security.sln" (rebuild target) (1) ->
"S:\c2\src\system.net.security\tests\FunctionalTests\System.Net.Security.Tests.csproj" (Rebuild target) (4) ->
(ResolvePkgProjReferences target) ->
  S:\c2\Tools\PackageLibs.targets(34,5): error : Could not locate compile assets for any of the frameworks .NETStandard,Version=
v1.3 [S:\c2\src\system.net.security\tests\FunctionalTests\System.Net.Security.Tests.csproj]
```

**Comment by davidsh** [comment]
One of the things you need to do when rev'ing a contract is to create a new sub-folder in the ref folder.  That subfolder needs to contain the previous contract.

So, while you added to new API to the contract by modifing this file:
src/System.Net.Security/ref/System.Net.Security.cs

You need to create a new subfolder named "4.0" under the ref folder.  And in that folder, you need to have the old contract (*.CS file) as well as a CSPROJ, etc.

Take a look at the System.Net.Http\ref folder and you'll see this.  We have the current 4.1 contract but there is also a 4.0 subfolder.

**Comment by davidsh** [comment]
Another suggestion is to not have this PR have any new API surface in it.  Instead, have a separate PR that only adds the new API but is just a stub implementation.  Then that PR can just have all the magic contract revision, pkgproj, builds files, etc.  Having a separate (small) PR that only deals with "new API surface" might make it easier to work thru the build issues.

**Comment by CIPop** [comment]
@davidsh Sure, I could do that next week.

Added an attempt to switch to netstandard1.6. Now I'm getting a different error:
```
S:\c2\Tools\PackageLibs.targets(213,5): error : Expected version 4.1.0.0 for referenced assembly S:\c2\packages\System.Security.Cryptography.Algorithms\4.2.0\ref\netstandard1.6\System.Security.Cryptography.Algorithms.dll but found 4.2.0.0 [S:\c2\src\system.net.security\ref\System.Net.Security.csproj]
```

[msbuild.log.txt](https://github.com/dotnet/corefx/files/440367/msbuild.log.txt)

**Comment by CIPop** [comment]
Closing the test PR. Will submit another with just the API changes.

**Pull request closed without merging**
