### PR TITLE
Avoid array allocations in HttpStatusDescription

### PR DESCRIPTION
**Pull request by jamesqo**
Currently, `HttpStatusDescription` in `Common` allocates a static array to map status codes to messages. I've replaced it with a giant switch-case statement that both 1) takes less lines of code and 2) is self explanatory (doesn't need comments explaining what code the message represents).

Script used to generate the output: https://gist.github.com/jamesqo/78121659bb7b555ac63ecc05f0e7b4de

cc @davidsh @stephentoub

### CODE REVIEW

**Comment by svick** [comment]
I think a newline between each hundred-group of error codes would make the switch easier to read.

**Comment by stephentoub** [comment]
@jamesqo, please share the performance benchmark you used to determine that this is a good change.

**Comment by jamesqo** [comment]
@stephentoub Sure thing. I made this program:

```cs
namespace ConsoleApplication3
{
    class Program
    {
        static void Main(string[] args)
        {
            for (int i = 0; i < 10; i++)
            {
                var message = new HttpResponseMessage();
                var watch = Stopwatch.StartNew();
                for (int j = 0; j < 1000000; j++)
                    GC.KeepAlive(message.ReasonPhrase);
                watch.Stop();
                Console.WriteLine(watch.Elapsed);
            }
        }
    }
}
```

After copy + pasting the `HttpResponseMessage` and `HttpStatusDescription` sources into the program, it prints this with the old implementation:

```
00:00:00.0360351
00:00:00.0318233
00:00:00.0306154
00:00:00.0303426
00:00:00.0304112
00:00:00.0302535
00:00:00.0302189
00:00:00.0305473
00:00:00.0318460
00:00:00.0305403
```

and this with the new one:

```
00:00:00.0175427
00:00:00.0168561
00:00:00.0169085
00:00:00.0170549
00:00:00.0170290
00:00:00.0191854
00:00:00.0190455
00:00:00.0190272
00:00:00.0192135
00:00:00.0198547
```

[Here's](https://github.com/dotnet/corefx/blob/master/src/System.Net.Http/src/System/Net/Http/HttpResponseMessage.cs#L86) the line where this method is being used right now in `HttpResponseMessage`.

**Comment by stephentoub** [comment]
Test Innerloop OSX Debug Build and Test please

**Comment by stephentoub** [comment]
Thanks. LGTM.

**Comment by davidsh** [comment]
LGTM

**Comment by danmosemsft** [comment]
This compiles to separate switch statements for each contiguous block. I'm impressed.

**Pull request merged**
