### PR TITLE
Reset reader awaitable when resetting pipe

### LINKED ISSUE #31176: Resetting Pipe does not reset reader and writer awaitables
Resetting a Pipe object through Pipe.Reset does not reset reader and writer awaitables. This leads to inconsistent behavior where before resetting, read methods return false or return tasks which complete when the writer is flushed; instead, after resetting, read methods return empty buffers if no data is available.

New pipe:
complete
As you can see, the `_readerAwaitable`'s IsCompleted property is false

Completed pipe:
reset
Upon completing the pipe, IsCompleted is now true as expected

Reset pipe:
completed
After resetting the pipe, IsCompleted is still true

### PR DESCRIPTION
**Pull request by ObsidianMinor**
Fixes #31176

### CODE REVIEW

**Comment by davidfowl** [comment]
Should we also reset the writerAwaitable?

**Comment by ObsidianMinor** [comment]
No, resetting both reader and writer awaitables puts the Pipe in an invalid state where neither the reader or writer are completed (which causes a deadlock if you try to read or write). All that is required is that the reader is put back into the non-completed state like when the Pipe is first constructed.

**Comment by pakrym** [comment]
It may be better to call constructors of both awaiters same way we do in pipe constructor.

**Comment by davidfowl** [comment]
Thanks!

**Pull request merged**
