### PR TITLE
Increase timeout for 2 socket option name tests

### PR DESCRIPTION
**Pull request by danmosemsft**
These two time out on UWP F5 runs about 4-5 times a week for some time. Changing 20 sec to 30 sec timeout to see whether that helps.

https://mc.dot.net/#/product/netcore/30/source/official~2Fdotnet~2Fcorefx~2Frefs~2Fheads~2Fmaster/type/test~2Ffunctional~2Fuwp~2F/build/20190328.7/workItem/System.Net.Sockets.Tests/analysis/xunit/System.Net.Sockets.Tests.SocketOptionNameTest~2FMulticastInterface_Set_AnyInterface_Succeeds

https://mc.dot.net/#/product/netcore/30/source/official~2Fdotnet~2Fcorefx~2Frefs~2Fheads~2Fmaster/type/test~2Ffunctional~2Fuwp~2F/build/20190328.7/workItem/System.Net.Sockets.Tests/analysis/xunit/System.Net.Sockets.Tests.SocketOptionNameTest~2FMulticastInterface_Set_IPv6_AnyInterface_Succeeds

cc @wfurt

### CODE REVIEW

**Comment by davidsh** [comment]
>These two time out on UWP F5 runs about 4-5 times a week for some time. Changing 20 sec to 30 sec timeout to see whether that helps.

Multicast is something that is risky in general to run in CI.  I wouldn't mind if we just disabled these tests for UWP if they are too noisy.

**Comment by danmosemsft** [comment]
Also for two others. SendToRecvFromAsync_Datagram_UDP_UdpClient has failed once in the last couple weeks and retried today (so probably many other times)

SendToRecvFrom_Datagram_UDP I don't have data on, I figured I'd increase its one as well.

**Comment by danmosemsft** [comment]
@davidsh they are already outerloop, if you mean "run on checkin" (It seems we use "CI" and "Official builds" to mean "Gated checkin" and "CI"...)

I suggest we see how they do with the longer timeouts. I've often found that a longer timeout makes a test much more stable.

**Comment by danmosemsft** [comment]
But sure, I have no objection to disabling for UWP if you want.

**Comment by davidsh** [comment]
>I suggest we see how they do with the longer timeouts. I've often found that a longer timeout makes a test much more stable.

I'm fine with trying the longer timeouts first before we disable the tests.

**Pull request merged**
