### PR TITLE
Use PROCESS_QUERY_LIMITED_INFORMATION when getting process handle

### LINKED ISSUE #302: Accessing Process.HasExited throws an "access is denied" exception if the target process is running with elevated permissions
Accessing `Process.HasExited` throws an "access is denied" exception if the target process is running with elevated permissions and the caller does not.

This was reported by me and confirmed by BCL Team but wasn't fixed: [Connect Issue](https://connect.microsoft.com/VisualStudio/feedback/details/714808/process-hasexited-throws-exception-if-the-process-is-running-with-elevated-permissions)

The error occurs as `ProcessManager` is calling `OpenProcess` with `PROCESS_QUERY_INFORMATION` access right while on Vista and Windows 7 it is enough to use `PROCESS_QUERY_LIMITED_INFORMATION` for getting handle.

### PR DESCRIPTION
**Pull request by Giorgi**
Accessing Process.HasExited throws an "access is denied" exception if
the target process is running with elevated permissions and the caller 
isn't.

Fix #302

### CODE REVIEW

**Comment by joshfree** [comment]
@MattGal please have a look after https://github.com/dotnet/corefx/pull/485 is commited.

**Comment by joshfree** [comment]
Hi @Giorgi; now that the initial unit tests have been added for System.Diagnostics.Process, could you update your PR to add a new regression test to cover your change?

**Comment by Giorgi** [comment]
@joshfree It sounds tricky but I will give it a try.

**Comment by Giorgi** [comment]
@joshfree I just discovered that ProcessStartInfo does not have verb property which is needed to start elevated process.

**Comment by ellismg** [comment]
I think that launching an elevated process is a bad idea, as that will require intervention at runtime to allow the process to elevate, correct?

Instead, could the test launch a process at a lower integrity level which tries to inspect the test process and reports back if it was able to do so?  Would this give us coverage?

**Comment by Giorgi** [comment]
You are right, running an elevated process does not make sense but I don't know how to do what you suggested.

**Comment by Alexx999** [comment]
I believe that this change will cause regression on Windows XP, so question is - do we care about it?

**Comment by davkean** [comment]
We do not support Windows XP.

**Comment by Alexx999** [comment]
I think this should be explicitly stated somewhere in readme or developers guide

**Comment by Giorgi** [comment]
What if you merge this without a test just like service controller pull request? #627 ?

**Comment by ellismg** [comment]
@Giorgi I would be fine with such an approach.  I believe that testing this in our current system is non trivial, once this goes in I will open an issue to track the test coverage.

**Comment by Giorgi** [comment]
@ellismg  Sounds good.

**Pull request merged**
