### PR TITLE
Update BuildTools to version 1.0.26-prerelease-00926-01

### PR DESCRIPTION
**Pull request by AlexGhiondea**
/cc @joperezr @weshaggard

### CODE REVIEW

**Comment by AlexGhiondea** [comment]
@dotnet-bot test Innerloop Windows_NT Release Build and Test (#13025)

**Comment by AlexGhiondea** [comment]
@dotnet-bot test Innerloop Windows_NT Debug Build and Test

**Comment by AlexGhiondea** [comment]
@dotnet-bot test  Innerloop Windows_NT Release Build and Test

**Comment by joperezr** [comment]
LGTM.

**Pull request merged**
