### PR TITLE
Simplify BitArray enumerator

### PR DESCRIPTION
**Pull request by nxtn**
|  Method |     Mean |    Error |   StdDev |
|-------- |---------:|---------:|---------:|
|  Before | 310.5 ns | 2.009 ns | 1.781 ns |
|   After | 265.6 ns | 2.436 ns | 2.279 ns |

### CODE REVIEW

**Review by stephentoub — APPROVED** [review]

**Comment by stephentoub** [comment]
Thanks

**Comment by danmosemsft** [comment]
Would MoveNext and Current inline better if the throws were moved into throw helper  methods?

**Comment by stephentoub** [comment]
> Would MoveNext and Current inline better if the throws were moved into throw helper methods?

Since BitArray's GetEnumerator just returns `IEnumerator`, such calls would need to be devirtualized before there'd be any chance of inlining.

**Comment by NextTurn** [comment]
Is it breaking to change the return type to a specific struct/class type?

**Comment by stephentoub** [comment]
> Is it breaking to change the return type to a specific struct/class type?

Yes

**Pull request merged**
