### PR TITLE
Update CentOS 6 docker image

### PR DESCRIPTION
**Pull request by janvorli**
This update fixes problem with git not supporting https protocol

### CODE REVIEW

**Comment by janvorli** [comment]
@dotnet-bot test RHEL.6 x64 Release Build

**Comment by janvorli** [comment]
@dotnet-bot test CentOS.6 x64 Release Build

**Comment by janvorli** [comment]
@dotnet-bot test UWP CoreCLR x64 Debug Build please

**Comment by janvorli** [comment]
cc: @chcosta

**Comment by chcosta** [comment]
LGTM

**Pull request merged**
