### PR TITLE
Added test for RegionInfo.NativeName

### PR DESCRIPTION
**Pull request by svick**
This depends on https://github.com/dotnet/coreclr/pull/6362.

### CODE REVIEW

**Comment by svick** [comment]
[There was a failure I did not expect on CentOS.](http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/master/job/centos7.1_debug_prtest/1012/):

> System.Globalization.Tests.RegionInfoPropertyTests.NativeName(name: "cy-GB", expected: "Y Deyrnas Unedig")
> Assert.Equal() Failure\n ↓ (pos 0)\nExpected: Y Deyrnas Unedig\nActual: Prydain Fawr\n ↑ (pos 0)

As far as I can tell, "Y Deyrnas Unedig" means "The United Kingdom" and "Prydain Fawr" means "Great Britain" in Welsh. Since both seem to be acceptable values returned from `new RegionInfo("cy-GB").NativeName`, I have removed the `cy-GB` testcase.

**Comment by stephentoub** [comment]
cc: @tarekgh

**Comment by stephentoub** [comment]
@dotnet-bot test this please

**Comment by stephentoub** [comment]
LGTM

**Comment by tarekgh** [comment]
:+1:

**Pull request merged**
