### PR TITLE
Add more badges to README.md

### PR DESCRIPTION
**Pull request by stephentoub**
Adds badges for:
- Native component builds on Linux and OS X
- Separate build and test legs on Linux and OS X
- Outer loop tests in debug and release on Windows

I restructured the layout of the badges a bit as part of this to try to keep it neat.  I also switched to shields.io badges that let us control the label on the badges, so that they all don't just say "build".

### CODE REVIEW

**Comment by stephentoub** [comment]
cc: @mmitche, @nguerrera

**Comment by nguerrera** [comment]
Cool! LGTM.

Side questions: 

1. Why does code coverage animate between different values? 

2. Can we add release outer testing to Mac OS and Linux? I'm particularly interested in testing native release bits, because valid compiler optimizations can expose inadvertent exposure to undefined behavior. (I am planning to turn on clang's sanitization checks for debug, but still best to test release as well to cover all of our bases.)

**Comment by nguerrera** [comment]
Ah, I see the answer to my first question is branch vs. line coverage.

**Comment by stephentoub** [comment]
Yup.  As for your second question, I'll let @mmitche answer that.

**Comment by mmitche** [comment]
@nguerrera Yeah we can.  I'm moving to a new job definition model that doesn't involve as much UI work and is more self-service. Do you have a specific deadline you want for those jobs or can I put it on the new train?

**Comment by nguerrera** [comment]
No specific deadline. New train is fine. Thanks!

**Pull request merged**
