### PR TITLE
Fix potential AVs from poorly written HashAlgorithm usage

### LINKED ISSUE #1996: Potential native out of bounds read caused by HashAlgorithm.ComputeHash(Stream)
`ComputeHash(Stream)` reads bytes to a buffer and remembers the bytes read indicated by the return value of `Stream.Read`. It then passes both to `HashAlgorithm.HashCore` of the respective implementations.
The built-in hash algorithms (such as SHA1) simply pass that on to `HashProvider.AppendHashData` which (in the case of Windows, same problem may exist in the Unix part) calls `BCryptHashData` without verifying that the byte length is valid for the buffer.

Thus the returned value of `Stream.Read` is passed unfiltered and unchecked to `BCryptHashData`, so an evil/buggy/wrong implementation of Stream can cause an out of bounds read in native `BCryptHashData` with values larger than the actual buffer.

As the `Stream` is a public parameter of `ComputeHash` and `Stream` is freely extensible, every return value of its members should be verified!
In this case the return value of `Stream.Read` should be compared to the buffer size or capped with `Math.Min`.

### PR DESCRIPTION
**Pull request by stephentoub**
The implementation of HashCore in all of our HashAlgorithms on both Windows and Unix uses the buffer/offset/count in unsafe code without argument validation.  While most usage of HashCore comes from internal data that's constructed to be correct, there are two paths where externally supplied data can arrive to HashCore unverified:

1. A Stream passed to ComputeHash can return a number of bytes read that's larger than the buffer size.  This value will be passed as the count to HashCore.
2. A type can derive from one of the hashing algorithms and access HashCore directly, which is protected.

This PR adds argument validation to our Windows and Unix implementations prior to using unsafe code to process those arguments.

Fixes #1996

### CODE REVIEW

**Comment by stephentoub** [comment]
cc: @bartonjs

**Comment by stephentoub** [comment]
@bartonjs, addressed your feedback. Thanks!

**Comment by bartonjs** [comment]
LGTM

**Comment by stephentoub** [comment]
@dotnet-bot test this please

**Comment by stephentoub** [comment]
@dotnet-bot test this please

**Pull request merged**
