### PR TITLE
Simplify Microsoft.CSharp.RuntimeBinder.Semantics.ExprFactory

### PR DESCRIPTION
**Pull request by JonHanna**
Move more logic into constructors, and when this allows properties to be init-only, do so.

Remove unsused types, unused parameters, and other dead code.

Rename variables with Hungarian prefixes (and prefixes apparently referring to C++ pointers at that).

### CODE REVIEW

**Comment by JonHanna** [comment]
Test OSX x64 Debug Build

(Error during cleanup: java.io.IOException: remote file operation failed: /Users/dotnet-bot/j/workspace/dotnet_corefx/master/osx-TGroup_netcoreapp+CGroup_Debug+AGroup_x64+TestOuter_false_prtest at hudson.remoting.Channel@9a612c:JNLP4-connect connection from 131.107.19.216/131.107.19.216:52146: hudson.remoting.ChannelClosedException: channel is already closed)

**Comment by JonHanna** [comment]
Test Test OSX x64 Debug Build
(#22347)

**Comment by VSadov** [comment]
Very nice change!!! Thanks a lot!
Some redundancies are kind of embarrassing. I can only guess the team wanted to save on maintenance by having code so close to the static binder.  
Considering that compiler has been rewritten, there is no much use in that now.

**Comment by JonHanna** [comment]
Yeah, when the static compiler was current it would have been easier to port fixes and changes from one to the other. That not being the case I want to get this to the point where it looks like it was written in C# from scratch as a dynamic binder, rather than ported from a static binder in another language, but the biggest difficulty is stopping before the result is a massive PR that would be harder to review than it was to write. (And besides, #22301 and #22117 are more urgent as they've caused the asp.net people problems).

**Pull request merged**
