### PR TITLE
Enable globstar in run-test.sh

### PR DESCRIPTION
**Pull request by mmitche**
Globstar is not enabled by default, and a recent commit attempting to increase the number of directories being run for the Linux build actually skipped a bunch of stuff.  Enable globstar in the script (this is local) to fix.

### CODE REVIEW

**Comment by nguerrera** [comment]
Which commit has the failed attempt? What was getting skipped without globstar?

**Comment by mmitche** [comment]
@nguerrera #2432 .  It was skipping everything but the tests that stoub wanted to include ;-)

**Comment by akoeplinger** [comment]
@mmitche can you configure Jenkins to fail the build if there are less than X tests run to catch this earlier in the future?

**Comment by mmitche** [comment]
@akoeplinger Yeah I should be able to.  I think I can set thresholds on the number of tests run.

**Comment by nguerrera** [comment]
LGTM

**Comment by stephentoub** [comment]
Thanks, Matt. LGTM.  Sorry about that :smile:

**Comment by stephentoub** [comment]
@mmitche, this failed due to the DriveLetter_Unix in System.IO.FileSystem (@ianhays, FYI).  I'd suggest just disabling that test right now as part of this so that we can get the CI back up and running.  I'm thankful this didn't find more breaks that occurred in the interim.

**Comment by nguerrera** [comment]
Looks like one failing test snuck in while this test hole was present:

```
09:58:08 Discovered:  System.IO.FileSystem.Tests
09:58:09 Starting:    System.IO.FileSystem.Tests
09:58:09    System.IO.FileSystem.Tests.Directory_CreateDirectory.DriveLetter_Unix [FAIL]
09:58:09       System.IO.DirectoryNotFoundException : Could not find a part of the path '/mnt/j/workspace/dotnet_corefx_linux_debug_tst_prtest/bin/tests/Windows_NT.AnyCPU.Debug/System.IO.FileSystem.Tests/dnxcore50/C:'.
09:58:09       Stack Trace:
09:58:10             at System.IO.UnixFileSystem.RemoveDirectoryInternal(String fullPath, Boolean recursive, Boolean throwOnTopLevelDirectoryNotFound)
09:58:10             at System.IO.UnixFileSystem.RemoveDirectory(String fullPath, Boolean recursive)
09:58:10             at System.IO.Directory.Delete(String path)
09:58:10             at System.IO.FileSystem.Tests.Directory_CreateDirectory.DriveLetter_Unix()
09:58:10 Finished:    System.IO.FileSystem.Tests
09:58:10 
09:58:10 === TEST EXECUTION SUMMARY ===
09:58:10    System.IO.FileSystem.Tests  Total: 1538, Errors: 0, Failed: 1, Skipped: 0, Time: 1.414s
```

**Comment by nguerrera** [comment]
Oh, @stephentoub already pointed that out. Comment race condition. :)

**Comment by stephentoub** [comment]
:smile:

**Comment by mmitche** [comment]
@stephentoub What's the right way to disable the test only on Unix?  PlatformSpecific + ActiveIssue?

**Comment by stephentoub** [comment]
It's already a platform-specific test with [PlatformSpecific], so you can just add [ActiveIssue(whatever)].

**Comment by mmitche** [comment]
Opened #2459

**Pull request merged**
