### PR TITLE
Add more Decimal constructor tests

### PR DESCRIPTION
**Pull request by hughbe**

### CODE REVIEW

**Comment by stephentoub** [comment]
Thanks.  What was driving these additions?  Trying to increase code coverage or something like that?  If so, can you share the impact?

**Comment by hughbe** [comment]
A while ago I saw something moving native code to managed so wrote some tests to verify stuff but never ended up submitting.  Went through my branches that were never sent in as a Pr And sent this in

**Comment by stephentoub** [comment]
> A while ago I saw something moving native code to managed so wrote some tests to verify stuff but never ended up submitting. Went through my branches that were never sent in as a Pr And sent this in

So these tests are validating things that weren't previously validated?  That's what I'm trying to figure out, whether this is actually new coverage or duplication.

**Comment by hughbe** [comment]
> So these tests are validating things that weren't previously validated?

Correct. These are new tests

**Pull request merged**
