### PR TITLE
Allows to build Release build

### PR DESCRIPTION
**Pull request by KrzysztofCwalina**
Use: build.cmd /p:Configuration=Release

### CODE REVIEW

**Comment by nguerrera** [comment]
/cc @weshaggard 

@KrzysztofCwalina and I found this together. There doesn't seem to be any need for the traversal targets to import Microsoft.Common.targets, but doing so causes an extra validation of the Configuration of build.proj as though it were a VS project and it breaks if you pass anything non-empty as the Configuration.

**Comment by mmitche** [comment]
@KrzysztofCwalina I believe I fixed this earlier today.

**Comment by KrzysztofCwalina** [comment]
Ok, I resubmitted the PR with a simple change that just removes the unnecessary checks. I will prototype the larger change separately. Could somebody CR this PR and comment or merge this change? Thanks.

**Comment by KrzysztofCwalina** [comment]
Ah, I missed that. I will close this PR then.

**Comment by weshaggard** [comment]
@mmitche just fixed this issue with https://github.com/dotnet/corefx/pull/406 but I think you are right that we don't need to import Microsoft.common.targets here, although I don't know why I would have added it to our internal version if it wasn't needed for something... I guess we will find it if there are issues.

**Pull request closed without merging**
