### PR TITLE
Update build tools to get core dumps for tests

### PR DESCRIPTION
**Pull request by ellismg**
On OSX, this build tools will set ulimit so that if a test crashes
we'll get a core dump produced. We want to use this to sniff out
some stress issues we are seeing in CI.

### CODE REVIEW

**Comment by ellismg** [comment]
@adityamandaleeka @sergiy-k @joshfree

**Comment by joshfree** [comment]
@ericstj can you review this buildtools update

**Comment by eerhardt** [comment]
:shipit: This version is used in core-setup, and it rocks.

**Comment by joshfree** [comment]
reviewed; LGTM

**Comment by ellismg** [comment]
test Innerloop CentOS7.1 Release Build and Test (failed due a segfault in [System.Xml.RW.ReadContentAs.Tests](http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/release_1.0.0/job/centos7.1_release_prtest/36/).  Of course, since this was Linux we don't get a dump :-(.

**Pull request merged**
