### PR TITLE
Add memory mapped files

### PR DESCRIPTION
**Pull request by mellinoe**
This adds the source and test code for MemoryMappedFiles.

A couple things to note:

- This includes a change to dirs.proj so that the build will pick up test projects in nested directories:

````
- <Project Include="*\tests\*.csproj" />
+ <Project Include="*\tests\**\*.csproj" />
````

This references newer versions of all of the framework assemblies (22512.00), because they rely on the fixed behavior of UnmanagedMemoryStream (recently fixed). We should update all of the other projects to use the latest version of the packages, as well.

### CODE REVIEW

**Comment by mellinoe** [comment]
+ @FiveTimesTheFun , Does the dirs.proj change look reasonable to you? I mentioned this to you a little while back. Basically just extends to search path to include any test projects that are in nested directories under "tests"

**Comment by krwq** [comment]
dirs.proj change looks good to me :+1:

**Comment by mellinoe** [comment]
@weshaggard I removed the dirs.proj changes and put the tests in the root "tests" directory. I did that originally just for organization and how they were structured internally. It doesn't matter in this case but I think it might be something we want in the future just for organization's sake. I'm also not sure how our current system handles assembly-specific packages.config files (needed if everything is in the same folder), but in this case these tests can all use the same packages.config.

Also, and I apologize about this, but there were some other comments and feedback about the source code here, but they all got deleted when I re-committed this. This is a direct port from our internal sources, so I will be merging this as-is, but please do file issues about anything that you see separately, and we will take a look at improving it.

**Comment by terrajobst** [comment]
@mellinoe can you update the README.md in the root as well?

**Pull request merged**
