### PR TITLE
Use .builds for command line building instead of .sln

### PR DESCRIPTION
**Pull request by svick**
As recommended by @mellinoe in https://github.com/dotnet/corefx/pull/8961#issuecomment-222794058.

### CODE REVIEW

**Comment by mellinoe** [comment]
Thanks, this looks like a good improvement.

It may be worthwhile to mention that the "builds" files are set up to build the project in every valid configuration. So if you're only interested in one configuration, it is faster to build the csproj itself in that specific configuration. That is probably more of an advanced scenario, and you need to pass parameters into msbuild, which may be beyond the scope of this section.

LGTM regardless

**Comment by danmosemsft** [comment]
The unfortunate thing about running msbuild directly is that you don't get build logs. (Really those basic logs should have been set up in the global msbuild.rsp long ago) The nice thing about a script like build.cmd is that you get msbuild.log, msbuild.err, msbuild.wrn.

**Comment by svick** [comment]
@mellinoe I just now noticed that the document talks about building configurations in sections just below the one I changed. Would it make sense to talk about building using .csproj instead of .builds here? (And gloss over cases where .csproj and .builds are not 1 to 1, like [sockets tests](https://github.com/dotnet/corefx/tree/master/src/System.Net.Sockets/tests))

As added advantage, it would mean simplifying `msbuild System.Diagnostics.DiagnosticSource.builds` back to just `msbuild` in the right directory.

**Comment by mellinoe** [comment]
Hmm, looking at the rest of the document I think it is good to keep your proposed version. We have so many configuration pivots now that it probably makes sense to describe how to build ALL of valid configurations up front. Newcomers most likely won't know which configuration they are interested in anyways, and they will want to just build all of the relevant configurations to make sure they haven't broken something.

> The unfortunate thing about running msbuild directly is that you don't get build logs. (Really those basic logs should have been set up in the global msbuild.rsp long ago) The nice thing about a script like build.cmd is that you get msbuild.log, msbuild.err, msbuild.wrn.

I dunno, most of the time if you're building an individual project, you don't really need to have detailed logs stored. There's not really that much info coming out of the build. I think msbuild is well-documented enough that folks can look up how to access more detailed logging if they're interested. Default logging makes sense on the full build because there's just so much more information to process.

**Comment by mellinoe** [comment]
Thanks for the improvement, @svick . I'm going to merge this in.

**Pull request merged**
