### PR TITLE
Add ItemRef and ValueRef to List/Dict (C# 7.2 constructs)

### PR DESCRIPTION
**Pull request by benaadams**
Requires https://github.com/dotnet/coreclr/pull/17405

Contributes to https://github.com/dotnet/corefx/issues/25189
Resolves https://github.com/dotnet/corefx/issues/20684

* Adds ItemRef() to `List<T>`
* Adds ValueRef() to `Dictionary<TKey, TValue>`

As per https://github.com/dotnet/corefx/pull/25738

### CODE REVIEW

**Comment by danmosemsft** [comment]
This is 2.2 work so marking no merge to avoid accidents for the next ~10 days until master becomes 2.2

**Comment by danmosemsft** [comment]
@dotnet-bot test this please

@safern looks like it needs a review.

**Comment by benaadams** [comment]
@danmosemsft would require https://github.com/dotnet/coreclr/pull/17405

**Comment by stephentoub** [comment]
@benaadams, thanks for this. Since there's some contention on whether we should proceed with https://github.com/dotnet/coreclr/pull/17405, I'm going to close this PR for now, and it can be re-opened if/when https://github.com/dotnet/coreclr/pull/17405 is merged.

**Pull request closed without merging**
