### PR TITLE
Update buildtools to 2.1.0-preview2-02621-01

### PR DESCRIPTION
**Pull request by mmitche**
Fixes issue with dumpling https://github.com/dotnet/buildtools/pull/1972

### CODE REVIEW

**Comment by stephentoub** [comment]
@mmitche, your Linux leg has been running for over six hours.
https://ci3.dot.net/job/dotnet_corefx/job/release_2.1/job/linux-TGroup_netcoreapp+CGroup_Release+AGroup_x64+TestOuter_false_prtest/54/
Do we know what's causing this?  I've seen lots of similar length legs recently. @joperezr, should the buildtools update have fixed this?

**Comment by stephentoub** [comment]
Ah, I see @joshfree already opened an issue related to it.

**Comment by danmosemsft** [comment]
@mmitche it shows System.Odbc tests are still running, but their execution logs show they completed successfully.

https://mc.dot.net/#/user/mmitche/pr~2Fjenkins~2Fdotnet~2Fcorefx~2Frelease~2F2.1~2F/test~2Ffunctional~2Fcli~2F/d844702aad4b93f903c8d54e0b6614ee17898f2f

**Comment by danmosemsft** [comment]
I'm going to merge this as everything seems complete and passing and this is fixing a build break.

**Comment by mmitche** [comment]
Thanks.

**Comment by MattGal** [comment]
It's an infra bug, I put details in Josh's issue.  Things hitting this bug will indeed never finish unless we send a fake event for them.

**Pull request merged**
