### PR TITLE
Use Array.Sort instead of custom QuickSort implementation in LINQ's OrderBy

### PR DESCRIPTION
**Pull request by stephentoub**
Fixes https://github.com/dotnet/corefx/issues/24110

The first commit just moves the various QuickSort implementations to the derived sealed class, to avoid some virtual dispatch for some of the comparison operations.  The second commit then addresses the core of the problem, by using Array.Sort (an IntroSort implementation) instead of the custom QuickSort implementation used today; stability is provided by comparison operator utilizing the provided indices.

It'll be easiest to review the commits individually.

cc: @JonHanna, @VSadov, @OmarTawfik, @maxzav

### CODE REVIEW

**Comment by JonHanna** [comment]
I'd like to take a look at randomising the pivoting in the current code (though probably with a faster PRNG than `Random` since I have one to hand anyway) which should solve the problem and also be applicable to the partial quicksort and quickselect that are in use. I won't really know if that's a good idea until I can do some performance tests (probably on Wednesday evening). Perhaps a tandem approach would be best, this or the full ordering, that for the partial.

**Comment by stephentoub** [comment]
> I'd like to take a look at randomising the pivoting in the current code

That's fine, but unless someone has a good argument for why it's important that LINQ have its own QuickSort implementation, I'd much prefer to just reuse Array.Sort.  Other improvements may of course help the partial and selection routines, which don't have equivalents on Array.

**Comment by VSadov** [comment]
I think there are two reasons why Linq has its own quicksort -
- it is stable  (which indeed is more a property of a comparer)
- it inlines the comparer so that it is fast.

As I see the stability will be preserved by the change. 
I wonder though how much of the perf penalty there will be. Does Array.Sort do a virtual/interface call on every compare?
 
Like - if we OrderBy a large int array. Does it get any slower after the change?

**Comment by stephentoub** [comment]
> it inlines the comparer so that it is fast.

Which comparer?

> 

Obviously there are many things that could be measured, and maybe some other inputs would slow down, but a quick and terribly dirty benchmark:
```C#
using System;
using System.Diagnostics;
using System.Linq;

class Program
{
    private static void Main()
    {
        Time("10      sorted", 1000000, Enumerable.Range(0, 10).ToArray());
        Time("1000000 sorted", 10, Enumerable.Range(0, 1000000).ToArray());

        var r = new Random();

        int[] arr = new int[10];
        for (int i = 0; i < arr.Length; i++) arr[i] = r.Next();
        Time("10      random", 1000000, arr);

        arr = new int[1000000];
        for (int i = 0; i < arr.Length; i++) arr[i] = r.Next();
        Time("1000000 random", 10, arr);
    }

    private static void Time(string name, int iters, int[] array)
    {
        var sw = new Stopwatch();
        array.OrderBy(i => i).ToArray();

        sw.Restart();
        for (int i = 0; i < iters; i++)
        {
            array.OrderBy(item => item).ToArray();
        }
        sw.Stop();

        Console.WriteLine(name.PadRight(40) + ": " + sw.Elapsed.TotalMilliseconds);
    }
}
```

Before:
```
10      sorted                          : 833.8023
1000000 sorted                          : 3859.5161
10      random                          : 1034.745
1000000 random                          : 6869.5707
```

After:
```
10      sorted                          : 613.1185
1000000 sorted                          : 2687.9658
10      random                          : 1050.7906
1000000 random                          : 4717.7168
```

**Comment by Drawaes** [comment]
@dotnet-bot Test Outerloop UWP CoreCLR x64 Debug Build
Just checking

**Comment by JonHanna** [comment]
I still haven't had a chance to look at the other cases where sorting is done, and won't any time this week, but for the whole-sequence sort, this LGTM

**Pull request merged**
