### PR TITLE
Add Ref and Pkg for S.SM.Syndication.

### PR DESCRIPTION
**Pull request by shmao**
The PR added \ref and \pkg folders for S.SM.Syndication.

### CODE REVIEW

**Comment by shmao** [comment]
@weshaggard , I'm adding \ref and \pkg for System.ServiceModel.Syndication. The build failed with the following error,

>15:02:59 D:\j\workspace\windows-TGrou---74aa877a\pkg\frameworkPackage.targets(124,5): error : Assembly 'System.ServiceModel.Web' is missing dependency 'System.ServiceModel.Syndication' [D:\j\workspace\windows-TGrou---74aa877a\pkg\Microsoft.Private.CoreFx.NETCoreApp\Microsoft.Private.CoreFx.NETCoreApp.pkgproj]

I saw you added `System.ServiceModel.Web` in that pkgproj. Do you know what's happening here? Do I want to add `System.ServiceModel.Syndication` as a ExcludeFromClosure in that pkgproj?

/cc: @zhenlan

**Comment by weshaggard** [comment]
>I saw you added System.ServiceModel.Web in that pkgproj. Do you know what's happening here? Do I want to add System.ServiceModel.Syndication as a ExcludeFromClosure in that pkgproj?

Add System.ServiceModel.Web to the ExcludeFromClosure list.

**Comment by shmao** [comment]
@dotnet-bot test Linux x64 Release Build

**Comment by shmao** [comment]
> System.Net.Requests.Tests failed.

@dotnet-bot test Linux x64 Release Build

**Comment by shmao** [comment]
The following tests failed,

>System.Collections.Performance.Tests	
System.Net.Http.Functional.Tests	
System.Net.Requests.Tests	
System.Net.WebHeaderCollection.Tests

I checked the log. None of them seemed related to the changes. Re-running the tests.

@dotnet-bot test Linux x64 Release Build

**Comment by shmao** [comment]
> 09:40:41 ERROR: Issue with creating launcher for agent ubuntu1604-20170216-a12640. The agent has not been fully initialized yet

@dotnet-bot test Linux x64 Release Build

**Comment by shmao** [comment]
> Timeout has been exceeded
Finished: ABORTED

@dotnet-bot test Linux x64 Release Build

**Pull request merged**
