### PR TITLE
Fix build break in System.Data.Common

### PR DESCRIPTION
**Pull request by ericstj**
/cc @stephentoub @saurabh500 
Replaces https://github.com/dotnet/corefx/pull/6066

### CODE REVIEW

**Comment by stephentoub** [comment]
Thanks, Eric.  LGTM.

**Comment by stephentoub** [comment]
Also, what magic incantation can I do locally to build all of the various flavors of just this one library?

**Comment by ericstj** [comment]
msbuild on the `.builds` file would do it here.  In other cases where there are OS-specific builds you should pass /p:OSGroup=AnyOS.

**Comment by stephentoub** [comment]
Thanks.  But if I want all builds for all platforms for the library, I can just do ```msbuild TheLibrary.builds``` and all the right stuff will happen?

**Comment by ericstj** [comment]
I believe that will filter to the running OS by default, right @weshaggard?

See
https://github.com/dotnet/corefx/blob/master/dir.traversal.targets#L5
https://github.com/dotnet/corefx/blob/master/dir.traversal.targets#L42

**Comment by weshaggard** [comment]
`msbuild ThisLibrary.builds` will build all combination of the library. The only place we do filtering to what you are building on is from the root build.proj (https://github.com/dotnet/corefx/blob/master/build.proj#L13).

**Comment by ericstj** [comment]
ahh, thanks for the correction.

**Pull request merged**
