### PR TITLE
Add ISerializable to several System.Runtime types in ref

### PR DESCRIPTION
**Pull request by stephentoub**
The implementations are there, the interface is just missing in the contract.

cc: @danmosemsft 
Contributes to https://github.com/dotnet/corefx/issues/12669

### CODE REVIEW

**Comment by danmosemsft** [comment]
Should you add these to the uber-test you have for serialization roundtripping? otherwise LGTM

**Comment by stephentoub** [comment]
> Should you add these to the uber-test you have for serialization roundtripping?

They're already there. It's not dependent on the contract, as BinaryFormatter uses reflection and casting.

**Comment by stephentoub** [comment]
Thanks for the review.

**Comment by danmosemsft** [comment]
@stephentoub if you update the baseline files by building with /p:BaselineAllAPICompatError=true then they update in the correct place in the file, which will merge cleanly. I'm guessing you pasted at the bottom ?

**Comment by stephentoub** [comment]
> I'm guessing you pasted at the bottom ?

Yes

**Pull request merged**
