### PR TITLE
Add waithandle checks in Process test.

### LINKED ISSUE #9678: TestUserCredentialsPropertiesOnWindows failing on Windows outer loop
e.g.
http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/master/job/outerloop_windows_nt_release/79/consoleText/
http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/master/job/outerloop_windows_nt_release/78/consoleText/
http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/master/job/outerloop_windows_nt_release/76/consoleText/
http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/master/job/outerloop_windows_nt_debug/79/consoleText
http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/master/job/outerloop_windows_nt_debug/78/consoleText
http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/master/job/outerloop_windows_nt_debug/77/consoleText
```
System.Diagnostics.Tests.ProcessStartInfoTests.TestUserCredentialsPropertiesOnWindows [FAIL]
        System.ComponentModel.Win32Exception : The user name or password is incorrect
        Stack Trace:
           D:\j\workspace\outerloop_win---65ef7d78\src\System.Diagnostics.Process\src\System\Diagnostics\Process.Windows.cs(619,0): at System.Diagnostics.Process.StartCore(ProcessStartInfo startInfo)
           D:\j\workspace\outerloop_win---65ef7d78\src\System.Diagnostics.Process\tests\ProcessStartInfoTests.cs(375,0): at System.Diagnostics.Tests.ProcessStartInfoTests.TestUserCredentialsPropertiesOnWindows()
```

### PR DESCRIPTION
**Pull request by Priya91**
fixes #9678 

cc @stephentoub

### CODE REVIEW

**Comment by stephentoub** [comment]
Test Outerloop Windows_NT Debug please

**Comment by stephentoub** [comment]
This doesn't fix it:
http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/master/job/outerloop_windows_nt_debug_prtest/10/consoleText

**Comment by Priya91** [comment]
Testing on the CI box, the same error happens with desktop Process.Start() APIs as well. Using the win32 apis through pinvoke, gives different errors randomly about password requirements not met, or username invalid, etc. Whereas using the c++ functions directly creates and deletes the user as expected. Since this test is flaky, will try to use the native app directly

**Comment by Priya91** [comment]
Test Outerloop Windows_NT Debug please

**Comment by Priya91** [comment]
Test Outerloop Windows_NT Debug please

**Comment by mellinoe** [comment]
I'm not fully understanding why we need the C++ code here. It sounds weird that there's any difference between PInvoking the functions and calling them from C++. Is it a timing issue or something only incidentally related to C# vs. C++? Also, do we have any other C++ code in with the managed tests like this?

**Comment by stephentoub** [comment]
> I'm not fully understanding why we need the C++ code here

Me, too.  If the C++ works and the C# doesn't, sounds like a problem with how the P/Invoke signatures/types are defined?

**Comment by stephentoub** [comment]
@dotnet-bot test this please

**Comment by Priya91** [comment]
I am not sure if it's marshalling that's the problem, running the pinvoked program results in error codes like username invalid, passport requirements not met and the like, even though the inputs are correct. But these errors are not even consistent, sometimes the methods pass and create an user. When testing just the win32 apis in c++, the apis always pass, creating an user. This could also be because of access policies although not sure why the errors are not being consistent with pinvoke

**Comment by Priya91** [comment]
Test Outerloop Windows_NT Debug please

**Comment by stephentoub** [comment]
> But these errors are not even consistent, sometimes the methods pass and create an user

This is partially what makes me think it's a problem in how the P/Invokes have been defined.  It could be, for example, that the strings are getting corrupted some of the time, in which case it doesn't work.

**Comment by Priya91** [comment]
The process test is failing with the files not getting copied to output directory.

**Comment by Priya91** [comment]
Test Outerloop Windows_NT Debug please

**Comment by Priya91** [comment]
Test Outerloop Windows_NT Debug please

**Comment by Priya91** [comment]
> This is partially what makes me think it's a problem in how the P/Invokes have been defined.

Hmm, i rechecked the pinvokes with the native api, verified the unicode string settings. I haven't tried out debugging through pinvoke native calls before, will take time to figure that out. In the meantime this will work.

**Comment by stephentoub** [comment]
> i rechecked the pinvokes with the native api, verified the unicode string settings

The USER_INFO_1 struct is missing the proper CharSet.  I've fixed that in https://github.com/dotnet/corefx/pull/9776.

**Pull request closed without merging**
