### PR TITLE
Remove TestWithLocalLibraries From CI

### LINKED ISSUE #11203: System.IO tests aborting in dev/api
This is happening frequently, e.g.
http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/dev_api/job/ubuntu14.04_release_prtest/504/
http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/dev_api/job/ubuntu14.04_release_prtest/511/
```
./corerun xunit.console.netcore.exe System.IO.Tests.dll -xml testResults.xml -notrait Benchmark=true -notrait category=IgnoreForCI -notrait category=OuterLoop -notrait category=failing -notrait category=nonlinuxtests
  
  Unhandled Exception: System.IO.FileLoadException: Could not load file or assembly 'System.IO, Version=4.2.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
  /mnt/j/workspace/dotnet_corefx/dev_api/ubuntu14.04_release_prtest/bin/tests/AnyOS.AnyCPU.Release/System.IO.Tests/netcoreapp1.0/RunTests.sh: line 293: 45732 Aborted                 (core dumped) ./corerun xunit.console.netcore.exe System.IO.Tests.dll -xml testResults.xml -notrait Benchmark=true -notrait category=IgnoreForCI -notrait category=OuterLoop -notrait category=failing -notrait category=nonlinuxtests
```

### PR DESCRIPTION
**Pull request by joperezr**
Removing TestWithLocalLibraries From the groovy script.

cc: @weshaggard @ericstj @JeremyKuhne @stephentoub @danmosemsft @tarekgh 

fixes #11203 

I created #11257 to track the work to re-add TestWithLocalLibraries back but using pkgproj references instead of trying to guess which asset to pick.

### CODE REVIEW

**Comment by joperezr** [comment]
@dotnet-bot test ci please

**Comment by JeremyKuhne** [comment]
:shipit:

**Comment by tarekgh** [comment]
LGTM

**Comment by joperezr** [comment]
Builds triggered with new definition:
- **OSX**: dotnet-ci.cloudapp.net/job/dotnet_corefx/job/dev_api/job/GenPRTest/job/outerloop_osx_debug/1/console
- **CentOS**: dotnet-ci.cloudapp.net/job/dotnet_corefx/job/dev_api/job/GenPRTest/job/centos7.1_debug_prtest/1/console
- **Ubuntu**: (*not triggered yet*)

**Comment by ericstj** [comment]
Looks like CI is still using TestWithLocalLibraries:
```
/mnt/resource/j/workspace/dotnet_corefx/dev_api/centos7.1_debug_prtest/Tools/dotnetcli/dotnet /mnt/resource/j/workspace/dotnet_corefx/dev_api/centos7.1_debug_prtest/Tools/run.exe build-managed -os -target-os -distroRid -debug -testWithLocalLibraries -- /p:TestNugetRuntimeId=centos.7-x64 /p:WithoutCategories=IgnoreForCI
10:56:41 Running: /mnt/resource/j/workspace/dotnet_corefx/dev_api/centos7.1_debug_prtest/Tools/msbuild.sh /nologo /verbosity:minimal /clp:Summary /maxcpucount /l:BinClashLogger,Tools/Microsoft.DotNet.Build.Tasks.dll;LogFile=binclash.log /p:OSGroup=Linux /p:TargetOS=Linux /p:TestNugetRuntimeId=centos.7-x64 /p:TestWithLocalLibraries=true /p:ConfigurationGroup=Debug  /flp:v=normal  /flp2:warningsonly;logfile=msbuild.wrn  /flp3:errorsonly;logfile=msbuild.err  /p:TestNugetRuntimeId=centos.7-x64 /p:WithoutCategories=IgnoreForCI
```

**Comment by stephentoub** [comment]
> Looks like CI is still using TestWithLocalLibraries:

The generated changes won't affect this PR. But Jose kicked off the above runs with the changes, and it looks like they all passed.

**Comment by joperezr** [comment]
@stephentoub thanks for clarifying that. @ericstj I added a comment above with the runs that I generated with the changes, and they all passed, so I'm merging this now.

**Comment by ericstj** [comment]
LGTM

**Pull request merged**
