### PR TITLE
Delete Unix-specific ColorTranslator, KnownColor, SystemColors

### PR DESCRIPTION
**Pull request by mellinoe**
We can just replace all of these with the Windows implementation.

As a consequence, I was able to re-enable all of the ColorTranslator tests which were previously failing.

### CODE REVIEW

**Comment by mellinoe** [comment]
Test NETFX x86 Release Build
```
    Starting:    System.Transactions.Local.Tests
      System.Transactions.Tests.CloneTxTests.Run(cloneType: RollbackDependent, isoLevel: Chaos, forcePromote: False, completeClone: False, expectedStatus: Aborted) [FAIL]
        Assert.Null() Failure
        Expected: (null)
        Actual:   System.TimeoutException: Transaction Timeout
        Stack Trace:
          D:\j\workspace\windows-TGrou---2a8f9c29\src\System.Transactions.Local\tests\CloneTxTests.cs(147,0): at System.Transactions.Tests.CloneTxTests.Run(CloneType cloneType, IsolationLevel isoLevel, Boolean forcePromote, Boolean completeClone, TransactionStatus expectedStatus)
```

Test Packaging All Configurations x64 Debug Build
```
java.nio.channels.ClosedChannelException
```
( @dotnet/dnceng )

Test Windows x86 Release Build

(I think this just failed to upload test results)

**Comment by mmitche** [comment]
@mellinoe Where do you see that? https://ci3.dot.net/job/dotnet_corefx/job/master/job/windows-TGroup_netcoreapp+CGroup_Release+AGroup_x86+TestOuter_false_prtest/2878/console

**Comment by mellinoe** [comment]
The ClosedChannelExcepion is [here](https://ci3.dot.net/job/dotnet_corefx/job/master/job/windows-TGroup_all+CGroup_Debug+AGroup_x64+TestOuter_false_prtest/2845/console)

I'm not sure what happened to the other results. I was just guessing based on some of the Infrastructure Logs messages that something had timed out. Those aren't showing up anymore, though.

**Comment by mellinoe** [comment]
Test NETFX x86 Release Build
(Unstable CopyFromScreen tests again -- I'm putting another PR to disable them).

**Comment by mellinoe** [comment]
Test NETFX x86 Release Build

**Pull request merged**
