### PR TITLE
Fix UrlEncodeToBytes returning entire rather than partial array

### LINKED ISSUE #6947: WebUtility.UrlEncodeToBytes erroneously returns the full array if no encoding is needed
This code prints `1 2 3`, when it should print `2 3`:

```csharp
byte[] input = { 49, 50, 51 };
byte[] output = WebUtility.UrlEncodeToBytes(input, offset: 1, count: 2);
foreach (var item in output)
    Console.WriteLine((char)item);
```

The problem seems to be coming from [this](https://github.com/dotnet/corefx/blob/master/src/System.Runtime.Extensions/src/System/Net/WebUtility.cs#L319) line in the internal `UrlEncode` implementation, which returns the whole byte array disregarding the offset and the count.

Luckily I've found out that I accidentally fixed this with #6698, so this can be closed soon enough when that is merged.

cc @stephentoub @davidsh

### PR DESCRIPTION
**Pull request by stephentoub**
Port fix from .NET Framework.

Fixes #6947 
cc: @davidsh, @jamesqo

### CODE REVIEW

**Comment by JonHanna** [comment]
LGTM

**Comment by stephentoub** [comment]
Test Innerloop OSX Debug Build and Test please (https://github.com/dotnet/corefx/issues/4829)

**Comment by bartonjs** [comment]
LGTM

**Comment by jamesqo** [comment]
:ship it:

**Comment by davidsh** [comment]
LGTM

**Comment by stephentoub** [comment]
Test Innerloop Windows_NT Debug Build and Test please (https://github.com/dotnet/corefx/issues/4467)

**Pull request merged**
