### PR TITLE
Consolidate TestData in Complex tests

### LINKED ISSUE #6149: Further work after #5974
Some remaining work needs to be done, brought up in #5974

- consolidate common test data
- refactor test methods (I'm gonna need some more details on this one - it was mentioned but not very much expanded on in the PR)

/cc @mellinoe

### PR DESCRIPTION
**Pull request by hughbe**
- Follow up on PR #5974
- Also cleans up some tests that weren't pulling their weight
- Fixes #6149

/cc @mellinoe

### CODE REVIEW

**Comment by mellinoe** [comment]
Looks good, still reading through all of it to make sure the coverage is still the same as before (I'll do a coverage run as well to see). Overall it's obviously a lot more compact, and there's a lot less duplicated code, which is great.

One thing that I noticed so far: Previously, the `s_validDoubleValues` array included `double.Epsilon`. We don't seem to be testing that value anymore. In two of the test cases, it was used like this, which could probably be another helper method:

```CSharp
foreach (double real in s_validDoubleValues)
{
    foreach (double imaginary in s_validDoubleValues)
    {
        yield return new object[] { real, imaginary };
    }
}
````CSharp

Can we make sure that the test methods using that still have that covered? this is close to the Primitives_2_TestData iterator, but includes double.Epsilon and `double.Min/MaxValue`. The two test methods that used this were `Ctor_Double_Double` and `Negate`. `FromPolarCoordinates` also used `s_validDoubleValues` as well, and doesn't cover `double.Epsilon` any longer.

**Comment by hughbe** [comment]
I didn't see much value in double.Epsilon, but I'll re-add it.

Uh oh, we seem to be having some failures on non-Windows platforms again. I'll investigate.

**Comment by mellinoe** [comment]
I see you changed a few values like this:

````CSharp
- yield return new object[] { double.MaxValue, double.MaxValue, Math.Cos(double.MaxValue) * double.PositiveInfinity, double.NegativeInfinity };

+ yield return new object[] { double.MaxValue, double.MaxValue, double.PositiveInfinity, double.NegativeInfinity };
````

This seems to be the cause of some of the failures. Why were these lines changed?

In checking this out, I also found that there's some behavior differences with `Math.Cos` between platforms. [MSDN says](https://msdn.microsoft.com/en-us/library/system.math.cos(v=vs.110).aspx#Anchor_1) that `Math.Cos` only works up to about 9223372036854775295, less than `double.MaxValue`. On Windows, `Math.Cos(double.MaxValue)` simply returns `double.MaxValue`. On Linux, it is returning -0.99998768942656 for me. I'll try to follow up and figure out why this difference exists.

**Comment by hughbe** [comment]
I realised that, and reverted those changes just now. This may actually be the cause of issue #6022

**Comment by hughbe** [comment]
Just pushed a PR feedback commit, which hopefully addresses the test failures and your comments

**Comment by mellinoe** [comment]
Additional feedback: `Exp_TestData` on line 721 seems to be identical to `Boundaries_2_TestData`, so it can be replaced with that.

**Comment by mellinoe** [comment]
`Cast_SByte_TestData()` is still in the code, but not used anywhere. The test method uses `InlineData` instead now.

**Comment by mellinoe** [comment]
The implicit/explicit casting tests are a bit different from before, but I am okay with the simplification. We should already have acceptable coverage for addition and subtraction, and the two random values for each test were not adding much value.

**Comment by mellinoe** [comment]
The latest version looks good to me. All of the tests passed on my Ubuntu machine so I expect CI will pass. Can you squash the last two commits together into one "PR Feedback" commit?

**Comment by mellinoe** [comment]
@dotnet-bot Test Innerloop CentOS7.1 Debug Build and Test
Test Innerloop OSX Debug Build and Test
Innerloop OSX Release Build and Test

**Comment by mellinoe** [comment]
The last two runs hit the sockets timeout twice in a row, so I'm going to go ahead and ignore those. They are being disabled by #6219 anyways. Thanks for cleaning this up @hughbe.

**Pull request merged**
