### PR TITLE
Enable outerloop runs for centos, rhel, opensuse, ubuntu15.10.

### PR DESCRIPTION
**Pull request by Priya91**
cc @mmitche @stephentoub @joshfree @vijaykota

### CODE REVIEW

**Comment by Priya91** [comment]
@dotnet-bot test ci please

**Comment by Priya91** [comment]
@dotnet-bot test ci please

**Comment by Priya91** [comment]
Requires dotnet/dotnet-ci#205

**Comment by Priya91** [comment]
The dotnet-ci PR is merged.

@dotnet-bot test ci please

**Comment by Priya91** [comment]
@dotnet-bot test ci please

**Comment by mmitche** [comment]
LGTM

**Pull request merged**
