### PR TITLE
Compilation types through attribute: Ternary tests

### PR DESCRIPTION
**Pull request by JonHanna**
Also change verification of exceptions to test specific inputs having specific exceptions, rather than try-and-repeat: Less exceptions thrown and caught, better-defined tests. Also tightens some Equals assertions to be Same assertions.

### CODE REVIEW

**Comment by JonHanna** [comment]
Test Innerloop Ubuntu Release Build and Test 
(Lack of disk space causing failures)
Innerloop Windows_NT Release Build and Test
(Hung process)

**Comment by JonHanna** [comment]
Test Innerloop Windows_NT Release Build and Test

**Comment by JonHanna** [comment]
Test Innerloop Ubuntu Release Build and Test

**Comment by stephentoub** [comment]
LGTM

**Pull request merged**
