### PR TITLE
Cleanup and complete System.Collections.NonGeneric tests

### PR DESCRIPTION
**Pull request by hughbe**
Completely revamped the System.Collections.NonGeneric test project
- Rewrote every single test in the project
- Converted tests to modern xunit testing
- Split individual tests into multiple tests
- Deobfuscate loads of tests
- Remove unnecessary (already covered) tests
- Test uncovered areas of the library
- Removed dead code from the library itself

### CODE REVIEW

**Comment by ianhays** [comment]
Thanks for doing these, @hughbe. I'll take a look through these changes but it'll take me a while :) Also as a heads up (so we don't end up duplicating work), I'm currently working on an overhaul for System.Collections as a resolution to #754.

**Comment by hughbe** [comment]
@ianhays
Awesome! Sorry for such a giant PR for you to review, but my philosophy is that if we fix this old fairly unused library then we don't have as many future issues!

Hugh

**Comment by ianhays** [comment]
>my philosophy is that if we fix this old fairly unused library then we don't have as many future issues!

Agreed!

>Sorry for such a giant PR for you to review,

I'm not too sure on <i>how</i> to review it to be honest. The Github UI limits how many files you can view in a commit and any files past that can't be commented on. I can of course pull the PR and review it on my computer, but that doesn't solve the commenting issue.

Would you mind breaking up the second commit into smaller commits based on the collections whose tests are being altered e.g. a commit for ArrayList tests, a commit for CollectionBase tests, etc. I think that would go a long way in increasing the readability of the changes and make reviewing significantly easier.

Thanks!

**Comment by hughbe** [comment]
@ianhays 
Okay, I've split up the files. I've checked to make sure that some stuff doesn't end up in the wrong commit, but please do alert me if i've screwed up somewhere!

**Comment by hughbe** [comment]
I've just rebased quite a lot of this - the main focus was solving a merge conflict and condensing tests into one file (with the exception of ArrayList)

**Comment by ianhays** [comment]
In HashTableTests.cs, the function PerformActionOnCustomCulture should use a try/finally around the action(); call so that the current culture gets properly set back to the default even if action(); throws.

**Comment by ianhays** [comment]
A lot of these tests set the DefaultThreadCurrentCulture pretty liberally. What kind of concurrency issues are possible here? Xunit tests run concurrently across classes but sequentially within a class such that the ComparerTests will not run overlapped with each other, but they will run overlapped with the CaseInsensitiveComparerTests. 

I also noticed that in some of the tests (e.g. SortedListTests.TestGetObject_DifferentCulture) you set the defaultthreadcurrentculture at the end of the method to "en-us" regardless of what it was at the beginning of the test. We should be setting it to whatever it was at the start of the test

**Comment by ianhays** [comment]
is XunitAssemblyAttribute.cs ever used?

**Comment by ianhays** [comment]
Thanks @hughbe, these tests are looking much better. Think that's all the feedback I've got for now.

The coverage report also looks great: we're at quite nearly 100% with these changes. There are a few untouched lines in HashTable and HashHelpers but everything else is at 100%.

**Comment by hughbe** [comment]
Okay, so I've implemented your requested changes. Couple of points:
- I'm actually not sure about the concurrency issues here - sorry! Have you got any ideas? I do remember that the tests were always like this, even before these changes - have we had any past failures?
- I'm getting a 404 from Jenkins for its coverage builds, and get unexplained errors when building the tests with `/P:Coverage=true` from the command line.
- There's currently a test failure on non-Windows platforms. I'll check that out (since I'm only on Windows, I've added a temporary Console.WriteLine)

**Comment by ianhays** [comment]
>I'm actually not sure about the concurrency issues here - sorry! Have you got any ideas? I do remember that the tests were always like this, even before these changes - have we had any past failures?

We have not that I can recall. If that's the way it has been then it is probably fine unless the split from RunTests to individual methods brought about some issues.

>I'm getting a 404 from Jenkins for its coverage builds, and get unexplained errors when building the tests with /P:Coverage=true from the command line.

I was unaware that we had Jenkins coverage builds for PRs. What are your unexplained errors when building locally? I pulled down your PR and had no trouble running the coverage build, so there may something else going on there.

**Comment by hughbe** [comment]
Here's the coverage build: http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/code_coverage_windows/

I run `msbuild /T:BuildAndTest` in the tests directory, and get the messsage "Test execution summary... Errors: 0, Failed: 0"
I run `msbuild /T:BuildAndTest /P:Coverage=true` in the tests directory, I get the message "Error: one or more tests failed while running tests"

**Comment by ianhays** [comment]
Hm, that's odd. And it's due to the coverage tag and not just an intermittent failure?

**Comment by hughbe** [comment]
Yup - only occurs when the coverage tag is applied

**Comment by ianhays** [comment]
I noticed that there is still some testdata in ArrayList_SynchronizedTests, Does it actually differ there?

Love all the code consolidation

**Comment by ianhays** [comment]
Code coverage went down ever so slightly in the most recent iteration for ArrayListEnumeratorSimple.MoveNext as well as Clear

**Comment by hughbe** [comment]
Okay, I realised the cause of the test failures: #5460 

Is that because of a test bug or a bug in production code?

I'll fix the coverage issue soon

**Comment by ianhays** [comment]
You can just mark the test that is failing as ActiveIssue if that is the cause of the failures

**Comment by hughbe** [comment]
Okay weird question - can you please upload your coverage report (or a screenshot(s) of the missing branches/lines) onto this github thread
This is because I am unable to build any projects in the library when the /P:Coverage=true flag is present (*really* weird)

Thanks a milllion

**Comment by ianhays** [comment]
[new 3.txt](https://github.com/dotnet/corefx/files/105893/new.3.txt)

**Comment by hughbe** [comment]
@ianhays thanks for that. all done!

**Comment by ianhays** [comment]
Thanks @hughbe! @stephentoub

**Comment by stephentoub** [comment]
Before I review again, could you rebase to address the "This branch has conflicts that must be resolved"? Thanks.

**Comment by hughbe** [comment]
Grr merge conflicts suck! Will do

**Comment by hughbe** [comment]
@ianhays makes sense - how about the tests for CaseInsensitiveComparer?

**Comment by ianhays** [comment]
>Also, do you just mean the constructors for the comparers, or the ones for Default and DefaultInvariant

Default and Invariant look fine as is. I mainly want to get rid of all of the code that looks like this:
```
// The following cultures do this the other way round:
// da-DK, is-IS, nb-NO, nn-NO
if (culture.Name != "da-DK" && culture.Name != "is-IS" && culture.Name != "nb-NO" && culture.Name != "nn-NO")
{
```
where we verify Comparer behavior based on what we expect CultureInfo to do.

**Comment by ianhays** [comment]
In doing that, we'll also resolve #5460 since in #5764 I'm removing the System.Collections tests that did this kind of thing.

**Comment by ianhays** [comment]
@Priya91 

System.Runtime.Extensions.Tests.Environment_MachineName.TestMachineNameProperty [FAIL]
08:31:31       Assert+WrapperXunitException : File path: d:\j\workspace\dotnet_corefx\osx_release_bld_prtest\src\System.Runtime.Extensions\tests\System\Environment.MachineName.cs. Line: 16
08:31:31       ---- Assert.Equal() Failure
08:31:31                              ↓ (pos 13)
08:31:31       Expected: dci-mac-bld-5.local
08:31:31       Actual:   dci-mac-bld-5
08:31:31                              ↑ (pos 13)
08:31:31       Stack Trace:
08:31:31             at Assert.WrapException(Exception e, String callerFilePath, Int32 callerLineNumber)
08:31:31             at Assert.Equal(String expected, String actual, String path, Int32 line)
08:31:31          ----- Inner Stack Trace -----
08:31:31             at Assert.Equal(String expected, String actual, String path, Int32 line)
08:31:34 Finished:    System.Runtime.Tests

This might have already been resolved in #5734

**Comment by hughbe** [comment]
Ian, I've updated the PR to include you latest request.
Unfortunately, I had to completely rebase it, as the recent licensing file header changes meant that everything conflicted.

**Comment by Priya91** [comment]
@ianhays The error should be fixed, maybe this build was from before the #5736 PR?

**Comment by hughbe** [comment]
@Priya91 yup it was, but I've now rebased on top of master so this should be fixed

**Comment by hughbe** [comment]
@ianhays pushed a fix for the build failure. That was my fault, caused by rebasing

**Comment by stephentoub** [comment]
Test Innerloop OSX Debug Build and Test please

**Comment by ianhays** [comment]
LGTM. @stephentoub

**Comment by hughbe** [comment]
Glad this hasn't been forgotten. I was just wondering about the tests for SyncRoot and Synchronized for some of these collections - they have their own class at the bottom of the file, and are pretty confusing to understand. 
Are they still necessary?

**Comment by JonHanna** [comment]
If the code's in the assembly, the code should be tested, so I'd say they're still necessary, as much as it would be great to send a cyborg back in time to stop that approach to synchronisation being used :smile: 

You could always circle back on them later though.

**Comment by ianhays** [comment]
>Are they still necessary?

Yes, but imo better to get to them in a future commit as Jon said. I'd rather get this merged sooner so you don't to have to keep rebasing :)

resolves #5460

**Comment by stephentoub** [comment]
@hughbe, thanks for cleaning these up.  I looked at the product changes, and there's a couple things I didn't understand why they needed to be done, so ideally those should be reverted.  For the tests, I skimmed through and generally they looked fine.  @ianhays, if you reviewed all of them in detail and are comfortable with them, looks good.

**Comment by hughbe** [comment]
Okay, I've rebased and fixed the merge conflicts and responded to your PR feedback.
Looking forward to this being merged!

**Comment by ianhays** [comment]
>@ianhays, if you reviewed all of them in detail and are comfortable with them, looks good.

Yup. I'll need to skim through the changes again after the rebase but otherwise it LGTM. Thanks for doing this @hughbe!

**Comment by stephentoub** [comment]
@dotnet-bot test this please

**Comment by hughbe** [comment]
@ianhays
Very happy to help! Glad I've improved the repo in any way I can ;)

**Comment by stephentoub** [comment]
Test Innerloop Ubuntu Debug Build and Test please

**Pull request merged**
