### PR TITLE
Re-enable unicode zip tests for Unix

### PR DESCRIPTION
**Pull request by ianhays**
I'm unable to repro any errors in the tests on my local Ubuntu machine.

### CODE REVIEW

**Comment by ianhays** [comment]
resolves #5096, #5459

**Comment by ellismg** [comment]
It's possible that this is a problem in how the automation copies around files with Unicode characters in their paths.  IIRC, Jenkins had problems with paths like this and I had to do some work in the automation to ensure we didn't generate non-ASCII file-names.  That may explain why you don't see this locally but we do hit it in CI.

**Comment by stephentoub** [comment]
FWIW, I also couldn't repro this locally. Matt's theory seems likely.

**Comment by ellismg** [comment]
It's probable we are running into this: https://issues.jenkins-ci.org/browse/JENKINS-12610.  When I switched us to using packer/unpacker I was getting file delete errors when Jenkins would try to clean the workspace before running a job similar to what's described in that bug.  At the time, I changed the unpacker program to map non ASCII characters to `?` to address the issue (it had looked like Jenkins had been doing this mapping while copying artifacts around previously).

It's possible we can solve this with `LANG` settings, which would be great.  Otherwise, we might need to exclude these tests from Jenkins runs until the upstream issue can be fixed.

**Comment by ianhays** [comment]
>we might need to exclude these tests from Jenkins runs until the upstream issue can be fixed.

Thanks @ellismg. Is there a way to disable a specific test for Jenkins but not for local testing? I was thinking of marking them as [OuterLoop] and adding a comment referencing that issue so that they could still be run locally but would be ignored by the Jenkins runs.

**Comment by ellismg** [comment]
The cleanest way will probably be something like adding another attribute like ActiveIssue (or extending it somehow) to have metadata to say not to run it in Jenkins.  Then, add a flag to our Jenkins runs to exclude items with that metadata.

**Comment by stephentoub** [comment]
> adding another attribute like ActiveIssue (or extending it somehow) to have metadata to say not to run it in Jenkins

Or if there's some mechanism by which we could detect we were in Jenkins in code, using [ConditionalFact("NotRunningInJenkins")].

**Comment by ianhays** [comment]
>The cleanest way will probably be something like adding another attribute like ActiveIssue (or extending it somehow) to have metadata to say not to run it in Jenkins.

>Or we could probably just put a trait on the type and have our CI runs pass -notrait whatever.

I was considering this but only want to add the extra trait if it's applicable to a generally wide range of scenarios. I'm unfamiliar with Jenkins' rate of bugfixes and updates - are there/have there been other cases where we want to exclude a test only from Jenkins? 

If this is a one-off situation then I'd rather hack it with what we've already got then bloat our trait-space. I do not know if it is, though.

**Comment by ianhays** [comment]
I turned them outerloop and added a comment addressing the change for now.

**Comment by ellismg** [comment]
Joe is planning a change that will run outer loop tests on Linux daily.  I would prefer not to merge this as the job will always be red then.

**Comment by ianhays** [comment]
Yeah, this commit won't solve anything in that case.

Looks like an XUnit attribute ```IgnoreForCI``` is the way to go for now.

**Pull request closed without merging**
