### PR TITLE
Coveralls upload

### PR DESCRIPTION
**Pull request by mmitche**
Enable uploading of results to the coveralls service, which provides better badging and analysis of coverage data.

### CODE REVIEW

**Comment by stephentoub** [comment]
Cool. Will this end up uploading even if a dev just runs coverage locally? We probably wasn't to avoid that, and only upload from the CI runs. Otherwise, LGTM.

**Comment by ellismg** [comment]
Could you please rebase away the merge and just move 4025785 on top of c653306?

**Comment by weshaggard** [comment]
I agree with @stephentoub that we should guard this with an extra property that is only set by our coverage CI builds.

**Comment by mmitche** [comment]
Yes.  You came actually upload without the token, which is not coded in.  So someone outside ci cannot upload.

Sent from my Windows Phone
________________________________

**Comment by stephentoub** [comment]
Sounds good.  Thanks, Matt.

**Pull request merged**
