### PR TITLE
Update dogfooding.md

### PR DESCRIPTION
**Pull request by akshatha-harshitha**
Change numbering

### CODE REVIEW

**Comment by stephentoub** [comment]
Thanks. This doesn't actually impact anything, though, right? The rendered results from the markdown will be the same either way, no?

**Comment by danmosemsft** [comment]
Previously it was 0 based in the rendered result, now 1 based. I actually prefer it the way it is, because the 0 is intended to indicate it's a prerequisite to the other steps.

I'm going to close this then. Please, feel free to contribute to an issue marked up-for-grabs.

**Comment by stephentoub** [comment]
> Previously it was 0 based in the rendered result, now 1 based.

Interesting.  I thought markdown always normalized numbering like this.  I guess not.

**Comment by svick** [comment]
@stephentoub 

> I thought markdown always normalized numbering like this. I guess not.

Modern Markdown parsers (those based on CommonMark) [ignore all numbers *except for the first one*](https://spec.commonmark.org/0.28/#start-number). So "1. 1. 1. 1." becomes "1. 2. 3. 4.", while "0. 3. 1. 4." becomes "0. 1. 2. 3.".

**Comment by stephentoub** [comment]
Thanks.

**Pull request closed without merging**
