### PR TITLE
Add System.Data.Common.DataTableMapping unit tests.

### PR DESCRIPTION
**Pull request by LTMenezes**
This pull request adds unit tests to the class System.Data.Common.DataTableMapping.

I'm currently assigned to the issue [#16337](https://github.com/dotnet/corefx/issues/16337). This PR is intended to not only add these unit tests but to also validate that this is the right coding style for the other PR's I will be making regarding this issue.

I tried to follow the existing tests coding style as closely as possible, feedbacks are welcome.

### CODE REVIEW

**Comment by LTMenezes** [comment]
Thanks for the review @keeratsingh, I just fixed it.

**Comment by keeratsingh** [comment]
@dotnet-bot Test NETFX x86 Release Build

**Comment by LTMenezes** [comment]
Thanks @AfsanehR. I just included the license header, I was unsure whether this was a requirement.

**Comment by stephentoub** [comment]
Thanks.

**Pull request merged**
