### PR TITLE
Fix CustomValidationAttribute to properly implement RequiresValidatonContext

### PR DESCRIPTION
**Pull request by stephentoub**
Squashed replacement for https://github.com/dotnet/corefx/pull/3794

### CODE REVIEW

**Comment by stephentoub** [comment]
@dotnet-bot test this please ("Hung process on target machine")

**Comment by stephentoub** [comment]
@mmitch, FYI, the build for this PR has failed a few times, with all of the legs hitting "A process is hung on the target machine and preventing it from cleaning up the workspace" errors.

**Comment by mmitche** [comment]
@stephentoub Looking into it.

**Comment by stephentoub** [comment]
@dotnet-bot test this please

**Pull request merged**
