### PR TITLE
Specify the full path to python3 in perf jobs

### PR DESCRIPTION
**Pull request by adiaaida**

### CODE REVIEW

**Comment by adiaaida** [comment]
@DrewScoggins PTAL. This fixes the issues we are seeing with dotnet/core-eng#4400

**Comment by adiaaida** [comment]
@dotnet-bot test ci please

**Comment by adiaaida** [comment]
I've reopened this issue because we continue to see the python 103 error, despite adding the py.ini file to the machines. It seems to be a sporadic issue that pops up on random machines at random times, with the only fix being to log on to the machines, which is not a good use of our time. So this change is now needed.

**Comment by DrewScoggins** [comment]
LGTM

**Comment by adiaaida** [comment]
@dotnet-bot test ci please

**Pull request merged**
