### PR TITLE
Delete stale HttpClientHandler.Unix.cs file from repo

### PR DESCRIPTION
**Pull request by stephentoub**
There are currently two HttpClientHandler.Unix.cs files checked in:
- One in System.Net.Http\src\System\Net\Http
- One in System.Net.Http\src\System\Net\Http\Unix

The former is the original stubbed out version, throws from every property, and isn't referenced by the .csproj, whereas the latter is where all of the recent development related to CurlHandler has happened.

This PR simply deletes the former to avoid confusion, and then moves the latter up one level so that it continues to be next to its .Windows.cs counterpart. (The GitHub diff makes it looks like I actually changed .cs file content, which I didn't; I left it as two commits to make it more evident that I simply deleted a file, moved another, and then made a two-line change to the .csproj.)

cc: @davidsh, @vijaykota, @kapilash

### CODE REVIEW

**Comment by stephentoub** [comment]
@dotnet-bot test this please
(failed due to https://github.com/dotnet/corefx/issues/3070)

**Comment by stephentoub** [comment]
@dotnet-bot test this please

**Comment by vijaykota** [comment]
LGTM

**Comment by davidsh** [comment]
LGTM

**Comment by stephentoub** [comment]
Thanks, @davidsh and @vijaykota.

**Pull request merged**
