### PR TITLE
Re-enable XML theories with English-only variants

### PR DESCRIPTION
**Pull request by stephentoub**
cc: @krwq
Fixes https://github.com/dotnet/corefx/issues/30017

### CODE REVIEW

**Review by krwq — APPROVED** [review]
LGTM, Thank you!

**Comment by danmosemsft** [comment]
failing tests .. rerunning to see info

**Comment by stephentoub** [comment]
> failing tests .. rerunning to see info

The failures are legit, in that this didn't fix them even though it did fix them locally.  Just need to get back around to figuring out why.

**Comment by krwq** [comment]
@stephentoub is it possible it's CurrentCulture vs CurrentUICulture?

**Pull request merged**
