### PR TITLE
Fix ConnectionTimeoutTestWithThread test

### LINKED ISSUE #26382: SqlConnectionTimeout test failing breaking CI
https://mc.dot.net/#/user/dotnet-maestro-bot/pr~2Fjenkins~2Fdotnet~2Fcorefx~2Fmaster~2F/test~2Ffunctional~2Fcli~2F/5130e06922a1491ff02ed162fd53459ec3d2ba5e/workItem/System.Data.SqlClient.Tests

@geleems  it is failing on Win10 and Win8.1 in CI jobs since https://github.com/dotnet/corefx/pull/26306

```

Assert.True() Failure
Expected: True
Actual:   False
Stack Trace :
   at System.Data.SqlClient.Tests.SqlConnectionBasicTests.ConnectionTimeoutTestWithThread() in D:\j\workspace\windows-TGrou---74aa877a\src\System.Data.SqlClient\tests\FunctionalTests\SqlConnectionBasicTests.cs:line 110
```

### PR DESCRIPTION
**Pull request by aerworker**
Port the change #28618 into 2.0

Fixes #26382
SqlConnectionTimeout test failing breaking CI

### CODE REVIEW

**Comment by aerworker** [comment]
@geleems Review please

**Comment by karelz** [comment]
@aerworker why is the test fix needed in release/2.0.0 branch? Is it failing 2.0.x CI often?
@geleems do you have any background on the backport?

If it is indeed important, it has to go through shiproom first.

**Comment by karelz** [comment]
cc @saurabh500

**Comment by karelz** [comment]
@saurabh500 can you please comment on the background / reason to backport this particular test failure? Does your team plan to bring it to shiproom?

**Comment by aerworker** [comment]
@karelz For the issue #28771 CI was run 2 times and all was failed. If it doesn't prevent pull request from merging we should just keep it in mind.

**Comment by karelz** [comment]
Thanks @aerworker for the background / motivation. I let area owners decide if they want to make the case to port the test fix into 2.0.x branch ...

**Comment by stephentoub** [comment]
Why wouldn't we port it? Windows legs are failing in the release/2.0 branch due to this, e.g. https://mc.dot.net/#/user/dotnet-maestro-bot/pr~2Fjenkins~2Fdotnet~2Fcorefx~2Frelease~2F2.0.0~2F/test~2Ffunctional~2Fcli~2F/06e0c877863902713845dca9a2ddf7c910afa54b/workItem/System.Data.SqlClient.Tests.

**Comment by karelz** [comment]
That's 4 failures in 1 run. @keeratsingh @David-Engel @AfsanehR it seems worth bringing it into 2.0.x. Can you please send it to .NET Core shiproom?

**Comment by danmosemsft** [comment]
Tell mode for test only changes.

**Pull request merged**
