### PR TITLE
Fix S.G.Extensions tests for netfx

### PR DESCRIPTION
**Pull request by danmosemsft**
@safern again I see the failures in MC but for some reason don't find issues for them https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Fdesktop~2Fcli~2F/build/20170418.01/workItem/System.Globalization.Extensions.Tests

### CODE REVIEW

**Comment by safern** [comment]
Still opening issues. Thanks for pointing that out!

**Comment by danmosemsft** [comment]
That's fine our focus is on other areas. I'm just picking off easy ones.

**Comment by safern** [comment]
Thanks! Appreciate the help.

**Comment by tarekgh** [comment]
@danmosemsft @ViktorHofer I left some comment on this PR, please consider it. thanks.

**Comment by danmosemsft** [comment]
I don't see it @tarekgh..

**Comment by tarekgh** [comment]
@danmosemsft 

We are going to port these to the desktop anyway so it would be nice if we keep testing this on the desktop too. we may split this method into 2 one for the desktop and one for non desktop.

CC @AlexGhiondea as he is defining the behavior on the desktop when getting null reference

**Comment by danmosemsft** [comment]
Didn't I split the method in such a way? I could have checked for NullReferenceException instead, I guess that wo9uld then trigger a failure when you did the port. Let me know what you prefer and I can throw it up.

**Comment by tarekgh** [comment]
What I meant the test of 

```C#
StringNormalizationExtensions.IsNormalized(null)
```

now is not done on the desktop. we are going to have this case on the desktop so it is worth to test it. the other idea is to ensure that the desktop and the net core behaviors are same and we don't have to skip it on the desktop.

**Comment by danmosemsft** [comment]
This test was previously this -- 
```
            Exception exception = Record.Exception(() => ((string)null).Normalize());
            
            // On desktop Normalize is not extension method, trying to do ((string)null).Normalize()
            // will get NullReferenceException, in .Net Core we use extension method which will throw
            // ArgumentNullException
            Assert.True((exception is ArgumentNullException) || (exception is NullReferenceException));

```

before that was a .NET FX specific test:
```
            // Ensure that extension method not used by current framework.
            Assert.Throws<NullReferenceException>(() => ((string)null).Normalize());
```

I can change it to any of these.. but why not add the test if and when we add to desktop?

**Comment by tarekgh** [comment]
I am fine if we delay adding it to the desktop. at least we want to ensure consistency between desktop and net core which I believe @AlexGhiondea already looking at that.

**Pull request merged**
