### PR TITLE
Cleanup TextInfo tests

### PR DESCRIPTION
**Pull request by hughbe**
Move text info tests to their new more up to date modern files

/cc @tarekgh @stephentoub

### CODE REVIEW

**Comment by tarekgh** [comment]
LGTM.

**Comment by hughbe** [comment]
Test Innerloop OSX Debug Build and Test please
Test Innerloop OSX Release Build and Test please
Test Innerloop Ubuntu Debug Build and Test please
Test Innerloop Ubuntu Release Build and Test please

**Comment by stephentoub** [comment]
Test Innerloop OSX Debug Build and Test please
Test Innerloop OSX Release Build and Test please
Test Innerloop Ubuntu Debug Build and Test please
Test Innerloop Ubuntu Release Build and Test please

(service unavailable)

**Comment by stephentoub** [comment]
@dotnet-bot test this please

**Comment by stephentoub** [comment]
Test Innerloop CentOS7.1 Debug Build and Test please
Test Innerloop OSX Release Build and Test please

**Pull request merged**
