### PR TITLE
Remove win10 jobs that depend on deprecated functionality

### PR DESCRIPTION
**Pull request by mmitche**
The Win10 images are no longer working (they were a pre-release version of Win Server 2016).  The Win10 functionality is now available in the new Portable builds.

Remove these old jobs for now (they get queued and never run)

See #20107

### CODE REVIEW

**Comment by mmitche** [comment]
@dotnet-bot test ci please

**Comment by davidsh** [comment]
>The Win10 images are no longer working (they were a pre-release version of Win Server 2016). The Win10 functionality is now available in the new Portable builds.

Can we get Windows 10 images that are based on client SKUs like Windows 10 Professional.  Using Windows Server 2016 to simulate "Windows 10" means that we don't get most recent Windows 10 builds/releases such as Creators Update and future Fall Creators Update.  We are going to need that in CI for UWP work.

cc: @karelz @DavidGoll

**Comment by karelz** [comment]
@danmosemsft @joshfree what is your thinking about UWP in CI/Helix?

**Comment by mmitche** [comment]
@davidsh That's what Helix is using.

**Comment by davidsh** [comment]
>@davidsh That's what Helix is using.

What do you mean by "That's"?  What version of Windows 10 is that?  And can the Jenkins/CI Win10 images (available via @dotnet-bot Test *) use those also?

**Comment by joshfree** [comment]
> @danmosemsft @joshfree what is your thinking about UWP in CI/Helix?

We will be adding UWP as pre-checkin once the tests are fully stood up.

**Comment by mmitche** [comment]
@MattGal can confirm, but I believe Helix targets Win10 enterprise.

Yes, the Jenkins CI can build on traditional VMs, then submit to Helix for testing.  This covers this scenario.

**Comment by MattGal** [comment]
@mmitche actually for all except AppCompat (which uses a Windows 10 Client SKU) our Windows 10 machines are actually Server 2016 DataCenter (Azure Image version 2016.127.20170421 currently).  

This SKU seems OK to run store apps (all UAP F5 scenario test results come from machines running this; the test actually executes inside an AppX).  If we need specific Client SKUs we'll need to prepare our own images for this instead of using default Azure ones.

**Comment by mmitche** [comment]
@dotnet-bot test portable windows debug pipeline
@dotnet-bot test portable linux debug pipeline
@dotnet-bot test portable windows release pipeline
@dotnet-bot test portable linux release pipeline

**Comment by danmosemsft** [comment]
@MattGal leaving UWP aside, Server 2016 is older code than Creators Edition, which presumably will be he most relevant Windows 10 edition when we ship. Is it possible/would it make sense to run on something newer -- if there's no Server matching that, then maybe Creators Edition itself?

**Comment by mmitche** [comment]
@danmosemsft can correct but, but running the client OS's in Azure can be a bit of a pain.

**Comment by mmitche** [comment]
@dotnet-bot help

**Comment by danmosemsft** [comment]
@mmitche for now we're at least getting inner loop coverage from all of us with Creators Edition dev boxes  so we know we're not in a bad state there. But yeah, for proper coverage and for UWP we will have to solve the problem of runs on actual client at some point.

**Comment by mmitche** [comment]
@dotnet-bot test portable windows debug pipeline
@dotnet-bot test portable linux debug pipeline
@dotnet-bot test portable windows release pipeline
@dotnet-bot test portable linux release pipeline

**Pull request merged**
