### PR TITLE
Update Tizen ci docker image

### PR DESCRIPTION
**Pull request by gbalykov**
Update Tizen CI docker image to ubuntu-16.04.

Related issue: #28901 

cc @Dmitri-Botcharnikov @alpencolt

### CODE REVIEW

**Comment by gbalykov** [comment]
@dotnet-bot help

**Comment by gbalykov** [comment]
@dotnet-bot test Tizen armel Release

**Comment by gbalykov** [comment]
@dotnet-bot test Tizen armel Release

**Comment by gbalykov** [comment]
@dotnet-bot test Tizen armel Release

**Comment by gbalykov** [comment]
@dotnet-bot test Tizen armel Release

**Comment by gbalykov** [comment]
@dotnet-bot test this please

**Comment by gbalykov** [comment]
@dotnet-bot test Tizen armel Release

**Comment by stephentoub** [comment]
@gbalykov, can/should this be merged?
cc: @joshfree, @RussKeldorph

**Comment by joshfree** [comment]
@stephentoub I'll defer this to @RussKeldorph @hqueue @alpencolt and the @dotnet/arm32-contrib folks working in this space

**Comment by RussKeldorph** [comment]
I don't have any objection to this.  I can merge it if you like, but I'm not likely to keep an eye on whether it causes failures.

**Comment by gbalykov** [comment]
@stephentoub, this is still work in progress, as same testing for CoreCLR doesn't fully work yet

**Comment by gbalykov** [comment]
@dotnet-bot test this please

**Comment by gbalykov** [comment]
@dotnet-bot test Tizen armel Release

**Comment by gbalykov** [comment]
@dotnet-bot test Tizen armel Release

**Comment by gbalykov** [comment]
@dotnet-bot test Tizen armel Release

**Comment by gbalykov** [comment]
@dotnet-bot test ci please

**Comment by gbalykov** [comment]
@stephentoub @RussKeldorph, could this be merged? same PR for CoreCLR (dotnet/coreclr#17814) is in master now

**Pull request merged**
