### PR TITLE
Fix argument name & use nameof instead of magic string

### PR DESCRIPTION
**Pull request by Youssef1313**

### CODE REVIEW

**Comment by Youssef1313** [comment]
> 
> 
> The code changes LGTM.
> 
> I see that no tests are changed as part of this. Does that mean there aren't any? It'd be good to tweak the tests to ensure that a) there are tests validating that an ArgumentNullException is thrown when `pen` is null, and b) that such an exception includes "pen" as the parameter name.

Yes, I think the tests [here](https://github.com/dotnet/corefx/blob/master/src/System.Drawing.Common/tests/GraphicsTests.cs) are related to that file change, However, I think it won't be affected by this change, but I'm not very sure.

**Comment by stephentoub** [comment]
Can you please add additional lines here to cover these overloads?
https://github.com/dotnet/corefx/blob/7a9c2ab617229faad613fa5554b298df388f6fb7/src/System.Drawing.Common/tests/GraphicsTests.cs#L2385-L2387

**Comment by Youssef1313** [comment]
> 
> 
> Can you please add additional lines here to cover these overloads?
> 
> https://github.com/dotnet/corefx/blob/7a9c2ab617229faad613fa5554b298df388f6fb7/src/System.Drawing.Common/tests/GraphicsTests.cs#L2385-L2387

May you clarify what is needed in these tests ? I didn't get it.

**Comment by stephentoub** [comment]
> May you clarify what is needed in these tests ? I didn't get it.

There are no tests there for the overloads you're modifying.  But there should be.

**Comment by Youssef1313** [comment]
> 
> 
> > May you clarify what is needed in these tests ? I didn't get it.
> 
> There are no tests there for the overloads you're modifying. But there should be.

I've modified the `DrawRectangles` function with. And I see the tests for the two overloads starting from line `2446` in the tests file. Am I getting something wrong ?

**Comment by stephentoub** [comment]
> Am I getting something wrong ?

In that case you need to remove:
https://github.com/dotnet/corefx/blob/7a9c2ab617229faad613fa5554b298df388f6fb7/src/System.Drawing.Common/tests/GraphicsTests.cs#L2444
as that's preventing those tests from running.

**Comment by Youssef1313** [comment]
> 
> 
> > Am I getting something wrong ?
> 
> In that case you need to remove:
> 
> https://github.com/dotnet/corefx/blob/7a9c2ab617229faad613fa5554b298df388f6fb7/src/System.Drawing.Common/tests/GraphicsTests.cs#L2444
> 
> as that's preventing those tests from running.

Removed it :)

**Pull request merged**
