### PR TITLE
Adding alpine 3.8 to the RID graph

### PR DESCRIPTION
**Pull request by joperezr**
cc: @eerhardt @MichaelSimons @ericstj 

related issue: #34316

I haven't added a RID in the past so I'm not sure if these are all the changes that are required, so please do let me know if there is anything I missed.

### CODE REVIEW

**Comment by MichaelSimons** [comment]
Should 3.9 be added right away as well?  Indications are 3.9 will be out well before .NET Core 3.0 ships.

**Comment by eerhardt** [comment]
What are the plans on back-porting this change to `2.1` and/or `2.2`?

> I haven't added a RID in the past so I'm not sure if these are all the changes that are required, so please do let me know if there is anything I missed.

This looks like the right change to add a new version.

**Comment by joperezr** [comment]
> Should 3.9 be added right away as well? Indications are 3.9 will be out well before .NET Core 3.0 ships.

I'm not sure if we have added a RID in the past without being actually released. If we have or have no problem with doing it, then I'm happy to add it here as well.

**Comment by joperezr** [comment]
> What are the plans on back-porting this change to 2.1 and/or 2.2?

Once this is in for master, the idea is to submit to shiproom the issue so that we can backport. Once that is approved, then we can port it to both 2.1 and 2.2

**Comment by eerhardt** [comment]
> I'm not sure if we have added a RID in the past without being actually released.

We added `ubuntu.18.10` a month before it actually was released:

https://github.com/dotnet/corefx/commit/321a87d9dffb4de480599895f55afd4093bc6613 (Sept 13, 2018)

https://xubuntu.org/release/18-10/ (October 18, 2018)

**Comment by joperezr** [comment]
Failures in CI are unrelated to this PR so I'll go ahead and merge. Thanks for the reviews!

**Pull request merged**
