### PR TITLE
Port to rc2: Adding System.Buffers support to the System.IO.Compression namespace

### PR DESCRIPTION
**Pull request by sokket**
Adding System.Buffers support to the System.IO.Compression namespace

Porting to RC2 from master

### CODE REVIEW

**Comment by ellismg** [comment]
@dotnet-bot test this please

**Comment by ellismg** [comment]
@sokket Can you look at these failures?  It looks like this new component wants to use a different version of packages.

**Comment by sokket** [comment]
@dotnet-bot test Innerloop OSX Debug Build and Test

**Comment by sokket** [comment]
@dotnet-bot test Innerloop OpenSUSE13.2 Release Build and Test

**Comment by sokket** [comment]
Fixed the package version issues. The other failed tests on OSX and OpenSuSE are known issues with bugs already tracking, so re-testing

**Pull request merged**
