### PR TITLE
Use constants instead of literal numbers

### PR DESCRIPTION
**Pull request by tmat**
A little bit of cleanup

### CODE REVIEW

**Comment by tmat** [comment]
@nguerrera

**Comment by stephentoub** [comment]
@tmat, @nguerrera, what's the status of this PR?

**Comment by tmat** [comment]
test this please

**Comment by tmat** [comment]
@nguerrera Please review.

**Comment by tmat** [comment]
test this please

**Comment by nguerrera** [comment]
:+1:

**Comment by tmat** [comment]
test this please

**Pull request merged**
