### PR TITLE
Update to buildtools 208

### PR DESCRIPTION
**Pull request by mellinoe**
Has a few fixes we want, including one which should fix the outer-loop failures we've been seeing on non-Windows runs.

@Priya91

### CODE REVIEW

**Comment by stephentoub** [comment]
LGTM

**Comment by mellinoe** [comment]
This will fix #7035

**Comment by joshfree** [comment]
Thanks @mellinoe

**Comment by Priya91** [comment]
@dotnet-bot test outerloop Ubuntu14.04 debug

**Pull request merged**
