### PR TITLE
Fixing Forward-Slash Issue

### PR DESCRIPTION
**Pull request by joperezr**
fixes: #3534 

CC: @weshaggard @AtsushiKan

### CODE REVIEW

**Comment by AtsushiKan** [comment]
Might be worth adding a conspicuous comment here...

https://github.com/dotnet/corefx/pull/8508/commits/779d779ac2da1884ee13fd154f46535a58579067#diff-0b192804a6349e8c26d2b027afbd89a2L36

and here...

https://github.com/dotnet/corefx/pull/8508/commits/779d779ac2da1884ee13fd154f46535a58579067#diff-0b192804a6349e8c26d2b027afbd89a2L491

that these two properties are receiving the special treatment because VS navigation will break without them.

Otherwise, LGTM. Thanks.

**Comment by joperezr** [comment]
will add the comments.

**Comment by joperezr** [comment]
@dotnet-bot test Innerloop Windows_NT Release Build and Test please

**Comment by weshaggard** [comment]
I'm not sure how I feel about this being in our dir.props file. If we are going to expect people to start depending on this new property we should consider moving it to build.common.props in build tools. This is a prime example of something I don't want to be copy and pasted in every repo.

**Comment by joperezr** [comment]
I see, I can do that as well. Would you also want OsEnvironment moved? or just the pathseparator

**Comment by weshaggard** [comment]
I actually want most of dir.props moved :) I just haven't had time to dig through it yet.

**Comment by akoeplinger** [comment]
Why not just change the separator to backslash? MSBuild handles this xplat.

**Comment by weshaggard** [comment]
@akoeplinger That is an option as well

**Comment by AtsushiKan** [comment]
Either the backslash or $(PathSeparator) LGTM. As long as it works cross-plat. And as this issue is causing pain right now, I’d like to see this merged in a timely manner and not get blocked on some future task to move things into the shared build tools.

**Comment by joperezr** [comment]
@akoeplinger We've seen problems in the past where msbuild creates folders that include backslashes in the names, but I have verified that at least with this two properties msbuild behaves correctly, so I'll go ahead and just change them to backslash for now, and then we will do the cleanup in dir.props as @weshaggard suggests

**Pull request merged**
