### PR TITLE
Add System.ServiceModel.Syndication tests

### PR DESCRIPTION
**Pull request by hughbe**
Extracted from https://github.com/dotnet/corefx/pull/29882

Designed to make to be merged before the aforementioned PR so that that PR only contains product code changes that are verified with testing

### CODE REVIEW

**Comment by stephentoub** [comment]
cc: @mconnew

**Comment by mconnew** [comment]
@hughbe, thankyou for this. It makes the changes a lot more digestible. There are some minor conflicts that need to be resolved. Once you've done that, this PR looks good. I'll take one last look through it after the conflicts are resolved and then I'll merge.

**Comment by hughbe** [comment]
Unrelated test failures

**Comment by mconnew** [comment]
Confirmed failure is unrelated. LGTM

**Pull request merged**
