### PR TITLE
Add FreeBSD support to System.Console.

### PR DESCRIPTION
**Pull request by janhenke**
This commit adds the necessary Interop pieces necessary for System.Console. Also add FreeBSD to the System.Console project.

### CODE REVIEW

**Comment by Maxwe11** [comment]
>Add FreeBSD support to System.Console

Sounds like implementation but this just interops :smile: 
Why this should get in repo before implementation?

**Comment by janhenke** [comment]
FreeBSD is a Unix system. There is already a Unix implementation. If you take a look into the files, the Interops are actually the only thing being different between Linux/OS X (and FreeBSD).

**Comment by Maxwe11** [comment]
@janhenke :+1: yeah but I'm confused that `src/Common/src/Interop/FreeBSD/Interop.Libraries.cs` not included in csproj

**Comment by janhenke** [comment]
That one file is not used by System.Console. It is actually identical to the Linux Interop file with the same name. Since the content is trivial, I added it as well. I assume some other assembly will need it.

**Comment by stephentoub** [comment]
I didn't check the values used, but the mechanics of the change LGTM. Nice job plugging this in.

**Comment by josteink** [comment]
I agree with @janhenke on this one.

While `Libraries` isn't used right now, it logically belongs with the rest of those files and it makes sense to introduce them all in the same commit. It will probably come to use sooner rather than later.

LGTM

**Pull request merged**
