### PR TITLE
Factor out large generic additions in System.Linq for uap build

### PR DESCRIPTION
**Pull request by stephentoub**
New generic types in System.Linq are causing significant size-on-disk increases in AOT builds of some apps that make heavy use of LINQ.  This PR addresses some of the key changes:

- The many implementations of `IPartition<T>` and `IIListProvider<T>` are causing a significant number of generic instantations.  I've factored out the majority of those large changes to only be used in a netcoreapp build, not in a uap build.  There are still code paths that test whether an object is `IPartition<T>` or `IIListProvider<T>`, but there are no types now in the uap build that implement them, so those checks are nops.  This does mean that there are still generic instantiations generated for those interfaces, but the bulk of the impact came from the types that implemented them and everything they brought in.
- As part of this, I replaced several places where `EmptyPartition<TResult>.Instance` was being used directly to implement an `IEnumerable<T>`, changed them to use `Enumerable.Empty<T>`, and then changed `Enumerable.Empty<T>` so that on netcoreapp it returns `EmptyPartition<TResult>.Instance`, and on uap it returns `Array.Empty<T>`.  This does mean now that code paths lighting-up on partitions will also light-up on `Enumerable.Empty<T>`.  It also means that I changed the empty partition's `IEnumerator.Reset` method to be a nop instead of throwing, to match the same behavior as array's `IEnumerator.Reset`.
- `LargeArrayBuilder` uses `T[][]`, which introduces lots of new array types and corresponding interface instantiations, helper types, etc.  I've specialized `LargeArrayBuilder` in the uap build to just be a thin wrapper around `ArrayBuilder`; we still end up with unnecessary instantiations of `LargeArrayBuilder`, but they're relatively small, and it saves everything to do with those T[][] instantiations while also avoiding having to special case all of the various usage sites of `LargeArrayBuilder`.

For one sizeable app, these changes represent an ~10% reduction in total size-on-disk for the whole app.

I went back and forth on whether to use ifdefs with compilation constants or whether to use partial files, and decided on the latter, but if there's a strong preference for the former, let me know and I can switch.  ifdefs make a few things easier (e.g. we could then also remove some of the `s is IPartition<T>` checks that remain as nops) but end up with lots of ifdef'ing being littered throughout the codebase, whereas for the most part, the partial files approach keeps things very clean, with only a couple cases where workarounds were needed.

cc: @OmarTawfik, @VSadov, @JonHanna, @jamesqo, @danmosemsft, @MichalStrehovsky, @jkotas

### CODE REVIEW

**Comment by jamesqo** [comment]
If you think the trade-off for removing the specializations is worth it on UAP, then LGTM

**Comment by VSadov** [comment]
I like the approach with partial classes. 
The separation of non-uwp code looks pretty clean.

**Comment by jkotas** [comment]
I am not sure whether netcoreapp vs. uap are the right names to use for the implementation files. This is really about implementation optimized for size (fixed footprint) vs. speed.

I expect that Mono will want to use the implementation optimized for size on their device targets. cc @marek-safar It will look odd to use Uap files for watchOS. 

The implementation optimized for size may be the right default for the netcoreappaot flavor being added in a different PR.

**Comment by stephentoub** [comment]
> I am not sure whether netcoreapp vs. uap are the right names to use for the implementation files. This is really about implementation optimized for size (fixed footprint) vs. speed.

I'd considered this, but didn't come up with any great naming scheme.  What would you recommend?

**Comment by jkotas** [comment]
Maybe use .SizeOpt.cs vs. .SpeedOpt.cs ?

**Comment by stephentoub** [comment]
> Maybe use .SizeOpt.cs vs. .SpeedOpt.cs ?

Hmm.  I guess we could do that.  It looked a bit weird to me in cases where both weren't used, e.g. it's obvious when you're choosing between them when you've got all three of Foo.cs, Foo.SizeOpt.cs, and Foo.SpeedOpt.cs, but it seems less clear when you've got just Foo.cs and Foo.SpeedOpt.cs, as then you're not choosing between two options, and rather it's a question of whether to use the .SpeedOpt.cs or not.  Maybe I've just been staring at these too long :)

**Comment by marek-safar** [comment]
@jkotas is correct and we'd be interested in such optimizations as well. I didn't see any numbers on the performance but perhaps if they are not significant we could just have SizeOpt version.

About the naming, I'd totally fine with `SizeOpt.cs`, `SpeedOpt.cs` or similar suffixes applied to all relevant files.

**Comment by VSadov** [comment]
Perhaps just `.Opt.cs` ?     (to stand for Optional/Optimizations )

Many optimizations here are to reduce allocations. Ultimately the goal is to improve throughput, but it could be confusing to place those between Size/Speed buckets.
Besides with AOT improvements in almost any metric tend to require size-on-disk increases.

**Comment by VSadov** [comment]
Also could be  `.Big.cs` ?  
As in optional additions appropriate for "bigger" environments?

**Comment by stephentoub** [comment]
> Many optimizations here are to reduce allocations.

Yes, though the majority here are about reducing algorithmic complexity / improving throughput, e.g. optimizing patterns like OrderBy().Select().Take().  For example, this repro:
```C#
using System;
using System.Diagnostics;
using System.Linq;

class Program
{
    static void Main()
    {
        int[] items = new int[5_000_000];
        var r = new Random();
        for (int i = 0; i < items.Length; i++) items[i] = r.Next();

        var sw = new Stopwatch();
        while (true)
        {
            sw.Restart();
            items.OrderByDescending(i => i).Select(i => i).Take(50).ToArray();
            Console.WriteLine(sw.Elapsed);
        }
    }
}
```
reports times like 0.13 seconds with the "speed-optimized" version, and times like 1.97 seconds with the "size-optimized" version.

> Perhaps just .Opt.cs ? (to stand for Optional/Optimizations )

There are a variety of cases where we need all three files, e.g. the shared file, the one for speed, or the one for size.

I'll just go with .SizeOpt.cs and .SpeedOpt.cs for now.

**Comment by stephentoub** [comment]
@dotnet-bot test NETFX x86 Release Build please (unrelated failures)
@dotnet-bot test Windows x86 Release Build please (unrelated failures)

**Pull request merged**
