### PR TITLE
Fix package ID for x64 sni package dependency

### PR DESCRIPTION
**Pull request by ericstj**
Fixes the issue pointed out after merging https://github.com/dotnet/corefx/pull/9123
/cc @weshaggard @ellismg @jhendrixMSFT

### CODE REVIEW

**Comment by ellismg** [comment]
LGTM.  Is it possible for us to fix up the existing package that was built in TFS tonight?  I was running into issues due to the wrong authoring when trying to consume the TFS build for SNI and Compression with the pipeline builds of CoreCLR and CoreFX.

**Comment by ericstj** [comment]
I can fix it, which version do you want me to fix?

**Comment by ericstj** [comment]
I'll fix up bot the RC3 and RC4 builds.

**Comment by ellismg** [comment]
Thanks Eric, rc3-24204-00 is the one I care about most.

**Comment by ericstj** [comment]
Ok, both have been fixed.

**Comment by ericstj** [comment]
Windows build is hanging in System.Net.Http.Functional.Tests again.

**Comment by ericstj** [comment]
@dotnet-bot test Innerloop Windows_NT Release Build and Test

**Pull request merged**
