### PR TITLE
Update buildtools to 1.0.25-prerelease-00136

### PR DESCRIPTION
**Pull request by ericstj**

### CODE REVIEW

**Comment by ericstj** [comment]
@dotnet-bot test Innerloop OpenSUSE13.2 Debug Build and Test

**Comment by ericstj** [comment]
Looks like all recent PRs are failing Innerloop OpenSUSE13.2 Debug Build and Test on what seems to be string comparison tests.  Did something change here? /cc @ellismg @weshaggard

**Comment by ellismg** [comment]
They pass sometimes, it seems.  I think this is due to some of the recent CLR changes (maybe around the JIT FI from 4.6.1) but I'm not sure.  I've been running some jobs to try to figure out when the regression was introduced.  Nothing has changed in Globalization recently.

**Comment by ericstj** [comment]
The last package update we took that would have brought in a new CLR was @stephentoub's change  https://github.com/dotnet/corefx/commit/6f6303f0356be4d2dd4ac117373f1e37f8752248 over a week ago.  Looking at the [build history](http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/opensuse13.2_debug_tst_prtest/) it seems this just failing on 12/18 around 1PM.

**Comment by ellismg** [comment]
We don't consume the CLR for the cross platform builds in CI.  We always copy the latest Jenkins master build.

**Comment by ericstj** [comment]
Ah, I see.  That explains it.  I was looking at the corefx changes and couldn't find any correlation.  Any objection to merging this despite the failing CI?

**Comment by ellismg** [comment]
No objections here.  In fact, I would prefer that was update the CI definitions to exclude openSUSE until we figure this out (may be after the holidays unfortunately, I am traveling this week and won't have much time to dig in).

**Comment by weshaggard** [comment]
No objections from me either, I've already been ignoring those results for recent merges.

**Pull request merged**
