### PR TITLE
Update branding for 3.1.21

### PR DESCRIPTION
**Pull request by vseanreesermsft**

### CODE REVIEW

**Comment by vseanreesermsft** [comment]
@GrabYourPitchforks, @dotnet/dnceng  can you help with the MacOS build failure?

**Comment by ulisesh** [comment]
We are taking a look

**Comment by ulisesh** [comment]
After some investigation, this doesn't look like an infrastructure issue. Helix executed the test successfully but the test had some certs issues and someone in the repo has to investigate.

**Comment by vseanreesermsft** [comment]
@ulisesh is it OK to merge this PR in the meantime?

**Comment by GrabYourPitchforks** [comment]
I think we need to backport https://github.com/dotnet/runtime/pull/48460 here. The certificates that were part of the original test expired, and it's causing chain building issues that are causing this test to fail across all PRs.

@vcsjones @bartonjs Does this assessment sound correct to you?

(Assuming this assessment is correct, I wouldn't let this block merge.)

**Comment by bartonjs** [comment]
It.... might? be related to that root going out of favor, but shouldn't.  The test is using an explicit verification time and suppressing any errors other than NotTimeValid, so whether it got UnknownRootAuthority or PartialChain it should have been suppressed.

I guess there's a possibility that Apple has moved it into ExplicitDistrust, which is a failure code that can't be suppressed.

**Comment by bartonjs** [comment]
Looks like 3.1's build script doesn't work on macOS 12, so I need to dust off the legacy mac and let it update a bunch to see what's going on.

But, I agree that this test failure has nothing to do with package versioning/branding, so don't let it hold the merge.

**Comment by MattGal** [comment]
> Looks like 3.1's build script doesn't work on macOS 12, so I need to dust off the legacy mac and let it update a bunch to see what's going on.
> 
> But, I agree that this test failure has nothing to do with package versioning/branding, so don't let it hold the merge.

I looked at it enough to convince myself nothing changed about the machines from an infra standpoint;  I'd just like to add whatever went wrong happened between 9/14 and 9/23/2021, if you know where to look where any external certificate policy changes could have happened.

**Comment by bartonjs** [comment]
K, got the compat-mac online.  With the current patches installed it fails the same tests.  Added some printing, and it's because "Symantec Class 3 EV SSL CA - G3" is marked as `ExplicitDistrust`.

So, yeah.  We should probably backport Kevin's "change the certs used for this test" change just to eliminate the noise.

In related news: I remembered how to build and run tests for 3.1 :smile:

**Comment by bartonjs** [comment]
> I'd just like to add whatever went wrong happened between 9/14 and 9/23/2021

Seems like the mac pool must have gotten patched in that time.

**Comment by vcsjones** [comment]
> So, yeah. We should probably backport Kevin's "change the certs used for this test" change just to eliminate the noise.

I don't know how cleanly that PR will backport from 5.0 to 3.1, but happy to do it if that would help.

**Comment by vcsjones** [comment]
> Seems like the mac pool must have gotten patched in that time.

Apple can ship CA and trust store changes out-of-band / OTA. These come from valid.apple.com and certs.apple.com. It's very likely this root cert was distrusted through those mechanisms.

**Comment by ericstj** [comment]
If we agree that this failure is not caused by this PR, can we merge this?  Folks who know about this test can you devise a course of action and peel that off into a separate PR?

**Review by ericstj — APPROVED** [review]

**Pull request merged**
