### PR TITLE
Fixing text clipped on main page (readme.md).

### PR DESCRIPTION
**Pull request by CIPop**
Changes: align columns to the left and surround text in the left column with <sub></sub>. Tested on Chrome and Edge. Seems to work at any zoom level.

### CODE REVIEW

**Comment by stephentoub** [comment]
I like the look of the smaller text (that it helps address the clipping is a bonus :smile:). LGTM.

**Comment by terrajobst** [comment]
LGTM

**Comment by terrajobst** [comment]
@stephentoub any idea why the CI is marked as failed but Jenkins doesn't report any issues?

**Comment by stephentoub** [comment]
According to the log, it hung:

d:\j\workspace\dotnet_corefx_windows_release_prtest>"C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\vcvarsall.bat" x86   && build.cmd /p:OSGroup=Windows_NT /p:Configuration=Release /p:SerializeProjects=true 
  Restoring build tools...
  Restoring all packages...
Build timed out (after 120 minutes). Marking the build as aborted

**Comment by stephentoub** [comment]
This file doesn't affect the build, though.

**Pull request merged**
