### PR TITLE
Making sure that build-tests.cmd will first restore the version files to avoid race conditions

### PR DESCRIPTION
**Pull request by joperezr**
Fixing build-test race conditions

cc: @chcosta

### CODE REVIEW

**Comment by chcosta** [comment]
tests.builds doesn't import or utilize the traversal targets.

**Comment by joperezr** [comment]
it does: https://github.com/dotnet/corefx/blob/master/src/tests.builds#L15

**Comment by chcosta** [comment]
Sorry, I only glanced quickly at the failure your target doesn't exist in the project.

**Comment by jhendrixMSFT** [comment]
@dotnet-bot test this please

**Comment by chcosta** [comment]
Target is still missing.

D:\j\workspace\centos7.1_deb---75db844b\dir.traversal.targets(235,24): error MSB4057: The target "CreateOrUpdateCurrentVersionFile" does not exist in the project. [D:\j\workspace\centos7.1_deb---75db844b\src\tests.builds]

**Comment by joperezr** [comment]
> Target is still missing.

yup my bad. It should work fine with the last change I pushed.

**Comment by chcosta** [comment]
Does it make sense to import Build.Common.targets instead and treat this as a real builds file which build.proj just happens to consume?

**Comment by joperezr** [comment]
In my mind, the .proj and .builds files should basically just have the traversal targets as imports since in theory they shouldn't be using any of the build targets. For this very particular case, we need the versioning.targets since that contains the target that generates the version file. If it were to me, I think I would leave it as is where we only explicitly import the versioning targets instead of everything else in buildtools, but I'm happy to change it if you feel strongly otherwise.

**Comment by chcosta** [comment]
I don't have a strong feeling.  It seems that this file was originally intended just to capture the test build projects and be imported into build.proj.  The dev workflow changed the intent though and introduced a build-tests.cmd wrapper script.  In my mind, this file is now evolving to be used in a way very similar to build.proj, except it's just kind of slowly iterating in that direction.  I guess the answer would depend on the vision for how our dev workflow is going to look, and in the immediate interim, I'm more concerned with getting something working reliably.

**Comment by chcosta** [comment]
LGTM

**Comment by weshaggard** [comment]
>For this very particular case, we need the versioning.targets since that contains the target that generates the version file.

Why do any of the builds files need the versioning.targets?

**Pull request merged**
