### PR TITLE
Cleanup NameObjectCollectionBase tests

### PR DESCRIPTION
**Pull request by hughbe**
- Take advantage of xunit
- Shorten tests
- Remove duplicate tests

Coverage remains at 100%
/cc @ianhays

### CODE REVIEW

**Comment by ianhays** [comment]
LGTM!

**Comment by hughbe** [comment]
Test Innerloop OSX Debug Build and Test

**Comment by hughbe** [comment]
Test Innerloop OSX Debug Build and Test

**Comment by stephentoub** [comment]
Test Innerloop OSX Debug Build and Test please

**Comment by hughbe** [comment]
Test Innerloop OSX Debug Build and Test

**Pull request merged**
