### PR TITLE
Update CLI to 1.0.0-preview2-002733

### PR DESCRIPTION
**Pull request by ericstj**
This is needed to bring in `netstandard1.6` support.

### CODE REVIEW

**Comment by ericstj** [comment]
/cc @steveharter @eerhardt @weshaggard @dagood 

Haven't yet removed the "import" netstandard1.6 workaround from the tests.  We need to wait until our internal restore tool is updated to do that.

This should unblock consuming the new packages/assets.  @steveharter you may need to make the tests that you want to use this target netcoreapp1.0 instead of dnxcore50.

**Comment by eerhardt** [comment]
:shipit: 

Only thing I'd say is that it feels odd to have the CLI version and the "channel" (beta, preview, etc) split up - one in the CLIVersion.txt file and the other in the script files.  But that is an existing issue that shouldn't block taking this change.

**Comment by steveharter** [comment]
I'll prep the tests today to use netcoreapp1.0

**Comment by dagood** [comment]
@eerhardt Is there a reason on the CLI end that the channels need to be separated? It seems like the versions being unique would be enough.

LGTM pending builds. I'm working on upgrading the internal tool. (NuGet still doesn't support basic auth in my attempts.)

**Comment by eerhardt** [comment]
> Is there a reason on the CLI end that the channels need to be separated? It seems like the versions being unique would be enough.

It is mostly a matter of statement of quality. But also we have a ".Latest" version in each channel, which would collide if we didn't have channels. The "channels" are streams of consumable assets from the CLI.

The vision is to get to:

Channel | Description
------------ | -------------
Production | Official, public supported versions
Preview | Not yet officially released, but preview quality
Nightly | The absolute latest

The idea is you could take the ".Latest" version from one of those streams and get the latest version with that quality.

We aren't there yet.  But the rename from `beta` to `preview` got us one step closer.

**Comment by ericstj** [comment]
@dotnet-bot test  Innerloop CentOS7.1 Debug Build and Test

**Comment by dagood** [comment]
@eerhardt Ok, that makes sense when it comes to latest. It also makes sense to me to present a list of package versions in categories like that, but when it comes to downloading them flatter seems better. Maybe I'm just too used to NuGet. :smile:

**Comment by steveharter** [comment]
@ericstj please verify proper reference to netcoreapp1.0. The json for test projects is currently this:
"frameworks": {
    "dnxcore50": {
      "imports": [
        "netstandard1.6",
        "portable-net45+win8"
      ]
    }
  },

I assume then we want this (note no netstandard1.6)
  "frameworks": {
    "netcoreapp1.0": {
      "imports": [
        "portable-net45+win8"
      ]
    }

**Comment by ericstj** [comment]
@steveharter yeah, you'll also need to set NuGetTargetMoniker in the project and you may need to hack the TestTargetFramework https://github.com/dotnet/buildtools/blob/30602719eaccee85145bc6d8a31f557d6eefc3eb/src/Microsoft.DotNet.Build.Tasks/PackageFiles/tests.targets#L45 as well.

**Comment by steveharter** [comment]
@ericstj did add NuGetTargetMoniker to point to netcoreapp1.0. Not sure on the hack for TestTargetFramework although something is needed; one of the first errors:
Error		Package xunit.netcore.extensions 1.0.0-prerelease-00312-04 is not compatible with netcoreapp1.0 (.NETCoreApp,Version=v1.0). Package xunit.netcore.extensions 1.0.0-prerelease-00312-04 supports: dotnet (.NETPlatform,Version=v5.0)	System.Security.Cryptography.Cng.Tests	C:\git\dotnet_corefx\src\System.Security.Cryptography.Cng\tests\EXEC		

FYI my current PR at https://github.com/dotnet/corefx/pull/6789

**Comment by ericstj** [comment]
@steveharter you'll need imports for the time being.  Essentially change dnxcore50 > netcoreapp10 in the project.json and add dnxcore50 to the imports.  TestTargetFramework hack would require a target in the project that runs early and clears TestTargetFramework to replace with netcorecoreapp1.0.

**Pull request merged**
