### PR TITLE
Remove boxing of chars when concatenated with strings

### PR DESCRIPTION
**Pull request by bbowyersmyth**
Changed chars to strings when joining them to other strings to prevent the boxing of the char literal.

### CODE REVIEW

**Comment by stephentoub** [comment]
LGTM.

**Comment by pdelvo** [comment]
What exaclty is better about this? In terms of performance this is worse. it is not better to read either. i dont see the point

**Comment by stephentoub** [comment]
@pdelvo, this changed them from being chars to strings, not the other way around. This change removed boxing the chars, removed the ToString call, etc. I'm not understanding your concern.

**Comment by pdelvo** [comment]
Oh. Okay this makes sense >.<

**Comment by bbowyersmyth** [comment]
Boxing is a tricky one as its hidden from view. Should become an FxCop optional warning I recon as it's usually trivial to avoid.

**Comment by pdelvo** [comment]
I thought for whatever reason that you changed "X" to 'X'.

**Pull request merged**
