### PR TITLE
Go back to a statically linked PAL (issue #728).

### PR DESCRIPTION
**Pull request by mikem8361**
Undo all the changes from a dynamic PAL module.

### CODE REVIEW

**Comment by mikem8361** [comment]
@ellismg code review please?

**Comment by ellismg** [comment]
Looks good.  We also need to do something like this internally in the FxCore TFS branch, since we have some code that we are working on open sourcing but depends on the PAL today.  I can take care of that if you'd like.

**Comment by mikem8361** [comment]
It would be great if you could take care of that and the asp.net dnx changes. Thanks.

**Comment by mikem8361** [comment]
@dotnet-bot test this please

**Comment by mmitche** [comment]
@mikem8361 We'll need this merged so that we can get the corefx tests on Linux passing again.  They use a live coreclr.

**Comment by mikem8361** [comment]
@mmitche I don't understand why this is failing now.  I've updated all the files, built both Linux and OSx locally and it the merged build fails. When I click on "details", is says "no failures".

**Comment by stephentoub** [comment]
Thanks, Mike.

**Pull request merged**
