### PR TITLE
Add support for testing of rc2 branch in CI

### PR DESCRIPTION
**Pull request by wtgodbe**

### CODE REVIEW

**Comment by wtgodbe** [comment]
@dotnet-bot test CI please

**Comment by wtgodbe** [comment]
@dotnet-bot test CI please

**Comment by wtgodbe** [comment]
@dotnet-bot test CI please

**Comment by wtgodbe** [comment]
@mmitche can you take a look? This file is organized a bit different than the coreclr one so I'm not 100% sure this is going to do what I expect it to

**Comment by mmitche** [comment]
@wtgodbe Looks pretty good to me.  I would use Local-Job-Gen (https://github.com/dotnet/dotnet-ci/blob/master/tools/Local-Job-Gen.ps1) locally to diff against the current state of master and ensure that there aren't unexpected changes in the old jobs.  Otherwise, it looks good to me.

**Comment by wtgodbe** [comment]
@mmitche I tried that, but couldn't get it to generate anything for this branch OR for master branch. I tried it with coreclr and was able to generate all the jobs, so I'm not sure what's going on there. Does that script generate the same output as generator_prtest?

**Comment by wtgodbe** [comment]
@dotnet-bot test this please

**Comment by mmitche** [comment]
@wtgodbe It appears it's because of the helix step.  I'm not quite sure how that support gets integrated into the main plugin.

Btw, tets this please has no effect on this job.  No need to run anything except the tets ci please

**Comment by wtgodbe** [comment]
OK, just confirmed that this generates all jobs it used to, plus 57 rc2 jobs.

**Pull request merged**
