### PR TITLE
Remove ExternalPackages

### PR DESCRIPTION
**Pull request by ianhays**
<strike>I updated the ExternalPackages props to be correct for clrcompression and updated them for the new SNI package.</strike>
ExternalPackages used to be used to build and test against the packages, but it is now dead code.

resolves https://github.com/dotnet/corefx/issues/10547

forked from https://github.com/dotnet/corefx/pull/10596

### CODE REVIEW

**Comment by ianhays** [comment]
@dotnet-bot test this please

**Comment by ianhays** [comment]
@stephentoub @chcosta

**Comment by stephentoub** [comment]
I don't have a lot of context here, but LGTM.

**Comment by weshaggard** [comment]
I believe @chcosta was using them for building our tests against packages. However given that things weren't failing I'm suspicious that this isn't used in which case we should just delete it. @chcosta can you confirm whether or not these are needed?

**Comment by chcosta** [comment]
ExternalPackage is no longer being used for building tests against packages and can be deleted from CoreFx.  I have an issue tracking code cleanup in BuildTools here - https://github.com/dotnet/buildtools/issues/1023

**Comment by ianhays** [comment]
Thanks @chcosta, I updated this PR to instead remove ExternalPackages from CoreFX

**Comment by weshaggard** [comment]
LGTM thanks for cleaning this up.

**Pull request merged**
