### PR TITLE
Disable S.IO.Pipes tests blocked by #1840

### PR DESCRIPTION
**Pull request by nguerrera**

### CODE REVIEW

**Comment by nguerrera** [comment]
@pallavit

**Comment by pallavit** [comment]
@nguerrera LGTM. Thanks :). I will wait for the CI to complete before merging :).

**Comment by nguerrera** [comment]
@dotnet-bot test this please

**Comment by nguerrera** [comment]
Looks like there is an intermittent issue with nuget restore. Similar failure occurred in #2112

**Comment by stephentoub** [comment]
LGTM

**Comment by nguerrera** [comment]
@dotnet-bot test this please.

**Comment by nguerrera** [comment]
@mmitche The second failure looked like the build was aborted but I couldn't tell why.

**Comment by nguerrera** [comment]
@dotnet-bot test this please

**Comment by stephentoub** [comment]
@dotnet-bot test this please

**Comment by mmitche** [comment]
@nguerrera That is almost certainly a dnx hang.  The system will abort and kill all processes that were started under the root shell process

**Comment by stephentoub** [comment]
@dotnet-bot test this please

**Comment by nguerrera** [comment]
@davidfowl @loudej Is there anything tracking the dnx parallelism issues we're hitting? It's getting insanely hard to get a PR through. :(

@mmitche @ericstj Do we have a workaround? Rollback to different DNX build? Temporarily disable build parallelism? Add retry to restore step?

**Comment by ericstj** [comment]
We need to just give up on running DNX during the build. They aren't fixing the stress bugs and it's just causing us pain.  We can move restore to a single step at the beginning of the build, letting DNX do the recursion/parrallelism and it solves these issues.
/cc @jkuhne

**Comment by mmitche** [comment]
@ericstj Yeah agreed.  Pass the restores all at once to a single dnx?

Looking https://github.com/aspnet/dnx/blob/f3e22af80c7bddea28c8f24b00f175ae67b9e835/src/Microsoft.Framework.Runtime/Internal/ConcurrencyUtilities.cs, I'm wondering whether the Release call is incorrect, and should be called always in the finally.

**Comment by davidfowl** [comment]
We're going to fix the bugs! We're just trying to get out a release :smile:

**Comment by mmitche** [comment]
I'm going to temporarily change the PR for now to serialize.  Hopefully this will fix the issues at the cost of longer PR time.

**Comment by mmitche** [comment]
okay done @dotnet-bot test this please

**Comment by nguerrera** [comment]
@dotnet-bot test this please

**Comment by nguerrera** [comment]
I don't think the build got kicked off again. The last error was still dnx restore issue, but the time I saw logged was before the prior "test this please". :(

**Comment by mmitche** [comment]
It did I believe, the issue was that the previous job finished and reported failed, and github didn't realize another one was running: http://dotnet-ci.cloudapp.net/job/dotnet_corefx_prtest/2011/

Should complete in a bit.  So far no issues after serializing.

**Comment by JeremyKuhne** [comment]
@ericstj Is just hitting the package restore step that I implemented up front good enough (and then skipping during the "normal" build?

**Comment by ericstj** [comment]
No, because that will still use MSBuild to concurrently run restore on many projects.  Instead I was thinking to just call dnu restore --parallel on the src directory.  It's supposed to recursively find all project.json's and restore them.  Doing it this way gives DNU visibility into the concurrency.

**Pull request merged**
