### PR TITLE
Fix version of nupkgs under pkg

### PR DESCRIPTION
**Pull request by ericstj**
When changing the Version property from Version to PackageVersion I
missed updating a few projects.

@mellinoe @weshaggard

### CODE REVIEW

**Comment by ericstj** [comment]
@dotnet-bot test Innerloop CentOS7.1 Release Build and Test

**Comment by mellinoe** [comment]
LGTM

**Comment by ericstj** [comment]
@dotnet-bot test Innerloop CentOS7.1 Release Build and Test

**Comment by ericstj** [comment]
@dotnet-bot test  Innerloop OSX Debug Build and Test

**Comment by weshaggard** [comment]
LGTM

**Pull request merged**
