### PR TITLE
Async improvements to System.IO

### PR DESCRIPTION
**Pull request by jamesqo**
This PR introduces the following changes:

- The null-object Stream, StreamReader, TextReader, and TextWriters now have better performance.
  - `Stream.Null` overrides `CopyToAsync`, and now returns cached tasks for async flush/read/write.
  - `StreamReader.Null` overrides `ReadBlock` and `ReadToEnd`, and returns cached tasks in async methods.
    - Ditto for `TextReader.Null`.
  - `TextWriter.Null` now overrides a bunch of `Write` and `WriteLine` (both sync and async) methods to either noop or return a cached task.
- A `TaskCache` class has been introduced in `Common` that holds completed tasks for the following values:
  - `Task<int>` with result 0
  - `Task<string>` with a null result
  - `Task<string>` for the empty string
- `MemoryStream` now returns cached tasks instead of using `async` where it isn't needed.
- `BufferedStream` and `StringReader` now make use of `TaskCache.Zero` in `Read`-related methods where they were previously using `Task.FromResult`.

cc @hughbe  @JonHanna @justinvp @stephentoub

### CODE REVIEW

**Comment by stephentoub** [comment]
@jamesko, while I appreciate your efforts, I'm going to close this. This Stream is only used with corert (on coreclr the one from mscorlib is used), and as a result we currently have no tests running in CI, and you couldn't have tested it locally. I'm not comfortable talking such changes under those conditions. Thank you, anyway.

**Comment by hughbe** [comment]
@stephentoub this isn't related to this PR but are there plans to move more mscorlib files from coreclr to corefx - obviously this is not a high priority issue, but is this in the post-release roadmap

**Comment by jamesqo** [comment]
@stephentoub Thank you, that's okay. Is there a roadmap/date of some sort you guys have for getting tests running for this, then? Would like to know when I could resubmit this PR :smile:

**Comment by stephentoub** [comment]
> are there plans to move more mscorlib files from coreclr to corefx

I expect we've already moved most of what we can; there may be some more we can in the future, but I expect it'll be done opportunistically as the possibility arises.  Some things simply can't be "moved" due to issues around type identity, layering, etc.

> Is there a roadmap/date of some sort you guys have for getting tests running for this in CI, then?

I don't know.  @weshaggard might.  Further, for things like Stream, StreamReader, etc., I expect we'd just want to port improvements from the ones in mscorlib rather than doing further one-off changes to it that cause the implementations to diverge further and more than they have to.

**Comment by hughbe** [comment]
> I expect we've moved what we can
 
I'm not sure that's strictly true - there's lots of stuff like Guid/Version/BitArray that sill uses mscorlib but can be in corefx, but maybe I'm misunderstanding something

**Comment by jamesqo** [comment]
> I expect we'd just want to port improvements from the ones in mscorlib

OK. I'll submit a PR to CoreCLR containing these changes then (and maybe add a couple of tests here), if that's alright with you.

**Comment by jamesqo** [comment]
@hughbe I suspect it's because mscorlib is an implementation assembly-- all the types exposed from mscorlib also have to be implemented in mscorlib, e.g. `List<T>`. We can't type forward like we can with the newer .NET Core assemblies, only the other way around (the façades forward to mscorlib). Therefore, all of the sources have to be included in mscorlib.

I'm actually kind of curious myself, however, why this doesn't apply to other assemblies like `System` or `System.Core`. For example, as far as I can see `System.Linq.Expressions` simply [forwards](https://github.com/dotnet/corefx/blob/master/src/System.Linq.Expressions/src/System.Linq.Expressions.csproj#L226) to `System.Core` for the actual implementation for `net462`, yet the sources here are somehow still getting included in test coverage.

**Comment by stephentoub** [comment]
> I'm not sure that's strictly true - there's lots of stuff like Guid/

Type identity is important.  If a type is used in mscorlib and exposed through public surface area, then if that type is also implemented in another assembly, the type identities between those implementations won't match, causing things to blow up.

And I didn't say we've moved all that we can, I say we've moved most that we can.

**Comment by hughbe** [comment]
Understood, thanks for the info @stephentoub

**Pull request closed without merging**
