### PR TITLE
Skip websocket testing on Windows 7.

### LINKED ISSUE #15380: Win7 outer loop test 'System.Net.Tests.WebSocketTests.AcceptWebSocketAsync_NullSubProtocol_Succeeds' failed with 'System.PlatformNotSupportedException'
Detail: https://ci.dot.net/job/dotnet_corefx/job/master/job/outerloop_win7_debug/lastFailedBuild/consoleText

Message:
~~~
System.Net.Tests.WebSocketTests.AcceptWebSocketAsync_NullSubProtocol_Succeeds [FAIL]
        System.PlatformNotSupportedException : The WebSocket protocol is not supported on this platform.
~~~

Stack Trace:
~~~
D:\j\workspace\outerloop_win---b280fd23\src\Common\src\System\Net\WebSockets\WebSocketValidate.cs(121,0): at System.Net.WebSockets.WebSocketValidate.ThrowPlatformNotSupportedException()
           D:\j\workspace\outerloop_win---b280fd23\src\System.Net.WebSockets.Client\src\System\Net\WebSockets\WebSocketHandle.Win32.cs(41,0): at System.Net.WebSockets.WebSocketHandle.CheckPlatformSupport()
           D:\j\workspace\outerloop_win---b280fd23\src\System.Net.WebSockets.Client\src\System\Net\WebSockets\ClientWebSocket.cs(31,0): at System.Net.WebSockets.ClientWebSocket..ctor()
           D:\j\workspace\outerloop_win---b280fd23\src\System.Net.HttpListener\tests\WebSocketTests.cs(35,0): at System.Net.Tests.WebSocketTests.<AcceptWebSocketAsync_NullSubProtocol_Succeeds>d__5.MoveNext()
           --- End of stack trace from previous location where exception was thrown ---
              at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
              at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
           --- End of stack trace from previous location where exception was thrown ---
              at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
              at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
           --- End of stack trace from previous location where exception was thrown ---
              at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
              at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
~~~

Configuration:
OuterLoop_Windows7_debug (build#73)

### PR DESCRIPTION
**Pull request by Priya91**
fixes #15380 

cc @CIPop

### CODE REVIEW

**Comment by Priya91** [comment]
@dotnet-bot test Outerloop Windows 7 Debug
@dotnet-bot test Outerloop Windows 7 Release

**Comment by stephentoub** [comment]
Could we use the managed implementation instead?

**Comment by Priya91** [comment]
> Could we use the managed implementation instead?

yes, that's tracked in #13663. Also the ClientWebSocket in System.Net.WebSockets should also switch to managed implementation for it to work downlevel on Windows 7.

**Comment by Priya91** [comment]
Windows 7 has other test failures, and not related to this PR.

**Comment by Priya91** [comment]
@dotnet-bot test Innerloop Ubuntu14.04 Release Build and Test

**Pull request merged**
