### PR TITLE
Add a test to validate sensitivity on OSX

### PR DESCRIPTION
**Pull request by JeremyKuhne**
See #26797

cc: @danmosemsft, @pjanotti

### CODE REVIEW

**Comment by JeremyKuhne** [comment]
Trying to see if we can flush out unexpected results here

**Comment by wfurt** [comment]
Just a note that OSX can have both case sensitive and case insensitive file systems. 
That is also true for things like NFS shares mapped via network. 
To do this correctly we would need to determine of what file system this resides on and set it accordingly.  
This is somewhat similar to Linux & FAT file system.

**Comment by JeremyKuhne** [comment]
@dotnet-bot test OSX x64 Debug Build

System.Reflection.Metadata.Tests core dumped

**Comment by JeremyKuhne** [comment]
> Just a note that OSX can have both case sensitive and case insensitive file systems.

@wfurt Yeah. Currently we're deciding to be sensitive/not sensitive based on what behavior we detect in the temp directory. I'm not terribly comfortable with the check but I'm unsure of how we could do better. I did overhaul enumeration so there is now an explicit option to pick sensitivity when enumerating.  It might be worth looking into offering an option to detect the file system characteristics for the target directory of an enumeration, but that still leaves strangeness with mount points, reparse points, symlinks, etc.

Do you have any thoughts on the matter?

**Comment by wfurt** [comment]
I was thinking about it but I'm not sure if there is practical impact @JeremyKuhne 
Let say there are two similar files in directory (like aaa.txt and AAA.txt)
We would loose one in enumeration? 
Similarly, we think FS is case sensitive and it is not and we try to create AAA.txt with aaa.txt present. 
We may bypass c# checks but OS open()/create() will probably fail. 

I think the use case with NFS/samba files is most interesting as remote FS will enforce remote rules. 
(like ability to have ':')

**Comment by wfurt** [comment]
one more thought are international file names. How do we decide that? Do we use LANG for that? 
If so, we still may have troubles with file shares...

**Comment by JeremyKuhne** [comment]
@wfurt I've removed most of the path validity checks .NET does in 2.1 specifically because it was blocking the sort of scenarios you discuss.

Now that we have extensible enumeration I'm hoping that we'll see common useful patterns emerge for matching and we can pull them into the framework when they get critical mass.

**Pull request merged**
