### PR TITLE
[release/2.1] Port to release/2.1: Fix __Arch for armv7l tests

### PR DESCRIPTION
**Pull request by gbalykov**
cc @alpencolt @Dmitri-Botcharnikov

### CODE REVIEW

**Comment by gbalykov** [comment]
cc @stephentoub

**Comment by stephentoub** [comment]
cc: @danmosemsft

**Comment by karelz** [comment]
@danmosemsft are we taking it for 2.1.3?

**Comment by danmosemsft** [comment]
@gbalykov can you give context? What is the consequence if we don't take this?

Although, I see it is a test only change.

**Comment by gbalykov** [comment]
@danmosemsft before this change no tests are found: `Total 0 (232 Dlls)` (for each dll the similar output is given: `Nothing to test in Canonicalization.Tests`). After this change tests are found correctly.

**Comment by karelz** [comment]
@danmosemsft is it sufficient info above?

**Comment by danmosemsft** [comment]
OK. I did not see this as I only look at the 2.1.x issues. Merging for tell mode.

**Pull request merged**
