### PR TITLE
Fix minor bug in `clean.sh`

### PR DESCRIPTION
**Pull request by lemmaa**
* add '-?' and '-h' option processing for usage.
* fix 'line 19: [: ==: unary operator expected' when running without option.
* fix typo '-all' to '--all'.

### CODE REVIEW

**Comment by lemmaa** [comment]
@dotnet-bot test Innerloop CentOS7.1 Release Build and Test

**Comment by lemmaa** [comment]
@maririos Please take a look this PR.

**Comment by maririos** [comment]
Thanks for fixing it.
Looking at the `--all` option,  the documentation is the one that is not correct. Because we want to keep parity with clean.cmd we should change the documentation to be `-all`.
Besides of that. LGTM

**Comment by lemmaa** [comment]
Using double hyphen is more natural in linux environment. Anyway, I have update the PR following your guide. :)

**Comment by stephentoub** [comment]
LGTM

**Pull request merged**
