### PR TITLE
Add "frameworks" node to project.json files that missed them

### PR DESCRIPTION
**Pull request by akoeplinger**
This caused an issue when building on Linux as the projects would build against DNX,4.5.1 instead of DNXCore,5.0

### CODE REVIEW

**Comment by stephentoub** [comment]
LGTM. @ericstj?

**Comment by ericstj** [comment]
LGTM, not sure how I missed these.  Maybe came in after initial change?  Thanks for fixing them!

**Comment by akoeplinger** [comment]
@ericstj :) I actually just saw that System.Security.Principal is also still using packages.config, so I guess that one was simply missed:

- https://github.com/dotnet/corefx/blob/e8f04cede01a78889e842e29b50a0deea84b261c/src/System.Security.Principal/tests/packages.config
- https://github.com/dotnet/corefx/blob/e8f04cede01a78889e842e29b50a0deea84b261c/src/System.Security.Principal.Windows/tests/packages.config

**Comment by ericstj** [comment]
I see, commit is dated before my change to move everyone to project.json but was merged after my PR.  We need to watch for things like this coming in.  I have a tool that I wrote to convert.  I will run it again on the repo and fix everything up.  That might be better then this.

**Comment by akoeplinger** [comment]
Closing in favor of #1717.

**Pull request closed without merging**
