### PR TITLE
Restore disabled MMF inter-process test

### LINKED ISSUE #2498: MemoryMappedFilesTests.DataShared failed in CI
http://dotnet-ci.cloudapp.net/job/dotnet_corefx_linux_debug_tst_prtest/1332/console
```
InterProcessCommunication.Tests.MemoryMappedFilesTests.DataShared [FAIL]
12:44:49       System.IO.IOException : The process cannot access the file '/tmp/MemoryMappedFilesTests_8729349d9699eb9cc0a6adf22b1b7afa/DataShared_16' because it is being used by another process.
12:44:50       Stack Trace:
12:44:50 Starting:    System.Collections.Immutable.Tests
12:44:50             at System.IO.UnixFileStream.SysCall[TArg1,TArg2](Func`4 sysCall, TArg1 arg1, TArg2 arg2, Boolean throwOnError)
12:44:50             at System.IO.UnixFileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, FileStream parent)
12:44:50             at System.IO.UnixFileSystem.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, FileStream parent)
12:44:50             at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
12:44:50             at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
12:44:50             at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, Boolean useAsync)
12:44:50             at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
12:44:50             at InterProcessCommunication.Tests.MemoryMappedFilesTests.DataShared()
12:44:50 Finished:    InterProcessCommunication.Tests
```

### PR DESCRIPTION
**Pull request by stephentoub**
Also removing some stale files that got left behind in a previous refactoring.

This test was previously causing fairly consistent "file in use" failures in the lab.  I've been unable to reproduce it locally or in private runs submitted through the CI system.  I'm reenabling it in hopes that whatever issues were previously there are gone, but I'll disable it again at the first sign of problems.

Fixes #2498

### CODE REVIEW

**Comment by stephentoub** [comment]
cc: @nguerrera

**Comment by nguerrera** [comment]
What's the deal with the deleted project.json and project.lock.json? Those were stale/unused?

LGTM otherwise.

**Comment by stephentoub** [comment]
> What's the deal with the deleted project.json and project.lock.json? Those were stale/unused?

Yes: "Also removing some stale files that got left behind in a previous refactoring." :smile:

**Comment by nguerrera** [comment]
;) Not sure how I missed that.

**Pull request merged**
