### PR TITLE
[release/2.1] Always build the OpenSSL shim in portable mode on macOS.

### PR DESCRIPTION
**Pull request by bartonjs**

### CODE REVIEW

**Comment by bartonjs** [comment]
#### Description

On macOS OpenSSL is only used for 5 interop types: DSAOpenSsl, ECDiffieHellmanOpenSsl, ECDsaOpenSsl, RSAOpenSsl, SafeEvpPKeyHandle.

Currently, our macOS builds use a single ABI version of OpenSSL which is determined at compile time. Further, the version is the now out-of-support OpenSSL 1.0.2.

This change will make macOS use the same late binding that the portable Linux release does, and dynamically support the better of OpenSSL 1.0.2 or OpenSSL 1.1.

#### Customer Impact

Customers who use the interop types will be broken if they are P/Invoking against a different version of OpenSSL than we end up binding to and using those pointers with our \*OpenSsl classes.  If they are following the guidance for interop with these types they will be aware of the state by reading the SafeEvpPKeyHandle.OpenSslVersion property.  These customers can force the downgrade by use of the CLR_OPENSSL_VERSION_OVERRIDE environment variable.

#### Regression?

No, reacting to dependency lifetimes.

#### Packaging reviewed?

Only impacts the shared runtime.

#### Risk

Low. This code has been used for multiple releases with Linux, and has been tested with all 4 combinations of OpenSSL 1.0.2 and OpenSSL 1.1 being present on the system.

**Comment by danmoseley** [comment]
approved offline for 2.1.16 to merge once we have CR signoff from someone

**Comment by bartonjs** [comment]
@danmosemsft On this one and the 3.0 version you marked api-approved, not servicing-approved.  Was that a placeholder for "once someone signs off on code review", or just a misclick? :)

**Comment by danmoseley** [comment]
misclick

**Review by GrabYourPitchforks — APPROVED** [review]

**Pull request merged**
