### PR TITLE
Fix S.S.Cryptography.Native compilation when OPENSSL_NO_SSL3* defined

### LINKED ISSUE #6741: 'SSLv3_method' vs 'SSLv23_method'
```
/src/Native/System.Security.Cryptography.Native/pal_ssl.cpp:33:32: error: use of undeclared identifier 'SSLv3_method'; did you
      mean 'SSLv23_method'?
    const SSL_METHOD* method = SSLv3_method();
                               ^~~~~~~~~~~~
                               SSLv23_method                                                                                                              
/usr/include/openssl/ssl.h:2360:19: note: 'SSLv23_method' declared here
const SSL_METHOD *SSLv23_method(void); /* Negotiate highest available SSL/TLS
```
```
$ openssl version
OpenSSL 1.0.2g  1 Mar 2016
```
```
#ifndef OPENSSL_NO_SSL3_METHOD
 const SSL_METHOD *SSLv3_method(void);
 const SSL_METHOD *SSLv3_server_method(void);
 const SSL_METHOD *SSLv3_client_method(void);
 #endif
```
https://www.openssl.org/docs/manmaster/ssl/SSL_CTX_new.html
SSLv23_* - Use of these functions is deprecated.
Ideally should be shifting to TLS now? (edit: nvm, I see it's an option to use in the enum SSLProtocols)
https://issues.asterisk.org/jira/browse/ASTERISK-24799

### PR DESCRIPTION
**Pull request by stephentoub**
Fixes #6741 
cc: @bartonjs, @kapilash

### CODE REVIEW

**Comment by stephentoub** [comment]
Test Innerloop Windows_NT Release Build and Test please (https://github.com/dotnet/corefx/issues/5306)

**Comment by bartonjs** [comment]
I'm a little confused as to why we're in a state where SSL3 isn't defined, but SSL2 is.  I'd expect guards for that to need to pop up soon... or us to just cut 2 and 3 from this layer altogether.

LGTM, modulo confusion (holding off on merge in case you felt like proactively guarding SSL2)

**Comment by stephentoub** [comment]
no_ssl2 is a deprecated option when building openssl (even when I set it, it wouldn't define the relevant headers).

**Comment by bartonjs** [comment]
Alrighty, thanks for checking.

**Pull request merged**
