### PR TITLE
Fix call to create submission metadata

### PR DESCRIPTION
**Pull request by DrewScoggins**
We made a change to the Benchview tooling and did not update the use of
it in the CoreFX repo.  This fixes that.

### CODE REVIEW

**Comment by DrewScoggins** [comment]
@dotnet/rap-team PTAL

**Comment by DrewScoggins** [comment]
test ci please

**Comment by jorive** [comment]
@DrewScoggins Could you please port these changes to the `release/1.1.0` and `release/2.0.0` branches?

**Comment by DrewScoggins** [comment]
Can do

**Pull request merged**
