### PR TITLE
Typo in linuxmint RID

### PR DESCRIPTION
**Pull request by BrennanConroy**
@ellismg

### CODE REVIEW

**Comment by ellismg** [comment]
@ericstj Can you take a look?

**Comment by ericstj** [comment]
Lgtm, sorry for that this one was rushed in

**Comment by ellismg** [comment]
Do we need this in RC1 as well?

**Comment by ericstj** [comment]
Yes.

**Comment by stephentoub** [comment]
@dotnet-bot test this please

**Comment by ericstj** [comment]
This is effectively just a content file in github, consumpution is only in the TFS build, so I'd merge it despite failing tests.

**Comment by weshaggard** [comment]
@ericstj what is the plan for this? Why is it in this directory on GitHub?

**Comment by ericstj** [comment]
Folks need to collaborate on the content of this file.  Rather than wait for all the packaging infrastructure to be moved to the open I moved just this file to the open to enable that collaboration.

**Comment by weshaggard** [comment]
@ericstj sounds good.

**Pull request merged**
