### PR TITLE
Cleanup some System.Reflection.Emit tests

### PR DESCRIPTION
**Pull request by hughbe**
- Take advantage of xunit
- Consolidate some really short tests into their own file
- Deobfuscate these tests and rename them

### CODE REVIEW

**Comment by stephentoub** [comment]
@hughbe, FYI there's a build failure:
```
error CS0103: The name 'Helpers' does not exist in the current context [D:\j\workspace\windows_nt_de---4526f5ff\src\System.Reflection.Emit\tests\System.Reflection.Emit.Tests.csproj]
```

**Comment by hughbe** [comment]
Crums I screwed up a rebase. Will fix

**Comment by stephentoub** [comment]
@dotnet-bot test this please

**Comment by hughbe** [comment]
Test Innerloop CentOS7.1 Release Build and Test

**Comment by AtsushiKan** [comment]
LGTM

**Pull request merged**
