### PR TITLE
Eliminate OpenSuSE 13.2 (EOL)

### PR DESCRIPTION
**Pull request by mmitche**

### CODE REVIEW

**Comment by mmitche** [comment]
@dotnet-bot test ci please

**Comment by mmitche** [comment]
@karelz Am I good to merge this?

**Comment by karelz** [comment]
@mmitche sounds reasonable to me - @weshaggard ?

**Comment by mmitche** [comment]
@karelz Anything I need to do for the 1.0/1.1 and 2.0 equivalents to be checked in?

**Comment by karelz** [comment]
@mmitche run it by Servicing Shiproom. Code review from @weshaggard would be useful prior to that.

**Comment by mmitche** [comment]
These are long gone from official

**Pull request merged**
