### PR TITLE
Avoid O(N^2) in HashSetEquals and SortedSetEquals

### PR DESCRIPTION
**Pull request by Gregory-Bell**
Avoid O(N^2) in HashSetEquals and SortedSetEquals when the two sets have different comparers, but one of them has the fallback comparer. We treat the set without the fallback comparer as just another IEnumerable, and determine equality in O(N)

### CODE REVIEW

**Comment by ianhays** [comment]
Thanks for the contribution, @Gregory-Bell. I'm curious how you came to this change - was it motivated by real-world data showing slowdown in this particular case?

cc: @safern @stephentoub

**Comment by Gregory-Bell** [comment]
@ianhays It was not. It was actually motivated by [this blog post](https://blogs.msdn.microsoft.com/dotnet/2017/06/07/performance-improvements-in-net-core/). A lot of the improvements looked like low-hanging fruit, so out of curiosity I went to see if there were more improvements to be made in the collections classes. 

If you want to see some benchmarks before accepting a perf change I will bring back data for that. Or, if the risk for a change like this is too high to be worth doing without a demonstrated real-world need, I can withdraw the pull request.

**Comment by safern** [comment]
It would be nice if you could show some benchmark data to see the improvement in different scenarios so that we can take this change.

**Comment by stephentoub** [comment]
@Gregory-Bell, thanks for contributing this.  Are you able to share some data about the improvements?

**Comment by karelz** [comment]
@Gregory-Bell do you have any ETA for the data? We would like to move the PR forward. Thanks!

**Comment by Gregory-Bell** [comment]
Sorry, I've been on vacation the past couple weeks. I'll do some benchmarking tonight!

**Comment by karelz** [comment]
@Gregory-Bell thanks! No rush. We just want to make sure that PRs are not abandoned. If someone is actively working on them, we can keep them open.
We also understand people have to adapt to their work/life schedule and don't have time every day to contribute to OSS as a hobby. Having some rough timeline expectations (even if larger) is sufficient.

**Comment by karelz** [comment]
@Gregory-Bell any update? If you still don't have time, I would prefer to close the PR and reopen it again when you have time to come back to it ... would that work for you? Thanks!

**Comment by danmosemsft** [comment]
I'll close this for now. Welcome to reopen this if you need to.

**Pull request closed without merging**
