### PR TITLE
Remove component table from README.md

### PR DESCRIPTION
**Pull request by stephentoub**
When the corefx repo was first created, we had four components in it, and it made sense to list them out on the README.md.  Since then, the table has expanded, to include more components, to include badges for version numbers, to include descriptions of each component, etc.

However, the table is stale with regards to all of the components in corefx, missing a few dozen entries (and containing some that are no longer valid).  It contains text duplicated from the NuGet package descriptions, which need to be kept in sync.  And it contains badges for the version numbers pulled from MyGet, and these badges can take quite some time to load.

I propose we get rid of the table, and replace it with basic information and links where the same data can be retrieved, e.g. on the structure of the src folder (which essentially provides an always-up-to-date list of all components in the repo), and with a link to the daily builds gallery on MyGet.

Thoughts?  If folks agree, we can merge this.  If folks disagree, someone should overhaul the table to bring it back into sync with reality.

cc: @joshfree, @richlander, @terrajobst, @ellismg, @davidsh

### CODE REVIEW

**Comment by bartonjs** [comment]
I agree.  It's just a bit too big.

**Comment by ellismg** [comment]
+1 on removing this.

**Comment by davidsh** [comment]
LGTM

**Comment by stephentoub** [comment]
Thanks, guys.

**Comment by weshaggard** [comment]
+1 thanks @stephentoub

**Pull request merged**
