### PR TITLE
Fix for LeftShift and RightShift code generation in LambdaCompiler

### PR DESCRIPTION
**Pull request by bartdesmet**
This fixes issue #3149 in the LambdaCompiler by inserting the masking behavior similar to what the C# and VB compilers do.

### CODE REVIEW

**Comment by VSadov** [comment]
LGTM

**Comment by VSadov** [comment]
I assume interpreter naturally does the right thing so does not need a similar fix.

**Comment by bartdesmet** [comment]
Correct; it relies on statically compiled C# code that emits the same masks.

**Comment by bartdesmet** [comment]
I've removed the stale comments in the interpreter that were the result of some copy/paste when the instructions were implemented.

**Pull request merged**
