### PR TITLE
Normalize line endings in .rc files

### PR DESCRIPTION
**Pull request by ellismg**
Somehow the newly added resource files were committed with DOS line
endings. This fixes that (when checked out on Windows they will still
have DOS line endings in the work tree due to autocrlf).

### CODE REVIEW

**Comment by ellismg** [comment]
@danmosemsft my guess is that this will fix the issue we're seeing in cross building.

**Comment by ellismg** [comment]
I validated that on my *nix box, with this change the files in the work tree don't have DOS line endings (they did previously).  I also looked on my windows machine and with this change git status shows no changes instead of line ending differences.

I don't have a good explanation as to how we got into this state, in our .gitattributes file we are explicit about using autocrlf for text files.  @attilah do you happen to remember when you created these .rc files how you created (I assume they were just spit out by VS 2017) and committed them? @alexperovich Did you do anything weird when you started working onto of @attilah's changes?

**Comment by ericstj** [comment]
For some reason I'm seeing these files as a diff after this change.  Nothing I can do seems to fix it (tried a number of different git reset commands, stash, etc).

**Comment by alexperovich** [comment]
I used curl to download the *.patch file from his PR and used `git am` to apply them before starting my work. That may have caused the windows line endings to get in there.

**Comment by danmosemsft** [comment]
@ericstj do you have this ?
core.autocrlf=true
core.safecrlf=true

**Comment by danmosemsft** [comment]
Actually that wouldn't explain how you can't get past it. Taht's bizarre, if you delete them and check them out, and your branch is synced past the change.

**Comment by ericstj** [comment]
If I delete them and check them out they still showed as a diff.

I had @alexperovich help and we just checked-in the diff that GIT thought it saw, then rebased on master (with this fix).  The rebase subtracted the commit and seems to have fixed the problem.

To repro you can do the following:
```
git checkout -b myBranch 0428a32171fc10693d84e586acefe23b619096a4
git status
```
This shows the bug, now the fix.
```
git add -u
git commit -m "REMOVE ME"
git rebase 0c69c81d44d4cbd7e9727908ede712e73aec65fb
```
This fixed the problem.  I used the specific hashes but rebasing on master will probably be better and also fixes the problem.

**Pull request merged**
