### PR TITLE
Linux: Fix NetworkAddressChange NullReferenceException on AddressChange when no Availability subscribers

### PR DESCRIPTION
**Pull request by tmds**
Fixes https://github.com/dotnet/corefx/issues/25081

This also fixes race conditions between availability subscriptions and timer events.

CC @stephentoub @davidsh @Const-me

### CODE REVIEW

**Comment by Priya91** [comment]
The test failures are not related to this change.

**Comment by d0nutptr** [comment]
Any idea when this will make it into a release? As far as I can tell this isn't in 2.1.4. Does that sound correct?
Thank you!

**Comment by danmosemsft** [comment]
Should be in master so it would be in 2.1 preview 1.

**Comment by d0nutptr** [comment]
@danmosemsft that's strange.. I'm on ubuntu 16.04, just installed the latest dotnet and get this error consistently. Perhaps it's unrelated.. but it's uncanny.

Thanks anyway :/

**Comment by d0nutptr** [comment]
Oh I see corefx and core CLI are on different version numbers so I thought you meant it hit the normal release already.. I'll see what I can do to run on the preview :)

**Comment by danmosemsft** [comment]
Yes it was/is confusing -- they've recently moved to a new versioning scheme that is less confusing. Let me know how Preview 1 looks.

**Comment by d0nutptr** [comment]
Hey @danmosemsft,
Everything is working perfectly now! Thanks for sending me in the right direction :)

**Comment by danmosemsft** [comment]
@d0nutptr awesome. Please, try out preview 1 and open issues for any problems you find so we can fix them.

**Comment by ravarnamsft** [comment]
Can this fix be made available sooner than later? We seem to be hitting a similar error on our Linx 16.04 Ubuntu machines (or let us know if there is a workaround):
Unhandled Exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at System.Net.NetworkInformation.NetworkChange.OnSocketEvent(NetworkChangeKind kind)
   at System.Net.NetworkInformation.NetworkChange.ProcessEvent(Int32 socket, NetworkChangeKind kind)
   at Interop.Sys.ReadEvents(Int32 socket, NetworkChangeEvent onNetworkChange)
   at System.Net.NetworkInformation.NetworkChange.LoopReadSocket(Int32 socket)
   at System.Net.NetworkInformation.NetworkChange.<>c.<CreateSocket>b__17_0(Object s)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)

**Comment by Const-me** [comment]
@ravarnamsft For workaround, you can try to subscribe for NetworkAvailabilityChanged event first (no need to do anything in the handler, an empty one will do), then subscribe for NetworkAddressChanged.

**Comment by ravarnamsft** [comment]
@Const-me  Thank you! Will try it out.

**Comment by Inumedia** [comment]
Is there any other work-around for this? I tried subscribing to the `NetworkAvailabilityChanged` event and `NetworkAddressChanged` immediately after and am still seeing exceptions surrounding this:

```
Apr 12 20:41:36 lucid henesys.chat[6765]: Unhandled Exception: System.Net.NetworkInformation.NetworkInformationException: An error was encountered while querying information from the operating system.
Apr 12 20:41:36 lucid henesys.chat[6765]:    at System.Net.NetworkInformation.LinuxNetworkInterface.GetLinuxNetworkInterfaces()
Apr 12 20:41:36 lucid henesys.chat[6765]:    at System.Net.NetworkInformation.NetworkInterfacePal.GetIsNetworkAvailable()
Apr 12 20:41:36 lucid henesys.chat[6765]:    at System.Net.NetworkInformation.NetworkChange.OnAvailabilityTimerFired(Object state)
Apr 12 20:41:36 lucid henesys.chat[6765]:    at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
Apr 12 20:41:36 lucid henesys.chat[6765]:    at System.Threading.TimerQueueTimer.CallCallback()
Apr 12 20:41:36 lucid henesys.chat[6765]:    at System.Threading.TimerQueueTimer.Fire()
Apr 12 20:41:36 lucid henesys.chat[6765]:    at System.Threading.TimerQueue.FireNextTimers()
```
Here's the code I use for subscribing to the events:
```
        public static void Main(string[] args)
        {
            NetworkChange.NetworkAvailabilityChanged += NetworkChange_NetworkAvailabilityChanged;
            NetworkChange.NetworkAddressChanged += NetworkChange_NetworkAddressChanged;
```
```
        private static void NetworkChange_NetworkAddressChanged(object sender, EventArgs e) { }
        private static void NetworkChange_NetworkAvailabilityChanged(object sender, NetworkAvailabilityEventArgs e) { }
```

For reference,
```
dotnet --info
.NET Command Line Tools (2.0.2)

Product Information:
 Version:            2.0.2
 Commit SHA-1 hash:  a04b4bf512

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  16.04
 OS Platform: Linux
 RID:         ubuntu.16.04-x64
 Base Path:   /usr/share/dotnet/sdk/2.0.2/

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.0
  Build    : e8b8861ac7faf042c87a5c2f9f2d04c98b69f28d
```

**Comment by Const-me** [comment]
@Inumedia Based in your comment, the problem you’re facing is completely different. It’s not even a NullReferenceException, you’re getting a NetworkInformationException because some OS system call has failed.

Apparently, the native function that returns the error code is SystemNative_EnumerateInterfaceAddresses from src\Native\Unix\System.Native\pal_interfaceaddresses.cpp, it returns errors when either [getifaddrs()](http://man7.org/linux/man-pages/man3/getifaddrs.3.html) or [if_indextoname()](https://linux.die.net/man/3/if_indextoname) kernel calls fail.

I have no idea what’s happening, but potentially this might be an issue with OS compatibility. Can you find your OS version [on this list](https://docs.microsoft.com/en-us/dotnet/core/linux-prerequisites?tabs=netcore2x)?

**Comment by Inumedia** [comment]
@Const-me Aha, sorry about that, yeah I guess it isn't a NullReferenceException anymore.

I'm on Ubuntu 16.04, so I'm not really sure what's going on either. I'll look around and open up a new issue if it persists.

**Comment by danports** [comment]
OK, I tried out the NetworkAvailabilityChanged workaround today and it seems to be working - I added this to my Main method before calling IWebHost.Run:
`NetworkChange.NetworkAvailabilityChanged += delegate { };`

I have been using .NET Core on Ubuntu since the 1.0-preview days, and this is the most severe bug I've run into. I'm surprised that it hasn't been more widely reported or already fixed in 2.0.x.

**Comment by danmosemsft** [comment]
Has anyone hitting this verified that it does not happen in 2.1 (preview 2 is released)? Just to be certain, while we still have a little time left to fix things in 2.1

**Comment by karelz** [comment]
Seems that 4 people hit this so far (@d0nutptr @ravarnamsft @Const-me @danports) - interestingly in last 2 months, quite some time after 2.0 shipping.
The issue will be fixed in 2.1 (if someone can double check, that would be great) + there is workaround (https://github.com/dotnet/corefx/pull/25888#issuecomment-376370318).
If there are more people hitting it, please let us know - we can consider to service 2.0 if it has broad impact.

**Comment by mukadr** [comment]
I'm having this issue too, aspnetcore with kestrel.

Workaround #25888 fixed the problem.
```
Unhandled Exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at System.Net.NetworkInformation.NetworkChange.OnSocketEvent(NetworkChangeKind kind)
   at System.Net.NetworkInformation.NetworkChange.ProcessEvent(Int32 socket, NetworkChangeKind kind)
   at Interop.Sys.ReadEvents(Int32 socket, NetworkChangeEvent onNetworkChange)
   at System.Net.NetworkInformation.NetworkChange.LoopReadSocket(Int32 socket)
   at System.Net.NetworkInformation.NetworkChange.<>c.<CreateSocket>b__17_0(Object s)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
```

```
$ dotnet --info
.NET Command Line Tools (2.1.105)

Product Information:
 Version:            2.1.105
 Commit SHA-1 hash:  141cc8d976

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  14.04
 OS Platform: Linux
 RID:         ubuntu.14.04-x64
 Base Path:   /usr/share/dotnet/sdk/2.1.105/

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.7
  Build    : 2d61d0b043915bc948ebf98836fefe9ba942be11

```

**Comment by marcwittke** [comment]
Happens on a linux build agent for me. The (integration) test builds and starts a docker container hosting a mssql-server-linux and kills the container when test is terminating, by means of xunit collectionfixture's Dispose method.

```
agent@mw-build03:~$ dotnet --info
.NET Command Line Tools (2.1.2)

Product Information:
 Version:            2.1.2
 Commit SHA-1 hash:  5695315371

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  17.10
 OS Platform: Linux
 RID:         linux-x64
 Base Path:   /usr/share/dotnet/sdk/2.1.2/

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.3
  Build    : a9190d4a75f4a982ae4b4fa8d1a24526566c69df
```

All tests are green, the failure happens on disposing of the collection fixture.

**Comment by danmosemsft** [comment]
The above reports show shared framework 2.0.x is being used by the app. If you republish the app for 2.1 you should see this solved.

**Comment by marcwittke** [comment]
I can confirm both: 

The [workaround](https://github.com/dotnet/corefx/pull/25888#issuecomment-376370318) for an app targeting 2.0 solves the issue. 
Changing 

```xml
<PropertyGroup>
  <TargetFramework>netcoreapp2.0</TargetFramework>
</PropertyGroup>
```
to
```xml
<PropertyGroup>
  <TargetFramework>netcoreapp2.1</TargetFramework>
</PropertyGroup>
```
in my Xxx.IntegrationTest.csproj (and reverting the workaround) works as well. Good work, the issue seems to be really hard to reproduce. I have a very similar test that was running fine all the time.

**Comment by danmosemsft** [comment]
Thanks @marcwittke . Hopefully the callstack leads anyone else hitting it to this post.

**Pull request merged**
