### PR TITLE
Add '--test-dir' option to run selected tests only.

### PR DESCRIPTION
**Pull request by jyoungyun**
Multiple of this switch may be specified.

#9958

### CODE REVIEW

**Comment by jyoungyun** [comment]
@ellismg Take a look please.

**Comment by ellismg** [comment]
Why not use alternation in the regex and continue to use restrict-proj?  I don't like the idea of having two different ways to do this filtering.

**Comment by jyoungyun** [comment]
@ellismg Because the existing `--restrict-proj` option compares all test lists to jugde if it runs or not. And it runs only matched tests with regex. If there is no matched rule among tests what I want to run, the `--test-dir` option is more useful than `--restrict-proj`.

**Comment by stephentoub** [comment]
@jyoungyun, @ellismg, what's the status of this PR?

**Comment by jyoungyun** [comment]
@ellismg Please see my comments plz. Whenever I tried to run CoreFX unittest, I had to check all of tc for comparing with `--restrict-proj` value even though I already knew the directory full path of TC and TC what I want to run was just one.

**Comment by stephentoub** [comment]
@ellismg, any further thoughts on this one?

**Comment by ellismg** [comment]
Sorry, I thought I LGTM'd this a while back.  I'm fine with the change (it does look like there are conflicts now for some reason).

**Comment by stephentoub** [comment]
@dotnet-bot test this please

**Comment by stephentoub** [comment]
@jyoungyun, can you rebase this?  Thanks.

**Comment by jyoungyun** [comment]
The same commit already merged. :) So I close this issue. Thank you all guys.
commit no. d194c64c92eb14ded78664d8693c2b7baf15de25

**Pull request closed without merging**
