### PR TITLE
Expose Array.Fill and add tests

### PR DESCRIPTION
**Pull request by jamesqo**
This PR exposes the new `Array.Fill` API and adds tests.

Fixes https://github.com/dotnet/corefx/issues/6695

cc: @hughbe, @justinvp

(edit: Sorry for all of the CI failures. I have trouble building this locally because of https://github.com/dotnet/corefx/issues/14423, but I'll try to fix these ASAP.)

### CODE REVIEW

**Comment by jamesqo** [comment]
@weshaggard @joperezr I'm not sure why, but the compiler is saying that it can't find the new API: https://ci.dot.net/job/dotnet_corefx/job/master/job/centos7.1_release_prtest/1551/consoleFull#787418830a82fefab-f698-416f-8fca-58544c94cd4e Any suggestions? The file I modified is conditionally compiled under netcoreapp1.1.

Another thing, I have been unable to build/test this particular assembly locally for a couple of weeks because of https://github.com/dotnet/corefx/issues/14423. Would either of you know why I'm getting that error?

- If it's relevant, I did not find `GetTargetFrameworkProperties` after a GitHub search in the .NET Core repos, but found some results that might be relevant in `Microsoft/msbuild` [here](https://github.com/Microsoft/msbuild/search?q=GetTargetFrameworkProperties&type=Issues&utf8=%E2%9C%93).

- I also tracked down the target to this file on my desktop: C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets

**Comment by karelz** [comment]
Both @weshaggard and @joperezr are OOF for the rest of the year. @AlexGhiondea can you please help?

**Comment by AlexGhiondea** [comment]
@jamesqo how is the Fill method exposed? In your commit I am only seeing the tests you added.

**Comment by jamesqo** [comment]
@AlexGhiondea Whoops, my bad; I thought I'd exposed the API earlier. I'll try modifying the ref file again.

**Comment by danmosemsft** [comment]
@dotnet-bot test this (logs gone)

**Comment by danmosemsft** [comment]
@dotnet-bot test this (logs gone)

**Comment by danmosemsft** [comment]
@mmitche another one which didn't retest (I guess reopen would work)

**Comment by mmitche** [comment]
@dotnet-bot test this please

**Comment by mmitche** [comment]
@danmosemsft Looks like the phrase is actually test this pease (spelled correctly) not just test this

**Comment by joperezr** [comment]
by looking at the log, it seems that the API is exposed correctly now but the tests are failing. @jamesqo can you repro locally?

**Comment by jamesqo** [comment]
@joperezr I was finally able to get it building. Yes, I can repro locally. I've just pushed a patch so this should build now.

**Comment by AlexGhiondea** [comment]
@jamesqo please ignore the failure of the System.Xml.Tests.Errata4.TestXslTransform test.

**Comment by joperezr** [comment]
@AlexGhiondea looks like that is the only failure in his build so this should be good to go. Is there a reason why this test only fails on Ubuntu Release?

**Comment by danmosemsft** [comment]
Don't know, Sepideh is investigating that test.

**Pull request merged**
