### PR TITLE
Upgrade dotnet CLI version

### PR DESCRIPTION
**Pull request by dagood**
The CLI version upgrade changes restore from using DNX to using xplat nuget. This was blocking https://github.com/dotnet/corefx/issues/5707. This change also means that the internal and open builds will use the same restore tool which will make it harder to get TFS-only errors when changing project.jsons.

project.json changes:
* Adding win7 runtimes to the redist packages allows xplat restore. xplat RIDs would otherwise be inferred.
* Capitalization fix for NetNative -> NETNative avoids xplat nuget race condition. (https://github.com/NuGet/Home/issues/2102)

/cc @ericstj @weshaggard

### CODE REVIEW

**Comment by ericstj** [comment]
Awesome!  LGTM once we we have a green build.

**Comment by ericstj** [comment]
You may need to pull in @weshaggard's fix: https://github.com/dotnet/corefx/pull/6336.  At the very least we should make sure to merge his before merging this one.

**Comment by dagood** [comment]
@ericstj Thanks, merged for now, will rebase on master once that goes in.

**Comment by weshaggard** [comment]
LGTM once we are green.

**Comment by ericstj** [comment]
We need to get this in today so I wouldn't wait for green after rebaseline.  Hopefully we can get results soon so that this can merge, mirror, and I can do the rename before EOD.

**Comment by ericstj** [comment]
@mmitche any idea what CI is doing here?  We need to get this change in ASAP.  I need to get a dependent change in for tonight's build.

**Comment by weshaggard** [comment]
CI is backed up and we need this in today so I'm merging this. It has been validated locally and is good. If there are is any fallout we will react to it.

**Pull request merged**
