### PR TITLE
Move to netcoreapp3.0

### PR DESCRIPTION
**Pull request by weshaggard**
PTAL @ericstj @eerhardt 

I thought about bumping the versions of Microsoft.NETCore.Platforms/Targets to 3.0 as well but I don't think it is necessary. What do you guys think? Should we keep them consistent or just let them version independently?

### CODE REVIEW

**Comment by ericstj** [comment]
I'd version them just to make it clear where they are coming from.  This is a case where not making a change makes things more complicated.

**Comment by weshaggard** [comment]
@RussKeldorph I've moved both corefx and core-setup to netcoreapp3.0 and versioned a few packages. You may want to consider moving the coreclr packages to 3.0 but it isn't absolutely necessary as they are just transport packages and don't ship independently.

**Comment by ericstj** [comment]
@weshaggard were you planning to separately update the config system?

**Comment by weshaggard** [comment]
Yes that is part of issue https://github.com/dotnet/corefx/issues/29384. Once I finish the work to update the harvested packages then I can do that work.

**Pull request merged**
