### PR TITLE
Mac Catalina build, suppress warnings 

### PR DESCRIPTION
**Pull request by buyaa-n**

### CODE REVIEW

**Comment by wfurt** [comment]
It builds for me on 10.15 without any changes. What Xcode version do you use? It may be better to adjust cmake rules than fix every occurrence.

**Comment by buyaa-n** [comment]
> What Xcode version do you use?

it was XCode 11, downloaded latest version

> It may be better to adjust cmake rules than fix every occurrence.

Yeah, as it was not that many did it for every occurance as we might want to be notified with deprecated functionalies for other areas too

**Comment by krwq** [comment]
Thanks @buyaa-n

**Comment by stephentoub** [comment]
The fact that these warnings are firing suggests that there's something better we should be using instead of these existing calls?

**Comment by bartonjs** [comment]
The MD5 ones, at least, are "MD5 is broken, you shouldn't be using it".  Except for all the places it's needed, of course.  Otherwise they've added some stuff for 10.15, and deprecated the alternatives.  But that doesn't help us on 10.13 or 10.14; so it's not useful for at least another two years (or we split our distribution from one build to one build per OS version).

**Comment by stephentoub** [comment]
> or we split our distribution from one build to one build per OS version

And that's what I'm wondering.  It seemed like there were some other issues still being investigated that might cause us to need to do that?  If that's the case, disabling these warnings seems premature.  If it turns out that's a red herring, great, let's proceed to port this disabling to 3.0.  But if that's actually required, seems we should hold off on https://github.com/dotnet/corefx/pull/39984 and port the "right" fix?

**Comment by bartonjs** [comment]
For 3.0 I don't think we'd rewrite SslStream on top of their new TLS stack in servicing; nor replace X509Chain with an easier to use, but less functionally capable (it only reports one code per chain), implementation of cert chaining.  If we already have to split the distribution then maybe for 3.1 or 5.0 we'd change things... but I think it'd have to be for something actually "better" vs just "different"... especially when we have to keep the old code around anyways.

**Comment by buyaa-n** [comment]
Issue #40031 created for tracking further upgrade

**Pull request merged**
