### PR TITLE
Manually updating dependencies in order to get the new coreclr packages.

### PR DESCRIPTION
**Pull request by joperezr**
FYI: @tarekgh @tannergooding since you both wanted a new version of coreclr ingested into corefx

This PR is manually updating our dependencies in order to bring some required changes from coreclr in. This PR is also doing the changes from #36927 per @tarekgh's request, which was doing an update the Index and Range interfaces and tests

### CODE REVIEW

**Comment by tannergooding** [comment]
https://github.com/dotnet/corefx/pull/36922 is also actively still going and looks to have all the stuff I need

**Comment by tarekgh** [comment]
@tannergooding do you need to update anythining corefx side for your changes?

**Comment by tannergooding** [comment]
> do you need to update anythining corefx side for your changes?

Yes, but those are included in the nearly complete PR I just linked.

**Comment by tannergooding** [comment]
(as well as are other fixes that are required)

**Comment by tarekgh** [comment]
I think it will make more sense if we cherry pick the commits we have here to #36922

**Comment by tannergooding** [comment]
@joperezr, @tarekgh. This should be unblocked now.

**Comment by tarekgh** [comment]
thanks @joperezr for the help here.

**Pull request merged**
