### PR TITLE
Add support for PCL profiles

### PR DESCRIPTION
**Pull request by ericstj**
Adds support for profile-based PCL using placeholders.

Requires: https://github.com/dotnet/buildtools/pull/633

Fixes: https://github.com/dotnet/corefx/issues/7649

### CODE REVIEW

**Comment by ericstj** [comment]
@dotnet-bot test Innerloop OSX Release Build and Test

**Comment by ericstj** [comment]
@dotnet-bot test Innerloop OSX Debug Build and Test

**Comment by weshaggard** [comment]
LGTM

**Comment by ericstj** [comment]
@dotnet-bot test Innerloop OSX Debug Build and Test

**Comment by ericstj** [comment]
@dotnet-bot test Innerloop OSX Release Build and Test

**Comment by stephentoub** [comment]
Test Innerloop Windows_NT Release Build and Test please

**Pull request merged**
