### PR TITLE
Adding Compile(bool) overload to ref file for System.Linq.Expressions.

### PR DESCRIPTION
**Pull request by bartdesmet**
This fixes issue #4191.

### CODE REVIEW

**Comment by VSadov** [comment]
LGTM

**Comment by stephentoub** [comment]
LGTM

@weshaggard, nothing additional needs to be done to update this contract, right?

@VSadov, assuming this is meant for rc1, this will likely also need to be cherry-picked to the rc1 branch.
cc: @joshfree

**Comment by VSadov** [comment]
Yes we need this in rc1 tree. 
I think it might be easier to simply issue a same PR against rc1

**Comment by joshfree** [comment]
@ericstj please review for any other needed changes

**Comment by weshaggard** [comment]
@VSadov once this change mirrors back into TFS I expect you will have to deal with some build breaks as this API isn't implemented on other platforms that this contract is supported on yet.

**Comment by VSadov** [comment]
@weshaggard - uh oh. 
The API is suggestive though, so initial implementation could just ignore the arg and call the regular Compile().

**Comment by stephentoub** [comment]
> The API is suggestive though, so initial implementation could just ignore the arg and call the regular Compile()

That sounds like a fine way to solve it, at least initially.

**Comment by weshaggard** [comment]
Agreed. Or you can temporarily baseline the APICompat issue and follow-up on it more.

**Pull request merged**
