### PR TITLE
[release/2.1] Port to release/2.1 update tizen rid for netcore app

### PR DESCRIPTION
**Pull request by gbalykov**
Cherry-pick of #30875

Related PR: #30640

cc @alpencolt @Dmitri-Botcharnikov

### CODE REVIEW

**Comment by karelz** [comment]
@danmosemsft are we going to take it for 2.1.3?

**Comment by danmosemsft** [comment]
@weshaggard is this really a necessary part of https://github.com/dotnet/corefx/pull/30640 ?  If so can you please review, and we can merge it today.

If not, we need info to take it to shiproom.

**Comment by danmosemsft** [comment]
@gbalykov  @alpencolt @Dmitri-Botcharnikov if you have a change like this that you would like to get into servicing, please invoke @danmosemsft and @karelz so we can help, because there is process we need to follow - otherwise it cannot get merged.

**Comment by weshaggard** [comment]
>@weshaggard is this really a necessary part of #30640 ? If so can you please review, and we can merge it today.

Assuming tizen is planning to have a build of 2.1.x for tizen 5.0.0 then yes this is necessary.

**Comment by danmosemsft** [comment]
OK merging as a necessary part of approved #30640.

**Comment by gbalykov** [comment]
@danmosemsft @weshaggard thank you

**Comment by gbalykov** [comment]
@weshaggard looks like .NET Core SDK 2.1.3, which is downloaded during `release/2.1` build, doesn't contain `tizen.5.0.0` RIDs at all. Should sdk version be updated?

**Comment by gbalykov** [comment]
@weshaggard I've checked and found that both `release/2.1` and `master` use SDKs, which do not contain `tizen.5.0.0` RIDs (2.1.3 and 2.1.4 correspondingly). SDK 2.2 contains `tizen.5.0.0` RID, however, it uses NETCore.App 2.2. Are there any plans for SDK updates for `release/2.1` branch? It seems that this is the reason why we are not able to build CoreFX for `tizen.5.0.0` on `release/2.1`.

**Comment by weshaggard** [comment]
I just took a quick look at our latest servicing build https://github.com/dotnet/versions/tree/master/build-info/dotnet/product/cli/release/2.1.3 and it does appear to have the tizen.5.0.0 RID in the runtime. Once that ships we can update to it. The version of the SDK for that build is 2.1.401 and so you can attempt to try that out.

**Comment by gbalykov** [comment]
@weshaggard thank you. Sdk, which you mentioned, partially helped. (For my previous comment I used https://github.com/dotnet/core-sdk/blob/master/README.md#installers-and-binaries)

Now I see that next restored nuget packages (from https://dotnet.myget.org/gallery/dotnet-core) do not contain `tizen.5.0.0` RID:

```
Microsoft.NETCore.Jit/2.1.3-servicing-26718-03
Microsoft.NETCore.Runtime.CoreCLR/2.1.3-servicing-26718-03
Microsoft.NETCore.TestHost/2.1.3-servicing-26718-03
```

These are restored during `Restoring ILAsm version '2.1.3-servicing-26718-03'` init-tools step.
For example, Microsoft.NETCore.Jit doesn't seem to contain `tizen.5.0.0` RID even in `3.0.0-preview1-26719-01`. Could you, please, suggest the way to fix this?

**Comment by gbalykov** [comment]
@weshaggard thank you!

**Comment by gbalykov** [comment]
@weshaggard I've added tizen.5.0.0 RID to CoreCLR (https://github.com/dotnet/coreclr/pull/19058). Could you, please, clarify, when will this change get to sdk?

**Comment by danmosemsft** [comment]
@gbalykov this is going to be in 2.1.4, which is on track to release mid next month.

**Pull request merged**
