### PR TITLE
Update corefx to stable packages

### PR DESCRIPTION
**Pull request by ericstj**
/cc @weshaggard @ellismg @stephentoub

### CODE REVIEW

**Comment by stephentoub** [comment]
I skimmed through the changes.  If/when CI passes, LGTM.

**Comment by dagood** [comment]
Looks good to me too. I tried fetching your change and making the CoreFX and CoreCLR rules' `ExpectedPrerelease`s nonsense values and they still validated, so there definitely aren't any missed project.json dependencies. :+1:

**Comment by joshfree** [comment]
:shipit:

**Pull request merged**
