### PR TITLE
Improved failure handling in init-tools.sh

### PR DESCRIPTION
**Pull request by rainersigwald**
I ran into some confusing error cases when I lost network during init-tools. These changes should make it both easier to understand what happened and easier to recover from.

I'm making similar changes in https://github.com/Microsoft/msbuild/pull/629.

### CODE REVIEW

**Comment by stephentoub** [comment]
@joperezr, @rainersigwald, what's the status of this PR?  Thanks.

**Comment by joperezr** [comment]
mm I'm still not sure why we need this. We've made some changes on the script to improve the error handling. @rainersigwald have you checked if the recent changes to init-tools fix your problem? If so, I would just close this.

**Comment by rainersigwald** [comment]
@joperezr I still think using `$__PROJECT_JSON_FILE` instead of a marker file written at the very end of the loop, post-success, isn't great. The error-checking you added in #8397 looks fine.

Rebased on current master and left just the more-atomic approach.

**Comment by joperezr** [comment]
LGTM

**Comment by rainersigwald** [comment]
Do y'all need anything else from me?

**Comment by joperezr** [comment]
Nope, sorry I was waiting for you to merge, but I guess you might not have the permissions to do so, do you mind fixing the conflicts you have and then I'll merge the PR for you?

**Comment by rainersigwald** [comment]
@joperezr Yeah, I don't have the commit bit in this repo :)

I rebased onto latest master.

**Comment by joperezr** [comment]
Cool, as soon as CI is green I'll merge this. Thanks @rainersigwald !

**Pull request merged**
