### PR TITLE
Escape Messages of InnerExceptions in DataContractSerializer

### LINKED ISSUE #9748: DataContractSerializer Fails to deserialize if any part contain '<' and '>'. Espically when u serialize exceptions stacktrace
Run the Program.cs file. I have reproduced the issue in simple format. The issue happens when i serialize any exception , espically stacktrace as it contains tempelate reference i.e. containing '<' and '>'.

**Program.cs**
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace SampleNetCore
{
using System.IO;
using System.Runtime.Serialization;

public class Program
{
     public static void Main(String[] srgs)
    {
        Exception e = new ArgumentException("Hello <> World");
        byte[] d = FromException1(e);
        Exception e1 = null;
        if (ToException1(d, out e1))
        {
            Console.WriteLine("After Deserializing Exception {0}", e1);
        }
        else
        {
            Console.WriteLine("Deserialiing Failed");
        }
        Console.ReadLine();

    }
    public static byte[] FromException1(Exception exception)
    {
        var serializer = new DataContractSerializer(typeof(AggregateException));

        using (var stream = new MemoryStream())
        {
            AggregateException e1 = new AggregateException(new Exception[] { exception });
            serializer.WriteObject(stream, e1);
            stream.Flush();
            return stream.ToArray();
        }

    }
    public static bool ToException1(byte[] remoteExceptionInformation, out Exception result)
    {
        var serializer = new DataContractSerializer(typeof(AggregateException));
        try
        {
            using (var stream = new MemoryStream(remoteExceptionInformation))
            {
                AggregateException result12 = (AggregateException)serializer.ReadObject(stream);
                result = result12.InnerException;
                return true;
            }
        }
        catch (Exception e)
        {
            System.Console.WriteLine("Exception Occured while Deserializing {0}  ", e);
        }
        result = null;
        return false;
    }
}
}

**project.json** 
{
"version": "1.0.0-*",
"buildOptions": {
"emitEntryPoint": true
},

"dependencies": {
"Microsoft.NETCore.App": {
"type": "platform",
"version": "1.0.0"
},
"System.Runtime.Serialization.Xml": "4.1.1"
},

"frameworks": {
"netcoreapp1.0": {
"imports": "dnxcore50"
}
}
}

Expected behavior

Any kind of exception should be serialize and deserialize, even if the content like "Message" / "StackTrace" contains '<' and '>'.

Actual behavior

The deserializing failed for above scenario.

**Environment data**

dotnet --info output:
.NET Command Line Tools (1.0.0-preview3-003161)

**Product Information:**
Version: 1.0.0-preview3-003161
Commit SHA-1 hash: 63846c5

**Runtime Environment:**
OS Name: ubuntu
OS Version: 16.04
OS Platform: Linux
RID: ubuntu.16.04-x64

### PR DESCRIPTION
**Pull request by svick**
Fixes #9748

### CODE REVIEW

**Comment by svick** [comment]
It seems to me that this and #9125 could have been avoided if `ExceptionXmlParser ` used something like `XmlWriter` instead of manually constructing the XML into a `StringBuilder`.

So, why does it use `StringBuider` directly and should that be changed?

**Comment by shmao** [comment]
@svick , thanks for finding the issue and making the PR. It looks good to me. And that's a good question, I asked the author of `ExceptionXmlParser` the same question when I worked on https://github.com/dotnet/corefx/pull/9125. The answer was that some `XmlWriter`'s APIs was not available on CoreCLR at that time. As these two fixes are simple enough, I think we can keep `ExceptionXmlParser` as is for now. 

@mconnew , can you please review the PR?

**Comment by mconnew** [comment]
LGTM

**Pull request merged**
