### PR TITLE
Fixed netfx System.Threading.Tasks.Tests fails on non-English Windows

### PR DESCRIPTION
**Pull request by AlexRadch**
See https://github.com/dotnet/corefx/issues/28136

### CODE REVIEW

**Comment by stephentoub** [comment]
Is the issue here simply because of this one Assert.Contains?
https://github.com/AlexRadch/corefx/blob/405cfe642ee799e3fd941c6809e225c0ca4a4d89/src/System.Threading.Tasks/tests/System.Runtime.CompilerServices/AsyncTaskMethodBuilderTests.cs#L578
If so, rather than adding all of these RemoteInvokes, I'd rather we just not run that Contains on netfx, e.g.
```C#
if (!PlatformDetection.IsFullFramework)
{
    Assert.Contains("End of stack trace", e.StackTrace);
}
```

**Comment by AlexRadch** [comment]
> Is the issue here simply because of this one Assert.Contains?

Yes, but I think it does not fail on corefx because it translated partially. String tests should be in invariant culture but UWP has culture issue.

**Comment by stephentoub** [comment]
Then I'd suggest just deleting the Contains.  That assert isn't worth adding a bunch of RemoteInvokes.

**Comment by AlexRadch** [comment]
> Then I'd suggest just deleting the Contains. That assert isn't worth adding a bunch of RemoteInvokes.

I do not know what tests I can remove so I make RemoteInvoke. If I can remove this test I will.

**Comment by stephentoub** [comment]
> I do not know what tests I can remove so I make RemoteInvoke. If I can remove this test I will.

Understood. Thanks.  I think it's fine to remove that one-line assert.

**Pull request merged**
