### PR TITLE
Consolidate AssemblyTests, AssemblyNameTests, MethodInfoTests fixtures within System.Reflection location

### PR DESCRIPTION
**Pull request by MaximLipnin**
It's a continuation of work done in https://github.com/dotnet/corefx/pull/32738

The following fixtures were merged/moved to System.Reflection location:
- AssemblyNameTests
- AssemblyTests (with AssemblyTests_GetType and AssemblyCustomAttributeTest)
- AssemblyNetCoreAppTests
- MethodInfoTests

/cc @marek-safar 

<details>
  <summary>
    Test methods mapping
  </summary>

System.Runtime | System.Reflection
-- | --
<b>AssemblyNameTests</b>
Verify_CultureName() | Verify_CultureName()
Verify_CodeBase() | Verify_CodeBase()
Verify_EscapedCodeBase() | Verify_EscapedCodeBase()
Verify_HashAlgorithm() | Verify_HashAlgorithm()
Verify_VersionCompatibility | Verify_VersionCompatibility
Clone() | Clone()
GetAssemblyName() | GetAssemblyName()
GetAssemblyName_LockedFile() | GetAssemblyName_LockedFile()
ReferenceMatchesDefinition(AssemblyName   a1, AssemblyName a2, bool expected) | ReferenceMatchesDefinition(AssemblyName a1, AssemblyName a2, bool   expected)
<b>AssemblyTests</b>
Equality(Assembly assembly1, Assembly   assembly2, bool expected) | Equality(Assembly assembly1, Assembly assembly2, bool expected)
GetAssembly_Nullery() | GetAssembly_Nullery()
GetAssembly(Assembly assembly1, Assembly   assembly2, bool expected) | GetAssembly(Assembly assembly1, Assembly assembly2, bool expected)
GetCallingAssembly(Assembly assembly1,   Assembly assembly2, bool expected) | GetCallingAssembly(Assembly assembly1, Assembly assembly2, bool expected)
GetExecutingAssembly() | GetExecutingAssembly()
GetSatelliteAssemblyNeg() | GetSatelliteAssemblyNeg()
AssemblyLoadFromString() | AssemblyLoadFromString()
AssemblyLoadFromStringNeg() | AssemblyLoadFromStringNeg()
AssemblyLoadFromBytes() | AssemblyLoadFromBytes()
AssemblyLoadFromBytesNeg() | AssemblyLoadFromBytesNeg()
ssemblyLoadFromBytesWithSymbols() | ssemblyLoadFromBytesWithSymbols()
AssemblyReflectionOnlyLoadFromString() | AssemblyReflectionOnlyLoadFromString()
AssemblyReflectionOnlyLoadFromBytes() | AssemblyReflectionOnlyLoadFromBytes()
AssemblyReflectionOnlyLoadFromNeg() | AssemblyReflectionOnlyLoadFromNeg()
etModules_GetModule(Assembly assembly) | etModules_GetModule(Assembly assembly)
GetLoadedModules() | GetLoadedModules()
CreateInstance(Assembly assembly, string   typeName, BindingFlags bindingFlags, Type expectedType) | CreateInstanceWithBindingFlags(Assembly assembly, string typeName,   BindingFlags bindingFlags, Type expectedType)
CreateInstance_Invalid(string typeName,   Type exceptionType) | CreateInstance_Invalid(string typeName, Type exceptionType)
GetManifestResourceStream() | GetManifestResourceStream(string resource, bool exists)
Test_GlobalAssemblyCache() | GlobalAssemblyCache()
Test_HostContext() | HostContext()
Test_IsFullyTrusted() | IsFullyTrusted()
SecurityRuleSet_Netcore() | Test_SecurityRuleSet_Netcore()
Test_SecurityRuleSet_Netfx() | SecurityRuleSet_Netfx()
Test_LoadFile() | LoadFile()
LoadFile_NullPath_Netcore_ThrowsArgumentNullException() | LoadFile_NullPath_Netcore_ThrowsArgumentNullException()
LoadFile_NoSuchPath_ThrowsArgumentException() | LoadFile_NoSuchPath_ThrowsArgumentException()
Test_LoadFromUsingHashValue_Netcore() | LoadFromUsingHashValue_Netcore()
Test_LoadFromUsingHashValue_Netfx() | LoadFromUsingHashValue_Netfx()
Test_LoadModule_Netcore() | LoadModule_Netcore()
Test_LoadModule_Netfx() | LoadModule_Netfx()
Test_LoadWithPartialName() | LoadWithPartialName()
LoadFrom_SamePath_ReturnsEqualAssemblies() | LoadFrom_SamePath_ReturnsEqualAssemblies()
LoadFrom_SameIdentityAsAssemblyWithDifferentPath_ReturnsEqualAssemblies() | LoadFrom_SameIdentityAsAssemblyWithDifferentPath_ReturnsEqualAssemblies()
LoadFrom_NullAssemblyFile_ThrowsArgumentNullException() | LoadFrom_NullAssemblyFile_ThrowsArgumentNullException()
LoadFrom_EmptyAssemblyFile_ThrowsArgumentException() | LoadFrom_EmptyAssemblyFile_ThrowsArgumentException()
LoadFrom_NoSuchFile_ThrowsFileNotFoundException() | LoadFrom_NoSuchFile_ThrowsFileNotFoundException()
UnsafeLoadFrom_SamePath_ReturnsEqualAssemblies() | UnsafeLoadFrom_SamePath_ReturnsEqualAssemblies()
LoadFrom_WithHashValue_NetCoreCore_ThrowsNotSupportedException() | LoadFrom_WithHashValue_NetCoreCore_ThrowsNotSupportedException()
GetFile() | GetFile()
GetFiles() | GetFiles()
<b>AssemblyTests_GetType</b> |  
AssemblyGetTypeNoQualifierAllowed() | GetType_NoQualifierAllowed()
AssemblyGetTypeDoesntSearchMscorlib() | GetType_DoesntSearchMscorlib()
AssemblyGetTypeDefaultsToItself() | GetType_DefaultsToItself()
<b>AssemblyCustomAttributeTest</b> |  
Test_Int32AttrSimple() | GetCustomAttributesData(Type attrType)
Test_Int64Attr() | GetCustomAttributesData(Type attrType)
Test_StringAttr() | GetCustomAttributesData(Type attrType)
Test_EnumAttr() | GetCustomAttributesData(Type attrType)
Test_TypeAttr() | GetCustomAttributesData(Type attrType)
Test_CompilationRelaxationsAttr() | GetCustomAttributesData(Type attrType)
Test_AssemblyIdentityAttr() | GetCustomAttributesData(Type attrType)
Test_AssemblyDescriptionAttribute() | GetCustomAttributesData(Type attrType)
Test_AssemblyCompanyAttribute() | GetCustomAttributesData(Type attrType)
Test_CLSCompliantAttribute() | GetCustomAttributesData(Type attrType)
Test_DebuggableAttribute() | GetCustomAttributesData(Type attrType)
Test_SimpleAttribute() | GetCustomAttributesData(Type attrType)
<b>MethodInfoTests</b>
TestEquality1(string str1, string str2,   bool expected) | Equality1(string str1, string str2, bool expected)
TestEquality2(Type sample1, Type sample2,   string str1, string str2, bool expected) | Equality2(Type sample1, Type sample2, string str1, string str2, bool   expected)
AssemblyNetCoreAppTests   (moved to System.Reflection)

</details>

### CODE REVIEW

**Comment by MaximLipnin** [comment]
@dotnet-bot test Linux x64 Release Build

**Comment by MaximLipnin** [comment]
@dotnet-bot test Packaging All Configurations x64 Debug Build

**Comment by stephentoub** [comment]
cc: @steveharter

**Comment by danmosemsft** [comment]
@stephentoub good to merge?

**Comment by MaximLipnin** [comment]
@steveharter Could you please take a look?

**Comment by marek-safar** [comment]
@danmosemsft can we get this merged soon?

**Comment by weshaggard** [comment]
@MaximLipnin is there any reason you needed to duplicate the ForwardedTypesAssembly and UnloadableAssembly projects? It is causing race conditions in our build see https://github.com/dotnet/corefx/issues/33219. I'm going to remove these and just reference the ones under System.Reflection.

**Comment by MaximLipnin** [comment]
Sorry for inconvenience, seems I forgot to delete those test assemblies from System.Runtime.

**Pull request merged**
