### PR TITLE
Port HttpListener fixes to release/2.0.0

### LINKED ISSUE #20060: [HttpListener] Port HttpListener managed fixes to 2.0 en mass
We have a bunch of fixes coming in to the managed HttpListener.  We should roll-up and review all changes made since forking for 2.0, and port them over en masse rather than reviewing each piece meal.

### PR DESCRIPTION
**Pull request by stephentoub**
This ports all changes to HttpListener since we forked the release/2.0.0 branch on May 17th.  We can separately do a clean-up port to address any remaining issues addressed today/tomorrow.

Fixes #20060.
cc: @geoffkizer

### CODE REVIEW

**Comment by stephentoub** [comment]
@dotnet-bot help

**Comment by stephentoub** [comment]
@dotnet-bot test outerloop netfx Windows_NT Debug
@dotnet-bot test outerloop netcoreapp Windows 10 Debug
@dotnet-bot test outerloop netcoreapp OSX10.12 Debug
@dotnet-bot test outerloop netcoreapp Ubuntu16.10 Debug
@dotnet-bot test outerloop netcoreapp PortableLinux Debug

**Comment by geoffkizer** [comment]
LGTM

**Comment by stephentoub** [comment]
@dotnet-bot test OuterLoop netfx Windows_NT Debug x64 please (https://github.com/dotnet/corefx/issues/11737)

**Comment by geoffkizer** [comment]
@dotnet-bot test OuterLoop netfx Windows_NT Debug x64 please

**Pull request merged**
