### PR TITLE
Add already-implemented Socket APM methods back to the public surface.

### PR DESCRIPTION
**Pull request by ericeil**
Added these to the reference assembly, and made them public in the implementation.  We already had some tests for these, via shims; I've just removed the shims.

@stephentoub @CIPop @danmosemsft

### CODE REVIEW

**Comment by ericeil** [comment]
@dotnet-bot Test Outerloop Windows_NT Debug please
@dotnet-bot Test Outerloop Ubuntu14.04 Debug please
@dotnet-bot Test Outerloop OSX Debug please

**Comment by davidsh** [comment]
Have we already rev'd 'dir.props' to increment the contract version for System.Net.Sockets?

**Comment by ericeil** [comment]
> Have we already rev'd 'dir.props' to increment the contract version for System.Net.Sockets?

Yes

**Comment by davidsh** [comment]
I thought we were going to do API stuff now in [master] since dev/api was merged?

**Comment by stephentoub** [comment]
> I thought we were going to do API stuff now in [master] since dev/api was merged?

We are.  I didn't notice the branch.  Eric, we should move this to master.

**Comment by ericeil** [comment]
> I thought we were going to do API stuff now in [master] since dev/api was merged?

I started my previous PR (the one that rev'd the version number) before I knew about that.  This change depends on that onw.  As I understand it, we're going to do another merge from dev/api in a week or so.

**Comment by ericeil** [comment]
> Eric, we should move this to master.

Should I do that without the version change?  Or merge that along with this change?

**Comment by davidsh** [comment]
>Or merge that along with this change?

Yes

**Pull request closed without merging**
