### PR TITLE
Fixed netfx System.ComponentModel.TypeConverter.Tests-InvariantCulture on non English Windows

### PR DESCRIPTION
**Pull request by AlexRadch**
Fixed netfx System.ComponentModel.TypeConverter.Tests-InvariantCulture on non English Windows
See https://github.com/dotnet/corefx/issues/28136

### CODE REVIEW

**Comment by AlexRadch** [comment]
@dotnet-bot test Windows x86 Release Build please

**Comment by danmosemsft** [comment]
@AlexRadch because on UWP culture is process wide currently, all tests that set culture must do it in a child process. It is very easy. Please search for Remoteinvoke. Test class must derive from RemoteTestBase

**Comment by AlexRadch** [comment]
> UWP culture is process wide currently

When I change current UI culture for thread it is be changed in all threads of process?
For example, can I use `Thread.CurrentUICulture` or not?

**Comment by AlexRadch** [comment]
I found `ThreadCultureChange` class https://github.com/dotnet/corefx/search?utf8=%E2%9C%93&q=ThreadCultureChange&type= . `ThreadCultureChange` class is used to change and restore `current culture` and `current UI culture` without using `Remoteinvoke`. I can change my code to use this class.

**Comment by safern** [comment]
cc @tarekgh who knows much about culture stuff.

**Comment by tarekgh** [comment]
@AlexRadch here is an example how to remote invoke the test 

https://github.com/dotnet/corefx/blob/master/src/System.Globalization/tests/CultureInfo/CultureInfoCurrentCulture.cs#L20

you need to do the same as any changes in current cultures can affect other tests running in parallel and the tests changing the current culture have to run remotely in its own processes.

**Comment by tarekgh** [comment]
@AlexRadch could you please paste here the original failures we before your change? so, we can know how your change is fixing the failures? #28136 is not having the failures logs.

**Comment by AlexRadch** [comment]
```
    Starting:    System.ComponentModel.TypeConverter.Tests
      System.ComponentModel.Tests.CollectionConverterTests.ConvertTo_WithContext [FAIL]
        Assert.Equal() Failure
        Expected: (Collection)
        Actual:   (Коллекция)
        Stack Trace:
             в Xunit.Assert.Equal[T](T expected, T actual, IEqualityComparer`1 comparer) в C:\BuildAgent\work\cb37e9acf085d108\src\xunit.assert\Asserts\EqualityAsserts.cs:строка 35
             в System.ComponentModel.Tests.ConverterTestBase.ConvertTo_WithContext(Object[,] data, TypeConverter converter)
             в System.ComponentModel.Tests.CollectionConverterTests.ConvertTo_WithContext()
      System.ComponentModel.Tests.CultureInfoConverterTest.ConvertFrom_Value_Null [FAIL]
        Assert.True() Failure
        Expected: True
        Actual:   False
        Stack Trace:
             в Xunit.Assert.True(Nullable`1 condition, String userMessage) в C:\BuildAgent\work\cb37e9acf085d108\src\xunit.assert\Asserts\BooleanAsserts.cs:строка 90
             в System.ComponentModel.Tests.CultureInfoConverterTest.ConvertFrom_Value_Null()
      System.ComponentModel.Tests.ReferenceConverterTest.ConvertTo [FAIL]
        Assert.Equal() Failure
                    (pos 1)
        Expected: (none)
        Actual:   (нет)
                    (pos 1)
        Stack Trace:
             в Xunit.Assert.Equal(String expected, String actual, Boolean ignoreCase, Boolean ignoreLineEndingDifferences, Boolean ignoreWhiteSpaceDifferences) в C:\BuildAgent\work\cb37e9acf085d108\src\xunit.assert\Asserts\StringAsserts.cs:строка 239
             в Xunit.Assert.Equal(String expected, String actual) в C:\BuildAgent\work\cb37e9acf085d108\src\xunit.assert\Asserts\StringAsserts.cs:строка 170
             в System.ComponentModel.Tests.ReferenceConverterTest.ConvertTo()
      System.ComponentModel.Design.Tests.DesignerOptionServiceTests.DesignerOptionConverter_ConvertToString_ReturnsExpected [FAIL]
        Assert.Equal() Failure
                    (pos 1)
        Expected: (Collection)
        Actual:   (Коллекция)
                    (pos 1)
        Stack Trace:
             в Xunit.Assert.Equal(String expected, String actual, Boolean ignoreCase, Boolean ignoreLineEndingDifferences, Boolean ignoreWhiteSpaceDifferences) в C:\BuildAgent\work\cb37e9acf085d108\src\xunit.assert\Asserts\StringAsserts.cs:строка 239
             в Xunit.Assert.Equal(String expected, String actual) в C:\BuildAgent\work\cb37e9acf085d108\src\xunit.assert\Asserts\StringAsserts.cs:строка 170
             в System.ComponentModel.Design.Tests.DesignerOptionServiceTests.DesignerOptionConverter_ConvertToString_ReturnsExpected()
      System.ComponentModel.Tests.MultilineStringConverterTests.ConvertTo_WithContext [FAIL]
        Assert.Equal() Failure
        Expected: (Text)
        Actual:   (Текст)
        Stack Trace:
             в Xunit.Assert.Equal[T](T expected, T actual, IEqualityComparer`1 comparer) в C:\BuildAgent\work\cb37e9acf085d108\src\xunit.assert\Asserts\EqualityAsserts.cs:строка 35
             в System.ComponentModel.Tests.ConverterTestBase.ConvertTo_WithContext(Object[,] data, TypeConverter converter)
             в System.ComponentModel.Tests.MultilineStringConverterTests.ConvertTo_WithContext()
      System.ComponentModel.Tests.ArrayConverterTests.ConvertTo_WithContext [FAIL]
        Assert.Equal() Failure
        Expected: Int32[] Array
        Actual:   Массив Int32[]
        Stack Trace:
             в Xunit.Assert.Equal[T](T expected, T actual, IEqualityComparer`1 comparer) в C:\BuildAgent\work\cb37e9acf085d108\src\xunit.assert\Asserts\EqualityAsserts.cs:строка 35
             в System.ComponentModel.Tests.ConverterTestBase.ConvertTo_WithContext(Object[,] data, TypeConverter converter)
             в System.ComponentModel.Tests.ArrayConverterTests.ConvertTo_WithContext()
      System.ComponentModel.Tests.TypeListConverterTests.ConvertTo_WithContext [FAIL]
        Assert.Equal() Failure
        Expected: (none)
        Actual:   (нет)
        Stack Trace:
             в Xunit.Assert.Equal[T](T expected, T actual, IEqualityComparer`1 comparer) в C:\BuildAgent\work\cb37e9acf085d108\src\xunit.assert\Asserts\EqualityAsserts.cs:строка 35
             в System.ComponentModel.Tests.ConverterTestBase.ConvertTo_WithContext(Object[,] data, TypeConverter converter)
             в System.ComponentModel.Tests.TypeListConverterTests.ConvertTo_WithContext()
    Finished:    System.ComponentModel.TypeConverter.Tests
  === TEST EXECUTION SUMMARY ===
C:\Code\corefx2\Tools\tests.targets(492,5): warning :    System.ComponentModel.TypeConverter.Tests  Total: 5725, Errors: 0, Failed: 7, Skipped: 0, Time: 0,886s [C:\Code\corefx2\src\System.ComponentModel.TypeConverter\tests\System.ComponentModel.TypeConverter.Tests.csproj]
```

**Comment by tarekgh** [comment]
Isn't better to pass the required culture in the test data instead of setting current cultures? for example in the test 

https://github.com/dotnet/corefx/blob/master/src/System.ComponentModel.TypeConverter/tests/CollectionConverterTests.cs#L18

instead of passing null in the array 

```C#
{ new Collection1(), "(Collection)", null }
``` 

you can try to pass CultureInfo.InvariantCulture

**Comment by AlexRadch** [comment]
> Isn't better to pass the required culture in the test data instead of setting current cultures? for example in the test

I will try but I think it will not work because it change numbers, date and etc format but not string resources.

**Comment by AlexRadch** [comment]
> Isn't better to pass the required culture in the test data instead of setting current cultures? for example in the test

I tested it does not work. Only CurrentUICulture changes string resources to invariant.

**Comment by tarekgh** [comment]
Thanks @AlexRadch. LGTM.

**Comment by AlexRadch** [comment]
@dotnet-bot test Linux x64 Release Build
@dotnet-bot test Windows x86 Release Build

**Pull request merged**
