### PR TITLE
Merge pull request #29281 from ericstj/sm.syndic.facade

### PR DESCRIPTION
**Pull request by StephenBonikowsky**
ServiceModel.Syndication needs to expose facade on desktop

(cherry picked from commit b64c6b8c4892ebe13a84f205f4558a7531da22c8)

### CODE REVIEW

**Comment by StephenBonikowsky** [comment]
@ericstj I'm not able to add reviewers, could you add as needed?
I also can't add any needed labels/milestones for ask mode purposes.
Could you take this PR through the CoreFx ask-mode process?

**Comment by ericstj** [comment]
I marked it for you.  For ask mode you should just send mail.  @Lxiamail should have the details.

**Comment by StephenBonikowsky** [comment]
Thanks guys, ship room approved this PR can someone merge it for me?

**Comment by ericstj** [comment]
Test OSX x64 Debug Build
Test NETFX x86 Release Build

**Comment by ericstj** [comment]
Test OSX x64 Debug Build

**Pull request merged**
