### PR TITLE
Directory.Build.props cleanup

### PR DESCRIPTION
**Pull request by jcagme**
Remove `RestoreSources` from Versions.props in order to complete [step 2](https://github.com/dotnet/arcade/blob/master/Documentation/RestoreSourcesUpdateStatus.md#part-2)

@danmosemsft could you please add someone to take a look at this?

### CODE REVIEW

**Comment by jcagme** [comment]
CI timed out during Linux testing so I assume all the libraries were restored correctly. Good to merge @safern ?

**Comment by safern** [comment]
FYI: @ericstj @ViktorHofer

**Comment by safern** [comment]
People can still use `CoreCLROverridePath` I think we should just update the docs and remove the `OverridePackageSource` instances in the docs.

**Comment by ViktorHofer** [comment]
Oh you are right. For `CoreCLROverridePath` we don't use nuget packages and just do a binary copying. I didn't think about that. Thanks!

**Comment by ViktorHofer** [comment]
I see one of our cross-build scripts use the `OverridePackageSource` option: https://github.com/dotnet/corefx/blob/5c83394112febe1b481ab1c0b61a45c850677165/cross/arm32_ci_script.sh#L237

**Pull request merged**
