### PR TITLE
Fix stale async-related comments in FileStream

### LINKED ISSUE #2117: Some comments in Win32FileStream out of date
Some comments in Win32FileStream still linking to methods BeginRead/BeginReadCore/BeginWrite/BeginWriteCore which were removed in #972

**UPD**
some `Debug.Assert` messages are also out of date

### PR DESCRIPTION
**Pull request by stephentoub**
Leftover after the async rewrite in #972.

Fixes #2117.

### CODE REVIEW

**Comment by stephentoub** [comment]
cc: @ericstj, @Maxwe11

**Comment by Maxwe11** [comment]
:+1:

**Comment by ericstj** [comment]
LGTM

**Comment by stephentoub** [comment]
Thanks, guys.

**Pull request merged**
