### PR TITLE
Implementation of ProcessStartInfo.CreateNewProcessGroup property

### PR DESCRIPTION
**Pull request by PaulHigin**
This is an implementation for the API request issue #17412.

Normally a new child process is created in the same process group as the parent process.  This change allows a child process to be created in its own process group.

For Windows this change simply sets the CREATE_NEW_PROCESS_GROUP flag when creating the process.

For Unix this change uses the setpgid system call to set the process group id to be the same as the process id.  

I wasn't able to find any Windows managed or native API to determine a process group id.  So functional tests work only in Unix where they use system calls to verify a process group id.

### CODE REVIEW

**Comment by danmosemsft** [comment]
@PaulHigin thanks for the contribution. The original issue needs to go through API Review process first. Then it gets tagged with api-approved (or not). @karelz that's @Priya91 's maybe there's someone else who can look at it or she can when she gets back from vac.

**Comment by karelz** [comment]
Correct, APIs need to follow [API review process](https://github.com/dotnet/corefx/blob/master/Documentation/project-docs/api-review-process.md).

I would suggest to close this PR and take the discussion into the issue #17412 first.
We are just finishing off 2.0 and my backup in area is OOF sick today (probably tomorrow), so if it can wait until next week, it would be really great. Thanks!

**Comment by PaulHigin** [comment]
I thought the API review process was complete.  The requested API change was acceptable to me and that is what I implemented here.  What is the next step?

**Comment by karelz** [comment]
Let's take the discussion to the issue

**Comment by PaulHigin** [comment]
Closing until the API review is complete.

**Pull request closed without merging**
