### PR TITLE
Add macOS 10.14 Mojave to the RID graph  (#31548)

### PR DESCRIPTION
**Pull request by joshfree**
Add macOS 10.14 Mojave to Microsoft.NETCore.Platforms

Fixes https://github.com/dotnet/corefx/issues/31547

### CODE REVIEW

**Comment by joshfree** [comment]
Will merge once we get the go-ahead for 2.1.5 PRs from @vivmishra

**Comment by karelz** [comment]
@vivmishra when do you expect the go-ahead?
cc @danmosemsft

**Comment by vivmishra** [comment]
We open on 8/27.

**Comment by karelz** [comment]
Thanks @vivmishra! @wtgodbe can you please merge it when the branch opens?

**Pull request merged**
