### PR TITLE
Revert "Add Win32 File.Encrypt/Decrypt() implementation"

### PR DESCRIPTION
**Pull request by ViktorHofer**
Reverts dotnet/corefx#31585
Fixes https://github.com/dotnet/corefx/issues/31724

### CODE REVIEW

**Comment by ViktorHofer** [comment]
@jkotas chose you as reviewer as you were online on IM

**Comment by jkotas** [comment]
Where are we seeing the build break? Why is not CI catching this?

I agree that this cycle is bad and needs to be fixed.

**Comment by ViktorHofer** [comment]
CI logged the error but didn't fail: https://ci3.dot.net/job/dotnet_corefx/job/master/job/windows-TGroup_netcoreapp+CGroup_Debug+AGroup_x64+TestOuter_false_prtest/15491/consoleText

**Comment by MarcoRossignoli** [comment]
i reported this issue https://github.com/dotnet/corefx/pull/31585#discussion_r209419445 on that PR. After merge i updated my local repo to add other changes https://github.com/dotnet/corefx/pull/31716 and also in my local buildi get error, so i reported it.

> I think it is overkill to pull in dependency on DriveInfo to just check for NTFS filesystem.

@jkotas @JeremyKuhne @pjanotti let me know if we can skip this check or what strategy we need to follow and i'll amend!

**Comment by jkotas** [comment]
> CI logged the error but didn't fail.

@ViktorHofer Do we have an issue that tracks this problem? My guess it is a bug introduced by switching build to use .NET Core msbuild.

> What do you think about use directly pinvoke?Similar to

Yes, I think it is a good idea.

**Comment by ViktorHofer** [comment]
> @ViktorHofer Do we have an issue that tracks this problem? My guess it is a bug introduced by switching build to use .NET Core msbuild.

Opened https://github.com/dotnet/corefx/issues/31728.

**Comment by JeremyKuhne** [comment]
@ViktorHofer thanks for taking care of this.

@MarcoRossignoli Personally I'm ok with not even checking the filesystem. If they had an API that gave back whether or not EFS was supported I'd consider that, checking the filesystem type is error-prone. (The filesystems evolve, "ReFS" being a case in point).

**Comment by JeremyKuhne** [comment]
https://github.com/dotnet/corefx/pull/31725 had to remove this.

I'm fine, and actually be better with removing the filesystem check completely as I described in the above pull.

In addition, you can add some tests that simply check to see that the encrypted flag is set / not set I believe. `FileAttributes.Encrypted`.

**Comment by MarcoRossignoli** [comment]
@jkotas @pjanotti @JeremyKuhne only to be sure(there are different idea on different thread, pinvoke vs remove check) i'll go with remove check, right?

**Comment by JeremyKuhne** [comment]
> per docs GetVolumeInformation has a flag to check for EFS support. It is much better than using some indirect validation.


Thanks for looking into it @pjanotti.  @MarcoRossignoli, that is definitely the API to use. :)

**Pull request merged**
