### PR TITLE
[ARM/CI] Fix arm32_ci_script.sh for hardfp

### PR DESCRIPTION
**Pull request by wateret**
Related Issue: #12545

### CODE REVIEW

**Comment by wateret** [comment]
Cannot do the test on CI cause there is no prtest for it.

**Comment by wateret** [comment]
The arm-hardfp CI fails with:

```
18:19:44 Building corefx...
18:19:44 Exporting LINUX_ARM_* environment variable
18:19:44 ./scripts/arm32_ci_script.sh: line 170: /opt/linux-arm-emulator-root_arm/dotnet/setenv/setenv_incpath.sh: No such file or directory
18:19:44 The script is exited. Cleaning environment..
```

This PR will fix it.

**Comment by mellinoe** [comment]
@dotnet-bot Test Innerloop Linux ARM Emulator SoftFP Debug Cross Build
Test Innerloop Linux ARM Emulator SoftFP Release Cross Build

**Comment by mellinoe** [comment]
@dotnet-bot Test Innerloop Linux ARM Emulator SoftFP Debug Cross Build

**Comment by mellinoe** [comment]
@dotnet-bot help

**Comment by wateret** [comment]
@mellinoe Is there a way to add optional prtests for arm(both hardfp and softfp)?

**Comment by mellinoe** [comment]
@wateret They should already exist, actually. The problem is I can't figure out the magic words to get @dotnet-bot to start a run for them... @mmitche

**Comment by mellinoe** [comment]
Actually I think what exist are jobs which run whenever something is actually committed to the branch. We might be able to trigger those manually here, I'm not sure. We might need to define other jobs instead, though. @mmitche would know for sure.

**Comment by mmitche** [comment]
you can comment @dotnet-bot help, it should tell you all available phrases.

**Comment by wateret** [comment]
@dotnet-bot help

**Comment by wateret** [comment]
@dotnet-bot help

**Pull request merged**
