### PR TITLE
Update S.L.E to compile when NO_FEATURE_STATIC_DELEGATE and FEATURE_MAKE_RUN_METHODS are defined

### PR DESCRIPTION
**Pull request by marek-safar**

### CODE REVIEW

**Comment by karelz** [comment]
cc: @JonHanna @bartdesmet @OmarTawfik @VSadov

**Comment by JonHanna** [comment]
What do these constants relate to? (Since I don't know, I won't opine on the change, but would like to know if it means there are possible conditions that aren't considered in the tests).

**Comment by marek-safar** [comment]
They are not used by coreclr/corert because they support delegate augmentation but that's not yet the case for Mono.

The relevant source code entry https://github.com/dotnet/corefx/blob/ff39fad5ed911cc1dadae16396209ab8c6720234/src/System.Linq.Expressions/src/System/Linq/Expressions/Interpreter/LightLambda.cs#L362

**Comment by VSadov** [comment]
>             throw new NotImplementedException("byref delegate");

Is this still NYI? 
It seems it would block most methods with ref parameters.

---
Refers to: src/System.Linq.Expressions/src/System/Linq/Expressions/Interpreter/LightLambda.cs:356 in 47ddeda. [](commit_id = 47ddeda6dd99315680a61473fe331543fca76b13, deletion_comment = False)

**Comment by VSadov** [comment]
>             lock (_runCache)

I think CacheDict is threadsafe. It might make sense to remove the lock if/when touching this code.

---
Refers to: src/System.Linq.Expressions/src/System/Linq/Expressions/Interpreter/LightLambda.cs:202 in 47ddeda. [](commit_id = 47ddeda6dd99315680a61473fe331543fca76b13, deletion_comment = False)

**Comment by VSadov** [comment]
The purpose of this change is just to make S.L.E. compilable with NO_FEATURE_STATIC_DELEGATE and FEATURE_MAKE_RUN_METHODS

**Comment by VSadov** [comment]
Note that there is some overlap between the codepath that is enabled by these flags and CreateObjectArrayDelegateRefEmit and because of caching and not using RefEmit, the overlapping cases might be better supported by NO_FEATURE_STATIC_DELEGATE code.

It might be an attractive change to rearrange the code to make these NO_FEATURE_STATIC_DELEGATE helpers to be always included (thus dropping these flags) and let them have the first chance at creating delegates when compiled with `!FEATURE_DYNAMIC_DELEGATE`.

The additional benefit would be that this code is actually tested when running on CLR as well.

**Comment by VSadov** [comment]
Assuming that the purpose of the change is just to make S.L.E. compilable with NO_FEATURE_STATIC_DELEGATE and FEATURE_MAKE_RUN_METHODS,  - LGTM

**Pull request merged**
