### PR TITLE
Fix System.Globalization test to run against net46

### PR DESCRIPTION
**Pull request by tarekgh**
Currently we build the tests as netstandard library so we never build with TargetGroup=net46
System.Globalization test was written depending on TargetGroup=net46.
The change here is to fix this issue and also fix Unicode Category test to run fine with old Unicode category data

### CODE REVIEW

**Comment by tarekgh** [comment]
CC @danmosemsft @weshaggard 

FYI @karajas 

Fixes #10885

**Comment by tarekgh** [comment]
please hold a little on the review, I am going to have some delta change.

**Comment by danmosemsft** [comment]
Consider adding inline comments after SkipOnTargetFramework bring briefly why the skip.

**Comment by tarekgh** [comment]
@danmosemsft I have added some comments as suggested.

**Comment by tarekgh** [comment]
The failed test on CentOS is tracked by the issue #13907

**Pull request merged**
