### PR TITLE
Add debian.8.2 to RID graph during transition period 

### PR DESCRIPTION
**Pull request by chcosta**
…ince these packages have now been published.

/cc @weshaggard

### CODE REVIEW

**Comment by chcosta** [comment]
Looks like the builds are failing due to a collision with https://github.com/dotnet/corefx/commit/dd98d34ef09e4ddfc571f3f069645838fd1064ca

**Comment by chcosta** [comment]
@dotnet-bot Test Innerloop OSX Debug Build and Test
@dotnet-bot Test Innerloop OSX Release Build and Test

**Comment by weshaggard** [comment]
@chcosta it is really hard to review these large changes did you also include an update to build tools which has the tool-runtime?

**Comment by chcosta** [comment]
The buildtools PR is still pending - https://github.com/dotnet/buildtools/pull/461

This change updates all of the project.json files, src\common\test-runtime\project.json (changes debian.8.2 reference to debian.8), and updates dir.props to change the ExpectedPrerelease version to 23819.

**Comment by weshaggard** [comment]
LGTM although the current changes don't match the title of the PR.

**Comment by stephentoub** [comment]
@dotnet-bot test this please

**Comment by ellismg** [comment]
LGTM as well.

**Pull request merged**
