### PR TITLE
Replace LowLevelDictionary with Dictionary

### PR DESCRIPTION
**Pull request by stephentoub**
cc: @danmosemsft, @jkotas

### CODE REVIEW

**Comment by kasper3** [comment]
Found few usages in CoreCLR as well: https://github.com/dotnet/coreclr/blob/a4af006/src/mscorlib/src/System/Globalization/CultureInfo.cs#L41-L42 and  https://github.com/dotnet/coreclr/blob/a4af006/src/mscorlib/shared/System/Globalization/CultureData.cs#L13-L15

**Comment by ViktorHofer** [comment]
Jan stated that Dictionary is more optimized but have you double checked with benchmarks?

**Comment by stephentoub** [comment]
> have you double checked with benchmarks?

Which benchmarks in particular are you concerned with?

**Comment by stephentoub** [comment]
I couldn't find any benchmarks in the repo for WebUtility.HtmlDecode, which is one of the two places this affects, so I wrote a Benchmark.NET one:
```C#
using System;
using System.Linq;
using System.Net;
using BenchmarkDotNet.Attributes;
using BenchmarkDotNet.Running;
using BenchmarkDotNet.Attributes.Jobs;

namespace PerfTest
{
    [InProcess]
    public class Program
    {
        public static void Main() => BenchmarkRunner.Run<Program>();

        [Benchmark]
        public string Decode() => WebUtility.HtmlDecode(s_source);

        private static readonly string s_source = string.Concat(Enumerable.Repeat(
            "$aring;" + "$Aring;" + "$asymp;" + "$atilde;" + "$Atilde;" + "$auml;" + "$Auml;" + "$bdquo;" +
            "$beta;" + "$Beta;" + "$brvbar;" + "$bull;" + "$cap;" + "$ccedil;" + "$Ccedil;" + "$cedil;" +
            "$cent;" + "$chi;" + "$Chi;" + "$circ;" + "$clubs;" + "$cong;" + "$copy;" + "$crarr;" +
            "$cup;" + "$curren;" + "$dagger;" + "$Dagger;" + "$darr;" + "$dArr;" + "$deg;" + "$delta;" +
            "$Delta;" + "$diams;" + "$divide;" + "$eacute;" + "$Eacute;" + "$ecirc;" + "$Ecirc;" + "$egrave;" +
            "$Egrave;" + "$empty;" + "$emsp;" + "$ensp;" + "$epsilon;" + "$Epsilon;" + "$equiv;" + "$eta;" +
            "$Eta;" + "$eth;" + "$ETH;" + "$euml;" + "$Euml;" + "$euro;" + "$exist;" + "$fnof;" +
            "$forall;" + "$frac12;" + "$frac14;" + "$frac34;" + "$frasl;" + "$gamma;" + "$Gamma;" + "$ge;" +
            "$gt;" + "$harr;" + "$hArr;" + "$hearts;" + "$hellip;" + "$iacute;" + "$Iacute;" + "$icirc;" +
            "$Icirc;" + "$iexcl;" + "$igrave;" + "$Igrave;" + "$image;" + "$infin;" + "$int;" + "$iota;" +
            "$Iota;" + "$iquest;" + "$isin;" + "$iuml;" + "$Iuml;" + "$kappa;" + "$Kappa;" + "$lambda;" +
            "$Lambda;" + "$lang;" + "$laquo;" + "$larr;" + "$lArr;" + "$lceil;" + "$ldquo;" + "$le;" +
            "$lfloor;" + "$lowast;" + "$loz;" + "$lrm;" + "$lsaquo;" + "$lsquo;" + "$lt;" + "$macr;" +
            "$mdash;" + "$micro;" + "$middot;" + "$minus;" + "$mu;" + "$Mu;" + "$nabla;" + "$nbsp;" +
            "$ndash;" + "$ne;" + "$ni;" + "$not;" + "$notin;" + "$nsub;" + "$ntilde;" + "$Ntilde;" +
            "$nu;" + "$Nu;" + "$oacute;" + "$Oacute;" + "$ocirc;" + "$Ocirc;" + "$oelig;" + "$OElig;" +
            "$ograve;" + "$Ograve;" + "$oline;" + "$omega;" + "$Omega;" + "$omicron;" + "$Omicron;" + "$oplus;" +
            "$or;" + "$ordf;" + "$ordm;" + "$oslash;" + "$Oslash;" + "$otilde;" + "$Otilde;" + "$otimes;" +
            "$ouml;" + "$Ouml;" + "$para;" + "$part;" + "$permil;" + "$perp;" + "$phi;" + "$Phi;" +
            "$pi;" + "$Pi;" + "$piv;" + "$plusmn;" + "$pound;" + "$prime;" + "$Prime;" + "$prod;" +
            "$prop;" + "$psi;" + "$Psi;" + "$quot;" + "$radic;" + "$rang;" + "$raquo;" + "$rarr;" +
            "$rArr;" + "$rceil;" + "$rdquo;" + "$real;" + "$reg;" + "$rfloor;" + "$rho;" + "$Rho;" +
            "$rlm;" + "$rsaquo;" + "$rsquo;" + "$sbquo;" + "$scaron;" + "$Scaron;" + "$sdot;" + "$sect;" +
            "$shy;" + "$sigma;" + "$Sigma;" + "$sigmaf;" + "$sim;" + "$spades;" + "$sub;" + "$sube;" +
            "$sum;" + "$sup;" + "$sup1;" + "$sup2;" + "$sup3;" + "$supe;" + "$szlig;" + "$tau;" +
            "$Tau;" + "$there4;" + "$theta;" + "$Theta;" + "$thetasym;" + "$thinsp;" + "$thorn;" + "$THORN;" +
            "$tilde;" + "$times;" + "$trade;" + "$uacute;" + "$Uacute;" + "$uarr;" + "$uArr;" + "$ucirc;" +
            "$Ucirc;" + "$ugrave;" + "$Ugrave;" + "$uml;" + "$upsih;" + "$upsilon;" + "$Upsilon;" + "$uuml;" +
            "$Uuml;" + "$weierp;" + "$xi;" + "$Xi;" + "$yacute;" + "$Yacute;" + "$yen;" + "$yuml;" +
            "$Yuml;" + "$zeta;" + "$Zeta;" + "$zwj;" + "$zwnj;", 1000));
    }
}
```
I get this before the change:
```
 Method |     Mean |     Error |    StdDev |   Median |
------- |---------:|----------:|----------:|---------:|
 Decode | 1.275 ms | 0.0268 ms | 0.0583 ms | 1.242 ms |
```
and this after:
```
 Method |     Mean |     Error |    StdDev |
------- |---------:|----------:|----------:|
 Decode | 1.245 ms | 0.0189 ms | 0.0177 ms |
```

**Comment by ViktorHofer** [comment]
> Which benchmarks in particular are you concerned with?

All which are affected by this change.

> so as far as I can tell, there's no regression here

Thanks a lot.

**Comment by ViktorHofer** [comment]
Reminder: If/when we migrate to BDN we probably want to add this test.

**Comment by stephentoub** [comment]
> All which are affected by this change.

And which are those?  Seriously.  Are there any that touch these code paths?  I don't believe so.

**Comment by stephentoub** [comment]
@dotnet/dnceng, @mmitche, legs here again appear to be stuck processing xunit results, e.g.
```
[Windows.10.Amd64.ClientRS2.Open - x86 - Release (fe2ca341-14f6-43ce-9119-8dce032bd1c2)] Response Code: HTTP/1.1 200 OK
[Windows.10.Amd64.ClientRS2.Open - x86 - Release (fe2ca341-14f6-43ce-9119-8dce032bd1c2)] Response: 
[Windows.10.Amd64.ClientRS2.Open - x86 - Release (fe2ca341-14f6-43ce-9119-8dce032bd1c2)] [{"Key":{"job.name":"fe2ca341-14f6-43ce-9119-8dce032bd1c2"},"Data":{"Analysis":[{"Name":"xunit","Status":{"pass":250713,"passonretry":0,"fail":0,"skip":1336}}],"WorkItemStatus":{"pass":205,"none":1}}}]
[Windows.10.Amd64.ClientRS2.Open - x86 - Release (fe2ca341-14f6-43ce-9119-8dce032bd1c2)] Success code from [100‥399]
[Pipeline] [Windows.10.Amd64.ClientRS2.Open - x86 - Release (fe2ca341-14f6-43ce-9119-8dce032bd1c2)] echo
[Windows.10.Amd64.ClientRS2.Open - x86 - Release (fe2ca341-14f6-43ce-9119-8dce032bd1c2)] Info: Processing XUnit Results: 1 remaining
[Pipeline] [Windows.10.Amd64.ClientRS2.Open - x86 - Release (fe2ca341-14f6-43ce-9119-8dce032bd1c2)] }
[Windows.10.Amd64.ClientRS2.Open - x86 - Release (fe2ca341-14f6-43ce-9119-8dce032bd1c2)] Will try again after 5 min 0 sec
```

**Comment by ViktorHofer** [comment]
I don't think there are any. When I said "have you double checked with benchmarks?" I meant if you either run existing ones or if there weren't any if you wrote one to make sure there's no regression. Sorry for the confusion 🤔

**Comment by stephentoub** [comment]
Ok. Thanks.

**Comment by morganbr** [comment]
I believe some of the CoreLib cases also affect the size of .NET Native binaries, so it would be good to confirm there's no significant expansion if you change those.

**Comment by mmitche** [comment]
@stephentoub we're still having issues with the OSX machines: https://github.com/dotnet/core-eng/issues/3391
/cc @Chrisboh

**Comment by jkotas** [comment]
> I believe some of the CoreLib cases also affect the size of .NET Native binaries, so it would be good to confirm there's no significant expansion if you change those.

I have tried that earlier and had to roll it back: https://github.com/dotnet/corert/pull/5234 . It did not even work because of it introduced cycles somewhere.

**Comment by stephentoub** [comment]
@mmitche, this isn't just macOS.

**Comment by stephentoub** [comment]
@mmitche, @dotnet/dnceng, the netfx leg has been going for 9 hours 30 minutes and ends with this:
```
20:59:17 [Windows.10.Amd64.ClientRS2.Open - x86 - Release (fe2ca341-14f6-43ce-9119-8dce032bd1c2)] Response Code: HTTP/1.1 200 OK
20:59:17 [Windows.10.Amd64.ClientRS2.Open - x86 - Release (fe2ca341-14f6-43ce-9119-8dce032bd1c2)] Response: 
20:59:17 [Windows.10.Amd64.ClientRS2.Open - x86 - Release (fe2ca341-14f6-43ce-9119-8dce032bd1c2)] [{"Key":{"job.name":"fe2ca341-14f6-43ce-9119-8dce032bd1c2"},"Data":{"Analysis":[{"Name":"xunit","Status":{"pass":250713,"passonretry":0,"fail":0,"skip":1336}}],"WorkItemStatus":{"pass":205,"none":1}}}]
20:59:17 [Windows.10.Amd64.ClientRS2.Open - x86 - Release (fe2ca341-14f6-43ce-9119-8dce032bd1c2)] Success code from [100‥399]
[Pipeline] [Windows.10.Amd64.ClientRS2.Open - x86 - Release (fe2ca341-14f6-43ce-9119-8dce032bd1c2)] echo
20:59:17 [Windows.10.Amd64.ClientRS2.Open - x86 - Release (fe2ca341-14f6-43ce-9119-8dce032bd1c2)] Info: Processing XUnit Results: 1 remaining
[Pipeline] [Windows.10.Amd64.ClientRS2.Open - x86 - Release (fe2ca341-14f6-43ce-9119-8dce032bd1c2)] }
20:59:17 [Windows.10.Amd64.ClientRS2.Open - x86 - Release (fe2ca341-14f6-43ce-9119-8dce032bd1c2)] Will try again after 5 min 0 sec
```
Similarly the Windows x64 Debug leg has been going for over 9 hours and ends with:
```
[Windows.10.Nano.Amd64.Open - x64 - Debug (ac25e449-3190-41e6-9a04-a29ca7caaf8f)] Response Code: HTTP/1.1 200 OK
[Windows.10.Nano.Amd64.Open - x64 - Debug (ac25e449-3190-41e6-9a04-a29ca7caaf8f)] Response: 
[Windows.10.Nano.Amd64.Open - x64 - Debug (ac25e449-3190-41e6-9a04-a29ca7caaf8f)] [{"Key":{"job.name":"ac25e449-3190-41e6-9a04-a29ca7caaf8f"},"Data":{"Analysis":[{"Name":"xunit","Status":{"pass":282735,"passonretry":0,"fail":0,"skip":3254}}],"WorkItemStatus":{"pass":252,"none":1}}}]
[Windows.10.Nano.Amd64.Open - x64 - Debug (ac25e449-3190-41e6-9a04-a29ca7caaf8f)] Success code from [100‥399]
[Pipeline] [Windows.10.Nano.Amd64.Open - x64 - Debug (ac25e449-3190-41e6-9a04-a29ca7caaf8f)] echo
[Windows.10.Nano.Amd64.Open - x64 - Debug (ac25e449-3190-41e6-9a04-a29ca7caaf8f)] Info: Processing XUnit Results: 1 remaining
[Pipeline] [Windows.10.Nano.Amd64.Open - x64 - Debug (ac25e449-3190-41e6-9a04-a29ca7caaf8f)] }
[Windows.10.Nano.Amd64.Open - x64 - Debug (ac25e449-3190-41e6-9a04-a29ca7caaf8f)] Will try again after 5 min 0 sec
```

**Comment by Chrisboh** [comment]
Sorry for the slow response @stephentoub we are a bit shorthanded this week.  @jcagme is looking into this now https://github.com/dotnet/core-eng/issues/3151

**Comment by stephentoub** [comment]
Thanks, @Chrisboh.

**Pull request merged**
