### PR TITLE
Fix SocketsHttpHandler proxy auth for 'Negotiate' scheme

### LINKED ISSUE #39887: WebClient http proxy broken in .Net Core 3 Preview 7
I am using WebClient and HttpWebRequest to call external Http APIs and is dependent on a proxy to make external calls. After upgrading to .Net Core Preview 7 I get Proxy authentication error (407). The code runs ok in .Net Core 2.1, and .Net Core 3 preview 3. 

This is a snippet that 
succeeds on .Net Core 2.1 & 3.0 preview 3 
but fails on preview 7, 
running in  Visual Studio 2019 16.2.0:

```c#
            string proxy = <_name of Proxy_>;
            string url = "https://www.kemi.se/global/faktablad/faktablad-om-sakerhetsdatablad.pdf";
            var client = new WebClient() {
                Proxy = new WebProxy(proxy, 8080) {
                    UseDefaultCredentials = true
                }
            };
            var data = client.DownloadData(url);
```

### PR DESCRIPTION
**Pull request by davidsh**
Issue #39887 reported that proxy authentication with 'Negotiate' scheme broke between
.NET Core 3.0 Preview 6 and Preview 7. The base64 blob was no longer using SPNEGO protocol
but instead was always using NTLM. While 'Negotiate' scheme can use either SPNEGO or NTLM,
it should always use SPNEGO if possible. And many enterprises have a setting which requires
it and rejects NTLM protocol.

This issue was caused by PR #38465 which fixed some other SPN issues with Kerberos
authentication. That PR regressed the SPN calculation for the proxy authentication by
using the wrong host name in the SPN. A mismatch of the SPN will cause NTLM to be used
instead of SPNEGO.

The fix is to check if proxy authentication is being used instead of server authentication.
If so, it ignores any 'Host' header and always will use the uri, which in this case is the
uri of the proxy server.

This was tested manually. It is impossible right now to test Kerberos and proxy scenarios in
CI because they require machine configuration to register SPNs in a Windows Active Directory
environment.

This PR will be ported for release/3.0 for ASK mode consideration since it affects a mainline
enterprise scenario.

Fixes #39887

### CODE REVIEW

**Comment by davidsh** [comment]
>Could we add test? (can be done post 3.0)

I am thinking about how to write a test for this. It would build on the work done in these tests
https://github.com/dotnet/corefx/blob/06d215d9fe6fff08f81add5ed341641f668075c0/src/System.Net.Http/tests/FunctionalTests/HttpClientHandlerTest.Authentication.cs#L519-L528
where they run only if running in a Windows ActiveDirectory environment.  The trick is to have a proxy server that can report whether SPNEGO or NTLM tokens were used for authentication and then we can test against that. I have a proxy server I wrote that I'm working on to support that.

**Comment by wfurt** [comment]
I know this is tricky. But in this case all we need to do is to verify that correct mechanism was selected, right?

**Comment by davidsh** [comment]
>I know this is tricky. But in this case all we need to do is to verify that correct mechanism was selected, right?

Thanks for the feedback. I was able to write a new test that builds on the existing set of tests we have that can run in a domain joined environment (when enabled via the required environment variables).

**Pull request merged**
