### PR TITLE
Remove appveyor CI links, making Jenkins the primary CI system.

### PR DESCRIPTION
**Pull request by mmitche**
Test to check Jenkins PR functionality.

### CODE REVIEW

**Comment by mmitche** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://corefx-ci.cloudapp.net/jenkins/job/CoreFX_Windows_Build/86/
Test PASSed.

**Comment by mmitche** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://corefx-ci.cloudapp.net/jenkins/job/CoreFX_Windows_Build/87/
Test PASSed.

**Comment by sharwell** [comment]
@mmitche Those automated comments are going to get quite annoying in a hurry. They are filling up my GitHub news feed. Is there *any* other approach you can take to include the information within the pull request UI? Possibilities include:

1. Use a check, like the **continuous-integration/appveyor** and **default** checks that appear currently.
2. Use a separate user account for the feedback. Individual users can be "muted" by visiting their profile, but it's only usable if a dedicated account is the one reporting the results. It would be especially helpful if different users were available for the PASS and FAIL results, so PASS could be muted while FAIL left unmuted.

**Comment by mmitche** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://corefx-ci.cloudapp.net/jenkins/job/CoreFX_Linux_Build/88/
Test FAILed.

**Comment by akoeplinger** [comment]
@sharwell The "default" check already comes from Jenkins (the Jenkins GitHub plugin doesn't support setting a proper title yet), so I think @mmitche could just disable the commenting which I find annoying too.

**Comment by mmitche** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://corefx-ci.cloudapp.net/jenkins/job/dotnet_corefx_linux_buildonly_prtest/1/
Test PASSed.

**Comment by mmitche** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://corefx-ci.cloudapp.net/jenkins/job/dotnet_corefx_windows_prtest/1/
Test PASSed.

**Comment by mmitche** [comment]
@sharwell - I'm trying to remove the comments.  The user should eventually not be me (should be dotnet-bot), but there is a snafu with that right now.

**Comment by mmitche** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://corefx-ci.cloudapp.net/jenkins/job/dotnet_corefx_windows_prtest/2/

**Comment by mmitche** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://corefx-ci.cloudapp.net/jenkins/job/dotnet_corefx_linux_buildonly_prtest/2/

**Comment by mmitche** [comment]
Okay I think that does it.  Removing the published URL appears to remove the comments.

**Pull request merged**
