### PR TITLE
[release/3.1] Add Fedora 35 RID

### PR DESCRIPTION
**Pull request by omajid**
Fedora rawhide now uses the fedora.35-x64 RID:

    $ podman run -it registry.fedoraproject.org/fedora:rawhide /bin/bash -c 'cat /etc/os-release'
    NAME=Fedora
    VERSION="35 (Container Image Prerelease)"
    ID=fedora
    VERSION_ID=35
    VERSION_CODENAME=""
    PLATFORM_ID="platform:f35"
    PRETTY_NAME="Fedora 35 (Container Image Prerelease)"
    ANSI_COLOR="0;38;2;60;110;180"
    LOGO=fedora-logo-icon
    CPE_NAME="cpe:/o:fedoraproject:fedora:35"
    HOME_URL="https://fedoraproject.org/"
    DOCUMENTATION_URL="https://docs.fedoraproject.org/en-US/fedora/rawhide/system-administrators-guide/"
    SUPPORT_URL="https://fedoraproject.org/wiki/Communicating_and_getting_help"
    BUG_REPORT_URL="https://bugzilla.redhat.com/"
    REDHAT_BUGZILLA_PRODUCT="Fedora"
    REDHAT_BUGZILLA_PRODUCT_VERSION=rawhide
    REDHAT_SUPPORT_PRODUCT="Fedora"
    REDHAT_SUPPORT_PRODUCT_VERSION=rawhide
    PRIVACY_POLICY_URL="https://fedoraproject.org/wiki/Legal:PrivacyPolicy"
    VARIANT="Container Image"
    VARIANT_ID=container

This is a backport of https://github.com/dotnet/runtime/pull/48200.

### CODE REVIEW

**Review by ViktorHofer — COMMENTED** [review]
@Anipik same question about if the PR is complete in it's current state.

**Review by Anipik — CHANGES_REQUESTED** [review]
can you add the packageindex changes here as well

**Review by Anipik — APPROVED** [review]

**Comment by aik-jahoda** [comment]
@Anipik , do we need service approval for this change?

**Comment by omajid** [comment]
AFAIK, RID updates are tell-mode.

**Comment by ViktorHofer** [comment]
Yes and we already communicated the change to Tactics.

**Pull request merged**
