### PR TITLE
Remove FEATURE_ETLEVENTS conditional compilation

### LINKED ISSUE #19624: Remove conditional compilation in System.Diagnostics.Tracing
As discussed offline with @vancem, we should remove conditional compilation which was introduced in PR https://github.com/dotnet/corefx/pull/18427 when these APIs will be available in NS21:

```
public abstract partial class EventListener : System.IDisposable 
{ 
    protected internal virtual void OnEventWritten(System.Diagnostics.Tracing.EventWrittenEventArgs eventData) { }
}
public class EventSourceCreatedEventArgs : EventArgs 
{ 
    public EventSourceCreatedEventArgs() { } 
    public EventSource EventSource { get; } 
} 
```

cc @brianrob

### PR DESCRIPTION
**Pull request by laurentkempe**
Fixes #19624

### CODE REVIEW

**Comment by ViktorHofer** [comment]
@dotnet-bot test OSX x64 Debug Build

**Comment by laurentkempe** [comment]
@ViktorHofer it seems to me that the failed build wasn't linked with my change

**Comment by ViktorHofer** [comment]
I pushed a commit to your PR to remove some obsolete constants and references here. cc @brianrob

**Comment by ViktorHofer** [comment]
Thanks a lot for your help @laurentkempe 👍

**Comment by brianrob** [comment]
Thanks very much @laurentkempe and @ViktorHofer!

**Pull request merged**
