### PR TITLE
[release/2.0.0] Fix Desktop app-compat issues with System.Web.HttpUtility

### LINKED ISSUE #23574: HttpUtility.ParseQueryString incorrect if first item's name begins with a question mark
If a query-string's first name-value pair begins with a question mark then the initial question mark is stripped twice, so the name in the parsed collection is incorrect.

E.g. with `??name=value&x=y` the result is a collection where `["name"] == "value"` while if it isn't the first element, as in `?x=y&?name=value` then it has the correct result of `["?name"] == "value"`

### LINKED ISSUE #23582: HttpUtility.ParseQueryString does HTML decoding first on CoreFX, but not on NetFX
The version of `HttpUtility.ParseQueryString` in CoreFX does HTML decoding first, differing from desktop:

```C#
HttpUtility.ParseQueryString("name=value&amp;name2=value2").ToString()
// name=value&amp%3bname2=value2 on Desktop
// name=value&name2=value2 on CoreFX

HttpUtility.ParseQueryString("?name=valu&#xe9;")["name"]
// valu on Desktop
// valué on CoreFX
```

#23573 is a knock-on effect of this. (Closing as such).
#23574 is an indirect knock-on effect in that ? is stripped both before and after HTML decoding that shouldn't be done at all.

### PR DESCRIPTION
**Pull request by JonHanna**
Fixes #23582, fixes #23574

Port of commits from #23591.

### CODE REVIEW

**Comment by davidsh** [comment]
Windows CI failures in unrelated components:
System.Globalization.Tests.IdnMappingIdnaConformanceTests.GetAscii_Invalid [FAIL]

**Comment by karelz** [comment]
Thanks @davidsh for fast turnaround! cc @DavidGoll

**Comment by JonHanna** [comment]
Is that a known issue in the CI with 2.0, and hence not worth triggering another test?

**Comment by davidsh** [comment]
@dotnet-bot Test Innerloop Windows_NT Debug x86 Build and Test
@dotnet-bot Test Innerloop Windows_NT Release x64 Build and Test

**Comment by davidsh** [comment]
>Is that a known issue in the CI with 2.0, and hence not worth triggering another test?

Not sure.  But those failures won't affect merging this after shiproom approval.

**Comment by stephentoub** [comment]
> Is that a known issue in the CI with 2.0

Yes

> Port of commits from #23591.

I'm late to the party here... can someone help me understand how the implementation diverged so much from what's in reference source?  Do we know there aren't other differences lurking?

**Comment by davidsh** [comment]
>I'm late to the party here... can someone help me understand how the implementation diverged so much from what's in reference source? Do we know there aren't other differences lurking?

My guess is that there are other differences lurking.  I don't know why the source wasn't ported as-is from .NET Framework.  @alexperovich might know.

**Comment by danmosemsft** [comment]
@dotnet-bot Test Innerloop Windows_NT Debug x86 Build and Test
@dotnet-bot Test Innerloop Windows_NT Release x64 Build and Test (idna fixed now)

**Comment by karelz** [comment]
Digging into the divergence - we took [Mono source code](https://github.com/mono/mono/blob/0af1ea70c29a66a59765183b45d6b75fa6c3d8fa/mcs/class/System.Web/System.Web/HttpUtility.cs#L622-L667) and test cases during the .NET Standard 2.0 porting effort, likely because the [Desktop source code](http://referencesource.microsoft.com/#System.Web/HttpValueCollection.cs,222f9a1bfd1f9a98) is a bit uglier and involves unnecessary internal type.

BTW: We forgot to add the Mono license line in the source code and tests. We should fix that.

**Comment by karelz** [comment]
@stephentoub can you please review the code?

**Comment by weshaggard** [comment]
test Innerloop Ubuntu14.04 Debug x64 Build and Test
test Innerloop Ubuntu14.04 Release x64 Build and Test

**Comment by karelz** [comment]
@weshaggard FYI: All tests passed before I submitted the comment-only change with copyright from Mono. We don't have to block on another green CI IMO.

**Comment by karelz** [comment]
@JonHanna thanks a LOT for your help here - discovering the issue, fixing it & porting into 2.0.x servicing branch. I really appreciate your dedication here!

**Pull request merged**
