### PR TITLE
Marking code as unchecked (pt 7)

### PR DESCRIPTION
**Pull request by dennisdietrich**
Marking code that may intentionally lead to over or underflows with
unchecked in preparation of turning on CheckForOverflowUnderflow for
all projects (issue #3140)

### CODE REVIEW

**Comment by dennisdietrich** [comment]
Huh. Don't think that failure has anything to do with my changes:
```
Assert.Throws() Failure
Expected: typeof(System.TimeoutException)
Actual:   typeof(Xunit.Sdk.EqualException): Assert.Equal() Failure
Expected: ::1
Actual:   ::ffff:127.0.0.1
Stack Trace:
   /mnt/j/workspace/dotnet_corefx/master/ubuntu14.04_debug_prtest/src/System.Net.Sockets/tests/FunctionalTests/DualModeSocketTest.cs(1652,0): at System.Net.Sockets.Tests.DualModeConnectionlessBeginReceiveFrom.BeginReceiveFrom_Helper(IPAddress listenOn, IPAddress connectTo, Boolean expectedToTimeout)
   /mnt/j/workspace/dotnet_corefx/master/ubuntu14.04_debug_prtest/src/System.Net.Sockets/tests/FunctionalTests/DualModeSocketTest.cs(1610,0): at System.Net.Sockets.Tests.DualModeConnectionlessBeginReceiveFrom.<BeginReceiveFromV6BoundToAnyV4_NotReceived>b__9_0()
```

**Comment by danmosemsft** [comment]
@steveharter @zhenlan @Priya91 crypto., serialization,. process.

**Comment by zhenlan** [comment]
cc: @shmao @mconnew

**Comment by tarekgh** [comment]
test Innerloop Ubuntu14.04 Debug Build and Test please

**Comment by tarekgh** [comment]
@dennisdietrich the socket failure looks tracked with the issue https://github.com/dotnet/corefx/issues/4002 so I don't think it is related to your change

**Comment by tarekgh** [comment]
I have reviewed the changes and LGTM. I am merging it but if anyone has any comment we can address it in other PR. Thanks.

**Pull request merged**
