### PR TITLE
Avoid race condition between queued HttpContent.CopyToAsync and request completion

### PR DESCRIPTION
**Pull request by stephentoub**
HttpContentAsyncStream is used by CurlHandler as the request content stream, with writes to it done via HttpContent.CopyToAsync.  We expect the writes to all be asynchronous via WriteAsync. However, it's possible for an override of CopyToAsync to use Write, and if it does, and if we just delegated from Write(...) to WriteAsync(...).GetAwaiter().GetResult(), we would likely deadlock, as the CopyToAsync call is invoked from the single thread responsible for processing libcurl interactions, including supplying the reader that would unblock the writer. To handle this, we have two options: schedule the CopyToAsync to be invoked asynchronously just in case it does a synchronous write, or implement the write to buffer the data.

The former is what was done in https://github.com/dotnet/corefx/pull/4095.  It adds some cost to the expected / common case, but more importantly and worse it can also lead to concurrency problems and spurious exceptions, as for example if the request is faulted/canceled between the time that a task to invoke CopyToAsync is scheduled and the time that it actually executes, we could be invoking CopyToAsync on a disposed HttpContent; worse, we could
end up invoking CopyToAsync while it's being disposed, which could lead to arbitrary state corruption, and which means we can't guard against this with checks to see if the task has already completed.  The only way to fully guard against that is via a lock, but such a lock would itself lead to deadlocks, as the reader that would unblock the writer would have to take the same lock.

In comparison, buffering has the downside of taking up more and arbitrary amounts of memory to store all of the input.  But, we expect synchronous Writes to be rare, and code shouldn't be doing it anyway; if it does, the fix should really be to switch to asynchronous writes. This commit changes from the first approach to the second, using buffering in synchronous Write calls in order to ensure correctness and to optimize for the expected case.

@mconnew, @roncain, this all originally started from https://github.com/dotnet/corefx/issues/4077.  Is WCF still doing such synchronous writes as part of HttpContent.CopyToAsync?  If so, is this change going to cause a problem for that?  We're between a rock and a hard place given the design of HttpClient.

Fixes https://github.com/dotnet/corefx/issues/8113 (I think; I couldn't actually reproduce it in the successful case mentioned)
cc: @davidsh, @ericeil, @kapilash

### CODE REVIEW

**Comment by davidsh** [comment]
I'm not a Curl expert, so I can't really comment much on the implementation.

It terms of the intent, LGTM:
>This commit changes from the first approach to the second, using buffering in synchronous Write calls in order to ensure correctness and to optimize for the expected case.

That is good. We should expect more devs to write async patterns and only have this logic kick in if we have sync calls in the CopyToAsync() overload.

**Comment by stephentoub** [comment]
Test Innerloop OSX Release Build and Test please

**Comment by stephentoub** [comment]
Thanks, David.

**Comment by ericeil** [comment]
Looks good.

**Comment by stephentoub** [comment]
@mconnew, @roncain, could you comment on any impact this might have for WCF?  Has WCF fixed the cases where it would synchronously invoke Write from CopyToAsync?

**Pull request merged**
