### PR TITLE
Disable sporadically failing GetGCMemoryInfo test

### PR DESCRIPTION
**Pull request by stephentoub**
cc: @luhenry, @ViktorHofer 
https://github.com/dotnet/corefx/issues/37378

### CODE REVIEW

**Comment by ViktorHofer** [comment]
Lgtm

**Comment by VSadov** [comment]
Any chance to know which exactly `InRange` check was failing?   (line 56 from the stack trace does not seem to map to anything..)

**Comment by stephentoub** [comment]
> Any chance to know which exactly InRange check was failing?

Probably not from the existing failures.  You could augment the test to output more details and re-enable it to get another hit.

**Comment by VSadov** [comment]
I was hoping anyone remembers ;)

**Pull request merged**
