### PR TITLE
fix HtmlEncoder issue

### PR DESCRIPTION
**Pull request by ChangweiZhang**
more detail about this issue, please read: https://github.com/dotnet/corefx/issues/11844

### CODE REVIEW

**Comment by stephentoub** [comment]
cc: @KrzysztofCwalina 

Several tests are failing as a result of this change:
```
Microsoft.Framework.WebEncoders.HtmlEncoderTests.Default_EquivalentToBasicLatin [FAIL]
        Assert.Equal() Failure
                  ↓ (pos 0)
        Expected: &#xA1;
        Actual:   ¡
                  ↑ (pos 0)
        Stack Trace:
           D:\j\workspace\windows_nt_de---4526f5ff\src\System.Text.Encodings.Web\tests\HtmlEncoderTests.cs(84,0): at Microsoft.Framework.WebEncoders.HtmlEncoderTests.Default_EquivalentToBasicLatin()
     Microsoft.Framework.WebEncoders.HtmlEncoderTests.Ctor_WithNoParameters_DefaultsToBasicLatin [FAIL]
        Assert.Equal() Failure
                  ↓ (pos 0)
        Expected: &#xE9;
        Actual:   é
                  ↑ (pos 0)
        Stack Trace:
           D:\j\workspace\windows_nt_de---4526f5ff\src\System.Text.Encodings.Web\tests\HtmlEncoderTests.cs(67,0): at Microsoft.Framework.WebEncoders.HtmlEncoderTests.Ctor_WithNoParameters_DefaultsToBasicLatin()

Microsoft.Framework.WebEncoders.JavaScriptStringEncoderTests.Ctor_WithNoParameters_DefaultsToBasicLatin [FAIL]
        Assert.Equal() Failure
                  ↓ (pos 0)
        Expected: \u00E9
        Actual:   é
                  ↑ (pos 0)
        Stack Trace:
           D:\j\workspace\windows_nt_de---4526f5ff\src\System.Text.Encodings.Web\tests\JavaScriptStringEncoderTests.cs(67,0): at Microsoft.Framework.WebEncoders.JavaScriptStringEncoderTests.Ctor_WithNoParameters_DefaultsToBasicLatin()
     Microsoft.Framework.WebEncoders.JavaScriptStringEncoderTests.Default_EquivalentToBasicLatin [FAIL]
        Assert.Equal() Failure
                  ↓ (pos 0)
        Expected: \u00A1
        Actual:   ¡
                  ↑ (pos 0)
        Stack Trace:
           D:\j\workspace\windows_nt_de---4526f5ff\src\System.Text.Encodings.Web\tests\JavaScriptStringEncoderTests.cs(84,0): at Microsoft.Framework.WebEncoders.JavaScriptStringEncoderTests.Default_EquivalentToBasicLatin()
```

**Comment by KrzysztofCwalina** [comment]
@GrabYourPitchforks, @blowdart, @Eilon, are you ok with this change? I thought the idea was that the default encoders were very conservative.

**Comment by blowdart** [comment]
No I'm not. They are conservative by default, and are configurable too. We documented the configuration steps at https://docs.asp.net/en/latest/security/cross-site-scripting.html#customizing-the-encoders

Once we start accepting one code page it will never stop, until all code pages are safe listed, thus doing away with the whole security advantage of the safe list approach. 

This needs to be an application level decision. Please reject.

@ChangweiZhang what's wrong with configuring them?

**Comment by GrabYourPitchforks** [comment]
Should also ask what the "error page" referenced in the bug report means. It's perfectly legitimate from an HTML perspective to encode every single character, even latin alphanumeric characters. The browser will render the page correctly.

**Comment by Eilon** [comment]
@GrabYourPitchforks I think it's a "translation" issue. So not an "error" per se, but rather an "undesirable result."

**Comment by stephentoub** [comment]
@ChangweiZhang, thanks both for opening the issue and submitting a potential fix.  From the discussion both here and there, it looks like this is by design, and as such the plan is to close the PR.  Do you have any remaining concerns?

**Pull request closed without merging**
