### PR TITLE
Another 556 System.Runtime.Test failures down.

### PR DESCRIPTION
**Pull request by AtsushiKan**
No more "Multidimensional arrays of rank 1 are not supported..."

### CODE REVIEW

**Comment by AtsushiKan** [comment]
@dotnet-bot test Innerloop Ubuntu14.04 arm Release Cross Build

**Comment by danmosemsft** [comment]
Can you include the pN bug number for the fix?

**Comment by AtsushiKan** [comment]
I don't think there's a Pn bug # since I haven't heard any indication we ever expect to support non-zero bounds in arrays.

@davidwr, can you confirm or deny?

**Comment by danmosemsft** [comment]
@davidwrighton  is the correct person

**Pull request merged**
