### PR TITLE
Fix build exit code

### PR DESCRIPTION
**Pull request by weshaggard**
This should fix issue #942. Initially I included a commit that introduces a failed test to verify CI fails. Once I verify that I will remove that commit and verify the build succeeds before merging.

### CODE REVIEW

**Comment by joshfree** [comment]
looks good; I'll wait to see the intentional failure.

**Comment by mmitche** [comment]
LGTM

**Comment by stephentoub** [comment]
Seems to have failed as expected. LGTM.

**Comment by weshaggard** [comment]
Failed as expected http://dotnet-ci.cloudapp.net/job/dotnet_corefx_prtest/145/ and we still got test results for the other tests which is what I was originally trying to fix.

**Comment by weshaggard** [comment]
I removed the test failure now so as long as this succeeds we should be good to merge.

**Comment by stephentoub** [comment]
Though it looked like there was actually a failure beyond the one introduced... maybe it's been hiding behind this?

MESSAGE:
Error, returned wrong item for uppercase key
+++++++++++++++++++
STACK TRACE:
at System.Collections.Specialized.Tests.GetItemObjTests.Test01() in d:\j\workspace\dotnet_corefx_windows_release_prtest\src\System.Collections.Specialized\tests\HybridDictionary\GetItemObjTests.cs:line 357

**Comment by krwq** [comment]
LGTM

**Comment by weshaggard** [comment]
@stephentoub interesting I didn't see that one locally. Perhaps it is an intermittent failure. I will look into it further if the CI fails again.

**Comment by weshaggard** [comment]
@stephentoub It didn't fail again this time so it looks intermittent, we will just need to keep an eye out for it.

**Pull request merged**
