### PR TITLE
Binary serialization is supported

### PR DESCRIPTION
**Pull request by danmosemsft**
@terrajobst please review.

### CODE REVIEW

**Comment by danmosemsft** [comment]
@dotnet-bot help

**Comment by danmosemsft** [comment]
@mmitche is there a magic command like "@dotnet-bot skip CI" that I can use in my initial PR to avoid wasting CI resources unnecessarily? This is a doc only change.

**Comment by stephentoub** [comment]
> is there a magic command like "@dotnet-bot skip CI" that I can use in my initial PR to avoid wasting CI resources unnecessarily?

I believe you can put "skip ci please" in the PR description.

**Comment by mellinoe** [comment]
I think we should clarify that this section is only talking about `BinaryFormatter`. There are a variety of other binary serialization libraries which already support .NET Core 1.0, and already don't have some of the restrictions mentioned here.

**Comment by mmitche** [comment]
Comment skip ci please in the initial pr comment.

Sent from my iPhone

On Nov 16, 2016, at 1:06 PM, Dan Moseley <notifications@github.com<mailto:notifications@github.com>> wrote:


@mmitche<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fmmitche&data=02%7C01%7Cmmitche%40microsoft.com%7Cfa0e7a53e39645914fbe08d40e6466ea%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C636149271769297894&sdata=nBNu6OBYhl%2FCCM5gxx5FFFJ0ZHZI%2FT9KI4ByTQWDOY8%3D&reserved=0> is there a magic command like "@dotnet-bot<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fdotnet-bot&data=02%7C01%7Cmmitche%40microsoft.com%7Cfa0e7a53e39645914fbe08d40e6466ea%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C636149271769297894&sdata=efctrxFnL%2B6ljBfxk1q3Um7h1%2BMoDgClE8N8FAIsi5U%3D&reserved=0> skip CI" that I can use in my initial PR to avoid wasting CI resources unnecessarily? This is a doc only change.

-

**Pull request merged**
