### PR TITLE
Update to buildtools 144, Fix x-plat build breaks

### PR DESCRIPTION
**Pull request by mellinoe**
Includes three changes since 142 (current version):

https://github.com/dotnet/buildtools/commit/a9cf8da8270218d66cb59cdc8b9604127aef5da1
https://github.com/dotnet/buildtools/commit/e3209b29c3fbb6e112987aabb9712acc5d8e9851
https://github.com/dotnet/buildtools/commit/4f9a9ee485350c0c13f140d8192e55a222c5539e

This should fix some of the issues encountered when building x-plat (part of #5199). Partial facades targeting net46 should now build properly.

Also, I would imagine the build should be marginally faster x-plat because I've deleted the fall-back target that restored NuGet packages in order to retrieve the contract assembly for GenFacades. So less things should be downloaded there in general.

@weshaggard , @clrjunkie

### CODE REVIEW

**Comment by mellinoe** [comment]
Note that there are still a few build errors in the Ubuntu build, at least that I am seeing locally:

* There's still a weird VB compiler error that I didn't investigate yet.
* It looks like using the ECMA keys for System.IO.Compression is causing issues on Ubuntu for some reason.

**Comment by stephentoub** [comment]
> Some tests, like Registry, are running against the Windows version of the library

These shouldn't run at all on platforms other than Windows.

**Comment by stephentoub** [comment]
LGTM

**Comment by mellinoe** [comment]
> These shouldn't run at all on platforms other than Windows.
Ah, good point :smile:

**Comment by mellinoe** [comment]
I added an additional commit that fixes the System.IO.Compression build failure. We were setting the <UseECMAKey> property twice, and only one had the correct Condition in it.

**Comment by weshaggard** [comment]
LGTM

**Pull request merged**
