### PR TITLE
Update xunit.netcore.extensions to 1.0.0-prerelease-00187

### PR DESCRIPTION
**Pull request by stephentoub**
cc: @ianhays, @priya91

@ianhays, this will replace part of https://github.com/dotnet/corefx/pull/6522.

### CODE REVIEW

**Comment by stephentoub** [comment]
@chcosta, what feeds are we using now?  I'm trying to move to the latest xunit.netcore.extensions to pick up some changes that were made around the testing attributes.  https://dotnet.myget.org/gallery/dotnet-buildtools shows the latest version as 00182, but the legs are all failing to resolve that.  I see now that https://dotnet.myget.org/gallery/dotnet-core shows the latest version as 00177.  Are we only pulling from the latter?  And if so, how do we get it to have a more recent build?

**Comment by Priya91** [comment]
Thanks @stephentoub

**Comment by chcosta** [comment]
We are only pulling from the latter in corefx.  Currently , any required updates which previously were pulled from dotnet-buildtools need to be manually pushed to dotnet-core.

**Comment by ianhays** [comment]
>We are only pulling from the latter in corefx. Currently , any required updates which previously were pulled from dotnet-buildtools need to be manually pushed to dotnet-core.

@dsgouda FYI

**Comment by dsgouda** [comment]
Thanks @ianhays , @mellinoe  confirmed this for me yesterday.

**Comment by weshaggard** [comment]
@dotnet-bot test this please

**Comment by stephentoub** [comment]
Test Innerloop Windows_NT Release Build and Test

**Pull request merged**
