### PR TITLE
*nix: do not queue completion callbacks for closed sockets.

### LINKED ISSUE #4396: "Called on completed result" assert in Socket APM tests on Linux
http://dotnet-ci.cloudapp.net/job/dotnet_corefx_linux_debug_tst_prtest/4193/console
```
16:36:36 Unhandled Exception: System.Diagnostics.Debug+DebugAssertException: LazyAsyncResult#1978366::set_Result()
16:36:36 Called on completed result.
16:36:36    at System.Environment.GetStackTrace(Exception e, Boolean needFileInfo)
16:36:36    at System.Environment.get_StackTrace()
16:36:36    at System.Diagnostics.Debug.Assert(Boolean condition, String message, String detailMessage)
16:36:36    at System.Net.GlobalLog.Assert(String message, String detailMessage)
16:36:36    at System.Net.GlobalLog.Assert(Boolean condition, String messageFormat, Object[] data)
16:36:36    at System.Net.LazyAsyncResult.set_Result(Object value)
16:36:36    at System.Net.Sockets.BaseOverlappedAsyncResult.CheckAsyncCallOverlappedResult(SocketError errorCode)
16:36:36    at System.Net.Sockets.Socket.DoBeginAccept(Socket acceptSocket, Int32 receiveSize, AcceptOverlappedAsyncResult asyncResult)
16:36:36    at System.Net.Sockets.Socket.BeginAccept(Socket acceptSocket, Int32 receiveSize, AsyncCallback callback, Object state)
16:36:36    at System.Net.Sockets.Socket.BeginAccept(Int32 receiveSize, AsyncCallback callback, Object state)
16:36:36    at System.Net.Sockets.Socket.BeginAccept(AsyncCallback callback, Object state)
16:36:36    at System.Net.Sockets.SocketTaskExtensions.<AcceptAsync>b__0(AsyncCallback callback, Object state)
16:36:36    at System.Threading.Tasks.TaskFactory`1.FromAsyncImpl(Func`3 beginMethod, Func`2 endFunction, Action`1 endAction, Object state, TaskCreationOptions creationOptions)
16:36:36    at System.Net.Sockets.SocketTaskExtensions.AcceptAsync(Socket socket)
16:36:36    at System.Net.Sockets.SocketAPMExtensions.BeginAccept(Socket socket, AsyncCallback callback, Object state)
16:36:36    at System.Net.Sockets.Tests.SocketTestServerAPM.OnAccept(IAsyncResult result)
16:36:36    at System.Threading.Tasks.TaskToApm.<>c__DisplayClass1.<InvokeCallbackWhenTaskCompletes>b__0()
16:36:36    at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
16:36:36    at System.Threading.Tasks.AwaitTaskContinuation.RunCallback(ContextCallback callback, Object state, Task& currentTask)
16:36:36    at System.Threading.Tasks.Task.FinishContinuations()
16:36:36    at System.Threading.Tasks.Task`1.TrySetResult(TResult result)
16:36:36    at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
16:36:36    at System.Net.LazyAsyncResult.Complete(IntPtr userToken)
16:36:36    at System.Net.ContextAwareResult.CompleteCallback(Object state)
16:36:36    at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
16:36:36    at System.Net.ContextAwareResult.Complete(IntPtr userToken)
16:36:36    at System.Net.LazyAsyncResult.ProtectedInvokeCallback(Object result, IntPtr userToken)
16:36:36    at System.Net.LazyAsyncResult.InvokeCallback(Object result)
16:36:36    at System.Net.Sockets.BaseOverlappedAsyncResult.CompletionCallback(Int32 numBytes, SocketError errorCode)
16:36:36    at System.Net.Sockets.AcceptOverlappedAsyncResult.CompletionCallback(Int32 acceptedFileDescriptor, Byte[] socketAddress, Int32 socketAddressLen, SocketError errorCode)
16:36:36    at System.Net.Sockets.SocketAsyncContext.AcceptOperation.InvokeCallback()
16:36:36    at System.Net.Sockets.SocketAsyncContext.AsyncOperation.<QueueCompletionCallback>b__26(Object o)
16:36:36    at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
16:36:36    at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
16:36:36    at System.Threading.ThreadPoolWorkQueue.Dispatch()
16:36:36    at System.Diagnostics.Debug.UnixDebugLogger.ShowAssertDialog(String stackTrace, String message, String detailMessage)
16:36:36    at System.Net.GlobalLog.Assert(String message, String detailMessage)
16:36:36    at System.Net.GlobalLog.Assert(Boolean condition, String messageFormat, Object[] data)
16:36:36    at System.Net.LazyAsyncResult.set_Result(Object value)
16:36:36    at System.Net.Sockets.BaseOverlappedAsyncResult.CheckAsyncCallOverlappedResult(SocketError errorCode)
16:36:36    at System.Net.Sockets.Socket.DoBeginAccept(Socket acceptSocket, Int32 receiveSize, AcceptOverlappedAsyncResult asyncResult)
16:36:36    at System.Net.Sockets.Socket.BeginAccept(Socket acceptSocket, Int32 receiveSize, AsyncCallback callback, Object state)
16:36:36    at System.Net.Sockets.Socket.BeginAccept(Int32 receiveSize, AsyncCallback callback, Object state)
16:36:36    at System.Net.Sockets.Socket.BeginAccept(AsyncCallback callback, Object state)
16:36:36    at System.Net.Sockets.SocketTaskExtensions.<AcceptAsync>b__0(AsyncCallback callback, Object state)
16:36:36    at System.Threading.Tasks.TaskFactory`1.FromAsyncImpl(Func`3 beginMethod, Func`2 endFunction, Action`1 endAction, Object state, TaskCreationOptions creationOptions)
16:36:36    at System.Net.Sockets.SocketTaskExtensions.AcceptAsync(Socket socket)
16:36:36    at System.Net.Sockets.SocketAPMExtensions.BeginAccept(Socket socket, AsyncCallback callback, Object state)
16:36:36    at System.Net.Sockets.Tests.SocketTestServerAPM.OnAccept(IAsyncResult result)
16:36:36    at System.Threading.Tasks.TaskToApm.<>c__DisplayClass1.<InvokeCallbackWhenTaskCompletes>b__0()
16:36:36    at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
16:36:36    at System.Threading.Tasks.AwaitTaskContinuation.RunCallback(ContextCallback callback, Object state, Task& currentTask)
16:36:36 --- End of stack trace from previous location where exception was thrown ---
16:36:36    at System.Threading.Tasks.AwaitTaskContinuation.<>c.<ThrowAsyncIfNecessary>b__18_0(Object s)
16:36:36    at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
16:36:36    at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
16:36:36    at System.Threading.ThreadPoolWorkQueue.Dispatch()
16:36:36 ./run-test.sh: line 130: 61302 Aborted                 (core dumped) ./corerun xunit.console.netcore.exe $testDllName -xml testResults.xml -notrait category=failing -notrait category=OuterLoop -notrait category=$xunitOSCategory
16:36:36 One or more tests failed while running tests from 'System.Net.Sockets.APMServer.Tests'.  Exit code 134.
```
cc: @pgavlin, @cipop, @davidsh

### PR DESCRIPTION
**Pull request by pgavlin**
This matches Winsock behavior.

Fixes #4396.

### CODE REVIEW

**Comment by pgavlin** [comment]
@stephentoub @CIPop PTAL

**Comment by stephentoub** [comment]
Thanks, Pat.  If that's the right behavior, LGTM.  

A few thoughts:
- Could you add comments indicating that we're explicitly not queueing for this reason?
- Could you add a test that ensures this behavior somehow?
- Each of these locations also has a TODO comment about checking Winsock behavior for the right error code.  Is that TODO still valid?  Is there an issue # we can add for it?

**Comment by pgavlin** [comment]
> Could you add comments indicating that we're explicitly not queueing for this reason?

Sure.

> Could you add a test that ensures this behavior somehow?

Unfortunately this is a very difficult behavior to test without better unit-testing capabilities, as it relies on a close and an accept racing. I'll see if I can come up with something.

> Each of these locations also has a TODO comment about checking Winsock behavior for the right error code. Is that TODO still valid? Is there an issue # we can add for it?

Yes, these are still valid. I'll double-check these today and add an issue if I can't resolve them.

**Comment by stephentoub** [comment]
Sounds good. Thanks.

**Pull request merged**
