### PR TITLE
Removing some double/single perf scenarios that conflict due to the generated xunit display name

### PR DESCRIPTION
**Pull request by tannergooding**
This is tracked by https://github.com/xunit/xunit/issues/1822

CC. @ViktorHofer, @danmosemsft

### CODE REVIEW

**Comment by jorive** [comment]
@dotnet-bot test Windows_NT perf

**Comment by jorive** [comment]
There are still more failures, for example: `ToStringWithFormat`

**Comment by ViktorHofer** [comment]
@dotnet-bot test Windows_NT perf

**Comment by ViktorHofer** [comment]
@tannergooding I hope you don't mind that I committed into your branch to fix the failing tests and add comments for the disabled tests.

**Comment by ViktorHofer** [comment]
As soon as the perf run finishes successfully the PR can be squashed. Ignore the unrelated failing test in the UWP leg.

**Pull request merged**
