### PR TITLE
Import XML Doc Comments for System.Collections.Concurrent

### PR DESCRIPTION
**Pull request by cartermp**
/cc @mairaw @Priya91

### CODE REVIEW

**Comment by stephentoub** [comment]
I see lots of crefs like:
```C#
<see cref="Concurrent.IProducerConsumerCollection`1" />
```
Why is this not either:
```C#
<see cref="System.Collections.Concurrent.IProducerConsumerCollection`1" />
```
or:
```C#
<see cref="IProducerConsumerCollection`1" />
```
?  It seems like it's in this strange middle ground.

Also, should it use the ```{T}``` syntax instead of the ````1``` syntax?

**Comment by cartermp** [comment]
Yeah that is a bit strange.  It's what the simplifier reduced it to.  [This doesn't seem to be the case all the time](https://github.com/cartermp/corefx/blob/import-sys-collections-specialized/src/System.Collections.Specialized/ref/System.Collections.Specialized.cs#L254), so we'll have to look into it.

As for the ``1`syntax, that's what the Intellisense files had.  We can go through and change that.

**Comment by cartermp** [comment]
I just noticed this same style of reduction when I imported `System.Diagnostics.Process`.  If I try to remove the `Process` qualifier, Visual Studio can't find the type.  For example:

Given this output from the tool:

`...<see cref="Process.StandardOutput" />...`

Pressing `f12` takes me to `public System.IO.StreamReader StandardOutput` as expected.

If I remove `Process`:

`<see cref="StandardOutput" />`

Pressive `f12` I get "Cannot navigate to the symbol under the caret.".

**Comment by stephentoub** [comment]
> Given this output from the tool

That's in an XML comment in the Process class, or on something outside of the Process class?

**Comment by cartermp** [comment]
Looks like that's only when it's outside the Process class.

Hmmm.  The `Concurrent.*` crefs seem strange since it doesn't seem like there's a need to disambiguate.  I can try it again on my machine and see what's going on.

**Comment by cartermp** [comment]
Seems like the culprit is the ``1`.  If I change the crefs to this:

`<see cref="IProducerConsumerCollection{T}" />`

Then it can find symbols and doesn't require the `Concurrent.` qualifier.  I'll make that change.

**Comment by mairaw** [comment]
But this will be true for all generic APIs. But I don't understand why the cref doesn't match the Comment ID for that API.

**Comment by cartermp** [comment]
Closing this out as we have a different plan for reference docs now.

**Pull request closed without merging**
