### PR TITLE
Remove 2 phase 2

### PR DESCRIPTION
**Pull request by danmosemsft**

### CODE REVIEW

**Comment by filipnavara** [comment]
The CI is stuck, but it looks like infrastructure errors. It's probably ready to go in.

**Comment by danmosemsft** [comment]
@safern all legs are green in the Azure page..is it a known issue that it shows pending here? I think you may have told me yes already..

**Comment by safern** [comment]
Yes this is one of the bugs that they have where they duplicate builds when you rerun.

**Comment by danmosemsft** [comment]
@stephentoub can you signoff?

**Pull request merged**
