### PR TITLE
Enable Environment.Exit tests.

### LINKED ISSUE #18776: Enable tests for Environment.ExitCode
Based on this comment(https://github.com/dotnet/coreclr/issues/6206#event-1048947484), [the tests of Environment.ExitCode](https://github.com/dotnet/corefx/blob/0ebc867d6bad9d777dd61afb78d0445c86143b34/src/System.Runtime.Extensions/tests/System/Environment.Exit.cs#L52) should be enabled as the bug has been fixed in CoreCLR.

I'll work on this issue after https://github.com/dotnet/core-setup/issues/2050 resolved.

### PR DESCRIPTION
**Pull request by mazong1123**
Since Environment.Exit bug has been fixed in both coreclr and core-setup, this PR enables the tests in corefx repo.

Related issue:
https://github.com/dotnet/coreclr/issues/6206#issuecomment-295339778
https://github.com/dotnet/core-setup/issues/2050

Fix #18776

### CODE REVIEW

**Comment by mazong1123** [comment]
@jkotas Seems like the corefx is not using the latest coreclr bits. All the Environment.ExitCode tests failed. Do I need to change any config/setting?

**Comment by joperezr** [comment]
@mazong1123 coreclr gets updated automatically in PRs like [this one](https://github.com/dotnet/corefx/pull/19229) which was merged an hour ago. I'm not sure if that one contains the fix you mention, but I'll rerun one of the legs to see if it does. Also if you can point me to the actual commit in coreclr t hat fix this We can easily check if it is includded on the update or not.

**Comment by joperezr** [comment]
@dotnet-bot test Innerloop Windows_NT Release x64 Build and Test please (checking if new coreclr has fixes for the tests.)

**Comment by jkotas** [comment]
@joperezr This needs update `dotnet.exe` from core-setup repo (it needs this change: https://github.com/dotnet/core-setup/pull/2150).

What is the process to update core-setup bits used by corefx?

**Comment by joperezr** [comment]
oh I see, we control the version of the cli with [this file](https://github.com/dotnet/corefx/blob/master/DotnetCLIVersion.txt). We don't update this one very often, so there might be potentially some build breaks with this. That said, @mellinoe recently upgraded it to the new 2.0 toolset so in theory, it shouldn't be that bad. I would suggest updating the version of the CLI on that file and triggering a new CI build, and see if that works.

**Comment by danmosemsft** [comment]
The update looks like it's happening in https://github.com/dotnet/corefx/pull/19242

**Comment by mazong1123** [comment]
Since #19242 was closed, do we have any plan to update the core-setup bits used by corefx?

**Comment by joperezr** [comment]
@ViktorHofer is there something wrong with updating the CLI that we use in corefx? Or can you explain a bit more on why was #19242 closed?

**Comment by ViktorHofer** [comment]
@joperezr the version of core-setup which was referenced by @ramarag in the PR contained a change which needed to be reverted. I suggest choosing a core-setup build before that one or a newer one and creating a manual PR as there is no auto-sync between core-setup and corefx currenty.

**Comment by joperezr** [comment]
Thanks for the info, do you have the hash of the revert so that we can make sure the one we pick has it?

**Comment by ViktorHofer** [comment]
Yes: 910c9cbe929e664b6f41b5e1725bbc3df0bf04fe

https://github.com/dotnet/core-setup/commit/910c9cbe929e664b6f41b5e1725bbc3df0bf04fe

**Comment by mazong1123** [comment]
@dotnet-bot test Innerloop Windows_NT Release x64 Build and Test please
@dotnet-bot test Innerloop CentOS7.1 Debug x64 Build and Test please

**Comment by mazong1123** [comment]
Was core-setup updated in corefx?

**Comment by ViktorHofer** [comment]
No the file where the core-setup version is stored wasn't touched for the last 28 days. You need to submit a manual PR and change the following version strings:
https://github.com/dotnet/corefx/blob/master/external/runtime/runtime.depproj#L39-L44

**Comment by danmosemsft** [comment]
What versoin should go in that file?
If I look at these the latest is 2.0.0-preview2-25308-01 but the aborted update used 2.0.0-preview2-002093-00 so I would expect a number similar to that.
https://dotnet.myget.org/feed/dotnet-core/package/nuget/Microsoft.NETCore.DotNetHost
https://dotnet.myget.org/feed/dotnet-core/package/nuget/Microsoft.NETCore.DotNetHostPolicy

@joperezr do we need to do this for shipping -- is this 2.0 work? This dotnet.exe is only for testing with, and it's generlaly not relevant, so it's not essential I guess?

**Comment by mazong1123** [comment]
@danmosemsft The new `dotnet.exe` invokes a [new corhost interface](https://github.com/dotnet/core-setup/blob/master/src/corehost/cli/coreclr.cpp#L53), which fixed the [Environment.ExitCode](https://github.com/dotnet/coreclr/issues/6206#issuecomment-295339778) bug. IMO the fix could not be absorbed to 2.0 if we don't update core-setup bits.

**Comment by ViktorHofer** [comment]
> I would expect a number similar to

They changed the build numbers between April, 26th and May, 1st from 2.0.0-preview2-002093-00 to 2.0.0-preview2-25301-07.

> but I would expect a higher number because we don't want the change that @ramarag reverted, right?

If you pick the latest package 2.0.0-preview2-25308-01 the reverted change from ramrag will be in there and also the change which is required for this issue.

> do we need to do this for shipping -- is this 2.0 work?

We definitely need to do this before 2.0 as we need the reverted change from ramrag in there. Otherwise it could break something...

**Comment by mazong1123** [comment]
@ViktorHofer So basically, I just need to update the number in https://github.com/dotnet/corefx/blob/master/external/runtime/runtime.depproj#L39-L44 to `2.0.0-preview2-25308-01`? Am I right?

**Comment by ViktorHofer** [comment]
Seems not working. Look at my PR where I am testing that with your commit.

I will talk with the right people about it today and give you an update

**Comment by joperezr** [comment]
> @joperezr do we need to do this for shipping -- is this 2.0 work? This dotnet.exe is only for testing with, and it's generlaly not relevant, so it's not essential I guess?

No, at least the issue today has a 'Future' milestone and I don't think it is required. Since we use the CLI to run the tests, this test in particular needs change dotnet/core-setup#2150 which is not yet in the CLI that we are using today, which is why in order for the test to pass, we would have to update the CLI version we use.

**Comment by jkotas** [comment]
> This dotnet.exe is only for testing with

Should we be worried that we are testing with stale bits? What other changes are missing in dotnet.exe used for testing vs. the shipping one?

**Comment by ViktorHofer** [comment]
> What other changes are missing in stale dotnet.exe used for testing vs. the shipping one?

The BaseDirectory trailing slash thing

**Comment by joperezr** [comment]
> Should we be worried that we are testing with stale bits? What other changes are missing in stale dotnet.exe used for testing vs. the shipping one?

I should have been more clear. We use the hostfxr plus dotnet.exe out from the CLI that we restore, but we swap the contents of the shared framework with the live build of corefx, plus the coreclr version that we depend on.

**Comment by jkotas** [comment]
Right, dotnet.exe and hostfxr are the stale bits that I am talking about.

**Comment by joperezr** [comment]
I see, we currently don't have an auto-upgrade scenario for it as we do for corefx, and I don't believe we have a plan for that in the near future. @weshaggard ?

**Comment by weshaggard** [comment]
>I see, we currently don't have an auto-upgrade scenario for it as we do for corefx, and I don't believe we have a plan for that in the near future. @weshaggard ?

Correct we don't have an explicit plan for that. We do have plans to run our corefx tests against the shared framework which should take this scenario into account but it isn't our normal flow. @gkhanna79 do you feel there is enough value to automatically update dotnet.exe in corefx to keep it updated for corefx testing? From my prospective the host we use for our testing is similar to the host we use for our toolsets and it isn't about testing the latest shipping bits but instead it is about using a stable toolset that supports what we need.

**Comment by gkhanna79** [comment]
If there is a test in CoreFX that would rely on picking up the newer host/hostfxr/sharedfx, then it should be done. I believe this change is in that category.

**Comment by weshaggard** [comment]
>If there is a test in CoreFX that would rely on picking up the newer host/hostfxr/sharedfx, then it should be done. I believe this change is in that category.

OK so you are in favor of doing it on demand when needed then as opposed to updating it with every core-setup build? That is what I would favor as well.

**Comment by gkhanna79** [comment]
Yes, on-demand.

**Comment by mazong1123** [comment]
I just thumb up all the discussions above to make sure that we're on the same page (Please correct me if I anything is wrong):

1. The `dotnet.exe` built from core-setup project is only used by corefx for test purpose. End user won't use this `dotnet.exe`.

2. We should update corefx settings to pick the newer core-setup bits on demand (when needed) - as this issue.

3. Enable the Environment.ExitCode tests in corefx is not required for shipping 2.0.

I got 2 questions:
1. This issue https://github.com/dotnet/coreclr/issues/6206 was labeled as 2.0.0 milestone. Can we confirm that even if the `dotnet.exe` from core-setup is not updated in corefx, the corefx is still using the latest corhost interface so that the fix can be included? If this can be confirmed then we're safe. Otherwise I'll download the latest corefx build to verify if this bug get fixed tonight.

2. As @ViktorHofer  mentioned in https://github.com/dotnet/corefx/pull/19232#issuecomment-300174344 , change https://github.com/dotnet/corefx/blob/master/external/runtime/runtime.depproj#L39-L44 is not working (The tests of Environment.ExitCode still failed). Any clue to update the core-setup bits?

**Comment by gkhanna79** [comment]
> Any clue to update the core-setup bits? 

I think updating the depproj is what we have talked about as an on-demand update. If you update the related values of dotnet and hostpolicy packages to recent ones (say, yesterday), will that suffice for your validation?

@weshaggard Are these the values that are updated manually on-demand?

**Comment by mazong1123** [comment]
I thought update the depproj  would be suffice. However, @ViktorHofer did that in https://github.com/dotnet/corefx/pull/19524 but the tests for Environment.ExitCode still failed. Seems like the changes in depproj didn't cause corefx uses the newer dotnet.exe bits.

**Comment by gkhanna79** [comment]
Please try with 2.0.0-preview2-25310-02	 as the version in depproj and confirm if it still does not work.

**Comment by mazong1123** [comment]
@gkhanna79 Seems like it does not work. I'll manually update the dotnet.exe used by corefx and run the tests. If the tests passed, that means the depproj changes are not working. Otherwise, there should be a bug either in the tests or in the code, which caused the failure.

**Comment by joperezr** [comment]
FWIW @ericstj updated the version to the latest we shipped in preview1 yesterday with PR https://github.com/dotnet/corefx/pull/19614 @mazong1123 does that not contain the fixes you need?

**Comment by joperezr** [comment]
Also, I'm not sure exactly what you meant with:
> The dotnet.exe built from core-setup project is only used by corefx for test purpose. End user won't use it.

but dotnet.exe is not only used for tests, we also use it to restore packages, and not sure what does your end user comment means but in theory no, the End user WILL use it since dotnet.exe is our command line interface that consumers will use to create, build, test and run .NET Core apps.

**Comment by gkhanna79** [comment]
>  I'd expect the fix not been included in #19614 either.

That PR says it is updating to CLI for PReview1 that does not have this change. https://github.com/dotnet/core-setup/pull/2150 was merged 10 days ago and will be in Preview2 CLI. 

@weshaggard @joperezr What updates need to happen to the depproj to consume latest CLI that will have the fix?

**Comment by weshaggard** [comment]
Assuming the fix is in dotnet.exe then update the depproj here is all that should be needed. See https://github.com/mazong1123/corefx/blob/75a12e9a19f8fdc0dbb532cf17717ff200096c3e/external/runtime/runtime.depproj#L50 where we copy the one restored into the test shared framework. 

@mazong1123 can you confirm whether or not the dotnet.exe that is in package 2.0.0-preview2-25310-0 has the necessary fixes? If it does can you confirm that is the same dotnet.exe that is at `bin\testhost\netcoreapp-Windows_NT-Debug-x64` when your run your test?

**Comment by mazong1123** [comment]
I'll do it tonight. Sorry for the late.

**Comment by mazong1123** [comment]
I tried to download the package from https://dotnetcli.blob.core.windows.net/dotnet/Runtime/master/dotnet-ubuntu.16.04-x64.latest.tar.gz

But this link gave me a not found error. Is this the right place to find the package? https://github.com/dotnet/core-setup#daily-builds

**Comment by danmosemsft** [comment]
@eerhardt the link above from core-setup does not work?

@mazong1123 it might e included in https://dotnetcli.blob.core.windows.net/dotnet/Sdk/master/dotnet-dev-ubuntu.16.04-x64.latest.tar.gz

**Comment by mazong1123** [comment]
@danmosemsft I already started downloading the SDK. Will test it later.

**Comment by mazong1123** [comment]
I downloaded the latest SDK and trying to run `dotnet new console` and `dotnet restore`. Just got following error message:
```
/home/mazong1123/lab/dotnetsdk/sdk/2.0.0-preview2-006082/NuGet.targets(98,5): error : Unable to resolve 'Microsoft.NETCore.App (>= 2.0.0-preview2-25309-07)' for '.NETCoreApp,Version=v2.0'. [/home/mazong1123/lab/hlsdk/hlsdk.csproj]
```

I'm following this instructions: https://github.com/dotnet/corefx/blob/master/Documentation/project-docs/dogfooding.md

I'm puzzled as I thought the sdk should download the dependencies for me when I ran `dotnet restore`. Am I missing something?

**Comment by eerhardt** [comment]
> @eerhardt the link above from core-setup does not work?

We are no longer building distro-specific archives.  Instead, we have a single tarball for all supported Linux systems:

https://dotnetcli.blob.core.windows.net/dotnet/Runtime/master/dotnet-linux-x64.latest.tar.gz

**Comment by danmosemsft** [comment]
@eerhardt any chance you could get the distro links removed from the readme/s then?

**Comment by eerhardt** [comment]
> any chance you could get the distro links removed from the readme/s then?

/cc @mellinoe @chcosta - can you guys take a look at updating our readme?

**Comment by eerhardt** [comment]
Nevermind - @rakeshsinghranchi already has a PR to fix the readme:  https://github.com/dotnet/core-setup/pull/2419

**Comment by mazong1123** [comment]
I tried to use latest SDK to create a console application, but failed in `donet restore` step. See my comment: https://github.com/dotnet/corefx/pull/19232#issuecomment-302051934

Now I'm going to download the donet runtime via https://dotnetcli.blob.core.windows.net/dotnet/Runtime/master/dotnet-linux-x64.latest.tar.gz along with latest corefx code to see if my changes included.

**Comment by mazong1123** [comment]
Update:

1. I installed .NET Core SDK (2.0.0-preview2-006082) and Ran the test app. Confirmed that the fix has been included.

2. Then I grabbed the latest master source code of corefx, changed the version inside depproj to `2.0.0-preview2-25310-02` and built the source code. Next I renamed the dotnetsdk directory so that when I invoke `dotnet`, the dotnet binary `corefx/bin/testhost/netcoreapp-Linux-Debug-x64/dotnet` would be called.

3. I invoked `corefx/bin/testhost/netcoreapp-Linux-Debug-x64/dotnet mytestapp`, still got the correct result. So I think the fix has been included in `2.0.0-preview2-25310-02` dotnet binary as well.

So why the CI tests failed? I'm going to check if there're some issues about the test cases of `Environment.ExitCode` itself.

**Comment by gkhanna79** [comment]
Restarting the CI since results are not available anymore.

**Comment by gkhanna79** [comment]
@dotnet-bot test this please

**Comment by gkhanna79** [comment]
@mazong1123 Can you please rebase to the tip and update the PR?

**Comment by mazong1123** [comment]
I just tried running the tests locally. The Environment.ExitCode tests will fail because the program complained that `libhostpolicy.so` cannot be found in `/home/mazong1123/github/corefx/bin/Unix.AnyCPU.Debug/System.Runtime.Extensions.Tests/netcoreapp/`. So I just copied all the *.so to the target folder by executing following command.

```
sudo cp ./bin/testhost/netcoreapp-Linux-Debug-x64/shared/Microsoft.NETCore.App/9.9.9/* /home/mazong1123/github/corefx/bin/Unix.AnyCPU.Debug/System.Runtime.Extensions.Tests/netcoreapp/
```

Then I set the CORE_ROOT to the latest .NET SDK share folder. This time the tests passed. So I doubt the CI test failure also caused by the absence of `libhostpolicy.so`.

I'll update the PR with latest master code to see if this issue still exists.

**Comment by mazong1123** [comment]
Seems like the absence of `libhostpolicy.so` still exists after the PR updated. Please search `libhostpolicy.so` in https://ci.dot.net/job/dotnet_corefx/job/master/job/ubuntu14.04_debug_prtest/8062/consoleFull#-5646644912d31e50d-1517-49fc-92b3-2ca637122019

Do you have any idea why `libhostpolicy.so` was not copied to the '/mnt/j/workspace/dotnet_corefx/master/ubuntu14.04_debug_prtest/bin/Unix.AnyCPU.Debug/System.Runtime.Extensions.Tests/netcoreapp/' directory?

**Comment by gkhanna79** [comment]
I will try to repro this locally and see what I can find.

@weshaggard If you have any inputs for the questions above, do chime in.

**Comment by weshaggard** [comment]
I'm trying to run it locally.

**Comment by gkhanna79** [comment]
I am able to repro it locally using this branch.

**Comment by weshaggard** [comment]
I've figured out what is going wrong. We need to correctly setup the runtimeconfig for the test exe we are running. I will push a change to @mazong1123's branch shortly.

**Comment by gkhanna79** [comment]
Yes that is what I started to suspect since test app was showing dependency on hostpolicy.

Post the fix, we should port this to 2.0.0 since product change is there already.




Thanks,
Gaurav


-------- Original message --------

**Comment by weshaggard** [comment]
commit pushed https://github.com/dotnet/corefx/pull/19232/commits/b1ce73e397e9ace79feb05cd96f35361a87ef2c0 hopefully that makes CI green.

>Post the fix, we should port this to 2.0.0 since product change is there already.

This is a test only change we can port to 2.0.0 if you think it is interesting but I don't know that it matters much, as it will always be testing the same version of dotnet.exe.

**Comment by weshaggard** [comment]
@dotnet-bot test Innerloop OSX10.12 Debug x64 Build and Test

**Comment by danmosemsft** [comment]
Wes is this branch containing too many changes? Seems not rebased properly?

**Comment by mazong1123** [comment]
@danmosemsft Seems that the dotnet-bot pushed a lot of commit to this branch. Any miss configuration after my rebase?  

BTW, the Windows tests are still failing. I may investigate this on Monday.

**Comment by danmosemsft** [comment]
@mazong1123 that's my question to @weshaggard ..

**Comment by weshaggard** [comment]
>Wes is this branch containing too many changes? Seems not rebased properly?

Yeah when I pushed it got a merge along with it. The extra commit that is interesting is https://github.com/dotnet/corefx/pull/19232/commits/b1ce73e397e9ace79feb05cd96f35361a87ef2c0. Beyond that there is still a bug in the test code that prevents it from working on .NET Framework. I'm still looking at that.

**Comment by weshaggard** [comment]
@mazong1123 I think I have the last change needed for this test to start working. In order to push the last fix and handle the merge I force pushed to your branch. Sorry about that you will need to reset your branch locally in order to make any additional changes (if necessary).

@mazong1123 thanks for being patient here you were hitting a number of unique issues in our testing infrastructure some of which I'm going to file issues to track getting fixed but others are still unique to this test which tries to start an external process which needs to be done in a particular manor for the different target .NET platforms we test on.

**Comment by weshaggard** [comment]
CI is green so merging. I linked 3 new issues to this to track some of the general issues we were hitting.

@mazong1123 Thanks for your contributions in getting this fixed all the way through the stack from the runtime to the host to the testing here. It is very impressive to see a full end-to-end feature get pushed into .NET Core.

**Comment by mazong1123** [comment]
Great to see the tests finally work. Great to work with you guys :)

**Pull request merged**
