### PR TITLE
Remove ActiveIssue1050 from CanReadFromSameMemoryMappedPEReaderInParallel() in MetadataReaderTests.cs

### PR DESCRIPTION
**Pull request by Jiayili1**
Remove [ActiveIssue1050] from CanReadFromSameMemoryMappedPEReaderInParallel() in MetadataReaderTests.cs
under src\System.Reflection.Metadata\tests\Metadata

### CODE REVIEW

**Comment by Jiayili1** [comment]
https://github.com/dotnet/corefx/issues/1050

**Comment by Jiayili1** [comment]
@Priya91

**Comment by stephentoub** [comment]
Please revert the changes that were made to the two .sh files... the contents weren't modified, but you changed their permissions, and those permissions are being submitted back to GitHub.

**Comment by danmosemsft** [comment]
Actually since I see other extra files in there I think it is best to reset to the branch point:
```
git reset master
git add src/System.Reflection.Metadata/tests/Metadata/MetadataReaderTests.cs
git commit -m "Remove ActiveIssue 1050."
git push <your fork> <branch> -f
```

**Pull request closed without merging**
