### PR TITLE
Update to latest build tools to pick up some fixes.

### PR DESCRIPTION
**Pull request by jhendrixMSFT**

### CODE REVIEW

**Comment by stephentoub** [comment]
LGTM

**Comment by mellinoe** [comment]
@weshaggard Are we okay to pick up the latest buildtools now?

**Comment by jhendrixMSFT** [comment]
I believe so.  The issue that broke us last time was fixed in https://github.com/dotnet/buildtools/pull/342 which is part of this version of build tools.
CC @joperezr

**Comment by mellinoe** [comment]
We'll at least need this one as well: https://github.com/dotnet/corefx/pull/4763 (@joperezr's PR)

**Comment by joperezr** [comment]
Yes, we do. I just merged so it should be ok to merge this one as well.

**Comment by joperezr** [comment]
@jhendrixMSFT I thought you wanted to add another change and create a new version of the package, are you not doing that anymore?

**Pull request merged**
