### PR TITLE
Move marvin hashing into shared partition to gain access to it in S.P.CoreLib

### PR DESCRIPTION
**Pull request by ViktorHofer**
Prep work

### CODE REVIEW

**Comment by ViktorHofer** [comment]
Ah RandomNumberGenerator is missing

**Comment by ViktorHofer** [comment]
Will reopen after I figured out what exactly needs to move into the shared partition from Crypto

**Comment by tarekgh** [comment]
I think you can still move it to the shared folder. I think corelib should have crypto support. but even if it is not, I am still seeing a value to move this to the shared folder

**Comment by ViktorHofer** [comment]
I will port it to Corelib but probably not in a shareable manner with corefx as @jkotas pointed out to me yesterday that the Marvin impl in corefx relies on the Crypto stack which we don't want to have in Corelib. That's why I closed this PR.

**Comment by jkotas** [comment]
It should be fine to change the shared Marvin impl to not depend on the Crypto stack.

**Pull request closed without merging**
