### PR TITLE
Move NTAuthentication to Common location for re-use in Mail.

### PR DESCRIPTION
**Pull request by Priya91**
This solution seems to be the best option to solve the issue #13364 for release before netstandard2.0. 

Designing a new public surface area for authentication protocols can be an independent project now, without being time sensitive for netstandard2.0 release.

cc @karelz @CIPop @davidsh @stephentoub @weshaggard

### CODE REVIEW

**Comment by stephentoub** [comment]
This didn't change any code, just moved files around, right? If so, LGTM.

**Comment by CIPop** [comment]
@Priya91 I thought we're going the add a simple new API route for netstandard after this being discussed with @weshaggard as a possibility.

**Comment by CIPop** [comment]
Leaving the above design related comment aside, did you manually test that both NTLM and Kerberos auth now works for `SmtpClient`?
Also, is there an issue tracking adding such automated tests similar to those in `NegotiateStream`?

**Comment by Priya91** [comment]
> This didn't change any code, just moved files around, right? If so, LGTM.

Yes, no code changed.

**Comment by Priya91** [comment]
> Leaving the above design related comment aside, did you manually test that both NTLM and Kerberos auth now works for SmtpClient?

This change is not introducing any new dependencies that didn't exist before. Instead of reflecting to the type in System.Net.Security, moved the relevant files around to build NTAuthentication in source in System.Net.Mail.

**Comment by CIPop** [comment]
> This change is not introducing any new dependencies that didn't exist before. Instead of reflecting to the type in System.Net.Security, moved the relevant files around to build NTAuthentication in source in System.Net.Mail.

That's not a good argument: we still need to test security-related aspects of all components in their respective environments, regardless of the test complexity.
In this case we need to ensure that actual Kerberos authentication works for this type and that, if no Domain exists, Negotiate uses NTLM.

Opened #13868 to track the work. 

/cc @blowdart @karelz @davidsh

**Comment by blowdart** [comment]
Also it needs to be tested on machines where NTLM is disabled, because, frankly NTLM needs to go away and die.

**Pull request merged**
