### PR TITLE
Cleanup RegularClass.RegularMethod tests in System.Dynamic.Runtime P1.

### PR DESCRIPTION
**Pull request by hughbe**
Firstly, *sorry* for the previous PR - looking back at it I don't know how I expected you to review the old PR.
I've tried to make reviewing this one much easier:
1) Splitting up PRs into multiple PRs
2) Keeping tests in the same order
3) Annotating the number of the old test above the new tests

This PR cleans up 50 out of the 95 tests for the RegularClass.RegularMethod tests

/cc @VSadov (**thank you!!**)

### CODE REVIEW

**Comment by stephentoub** [comment]
> I've tried to make reviewing this one much easier:

Thanks, @hughbe.  Unfortunately it's still difficult to review, as it's too large for GitHub to show:
```
459 additions, 2,254 deletions not shown because the diff is too large
```

**Comment by hughbe** [comment]
@stephentoub thanks for the heads up.
I've basically split up this PR into more than one commit for review purposes.
- Commit 1: Tests 1-35 inclusive
- Commit 2: formatting changes
- Commit 3: Tests 36-50 inclusive

**Comment by hughbe** [comment]
Test Innerloop CentOS7.1 Debug Build and Test

**Comment by stephentoub** [comment]
Thanks for doing this, @hughbe. These look great; so much cleaner than before.

**Comment by stephentoub** [comment]
@dotnet-bot test this please

**Comment by hughbe** [comment]
Test Innerloop OSX Release Build and Test

**Comment by VSadov** [comment]
LGTM
Thanks!

**Pull request merged**
