### PR TITLE
Update MemberDescriptor.cs

### PR DESCRIPTION
**Pull request by kuns200**
Fixing Exception to  ANE
#38985

### CODE REVIEW

**Comment by danmosemsft** [comment]
Can you please include a test?
Does this overlap https://github.com/dotnet/corefx/pull/39026/files ? @hughbe

**Comment by hughbe** [comment]
https://github.com/hughbe/corefx/commit/8fecb18cce5a9a434eb2dea91b11b030fe1ff980

Yeah a bit of overlap - submitting this now that the other PR r.e CategoryAtrribute has been merged

**Comment by kuns200** [comment]
@hughbe thanks for completing it. I couldn't complete it.

**Comment by maryamariyan** [comment]
Closing. Thank you @kuns200 for the effort.

**Pull request closed without merging**
