### PR TITLE
Tests maintaining compat in when Linq Contains uses ICollection<T>.Contains

### PR DESCRIPTION
**Pull request by JonHanna**
cc @stephentoub

### CODE REVIEW

**Comment by karelz** [comment]
BTW: Stephen is OOF until end of year.
cc: @OmarTawfik @VSadov (also OOF - just this week)

**Comment by OmarTawfik** [comment]
@JonHanna Can we add a case where there is a collection comparer AND another one passed to Contains()?
Otherwise, LGTM.

**Comment by JonHanna** [comment]
Added.

**Comment by OmarTawfik** [comment]
Thanks @JonHanna!

**Pull request merged**
