### PR TITLE
[WIP] Fix Linux process names

### LINKED ISSUE #34437: Process.GetProcesses returns truncated 15 char string on Linux
When using `Process.GetProcesses()` in dotnet core it returns the `Process.ProcessName` property fine under Windows as expected. 

However when ran under Linux (Tested on Ubuntu 17.04) it seems to return process names as 15 char long strings. It truncates the process names to all be 15 char long strings.

My applogies if there is an issue for this somewhere under another repo. I found there was such an issue with the mono framework when doing research prior to submitting this issue: https://bugzilla.xamarin.com/show_bug.cgi?id=32539

### PR DESCRIPTION
**Pull request by 2E0PGS**
Fix for Process.GetProcesses returns truncated 15 char string on Linux.

Fixes #34437

### CODE REVIEW

**Comment by danmosemsft** [comment]
Thanks @2E0PGS . As mentioned in the issue the next step is a test. You can probably copy and modify the ProcessStart_DirectoryNameInCurDirectorySameAsFileNameInExecDirectory_Success test. 

I suggest you use sleep as the test program, suitably renamed to a long name. You can use the logic in IsProgramInstalled to find it (perhaps extract a GetProgramPath). On some distros it doens't exist by default: I would skip the test in that case, unless you thnk of some other scheme. The test should run for macOS as well as Linux.

**Comment by danmosemsft** [comment]
BTW recent github feature - when you click the button to create a PR, you have the option of making it a "draft" PR so it can't be merged.

**Comment by krwq** [comment]
codewise looks good but as @danmosemsft mentioned this is missing a test

**Comment by karelz** [comment]
@2E0PGS do you plan to add test as suggested above in https://github.com/dotnet/corefx/pull/35809#issuecomment-470198991?

**Comment by 2E0PGS** [comment]
Hi chaps,

Sorry I have been very busy with work related activities (programming).

I suggest someone else take a look into writing some tests for this because I would need to mock a lot more than just my section of code. There is a few other objects in that method I modified which I haven't studied enough to mock yet.

I would look into it if I had more free time. So if no one does I may eventually pick this back up. However in the meantime if there is a release goal I suggest someone take ownership of the tests.

Perhaps someone who has written unit tests for this project previously is ideal.

**Comment by karelz** [comment]
Thanks @2E0PGS! @wtgodbe @krwq any thoughts on this? Do you want to take the PR as is, or close it and wait for a new one with tests?

**Comment by 2E0PGS** [comment]
Given the current class has no test's against it. It does seem odd it's only suddenly become a issue that it's missing tests. Since my code changes are minimal and quite obvious I would suggest the benefit is high and the changes are not a large risk. 

I personally would wait and see if somone takes charge of writing a test. If no response before deadline then merge.

However if the latter occured then it would be a new issue opened for someone to write tests against various methods. Perhaps make the issue blocking of other new submissions.

**Comment by danmosemsft** [comment]
@marcorossignoli might be interested in finishing this.

**Comment by MarcoRossignoli** [comment]
Sure I'll work on it next days!

**Comment by danmosemsft** [comment]
Thanks @marcorossignoli

**Comment by 2E0PGS** [comment]
See new PR: https://github.com/dotnet/corefx/pull/36913

**Comment by karelz** [comment]
@2E0PGS stupid question: Does the new PR replace this one? If yes, can we close this one. If not ... please ignore my comment :)

**Comment by MarcoRossignoli** [comment]
Yes we can close this one

**Comment by karelz** [comment]
Replaced by #36913

Thanks @MarcoRossignoli for confirmation!

**Pull request closed without merging**
