### PR TITLE
Changed EqualityComparerForDouble and EqualityComparerForSingle to us Equals

### PR DESCRIPTION
**Pull request by ankitbko**
Pretty basic fix for #5558

### CODE REVIEW

**Comment by stephentoub** [comment]
LGTM
cc: @AlexGhiondea

**Comment by AlexGhiondea** [comment]
@ankitbko Thanks for doing this! 
Could you also add a couple of tests to make sure we don't regress this in the future?

**Comment by ankitbko** [comment]
@AlexGhiondea I am doing that. I see there are no tests for EqualityComparer class so I created one.
The problem is,  the tests run against EqualityComparer class in System.Collections, Version=4.0.10.0 dll, not against EqualityComparer in System.Collections csproj file.  What is going on here?
```
#region Assembly System.Collections, Version=4.0.10.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
// D:\dotnet\corefx\packages\System.Collections\4.0.10\ref\dotnet\System.Collections.dll
#endregion
```
Also shall I go ahead and add tests for all the types or just for Single and Double?

**Comment by stephentoub** [comment]
> the tests run against EqualityComparer class in System.Collections, Version=4.0.10.0 dll, not against EqualityComparer in System.Collections csproj file

The EqualityComparer file you edited is used by .NET Native / CoreRT.  For CoreCLR, it's actually using the EqualityComparer in mscorlib; System.Collections.dll is a partial facade, with some of the types it "contains" actually just getting type forwarded to mscorlib.  For the test to pass, the behavior from the mscorlib implementation needs to fixed first, if it's not correct already.

**Comment by ankitbko** [comment]
So this change needs to be done in CoreCLR mscorlib? I gone and checked, the implementaion of EqualityComparer there is quite different but it already uses [x.Equals(y)](https://github.com/dotnet/coreclr/blob/master/src/mscorlib/src/System/Collections/Generic/EqualityComparer.cs#L134). So what should I do now?

BTW this isn't considered as major change? Shouldn't the dnfclas bot change cla-not-required tag to cla-required?

**Comment by AlexGhiondea** [comment]
As @stephentoub pointed out, we can't actually test this code in the open. However, the tests you added will run against the mscorlib implementation and provide us with additional coverage.

I am going to figure out how we can bring back some of these tests in our internal build where we can actually test this code.

The change LGTM!

**Comment by weshaggard** [comment]
The change LGTM as well but in the interest of transparency we are considering turning these comaprers into a compiler intrinsic to enable us to get exact parity with full .Net Framework. If that happens all the code in this file essentially becomes dead code.

**Pull request merged**
