### PR TITLE
System.Text.Encoding: Add missing dnxcore50 frameworks element to project.json

### PR DESCRIPTION
**Pull request by akoeplinger**
@ericstj can I just commit the project.lock.json as well? I noticed there are a couple other lockfiles that aren't checked in.

### CODE REVIEW

**Comment by mellinoe** [comment]
Yes, I think we should check in all of the lock files that are missing now,

**Comment by akoeplinger** [comment]
Ok, I think this should be done as a separate PR then (partly because I'm not sure I got the correct versions right now).

@dotnet-bot test this please

**Comment by Maxwe11** [comment]
@dotnet-bot test this please

**Comment by ericstj** [comment]
LGTM.  For lock files please check them in.  I'm ok with it being a separate commit.  If the versions showing up don't match the rest of the repo simply find/replace.

**Comment by stephentoub** [comment]
LGTM

**Pull request merged**
