### PR TITLE
Add packaging projects

### PR DESCRIPTION
**Pull request by ericstj**
This is the initial port of packaging infrastructure from closed source, 
adding project files for a few packages.

At the moment this is only building out the nuspecs.

### CODE REVIEW

**Comment by ericstj** [comment]
Looks like someone added a new dependency since my past merge.  I rebased on latest and repro locally.  We need to exclude System.Private.CoreLib from the dependency walk.  It's dependencies are missing from the targeting pack package and even if they were present they have cycles (known issue) since they are built against contracts.

**Comment by ericstj** [comment]
Found another issue.  @erme it looks like when you consolidated some projects you left PackageTargetFramework set to `dotnetN.M` even for some desktop projects.  I believe you need to add a condition to this.

**Comment by ericstj** [comment]
This is actually causing both issues.  Projects that previously would have had a PackageTargetFramework of net46 or netcore50 and thus skip generation validation are now getting a PackageTargetFramework of dotnet5.4 due to https://github.com/dotnet/corefx/commit/f39d73a00d80c5552c3c88a6b82521c71fecf568.

**Comment by mmitche** [comment]
@dotnet-bot test Innerloop Windows_NT Debug Build and Test

**Comment by ericstj** [comment]
Don't merge yet, this will need to rebase on a change coming from TFS to avoid a conflict.

**Comment by ericstj** [comment]
This should be ready to merge now.  @weshaggard can you have a look and let me know?

**Comment by weshaggard** [comment]
LGTM please squash the commits.

**Pull request merged**
