### PR TITLE
Reduce S.R.InteropServices outerloop test time from ~100s to ~0.2s

### PR DESCRIPTION
**Pull request by stephentoub**
Most of the tests in the test library run very quickly.  But one runs for ~100s, calling HandleCollector.Add 2B times to get it to overflow.  As a hack but IMHO a worthwhile hack, this commit uses reflection to jump the HandleCollector forward as if it were already called almost int.MaxValue times.  It then proceeds to do the remaining Adds manually, verifying that still works, and then overflows and verifies the expected failure.  This reduces the overall test execution from over 100 seconds to a few hundred milliseconds.

cc: @mellinoe, @Petermarcu

### CODE REVIEW

**Comment by hughbe** [comment]
Now that the tests so short, does it need [OuterLopp{?

**Comment by stephentoub** [comment]
> Now that the tests so short, does it need [OuterLoop]?

Nope.  I thought I'd removed that.  Will do so. Thanks.

**Comment by stephentoub** [comment]
@dotnet-bot test this please

**Comment by stephentoub** [comment]
Test Innerloop OSX Release Build and Test  please

**Comment by stephentoub** [comment]
@mmitche, I'm seeing a bunch of errors on OSX on various PRs of the form:
```
[WS-CLEANUP] Deleting project workspace...
ERROR: [WS-CLEANUP] Cannot delete workspace: remote file operation failed: /Users/dotnet-bot/j/workspace/dotnet_corefx/master/osx_release_prtest at hudson.remoting.Channel@25cc8326:dci-macpro-08: java.nio.file.AccessDeniedException: /Users/dotnet-bot/j/workspace/dotnet_corefx/master/osx_release_prtest/.editorconfig
ERROR: Cannot delete workspace: remote file operation failed: /Users/dotnet-bot/j/workspace/dotnet_corefx/master/osx_release_prtest at hudson.remoting.Channel@25cc8326:dci-macpro-08: java.nio.file.AccessDeniedException: /Users/dotnet-bot/j/workspace/dotnet_corefx/master/osx_release_prtest/.editorconfig
```

**Comment by bartonjs** [comment]
LGTM

**Comment by stephentoub** [comment]
Thanks

**Pull request merged**
