### PR TITLE
[release/2.1] Port Tizen missing rids to release/2.1

### PR DESCRIPTION
**Pull request by gbalykov**
cc @alpencolt @Dmitri-Botcharnikov

### CODE REVIEW

**Comment by stephentoub** [comment]
cc: @danmosemsft

**Comment by danmosemsft** [comment]
This needs to go to shiproom. @weshaggard are you the right person to write that up?

**Comment by weshaggard** [comment]
@danmosemsft I don't have any context here. The change looks good to me but I'm not sure who the sponsor should be.

**Comment by gbalykov** [comment]
@weshaggard could you, please, share the approximate date, when this could be merged?

**Comment by gbalykov** [comment]
cc @jkotas @Petermarcu 
This is required for build for Tizen 5.0.0, original PR #29684

**Comment by gbalykov** [comment]
@jkotas 

1. This change allows to build CoreFX with Tizen 5.0 and Tizen x86 RIDs both on master and release/2.1 branches (master branch downloads `https://www.nuget.org/packages/Microsoft.NETCore.Platforms`, `https://www.nuget.org/packages/Microsoft.NETCore.App/`, etc., which currently don't contain Tizen 5.0 RIDs)
2. Currently, we don't see workarounds for this

**Comment by danmosemsft** [comment]
Approved

**Comment by jkotas** [comment]
@weshaggard @danmosemsft Thank you for getting this approved

**Comment by weshaggard** [comment]
@wtgodbe this is going to require that we bump the version of Microsoft.NETCore.Platforms and add it to the list of packages we are shipping. Can you please go ahead and do that?

**Comment by wtgodbe** [comment]
@weshaggard sure thing

**Comment by wtgodbe** [comment]
https://github.com/dotnet/corefx/pull/30854

**Comment by karelz** [comment]
Adding approved tag based on @danmosemsft approval above: https://github.com/dotnet/corefx/pull/30640#issuecomment-402817520

**Pull request merged**
