### PR TITLE
Update BuildTools to 613-01

### PR DESCRIPTION
**Pull request by karajas**

### CODE REVIEW

**Comment by karajas** [comment]
@dotnet-bot test this please

**Comment by stephentoub** [comment]
@dotnet-bot test this please

**Comment by stephentoub** [comment]
@dotnet-bot test this please

**Comment by MattGal** [comment]
@dotnet-bot test this please

**Comment by MattGal** [comment]
@dotnet-bot Test Innerloop CentOS7.1 Debug Build and Test please
@dotnet-bot Test Innerloop CentOS7.1 Release Build and Test please

**Pull request merged**
