### PR TITLE
Fix LoadFromAssemblyName usage to account for DefaultContext binding.

### PR DESCRIPTION
**Pull request by gkhanna79**
Test fixes for https://github.com/dotnet/coreclr/issues/6670

### CODE REVIEW

**Comment by gkhanna79** [comment]
@dotnet-bot test this please

**Comment by gkhanna79** [comment]
@dotnet-bot test this please

**Comment by gkhanna79** [comment]
@dotnet-bot test this please

**Comment by gkhanna79** [comment]
@dotnet-bot test this please

**Comment by gkhanna79** [comment]
@dotnet-bot test Innerloop CentOS7.1 Release Build and Test  please

**Comment by gkhanna79** [comment]
@mmitche CentOS failed with the following twice:

`Failed to create the workspace for the job This can happen on CentOS if the resource disk attached by Azure is not made writable upon startup (which can happen because of a race condition). https://github.com/dotnet/dotnet-ci/issues/307 You should delete the node by clicking on the computer that ran the job (if 404 this has already been done), logging in, and hitting "Delete Slave"
`

**Comment by gkhanna79** [comment]
@dotnet-bot test this please

**Comment by gkhanna79** [comment]
@dotnet-bot test Innerloop Windows_NT Debug Build and Test  please

**Comment by gkhanna79** [comment]
@dotnet-bot test Innerloop Windows_NT Debug Build and Test please

**Comment by mmitche** [comment]
Please follow the noted directions of you have not already done so.

Sent from my iPhone

On Aug 11, 2016, at 7:40 PM, Gaurav Khanna <notifications@github.com<mailto:notifications@github.com>> wrote:


@mmitche<https://github.com/mmitche> CentOS failed with the following twice:

Failed to create the workspace for the job This can happen on CentOS if the resource disk attached by Azure is not made writable upon startup (which can happen because of a race condition). https://github.com/dotnet/dotnet-ci/issues/307 You should delete the node by clicking on the computer that ran the job (if 404 this has already been done), logging in, and hitting "Delete Slave"

**Pull request merged**
