### PR TITLE
SqlConnection timeout test is ported

### PR DESCRIPTION
**Pull request by geleems**
The connection timeout unit test that had been merged to release/2.0.0 branch is to be ported to master branch.

### CODE REVIEW

**Comment by geleems** [comment]
@dotnet-bot test Linux arm Release Build please

**Comment by stephentoub** [comment]
ConnectionTimeoutTestWithThread appears to be causing all PRs to fail on Windows.
cc: @danmosemsft

**Comment by saurabh500** [comment]
I will disable the test. @geleems please investigate.

**Comment by geleems** [comment]
The timeout was set 5 seconds, and cutoff time for valid elapsed time was set 6 seconds. It seems some elapsed time were slightly over 6 seconds in some environment, which causes the PR failures.

**Comment by danmosemsft** [comment]
I have seen timeouts/sleeps be several times longer than you expect, depending on the machine, the load etc. Eg., if something is supposed to return in 5 secs you would want to wait for 30 secs to be safe. And there is no reliable way of knowing that what you're waiting on did not attempt to wait for longer.

**Pull request merged**
