### PR TITLE
Fixed IPv6 address parsing on Linux from /proc/net/tcp6, /proc/net/udp6

### LINKED ISSUE #33257: IPGlobalProperties.GetIPGlobalProperties().GetActiveTcpListeners() (or GetActiveTcpConnections()) gives wrong IPv6 address on Linux
This is related to #32727.
It turned out that parsing of IPv6 addresses is incorrect on Linux. ::1 shows as ::1.0.0.0

This is easy to reproduce - just create any connection to loopback and call  GetActiveTcpConnections().
IPv6 addresses from the list will not match netstat. 

The reason is explained here:
https://serverfault.com/questions/592574/why-does-proc-net-tcp6-represents-1-as-1000

We use ParseHexIPAddress() under the cover and that assume that we have whole address represented as sequence of hex. This is not the case for tcp6 and we have four integers encoded network byte order.

### PR DESCRIPTION
**Pull request by VasiliyNovikov**
Here is the current logic:
https://github.com/dotnet/corefx/blob/f7539b726c4bc2385b7f49e5751c1cff2f2c7368/src/System.Net.NetworkInformation/src/System/Net/NetworkInformation/StringParsingHelpers.Connections.cs#L297
```cs
            for (int i = 0; i < 16; i++)
            {
                addressBytes[i] = (byte)(HexToByte(hexAddress[(i * 2)])
                                    + HexToByte(hexAddress[(i * 2) + 1]));
            }
```
It has 2 issues:
1. It misses left shift by 4 bits of high peace of byte:
2. It parses the whole sequence as a single byte array but instead it should parse it as sequence of 32-bit hex integers. 

And it was not caught in the tests since this logic was indirectly verified by itself.
Test uses it to validate parsing of connections from /proc/net/tcp6:
https://github.com/dotnet/corefx/blob/bed8a614c02bc24488a3208b80a5553f0e43b3d7/src/System.Net.NetworkInformation/tests/FunctionalTests/ConnectionsParsingTests.cs#L34
Usage
And parsing logic itself uses it:
https://github.com/dotnet/corefx/blob/bed8a614c02bc24488a3208b80a5553f0e43b3d7/src/System.Net.NetworkInformation/src/System/Net/NetworkInformation/StringParsingHelpers.Connections.cs#L240

fixes #33257

### CODE REVIEW

**Comment by danmosemsft** [comment]
Looks like you and @wfurt had hte same idea at the same time? https://github.com/dotnet/corefx/pull/34132

**Comment by VasiliyNovikov** [comment]
Yeah. Probably mine can be abandoned then. Maybe we could add some tests from mine to @wfurt 's

**Comment by wfurt** [comment]
Your change seems bigger and  has more tests. 
Why don't you pick up change in IPGlobalPropertiesTest.cs and add reference to the the issue so it will get closed when you submit? 
We can go the other way as if you prefer that.

**Comment by VasiliyNovikov** [comment]
> Why don't you pick up change in IPGlobalPropertiesTest.cs and add reference to the the issue so it will get closed when you submit?

Will do that

**Comment by VasiliyNovikov** [comment]
Done

**Comment by wfurt** [comment]
@dotnet-bot test this please

tests seems to fail because of jenkins

**Pull request merged**
