### PR TITLE
Add tests to improving TimeSpan precision

### PR DESCRIPTION
**Pull request by idlerboris**
Fixes [dotnet/corefx#41380](https://github.com/dotnet/corefx/issues/41380)

Related coreclr PR [dotnet/coreclr#26992](https://github.com/dotnet/coreclr/pull/26992)

### CODE REVIEW

**Comment by stephentoub** [comment]
cc: @anipik, @tannergooding

**Comment by danmosemsft** [comment]
@idlerboris as you probably know, the tests will fail until this repo ingests the other one.

**Comment by idlerboris** [comment]
> @idlerboris as you probably know, the tests will fail until this repo ingests the other one.

Yes, I read it. Am I right that this PR should just wait until this repo would be updated? Or should I (or someone else) monitor the repo and notify in this PR when it'd be ready to run tests on it?

**Comment by stephentoub** [comment]
Thanks

**Pull request merged**
