### PR TITLE
Remove ActiveIssue tags now that CLR is updated

### LINKED ISSUE #27269: Need to update tests for https://github.com/dotnet/coreclr/pull/16447
I will link to the test change that disables the tests that are impacted.

### PR DESCRIPTION
**Pull request by JeremyKuhne**
Fixes #27269 

cc: @Anipik, @pjanotti, @danmosemsft

### CODE REVIEW

**Comment by JeremyKuhne** [comment]
One test failed in OSX:

```
System.Net.Http.Functional.Tests.HttpClientHandler_Cancellation_Test
--
MaxConnectionsPerServer_WaitingConnectionsAreCancelable

Message :
System.Exception : Unexpected EOF trying to read request header
Stack Trace :
   at System.Net.Test.Common.LoopbackServer.Connection.ReadRequestHeaderAsync() in /Users/dotnet-bot/j/workspace/dotnet_corefx/master/osx-TGroup_netcoreapp+CGroup_Debug+AGroup_x64+TestOuter_false_prtest/src/Common/tests/System/Net/Http/LoopbackServer.cs:line 353
   at System.Net.Test.Common.LoopbackServer.Connection.ReadRequestHeaderAndSendResponseAsync(HttpStatusCode statusCode, String additionalHeaders, String content) in /Users/dotnet-bot/j/workspace/dotnet_corefx/master/osx-TGroup_netcoreapp+CGroup_Debug+AGroup_x64+TestOuter_false_prtest/src/Common/tests/System/Net/Http/LoopbackServer.cs:line 370
   at System.Net.Test.Common.LoopbackServer.<>c__DisplayClass14_0.<<AcceptConnectionSendResponseAndCloseAsync>b__0>d.MoveNext() in /Users/dotnet-bot/j/workspace/dotnet_corefx/master/osx-TGroup_netcoreapp+CGroup_Debug+AGroup_x64+TestOuter_false_prtest/src/Common/tests/System/Net/Http/LoopbackServer.cs:line 144
--- End of stack trace from previous location where exception was thrown ---
   at System.Net.Test.Common.LoopbackServer.AcceptConnectionAsync(Func`2 funcAsync) in /Users/dotnet-bot/j/workspace/dotnet_corefx/master/osx-TGroup_netcoreapp+CGroup_Debug+AGroup_x64+TestOuter_false_prtest/src/Common/tests/System/Net/Http/LoopbackServer.cs:line 117
   at System.Net.Test.Common.LoopbackServer.AcceptConnectionSendResponseAndCloseAsync(HttpStatusCode statusCode, String additionalHeaders, String content) in /Users/dotnet-bot/j/workspace/dotnet_corefx/master/osx-TGroup_netcoreapp+CGroup_Debug+AGroup_x64+TestOuter_false_prtest/src/Common/tests/System/Net/Http/LoopbackServer.cs:line 142
   at System.Net.Http.Functional.Tests.HttpClientHandler_Cancellation_Test.<>c__DisplayClass5_0.<<MaxConnectionsPerServer_WaitingConnectionsAreCancelable>b__0>d.MoveNext() in /Users/dotnet-bot/j/workspace/dotnet_corefx/master/osx-TGroup_netcoreapp+CGroup_Debug+AGroup_x64+TestOuter_false_prtest/src/System.Net.Http/tests/FunctionalTests/HttpClientHandlerTest.Cancellation.cs:line 345
--- End of stack trace from previous location where exception was thrown ---
   at System.Net.Test.Common.LoopbackServer.CreateServerAsync(Func`2 funcAsync, Options options) in /Users/dotnet-bot/j/workspace/dotnet_corefx/master/osx-TGroup_netcoreapp+CGroup_Debug+AGroup_x64+TestOuter_false_prtest/src/Common/tests/System/Net/Http/LoopbackServer.cs:line 67
   at System.Net.Http.Functional.Tests.HttpClientHandler_Cancellation_Test.MaxConnectionsPerServer_WaitingConnectionsAreCancelable() in /Users/dotnet-bot/j/workspace/dotnet_corefx/master/osx-TGroup_netcoreapp+CGroup_Debug+AGroup_x64+TestOuter_false_prtest/src/System.Net.Http/tests/FunctionalTests/HttpClientHandlerTest.Cancellation.cs:line 313
--- End of stack trace from previous location where exception was thrown ---
```

**Comment by stephentoub** [comment]
@geoffkizer, this "Unexpected EOF trying to read request header" assert that got added seems to be triggering a lot:
https://github.com/dotnet/corefx/blame/662d9bffae0c1e6119d1a62b073966d8aee673d3/src/Common/tests/System/Net/Http/LoopbackServer.cs#L350
Do you happy to know why?

**Comment by danmosemsft** [comment]
Also seen here: https://github.com/dotnet/corefx/pull/27499#issuecomment-369004060
I'm going to merge then.

**Comment by geoffkizer** [comment]
The exception I added fires when the loopback server gets EOF before it finishes reading the request headers (i.e. empty line).  Previously, it would have just treated EOF as the end of the request headers.

So, the previous behavior could have been masking real issues.  It was also definitely masking benign issues, which is why we are seeing it in CI now.

I'll dig into the specific failures and see if I can figure out how to improve this.  If necessary, we could revert back to the old behavior, but I'd prefer not to since it could hide real issues here.

**Pull request merged**
