### PR TITLE
TimeSpan Multiplication and Division

### LINKED ISSUE #7175: API Proposal: Support operators * / etc on type TimeSpan
## Background

TimeSpan represents a time interval, which makes it a common candidate for "mathematical" processing, such as taking a 1-hour interval, and divide it by 2, resulting a 0.5-hour interval. Currently, the TimeSpan type support only a limited subset of operators (+ and -), and only with a TimeSpan operand.

## Proposed API - Approved
Approved in
* https://github.com/dotnet/corefx/issues/7175#issuecomment-262323805
* https://github.com/dotnet/corefx/issues/7175#issuecomment-274889934
```C#
namespace System
{
    public struct TimeSpan
    {
        public static System.TimeSpan operator *(TimeSpan timeSpan, double factor);
        public static System.TimeSpan operator /(TimeSpan timeSpan, double divisor);

        public static TimeSpan operator *(double factor, TimeSpan timeSpan);
        public static double operator /(TimeSpan t1, TimeSpan t2);
    }
}
```

**Motivation:**
The extra 2 APIs proposal are mainly for supporting the commutative * and / operation (basically adding the same operation with flipped parameters order) and support / with time span.

## Naïve implementation

``` csharp
namespace System
{
    public struct TimeSpan
    {
        public static System.TimeSpan operator *(TimeSpan timeSpan, double factor)
        {
            return TimeSpan.FromTicks(timeSpan.Ticks * factor);
        }

        public static System.TimeSpan operator /(TimeSpan timeSpan, double divisor);
        {
            return TimeSpan.FromTicks(timeSpan.Ticks / divisor);
        }

    }
}
```

### PR DESCRIPTION
**Pull request by JonHanna**
Update refs and add tests.

Closes #7175

Won't pass CI until dotnet/coreclr#9804 is in.

### CODE REVIEW

**Comment by JonHanna** [comment]
@dotnet-bot help (curious if there's a command for skipping CI when I know it won't pass yet).

**Comment by joperezr** [comment]
> Won't pass CI until dotnet/coreclr#9804 is in.

Just FYI, even when that is in, you might still see failures on the Vertical uapaot Build, since it uses a different corelib. For that case, please update the apicompat baseline so that the build succeeds.

**Comment by danmosemsft** [comment]
@JonHanna I believe it's `@<thebot> skip ci please`

**Comment by JonHanna** [comment]
@joperezr is there a doc on how that works?

**Comment by joperezr** [comment]
> @JonHanna I believe it's @<thebot> skip ci please

I don't think you want to do this, or else you won't be able to turn the ci back on once you are ready to consume coreclr. @mmitche can confirm.

> @joperezr is there a doc on how that works?

I don't think so, but basically what you want to do is the following:
 - Do a vertical uapaot build: run `build.cmd -framework:uapaot -- /p:BaselineAllApiCompatError=true` from the root of the repo
 - make sure that the ApiCompat baseline for uapaot gets updated accordingly to say that the new api does not exist in corelib.
 - Add the changes of that baseline to your PR. We don't always update these baselines so you might see other changes on different baseline files, if so, just ignore them and only add the system.runtime one. I will go and do a general pass of the rest.

If you see any issues, just let me know.

**Comment by tarekgh** [comment]
The changes here LGTM. hopefully we'll get the new updated coreclr package soon to corefx. 

cc @weshaggard

**Comment by stephentoub** [comment]
@dotnet-bot test this please

**Comment by tarekgh** [comment]
@JonHanna I am seeing you have added the new APIs to the uap-oat baseline which is fine to get this change in but please port your coreclr changes to corert repo. let me know if you need help with that. Thanks. 

@stephentoub can we merge this one now? or is there anything else pending?

**Comment by tarekgh** [comment]
thanks @JonHanna. yes it should be straight forward copying the changes there.

**Pull request merged**
