### PR TITLE
Update signing targets

### PR DESCRIPTION
**Pull request by weshaggard**
Need to run the signing updates through CI to make sure the correct keys are used on all the different platforms. Once I get that validated I will update the commit to remove the debugging messages and merge.

### CODE REVIEW

**Comment by weshaggard** [comment]
Fixes https://github.com/dotnet/corefx/issues/16152

**Comment by weshaggard** [comment]
@mellinoe @ericstj could you guys PTAL

**Comment by weshaggard** [comment]
@dotnet-bot test Innerloop Windows_NT Debug Build and Test please

**Comment by sdmaclea** [comment]
I am seeing this type of error when I try to build corefx on Ubuntu 16.04 AMD64.

`
CSC : error CS7027: Error signing output with public key from file '/home/vmjenkins/workspace/Dotnet/Build_CoreCLR_Amd64/corefx/Tools/Open.snk' -- Assembly signing not supported. [/home/vmjenkins/workspace/Dotnet/Build_CoreCLR_Amd64/corefx/src/System.Diagnostics.DiagnosticSource/ref/System.Diagnostics.DiagnosticSource.csproj]
`

I suspect it is due to this PR.

**Comment by ericstj** [comment]
@sdmaclea, what do you see if you do a -v:Diag build of `src/System.Diagnostics.DiagnosticSource/ref/System.Diagnostics.DiagnosticSource.csproj`?  Check for the values of the RunningOnUnix and DelaySign properties, or just take the diag log and put it up on gist.github.com.

**Comment by sdmaclea** [comment]
I need more detailed directions, because I currently just build corefx to test coreclr.  ....  No idea what -v:Diag means.

I can confirm that I could build the commit before the merge commit.  And that I am using ./build.sh

**Comment by ericstj** [comment]
Run 
```
/home/vmjenkins/workspace/Dotnet/Build_CoreCLR_Amd64/corefx/Tools/MSBuild.sh /home/vmjenkins/workspace/Dotnet/Build_CoreCLR_Amd64/corefx/src/System.Diagnostics.DiagnosticSource/ref/System.Diagnostics.DiagnosticSource.csproj -flp:v=diag
```
Then copy the msbuild.log it generated.

**Comment by sdmaclea** [comment]
```
dotnet ./Tools/MSBuild.dll src/System.Diagnostics.DiagnosticSource/ref/System.Diagnostics.DiagnosticSource.csproj -flp:v=diag
Microsoft (R) Build Engine version 15.1.523.56541
Copyright (C) Microsoft Corporation. All rights reserved.

Build started 2/15/17 12:23:51 PM.
Project "/home/vmjenkins/workspace/Dotnet/corefx_build/src/System.Diagnostics.DiagnosticSource/ref/System.Diagnostics.DiagnosticSource.csproj" on node 1 (default targets).
GenerateAssemblyInfo:
Skipping target "GenerateAssemblyInfo" because all output files are up-to-date with respect to the input files.
CoreCompile:
Skipping target "CoreCompile" because all output files are up-to-date with respect to the input files.
CopyFilesToOutputDirectory:
  Copying file from "/home/vmjenkins/workspace/Dotnet/corefx_build/bin/obj/ref/System.Diagnostics.DiagnosticSource/4.0.2.0/netstandard/System.Diagnostics.DiagnosticSource.dll" to "/home/vmjenkins/workspace/Dotnet/corefx_build/bin/ref/System.Diagnostics.DiagnosticSource/4.0.2.0/netstandard/System.Diagnostics.DiagnosticSource.dll".
  System.Diagnostics.DiagnosticSource -> /home/vmjenkins/workspace/Dotnet/corefx_build/bin/ref/System.Diagnostics.DiagnosticSource/4.0.2.0/netstandard/System.Diagnostics.DiagnosticSource.dll
  Copying file from "/home/vmjenkins/workspace/Dotnet/corefx_build/bin/obj/ref/System.Diagnostics.DiagnosticSource/4.0.2.0/netstandard/System.Diagnostics.DiagnosticSource.pdb" to "/home/vmjenkins/workspace/Dotnet/corefx_build/bin/ref/System.Diagnostics.DiagnosticSource/4.0.2.0/netstandard/System.Diagnostics.DiagnosticSource.pdb".
BinPlaceReferenceAssembly:
  Copying file from "/home/vmjenkins/workspace/Dotnet/corefx_build/bin/ref/System.Diagnostics.DiagnosticSource/4.0.2.0/netstandard/System.Diagnostics.DiagnosticSource.dll" to "/home/vmjenkins/workspace/Dotnet/corefx_build/bin/ref/netcoreapp/System.Diagnostics.DiagnosticSource.dll".
  Copying file from "/home/vmjenkins/workspace/Dotnet/corefx_build/bin/ref/System.Diagnostics.DiagnosticSource/4.0.2.0/netstandard/System.Diagnostics.DiagnosticSource.pdb" to "/home/vmjenkins/workspace/Dotnet/corefx_build/bin/ref/netcoreapp/System.Diagnostics.DiagnosticSource.pdb".
  Copying file from "/home/vmjenkins/workspace/Dotnet/corefx_build/bin/ref/System.Diagnostics.DiagnosticSource/4.0.2.0/netstandard/System.Diagnostics.DiagnosticSource.dll" to "/home/vmjenkins/workspace/Dotnet/corefx_build/bin/pkg/netcoreapp/ref/System.Diagnostics.DiagnosticSource.dll".
  Copying file from "/home/vmjenkins/workspace/Dotnet/corefx_build/bin/ref/System.Diagnostics.DiagnosticSource/4.0.2.0/netstandard/System.Diagnostics.DiagnosticSource.pdb" to "/home/vmjenkins/workspace/Dotnet/corefx_build/bin/pkg/netcoreapp/ref/System.Diagnostics.DiagnosticSource.pdb".
  Copying file from "/home/vmjenkins/workspace/Dotnet/corefx_build/bin/ref/System.Diagnostics.DiagnosticSource/4.0.2.0/netstandard/System.Diagnostics.DiagnosticSource.dll" to "/home/vmjenkins/workspace/Dotnet/corefx_build/bin/ref/netstandard/System.Diagnostics.DiagnosticSource.dll".
  Copying file from "/home/vmjenkins/workspace/Dotnet/corefx_build/bin/ref/System.Diagnostics.DiagnosticSource/4.0.2.0/netstandard/System.Diagnostics.DiagnosticSource.pdb" to "/home/vmjenkins/workspace/Dotnet/corefx_build/bin/ref/netstandard/System.Diagnostics.DiagnosticSource.pdb".
Done Building Project "/home/vmjenkins/workspace/Dotnet/corefx_build/src/System.Diagnostics.DiagnosticSource/ref/System.Diagnostics.DiagnosticSource.csproj" (default targets).

Build succeeded.
    0 Warning(s)
    0 Error(s)

Time Elapsed 00:00:00.51

```

**Comment by sdmaclea** [comment]
./build.sh last few lines of output...
```
Build FAILED.

CSC : error CS7027: Error signing output with public key from file '/home/vmjenkins/workspace/Dotnet/corefx_build/Tools/Open.snk' -- Assembly signing not supported. [/home/vmjenkins/workspace/Dotnet/corefx_build/src/System.ValueTuple/ref/System.ValueTuple.csproj]
    0 Warning(s)
    1 Error(s)

Time Elapsed 00:01:27.92
Command execution failed with exit code 1.
```

**Comment by ericstj** [comment]
You probably need to do a rebuild of DiagnosticSource to get it to repro again.  Add -t:Rebuild to the previous commandline I shared.

**Comment by sdmaclea** [comment]
```
dotnet ./Tools/MSBuild.dll src/System.Diagnostics.DiagnosticSource/ref/System.Diagnostics.DiagnosticSource.csproj -flp:v=diag -t:Rebuild
Microsoft (R) Build Engine version 15.1.523.56541
Copyright (C) Microsoft Corporation. All rights reserved.

Build started 2/15/17 1:10:24 PM.
Project "/home/vmjenkins/workspace/Dotnet/corefx_build_amd64/src/System.Diagnostics.DiagnosticSource/ref/System.Diagnostics.DiagnosticSource.csproj" on node 1 (Rebuild target(s)).
GenerateAssemblyInfo:
Skipping target "GenerateAssemblyInfo" because all output files are up-to-date with respect to the input files.
CoreCompile:
  /home/vmjenkins/workspace/Dotnet/corefx_build_amd64/Tools/dotnetcli/dotnet /home/vmjenkins/workspace/Dotnet/corefx_build_amd64/Tools/csc.exe /noconfig /nowarn:1701,1702 /nostdlib+ /warn:4 /define:DEBUG;TRACE;DEBUGRESOURCES;SIGNED /reference:/home/vmjenkins/workspace/Dotnet/corefx_build_amd64/bin/ref/netstandard/netstandard.dll /reference:/home/vmjenkins/workspace/Dotnet/corefx_build_amd64/bin/ref/netstandard/System.Runtime.dll /debug+ /debug:Portable /delaysign- /keyfile:/home/vmjenkins/workspace/Dotnet/corefx_build_amd64/Tools/Open.snk /optimize- /out:/home/vmjenkins/workspace/Dotnet/corefx_build_amd64/bin/obj/ref/System.Diagnostics.DiagnosticSource/4.0.2.0/netstandard/System.Diagnostics.DiagnosticSource.dll /ruleset:/home/vmjenkins/workspace/Dotnet/corefx_build_amd64/CodeAnalysis.ruleset /target:library /warnaserror+ /utf8output /analyzer:/home/vmjenkins/workspace/Dotnet/corefx_build_amd64/Tools/analyzers/Microsoft.DotNet.CodeAnalysis.dll System.Diagnostics.DiagnosticSource.cs System.Diagnostics.DiagnosticSourceActivity.cs /home/vmjenkins/workspace/Dotnet/corefx_build_amd64/bin/obj/ref/System.Diagnostics.DiagnosticSource/4.0.2.0/netstandard/_AssemblyInfo.cs @/home/vmjenkins/workspace/Dotnet/corefx_build_amd64/Tools/checksum.rsp
  Using shared compilation with compiler from directory: /home/vmjenkins/workspace/Dotnet/corefx_build_amd64/Tools/dotnetcli
  Shared compilation failed; falling back to tool: /home/vmjenkins/workspace/Dotnet/corefx_build_amd64/Tools/dotnetcli/dotnet
CSC : error CS7027: Error signing output with public key from file '/home/vmjenkins/workspace/Dotnet/corefx_build_amd64/Tools/Open.snk' -- Assembly signing not supported. [/home/vmjenkins/workspace/Dotnet/corefx_build_amd64/src/System.Diagnostics.DiagnosticSource/ref/System.Diagnostics.DiagnosticSource.csproj]
Done Building Project "/home/vmjenkins/workspace/Dotnet/corefx_build_amd64/src/System.Diagnostics.DiagnosticSource/ref/System.Diagnostics.DiagnosticSource.csproj" (Rebuild target(s)) -- FAILED.

Build FAILED.

"/home/vmjenkins/workspace/Dotnet/corefx_build_amd64/src/System.Diagnostics.DiagnosticSource/ref/System.Diagnostics.DiagnosticSource.csproj" (Rebuild target) (1) ->
(CoreCompile target) -> 
  CSC : error CS7027: Error signing output with public key from file '/home/vmjenkins/workspace/Dotnet/corefx_build_amd64/Tools/Open.snk' -- Assembly signing not supported. [/home/vmjenkins/workspace/Dotnet/corefx_build_amd64/src/System.Diagnostics.DiagnosticSource/ref/System.Diagnostics.DiagnosticSource.csproj]

    0 Warning(s)
    1 Error(s)

Time Elapsed 00:00:01.10
```

**Comment by weshaggard** [comment]
For some reason your command line is passing `/delaysign-` to the compiler when it should be passing `/delaysign+`.  

Actually I think I now why this is happening which is you have an stale Tools folder. Can you please either do a full clean to rebuild everything or just copy everything from "Tools-Override" to "Tools" directory to refresh the targets files and try again.

**Comment by sdmaclea** [comment]
OK when I did a full clean build the problem resolved for me.

```
git clean -x
rm -rf Tools bin packages
```

**Pull request merged**
