### PR TITLE
Ensure "frameworks" in project.json and remove packages.configs

### PR DESCRIPTION
**Pull request by ericstj**
New projects were introduced after my change https://github.com/dotnet/corefx/commit/eb35a304c7e89e8b4335ed13c5d23706360d49a4 to move completely to project.json.

I also missed the one *.vbproj in the repo (sorry!)

### CODE REVIEW

**Comment by ericstj** [comment]
Larger version of https://github.com/dotnet/corefx/pull/1713 that uses a tool to automate the change.  /cc @akoeplinger @stephentoub

**Comment by akoeplinger** [comment]
LGTM :+1:

**Comment by JeremyKuhne** [comment]
LGTM

**Comment by ericstj** [comment]
Thanks!

**Pull request merged**
