### PR TITLE
Update System.Memory package description to be complete

### PR DESCRIPTION
**Pull request by AlexRadch**
See https://github.com/dotnet/corefx/issues/27481

### CODE REVIEW

**Comment by AlexRadch** [comment]
@dotnet-bot test Linux x64 Release Build please

**Comment by AlexRadch** [comment]
This PR is reverted should I send it again?

**Comment by stephentoub** [comment]
Aren't all of the changes still in master?

**Comment by AlexRadch** [comment]
@stephentoub No I repeated this PR https://github.com/dotnet/corefx/pull/27932/files

**Pull request merged**
