### PR TITLE
Move the SendReceive tests out of [OuterLoop].

### PR DESCRIPTION
**Pull request by pgavlin**
With the Windows fix in #3575, these tests should be stable enough to
run per-PR in CI.

### CODE REVIEW

**Comment by pgavlin** [comment]
@cipop @davidsh @stephentoub PTAL

**Comment by stephentoub** [comment]
LGTM

**Comment by CIPop** [comment]
LGTM

**Comment by pgavlin** [comment]
@dotnet-bot test this please

**Comment by pgavlin** [comment]
@dotnet-bot test this please

**Comment by ellismg** [comment]
@dotnet-bot test this please

**Comment by stephentoub** [comment]
@dotnet-bot test this please

**Pull request merged**
