### PR TITLE
Try to enable SignedXml on UAP

### PR DESCRIPTION
**Pull request by krwq**
contract is building against both netcoreapp and uap while tests and source only netcoreapp. This is changing that to build against both.

My local build is working and local tests are failing for unrelated reasons

### CODE REVIEW

**Comment by krwq** [comment]
@joperezr I was getting random unrelated failures for uapaot, i'd rather have CI check this than fighting with local build

**Comment by joperezr** [comment]
ok, but please do run UpdateVSConfigurations and check in the changes of the csprojs in this PR as well

**Comment by krwq** [comment]
@joperezr which project do I run that on? it tells me that target does not exist when i run it on any csproj in my project?

**Comment by joperezr** [comment]
you  run it from the root, on the build.proj

**Comment by krwq** [comment]
@joperezr I got larger diff and something started failing after this

**Comment by krwq** [comment]
@dotnet-bot test CROSS Check please

**Comment by krwq** [comment]
@dotnet-bot test CROSS Check please

**Comment by krwq** [comment]
@dotnet-bot test this please

**Comment by joperezr** [comment]
> I got larger diff and something started failing after this

yeah, I've tried to have people running this in all PRs that change Configurations.props but I have missed some which is why running it changed more than the expected projects.

**Comment by krwq** [comment]
fixed merge conflict with VS configuration

**Comment by krwq** [comment]
@dotnet-bot test Innerloop OSX10.12 Release x64 Build and Test please

**Comment by joperezr** [comment]
@krwq which PR will go in then, this one? or the netstandard one you have open as well?

**Comment by krwq** [comment]
@joperezr Let's merge this one for now since I haven't figured out if we want to target netstandard and there are people waiting for package working on UWP - OSX builds are super slow yesterday and today

**Comment by krwq** [comment]
@dotnet-bot test Innerloop OSX10.12 Release x64 Build and Test please

**Pull request merged**
