### PR TITLE
Enabling perf tests execution on linux via helix

### PR DESCRIPTION
**Pull request by dsgouda**
Referencing latest version of build tools with script changes that should allow execution of perf tests on linux machines via helix
Referencing latest xunit performance changes which contain the cross-plat cli libraries that can be run on linux
@lt72 @ericstj @MattGal

### CODE REVIEW

**Comment by ellismg** [comment]
@dotnet-bot test Innerloop OSX Debug Build and Test please (downloading the nuget package for buildtools failed).

**Comment by ellismg** [comment]
@stephentoub Is the failure [here](http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/master/job/ubuntu14.04_debug_prtest/994/testReport/junit/System.Net.Http.Functional.Tests/HttpClientHandler_SslProtocols_Test/GetAsync_AllowedSSLVersion_Succeeds_acceptedProtocol__Tls_/) interesting to you?  It looks like curl failed to send the request, but we should have been talking to the loopback server?

**Comment by ellismg** [comment]
@dotnet-bot test Innerloop Ubuntu14.04 Debug Build and Test please (curl error)

**Comment by stephentoub** [comment]
> Is the failure here interesting to you? It looks like curl failed to send the request, but we should have been talking to the loopback server?

Yeah, I'm not sure what's going on here.  I'm concerned there's actually a product bug in SslStream, but I'm not sure where yet.

**Comment by ellismg** [comment]
Opened #8444

**Comment by ellismg** [comment]
@dotnet-bot test Innerloop OSX Debug Build and Test please (package restore failure).

**Comment by dsgouda** [comment]
@MattGal @lt72 PTAL

**Comment by dsgouda** [comment]
@dotnet-bot Test this please

**Comment by MattGal** [comment]
LGTM once tests pass

**Pull request merged**
