### PR TITLE
Expose SpinWait.SpinOnce(int sleep1Threshold) overload

### PR DESCRIPTION
**Pull request by kouvel**
Depends on https://github.com/dotnet/coreclr/pull/18204

To allow customizing the spin count threshold for Sleep(1) usage, and to allow disabling the use of Sleep(1).

API review: https://github.com/dotnet/corefx/issues/29623
Part of fix for https://github.com/dotnet/corefx/issues/29595

### CODE REVIEW

**Comment by Anipik** [comment]
@dotnet-bot test this please

**Comment by karelz** [comment]
@kouvel do you have plans to finish the PR in near future? If not, let's close it, until you have time ... Thanks!

**Comment by stephentoub** [comment]
@dotnet-bot test this please

**Comment by kouvel** [comment]
@karelz this PR was waiting for a dependency PR in coreclr that was only recently merged, waiting for that to reach corefx

**Comment by kouvel** [comment]
@dotnet-bot test this please

**Comment by kouvel** [comment]
Failure in Linux x64 Release Build is duplicate of https://github.com/dotnet/corefx/issues/31271

**Pull request merged**
