### PR TITLE
Update unix-instructions.md

### PR DESCRIPTION
**Pull request by CIPop**
One change based on my (short) experience with Ubuntu 16 and Bash on Windows.
Also linking to the issues with Bash on Windows.

@mellinoe, @stephentoub, @joshfree PTAL

### CODE REVIEW

**Comment by mellinoe** [comment]
Looks fine to me. Ubuntu 16.10 does use libicu57, by the way. So we might want to say "Ubuntu 16.04" instead of "Ubuntu 16.x" here. Either way, it's a minor nit. It's kind of futile trying to list out the pre-requisites on every distro we support.

**Comment by danmosemsft** [comment]
Yes I should have said 'libicu55 or libicu57'..

**Comment by CIPop** [comment]
Thanks @mellinoe @danmosemsft. I've updated the documentation. As far as I understand, the LTS versions are the most important. 16.04 is what one gets by default in WSL as well.

**Comment by danmosemsft** [comment]
@CIPop it's probably obvious, but you don't need to wait for CI to commit a change to an .md file.

**Comment by CIPop** [comment]
Thanks @mellinoe @danmosemsft for the review!

**Pull request merged**
