### PR TITLE
Marking {ReadOnly}Memory as readonly structs

### PR DESCRIPTION
**Pull request by ahsonkhan**
Fixes issue https://github.com/dotnet/corefx/issues/23809
https://github.com/dotnet/coreclr/pull/13886#issuecomment-328285541

Related PR for coreclr: https://github.com/dotnet/coreclr/pull/14180

cc @KrzysztofCwalina, @VSadov

### CODE REVIEW

**Comment by KrzysztofCwalina** [comment]
looks good.

**Comment by ahsonkhan** [comment]
@dotnet-bot test Windows x64 Debug Build

**Comment by ahsonkhan** [comment]
@dotnet-bot test UWP CoreCLR x64 Debug Build

**Comment by stephentoub** [comment]
@dotnet/dnceng, the UWP builds appear to down and have been for a while.  Can you help?

**Comment by markwilkie** [comment]
@stephentoub The problem is likely https://github.com/dotnet/core-eng/issues/1816  @ChadNedzlek, can you get an update from Azure please?

**Comment by stephentoub** [comment]
@dotnet-bot test UWP CoreCLR x64 Debug Build please

**Pull request merged**
