### PR TITLE
Add support for JsonSnakeNamingPolicy

### LINKED ISSUE #782: Add snake_case support for System.Text.Json
Contents below were taken from @khellang, thanks!

## API Proposal
Add additional casing support for `System.Text.Json`, based [on this comment](https://github.com/dotnet/runtime/issues/782#issuecomment-1133247911).

```diff
namespace System.Text.Json;

public partial class JsonNamingPolicy
{
    public static JsonNamingPolicy CamelCase { get; }
+    public static JsonNamingPolicy SnakeLowerCase { get; }
+    public static JsonNamingPolicy SnakeUpperCase { get; }
+    public static JsonNamingPolicy KebabLowerCase { get; }
+    public static JsonNamingPolicy KebabUpperCase { get; }
}

public enum JsonKnownNamingPolicy
{
    Unspecified = 0,
    CamelCase = 1,
+    SnakeLowerCase = 2,
+    SnakeUpperCase = 3,
+    KebabLowerCase = 4,
+    KebabUpperCase = 5,
}
```
## Behavior Proposal
I propose the same behavior as Newtonsoft.Json, just like the existing camel case behavior. The implementation is here and the tests are here.

## Other Comments
I think snake case naming is pretty common, especially in the Ruby world, and should be supported out of the box. GitHub's API is probably the most popular example using this naming convention off the top of my head.

## Implements
See: dotnet/corefx#40003

### LINKED ISSUE #39564: Add UnderScoreCase support for System.Text.Json
Can you add UnderScoreCase in System.Text.Json?
This naming policy is also common used.

### PR DESCRIPTION
**Pull request by hez2010**
* Add JsonSnakeNamingPolicy support
* Add tests for JsonSnakeNamingPolicy

Fixed #39564

### CODE REVIEW

**Comment by Gnbrkm41** [comment]
Shouldn't this go through the API review process though, no?

**Comment by hez2010** [comment]
@Gnbrkm41 It had been added to the 5.0 milestone so I think that I can implement it in advance :) 
And it's really useful in json serialization/deserialization, if there's no snake case in System.Text.Json, many people who migrate from Newtonsoft.Json to System.Text.Json would face breaking changes and they will have to implement it by themselves.

**Comment by Gnbrkm41** [comment]
Being added to milestones doesn't mean it's approved; every single thing about the public APIs should be thoroughly discussed, [marked as ready for review](https://github.com/dotnet/corefx/issues?q=is%3Aopen+is%3Aissue+label%3Aapi-ready-for-review) when the area owner thinks it's solid enough, reviewed by the review team [then approved](https://github.com/dotnet/corefx/issues?q=is%3Aopen+is%3Aissue+label%3Aapi-approved) in order to actually be implemented.

The Pull Request section of the API review process document says:
> Pull requests against corefx shouldn't be submitted before getting approval. Also, we don't want to get work in progress (WIP). The reason being that we want to reduce the number pending PRs so that we can focus on the work the community expects we take action on.

**Comment by danmosemsft** [comment]
I'm going to close for reason mentioned above. Let's continue discussion on the issue. Thanks.

**Comment by tcfialho** [comment]
Those who do nothing love to keep the discussion open.
Typical case of those who don't do it and don't let it do it.

**Pull request closed without merging**
