### PR TITLE
Remove System.ServiceModel.Dispatcher namespace to fix reflection block issue in Wcf

### PR DESCRIPTION
**Pull request by khdang**
Type 'System.ServiceModel.Dispatcher.FaultFormatter.OperationFault' is blocked from reflection in NetNative by the toolchain.
Reflection on System.Xml.XmlSerializer is blocked which causes overzealous blocking for the System.ServiceModel.Dispatcher namespace as well.
Since serialization doesn't use this namespace, this change removes it together with XmlSchema.cs.

cc: @hongdai @morganbr @AlexGhiondea @SGuyGe @zhenlan @shmao

### CODE REVIEW

**Comment by morganbr** [comment]
LGTM if you've verified it fixes the OperationFault issue

**Comment by AlexGhiondea** [comment]
LGTM

**Comment by hongdai** [comment]
Just figured out there was another dll using the same namespace. So this fix will NOT unblock the OperationFault issue.

**Comment by stephentoub** [comment]
@dotnet-bot test this please

**Comment by stephentoub** [comment]
@dotnet-bot test this please

**Comment by stephentoub** [comment]
What's the status of this PR?  I see the comment "So this fix will NOT unblock the OperationFault issue."... should this PR be closed then?

**Comment by khdang** [comment]
Yes it should be closed. This was intended to fix OperationFault issue but it turns out that the change in this PR is not sufficient.

**Pull request closed without merging**
