### PR TITLE
Remove null checks before GetValueOrDefault

### PR DESCRIPTION
**Pull request by James-Ko**
Separated from PR #2318. Free perf.

### CODE REVIEW

**Comment by stephentoub** [comment]
> Free perf

Can you please share your perf tests and results?  What's the impact when all values are null?  When some are null?  When none are null?  Etc.

**Comment by stephentoub** [comment]
cc: @VSadov

**Comment by mikedn** [comment]
> Can you please share your perf tests and results? What's the impact when all values are null? When some are null? When none are null? Etc.

This approach should be faster if the number of nulls in the source is low. `GetValueOrDefault` "cheats" and returns the `value` field without actually checking `hasValue`, that avoids a bunch of things: a memory load, a 0 test and a branch.

If the number of nulls is high then this will likely be slower, especially in the decimal case. `add` operations that previously were simply skipped now how to be done.

Let's see what benchmarks will say :)

**Comment by James-Ko** [comment]
Just finished writing the test. [Here](https://gist.github.com/James-Ko/3741a5024ffbc6e8b3ce) is the test ([ideone[(http://ideone.com/nicJBg)), [here](https://gist.github.com/James-Ko/9ff5f1b166f77e839d75) are the old results, [here](https://gist.github.com/James-Ko/99ec130bb94073ca0d9f) are the new ones.

**Comment by stephentoub** [comment]
Thanks for sharing.  Based purely on the data you shared, I don't think this is a change we should take.  Where there was an improvement, it was typically significantly less than 1%, and there were plenty of regressions, including several greater than 1%, and one almost 5%.

**Comment by James-Ko** [comment]
Alright, I understand. Thanks.

**Pull request closed without merging**
