### PR TITLE
Extend 'Capture' to expose '.Span' in addition to '.Value'.

### PR DESCRIPTION
**Pull request by electricessence**

### CODE REVIEW

**Comment by jkotas** [comment]
cc @ViktorHofer

**Comment by ViktorHofer** [comment]
@electricessence thanks for your contribution but such a change must go through an official api review first. Also you need to expose the new API in the ref assembly and add tests. Most of this is already done in my PR https://github.com/ViktorHofer/corefx/pull/3 and can be factored out.

**Comment by electricessence** [comment]
Ok sorry, it's my first time in the corefx repo.  Great work in your PR thank you!

**Comment by ViktorHofer** [comment]
No problem at all!

**Pull request closed without merging**
