### PR TITLE
Expose  Marshall.LoadLibrary API

### PR DESCRIPTION
**Pull request by ericstj**
@swaroop-sridhar and I worked on this to expose the LoadLibrary api from System.Runtime.InteropServices reference assembly.  

https://github.com/dotnet/coreclr/pull/20871

### CODE REVIEW

**Comment by swaroop-sridhar** [comment]
Here's the API review, showing approved APIs

**Comment by jkotas** [comment]
Tests?

**Comment by ericstj** [comment]
@jkotas I assumed those were in coreclr already.  If not @swaroop-Sridhar could you create a PR with tests and cherry pick the change we worked on?

**Comment by swaroop-sridhar** [comment]
@dotnet-bot test Windows x86 Release Build

**Pull request merged**
