### PR TITLE
Adding netcoreapp1.2corert configuration to System.Reflection.Primitives

### PR DESCRIPTION
**Pull request by SedarG**
@jkotas, PTAL

/cc @dotnet/corert-contrib

### CODE REVIEW

**Comment by SedarG** [comment]
@dotnet-bot please test 
Innerloop OSX Debug Build and Test and 
Innerloop OSX Release Build and Test

**Comment by SedarG** [comment]
@dotnet-bot please test Innerloop OSX Release Build and Test

**Comment by weshaggard** [comment]
cc @joperezr

**Comment by karelz** [comment]
@weshaggard @joperezr do you want to merge it or wait post dev/eng RI?

**Pull request merged**
