### PR TITLE
Regenerating reference sources in order to reorder enum fields

### PR DESCRIPTION
**Pull request by tannergooding**
CC. @ericstj, @safern, @stephentoub, @danmosemsft 

This picks up the GenAPI change to make enum fields ordered numerically, rather than alphabetically. This should make it easier to diff against most implementations given that this is how they are typically ordered there.

### CODE REVIEW

**Comment by tannergooding** [comment]
Just as a note. I generated these by first running GenAPI before the enum field change in order to generate a new baseline. This picks up a number of places where we currently differ (https://github.com/dotnet/corefx/issues/29737). I then reran it again using the new GenAPI version with the enum field change and had to manually fixup the following files (so they might warrant a slightly closer inspection):
```csharp
src/System.ComponentModel.TypeConverter/ref/System.ComponentModel.TypeConverter.cs
src/System.Data.SqlClient/ref/System.Data.SqlClient.cs
src/System.Diagnostics.DiagnosticSource/ref/System.Diagnostics.DiagnosticSource.cs
src/System.Diagnostics.EventLog/ref/System.Diagnostics.EventLog.cs
src/System.Diagnostics.TraceSource/ref/System.Diagnostics.TraceSource.cs
src/System.Net.Primitives/ref/System.Net.Primitives.cs
src/System.Net.ServicePoint/ref/System.Net.ServicePoint.cs
src/System.Runtime.Extensions/ref/System.Runtime.Extensions.cs
src/System.Runtime.InteropServices/ref/System.Runtime.InteropServices.cs
src/System.Runtime/ref/System.Runtime.cs
src/System.Security.Cryptography.Pkcs/ref/System.Security.Cryptography.Pkcs.cs
src/System.Security.Cryptography.Primitives/ref/System.Security.Cryptography.Primitives.cs
src/System.Security.Permissions/ref/System.Security.Permissions.cs
src/System.Security.Principal.Windows/ref/System.Security.Principal.Windows.cs
src/System.Xml.ReaderWriter/ref/System.Xml.ReaderWriter.cs
```

The end result is this PR which just contains the enum field changes.

**Comment by tannergooding** [comment]
Also CC. @ahsonkhan

**Comment by ahsonkhan** [comment]
Should we hold off on this until Monday? Doesn't seem critical enough and is a bit of a churn.

**Comment by danmosemsft** [comment]
Yeah please let's wait until after the merge on Monday.

**Comment by tannergooding** [comment]
@danmosemsft, this should be good to merge now, correct (provided I finish getting sign-off, naturally)?

**Comment by danmosemsft** [comment]
Yep!

**Comment by tannergooding** [comment]
@ericstj, would it actually be viewable, since you would resolve the implementation assembly at runtime, rather than the reference assembly?

I guess you could see it if you explicitly loaded the reference assembly, but I doubt that is the common scenario...

**Pull request merged**
