### PR TITLE
Moving the Windows Performance runs from Server 2012 to Server 2016.

### PR DESCRIPTION
**Pull request by jorive**

### CODE REVIEW

**Comment by jorive** [comment]
@dotnet/rap-team PTAL

**Comment by jorive** [comment]
@dotnet-bot test ci please

**Comment by danmosemsft** [comment]
@jorive have you done a run on both and determined that it makes no difference to our numbers? Or will you re run old numbers?

**Comment by jorive** [comment]
@danmosemsft We have few options here. I will be updating the pool on the other branches too, and once they are updated a new run will be executed and uploaded, then we could:
1. Set the baseline to the results generated by the CI on the release/1.1.0 branch
2. We can manually rerun the v1.1 runs on the new OS and re-upload the new data
3. Master is already 2.0+, and it might make sense to set the release/2.0.0 branch as the new baseline (we could keep the 1.1 too, but it might be too noisy on the plots)

I'm open to suggestions :)

**Comment by danmosemsft** [comment]
I think release/2.0 should be the baseline now, but we should have release/1.1 numbers in there (just as the oldest datapoint). Can we do that?

**Comment by jorive** [comment]
@danmosemsft Yes, we can do that.

**Pull request merged**
