### PR TITLE
[x86/Linux] Initial support of x86 cross build

### PR DESCRIPTION
**Pull request by lucenticus**
This PR adds initial support of cross building native parts of CoreFX for Linux x86 platform.
Related issue: https://github.com/dotnet/coreclr/issues/8188

### CODE REVIEW

**Comment by lucenticus** [comment]
\CC: @seanshpark @parjong @Dmitri-Botcharnikov

**Comment by lucenticus** [comment]
You can test this PR by using following commands
```
sudo ./cross/build-rootfs.sh x86
./build-native.sh -debug -buildArch=x86 -- verbose cross

```

**Comment by lucenticus** [comment]
I've added commit which adds support of native build using` src/Native/build-native.sh` script

**Comment by lucenticus** [comment]
@dotnet-bot test this please

**Comment by mellinoe** [comment]
@lucenticus I'd like to get this merged in, but I'm not sure how to test it. The instructions above don't work for me, because I seem to be missing some packages. Is there a more complete set of instructions that I can follow to try and validate this?

**Comment by lucenticus** [comment]
@mellinoe  Probably, you have install packages from cross building instruction (https://github.com/dotnet/corefx/blob/master/Documentation/building/cross-building.md)
`sudo apt-get install qemu qemu-user-static binfmt-support debootstrap`
Could you provide build log for better understanding of this issue?

**Comment by mellinoe** [comment]
@lucenticus Thanks for the pointer, that was a lot easier than I expected. This looks good to me now. I added a commit to resolve the merge conflict (in the `usage()` function of build-rootfs.sh). I'll merge this once CI shows up green again.

**Pull request merged**
