### PR TITLE
Fix project reference

### PR DESCRIPTION
**Pull request by Maxwe11**
Just fix project reference

~~Considered scenario: just forked or just cleaned repo.~~
~~Test projects of these solutions:~~
~~System.Collections.sln~~
~~System.ComponentModel.EventBasedAsync.sln~~
~~System.ComponentModel.sln~~
~~System.Console.sln~~
~~System.Diagnostics.Process.sln~~
~~System.IO.FileSystem.DriveInfo.sln~~
~~System.Runtime.Numerics.sln~~
~~System.Text.Encoding.CodePages.sln~~

~~depends on XunitTraitsDiscoverers project but solutions itself doesn't includes XunitTraitsDiscoverers~~
~~so building whole solution in VS will fail.~~

### CODE REVIEW

**Comment by weshaggard** [comment]
This is issue https://github.com/dotnet/corefx/issues/745. Also please read the discussion on https://github.com/dotnet/corefx/issues/770 if you haven't already. I think we would prefer another solution as opposed to having to have the project reference in all our projects. Right now I'm currently leaning towards having this library included in either our buildtools package or in its own package to become a package dependency instead of a project dependency.

**Comment by Maxwe11** [comment]
ok @weshaggard, I'll remove first commit and rename PR

**Comment by mellinoe** [comment]
This looks fine to me, but is it related to #745?

**Comment by Maxwe11** [comment]
@mellinoe originally PR was related to 745 but not now

**Comment by mellinoe** [comment]
Okay, that makes sense, thanks for the fix :+1:

**Pull request merged**
