### PR TITLE
Enable Encoding netstandard1.7 on Linux

### PR DESCRIPTION
**Pull request by tarekgh**
The full functionality now existed in coreclr package which allow us to enable the encoding tests on corefx

### CODE REVIEW

**Comment by tarekgh** [comment]
#11858

**Comment by tarekgh** [comment]
CC @danmosemsft @weshaggard @stephentoub

**Comment by danmosemsft** [comment]
:shipit:

**Comment by tarekgh** [comment]
test Innerloop CentOS7.1 Debug Build and Test please

**Pull request merged**
