### PR TITLE
Add test coverage for EqualityComparer

### PR DESCRIPTION
**Pull request by jamesqo**
This is a moderately large PR (750 lines), so it's best to review commit-by-commit.

It contains several changes, including:

- Add generic & type-specific tests for EqualityComparer
  - Covers all of the codepaths [here] and a few more, including
    - byte
    - IEquatable
    - Nullable {bytes,ints,enums}
    - short enums
    - sbyte enums
    - int enums
    - long enums
    - structs that don't override Equals/GetHashCode
    - regular, non-equatable objects
  - Ensure left-hand `Equals` is called first for 2 non-null iputs
- Move some enum types from `EnumTests` to a test folder in Common, so other tests can use them
  - Remove `IntEnum`, `UIntEnum` types introduced in #11074 in favor of @hughbe's types
    - Rename some things accordingly, `Long` -> `Int64`, `Int` -> `Int32`
- Add a few more interesting test cases to the generic specializations, incl. `IntPtr?`, `UIntPtr?`, equatable types
  - Renamed test classes from `...ComparerTests` to `...ComparersTests`
- Prefix Comparer generic tests with `Comparer_` and EqualityComparer generic tests with `EqualityComparer_` to avoid name clashes and get better stack traces

The bulk of the PR is in `EqualityComparer.Tests.cs` and `EqualityComparer.Generic.Tests.cs`.

/cc @stephentoub, @hughbe

### CODE REVIEW

**Comment by stephentoub** [comment]
Thanks for adding these, @jamesqo. I've been traveling and am behind on reviewing PRs, but will get to this (and Hugh's PRs) this week.

**Comment by jamesqo** [comment]
@stephentoub Sure, no problem. Thanks for letting me know.

**Comment by hughbe** [comment]
Brill, enjoy travelling!

**Comment by stephentoub** [comment]
@dotnet-bot Test Innerloop OSX Debug Build and Test please (build hang)
@dotnet-bot Test Innerloop Windows_NT Debug Build and Test please (DNS failure that's since been fixed)

**Comment by stephentoub** [comment]
I'm going to go ahead and merge; my nits can be addressed subsequently if desired.

**Pull request merged**
