### PR TITLE
Finished incorporating API review feedback for System.Text.Encodings.Web

### PR DESCRIPTION
**Pull request by KrzysztofCwalina**
With the exception of feedback/workitems that are are being debated or researched:
1. Research ability to encode UTF8 text buffers
2. Come up with a better namespace name

After this is checked in, we will start moving ASP.NET to these APIs

### CODE REVIEW

**Comment by KrzysztofCwalina** [comment]
cc: @Eilon, @GrabYourPitchforks, @terrajobst

**Comment by jasonwilliams200OK** [comment]
ASPE.NET => American Society for Precision Engineering
For a moment, I thought that has something to do with ASP.NET :smile:

**Comment by Eilon** [comment]
:shipit:

**Comment by ellismg** [comment]
What do you think about putting TextEncoder and TextEncoderSettings in the System.Text.Encodings namespace (and keeping the concrete encoders in System.Text.Encodings.Web?)

**Comment by KrzysztofCwalina** [comment]
@jasonwilliams200OK, good catch :-)

**Comment by KrzysztofCwalina** [comment]
@ellismg, I would prefer to come up with a namespace name that can contain all these types and not be web specific. The probability of these abstractions actually being used for non-web encoders is not super high, the number of types is low, and so probably not worth having them distributed across namespaces.

**Pull request merged**
