### PR TITLE
Merge master and use immutable collections 1.1.36 in metadata

### PR DESCRIPTION
**Pull request by tmat**

### CODE REVIEW

**Comment by tmat** [comment]
@stephentoub Any ideas why this failed?

**Comment by tmat** [comment]
@dotnet-bot retest this please

**Comment by tmat** [comment]
I see what the problem is now:
```
=== TEST EXECUTION SUMMARY ===
     System.IO.Pipes.Tests  Total: 98, Errors: 0, Failed: 0, Skipped: 0, Time: 0.350s
  Discovering: System.IO.FileSystem.DriveInfo.Tests
  
  Unhandled Exception: System.Exception: The handle is invalid. (Exception from HRESULT: 0x80070006 (E_HANDLE))
     at System.Threading.TimerQueue.DeleteAppDomainTimer(IntPtr handle)
     at System.Threading.TimerQueue.AppDomainTimerSafeHandle.ReleaseHandle()
     at System.Runtime.InteropServices.SafeHandle.InternalFinalize()
     at System.Runtime.InteropServices.SafeHandle.Dispose(Boolean disposing)
     at System.Runtime.InteropServices.SafeHandle.Finalize()
  Discovered:  System.IO.FileSystem.DriveInfo.Tests
  Starting:    System.IO.FileSystem.DriveInfo.Tests
  Finished:    System.IO.FileSystem.DriveInfo.Tests
  
  === TEST EXECUTION SUMMARY ===
     System.IO.FileSystem.DriveInfo.Tests  Total: 6, Errors: 0, Failed: 0, Skipped: 0, Time: 0.183s
d:\j\workspace\dotnet_corefx_windows_debug_prtest\packages\Microsoft.DotNet.BuildTools.1.0.25-prerelease-00050\lib\tests.targets(101,5): warning MSB3073: The command "corerun.exe xunit.console.netcore.exe System.IO.Pipes.Tests.dll  -xml testResults.xml -notrait category=nonwindowstests  -notrait category=OuterLoop -notrait category=failing " exited with code -532462766. [d:\j\workspace\dotnet_corefx_windows_debug_prtest\src\System.IO.Pipes\tests\System.IO.Pipes.Tests.csproj]
d:\j\workspace\dotnet_corefx_windows_debug_prtest\packages\Microsoft.DotNet.BuildTools.1.0.25-prerelease-00050\lib\tests.targets(112,5): error : One or more tests failed while running tests from 'System.IO.Pipes.Tests' please check log for details! [d:\j\workspace\dotnet_corefx_windows_debug_prtest\src\System.IO.Pipes\tests\System.IO.Pipes.Tests.csproj]
  System.Runtime.Numerics.Tests -> d:\j\workspace\dotnet_corefx_windows_debug_prtest\bin\Windows_NT.AnyCPU.Debug\System.Runtime.Numerics.Tests\System.Runtime.Numerics.Tests.dll
  System.Text.Encodings.Web.Tests -> d:\j\workspace\dotnet_corefx_windows_debug_prtest\bin\Windows_NT.AnyCPU.Debug\System.Text.Encodings.Web.Tests\System.Text.Encodings.Web.Tests.dll
  xUnit.net console test runner (32-bit .NET Core)
  Copyright (C) 2014 Outercurve Foundation.
```

**Comment by stephentoub** [comment]
I opened #1841 for the SafeHandle failure.

**Comment by stephentoub** [comment]
@dotnet-bot test this please

**Pull request merged**
