### PR TITLE
Removing obsolete documentation references in API comments

### PR DESCRIPTION
**Pull request by alphonsekurian**
Removing obsolete documentation references in API comments. @Petermarcu

### CODE REVIEW

**Comment by stephentoub** [comment]
Some of these may be ok to remove, but many of them are not obsolete.  For example, all of the ones in System.Threading.Tasks.Dataflow should be valid.

**Comment by Petermarcu** [comment]
@stephentoub, After talking to our doc team, they didn't think any of these were used anymore. Do you know of them being used in any way anymore?

**Comment by Petermarcu** [comment]
Ah, I see some failures in CI. It looks like the failures are in dataflow. Maybe this is too aggressive a change and we shouldn't remove items pointing to xml files but instead just uex files?

**Comment by Petermarcu** [comment]
@alphonsekurian, Looks like I'm right. the ones that refer to docs in src/XmlDocs from the root of the library project need to be left alone. Example is here:
https://github.com/alphonsekurian/corefx/tree/master/src/System.Threading.Tasks.Dataflow/src/XmlDocs

**Comment by stephentoub** [comment]
Replaced by https://github.com/dotnet/corefx/pull/11336

**Pull request closed without merging**
