### PR TITLE
Add unit test to check edge case in Array.Reverse(Array, ...)

### PR DESCRIPTION
**Pull request by GrabYourPitchforks**
Adds a test for a fix to an integer underflow condition in `Array.Reverse(Array, ...)`. This test is only enabled for `netcoreapp` because desktop CLR doesn't yet have the fix.

### CODE REVIEW

**Comment by GrabYourPitchforks** [comment]
Quick reminder - we can't complete the merge until corefx gets the fixed build of coreclr.

**Comment by stephentoub** [comment]
@dotnet-bot test this please

**Comment by stephentoub** [comment]
@dotnet-bot test OSX x64 Debug Build please

**Comment by stephentoub** [comment]
@dotnet/dnceng, FYI "Cannot contact OSX.1012.Amd64.Open-0511031906155-0: java.lang.InterruptedException"
https://ci3.dot.net/job/dotnet_corefx/job/master/job/osx-TGroup_netcoreapp+CGroup_Debug+AGroup_x64+TestOuter_false_prtest/12217/

Trying again:
@dotnet-bot test OSX x64 Debug Build please

**Comment by stephentoub** [comment]
@dotnet/dnceng, can you help with this leg?
https://ci3.dot.net/job/dotnet_corefx/job/master/job/osx-TGroup_netcoreapp+CGroup_Debug+AGroup_x64+TestOuter_false_prtest/12217/
```
Cannot contact OSX.1012.Amd64.Open-0511031906155-0: java.lang.InterruptedException
Cancelling nested steps due to timeout
Could not connect to OSX.1012.Amd64.Open-0511031906155-0 to send interrupt signal to process
[Pipeline] }
[Pipeline] // stage
[Pipeline] }
[Pipeline] // timeout
[Pipeline] }
[Pipeline] // timestamps
[Pipeline] echo
Archiving logs in netci-archived-logs/**
[Pipeline] step
Required context class hudson.Launcher is missing
Perhaps you forgot to surround the code with a step that provides this, such as: node
[Pipeline] echo
Error during cleanup: java.lang.IllegalArgumentException: Failed to prepare archiveArtifacts step
[Pipeline] isUnix
Required context class hudson.Launcher is missing
Perhaps you forgot to surround the code with a step that provides this, such as: node
```

**Comment by MattGal** [comment]
Have not seen this before, filed https://github.com/dotnet/core-eng/issues/3475

**Comment by stephentoub** [comment]
@dotnet-bot test OSX x64 Debug Build please

**Pull request merged**
