### PR TITLE
Fix a failing SemaphoreSlim outer loop test

### LINKED ISSUE #1575: [System.Threading] Test failure
cmd: `build /p:WithCategories=OuterLoop`

	Test.SemaphoreSlimTests.RunSemaphoreSlimCurrentTests [FAIL]
    RunSemaphoreSlimTest8_ConcWaitAndRelease(5,1000,50, 50, 50, 0, 5, 1000): FAILED.  ConcurrentWaitRelease failed, the code threw exception Xunit.Sdk.TrueException: RunSemaphoreSlimTest8_ConcWaitAndRelease(5,1000,50, 50, 50, 0, 5, 1000): FAILED.  Expected succeeded=50, failed=0, count=5, but got 27, 23, 28
           at Xunit.Assert.True(Boolean condition, String userMessage)
           at Test.SemaphoreSlimTests.RunSemaphoreSlimTest8_ConcWaitAndRelease(Int32 initial, Int32 maximum, Int32 waitThreads, Int32 releaseThreads, Int32 succeededWait, Int32 failedWait, Int32 finalCount, Int32 timeout) in m:\Workspace\github\corefx\src\System.Threading\tests\SemaphoreSlimTests.cs:line 629
        Stack Trace:
           m:\Workspace\github\corefx\src\System.Threading\tests\SemaphoreSlimTests.cs(635,0): at Test.SemaphoreSlimTests.RunSemaphoreSlimTest8_ConcWaitAndRelease(Int32 initial, Int32 maximum, Int32 waitThreads, Int32 releaseThreads, Int32 succeededWait, Int32 failedWait, Int32 finalCount, Int32 timeout)
           m:\Workspace\github\corefx\src\System.Threading\tests\SemaphoreSlimTests.cs(168,0): at Test.SemaphoreSlimTests.RunSemaphoreSlimCurrentTests()

### PR DESCRIPTION
**Pull request by stephentoub**
Fixes #1575.

### CODE REVIEW

**Comment by stephentoub** [comment]
@dotnet-bot test this please

**Comment by stephentoub** [comment]
cc: @mellinoe

**Comment by stephentoub** [comment]
@dotnet-bot test this please

**Comment by mellinoe** [comment]
This one must have slipped by since it was outer loop, LGTM

**Pull request merged**
