### PR TITLE
Revert "Merge pull request #1315 from mmitche/supported-oses"

### PR DESCRIPTION
**Pull request by mmitche**
This reverts commit d49f8f5f40458b850b2c49c2966db13777957ac0, reversing
changes made to c2c8efbd2a359d8e33ddef54b5b553c45404865f.

### CODE REVIEW

**Comment by mmitche** [comment]
cc @weshaggard This is the revert

**Comment by weshaggard** [comment]
LGTM thanks.

**Comment by ellismg** [comment]
I'm curious as to what the problem was that caused this revert?

**Comment by mmitche** [comment]
The internal builds are always setting Platform in the environment (specifically as x86 for instance).  This causes the build to fail.  Wes suggested that maybe we redesign this to have an "ignore the restrictions" property.

**Pull request merged**
