### PR TITLE
Harvest internal package deps

### PR DESCRIPTION
**Pull request by ericstj**
These are no longer needed with the latest buildtools.  They'll be
harvested just like other dependencies.  /cc @weshaggard @stephentoub

### CODE REVIEW

**Comment by ericstj** [comment]
@dotnet-bot test Innerloop Windows_NT Debug Build and Test

**Comment by ericstj** [comment]
all legs are failing in a packaging task.  Investigating.

**Comment by ericstj** [comment]
@dotnet-bot test Innerloop Windows_NT Release Build and Test

**Comment by ericstj** [comment]
@dotnet-bot test Innerloop Windows_NT Release Build and Test

**Comment by weshaggard** [comment]
LGTM

One scenario that I believe still isn't covered but I don't know if we actually have it right now or not either, is if one of our native packages have a dependency on one of our other native packages. I guess if we have that we can still manually setup that.

**Comment by ericstj** [comment]
@weshaggard yeah, and soft dependencies.  Those can be manual.

**Pull request merged**
