### PR TITLE
Test System.Dynamic.InvokeBinder.

### PR DESCRIPTION
**Pull request by JonHanna**

### CODE REVIEW

**Comment by JonHanna** [comment]
@dotnet-bot test this, please. (That's the second time you didn't start testing things yourself, dotnet-bot. Do bots take time off during the Thanksgiving weekend?)

**Comment by JonHanna** [comment]
@dotnet-bot help

**Comment by stephentoub** [comment]
@dotnet-bot test this please

**Comment by stephentoub** [comment]
@mmitche, looks like Jenkins might be having some issues...?  The ci site appears to be unreachable at the moment.

**Comment by JonHanna** [comment]
@dotnet-bot test this please

**Comment by stephentoub** [comment]
@dotnet-bot test this please

**Pull request merged**
