### PR TITLE
Updated StringComparison

### PR DESCRIPTION
**Pull request by hann013**
Completed #9801 by adding InvariantCulture and InvariantCultureIgnoreCase to StringComparison in System.Runtime.

### CODE REVIEW

**Comment by danmosemsft** [comment]
@hann013 Please also add some tests (same as for adding any API). Either from the desktop tests, or from Mono, or some of your own .

**Comment by hann013** [comment]
@danmosemsft Updated existing tests and added a new test for InvariantCulture/InvariantCultureIgnoreCase.

**Comment by danmosemsft** [comment]
LGTM

**Comment by stephentoub** [comment]
LGTM2.  Thanks for fixing these up.

Three comments:
1. This PR is submitted against dotnet:master rather than against dotnet:dev/api.  Most of our recent work to add back APIs has been going into the dev/api branch... but, I believe @danmosemsft is planning for that branch to be merged into dotnet:master imminently, so this may not matter.  @joperezr is working as well to bump up the System.Runtime contract version as part of that, which is necessary with adding back such APIs.
2. There's also the closely related StringComparer class, which is missing its InvariantCulture and InvariantCultureIgnoreCase properties in the contract, as well its Create method (I think that's it, but it'd be worth double checking nothing else is missing either).  Will you be adding those back as well, either in this PR or in another one?
3. We'll want to expose this in CoreRT as well.  I see that these values are commented out there, too: https://github.com/dotnet/corert/blob/4376c55dd018d8b7b9fed82449728711231ba266/src/System.Private.CoreLib/src/System/StringComparison.cs#L19.  That's likely non-trivially more work, though, as it looks like the implementation itself isn't expecting those values, e.g. https://github.com/dotnet/corert/blob/6ad4b86796a610af4786e0e2d6adec602a04198a/src/System.Private.CoreLib/src/System/String.cs#L949. cc: @ellismg, @jkotas

**Comment by hann013** [comment]
Updated to #10019 to merge against dev/api instead of master. Closing this one.

**Pull request closed without merging**
