### PR TITLE
SerialPort: Clear fAbortOnError when port opens

### LINKED ISSUE #17396: SerialPort: fAbortOnError not always cleared correctly when port is opened
@daflame76 reported this in #984.

There has been a long-standing problem with SerialPort where the DCB fAbortOnError flag can get set somehow (by past problems with the port, how it gets set doesn't really matter) and is then not cleared by SerialPort when the port is opened in a .NET application.  This changes the behaviour of the port so that it doesn't work correctly with SerialPort, because it's not expecting the fAbortOnError flag.

There have been reports of this before [here](https://connect.microsoft.com/VisualStudio/feedback/details/584116) which have been closed as 'by design', which was, IMO, a mistake - or at least the reasoning given was incorrect.

This needs a test in the test suite, and to be investigated to see:

1. Does the problem still exist
2. Is it really a SerialPort bug or do some USB ports behave differently to real ports
3. Regardless of '2', can the situation be improved by changes to SerialPort to be more defensive.

This can be assigned to me.

### PR DESCRIPTION
**Pull request by willdean**
Fixes #17396

### CODE REVIEW

**Comment by willdean** [comment]
@daflame76 How does this look to you?

**Comment by daflame76** [comment]
Sorry I took so long to respond.  Yes, that looks right to me.

**Comment by danmosemsft** [comment]
@JeremyKuhne can you review/merge?

**Comment by danmosemsft** [comment]
ping @JeremyKuhne ?

**Comment by danmosemsft** [comment]
@JeremyKuhne

**Comment by danmosemsft** [comment]
I forgot that @JeremyKuhne is out until the 19th. This can sit til then...

**Pull request merged**
