### PR TITLE
Don't raise Exited events when Process.EnableRaisingEvents is false

### PR DESCRIPTION
**Pull request by mbinette91**
`Process.HasExited` raises Exited events even when `EnableRaisingEvents` is false.

Added a `_watchForExit` check before raising the event, which is the same as in `WaitForExit`.

Also added separate EnableRaisingEvents test for `HasExited` based on existing TestEnableRaiseEvents test.

### CODE REVIEW

**Comment by mbinette91** [comment]
@dotnet-bot Test Innerloop OSX Debug Build and Test

**Comment by stephentoub** [comment]
Thanks, @mbinette91.  Both the fix and the test LGTM.

@weshaggard, @Priya91, do you have thoughts on this?  I agree this is a bug.  However, it exists in desktop as well, and I'm slightly concerned that code could be inadvertently relying on the fact that HasExited may trigger the event to fire.  Thoughts?

**Comment by Priya91** [comment]
LGTM as well

> However, it exists in desktop as well

Yeah, not sure of the implications of porting the bug back to desktop, causing silent broken behavior on update.

**Comment by stephentoub** [comment]
@weshaggard, from a standards perspective, do you have an opinion on taking this fix for corefx, regardless of whether it then goes to desktop?

**Comment by weshaggard** [comment]
>@weshaggard, from a standards perspective, do you have an opinion on taking this fix for corefx, regardless of whether it then goes to desktop?

I don't really have a lot of context in this area and I agree it is probably a bug but we should weigh that against the value we have from the existing code. Is this behavior really causing any issues? If not would just keep the behavior in the name of compat to avoid any risk.

**Comment by mbinette91** [comment]
> Is this behavior really causing any issues?

Well... It was causing at least one or I wouldn't be here. :-)

It doesn't sound unreasonable that someone would expect code in their callbacks not to be executed after disabling `EnableRaisingEvents`. If the compatibility risks are too big, the doc should at least be updated to reflect this so people use it knowing there's no guarantee it will be honored (depending on the state of an unknown internal flag (_exited)) and that they shouldn't trust it.

But I understand the compatibility concerns too - you're the experts. :-)

**Comment by karelz** [comment]
@Priya91 can you please drive the decision on taking it / not taking it?

In general the more we divert .NET Core from full .NET, the harder time will devs have to migrate between platforms. So unless this is significant pain for devs, I would suggest to not take it.

@mbinette91 if we don't take it, please file a documentation bug (as you suggested above). Thanks!

**Comment by mbinette91** [comment]
Some more info that might help drive the decision:

The default for `EnableRaisingEvents` is false, so an application that currently doesn't assign this property and relies on HasExited to trigger an Exited event could break. I don't know how likely it is that someone would expect (intentionally or not) that event only to be raised through HasExited (because it's not going to be raised when the process exits), but that sounds possible enough.

FWIW, in our case, this bug manifested itself in a rare race condition: we'd have one Thread looking at HasExited while the second thread was `>>Here<<` (and ProcExitCallback depends on _resourceA). 

  ```
  _process.EnableRaisingEvents = false;
  // ...
  _resourceA.Dispose();
  // >>Here<<
  _process = null;
  ```

(I simplified, but you can ping me on lync if you want some more details..)

This kind of scenario doesn't sound more likely than the former scenario, so I'd be temped to leave it as-is if it wasn't for my hate of by-design bugs. :)

@karelz Can you point me towards where I would file a documention bug ? Would it be through here or elsewhere ?

Thanks!

**Comment by Priya91** [comment]
> This kind of scenario doesn't sound more likely than the former scenario, so I'd also be temped to leave it as-is if it wasn't for my hate of by-design bugs. :)

👍 I will close this PR, thanks for bringing this up.

@karelz Can you point me towards where I would file a documention bug ? Would it be through here or elsewhere ?

Yeah you file the bug on corefx, and we'll add label Documentation on it.

**Pull request closed without merging**
