### PR TITLE
Merge v1.0 to master

### PR DESCRIPTION
**Pull request by nguerrera**
Straight automated PR with no merge conflicts to resolve.

### CODE REVIEW

**Comment by nguerrera** [comment]
Do not merge yet. We're waiting for #585, #586, #589, #595

cc @stephentoub

**Comment by nguerrera** [comment]
@dotnet-bot test this please

**Comment by nguerrera** [comment]
@mmitche Possibly another sync race here as more commits have come in (by design).

**Comment by mmitche** [comment]
@nguerrera like a flaky test this time:

Discovered:  System.IO.FileSystem.Tests
     System.Diagnostics.ProcessTests.ProcessTest.Process_EnableRaiseEvents [FAIL]
        Process_CanRaiseEvents0001: isExited Event not called when EnableRaisingEvent is set to true.
        Stack Trace:

I think there is an issue for this already

**Comment by nguerrera** [comment]
Sigh. This is another intermittent failure. I'm going to try to get things stabilized and get more PRs through before merging. I've had enough of the re-testing randomization!

**Comment by stephentoub** [comment]
Yes, #597

**Comment by mmitche** [comment]
This looks like another push that squashed the origin PR branch.

**Comment by mmitche** [comment]
@dotnet-bot test this please

**Comment by nguerrera** [comment]
@mmitche There's no squash here, just more incoming commits. It should work.

**Comment by nguerrera** [comment]
@stephentoub  thanks for #608. I believe that every test with a CreateProcessInfinite is at risk of random failure. I'd like to se

For example, I get the same error as #595 very often by reducing the timeout to zero. I think we either need a more robust IPC (not sure of best approach that would go OK with xplat Process) or we need to consider anything requiring killing a long-running process to be outer loop. I'm sending a PR that does that.

**Comment by mmitche** [comment]
That's really odd then.  Maybe there is some race within GH then? The event is getting fired before the updated branch exists perhaps?  We'll need to watch this to see what the pattern is.

**Comment by mmitche** [comment]
@nguerrera I have a theory actually.  I had the CI set up to build immediately rather than waiting a set number of seconds.  The default setup waits for 5 seconds after receiving the event to see whether another event for the same job fires.  Then it may combine the two if resources are low (for instance, two pushes quickly one after the other).  I wonder if that wait period covers a race in github normally.

**Comment by nguerrera** [comment]
Taking this. I need to head out and will look at the remaining Process issues some more tonight.

**Pull request merged**
