### PR TITLE
Update build to clang/llvm 3.9

### PR DESCRIPTION
**Pull request by mikem8361**
Update scripts, docs and build pipeline docker images to clang/llvm/lldb 3.9

### CODE REVIEW

**Comment by danmosemsft** [comment]
@mikem8361 although this may be a good idea, we have to go through shiproom if we want to modify the release branch. This would modify the binaries we ship, and potentially their behavior right? 

We might want to wait anyway, to see if there's fall out in master.

**Comment by mikem8361** [comment]
@dotnet-bot test Innerloop Tizen armel Release Cross Build
@dotnet-bot test Innerloop Tizen armel Debug Cross Build

**Comment by karelz** [comment]
What is the motivation to bring the change to 2.0.x servicing release?

**Comment by mikem8361** [comment]
There were a few devs that thought this was a good idea when I was updating master, but now I’m not so sure.  I was more interested in the libsosplugin.so being built against 3.9 instead of 3.5. Building with clang 3.9 was to be consistent with that. Since the lldb 3.9 dev package was installed on the CI VMs I think the plugin will be built for lldb 3.9, but without the new docker file changes, the actual release builds won’t. @mmitche?

It seems that something went wrong with my cherry-pit/merge and the arm legs are failing.  I’ll need to fix that if we move forward on this.

Of course, I was going to run this through/back the ship room.

**Comment by mikem8361** [comment]
@dotnet-bot test this please

**Comment by karelz** [comment]
@mikem8361 any update? I don't see any progress in last 3 weeks ...

**Comment by mikem8361** [comment]
I haven’t had a chance to look into the failures and I’m still considering whether we should take this change into 2.0.x.

**Comment by karelz** [comment]
@mikem8361 any update? If not, I would recommend to close the PR and reopen it when it is useful / when we are ready to make it real.

**Pull request closed without merging**
