### PR TITLE
Convert most Assert.Throws<ArgumentException> without param name to AssertExtensions

### PR DESCRIPTION
**Pull request by hughbe**
In preparation for #21409

Missing:
- ICollection/IDictionary/IEnumerable helpers (pending discussion on what we want to do here)
- All of System.IO.FileSystem (will send in PR later)

Next up:
- Do the same for ArgumentNullException/ArgumentOutOfRangeException/InvalidEnumArgumentException
- Batch convert all remaining uses of these to AssertExtensions
- Somehow deprecate `Assert.Throws<Argument`

<details>
<summary>Powershell script for converting these files</summary>

```powershell

$configFiles = Get-ChildItem ./src *.cs -rec
$old = "Assert.Throws<ArgumentException>(()"
$new = "AssertExtensions.Throws<ArgumentException>(()"

function Get-FileEncoding {
    param ( [string] $FilePath )

    [byte[]] $byte = get-content -Encoding byte -ReadCount 4 -TotalCount 4 -Path $FilePath

    if ( $byte[0] -eq 0xef -and $byte[1] -eq 0xbb -and $byte[2] -eq 0xbf )
        { $encoding = 'UTF8' }  
    elseif ($byte[0] -eq 0xfe -and $byte[1] -eq 0xff)
        { $encoding = 'BigEndianUnicode' }
    elseif ($byte[0] -eq 0xff -and $byte[1] -eq 0xfe)
         { $encoding = 'Unicode' }
    elseif ($byte[0] -eq 0 -and $byte[1] -eq 0 -and $byte[2] -eq 0xfe -and $byte[3] -eq 0xff)
        { $encoding = 'UTF32' }
    elseif ($byte[0] -eq 0x2b -and $byte[1] -eq 0x2f -and $byte[2] -eq 0x76)
        { $encoding = 'UTF7'}
    else
        { $encoding = 'ASCII' }
    return $encoding
}

foreach ($file in $configFiles) {
    $encoding = Get-FileEncoding $file.fullname

    Write-Output $file
    If(Select-String -Path $file.fullname -SimpleMatch $old -quiet){
        (Get-Content -Path $file.PSPath -Encoding $encoding) |
        Foreach-Object { $_ -replace [regex]::Escape($old), $new } |
        Set-Content -Path $file.PSPath -Encoding $encoding
    }
}
```
</details>

### CODE REVIEW

**Comment by hughbe** [comment]
This will need outer loop tests to be run as well, I'm just waiting on netfx and Unix

**Comment by stephentoub** [comment]
> Fixes for unix and netfx

What were the fixes for Unix?  I'm worried there's an inconsistency between implementations that's actually a bug we should fix.

**Comment by hughbe** [comment]
> What were the fixes for Unix? I'm worried there's an inconsistency between implementations that's actually a bug we should fix.

I detailed them in the issue - the first one (which failed 3 times) is just a missing param name that I've sent in a fix in #21461 

The second is a globalization one. On Unix, `IsNormalized` validated `normalizationForm` [here](https://github.com/dotnet/coreclr/blob/cdff8b0babe5d82737058ccdae8b14d8ae90160d/src/mscorlib/src/System/Text/Normalization.Unix.cs#L78-L82)

However, on Windows, we just [immediately pass off to the C++ API](https://github.com/dotnet/coreclr/blob/cdff8b0babe5d82737058ccdae8b14d8ae90160d/src/mscorlib/src/System/Text/Normalization.Windows.cs#L21-L55)

In this case, we get
```
case Interop.Errors.ERROR_INVALID_PARAMETER:
case Interop.Errors.ERROR_NO_UNICODE_TRANSLATION:
     throw new ArgumentException(SR.Argument_InvalidCharSequenceNoIndex, nameof(strInput));
```

Which always throws for `strInput`, even if `normalizationForm` is invalid

**Comment by hughbe** [comment]
A potential fix could be to change the code to the following

```cs
                case Interop.Errors.ERROR_INVALID_PARAMETER:
                case Interop.Errors.ERROR_NO_UNICODE_TRANSLATION:
                    if (!Enum.IsDefined(typeof(NormalizationForm), normForm))
                    {
                        throw new ArgumentException(SR.Argument_InvalidNormalizationForm, nameof(normalizationForm));
                    }
                    throw new ArgumentException(SR.Argument_InvalidCharSequenceNoIndex, nameof(strInput));

```

**Pull request merged**
