### PR TITLE
Added System.Diagnostics.Process tests.

### PR DESCRIPTION
**Pull request by richamsft**
Added AssemblyInfo.cs file to Microsoft.Win32.Primitives, upped the version number to maximum. Tests dependent on this assembly and looking for any version of this assembly should be able to pick this up.
Fix dirs.proj to pick up csproj files that don't immediately exist under test directory but a level below.

### CODE REVIEW

**Comment by stephentoub** [comment]
@richamsft, is this ready to be committed?  I'm going to be looking at some issues in the library, and having / being able to augment the tests would be helpful.  Thanks!

**Comment by joshfree** [comment]
@mattgal picked this and the console test PR up yesterday and is wrapping them up (starting clean) this sprint.

**Comment by stephentoub** [comment]
@joshfree, ah, thanks, that probably explains then why he discovered #478 :smile:

**Comment by Giorgi** [comment]
Sorry for hijacking the thread but is there any work done to integrate #303 ?

**Comment by joshfree** [comment]
Hi @Giorgi! Your change to Process hasn't been forgotten! :smile: As you can see from https://github.com/dotnet/corefx/tree/master/src, it's unfortunate that both Console and Process are still missing their unit tests.  @MattGal has picked up this work and we should be able to look at #303 right after the Process tests are up.

**Comment by Giorgi** [comment]
Great, I look forward to it!

**Comment by joshfree** [comment]
I am closing this old PR out as @mattgal is commiting the Process tests fromPR https://github.com/dotnet/corefx/pull/485

**Pull request closed without merging**
