### PR TITLE
[Port to 1.1] Ensure CURLOPT_TCP_NODELAY is set by CurlHandler

### PR DESCRIPTION
**Pull request by stephentoub**
Port https://github.com/dotnet/corefx/pull/15354 to the release/1.1.0 branch.
cc: @geoffkizer, @mikeharder, @gkhanna79

### CODE REVIEW

**Comment by stephentoub** [comment]
@dotnet-bot test Outerloop Ubuntu14.04 Debug please
@dotnet-bot test Outerloop OSX Debug please

**Comment by gkhanna79** [comment]
@stephentoub Can you please update packages.builds to reflect that this package needs to be built for the servicing branch?

**Comment by gkhanna79** [comment]
https://github.com/dotnet/corefx/commit/7e8305aca4916b96a4cbaccceea977b5249463c6 is an example of where it was undone. @weshaggard can suggest a better place/way, if available.

**Comment by weshaggard** [comment]
See https://github.com/dotnet/corefx/commit/3ac33e4df7acd85c557bc5cecb9a4b4cb4a67007. You will need to bump package version and potentially assembly version if this applies to desktop.

**Comment by stephentoub** [comment]
> See 3ac33e4

So are these two places the relevant changes I should copy / update?
https://github.com/dotnet/corefx/commit/3ac33e4df7acd85c557bc5cecb9a4b4cb4a67007#diff-e72017c9a98ac3e48b0f5fa0c1731ad1R5
https://github.com/dotnet/corefx/commit/3ac33e4df7acd85c557bc5cecb9a4b4cb4a67007#diff-cb73a137838f73872d476fa5146bfedeR28

Can we document the steps somewhere in our project documentation?

> if this applies to desktop.

This only affects the Unix build.

**Comment by stephentoub** [comment]
@weshaggard, @ericstj, @gkhanna79, I made the requested changes... please let me know if I did so correctly, or if not, what I need to fix. Thanks!

**Comment by gkhanna79** [comment]
@stephentoub The changes looks fine to me. @weshaggard Do you have anything else to add before this gets merged?

**Comment by stephentoub** [comment]
@ericstj, could you confirm I've done the right thing (or not) for the servicing part of this change, version number, etc.?

**Comment by ericstj** [comment]
@stephentoub what will happen when someone has the IL portion of this fix without the shim?  I suspect that will be the case unless you make System.Net.Http.native packages direct references like @bartonjs did with crypto.

**Comment by stephentoub** [comment]
> what will happen when someone has the IL portion of this fix without the shim?

It'll actually work ok; the native changes here are purely for static asserts to flag the (very unexpected) case where libcurl changes its defines from what we expect them to be.

**Comment by bartonjs** [comment]
The only thing we're doing in the shim is `static_assert`ing that the value we put in C# is the same as is used in the native `.h` file.  So I think this will be fine.  (It's not calling into a new export, or anything like that).

**Comment by stephentoub** [comment]
@ericstj, does this look ok then?

**Comment by ericstj** [comment]
Ok, package change is OK.  So we're just deciding not to bump assembly version because there are no substantial assembly change such that you wouldn't care if someone installed the old one to the GAC and that's what folks got when using the new package?

**Comment by stephentoub** [comment]
> you wouldn't care if someone installed the old one to the GAC and that's what folks got when using the new package?

The only change here is in the unix build.  This shouldn't affect anything about the GAC.  Or am I misunderstanding?

**Comment by stephentoub** [comment]
That said, if bumping the version number if the right thing to do, I can certainly do so; I was just following the guidance that it only needed to be bumped if it affects desktop, which it doesn't.  Should I bump it?  And if so, what files need to be changed for that?

**Comment by ericstj** [comment]
Same file, System.Net.Http\dir.props.  In the past we've been bumping 4th part during any servicing as was done here https://github.com/dotnet/corefx/commit/8c2b67e16855f4c29f1ff880cd0c09388b9c38b4.

**Comment by stephentoub** [comment]
> Same file, System.Net.Http\dir.props. In the past we've been bumping 4th part during any servicing as was done here 8c2b67e.

Ok, bumped.

**Comment by ericstj** [comment]
```
 error : PackageIndex from D:\j\workspace\windows_nt_de---62a15db0\pkg\Microsoft.Private.PackageBaseline\packageIndex.json is missing an assembly version entry for 4.1.1.1 for package System.Net.Http.  Please run /t:UpdatePackageIndex on this project to commit an update.
```
Do this on the System.Net.Http.pkgproj after building it.

**Comment by stephentoub** [comment]
> Do this on the System.Net.Http.pkgproj after building it.

Fixed

**Comment by ericstj** [comment]
LGTM, make sure you pass CI and have shiproom approval for servicing.

**Comment by stephentoub** [comment]
Thanks for the help, @ericstj .

> have shiproom approval for servicing

Already done.

**Pull request merged**
