### PR TITLE
[release/3.1] Make PathAssemblyResolver handle Retargetable

### PR DESCRIPTION
**Pull request by ericstj**
Release/3.1 port of fca60323d9606a90b327273d08089200ae6f527b + package authoring.

### CODE REVIEW

**Comment by ericstj** [comment]
Fixes https://github.com/dotnet/runtime/issues/730
/cc @mmitche

**Review by Anipik — APPROVED** [review]

**Comment by tmat** [comment]
I think this belongs to System.Reflection, not System.Reflection.Metadata

**Comment by ericstj** [comment]
Failure here appears to be related to how we support netcoreapp3.1 package tests.  We didn't catch it in the 3.1 SDK update PR since we weren't building packages at that time.  I'll fix this in the package testing infra.

**Comment by mmitche** [comment]
Hold this until 3.1.2, as I think the other fix is slipping too, and aspnetcore is just about ready to go.

**Comment by ericstj** [comment]
@mmitche where are we at for 3.1.2?

**Comment by mmitche** [comment]
Not started yet. Waiting on the last signoffs for 3.1.1

**Comment by danmoseley** [comment]
@mmitche @ericstj we can remove "no-merge" right? and merge this now.

**Comment by mmitche** [comment]
Not until branding is updated.

**Comment by danmoseley** [comment]
Sure, I meant we can remove "no-merge" ?

**Pull request merged**
