### PR TITLE
Cleanup code in System.Runtime.Serialization.Formatters.Tests

### PR DESCRIPTION
**Pull request by ViktorHofer**
@krwq if you have time it would be nice if you can review my changes as you contributed a fair amount of code to it :)

Motivation for changes:
1. Get rid of BinaryFormatterHelper.cs in favor of BinaryFormatterHelpers.cs (Common)
2. Move code to read and write from/to base64strings and byte arrays to common to be able to test serialization code in different packages.

### CODE REVIEW

**Comment by ViktorHofer** [comment]
I see that krwq is on holiday. @stephentoub or @danmosemsft would you mind reviewing this cleanup PR?

**Comment by ViktorHofer** [comment]
@dotnet/dnceng Tizen build failing:

> Status: Downloaded newer image for hqueue/dotnetcore:ubuntu1404_cross_prereqs_v4-tizen_rootfs docker: Error response from daemon: failed to get network during CreateEndpoint: could not find endpoint count for network bridge: Key not found in store.

**Comment by markwilkie** [comment]
@ViktorHofer - Did the Tizen build get sorted?

**Comment by ViktorHofer** [comment]
I merged without the Tizen build so I can't say if it's still occurring.

**Pull request merged**
