### PR TITLE
Add missing Shutdown calls in HTTP loopback servers

### PR DESCRIPTION
**Pull request by stephentoub**
General goodness, but potentially the cause of https://github.com/dotnet/corefx/issues/25640 and maybe some other issues.

cc: @davidsh, @wfurt, @Priya91

### CODE REVIEW

**Comment by stephentoub** [comment]
> I assume you'll run Outerloop tests since most HTTP tests are Outerloop.

Yup, once innerloop completes.

**Comment by stephentoub** [comment]
@dotnet-bot test NETFX x86 Release Build please
@dotnet-bot test Outerloop Windows x64 Debug Build please
@dotnet-bot test Outerloop Linux x64 Debug Build please
@dotnet-bot test Outerloop OSX x64 Debug Build please

**Comment by wfurt** [comment]
looks ok to me.

**Comment by ahsonkhan** [comment]
@dotnet-bot test Outerloop OSX x64 Debug Build

**Pull request merged**
