### PR TITLE
Remove search trimming

### LINKED ISSUE #21096: Windows TrimEndChars not aligned with NTFS
In `corefx/src/System.IO.FileSystem/src/System/IO/PathHelpers.Windows.cs` we have definition

`internal static readonly char[] TrimEndChars = { (char)0x9, (char)0xA, (char)0xB, (char)0xC, (char)0xD, (char)0x20, (char)0x85, (char)0xA0 };`

This is not fully aligned with underlying file system. For example 0xA0 is allowed as end char on NTFS. This can cause problems, as described [here](https://github.com/PowerShell/PowerShell/issues/4017). I think the same is with char 0x85. Others seems to be OK, but I have not confirmed it.

### PR DESCRIPTION
**Pull request by JeremyKuhne**
Trimming prevents access to valid Windows paths. We've removed trimming from the rest of our API surface, this is the last place we have it.

Fixes #21096

### CODE REVIEW

**Comment by danmosemsft** [comment]
This may be water under the bridge at this point, but if my code eg,., accepts user input for the pattern, I might well be relying on the trimming I observe is happening. It is more likely if a user passes in ` *.png  ` that they expect `*.png` rather than treating it literally. After this change,  that would appear as a bug wouldn't it? Leaving aside whether we should ever have done it in the first place

**Comment by JeremyKuhne** [comment]
> This may be water under the bridge at this point

The most "normal" situations would still work. If you have a trailing space or period in the search string Windows will eat it in the FindFirstFile API. From that point it gets pretty remote that we'll break someone.

**Comment by jkotas** [comment]
Note that the same code is duplicated in CoreLib as well.

**Comment by JeremyKuhne** [comment]
I'm going to make another pass and clean this up a bit more. The more complicated behavior is meant to deal with the way FindFirstFile works, and isn't terribly obvious. The logic can be unified between Unix/Windows and made clearer. I'll update the PR once I've done so.

**Comment by karelz** [comment]
@JeremyKuhne do you have ETA? There was no update for 1 month.

**Comment by JeremyKuhne** [comment]
Closing in favor of #25387 for now- where I've rolled this into.

**Pull request closed without merging**
