### PR TITLE
Move test-runtime to newest packages

### PR DESCRIPTION
**Pull request by stephentoub**
Motivated by needing to pick up newer System.Console and System.Diagnostic.Debug assemblies.

cc: @ericstj, @ellismg, @roncain

### CODE REVIEW

**Comment by weshaggard** [comment]
I'm fine with updating the test-runtime to the latest version but why did that invalidate all the other lock files?

**Comment by stephentoub** [comment]
> why did that invalidate all the other lock files?

No idea, you tell me :)

**Comment by weshaggard** [comment]
I suspect that is because of the DNU bug. Can you try undoing all but the test-runtime\project.json and project.lock.json and rebuild and see if those still refresh?

**Comment by stephentoub** [comment]
Ok, thanks. Looks like when I undid all but the automatic project.lock.json changes for the test-runtime, the other files were not re-updated. I've pushed a new commit with just the test-runtime updates.

**Comment by weshaggard** [comment]
LGTM thanks @stephentoub

**Comment by stephentoub** [comment]
@dotnet-bot test this please (github timeout)

**Pull request merged**
