### PR TITLE
Enable server GC for OSX Debug build & test on PRs

### PR DESCRIPTION
**Pull request by wtgodbe**

### CODE REVIEW

**Comment by wtgodbe** [comment]
@sergiy-k corefx tests use Release bits of coreclr, so we should be fine sticking with debug

**Comment by wtgodbe** [comment]
@stephentoub PTAL

**Comment by wtgodbe** [comment]
@dotnet-bot test CI please

**Comment by stephentoub** [comment]
LGTM

Though, thinking more about it, I wonder whether if we're going to pick one configuration for server GC, maybe it should be Release?  (Either way we're using a release coreclr/mscorlib.)  Then release would more closely approximate what we expect many apps in the wild to be using.

**Comment by wtgodbe** [comment]
Makes sense to me, I suppose it's more consistent that way as well.

**Comment by wtgodbe** [comment]
@dotnet-bot test CI please

**Pull request merged**
