### PR TITLE
Adding scalar hardware intrinsics for x86

### PR DESCRIPTION
**Pull request by tannergooding**
This is the CoreFX side of https://github.com/dotnet/coreclr/pull/15341 and adds the contracts for the new APIs approved in dotnet/corefx#23519

### CODE REVIEW

**Comment by tannergooding** [comment]
Several of the existing APIs don't follow the `{ throw null; }` convention and instead throw other exceptions. Should they be updated as part of this PR, or separately?

**Comment by tannergooding** [comment]
FYI. @fiigii, @eerhardt

**Comment by tannergooding** [comment]
Rebased onto head. The CoreCLR has been pumped back, so this should pass now.

**Comment by jkotas** [comment]
> Should they be updated as part of this PR, or separately?

Yes, it would be nice to get them updated. Either second commit in this PR, or a new PR are fine.

**Comment by tannergooding** [comment]
Updated as part of this PR.

Am I good to merge once tests are green?

**Comment by jkotas** [comment]
Yes (with Rebase & Merge).

**Comment by tannergooding** [comment]
Merged with rebase and merge. Thanks!

**Pull request merged**
