### PR TITLE
Add back System.Runtime forwards for GCHandle

### PR DESCRIPTION
**Pull request by jkotas**
Adding these forwards back to make upgrades from rc2 easier.

### CODE REVIEW

**Comment by botaberg** [comment]
LGTM

I did have a concern about this in #8626 and asked whether it was a good idea to remove these type forwards.

**Comment by ericstj** [comment]
LGTM

**Comment by weshaggard** [comment]
:+1:

**Comment by ericstj** [comment]
I think we need this in rel/1.0.0 too, for some time.

**Comment by jkotas** [comment]
@dotnet-bot test this please

**Comment by joshfree** [comment]
thanks @jkotas; please also submit this to release/1.0.0.  Ideally it makes it into the internal 12n release build.

**Pull request merged**
