### PR TITLE
Remove git setup from Nano job.

### PR DESCRIPTION
**Pull request by Priya91**
cc @mmitche

### CODE REVIEW

**Comment by Priya91** [comment]
@dotnet-bot test ci please

**Comment by Priya91** [comment]
@mmitche the generator is failing at ```addPrivatePermissions``` that no such method exists.. This was added in this PR #7395 

How to fix this? Is this because corefx is using an older dotnet-ci generator definition..

**Comment by Priya91** [comment]
@dotnet-bot test ci please

**Comment by Priya91** [comment]
@dotnet-bot test ci please

**Comment by mmitche** [comment]
@Priya91 Looks like this exposed a bug in the pull request builder (maybe, might be something else).  That is keeping projects from launching PRs.  I'm going to revert this for until tomorrow morning when I can figure out what's going on.

**Comment by Priya91** [comment]
@mmitche this is very specific to Nano job. Can't think of how this can affect other jobs..

**Comment by mmitche** [comment]
@Priya It's because of the way the plugin is written.  The lack of a github address in the job was causing the PR trigger to initialize improperly (throwing an error that there was no github address).  However it was blocking other PRs from starting.

You are right about setting the affinity of the flow job though.  That should work.

**Pull request merged**
