### PR TITLE
System.Linq: Initial port of legacy tests

### PR DESCRIPTION
**Pull request by akoeplinger**
From https://github.com/VSadov/corefx/tree/UnportedLegacyTests/src/System.Linq/LegacyTestsToPort/LINQ

The tests were grouped into classes based on the tested area. The Main() method was wrapped
with an Assert that verifies it returns 0 (which means a successful test).

Further cleanup and embracing of Xunit can be done in follow-up commits. I already ran the CodeFormatter on this.

#2851 

Code coverage increased from 70.4% to 94.2%.  Fixes https://github.com/dotnet/corefx/issues/1143

### CODE REVIEW

**Comment by stephentoub** [comment]
Very cool.

> let me know if I need to do this as @dotnet-bot :)

Yes, please, if you wouldn't mind ;)

**Comment by VSadov** [comment]
Very nice!!!

**Comment by akoeplinger** [comment]
@stephentoub done :)

**Comment by jaredpar** [comment]
:+1: Awesome!

**Comment by stephentoub** [comment]
@akoeplinger, thanks for doing this.

I pulled down your branch and tried it locally.  There's a bunch of output that gets dumped to the console:
```
  Discovering: System.Linq.Tests
  Discovered:  System.Linq.Tests
  Starting:    System.Linq.Tests
  System.InvalidCastException: Specified cast is not valid.
     at System.Linq.Enumerable.<CastIterator>d__94`1.MoveNext() in corefx\src\System.Linq\src\System\Linq\Enumerable.cs:line 1159
     at System.Linq.Tests.LegacyTests.Verification.AllequalComparer[T](IEnumerable`1 expected, IEnumerable`1 actual, IEqualityComparer`1 comparer) in c:\Users\
  stoub\Source\repos\corefx\src\System.Linq\tests\LegacyTests\Helper.cs:line 98
  System.InvalidCastException: Specified cast is not valid.
     at System.Linq.Enumerable.<CastIterator>d__94`1.MoveNext() in corefx\src\System.Linq\src\System\Linq\Enumerable.cs:line 1159
     at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
     at System.Linq.Tests.LegacyTests.Verification.AllequalComparer[T](IEnumerable`1 expected, IEnumerable`1 actual, IEqualityComparer`1 comparer) in c:\Users\
  stoub\Source\repos\corefx\src\System.Linq\tests\LegacyTests\Helper.cs:line 97
  System.InvalidCastException: Specified cast is not valid.
     at System.Linq.Enumerable.<CastIterator>d__94`1.MoveNext() in corefx\src\System.Linq\src\System\Linq\Enumerable.cs:line 1159
     at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
     at System.Linq.Tests.LegacyTests.Verification.AllequalComparer[T](IEnumerable`1 expected, IEnumerable`1 actual, IEqualityComparer`1 comparer) in c:\Users\
  stoub\Source\repos\corefx\src\System.Linq\tests\LegacyTests\Helper.cs:line 97
  actual 2147483657
  expected  2147483657
  System.InvalidCastException: Specified cast is not valid.
     at System.Linq.Enumerable.<CastIterator>d__94`1.MoveNext() in corefx\src\System.Linq\src\System\Linq\Enumerable.cs:line 1159
     at System.Linq.Tests.LegacyTests.Verification.AllequalComparer[T](IEnumerable`1 expected, IEnumerable`1 actual, IEqualityComparer`1 comparer) in c:\Users\
  stoub\Source\repos\corefx\src\System.Linq\tests\LegacyTests\Helper.cs:line 98
  111
  333
  System.InvalidCastException: Specified cast is not valid.
     at System.Linq.Enumerable.<CastIterator>d__94`1.MoveNext() in corefx\src\System.Linq\src\System\Linq\Enumerable.cs:line 1159
     at System.Linq.Tests.LegacyTests.Verification.AllequalComparer[T](IEnumerable`1 expected, IEnumerable`1 actual, IEqualityComparer`1 comparer) in c:\Users\
  stoub\Source\repos\corefx\src\System.Linq\tests\LegacyTests\Helper.cs:line 98
  System.InvalidCastException: Specified cast is not valid.
     at System.Linq.Enumerable.<CastIterator>d__94`1.MoveNext() in corefx\src\System.Linq\src\System\Linq\Enumerable.cs:line 1159
     at System.Linq.Tests.LegacyTests.Verification.AllequalComparer[T](IEnumerable`1 expected, IEnumerable`1 actual, IEqualityComparer`1 comparer) in c:\Users\
  stoub\Source\repos\corefx\src\System.Linq\tests\LegacyTests\Helper.cs:line 98
  System.InvalidCastException: Specified cast is not valid.
     at System.Linq.Enumerable.<CastIterator>d__94`1.MoveNext() in corefx\src\System.Linq\src\System\Linq\Enumerable.cs:line 1159
     at System.Linq.Tests.LegacyTests.Verification.AllequalComparer[T](IEnumerable`1 expected, IEnumerable`1 actual, IEqualityComparer`1 comparer) in c:\Users\
  stoub\Source\repos\corefx\src\System.Linq\tests\LegacyTests\Helper.cs:line 98
  System.InvalidCastException: Specified cast is not valid.
     at System.Linq.Enumerable.<CastIterator>d__94`1.MoveNext() in corefx\src\System.Linq\src\System\Linq\Enumerable.cs:line 1159
     at System.Linq.Tests.LegacyTests.Verification.AllequalComparer[T](IEnumerable`1 expected, IEnumerable`1 actual, IEqualityComparer`1 comparer) in c:\Users\
  stoub\Source\repos\corefx\src\System.Linq\tests\LegacyTests\Helper.cs:line 98
  System.InvalidCastException: Specified cast is not valid.
     at System.Linq.Enumerable.<CastIterator>d__94`1.MoveNext() in corefx\src\System.Linq\src\System\Linq\Enumerable.cs:line 1159
     at System.Linq.Tests.LegacyTests.Verification.AllequalComparer[T](IEnumerable`1 expected, IEnumerable`1 actual, IEqualityComparer`1 comparer) in c:\Users\
  stoub\Source\repos\corefx\src\System.Linq\tests\LegacyTests\Helper.cs:line 98
  System.InvalidCastException: Specified cast is not valid.
     at System.Linq.Enumerable.<CastIterator>d__94`1.MoveNext() in corefx\src\System.Linq\src\System\Linq\Enumerable.cs:line 1159
     at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
     at System.Linq.Tests.LegacyTests.Verification.AllequalComparer[T](IEnumerable`1 expected, IEnumerable`1 actual, IEqualityComparer`1 comparer) in c:\Users\
  stoub\Source\repos\corefx\src\System.Linq\tests\LegacyTests\Helper.cs:line 97
  System.InvalidCastException: Specified cast is not valid.
     at System.Linq.Enumerable.<CastIterator>d__94`1.MoveNext() in corefx\src\System.Linq\src\System\Linq\Enumerable.cs:line 1159
     at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
     at System.Linq.Tests.LegacyTests.Verification.AllequalComparer[T](IEnumerable`1 expected, IEnumerable`1 actual, IEqualityComparer`1 comparer) in c:\Users\
  stoub\Source\repos\corefx\src\System.Linq\tests\LegacyTests\Helper.cs:line 97
  System.InvalidCastException: Specified cast is not valid.
     at System.Linq.Enumerable.<CastIterator>d__94`1.MoveNext() in corefx\src\System.Linq\src\System\Linq\Enumerable.cs:line 1159
     at System.Linq.Tests.LegacyTests.Verification.AllequalComparer[T](IEnumerable`1 expected, IEnumerable`1 actual, IEqualityComparer`1 comparer) in c:\Users\
  stoub\Source\repos\corefx\src\System.Linq\tests\LegacyTests\Helper.cs:line 98
  System.InvalidCastException: Specified cast is not valid.
     at System.Linq.Enumerable.<CastIterator>d__94`1.MoveNext() in corefx\src\System.Linq\src\System\Linq\Enumerable.cs:line 1159
     at System.Linq.Tests.LegacyTests.Verification.AllequalComparer[T](IEnumerable`1 expected, IEnumerable`1 actual, IEqualityComparer`1 comparer) in c:\Users\
  stoub\Source\repos\corefx\src\System.Linq\tests\LegacyTests\Helper.cs:line 98
  System.InvalidCastException: Specified cast is not valid.
     at System.Linq.Enumerable.<CastIterator>d__94`1.MoveNext() in corefx\src\System.Linq\src\System\Linq\Enumerable.cs:line 1159
     at System.Linq.Tests.LegacyTests.Verification.AllequalComparer[T](IEnumerable`1 expected, IEnumerable`1 actual, IEqualityComparer`1 comparer) in c:\Users\
  stoub\Source\repos\corefx\src\System.Linq\tests\LegacyTests\Helper.cs:line 98
  System.InvalidCastException: Specified cast is not valid.
     at System.Linq.Enumerable.<CastIterator>d__94`1.MoveNext() in corefx\src\System.Linq\src\System\Linq\Enumerable.cs:line 1159
     at System.Linq.Tests.LegacyTests.Verification.AllequalComparer[T](IEnumerable`1 expected, IEnumerable`1 actual, IEqualityComparer`1 comparer) in c:\Users\
  stoub\Source\repos\corefx\src\System.Linq\tests\LegacyTests\Helper.cs:line 98
  Finished:    System.Linq.Tests

  === TEST EXECUTION SUMMARY ===
     System.Linq.Tests  Total: 1175, Errors: 0, Failed: 0, Skipped: 0, Time: 1.023s
```
We don't need to do all of the xunit cleanup as part of this commit, but I'd prefer it if we not have such output spewed in a normal run.  Could you evaluate the Console.WriteLines and eliminate at least those that aren't on a test failure path?  Also, it'd be worth double-checking all of those cast failures to see whether they're expected or not.

**Comment by akoeplinger** [comment]
@stephentoub I investigated those cast failure messages and they come from [Helper.cs#L225](https://github.com/akoeplinger/corefx/blob/a723067473283cd9242b50066109fe91e3793e95/src/System.Linq/tests/LegacyTests/Helper.cs#L225), which is expected because of tests like [AggregateTests.cs#L93-L96](https://github.com/akoeplinger/corefx/blob/a723067473283cd9242b50066109fe91e3793e95/src/System.Linq/tests/LegacyTests/AggregateTests.cs#L93-L96), which basically verify if an exception is thrown.

Since there are only a handful of those, I'll convert them to Assert.Throws() instead.

**Comment by stephentoub** [comment]
Thanks! Feel free to do such cleanup in a separate commit.

**Comment by akoeplinger** [comment]
@stephentoub output is clean now :)

**Comment by stephentoub** [comment]
Excellent.  Thanks!

**Pull request merged**
