### PR TITLE
[On hold til 3/7] [release/1.1.0] Baseline 1.0.0 value tuple

### PR DESCRIPTION
**Pull request by ericstj**
This checks in the package baseline info from the 1.0.0 release and configures ValueTuple to use that.

/cc @jcouv

### CODE REVIEW

**Comment by jcouv** [comment]
Fixes https://github.com/dotnet/corefx/issues/15826 (downgrade warnings)

**Comment by jcouv** [comment]
@dotnet-bot test Innerloop OSX Debug Build and Test please

**Comment by jcouv** [comment]
@weshaggard @tarekgh @jkotas for review. 
I will submit to shiproom after that. Thanks

**Comment by jcouv** [comment]
A note for code review: 
Eric copied the baseline files from 1.0.0 branch. That is the bulk of the change.
The rest (the second and third commits) have a small change to `Packaging.props` and `System.ValueTuple.pkgproj` to point to those baseline files.

**Comment by jcouv** [comment]
@weshaggard @tarekgh @jkotas @AlexGhiondea for review. Thanks

**Comment by weshaggard** [comment]
@Jcouv so it seems like @ericstj agreed with me to go with your option (2) which was to change the existing dependencies. While I do still think that is the best option it is potentially a source breaking change  which I think is acceptable.

**Comment by jcouv** [comment]
Correct. I will make sure to call this out in the email to shiproom after review:

> If a customer is getting the System.Collections package indirectly (only via the ValueTuple package) and gets the ValueTuple package after this fix, she could suffer a regression.
> But we do not expect many customers to have such indirect-only references and to be using ValueTuple as this point, as the main usage will come from C#7.0 which is not released yet.

**Comment by jcouv** [comment]
Ping. I crave approval ;-)

**Comment by nguerrera** [comment]
I have seen downgrades involving System.Collections.Immutable too. Is it the same issue? Are we fixing all of the packages that can exhibit the behavior?

**Comment by ericstj** [comment]
@nguerrera this isn't so much a "fix" as a change in policy.  If folks desire that more packages have this policy applied we'll need to call those out individually.

**Comment by jcouv** [comment]
This PR is on hold until 3/7 when the branch will re-open. I will keep the PR open until then, and restart the shiproom discussion then.

**Comment by jcouv** [comment]
From discussion with @ericstj and @Petermarcu this fix is no longer valuable. Instead we recommend customers to upgrade to 1.1.

**Pull request closed without merging**
