### PR TITLE
Fix casing for native binaries

### PR DESCRIPTION
**Pull request by chcosta**
Native binary path is in 'Native'.  https://github.com/dotnet/corefx/blob/dev/eng/src/Native/build-native.sh#L260

This is causing package builds to fail on Unix

### CODE REVIEW

**Comment by weshaggard** [comment]
Where is the other location that is expecting uppercase? Given a preference I would prefer to keep everything lowercase.

**Comment by mellinoe** [comment]
LGTM. I have this same change in my big testing PR.

**Comment by mellinoe** [comment]
I'm also fine with changing everything to lower-case if we know where all the places are.

**Comment by chcosta** [comment]
lower case sounds good to me.  I'll scour the source code and try to find instances of upper-case

**Pull request merged**
