### PR TITLE
Add issue template directing new issues to dotnet/runtime

### PR DESCRIPTION
**Pull request by danmoseley**

### CODE REVIEW

**Review by stephentoub — APPROVED** [review]

**Comment by stephentoub** [comment]
I see this when I try to view the file:
image
https://help.github.com/en/github/building-a-strong-community/about-issue-and-pull-request-templates

**Comment by danmoseley** [comment]
hmm

**Comment by danmoseley** [comment]
My assumption is that this workflow still works, though. I suggest to merge and see.

**Comment by danmoseley** [comment]
Yeah, it works.

**Pull request merged**
