### PR TITLE
Re-enabling the MathF.Atan2 and MathF.Pow tests for all platforms.

### PR DESCRIPTION
**Pull request by tannergooding**
Resolves https://github.com/dotnet/corefx/issues/16674

### CODE REVIEW

**Comment by tannergooding** [comment]
These will probably fail, but the failures should be investigate as it represents an actual issue in the implementation. The tests are covering explicit corner cases where a specific result is expected on all platforms.

**Comment by joperezr** [comment]
I just tried this locally and it failed. I added the output to the issue I logged. The Windows Debug CI runs tests in x86 so that will fail with same problem.

**Comment by tannergooding** [comment]
Thanks! I am going to investigate these further. Will probably log a bug against the CRT implementation for Windows x86 and will add a workaround on the CoreCLR side.

**Comment by joperezr** [comment]
BTW, if you want to repro locally, you can simply run:
```
(Make your changes to turn them into facts, instead of conditional facts.)
build.cmd -buildArch:x86
msbuild src\System.Runtime.Extensions\tests\System.Runtime.Extensions.Tests.csproj /p:ArchGroup=x86 /t:rebuildandtest
```

**Comment by tannergooding** [comment]
Sadly we don't work on VS2017 yet (and I don't have VS2015 installed anymore).

**Comment by tannergooding** [comment]
Hmmm, the CRT functions that the failing calls resolve down to are returning the expected values. I am going to continue digging.

**Comment by tannergooding** [comment]
Ok. Interesting....

`Assert.Equal(8.0f, MathF.Pow(2.0f, 3.0f));` is failing with an expect value of 9. And given that `Assert.Equal(-0.0f, MathF.Atan2(-0.0f, 0.0f));` is failing with an expected value of `MathF.PI`, my conclusion is that arguments are getting swapped somewhere.

Fun.

**Comment by tannergooding** [comment]
@mellinoe, are you aware of anywhere in the x86 debug (this is not failing for Release) codegen that constants or registers could potentially be swapped?

**Comment by tannergooding** [comment]
My best guess at this point is that we have some invalid debug check that makes a no longer valid assumption in relation to FCALLs.

Specifically, we declare `Atan2` and `Pow` as:
```C++
FCDECL2(static float, Atan2, float y, float x);
FCDECL2(static float, Pow, float x, float y);
```

On Windows, FCDECL2 is defined as (note how the registers are swapped for `FCDECL2_VV` on 32-bit, but not on 64-bit:
```
#ifdef _TARGET_X86_

// Choose the appropriate calling convention for FCALL helpers on the basis of the JIT calling convention
#define F_CALL_CONV __fastcall

#define FCDECL2(rettype, funcname, a1, a2) rettype F_CALL_CONV funcname(a1, a2)
#define FCDECL2_VV(rettype, funcname, a1, a2) rettype F_CALL_CONV funcname(a2, a1)

#else // !_TARGET_X86

#define F_CALL_CONV

#define FCDECL2(rettype, funcname, a1, a2) rettype funcname(a1, a2)
#define FCDECL2_VV(rettype, funcname, a1, a2) rettype funcname(a1, a2)

#endif // _TARGET_X86_ 
```

One of the listed 'gotchas' of using FCALLs is the following:
> //  - If first and/or second argument of your FCall is 64-bit value on x86
> //    (ie INT64, UINT64 or DOUBLE), you must use "V" versions of FCDECL and 
> //    FCIMPL macros to enregister arguments correctly. For example, FCDECL3_IVI 
> //    must be used for FCalls that take 3 arguments and 2nd argument is INT64.

Now, we are only passing 32-bit values around here, but perhaps there is a legacy check related to the assumption we are running on the x87 floating-point stack that is causing a break here....

**Comment by mellinoe** [comment]
@tannergooding Unfortunately I'm not familiar enough with how runtime handles these calls. @jkotas Do you have a better idea of what might be going wrong, specifically on x86?

**Comment by tannergooding** [comment]
I am getting JitDmps now for both x86 debug and release so I can attempt to diff and see if there are any obvious differences.

**Comment by jkotas** [comment]
This gotcha applies to floats too - the comment is not completely accurate. These need to be defined using the `FCDECL1_V` and `FCDECL2_VV` macros. Also, could you please fix the comment as well?

**Comment by tannergooding** [comment]
@jkotas, sure thing. Is there a particular reason why this applies to floats? I would like to be able to clarify in the comment why it applies to 32-bit floating-point values, despite their size.

**Comment by tannergooding** [comment]
Also, I'm wondering why this is only failing on debug and not release as well.

**Comment by jkotas** [comment]
> Is there a particular reason why this applies to floats?

It applies to everything that is not passed in registers in x86 fastcall calling convention. floats are not passed in registers in x86 fastcall calling convention.

> Also, I'm wondering why this is only failing on debug and not release as well.

Because of you just got lucky.

**Comment by mellinoe** [comment]
Actually, if you're referring to the Debug and Release builds in CI here, it's because the Windows_NT Debug build is x86, and the Windows_NT Release build is x64. We should make that more obvious in the labeling.

**Comment by tannergooding** [comment]
Ok, next time we update the CoreCLR version on this side, these tests can be re-enabled.

**Comment by mellinoe** [comment]
> Ok, next time we update the CoreCLR version on this side, these tests can be re-enabled.

We've updated since then. Was there anything else left to do except "turn it on" ?

**Comment by tannergooding** [comment]
Nope. I've rebased and pushed. Tests should pass now.

**Comment by tannergooding** [comment]
I've removed the `NO MERGE` label now that both Windows jobs have passed.

Will merge once I get sign-off and all jobs are passing.

**Comment by tannergooding** [comment]
@mellinoe, am I good to merge?

**Comment by stephentoub** [comment]
Thanks, @tannergooding.

**Pull request merged**
