### PR TITLE
Update document on how to consume local build corefx packages

### PR DESCRIPTION
**Pull request by weshaggard**
Fixes https://github.com/dotnet/corefx/issues/3656

skip ci please

cc @danmosemsft @karelz

### CODE REVIEW

**Comment by danmosemsft** [comment]
Thanks for doing this.
Every time I build with some new change, do i have to update the version number (or delete the existing package)?
It's good to have this documented but we should make this easier in future, ideally I would just set a pointer to some point in my corefx bin folder and forget about it.

**Comment by weshaggard** [comment]
>It's good to have this documented but we should make this easier in future, ideally I would just set a pointer to some point in my corefx bin folder and forget about it.

Unfortunately that requires either some auto-hacking (i.e. us always deleting that installed package, which I would like to avoid if possible) or updates in nuget. The only real other way around this is to copy around raw binaries but that can be tricky if you don't know which ones to copy.

**Comment by danmosemsft** [comment]
@weshaggard can we make it clearer? eg "From then on every time you update your code, you must repeat the step to increment the version number in both the env var and the project file"

**Comment by dotnetjt** [comment]
Hey guys, sorry to comment on something old here, but I've been pulling my hair out on looking for some guidance and clear documentation on dogfooding.

First off, I can dogfood my corefx build by following the instructions. I see my libraries in the publish output. 

However, I'm confused as to how `<RuntimeFrameworkVersion>` comes into play in this scenario. Can you shed some light on it for me? It seems to me that if you've added a package ref to your dogfood package, this is unnecessary to include. Is that true?

Or, on the other hand, if you don't package ref the assembly, but still add the local build location to your nuget feed, will the dogfood package be picked up by putting it's version in this property?

**Comment by weshaggard** [comment]
>However, I'm confused as to how <RuntimeFrameworkVersion> comes into play in this scenario. Can you shed some light on it for me? It seems to me that if you've added a package ref to your dogfood package, this is unnecessary to include. Is that true?

Have a look at https://github.com/dotnet/sdk/blob/a4bceb67b160c72318a581d87d52796e4fa31794/src/Tasks/Microsoft.NET.Build.Tasks/build/Microsoft.NET.Sdk.DefaultItems.targets#L67 to get an idea of what RuntimeFrameworkVersion ends up doing. It is more important when you are doing a shared application so for standalone applications it isn't as critical. However it is a good idea I to pick a version close to the corefx build you are using otherwise you might end up with an older incompatible runtime. Note that whatever version you pick is what version of Microsoft.NETCore.App (https://github.com/dotnet/sdk/blob/feca75bd43f6374715621024d930164de8bde67c/src/Tasks/Microsoft.NET.Build.Tasks/build/Microsoft.NET.Sdk.DefaultItems.props#L49) you get seeded in your project. When you specify your local Microsoft.Private.CoreFx.NETCoreApp version it will override some of the binaries from Microsoft.NETCore.App but not all of them, in particular the runtime will not be overridden so you will need to have a new enough version to ensure your runtime is still compatible with the corefx build you produced.

**Comment by dotnetjt** [comment]
Ok, that's somewhat how I assumed it would work, but wasn't very clear from the docs. For what it's worth, I'm also targetting a package for my own runtime, so I am covered there as well. But makes more sense now.

Thank you.

**Pull request merged**
