### PR TITLE
Disable Test_Write_Metric_EventListener test

### PR DESCRIPTION
**Pull request by stephentoub**
cc: @brianrob 
https://github.com/dotnet/corefx/issues/25029

### CODE REVIEW

**Comment by brianrob** [comment]
@stephentoub, from this issue, it looks like this failure happens 1-2 times per month if that.  Are you seeing it more often?  I'm OK with disabling this, but I suspect it's going to be very difficult to reproduce, and the answer is more likely going to be just to increase the acceptable time in the test or run the test multiple times to drive noise out of the result.  Thoughts?

**Comment by stephentoub** [comment]
> Thoughts?

We end up suffering from a thousand papercuts; a given test only fails once or twice a month, but we've got hundreds of thousands of tests, which means any given PR often ends up hitting some random failure and causing productivity loss.  I would like for us to become much more stringent about disabling / fixing tests, even if they only fail once in a blue moon.

> The answer is more likely going to be just to increase the acceptable time

If that's the answer, I'm fine with that being the fix for the issue.  For now, though, I would like to just disable the test, and then whoever addresses the issue can determine the right fix, which could be extending a timeout, finding an underlying bug, deleting the test, etc.

**Comment by brianrob** [comment]
Ok, sounds good.

**Comment by stephentoub** [comment]
Thanks

**Pull request merged**
