### PR TITLE
Updated to new buildtools for perf targets

### PR DESCRIPTION
**Pull request by ianhays**
Consumes the changes from https://github.com/dotnet/buildtools/pull/299

Enables the perf tests to be run using -trait Benchmark=true

### CODE REVIEW

**Comment by stephentoub** [comment]
LGTM

**Comment by ianhays** [comment]
MESSAGE:
System.NullReferenceException : Object reference not set to an instance of an object.
+++++++++++++++++++
STACK TRACE:
at System.Net.Sockets.Socket.WSARecvMsgBlocking(IntPtr socketHandle, IntPtr msg, Int32& bytesTransferred, IntPtr overlapped, IntPtr completionRoutine) in d:\j\workspace\dotnet_corefx_windows_release_prtest\src\System.Net.Sockets\src\System\Net\Sockets\Socket.Windows.cs:line 116 at System.Net.Sockets.SocketPal.ReceiveMessageFrom(Socket socket, SafeCloseSocket handle, Byte[] buffer, Int32 offset, Int32 size, SocketFlags& socketFlags, SocketAddress socketAddress, SocketAddress& receiveAddress, IPPacketInformation& ipPacketInformation, Int32& bytesTransferred) in d:\j\workspace\dotnet_corefx_windows_release_prtest\src\System.Net.Sockets\src\System\Net\Sockets\SocketPal.Windows.cs:line 409 at System.Net.Sockets.Socket.ReceiveMessageFrom(Byte[] buffer, Int32 offset, Int32 size, SocketFlags& socketFlags, EndPoint& remoteEP, IPPacketInformation& ipPacketInformation) in d:\j\workspace\dotnet_corefx_windows_release_prtest\src\System.Net.Sockets\src\System\Net\Sockets\Socket.cs:line 1774 at System.Net.Sockets.Tests.ReceiveMessageFrom.Success() in d:\j\workspace\dotnet_corefx_windows_release_prtest\src\System.Net.Sockets.Legacy\tests\FunctionalTests\ReceiveMessageFrom.cs:line 32

**Comment by ianhays** [comment]
@dotnet-bot test this please

**Comment by jasonwilliams200OK** [comment]
@dotnet-bot, test this please.

**Comment by jasonwilliams200OK** [comment]
:white_check_mark:  :+1: 
This will also unblock FreeBSD and non-Ubuntu Linux builds: https://github.com/dotnet/buildtools/issues/292.
 /cc @pgavlin

**Pull request merged**
