### PR TITLE
Fix missing System.Private.Uri dependencies

### PR DESCRIPTION
**Pull request by ericstj**
Update buildtools to fix missing System.Private.* dependencies.

/cc @weshaggard @roncain

### CODE REVIEW

**Comment by stephentoub** [comment]
@ericstj, FYI, merging the TFS changes in another PR caused a merge conflict here.

**Comment by ericstj** [comment]
Crud was hoping we'd just close out that TFS mirror PR.  That's OK, I'll rebase this.

**Comment by weshaggard** [comment]
LGTM - Does this also include your other path fix?

**Comment by ericstj** [comment]
No, this is prior to the fixes I was making for @tarekgh's dev/api work.

**Comment by ericstj** [comment]
@dotnet-bot test Innerloop CentOS7.1 Debug Build and Test

**Pull request merged**
