### PR TITLE
Change an internal Hashtable to a Dictionary.

### PR DESCRIPTION
**Pull request by vargaz**

### CODE REVIEW

**Review by stephentoub — COMMENTED** [review]
Thanks. Two things:
1. This code is only compiled in corelib. It should be made in dotnet/coreclr rather than dotnet/corefx.
2. This is introducing a global lock on a path that used to be lock-free, and that looks like it could be hot-path. How do we know this won't impact scalability?

**Comment by jkotas** [comment]
>  looks like it could be hot-path

ASP.NET calls this per request on some paths.

**Comment by vargaz** [comment]
- The hashtable was synchronized before.
- Isn't this the version of this file which ends up in System.Private.CoreLib in the mono repo ?

**Comment by vargaz** [comment]
It was a SyncHashtable before, nm.

**Pull request closed without merging**
