### PR TITLE
[port] XEvent Delay bug fix

### PR DESCRIPTION
**Pull request by tarikulsabbir**
Description
XEvents are arriving as expected, but with 1 XEvent delay. It means that to receive the most recent XEvent, the app has to wait for another XEvent to be generated. 

Customer Impact
Blocker for shipping the XEvent library for .NET Standard. TdService (a SQL Azure feature) uses the Microsoft.SqlServer.XEvent.Linq namespace to consume XEvents which underneath uses System.Data.SqlClient. It is susceptible to this bug as it is dependent on getting XEvents for statement execution or changes in state of DBs or policies within the SQLServer.

Regression
No, since this code path existed in .Net Framework before it got fixed. This PR ports the fix from .Net Framework.

Risk
low. The fix has been in Framework for some time with no reported negative effects to SqlClient.

This is already merged to master #36015

### CODE REVIEW

**Comment by danmosemsft** [comment]
Does this need to go into 2.1? @tarikulsabbir @AfsanehR 

Also briefly what are XEvents? Some SQL specific evening system apparently?

**Comment by David-Engel** [comment]
> Does this need to go into 2.1? @tarikulsabbir @AfsanehR

@danmosemsft I asked the original requestor to confirm, but I don't believe so. He did not say anything previously when I said we would port it into 3.0 and 2.2.

> Also briefly what are XEvents? Some SQL specific evening system apparently?

Yes. Extended Events for gathering detailed information about database events:
https://docs.microsoft.com/en-us/sql/relational-databases/extended-events/extended-events?view=sql-server-2017

**Comment by danmosemsft** [comment]
Thanks @David-Engel yes if you can confirm 2.1 is not required, that would be great.

> Risk: High. The Threat Detection Service (TdService) in SQL Azure is susceptible to this bug as it is dependent on getting XEvents for statement execution or changes in state of DBs or policies within the SQLServer.
The risk field is intended to suggest to shiproom what the risk is that this will cause more problems. Their job is basically making a risk vs benefit calculation.
Should I read the above statement to mean there is a high risk of breaking "TDService" ? If so we need to be very careful and will need extra scrutiny, exhaustive testing, etc. 
OR perhaps this was intended to mean "high risk of customer impact if we don't fix this". If so what is the risk to the product of the change ?

**Comment by David-Engel** [comment]
> > Risk: High. The Threat Detection Service (TdService) in SQL Azure is susceptible to this bug as it is dependent on getting XEvents for statement execution or changes in state of DBs or policies within the SQLServer.
> 
> The risk field is intended to suggest to shiproom what the risk is that this will cause more problems. Their job is basically making a risk vs benefit calculation.
> Should I read the above statement to mean there is a high risk of breaking "TDService" ? If so we need to be very careful and will need extra scrutiny, exhaustive testing, signoff by "TdService" that they have verified it etc.
> OR perhaps this was intended to mean "high risk of customer impact if we don't fix this". If so what is the risk to the product of the change ?

@danmosemsft The latter. TDService requested we port this fix for them. The risk field should say low. The fix has been in Framework for some time with no reported negative effects to SqlClient.

**Comment by tarikulsabbir** [comment]
> > > Risk: High. The Threat Detection Service (TdService) in SQL Azure is susceptible to this bug as it is dependent on getting XEvents for statement execution or changes in state of DBs or policies within the SQLServer.
> > 
> > 
> > The risk field is intended to suggest to shiproom what the risk is that this will cause more problems. Their job is basically making a risk vs benefit calculation.
> > Should I read the above statement to mean there is a high risk of breaking "TDService" ? If so we need to be very careful and will need extra scrutiny, exhaustive testing, signoff by "TdService" that they have verified it etc.
> > OR perhaps this was intended to mean "high risk of customer impact if we don't fix this". If so what is the risk to the product of the change ?
> 
> @danmosemsft The latter. TDService requested we port this fix for them. The risk field should say low. The fix has been in Framework for some time with no reported negative effects to SqlClient.

**Comment by danmosemsft** [comment]
> Blocker for shipping the XEvent library for .NET Standard. 

Who owns this library - is it ours?

**Comment by David-Engel** [comment]
> > Blocker for shipping the XEvent library for .NET Standard.
> 
> Who owns this library - is it ours?

@danmosemsft Yes. TdService (a SQL Azure feature) uses the Microsoft.SqlServer.XEvent.Linq namespace to consume XEvents which underneath uses System.Data.SqlClient.

**Comment by vivmishra** [comment]
Approved for 2.2.5
Wait for branch to open.

**Comment by danmosemsft** [comment]
Marking nomerge until branch is open.

/azp run

**Comment by David-Engel** [comment]
@vivmishra @danmosemsft Do you know what version of the SqlClient package containing this fix 2.2.5 will correspond with? 4.6.1, I assume?

**Comment by danmosemsft** [comment]
@wtgodbe can you answer that? Also, can you please check package authoring? It looks like we forgot it here again. 😢

**Comment by wtgodbe** [comment]
The version of SqlClient will be 4.6.2, but we need to manually "turn on" the build for that package - please add a commit similar to https://github.com/dotnet/corefx/commit/c82b438c8ed6eaba3dbed009cd484d5bb392237e in order to get the package building for 2.2.5.

**Comment by danmosemsft** [comment]
Thanks @wtgodbe - could you keep track of this one to make sure it happens correctly?

@tarikulsabbir let us know if you have questions. Without this authoring, the change will not ship

**Comment by wtgodbe** [comment]
Sure thing, I've assigned myself.

**Comment by tarikulsabbir** [comment]
> Sure thing, I've assigned myself.

Hi, @wtgodbe , Just to clarify, are you doing the commit yourself ? or we will be doing it? Kindly confirm.

**Comment by wtgodbe** [comment]
@tarikulsabbir please put up the commit yourself, then I will review it.

**Comment by tarikulsabbir** [comment]
> @tarikulsabbir please put up the commit yourself, then I will review it.

Sure, No problem. I will let you know once I do the commit. Thanks.

**Comment by tarikulsabbir** [comment]
Hi @wtgodbe , I made the changes for packagesIndex.json and dir.props. I was looking at the changes for  packages.builds. Currently on the release 2.2 I don't see these changes -
` <Project Include="$(MSBuildThisFileDirectory)System.Data.SqlClient\pkg\System.Data.SqlClient.pkgproj">
      <AdditionalProperties>$(AdditionalProperties)</AdditionalProperties>
    </Project>`

It currently has the following -
`    <Project Include="$(MSBuildThisFileDirectory)..\pkg\Microsoft.Windows.Compatibility\Microsoft.Windows.Compatibility.builds">
      <AdditionalProperties>$(AdditionalProperties)</AdditionalProperties>
    </Project>
`

Do we need to remove these lines  and add your changes? Or do we keep these ones and also add your changes? Kindly clarify. Thanks.

**Comment by wtgodbe** [comment]
@tarikulsabbir we should add `SqlClient` without removing the lines you referenced. Basically, `packages.builds` keeps a running list of all of the packages we want to build for the current release. At the moment, that's just `Microsoft.Windows.Compatibility` - we want to add `SqlClient` to that list. After each release, the list resets.

**Comment by tarikulsabbir** [comment]
> @tarikulsabbir we should add `SqlClient` without removing the lines you referenced. Basically, `packages.builds` keeps a running list of all of the packages we want to build for the current release. At the moment, that's just `Microsoft.Windows.Compatibility` - we want to add `SqlClient` to that list. After each release, the list resets.

I understand. Thanks a lot. I will make the change now.

**Comment by tarikulsabbir** [comment]
Hi @wtgodbe , I pushed the commit. Please let me know if anything else needs changes. Thanks a lot for the help.

**Comment by wtgodbe** [comment]
Looks like we also need to update https://github.com/dotnet/corefx/blob/release/2.2/external/harvestPackages/harvestPackages.props#L50 to harvest 4.6.1 instead of 4.6.0 - @ericstj can you confirm?

**Comment by ericstj** [comment]
Yeah, sounds right.  It may not matter depending on what SqlClient harvests but its best to keep those bits up to date.

**Comment by tarikulsabbir** [comment]
@wtgodbe , harvestPackages.props version is changed to 4.6.1. Thanks a lot.

**Comment by wtgodbe** [comment]
@mmitche I thought we'd shipped SqlClient 4.6.1 with the 2.2.3 release - did it get pushed back to 2.2.4? https://github.com/dotnet/corefx/pull/35525

@tarikulsabbir if SqlClient 4.6.1 is actually shipping with 2.2.4, the build here won't succeed until the 4.6.1 package is pushed to nuget (which is something we'd just have to wait for).

**Comment by mmitche** [comment]
@wtgodbe I don't see it in the manifest there or in 2.2.4

**Comment by wtgodbe** [comment]
Looks like we missed the boat last time we tried to ship SqlClient. Therefore @tarikulsabbir, we need to do the following things:

1. Revert the `PackageVersion` & `AssemblyVersion` to 4.6.1 & 4.5.0.1
2. Revert the version of `SqlClient` in `HarvestPackages.props` to 4.6.0

This will make it so that we ship a 4.6.1 version of `SqlClient` (which we haven't done yet), with the changes we intended to ship in 2.2.3, plus the changes from this PR. Sorry for all of the confusion.

**Comment by tarikulsabbir** [comment]
@wtgodbe , done. I kept the changes made in packages.builds as it wasn't mentioned in the list (in the earlier comment). Please review. Thanks.

**Comment by wtgodbe** [comment]
@tarikulsabbir it looks good!

**Comment by tarikulsabbir** [comment]
Thanks @wtgodbe for the help.

**Comment by tarikulsabbir** [comment]
Hi @wtgodbe , Hi , I have a different question regarding the daily build of the master branch. So we also merged this fix in the master branch and one of the stakeholders is asking for a build to test it in their system before the release 2.2. As it was merged in the master, we checked the daily build from the master branch but couldn't find the System.Data.Sqlclient.dll. Do we have to do any kind of versioning change? or is there any other way to get this fix in a build. I am not sure whether you're the right person to ask but any kind of suggestion or pointing us to right direction would help a lot. Thanks.

**Comment by wtgodbe** [comment]
@dotnet-bot test Linux x64 Release Build
@dotnet-bot test NETFX x86 Release Build
@dotnet-bot test OSX x64 Debug Build

**Comment by wtgodbe** [comment]
@tarikulsabbir were you looking for the package on myget, or in azure storage? We recently have been having issues publishing to myget due to storage space issues, but the package is present in our Azure storage blob. Feel free to reach out to me over Teams or email if you need help accessing that storage location.

**Comment by wtgodbe** [comment]
@dotnet-bot test Linux x64 Release Build
@dotnet-bot test NETFX x86 Release Build
@dotnet-bot test OSX x64 Debug Build

**Comment by wtgodbe** [comment]
@dotnet-bot test Linux x64 Release Build

**Pull request merged**
