### PR TITLE
Disable tests to unblock CI

### PR DESCRIPTION
**Pull request by davidsh**
Disabling tests for #12637, #12778, #10504, and #13188

### CODE REVIEW

**Comment by davidsh** [comment]
cc: @danmosemsft @stephentoub @CIPop

**Comment by danmosemsft** [comment]
LGTM thanks David.

**Comment by davidsh** [comment]
Test OuterLoop Windows_NT Debug Build and Test
Test OuterLoop CentOS7.1 Debug Build and Test

**Comment by davidsh** [comment]
Test OuterLoop Windows_NT Debug

**Comment by davidsh** [comment]
Test OuterLoop Windows_NT Debug Build and Test

**Comment by davidsh** [comment]
Test OuterLoop Windows_NT Debug Build and Test
Test OuterLoop CentOS7.1 Debug Build and Test

**Comment by davidsh** [comment]
Test OuterLoop CentOS7.1 Debug

(System.Net.WebException : An error occurred while sending the request. Problem with the SSL CA cert (path? access rights?)\n---- System.Net.Http.HttpRequestException : An error occurred while sending the request.\n-------- System.Net.Http.CurlException : Problem with the SSL CA cert (path? access rights?))

**Comment by davidsh** [comment]
Test OuterLoop CentOS7.1 Debug

**Pull request merged**
