### PR TITLE
Use Array.Empty<T>() in more places

### PR DESCRIPTION
**Pull request by stephentoub**
We've previously done multiple sweeps.  Doing another.

### CODE REVIEW

**Comment by stephentoub** [comment]
Done with a little Roslyn-based tool:
```C#
using System;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

public static class Program
{
    public static async Task Main()
    {
        string loc = @"d:\repos\coreclr\src\System.Private.CoreLib\";
        foreach (string path in Directory.EnumerateFiles(loc, "*.cs", SearchOption.AllDirectories))
        {
            //if (path.IndexOf(@"\src\", loc.Length) < 0) continue;

            string text = File.ReadAllText(path);
            using (var workspace = new AdhocWorkspace())
            {
                Project proj = workspace.AddProject(nameof(EmptyArrayRewriter), LanguageNames.CSharp).WithMetadataReferences(new[] { MetadataReference.CreateFromFile(typeof(object).Assembly.Location) });
                Document doc = proj.AddDocument(Path.GetFileName(path), SourceText.From(text));
                Compilation compilation = await doc.Project.GetCompilationAsync();
                SyntaxNode root = await doc.GetSyntaxRootAsync();

                var rewriter = new EmptyArrayRewriter { _model = compilation.GetSemanticModel(root.SyntaxTree) };
                SyntaxNode node = rewriter.Visit(root);
                if (rewriter._madeChanges)
                {
                    File.WriteAllText(path, node.ToFullString());
                    Console.ForegroundColor = ConsoleColor.Yellow;
                    Console.WriteLine(path);
                    Console.ResetColor();
                }
                else
                {
                    Console.WriteLine(path);
                }
            }
        }
    }
}

internal sealed class EmptyArrayRewriter : CSharpSyntaxRewriter
{
    internal SemanticModel _model;
    internal bool _madeChanges;

    public override SyntaxNode VisitArrayCreationExpression(ArrayCreationExpressionSyntax node)
    {
        SyntaxList<ArrayRankSpecifierSyntax> rank = node.Type.RankSpecifiers;
        if (rank.Count == 1)
        {
            SeparatedSyntaxList<ExpressionSyntax> sizes = rank[0].Sizes;
            if (sizes.Count == 1 &&
                ((sizes[0].ChildTokens().Count() == 1 && sizes[0].ChildTokens().First().ValueText == "0") ||
                (rank[0].DescendantNodes().Any(n => n is OmittedArraySizeExpressionSyntax) && node.Initializer != null && node.Initializer.Expressions.Count == 0)))
            {
                _madeChanges = true;
                return SyntaxFactory.InvocationExpression(
                    SyntaxFactory.MemberAccessExpression(
                        SyntaxKind.SimpleMemberAccessExpression, SyntaxFactory.IdentifierName("Array"), SyntaxFactory.GenericName(SyntaxFactory.Identifier("Empty"), SyntaxFactory.TypeArgumentList(
                        SyntaxFactory.SeparatedList(new[] { node.Type.ElementType })))))
                    .WithLeadingTrivia(node.GetLeadingTrivia()).WithTrailingTrivia(node.GetTrailingTrivia());
            }
        }

        return base.VisitArrayCreationExpression(node);
    }
}
```

**Comment by MisinformedDNA** [comment]
@stephentoub Any plans to convert it into an analyzer for use in [roslyn-analyzers](https://github.com/dotnet/roslyn-analyzers)? Maybe there should be a `Microsoft.Performance.Analyzers`?

**Comment by stephentoub** [comment]
@MisinformedDNA:
https://github.com/dotnet/roslyn-analyzers/blob/c5d23f2f2b4da4b2a9b0c92d69937670e742bf59/src/Microsoft.NetCore.Analyzers/Core/Runtime/AvoidZeroLengthArrayAllocations.cs

**Comment by stephentoub** [comment]
> You're doing lots of cleanup!

There's lots to do :)

**Pull request merged**
