### PR TITLE
Cleanup unused/duplicate code(Xml)

### LINKED ISSUE #28069: Investigate if there is a duplicate code in the common folder for XmlSchema
As @danmosemsft has mentioned in https://github.com/dotnet/corefx/issues/28055 there are two copies of XsdDateTime which might be the same:

```
C:\git\corefx\src\Common\src\System\Xml\Schema\XsdDateTime.cs
C:\git\corefx\src\System.Private.Xml\src\System\Xml\Schema\XsdDateTime.cs
```

If that is the case there might be more copies of other files from XmlSchema as well. Investigate and remove any duplicate code.

### PR DESCRIPTION
**Pull request by MarcoRossignoli**
closes #28069 

I did some check and files on `src\Common\src\System\Xml\*.*` are unused.
Xml files used are in `src\System.Private.Xml\src\System\Xml`, there are other xml files here, so i thought to remove xml folder in common.

Tested on local Win/Linux, wait for CI.

/cc @krwq @danmosemsft

### CODE REVIEW

**Comment by krwq** [comment]
@dotnet-bot help

**Comment by krwq** [comment]
@dotnet-bot test Outerloop Windows x64 Debug Build

**Comment by stephentoub** [comment]
How does this relate to https://github.com/dotnet/corefx/pull/28989?

**Comment by krwq** [comment]
@stephentoub - #28989 removes compiled code. This removed some leftover files which are not used anymore

**Comment by MarcoRossignoli** [comment]
sorry @stephentoub i made a typo, updated.

**Comment by stephentoub** [comment]
Ok, thanks, as long as they don't conflict :)

**Comment by krwq** [comment]
Outerloop Windows x64 Debug Build failure seem to be unrelated

**Pull request merged**
