### PR TITLE
Update packages to rc3-23829

### PR DESCRIPTION
**Pull request by stephentoub**

### CODE REVIEW

**Comment by stephentoub** [comment]
@weshaggard, @chcosta, from the build failures, it looks like this is blocked on the Debian RID change?
e.g.
```
20:16:10 EXEC : error : System.IO.Compression 4.1.0-rc3-23823 provides a compile-time reference assembly for System.IO.Compression on DNXCore,Version=v5.0, but there is no run-time assembly compatible with debian.8.2-x64. [d:\j\workspace\windows_nt_de---06b7984d\build.proj]
```

**Comment by stephentoub** [comment]
@dotnet-bot test this please

**Comment by chcosta** [comment]
Looking

**Comment by chcosta** [comment]
The immediate problems I see is that Microsoft.NetCore.Platforms does not include the debian fix - https://github.com/dotnet/corefx/commit/5cf5f2e7a9048d9d8d92678048e309f438164015

If I manually apply that fix, then I see some other package restore issues, but I'm not certain if they are valid at this point or not.  Stephen, you'll need to consume a package which contains the fix mentioned previously.  If tomorrow's packages do not contain the fix, then there may be something broken in the build pipeline.

**Comment by stephentoub** [comment]
Ok.  Thanks, @chcosta.  I'll try to update this again with tomorrow's packages.

**Comment by stephentoub** [comment]
@ericstj, @chcosta, I followed Chris' suggestion and updated to rc3-23829, now it's failing with these errors:
```
11:57:04   [19:57:17.87] Restoring all packages...
11:57:59 EXEC : error : System.Resources.ResourceManager 4.0.1-rc3-23829 provides a compile-time reference assembly for System.Resources.ResourceManager on DNXCore,Version=v5.0, but there is no run-time assembly compatible with win7-x64. [d:\j\workspace\windows_nt_de---06b7984d\build.proj]
11:57:59 EXEC : error : System.Runtime.Serialization.Primitives 4.1.0-rc3-23829 provides a compile-time reference assembly for System.Runtime.Serialization.Primitives on DNXCore,Version=v5.0, but there is no run-time assembly compatible with win7-x64. [d:\j\workspace\windows_nt_de---06b7984d\build.proj]
11:57:59 EXEC : error : Some packages are not compatible with DNXCore,Version=v5.0 (win7-x64). [d:\j\workspace\windows_nt_de---06b7984d\build.proj]
11:57:59 EXEC : error : System.Resources.ResourceManager 4.0.1-rc3-23829 provides a compile-time reference assembly for System.Resources.ResourceManager on DNXCore,Version=v5.0, but there is no run-time assembly compatible with win7-x86. [d:\j\workspace\windows_nt_de---06b7984d\build.proj]
11:57:59 EXEC : error : System.Runtime.Serialization.Primitives 4.1.0-rc3-23829 provides a compile-time reference assembly for System.Runtime.Serialization.Primitives on DNXCore,Version=v5.0, but there is no run-time assembly compatible with win7-x86. [d:\j\workspace\windows_nt_de---06b7984d\build.proj]
11:57:59 EXEC : error : Some packages are not compatible with DNXCore,Version=v5.0 (win7-x86). [d:\j\workspace\windows_nt_de---06b7984d\build.proj]
11:58:20 EXEC : error : System.IO.Compression 4.1.0-rc3-23829 provides a compile-time reference assembly for System.IO.Compression on DNXCore,Version=v5.0, but there is no run-time assembly compatible with win7-x64. [d:\j\workspace\windows_nt_de---06b7984d\build.proj]
11:58:20 EXEC : error : Some packages are not compatible with DNXCore,Version=v5.0 (win7-x64). [d:\j\workspace\windows_nt_de---06b7984d\build.proj]
11:58:20 EXEC : error : System.IO.Compression 4.1.0-rc3-23829 provides a compile-time reference assembly for System.IO.Compression on DNXCore,Version=v5.0, but there is no run-time assembly compatible with win7-x86. [d:\j\workspace\windows_nt_de---06b7984d\build.proj]
11:58:20 EXEC : error : Some packages are not compatible with DNXCore,Version=v5.0 (win7-x86). [d:\j\workspace\windows_nt_de---06b7984d\build.proj]
11:58:20 EXEC : error : System.IO.Compression 4.1.0-rc3-23829 provides a compile-time reference assembly for System.IO.Compression on DNXCore,Version=v5.0, but there is no run-time assembly compatible with win7-x64. [d:\j\workspace\windows_nt_de---06b7984d\build.proj]
11:58:20 EXEC : error : Some packages are not compatible with DNXCore,Version=v5.0 (win7-x64). [d:\j\workspace\windows_nt_de---06b7984d\build.proj]
11:58:20 EXEC : error : System.IO.Compression 4.1.0-rc3-23829 provides a compile-time reference assembly for System.IO.Compression on DNXCore,Version=v5.0, but there is no run-time assembly compatible with win7-x86. [d:\j\workspace\windows_nt_de---06b7984d\build.proj]
11:58:20 EXEC : error : Some packages are not compatible with DNXCore,Version=v5.0 (win7-x86). [d:\j\workspace\windows_nt_de---06b7984d\build.proj]
11:58:20 EXEC : error : System.IO.Compression 4.1.0-rc3-23829 provides a compile-time reference assembly for System.IO.Compression on DNXCore,Version=v5.0, but there is no run-time assembly compatible with win7-x64. [d:\j\workspace\windows_nt_de---06b7984d\build.proj]
11:58:20 EXEC : error : Some packages are not compatible with DNXCore,Version=v5.0 (win7-x64). [d:\j\workspace\windows_nt_de---06b7984d\build.proj]
11:58:20 EXEC : error : System.IO.Compression 4.1.0-rc3-23829 provides a compile-time reference assembly for System.IO.Compression on DNXCore,Version=v5.0, but there is no run-time assembly compatible with win7-x86. [d:\j\workspace\windows_nt_de---06b7984d\build.proj]
11:58:20 EXEC : error : Some packages are not compatible with DNXCore,Version=v5.0 (win7-x86). [d:\j\workspace\windows_nt_de---06b7984d\build.proj]
11:58:32 EXEC : error : System.IO.Compression 4.1.0-rc3-23829 provides a compile-time reference assembly for System.IO.Compression on DNXCore,Version=v5.0, but there is no run-time assembly compatible with win7-x64. [d:\j\workspace\windows_nt_de---06b7984d\build.proj]
11:58:32 EXEC : error : Some packages are not compatible with DNXCore,Version=v5.0 (win7-x64). [d:\j\workspace\windows_nt_de---06b7984d\build.proj]
11:58:32 EXEC : error : System.IO.Compression 4.1.0-rc3-23829 provides a compile-time reference assembly for System.IO.Compression on DNXCore,Version=v5.0, but there is no run-time assembly compatible with win7-x86. [d:\j\workspace\windows_nt_de---06b7984d\build.proj]
11:58:32 EXEC : error : Some packages are not compatible with DNXCore,Version=v5.0 (win7-x86). [d:\j\workspace\windows_nt_de---06b7984d\build.proj]
11:58:32 EXEC : error : System.IO.Compression 4.1.0-rc3-23829 provides a compile-time reference assembly for System.IO.Compression on DNXCore,Version=v5.0, but there is no run-time assembly compatible with win7-x64. [d:\j\workspace\windows_nt_de---06b7984d\build.proj]
11:58:32 EXEC : error : Some packages are not compatible with DNXCore,Version=v5.0 (win7-x64). [d:\j\workspace\windows_nt_de---06b7984d\build.proj]
11:58:32 EXEC : error : System.IO.Compression 4.1.0-rc3-23829 provides a compile-time reference assembly for System.IO.Compression on DNXCore,Version=v5.0, but there is no run-time assembly compatible with win7-x86. [d:\j\workspace\windows_nt_de---06b7984d\build.proj]
11:58:32 EXEC : error : Some packages are not compatible with DNXCore,Version=v5.0 (win7-x86). [d:\j\workspace\windows_nt_de---06b7984d\build.proj]
11:59:25 
d:\j\workspace\windows_nt_de---06b7984d\build.proj(54,5): error MSB3073: The command ""d:\j\workspace\windows_nt_de---06b7984d\Tools/dotnetcli/bin/dotnet.exe" restore --packages "d:\j\workspace\windows_nt_de---06b7984d\packages" --source https://dotnet.myget.org/F/dotnet-core/api/v3/index.json --source https://www.nuget.org/api/v2/ "d:\j\workspace\windows_nt_de---06b7984d\/src" "d:\j\workspace\windows_nt_de---06b7984d\/pkg"" exited with code 1.
```
Suggestions?

**Comment by ericstj** [comment]
I just worked with @pallavit to fix these issues.  It looks like you are both working on the same thing.

**Comment by stephentoub** [comment]
Ok.  @pallavit, if you're fixing this, I can close this PR.  I've been trying to update this since last week, and kept hitting different issues, going from 818 to 823 to 826 and now finally to 829.  The Debian issues got cleared up with the latest packages, revealing this issue.

**Comment by pallavit** [comment]
> Ok. @pallavit, if you're fixing this, I can close this PR. I've been trying to update this since last week, and kept hitting different issues, going from 818 to 823 to 826 and now finally to 829. The Debian issues got cleared up with the latest packages, revealing this issue.

Yes, I am working on the same thing as well since last week :). I am seeing a couple of other issues after the fixes Eric helped me with but I am pounding on them. Feel free to close this PR :).

**Pull request closed without merging**
