### PR TITLE
Add downlevel ValueTuple configuration

### PR DESCRIPTION
**Pull request by ericstj**
I targeted Profile36 rather than 47 since it would work and apply to more frameworks.

/cc @weshaggard @jcouv

### CODE REVIEW

**Comment by jcouv** [comment]
Thanks
FYI for @KevinRansom

**Comment by ericstj** [comment]
@dotnet-bot test Innerloop CentOS7.1 Debug Build and Test

**Comment by ericstj** [comment]
@dotnet-bot test Innerloop CentOS7.1 Release Build and Test

**Comment by ericstj** [comment]
@dotnet-boy test Innerloop Ubuntu14.04 Debug Build and Test

**Comment by ericstj** [comment]
@dotnet-bot test Innerloop CentOS7.1 Release Build and Test

**Comment by ericstj** [comment]
@dotnet-bot test Innerloop Ubuntu14.04 Debug Build and Test

**Pull request merged**
