### PR TITLE
add missing FTP stuff to contract

### PR DESCRIPTION
**Pull request by geoffkizer**
See #13372

### CODE REVIEW

**Comment by geoffkizer** [comment]
@karelz @stephentoub @cipop @davidsh

**Comment by stephentoub** [comment]
@dotnet-bot help

**Comment by stephentoub** [comment]
@dotnet-bot test Innerloop Linux ARM Emulator SoftFP Debug Cross Build
@dotnet-bot test Innerloop Linux ARM Emulator SoftFP Release Cross Build

**Comment by geoffkizer** [comment]
@dotnet-bot test Innerloop Linux ARM Emulator SoftFP Debug Cross Build
@dotnet-bot test Innerloop Linux ARM Emulator SoftFP Release Cross Build

**Pull request merged**
