### PR TITLE
improve abstraction

### PR DESCRIPTION
**Pull request by NonSecwitter**
The condition of being sorted is a question of the internal state of the array. absent an internal representation to convey it's state, knowing the internal state of being sorted depends on (a) compliance with requirements known by successful communication through documentation or (b) as the routine using the array, always performing a sort operation on a received array.

The first case pushes the responsibility of creating and maintaining knowledge of internal state onto the client, thus violating data abstraction principles. The second case would likely be grossly inneficient, and it may not always be clear whether the implementer has assumed the responsibility of assuming nothing is sorted.

### CODE REVIEW

**Comment by Wraith2** [comment]
This is a publc api change which would need to go through the [api review process](https://github.com/dotnet/corefx/blob/686ec27d3ff5337632391f75d9ea9747570fcf60/Documentation/project-docs/api-review-process.md), if it has can you please link to the issue.

**Comment by stephentoub** [comment]
@NonSecwitter, thank you for the interest in contributing, but as @Wraith2 highlighted, this is new public surface area, which needs to follow the mentioned API review process.  Even without that, this PR as it stands doesn't implement the mentioned feature, it just adds it to the reference assembly, and without an implementation to back it up (which would need to be in coreclr), this won't work.  As such, I'm going to close this.

**Comment by NonSecwitter** [comment]
@stephentoub I suspected as much. Unfortunately, I'm not nearly familiar enough with the code base or API process to get that done efficiently. I just wanted to highlight the potential and provide some justification. Given everything else on my plate, I can't say whether I'd get around to full implementation. Is there an internal team to hand this off to?

**Comment by stephentoub** [comment]
You can open an issue with the suggested API, as outlined in https://github.com/dotnet/corefx/blob/master/Documentation/project-docs/api-review-process.md.  See Step 1 in that doc ("Requester files an issue").

**Comment by NonSecwitter** [comment]
I'll give file the issue... I just can't promise how far I can see it through.

**Comment by NonSecwitter** [comment]
@stephentoub Issue created: https://github.com/dotnet/corefx/issues/34744

**Pull request closed without merging**
