### PR TITLE
Fix downgrade warnings about TraceEvent package

### PR DESCRIPTION
**Pull request by weshaggard**
Fixes https://github.com/dotnet/corefx/issues/18836.

cc @stephentoub  @drewscoggins @jorive @brianrob

### CODE REVIEW

**Comment by weshaggard** [comment]
@DrewScoggins I don't know how to test whether or not this impacts the perf runs.

**Comment by brianrob** [comment]
@adiaaida I think you changed the trigger phrases recently.  Can you trigger a new perf run?

**Comment by stephentoub** [comment]
@dotnet-bot help

**Comment by adiaaida** [comment]
@dotnet-bot test Windows_NT x64 perf please
@dotnet-bot test Windows_NT x86 perf please
@dotnet-bot test Windows_NT x86jit32 perf please

**Comment by adiaaida** [comment]
I only changed the coreclr triggers.
@dotnet-bot test Windows_NT perf please

**Comment by jorive** [comment]
LGTM

**Pull request merged**
