### PR TITLE
Remove dead code from S.N.{Security,Sockets}.

### PR DESCRIPTION
**Pull request by pgavlin**
This change removes unused, internal-only APM APIs from the aforementioned assemblies as well as related types.

### CODE REVIEW

**Comment by pgavlin** [comment]
@CIPop @davidsh PTAL. Please let me know if the removed APM APIs in S.N.Security are simply latent--there isn't anything checked in that was using them.

**Comment by CIPop** [comment]
/cc @vijaykota @bartonjs 

Did a quick lookup in desktop code. The internal Security APIs were previously used by TlsStream and provide an APM Async implementation of SslStream. It doesn't appear to be usable via public APIs.
I think it's ok to remove at this time: we can always bring it back if we need to optimize.

TlsStream was the only reason for `NetworkStream::UnsafeBeginMultipleWrite`.

LGTM

Thanks @pgavlin for detecting and removing the unused code!

**Comment by bartonjs** [comment]
Nothing here was something I was expecting to modify, so fine with me :)

**Comment by pgavlin** [comment]
@dotnet-bit test this please

**Comment by pgavlin** [comment]
@dotnet-bot test this please

**Pull request merged**
