### PR TITLE
Not For Merge

### PR DESCRIPTION
**Pull request by Anipik**
This is to check whether dumpling and helix are creating dumps for hung processes

### CODE REVIEW

**Comment by stephentoub** [comment]
@Anipik, do you still need this PR?  It's fine if you do, but if not, it'd be good to close it.  Thanks.

**Comment by danmosemsft** [comment]
This work isn't finished yet

**Comment by karelz** [comment]
@Anipik is it still active work? Any ETA?
If you don't use it right now / on regular basis, maybe closing it for now might be best. You can reopen the PR when you need it again ...

**Comment by Anipik** [comment]
@dotnet-bot test this please

**Comment by stephentoub** [comment]
@Anipik, is this PR still needed?  Can we close it and you can open a new one if/when necessary?

**Comment by Anipik** [comment]
Actually @stephentoub I am using this today for the testing purpose.

**Pull request closed without merging**
