### PR TITLE
Fix Socket.Disconnect on Unix

### PR DESCRIPTION
**Pull request by luhenry**

### CODE REVIEW

**Comment by luhenry** [comment]
cc @stephentoub

**Comment by stephentoub** [comment]
@dotnet-bot test Outerloop OSX10.12 Debug please

**Comment by luhenry** [comment]
@stephentoub does the `SendAsyncs_ReuseInstance_Hostname` test failure seems to be related to this change?

**Comment by stephentoub** [comment]
> does the SendAsyncs_ReuseInstance_Hostname test failure seems to be related to this change?

Unlikely.  Looks like:
https://github.com/dotnet/corefx/issues/16401

@dotnet-bot test OuterLoop Ubuntu14.04 Debug x64 please

**Comment by stephentoub** [comment]
Thanks, @luhenry.

**Pull request merged**
