### PR TITLE
Avoid unnecessary char array allocations in System.Data.SqlClient

### PR DESCRIPTION
**Pull request by Maxwe11**

### CODE REVIEW

**Comment by Maxwe11** [comment]
@dotnet-bot test this please

**Comment by stephentoub** [comment]
@dotnet-bot test this please (GitHub timeout)

**Comment by stephentoub** [comment]
LGTM.  Thanks for fixing these.

cc: @saurabh500

**Comment by NickCraver** [comment]
+1

**Comment by saurabh500** [comment]
@Maxwe11 Thanks for the patch.
Merging this.

**Pull request merged**
