### PR TITLE
Add back missing System.Net.Ping APIs

### PR DESCRIPTION
**Pull request by stephentoub**
Adds back all of the missing Send and SendAsync overloads, plus the support for the SendAsync overloads like PingCompletedEventArgs and SendAsyncCancel.

cc: @davidsh, @cipop, @ericeil, @mellino, @karelz

### CODE REVIEW

**Comment by stephentoub** [comment]
@dotnet-bot Test Outerloop Windows_NT Debug please
@dotnet-bot Test Outerloop Ubuntu14.04 Debug please
@dotnet-bot Test Outerloop OSX Debug please

**Comment by CIPop** [comment]
Thanks @stephentoub !

**Comment by Petermarcu** [comment]
Looks like all the legs are failing and this is what it says you need to do:

Please run /t:UpdatePackageIndex on this project to commit an update

**Comment by stephentoub** [comment]
> Looks like all the legs are failing and this is what it says you need to do

Thanks. Done.

**Comment by stephentoub** [comment]
@adityamandaleeka, another seg fault in CLI:
http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/master/job/centos7.1_release_prtest/176/

**Comment by stephentoub** [comment]
@adityamandaleeka, another seg fault in CLI:
http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/master/job/centos7.1_release_prtest/180/
I logged on to the machine but don't see any core dumps.

**Comment by stephentoub** [comment]
@dotnet-bot Test Innerloop CentOS7.1 Release Build and Test please (seg fault)
@dotnet-bot Test Outerloop Windows_NT Debug please
@dotnet-bot Test Outerloop Ubuntu14.04 Debug please

**Comment by stephentoub** [comment]
@dotnet-bot Test OuterLoop Windows_NT Debug please (https://github.com/dotnet/corefx/issues/11737)

**Pull request merged**
