### PR TITLE
Update buildtools 00412-03

### PR DESCRIPTION
**Pull request by ericstj**
This brings in buildtools version with update to packaging min version for nuget.

We now only pre-req nuget 2.12, but list 3.4 as a requirement for 3.x nuget clients in the package description.

### CODE REVIEW

**Comment by stephentoub** [comment]
I've not seen this error before:
```
12:13:13 [12:13:14.47] Building Managed Libraries...
12:13:14 MSBUILD : error MSB1021: Cannot create an instance of the logger. The given assembly name or codebase was invalid. (Exception from HRESULT: 0x80131047)
12:13:14 Switch: BinClashLogger,D:\j\workspace\centos7.1_deb---75db844b\Tools\net45\Microsoft.DotNet.Build.Tasks.dll;LogFile=D:\j\workspace\centos7.1_deb---75db844b\binclash.log
```

**Comment by ericstj** [comment]
That happens when Nuget doesn't download the new package. I see this regularly when updating buildtools soon after publishing to myget due to http cache age in Nuget.  Just need to rerun after some time.

**Comment by ericstj** [comment]
@dotnet-bot test Innerloop CentOS7.1 Debug Build and Test

**Pull request merged**
