### PR TITLE
Merge v1 to master

### PR DESCRIPTION
**Pull request by stephentoub**
Bringing in new libraries recently committed to v1 branch

### CODE REVIEW

**Comment by stephentoub** [comment]
cc: @joshfree, @nguerrera, @weshaggard

**Comment by joshfree** [comment]
:shipit: LGTM

**Comment by nguerrera** [comment]
LGTM. Still not sure how to best review merges. Were there any tricky conflicts? I tried the 'unified diff with only merged files' in TortoiseGit this time and it just showed me the adds coming in to README.md, which looked fine. I'm unsure if that's representative of the interesting part or not.

**Comment by stephentoub** [comment]
It didn't show any conflicts, my favorite :)

**Comment by stephentoub** [comment]
@dotnet-bot test this please

**Comment by nguerrera** [comment]
@stephentoub Nice. If there are no conflicts, a straight PR from v1.0 to master should work using the UI. Worth trying first to see if the "we can merge this" shows up before resorting to the intermediate branch...

**Comment by stephentoub** [comment]
Good point. Ok, let's do that in the future.

**Pull request merged**
