### PR TITLE
Remove unnecessary assembly-level CLSCompliant attributes

### PR DESCRIPTION
**Pull request by stephentoub**
cc: @weshaggard, @terrajobst, @bartonjs, @ianhays, @nguerrera

### CODE REVIEW

**Comment by bartonjs** [comment]
LGTM.

**Comment by nguerrera** [comment]
:+1: Thanks

**Comment by weshaggard** [comment]
LGTM (assuming CI is green)

**Comment by RehanSaeed** [comment]
Can I ask for more information about why this PR was made? Particularly interested in understanding why the warning asking to enable CLS Compliance still exists.

**Comment by RehanSaeed** [comment]
Reading more about CLS compliance in https://github.com/dotnet/runtime/issues/44194 and I'd love to know more about why this PR was made.

**Comment by stephentoub** [comment]
> I'd love to know more about why this PR was made.

Because there wasn't anything non-compliant here.

**Pull request merged**
