### PR TITLE
Avoid delegate and closure allocations in System.Net.Sockets

### PR DESCRIPTION
**Pull request by Maxwe11**

### CODE REVIEW

**Comment by davidsh** [comment]
@CIPop @pgavlin @stephentoub PTAL

**Comment by pgavlin** [comment]
LGTM.

**Comment by davidsh** [comment]
CI failure:

http://dotnet-ci.cloudapp.net/job/dotnet_corefx_prtest/6206/

System.Net.Sockets.Tests.UdpClientTest.BeginSend_AsyncOperationCompletes_Success
MESSAGE:
System.Net.Sockets.SocketException : An address incompatible with the requested protocol was used
+++++++++++++++++++
STACK TRACE:
at System.Net.Sockets.Socket.DoBeginSendTo(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, EndPoint endPointSnapshot, SocketAddress socketAddress, OverlappedAsyncResult asyncResult) in d:\j\workspace\dotnet_corefx_windows_debug_prtest\src\System.Net.Sockets\src\System\Net\Sockets\Socket.cs:line 2955 at System.Net.Sockets.Socket.BeginSendTo(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, EndPoint remoteEP, AsyncCallback callback, Object state) in d:\j\workspace\dotnet_corefx_windows_debug_prtest\src\System.Net.Sockets\src\System\Net\Sockets\Socket.cs:line 2900 at System.Net.Sockets.UdpClient.BeginSend(Byte[] datagram, Int32 bytes, IPEndPoint endPoint, AsyncCallback requestCallback, Object state) in d:\j\workspace\dotnet_corefx_windows_debug_prtest\src\System.Net.Sockets\src\System\Net\Sockets\UDPClient.cs:line 297 at System.Net.Sockets.UdpClient.<SendAsync>b__4(Byte[] targetDatagram, Int32 targetBytes, IPEndPoint targetEndpoint, AsyncCallback callback, Object state) in d:\j\workspace\dotnet_corefx_windows_debug_prtest\src\System.Net.Sockets\src\System\Net\Sockets\UDPClient.cs:line 618 at System.Threading.Tasks.TaskFactory`1.FromAsyncImpl[TArg1,TArg2,TArg3](Func`6 beginMethod, Func`2 endFunction, Action`1 endAction, TArg1 arg1, TArg2 arg2, TArg3 arg3, Object state, TaskCreationOptions creationOptions) at System.Threading.Tasks.TaskFactory`1.FromAsync[TArg1,TArg2,TArg3](Func`6 beginMethod, Func`2 endMethod, TArg1 arg1, TArg2 arg2, TArg3 arg3, Object state) at System.Net.Sockets.UdpClient.SendAsync(Byte[] datagram, Int32 bytes, IPEndPoint endPoint) in d:\j\workspace\dotnet_corefx_windows_debug_prtest\src\System.Net.Sockets\src\System\Net\Sockets\UDPClient.cs:line 617 at System.Net.Sockets.UdpClientAPMExtensions.BeginSend(UdpClient client, Byte[] datagram, Int32 bytes, IPEndPoint endPoint, AsyncCallback requestCallback, Object state) in d:\j\workspace\dotnet_corefx_windows_debug_prtest\src\Common\src\System\Net\Sockets\SocketAPMExtensions.cs:line 1184 at System.Net.Sockets.Tests.UdpClientTest.BeginSend_AsyncOperationCompletes_Success() in d:\j\workspace\dotnet_corefx_windows_debug_prtest\src\System.Net.Sockets.Legacy\tests\FunctionalTests\UdpClientTest.cs:line 51

**Comment by stephentoub** [comment]
@dotnet-bot test this please

**Comment by stephentoub** [comment]
LGTM

**Comment by CIPop** [comment]
> CI failure
Tracked by #4363

Thanks @stephentoub for opening the tracking issue!

**Pull request merged**
