### PR TITLE
Avoid creating CurlChannelBinding.ToString() description until needed

### PR DESCRIPTION
**Pull request by stephentoub**
Today CurlChannelBinding creates the result of ToString when the token is set into it.  Getting the description of the binding is rare compared to setting a token into the binding, so just create the string when it's requested. Also a bit of miscellaneous cleanup in related code.

cc: @bartonjs, @ericeil, @davidsh, @kapilash

### CODE REVIEW

**Comment by bartonjs** [comment]
The misc cleanup (particularly properties to expression bodied statements) seems superfluous, and better suited to a standalone commit by CodeFormatter/etc; but the change is small enough that it isn't really worth complaining about more than one run-on sentence :).

LGTM

**Comment by bartonjs** [comment]
I can't figure out why my comments restarted the CI tests on this.  I said none of the words of the phrase, much less having them together...

**Comment by stephentoub** [comment]
> I can't figure out why my comments restarted the CI tests on this. I said none of the words of the phrase, much less having them together...

Jenkins was down this morning when I submitted this.  He's since come back up, and it wasn't until you commented then that he noticed this existed :)

**Comment by davidsh** [comment]
LGTM

**Pull request merged**
