### PR TITLE
Add test cases for UnmanagedMemoryStream.CopyTo/CopyToAsync

### PR DESCRIPTION
**Pull request by stephentoub**
Replaces #1721. Thanks, @vecode.

### CODE REVIEW

**Comment by jasonwilliams200OK** [comment]
:+1:
Perhaps I am stating the obvious here: you can amend this commit by making changes and yet the attribution of original committer will retain.

```powershell
# in powershell with git in PATH
# at corefx root
# with ums_copytests branch
# notepad src/System.IO.UnmanagedMemoryStream/tests/UmsTests.cs 
# make changes, save and close
git commit --amend
# close the notepad
git push -f
```

**Comment by stephentoub** [comment]
@jasonwilliams200OK, did I do it incorrectly?  The commit shows as coming @vecode, right?  I did make changes to it, but left the attribution the same.

**Comment by jasonwilliams200OK** [comment]
@stephentoub yes it is perfectly fine :smiley:
I saw the CI build it failing so it may require further code changes (perhaps CI build failure is unrelated?).

**Comment by stephentoub** [comment]
Thanks.  It failed due to #1972.

**Comment by stephentoub** [comment]
@dotnet-bot test this please

**Comment by stephentoub** [comment]
@dotnet-bot test this please

**Comment by jasonwilliams200OK** [comment]
@stephentoub, just wanted to chime in a bit more (something I found recently), we can also change the author of the commit exec'ing `git commit --amend` during interactive rebase `git rebase -i ...` as described in this answer: http://stackoverflow.com/a/8434756. This could be useful if someone text you some code (bad example probably? rest assured I won't be texting you any code :stuck_out_tongue_winking_eye:) and you like to give the acknowledgement. The end result in the repo history would be the same (it will show the original author as the other person and you as a committer (/ *delegatee*?)).

**Pull request merged**
