### PR TITLE
Fix signing problem in Linux with System.Globalization.Test

### PR DESCRIPTION
**Pull request by tarekgh**

### CODE REVIEW

**Comment by stephentoub** [comment]
LGTM

**Comment by joperezr** [comment]
LGTM. and I've verified that this fixes the outerloop full build.

**Comment by joperezr** [comment]
fixes: #7383

**Comment by weshaggard** [comment]
@joperezr Have we followed up on the ability to sign on x-plat?

@tarekgh while minor we should have conditioned this on OSGroup=Windows_NT

**Comment by tarekgh** [comment]
@weshaggard we are going to remove it anyway soon after fixing the signing.

**Comment by joperezr** [comment]
> Have we followed up on the ability to sign on x-plat?

Looks like they marked our issue as a feature request about a month ago, but I'm not sure if they are planning on fixing it soon, looks like milestone is still marked as Unknown. I'll ping the issue to see what are the plans on fixing it.

**Pull request merged**
