### PR TITLE
Fix race condition in AsyncOperation setting of completion flag

### LINKED ISSUE #1937: AsyncOperationTests.ThrowAfterAsyncComplete failed in Linux CI
http://dotnet-ci.cloudapp.net/job/dotnet_corefx_linux_debug_tst_prtest/622/console
```
System.ComponentModel.EventBasedAsync.Tests.AsyncOperationTests.ThrowAfterAsyncComplete [FAIL]
19:59:56       Assert.Throws() Failure
19:59:56       Expected: typeof(System.InvalidOperationException)
19:59:56       Actual:   (No exception was thrown)
19:59:56       Stack Trace:
19:59:56             at System.ComponentModel.EventBasedAsync.Tests.AsyncOperationTests.<ThrowAfterAsyncComplete>b__4()
19:59:56             at System.Threading.Tasks.Task.Execute()
19:59:56          --- End of stack trace from previous location where exception was thrown ---
19:59:56             at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
19:59:56             at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
19:59:56             at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
19:59:56             at System.ComponentModel.EventBasedAsync.Tests.AsyncOperationTests.ThrowAfterAsyncComplete()
19:59:56 Finished:    System.ComponentModel.EventBasedAsync.Tests
```

### PR DESCRIPTION
**Pull request by stephentoub**
The AsyncOperation type in System.ComponentModel.EventBasedAsync tracks whether it's already been completed, and any subsequent attempts to Post operations through a completed instance are supposed to result in exceptions.  However, the implementation currently doesn't set its completion flag until after it's invoked the completion callback.  This means that if the completion callback then itself attempts to reuse the instance or if it initiates another async operation that does, there's a race condition between the subsequent access to the instance and the setting of the flag. This change fixes up the ordering so that the flag is set prior to invoking the completion callback rather than after.

Fixes #1937.

### CODE REVIEW

**Comment by stephentoub** [comment]
cc: @YingP99

**Comment by stephentoub** [comment]
@ellismg, could you review?  This is the same issue you addressed internally in another branch.

**Comment by ellismg** [comment]
LGTM.

**Comment by stephentoub** [comment]
Thanks.

**Pull request merged**
