### PR TITLE
Mark several tests with [SkipOnTargetFramework(TargetFrameworkMonikers.Mono)]

### PR DESCRIPTION
**Pull request by EgorBo**
We use corefx's sources and tests but since mono also uses reference sources (desktop .NET) it can not use [SkipOnMono(NetFramework)] or [SkipOnMono(NetCoreApp)] that is why we introduced [TargetFrameworkMonikers.Mono](https://github.com/dotnet/buildtools/pull/1690)

### CODE REVIEW

**Comment by akoeplinger** [comment]
I understand the changes where Mono is added in addition to `TargetFrameworkMonikers.NetFramework` but not the others. Are they to work around bugs in Mono?

**Comment by EgorBo** [comment]
@akoeplinger 
two CanBeFinalized tests rely on GC.Collect that won't work this way on mono (we discussed that a while ago 🙂 )
SqlErrorCollectionTest.cs - those two are not relevant anymore - removing from the PR now, thanks for noticing
SynchronizationContextTests one of those throws a NotImplementedException the other one is a bug in mono - ignored while is not fixed.

**Comment by akoeplinger** [comment]
@EgorBo ok, that's what I thought but wanted to confirm :) Please add a comment for the CanBeFinalized that this is expected/by design. For the other ones it'd be good to add links to the bugzilla entries.

**Comment by marek-safar** [comment]
@EgorBo Please add a comment about the mono bug to the sources

@danmosemsft @karelz @terrajobst This is a good example of testbed challenges

- CanBeFinalized relies on specific GC behaviour (probably not netstandard required)
- CurrentCultureTest_SkipOnDesktopFramework netcore specific extension (probably not netstandard required)
- SetMinMaxThreadsTest_ChangedInDotNetCore who decides this is netstandard required or not?

**Comment by stephentoub** [comment]
> CanBeFinalized relies on specific GC behaviour (probably not netstandard required)

What about mono's GC makes this test not work?  I'd prefer to see the test fixed to work with the various GCs, as presumably even the CLR and CoreCLR's GC could change in the future and break this.

> CurrentCultureTest_SkipOnDesktopFramework netcore specific extension (probably not netstandard required)

@danmosemsft, @kouvel, why does core behave differently here?  .NET Core is throwing an exception where desktop isn't... why is that ok?

**Comment by EgorBo** [comment]
@stephentoub the GC.Collect is not a deterministic operation on mono so all CanBeFinalized tests fail for us (they can be fixed with some hacks like Thread.Sleep or wrapping this call https://github.com/EgorBo/corefx/blob/df589e0ee6f52cbe33661760101925e991212678/src/System.Data.Common/tests/System/Data/Common/DbCommandTests.cs#L160 with 
```
Thread thr = new Thread(() => FinalizingCommand.CreateAndRelease());
thr.Start();
thr.Join();
```
Not sure what is the best approach to apply here - @marek-safar

**Comment by stephentoub** [comment]
> the GC.Collect is not a deterministic operation on mono

GC.Collect on Mono doesn't actually force a collection to be initiated?

**Comment by kouvel** [comment]
> CurrentCultureTest_SkipOnDesktopFramework

> why does core behave differently here?

These properties are a bit confusing. They are non-static but their values are for the current thread, not for the thread instance. To avoid accidental accesses to the culture of the current thread instead of the instance on which the properties are accessed, it was decided at the time these properties were exposed to make these properties accessible only from the same thread as the instance.

**Comment by stephentoub** [comment]
> To avoid accidental accesses to the culture of the current thread instead of the instance on which the properties are accessed, it was decided at the time these properties were exposed to make these properties accessible only from the same thread as the instance.

@danmosemsft, @tarekgh, you guys on board with this break?  I thought we were on a path of backing away from such "we don't like the behavior so we're changing it" changes, but maybe we decided differently on this one?  Or maybe things have changed since this was decided?

**Comment by tarekgh** [comment]
@stephentoub I was not aware of this difference and even not involved in it. I am not seeing this is documented either https://docs.microsoft.com/en-us/dotnet/api/system.threading.thread.currentculture?view=netframework-4.7.1#System_Threading_Thread_CurrentCulture

**Comment by kouvel** [comment]
That change was documented in the ApiCompat list here: https://github.com/dotnet/corefx/wiki/ApiCompat#thread. Not sure if those notes get folded into the docs. IIRC @jkotas and I had discussed this change in behavior to the Thread.CurrentCulture / CurrentUICulture properties to throw when accessed from a different thread. It would be easy to change if that's what is desired.

**Comment by jkotas** [comment]
> I thought we were on a path of backing away from such "we don't like the behavior so we're changing it" changes

We are not changing the behavior from one correct behavior to a different correct behavior. We are not supporting the behavior - it is in the same category as not supporting `Thread.Abort` or all other more subtle cases that throw PlatformNotSupported exception.

CurrentCulture is a thread local. If you allow for external threads to change or observe your thread locals, things get tricky. There is a pretty complex code in desktop to make it work in backward compatible ways and it costs some perf too. It was never in CoreCLR (since Silverligh days - it was originally removed for security reasons). Unless we hear from real customers that this is a problem, I do not see a reason to change it. I do not think that it would be easy to actually replicate the desktop behavior with all its quirks.

**Comment by stephentoub** [comment]
> I do not think that it would be easy to actually replicate the desktop behavior with all its quirks.

I thought @kouvel was saying that the instance Thread.CurrentCulture property simply returned the calling thread's culture (i.e. it shouldn't have been an instance member).  If that's true, then it would not seem difficult to replicate, and I could certainly imagine someone have taken a dependency on it.  If that's not true, and it would really be a difficult feat to emulate the desktop behavior, then throwing makes sense.

**Comment by tarekgh** [comment]
@kouvel 

> That change was documented in the ApiCompat list here: https://github.com/dotnet/corefx/wiki/ApiCompat#thread. Not sure if those notes get folded into the docs. 

It will not hurt to open a doc issue in the docs repo to track this.

**Comment by kouvel** [comment]
Filed https://github.com/dotnet/docs/issues/3640

It looks like the desktop behavior by default is different from what I thought. If I understand correctly, a thread can set only its own culture, but it can read the culture of any other thread, along with other tweaks to support some compat switches.

**Comment by jkotas** [comment]
> thread can set only its own culture

In desktop, thread can set other threads culture. Run this on desktop:

```C#
using System;
using System.Threading;
using System.Globalization;

class My {

static void Work() {
   for (;;)
      Console.WriteLine(Thread.CurrentThread.CurrentCulture);
}

static void Main() {
    Thread t = new Thread(Work);
    t.Start();
    for (;;) {
        t.CurrentCulture = new CultureInfo("en-US");
        t.CurrentCulture = new CultureInfo("cz-cz");
    }
}

}
```

When you look into details, you will find that it is broken in number of different ways. For example, the current culture is cached on the unmanaged side of the runtime - when you set the culture for other thread, the unmanaged side is update for your current thread and the two will get out of sync.

**Comment by tarekgh** [comment]
it would be good in general if the docs mark these APIs as obsolete and recommend to use the CultureInfo.CurrentCulture

**Comment by jkotas** [comment]
Also filled https://github.com/dotnet/platform-compat/issues/64 to flag these in the platform-compat tooling.

**Comment by kouvel** [comment]
@jkotas I see how that works now, thanks

**Comment by stephentoub** [comment]
We can revisit individual tests subsequently, but no point in holding up this PR.

**Pull request merged**
