### PR TITLE
[release/3.1] Fix netstandard problem with new ACL changes

### PR DESCRIPTION
**Pull request by carlossanlop**
Fixes: https://github.com/dotnet/corefx/issues/42483
Fixes: https://github.com/dotnet/coreclr/pull/27742

The build passed in all configurations.
I addressed this by following @ericstj 's suggestions in the commit shared in the issue he opened.

Related change for 5.0: https://github.com/dotnet/corefx/pull/42546

### CODE REVIEW

**Comment by jkotas** [comment]
Could you please make this in master first and then back port it?

**Comment by carlossanlop** [comment]
@jkotas this one was the urgent change.
I could submit a 5.0 PR and have them both up for review at the same time. Would that be an acceptable option?

**Comment by ericstj** [comment]
I believe a lot of the UAP tests are failing when run under app-container.  Can you reproduce these locally?

**Comment by carlossanlop** [comment]
> _I believe a lot of the UAP tests are failing when run under app-container. Can you reproduce these locally?_

@ericstj I'm getting a strange failure, but I am not sure if it's the same problem as in the CI ([example](https://helix.dot.net/api/2019-06-17/jobs/da240581-9c4f-417e-a1ae-82a1075baabe/workitems/System.Xml.Linq.Axes.Tests/console)):

1. I built using `build.cmd -framework uap`, which succeeded.

2. Then I ran the unit tests, and this is the output:

```
PS D:\corefx> dotnet.exe msbuild /t:rebuildandtest D:\corefx\src\System.IO.FileSystem.AccessControl\tests\System.IO.FileSystem.AccessControl.Tests.csproj /p:TargetGroup=uap

Microsoft (R) Build Engine version 16.3.0+0f4c62fea for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.

  CoreFx.Private.TestUtilities -> D:\corefx\artifacts\bin\CoreFx.Private.TestUtilities\uap-Debug\CoreFx.Private.TestUtilities.dll
  System.IO.FileSystem.AccessControl.Tests -> D:\corefx\artifacts\bin\System.IO.FileSystem.AccessControl.Tests\uap-Windows_NT-Debug\System.IO.FileSystem.Access                          Control.Tests.dll
  ----- start 2019-11-11 12:38:17.04 ===============  To repro directly: =====================================================
  pushd D:\corefx\artifacts\bin\System.IO.FileSystem.AccessControl.Tests\uap-Windows_NT-Debug\
  for /F %f in ('dir /b /s "D:\corefx\artifacts\bin\testhost\uap-Windows_NT-Debug-x64\Runner\"|find /i /v ".pri"') do @(set relPath=%f& set relPath=D:\corefx\a                          rtifacts\bin\testhost\uap-Windows_NT-Debug-x64\Runner\=relPathrelPathrelPathrelPath %f 1>NUL))
  for /R "D:\corefx\artifacts\bin\testhost\uap-Windows_NT-Debug-x64\UAPLayout\" %I in (*) do @if not exist "%~nxI" (mklink /H "%~nxI" "%I" 1>NUL)
  copy /y "D:\corefx\artifacts\bin\testhost\uap-Windows_NT-Debug-x64\UAPLayout\System.Private.CoreLib.dll" System.Private.CoreLib.ni.dll
  call "D:\corefx\artifacts\bin\testhost\uap-Windows_NT-Debug-x64\Launcher\WindowsStoreAppLauncher.exe" -install appxmanifest.xml System.IO.FileSystem.AccessControl.Tests.dll
  XUnitRunnerUap System.IO.FileSystem.AccessControl.Tests.dll -xml "C:\Users\calope\AppData\Local\Packages\5cd54353-3ed7-4a6e-a72f-db349f28867c_v52bfwc2c21ha\LocalState\System.IO.FileSystem.AccessControl.Tests.xml" -nologo -notrait category=nonuaptests -notrait category=nonwindowstests -notrait category=OuterLoop -notrait category=failing
  set ERRORLEVEL=0
  move /Y "C:\Users\calope\AppData\Local\Packages\5cd54353-3ed7-4a6e-a72f-db349f28867c_v52bfwc2c21ha\LocalState\System.IO.FileSystem.AccessControl.Tests.xml" .\testResults.xml
  call "D:\corefx\artifacts\bin\testhost\uap-Windows_NT-Debug-x64\Launcher\WindowsStoreAppLauncher.exe" -uninstall appxmanifest.xml System.IO.FileSystem.AccessControl.Tests.dll
  popd
  ===========================================================================================================
          1 file(s) copied.
  Got manifest file appxmanifest.xml
  Removing any previous installation...
  Installing the application...
  Package Full Name is 5cd54353-3ed7-4a6e-a72f-db349f28867c_1.0.0.0_x64__v52bfwc2c21ha

  SUCCESS
  ExitCode 100
  Unhandled exception. System.IO.FileLoadException: Could not load file or assembly 'System.Linq, Version=4.2.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The located assembly's manifest definition does not match the assembly reference. (0x80131040)
  File name: 'System.Linq, Version=4.2.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
     at Xunit.ConsoleClient.Program.Main(String[] args)


  The system cannot find the file specified.
  Got manifest file appxmanifest.xml
  Removing the application...

  SUCCESS
  ExitCode 100
  ----- end 2019-11-11 12:38:22.73 ----- exit code -532462766 ----------------------------------------------------------
C:\Users\calope\.nuget\packages\microsoft.dotnet.corefxtesting\1.0.0-beta.19474.3\build\core\Core.targets(153,5): warning MSB3073: The command ""D:\corefx\artifacts\bin\System.IO.FileSystem.AccessControl.Tests\uap-Windows_NT-Debug\RunTests.cmd" --runtime-path "D:\corefx\artifacts\bin\testhost\uap-Windows_NT-Debug-x64"" exited with code -532462766. [D:\corefx\src\System.IO.FileSystem.AccessControl\tests\System.IO.FileSystem.AccessControl.Tests.csproj]
C:\Users\calope\.nuget\packages\microsoft.dotnet.corefxtesting\1.0.0-beta.19474.3\build\core\Core.targets(164,5): error : One or more tests failed while running tests from 'System.IO.FileSystem.AccessControl.Tests'. [D:\corefx\src\System.IO.FileSystem.AccessControl\tests\System.IO.FileSystem.AccessControl.Tests.csproj]
PS D:\corefx>
```

**Comment by ericstj** [comment]
That's close, something in your process is preventing you from running UAP locally.

```
System.IO.FileLoadException: Could not load file or assembly 'System.Linq, Version=4.2.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The located assembly's manifest definition does not match the assembly reference. (0x80131040)
```

This indicates the System.Linq being loaded is lower than 4.2.1.0.  You might want to check the system.linq dll here:
D:\corefx\artifacts\bin\testhost\uap-Windows_NT-Debug-x64
D:\corefx\artifacts\bin\System.IO.FileSystem.AccessControl.Tests\uap-Windows_NT-Debug\

Just a guess.

**Comment by ericstj** [comment]
For me I'm able to repro.  Checkout out your branch, removed artifacts, `build -framework uap` from root, then `dotnet msbuild /t:rebuildandtest /p:targetgroup=uap` from `src\System.IO.FileSystem.AccessControl\tests`.

I see the following errors:
https://gist.github.com/ericstj/c1bc585478c08385ce4ad74beb770a52

**Comment by Pilchie** [comment]
Approved for 3.1 GA, pending CI completion.

**Pull request merged**
