### PR TITLE
Fix System.IO.Pipelines reference assembly

### PR DESCRIPTION
**Pull request by ahsonkhan**
cc @pakrym, @davidfowl, @joperezr, @weshaggard 

~The ref csproj doesn't need System.Buffers.~

And if I reference System.Memory as a ProjectReference, I get the following errors, when I run `msbuild` after navigating to `corefx\src\System.IO.Pipelines`:
```text
...
System.IO.Pipelines.cs(86,107): error CS1069: The type name 'ReadOnlyMemory<>' could not be found in the namespace 'System'. This type has been forwarded to assembly 'System.Runtime, Version=4.2.1.0, Culture=neutral, PublicKeyToken=b0
3f5f7f11d50a3a' Consider adding a reference to that assembly. [D:\GitHub\Fork\corefx\src\System.IO.Pipelines\ref\System.IO.Pipelines.csproj]
  System.IO.Pipelines.cs(76,48): error CS0012: The type 'Memory<>' is defined in an assembly that is not referenced. You must add a reference to assembly 'System.Runtime, Version=4.2.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
'. [D:\GitHub\Fork\corefx\src\System.IO.Pipelines\ref\System.IO.Pipelines.csproj]
  System.IO.Pipelines.cs(76,48): error CS0012: The type 'Span<>' is defined in an assembly that is not referenced. You must add a reference to assembly 'System.Runtime, Version=4.2.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.
 [D:\GitHub\Fork\corefx\src\System.IO.Pipelines\ref\System.IO.Pipelines.csproj]
  CSC : error CS0012: The type 'CLSCompliantAttribute' is defined in an assembly that is not referenced. You must add a reference to assembly 'System.Runtime, Version=4.2.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. [D:\GitHu
b\Fork\corefx\src\System.IO.Pipelines\ref\System.IO.Pipelines.csproj]
  System.IO.Pipelines.cs(91,65): error CS3001: Argument type 'ReadOnlySequence<byte>' is not CLS-compliant [D:\GitHub\Fork\corefx\src\System.IO.Pipelines\ref\System.IO.Pipelines.csproj]
  System.IO.Pipelines.cs(48,60): error CS3001: Argument type 'MemoryPool<byte>' is not CLS-compliant [D:\GitHub\Fork\corefx\src\System.IO.Pipelines\ref\System.IO.Pipelines.csproj]
  System.IO.Pipelines.cs(60,64): error CS3001: Argument type 'SequencePosition' is not CLS-compliant [D:\GitHub\Fork\corefx\src\System.IO.Pipelines\ref\System.IO.Pipelines.csproj]
  System.IO.Pipelines.cs(61,64): error CS3001: Argument type 'SequencePosition' is not CLS-compliant [D:\GitHub\Fork\corefx\src\System.IO.Pipelines\ref\System.IO.Pipelines.csproj]
  System.IO.Pipelines.cs(61,98): error CS3001: Argument type 'SequencePosition' is not CLS-compliant [D:\GitHub\Fork\corefx\src\System.IO.Pipelines\ref\System.IO.Pipelines.csproj]
...
```

Also, only include reference to System.Threading.Tasks when necessary in src csproj.

### CODE REVIEW

**Comment by ahsonkhan** [comment]
```text
20:37:43 System.IO.Pipelines.cs(48,35): error CS0234: The type or namespace name 'Buffers' does not exist in the namespace 'System' (are you missing an assembly reference?) [/mnt/j/workspace/dotnet_corefx/master/linux-TGroup_netcoreapp+CGroup_Release+AGroup_x64+TestOuter_false_prtest/src/System.IO.Pipelines/ref/System.IO.Pipelines.csproj]
```

Looks like Buffers is needed (on Linux).

**Comment by davidfowl** [comment]
How can a reference only be needed on linux?

**Comment by pakrym** [comment]
Doesn't look like it's only linux, all builds are red.

**Comment by ahsonkhan** [comment]
> How can a reference only be needed on linux?

> Doesn't look like it's only linux, all builds are red.

No clue. I ran locally (on windows) and the build was passing.
Hmm... I think if I use Reference (instead of project reference) the build order matters. And in some cases (or in CI at least), Pipelines gets built first (before Memory) which causes the errors.

**Comment by benaadams** [comment]
```
warning MSB3245: Could not resolve this reference.
 Could not locate the assembly "System.Memory".
 Check to make sure the assembly exists on disk.
 If this reference is required by your code, you may get compilation errors. 
 [D:\j\workspace\windows-TGrou---74aa877a\src\System.IO.Pipelines\ref\System.IO.Pipelines.csproj]
The type or namespace name 'SequencePosition' does not exist in the namespace 'System' (are you missing an assembly reference?) [D:\j\workspace\windows-TGrou---74aa877a\src\System.IO.Pipelines\ref\System.IO.Pipelines.csproj]
The type or namespace name 'SequencePosition' does not exist in the namespace 'System' (are you missing an assembly reference?) [D:\j\workspace\windows-TGrou---74aa877a\src\System.IO.Pipelines\ref\System.IO.Pipelines.csproj]
The type or namespace name 'SequencePosition' does not exist in the namespace 'System' (are you missing an assembly reference?) [D:\j\workspace\windows-TGrou---74aa877a\src\System.IO.Pipelines\ref\System.IO.Pipelines.csproj]
The type or namespace name 'Buffers' does not exist in the namespace 'System' (are you missing an assembly reference?) [D:\j\workspace\windows-TGrou---74aa877a\src\System.IO.Pipelines\ref\System.IO.Pipelines.csproj]
The type or namespace name 'Buffers' does not exist in the namespace 'System' (are you missing an assembly reference?) [D:\j\workspace\windows-TGrou---74aa877a\src\System.IO.Pipelines\ref\System.IO.Pipelines.csproj]
The type or namespace name 'Buffers' does not exist in the namespace 'System' (are you missing an assembly reference?) [D:\j\workspace\windows-TGrou---74aa877a\src\System.IO.Pipelines\ref\System.IO.Pipelines.csproj]
The type or namespace name 'Memory<>' does not exist in the namespace 'System' (are you missing an assembly reference?) [D:\j\workspace\windows-TGrou---74aa877a\src\System.IO.Pipelines\ref\System.IO.Pipelines.csproj]
The type or namespace name 'Span<>' does not exist in the namespace 'System' (are you missing an assembly reference?) [D:\j\workspace\windows-TGrou---74aa877a\src\System.IO.Pipelines\ref\System.IO.Pipelines.csproj]
 The type or namespace name 'ReadOnlyMemory<>' does not exist in the namespace 'System' (are you missing an assembly reference?) [D:\j\workspace\windows-TGrou---74aa877a\src\System.IO.Pipelines\ref\System.IO.Pipelines.csproj]
The type or namespace name 'Buffers' does not exist in the namespace 'System' (are you missing an assembly reference?) [D:\j\workspace\windows-TGrou---74aa877a\src\System.IO.Pipelines\ref\System.IO.Pipelines.csproj]
The type or namespace name 'Buffers' does not exist in the namespace 'System' (are you missing an assembly reference?) [D:\j\workspace\windows-TGrou---74aa877a\src\System.IO.Pipelines\ref\System.IO.Pipelines.csproj]
```

**Comment by ahsonkhan** [comment]
Yes, now I remember. If you use project reference, the build order (based on dependencies) is maintained. If you use Reference, then you have to ensure (somehow) that System.Memory gets built before System.IO.Pipelines, or you will see the above errors.

I will look into this some more.

**Comment by davidfowl** [comment]
@ahsonkhan what were you fixing in the first place? When did this break?

**Comment by ahsonkhan** [comment]
> what were you fixing in the first place? When did this break?

I just noticed that the arguments in the ref didn't match the recent changes so wanted to fix it. Then I noticed the CLS errors, if you try to build at the root of the Pipelines directory. I don't think this affects CI/etc, so it was likely like this from the beginning.

If you run msbuild from the ref/src/test directory, it builds fine (and build.cmd at root of corefx repo also works fine).

**Comment by benaadams** [comment]
Issue in packaging checker? (not confirming the matches)

Would be issue if someone explicitly referred to params? `minimumLength: 25`

**Comment by benaadams** [comment]
@dotnet-bot test OSX x64 Debug Build

**Comment by ahsonkhan** [comment]
We still see the CLS-compliant errors (wasn't able to figure out how to fix those since I reverted the csproj change), but I think this change is good to merge.

Any feedback?

**Comment by benaadams** [comment]
OSX is a bust (unrelated)
UWP have logged the 3 (unrelated) issues https://github.com/dotnet/corefx/issues/27590 https://github.com/dotnet/corefx/issues/27653 https://github.com/dotnet/corefx/issues/27655

**Pull request merged**
