### PR TITLE
Fix use of nameof with ArgumentException

### LINKED ISSUE #6251: ArgumentExceptions constructed with wrong message / name
A quick search of the codebase shows more than 20 call sites where an ArgumentException is constructed with the pattern:
```C#
throw new ArgumentException(nameof(
```
Each of these is almost certainly a bug, as the first argument to ArgumentException's ctor is unfortunately not the parameter name but rather the message... the second argument is the parameter name.

### PR DESCRIPTION
**Pull request by stephentoub**
Simply a squashed version of the already reviewed https://github.com/dotnet/corefx/pull/6270.
Replaces https://github.com/dotnet/corefx/pull/6270.
Fixes #6251

### CODE REVIEW

**Comment by KrzysztofCwalina** [comment]
This changes a couple of exception types. Is that a compatible change?

**Comment by stephentoub** [comment]
> Is that a compatible change?

Don't we usually say it's acceptable to go to a more derived type?

**Comment by KrzysztofCwalina** [comment]
Sorry, I was not clear. I wanted to ask if this is compatible with .NET Framework, i.e. can users write portable code catching the more derived exceptions?

**Comment by stephentoub** [comment]
> can users write portable code catching the more derived exceptions?

They can write portable code catching ArgumentException, exactly as they do today.  Sure, if they write new code to catch the more derived exception, then that code would not work as desired on the full framework.  If we say that throwing a more derived exception isn't portable because then people might catch the more derived exception and end up missing it on the full framework, then aren't we also effectively saying we can never throw more derived types (a change that's been allowed in the past)?

I can't tell... are you asking a real question or are you making a statement that you think we shouldn't allow such changes?

cc: @terrajobst, @weshaggard

**Comment by KrzysztofCwalina** [comment]
I think we want to be able to describe exceptions propagating out of an API as part of the contract of the API. In fact, I still really want to attribute all our ref assemblies in stdlib with information about the exceptions they throw. The exceptions need to be the common denominator between all implementations.
I was thinking that .NET Core would be the "reference" implementation; throwing exactly what the contract say. 
Given that, I am not sure it makes sense to throw more derived exceptions from .NET Core implementations.

**Comment by stephentoub** [comment]
Are exceptions different from return types in this regard, and if so, why?  All over the place we return more derived types than what the return type statically says, and we're certainly not going to change those.  What makes exceptions different in this regard?  I completely get the desire to specify a common denominator exception as part of the contract / docs... but I don't understand why the exception thrown can't be more derived than that.

**Comment by stephentoub** [comment]
(Also, it's not always going to be possible to throw exactly what the contract says, e.g. places where internal exception types derive from public ones, like https://github.com/dotnet/corefx/blob/ac67ffac987d0c27236c4a6cf1255c2bcbc7fe7d/src/System.IO.Compression/src/System/IO/Compression/ZLibException.cs#L14)

**Comment by KrzysztofCwalina** [comment]
1. I don't see a reason to throw more derived exceptions for usage errors. These exceptions will/should never be caught/handled.
2. There is value in .NET Core being the "reference implementation" of our contracts.
3. When the implementation and the contract diverge (even in substitutable way), it just adds to the cost of keeping them in sync.
4. Just because we have some divergence already, does not mean we want to have more.
5. The divergence that we do already have (returning more derived types), at least has value. Throwing more derived exceptions for usage errors has little value IMO.
6. When we return more derived types, the users still see the less derived in the method signature and docs. In case of exceptions, we tend to document what the implementation throws as there is nothing in the signature.

**Comment by stephentoub** [comment]
> These exceptions will/should never be caught/handled

Then what does it matter if they're more derived?

> There is value in .NET Core being the "reference implementation" of our contracts.

Sure.  I don't understand why that's relevant.  If by "reference implementation" you mean the thing that others look to as the gold standard for how it should be implemented, great, then they'll see that the exception really should have been an ArgumentNullException to begin with.

> Throwing more derived exceptions for usage errors has little value IMO.

And little cost.  As the code currently stands, it's a bug: the argument name is being used as the message.  To fix that bug, we have two options: 1) throw the proper more derived type, or 2) add a custom message to the .resx, ensure it's properly localized, and use that message when constructing the exception.  (2) has cost as well, and IMHO is the worse of the two solutions.

> When we return more derived types, the users still see the less derived in the method signature and docs. In case of exceptions, we tend to document what the implementation throws as there is nothing in the signature.

We control the documentation.  And in these cases, these are already documented as throwing ArgumentException, and I don't expect anyone will proactively change that.

**Comment by stephentoub** [comment]
I'd be interested in @terrajobst, @weshaggard, and @nguerrera's opinions here.

If the consensus is we should revert back to the base type in these few cases and add new messages to the .resx, fine, I'll do so.  But to me that seems like a step backwards.

**Comment by KrzysztofCwalina** [comment]
>> These exceptions will/should never be caught/handled

>Then what does it matter if they're more derived?

Because people will, even though they should not.

>> There is value in .NET Core being the "reference implementation" of our contracts.

>Sure.  I don't understand why that's relevant.  If by "reference implementation" you mean the thing 
that others look to as the gold standard for how it should be implemented, great, then they'll see that the exception really should have been an ArgumentNullException to begin with.

Yeah, I mean gold standard. But the gold standard cannot be incompatible with the contract. And so if ArgumentNullException is incompatible, then we would have to pay the cost of changing other implementations, and I don't think it's worth it for usage errors.

>> Throwing more derived exceptions for usage errors has little value IMO.

>And little cost.  As the code currently stands, it's a bug: the argument name is being used as the message.  To fix that bug, we have two options: 1) throw the proper more derived type, or 2) add a custom message to the .resx, ensure it's properly localized, and use that message when constructing the exception.  (2) has cost as well, and IMHO is the worse of the two solutions.

If we don't have to change the other implementation (net fx) then it would have small cost.

>> When we return more derived types, the users still see the less derived in the method signature and docs. In case of exceptions, we tend to document what the implementation throws as there is nothing in the signature.

> We control the documentation.  And in these cases, these are already documented as throwing ArgumentException, and I don't expect anyone will proactively change that.

I was answering your questions why exceptions are different than return types.

**Comment by stephentoub** [comment]
> And so if ArgumentNullException is incompatible

I don't see how it's incompatible.

We're going around in circles here I think.

**Comment by KrzysztofCwalina** [comment]
I am not sure why we are going in circles. You said/implied that some of the changes are not compatible, see:
"> can users write portable code catching the more derived exceptions?
They can write portable code catching ArgumentException, exactly as they do today.  Sure, if they write new code to catch the more derived exception, then that code would not work as desired on the full framework."

**Comment by stephentoub** [comment]
That's no different than for return types:
```
Foo f = SomeMethod();
if (f.GetType() == typeof(DerivedFoo))
{
    ... // do stuff if SomeMethod actually returned a DerivedFoo
}
```

**Comment by KrzysztofCwalina** [comment]
We are going in circles:

> When we return more derived types, the users still see the less derived in the method signature and docs. In case of exceptions, we tend to document what the implementation throws as there is nothing in the signature.
> 
> We control the documentation. And in these cases, these are already documented as throwing ArgumentException, and I don't expect anyone will proactively change that.
> 
> I was answering your questions why exceptions are different than return types._

**Comment by stephentoub** [comment]
> I was answering your questions why exceptions are different than return types._

And I was responding to your answer about why I disagree and don't believe that difference is valid.

**Comment by KrzysztofCwalina** [comment]
Which response are you referring to? The one where you say you believe they are compatible?

Or is it the one saying that we already have docs for some of these?

If the later, then a) docs is one but signature/implementation is the other. b) I think it might be a good topic to discuss at the API review. We should establish guidance spelling out the relationship between the contracts and implementations for exceptions, and then design .net core following the guidance.

**Comment by stephentoub** [comment]
> I think it might be a good topic to discuss at the API review

That's fine.  In the meantime, so as to not block the rest of the changes, I will revert the relevant changes, leaving bugs in the code to be dealt with later. :frowning:

There is no joy in Mudville.

**Comment by nguerrera** [comment]
I'm surprised this is controversial at all.

1. Throwing a more derived exception type has long been explicitly called out as something we do not consider breaking.

2.  We are held back enough from simply correcting incorrect code in .NET Core. We shouldn't add more burden to that unnecessarily.

Art  most, I would slap an exception cref doc comment for base type and and a code comment at the throw site indicating that other platforms throw base. 

Maintaining extra localized resources just for this would be silly.

2c

**Comment by stephentoub** [comment]
> 2c

Here here.

**Comment by KrzysztofCwalina** [comment]
Had to look up Mudville :-) http://dictionary.reference.com/browse/there-is-no-joy-in-mudville

@nguerrera, you need to read the whole thread. I know changing to more derived type is compatible for given API. This is a question about portability, not compatibility.

**Comment by stephentoub** [comment]
> Had to look up Mudville

:smile:

**Comment by nguerrera** [comment]
@KrzysztofCwalina I assure you I have read it.

With respect to portability, let me make two assertions that reflect my understanding:

1. All existing code written prior to this change that catches ArgumentException (with the pathological exception of a `if (ex.GetType() == typeof(ArgumentException)`) remains portable.

2. New code written after this change that catches ArgumentNullException (and must only have been tested on .NET Core) would not be portable.

I don't care about (2) at all. It will impact nobody.

As far as .NET Core being reference implementation / gold standard, it is sufficient to me if there is a comment in the code that reflects the portable contract and the reality on other platforms. The actual implementation should be the best possible within the already stringent portability and compatibility constraints. We should not worsen the .NET Core implementation where documentation would suffice.

**Comment by nguerrera** [comment]
Also keep in mind that there are almost certainly existing discrepancies like this as a consequence of

1. A deliberate policy that it was OK: https://github.com/dotnet/corefx/blob/master/Documentation/coding-guidelines/breaking-change-rules.md#exceptions

2. Code flow to .NET Core from a mix of.other platforms that weren't 100% consistent on this.

As such, reversing our stance in (1) implies scrubbing the whole repo for it, which would be costly.

**Comment by stephentoub** [comment]
This just felt so wrong, but here you go:
https://github.com/stephentoub/corefx/commit/1667fb568f05cb02eace29243b1d1b166d67d566

**Comment by terrajobst** [comment]
My opinion is:

1. The most important compat bar is .NET Framework X to .NET Framework X + 1. We need to worry about changing code in .NET Core that might get ported to .NET Framework that would break that.
2. Throwing a more derived exception type is a compatible change.
3. Argument exceptions shouldn't be caught.

I think the changes I saw in @stephentoub's PR seem to be in alignment with (1) and (2). While I agree with @KrzysztofCwalina that we need to make it easy for folks to write portable code, I see no point in optimizing for a scenario that folks shouldn't do anyways, i.e. code shouldn't worry whether something throws `ArgumentException` or `ArgumentNullException`.

I'm supportive of merging the PR without https://github.com/stephentoub/corefx/commit/1667fb568f05cb02eace29243b1d1b166d67d566.

**Pull request merged**
