### PR TITLE
Port to release/1.0.0: Avoid using tmp subdirectories in Pipes and MMF on Unix

### PR DESCRIPTION
**Pull request by stephentoub**
Port https://github.com/dotnet/corefx/pull/8800 to release/1.0.0
cc: @ellismg

### CODE REVIEW

**Comment by stephentoub** [comment]
Test Innerloop Windows_NT Debug Build and Test please (timed out restoring packages)
Test Innerloop Windows_NT Release Build and Test please (timed out restoring packages)
Test Innerloop OSX Debug Build and Test please (Jenkins failure)

@mmitche, that OSX leg passed all tests and then failed with this exception:
http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/release_1.0.0/job/osx_debug_prtest/13/consoleText
```
ERROR: Step ‘Publish xUnit test result report’ aborted due to exception: 
java.lang.InterruptedException
	at java.lang.Object.wait(Native Method)
	at hudson.remoting.Request.call(Request.java:147)
	at hudson.remoting.Channel.call(Channel.java:780)
	at hudson.FilePath.act(FilePath.java:979)
	at hudson.FilePath.act(FilePath.java:968)
	at org.jenkinsci.plugins.xunit.XUnitProcessor.performTests(XUnitProcessor.java:145)
	at org.jenkinsci.plugins.xunit.XUnitProcessor.performXUnit(XUnitProcessor.java:88)
	at org.jenkinsci.plugins.xunit.XUnitPublisher.perform(XUnitPublisher.java:142)
	at org.jenkinsci.plugins.xunit.XUnitPublisher.perform(XUnitPublisher.java:134)
	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:782)
	at hudson.model.AbstractBuild$AbstractBuildExecution.performAllBuildSteps(AbstractBuild.java:723)
	at hudson.model.Build$BuildExecution.post2(Build.java:185)
	at hudson.model.AbstractBuild$AbstractBuildExecution.post(AbstractBuild.java:668)
	at hudson.model.Run.execute(Run.java:1763)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:98)
	at hudson.model.Executor.run(Executor.java:410)
```

**Comment by mmitche** [comment]
@stephentoub That was right around when I rebooted it this morning

**Comment by ianhays** [comment]
:+1:

**Comment by mmitche** [comment]
@dotnet-bot test Innerloop CentOS7.1 Release Build and Test

**Comment by mmitche** [comment]
@dotnet-bot test Innerloop CentOS7.1 Debug Build and Test

**Pull request merged**
