### PR TITLE
Fix deadlock when ending process watching on Unix

### PR DESCRIPTION
**Pull request by stephentoub**
Move a RegisteredWaitHandle.Unregister out of a lock.

cc: @mellinoe

### CODE REVIEW

**Comment by ellismg** [comment]
Why did this deadlock before?

**Comment by stephentoub** [comment]
I'm still trying to figure that out and come up with an isolated repro.  It's only deadlocking on Unix, and its doing so in part due to a wait that's happening inside of RegisteredWaitHandle.Unregister, which makes me believe there's something happening related to the synchronization implementation of wait handles in libcoreclr.  I wouldn't be surprised if it's related to https://github.com/dotnet/corefx/pull/4269.

**Comment by ellismg** [comment]
Gotcha.

**Comment by mellinoe** [comment]
LGTM. This fixed the deadlock I was hitting in the ping tests when subscribed to Process.Exited and reading from Process.HasExited.

**Comment by stephentoub** [comment]
Thanks, guys.

**Pull request merged**
