### PR TITLE
Add internal platform-agnostic case sensitivity detection

### PR DESCRIPTION
**Pull request by stephentoub**
After the recent refactoring based on introducing native shims, the only reason there are special builds of System.IO.FileSystem and System.IO.FileSystem.DriveInfo for each of Linux and OS X is because of PathInternal.CaseSensitive/CaseInsensitive.cs, which just provides a hard-coded value as to whether the target platform is case-sensitive or case-insensitive-but-preserving.  Similarly, these files are the only things forcing System.IO.Compression.ZipFile to not be completely platform-agnostic and to have separate Windows/Unix builds.

This commit recombines those assemblies by adding a platform-agnostic helper that simply creates a temporary file with upper-case letters and then checks whether that file can be found via the lower-cased version.  This isn't perfect, in that it's possible to mount multiple file systems each with different case sensitivities, but a) it's better than the hardcoded version we currently have, and b) I don't know of any better portable solution.

(Issue #3156 tracks adding an API to provide information on case sensitivity.  This change can be replaced by using such an API if/when it's available.)

cc: @ericstj, @nguerrera, @sokket, @chcosta

### CODE REVIEW

**Comment by nguerrera** [comment]
LGTM. Love how this cleans things up. 

cc @JeremyKuhne who was thinking about the longer term solution for this for a PathsAreEquivalent proposal IIRC.

**Comment by sokket** [comment]
This cleans things up nicely! :) LGTM 2

**Comment by stephentoub** [comment]
Thanks, guys.

**Comment by JeremyKuhne** [comment]
It looks like we'll need a PathStartsWith as well as PathsAreEquivalent.

**Comment by ericstj** [comment]
LGTM

**Pull request merged**
