### PR TITLE
Upgrade CoreFX to buildtools 106

### PR DESCRIPTION
**Pull request by ianhays**
Consumes some changes to perf testing from https://github.com/dotnet/buildtools/pull/308

@stephentoub @mellinoe

### CODE REVIEW

**Comment by stephentoub** [comment]
It looks like buildtools is already at 107... should we be going to that?  Though it's not clear if there are any actual changes between 106 and 107.

**Comment by stephentoub** [comment]
Assuming we do want 106, LGTM

**Comment by mellinoe** [comment]
It doesn't look like there's any changes between 106 and 107. The official build must have gotten kicked off twice for some reason. LGTM.

**Comment by jasonwilliams200OK** [comment]
Looks like the version is already bumped to 00107 via 0931c34. :smile:

**Comment by ianhays** [comment]
Works for me, thanks @jasonwilliams200OK :)

I need to push another buildtools fix, so expect another of these PRs in a little while.

**Pull request closed without merging**
