### PR TITLE
Add some tests for PersianCalendar

### PR DESCRIPTION
**Pull request by hughbe**

### CODE REVIEW

**Comment by hughbe** [comment]
Test Innerloop Windows_NT Release Build and Test
Test Innerloop Windows_NT Debug Build and Test

**Comment by hughbe** [comment]
I think a bug is causing the Windows tests to fail - they pass on my machine though for some reason - @tarekgh let me know what you think

**Comment by tarekgh** [comment]
@hughbe the calculation of the ToFourDigitYear depends on the TwoDigitYearMax which we read from the OS. PersianCalendar was not defined before Windows 10. so I think we use the default value at that time. so basically the behavior can change on different Windows versions

**Comment by tarekgh** [comment]
Maybe you can explicitly set the TwoDigitYearMax to the calendar before testing the ToFourDigitYear

**Comment by hughbe** [comment]
@tarekgh good to know, thanks - another insight into the inconsistent world of internationalization!

**Comment by tarekgh** [comment]
Now Windows tests passed :-)

**Comment by tarekgh** [comment]
LGTM

**Comment by hughbe** [comment]
Test Innerloop OSX Debug Build and Test

**Comment by stephentoub** [comment]
LGTM

**Pull request merged**
