### PR TITLE
Add new non english CI

### PR DESCRIPTION
**Pull request by Anipik**
Fixes https://github.com/dotnet/corefx/issues/28729

### CODE REVIEW

**Comment by Anipik** [comment]
@dotnet-bot test ci please

**Comment by Anipik** [comment]
@dotnet-bot test ci please

**Comment by Anipik** [comment]
@dotnet-bot test ci please

**Comment by Anipik** [comment]
@dotnet-bot test ci please

**Comment by Anipik** [comment]
@dotnet-bot test ci please

**Comment by Anipik** [comment]
@dotnet-bot test ci please

**Comment by Anipik** [comment]
@dotnet-bot test ci please

**Comment by Anipik** [comment]
@dotnet-bot test ci please

**Comment by Anipik** [comment]
@dotnet-bot test ci please

**Comment by danmosemsft** [comment]
@safern is the expert here and will review this.

BTW when this is clean, we should make it enabled by default; and if that works ok, we can remove the en-US version of this OS from CI.

**Comment by joshfree** [comment]
> The changes for this should go in pipelines.groovy 

See https://github.com/dotnet/dotnet-ci/blob/master/docs/CI-PIPELINES.md#the-new-world-of-pipelines

also /cc @mmitche

**Pull request closed without merging**
