### PR TITLE
Compilation types through attribute: Lambda Tests

### PR DESCRIPTION
**Pull request by JonHanna**
Also change verification of exceptions to test specific inputs having specific exceptions, rather than try-and-repeat: Less exceptions thrown and caught, better-defined tests.

### CODE REVIEW

**Comment by JonHanna** [comment]
Test Innerloop CentOS7.1 Release Build and Test
(SSL test at http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/centos7.1_release_tst_prtest/3161/consoleFull network fluke or issue?)

**Comment by JonHanna** [comment]
Test Innerloop CentOS7.1 Release Build and Test
(Timeout)

**Comment by JonHanna** [comment]
Test Innerloop CentOS7.1 Debug Build and Test
(Timeout).

**Comment by JonHanna** [comment]
Test Innerloop CentOS7.1 Debug Build and Test
Test Innerloop CentOS7.1 Release Build and Test 

(never started)

**Comment by JonHanna** [comment]
Test Innerloop CentOS7.1 Debug Build and Test
Test Innerloop CentOS7.1 Release Build and Test

**Comment by stephentoub** [comment]
Nit: I can't comment on the diff, but you've added code like this:
```C#
            ResultType outcome;
            int? expected = null;
            if (a.HasValue && b == 0)
                outcome = ResultType.DivideByZero;
            else if (a == int.MinValue && b == -1)
                outcome = ResultType.Overflow;
            else
            {
                expected = a / b;
                outcome = ResultType.Success;
            }
```
Can you use braces for all of the if/elseif/else blocks here?

**Comment by stephentoub** [comment]
LGTM.

When addressing nits, can you do so in a separate commit?  GitHub let's us squash when merging now, so we can have the best of both worlds: be able to review just the additional changes in additional commits, while still only having a single resulting commit.

**Comment by JonHanna** [comment]
Oh, that is a nice piece of functionality. Github just gets better and better.

**Comment by JonHanna** [comment]
This this, please.

**Comment by stephentoub** [comment]
LGTM. Thanks.

**Pull request merged**
