### PR TITLE
Merge branch dev/api into master

### PR DESCRIPTION
**Pull request by joperezr**
cc: @stephentoub @weshaggard @danmosemsft @ericstj 

Merging branch dev/api into master.

Changes I had to do after resolving merge conflicts in order for this to build is: 	ed83470 so that would be the one to review.

### CODE REVIEW

**Comment by ericstj** [comment]
LGTM once green

**Comment by ericstj** [comment]
Looks like you're going to need a mop-up merge since I see folks are still merging into dev/API since you started this.

**Comment by joperezr** [comment]
> Looks like you're going to need a mop-up merge since I see folks are still merging into dev/API since you started this.

Yeah, I planned to do this anyway since there were already a bunch of PRs opened against dev/api. I'll probably do it next week once all of them are merged.

**Comment by joperezr** [comment]
@dotnet-bot test ci please

**Comment by joperezr** [comment]
Non-Windows CI builds are expected to fail since dev/api updated the netci.groovy file to remove the TestWithLocalLibraries attribute. I will generate the new definitions, and trigger a build for each OS and add a comment here with the results along with a link to the build jobs.

**Comment by joperezr** [comment]
Updated Definition Build Status: ( Checked box means build finished succesfully)

- [ ] [OSX build](http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/master/job/GenPRTest/job/osx_debug_prtest/1/)
- [ ] [Ubuntu build](http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/master/job/GenPRTest/job/ubuntu14.04_debug_prtest/1/)
- [ ] CentOS build (triggered, not started yet)
- [ ] Linux ARM Emulator build (triggered, not started yet)

**Comment by joperezr** [comment]
All [self-triggered non-Windows builds](https://github.com/dotnet/corefx/pull/11679#issuecomment-246861565) have finished successfully so I'll merge this in now. Thanks for the review @ericstj and @weshaggard

**Pull request merged**
