### PR TITLE
SocketsHttpHandler: remove Content-Length header if Transfer-Encoding: chunked is present

### PR DESCRIPTION
**Pull request by geoffkizer**
This matches behavior of other handlers.  We've been getting away with not doing this because #27245 would cause Content-Length to not appear in the enumeration in normal cases.

Contributes to #27245 

@stephentoub @davidsh

### CODE REVIEW

**Comment by geoffkizer** [comment]
@dotnet-bot test outerloop Linux x64 debug
@dotnet-bot test outerloop Windows x64 debug
@dotnet-bot test outerloop OSX x64 debug

**Comment by stephentoub** [comment]
@dotnet-bot test Windows x64 Debug Build please
@dotnet-bot test Linux x64 Release Build please
@dotnet-bot test OSX x64 Debug Build please

**Comment by geoffkizer** [comment]
Were there outerloop failures?

**Comment by stephentoub** [comment]
> Were there outerloop failures?

They didn't run; your request was missing "Build" at the end of the description :)

**Comment by stephentoub** [comment]
> They didn't run; your request was missing "Build" at the end of the description :)

Ugh, and now I forgot "Outerloop".

**Comment by stephentoub** [comment]
@dotnet-bot test Outerloop Windows x64 Debug Build please
@dotnet-bot test Outerloop Linux x64 Release Build please
@dotnet-bot test Outerloop OSX x64 Debug Build please

**Comment by geoffkizer** [comment]
Ah :)

**Comment by geoffkizer** [comment]
@dotnet-bot test Outerloop Windows x64 Debug Build please

**Pull request merged**
