### PR TITLE
Re-enable source link validation

### PR DESCRIPTION
**Pull request by ViktorHofer**
fa168dd690798a683ef0d1e65d60ce5d6918d987 in arcade should have a fix to prevent OOM exceptions.

Fixes https://github.com/dotnet/corefx/issues/40195

### CODE REVIEW

**Comment by ericstj** [comment]
Thanks for picking this up @ViktorHofer.  Do we need to do an official build with this to test it or will the CI run the validation?

**Comment by ViktorHofer** [comment]
I think this is internal only: https://dnceng.visualstudio.com/internal/_build/results?buildId=320672

**Comment by ericstj** [comment]
Got it, I see the sourcelink validation phase in that build.  Assuming it passes this should be good to merge.  We can also do a tell-mode merge into release/3.0 for this assuming the Arcade update made it there too.

**Comment by ericstj** [comment]
@ViktorHofer this didn't pass.  Have a look here: https://dnceng.visualstudio.com/internal/_build/results?buildId=320672&view=logs&jobId=0a6c679f-72be-5867-422e-acb741a068a3&taskId=d2ccdc12-7474-5a79-d9be-9757fb834354&lineStart=262&lineEnd=271&colStart=2&colEnd=36
```
The variable '$Jobs' cannot be retrieved because it has not been set.
System.Management.Automation.RuntimeException: The variable '$Jobs' cannot be retrieved because it has not been set.
   at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext funcContext, Exception exception)
   at System.Management.Automation.Interpreter.ActionCallInstruction`2.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
at ValidateSourceLinkLinks, D:\a\1\s\eng\common\post-build\sourcelink-validation.ps1: line 218
at <ScriptBlock>, D:\a\1\s\eng\common\post-build\sourcelink-validation.ps1: line 250
at <ScriptBlock>, D:\a\_temp\5008bb56-7bcd-435c-b2f3-4f5778f663b8.ps1: line 2
at <ScriptBlock>, <No file>: line 1
```
/cc @JohnTortugo

**Comment by ViktorHofer** [comment]
Oh I overlooked the warning... Will work with @JohnTortugo on a fix. I don't think we need to revert the change. Will keep you updated.

**Comment by ViktorHofer** [comment]
@ericstj just wanted to let you know that source link validation now really works: https://dnceng.visualstudio.com/internal/_build/results?buildId=322071&view=logs&jobId=0a6c679f-72be-5867-422e-acb741a068a3&taskId=d2ccdc12-7474-5a79-d9be-9757fb834354&lineStart=263&lineEnd=264&colStart=1&colEnd=1

**Pull request merged**
