### PR TITLE
Linked doc for debugging tests in Visual Studio

### PR DESCRIPTION
**Pull request by WinCPP**
While searching how to debug one specific test case using Visual Studio, I ended up on section "Debugging tests in Visual Studio" in this doc, but more information was somewhere else. So proposing this change to provide a link so that developers are led to proper page that has information on advanced features.

@karelz @ahsonkhan

### CODE REVIEW

**Comment by danmosemsft** [comment]
Thanks. My only thought is - I am not sure the wiki is the way forward. I think we want to move anything useful in there into the docs. It has served it's purpose and is duplicative at this point. @karelz ?

**Comment by karelz** [comment]
Yes, we need to merge the wiki content back into main docs. We should add it on Infra backlog - @wtgodbe can you please make sure it is tracked?

**Comment by wtgodbe** [comment]
Sure, I added an item for it

**Comment by karelz** [comment]
@wtgodbe can you please link it here / above? Thanks!

**Comment by wtgodbe** [comment]
I just added a brief blurb for it under Documentation - [here](https://microsoft.sharepoint.com/teams/netfx/corefx/_layouts/15/WopiFrame.aspx?sourcedoc={0cfbc196-0645-4781-84c6-5dffabd76bee}&action=edit&wd=target%28Engineering%2FEngineering.one%7C70363cf0-e56f-4207-9066-875eb8c74ab0%2FInfrastructure%20Tasks%20%20Backlog%7C8deb38f6-ca13-43cb-ab54-74d91a86f7f7%2F%29). I can create an issue as well if we want something more descriptive

**Comment by karelz** [comment]
Let's create GH issue as well please

**Comment by wtgodbe** [comment]
https://github.com/dotnet/corefx/issues/36057

**Comment by stephentoub** [comment]
Since we don't actually want the wiki used, I'm going to close this PR that links into it.  Once the content is migrated, links into the migrated content can be added.  Thanks!

**Pull request closed without merging**
