### PR TITLE
Marking {ReadOnly}Span as readonly structs

### PR DESCRIPTION
**Pull request by ahsonkhan**
Fixes issue https://github.com/dotnet/corefx/issues/23809

Related PR for coreclr: https://github.com/dotnet/coreclr/pull/13886

cc @KrzysztofCwalina, @VSadov

### CODE REVIEW

**Comment by ahsonkhan** [comment]
IsByRefLike and IsReadOnly attributes are not part of .net standard. How can I address this issue for the netstandard1.1 and netstandard build configurations?

cc @VSadov, @KrzysztofCwalina 

image
image

**Comment by ahsonkhan** [comment]
Waiting for corefx to get the new compiler (https://github.com/dotnet/buildtools/pull/1661).

cc @joperezr

**Comment by stephentoub** [comment]
@dotnet-bot test this please

**Comment by joperezr** [comment]
FYI: PR for the new compiler in corefx is out: #24076

**Comment by stephentoub** [comment]
@dotnet-bot test this please

**Comment by stephentoub** [comment]
@dotnet-bot test UWP CoreCLR x64 Debug Build please ("Cannot create a file when that file already exists.")

**Pull request merged**
