### PR TITLE
Porting XEvent Delay BugFix from .Net Framework to 3.0

### PR DESCRIPTION
**Pull request by tarikulsabbir**
The bug description is given below-
The issues is that the XEvents are arriving as expected, but with 1 XEvent delay. It means that to receive the most recent XEvent, the app has to wait for another XEvent to be generated.
For example, when listening for XEvents that fires on every query that the clients are running:
• At startup, if the client is running for example, “select 1”, and then the client doesn't get any XEvent.
• If the client is running “select 2”, then the client receives the “select 1” event.
• If the client is running “select 3”, then the client receives “select 2” event. And so on…

It seems like the server is sending the most recent XEvent on the wire, but the client holds it inside up until the next XEvent is arrived .

This fix already exists in the .Net Framework. This PR merges this fix into .Net Core 3.0.

### CODE REVIEW

**Comment by Wraith2** [comment]
The diff, me, or both are confused. It looks like you're removing a bit of code from `TryReadByteArray` that doesn't exist in the master, and yet it's happily diffing it..,

**Comment by tarikulsabbir** [comment]
> The diff, me, or both are confused. It looks like you're removing a bit of code from `TryReadByteArray` that doesn't exist in the master, and yet it's happily diffing it..,

This is an internal fix which already got merged to master (https://github.com/dotnet/corefx/pull/36015). This PR is for 3.0.

**Comment by tarikulsabbir** [comment]
@karelz can you please confirm whether this is correct branch for 3.0 release?

**Comment by Wraith2** [comment]
> This is an internal fix which already got merged to master (#36015). This PR is for 3.0.

I've no problem with the fix, looks like an unpleasant one to debug. I just don't have the code it's referencing in my repo and I synced to make sure I wasn't behind. I'll chalk it up as me not understanding git very well.

**Comment by stephentoub** [comment]
> @karelz can you please confirm whether this is correct branch for 3.0 release?

It's confusing, but master currently is for .NET Core 3.0.  The release/3.0 branch is used for what we actually ship as part of previews, and ultimately the final 3.0 bits, and we automatically integrate everything in master into release/3.0 once a week or so.

So if the change is already in master, it'll naturally flow into release/3.0 and this PR can be closed.

**Comment by stephentoub** [comment]
I see this is just a port to release/3.0 of https://github.com/dotnet/corefx/pull/36015.  So per the above, we can close this.  Thanks.

**Comment by tarikulsabbir** [comment]
> I see this is just a port to release/3.0 of #36015. So per the above, we can close this. Thanks.

Thanks @stephentoub for closing this PR.

**Pull request closed without merging**
