### PR TITLE
Fixes race in NamespaceCache

### PR DESCRIPTION
**Pull request by MarcoRossignoli**
fixes https://github.com/dotnet/corefx/issues/36430

/cc @tmat @stephentoub

### CODE REVIEW

**Comment by stephentoub** [comment]
I'd feel more comfortable about this if `_rootNamespace` were `volatile`.

**Comment by MarcoRossignoli** [comment]
@stephentoub BTW I did another check and maybe we could remove `volatile` creating dependency between stores
```diff
_namespaceTable = namespaceTable;
-_rootNamespace = namespaceTable[rootNamespace];
+_rootNamespace = _namespaceTable[rootNamespace];
```
what do you think?

**Comment by tmat** [comment]
Wouldn't it be enough to swap these lines (+ make _namespaceTable volatile)? https://github.com/dotnet/corefx/pull/36699/files#diff-ce440dd4ccbe0de41bf088e1ef753e48R157 and https://github.com/dotnet/corefx/pull/36699/files#diff-ce440dd4ccbe0de41bf088e1ef753e48R158

**Comment by stephentoub** [comment]
> what do you think?

No, the volatile write to publish the built up state needs to be after all the other writes.

**Comment by MarcoRossignoli** [comment]
@tmat my challenge here was find a way to not use `volatile` to make code more clear

**Comment by MarcoRossignoli** [comment]
> No, the volatile write to publish the built up state needs to be after all the other writes.

@stephentoub @tmat, I have looked again at memory models ([`interesting paper`](http://www.rdrop.com/users/paulmck/scalability/paper/whymb.2010.07.23a.pdf)), my assumption was incomplete.
I reverted to initial idea(less code).

**Pull request merged**
