### PR TITLE
Add CoreCLROverridePath option to consume private coreclr in corefx

### PR DESCRIPTION
**Pull request by weshaggard**
Fixes https://github.com/dotnet/corefx/issues/16508.

PTAL @stephentoub @jkotas @danmosemsft @RussKeldorph

### CODE REVIEW

**Comment by weshaggard** [comment]
@dotnet-bot test Innerloop Windows_NT Release Build and Test please

**Comment by AndyAyersMS** [comment]
@weshaggard I can't get this to work. CoreFx builds fail and it looks like the issue is that the core library can't be found:
```
.\build.cmd -release -tests -- /p:CoreCLROverridePath=C:\repos\coreclr\bin\Product\Windo
ws_NT.x64.Release\
... lots of errors, like...
System\Uri.cs(4897,24): error CS0518: Predefined type 'System.Char' is not defined or imported [C:\repos\corefx\src\Sys
tem.Private.Uri\src\System.Private.Uri.csproj]
```

**Comment by AndyAyersMS** [comment]
@RussKeldorph were you able to get this to work?

**Comment by weshaggard** [comment]
I only did some basic local scoped testing I will try your scenario and see if it works for me. Would you mind sending along your log file so I can have a look?

**Comment by weshaggard** [comment]
@AndyAyersMS out of curiosity do you have a System.Private.CoreLib.dll in  C:\repos\coreclr\bin\Product\Windows_NT.x64.Release\?

**Comment by AndyAyersMS** [comment]
Yes, it's there. Where does the log file end up?

**Comment by AndyAyersMS** [comment]
Hmm, while scouting for the log I realized I had overwritten it with a regular build/test. Redid the run with the CoreCLR override and now it works. 

So maybe the failure I saw requires both the CoreCLR override and a clean repo?

**Comment by RussKeldorph** [comment]
@AndyAyersMS my first attempt failed with hundreds of build breaks.  I haven't had a chance to try again or investigate, but I'm working on ingesting this.

**Comment by weshaggard** [comment]
>So maybe the failure I saw requires both the CoreCLR override and a clean repo?

That is how I was testing it. Perhaps there is some incremental changes that cause issues. I will try that scenario today and see if I can understand what might be going wrong.

**Comment by RussKeldorph** [comment]
@weshaggard This doesn't work for me.  I get hundreds of build errors.

Here's what I tried:
```cmd
git clone https://github.com/dotnet/corefx
git clone https://github.com/dotnet/coreclr
pushd coreclr
call build.cmd x64 release skiptests
popd
pushd corefx
call build.cmd -Release -- /p:CoreCLROverridePath=%CD%\..\coreclr\bin\Product\Windows_NT.x64.Release
popd
```
Log: [msbuild.log.txt](https://github.com/dotnet/corefx/files/814518/msbuild.log.txt)

**Comment by weshaggard** [comment]
I think I have identified the issue and will put out a fix for it today.

**Pull request merged**
