### PR TITLE
[release/2.0.0] Update buildtools

### PR DESCRIPTION
**Pull request by ellismg**

### CODE REVIEW

**Comment by danmosemsft** [comment]
@dotnet-bot test this please

**Comment by ViktorHofer** [comment]
@dotnet-bot test this please

**Comment by weshaggard** [comment]
@ellismg did you ever figure out what is causing the compiler issues with the build tools update? I'm hitting the same thing with my PR https://github.com/dotnet/corefx/pull/22062 when updating BuildTools.

The closest thing I found is issue https://github.com/dotnet/roslyn/pull/16486 but I'm not sure if is the same root cause or not.

**Comment by ellismg** [comment]
It was related to the files have non ascii characters but not encoded in UTF-8, instead using some legacy code page stuff (it looked like).

I worked around the issue by resaving the files as UTF-8.  I also verified that I didn't see this behavior on the newest tooling (I got a different and better error message).

**Comment by weshaggard** [comment]
Did you submit a PR with those changes? Or do we need to move to an even newer BuildTools?

**Comment by ellismg** [comment]
> Did you submit a PR with those changes? Or do we need to move to an even newer BuildTools?

@weshaggard, Yes, see 182e565fa4d1e596d88b30f896ed6a67f5d76b83, which landed in master.

**Comment by weshaggard** [comment]
Closing in favor of https://github.com/dotnet/corefx/pull/22062

**Pull request closed without merging**
