### PR TITLE
Fix tests for CoreCLR 6269

### PR DESCRIPTION
**Pull request by gkhanna79**
Added tests for https://github.com/dotnet/coreclr/issues/6269

@jkotas PTAL

### CODE REVIEW

**Comment by jkotas** [comment]
LGTM

**Comment by gkhanna79** [comment]
@dotnet-bot test this please

**Comment by gkhanna79** [comment]
@stephentoub Is there a way to close/reopen the PR so that it picks up the latest CoreFX changes (that pull in CoreCLR that corresponds to this test change)?

**Comment by gkhanna79** [comment]
@dotnet-bot test this please

**Comment by stephentoub** [comment]
> Is there a way to close/reopen the PR so that it picks up the latest CoreFX changes (that pull in CoreCLR that corresponds to this test change)?

There's a chicken-and-egg problem.  With this test active in the repo, we can't update to a new CoreCLR as all of the test legs then fail.  And we can't merge this change without a new CoreCLR as all of the legs then fail.  The two valid approaches are to first disable the offending tests, then merge in the new CoreCLR, and then update/re-enable the offending tests, or to cherry-pick the test changes into the same PR that's updating CoreCLR.  I already did the latter:
https://github.com/dotnet/corefx/pull/10191#issuecomment-234089055

**Comment by gkhanna79** [comment]
Thanks @stephentoub - will keep your suggestion in mind for future. I will close this PR once the other PR merges.

**Pull request closed without merging**
