### PR TITLE
Remove periods from embedded resource names in Metadata tests

### LINKED ISSUE #7125: Several MetadataReaderTests failing with NullReferenceException on OSX
http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/outerloop_osx_debug/49/consoleFull
```
12:42:12      System.Reflection.Metadata.Tests.MetadataReaderTests.ValidateMethodImplTable [FAIL]
12:42:12         System.TypeInitializationException : The type initializer for 'System.Reflection.Metadata.Tests.Interop' threw an exception.
12:42:12         ---- System.NullReferenceException : Object reference not set to an instance of an object.
12:42:12         Stack Trace:
12:42:12               at System.Reflection.Metadata.Tests.MetadataReaderTests.ValidateMethodImplTable()
12:42:12            ----- Inner Stack Trace -----
12:42:12               at System.Reflection.Metadata.Tests.ResourceHelper.GetResource(String name)
12:42:12               at System.Reflection.Metadata.Tests.Interop..cctor()
12:42:12      System.Reflection.Metadata.Tests.MetadataReaderTests.ValidateSignature [FAIL]
12:42:12         System.TypeInitializationException : The type initializer for 'System.Reflection.Metadata.Tests.Interop' threw an exception.
12:42:12         ---- System.NullReferenceException : Object reference not set to an instance of an object.
12:42:12         Stack Trace:
12:42:12               at System.Reflection.Metadata.Tests.MetadataReaderTests.ValidateSignature()
12:42:12            ----- Inner Stack Trace -----
12:42:12               at System.Reflection.Metadata.Tests.ResourceHelper.GetResource(String name)
12:42:12               at System.Reflection.Metadata.Tests.Interop..cctor()
12:42:12      System.Reflection.Metadata.Tests.MetadataReaderTests.ValidateInterfaceImplTable [FAIL]
12:42:12         System.TypeInitializationException : The type initializer for 'System.Reflection.Metadata.Tests.Interop' threw an exception.
12:42:12         ---- System.NullReferenceException : Object reference not set to an instance of an object.
12:42:12         Stack Trace:
12:42:12               at System.Reflection.Metadata.Tests.MetadataReaderTests.ValidateInterfaceImplTable()
12:42:12            ----- Inner Stack Trace -----
12:42:12               at System.Reflection.Metadata.Tests.ResourceHelper.GetResource(String name)
12:42:12               at System.Reflection.Metadata.Tests.Interop..cctor()
12:42:12      System.Reflection.Metadata.Tests.MetadataReaderTests.ValidateFieldLayoutTable [FAIL]
12:42:12         System.TypeInitializationException : The type initializer for 'System.Reflection.Metadata.Tests.Interop' threw an exception.
12:42:12         ---- System.NullReferenceException : Object reference not set to an instance of an object.
12:42:12         Stack Trace:
12:42:12               at System.Reflection.Metadata.Tests.MetadataReaderTests.ValidateFieldLayoutTable()
12:42:12            ----- Inner Stack Trace -----
12:42:12               at System.Reflection.Metadata.Tests.ResourceHelper.GetResource(String name)
12:42:12               at System.Reflection.Metadata.Tests.Interop..cctor()
12:42:12      System.Reflection.Metadata.Tests.MetadataReaderTests.ValidateCustomAttribute [FAIL]
12:42:12         System.TypeInitializationException : The type initializer for 'System.Reflection.Metadata.Tests.Interop' threw an exception.
12:42:12         ---- System.NullReferenceException : Object reference not set to an instance of an object.
12:42:12         Stack Trace:
12:42:12               at System.Reflection.Metadata.Tests.MetadataReaderTests.ValidateCustomAttribute()
12:42:12            ----- Inner Stack Trace -----
12:42:12               at System.Reflection.Metadata.Tests.ResourceHelper.GetResource(String name)
12:42:12               at System.Reflection.Metadata.Tests.Interop..cctor()
12:42:12      System.Reflection.Metadata.Tests.MetadataReaderTests.ValidateFieldMarshal [FAIL]
12:42:12         System.TypeInitializationException : The type initializer for 'System.Reflection.Metadata.Tests.Interop' threw an exception.
12:42:12         ---- System.NullReferenceException : Object reference not set to an instance of an object.
12:42:12         Stack Trace:
12:42:12               at System.Reflection.Metadata.Tests.MetadataReaderTests.ValidateFieldMarshal()
12:42:12            ----- Inner Stack Trace -----
12:42:12               at System.Reflection.Metadata.Tests.ResourceHelper.GetResource(String name)
12:42:12               at System.Reflection.Metadata.Tests.Interop..cctor()
12:42:12      System.Reflection.Metadata.Tests.MetadataReaderTests.ValidateClassLayoutTable [FAIL]
12:42:12         System.TypeInitializationException : The type initializer for 'System.Reflection.Metadata.Tests.Interop' threw an exception.
12:42:12         ---- System.NullReferenceException : Object reference not set to an instance of an object.
12:42:12         Stack Trace:
12:42:12               at System.Reflection.Metadata.Tests.MetadataReaderTests.ValidateClassLayoutTable()
12:42:12            ----- Inner Stack Trace -----
12:42:12               at System.Reflection.Metadata.Tests.ResourceHelper.GetResource(String name)
12:42:12               at System.Reflection.Metadata.Tests.Interop..cctor()
12:42:12   Finished:    System.Reflection.Metadata.Tests
12:42:12   
12:42:12   === TEST EXECUTION SUMMARY ===
12:42:12      System.Reflection.Metadata.Tests  Total: 153, Errors: 0, Failed: 7, Skipped: 0, Time: 0.512s
```

### PR DESCRIPTION
**Pull request by mellinoe**
This removes the periods from embedded resource names in the System.Reflection.Metadata tests. Due to an x-plat MSBuild issue, these resources are omitted from the assembly outside of Windows, unless the periods are removed from their names. (See https://github.com/Microsoft/msbuild/issues/541).

Resolves #7125 
@tmat, @stephentoub

### CODE REVIEW

**Comment by mellinoe** [comment]
@dotnet-bot Test Innerloop OSX Debug Build and Test

**Comment by tmat** [comment]
Could you add a comment to the source that warns to not use dots in resource file names and links the msbuild? Also, could you file a bug to revert this change once msbuild issue is fixed?

**Comment by mellinoe** [comment]
Added a comment, and filed https://github.com/dotnet/corefx/issues/7192.

**Comment by mellinoe** [comment]
@dotnet-bot  Test Innerloop OSX Debug Build and Test
Test Innerloop OSX Release Build and Test

**Comment by stephentoub** [comment]
LGTM

**Pull request merged**
