### PR TITLE
Fixed overflows in System.Span<T>

### LINKED ISSUE #16298: Span: System.Memory is missing `unchecked` annotations
It is causing different behaviors between debug and release builds.

Repro: Run this against netfx debug build of System.Memory:

```c#
static void Main() {
    var span = new Span<int>(new int[1]);
    Console.WriteLine(span[-5]);
}
```

Actual result: System.OverflowException
Expected result: System.IndexOutOfRangeException

### PR DESCRIPTION
**Pull request by dennisdietrich**
Several overflows in System.Span<T> that were missed when turning
on overflow checks for Debug.

Fix #16298

### CODE REVIEW

**Comment by ahsonkhan** [comment]
Can you explain why unchecked is necessary here? How does it prevent the exception System.OverflowException and instead we get the right exception?

**Comment by dennisdietrich** [comment]
If you look at the changes you'll notice a common pattern. Instead of say
```csharp
if (start < 0 || start > length) // both are int
    throw new ArgumentOutOfRangeException();
```
we do
```csharp
if ((uint)start > (uint)length)
    throw new ArgumentOutOfRangeException();
```
which saves one comparison but of course the first cast has to be performed unchecked to account for start being less than zero.

**Comment by morganbr** [comment]
Is there any chance of this code supporting >2gb arrays in the future? If so, the uint cast would not be sufficient.

**Comment by dennisdietrich** [comment]
@morganbr That's a fair question but I would argue regardless of the answer it is out of scope for this PR. I haven't looked at the code in detail but my impression is that probably more than a few casts will have to change if this is supposed to support large arrays at a later point.

**Comment by danmosemsft** [comment]
@dennisdietrich @stephentoub hijacking @morganbr 's point for a general question about the `unchecked` work -- I was chatting to @tarekgh offline about this: what we're doing here is great in that it can't create any bugs that we didn't have already -- and of course it will catch any new ones we might create.

However, I don't believe the reviewers have necessarily been examining each place we add `unchecked` to satisfy ourselves that none of them are (prexisting) bugs that we might want to address subsequently. Should we have an issue to make such a pass? I suspect there's cases where unchecked should not be necessary at all.

**Comment by KrzysztofCwalina** [comment]
@morganbr, we talked about this at Design Review, and decided against supporting more than 2GB spans. @terrajobst, would you happen to have the rationale handy?

**Comment by dennisdietrich** [comment]
@danmosemsft Can't hurt but I think it'd be a low priority task. With very few exceptions I added unchecked only where it broke the existing unit test (and the exceptions were cases where I noticed a pattern within the vicinity of the original failure). That said, all the unchecked calculations should facilitated correct behavior of the classes under test. A possible outcome of reviewing them all could be changing some of the code to not rely on unchecked calculations but this - again, given the passing unit tests - would be mostly a matter of coding style, not of correctness. Just my 2 cents. :)

**Comment by danmosemsft** [comment]
I'm trying to thinking when overflow is definitely OK. Looking through your changes I see stuff like counters eg collection versions that are expected to wrap, making hashes, random numbers, negating something that's essentially got the same range both sides of zero, such are clearly fine. Also cases where we're dealing with ints that we are assuming are always positive and don't want to change to uint for some reason, or longs that we know should always fit in an int.

For stuff like offsets, it's often not clear to me. Eg random example `int minIndex = unchecked(_minIndexInclusive + count);`. The `unchecked` means that there's a codepath in the tests that wraps the int, right? Does the code anticipate that? I think in most cases I would not.

It's also interesting to me how many the unit tests are finding -- I assume this means there's a lot of "int.max" in the tests and suchlike. Although there's cases where asymmetry implies missing test coverage eg random example
```
                    case LowercaseSet:
                        chMinT = (char)lc._data;
                        chMaxT = (char)lc._data;
                        break;
                    case LowercaseAdd:
                        unchecked
                        {
                            chMinT += (char)lc._data;
                            chMaxT += (char)lc._data;
                        }
                        break;
```


Am I thinking about this in the right way?

**Comment by jkotas** [comment]
> supporting >2gb arrays in the future?

Arrays are set in stone to have 2gb indices. The storage can be more than 2gb, but the index - what is checked here - can only be Int32.MaxInt.

**Comment by jkotas** [comment]
> It's also interesting to me how many the unit tests are finding

@tarekgh @danmosemsft We should be looking at whether this effort is finding any actual *bugs*. Did we find any actual bug so far?

If we are spending energy on something that is not improving the product, we should be rather spending that energy on something else.

You have brought up the example of collection version. All ~100 places `_version++` in different collection classes need to unchecked. 3 of them have it now. So based on this sample, we have added only about 3% of the unchecked annotations that would be needed so far. It gives you idea about the bug tail required to make these annotations correct.

I have mentioned in https://github.com/dotnet/corefx/issues/3140#issuecomment-277540659 that the turning on overflow checks in debug builds was considered for .NET Framework in the past (remember those MQ milestones?), but it was not done because it did not have possible ROI.

**Comment by stephentoub** [comment]
+1 to Jan's comments, which I've also echoed in the past. Additionally, while I certainly appreciate the significant effort that's gone into this, IMO it leaves the code base in an inconsistent state, in that there are now some things marked as checked, some marked as unchecked, probably many not marked that should be, and many not marked that don't need to be, and I can't really infer anything about any of them because they're incomplete and largely unverified.

**Comment by tarekgh** [comment]
> @tarekgh @danmosemsft We should be looking at whether this effort is finding any actual bugs. Did we find any actual bug so far?

Most of the time when adding unchecked to places is considered a potential issue. the question here is how aggressive we should go and fix such places. This will need more effort to stop at every single place and investigate the calling scenario and judging the situation and balance if it is ok to be incompatible with the full framework.
This effort caught a real JIT issue and also it will help for the new code so we'll be conscious about overflow /underflow when writing a new code too.

**Comment by karelz** [comment]
> @tarekgh This effort caught a real JIT issue

Can you link it please?
I worry about what @jkotas and @stephentoub said above - if we're getting code base into inconsistent state and doing it properly is years of work, I don't think we should do it. Even if it catches a few bugs.
Or at least we should not check in such changes.

**Comment by stephentoub** [comment]
> Can you link it please?

https://github.com/dotnet/coreclr/issues/9591

**Comment by dennisdietrich** [comment]
@karelz Let me play devil's advocate and ask: What consistency? If you grep 7a88efd (the last commit before I started working on this) for ```unchecked``` you'll find hundreds of them. Would you want to remove them to achieve consistency?
If we continue this effort it could take years until every calculation that needs to is marked as ```unchecked```. But good code doesn't simply produce the right results. It should capture intent was much as possible without compromising on performance goals. Which means the next step IMHO would be to officially mandate using ```unchecked``` in the coding guidelines rather than just letting people walk into overflow exceptions.
These are my last 2 cents on the topic (don't have any change left).

**Comment by stephentoub** [comment]
> What consistency?

From my perspective there are really only three constructions here you expect in code:
1. A calculation may overflow and that's fine.
2. A calculation can never overflow, by construction.
3. A calculation should never overflow and if it does we should throw for it.

For production we compile such that, by default, every calculation is in the first bucket, and you have to opt-in to bucket 3 via the `checked` keyword, in large part because there's a performance impact to doing otherwise.  But spread across the codebase (as you point out, even prior to recent changes) we have `unchecked` usage, which indicates the default of (1) that you would otherwise already be in.

So if I then look at two calculations in code in the repo, one that uses `unchecked` and one that doesn't, what do I know about the one that doesn't?  It could be bucket 1 and simply hasn't been annotated; it could be bucket 2.  And it could even be bucket 3. That's the inconsistency: since every calculation is not explicitly called out as unchecked, checked, or neither, I don't know whether the code should have been unchecked and is benefiting from the default we apply everywhere, whether the use of unchecked was actually unnecessary because it was bucket (2), or whether the use of unchecked is there because we may have compiled the code changing the default to `checked`.

Our approach here of using the tests to guide this, IMHO, contributes to this.  We only convert things from unannotated to annotated when a test happens to hit them.  But we only have 50% code coverage of the whole repo, so by definition there's no way for us to even know about annotations that might be required in half of the repo's src.  And for the half that is covered, just being covered doesn't really indicate much, because many things that would need to be unchecked in a checked-by-default world would only trigger an exception after something rolls over, e.g. after adding 2B items to a list, which our unit tests typically don't do.  We're unlikely to address these gaps completely in the foreseeable future, which then further contributes to the inconsistency I mentioned.

Again, please don't interpret my comments as being at all negative about the work you've done.  I do appreciate the contributions.  I just personally don't see a lot of value in spending time on checked/unchecked in the codebase, and when I do then see unchecked in the codebase (or the lack of it), I don't know how to interpret that.

**Comment by karelz** [comment]
We also chatted with @danmosemsft and @tarekgh earlier about the topic:

The key benefit of this effort is to find real bugs in code and fix them (e.g. the JIT bug https://github.com/dotnet/coreclr/issues/9591 or @stephentoub's category [3] - overflows where we should throw due to security/correctness issues).
Bonus: Prevent new real bugs to be introduced in future.

We have few options regarding marking checked/unchecked:

1. All arithmetic code in CoreFX is marked as checked or unchecked.
    - Cons: Years of work across the repo.
2. Only some arithmetic code in CoreFX is marked as checked or unchecked.
3. No arithmetic code in CoreFX is marked as checked or unchecked.
    - Pros: No work needed
    - Cons: Does not help with the key benefit of the effort.

**2a.** The marking is driven by test runs - all repo-wide debug builds are checked by default
  - Cons:
    - Due to limited CoreFX test coverage, marking is inconsistent in the scope of method, class, source file and/or library.
    - Adding new tests may require also code change due to hitting new not-yet-marked code paths.
  - Pros: New code will automatically get flagged for overflows on debug builds (if we have test coverage).

**2b.** The marking is complete per library - specific libraries debug builds are checked
  - Pros: New code in the library will automatically get flagged for overflows on debug builds (if we have test coverage).
  - Cons: No enforcement to ensure that all new arithmetic code in the library is marked as checked or unchecked. It will lead to inconsistency eventually, or require even more work.

**2c.** The marking is driven by semantics of the code - no debug builds are checked
  - The places which are unchecked by design - e.g. Hash function (@stephentoub's category [1])
  - Cons: Does not help with the key benefit of the effort.

We agreed that options [1] and [2a] are not right for CoreFX (seems to be in line with @stephentoub and @jkotas, CoreFX key architects).
Option [2b] could be an option - it's the experiment that @jkotas mentioned earlier. We had mixed feelings about it, slightly leaning towards rejection. **Question:** @stephentoub @jkotas do you believe it is something worth trying out?

Options [3] and [2c] are the most attractive. Sadly they don't help with the key benefit of the effort - **finding real bugs**, however we can leverage the effort done so far to help discover real bugs. Here's how it could go:
* Revert the changes made so far (ASAP to prevent merge conflicts with changes in the meantime).
* Review the PRs done so far to identify **real bugs** (file them and fix them) and optionally add unchecked on by-design overflowing code ([2c] option above).

Thoughts?

**Comment by danmosemsft** [comment]
Orthogonally, there could be value in adding `unchecked` where my intent is that overflow is legitimate. For example if I write a hash combining function. Even if the compiler flag is never flipped, doing so operates much like `/* may overflow */` and demonstrates my intent.  The PR's here demonstrate how many places that might be -- say, 50% of them we can clearly say that overflow was intended. @stephentoub / @jkotas do you believe the value of that convention would outweigh the clutter?

**Comment by morganbr** [comment]
We do periodically see security issues due to overflows, so there is important value in eliminating them. The most frequent overflow security problems happen in relation to pointer arithmetic. Would it be useful to focus efforts in/near unsafe code? (That's why this PR caught my eye).

Of course, we could also turn overflow checks on in retail builds, but I imagine @jkotas and others would be concerned about the resulting performance. I do like @danmosemsft 's suggestion that ``unchecked`` means that somebody is allowing overflows on purpose -- I strongly suspect most code is not intended to work correctly in the event of an overflow. 

@karelz , I'd certainly be supportive of making sure we didn't just put an ``unchecked`` block around a real bug. @dennisdietrich , can you please tell us more about the considerations you put into adding unchecked blocks?

**Comment by jkotas** [comment]
There are number of places where explicit `checked` is used because of it is required for correctness. Similarly, there was number of places with explicit unchecked before recent effort started because of whoever was writing the code wanted to express the intent, or because of it was left-over from old experiments with the overflow checks.

I have done cursory review of the changes made recently. I have not found any places where they were hiding a bug. I do not have a strong opinion whether to roll them back, or keep them. However, I would switch back the change to enable the overflow checks globally by default, and I would stop actively investing into perfecting these annotations accross the repo.

It is fine if the overflow checks are enabled by default for individual libraries where the maintainers of these libraries see the value in in, given the library risk profile. In fact, it is how the suggestion started originally because of it is what maintainers of System.Reflection.Metadata chosen to do.

**Comment by danmosemsft** [comment]
My small preference is to rollback the annotations except where it's obvious they are expected to overflow harmlessly. But I am also fine with rolling them back entirely though.

(It's a shame that all this work has gone into annotations, but when we went ahead with the plan, I assumed it would be only a handful cases, and those would be ones where it was obviously correct to overflow, perhaps finding a couple of bugs. Mea culpa.). 

Nobody is in favor of random overflows where the programmer did not intend them and it's also fairly clear that those exist. I could certainly see adding `unchecked` on a library by library basis in future, iff there was a group committed to get the library totally clean, which would include a bunch of test work and code analysis. A good choice a library that has a lot of unsafe code and/or has more security exposure.

That's my 2c. @stephentoub ?

**Comment by stephentoub** [comment]
> My small preference is to rollback the annotations except where it's obvious they are expected to overflow harmlessly.

I'm unclear on this suggestion... my understanding is that every one of the annotations added was added because it actually caused an overflow.  And we're currently not aware of any of them actually being bugs.  So is the suggestion not to rollback any?  Or to audit all of them (https://github.com/dotnet/corefx/pull/15690#issuecomment-276751547)?

**Comment by danmosemsft** [comment]
We're not aware of any actually being bugs because we haven't analyzed the code carefully (as far as I know). So a number of the `unchecked` placed around adding an offset to an index (such as the Linq and Regex examples in my comment above) are not obviously correct to me without spending some time reading the code. There are many that are obviously correct though, such as [this](https://github.com/dotnet/corefx/blob/master/src/Common/src/System/Numerics/Hashing/HashHelpers.cs#L13. ) and a number of others.

**Comment by stephentoub** [comment]
> We're not aware of any actually being bugs because we haven't analyzed the code carefully (as far as I know).

From Jan above: "I have done cursory review of the changes made recently. I have not found any places where they were hiding a bug."

**Comment by danmosemsft** [comment]
OK, the consensus seems to be to pull the annotations, or at least almost all. @sepidehMS I"ll follow up with you offline about doing this.

@dennisdietrich thanks again for doing this -- I hope it doesn't discourage you from other contributions although I'd understand if it did. We didn't have enough foresight when this started.

**Pull request closed without merging**
