### PR TITLE
Re-enable disabled Uri tests on Unix

### PR DESCRIPTION
**Pull request by stephentoub**
cc: @hughbe 
Closes https://github.com/dotnet/corefx/issues/7791 after https://github.com/dotnet/corefx/pull/7829 hopefully fixed it.

### CODE REVIEW

**Comment by hughbe** [comment]
Interesting, it seems like we have a behaviour difference between Windows and non-Windows in the way that they handle invalid punycode in the host:
E.g. `http://xn--abc` parses as `xn--abc` on Windows but is converted into Unicode on non-Windows (see the logs for more)

**Comment by stephentoub** [comment]
Thanks, @hughbe. I've disabled that one theory entry on Unix against a new issue https://github.com/dotnet/corefx/issues/7921.

**Comment by bartonjs** [comment]
LGTM

**Comment by mmitche** [comment]
@dotnet-bot test Innerloop OSX Debug Build and Test
@dotnet-bot test Innerloop OSX Release Build and Test

**Comment by mmitche** [comment]
@dotnet-bot test Innerloop OSX Release Build and Test
@dotnet-bot test Innerloop OSX Debug Build and Test

**Comment by stephentoub** [comment]
Test Innerloop OSX Debug Build and Test please
Test Innerloop OSX Release Build and Test please

**Comment by stephentoub** [comment]
Test Innerloop OSX Debug Build and Test please
 Test Innerloop OSX Release Build and Test please

**Comment by stephentoub** [comment]
Test Innerloop OSX Release Build and Test please

**Pull request merged**
