### PR TITLE
Fix 7547 - BOOL result compared against TRUE

### PR DESCRIPTION
**Pull request by AtsushiKan**
Fixes https://github.com/dotnet/corefx/issues/7547

Let's just call a bool, a bool, yes?

The .sln configuration list was all out of sync too
so fixed that.

### CODE REVIEW

**Comment by AtsushiKan** [comment]
cc @bartonjs

**Comment by bartonjs** [comment]
I was initially concerned that ConvertStringSecurityDescriptorToSecurityDescriptorW wasn't well formed on its return values; but it looks pretty well behaved to me.

LGTM.

**Comment by Dmitry-Me** [comment]
What? `[DllImport]`ing a function and changing its return type? Does this have a chance to work?

**Comment by AtsushiKan** [comment]
“bool” on a P/Invoke maps to Win32 BOOL (32-bit int where 0x00000000 marshals to C# false and everything else marshals to C# true.)

I believe there was another package that has this same pattern – you should probably change that too as the old pattern looks really strange to a C# programmer.

**Comment by bartonjs** [comment]
> 32-bit int where 0x00000000 marshals to C# false and everything else marshals to C# true.

Well, sort of.
0x00000000 marshals to C# false.
0x00000001 marshals to C# true.
Everything else marshals to a System.Boolean whose ToString() is "true", but whose value is != true.  I don't remember which way it evaluates in an if (probably as true), but if (someRealBool == someMarshalledBool) might be false even if both things ToString as true.

Strange, but true.

**Comment by AtsushiKan** [comment]
You’re talking to the guy who implemented P/Invoke ☺

The default bool marshaler assumes the WINBOOL is non-normalized and normalizes to the managed bool.

Here’s the proof:


extern "C"
FOO_API BOOL Weird(void)
{
    printf("Hi!\n");
    return (BOOL)42;
}


using System;
using System.Runtime.InteropServices;

class n
{
    static void Main()
    {
        bool b = Weird();
        Console.WriteLine(b);
        Console.WriteLine(b == true);

        unsafe
        {
            byte* pb = (byte*)&b;
            byte bAsByte = *pb;
            Console.WriteLine(bAsByte == 1);
        }

    }

    [DllImport("foo.dll")]
    static extern bool Weird();
}

prints

Hi!
True
True
True

**Comment by bartonjs** [comment]
@AtsushiKan Huh, someone must've broken it on Linux, I definitely got into a state where a returned Boolean printed as "True" but wasn't == to Boolean.True.  I assumed it was me being off-the-grid, not a bug in the marshaller.

**Comment by AtsushiKan** [comment]
That may be a bug in the marshaler on Linux. Even if the definition of native bool on Unix “guarantees” normalization, it sounds iffy for the coreclr marshaler to rely on it.

**Pull request merged**
