### PR TITLE
Fix three failed DateTime array tests.

### PR DESCRIPTION
**Pull request by shmao**
Three DCS/DCJS tests are failing in dev/api branch. A fix had been merged into master branch. The PR cherry-picks commit cfbaa48f113a50757f76169ba24fed910b0750f0 from master to dev/api.

### CODE REVIEW

**Comment by shmao** [comment]
@mconnew @iamjasonp @zhenlan Is cherry-picking  the right way of merging commits from master branch to dev/api branch? Will it cause any conflicts in the future? I noticed that the cherry-pick commit number, 63c05d0a1425e65bcf35e70c00d780aa94296f9f, is different from the one, cfbaa48, in master branch.

**Comment by zhenlan** [comment]
LGTM pending CI passing.

cc: @Petermarcu fyi

**Comment by iamjasonp** [comment]
Changes LGTM

As for your questions... 

>  Is cherry-picking the right way of merging commits from master branch to dev/api branch? 

Yeah, that's the best way I know of

> Will it cause any conflicts in the future? 

Depends on the merge algorithm :laughing: But my experience has been when merging files with the exact same content/changes, the Git merge algorithm seems to automerge correctly

> I noticed that the cherry-pick commit number,  63c05d0 , is different from the one,  cfbaa48 , in master branch. 

Yep, this is expected; the SHA is based on a few things, such as the parent commit sha1, the committer info, and the commit message among others. When you cherry pick, you're basing your commit off a new parent commit, which means that the hash will be different even if the changes are the same

Hope this answers your questions :smile:

**Comment by stephentoub** [comment]
@joperezr, is this going to complicate your merge of master to dev/api?

**Comment by shmao** [comment]
@dotnet-bot test Innerloop Ubuntu14.04 Release Build and Test please

A System.Net test failed.

**Comment by shmao** [comment]
@dotnet-bot test Innerloop Ubuntu14.04 Release Build and Test please

> There were xunit test failures in System.IO.Tests

**Comment by shmao** [comment]
@dotnet-bot test Innerloop Ubuntu14.04 Release Build and Test please

The test still failed for the same reason,
> There were xunit test failures in System.IO.Tests

**Comment by shmao** [comment]
Ubuntu release build keeps failing on the following error, which seems not related to the change,

```
10:34:36 /mnt/j/workspace/dotnet_corefx/dev_api/ubuntu14.04_release_prtest/Tools/tests.targets(260,5): warning MSB3073: The command "/mnt/j/workspace/dotnet_corefx/dev_api/ubuntu14.04_release_prtest/bin/tests/AnyOS.AnyCPU.Release/System.IO.Tests/netcoreapp1.0/RunTests.sh /mnt/j/workspace/dotnet_corefx/dev_api/ubuntu14.04_release_prtest/packages/" exited with code 134. [/mnt/j/workspace/dotnet_corefx/dev_api/ubuntu14.04_release_prtest/src/System.IO/tests/System.IO.Tests.csproj]
10:34:36 /mnt/j/workspace/dotnet_corefx/dev_api/ubuntu14.04_release_prtest/Tools/tests.targets(269,5): error : One or more tests failed while running tests from 'System.IO.Tests' please check log for details! [/mnt/j/workspace/dotnet_corefx/dev_api/ubuntu14.04_release_prtest/src/System.IO/tests/System.IO.Tests.csproj]
```

@stephentoub is it ok to merge this PR?

**Comment by shmao** [comment]
@dotnet-bot test Innerloop Ubuntu14.04 Release Build and Test please

**Comment by stephentoub** [comment]
Yeah, go ahead.  @joperezr currently has a PR out to fix the System.IO assembly loading issue.

**Comment by shmao** [comment]
Thanks for the ACK, @stephentoub. Merging the PR.

**Pull request merged**
