### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by joshfree**
- change the columns from debug/release to inner/outer loop
- add cpu prefix to badges
- correct win 8 to be win 8.1

### CODE REVIEW

**Comment by ellismg** [comment]
To capture what we discussed in your office.  We think we should add per merge coverage for all the empty cells in this table.

@joshfree I was thinking about how we display the code coverage stuff, what would you think about moving the code coverage badges out into a new column named "Code Coverage"?  We could then try to fill in the code coverage runs on Windows 7/Windows 10/Nano as well and the table might look a little less unbalanced.  @stephentoub uses the code coverage stuff the most, so he might have an opinion as well?

**Comment by joshfree** [comment]
@ellismg I think increasing the code coverage runs to cover native and other OS versions and platforms is general goodness.  We could add another column as part of adding more CC runs; we could also just move the CC badges to another separate table as well.  For the mean time, I think I'll just leave the CC badges there for now and we can fiddle with that piece a bit more once we increase coverage.  Let me know if you disagree.

**Comment by ellismg** [comment]
> I think I'll just leave the CC badges there for now and we can fiddle with that piece a bit more once we increase coverage.

Sounds good.  LGTM.

**Comment by joshfree** [comment]
thanks @ellismg

**Comment by stephentoub** [comment]
> I was thinking about how we display the code coverage stuff, what would you think about moving the code coverage badges out into a new column named "Code Coverage"? We could then try to fill in the code coverage runs on Windows 7/Windows 10/Nano as well and the table might look a little less unbalanced. @stephentoub uses the code coverage stuff the most, so he might have an opinion as well?

I've gone back and forth on that in the past.  I don't know that it's actually worth filling out such coverage, unless a) we have non-trivial amounts of code paths that differ based on the Windows platform, b) we have a good way to see such diffs, and c) people will pay attention to those diffs and work to eliminate the gaps.  I do think it'd be valuable to have a code coverage run on Linux and one on OSX, but I don't believe the tools are ready for that yet.  Until then, I'd be fine if we wanted to either move them to a separate table, or even just turn them into their own row in the table, even though "code coverage" isn't a "platform".

**Pull request merged**
