### PR TITLE
Add Ubuntu 18.04 to CI test runs

### PR DESCRIPTION
**Pull request by MattGal**
@richlander  FYI.

### CODE REVIEW

**Comment by MattGal** [comment]
@dotnet-bot test Linux x64 Release Build please

**Comment by stephentoub** [comment]
@MattGal, can this be merged?

**Comment by MattGal** [comment]
Thanks @stephentoub , yes I will merge now.  There was a weird seg fault in a single test in the first run, if that starts to repro regularly we can revisit it.

**Comment by stephentoub** [comment]
Thanks.

**Pull request merged**
