### PR TITLE
Remove some unnecessary Substrings in System.Net.Http

### PR DESCRIPTION
**Pull request by stephentoub**
cc: @geoffkizer, @davidsh

### CODE REVIEW

**Comment by stephentoub** [comment]
@dotnet-bot test OSX x64 Debug Build please ("Error during cleanup: java.io.IOException: remote file operation failed")

**Comment by benaadams** [comment]
@dotnet-bot test Windows x64 Debug Build

**Comment by benaadams** [comment]
@dotnet-bot test outerloop linux x64 debug build
@dotnet-bot test outerloop windows x64 debug build
@dotnet-bot test outerloop OSX x64 debug build

**Comment by benaadams** [comment]
Outerloop issue is some issue with BinaryFormatterTests
```
 System.Runtime.Serialization.Formatters.Tests  xunit  
System.Runtime.Serialization.Formatters.Tests.BinaryFormatterTests/ValidateAgainstBlobs
(obj: Bitmap
 { Flags = 77840, FrameDimensionsList = [7462dc86-6180-4c7e-8e3f-ee7333a7a483], Height = )
Assert.Equal() Failure
Expected: 77840
Actual:   73744

   at System.Runtime.Serialization.Formatters.Tests.EqualityExtensions.IsEqual(Bitmap this, Bitmap other, Boolean isSamePlatform)
 in /mnt/j/workspace/dotnet_corefx/master/linux-TGroup_netcoreapp+CGroup_Debug+AGroup_x64+TestOuter_true_prtest/
src/System.Runtime.Serialization.Formatters/tests/EqualityExtensions.cs:line 1233
```

**Pull request merged**
