### PR TITLE
Increment package versions for 1.0.0 servicing

### PR DESCRIPTION
**Pull request by chcosta**
/cc @ericstj @markwilkie @Chrisboh @gkhanna79

### CODE REVIEW

**Comment by gkhanna79** [comment]
Skimming through the change, looks good to me. I will let @ericstj make the final call.

**Comment by ericstj** [comment]
What about the PKGProjs in the pkg folder?

**Comment by chcosta** [comment]
Thanks Eric,  I thought you had mentioned earlier today that updating those packages was not necessary.  I misinterpreted your comments,  I'll prepare a change to update those as well and get this pr updated late this weekend.

**Comment by chcosta** [comment]
@dotnet-bot test Innerloop Windows_NT Release Build and Test

**Comment by ericstj** [comment]
Only NETStandard.Library shouldn't be updated.  The others should be.  Also make sure to update their versions in packages.props in the root.

**Comment by ericstj** [comment]
Please update these: https://github.com/dotnet/corefx/blob/master/Packaging.props#L20-L21

**Comment by chcosta** [comment]
Those properties don't exist in release/1.0.0.  Does something else need to be done?

https://github.com/dotnet/corefx/blob/release/1.0.0/Packaging.props#L19

**Comment by ericstj** [comment]
We were using the default values in buildtools: https://github.com/dotnet/buildtools/blob/release/1.0.0/src/Microsoft.DotNet.Build.Tasks.Packaging/src/PackageFiles/Packaging.targets#L85-L88

We should add to `packaging.props` as
```xml
  <PropertyGroup>
    <LineupPackageVersion Condition="'$(LineupPackageVersion)' == ''">1.0.3</LineupPackageVersion>
    <PlatformPackageVersion  Condition="'$(PlatformPackageVersion)' == ''">1.0.2</PlatformPackageVersion>
  </PropertyGroup>
```

Optionally you could use these in the individual pkgproj's for these same packages if you wanted to avoid duplication.

**Comment by chcosta** [comment]
@ericstj , I spent a few moments playing around with adding those properties to the individual packages to avoid duplication, but the properties weren't flowing correctly and I didn't dive into it.  I updated packaging.props and one other package which did not have a properly updated package version.

**Comment by gkhanna79** [comment]
@chcosta Please merge the change when CI is green and trigger a pipeline build. Do coordinate with @dagood to ensure we get the correct updates of CoreFX packages in Core-Setup.

**Pull request merged**
