### PR TITLE
[release/2.0.0] Merge dev/release/2.0.0 into release/2.0.0

### PR DESCRIPTION
**Pull request by weshaggard**
cc @dagood @eerhardt

### CODE REVIEW

**Comment by eerhardt** [comment]
Are the .groovy file changes necessary?  Those changes seem outside the scope of the source-build and orchestrated build efforts.

Have we ensured the .groovy file changes work correctly?  /cc @chcosta

**Comment by chcosta** [comment]
The groovy changes aren't strictly necessary.  They were needed as part of the work to transition official builds from VSTS to Jenkins, but with that work being de-prioritized, I still opportunistically ported the groovy changes to dev/release/2.0.0 in the hopes that they would merge to release/2.0.0 at some point (looks like that point is now).  I don't, however, think they were fully validated.  In discussions with @mmitche at the time, we thought the changes would be relatively safe.

**Comment by weshaggard** [comment]
I would like the groovy file changes to come into release/2.0.0 as I've been wanting to get the pipeline based CI working here for a while.

**Comment by weshaggard** [comment]
test Innerloop OSX10.12 Debug x64 Build and Test 
test Innerloop OSX10.12 Release x64 Build and Test

test ci

**Comment by weshaggard** [comment]
test Innerloop OSX10.12 Debug x64 Build and Test
test Innerloop OSX10.12 Release x64 Build and Test

**Pull request merged**
