### PR TITLE
Add System.Net.HttpListener to test-runtime project.json

### PR DESCRIPTION
**Pull request by karajas**
This fixes an issue in official build. 
edit: Adding it to netcoreapp1.1 section as well

/cc @weshaggard @Priya91

### CODE REVIEW

**Comment by Priya91** [comment]
LGTM

**Comment by weshaggard** [comment]
@karajas do you know why this didn't repro in CI? I'm not sure I understand that part.

**Comment by karajas** [comment]
As far as I can tell, it seems as though since it's a new library we didn't have a reference to it in the generated project.json. So local CI would pick up the pkgproj ref and compile and execute, whereas in the BuildAgainstPackages scenario the pkgproj references aren't evaluated and instead the refs from the generated project.json are used, which come from the test-runtime project.json with the latest version.

**Comment by karajas** [comment]
So now there's like an implicit requirement to add a new library to the test-runtime project.json. This requires some automation maybe.

**Pull request merged**
