### PR TITLE
Fixing documentation for code coverage

### PR DESCRIPTION
**Pull request by joperezr**
Fixing docs for code coverage runs

Note: I'm not skipping CI since I'll use this PR to validate outerloop and coverage runs.

cc: @weshaggard

### CODE REVIEW

**Comment by joperezr** [comment]
@dotnet-bot help

**Comment by joperezr** [comment]
@dotnet-bot test ci please

**Comment by joperezr** [comment]
@dotnet-bot test outerloop please

**Comment by joperezr** [comment]
@dotnet-bot test @dotnet-bot test outerloop Windows_NT Debug please

**Comment by joperezr** [comment]
@dotnet-bot test outerloop Ubuntu14.04 Debug please

**Comment by weshaggard** [comment]
This might help kick off the coverage runs for CI but do they actually work? It was my understanding that we are still missing the pdbs so the don't actually work.

**Comment by joperezr** [comment]
shouldn't they work at least in Windows? cc: @stephentoub

**Comment by mellinoe** [comment]
@weshaggard That's what I thought as well. There's no PDB's in the runtime folder, but that should be easily fixable. Want me to give it a shot?

**Comment by weshaggard** [comment]
>@weshaggard That's what I thought as well. There's no PDB's in the runtime folder, but that should be easily fixable. Want me to give it a shot?

Yes please.

**Comment by joperezr** [comment]
Merging this since even if more changes are required for coverage runs to work, documentation change is required anyway.

**Pull request merged**
