### PR TITLE
Misc. cleanup of instructions

### PR DESCRIPTION
**Pull request by bartdesmet**
In preparation of generating many of the instructions using a T4 file, I'm addressing some stylistic oddities and inconsistencies in the existing code.

The use of T4 text templates will make it easier to maintain these instructions (typically N operations against M primitive types, e.g. arithmetic instructions) and change them in bulk for performance optimizations and whatnot.

Related to https://github.com/dotnet/corefx/pull/14086.

### CODE REVIEW

**Comment by danmosemsft** [comment]
@VSadov

**Comment by stephentoub** [comment]
I'm not clear on why some of these changes are being made.  For example, why does ```s_int32``` need to change to ```s_Int32```... could the template just lowercase the type name?

**Comment by JonHanna** [comment]
Then `s_UInt16` would have to change to `s_uint16`, though that is perhaps the more consistent with naming elsewhere.

**Comment by bartdesmet** [comment]
See https://github.com/dotnet/corefx/pull/14180 for the WIP PR that introduces the T4 files. To make generating the triplets of `XYZInstruction`, `case TypeCode.XYZ`, and `s_XYZ` - where `XYZ` is a primitive type such as `Int32` - easy/consistent, this rename of fields was carried out. Note that the `Not` instruction has more work to be done; the static fields don't even start with `s_`.

**Pull request merged**
