### PR TITLE
Console Title test should run in separate process.

### LINKED ISSUE #6223: WindowAndCursorProps.Title_Set failed on Windows 10
http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/outerloop_win10_debug/91/consoleFull
```
10:33:10      WindowAndCursorProps.Title_Set [FAIL]
10:33:10         System.IO.IOException : No process is on the other end of the pipe
10:33:10         Stack Trace:
10:33:10            d:\j\workspace\outerloop_win---0cba2915\src\System.Console\src\System\ConsolePal.Windows.cs(539,0): at System.ConsolePal.set_Title(String value)
10:33:10            d:\j\workspace\outerloop_win---0cba2915\src\System.Console\src\System\Console.cs(265,0): at System.Console.set_Title(String value)
10:33:10            d:\j\workspace\outerloop_win---0cba2915\src\System.Console\tests\WindowAndCursorProps.cs(107,0): at WindowAndCursorProps.Title_Set()
```

### PR DESCRIPTION
**Pull request by ianhays**
Modifying the Title of the test process in Outerloop is prone to failure. Moving it to its own process is a bit safer.

probably resolves #6223. I'll have to keep an eye on the win10 outerloop runs to verify this. They pass without issue locally.

### CODE REVIEW

**Comment by stephentoub** [comment]
Test Outerloop Win10 Debug please

**Comment by stephentoub** [comment]
Test Outerloop Windows10 Debug please

**Comment by stephentoub** [comment]
Test Outerloop Windows 10 Debug please

**Comment by stephentoub** [comment]
Test Innerloop Ubuntu14.04 Debug Build and Test please

**Comment by stephentoub** [comment]
If this fixes the issue, LGTM.

**Comment by ianhays** [comment]
Test Outerloop Windows 7 Debug please
Test Outerloop Windows 8 Debug please

**Comment by ianhays** [comment]
Test Outerloop Windows 8.0 Debug please
Test Outerloop Windows 8.1 Debug please

**Comment by ianhays** [comment]
Test Outerloop Windows 10 Debug please

**Comment by ianhays** [comment]
Test Outerloop Windows 10 Debug please

**Comment by ianhays** [comment]
Split the test up and did some refactoring and now it passes apparently.

**Comment by ianhays** [comment]
Test Outerloop Windows 10 Debug please

**Comment by ianhays** [comment]
Test Outerloop Windows 7 Debug please

**Comment by ianhays** [comment]
test OuterLoop Windows 7 Debug please
test OuterLoop Windows 10 Debug please

**Comment by ianhays** [comment]
@stephentoub I made some more small changes and broke up the test. I tried it a few times on the CI and it passes Win10 outerloop consistently now. I also enabled some other tests that weren't marked as [Fact]s.

**Comment by stephentoub** [comment]
Test OuterLoop Windows 7 Debug please

**Comment by stephentoub** [comment]
LGTM.

Were you able to determine why it was failing?

**Comment by ianhays** [comment]
No, I wasn't. The old test that just set the title and did nothing else failed in the same way as the big test that set it in a try/finally, so I'm stumped there because by that logic these tests should fail also. The difference is the RemoteInvoke,

**Comment by stephentoub** [comment]
Test OuterLoop Windows 7 Debug please

**Pull request merged**
