### PR TITLE
Move XmlSerializer CodeGen from SGen to S.P.Xml

### PR DESCRIPTION
**Pull request by shmao**
The PR is moving the CodeGen code of XmlSerializer from SGen back to System.Private.Xml.dll.

### CODE REVIEW

**Comment by jkotas** [comment]
Could you please share more detail on why this change is done? Why it was separate in the first places? What impact does it have on how the SGen tool is shipped and serviced?

**Comment by shmao** [comment]
@dotnet-bot test NETFX x86 Release Build

**Comment by shmao** [comment]
@jkotas Thanks for reviewing this. Please see below for my answers to your questions.

> Why it was separate in the first places? 

The desktop framework can do serialization in two different ways, using IL emit or using code generation (CodeGen). Using CodeGen is the legacy way. On Net Core, we made the serialization to use IL emit only. We didn't port the implementation of CodeGen to Net Core. 

The Sgen tool, however, requires CodeGen. As Sgen is the only consumer of those types, we put those types into Sgen's folder at the first place. And Sgen shared some code files with `System.Private.Xml`. We put the types in those files under different namespaces.

> Could you please share more detail on why this change is done? 

Although the structure described above worked for Sgen, it didn't work for Svcutil. Especially the types under different namespaces caused some problems.

> What impact does it have on how the SGen tool is shipped and serviced?

The released SGen 1.0 would not work with the next release of Net Core. It works with Net Core 2.0 only.

The next release of SGen would support the next release of Net Core. It would not support Net Core 2.0. 

For servicing Sgen 1.0, we would release servicing packages from release/2.0.0 branch.

**Comment by jkotas** [comment]
> The released SGen 1.0 would not work with the next release of Net Core. It works with Net Core 2.0 only.

This means that we cannot use roll forward to 2.1 for SGen.

@Petermarcu Is this a problem?

**Comment by shmao** [comment]
> The released SGen 1.0 would not work with the next release of Net Core.

This statement was incorrect. SGen 1.0 should still work with the next release of Net Core. 

And we planned to release the new version of Sgen along with the next release of Net Core.

**Comment by shmao** [comment]
@jkotas @Petermarcu please let me know if you have any further concerns regarding to this PR. I planned to merge this by noon today. Thanks.

**Comment by weshaggard** [comment]
IIRC the reason we didn't put the code into System.Private.Xml to begin with was because of the size of the additional code. Is that no longer a concern? Does System.Private.Xml grow in any sizable amount?

I would also like to understand the svcutil issue a little better. Why does it need to care about what namespace these types are contained in?

>This statement was incorrect. SGen 1.0 should still work with the next release of Net Core.
And we planned to release the new version of Sgen along with the next release of Net Core.

The issue that @jkotas is bringing up is we need to ensure that any sgen'ed library from 1.0 SGen will still run correctly on the next version of .NET Core without needing to regenerate with a newer version of SGen tool. Can you please confirm that should be the case?

**Comment by shmao** [comment]
@weshaggard The size of the additional code was one of the reasons we didn't put the CodeGen code into System.Private.Xml.dll. And it also because we didn't see value of having the additional code in the library. But now we see the value. Before the change, the size of System.Private.Xml was 3573 KB; after the change, the size became 3683 KB. The size increase does not seem too bad.

> Why does it need to care about what namespace these types are contained in?

To be able to serialize a type, XmlSerializer needs to parse the type first and generate an instance of `XmlMapping`, which contains all the information of the type. XmlSerializer then generates the serializer according to the `XmlMapping` object. WCF has its own way of generating `XmlMapping` objects for `ServiceContract`s or `OperationContract`s. The two `XmlMapping` types under different namespaces cause Sgen cannot use the `XmlMapping` objects created by WCF.

> We need to ensure that any sgen'ed library from 1.0 SGen will still run correctly on the next version of .NET Core without needing to regenerate with a newer version of SGen tool. Can you please confirm that should be the case?

Yes, that will be the case. The serialization assembly generated by 1.0 will still work with the newer version of the framework.

**Comment by weshaggard** [comment]
>To be able to serialize a type, XmlSerializer needs to parse the type first and generate an instance of XmlMapping, which contains all the information of the type. XmlSerializer then generates the serializer according to the XmlMapping object. WCF has its own way of generating XmlMapping objects for ServiceContracts or OperationContracts. The two XmlMapping types under different namespaces cause Sgen cannot use the XmlMapping objects created by WCF.

I assume you guys also considered just doing this for XmlMapping and its closure? I don't know how large that is but it would also be another potential option.

**Comment by shmao** [comment]
> I assume you guys also considered just doing this for XmlMapping and its closure? 

Yes, we considered that option. `XmlMapping` gets involved with many other types and internal types and fields. This option is not actually feasible.

**Comment by weshaggard** [comment]
A couple more follow-up questions:

- Does this expose any new public surface area in System.Private.Xml? I didn't see any at a quick glance but there is a lot of code here.
- Does this require any internalsvisibleto from Sgen to System.Private.Xml, or are all the APIs Sgen requires already public in System.Private.Xml?

**Comment by shmao** [comment]
> Does this expose any new public surface area in System.Private.Xml? I didn't see any at a quick glance but there is a lot of code here.

No, this does not expose new public surface area. 

> Does this require any internalsvisibleto from Sgen to System.Private.Xml, or are all the APIs Sgen requires already public in System.Private.Xml?

Sgen and Svcutil will need to call a method in System.Private.Xml.dll via reflection.

**Comment by weshaggard** [comment]
OK that is all my questions. I think I can live with the change.

**Comment by shmao** [comment]
Thanks a lot for reviewing the changes and the questions, @weshaggard

**Pull request merged**
