### PR TITLE
Rename the baseline file for ApiCompat to specify net463.

### PR DESCRIPTION
**Pull request by AlexGhiondea**
The 2 APIs that are currently baselined were introduced in 4.6.3. but we don't have a targeting pack for that and we are using the 4.6.2. one which does not expose those APIs.

Once we have the targeting pack for 4.6.3. we are going to be able to remove the baseline file.

### CODE REVIEW

**Comment by AlexGhiondea** [comment]
@dotnet-bot please test Innerloop CentOS7.1 Debug Build and Test and Innerloop CentOS7.1 Release Build and Test

**Comment by AlexGhiondea** [comment]
@dotnet-bot please test Innerloop CentOS7.1 Release Build and Test

**Comment by ellismg** [comment]
The centos failures are due to us picking up a live coreclr and getting [this](https://github.com/dotnet/coreclr/commit/a22c755549f6c472af861d7b1eaef918db9a0041) change which updated Guid's HashCode algorithm.

I am going to disable these tests.

**Comment by ericstj** [comment]
No need to reset this PR if that;s the only failure.  Need to get CI unblocked.

**Comment by ellismg** [comment]
> No need to reset this PR if that;s the only failure. Need to get CI unblocked.

I agree.  It looks like the Innerloop Windows_NT Release Build and Test run has hung.  I am going to try to get a dump from the machine.

**Comment by ellismg** [comment]
> I am going to try to get a dump from the machine.

Didn't catch it in time and Jenkins aborted the job.  I'll try to look at the logs and understand at least what test suite was running.

**Comment by ellismg** [comment]
I'm just going to merge this as is.  The other Windows leg passed.  I don't think Alex's changes could have caused the hang.  I would like to get CI unblocked.

**Comment by ericstj** [comment]
:+1:

**Comment by AlexGhiondea** [comment]
@ellismg thanks for merging. 

About the Guid tests, do these failures point to a compat issue with the new hashcode?

**Comment by ericstj** [comment]
@AlexGhiondea Perhaps on desktop.  HashCode changes can impact sort order which we know is compat-impacting.

**Pull request merged**
