### PR TITLE
Update package dependencies to rc2-23921

### PR DESCRIPTION
**Pull request by ellismg**

### CODE REVIEW

**Comment by ellismg** [comment]
@stephentoub, was there anything I needed to do aside from update the expected version in dir.props and then run `.\build.cmd /t:UpdateInvalidPackageVersions`?

**Comment by stephentoub** [comment]
Nope, that's it.

**Comment by stephentoub** [comment]
LGTM

**Comment by weshaggard** [comment]
LGTM

**Comment by bartonjs** [comment]
The "do you want to create a pull request?" banner) reiterated to me that this was rc2.  Should I have left this for the rc2 review meeting (and if yes, should we revert it)?

**Comment by ellismg** [comment]
@bartonjs It was alreasy approved, so no worries.

**Pull request merged**
