### PR TITLE
Remove allocation for empty Activity.Baggage/Tags

### PR DESCRIPTION
**Pull request by stephentoub**
Accessing Activity.Baggage/Tags allocates an enumerable, even when there is no baggage or tags.  This fast-paths the empty case.

### CODE REVIEW

**Comment by stephentoub** [comment]
I realized that technically this is a breaking change. If you get the enumerable, then add baggage, and then iterate through the previously retrieved enumerable, it may not contain the subsequently-added baggage. I don't know whether that matters.

**Comment by stephentoub** [comment]
Thanks, @lmolkova.  @noahfalk, do you agree?

**Comment by davidfowl** [comment]
+1 Agree with @lmolkova

**Comment by davidfowl** [comment]
One of the platforms is missing Array.Empty

**Comment by stephentoub** [comment]
> One of the platforms is missing Array.Empty

Yeah, just been waiting to fix it until we all agreed to go ahead with this :)

**Comment by stephentoub** [comment]
Thanks, all.

**Pull request merged**
