### PR TITLE
Reorganize src\Common\tests\ a bit

### LINKED ISSUE #3543: Repo organization guidelines for Common\tests
Currently, there's a free-for-all regarding how code is placed in `src/Common/tests` folders, unlike the `src/Common/src` folder tree which has clear guidelines.

There are a few proposals:
1) Mirror the `src/Common/src` idea and have everything properly aligned to the namespace. So, the folder paths would look like this:

`src/Common/tests/System/Net/Http/HelperClass.cs`.  

Note that each namespace path is one word only per part in the pathname.

This seems to be the most logical choice although. It could create some confusion at first since, for example, Sockets tests will add to Threading, EventSource and Resources but in the end will allow for better organization, review and increase code reuse.

2) Organize `src/Common/tests` per namespace ownership: /System.Net; /System.Xml, etc. So, the folder paths would look like this:

`src/Common/tests/System.Net.Http/HelperClass.cs`

This is partially what's going on today although there are folders that aren't fully specifying the namespace such as Collections, Compression, etc.

Please add your opinions.

### PR DESCRIPTION
**Pull request by stephentoub**
Fixes #3543 
cc: @nguerrera, @weshaggard, @cipop

Our common tests folder has gotten a bit unwieldy in its organization.  This change simply moves files around to better map to how src\Common\src is organized.  Files are now stored in a path based on functionality/namespace.

I mostly kept groups of functionality together and did not attempt to reorganize at that level, e.g. I moved the src\Common\tests\System.Xml.XPath\ folder to be src\Common\tests\System\Xml\XPath\ and did not further reorganize all of the folders/files it contains.  Such cleanup can be done separately on each individual area.

Some of the files also need to be cleaned up internally, e.g. the namespace (or lack thereof), so I put such things in a path that I thought made sense even if it differs from the current namespace in the file; I wanted this change to be relatively simple and just be about moving files around to clean up the main hierarchy.

### CODE REVIEW

**Comment by nguerrera** [comment]
LGTM. Thanks for cleaning this up.

**Comment by weshaggard** [comment]
LGTM as well assuming the CI is green.

**Comment by CIPop** [comment]
Nit: Please add a coding organization .md file as well. 

LGTM

**Comment by stephentoub** [comment]
@dotnet-bot test this please (after Jenkins changes related to setting culture-related env vars)

**Comment by stephentoub** [comment]
@dotnet-bot test this please (#3744)

**Comment by stephentoub** [comment]
> Nit: Please add a coding organization .md file as well.

Thanks.  We can address that separately.

**Pull request merged**
