### PR TITLE
Stub out OSX implementations of Process and DriveInfo

### PR DESCRIPTION
**Pull request by stephentoub**
Stubs out OSX implementations of System.Diagnostics.Process.dll and  System.IO.FileSystem.DriveInfo.dll.

I moved some code around in the Linux implementation, but other than one function (IsProcessRunning), I didn't actually change any code in the Linux implementation.

### CODE REVIEW

**Comment by stephentoub** [comment]
cc: @ellismg, @sokket

**Comment by ellismg** [comment]
Can you help me understand the difference between the PAL section and the Unix PAL sections?

**Comment by stephentoub** [comment]
I reverted the automatic changes made to the solution file.

Regarding the PAL comments... in most cases, we have a main partial class P.cs and then we specialize it for Windows or Unix with P.Windows.cs or P.Unix.cs.  In such cases, we separate out things that are required either by consumers of P or by the main P implementation from things that are only needed by the implementation of one of those specialized implementations... anything needed outside of P.Windows.cs goes above the comment, anything only by what's above the comment goes below the comment.  But in a few cases, we have a sort of hierarchy: we have the main P.cs, P.Windows.cs, and P.Unix.cs, but then P.Unix.cs itself is a sort of parent to P.Linux.cs and P.OSX.cs... in such cases, P.Unix.cs provides some functionality and is then expecting certain pieces of function to be exposed from P.Linux.cs and P.OSX.cs.  Since such functionality need not be exposed by P.Windows.cs but must be exposed by any derivation of P.Unix.cs, I thought it worthwhile to call it out as being part of a PAL layer but to keep it separate from the main one. Let me know if you don't think that's a worthwhile distinction to make or if you'd prefer to see it done differently.

**Comment by ellismg** [comment]
Thanks, that sort of matched what I had guessed.  If it was me, I would not distinguish the PAL between the two cases, but it's a judgment call and my care level on this one is pretty low.  If you think it's worthwhile, I'm happy to defer to your gut, since you've been doing much more of this recently.

It might be a good idea at some point for us to write out an overview of how we PAL out APIs (and talk about some of the conventions, like PAL ENDS HERE and such).  When we do that, let's just make sure we explain the convention.

**Comment by stephentoub** [comment]
Sounds good.  I'll leave it for now... it's easy to delete the comment later if we so choose :smile:  And, yeah, adding a wiki page on this stuff is a good idea.

**Pull request merged**
