### PR TITLE
Remove CmsSigner property setters not present in .NET Framework.

### PR DESCRIPTION
**Pull request by filipnavara**

### CODE REVIEW

**Comment by filipnavara** [comment]
All the test fail because it doesn't match the API baseline. Well, that's true, but the baseline was probably wrong in the first place. These property setters are not present in either .NET Framework or .NET Standard. How to proceed?

**Comment by stephentoub** [comment]
cc: @bartonjs

**Comment by bartonjs** [comment]
The properties are defined as get/set in the ref.cs (src\System.Security.Cryptography.Pkcs\ref\System.Security.Cryptography.Pkcs.cs), so they'd need to be removed from there at the same time.

I'm not sure we have a process to oops and remove an unintended setter after a package ships.  @weshaggard Thoughts?  (System.Security.Cryptography.Pkcs is not part of the shared framework, as far as I know, if that matters)

**Comment by bartonjs** [comment]
Looks like the problem is ApiCompat for netfx ran against the netfx ref... and that meant it compared System.Security.dll's copy of CmsSigner against System.Security.dll's copy of CmsSigner (surprise, they matched :smile:).

Running ApiCompat for netfx impl vs netstandard ref

> D:\git\bartonjs\corefx\Tools\dotnetcli\dotnet D:\git\bartonjs\corefx\Tools\ApiCompat.exe D:\git\bartonjs\corefx\bin\ref\netstandard\System.Security.Cryptography.Pkcs.dll -contractDepends:"D:\git\bartonjs\corefx\bin\ref\netfx\,D:\git\bartonjs\corefx\bin/ref/netfx/," -implDirs:"D:\git\bartonjs\corefx\bin/obj/Windows_NT.AnyCPU.Debug/System.Security.Cryptography.Pkcs/netfx/,D:\git\bartonjs\corefx\bin\ref\netfx\,"

Indicates just these three errors:

> Compat issues with assembly System.Security.Cryptography.Pkcs:
MembersMustExist : Member 'System.Security.Cryptography.Pkcs.CmsSigner.Certificates.set(System.Security.Cryptography.X509Certificates.X509Certificate2Collection)' does not exist in the implementation but it does exist in the contract.
MembersMustExist : Member 'System.Security.Cryptography.Pkcs.CmsSigner.SignedAttributes.set(System.Security.Cryptography.CryptographicAttributeObjectCollection)' does not exist in the implementation but it does exist in the contract.
MembersMustExist : Member 'System.Security.Cryptography.Pkcs.CmsSigner.UnsignedAttributes.set(System.Security.Cryptography.CryptographicAttributeObjectCollection)' does not exist in the implementation but it does exist in the contract.
Total Issues: 3

Running it in master indicates 9 additional errors, new members which got added to the netstandard ref instead of the netcoreapp ref.  So I'll merge this now, and fix up the other 9 in a different PR.

**Comment by weshaggard** [comment]
@bartonjs do you plan to try and take this for servicing in 2.1?

**Comment by bartonjs** [comment]
@weshaggard Yep, #30359 for the issue,  #30361 for the PR.

**Pull request merged**
