### PR TITLE
Remove System.Linq dependency from System.Console

### PR DESCRIPTION
**Pull request by stephentoub**
Fixes https://github.com/dotnet/coreclr/issues/3002#issuecomment-179349358
cc: @sergiy-k, @pallavit

### CODE REVIEW

**Comment by JonHanna** [comment]
And a little boost too from just using one loop :smile: 
LGTM

**Comment by pallavit** [comment]
LGTM. Thanks for fixing this :)

**Comment by justinvp** [comment]
> And a little boost too from just using one loop

And avoids the `KeyCollection` and enumerator allocations :smile:

**Comment by stephentoub** [comment]
Thanks.

**Pull request merged**
