### PR TITLE
Clean up the date helper in Utf8JsonReader

### PR DESCRIPTION
**Pull request by layomia**
Addresses feedback from https://github.com/dotnet/corefx/pull/39541.

### CODE REVIEW

**Comment by karelz** [comment]
Looks like one of the last PRs that made it to release/3.0 branch via last master->release/3.0 bulk integration. @wtgodbe can you please confirm?

**Comment by wtgodbe** [comment]
Yes, I cherry-picked this one manually.

**Comment by ahsonkhan** [comment]
> Yes, I cherry-picked this one manually.

Are you sure? Looks like this one was part of the bulk move of commits from master to release. As far as I can tell, there were just two commits that were manually cherry-picked.

**Comment by karelz** [comment]
Fixed in master (5.0) in PR #39638 and also in release/3.0 branch (3.0) in PR #39775.

**Comment by karelz** [comment]
@geoffkizer looks like there was a mistake in your PR description in #39638 and this was accidentally listed as one of the fixed issues. Which was the right issue number?

**Pull request merged**
