### PR TITLE
Add UAP AOT Helix tests to CI.

### PR DESCRIPTION
**Pull request by crummel**

### CODE REVIEW

**Comment by crummel** [comment]
@dotnet-bot test ci please
cc @ahsonkhan @joperezr Not too familiar with this part of CoreFX testing so let me know if anything looks off.

**Comment by crummel** [comment]
We plan to approach this another way - closing.

**Comment by joperezr** [comment]
We can't really do this because of a dependency package that we need to run the tests.

**Comment by joperezr** [comment]
Feel free to chat with me offline if you want more insights on why is doing this a bit tricky.

**Pull request closed without merging**
