### PR TITLE
Improve Enumerable.Reverse() performance

### PR DESCRIPTION
**Pull request by timandy**
- In sequence reverse, if the sequence is IList, we can enumerate the sequence backwards to improve performance and reduce memory allocation.

- In IEnumerable.Reverse().Reverse() case, we can return the source sequence direct to improve performance.

Here is the performance test case.
``` C#
    [MemoryDiagnoser]
    public class ReversePerfTest
    {
        private int[] data;

        [Params(0, 10, 100, 1000)]
        public int COUNT;


        [GlobalSetup]
        public void Setup()
        {
            data = new int[COUNT];
            for (int i = 0; i < COUNT; i++)
            {
                data[i] = i;
            }
        }

        [Benchmark]
        public int[] ReversePerf()
        {
            return data.ReversePerf().Skip(5).Take(10).ToArray();
        }

        [Benchmark(Baseline = true)]
        public int[] Reverse()
        {
            return data.Reverse().Skip(5).Take(10).ToArray();
        }
    }
```

Here is the result.
``` ini

BenchmarkDotNet=v0.11.5, OS=Windows 10.0.17134.765 (1803/April2018Update/Redstone4)
Intel Core i7-7500U CPU 2.70GHz (Kaby Lake), 1 CPU, 4 logical and 2 physical cores
Frequency=2835938 Hz, Resolution=352.6170 ns, Timer=TSC
  [Host]     : .NET Framework 4.7.2 (CLR 4.0.30319.42000), 32bit LegacyJIT-v4.7.3416.0
  DefaultJob : .NET Framework 4.7.2 (CLR 4.0.30319.42000), 32bit LegacyJIT-v4.7.3416.0


```
|      Method | COUNT |      Mean |      Error |     StdDev | Ratio |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|------------ |------ |----------:|-----------:|-----------:|------:|-------:|------:|------:|----------:|
| **ReversePerf** |     **0** |  **68.00 ns** |  **0.9577 ns** |  **0.8489 ns** |  **0.45** | **0.0151** |     **-** |     **-** |      **32 B** |
|     Reverse |     0 | 150.68 ns |  2.9447 ns |  2.7544 ns |  1.00 | 0.0474 |     - |     - |     100 B |
|             |       |           |            |            |       |        |       |       |           |
| **ReversePerf** |    **10** | **107.81 ns** |  **1.8778 ns** |  **1.5680 ns** |  **0.28** | **0.0457** |     **-** |     **-** |      **96 B** |
|     Reverse |    10 | 390.91 ns |  7.5755 ns |  7.0861 ns |  1.00 | 0.1216 |     - |     - |     256 B |
|             |       |           |            |            |       |        |       |       |           |
| **ReversePerf** |   **100** | **130.14 ns** |  **2.9506 ns** |  **4.4163 ns** |  **0.26** | **0.0703** |     **-** |     **-** |     **148 B** |
|     Reverse |   100 | 508.18 ns | 10.0186 ns | 13.7136 ns |  1.00 | 0.3233 |     - |     - |     680 B |
|             |       |           |            |            |       |        |       |       |           |
| **ReversePerf** |  **1000** | **131.47 ns** |  **2.5980 ns** |  **2.5516 ns** |  **0.17** | **0.0703** |     **-** |     **-** |     **148 B** |
|     Reverse |  1000 | 768.03 ns | 15.0081 ns | 20.5433 ns |  1.00 | 2.0399 |     - |     - |    4280 B |

### CODE REVIEW

**Comment by stephentoub** [comment]
Thanks.

Can you please share real-world examples where this makes a meaningful difference?  There are a huge number of possible optimizations that can be made in LINQ, but most of them (like this one) requires a non-trivial amount of additional code that has the potential to be buggy, needs to be maintained (and updated when further additional interacting optimizations come along), adds potentially significant runtime overheads in terms of additional generic instantiations, etc... so we're only proceeding to add such optimizations when they're really worth they're weight and when it can be demonstrated that they make a meaningful difference on real-world cases.

Also, have you tried this on collections where indexing isn't O(1)? e.g. have you tried your perf test with an `ImmutableList<T>`?

**Comment by timandy** [comment]
@stephentoub  I test the ImmutableList<T> by this code.
```C#
    [MemoryDiagnoser]
    public class ReverseImutableList
    {
        private IEnumerable<int> data;

        [Params(0, 10, 100, 1000)]
        public int COUNT;


        [GlobalSetup]
        public void Setup()
        {
            int[] tmp = new int[COUNT];
            for (int i = 0; i < COUNT; i++)
            {
                tmp[i] = i;
            }

            ImmutableList<int> list = ImmutableList<int>.Empty;
            data = list.AddRange(tmp);
        }

        [Benchmark]
        public int ReversePerf()
        {
            int sum = 0;
            foreach (int item in data.ReversePerf())
                sum += item;
            return sum;
        }

        [Benchmark(Baseline = true)]
        public int Reverse()
        {
            int sum = 0;
            foreach (int item in data.Reverse())
                sum += item;
            return sum;
        }
    }

```

And here is the test result
``` ini

BenchmarkDotNet=v0.11.5, OS=Windows 10.0.17134.860 (1803/April2018Update/Redstone4)
Intel Core i7-7500U CPU 2.70GHz (Kaby Lake), 1 CPU, 4 logical and 2 physical cores
Frequency=2835940 Hz, Resolution=352.6168 ns, Timer=TSC
  [Host]     : .NET Framework 4.7.2 (CLR 4.0.30319.42000), 32bit LegacyJIT-v4.7.3416.0
  DefaultJob : .NET Framework 4.7.2 (CLR 4.0.30319.42000), 32bit LegacyJIT-v4.7.3416.0


```
|      Method | COUNT |         Mean |        Error |       StdDev |       Median | Ratio | RatioSD |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|------------ |------ |-------------:|-------------:|-------------:|-------------:|------:|--------:|-------:|------:|------:|----------:|
| **ReversePerf** |     **0** |     **46.25 ns** |     **1.658 ns** |     **4.705 ns** |     **45.75 ns** |  **0.66** |    **0.08** | **0.0152** |     **-** |     **-** |      **32 B** |
|     Reverse |     0 |     70.85 ns |     2.420 ns |     6.745 ns |     70.06 ns |  1.00 |    0.00 | 0.0132 |     - |     - |      28 B |
|             |       |              |              |              |              |       |         |        |       |       |           |
| **ReversePerf** |    **10** |    **248.58 ns** |     **7.148 ns** |    **20.623 ns** |    **242.80 ns** |  **0.37** |    **0.05** | **0.0150** |     **-** |     **-** |      **32 B** |
|     Reverse |    10 |    673.63 ns |    21.889 ns |    64.198 ns |    659.91 ns |  1.00 |    0.00 | 0.0372 |     - |     - |      80 B |
|             |       |              |              |              |              |       |         |        |       |       |           |
| **ReversePerf** |   **100** |  **2,960.12 ns** |    **95.955 ns** |   **275.312 ns** |  **2,889.61 ns** |  **0.80** |    **0.08** | **0.0114** |     **-** |     **-** |      **32 B** |
|     Reverse |   100 |  3,714.60 ns |    73.544 ns |   105.475 ns |  3,685.10 ns |  1.00 |    0.00 | 0.2060 |     - |     - |     440 B |
|             |       |              |              |              |              |       |         |        |       |       |           |
| **ReversePerf** |  **1000** | **50,477.70 ns** |   **969.233 ns** | **1,077.300 ns** | **50,799.48 ns** |  **1.36** |    **0.08** |      **-** |     **-** |     **-** |      **32 B** |
|     Reverse |  1000 | 37,790.31 ns | 1,011.487 ns | 2,852.917 ns | 36,981.29 ns |  1.00 |    0.00 | 1.8921 |     - |     - |    4041 B |



ps: ListPartition also access IList by index, should be optimize?

**Comment by adamsitnik** [comment]
Hi @timandy 

Thank you for your PR!

> IEnumerable.Reverse().Reverse()

This is a performance anti-pattern, we should not be optimizing for such scenario

> DefaultJob : .NET Framework 4.7.2 (CLR 4.0.30319.42000), 32bit LegacyJIT-v4.7.3416.0

I can see that you've run the benchmarks for Full .NET Framework 4.7.2 **32bit**. Could you please run the benchmarks using a local build of CoreFX? [This](https://github.com/dotnet/performance/blob/master/docs/benchmarking-workflow-corefx.md#corefx-prerequisites) doc describes how to run the benchmarks for private build of CoreFX.

Once you build CoreFX in Release and have a copy of CoreRun stored in `$pathToCoreRun`

```cs
class Program
{
    static void Main(string[] args) 
          => BenchmarkSwitcher.FromAssembly(typeof(Program).Assembly).Run(args);
}
```

```cmd
dotnet run -c Release -f netcoreapp3.0 --filter * --corerun $pathToCoreRun
```

**Comment by timandy** [comment]
@adamsitnik 
I rerun the test case in .netcore 3.0 daily release.
For ImutableList.MoveNext() the performance are the same.
``` ini

BenchmarkDotNet=v0.11.5, OS=Windows 10.0.17134.915 (1803/April2018Update/Redstone4)
Intel Core i7-7500U CPU 2.70GHz (Kaby Lake), 1 CPU, 4 logical and 2 physical cores
Frequency=2835936 Hz, Resolution=352.6173 ns, Timer=TSC
.NET Core SDK=3.0.100-preview9-013639
  [Host]     : .NET Core 3.0.0-preview8-28379-12 (CoreCLR 4.700.19.37902, CoreFX 4.700.19.37903), 64bit RyuJIT
  DefaultJob : .NET Core 3.0.0-preview8-28379-12 (CoreCLR 4.700.19.37902, CoreFX 4.700.19.37903), 64bit RyuJIT


```
|      Method | COUNT |         Mean |         Error |       StdDev | Ratio | RatioSD |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|------------ |------ |-------------:|--------------:|-------------:|------:|--------:|-------:|------:|------:|----------:|
| **ReversePerf** |     **0** |     **61.41 ns** |     **1.2219 ns** |     **1.407 ns** |  **1.39** |    **0.05** | **0.0229** |     **-** |     **-** |      **48 B** |
|     Reverse |     0 |     44.29 ns |     0.8981 ns |     1.103 ns |  1.00 |    0.00 | 0.0229 |     - |     - |      48 B |
|             |       |              |               |              |       |         |        |       |       |           |
| **ReversePerf** |    **10** |    **858.60 ns** |    **16.3558 ns** |    **22.929 ns** |  **1.03** |    **0.03** | **0.0534** |     **-** |     **-** |     **112 B** |
|     Reverse |    10 |    834.16 ns |    16.4046 ns |    15.345 ns |  1.00 |    0.00 | 0.0534 |     - |     - |     112 B |
|             |       |              |               |              |       |         |        |       |       |           |
| **ReversePerf** |   **100** |  **6,436.50 ns** |   **125.5627 ns** |   **154.202 ns** |  **1.01** |    **0.03** | **0.2213** |     **-** |     **-** |     **472 B** |
|     Reverse |   100 |  6,403.05 ns |   123.7618 ns |   115.767 ns |  1.00 |    0.00 | 0.2213 |     - |     - |     472 B |
|             |       |              |               |              |       |         |        |       |       |           |
| **ReversePerf** |  **1000** | **64,645.04 ns** | **1,231.8871 ns** | **1,369.239 ns** |  **1.00** |    **0.03** | **1.8311** |     **-** |     **-** |    **4072 B** |
|     Reverse |  1000 | 65,014.23 ns | 1,277.5686 ns | 1,568.969 ns |  1.00 |    0.00 | 1.8311 |     - |     - |    4072 B |
----
I wrote an test case for List.MoveNext().
It allocate less memery in this case.
Like @stephentoub  said that, optimize `Reverse` should be carefully, Because it may take a lot of time to take care of the code which is rarely used.

```C#
    [MemoryDiagnoser]
    public class ReverseListPerf
    {
        private IEnumerable<int> data;

        [Params( 10, 100, 1000)]
        public int COUNT;


        [GlobalSetup]
        public void Setup()
        {
            int[] tmp = new int[COUNT];
            for (int i = 0; i < COUNT; i++)
            {
                tmp[i] = i;
            }
            data =  new List<int>(tmp);
        }

        [Benchmark]
        public int ReversePerf()
        {
            int sum = 0;
            foreach (int item in data.ReversePerf())
                sum += item;
            return sum;
        }

        [Benchmark(Baseline = true)]
        public int Reverse()
        {
            int sum = 0;
            foreach (int item in data.Reverse())
                sum += item;
            return sum;
        }
    }
```
``` ini

BenchmarkDotNet=v0.11.5, OS=Windows 10.0.17134.915 (1803/April2018Update/Redstone4)
Intel Core i7-7500U CPU 2.70GHz (Kaby Lake), 1 CPU, 4 logical and 2 physical cores
Frequency=2835936 Hz, Resolution=352.6173 ns, Timer=TSC
.NET Core SDK=3.0.100-preview9-013639
  [Host]     : .NET Core 3.0.0-preview8-28379-12 (CoreCLR 4.700.19.37902, CoreFX 4.700.19.37903), 64bit RyuJIT
  DefaultJob : .NET Core 3.0.0-preview8-28379-12 (CoreCLR 4.700.19.37902, CoreFX 4.700.19.37903), 64bit RyuJIT


```
|      Method | COUNT |        Mean |      Error |     StdDev | Ratio | RatioSD |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|------------ |------ |------------:|-----------:|-----------:|------:|--------:|-------:|------:|------:|----------:|
| **ReversePerf** |    **10** |    **84.14 ns** |   **1.559 ns** |   **1.382 ns** |  **0.74** |    **0.03** | **0.0191** |     **-** |     **-** |      **40 B** |
|     Reverse |    10 |   113.74 ns |   2.290 ns |   3.284 ns |  1.00 |    0.00 | 0.0535 |     - |     - |     112 B |
|             |       |             |            |            |       |         |        |       |       |           |
| **ReversePerf** |   **100** |   **541.82 ns** |  **10.759 ns** |  **11.049 ns** |  **0.85** |    **0.02** | **0.0191** |     **-** |     **-** |      **40 B** |
|     Reverse |   100 |   637.64 ns |  12.764 ns |  17.472 ns |  1.00 |    0.00 | 0.2251 |     - |     - |     472 B |
|             |       |             |            |            |       |         |        |       |       |           |
| **ReversePerf** |  **1000** | **5,140.63 ns** |  **98.329 ns** |  **91.977 ns** |  **0.94** |    **0.03** | **0.0153** |     **-** |     **-** |      **40 B** |
|     Reverse |  1000 | 5,454.46 ns | 112.245 ns | 115.268 ns |  1.00 |    0.00 | 1.9455 |     - |     - |    4072 B |

**Comment by timandy** [comment]
@stephentoub 
> Also, have you tried this on collections where indexing isn't O(1)? e.g. have you tried your perf test with an `ImmutableList<T>`?

I have tested ImmutableIList  index vs enumerator. 
The result is index is faster than enumertor.
When enumerating a IList, I think we should use the index first.
So in ListPartition access IList with index is the right choice.

    [CoreJob]
    public class ImmutableTest
    {
        private ImmutableList<int> data;

        [Params(10, 100, 1000)]
        public int length;

        [GlobalSetup]
        public void Init()
        {
            int[] a = new int[length];
            for (int i = 0; i < length; i++)
            {
                a[i] = i;
            }

            data = ImmutableList.Create(a);
        }

        [Benchmark]
        public int Enumerate()
        {
            int sum = 0;
            using (IEnumerator<int> e = data.GetEnumerator())
            {
                while (e.MoveNext())
                    sum += e.Current;
            }

            return sum;
        }

        [Benchmark]
        public int Index()
        {
            int sum = 0;
            ImmutableList<int> dataTmp = data;
            for (int i = 0, len = length; i < len; i++)
                sum += dataTmp[i];
            return sum;
        }
    }

``` ini

BenchmarkDotNet=v0.11.5, OS=Windows 10.0.17134.915 (1803/April2018Update/Redstone4)
Intel Core i7-7500U CPU 2.70GHz (Kaby Lake), 1 CPU, 4 logical and 2 physical cores
Frequency=2835936 Hz, Resolution=352.6173 ns, Timer=TSC
.NET Core SDK=3.0.100-preview9-013639
  [Host] : .NET Core 3.0.0-preview8-28379-12 (CoreCLR 4.700.19.37902, CoreFX 4.700.19.37903), 64bit RyuJIT
  Core   : .NET Core 3.0.0-preview8-28379-12 (CoreCLR 4.700.19.37902, CoreFX 4.700.19.37903), 64bit RyuJIT

Job=Core  Runtime=Core  

```
|    Method | length |         Mean |         Error |      StdDev |       Median |
|---------- |------- |-------------:|--------------:|------------:|-------------:|
| **Enumerate** |     **10** |    **765.37 ns** |    **19.3197 ns** |  **44.0007 ns** |    **749.31 ns** |
|     Index |     10 |     57.48 ns |     0.2901 ns |   0.2714 ns |     57.42 ns |
| **Enumerate** |    **100** |  **5,942.47 ns** |   **114.6102 ns** | **112.5626 ns** |  **5,888.50 ns** |
|     Index |    100 |    913.05 ns |     6.7702 ns |   6.3328 ns |    913.03 ns |
| **Enumerate** |   **1000** | **61,081.75 ns** | **1,053.8875 ns** | **985.8070 ns** | **61,197.05 ns** |
|     Index |   1000 | 35,324.18 ns |   168.3830 ns | 157.5056 ns | 35,301.03 ns |

**Comment by stephentoub** [comment]
@AArnott, do you have an example case where enumerating an `ImmutableList<T>` via its enumerator is measurably faster than enumerating it via its indexer?  I get that the enumerator leads to O(N) time and the indexer leads to O(N log N) time, but it appears the overheads associated with the enumerator are so high that it requires a really big data set for them to cross-over, e.g. a list with 10M elements appears to be around the break even point, and even at 100M they're fairly comparable on my machine.  I'm wondering whether that's actually the right trade-off.

**Comment by AArnott** [comment]
@stephentoub I do not have any stock repro for the perf I was expecting. There may have been some actual cases in VS that we saw, but if you're seeing the indexer be pretty consistently faster than enumerating, I'm surprised, but don't object to you making a data-based decision over a theory based one. :)

**Comment by stephentoub** [comment]
@timandy, thanks again for your interest in contributing here.

I took another look at this.  These changes are adding a significant amount of code.  That not only adds a maintenance burden, but also has a non-trivial impact on other performance-related aspects, such as size.  In fact, this one PR increases the size of System.Linq.dll by ~10%.  That's a lot of IL.  It also adds a non-trivial number of generic types that could mean a significant amount of additional assembly code generated as part of generic instantiations wherever Reverse is used.  And in looking through various code bases that use LINQ, related to my question at https://github.com/dotnet/corefx/pull/39356#issuecomment-510074624, I'm not seeing enough real-world cases where performance improvements in Reverse would make a significant enough difference to warrant these costs, especially since the majority of the cases I saw were on relatively small inputs.

Given all that, I'm going to close this.  If you can demonstrate that there are important cases where improving the performance of Reverse will make a meaningful difference in real applications, we can revisit it.

Thanks, again.

**Comment by timandy** [comment]
@stephentoub Thanks for your response. Agree with your opinion.

**Pull request closed without merging**
