### PR TITLE
Remove unnecessary string allocation from ZipFileUtils

### PR DESCRIPTION
**Pull request by stephentoub**
cc: @carlossanlop, @ahsonkhan, @ViktorHofer

### CODE REVIEW

**Comment by ViktorHofer** [comment]
I'm wondering, isn't a path separator (both the Unix and Windows variant) a perfect candidate for caching in the CLR similar to what you did with some numbers?

**Comment by stephentoub** [comment]
With numbers we already had to go down a formatting path that has a ton of logic, requires checking the current culture, requires looking at formatting options, required checking things like how long the number would be once formatted, etc., so adding in a special-path for a length of 1 added unmeasurable overhead.  With char.ToString(), all it does is:
```C#
string result = FastAllocateString(1);
result._firstChar = c;
return result;
```
I don't think it's worth adding in a special path for certain characters.

**Comment by danmosemsft** [comment]
>  similar to what you did with some numbers?

I didn't see that - what change? Just curious

**Comment by ViktorHofer** [comment]
`corefx-ci (Linux arm64_Release)` is failing probably because of transient errors with the queue.
`corefx-ci (Windows x64_Debug)` is failing becuase of a flaky test: `PerformanceCounter_NextValue_ProcessorCounter`. Commented in https://github.com/dotnet/corefx/issues/29377

**Comment by stephentoub** [comment]
> I didn't see that - what change? Just curious

https://github.com/dotnet/coreclr/pull/18383

**Pull request merged**
