### PR TITLE
Enable BeginExecuteNonQuery functions in .NET Core

### PR DESCRIPTION
**Pull request by LotharOfTheHillPeople**
Make public previously private BeginExecuteNonQuery and related functions. Add basic functional tests.

### CODE REVIEW

**Comment by karelz** [comment]
This is exposing APIs which are available on .NET Framework (see https://apisof.net/catalog/System.Data.SqlClient.SqlCommand).
While we do not need formal API review for those, we need explicit ack from area experts/owners (@saurabh500 @corivera @divega). I assume there was some reason why these APIs were left behind in .NET Core / .NET Standard 2.0.

Marking as blocked for now.

**Comment by saurabh500** [comment]
@karelz we will take this PR.
@LotharOfTheHillPeople is a colleague  and will be starting with System.data.SqlClient from now on.
He is working on exposing this API to get familiar with the dev process.

**Comment by saurabh500** [comment]
Also these were left behind because of lack to time and focus on other high priority items.

**Comment by karelz** [comment]
Ah, welcome on board @LotharOfTheHillPeople - you should associate yourself with Microsoft and dotnet organizations, I'll ping you offline with instructions.

**Comment by karelz** [comment]
Hmmm, @LotharOfTheHillPeople I don't even know your name (also something to fix :)) - can you ping me via email to send you the instructions?

**Pull request merged**
