### PR TITLE
Adding support for /m in non-Windows builds

### PR DESCRIPTION
**Pull request by joperezr**
This new buildtools contains a .Net Core MSBuild version that supports /m, so this PR updates to it and then it uses it in non-Windows builds. Additionally this also fixes the dependency warnings that were thrown when running init-tools

cc: @weshaggard 
FYI: @stephentoub @dsplaisted 

Fixes: #7079

### CODE REVIEW

**Comment by mellinoe** [comment]
@dotnet-bot test outerloop Ubuntu14.04 debug

**Comment by mellinoe** [comment]
The outerlooop run will almost certainly fail (pre-existing issues), but I'd like to see what the output is regardless.

**Comment by joperezr** [comment]
@dotnet-bot test Innerloop OSX Debug Build and Test please

**Comment by joperezr** [comment]
@mellinoe 
> The outerlooop run will almost certainly fail (pre-existing issues), but I'd like to see what the output is regardless.

Just as FYI, in my OSX machine(8 cores) I saw a performance improvement from ~ 1 hour and 20 minutes, to ~ 20 minutes. This is counting tests, but without counting package restore.

**Comment by mellinoe** [comment]
Very nice. That seems to be fast enough to start running in the inner-loop builds, but I guess we'd have to see just how much slower it is on the machines/VM's we're using in Jenkins. We will also probably want to wait until the CI is a bit more stable before we make the jump :smile:

**Comment by joperezr** [comment]
Right, the idea is to frist move Outerloop only to this, and once it is stable enough then move the CI as well.

**Comment by weshaggard** [comment]
LGTM once tests are green. We definitely do want to enable the CI for inner loop once this we get some coverage in outerloop runs.

**Pull request merged**
