### PR TITLE
Fix typo.

### PR DESCRIPTION
**Pull request by jacobcarpenter**

### CODE REVIEW

**Comment by mmitche** [comment]
Can one of the admins verify this patch?

**Comment by mmitche** [comment]
Can one of the admins verify this patch?

**Comment by mellinoe** [comment]
Looks good two me.

**Comment by jacobcarpenter** [comment]
Lol.

**Comment by weshaggard** [comment]
ok to test

**Comment by weshaggard** [comment]
LGTM Once our new CI system comes back clean I will merge.

**Pull request merged**
