### PR TITLE
Update CoreFx dependencies to beta-24623-01

### PR DESCRIPTION
**Pull request by stephentoub**

### CODE REVIEW

**Comment by stephentoub** [comment]
@JeremyKuhne, it looks like your changes to FileStream broke IsolateStorage:
```
System.IO.IsolatedStorage.Tests  Total: 255, Errors: 0, Failed: 94, Skipped: 0
```
e.g. 
```
System.IO.IsolatedStorage.RemoveTests.RemoveStoreWithContent(scope: MachineStoreForDomain) [FAIL]
        System.NullReferenceException : Object reference not set to an instance of an object.
        Stack Trace:
              at System.IO.IsolatedStorage.IsolatedStorageFileStream.get_CanRead()
              at System.IO.FileStream.VerifyHandleIsSync()
              at System.IO.FileStream.InitFromHandle(SafeFileHandle handle)
              at System.IO.FileStream..ctor(SafeFileHandle handle, FileAccess access, Int32 bufferSize, Boolean isAsync)
              at System.IO.FileStream..ctor(SafeFileHandle handle, FileAccess access, Int32 bufferSize)
              at System.IO.IsolatedStorage.IsolatedStorageFileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, InitialiationData initializationData)
              at System.IO.IsolatedStorage.IsolatedStorageFileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, IsolatedStorageFile isf)
              at System.IO.IsolatedStorage.IsolatedStorageFileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, IsolatedStorageFile isf)
              at System.IO.IsolatedStorage.IsolatedStorageFile.CreateFile(String path)
           D:\j\workspace\windows_nt_de---4526f5ff\src\System.IO.IsolatedStorage\tests\System\IO\IsolatedStorage\RemoveTests.cs(66,0): at System.IO.IsolatedStorage.RemoveTests.RemoveStoreWithContent(PresetScopes scope)
     System.IO.IsolatedStorage.RemoveTests.RemoveUserStoreForAssembly [FAIL]
```
IsolatedStorageFileStream's ctor delegates to the base FileStream's ctor, which ends up calling the virtual CanRead on IsolatedStorageFileStream, which tries to dereference its ```_fs``` field, which hasn't been initialized yet.

**Comment by stephentoub** [comment]
@JeremyKuhne, for a similar reason, your changes also broke IsolatedStorageStream on Unix, with CanSeek being called from InitFromHandle:
```
System.IO.IsolatedStorage.CopyFileTests.CopyFile_CopyOver(scope: UserStoreForApplication) [FAIL]
        System.NullReferenceException : Object reference not set to an instance of an object.
        Stack Trace:
              at System.IO.IsolatedStorage.IsolatedStorageFileStream.get_CanSeek()
              at System.IO.FileStream.InitFromHandle(SafeFileHandle handle)
              at System.IO.FileStream..ctor(SafeFileHandle handle, FileAccess access, Int32 bufferSize, Boolean isAsync)
              at System.IO.FileStream..ctor(SafeFileHandle handle, FileAccess access, Int32 bufferSize)
              at System.IO.IsolatedStorage.IsolatedStorageFileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, InitialiationData initializationData)
              at System.IO.IsolatedStorage.IsolatedStorageFileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, IsolatedStorageFile isf)
              at System.IO.IsolatedStorage.IsolatedStorageFileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, IsolatedStorageFile isf)
              at System.IO.IsolatedStorage.IsolatedStorageFile.CreateFile(String path)
           /mnt/j/workspace/dotnet_corefx/master/ubuntu14.04_debug_prtest/src/System.IO.IsolatedStorage/tests/System/IO/IsolatedStorage/TestHelper.cs(67,0): at System.IO.IsolatedStorage.TestHelper.CreateTestFile(IsolatedStorageFile isf, String fileName, String content)
           /mnt/j/workspace/dotnet_corefx/master/ubuntu14.04_debug_prtest/src/System.IO.IsolatedStorage/tests/System/IO/IsolatedStorage/CopyFileTests.cs(92,0): at System.IO.IsolatedStorage.CopyFileTests.CopyFile_CopyOver(PresetScopes scope)
```

**Comment by stephentoub** [comment]
@dotnet-bot Test Innerloop Ubuntu14.04 Debug Build and Test please (package restore failure)
@dotnet-bot Test Innerloop Ubuntu14.04 Release Build and Test please (package restore failure)

**Comment by stephentoub** [comment]
@dotnet-bot Test Innerloop Ubuntu14.04 Release and Test (package restore failure)
@dotnet-bot Test Innerloop Linux ARM Emulator Release Cross Build (package restore failure)

**Comment by stephentoub** [comment]
@dotnet-bot Test Innerloop Ubuntu14.04 Release Build and Test (package restore failure)

**Comment by stephentoub** [comment]
@dotnet-bot Test Outerloop Windows_NT Debug please
@dotnet-bot Test Outerloop Ubuntu14.04 Debug please

**Comment by stephentoub** [comment]
@dotnet-bot Test Outerloop Windows_NT Debug please (https://github.com/dotnet/corefx/issues/12939)

**Comment by stephentoub** [comment]
@JeremyKuhne, I've fixed the FileStream failures.  Once CI completes, I'm going to merge this, so as to unblock getting packages updated and keeping things flowing.  If we're not happy with the fix I put in place (which basically restores how those pieces previously behaved), we can update it subsequently.

cc: @weshaggard, @joperezr, just FYI that I put a few additional fixes in place, adding an entry to a project.json and suppressing some API compat warnings.

**Comment by joperezr** [comment]
>suppressing some API compat warnings.

In general, when updating versions cause new API compat warnings, it is usually because ref is using latest version of the packages but the implementation is not for a specific package, so I think in those cases is better to fix them by adding entries on the project.json instead of baselining the errors. I'll take care of the ones that were done here.

**Comment by stephentoub** [comment]
>  so I think in those cases is better to fix them by adding entries on the project.json instead of baselining the errors

Not sure I understand.  Most of these were due to MarshalByRefObject not existing as a base type in uap101aot.  What do we add to the project.json to fix that, and why don't we just do that across the board rather than baselining as we have been?

**Comment by joperezr** [comment]
The ones for uap101aot are fine, since to fix them we would have to fix the .NetNative package, but the one for System.Net.Sockets for example, that one is not for uap101aot, so that one would get fixed by simply updating the version of System.Runtime that is used by the implementation.

**Pull request merged**
