### PR TITLE
[NOMERGE] Testing some CI changes

### PR DESCRIPTION
**Pull request by ianhays**
Not aware of a better way to test ci changes besides doing a `test ci` run.

### CODE REVIEW

**Comment by ianhays** [comment]
@dotnet-bot test ci

**Comment by ianhays** [comment]
@dotnet-bot test ci please

**Comment by ianhays** [comment]
Hey @MattGal do the opensuse423 machines have Java installed on them?

[I generated a job](https://ci.dot.net/job/dotnet_corefx/job/release_1.0.0/job/GenPRTest/job/opensuse42.3_debug/) using the [OpenSuse.423.Amd64.Open](https://ci.dot.net/label/OpenSuse.423.Amd64.Open/) label but it seems to be having issues actually connecting to the machines that it is spinning up.

I also tried out [the Fedora27 queue, but I'm seeing directory creation errors which makes me think there's a permissions issue.](https://ci.dot.net/job/dotnet_corefx/job/release_1.0.0/job/GenPRTest/job/fedora27_debug/1/) I recall @mmitche mentioning the Jenkins Linux images having some extra setup step that was necessary but I don't remember what we're missing.

**Comment by MattGal** [comment]
@ianhays no, we had not been using the OpenSuse open queues for build (just portable test execution) so Java is not on them by default.  It's not difficult to add, please open a FR ticket in core-eng about it.

**Comment by ianhays** [comment]
Ah that explains it then, thanks Matt. I'll wait to open the issue until we determine the cause of the Fedora permissions failures, as those would also presumably be present on OpenSuse as well if it had java.

**Comment by ianhays** [comment]
@dotnet-bot test ci

**Comment by ianhays** [comment]
@dotnet-bot test ci please

**Comment by ianhays** [comment]
Opened https://github.com/dotnet/core-eng/issues/2688 for the opensuse jenkins loading.

**Comment by ianhays** [comment]
Update: The Fedora27 testing works! Thanks @MattGal and @mmitche for the assistance.

It of course fails package restoration because we don't have any packages for Fedora27 built, but that's the next step :)

**Comment by MattGal** [comment]
Nice!  I've applied the workspace path fix to all .Open queues we have right now, and fixed the ARM templates for the rest.

**Comment by stephentoub** [comment]
@ianhays, can this be closed?

**Pull request closed without merging**
