### PR TITLE
Interpret ListInitExpression with non-void Add methods correctly.

### LINKED ISSUE #5945: ListInitExpression with non-void Add method fails with interpreter
An expression of the form `() => new HashSet<int>{ 1, 2, 3}` works fine with the compiler, but fails with the interpreter with a `TargetException` (or an assertion failure in debug), or possibly some other bad things with variants of this.

The interpreter is assuming that `Add()` methods return void, so doesn't deal with the value pushed to the stack by a method like `HashSet<int>.Add()` that returns `bool`

cc @VSadov @bartdesmet .

### PR DESCRIPTION
**Pull request by JonHanna**
Fixes #5945

Also add List Initialization Expression Tests beyond those needed
to verify this fix.

cc: @stephentoub @VSadov @bartdesmet

### CODE REVIEW

**Comment by JonHanna** [comment]
Test Innerloop OSX Debug Build and Test please

**Comment by JonHanna** [comment]
Test Innerloop OSX Debug Build and Test please

**Comment by VSadov** [comment]
LGTM 
Good catch. Should pop after Add if Add is nonvoid.

**Comment by bartdesmet** [comment]
LGTM

**Pull request merged**
