### PR TITLE
Revert "Implement cancellation token for SslStream new AuthenticateAs*Async methods"

### PR DESCRIPTION
**Pull request by stephentoub**
Reverts dotnet/corefx#24857

Per investigation in https://github.com/dotnet/corefx/pull/25199, https://github.com/dotnet/corefx/pull/25198
cc: @Priya91

### CODE REVIEW

**Comment by stephentoub** [comment]
@dotnet-bot test Linux x64 Debug Build please

**Comment by Drawaes** [comment]
@dotnet-bot test Linux arm Release Build please

This seems to fail before doing anything ".net" related sometimes with an IO timeout setting up the container.

**Comment by benaadams** [comment]
@dotnet-bot test Outerloop Linux x64 Release Build please

**Comment by stephentoub** [comment]
test Outerloop Linux x64 Debug Build please

**Comment by stephentoub** [comment]
@dotnet-bot test Windows x64 Debug Build please (https://github.com/dotnet/corefx/issues/24874#issuecomment-343753418)

**Pull request merged**
