### PR TITLE
Update build to use DNX beta7 instead of beta5

### LINKED ISSUE #3173: Fails to build on FreeBSD due to using outdated dnx-beta5
Currently CoreFX cannot be build on FreeBSD, because it uses an old version of dnx with hard coded path to bash. CoreFX uses dnx-mono.1.0.0-beta5-12101. This has been fixed in dnx since then. Can we upgrade dnx to the most recent version to fix this issue?

I was trying to create a PR for this, but I do not find where the dnx version is defined. So it would be helpful of someone else can bump the dnx version.

### PR DESCRIPTION
**Pull request by akoeplinger**
The corefx build used an older beta5 version of DNX which hardcoded the path to bash in dnu, breaking the build on FreeBSD.
Updating DNX to the latest "stable" beta7 release fixes this.

After updating I noticed a few test projects didn't build anymore as they were missing some dependencies in project.json, added those.

Fixes #3173

/cc @ericstj

### CODE REVIEW

**Comment by akoeplinger** [comment]
Hmm, looks like this breaks something on Windows:

```
Unhandled Exception: System.IO.FileNotFoundException: Could not load file or assembly 'System.Console, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
     at Xunit.ConsoleClient.Program.Main(String[] args)
d:\j\workspace\dotnet_corefx_windows_debug_prtest\packages\Microsoft.DotNet.BuildTools.1.0.25-prerelease-00085\lib\tests.targets(130,5): warning MSB3073: The command "CoreRun.exe xunit.console.netcore.exe Common.Tests.dll  -xml testResults.xml -notrait category=nonwindowstests  -notrait category=OuterLoop -notrait category=failing " exited with code -532462766. 
```

**Comment by jasonwilliams200OK** [comment]
`OuterLoop` tests; perhaps it has something to do with https://github.com/dotnet/corefx/issues/3166?

**Comment by jasonwilliams200OK** [comment]
Shall we try one more time?
@dotnet-bot, test this please.

**Comment by akoeplinger** [comment]
@jasonwilliams200OK no, those aren't OuterLoop tests (-notrait). I see the same failures on my Windows box, investigating.

**Comment by mellinoe** [comment]
That sort of looks like an issue @joperezr was hitting on some local builds. For whatever reason, System.Console was not being restored by dnu, despite being clearly listed in the project.json and project.lock.json files. Not sure if it's the exact same issue, but it looks similar.

**Comment by jasonwilliams200OK** [comment]
@dotnet-bot, test this please!

**Comment by akoeplinger** [comment]
@mellinoe I think there's a little bit more going on, here's are the files that are missing in one of the test folders after the change, there's a lot more stuff missing:

```diff
- API-MS-Win-Base-Util-L1-1-0.dll
- api-ms-win-core-com-l1-1-0.dll
- api-ms-win-core-com-private-l1-1-0.dll
- api-ms-win-core-comm-l1-1-0.dll
- api-ms-win-core-console-l1-1-0.dll
- api-ms-win-core-console-l2-1-0.dll
- api-ms-win-core-datetime-l1-1-0.dll
- api-ms-win-core-datetime-l1-1-1.dll
- api-ms-win-core-debug-l1-1-0.dll
- api-ms-win-core-debug-l1-1-1.dll
- api-ms-win-core-delayload-l1-1-0.dll
- api-ms-win-core-errorhandling-l1-1-0.dll
- api-ms-win-core-errorhandling-l1-1-1.dll
- api-ms-win-core-fibers-l1-1-0.dll
- api-ms-win-core-fibers-l1-1-1.dll
- api-ms-win-core-file-l1-1-0.dll
- api-ms-win-core-file-l1-2-0.dll
- api-ms-win-core-file-l1-2-1.dll
- api-ms-win-core-file-l2-1-0.dll
- api-ms-win-core-file-l2-1-1.dll
- api-ms-win-core-handle-l1-1-0.dll
- api-ms-win-core-heap-l1-1-0.dll
- api-ms-win-core-heap-obsolete-l1-1-0.dll
- api-ms-win-core-interlocked-l1-1-0.dll
- api-ms-win-core-io-l1-1-0.dll
- api-ms-win-core-io-l1-1-1.dll
- api-ms-win-core-kernel32-legacy-l1-1-0.dll
- api-ms-win-core-kernel32-legacy-l1-1-1.dll
- api-ms-win-core-kernel32-legacy-l1-1-2.dll
- API-MS-Win-Core-Kernel32-Private-L1-1-0.dll
- API-MS-Win-Core-Kernel32-Private-L1-1-1.dll
- API-MS-Win-Core-Kernel32-Private-L1-1-2.dll
- api-ms-win-core-libraryloader-l1-1-0.dll
- api-ms-win-core-libraryloader-l1-1-1.dll
- api-ms-win-core-localization-l1-2-0.dll
- api-ms-win-core-localization-l1-2-1.dll
- api-ms-win-core-localization-l2-1-0.dll
- api-ms-win-core-localization-obsolete-l1-2-0.dll
- api-ms-win-core-memory-l1-1-0.dll
- api-ms-win-core-memory-l1-1-1.dll
- api-ms-win-core-memory-l1-1-2.dll
- api-ms-win-core-memory-l1-1-3.dll
- api-ms-win-core-namedpipe-l1-1-0.dll
- api-ms-win-core-namedpipe-l1-2-1.dll
- api-ms-win-core-normalization-l1-1-0.dll
- API-MS-Win-Core-PrivateProfile-L1-1-0.dll
- api-ms-win-core-privateprofile-l1-1-1.dll
- api-ms-win-core-processenvironment-l1-1-0.dll
- api-ms-win-core-processenvironment-l1-2-0.dll
- api-ms-win-core-processsecurity-l1-1-0.dll
- api-ms-win-core-processthreads-l1-1-0.dll
- api-ms-win-core-processthreads-l1-1-1.dll
- api-ms-win-core-processthreads-l1-1-2.dll
- API-MS-Win-Core-ProcessTopology-Obsolete-L1-1-0.dll
- api-ms-win-core-profile-l1-1-0.dll
- api-ms-win-core-psapi-ansi-l1-1-0.dll
- api-ms-win-core-psapi-l1-1-0.dll
- api-ms-win-core-psapi-obsolete-l1-1-0.dll
- api-ms-win-core-realtime-l1-1-0.dll
- api-ms-win-core-registry-l1-1-0.dll
- api-ms-win-core-registry-l2-1-0.dll
- api-ms-win-core-rtlsupport-l1-1-0.dll
- api-ms-win-core-shlwapi-legacy-l1-1-0.dll
- api-ms-win-core-shlwapi-obsolete-l1-1-0.dll
- api-ms-win-core-shutdown-l1-1-0.dll
- api-ms-win-core-shutdown-l1-1-1.dll
- api-ms-win-core-string-l1-1-0.dll
- API-MS-Win-Core-String-L2-1-0.dll
- api-ms-win-core-string-obsolete-l1-1-0.dll
- api-ms-win-core-string-obsolete-l1-1-1.dll
- API-MS-Win-Core-StringAnsi-L1-1-0.dll
- api-ms-win-core-stringloader-l1-1-0.dll
- api-ms-win-core-stringloader-l1-1-1.dll
- api-ms-win-core-synch-l1-1-0.dll
- api-ms-win-core-synch-l1-2-0.dll
- api-ms-win-core-sysinfo-l1-1-0.dll
- api-ms-win-core-sysinfo-l1-2-0.dll
- api-ms-win-core-sysinfo-l1-2-1.dll
- api-ms-win-core-sysinfo-l1-2-2.dll
- api-ms-win-core-sysinfo-l1-2-3.dll
- api-ms-win-core-threadpool-l1-2-0.dll
- api-ms-win-core-threadpool-legacy-l1-1-0.dll
- api-ms-win-core-threadpool-private-l1-1-0.dll
- api-ms-win-core-timezone-l1-1-0.dll
- api-ms-win-core-url-l1-1-0.dll
- api-ms-win-core-util-l1-1-0.dll
- api-ms-win-core-version-l1-1-0.dll
- api-ms-win-core-winrt-error-l1-1-0.dll
- api-ms-win-core-winrt-error-l1-1-1.dll
- api-ms-win-core-winrt-l1-1-0.dll
- api-ms-win-core-winrt-registration-l1-1-0.dll
- api-ms-win-core-winrt-robuffer-l1-1-0.dll
- api-ms-win-core-winrt-roparameterizediid-l1-1-0.dll
- api-ms-win-core-winrt-string-l1-1-0.dll
- api-ms-win-core-wow64-l1-1-0.dll
- api-ms-win-core-xstate-l1-1-0.dll
- api-ms-win-core-xstate-l2-1-0.dll
- API-MS-Win-devices-config-L1-1-0.dll
- API-MS-Win-devices-config-L1-1-1.dll
- API-MS-Win-Eventing-ClassicProvider-L1-1-0.dll
- API-MS-Win-Eventing-Consumer-L1-1-0.dll
- API-MS-Win-Eventing-Controller-L1-1-0.dll
- API-MS-Win-Eventing-Legacy-L1-1-0.dll
- API-MS-Win-Eventing-Provider-L1-1-0.dll
- API-MS-Win-EventLog-Legacy-L1-1-0.dll
- api-ms-win-ro-typeresolution-l1-1-0.dll
- api-ms-win-security-base-l1-1-0.dll
- api-ms-win-security-cpwl-l1-1-0.dll
- api-ms-win-security-cryptoapi-l1-1-0.dll
- api-ms-win-security-lsalookup-l2-1-0.dll
- api-ms-win-security-lsalookup-l2-1-1.dll
- API-MS-Win-Security-LsaPolicy-L1-1-0.dll
- api-ms-win-security-provider-l1-1-0.dll
- api-ms-win-security-sddl-l1-1-0.dll
- api-ms-win-service-core-l1-1-0.dll
- api-ms-win-service-core-l1-1-1.dll
- api-ms-win-service-management-l1-1-0.dll
- api-ms-win-service-management-l2-1-0.dll
- api-ms-win-service-private-l1-1-0.dll
- api-ms-win-service-private-l1-1-1.dll
- api-ms-win-service-winsvc-l1-1-0.dll
- clretwrc.dll
- coreclr.dll
  CoreRun.exe
- dbgshim.dll
- ext-ms-win-advapi32-encryptedfile-l1-1-0.dll
- mscordaccore.dll
- mscordbi.dll
- mscorlib.ni.dll
- mscorrc.debug.dll
- mscorrc.dll
  System.Collections.Concurrent.dll
  System.Collections.dll
  System.ComponentModel.dll
  System.ComponentModel.pdb
  System.ComponentModel.Tests.dll
  System.ComponentModel.Tests.pdb
- System.Console.dll
  System.Diagnostics.Contracts.dll
  System.Diagnostics.Debug.dll
  System.Diagnostics.StackTrace.dll
  System.Diagnostics.Tools.dll
  System.Diagnostics.Tracing.dll
  System.Globalization.Calendars.dll
  System.Globalization.dll
  System.IO.dll
  System.IO.FileSystem.dll
  System.IO.FileSystem.Primitives.dll
  System.Linq.dll
  System.ObjectModel.dll
  System.Private.Uri.dll
  System.Reflection.dll
  System.Reflection.Extensions.dll
  System.Reflection.Primitives.dll
  System.Resources.ResourceManager.dll
  System.Runtime.dll
  System.Runtime.Extensions.dll
  System.Runtime.Handles.dll
  System.Runtime.InteropServices.dll
  System.Runtime.InteropServices.RuntimeInformation.dll
  System.Text.Encoding.dll
  System.Text.Encoding.Extensions.dll
  System.Text.RegularExpressions.dll
  System.Threading.dll
  System.Threading.Overlapped.dll
  System.Threading.Tasks.dll
  System.Threading.Thread.dll
  System.Threading.ThreadPool.dll
- System.Threading.Timer.dll
  System.Xml.ReaderWriter.dll
  System.Xml.XDocument.dll
  xunit.abstractions.dll
  xunit.assert.dll
  xunit.console.netcore.exe
  xunit.core.dll
  xunit.execution.dnx.dll
  Xunit.NetCore.Extensions.dll
  xunit.runner.utility.dnx.dll
```

**Comment by weshaggard** [comment]
I believe you are hitting this because the test runtime lock file is being updated and the latest version of the system.console package needs an update to the project.json file for the test runtime. See my recent commit in buildtools (sorry I'm on my phone or I would point you to it).

**Comment by akoeplinger** [comment]
@weshaggard thanks, that was it, works with that change. Waiting on a bump of the buildtools package then :)

**Comment by joshfree** [comment]
cc: @mellinoe

**Comment by weshaggard** [comment]
I'm trying to finish up my open PR in the buildtools repo once that is done I will get an updated build tools packages published and into corefx.

**Comment by weshaggard** [comment]
@akoeplinger change https://github.com/dotnet/corefx/pull/3259#issuecomment-140581653 updated the build tools so please fix the conflicts in your PR and try again. Hopefully this will now work.

**Comment by akoeplinger** [comment]
@weshaggard done

**Comment by weshaggard** [comment]
@dotnet-bot test this please

**Comment by jasonwilliams200OK** [comment]
Failing with a funny+verbose exception message:
http://dotnet-ci.cloudapp.net/job/dotnet_corefx_windows_debug_prtest/3905/testReport/junit/System.Diagnostics.ProcessTests/ProcessStartInfoTests/TestEnvironmentOfChildProcess/ :smile:

**Comment by weshaggard** [comment]
@dotnet-bot test this please

**Comment by jasonwilliams200OK** [comment]
it's green! :white_check_mark:

**Comment by weshaggard** [comment]
LGTM thanks @akoeplinger 

I also build and spot checked these lock file updates locally and they appear to be OK.

**Pull request merged**
