### PR TITLE
Remove ILLinkTrim.xml from System.Data.Common

### PR DESCRIPTION
**Pull request by stephentoub**
All use of PreserveDependencyAttribute should be removable when https://github.com/mono/linker/issues/800 is fixed.
cc: @marek-safar, @roji

### CODE REVIEW

**Comment by khellang** [comment]
I just rebased https://github.com/dotnet/corefx/pull/41940 all builds ended up breaking. The [error](https://dev.azure.com/dnceng/public/_build/results?buildId=404894&view=results) seems related to this PR:

> ##[error]CSC(0,0): error CS2001: Source file 'D:\a\1\s\src\Common\src\System\Runtime\CompilerServices\PreserveDependencyAttribute.cs' could not be found.

Is there anything I need to do to get everything building?

**Comment by stephentoub** [comment]
Shoot, this crossed with another PR in CI; I forgot a file got moved when I merged both. I'll fix it.

**Comment by stephentoub** [comment]
Try now.

**Comment by khellang** [comment]
Yeah, that'll probably fix it. Thanks! 😘

**Pull request merged**
