### PR TITLE
Extract duplicated code

### PR DESCRIPTION
**Pull request by Dmitry-Me**
This resolves https://github.com/dotnet/corefx/issues/5452

### CODE REVIEW

**Comment by stephentoub** [comment]
LGTM

cc: @saurabh500

**Comment by JonHanna** [comment]
:+1:

**Comment by saurabh500** [comment]
LGTM I will merge it when checks complete.

**Comment by saurabh500** [comment]
@dotnet-bot Test Innerloop CentOS7.1 Debug Build and Test please

**Pull request merged**
