### PR TITLE
Use NativeLibrary APIs in .NET Core 3 and above

### PR DESCRIPTION
**Pull request by am11**
Windows part of #34633; replacing `LoadLibrary[Ex]` calls with `NativeLibrary.[Try]Load` managed APIs.

### CODE REVIEW

**Comment by am11** [comment]
@jkotas, @safern, I have created as draft because `./build.cmd -allconfigurations` is failing and I couldn't figure out best way to fix them.

sometimes because for .NET Core 2.1, there is no constant defined (like `netcoreapp21`):

> System\Data\SqlClient\LocalDBAPI.Windows.cs(19,13): error CS0103: The name 'NativeLibrary' does not exist in the current context [C:\Users\adeel\Source\Repos\corefx\src\System.Data.SqlClien
t\src\System.Data.SqlClient.csproj]

and sometimes with APICompat failure (netfx as well as netcoreapp configurations), e.g.:

> C:\Users\adeel\.nuget\packages\microsoft.dotnet.apicompat\1.0.0-beta.19218.7\build\Microsoft.DotNet.ApiCompat.targets(85,5): error : ApiCompat failed for 'C:\Users\adeel\Source\Repos\corefx\artifacts\bin\System.ServiceModel.Syndication\netfx-Windows_NT-Debug\System.ServiceModel.Syndication.dll' [C:\Users\adeel\Source\Repos\corefx\src\System.ServiceModel.Syndication\src\System.ServiceModel.Syndication.csproj]

Can you provide some suggestions how to fix these? :)

**Comment by jkotas** [comment]
I do not think there is much value in replacing calls to LoadLibrary in Windows-specific code with the platform-neutral ones. I would do it only if it makes the code simpler. None of the cases in your delta makes the code simpler.

**Comment by am11** [comment]
I had this branch going alongside https://github.com/dotnet/corefx/pull/36944, to streamline library loading mechanics. In case of Unix, we were not `dlclose`ing/freeing the library, but Windows usages have safe handle disposes, which makes it spaghetti with `NativeLibrary.Free` calls in `finally`s and finalizers.

As a guiding principle for new code, should we continue P/Invoking `LoadLibrary[Ex]` on Windows or favor `NativeLibrary.[Try]Load` (because later is a managed API)?

**Comment by jkotas** [comment]
> As a guiding principle for new code

I would use the option that makes the code simpler. There are number of factors to consider: Is the new code for netcoreapp3.0+, or does it need to run on older profiles too? Is the new code Windows specific?

**Pull request closed without merging**
