### PR TITLE
Add support for running code coverage reports on individual projects

### PR DESCRIPTION
**Pull request by weshaggard**
Add support for running code coverage reports on individual projects This commit enables generating code coverage reports for individual projects. To run a build and test with code coverage reports run
command:

msbuild /t:BuildAndTest /p:Coverage=true

### CODE REVIEW

**Comment by weshaggard** [comment]
@orteipid I've submitted a PR that fixes #991. 

cc @mmitche @stephentoub

**Comment by akoeplinger** [comment]
Why do I need /p:RunCoverageReport=true? Shouldn't /p:Coverage=true (like with build.cmd) be enough?

**Comment by stephentoub** [comment]
I agree; it'd be nice if /p:Coverage=true would just do the RightThing(tm), generating a coverage report for whatever projects were built/tested as part of the run, whether all of them or one of them.

**Comment by weshaggard** [comment]
The issue is that we need something that makes this unique for just one project. Coverage=true is for the root project so if you build the root and it will try to generate the report for every project (causing races and conflicts) because the report generation always writes to the same index.htm file. So I need some way to distinguish the root build from the individual left project build. If you guys have other thoughts on how to do that then please let me know. Another potential option would be to create another target unique to only individual projects, something like: "/t:BuildAndTestWithCoverage /p:Coverage=true". If you guys think that is better we could certainly do that but I was trying to not introduce new targets and instead was trying to control it via a property.

**Comment by mmitche** [comment]
@weshaggard Can't you detect whether you're building the root (it's building build.proj) and set a "wait for all dirs to complete to generate cov report".

**Comment by weshaggard** [comment]
@mmitche I maybe able to set some other property only while building from the root and use that as a condition to not run it for individual projects. Let me have a look.

**Comment by weshaggard** [comment]
OK I figured out a way to pass an extra property via the dir.tarversals.targets that we can use to distinguish a root build from an individual project build. I updated my original comment and title to reflect the current changes I've pushed.

**Comment by akoeplinger** [comment]
Great :+1:

**Comment by stephentoub** [comment]
Thanks, Wes.

**Comment by akoeplinger** [comment]
@weshaggard Could you please add a note about this to the wiki (https://github.com/dotnet/corefx/wiki/Developer-Guide#tests) as well? Thanks!

**Comment by weshaggard** [comment]
@akoeplinger done.

**Pull request merged**
