### PR TITLE
Reduce XDocument Console spam

### PR DESCRIPTION
**Pull request by krwq**

### CODE REVIEW

**Comment by nguerrera** [comment]
LGTM once CI passes.

**Comment by weshaggard** [comment]
@krwq Looking at a recent CI build for example http://dotnet-ci.cloudapp.net/job/dotnet_corefx_windows_debug_prtest/47/console there is still a lot of console output coming out of the Xml tests can you please clean up all the extra console output.

**Comment by krwq** [comment]
This is only displaying which tests were skipped, how many passed and some failures (unfortunately they are showing error message but not failing). They are not really using Xunit so if I disable those messages there will be no information about what failed/got skipped. I will convert the tests which are failing/being skipped to Xunit just to reduce messages although I don't think disabling information about how many tests passed is a good idea.

**Comment by weshaggard** [comment]
@krwq If these tests aren't using Xunit then they shouldn't be included in our inner loop tests and should be disabled as they will not get the correct reporting anyway. Just dumping that information to the console isn't useful. Please disable these tests and file an issue to re-enable them when you can convert them to xunit.

**Pull request merged**
