### PR TITLE
Reset packaging for 2.2.6

### PR DESCRIPTION
**Pull request by wtgodbe**
CC @joperezr @safern

### CODE REVIEW

**Comment by wtgodbe** [comment]
@mmitche do we need to port https://github.com/dotnet/corefx/commit/b2b5fc0370028f2e5b21c233f7b13d4953fe633b to 2.2 to get CI running for this?

**Comment by mmitche** [comment]
@wtgodbe Yeah

**Comment by wtgodbe** [comment]
I'll work on getting https://github.com/dotnet/corefx/pull/37714 in

**Pull request merged**
