### PR TITLE
Port netcoreapp1.0 test to rtm

### PR DESCRIPTION
**Pull request by ericstj**
RTM port of https://github.com/dotnet/corefx/pull/8838

### CODE REVIEW

**Comment by ericstj** [comment]
@dotnet-bot test Innerloop CentOS7.1 Debug Build and Test
@dotnet-bot test Innerloop CentOS7.1 Release Build and Test

**Comment by ericstj** [comment]
@dotnet-bot test Innerloop CentOS7.1 Debug Build and Test

**Comment by ericstj** [comment]
/cc @bartonjs @ellismg 
Either of you know why this would happen only in the centos builds:
```
 ./run-test.sh --configurationGroup Debug --os Linux --corefx-tests /mnt/resource/j/workspace/dotnet_corefx/release_1.0.0/centos7.1_debug_tst_prtest/bin/tests/Linux.AnyCPU.Debug/ --coreclr-bins /mnt/resource/j/workspace/dotnet_corefx/release_1.0.0/centos7.1_debug_tst_prtest/bin/Product/Linux.x64.Release/ --mscorlib-bins /mnt/resource/j/workspace/dotnet_corefx/release_1.0.0/centos7.1_debug_tst_prtest/bin/Product/Linux.x64.Release/ --IgnoreForCI
09:37:46 /tmp/hudson7004893561772491311.sh: line 4: ./run-test.sh: Permission denied
```

**Comment by ellismg** [comment]
If I had to hazard a guess it would be that either run-test.sh is not being marked as executable for some reason (which should happen from git).

**Comment by ericstj** [comment]
Hmm, I do notice that in the github file view it lists `run-test.sh 100755 → 100644`.  That could mean that encoding changed, which might have caused this?

**Comment by ellismg** [comment]
@ericstj That is likely the problem.

git update-index --chmod=+x <path-to-run-tests.sh> should pend a change that makes it writeable again, which you can commit.

**Comment by ericstj** [comment]
OK, that fixed the diff.  This should go through now.

**Comment by ericstj** [comment]
Fixes https://github.com/dotnet/corefx/issues/8867

**Comment by ericstj** [comment]
Conflict was introduced by https://github.com/dotnet/corefx/pull/8863.

We've got this passing on CentOS now, this change needs to go in yesterday so I'm going to rebase, resolve the conflict, and merge.  I'll deal with the fallout.

**Pull request merged**
