### PR TITLE
Alc enhancements

### LINKED ISSUE #34791: AssemblyLoadContext .NET Core 3.0 improvements
### Concrete Type
There is a desire to simplify `System.Runtime.Loader.AssemblyLoadContext` usage by making it a concrete type.  (from #34535)

The existing class is abstract because the `Load()` method is not implemented.  Recommend adding a default implementation of `Load()` as a method returning `null` and make the constructors public. This is a logical default implementation as it implies falling back to the `AssemblyLoadContext.Default` for first chance to load the assembly.

### Naming ALCs
To simplify diagnostics for `System.Runtime.Loader.AssemblyLoadContext` (from #34530):
 * Add a `Name` to each ALC making understanding of role of each ALC easier

The name will make it more convenient to understand what is happening in the debugger.  It will also make any tracing easier to understand.

+ The Default ALC would be constructed with name = "Default".
+ The Assembly.LoadFile(path) generated ALCs would be constructed with name =  "Assembly.LoadFile(_path_)" .
+ Custom AssemblyLoadContext implementations could provide a logical name.  
+ The legacy Custom AssemblyLoadContext using the current protected constructor will not set the name.  In these cases the name will default to `null`.

### Set of ALCs & Assemblies
Provide a mechanism to iterate through ALCs and their contents to create a graphical representation. These APIs are intended to help make understanding and diagnosing isolation designs (from #34530). 

Add `Contexts`, and `Assemblies` properties.

## Proposed API changes

```C#
namespace System.Runtime.Loader
{
    public partial class AssemblyLoadContext
    {
        // Add a public constructor
        // Allow naming each AssemblyLoadContext
        public AssemblyLoadContext(String name, bool isCollectible = false);

        // Add default Load() implementation
        protected virtual System.Reflection.Assembly Load(System.Reflection.AssemblyName assemblyName)
        {
            return null;
        }
          
        public String Name { get; }
          
        // Override the ToString to return Name, type name, and unique instance id.
        public override string ToString();

        // Set of ALCs
        public static IEnumerable<AssemblyLoadContext> Contexts { get; }

        // Set of Assemblies in the ALC
        public IEnumerable<System.Reflection.Assembly> Assemblies { get; }
    }
}
```
## Open issues
* Consider renaming `Contexts` to `AllContexts` or `GetAllContexts`

### PR DESCRIPTION
**Pull request by sdmaclea**
Included #36441 w/ merge conflicts fixed. So that this would compile.

Fixes #34791

### CODE REVIEW

**Comment by jkotas** [comment]
Do you plan to add a test coverage for these APIs in CoreFX as well?

**Comment by sdmaclea** [comment]
I should add a few tests in CoreFX. Unless there are objections, I'll make it a separate PR.

**Comment by jkotas** [comment]
> I'll make it a separate PR.

Yes, that's fine.

**Comment by sdmaclea** [comment]
This is failing on UWP_NETNative.  @jkotas Do I need to do anything special? I assume these bits come from corert. I don't see any update dependencies for corert though.

**Comment by sdmaclea** [comment]
If my quick analysis is correct, UWP_NETNative version is coming from ` <UAPvNextVersion>10.0.16300</UAPvNextVersion>` which hasn't been update since 7/2018.

**Comment by sdmaclea** [comment]
I guess the ref change needs to be marked `#if netcoreapp` or `#if !uap`

**Comment by jkotas** [comment]
Add the missing APIs to https://github.com/dotnet/corefx/blob/master/src/System.Runtime.Loader/src/ApiCompatBaseline.uapaot.txt to make the build green

**Pull request merged**
