### PR TITLE
Cleanup and consolidate BigInteger.Subtract tests

### PR DESCRIPTION
**Pull request by hughbe**
- Consolidate common test data
- Remove random data (but add tests that cover the random data, of
course)
- Stop using this strange StackCalculator thingy that confuses things,
and verify results properly

/cc @stephentoub

### CODE REVIEW

**Comment by stephentoub** [comment]
>             BigInteger largeNegativeBigInt = BigInteger.Parse("-123123123123123123123123123123123123123123123123123123123123123123123123123123123123123123123123");

test

---
Refers to: src/System.Runtime.Numerics/tests/BigInteger/BigInteger.SubtractTests.cs:15 in 921832a. [](commit_id = 921832ad0880b60d0d7de47a632c4f5422023a57, deletion_comment = False)

**Comment by stephentoub** [comment]
>             BigInteger largeNegativeBigInt = BigInteger.Parse("-123123123123123123123123123123123123123123123123123123123123123123123123123123123123123123123123");

Can you put the string into a local, such that we can easily see it's the same in both cases? e.g.
```C#
string largePositiveBigIntString = "123123123...";
var largePositiveBigInt = BigInteger.Parse(largePositiveBigIntString);
var largeNegativeBigInt = BigInteger.Parse("-" + largePositiveBigIntString);
```

---
Refers to: src/System.Runtime.Numerics/tests/BigInteger/BigInteger.SubtractTests.cs:15 in 921832a. [](commit_id = 921832ad0880b60d0d7de47a632c4f5422023a57, deletion_comment = False)

**Comment by stephentoub** [comment]
>             yield return new object[] { new BigInteger(-123), largeNegativeBigInt1, BigInteger.Parse("123123123123123123123123123123123123123123123123123123123123123123123123123123123123123123123000") };

At least where these strings are repeated, can you put them into local variables or consts?

---
Refers to: src/System.Runtime.Numerics/tests/BigInteger/BigInteger.SubtractTests.cs:71 in 921832a. [](commit_id = 921832ad0880b60d0d7de47a632c4f5422023a57, deletion_comment = False)

**Comment by stephentoub** [comment]
>     }

I wonder if it would help to provide any more verification to add:
```C#
Assert.Equal(-expected, bigInteger2 - bigInteger1);
```

---
Refers to: src/System.Runtime.Numerics/tests/BigInteger/BigInteger.SubtractTests.cs:317 in 921832a. [](commit_id = 921832ad0880b60d0d7de47a632c4f5422023a57, deletion_comment = False)

**Comment by stephentoub** [comment]
Thanks, @hughbe.  A few comments, but otherwise LGTM.

**Comment by hughbe** [comment]
Thanks @stephentoub. Sorry about GitHub truncating my changes, not sure why it did that :(

I've addressed all your comments

**Comment by stephentoub** [comment]
Great.  Thanks, @hughbe.

**Pull request merged**
