### PR TITLE
Replace % inside loop of Random ctor

### PR DESCRIPTION
**Pull request by chrisaut**
This fixes/implements #11568

A quick local instantiation loop/benchmark thingy seems to show this about twice as fast as before in x86. 

In x64 it does seem to be about the same performance, maybe I'm doing something wrong. x64 assembly shows it did not do a idiv with the existing code, but optimized it away to shifts. The new version generates far fewer instruction, but includes a branch now, maybe that's why it still about the same performance.

Assembly before (x86):
```
            for (int i = 1; i < 55; i++)
010F2F4E  mov         ebx,edi  
010F2F50  mov         eax,dword ptr [ebp-18h]  
010F2F53  mov         esi,dword ptr [eax+4]  
            {  //Apparently the range [1..55] is special (Knuth) and so we're wasting the 0'th position.
                ii = (21 * i) % 55;
010F2F56  imul        eax,ebx,15h  
010F2F59  mov         ecx,37h  
010F2F5E  cdq  
010F2F5F  idiv        eax,ecx  
                SeedArray[ii] = mk;
010F2F61  cmp         edx,dword ptr [esi+4]  
010F2F64  jae         010F3018  
010F2F6A  mov         dword ptr [esi+edx*4+8],edi  
```

Assembly after (x86):
```
            for (int i = 1; i < 55; i++)
010F312C  mov         ebx,edx  
010F312E  mov         eax,dword ptr [ebp-14h]  
010F3131  mov         esi,dword ptr [eax+4]  
            {  //Apparently the range [1..55] is special (Knuth) and so we're wasting the 0'th position.
                if ((ii += 21) >= 55) ii -= 55;
010F3134  add         edi,15h  
010F3137  cmp         edi,37h  
010F313A  jl          010F313F  
                if ((ii += 21) >= 55) ii -= 55;
010F313C  add         edi,0FFFFFFC9h  
                SeedArray[ii] = mk;
010F313F  cmp         edi,dword ptr [esi+4]  
010F3142  jae         010F31F0  
010F3148  mov         dword ptr [esi+edi*4+8],edx  
```

Assembly before (x64):
```
            for (int i = 1; i < 55; i++)
00007FFC9D2C0696  mov         r11d,1  
            {  //Apparently the range [1..55] is special (Knuth) and so we're wasting the 0'th position.
                ii = (21 * i) % 55;
00007FFC9D2C069C  imul        edi,r11d,15h  
00007FFC9D2C06A0  mov         eax,94F2095h  
00007FFC9D2C06A5  imul        edi  
00007FFC9D2C06A7  mov         eax,edx  
00007FFC9D2C06A9  sar         eax,1  
00007FFC9D2C06AB  mov         edx,eax  
00007FFC9D2C06AD  shr         edx,1Fh  
00007FFC9D2C06B0  add         eax,edx  
00007FFC9D2C06B2  imul        eax,eax,37h  
00007FFC9D2C06B5  mov         edx,edi  
00007FFC9D2C06B7  sub         edx,eax  
00007FFC9D2C06B9  mov         eax,edx  
                SeedArray[ii] = mk;
00007FFC9D2C06BB  mov         rdx,r8  
00007FFC9D2C06BE  cmp         eax,r9d  
00007FFC9D2C06C1  jae         00007FFC9D2C0790  
00007FFC9D2C06C7  movsxd      rdi,eax  
00007FFC9D2C06CA  mov         dword ptr [rdx+rdi*4+10h],r10d  
```

Assembly after(x64):
```
            for (int i = 1; i < 55; i++)
00007FFC9D2C0B66  mov         r9d,1  
            {  //Apparently the range [1..55] is special (Knuth) and so we're wasting the 0'th position.
                if ((ii += 21) >= 55) ii -= 55;
00007FFC9D2C0B6C  add         ebx,15h  
00007FFC9D2C0B6F  cmp         ebx,37h  
00007FFC9D2C0B72  jl          00007FFC9D2C0B77  
                if ((ii += 21) >= 55) ii -= 55;
00007FFC9D2C0B74  add         ebx,0FFFFFFC9h  
                SeedArray[ii] = mk;
00007FFC9D2C0B77  mov         r10,rcx  
00007FFC9D2C0B7A  cmp         ebx,r8d  
00007FFC9D2C0B7D  jae         00007FFC9D2C0C4C  
00007FFC9D2C0B83  movsxd      r11,ebx  
00007FFC9D2C0B86  mov         dword ptr [r10+r11*4+10h],edx  
```

### CODE REVIEW

**Comment by chrisaut** [comment]
Second % operator in inner loop:

With this x64 also seems to be measurably faster for me:
500000 runs
new ~260ms x86
old ~570ms x86

new ~255ms x64
old ~380ms x64

```C#
            for (int j = 0; j < 15; j++)
            {
                sw.Restart();
                for (int i = 0; i < 500000, i++)
                {
                    new Random(10);
                }
                sw.Stop();
                Console.WriteLine(sw.ElapsedMilliseconds);
            }
```

Assembly before (x86):
```
                for (int i = 1; i < 56; i++)
028409DA  mov         edi,1  
028409DF  mov         eax,dword ptr [ebp-14h]  
028409E2  mov         esi,dword ptr [eax+4]  
                {
                    SeedArray[i] -= SeedArray[1 + (i + 30) % 55];
028409E5  mov         eax,dword ptr [ebp-14h]  
028409E8  mov         esi,dword ptr [eax+4]  
028409EB  cmp         edi,dword ptr [esi+4]  
028409EE  jae         02840A50  
028409F0  lea         ebx,[esi+edi*4+8]  
028409F4  lea         eax,[edi+1Eh]  
028409F7  mov         ecx,37h  
028409FC  cdq  
028409FD  idiv        eax,ecx  
028409FF  inc         edx  
02840A00  cmp         edx,dword ptr [esi+4]  
02840A03  jae         02840A50  
02840A05  mov         eax,dword ptr [esi+edx*4+8]  
02840A09  sub         dword ptr [ebx],eax  
                    if (SeedArray[i] < 0) SeedArray[i] += MBIG;
```
Assembly after (x86):
```
                for (int i = 1; i < 56; i++)
028406B5  mov         ecx,1  
028406BA  mov         edx,dword ptr [ebx+4]  
                {
                    int n = i + 30;
028406BD  lea         edi,[ecx+1Eh]  
                    if (n >= 55) n -= 55;
028406C0  cmp         edi,37h  
028406C3  jl          028406C8  
028406C5  add         edi,0FFFFFFC9h  
                    SeedArray[i] -= SeedArray[1 + n];
028406C8  mov         edx,dword ptr [ebx+4]  
028406CB  cmp         ecx,dword ptr [edx+4]  
028406CE  jae         0284071C  
028406D0  lea         esi,[edx+ecx*4+8]  
028406D4  inc         edi  
028406D5  cmp         edi,dword ptr [edx+4]  
028406D8  jae         0284071C  
028406DA  mov         eax,dword ptr [edx+edi*4+8]  
028406DE  sub         dword ptr [esi],eax  
                    if (SeedArray[i] < 0) SeedArray[i] += MBIG;
```
Assembly before (x64):
```
                for (int i = 1; i < 56; i++)
00007FFC9D2B0B3C  mov         r10d,1  
                {
                    SeedArray[i] -= SeedArray[1 + (i + 30) % 55];
00007FFC9D2B0B42  mov         rax,rcx  
00007FFC9D2B0B45  cmp         r10d,r8d  
00007FFC9D2B0B48  jae         00007FFC9D2B0BCC  
00007FFC9D2B0B4E  movsxd      rdx,r10d  
00007FFC9D2B0B51  lea         r11,[rax+rdx*4+10h]  
00007FFC9D2B0B56  mov         rdi,r11  
00007FFC9D2B0B59  mov         rbx,rcx  
00007FFC9D2B0B5C  lea         ebp,[r10+1Eh]  
00007FFC9D2B0B60  mov         eax,94F2095h  
00007FFC9D2B0B65  imul        ebp  
00007FFC9D2B0B67  mov         eax,edx  
00007FFC9D2B0B69  sar         eax,1  
00007FFC9D2B0B6B  mov         edx,eax  
00007FFC9D2B0B6D  shr         edx,1Fh  
00007FFC9D2B0B70  add         eax,edx  
00007FFC9D2B0B72  imul        eax,eax,37h  
00007FFC9D2B0B75  mov         edx,ebp  
00007FFC9D2B0B77  sub         edx,eax  
00007FFC9D2B0B79  lea         eax,[rdx+1]  
00007FFC9D2B0B7C  cmp         eax,r8d  
00007FFC9D2B0B7F  jae         00007FFC9D2B0BCC  
00007FFC9D2B0B81  movsxd      rax,eax  
00007FFC9D2B0B84  mov         eax,dword ptr [rbx+rax*4+10h]  
00007FFC9D2B0B88  sub         dword ptr [rdi],eax  
                    if (SeedArray[i] < 0) SeedArray[i] += MBIG;
```
Assembly after (x64):
```
                for (int i = 1; i < 56; i++)
00007FFC9D2D070A  mov         ecx,1  
                {
                    int n = i + 30;
00007FFC9D2D070F  lea         r9d,[rcx+1Eh]  
                    if (n >= 55) n -= 55;
00007FFC9D2D0713  cmp         r9d,37h  
00007FFC9D2D0717  jl          00007FFC9D2D071D  
00007FFC9D2D0719  add         r9d,0FFFFFFC9h  
                    SeedArray[i] -= SeedArray[1 + n];
00007FFC9D2D071D  mov         r10,rdx  
00007FFC9D2D0720  cmp         ecx,r8d  
00007FFC9D2D0723  jae         00007FFC9D2D0787  
00007FFC9D2D0725  movsxd      r11,ecx  
00007FFC9D2D0728  lea         r10,[r10+r11*4+10h]  
00007FFC9D2D072D  mov         r11,r10  
00007FFC9D2D0730  mov         rdi,rdx  
00007FFC9D2D0733  inc         r9d  
00007FFC9D2D0736  cmp         r9d,r8d  
00007FFC9D2D0739  jae         00007FFC9D2D0787  
00007FFC9D2D073B  movsxd      r9,r9d  
00007FFC9D2D073E  mov         r9d,dword ptr [rdi+r9*4+10h]  
00007FFC9D2D0743  sub         dword ptr [r11],r9d  
                    if (SeedArray[i] < 0) SeedArray[i] += MBIG;
```

**Comment by hughbe** [comment]
Test Innerloop Ubuntu14.04 Debug Build and Test

**Comment by stephentoub** [comment]
LGTM

Note, though, that this implementation is currently only used when running on .NET Native.  The copy of the source in the coreclr repo is used when running on coreclr.  If we're going to make such a change in one place, ideally we'd make it in both.

That said, I'm not sure why we don't just always use the corefx implementation.  @mellinoe, @weshaggard , do you know if there's any reason we can't just use this corefx implementation in System.Runtime.Extensions rather than type-forwarding on coreclr?  I don't see Random exposed out of any other mscorlib surface area that would impact type identity.

**Comment by chrisaut** [comment]
That is unfortunate, if the corefx version cannot be used, I'll prepare a pull request for the coreclr version. But I'll wait until you guys decide what to do.

**Comment by mellinoe** [comment]
> I don't see Random exposed out of any other mscorlib surface area that would impact type identity

Yeah, I would be surprised if there's anything like that. This is most likely just something that we never bothered to unify since it has been relatively untouched for a while. Unless there's something I'm not thinking of, we should be able to use the version here everywhere.

**Comment by stephentoub** [comment]
> Unless there's something I'm not thinking of, we should be able to use the version here everywhere.

Ok, I'll submit a PR to do that.

**Comment by stephentoub** [comment]
https://github.com/dotnet/corefx/pull/11653

**Comment by stephentoub** [comment]
@dotnet-bot test this please (to run recently added Random test)

**Comment by stephentoub** [comment]
@chrisaut, I'm going to close this PR: per the discussion in #11653 and https://github.com/dotnet/corefx/issues/11665, we're actually going to delete this code from corefx, as both coreclr and corert have their own public versions that'll be used (as I mentioned, the coreclr is already being used for things other than .NET Native, so merging this PR wouldn't help that).  Thanks for the interest in contributing, and please feel free to submit PRs to those repos for this change.

**Pull request closed without merging**
