### PR TITLE
Native projects for FileVersionInfo tests.

### LINKED ISSUE #16613: Port source for FileVersionInfo test binaries
We don't have source for ```NativeLibrary.dll``` or ```SecondNativeLibrary.dll``` available anywhere. I wasn't able to find it in the TFS maze, but it wouldn’t be difficult to rewrite them if we can’t find the source and decide we need the ability to rebuild them.

They don't need to be included in the build, but they need some sort of instructions to build or a batch script alongside the sources so we can rebuild them easily in the future when needed. They should probably go to https://github.com/dotnet/corefx-testdata

### PR DESCRIPTION
**Pull request by attilah**
Native projects for ```FileVersionInfo``` tests instead of checking in in binaries. Fixes #16613.

### CODE REVIEW

**Comment by weshaggard** [comment]
@attilah thanks for working on building projects for these. Looks like for some reason the configuration.props didn't exist for this test project before, we must have missed it in the past, thanks for adding it. The current build issue in CI is caused by that addition you need to also add a build configuration for src\System.Diagnostics.FileVersionInfo\tests\System.Diagnostics.FileVersionInfo.Tests\System.Diagnostics.FileVersionInfo.Tests.csproj similar to the other test projects.

Now the question for me is whether or not we think it is worth building these live or just have the projects for rebuilding them and checking in the binaries only when they get updated. If we build them live that means we will not be able to build and run these tests on non-windows because we don't have the necessary toolset to build vcxproj projects there. For that reason I think I would suggest just including the projects but not actually pulling them into the build and instead just use them to manually build the binaries and commit them. Also probably worth a batch script or readme that says how to update those binaries.

**Comment by joperezr** [comment]
Hey @attilah, are you still planning on doing what @weshaggard suggested?

**Comment by attilah** [comment]
@joperezr oh @weshaggard ended the comment with possible choices and I don't think I am the one who can decide about the build process in this matter, I thought someone from the corefx team will jump in and comment about this decision.

Regarding that comment I think these tests are already specified to run and build on windows only, and excluded on non-windows platforms so having them as source and building them this way I think - I can be wrong! - cannot harm the process.

**Comment by ianhays** [comment]
>Regarding that comment I think these tests are already specified to run and build on windows only, and excluded on non-windows platforms so having them as source and building them this way I think - I can be wrong! - cannot harm the process.

Is there any reason why we can't have them run on Unix as well? If we're building the src project for all platforms then we should be running tests for all platforms also.

**Comment by weshaggard** [comment]
I would like to run the tests on all platforms but we cannot build vcproj's on all platforms. We could change these to build natively on each platform but I don't think it is worth the extra work to maintain that. So I would suggest we check-in the binaries given they rarely change anyway.

**Comment by ianhays** [comment]
>I would like to run the tests on all platforms but we cannot build vcproj's on all platforms. 

Yeah, building the vcxproj should not be a requirement for running the tests. 

>I think these tests are already specified to run and build on windows only, and excluded on non-windows platforms

If we're not currently running these tests on non-windows Platforms, then we should be.

> We could change these to build natively on each platform but I don't think it is worth the extra work to maintain that. 

Agreed.

> So I would suggest we check-in the binaries given they rarely change anyway.

Why not have the vcxproj from this PR and continue building it on Windows, but **also** check-in the binaries so they can be used on Unix without the need to build?

**Comment by weshaggard** [comment]
>Why not have the vcxproj from this PR and continue building it on Windows, but also check-in the binaries so they can be used on Unix without the need to build?

I want to have the vcxproj's from this PR checked in but I don't think it is worth having the build live. We should just drop a batch file or readme file on how to regenerate these when/if we need to do that.

**Comment by ianhays** [comment]
>I want to have the vcxproj's from this PR checked in but I don't think it is worth having the build live. We should just drop a batch file or readme file on how to regenerate these when/if we need to do that.

A batch file or readme to build a vcxproj seems like overkill imo, but I don't have a strong opinion.

**Comment by weshaggard** [comment]
>A batch file or readme to build a vcxproj seems like overkill imo, but I don't have a strong opinion.

It is nice to have a batch file that calls builds on the right packages and copies them to the expected locations in the tree, just to make it trivial to update if needed.

**Comment by ianhays** [comment]
>It is nice to have a batch file that calls builds on the right packages and copies them to the expected locations in the tree, just to make it trivial to update if needed.

Works for me.

@attilah sorry for the delay in getting back to you on this. Sounds like we've reached a consensus that the next steps for this PR should be:
- Make sure the tests are running on Windows and Unix
- Remove the native vcxproj from the full build
- Add/commit the new binary output
- Add a script to build the vcxproj and replace the existing test binaries with the newly built ones.

**Comment by danmosemsft** [comment]
@attilah do you have time to continue with this one? thanks!

**Comment by karelz** [comment]
@attilah any update? (if you don't have time now, that's fine, just let us know - it happens, we have seen it before ;-), no hard feelings)

**Comment by attilah** [comment]
@karelz sorry, now I don't have time to finish it, if you can wait of course I will.

But as of the requirements, I don't have a *nix environment to run the tests.

**Comment by karelz** [comment]
@attilah did you consider using Docker? It is nicely integrated into VS 2017 ;-)

Closing the PR. Feel free to reopen if/when you get time to work on it again.

**Pull request closed without merging**
