### PR TITLE
Prepare license and other files for the repo consolidation

### PR DESCRIPTION
**Pull request by ViktorHofer**
- The /*.md filter isn't working in AzDO, therefore we are listening the excluded files manually. 
- Renaming CODE_OF_CONDUCT.md to CODE-OF-CONDUCT.TXT to be consistent with THIRD-PARTY-NOTICES.TXT
- Rename LICENSE.TXT to LICENSE so that GH picks it up correctly and to align it with core-setup.

### CODE REVIEW

**Review by stephentoub — APPROVED** [review]
cc: @richlander

**Comment by ViktorHofer** [comment]
Unfortunately it's the **PATENTS.TXT** file which makes GH not honor our LICENSE file-

GH is using licensee to detect the license in the repo. I just followed the docs to find out why it's still not detecting the license: https://github.com/licensee/licensee/blob/master/docs/CONTRIBUTING.md#reporting-an-improperly-detected-license

It seems that the duplicate license in README.md is confusing the tool:

```
vihofer@DESKTOP-803H9R0:~/licensee$ script/git-repo https://github.com/dotnet/corefx
License:        NOASSERTION
Matched files:  LICENSE, PATENTS.TXT, README.md
LICENSE:
  Content hash:  d64f3bb4282a97b37454b5bb96a8a264a3363dc3
  Attribution:   Copyright (c) .NET Foundation and Contributors
  Confidence:    100.00%
  Matcher:       Licensee::Matchers::Exact
  License:       MIT
PATENTS.TXT:
  Content hash:  fab2cb8362aea178cb0953521a67d438862fd7cc
  License:       NOASSERTION
  Closest non-matching licenses:
    MS-PL similarity:  32.28%
README.md:
  Content hash:  b626825aaa1222a80b528e83c2e7fee352c7544d
  Confidence:    90.00%
  Matcher:       Licensee::Matchers::Reference
  License:       MIT
```

**Comment by ViktorHofer** [comment]
In my fork where I removed that file it now identifies the repo correctly as MIT: https://github.com/ViktorHofer/corefx/tree/master

**Comment by ViktorHofer** [comment]
@richlander @terrajobst @jkotas do we actually need the PATENS.TXT file? I don't see in core-setup or msbuild or other dotnet repos.

**Comment by ViktorHofer** [comment]
cc @danmosemsft

**Comment by richlander** [comment]
The patents.txt is only for a repo that has CoreCLR in it. That's been dotnet/coreclr. After repo consolidation, it's whichever repo has CoreCLR. HTH.

**Pull request merged**
