### PR TITLE
Fixing the python style script to fix CI builds

### PR DESCRIPTION
**Pull request by sokket**
Fixing the python style script to output only the differences when the checkonly flag has been placed. This will normalize the output and allows us to check for the expected output length to determine if any style replacements happened in the file

/cc @stephentoub @mmitche

### CODE REVIEW

**Comment by sokket** [comment]
test ci please

**Comment by mmitche** [comment]
@sokket test ci please is just testing the netci.groovy generation, not actually running the legs themselves.  What are you trying to do?

**Comment by sokket** [comment]
Yeah I typed that and was like...wait, I didn't actually need that...

**Comment by mmitche** [comment]
Btw you can rerun the code formatter if required by typing "test code formatter check"

**Comment by sokket** [comment]
Good to know, thanks!

**Comment by stephentoub** [comment]
```
12:01:02 Running clang-format style cop on native code...
12:01:02 Formatting native file with command: clang-format -style=file -output-replacements-xml d:\j\workspace\dotnet_corefx\native_code_format_check_prtest\src\Native\System.Native\pal_errno.cpp
12:01:02 File not style compliant, exiting: System.Native\pal_errno.cpp
```

**Comment by sokket** [comment]
Yeah, it passed on my OS X machine but it looks like that's due to clang-format being v3.8 on my local machine. I have a repro of the issue on my Windows box and it looks to only repro with v3.6. I'm investigating why it complains about the formatting yet when asked to fix it (or even output the fixes), it doesn't do anything. Might be a bug in v3.6

**Comment by stephentoub** [comment]
I have 3.6 on my Ubuntu VM and it runs fine.  The lab is using Windows.  Is it possible it's an issue of formatting on Windows vs formatting on Unix rather than being about the clang version?  Maybe something to do with newlines or having one at the end of the file?  Just speculating.

**Comment by sokket** [comment]
That could be...it's weird that when I run it (manually and with the script) to fix the "formatting errors" that it complains about with ```checkonly```, it doesn't find any. I'll try changing the groovy script to have it run on Ubuntu and see if that changes anything

**Comment by sokket** [comment]
test ci please

**Comment by sokket** [comment]
Found the bug - I need to avoid running brew update since it moved my clang-format to v3.8. This means I added an invalid key to the .clang-format file and when running clang-format manually, it could not parse the file and thus reverted to basic LLVM styling. Since we were ever only checking on the server and not applying the formatting, this was never fixed. I changed the .clang-format file to use only keys that are supported for that version as well as reverted my version back to 3.6 to avoid this issue in the future.

**Comment by sokket** [comment]
test code formatter check

**Comment by sokket** [comment]
The Windows clang-format seems to choke on certain files while the OS X and Ubuntu versions do not (all v3.6...triple checked that). I changed the groovy script to use Ubuntu (since the native code is needed for non-Windows platforms) but the CI system doesn't use that change. @mmitche is there any way to test the Formatter step with my groovy changes without merging?

**Comment by mmitche** [comment]
@sokket Unfortunately no.  There potentially could be in the future, but the mechanics and practical aspects around doing this are a little difficult.  One way we can test major changes like this is to actually make a new job that's not triggered by default (like code coverage is) as a testing ground, iterate on that, and then merge those changes into the 'live' version when they are good.

**Pull request merged**
