### PR TITLE
Remove [SecureSafeCritical] and [SecurityCritical] in System.Private.DataContractSerialization

### LINKED ISSUE #13190: Remove [SecuritySafeCritical] and [SecurityCritical] in System.Private.DataContractSerialization
SecuritySafeCritical or SecurityCritical is a no-op on NetCore as there's no partial trust. The task is to remove all of these attributes from methods.

### PR DESCRIPTION
**Pull request by stephenmichaelf**
Removed usage of both [SecureSafeCritical] and [SecurityCritical] as well as removing unused references where it seemed appropriate.

@shmao 

Fix #13190

### CODE REVIEW

**Comment by shmao** [comment]
Thanks for the great work, @stephenmichaelf ! LGTM.

@mconnew @zhenlan can you please take a look at the changes?

**Comment by karelz** [comment]
@stephenmichaelf thanks for your contribution!
In future please ping us on the issue mentioning you plan to grab the issue - we can then assign it to you, avoiding others to grab it in parallel.
Thanks!

**Comment by stephenmichaelf** [comment]
Sorry about that! Will do :)

**Comment by shmao** [comment]
@stephenmichaelf I just merged one of my PRs, which turned out caused some conflicts for your changes. Would you mind resolving the conflicts and update your PR? Thanks!

**Comment by stephenmichaelf** [comment]
@shmao I did a rebase following the directions [here](http://stackoverflow.com/questions/3903817/pull-new-updates-from-original-github-repository-into-forked-github-repository) but not sure if I did it right?

**Comment by shmao** [comment]
It doesn't seem right. Can you try the following commands from your `13190-RemoveSecurityAttributes` branch?

```
git fetch --all --prune
git rebase upstream/master
```

Then you would get errors saying,

```
Failed to merge in the changes.
Patch failed at 0001 Remove [SecureSafeCritical] and [SecurityCritical] in System.Private.DataContractSerialization.
The copy of the patch that failed is found in:
   d:/OSS/corefx-1/corefx/.git/rebase-apply/patch

When you have resolved this problem, run "git rebase --continue".
If you prefer to skip this patch, run "git rebase --skip" instead.
To check out the original branch and stop rebasing, run "git rebase --abort".
```

At that point, you need to resolve the conflicts. `git status` would show you the following 3 files have conflicts,

```

        both modified:   ../../../System.Private.DataContractSerialization/src/System/Runtime/Serialization/Globals.cs
        both modified:   ../../../System.Private.DataContractSerialization/src/System/Runtime/Serialization/Json/JsonFormatGeneratorStatics.cs
        both modified:   ../../../System.Private.DataContractSerialization/src/System/Runtime/Serialization/XmlFormatGeneratorStatics.cs
```

If you open Globals.cs, you would see conflicts like below,

```
<<<<<<< HEAD
        private static Type s_typeOfIExtensibleDataObject;
        internal static Type TypeOfIExtensibleDataObject => s_typeOfIExtensibleDataObject ?? (s_typeOfIExtensibleDataObject = typeof (IExtensibleDataObject));

        private static Type s_typeOfExtensionDataObject;
        internal static Type TypeOfExtensionDataObject => s_typeOfExtensionDataObject ?? (s_typeOfExtensionDataObject = typeof (ExtensionDataObject));

        [SecurityCritical]
=======
>>>>>>> Remove [SecureSafeCritical] and [SecurityCritical] in System.Private.DataContractSerialization.
```

You need to change the code to,

```
        private static Type s_typeOfIExtensibleDataObject;
        internal static Type TypeOfIExtensibleDataObject => s_typeOfIExtensibleDataObject ?? (s_typeOfIExtensibleDataObject = typeof (IExtensibleDataObject));

        private static Type s_typeOfExtensionDataObject;
        internal static Type TypeOfExtensionDataObject => s_typeOfExtensionDataObject ?? (s_typeOfExtensionDataObject = typeof (ExtensionDataObject));
```


After resolving all conflicts, run "git rebase --continue" from the command line. And then you can push your commits to remote again.

Sorry for the trouble. Please let me know if you have any other questions.

**Comment by stephenmichaelf** [comment]
@shmao I did those commands but it still doesn't seem to be working. The PR is showing 97 changes instead of 37. Sorry it has been a while since I've rebased! Not sure what's going on. Any ideas? If I do a git log I see this:

image

**Comment by shmao** [comment]
Maybe I missed something. But I think those commands should just be what you need to run. 

Would you mind if I resolve the conflicts and send out a PR on behalf of you?

**Comment by stephenmichaelf** [comment]
Yes I think that's a good idea. Thanks! Sorry for the confusion. Not sure what is going on.

**Comment by shmao** [comment]
@stephenmichaelf sounds good. I just sent out #13820. I'm closing this. Thanks!

**Pull request closed without merging**
