### PR TITLE
Augment GlobalLog.Assert* call sites in System.Net

### PR DESCRIPTION
**Pull request by stephentoub**
The "temporary" part 1 of https://github.com/dotnet/corefx/issues/5265 until a better logging solution can be put in place.

1. Removed the "bool globalLogEnabled = GlobalLog.IsEnabled" that had been used previously.
2. Added Debug.Fail calls at all GlobalLog.Assert* call sites.

cc: @cipop, @davidsh, @josguil

### CODE REVIEW

**Comment by davidsh** [comment]
Looks like the Window DEBUG failures might be caused by an inadvertent logic change in this PR.

**Comment by stephentoub** [comment]
> Looks like the Window DEBUG failures might be caused by an inadvertent logic change in this PR.

Yeah, I'm fixing it now.  It's from a previous change rather than from this one.

**Comment by stephentoub** [comment]
Test Innerloop Windows_NT Debug Build and Test please

**Comment by stephentoub** [comment]
@davidsh, @cipop, the failure is due to this:
https://github.com/dotnet/corefx/pull/5419/files#diff-a92dcc50fa7799a1b77b747a99c6222bR3301

As far as I can tell, my transformation was correct, which means that there's some other issue underlying this if the assertion is failing.  Does that sound right?  If so, how would you like me to handle this?

**Comment by davidsh** [comment]
Since we're not seeing this problem except for your PR, the problem lies in your PR most likely.  I would suggest scaling back this PR in some way (maybe revert the changes to Socket.cs file) and see if you can localize the area that broke.

**Comment by stephentoub** [comment]
> the problem lies in your PR most likely

Actually, looking at the original code ported to GitHub, this was an assert that never fired due to always have a true condition:
https://github.com/dotnet/corefx/blob/36c09c4802aebed9abfe4dd86fe9fbfd7b9c72cc/src/System.Net.Sockets/src/System/Net/Sockets/Socket.cs#L3419-L3421

So, I can simply remove the assert/fail entirely if that's the right answer.  However, in looking at the original full framework code, the reason the condition is checked again is because it's assigned a new value:
http://referencesource.microsoft.com/#System/net/System/Net/Sockets/Socket.cs,4298

Is there something missing here, or should the whole logging block and assertion here be removed?

**Comment by davidsh** [comment]
>Is there something missing here, or should the whole logging block and assertion here be removed?

@CIPop will need to answer this as he is more familiar with that code.

**Comment by CIPop** [comment]
/cc: @pgavlin 

@stephentoub The original transformation is incorrect. We need to move the check immediately after the call to `Marshal.GetLastWin32Error();` which now seems to be made in within the function at https://github.com/dotnet/corefx/pull/5419/files#diff-a92dcc50fa7799a1b77b747a99c6222bR3282 

I think this is going to require quite some work to get right (I'm afraid it might have been missed in other places): please add a TODO and temporarily comment out the incorrectly placed Assert.

**Comment by pgavlin** [comment]
> I think this is going to require quite some work to get right (I'm afraid it might have been missed in other places): please add a TODO and temporarily comment out the incorrectly placed Assert.

I actually don't think that this should be too tough to track down. This is an example of a common pattern where the call to `GLW32Error` was moved behind the PAL. Looking through the PAL for these calls and adding the appropriate asserts will probably suffice.

**Comment by CIPop** [comment]
> I actually don't think that this should be too tough to track down.

@pgavlin You're right - already found some of the right places in my last comment. I should have formulated that we don't necessarily need to do this within this PR.

**Comment by stephentoub** [comment]
@cipop, @davidsh, anything else before I merge?

**Comment by davidsh** [comment]
LGTM

**Comment by stephentoub** [comment]
Thanks, all.

**Pull request merged**
