### PR TITLE
Increment versions post 2.0

### PR DESCRIPTION
**Pull request by ericstj**
/cc @weshaggard

### CODE REVIEW

**Comment by ericstj** [comment]
Most of these legs are failing System.Reflection.Tests.MemberInfoTests.TestEquality_Multiple.

They're failing this check: https://github.com/dotnet/corefx/blob/2117bae3a6c9736033e6d1659821ff3a1069920b/src/System.Runtime/tests/System/Reflection/MemberInfoTests.cs#L182

In the debugger I can see that the first call to get the members lists the nested types in source order with `Base` appearing first.  The second call has a different order for the nested types, with `SampleClass` appearing before `Base`.  @AtsushiKan this seems like a bug in reflection.  I don't see how my changes could have caused it but it seems to reliably repro with my changes.

```
-		mi1	{System.Reflection.MemberInfo[15]}	System.Reflection.MemberInfo[]
+		[0]	{Void TestGetCustomAttributesData()}	System.Reflection.MemberInfo {System.Reflection.RuntimeMethodInfo}
+		[1]	{Void TestEquality_Multiple()}	System.Reflection.MemberInfo {System.Reflection.RuntimeMethodInfo}
+		[2]	{System.Reflection.MemberInfo[] GetMembers(System.Type)}	System.Reflection.MemberInfo {System.Reflection.RuntimeMethodInfo}
+		[3]	{System.String ToString()}	System.Reflection.MemberInfo {System.Reflection.RuntimeMethodInfo}
+		[4]	{Boolean Equals(System.Object)}	System.Reflection.MemberInfo {System.Reflection.RuntimeMethodInfo}
+		[5]	{Int32 GetHashCode()}	System.Reflection.MemberInfo {System.Reflection.RuntimeMethodInfo}
+		[6]	{System.Type GetType()}	System.Reflection.MemberInfo {System.Reflection.RuntimeMethodInfo}
+		[7]	{Void Finalize()}	System.Reflection.MemberInfo {System.Reflection.RuntimeMethodInfo}
+		[8]	{System.Object MemberwiseClone()}	System.Reflection.MemberInfo {System.Reflection.RuntimeMethodInfo}
+		[9]	{Void .ctor()}	System.Reflection.MemberInfo {System.Reflection.RuntimeConstructorInfo}
+		[10]	{System.Reflection.Tests.MemberInfoTests+SampleClass}	System.Reflection.MemberInfo {System.RuntimeType}
+		[11]	{System.Reflection.Tests.MemberInfoTests+Base}	System.Reflection.MemberInfo {System.RuntimeType}
+		[12]	{System.Reflection.Tests.MemberInfoTests+Derived}	System.Reflection.MemberInfo {System.RuntimeType}
+		[13]	{System.Reflection.Tests.MemberInfoTests+GBase`1[T]}	System.Reflection.MemberInfo {System.RuntimeType}
+		[14]	{System.Reflection.Tests.MemberInfoTests+GDerived`1[T]}	System.Reflection.MemberInfo {System.RuntimeType}
-		mi2	{System.Reflection.MemberInfo[15]}	System.Reflection.MemberInfo[]
+		[0]	{Void TestGetCustomAttributesData()}	System.Reflection.MemberInfo {System.Reflection.RuntimeMethodInfo}
+		[1]	{Void TestEquality_Multiple()}	System.Reflection.MemberInfo {System.Reflection.RuntimeMethodInfo}
+		[2]	{System.Reflection.MemberInfo[] GetMembers(System.Type)}	System.Reflection.MemberInfo {System.Reflection.RuntimeMethodInfo}
+		[3]	{System.String ToString()}	System.Reflection.MemberInfo {System.Reflection.RuntimeMethodInfo}
+		[4]	{Boolean Equals(System.Object)}	System.Reflection.MemberInfo {System.Reflection.RuntimeMethodInfo}
+		[5]	{Int32 GetHashCode()}	System.Reflection.MemberInfo {System.Reflection.RuntimeMethodInfo}
+		[6]	{System.Type GetType()}	System.Reflection.MemberInfo {System.Reflection.RuntimeMethodInfo}
+		[7]	{Void Finalize()}	System.Reflection.MemberInfo {System.Reflection.RuntimeMethodInfo}
+		[8]	{System.Object MemberwiseClone()}	System.Reflection.MemberInfo {System.Reflection.RuntimeMethodInfo}
+		[9]	{Void .ctor()}	System.Reflection.MemberInfo {System.Reflection.RuntimeConstructorInfo}
+		[10]	{System.Reflection.Tests.MemberInfoTests+SampleClass}	System.Reflection.MemberInfo {System.RuntimeType}
+		[11]	{System.Reflection.Tests.MemberInfoTests+Base}	System.Reflection.MemberInfo {System.RuntimeType}
+		[12]	{System.Reflection.Tests.MemberInfoTests+Derived}	System.Reflection.MemberInfo {System.RuntimeType}
+		[13]	{System.Reflection.Tests.MemberInfoTests+GBase`1[T]}	System.Reflection.MemberInfo {System.RuntimeType}
+		[14]	{System.Reflection.Tests.MemberInfoTests+GDerived`1[T]}	System.Reflection.MemberInfo {System.RuntimeType}
```

**Comment by ericstj** [comment]
Just changing the assembly version of System.Runtime seems to be enough to cause this to fail.  See https://github.com/dotnet/corefx/pull/19849

**Comment by AtsushiKan** [comment]
Reflection does not guarantee a specific order for returned MemberInfo and that includes serial calls in the same thread. In fact, I think the full framework intentionally introduced entropy at times to enforce that. And if it wasn't intentional, there's so much arcane caching logic there, there's probably unintentional entropy there. Nevertheless, that's allowed.

This test is working by accident. It should be doing an unordered set compare, not a ordered list compare.

**Comment by ericstj** [comment]
IIRC didn't we explicitly go out of our way to maintain order of this stuff in desktop for appcompat?  See http://vstfdevdiv:8080/DevDiv2/DevDiv/_workitems/edit/653658.  /cc @jkotas

**Comment by AtsushiKan** [comment]
That fix restored a prior order to fix a specific appcompat problem. It doesn't mean the prior order was deterministic or that CoreCLR/CoreRT (especially CoreRT) would return it the same way.

**Comment by ericstj** [comment]
I see.  I was able to reproduce this by merely changing the version of the test assembly which makes me feel like the ordering issue is less a result of changing the framework vs changing the assembly being reflected on.  I'll disable the test and file an issue.

**Comment by ericstj** [comment]
Need to investigate remaining failures:
- System.Diagnostics.Tests.FileVersionInfoTest.Symlink_ValidFile_Succeeds
- System.Diagnostics.Tests.FileVersionInfoTest.FileVersionInfo_CustomManagedAssembly
- System.Text.Tests.EncodingTest.TestDefaultEncodings

**Comment by ericstj** [comment]
FileVersion ones could be related to https://github.com/dotnet/corefx/pull/19828.  /cc @stephentoub

**Comment by ericstj** [comment]
So get this, its the same reflection issue.  There was already a test that *DELETED* the test assembly: https://github.com/dotnet/corefx/blob/486ad25fec5255bc50396ab76ad5478f2771061c/src/System.Diagnostics.FileVersionInfo/tests/System.Diagnostics.FileVersionInfo.Tests/FileVersionInfoTest.Unix.cs#L72

That test was working before because it happened to be run after the tests that actually used the test assembly.

Now that the reflection ordering changed (per previous test failure) this causes the tests to run in a different order.

**Comment by stephentoub** [comment]
Ugh. "Bad test!" Want me to fix it or are you going to?

**Comment by ericstj** [comment]
I've already fixed it.  I'm looking into the last failure now.

I think we should try to do something to run our tests in different orders on a regular basis to catch this sort of thing more often, but at the same time I don't want random order since that will cause non-deterministic failures.  Perhaps seeding the order that the tests run in with the number of commits?

**Comment by ericstj** [comment]
The encoding test failure was a similar ordering issue.  We don't have a good way for this test to isolate or clean up its state: it registers a provider to a global collection and cannot remove it.  As a workaround I've just merged that test case into the one that requires no registered providers.  @tarekgh if you'd like to do something different please file an issue.

**Comment by stephentoub** [comment]
> We don't have a good way for this test to isolate or clean up its state

We've used RemoteInvoke for things like this elsewhere, so that the code is run in its own process.

**Comment by ericstj** [comment]
That's a big hammer.  Feel free to do that in a separate issue if preferred.

**Comment by tarekgh** [comment]
@ericstj @stephentoub 

> That's a big hammer. Feel free to do that in a separate issue if preferred.

I think for this specific case, it is ok to keep what Eric has. if we find more cases for this tests we can consider the remote execution.

**Pull request merged**
