### PR TITLE
Add path to FillAttributeInfo assert

### PR DESCRIPTION
**Pull request by danmosemsft**
To help investigate https://github.com/dotnet/corefx/issues/35665

### CODE REVIEW

**Comment by danmosemsft** [comment]
Whoa
```
D:\a\1\s\.packages\microsoft.net.compilers.toolset\3.2.0-beta4-19312-15\tasks\netcoreapp2.1\Microsoft.CSharp.Core.targets(59,5): error : Internal CLR error. (0x80131506) [D:\a\1\s\src\System.Collections.NonGeneric\src\System.Collections.NonGeneric.csproj]
##[error].packages\microsoft.net.compilers.toolset\3.2.0-beta4-19312-15\tasks\netcoreapp2.1\Microsoft.CSharp.Core.targets(59,5): error : Internal CLR error. (0x80131506)
D:\a\1\s\.packages\microsoft.net.compilers.toolset\3.2.0-beta4-19312-15\tasks\netcoreapp2.1\Microsoft.CSharp.Core.targets(59,5): error :    at Roslyn.Utilities.SpecializedCollections.EmptyEnumerable[[System.__Canon, System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]]() [D:\a\1\s\src\System.Collections.NonGeneric\src\System.Collections.NonGeneric.csproj]
##[error].packages\microsoft.net.compilers.toolset\3.2.0-beta4-19312-15\tasks\netcoreapp2.1\Microsoft.CSharp.Core.targets(59,5): error :    at Roslyn.Utilities.SpecializedCollections.EmptyEnumerable[[System.__Canon, System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]]()
D:\a\1\s\.packages\microsoft.net.compilers.toolset\3.2.0-beta4-19312-15\tasks\netcoreapp2.1\Microsoft.CSharp.Core.targets(59,5): error :    at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxTree.GetDiagnostics(Microsoft.CodeAnalysis.GreenNode, Int32) [D:\a\1\s\src\System.Collections.NonGeneric\src\System.Collections.NonGeneric.csproj]
##[error].packages\microsoft.net.compilers.toolset\3.2.0-beta4-19312-15\tasks\netcoreapp2.1\Microsoft.CSharp.Core.targets(59,5): error :    at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxTree.GetDiagnostics(Microsoft.CodeAnalysis.GreenNode, Int32)
D:\a\1\s\.packages\microsoft.net.compilers.toolset\3.2.0-beta4-19312-15\tasks\netcoreapp2.1\Microsoft.CSharp.Core.targets(59,5): error :    at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxTree.GetDiagnostics(Microsoft.CodeAnalysis.SyntaxNode) [D:\a\1\s\src\System.Collections.NonGeneric\src\System.Collections.NonGeneric.csproj]
##[error].packages\microsoft.net.compilers.toolset\3.2.0-beta4-19312-15\tasks\netcoreapp2.1\Microsoft.CSharp.Core.targets(59,5): error :    at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxTree.GetDiagnostics(Microsoft.CodeAnalysis.SyntaxNode)
D:\a\1\s\.packages\microsoft.net.compilers.toolset\3.2.0-beta4-19312-15\tasks\netcoreapp2.1\Microsoft.CSharp.Core.targets(59,5): error :    at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxTree.GetDiagnostics(System.Threading.CancellationToken) [D:\a\1\s\src\System.Collections.NonGeneric\src\System.Collections.NonGeneric.csproj]
##[error].packages\microsoft.net.compilers.toolset\3.2.0-beta4-19312-15\tasks\netcoreapp2.1\Microsoft.CSharp.Core.targets(59,5): error :    at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxTree.GetDiagnostics(System.Threading.CancellationToken)
D:\a\1\s\.packages\microsoft.net.compilers.toolset\3.2.0-beta4-19312-15\tasks\netcoreapp2.1\Microsoft.CSharp.Core.targets(59,5): error :    at Microsoft.CodeAnalysis.CSharp.CSharpCompilation+<>c__DisplayClass187_0.<GetDiagnostics>b__0(Int32) [D:\a\1\s\src\System.Collections.NonGeneric\src\System.Collections.NonGeneric.csproj]
##[error].packages\microsoft.net.compilers.toolset\3.2.0-beta4-19312-15\tasks\netcoreapp2.1\Microsoft.CSharp.Core.targets(59,5): error :    at Microsoft.CodeAnalysis.CSharp.CSharpCompilation+<>c__DisplayClass187_0.<GetDiagnostics>b__0(Int32)
D:\a\1\s\.packages\microsoft.net.compilers.toolset\3.2.0-beta4-19312-15\tasks\netcoreapp2.1\Microsoft.CSharp.Core.targets(59,5): error :    at Roslyn.Utilities.UICultureUtilities+<>c__DisplayClass6_0`1[[System.Int32, System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].<WithCurrentUICulture>b__0(Int32) [D:\a\1\s\src\System.Collections.NonGeneric\src\System.Collections.NonGeneric.csproj]
##[error].packages\microsoft.net.compilers.toolset\3.2.0-beta4-19312-15\tasks\netcoreapp2.1\Microsoft.CSharp.Core.targets(59,5): error :    at Roslyn.Utilities.UICultureUtilities+<>c__DisplayClass6_0`1[[System.Int32, System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].<WithCurrentUICulture>b__0(Int32)
D:\a\1\s\.packages\microsoft.net.compilers.toolset\3.2.0-beta4-19312-15\tasks\netcoreapp2.1\Microsoft.CSharp.Core.targets(59,5): error :    at System.Threading.Tasks.Parallel+<>c__DisplayClass19_0`1[[System.__Canon, System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].<ForWorker>b__1(System.Threading.Tasks.RangeWorker ByRef, Int32, Boolean ByRef) [D:\a\1\s\src\System.Collections.NonGeneric\src\System.Collections.NonGeneric.csproj]
##[error].packages\microsoft.net.compilers.toolset\3.2.0-beta4-19312-15\tasks\netcoreapp2.1\Microsoft.CSharp.Core.targets(59,5): error :    at System.Threading.Tasks.Parallel+<>c__DisplayClass19_0`1[[System.__Canon, System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].<ForWorker>b__1(System.Threading.Tasks.RangeWorker ByRef, Int32, Boolean ByRef)
D:\a\1\s\.packages\microsoft.net.compilers.toolset\3.2.0-beta4-19312-15\tasks\netcoreapp2.1\Microsoft.CSharp.Core.targets(59,5): error :    at System.Threading.Tasks.TaskReplicator+Replica`1[[System.Threading.Tasks.RangeWorker, System.Threading.Tasks.Parallel, Version=4.0.3.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a]].ExecuteAction(Boolean ByRef) [D:\a\1\s\src\System.Collections.NonGeneric\src\System.Collections.NonGeneric.csproj]
##[error].packages\microsoft.net.compilers.toolset\3.2.0-beta4-19312-15\tasks\netcoreapp2.1\Microsoft.CSharp.Core.targets(59,5): error :    at System.Threading.Tasks.TaskReplicator+Replica`1[[System.Threading.Tasks.RangeWorker, System.Threading.Tasks.Parallel, Version=4.0.3.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a]].ExecuteAction(Boolean ByRef)
D:\a\1\s\.packages\microsoft.net.compilers.toolset\3.2.0-beta4-19312-15\tasks\netcoreapp2.1\Microsoft.CSharp.Core.targets(59,5): error :    at System.Threading.Tasks.TaskReplicator+Replica.Execute() [D:\a\1\s\src\System.Collections.NonGeneric\src\System.Collections.NonGeneric.csproj]
##[error].packages\microsoft.net.compilers.toolset\3.2.0-beta4-19312-15\tasks\netcoreapp2.1\Microsoft.CSharp.Core.targets(59,5): error :    at System.Threading.Tasks.TaskReplicator+Replica.Execute()
```

**Comment by ViktorHofer** [comment]
cc @ericstj another internal CLR error hit.

**Comment by danmosemsft** [comment]
@dotnet/dnceng this shows a fireball for driveinfo tests
https://mc.dot.net/#/user/dotnet-bot/pr~2Fdotnet~2Fcorefx~2Frefs~2Fpull~2F38709~2Fmerge/test~2Ffunctional~2Fcli~2Finnerloop~2F/20190619.82
AzDo shows them as completed
But no log exists at all: https://mc.dot.net/#/user/dotnet-bot/pr~2Fdotnet~2Fcorefx~2Frefs~2Fpull~2F38709~2Fmerge/test~2Ffunctional~2Fcli~2Finnerloop~2F/20190619.82/workItem/System.IO.FileSystem.DriveInfo.Tests/wilogs
Can you help me figure this out?

**Comment by MattGal** [comment]
> @dotnet/dnceng this shows a fireball for driveinfo tests
> https://mc.dot.net/#/user/dotnet-bot/pr~2Fdotnet~2Fcorefx~2Frefs~2Fpull~2F38709~2Fmerge/test~2Ffunctional~2Fcli~2Finnerloop~2F/20190619.82
> AzDo shows them as completed
> But no log exists at all: https://mc.dot.net/#/user/dotnet-bot/pr~2Fdotnet~2Fcorefx~2Frefs~2Fpull~2F38709~2Fmerge/test~2Ffunctional~2Fcli~2Finnerloop~2F/20190619.82/workItem/System.IO.FileSystem.DriveInfo.Tests/wilogs
> Can you help me figure this out?

@danmosemsft Some notes:

- Relevant AzDO log notes that tests failed:
```
D:\a\1\s\.packages\microsoft.dotnet.helix.sdk\2.0.0-beta.19320.1\tools\Microsoft.DotNet.Helix.Sdk.MultiQueue.targets(67,5): error : Work item System.IO.FileSystem.DriveInfo.Tests in job 2f8c5b01-6063-479e-a3ef-fd1a6d5824fc has failed, logs available here: https://helix.dot.net/api/2018-03-14/jobs/2f8c5b01-6063-479e-a3ef-fd1a6d5824fc/workitems/System.IO.FileSystem.DriveInfo.Tests/console. [D:\a\1\s\eng\sendtohelix.proj]
```
The logs on the linked MC.dot.net site show timeout whilst trying to uninstall the app (possibly a strange dialog popped that the dialog handler had trouble with, possibly just a hang).  Relevant snippets:

```
C:\dotnetbuild\work\2f8c5b01-6063-479e-a3ef-fd1a6d5824fc\Work\f85aa381-786a-4c3b-8e9d-b6f1cec52cdc\Exec>call "C:\dotnetbuild\work\2f8c5b01-6063-479e-a3ef-fd1a6d5824fc\Payload\Launcher\WindowsStoreAppLauncher.exe" -uninstall appxmanifest.xml System.IO.FileSystem.DriveInfo.Tests.dll 
Got manifest file appxmanifest.xml
Removing the application...
```
... and 
```
2019-06-20 15:29:52,412: ERROR: job(46): kill: Job running for too long. Killing...
2019-06-20 15:29:52,412: ERROR: executor(556): _execute_command: Executor timed out after 900 seconds and was killed.
2019-06-20 15:29:52,412: INFO: event(42): send: Sending event type WorkItemTimeout
...
2019-06-20 15:30:03,905: INFO: servicebusrepository(95): renew_workitem_lock: Renewed work item lock. Status Code: 200
2019-06-20 15:30:12,954: INFO: executor(576): _execute_command: Finished _execute_command, exit code: -3
```

Couple more things to note:
- The way Kusto ingestion works, you may not see logs for 2-3 minutes after a work item completes despite that we may already know the exit code and that it timed out.
- Work items that time out don't currently manage to report to AzDO, but I don't _think_ this is what you're talking about.

I'm happy to stop by and discuss further, if I'm missing something though!

**Comment by danmosemsft** [comment]
@mattgal thanks for the information - I think my confusion was due to that 2-3 minute delay.

**Comment by danmosemsft** [comment]
@ViktorHofer this I guess is not actionable, but the hang was here:
```
C:\dotnetbuild\work\2f8c5b01-6063-479e-a3ef-fd1a6d5824fc\Work\f85aa381-786a-4c3b-8e9d-b6f1cec52cdc\Exec>call "C:\dotnetbuild\work\2f8c5b01-6063-479e-a3ef-fd1a6d5824fc\Payload\Launcher\WindowsStoreAppLauncher.exe" -uninstall appxmanifest.xml System.IO.FileSystem.DriveInfo.Tests.dll 
Got manifest file appxmanifest.xml
Removing the application...
```

**Comment by danmosemsft** [comment]
Merging as the tests did pass.

**Pull request merged**
