### PR TITLE
Update to a xUnit Performance Api that has a bigger Etw buffer size. …

### PR DESCRIPTION
**Pull request by jorive**
…(#29229)

These change is to alleviate the frequent failures on the Concurrent tests due to the lost of events, which blocks uploading any data on Windows.

### CODE REVIEW

**Comment by jorive** [comment]
@dotnet/rap-team PTAL

**Comment by jorive** [comment]
@dotnet-bot test ci please

**Comment by jorive** [comment]
What is this `CROSS Check Pending — Triggered.`?

**Comment by jorive** [comment]
@dotnet/dnceng What is this `CROSS Check Pending — Triggered.`?

**Comment by MattGal** [comment]
@jorive it's a Jenkins job that checks ... something ... for Open source compliance: https://ci.dot.net/job/dotnet_corefx/job/master/job/CROSS_check_prtest/ 

Since you're just touching project files here, I think you can safely choose to ignore it or wait.  Looks like there's 3 jobs waiting in the queue given the above link.

**Pull request merged**
