### PR TITLE
Commit initial set of Console tests.

### PR DESCRIPTION
**Pull request by ellismg**
This is #572 except against the v1.0 branch plus responses to all of @weshaggard's feedback.

### CODE REVIEW

**Comment by ellismg** [comment]
It turns out in addition to the packages.config needing some stuff that @weshaggard wanted removed (in order to satisfy runtime dependencies) the tests themselves are a little flaky, failing on machine about 20% of the time.  I am going to look at fixing these or disabling the flaky ones before submitting.

**Comment by ellismg** [comment]
@nguerrera @MattGal Do either of you mind taking a look?

Also, it's unclear to me if we should keep the donet-bot commit or rebase it away.  I am keeping it for review so you can see what changed between the two implementations of the tests and see if I dropped any coverage.

I am also interested in seeing what the code coverage numbers end up saying after this is in.

**Comment by nguerrera** [comment]
Thanks for cleaning these up! We should be doing this to all of the ancient tests...

I see you've collapsed many asserts in to one test method. I often do that too to be honest, but some folks like @davkean strongly suggest 1 assert per test method wherever possible. There are definitely benefits to following that guidance. @davkean, you wrote up some internal docs on do's and don'ts of unit tests while rewriting some other old tests.  Can you share those on the wiki somewhere?

**Comment by nguerrera** [comment]
LGTM other than the small comments. 

Consider the 1 assert per method thing a separate side discussion not code review feedback for initial commit.

**Comment by nguerrera** [comment]
Also, I like the dotnet-bot commits auto-converted ancient tests, team dev cleans them up patter for code reviews moving forward. :)

**Comment by ellismg** [comment]
Thanks @nguerrera.  I addressed your feedback.  I'd be happy to address @davkean's feedback at a later date.  I suppose the issue is that when you couple a bunch of things together (e.g. the work done in NegativeTesting) it makes it hard to understand from the log file what specifically is breaking?

FWIW, I worry that strict adherence to that guidance will leads to tons of test which may lose value.  I can understand splitting up the negative tests into a bunch of cases, but factoring them further so that they are duplicated for both StandardOut and Error seems like it would be a net loss to me.

**Pull request merged**
