### PR TITLE
Update badges to point to new job locations

### PR DESCRIPTION
**Pull request by mmitche**

### CODE REVIEW

**Comment by stephentoub** [comment]
LGTM

**Comment by weshaggard** [comment]
Is there any way to parameterize these based on the branch name?

**Comment by stephentoub** [comment]
> Is there any way to parameterize these based on the branch name?

In a .md?  I'm not aware of any.  If there is that'd be cool.

**Comment by weshaggard** [comment]
I'm not aware of any either, just thought I would throw the question out there.

**Pull request merged**
