### PR TITLE
Merge master into dev/metadata

### PR DESCRIPTION
**Pull request by AlexGhiondea**
@tmat @stephentoub @nguerrera

### CODE REVIEW

**Comment by stephentoub** [comment]
@AlexGhiondea, were there any conflicts you needed to resolve?

**Comment by AlexGhiondea** [comment]
@stephentoub yes -- around versions in the project.json files.

**Comment by stephentoub** [comment]
Ok, thanks. In that case, LGTM as long as it passes CI.

**Comment by AlexGhiondea** [comment]
@dotnet-bot please test this.

**Comment by AlexGhiondea** [comment]
@dotnet-bot test this please

**Comment by AlexGhiondea** [comment]
Apparently I used the wrong incantation to trigger a new test build. Trying again :).

**Comment by stephentoub** [comment]
@dotnet-bot test this please

**Pull request merged**
