### PR TITLE
updating project.lock.json

### PR DESCRIPTION
**Pull request by venkat-raman251**
updated project.lock.json for corresponding changes in the project.json file.

### CODE REVIEW

**Comment by stephentoub** [comment]
cc: @ericstj 

LGTM

**Comment by mellinoe** [comment]
LGTM

**Comment by mellinoe** [comment]
@dotnet-bot  test this, please

**Comment by venkat-raman251** [comment]
@stephentoub , @ericstj  : I see that there are test failures in other libraries. I'd assume my commit should not affect any other library. Could you please clarify? Thanks

**Comment by stephentoub** [comment]
Your change shouldn't have affected this, but I'm running it again... all of our ETW tests failed.

**Comment by stephentoub** [comment]
@dotnet-bot test this please

**Comment by ericstj** [comment]
LGTM

**Comment by venkat-raman251** [comment]
@stephentoub  : still failing. do I just go ahead and merge? or wait

**Comment by stephentoub** [comment]
Please hold off until we get this figured out, just in case.

@ellismg, on multiple runs now, all of our ETW tests (across different projects) have failed on Linux.  Has something changed in mscorlib in CoreCLR recently that could have affected this?

**Comment by ellismg** [comment]
I don't think so.  Let me dig in.

**Comment by Maxwe11** [comment]
@dotnet-bot test this please

**Comment by venkat-raman251** [comment]
Can it be merged now?

**Pull request merged**
