### PR TITLE
Fix issues with XUnit Desktop behavior and CoreFX tests on UWP

### PR DESCRIPTION
**Pull request by MattGal**
A couple test fixes that fell out of recent bugs and package restore improvements:

Fix Xunit return code / file creation behavior:
- Update Xunit.console.netcore - now has same behavior as 2.2.0 Desktop version for exit codes
- Update Microsoft.DotNet.BUildTools to 1.0.26-prerelease-00921-01, to pick up a runner script that can honor the exit code from above instead of hide it.

Fix UWP tests:
- Update Microsoft.DotNet.BuildTools.TestSuite  1.0.0-prerelease-00921-01 - Pick up native compilation package
- Update microsoft.xunit.runner.uwp to 1.0.3-prerelease-00921-01 - Various fixes included in PR
- Microsoft.xunit.netcore.extensions to 1.0.0-prerelease-00920-01 - Same

### CODE REVIEW

**Comment by MattGal** [comment]
@weshaggard, @ellismg 
This change addresses all the recent issues around Desktop execution (where return code indicates failure but we "pass" due to result xml creation) and UWP execution.

**Comment by MattGal** [comment]
@dotnet-bot Test this please

**Comment by MattGal** [comment]
@dotnet-bot test Innerloop Ubuntu14.04 Debug Build and Test

**Comment by MattGal** [comment]
I've rebased on master this morning;  thus far there seems to be nothing wrong with the changes but I've hit flaky tests, test breaks, DDoS outage, and various version updates.  It would be very good to merge this today for UWP and desktop test execution.

**Comment by weshaggard** [comment]
LGTM

**Pull request merged**
