### PR TITLE
Remove FEATURE_INTERPRET from System.Linq.Expressions

### PR DESCRIPTION
**Pull request by JonHanna**
Since it's been set on every build for some time, it no longer serves any purpose, and it existing implies it could perhaps not be set.

### CODE REVIEW

**Comment by jkotas** [comment]
@marek-safar @luhenry Are you using this define in Mono?

**Comment by jkotas** [comment]
In any case,

**Comment by marek-safar** [comment]
@jkotas we don't, we use FEATURE_COMPILE and FEATURE_COMPILE_TO_METHODBUILDER to control Reflection.Emit behaviour

**Comment by JonHanna** [comment]
As is, it doesn't wrap enough to gain a code-size benefit (of course, we could go the other way and wrap more code that is only relevant with it defined) but just the behaviour of it being requested by the user (if not defined their passing true would be ignored). The tests though have more blocks wrapped in it.

**Comment by VSadov** [comment]
I think we should keep this for now. 
The other reason is that desktop counterpart does not have interpreter support. If we are to port the interpreter, (for whatever reason - I heard that for run-once code interpreting could be faster than compiling), it would be nice to know where the pieces are. Even if it is not completely precise, it could be helpful.

And yes, there is a possibility that we may get a sufficiently complete and fast IL interpreter + S.R.Emit support. Not sure how soon this can reasonably happen, but that may cause us to consider removing ET interpreter. After all the main justification for the interpreter is to support environments where dynamic IL cannot run.

**Comment by JonHanna** [comment]
If anything there should probably be more code wrapped in this then (which is not to say I'm planning on adding them in any time soon, unless there's an actual immediate benefit to it).

**Pull request closed without merging**
