### PR TITLE
[release/2.1] Enable Tizen CI

### PR DESCRIPTION
**Pull request by gbalykov**
cc @alpencolt

### CODE REVIEW

**Comment by wtgodbe** [comment]
@dotnet-bot test CI please

**Comment by wtgodbe** [comment]
@dotnet-bot test Linux x64 Release Build

**Comment by wtgodbe** [comment]
@gbalykov Is there anything else you need to do here before we think about merging?

**Comment by gbalykov** [comment]
@wtgodbe we need to wait for https://github.com/dotnet/coreclr/pull/19058 to get to sdk first, because build with tizen.5.0.0 RID doesn't work yet

**Comment by wtgodbe** [comment]
@gbalykov any update?

**Comment by gbalykov** [comment]
@wtgodbe release/2.1 Tizen builds should work now, but master builds do not work yet, this is work in progress

**Comment by gbalykov** [comment]
@dotnet-bot test ci please

**Comment by gbalykov** [comment]
@dotnet-bot test OSX x64 Debug Build
@dotnet-bot test Windows x86 Release Build

**Comment by gbalykov** [comment]
@dotnet-bot test ci please

**Comment by stephentoub** [comment]
@gbalykov, is this still blocked? From your comment almost a month ago it sounds like this can now be merged?

**Comment by gbalykov** [comment]
@stephentoub this should work now, but I was not able to test Tizen CI on this PR, as `test ci please` doesn't seem to regenerate ci jobs. Could you, please, try `test ci please`?

**Comment by stephentoub** [comment]
@dotnet-bot test ci please

**Comment by gbalykov** [comment]
@stephentoub tizen jobs are not regenerated, do you know what could be the reason of this?

**Comment by stephentoub** [comment]
> tizen jobs are not regenerated, do you know what could be the reason of this?

@mmitche?  Do we not regenerate jobs as part of part of asking to test ci please?  I remember that used to be the case, and you had to actually merge and then subsequent PRs would pick it up, but I thought that changed. No?

**Comment by mmitche** [comment]
@stephentoub It still only generates disabled jobs for verification, it does not do anything to the jobs on this PR.  That will change as we move to Azure DevOps.

**Comment by gbalykov** [comment]
@stephentoub for some reason `Gen CI(dotnet-ci) - release/2.1/netci.groovy` has started just few minutes ago, and looks like it has generated tizen jobs

**Comment by gbalykov** [comment]
@dotnet-bot test Tizen armel Release Build

**Comment by stephentoub** [comment]
@dotnet-bot test OSX x64 Debug Build please

**Comment by gbalykov** [comment]
@dotnet-bot test OSX x64 Debug Build please

**Comment by gbalykov** [comment]
@dotnet-bot test OSX x64 Debug Build please

**Comment by gbalykov** [comment]
@dotnet-bot test OSX x64 Debug Build please

**Comment by gbalykov** [comment]
@dotnet-bot test OSX x64 Debug Build please

**Comment by gbalykov** [comment]
@dotnet-bot test OSX x64 Debug Build please

**Comment by gbalykov** [comment]
@dotnet-bot test OSX x64 Debug Build please

**Comment by gbalykov** [comment]
@dotnet-bot test OSX x64 Debug Build please

**Comment by gbalykov** [comment]
@stephentoub CI testing has fully passed

**Comment by stephentoub** [comment]
@danmosemsft, can this be merged? (release/2.1)

**Comment by danmosemsft** [comment]
Merged to match https://github.com/dotnet/coreclr/pull/19410 per discussion.

**Pull request merged**
