### PR TITLE
Fix WorkingSet{64} on Linux to be bytes, not pages

### PR DESCRIPTION
**Pull request by stephentoub**
Fixes https://github.com/dotnet/corefx/issues/13423

cc: @priya91, @ayende

### CODE REVIEW

**Comment by Priya91** [comment]
@dotnet-bot test Innerloop Linux ARM Emulator SoftFP Debug Cross Build

**Comment by danmosemsft** [comment]
I guess the ARM job is failing because of `13:42:38 ./scripts/arm32_ci_script.sh: line 170: /opt/linux-arm-emulator-root/dotnet/setenv/setenv_incpath.sh: No such file or directory`. This is from arm32_ci_script.sh and I don't know what is supposed to place the file.

**Comment by danmosemsft** [comment]
@mmitche do you know who might know about setenv_incpath.sh ?

**Comment by mellinoe** [comment]
@danmosemsft That happens quite often. https://github.com/dotnet/corefx/issues/13394.

@dotnet-bot Test Innerloop Linux ARM Emulator SoftFP Debug Cross Build

**Pull request merged**
