### PR TITLE
Revert "Fix some named mutex tests"

### LINKED ISSUE #8745: failure in System.Threading.Tests.MutexTests.AbandonExisting
@kouvel It seems these tests should not be enabled for Ubuntu?

System.PlatformNotSupportedException : Named synchronization primitives are not supported on this platform.

http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/master/job/ubuntu14.04_debug_prtest/1439/

### PR DESCRIPTION
**Pull request by kouvel**
Reverts dotnet/corefx#8625

The PR had showed green when I merged, I thought tests had passed and it was green but I guess it hadn't run any tests and showed green. It looks like there are failures due to CoreFX tests not using the latest CoreCLR bits. Reverting the change for now, will try again later. Sorry about that!

Fixes #8745

### CODE REVIEW

**Comment by kouvel** [comment]
@sergiy-k @danmosemsft

**Comment by kouvel** [comment]
@dotnet-bot test this please

**Comment by danmosemsft** [comment]
NP thanks!

**Comment by bartonjs** [comment]
LGTM

**Pull request merged**
