### PR TITLE
Reflection cleanup

### PR DESCRIPTION
**Pull request by venkat-raman251**
Formatting changes for System.Reflection.TypeExtensions

### CODE REVIEW

**Comment by stephentoub** [comment]
The changes look fine, but can you squash this?

**Comment by ellismg** [comment]
You also need to update your git author setting so you have your @microsoft.com e-mail instead of your personal e-mail, so the commits are owned by the right person:

`git config --global user.email "the-address-you-have-on-your-github-account@microsoft.com"`

You should also not have the merge commit there, instead rebase on top of master.

**Comment by venkat-raman251** [comment]
@ellismg : Changed e-mail. How do I rebase and undo the merge commit?
@stephentoub :This is the first time I am commiting on github/corefx. What does squash mean?

**Comment by Maxwe11** [comment]
>What does squash mean?

Squash means that you merge multiple commits into one. Squashing it's a one of the features of rebasing.

>How do I rebase and undo the merge commit?

I think it will be deleted when you squash.
Try to google about `git interactive rebase`.

**Comment by ellismg** [comment]
Here is what I would do if I was you:

```
> git checkout reflection-cleanup
```

This moves you back to your reflection-cleanup branch, you might already have it checked out but this can't hurt.

```
>  git reset --hard 24c43ac
```

This resets the HEAD pointer for your branch to point to 24c43ac (which was the commit before the merge of "master" into your branch.  This effectively removes the commit from your branch.

```
> git fetch upstream
> git rebase upstream/master
```
 
This pulls the changes from the remote called "upstream" (which should be dotnet/corefx) and then replays the new changes in your branch on top of of the new master.

Finally, to sqash, things, you do an interactive rebase of the last three changes:

```
> git rebase -i HEAD~3
```

That will give you a file that looks like this:

```
pick b8104e4 Changed Assert.true to Assert.Equal
pick 560e531 Revert "Changed Assert.true to Assert.Equal"
pick d2acd3c formatting changes

# Rebase 0a64812..d2acd3c onto 0a64812
#
# Commands:
#  p, pick = use commit
#  r, reword = use commit, but edit the commit message
#  e, edit = use commit, but stop for amending
#  s, squash = use commit, but meld into previous commit
#  f, fixup = like "squash", but discard this commit's log message
#  x, exec = run command (the rest of the line) using shell
#
# These lines can be re-ordered; they are executed from top to bottom.
#
# If you remove a line here THAT COMMIT WILL BE LOST.
#
# However, if you remove everything, the rebase will be aborted.
#
# Note that empty commits are commented out
```

In this case, we want to discard the first two commits (since they cancel each out), so just delete the lines from the file.  I would then change the third commit from "pick" to "reword" so you will get a chance to edit the commit message.  Save the file and close your editor and then git will chew on this for a while and give you a chance to edit the new commit message.

You'll also want to update the e-mail address on the single commit now, you can do that by doing:

```> git commit --amend --reset-author```

After you have done the rebase and when the editor comes up save the message and exit.  Once that's done you can use `git log` to make sure the history looks correct.

**Comment by stephentoub** [comment]
@venkat-raman251, what's the status of this?  Are you planning on continuing with this PR, or should this be closed?

**Comment by venkat-raman251** [comment]
I think this can be closed. I seem to be having some trouble with it. I can re-open a pull request with a few more changes.

**Comment by stephentoub** [comment]
Ok. Thanks.

**Pull request closed without merging**
