### PR TITLE
Merge master into dev/api

### PR DESCRIPTION
**Pull request by joperezr**
Merging branch master into dev/api

cc: @weshaggard @danmosemsft @stephentoub @ericstj 
FYI: @tarekgh @sepidehMS

### CODE REVIEW

**Comment by joperezr** [comment]
Changes that I had to do in order to get this building are in bf7911a

**Comment by joperezr** [comment]
Looking into the non-Windows test failures...

**Comment by joperezr** [comment]
After analyzing the tests failures in an OSX and an Ubuntu machine, looks like the 8 test projects that have failures are all because of the same reason: They are missing System.Security.Cryptography.Native.OpenSsl native binary in the test folder. I checked and it looks like that package doesn't exist yet in the dev/api myget feed, and I can't seem to get it to work by adding a .pkgproj reference to the native project that drops that binary. Any help is appreciated.

**Comment by stephentoub** [comment]
> I checked and it looks like that package doesn't exist yet in the dev/api myget feed

Could the one from the core feed be manually pushed to dev-api feed for bootstrapping?

**Comment by steveharter** [comment]
FWIW diff on master vs dev\api from https://github.com/dotnet/versions/tree/master/build-info/dotnet/corefx shows these as missing (not just OpenSsl):

runtime.debian.8-x64.runtime.native.System.Security.Cryptography.OpenSsl
runtime.fedora.23-x64.runtime.native.System.Security.Cryptography.OpenSsl
runtime.native.System.Security.Cryptography.OpenSsl
runtime.opensuse.13.2-x64.runtime.native.System.Security.Cryptography.OpenSsl
runtime.opensuse.42.1-x64.runtime.native.System
runtime.opensuse.42.1-x64.runtime.native.System.IO.Compression
runtime.opensuse.42.1-x64.runtime.native.System.Net.Http
runtime.opensuse.42.1-x64.runtime.native.System.Net.Security
runtime.opensuse.42.1-x64.runtime.native.System.Security.Cryptography
runtime.opensuse.42.1-x64.runtime.native.System.Security.Cryptography.OpenSsl
runtime.osx.10.10-x64.runtime.native.System.Security.Cryptography.OpenSsl
runtime.rhel.7-x64.runtime.native.System.Security.Cryptography.OpenSsl
runtime.ubuntu.14.04-x64.runtime.native.System.Security.Cryptography.OpenSsl
runtime.ubuntu.16.04-x64.runtime.native.System.Security.Cryptography.OpenSsl
runtime.ubuntu.16.10-x64.runtime.native.System
runtime.ubuntu.16.10-x64.runtime.native.System.IO.Compression
runtime.ubuntu.16.10-x64.runtime.native.System.Net.Http
runtime.ubuntu.16.10-x64.runtime.native.System.Net.Security
runtime.ubuntu.16.10-x64.runtime.native.System.Security.Cryptography
runtime.ubuntu.16.10-x64.runtime.native.System.Security.Cryptography.OpenSsl

Here's the new ones:
System.Diagnostics.Debug.SymbolReader
System.Json
System.Private.Xml
System.Private.Xml.Linq
System.Security.Permissions
System.Transactions

**Comment by joperezr** [comment]
> Could the one from the core feed be manually pushed to dev-api feed for bootstrapping?

we could, but I believe that wouldn't be enough as we would also need to push an update for Microsoft.NETCore.Targets package since this is the one that pulls the openSsl native package in. Given there is already one of these in our feed with the matching prerelease, I believe we would have to remove the one that's there and then push the updated version of it keeping the same prerelease. One other option, would be to disable these 8 test projects for non-Windows runs until we update the corefx packages in dev/api, which would even probably happen today as well.

@stephentoub @weshaggard thoughts?

**Comment by ericstj** [comment]
I would have expected your change for TestWithLocalNativeLibraries to actually have solved this.  Let's look at a repro to find out why that's not happening.

**Comment by joperezr** [comment]
With the help of @ericstj I finally know what the problem is and how to fix it. It will require a buildtools update. I'll update this PR very soon.

**Comment by joperezr** [comment]
@dotnet-bot test Innerloop CentOS7.1 Release Build and Test please (segfault during System.Runtime.Tests)

**Comment by davidsh** [comment]
Due to PR #11341 you might want to run some [outerloop] passes on this. Otherwise you are not getting any networking test coverage.

**Comment by joperezr** [comment]
@davidsh I didn't get those changes as part of this merge. Last commit I got from master was 022a8c2088582c3175e7aee4ad4c97c3cea58a28 which I think happened before your merge.

**Comment by davidsh** [comment]
>@davidsh I didn't get those changes as part of this merge. Last commit I got from master was 022a8c2 which I think happened before your merge.

Ok.  Then it is something to do for future merges.

**Pull request merged**
