### PR TITLE
Update ApiCompatBaseline for uap and uapaot for System.Runtime

### PR DESCRIPTION
**Pull request by ahsonkhan**
cc @jkotas, @weshaggard

### CODE REVIEW

**Comment by ahsonkhan** [comment]
For uapaot, it looks like we still need to keep some of the methods in the baseline. Any ideas why all the changes didn't propagate? Are we waiting on a mirror or new build?

```text
D:\GitHub\Fork\corefx\Tools\ApiCompat.targets(58,5): error : MembersMustExist : Member 'System.ReadOnlySpan<T>.GetPinnableReference()' does not exist in the implementation but it does exist in the contract. [D:\GitHub\Fork\corefx\src\Sy
stem.Runtime\src\System.Runtime.csproj]
D:\GitHub\Fork\corefx\Tools\ApiCompat.targets(58,5): error : MembersMustExist : Member 'System.Span<T>.GetPinnableReference()' does not exist in the implementation but it does exist in the contract. [D:\GitHub\Fork\corefx\src\System.Run
time\src\System.Runtime.csproj]
D:\GitHub\Fork\corefx\Tools\ApiCompat.targets(58,5): error : MembersMustExist : Member 'System.Buffers.MemoryManager<T>.CreateMemory(System.Int32)' does not exist in the implementation but it does exist in the contract. [D:\GitHub\Fork\
corefx\src\System.Runtime\src\System.Runtime.csproj]
D:\GitHub\Fork\corefx\Tools\ApiCompat.targets(58,5): error : MembersMustExist : Member 'System.Buffers.MemoryManager<T>.CreateMemory(System.Int32, System.Int32)' does not exist in the implementation but it does exist in the contract. [D
:\GitHub\Fork\corefx\src\System.Runtime\src\System.Runtime.csproj]
```

**Comment by jkotas** [comment]
> Any ideas why all the changes didn't propagate?

Some of the changes were missed by the CoreCLR -> CoreRT mirror. @Anipik Could you please take look?

**Comment by ahsonkhan** [comment]
@dotnet-bot test Linux x64 Release Build
@dotnet-bot test NETFX x86 Release Build
@dotnet-bot test Windows x64 Debug Build 
@dotnet-bot test Windows x86 Release Build

**Comment by ahsonkhan** [comment]
@dotnet-bot test Linux x64 Release Build
@dotnet-bot test NETFX x86 Release Build
@dotnet-bot test Windows x64 Debug Build 
@dotnet-bot test Windows x86 Release Build

**Comment by ahsonkhan** [comment]
CI is failing consistently across several PRs - https://github.com/dotnet/core-eng/issues/3293

**Comment by ahsonkhan** [comment]
@dotnet-bot test Linux x64 Release Build
@dotnet-bot test NETFX x86 Release Build
@dotnet-bot test Windows x64 Debug Build 
@dotnet-bot test Windows x86 Release Build
@dotnet-bot test OSX x64 Debug Build

**Comment by morganbr** [comment]
I ran into something similar in #28936, but assumed it was something I was doing wrong. Does this end up aligning these APIs for ProjectN, CoreRT and CoreFX?

**Comment by ahsonkhan** [comment]
> Does this end up aligning these APIs for ProjectN, CoreRT and CoreFX?

Mostly, yes. There still seem to be 4 APIs missing in ProjectN: https://github.com/dotnet/corefx/pull/29138/files#diff-471e23afe8a5d9e9ad4553d3c90b795cR2

**Comment by ahsonkhan** [comment]
> Some of the changes were missed by the CoreCLR -> CoreRT mirror. @Anipik Could you please take look?

@safern, can you please help with this?

**Comment by ahsonkhan** [comment]
@jkotas, good to merge?

**Comment by Anipik** [comment]
sorry I just saw it. I am on it

**Comment by Anipik** [comment]
@ahsonkhan I opened the mirror PR. I will take care of other missing commits also after it got merged :)

**Pull request merged**
