### PR TITLE
Betterness for Queue.Contains

### PR DESCRIPTION
**Pull request by jamesqo**
Use `Array.IndexOf` instead of manually looping. Related pr for Stack: #9947

@stephentoub, @ianhays

### CODE REVIEW

**Comment by stephentoub** [comment]
LGTM. Thanks, @jamesqo.

**Comment by stephentoub** [comment]
Though, to be sure, can you please share some performance results across several Ts, both primitives and non-primitives?

**Comment by jamesqo** [comment]
@stephentoub Done: https://gist.github.com/jamesqo/5e4629cf6e8e13617f952eab97119090 Even for types where the comparison is non-trivial, e.g. `string` or `ValueTuple<string>`, there seems to be a noticeable speedup for large Queues.

**Comment by stephentoub** [comment]
Thanks.

**Pull request merged**
