### PR TITLE
Fix missing .NET Core argument validation for PrivateFontCollection.AddFontFile

### LINKED ISSUE #21558: [porting] PrivateFontCollection has different argument validation in netfx and netcoreapp
```cs
[ConditionalFact(nameof(PlatformDetection) + "." + nameof(PlatformDetection.IsNotWindowsNanoServer))]
public void AddFontFile_NullFileName_ThrowsArgumentNullException()
{
    using (var fontCollection = new PrivateFontCollection())
    {
        AssertExtensions.Throws<ArgumentNullException>("path", () => fontCollection.AddFontFile(null));
    }
}

[ConditionalFact(nameof(PlatformDetection) + "." + nameof(PlatformDetection.IsNotWindowsNanoServer))]
public void AddFontFile_InvalidPath_ThrowsArgumentException()
{
    using (var fontCollection = new PrivateFontCollection())
    {
        AssertExtensions.Throws<ArgumentException>(null, () => fontCollection.AddFontFile(string.Empty));
    }
}

[ConditionalFact(nameof(PlatformDetection) + "." + nameof(PlatformDetection.IsNotWindowsNanoServer))]
public void AddFontFile_NoSuchFilePath_ThrowsArgumentException()
{
    using (var fontCollection = new PrivateFontCollection())
    {
        Assert.Throws<FileNotFoundException>(() => fontCollection.AddFontFile("fileName"));
    }
}

[ConditionalFact(nameof(PlatformDetection) + "." + nameof(PlatformDetection.IsNotWindowsNanoServer))]
public void AddFontFile_LongFilePath_ThrowsPathTooLongException()
{
    using (var fontCollection = new PrivateFontCollection())
    {
        Assert.Throws<PathTooLongException>(() => fontCollection.AddFontFile(new string('a', 261)));
    }
}
```

These tests pass with netfx. On .NET core, they fail with:
```
  Discovering: System.Drawing.Common.Tests
  Discovered:  System.Drawing.Common.Tests
  Starting:    System.Drawing.Common.Tests
     System.Drawing.Tests.BrushTests.Dispose_NoSuchEntryPoint_SilentyCatchesException [SKIP]
        Condition(s) not met: \"IsWindowsNanoServer\"
     System.Drawing.Text.Tests.PrivateFontCollectionTests.AddFontFile_InvalidPath_ThrowsArgumentException [FAIL]
        Assert.Throws() Failure
        Expected: typeof(System.ArgumentException)
        Actual:   typeof(System.IO.FileNotFoundException): File not found.
        Stack Trace:
              at System.Drawing.SafeNativeMethods.Gdip.CheckStatus(Int32 status)
              at System.Drawing.Text.PrivateFontCollection.AddFontFile(String filename)
              at System.Drawing.Text.Tests.PrivateFontCollectionTests.<>c__DisplayClass3_0.<AddFontFile_InvalidPath_Thr
  owsArgumentException>b__0()
     System.Drawing.Text.Tests.PrivateFontCollectionTests.AddFontFile_LongFilePath_ThrowsPathTooLongException [FAIL]
        Assert.Throws() Failure
        Expected: typeof(System.IO.PathTooLongException)
        Actual:   typeof(System.IO.FileNotFoundException): File not found.
        Stack Trace:
              at System.Drawing.SafeNativeMethods.Gdip.CheckStatus(Int32 status)
              at System.Drawing.Text.PrivateFontCollection.AddFontFile(String filename)
              at System.Drawing.Text.Tests.PrivateFontCollectionTests.<>c__DisplayClass5_0.<AddFontFile_LongFilePath_Th
  rowsPathTooLongException>b__0()
     System.Drawing.Text.Tests.PrivateFontCollectionTests.AddFontFile_NullFileName_ThrowsArgumentNullException [FAIL]
        Assert.Throws() Failure
        Expected: typeof(System.ArgumentNullException)
        Actual:   typeof(System.ArgumentException): Parameter is not valid.
        Stack Trace:
              at System.Drawing.SafeNativeMethods.Gdip.CheckStatus(Int32 status)
              at System.Drawing.Text.PrivateFontCollection.AddFontFile(String filename)
              at System.Drawing.Text.Tests.PrivateFontCollectionTests.<>c__DisplayClass2_0.<AddFontFile_NullFileName_Th
  rowsArgumentNullException>b__0()
     System.Drawing.Printing.Tests.PageSettingsTests.Clone_Success [SKIP]
        Condition(s) not met: \"AnyInstalledPrinters\"
  Finished:    System.Drawing.Common.Tests
```

### PR DESCRIPTION
**Pull request by hughbe**
This is a cleaned up copy of the netfx source code.

However, is the whole `IntSecurity.DemandReadFileIO(filename)` stuff necessary

Or maybe I could just replace that with `filename = Path.GetFullPath(filename)` and delete `IntSecurity.cs`

Fixes #21558

### CODE REVIEW

**Comment by stephentoub** [comment]
> is the whole IntSecurity.DemandReadFileIO(filename) stuff necessary

Nope :)

**Comment by danmosemsft** [comment]
@hughbe I believe all use of System.Security.Permissions.* (and using statements) can be removed from Drawing. (Almost) all of our implmentations of those types are stubs.

**Comment by hughbe** [comment]
I asked before but it may have gone unnoticed. Does that apply even for Mono? 

I've updated this PR after Stephen commented to get rid of the security stuff

**Comment by mellinoe** [comment]
> This is a cleaned up copy of the netfx source code.

Maybe I'm misinterpreting this, but I don't think the .NET Framework version does this normalization. Could you clear that up? It looks like an okay change, but TBH I'd rather just keep 100% behavior compat with .NET Framework until we have excellent test coverage.

**Comment by hughbe** [comment]
Before this cleanup, it used IntSecurity.DemandReadFileIO. This was unnecessary in netcoreapp as Stephen mentioned so I could just shorten it to Path.GetFullPath

**Comment by mellinoe** [comment]
I get that it used `IntSecurity.DemandReadFileIO(filename);` before, but that shouldn't affect which value is passed into `GdipPrivateAddFontFile`, right? From my understanding `DemandReadFileIO` will just do a security / permissions check on that full path, and that's the part we no longer care about.

**Comment by hughbe** [comment]
The code in netfx is:

```public void AddFontFile (string filename) {
    IntSecurity.DemandReadFileIO(filename);
    int status = SafeNativeMethods.Gdip.GdipPrivateAddFontFile(new HandleRef(this, nativeFontCollection), filename);

    if (status != SafeNativeMethods.Gdip.Ok)
        throw SafeNativeMethods.Gdip.StatusException(status);
        
    // Register private font with GDI as well so pure GDI-based controls (TextBox, Button for instance) can access it.
    SafeNativeMethods.AddFontFile( filename );
}
```

We got rid of the `IntSecurity.DemandReadFileIO(filename);` part presumably because .NET Core doesn't need the security/permissions bit.

However, this method has side effects that weren't evident at the time of porting due to no tests. 

Namely, that it called `UnsafeGetFullPath` before demanding the permissions

```cs
internal static void DemandReadFileIO(string fileName) {
  string full = fileName;
  
  full = UnsafeGetFullPath(fileName);

  new FileIOPermission(FileIOPermissionAccess.Read, full).Demand();
}

[ResourceExposure(ResourceScope.Machine)]
[ResourceConsumption(ResourceScope.Machine)]
internal static string UnsafeGetFullPath(string fileName) {
    string full = fileName;

    FileIOPermission fiop = new FileIOPermission(PermissionState.None);
    fiop.AllFiles = FileIOPermissionAccess.PathDiscovery;
    fiop.Assert();

    try {
        full = Path.GetFullPath(fileName);
    } finally {
        CodeAccessPermission.RevertAssert();
    }

    return full;
}
```

So we'd get to the call `full = Path.GetFullPath(fileName);`, which can and does throw in the situation this PR fixes.

>  but that shouldn't affect which value is passed into GdipPrivateAddFontFile, right? 
The value passed to `GdipPrivateAddFontFile` is not affected by `DemadReadFileIO`, correct

**Comment by mellinoe** [comment]
> The value passed to GdipPrivateAddFontFile is not affected by DemadReadFileIO, correct

I'm trying to point out that this change does affect the call to `GdipPrivateAddFontFile`:

```C#
filename = Path.GetFullPath(filename);
int status = SafeNativeMethods.Gdip.GdipPrivateAddFontFile(new HandleRef(this, _nativeFontCollection), filename);
```

**Comment by hughbe** [comment]
Ohhhhh dammit! Sorry I wasn't really getting that. It shouldn't actually matter as GdipPrivateAddFontFile handles relative file paths anyways (and we have a test for that already)

But I removed the assignment :)

**Comment by mellinoe** [comment]
LGTM. Thanks, @hughbe

**Pull request merged**
