### PR TITLE
Updating package prerelease to preview1

### PR DESCRIPTION
**Pull request by joperezr**
Updating prerelease label on the release/1.1.0 branch to be preview1.

cc: @weshaggard @danmosemsft @ericstj @Petermarcu

### CODE REVIEW

**Comment by joperezr** [comment]
I just merged PR dotnet/dotnet-ci#446 that enables CI testing on this branch. Once the deployment of the new instance is complete(~20 mins), I'll check if CI is setup correctly in this branch now.

**Comment by joperezr** [comment]
FYI: @markwilkie @Chrisboh @stephentoub

**Comment by weshaggard** [comment]
LGTM - Thanks @joperezr

**Comment by ericstj** [comment]
LGTM

**Pull request merged**
