### PR TITLE
Port the Html Encoder fix from VSO branch

### PR DESCRIPTION
**Pull request by tarekgh**
This is the fix we have done in VSO branch and now we are porting it to corefx after we released the fix in the servicing packages

### CODE REVIEW

**Comment by tarekgh** [comment]
CC @weshaggard @KrzysztofCwalina

**Comment by safern** [comment]
@dotnet-bot test Innerloop netfx Windows_NT Release x64 Build and Test (#19580)

**Comment by stephentoub** [comment]
@dotnet-bot test Innerloop netfx Windows_NT Release x64 Build and Test please

**Comment by tarekgh** [comment]
Thanks @stephentoub and @safern for your follow up here.

**Pull request merged**
