### PR TITLE
ARM-CI: Change Linux ARM Emulator job setup

### PR DESCRIPTION
**Pull request by prajwal-aithal**
Made the Linux ARM Emulator PR job automatic under the name `linuxarmemulator_cross_<configuration>_prtest`

Added a push-based job for non-PR configuration under the name `linuxarmemulator_cross_<configuration>`

Signed-off-by: Prajwal A N <an.prajwal@samsung.com>

### CODE REVIEW

**Comment by prajwal-aithal** [comment]
@dotnet-bot test CI please

**Comment by prajwal-aithal** [comment]
@dotnet-bot test CI please

**Comment by prajwal-aithal** [comment]
@jashook @Priya91 Could you please review this?

**Comment by prajwal-aithal** [comment]
@dotnet-bot test Innerloop Ubuntu14.04 Release Build and Test

**Comment by Priya91** [comment]
LGTM

**Pull request merged**
