### PR TITLE
Add xunit trait to xslt tests depending on xsltc.exe

### PR DESCRIPTION
**Pull request by krwq**
Fixes: https://github.com/dotnet/corefx/issues/25053
Unblocks: https://github.com/dotnet/coreclr/issues/14810

### CODE REVIEW

**Comment by krwq** [comment]
```
14:26:14 /Users/dotnet-bot/j/workspace/dotnet_corefx/master/osx-TGroup_netcoreapp+CGroup_Debug+AGroup_x64+TestOuter_false_prtest/Tools/dotnetcli/sdk/2.0.0/NuGet.targets(102,5): error :   Access to the path '/tmp/NuGet/TempCache/0366a873-7c5b-4924-af56-a5ac111bca98' is denied. [/Users/dotnet-bot/j/workspace/dotnet_corefx/master/osx-TGroup_netcoreapp+CGroup_Debug+AGroup_x64+TestOuter_false_prtest/init-tools.msbuild]
```

this looks like CI/infra problem - let's see if it happens again

**Comment by krwq** [comment]
test OSX x64 Debug Build

**Comment by krwq** [comment]
Failing Windows x64 test is tracked by issue: https://github.com/dotnet/corefx/issues/24874

**Comment by tarekgh** [comment]
Test Windows x64 Debug Build please

**Pull request merged**
