### PR TITLE
Add tests for Configuration SectionGroups

### PR DESCRIPTION
**Pull request by FireAlkazar**
Related to #15554 
Tests for Root, Empty and Simple group sections
cc @karelz @JeremyKuhne

### CODE REVIEW

**Comment by danmosemsft** [comment]
Let's see where we're at!
@dotnet-bot test code coverage please

**Comment by danmosemsft** [comment]
Hmm, CI is down so the incantation might need repeating when it's up

**Comment by FireAlkazar** [comment]
@danmosemsft I can do that, after CI will work

**Comment by JonHanna** [comment]
@dotnet-bot test this please.
@dotnet-bot test code coverage please

**Comment by FireAlkazar** [comment]
@dotnet-bot test code coverage please

**Pull request merged**
