### PR TITLE
Prevent leak through of failed export

### PR DESCRIPTION
**Pull request by ViktorHofer**
Fixes https://github.com/dotnet/corefx/issues/21398

+ minor code cleanup

### CODE REVIEW

**Comment by ViktorHofer** [comment]
The question is, why was the leak through not addressed when the tests which point it out were written...

**Comment by ViktorHofer** [comment]
@dotnet-bot test Windows x64 Debug Build

**Comment by ViktorHofer** [comment]
@dotnet/dnceng Windows x64 Debug Build Job has been running for over 5 hours now: https://ci3.dot.net/job/dotnet_corefx/job/master/job/windows-TGroup_netcoreapp+CGroup_Debug+AGroup_x64+TestOuter_false_prtest/10330/

**Comment by MattGal** [comment]
@ViktorHofer this is a problem with our telemetry system, ironically caused by Pull request telemetry.

This run will never finish, but @alexperovich  is ready to deploy a fix that should prevent this specific issue in the future.

**Comment by alexperovich** [comment]
The fix for this is rolled out. See https://github.com/dotnet/core-eng/issues/2959

**Comment by ViktorHofer** [comment]
@dotnet-bot test Windows x64 Debug Build

**Comment by ViktorHofer** [comment]
@dotnet-bot test Windows x64 Debug Build

**Pull request merged**
