### PR TITLE
dynamic: Make exception message match CS0022 on index-count mismatch

### LINKED ISSUE #18064: Incorrect error message on rank-mismatch via dynamic
Given:
```C#
var array = new int[2,2,2];
array[1,1] = 9;
```
This fails to compile with "CS0022 Wrong number of indices inside []; expected 3"

However:
```C#
dynamic array = new int[2,2,2];
array[1,1] = 9;
```

The error message of the `RuntimeException` is "Cannot apply indexing with [] to an expression of type 'System.Array'" (the same as that for the CS0021 one would get if `array` was typed as `Array`).

Ideally it should match the exception of the most strongly-typed way of resolving the `dynamic` vis that of CS0022.

### PR DESCRIPTION
**Pull request by JonHanna**
Fixes #18064

### CODE REVIEW

**Comment by danmosemsft** [comment]
@dotnet-bot Test Innerloop OSX10.12 Debug x64 Build and Test (network)
@dotnet-bot  Test Innerloop OSX10.12 Release x64 Build and Test (network)

**Comment by danmosemsft** [comment]
real test failures

**Comment by JonHanna** [comment]
@danmosemsft oh dear. An experimental deliberate mistake got into my commit :oo:

**Comment by JonHanna** [comment]
Test Innerloop OSX10.12 Debug x64 Build and Test

**Pull request merged**
