### PR TITLE
Upgrade zlib to 1.2.11

### PR DESCRIPTION
**Pull request by ianhays**
- Upgrades our vanilla zlib code to 1.2.11
- Add PAL layer around zlib on Windows 
    - On Windows we currently directly pinvoke into zlib. This requires defining/declaring the Zstream ourselves, which we currently do in managed code. This is an issue for zlib 1.2.8.1+ where it is required that the ZStream object remain at a fixed location. Our current ZStream is moveable, so we hit issues when it gets moved by the GC. There's also the issue that our ZStream definition can go out of sync with the one in zlib if we update again.
    - This changeset makes the PAL layer around zlib that we have on Unix also wrap the Windows zlib. This results in an unmanaged instantiation of the ZStream while also bringing the Windows and Unix code closer together, allowing us to delete a bunch of platform-specific files.
- Disable zlib-intel (1.2.8) to use zlib-vanilla (1.2.11)
    - Make clrcompression use zlib 1.2.11 until zlib-intel upgrades their version to 1.2.11.

resolves https://github.com/dotnet/corefx/issues/25844

PTAL: @stephentoub @ViktorHofer @jkotas

### CODE REVIEW

**Comment by stephentoub** [comment]
> Make clrcompression use zlib 1.2.11 until zlib-intel upgrades their version to 1.2.11.

Is that in the works?

**Comment by jkotas** [comment]
Agree with Stephen. This change is introducing 30% performance regression - it would be useful to understand the plan to fix this performance regression.

**Comment by ianhays** [comment]
> Is that in the works?

Yes, it is. The intel folks were blocked by the issue that this PR resolves and are planning on continuing their upgrade after this is merged. I can't speak to the timeline on that, however.

**Comment by kasper3** [comment]
Could https://github.com/dotnet/corefx/pull/30229 be merged before this one? Otherwise I will have merge conflicts. Outerloop test failure is related to System.Drawring for which i have opened an issue.

**Comment by stephentoub** [comment]
> I can't speak to the timeline on that, however.

Can we find out?  It'd be good to know that the regression will be addressed in relatively short order.

**Comment by ianhays** [comment]
I last talked to them yesterday and they said they were actively working on it. I can reach out to them again to try to get an ETA.

**Comment by stephentoub** [comment]
Thanks

**Comment by ianhays** [comment]
I did one better and changed our build to use zlib-intel with zlib 1.2.11 components. 

I ran perf tests before/after my change and results are within stdev of each other, so perf impact of upgrading zlib-intel's shared zlib components is negligible.

**Comment by ianhays** [comment]
The intel folks expect to push a PR to CoreFX by the end of next week,

**Comment by stephentoub** [comment]
That sounds good,.  Thanks, @ianhays.

**Comment by ianhays** [comment]
Thanks for reviewing!

**Pull request merged**
