### PR TITLE
Compilation types through attribute: Unary tests

### PR DESCRIPTION
**Pull request by JonHanna**
Also change verification of exceptions to test specific inputs having specific exceptions, rather than try-and-repeat: Less exceptions thrown and caught, better-defined tests

### CODE REVIEW

**Comment by stephentoub** [comment]
@dotnet-bot test this please

**Comment by JonHanna** [comment]
Just realised I missed a few things that should have been included in this batch, so marking WIP until I get those in too.

**Comment by JonHanna** [comment]
There. The further changes were to UnaryArithmeticNegateCheckedTests.cs and UnaryConvertTests.cs only.

**Comment by JonHanna** [comment]
Test this please.

**Comment by JonHanna** [comment]
Test this please.

**Comment by stephentoub** [comment]
LGTM

**Pull request merged**
