### PR TITLE
[TODO] Avoid boxing in IPv4AddressHelper.ParseCanonicalName

### PR DESCRIPTION
**Pull request by jamesqo**
cc: @stephentoub @davidsh

### CODE REVIEW

**Comment by stephentoub** [comment]
LGTM

**Comment by davidsh** [comment]
cc: @CIPop

**Comment by CIPop** [comment]
In my simple experiment I fail to see any improvement. Actually, I see a 5x increase in heap usage. 

Original:
image

After this change:
image

**Comment by jamesqo** [comment]
@CIPop That's strange, the object-based overload of `Concat` calls `ToString` on everything and forwards to the other overload. Maybe your profiler isn't picking up on allocations in mscorlib?

**Comment by CIPop** [comment]
@jamesqo it could be: I've used VS2015 Update 3, removing all filters (which includes "Just my code").

Please add a perf test to prove that the change is not actually making things worse as well as to measure the benefits and pin them to prevent future accidental regressions.

**Comment by jamesqo** [comment]
@CIPop Hmm... AFAICS this method is only ever called [once](https://github.com/dotnet/corefx/blob/ca9e2b068e75898a3b35860632b1fec01cc5af93/src/System.Private.Uri/src/System/Uri.cs#L2327) in Uri, and the only way that method can be called (with `HostTypeMask` set) is [here](https://github.com/dotnet/corefx/blob/ca9e2b068e75898a3b35860632b1fec01cc5af93/src/System.Private.Uri/src/System/Uri.cs#L311) which will only ever be called once (the first time the host string is inited) and then that's it. If it's only possible to call such a method once per Uri, is it possible to write perf tests for it?

**Comment by CIPop** [comment]
@jamesqo Would it be possible to create thousands of `Uri`s with the right type of hostname then measure the allocations?
My testing using only the pattern (not `Uri`), showed that the change is actually worse than the current code...

**Comment by jamesqo** [comment]
@CIPop Thanks for your advice. I've partially written the performance tests, however I've been a bit busy as of late. Closing in accordance with #9864 until I can finish them.

**Comment by CIPop** [comment]
Thanks @jamesqo ! Please let us know if there is anything we can help with by publishing a partial/WIP PR.
This might help: working myself on perf-related investigations, I've found that using [PerfView](https://www.microsoft.com/en-us/download/details.aspx?id=28567) works well with Core (the version of VS I have installed doesn't have the perf tools for Core).

**Pull request closed without merging**
