### PR TITLE
[WIP] Expose string.Join APIs in System.Runtime

### PR DESCRIPTION
**Pull request by jamesqo**
**Description:** This PR exposes and adds tests for `string.Join` overloads accepting a char in System.Runtime.

**Notes:** I'm very hopeful that this will build, but unable to test or even compile this locally because I'm consistently running into an issue: https://github.com/dotnet/corefx/issues/14423. So I will try to inspect any errors raised by CI and hopefully fix them, and then un-WIP this.

**Fixes:** #12655, #5552

### CODE REVIEW

**Comment by hughbe** [comment]
@AlexRadch FYI

**Comment by AlexRadch** [comment]
Ha ha ha https://github.com/dotnet/corefx/pull/14641

**Comment by jamesqo** [comment]
@AlexRadch Shucks, that's unfortunate. Do you want to git cherry-pick the changes from this PR into yours and have me close this?

**Comment by AlexRadch** [comment]
@jamesqo we tests the same thing by different way.

**Comment by karelz** [comment]
@jamesqo just curious if you think we could have done something better on our side (labels, assignees, etc.) to avoid duplicated work ...

**Comment by jamesqo** [comment]
@karelz No, I think it was my fault. It had been 28 days since the last comment on that issue, and I didn't think someone else would grab it within hours of me.

**Comment by karelz** [comment]
Got it. Maybe following the flow of saying on the issue "I am working on it" would help in future. This is the first time it happened, so I assume not a big deal.

**Comment by karelz** [comment]
@jamesqo the dupe PR #14641 was abandoned. Do you want to ressurrect yours or #14641 to finish it off?

**Comment by jamesqo** [comment]
@karelz I am planning to come back to this PR sometime,  I already have it on my ZenHub todo list. You can reopen this issue in the meantime.

**Comment by karelz** [comment]
@jamesqo very cool! No pressure. When you're ready, just ping the issue #5552 - you can then decide if you want to reopen this PR or create a new one.

**Pull request closed without merging**
