### PR TITLE
Update CoreClr, ProjectNTfs, Standard to beta-25010-03, beta-25010-00, beta-25010-01, respectively

### PR DESCRIPTION
**Pull request by jkotas**

### CODE REVIEW

**Comment by jkotas** [comment]
Failing on https://github.com/dotnet/corefx/pull/16052

**Comment by stephentoub** [comment]
@dotnet-bot test this please

**Comment by jkotas** [comment]
Serial port tests failing with `System.UnauthorizedAccessException : Access to the port 'COM1' is denied."`

**Comment by jkotas** [comment]
@dotnet-bot test Innerloop Windows_NT Release Build and Test please

**Comment by jkotas** [comment]
@willdean Should the serial port tests be running in the CI? Number of them just failed in the Windows_NT Release Build with System.UnauthorizedAccessException

**Comment by willdean** [comment]
@jkotas There is a feeling that they should be running in the CI, yes, though if they're too much trouble.

The ones which are causing trouble right now are new but have already passed CI before the merge - they've just decided to act-up now - I'm looking into it right away. 

@JeremyKuhne fyi

**Comment by JeremyKuhne** [comment]
@jkotas we're (@willdean mostly) actively working through porting the tests right now, fixing issues (reliability notably), and refining the set we run in CI. We won't leave any flaky ones active when we find them.

We want as much coverage as possible without negatively impacting the CI. There will be a few hiccups as the CI environment is different both from the environment in which the tests were originally written and our local setups.

**Comment by willdean** [comment]
I've just pushed a suppression PR which I hope might squash the ones which are causing trouble (the list of specific failures is not directly representative of the cause of the problem)

**Comment by karelz** [comment]
@JeremyKuhne I expected that we won't enable the tests in CI until we are done ... to reduce the noise for others ...

**Comment by willdean** [comment]
@karelz The challenge is that the tests failures are intermittent and their behaviour depends on specific hardware performance, so it's impossible to know how they'll run on the CI without actually running them on the CI.   Clearly they do pass on the CI on a PR branch before they get merged, so it's not like they're completely untested before we inflict them on anyone else.

Is there any way to get the CI to run tests on a branch/PR (perhaps some manual dotnet-bot stuff?) without them running automatically on everyone else's build?

**Comment by karelz** [comment]
We should IMO stabilize the tests first locally (let's say 100-1000 runs in a loop without failure).
Then we can stabilize the per-PR CI, by asking @dotnet-bot to run it over and over again (probably ~10-times as it is manual and takes time). That should be IMO sufficient - the post-checkin CI uses the same infra and Helix (our internal infra) will have to adjust - @JeremyKuhne can help with that.

**Comment by willdean** [comment]
@karelz Thanks for this - then I think the best thing would be to go back to building one mega-PR and working on that until it's all stable.   At the moment I am trying to put in small, focused PRs to keep it clear what's being changed within each PR, but that's causing me more and more difficulty here as I have to maintain multiple branches while their PRs remain open, and another private branch with everything merged in to keep making progress.   Because there's so much clean-up going on, a PR might be focused on one topic, but it still touches a lot of files, which means there are repeated merge problems.

Not merging would probably suit me better, but it runs counter to the dev docs which ask one not to maintain WIP PRs - perhaps everyone can agree this is a special case?

(The mega-WIP-PR does rather hinder other community involvement, but there doesn't seem to be too much clamour for that anyway.)

**Comment by willdean** [comment]
@karelz Would it be an enormous admin burden for the SerialPort work to have a separate branch rather than merging to master?  That would let us have smaller PRs, more chance for cooperation, no chance of breaking the master build, but still get the use of the CI?

**Comment by JeremyKuhne** [comment]
> We should IMO stabilize the tests first locally (let's say 100-1000 runs in a loop without failure).
Then we can stabilize the per-PR CI, by asking @dotnet-bot to run it over and over again (probably ~10-times as it is manual and takes time).

@karelz That is a rational request. Keep in mind, as @willdean points out, we didn't know the CI setup would struggle until after our tests had passed their initial CI without incident. I have not merged in anything that showed an error. I think 10 iterations is a bit much to ask- 3 times seems like a better place to start and we can adjust if that doesn't seem to be enough.

@willdean, you can put up PRs with multiple commits for clarity (commit 1, formatting, 2, compiling, 3, functional change 1, ...) I think that is the simplest way to go.

**Comment by karelz** [comment]
My original overall expectation was that neither product, nor tests will be part of full build / test pass, until we are done.
Even in that setup you can imagine multiple PRs. To run the tests in CI, one can temporarily make the build & tests part of full build.
Maybe my expectations were naive ...

Either way, what is the best next step to make sure we do not affect neither local nor CI test runs with SerialPort effort?

**Comment by willdean** [comment]
@karelz  #16102 will stop the current problems - it's failing at the moment, but not because of SerialPort stuff.

**Comment by karelz** [comment]
@willdean perfect, thank you!

**Pull request merged**
