### PR TITLE
Fix mutating static issue

### LINKED ISSUE #38092: Test failure: System.Text.Json.Serialization.Tests.ObjectTests/Write(testObj: JsonElementClass { Array = , False = , Number = , Object = , String = , ... })
Test `System.Text.Json.Serialization.Tests.ObjectTests/Write(testObj: JsonElementClass { Array = , False = , Number = , Object = , String = , ... }) `has fail.
Message :
```
System.Text.Json.JsonException : The provided data of length 100 has remaining bytes 97.
```
Stack Trace :
```
   at System.Text.Json.ThrowHelper.ThrowJsonException_DeserializeDataRemaining(Int64 length, Int64 bytesRemaining) in /_/src/System.Text.Json/src/System/Text/Json/ThrowHelper.Serialization.cs:line 70
   at System.Text.Json.Serialization.JsonSerializer.ParseCore(String json, Type returnType, JsonSerializerOptions options) in /_/src/System.Text.Json/src/System/Text/Json/Serialization/JsonSerializer.Read.String.cs:line 79
   at System.Text.Json.Serialization.JsonSerializer.Parse(String json, Type returnType, JsonSerializerOptions options) in /_/src/System.Text.Json/src/System/Text/Json/Serialization/JsonSerializer.Read.String.cs:line 60
   at System.Text.Json.Serialization.Tests.ObjectTests.Write(ITestClass testObj) in /_/src/System.Text.Json/tests/Serialization/Object.WriteTests.cs:line 31
```

Build: Master - [20190530.71](https://mc.dot.net/#/user/dotnet-bot/pr~2Fdotnet~2Fcorefx~2Frefs~2Fheads~2Fmaster/test~2Ffunctional~2Fcli~2Finnerloop~2F/20190530.71)

Failing configurations:

- Alpine.38.Arm64.Open-arm64-Release

Details:
https://mc.dot.net/#/user/dotnet-bot/pr~2Fdotnet~2Fcorefx~2Frefs~2Fheads~2Fmaster/test~2Ffunctional~2Fcli~2Finnerloop~2F/20190530.71/workItem/System.Text.Json.Tests/analysis/xunit/System.Text.Json.Serialization.Tests.ObjectTests~2FWrite(testObj:%20JsonElementClass%20%7B%20Array%20=%20,%20False%20=%20,%20Number%20=%20,%20Object%20=%20,%20String%20=%20,%20...%20%7D)

### PR DESCRIPTION
**Pull request by JeremyKuhne**
The default options static was getting mutated. Moving to ReadStack which doesn't have this issue.

Fixes #38092

### CODE REVIEW

**Comment by wtgodbe** [comment]
One of these days this is going to work 😆

**Comment by JeremyKuhne** [comment]
The mutated state would typically fix itself as any successful test would unset the flag. Need to be unlucky when running the tests multithreaded, which doesn't happen when running in VS. ;P

**Comment by wtgodbe** [comment]
@JeremyKuhne how critical is this for preview6?

**Comment by JeremyKuhne** [comment]
@wtgodbe, this one will need ported to preview 6. :)

**Comment by wtgodbe** [comment]
@JeremyKuhne gotcha. How confident are you it will pass CI? If you are very confident, I can cherry-pick it to the code merge PR now to jump-start the CI there. Otherwise I'll wait until you merge this to cherry-pick it.

**Comment by JeremyKuhne** [comment]
> How confident are you it will pass CI? 

Very confident.

**Comment by JeremyKuhne** [comment]
Windows failed with #29377.

RedHat6 failed in libgdiplus, don't see enough data to follow up:

```
*** glibc detected *** /home/helixbot/work/78e9f3fd-76af-4045-ba6f-3b8d879c73c8/Payload/dotnet: double free or corruption (fasttop): 0x00007ff36c0b5f70 ***
======= Backtrace: =========
/lib64/libc.so.6(+0x75dee)[0x7ff4423b7dee]
/lib64/libc.so.6(+0x78c3d)[0x7ff4423bac3d]
/usr/lib64/libcairo.so.2(cairo_font_face_destroy+0x3f)[0x7ff3c49a7c0f]
/usr/lib64/libcairo.so.2(+0x157e6)[0x7ff3c49ab7e6]
/usr/lib64/libcairo.so.2(cairo_destroy+0x91)[0x7ff3c49a5f71]
/usr/lib64/libgdiplus.so.0(GdipDeleteGraphics+0x85)[0x7ff3c4f3f965]
[0x7ff3ca0c1143]
```

**Pull request merged**
