### PR TITLE
Fix ServiceProcess Tests to have a P2P reference

### PR DESCRIPTION
**Pull request by weshaggard**
This adds a P2P reference to the NativeTestService project and copies
it to locally so it can be consumed in the project. Also adds dir.props
import into the NativeTestSerivce.vcxproj file.

### CODE REVIEW

**Comment by Priya91** [comment]
:+1: LGTM

**Comment by nslottow** [comment]
LGTM until we have a better solution for native binaries.

**Comment by nslottow** [comment]
@dotnet-bot test this please

**Comment by nslottow** [comment]
I didn't see any test failures in the last CI build, but it failed anyway. @mmitche have you seen this happen before?

**Comment by akoeplinger** [comment]
@nslottow there are errors in the log, e.g.:

```
NativeTestService.cpp(678): fatal error C1010: unexpected end of file while looking for precompiled header. Did you forget to add '#include "stdafx.h"' to your source? 
```

and

```
C:\Program Files (x86)\MSBuild\12.0\bin\Microsoft.Common.CurrentVersion.targets(3940,5): error MSB3030: Could not copy the file "d:\j\workspace\dotnet_corefx_prtest\Config\Debug\OS\Windows_NT\Tests\false\label\windows\bin\Win32\Debug\NativeTestService\NativeTestService.exe" because it was not found. [d:\j\workspace\dotnet_corefx_prtest\Config\Debug\OS\Windows_NT\Tests\false\label\windows\src\System.ServiceProcess.ServiceController\tests\System.ServiceProcess.ServiceController.Tests\System.ServiceProcess.ServiceController.Tests.csproj]
```

**Comment by weshaggard** [comment]
I'm looking into this I suspect I may need to make some tweaks to how I get the NativeTestService.exe.

**Pull request merged**
