### PR TITLE
Add `--sequential` option to `run-test.sh`

### PR DESCRIPTION
**Pull request by lemmaa**
for running unit-tests one by one.

### CODE REVIEW

**Comment by ellismg** [comment]
LGTM.

**Comment by prajwal-aithal** [comment]
@dotnet-bot test Innerloop Linux ARM Emulator Debug Cross Build

**Comment by prajwal-aithal** [comment]
@dotnet-bot test Innerloop Linux ARM Emulator Release Cross Build

**Comment by lemmaa** [comment]
@dotnet-bot test Innerloop Linux ARM Emulator Debug Cross Build

**Comment by lemmaa** [comment]
@dotnet-bot test Innerloop Linux ARM Emulator Debug Cross Build

**Comment by lemmaa** [comment]
@dotnet-bot test Innerloop Linux ARM Emulator Debug Cross Build

**Comment by lemmaa** [comment]
@dotnet-bot test Innerloop Linux ARM Emulator Release Cross Build

**Comment by lemmaa** [comment]
@jkotas Please take a look this one.

**Comment by jkotas** [comment]
LGTM

**Pull request merged**
