### PR TITLE
Update project ToolsVersions to 14.0

### PR DESCRIPTION
**Pull request by alexperovich**
This change updates the ToolsVersion in all projects to 14.0.
This fixes an error emitted by OmniSharp caused by an unknown ToolsVersion that prevents projects from being loaded.

This change was made by running
```bash
sed -i 's/ToolsVersion="[0-9.]\+"/ToolsVersion="14.0"/'
```
on all project files in the repository.

/cc @weshaggard

### CODE REVIEW

**Comment by alexperovich** [comment]
@dotnet-bot test this please

**Comment by alexperovich** [comment]
@dotnet-bot test Innerloop Ubuntu14.04 Release Build and Test please (Build Timeout)

**Comment by ericstj** [comment]
LGTM /cc @weshaggard

**Comment by weshaggard** [comment]
LGTM

**Pull request merged**
