### PR TITLE
Fix for issue https://github.com/dotnet/wcf/issues/1340 (DataContract…

### PR DESCRIPTION
**Pull request by mlacouture**
Fix for issue 1340.

cc: @shmao @mconnew for code review

### CODE REVIEW

**Comment by shmao** [comment]
LGTM.

**Comment by mlacouture** [comment]
@roncain for code review - thanks,

**Comment by mlacouture** [comment]
hey, @shmao @roncain, any update on this pull request?

**Comment by roncain** [comment]
LGTM.
Can we add a test to verify this works for the scenario originally reported?  That could be a different PR to we don't block this one.

**Comment by mlacouture** [comment]
Yes, that's in the backlog - thanks

**Pull request merged**
