### PR TITLE
Fix UseShellExec tests for Nano

### PR DESCRIPTION
**Pull request by danmosemsft**
Fixes https://github.com/dotnet/corefx/issues/20288

I need nano support on CI to test this. @mmitche ...

### CODE REVIEW

**Comment by tarekgh** [comment]
@danmosemsft does this change need to ported to 2.0 with other @JeremyKuhne changes?

**Comment by danmosemsft** [comment]
@tarekgh yes, on top of https://github.com/dotnet/corefx/pull/20289

Although, I haven't seen a run yet that proves that it fixed Nano. So you could just port Jeremy's + 20289 and then we can follow up with this one once we see it in a run. Maybe that will be later today .

**Comment by danmosemsft** [comment]
@tarekgh I just realized that CI now runs Nano legs too - and they were green! So at least inner loop is fixed. So yes, please include this on top of #20289 on top of Jeremy's change. All are ready to go into 2.0 now.

**Comment by tarekgh** [comment]
@danmosemsft I have picked up all needed change in the PR https://github.com/dotnet/corefx/pull/20273 and I am going to send the request to the shiproom. could you please have a quick look at the PR to double check if there is anything  wrong there?

**Pull request merged**
