### PR TITLE
Add Debian8.4 CI runs

### LINKED ISSUE #8228: Update CI to Debian 8.4
1. We should update CI infra to Debian 8.4 (https://www.debian.org/News/2016/20160402)
2. Also please review the RID graph entries for Debian 8.2+ (8.3, 8.4) so there are no issues for users on newer Debian 8 patch levels

### PR DESCRIPTION
**Pull request by Priya91**
fixes #8228 

cc @mmitche @joshfree @ellismg

### CODE REVIEW

**Comment by Priya91** [comment]
@dotnet-bot test ci please

**Comment by ellismg** [comment]
LGTM.

**Comment by Priya91** [comment]
@dotnet-bot test ci please

**Comment by Priya91** [comment]
@dotnet-bot test ci please

**Pull request merged**
