### PR TITLE
Kill notepad in finally {}

### PR DESCRIPTION
**Pull request by danmosemsft**
This may be the cause of a hang we saw in Helix.
Also remove path from file in notepad title. This may not be robust enough, we'll see.

### CODE REVIEW

**Comment by karelz** [comment]
@danmosemsft do we have a bug tracking the failure?

**Comment by danmosemsft** [comment]
Primary job failed due to CI bug. NetFX failures are all due to tracing issue tracked separately.

**Comment by danmosemsft** [comment]
@karelz no. If it turns up needed in 2.0 I'll port it.

**Comment by MattGal** [comment]
I'd be surprised if this didn't have the same effect anywhere else this code is, since runs use the same VMs which will be configured to not show file extensions (it's the Windows default).    It may not be worth porting the fix around though.

**Pull request merged**
