### PR TITLE
RID for Exherbo linux

### PR DESCRIPTION
**Pull request by s0dyy**
Hello ;)

I'm the maintainer of dotnet/source-build for the Exherbo linux distribution. I would like to have the RID in Corefx if possible.

### CODE REVIEW

**Comment by aik-jahoda** [comment]
@wtgodbe, @wfurt, can you please review or suggest reviewer?

**Comment by wfurt** [comment]
We should get https://github.com/dotnet/runtime/pull/47232 in first IMHO.

**Comment by aik-jahoda** [comment]
Please remove * NO MERGE * once this PR is ready

**Comment by s0dyy** [comment]
It has been merged on Runtime ;)

**Review by Anipik — APPROVED** [review]

**Comment by Anipik** [comment]
@wfurt  can we merge this one ?

**Review by wfurt — APPROVED** [review]
LGTM

**Pull request merged**
