### PR TITLE
Removing an unused contract method and adding documentation

### PR DESCRIPTION
**Pull request by bartdesmet**
Noticed an unused `ContractUtils` method, thus removing it. While at it, also adding and improving documentation on the remaining methods.

### CODE REVIEW

**Comment by JonHanna** [comment]
On a related note, should `Common\System\Dynamic` be moved into Expressions now? It doesn't seem to be shared with anything else, any more. Is it going to be?

**Comment by bartdesmet** [comment]
Yup, I think we can start moving these.

**Comment by JonHanna** [comment]
Okay. I'm going to stomp all over this PR with my next one then ;)

**Comment by bartdesmet** [comment]
@dotnet-bot test Innerloop CentOS7.1 Debug Build and Test please (https://github.com/dotnet/corefx/issues/13967)

**Comment by JonHanna** [comment]
Oh. Doing that now would stomp on a lot of the open PRs. I won't to it tonight, so.

**Comment by JonHanna** [comment]
Test Innerloop OSX Debug Build and Test
(Failure in System.Diagnostics.Tests.ProcessTests.TestMinWorkingSet)

**Comment by bartdesmet** [comment]
Going offline for today here; @JonHanna, can you open an issue for the CI failure in `System.Diagnostics.Tests.ProcessTests.TestMinWorkingSet`? Thanks!

**Pull request merged**
